### ISSUE TITLE
Distribute Windows Package via Chocolatey

### ISSUE THREAD

**Issue by reicheltp** [zeit/hyper#1002]
As choco is the apt-get/brew for windows it would be awesome to have the windows package on http://chocolatey.org

This would allow users to simply install it with:
`choco install hyper`

**Comment by brase** [comment]
Now it is already there but with an old Version. It would be nice getting the latest version from there, too.

**Comment by timothyis** [comment]
Seems to be resolved! https://chocolatey.org/packages/hyper
