### ISSUE TITLE
Problem with US Extended keyboard under OS X

### ISSUE THREAD

**Issue by christopherastone** [zeit/hyper#1010]
- **OS version and name**: OS X 10.11.6 
- **Hyper.app version**: 0.8.3.873
- **Relevant information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 

```
Uncaught dead key on international keyboard
KeyboardEvent {isTrusted: true, key: "Dead", code: "KeyV", location: 0, ctrlKey: false…}
altKey: true
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "KeyV"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
isTrusted: true
key: "Dead"
keyCode: 86
keyIdentifier: "U+0056"
location: 0
metaKey: false
path: Array[5]
repeat: false
returnValue: true
shiftKey: false
sourceCapabilities: InputDeviceCapabilities
srcElement: x-screen
target: x-screen
timeStamp: 19296757.820000004
type: "keydown"
view: Window
which: 86
__proto__: KeyboardEvent
```

- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

On OS X, I use the "US Extended" keyboard so that I can type foreign names properly, with appropriate accents. This works in just about every program except Hyper. 

The above error is the result of hitting Option-V, which would normally wait and add a v-shaped accent to the next character typed (e.g., `Option-V C` produces `Č`)

**Comment by matheuss** [comment]
@christopherastone thanks for reporting! This was fixed yesterday on #1006 😄 Will be released *very soon* 👌
