### ISSUE TITLE
Starting CWD on Windows is Always Hyper.exe's Folder

### ISSUE THREAD

**Issue by zbuttram** [zeit/hyper#1011]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 build 14393
- **Hyper.app version**: 0.8.3 (installer from AppVeyor artifacts)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/zbuttram/76b649fc07aaba5602dc8f3186b041b2
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Installed from AppVeyor artifacts https://ci.appveyor.com/project/appveyor-zeit/hyper/build/1.0.121/artifacts

## Issue
Seems like whenever Hyper is started on Windows, the starting CWD is wherever Hyper.exe is run from (as opposed to the user's home or the system root):

![image](https://cloud.githubusercontent.com/assets/396699/20403013/f27cb880-acb3-11e6-8f98-73074c876042.png)

**Comment by c0b41** [comment]
relevant comment https://github.com/zeit/hyper/issues/988#issuecomment-260334979 also i think not hyper app problem..

**Comment by Specro** [comment]
My guess is HOME env variable doesn't exist. Should use HOMEPATH for Windows instead.

**Comment by zbuttram** [comment]
I think @Specro nailed it:

![image](https://cloud.githubusercontent.com/assets/396699/20441833/f8030986-ad7a-11e6-96c3-9dbc2233abe7.png)

Looks like we could fix it [here](https://github.com/zeit/hyper/blob/27a20e0cfc7cb5dbafbad1b7a0600393f5d7553d/app/index.js#L183) maybe?

I'll test it out when I get a chance and see if I can put a PR together.
