### ISSUE TITLE
macOS app signing fails on prepush hook and "npm run pack"

### ISSUE THREAD

**Issue by khovansky-al** [zeit/hyper#1012]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12
- **Hyper.app version**: git master version (Latest commit 27a20e0)

## Issue
Packing the app fails on signing stage with `Error: No identity found for signing`. README encourages you to try packing it as a way of testing that things work as a whole. 
According to electron docs though (https://github.com/electron-userland/electron-osx-sign/wiki/1.-Getting-Started) you have to setup a Mac Developer Profile to get it working (which is kind of expected, although I thought nowadays you don't have to pay for enrollment to codesign dev versions. Maybe that only applies to iOS apps).
Also prepush hook has packing stage so this interferes with pushing to a forked repo.
I've got a feeling that I might be missing something though. If I'm not, maybe we should at least mention this in README.

**Comment by ppot** [comment]
I can relate:

```
> @ build /Users/ppot/DEV/Contrib/hyper
> cross-env NODE_ENV=production webpack

Hash: 323238cb2b5e4e916f5a
Version: webpack 2.1.0-beta.25
Time: 4943ms
           Asset     Size  Chunks             Chunk Names
       bundle.js  1.64 MB       0  [emitted]  main
   bundle.js.map  2.04 MB       0  [emitted]  main
assets/icons.svg  2.81 kB          [emitted]
    + 296 hidden modules
Rebuilding native production dependencies for arch x64
Packaging for darwin x64 using electron 1.4.5 to dist/mac
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
```

**Comment by jdsimcoe** [comment]
I'm getting the same thing.

**Comment by Matt-Owens** [comment]
Same here :\
