### ISSUE TITLE
Graphic accentuation

### ISSUE THREAD

**Issue by kamihouse** [zeit/hyper#1013]
By accenting sentences on Hyper.app, it is not possible to accent words.

For example: `Ao acentuar frases, não é possível acentuar palavras.`

- **OS**: macOS Sierra (10.12.1) 
- **Hyper.app**:  0.8.3 (0.8.3.873)
- **Link of a [Gist](https://gist.github.com/kamihouse/3075e66bbea7ca60e23cdef788724276) with the contents of your .hyper.js**: 

## Issue
You can not accent words in the Hyper terminal using the MacOS operating system.  
When using an accent, it comes before the letter.

**Comment by ppot** [comment]
@matheuss  you're to test

**Comment by matheuss** [comment]
@kamihouse it was fixed via #1006 – it'll be shipped in a new release *very soon* 😄

**Comment by kamihouse** [comment]
Great @matheuss !
