### ISSUE TITLE
Preferences spawns a new Hyper Window

### ISSUE THREAD

**Issue by jimmck** [zeit/hyper#1015]
MacOS Sierra -  When I select Preferences menu option of do CMD + , I do not get preferences I get another Hyper window.
-

Hyper 0.8.3
Electron 1.4.0
darwin x64 16.1.0

**Comment by khovansky-al** [comment]
If you wait a little it's going to open text editor with ~/.hyper.js in it. As far as I'm concerned there is no settings GUI at the moment.

**Comment by CodeTheory** [comment]
@jimmck Is the issue that you get a new, empty, Hyper.app window?

**Comment by jimmck** [comment]
Hi,

Well. I am using Zsh and because of my startup I have to enter admin
password. I have to do this for iTerm2 as well. But yes the new windows
opens: sequence of events is.

In an Opened Hyper term window, I press CMD+,  and a new window is opened.

I am prompted for a password which I enter.

A new window is opened no settings file appears no GUI either which is what
I expected as that is what usually happens.

I assume I can edit the file manually.

MAC Sierra 10.12.1

**Comment by ppot** [comment]
CLOSED in #1918
