### ISSUE TITLE
Right click to copy and paste

### ISSUE THREAD

**Issue by lednhatkhanh** [zeit/hyper#1019]
Hi, that's what we can do on powershell, it's be nice if we can do that too on hyper, and another one, can you please add a shortcut for copy and paste: like Ctrl+Shift+C/V. 

Thank you

**Comment by luisrudge** [comment]
Selecting a text is not copying to clipboard.
Paste is not working when clicking with the right button.

**Comment by matheuss** [comment]
> can you please add a shortcut for copy and paste
@lednhatkhanh we already have such shortcuts, but there's a bug with them on Windows and Linux: #1025 – I'll fix it tomorrow 🙌 

> Selecting a text is not copying to clipboard.
@luisrudge that's an [option](https://github.com/zeit/hyper/blob/master/app/config-default.js#L80) in `.hyper.js` 😄

**Comment by luisrudge** [comment]
maybe that option should be on by default? at least on windows.. this is the default cmd behavior

**Comment by Specro** [comment]
Implemented in #1247 😄

**Comment by mlosh** [comment]
Still having a problem in Ubuntu 17.04

**Comment by iskilled** [comment]
@mlosh have you tried changing the 'copyOnSelect:' option from false to true on Hyper's preferences?

**Comment by albinekb** [comment]
@b3l0v please open a new issue and fill out the issue template if you're still experiencing problems 👍
