### ISSUE TITLE
Windows: Can't set powershell as default

### ISSUE THREAD

**Issue by lednhatkhanh** [zeit/hyper#1020]
I've just noticed another problem on windows, after I set powershell as my default shell, everytime I open hyper, it will be closed immediately.

**Comment by stefanivic** [comment]
You need to put full path to the shell : C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe and also remove the -login from shellArgs.

**Comment by twisty** [comment]
Also, you'll need to escape the backslashes in <code>.hyper.js</code>.

For example, this worked for me (to use Bash on Ubuntu on Windows):

```javascript
shell: 'C:\\Windows\\System32\\bash.exe'
```

**Comment by DanielPintilei** [comment]
BTW `-NoLogo` comes handy in shellArgs for powershell

**Comment by lednhatkhanh** [comment]
Nice! Thank you!

**Comment by reicheltp** [comment]
Maybe it would be nice to have some default aliases for easier usage like:
- `bash` for `C:\\Windows\\System32\\bash.exe`
- `powershell` for `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`

**Comment by mineiro** [comment]
Hey guys!

Using `C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe` (with double `\`) worked for me.

Remember what @stefanivic said and remove `--login` from `shellArguments`.

From:

```
// for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
// by default ['--login'] will be used
shellArgs: ['--login'],
```

To:

```
// for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
// by default ['--login'] will be used
shellArgs: [],
```

**Comment by wmeints** [comment]
Also, if you use Powershell and try to edit the preferences it will attempt to open `%userprofile%\.hyper.js` which doesn't work. In powershell you need to use $env:userprofile instead. 

Other than that, an awesome terminal!

**Comment by lednhatkhanh** [comment]
@wmeints Hi, can you help me with it please, I don't know where to change the path.

**Comment by tmr232** [comment]
Yeah, properly support Powershell we need the env variables resolved before the `start` command.

**Comment by patriciomartinns** [comment]
To use git-bash as a standard terminal replacing cmd?

**Comment by tmr232** [comment]
I assume git-bash will have the same issues, as env-var expansion is different as well.

**Comment by ekinnee** [comment]
Current build I was able to specify powershell.exe alone and remove the --login option and it works.

**Comment by gluons** [comment]
Oh! This issue must be explained in the documentation in next release. It's really useful for Powershell user.

**Comment by Snazzyham** [comment]
I tried putting this in my `.hyper.js` file, both just as `powershell.exe` and as `C:\\Windows\\System32\\bash.exe` but neither seem to be working. I get the notification that I need to open a new tab to use the new shell but even when I quit hyper and re-open it I'm still on cmd. Has this happened to anyone else?

**Comment by jkymarsh** [comment]
Can confirm that the following settings properly open a PowerShell session on Windows 10:

```
shell: 'powershell.exe',
shellArgs: [''],
```

on Hyper 1.1.0

**Comment by matheuss** [comment]
Thanks everyone for the insights and investigation 🕵️ [I added some notes](https://github.com/zeit/hyper/commit/d54fa3889b4b9d7e48334e9fdd71b13889653187) to the default `~/.hyper.js` 😄

**Comment by reeddunkle** [comment]
@DanielPintilei What does the `-NoLogo` flag do? Why does it come in handy?

**Comment by DanielPintilei** [comment]
Disables the copyright text you see every time you open a terminal.

**Comment by kireerik** [comment]
Hi all, is it possible to remove the `PS ` prefix?

**Comment by slamoureux** [comment]
how do you open powershell as admin in hyper?

**Comment by slamoureux** [comment]
it's embarrassing how much I overthought this, thanks!
