### ISSUE TITLE
[Ubuntu] Black bar at top when no tabs

### ISSUE THREAD

**Issue by perry-mitchell** [zeit/hyper#1021]
- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: 0.8.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/perry-mitchell/e524335b722839b55ea6d09140648bc3
- **Relevent information from devtools**: _NA_
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue

There is a black bar at the top of the app where tabs would normally be. Panes or not, the bar doesn't disappear:

![image](https://cloud.githubusercontent.com/assets/3869469/20474912/95fad5ee-afd1-11e6-973c-816c6949973c.png)

When using tabs, the bar is occupied:

![image](https://cloud.githubusercontent.com/assets/3869469/20474895/80d78f7c-afd1-11e6-94cd-54692d687907.png)

Seems to be a purely aesthetic issue.

**Comment by matheuss** [comment]
Thanks for the report, @perry-mitchell 😄 This was fixed via #946 🙌

**Comment by perry-mitchell** [comment]
Thanks @matheuss - Will this also address the black border around the edge?

![image](https://cloud.githubusercontent.com/assets/3869469/20514125/eed88078-b092-11e6-8fe3-e5923b926f0e.png)

**Comment by pbentkowski** [comment]
I'm on KDE 4 running on Ubuntu 14.04 LTS 64-bit using Hyper 0.8.3 installed via your .deb package 

 **Ctrl+T / Ctrl+N don't work.**
