### ISSUE TITLE
What is the action triggered in redux when windows focus?

### ISSUE THREAD

**Issue by alexandref93** [zeit/hyper#1022]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.11.5 OS X El Captain 
- **Hyper.app version**: 0.8.3.873
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Link](https://gist.github.com/alexandref93/bf8dc6284f00bd14fac103e9a13d5193)

## Issue

What is the action triggered in redux when windows focus? Or is there no action for this?

**Comment by ppot** [comment]
it's the `SESSION_SET_ACTIVE`

**Comment by alexandref93** [comment]
:(

**Comment by ppot** [comment]
@alexandref93 Friendly ping. Still need? Or close?
