### ISSUE TITLE
[Windows] double clicking the title bar doesn't maximize the app

### ISSUE THREAD

**Issue by luisrudge** [zeit/hyper#1024]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Hyper.app version**: 1.0.0 from appveyor

## Issue
double clicking the title bar doesn't maximize the app

**Comment by luisrudge** [comment]
I just noticed that if you double click a tab, it works as expected. It just doesn't work with the main title bar

**Comment by zbuttram** [comment]
It also seems to work if you double-click the hamburger menu. I can't seem to get it to register clicks for the middle of the title bar for some reason, even after moving the event handler directly onto it.

**Comment by matheuss** [comment]
Can reproduce 🙇 Thanks for reporting 🙌

**Comment by Specro** [comment]
Windows eats up all the events on `-webkit-app-region: drag` elements https://github.com/electron/electron/issues/7107. This means we need custom dragging here 😢
