### ISSUE TITLE
[Windows] ctrl+T / ctrl+n / ctrl+w not working

### ISSUE THREAD

**Issue by luisrudge** [zeit/hyper#1025]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Hyper.app version**: 1.0.0 from appveyor

## Issue
ctrl+T / ctrl+n / ctrl+w shorcuts are not working. Instead, it's adding `^T`, `^N` and `^W` to my command input

**Comment by TheSandman86** [comment]
I have the same problem on Linux with i3wm:
Hyper Version: latest
OS: Ubuntu 16.04
Keyboard shortcuts does not work.

**Comment by luisrudge** [comment]
ctrl+t doesn't work as well

**Comment by parro-it** [comment]
Probably related to #274

**Comment by zbuttram** [comment]
As mentioned in #274, pressing the <kbd>super</kbd> (or in this case the <kbd>Win</kbd> or Windows) key as part of the key combo makes it work for some reason, so there is a workaround for now until whatever is causing #274 is fixed.

**Comment by luisrudge** [comment]
Thanks for the workaround. It's so hard to change muscle memory though 😝

**Comment by matheuss** [comment]
I'm fixing this tomorrow 🙌

**Comment by matheuss** [comment]
Yo everyone please test #1058! 🙌
