### ISSUE TITLE
OSX Accented letters with deadkeys

### ISSUE THREAD

**Issue by noamcore** [zeit/hyper#1028]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX El Capitan 10.11.6
- **Hyper.app version**: 0.8.3.873
- **Link of a Gist with the contents of your .hyper.js**: https://gist.github.com/noamcore/e98b5a3340332740ec19b909f92ce016
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: is Vanilla

## Issue

If I try to write some accented letter – like á (`´`+`a`), ã (`~`+`a`), ó (`´`+`o`) – I get something like – ^a, 'a, ^o –.

I'm Brazilian and I'm using a ABNT2 keyword.

**Comment by matheuss** [comment]
@noamcore this was fixed by #1006 – it'll be released very soon 😄
