### ISSUE TITLE
Can't type ~ with Spanish Keyboard

### ISSUE THREAD

**Issue by osrecio** [zeit/hyper#1034]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 0.83 (0.8.3.873)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
```
Uncaught dead key on international keyboard KeyboardEvent {isTrusted: true, key: "Dead", code: "Semicolon", location: 0, ctrlKey: false…}
```
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

When you try to type `alt + Ñ` = `~` You have this warning and `~` not typed.

GIF:
![alt text](http://www.osrecio.com/hyper_error.gif "Hyper Error")

**Comment by CodeTheory** [comment]
Will be fixed with the next release. 😄 #26

**Comment by iovis9** [comment]
And when is it expected to be released? Can't type backticks either.

**Comment by CodeTheory** [comment]
@iovis9 All I can say is that it'll be really soon. I haven't heard any solid date yet, but I think the majority is done and we're just waiting to be organised for release.
