### ISSUE TITLE
Linux Download

### ISSUE THREAD

**Issue by lucaros97** [zeit/hyper#1035]
Download link for Linux doesn't work. When you click on it, a new windows display "Version not found: latest" but nothing happen

**Comment by AnwarShahriar** [comment]
I'm facing the same problem too :(

**Comment by jamo** [comment]
Linux version can be downloaded from: https://github.com/zeit/hyper/releases/latest
The dl link will be fixed soon

**Comment by jamo** [comment]
Duplicate of our most duplicated issue: #799
