### ISSUE TITLE
default bash command for editor not working 

### ISSUE THREAD

**Issue by Anzumana** [zeit/hyper#1041]
I just god a college of mine to install hyper.
First thing that did not work is :
bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'
I remembered that this was the same for me so i fixed it by adding to 
his .bashrc / my .zshrc.
I am not that familiar with bash is there something wrong with the statement that this should work?

I changed mine to vim and when i try this from bash it still opens my settings in vim. Even though it should open in nano.

- **OS X 10.11.6**: 
- **Hyper.app version 0.8.3 **:

**Comment by pete-otaqui** [comment]
It's not a bug.

What it's saying is that if you have an environment variable called EDITOR (which is often used in other situations) to use that, or to default to `nano` if EDITOR is not found.

so if you want to specify nano as the default EDITOR you can do this in your bashrc / zshrc:

```
export EDITOR=nano
```

**Comment by Anzumana** [comment]
ok maybe i explained it wrong. this is the line that hyperterm is suggesting to change the editor.
```
echo Attempting to open ~/.hyper.js with your $EDITOR                                                                                                                    echo If it fails, open it manually with your favorite editor!
bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'
```
With a clean new install of hyper.
And that suggested  bash line did not work for him or me either bak when i installed hyper for the first time.
So either we sould change the line to edit you bash/zshrc and add 
```export EDITOR=YourEditorName
```
or we should figure out why the line we are suggesting to people to run is not working.

**Comment by matheuss** [comment]
@Anzumana that's not a suggestion – that's the command we run to open the file 😄 The suggestion is `If it fails, open it manually with your favorite editor!` 😅

**Comment by kleinfreund** [comment]
@matheuss 

> that's not a suggestion – that's the command we run to open the file 😄 The suggestion is If it fails, open it manually with your favorite editor! 😅

I found that confusing when first running Hyper, too. Especially that `echo` is being printed. Is this avoidable?
