### ISSUE TITLE
How to edit .hyper.js?

### ISSUE THREAD

**Issue by jacc** [zeit/hyper#1043]
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X El Capitan
- **Hyper.app version**: Latest

## Issue
Not too sure how to save the file in hyper.js. Doing `vi .hyper.js` opens it, but when I edit it and do quit, it doesn't save.

**Comment by CodeTheory** [comment]
Try editing it when opening it with the command `CMD+,`?

**Comment by jaacks** [comment]
How @CodeTheory? I'm really new but it looked amazing.

**Comment by kleinfreund** [comment]
@jaacks 
> but when I edit it and do quit, it doesn't save.

You edit the file, okay. What are you doing after that? How are you quitting vi? You can save your changes in vi by pressing <kbd>Esc</kbd> and typing `:wq` (which stands for write and quit) followed by pressing <kbd>return</kbd>.

**Comment by CodeTheory** [comment]
@jaacks did the above help you?

As to your question to me <kbd>cmd</kbd> + <kbd>,</kbd> will bring up the hyper preferences file in your default editor.

As @kleinfreund pointed out, with vi you need to write `:wq` to save your changes. With nano you'll need to press <kbd>cmd</kbd> + <kbd>x</kbd> to exit the file, type `Y` and press <kbd>enter</kbd> to save and quit and then <kbd>enter</kbd> again to accept the file name.
