### ISSUE TITLE
Symlink for .hyper.js

### ISSUE THREAD

**Issue by rkb81** [zeit/hyper#1056]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOs Sierra 10.12.1
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/rkb81/889b1fa8eda9f8dbab7cd3b60d37aa4c

## Issue
I have all my configurations for all apps, saved on my dropbox, and create a symlink to use directly, but with hypertherm just not working, the only way the .hyper.js work is put the file directly to my home folder.

**Comment by ivanovyordan** [comment]
It works in Ubuntu 16.04.

**Comment by iovis9** [comment]
macOS Sierra here too. I have a similar configuration as yours but with a `dotfiles` GitHub repo and it works for me. How are you creating the symlink?

**Comment by borwahs** [comment]
@rkb81 - What does the `.hyper.js` file show when running `ls -l` in your home directory?

**Comment by daveaspinall** [comment]
macOS Sierra here and I use a dotfiles setup like @iovis9. Symlinks are created using stow and are working spot on.

<img width="579" alt="screen shot 2016-12-09 at 13 25 55" src="https://cloud.githubusercontent.com/assets/681517/21050533/181cc2cc-be13-11e6-9e08-661ffc8cc244.png">

**Comment by coderobe** [comment]
your symlinks are relative to the current working directory. using absolute symlinks fixes this and is also the recommended way to create symlinks

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by thedonquixotic** [comment]
@Stanzilla I am still having problems with this issue and I have logged a new ticket here: https://github.com/zeit/hyper/issues/3132
