### ISSUE TITLE
Window "decoration"?

### ISSUE THREAD

**Issue by rumpelsepp** [zeit/hyper#1059]
Hi, I am using i3wm. The latest Git version behaves a bit strange according to the window "decorations" (I am not a gui programmer, so I might lack some technical terms. I do not get decorations from i3 any more, instead it seems that hyper is drawing them itself. How can I get the old behaviour back? It is annoying, since hyper does not integrate well into my desktop any more... I do not see the splitmarker any more, the mouse pointer changes, when I touch the border and so on. 

Three times gnome-terminal and one hyper instance.
![2016-11-30-231101_1922x1199_scrot](https://cloud.githubusercontent.com/assets/1961699/20773474/492717a4-b752-11e6-8393-9cd243d89be5.png)

**Comment by kosciak9** [comment]
Same thing here, with qtile wm.
Urxvt and Hyper on screenshot - orange border is appearing when window is active.

![2016-12-13-200908_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4347034/21154860/3db2fd0c-c170-11e6-9095-32335237fc95.png)
![2016-12-13-200912_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4347034/21154859/3dacf312-c170-11e6-97b6-0a5d7727f89d.png)

**Comment by rumpelsepp** [comment]
The Minimize/Maximize/Close buttons can be disabled in the config file; the title bar AFAIK not. Since hyper does not integrate properly in tiling windows managers, I moved to mate-terminal for now.

**Comment by solomonbroadbent** [comment]
As found in the reference Lindenk posted, the solution is to add the plugin: 'hyper-native-window-decoration' to .hyper.js configuration file.

hyper-native-window-decoration GitHub page: https://github.com/bgw/hyper-native-window-decoration

**Comment by albinekb** [comment]
Thanks @solomonbroadbent 👍  Let's close this.  For anyone coming here with the same problem, install `hyper-native-window-decoration` and you're set.
