### ISSUE TITLE
Font Book

### ISSUE THREAD

**Issue by ccorcos** [zeit/hyper#1066]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac Sierra
- **Hyper.app version**: 0.8.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

![image](https://cloud.githubusercontent.com/assets/1794527/20807829/403f1548-b7b5-11e6-891f-c782ef090150.png)

![image](https://cloud.githubusercontent.com/assets/1794527/20807873/66403e98-b7b5-11e6-87df-3e0889698bd3.png)

**Comment by L-A** [comment]
FWIW, this seems to be entirely covered by #914. I suggest treating it as a duplicate?

**Comment by ccorcos** [comment]
@L-A yup!
