### ISSUE TITLE
Link to linux version not found - website

### ISSUE THREAD

**Issue by iheartkode** [zeit/hyper#1067]
https://hyper-updates.now.sh/download/linux  returns "Version not found: latest"

**Comment by kleinfreund** [comment]
Duplicate of https://github.com/zeit/hyper/issues/799

Use the search first, please.

**Comment by matheuss** [comment]
Thank you @kleinfreund

**Comment by iheartkode** [comment]
I used search, it returned no results for me. :+1:

**Comment by matheuss** [comment]
Don't worry @iheartkode 🙌
