### ISSUE TITLE
Hyper is not visible in Spotlight results in MacOS 10.12.1

### ISSUE THREAD

**Issue by smpetrey** [zeit/hyper#1068]
I installed Hyper.
Pressed Command-spacebar to bring up spotlight.
Keyed in: h-y-p-e-r

Results:
![screen shot 2016-12-01 at 9 45 01 pm](https://cloud.githubusercontent.com/assets/6411509/20822502/c2b82c16-b810-11e6-833c-1bdef37539cf.png)

Expected results:
The Hyper App should appear first in Spotlight results.

MacOS 10.12.1
Hyper 0.8.3
Electron 1.4.0
darwin x64 16.1.0

**Comment by ppot** [comment]
Did you install it?
Here is my search. 
<img width="1280" alt="screen shot 2016-12-01 at 11 11 52 pm" src="https://cloud.githubusercontent.com/assets/5577409/20822789/a2c4920e-b81b-11e6-8041-12a974512629.png">

**Comment by smpetrey** [comment]
Sure did 😬
Installed it on the 23rd.

![screen shot 2016-12-01 at 10 15 42 pm](https://cloud.githubusercontent.com/assets/6411509/20822835/c348167a-b813-11e6-9ccf-e6ff5bd9c7da.png)

**Comment by ppot** [comment]
I have the same version as you. So I can't tell what's on your side.

**Comment by smpetrey** [comment]
Well, I re-downloaded the image, reinstalled (overwrote the app in the Applications directory) and that resolved my issue. Feel free to close this strange issue! 🙌

![screen shot 2016-12-01 at 10 22 33 pm](https://cloud.githubusercontent.com/assets/6411509/20822939/c6f5675e-b814-11e6-8e50-578e152041d6.png)
![screen shot 2016-12-01 at 10 23 09 pm](https://cloud.githubusercontent.com/assets/6411509/20822940/c6f8e988-b814-11e6-9693-dfc1ffe6a88a.png)

**Comment by ppot** [comment]
@smpetrey You can close it by yourself. I don't have the permission

**Comment by dfreeman** [comment]
For what it's worth, I just ran into the same issue (and reinstalling also fixed) with Hyper 1.0.0, so it seems like there's something to it, but no clue what could be going on.

**Comment by zcserei** [comment]
Also ran into this issue, I have no idea what causes it, but rebuilding the Spotlight index for the Applications folder seemingly did the trick for me, and I think it's simpler then reinstalling the app.

Here's a quick guide on reindexing:

https://support.apple.com/en-us/HT201716

**Comment by smpetrey** [comment]
Thank you @zcserei ! That is a handy super support article 👏  (and way faster than re-downloading indeed)
