### ISSUE TITLE
Ghosting in console when more than one tab is open and semitransparent background is used.

### ISSUE THREAD

**Issue by vcanales** [zeit/hyper#1071]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX El Capitan 10.11.6
- **Hyper.app version**: 0.8.3 (0.8.3.873)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/devjunkORG/8c98a9c880a58c02c30fc4ee24f7d1c4

- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Whenever I have two tabs open, you can see the content of the other faded, but it doesn't happen all the time and I don't know a way to reproduce it 100% for sure.

Example images attached.

![ghosting](https://cloud.githubusercontent.com/assets/1157901/20836920/5d4dd52c-b880-11e6-9a27-0903787a7d99.png)

![ghosting2](https://cloud.githubusercontent.com/assets/1157901/20836925/65649b10-b880-11e6-89f4-f12a14721740.png)

**Comment by karlpokus** [comment]
Same happens to me. Same OS and app version. The only difference is I have the opacity at `rgba(0,0,0,0.8)`. Wierd.

**Comment by dfrankland** [comment]
It happens after resizing the terminal on my machine.

**Comment by dfrankland** [comment]
Ah, I found the issue! It's caused by the window having a shadow on macOS. If you set the window to not have a shadow it resolves the issue; you may do like below:
```js
exports.onWindow = win => {
  win.setHasShadow(false);
};
```

**Comment by karlpokus** [comment]
@dfrankland Thanks! It works.

**Comment by devjunkORG** [comment]
@dfrankland works perfectly. I do think there should be a solution that doesn't require a plugin. I tried fooling around with settings related to transparency on electron, but it doesn't make a difference. 

Gonna look into the resizing next.

**Comment by xscheiner** [comment]
That doesn't really fix it for me. When I click on a window, the ghosted text goes away. But then when I shift focus to another window, it returns. Since I run on 2 screens and am often watching the terminal while I do something on the other screen, that is annoying.

Also, when I bring the machine back on after sleep, the ghosting is there all the time, whether I have focus on the window or not and I have to quit and restart the app to get rid of it.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
