### ISSUE TITLE
Website download Linux link is broken

### ISSUE THREAD

**Issue by rafaelstz** [zeit/hyper#1073]
The link of Linux version in the website is broken.

![image](https://cloud.githubusercontent.com/assets/610598/20850224/40f61736-b8c1-11e6-97c0-15afa49534b4.png)

**Comment by pablopunk** [comment]
Shouldn't this be an issue in [hyper-website](https://github.com/zeit/hyper-website)?

**Comment by rafaelstz** [comment]
Thanks @pablopunk

**Comment by citycide** [comment]
FWIW, this is also a common duplicate, see:

#1067 
#1051
#1035 
#926 
#918 
#900 
#877 
#799
...

and others. You can download the latest Linux release [here on GitHub](https://github.com/zeit/hyper/releases/tag/0.8.3) I think.
