### ISSUE TITLE
Backspace not working in vim

### ISSUE THREAD

**Issue by samholmes** [zeit/hyper#1081]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- MacOS 10.12.1
- 0.8.3 (0.8.3.873)
- https://gist.github.com/samholmes/e9daf69432e07ea1b9f6a6dd875ed1bf
- N/A
- Vanilla

## Issue

Soooo, when am in INSERT mode in vim, backspace inputs this weird ^? string instead of actually doing a backspace.. Why is this happening? This doesn't happen in Terminal.app

**Comment by OJFord** [comment]
This doesn't happen for me in vim, but I do get that `^?` when the pane locks up, which happens quite frequently in interactive shells, like git's or ssh - so linking my issue (#1254) on that since they may have the same cause.

**Comment by fallspectrum** [comment]
Duplicate of #1801 (this issue is the original, but #1801 was closed for presumably the same reason.)

**Comment by samholmes** [comment]
#1801 has the solution. Issue was related to shell configuration.
