### ISSUE TITLE
Cannot paste sometimes

### ISSUE THREAD

**Issue by Hkmu** [zeit/hyper#1083]
![hyper](https://cloud.githubusercontent.com/assets/3169251/20873902/8c5ccc24-bae7-11e6-8e47-3a1279b94052.gif)

**Comment by ppot** [comment]
Please complete with the desired issue information.

**Comment by johnwebbcole** [comment]
I'm running into the same issue with a fresh load from homebrew.  I can copy *from* hyper, but not to it.

Pasting from the menu does work.  And using pbpaste works too.  Ctrl+v does not.

 OS X 10.12.1 Hyper 0.8.3.873

**Comment by ppot** [comment]
What version. This is fixed in resent master.  #1058 @matheuss

**Comment by johnwebbcole** [comment]
Hyper 0.8.3.873

**Comment by matheuss** [comment]
Truth @ppot, it's fixed 👌 Thank you 😄
