### ISSUE TITLE
Linux Build DL issue on Site

### ISSUE THREAD

**Issue by gmikeska** [zeit/hyper#1087]
when you click the link on your site to download the linux build
https://hyper-updates.now.sh/download/linux

you get:
"Version not found: latest"

I was able to download using the releases tab, and most linux users probably won't have an issue figuring this out but I thought I'd report it! Thanks!

**Comment by citycide** [comment]
Common duplicate. It's being tracked at #799 and according to @matheuss will be solved in the next release.

https://github.com/zeit/hyper/issues/799#issuecomment-255611620

**Comment by matheuss** [comment]
Thank you @citycide 🙌
