### ISSUE TITLE
[Linux] cd ... problems

### ISSUE THREAD

**Issue by V1RE** [zeit/hyper#1092]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04 (64-bit)
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/V1RE/5eba0f1d1297163e59ad8482043553c0
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Whenever I accidentally type "cd ...", hyper.js just goes blank.
Not sure if this is hyper's or ubuntu's fault.

**Comment by kleinfreund** [comment]
Cannot reproduce:

```
$ cd ...
cd: no such file or directory: ...
```

**Comment by nirnanaaa** [comment]
same here.

in my case it's just `cd..` without three dots or space. I'm using zsh and Version 1.0.0 (1.0.0.1303) of hyper.

**Comment by ppot** [comment]
Fixed in #1216
