### ISSUE TITLE
Doesn't seem to be compatible with the rc shell

### ISSUE THREAD

**Issue by danyisill** [zeit/hyper#1095]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X Mavericks 10.9.5

## Issue
It said it can't find the npm command in the $PATH. When I added it to $path it still closed down on start even though it said it installed plugins
Rc shell:
1. Does not use $PATH (it uses $path but it's actually recommended to bind the directories to /bin on load)
2. Even if I did add npm to the path it still didn't open.

![2016-12-07 17 16 41](https://cloud.githubusercontent.com/assets/23189912/20971021/fdb8ce1c-bca0-11e6-9fd1-d3e8bc08ee1a.png)
this is what happens when i try to access settings

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
