### ISSUE TITLE
No tabs open leaves large blank space for tab bar on Ubuntu / Gnome Shell

### ISSUE THREAD

**Issue by antony** [zeit/hyper#1096]
- **OS version and name**: Ubuntu 16.10 / Gnome Shell
- **Hyper.app version**: 0.8.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Is Fresh Install
- **Relevent information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When I have no tabs open (i.e. a freshly loaded terminal with a prompt), there is a huge black void at the top of the screen where the tabs would otherwise be.

This should probably disappear when there are no tabs.

**Comment by ppot** [comment]
@antony  Friendly ping: This require a picture

**Comment by kleinfreund** [comment]
I think theyre just talking about this:

![Screenshot of blank tab bar with only one tab open in Hyper](https://cloud.githubusercontent.com/assets/5774638/21000723/bd570736-bd1c-11e6-9fbb-fec9b1d2ea4e.png)

Not exactly *huge*, but noticable.

**Comment by markokajzer** [comment]
Same on MacOS!

<img width="568" alt="Zero Tabs" src="https://cloud.githubusercontent.com/assets/9379317/21207750/52534422-c2ad-11e6-94e7-bef17fb3984c.png">
<img width="565" alt="Multiple Tabs" src="https://cloud.githubusercontent.com/assets/9379317/21207749/525342ce-c2ad-11e6-89ba-7a7b7b907208.png">

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
