### ISSUE TITLE
Drag & Drop file or folder should place path at cursor

### ISSUE THREAD

**Issue by ndelangen** [zeit/hyper#110]
When dropping a folder or file unto the shell, it should result in the path being placed where the cursors was.

Currently the window just turns completely white.

**Comment by arronhunt** [comment]
Confirmed, dragging and dropping blanks out the view and makes the app unusable. Should insert the path to the file. 

I may play around a little bit and see if I can get it to work.

**Comment by eljefedelrodeodeljefe** [comment]
Added a PR #171

**Comment by samnau** [comment]
This is definitely a feature that makes it not as usable the native terminal. I use the folder drag all the time.

**Comment by luisherranz** [comment]
> This is definitely a feature that makes it not as usable the native terminal. I use the folder drag all the time.

Same here!

**Comment by luisherranz** [comment]
I see another PR (https://github.com/zeit/hyperterm/pull/559) with this functionality is already merged. Awesome!

Keep up the great work :)

**Comment by ppot** [comment]
@matheuss  Closed in #559

**Comment by matheuss** [comment]
Thanks @ppot 😄
