### ISSUE TITLE
CTRL+a does not work in tmux under Linux

### ISSUE THREAD

**Issue by newgene** [zeit/hyper#1100]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.10
- **Hyper.app version**: @aa41081
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: original .hyper.js
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I mapped tmux's "CTRL+b" to "CTRL+a" for convenience. When using tmux under Linux, CTRL+a does not work. I did notice that "CTRL+SHIFT+a" works for the expected "CTRL+a" tmux behavior, but this is still very annoying.

This looks similar to issue #1069, but not sure if they have the same underlying cause.

**Comment by thekalinga** [comment]
Same issue in ubuntu 14.04

Also, pressing Ctrl/Right click deselects the current mouse selection

These are regressions

**Comment by adriaanzon** [comment]
It seems like a lot of keybindings aren't passed to the shell, like Ctrl-a, Ctrl-x, Ctrl-n, Ctrl-z, Ctrl-w, Ctrl-k, Ctrl-t, and all Alt-keybindings

I'm on linux, using version 1.0.0

**Comment by nbolten** [comment]
Hi, I've put in a pull request that hopefully addresses this issue here: https://github.com/zeit/hyper/pull/1191 . It would make the default `mod` key into <kbd>Ctrl</kbd>+<kbd>Shift</kbd> on Windows and Linux so that there are no longer conflicts with CLI apps using <kbd>Ctrl</kbd> shortcuts.

It does not make the `mod` key configurable in `hyper.js`, but I think there's another patch in the works for that.

Feedback is helpful! The pull request is surely not perfect.

**Comment by tarvos21** [comment]
I also have the problem, on Ubuntu, my tmux prefix is `ctrl+a`, it can not work in hyper.js

**Comment by benoror** [comment]
Can confirm latest version of Hyper (`1.0.1.1369`) on MacOS (OS X El Capitan) `CTRL` keybindings doesn't work. 

My particular issue:

```bash
# Bind CTRL (+ Shift) + Tab to move between windows
# http://stackoverflow.com/questions/15470001/bind-ctrltab-and-ctrlshifttab-in-tmux
bind-key -n C-Tab next-window
bind-key -n C-S-Tab previous-window
```

**Comment by alexlitty** [comment]
Confirming for Hyper `1.3.1` on Debian for `ctrl` keybinds in general.

I have `ctrl+left` and `ctrl+right` shortcuts for switching panes. Oddly, they seem to work if I hit `ctrl` once then the arrow key twice. Would be nice to see https://github.com/zeit/hyper/pull/1191 go through :)

**Comment by ppot** [comment]
close in #1876
