### ISSUE TITLE
Plugin and Theme Directory

### ISSUE THREAD

**Issue by daenuprobst** [zeit/hyper#1105]
I just created a couple of (very, very basic and simple) themes for my own use (turnhyperflat, turnhyperflatblack. It would be nice to have a plugin and theme directory to share and get new stuff. Is this currently planned or will you stick with just using the hyper tag on npm? In that case I would suggest to add the link (https://www.npmjs.com/browse/keyword/hyper) to the website.

**Comment by bnb** [comment]
You can check out https://github.com/bnb/awesome-hyper - has a ton of plugins and themes!

**Comment by MatthiasWinkelmann** [comment]
You can browse themes at [http://hyperthemes.matthi.coffee](http://hyperthemes.matthi.coffee).

**Comment by timothyis** [comment]
There is also now an official Hyper Store! https://hyper.is
