### ISSUE TITLE
Add `Launch Hyper here` to nautilus file manager right click

### ISSUE THREAD

**Issue by thekalinga** [zeit/hyper#1109]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 14.04, Linux idealx 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Hyper.app version**:  Latest master branch as of today (not sure where to find version of master branch)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue

In ubuntu file explorer when the user right clicks, it would be better to have an option to open hyper in the current directory like `Launch Hyper here` so that user will not need to navigate to current directory after opening the terminal

**Comment by Dohxis** [comment]
With Nautilus `3.14.3` I have an option to open terminal here when right clicking. So just set Hyper as your default terminal application and you will get this behavior.

**Comment by d0h0** [comment]
![bildschirmfoto von 2016-12-12 17-41-54](https://cloud.githubusercontent.com/assets/5195185/21107617/9fc8d554-c092-11e6-92b0-b3d3a23f4854.png)
It can be realized using nautilus-actions. This allows you to add custom menu points to your dropdowns in nautilus. (see screenshot)

**Comment by leonardon397** [comment]
What I have to do in Naulitus 40?

**Comment by sandenbergmelo** [comment]
Nothing new?
