### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by levani** [zeit/hyper#1110]
I just installed app (have never used it before) and saw several ui issues. This is a clean installation (version 0.8.3.873), I haven't changed any configuration.

There seems to be a font issue:

<img width="247" alt="screen shot 2016-12-10 at 7 14 21 pm" src="https://cloud.githubusercontent.com/assets/184472/21074223/23ec8858-bf0d-11e6-98df-da4fa6cacec1.png">

and when using `nano` there are places where white text is written on white background:

<img width="292" alt="screen shot 2016-12-10 at 7 13 57 pm" src="https://cloud.githubusercontent.com/assets/184472/21074227/3c1554f0-bf0d-11e6-8096-67c47f05243c.png">

That's what I've found so far...

**Comment by jamo** [comment]
You may change the font in `~/.hyper.js`...

**Comment by ppot** [comment]
Closing since we are at `1.3.3` if it's still active please fill a more resent issue.
