### ISSUE TITLE
tmux utf-8

### ISSUE THREAD

**Issue by Fetz** [zeit/hyper#1116]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra 10.12.1 (16B2555)
- **Hyper.app version**:  0.8.3 (0.8.3.873)

## Issue
In TMUX session when mouse clicking in the right side of the windows, characters are typed instead of selecting the pane. Characters are being typed depending from the vertical position and goes from `!"#` to `XYZ`.  I think the problem is that hyper is not supporting mouse utf8

Similar issue https://github.com/zeit/hyper/issues/95

**Comment by dotcypress** [comment]
Fixed in https://github.com/zeit/hyper/pull/1111

**Comment by jkrup** [comment]
I am getting this issue (or something similar), when I click on a tmux pane in certain areas of the screen I get random letters/symbols. I can click and drag to get several characters.
