### ISSUE TITLE
deb package does not depend on npm, 

### ISSUE THREAD

**Issue by karcaw** [zeit/hyper#1117]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 16.04**: 
- **1.0.0**: 
- **default after dpkg install**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

sudo dpkg -i ~/down/hyper_1.0.0_amd64-linux.deb
/opt/Hyper/hyper
Error: Command failed: npm prune && npm install --production
/bin/sh: 1: npm: not found

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
[Notification] Error updating plugins.: Check `~/.hyper_plugins/npm-debug.log` for more information.

please add npm to the dpkg dependencies list.

**Comment by radicaled** [comment]
> please add npm to the dpkg dependencies list.

I use `nvm` and I'd hate to have hyper drag in a system-wide node installation unless absolutely necessary.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
