### ISSUE TITLE
Missing hamburger menu Fedora 25

### ISSUE THREAD

**Issue by plessbd** [zeit/hyper#1118]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 25
- **Hyper.app version**: 1.0
- **Relevant information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

hamburger menu does not show, tried both the appImage and the RPM,  deleted config directories between run of each

```
rm -rf .hyper.js .hyper_plugins .config/Hyper
                                                                                
/opt/Hyper/hyper

read error /home/user/.hyper.js ENOENT: no such file or directory, open '/home/user/.hyper.js'
attempting to write default config to /home/user/.hyper.js
plugins have changed / not init, scheduling plugins installation
running in prod mode
electron will open file:///opt/Hyper/resources/app/index.html
Checking for notification messages
ignoring auto updates during dev
No matching notification messages
```

I tried to use devtools, but when opening them I get a blank pane.

I tried to install hyperterm-install-devtools and hyperterm-open-devtools plugins buth that did not seem to change anything with devtools either

If there is anything I can do to help let me know

**Comment by plessbd** [comment]
I tried to use devtools, but when opening them I get a blank pane.

I tried to install hyperterm-install-devtools and hyperterm-open-devtools plugins buth that did not seem to change anything with devtools either

**Comment by matheuss** [comment]
@plessbd please check here: https://github.com/zeit/hyper/blob/master/app/config-default.js#L33
put `showHamburgerMenu: true,` in your `.hyper.js` and let me know if it works 😄

**Comment by plessbd** [comment]
that did it.  Should have thought to actually look at the config.  Might be nice if we could add that to default to true if we detect linux on first write of config.

**Comment by matheuss** [comment]
Actually is our fault – we need to document it on the website 😅 I'll make sure to do it soon 🙌
