### ISSUE TITLE
ctrl+shift+n creates an empty window

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#112]
Ubuntu 16.04, no errors in console.

![image](https://cloud.githubusercontent.com/assets/2193314/16889371/d1572efe-4a9a-11e6-9204-dfad07ee5094.png)

**Comment by albinekb** [comment]
Can reproduce on OS X 10.11.6, even in master, not sure what's causing it 🙌

**Comment by yesmeck** [comment]
Reproduce on my Mac, using current master(https://github.com/zeit/hyperterm/commit/7398593bc36b9624db25f3faee21c3a35b1ca415).

**Comment by yesmeck** [comment]
`ctrl-shift-n` create a new window, but not emit `new` event.

**Comment by yesmeck** [comment]
Find it, `ctrl-shift-n` is hterm's shortcut to open new window.

**Comment by yesmeck** [comment]
Overriding `onCtrlN_` to a no-op function fix this issue.

```javascript
hterm.Keyboard.KeyMap.prototype.onCtrlN_ = function() {};
```

**Comment by yesmeck** [comment]
I'd be pleasure to send a PR.

**Comment by CodeTheory** [comment]
@Tyriar, is this still happening? cc/ @albinekb
I can't reproduce

**Comment by Tyriar** [comment]
Can no longer repro, but I filed https://github.com/zeit/hyper/issues/1159
