### ISSUE TITLE
1.0.0 release broke some keybindings

### ISSUE THREAD

**Issue by jritsema** [zeit/hyper#1120]
I use [Karabiner](https://github.com/tekezo/Karabiner) for MacOS and noticed that the 1.0.0 release seems to have broke some of my custom keybindings.  Anyone else notice this yet?  Any idea what could have caused it?

**Comment by bradleyboy** [comment]
Same issue here. I remap left command to control, and that is not working in Hyper 1.0.0.

**Comment by ppot** [comment]
close in#1876
