### ISSUE TITLE
Installing Hyper on Linux via `*.deb` creates broken symbolic link. (command not found: hyper)

### ISSUE THREAD

**Issue by c650** [zeit/hyper#1123]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 15.10
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Here](https://gist.github.com/c650/f4b2fa82ddbd1c00bde6f8ccae4b4880)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: Fresh Install, so Yes.

## Issue

Hello. My Issue is about installing from the standard 1.0.0 debian package (downloaded from [hyper.is](https://hyper.is/#installation)). I ran the typical `sudo dpkg --install ./hyper-1.0.0.deb` and it installed successfully. However, running `hyper` results in `command not found`.

It turns out that a broken link is created by the installation.

`/usr/local/bin/hyper -> /opt/hyper/hyper`

should be...

`/usr/local/bin/hyper -> /opt/Hyper/hyper`

That capital H caused a "failed" installation.

**Comment by Asuza** [comment]
This also happened to me on Ubuntu 16.04, on Hyper version 1.0.0.

**Comment by c650** [comment]
@Asuza and my fix worked for you, I assume?

**Comment by Asuza** [comment]
@c650 your fix worked fine.

**Comment by geekosupremo** [comment]
I have tried to do as you recommend @c650 on a Debian Stable install, and it keeps telling me that
`bash: hyper: command not found`

if I use `/opt/Hyper/hyper` the app opens

I have tried to change the sym link using 
- `ln -f -s /usr/local/bin/hyper /opt/Hyper/hyper`
- `ln -s /opt/Hyper/hyper hyper`
`ln -s /usr/local/bin/hyper newhyper`
`mv -T newhyper hyper`
- `$ ln -sfnv /usr/local/bin/hyper /opt/Hyper/hyper`

Yet the "command not found" is always the response.

What am I missing?

**Comment by c650** [comment]
I deleted the link and made a new one, @geekosupremo.

**Comment by geekosupremo** [comment]
@c650 Gotcha. Thank you for the heads up. I am still fairly new to Linux and I messed up the command.

Anyway I did get the symlink to work after reading the man page more carefully, and after installing a couple of needed libs, the command runs as expected. :grinning: Thank you for your patience and for pointing out, gently, where I had gone awry.

**Comment by dunst0** [comment]
this is also happening on Hyper 1.1.0 on Linux Mint, the link is still broken

**Comment by edouerd** [comment]
This is still occurring in 1.2.1, reporting in from Lubuntu.

**Comment by c650** [comment]
This bug really does affect usability for less-advanced linux users (unless they find this Issue easily).

**Comment by edouerd** [comment]
@c650 yeah! It seems like a rather straightforward fix — would be so cool to see this make the next release!

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
