### ISSUE TITLE
Ctrl+C, Ctrl+D not parsed in Windows Command Prompt/Powershell

### ISSUE THREAD

**Issue by rainyday** [zeit/hyper#1124]
- **OS version and name**: Windows 8.1 x64
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: No changes from default.
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 

```
bundle.js:628 (re)loading renderer plugins
index.html:34 total init time 1216.7900000000004
6bundle.js:33054 Bold characters disabled: Size of bold weight differs from normal.  Font family is: Menlo, "DejaVu Sans Mono", "Lucida Console", monospace
```

- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla
## Issue

Pressing Ctrl+C in the windows command prompt in 1.0.0 doesn't do anything, Pressing Ctrl+D simply prints out "^D" instead of killing the current process. In msys bash these commands behave as expected so this is specific to cmd and Powershell.

**Comment by CodeTheory** [comment]
Sorry, didn't realise but this is already an issue at #1121. If you could extend that issue, I'd be incredibly grateful.
