### ISSUE TITLE
Preferences are opened in notepad.exe on Windows, mangling line endings

### ISSUE THREAD

**Issue by mqudsi** [zeit/hyper#1126]
On Windows, the settings are opened in notepad.exe which does not support line breaks. You should either use `\r\n` in your settings or open the settings with wordpad or any other app that supports Linux-style link breaks.

**Comment by mqudsi** [comment]
Not a bad idea, but honestly most people won't have changed their default text editor.

**Comment by jongalloway** [comment]
@mqudsi I agree. If you've got notepad++, atom, vs code, etc. configured that'd be best, but that'd be a tiny percentage of users. Lauching with wordpad is probably the best option right now. 

Longer term, a fancier solution would be to check if the user has configured a text editor (look up reg key, if it's not notepad.exe use it, otherwise use wordpad) but wordpad would probably be fine.

**Comment by tivac** [comment]
It's too bad that `.js` files don't have a default text editor association on windows, it'd be much easier if `shell.openItem(fullPath)` would do a sane thing by default.

**Comment by jongalloway** [comment]
@tivac There is a default `.js` editor on Windows, and it's configurable. It's just that very few people seem to change it, and code editors (like VS Code) don't seem to set it either. The reg setting is `HKEY_CLASSES_ROOT\JSFile\Shell\Edit\Command`

**Comment by jongalloway** [comment]
A good recommendation in the [comments on the PR](https://github.com/zeit/hyper/pull/1138#issuecomment-266556896) is to use `shell.showItemInFolder()` to just show the file in the folder (`shell.showItemInFolder()`) and allow the user to open via context menu.

**Comment by tmr232** [comment]
Why not simply add it as a configuration option in `.hyper.js`? That would be the easiest way to configure it.

**Comment by mackenza** [comment]
I am in complete agreement with @tmr232 . There should be an `editor:` property of the `config{}` object where the executable (with or without path) can be entered.

It wouldn't hurt to first default to an ENV variable first like `%EDITOR%` but that is much less common on windows.

**Comment by jonathandelgado** [comment]
I think that is a little bit circular, setting `editor` in a config that is supposed to be opened by `editor`.

Ultimately, opening the config is a once-a-month thing, no need to over complicate it. `shell.showItemInFolder()` is a simple and adaptive solution.

**Comment by warpdesign** [comment]
I would suggest to either use HKEY_CLASSES_ROOT\JSFile\Shell\Edit\Command to get the default editor for js files, and if not defined, fall back to Wordpad.

But avoid using notepad since loaded file is unusable as @mqudsi pointed out.

**Comment by mqudsi** [comment]
Why don't we just add Windows line endings to the default configurations file?




On Tue, Dec 13, 2016 at 10:57 AM -0600, "Nicolas Ramz" <notifications@github.com> wrote:












I would suggest to either use HKEY_CLASSES_ROOT\JSFile\Shell\Edit\Command to get the default editor for js files, and if not defined, fall back to Wordpad.


But avoid using notepad since loaded file is unusable as @mqudsi pointed out.

**Comment by cthedot** [comment]
Problem is **even if** a default editor for .js is defined (which maybe a lot of devs and so users of Hyper do anyway) Hyper still opens it in Notepad :(
If I open it manually in VCSCode (my default .js editor and which handles lines too) it is just fine.

**Comment by jamesrom** [comment]
There are three solutions:

1. Make .hyper.js use CR+LF line endings on Windows. This is trivial.
2. Check registry for default js editor, and open .hyper.js with that. Fallback to wordpad (see [this](https://github.com/zeit/hyper/issues/1126#issuecomment-266779812) comment).
3. Ship with a default text editor (perhaps a plugin) that is a simple textarea with a save button.

**Comment by tmr232** [comment]
Can't see any reason not to use both (1) and (2).

**Comment by mqudsi** [comment]
This directly inspired the development and release of the open source [betterpad](https://neosmart.net/blog/2017/hello-betterpad/), a plain-text editor for Windows that doesn't suck. [Fork on github](http://github.com/neosmart/betterpad).
