### ISSUE TITLE
Support Windows Semi-Maximized States

### ISSUE THREAD

**Issue by WorldMaker** [zeit/hyper#1128]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1
- **Hyper.app version**: 1.0
- **The issue is reproducible in vanilla Hyper.app**:  Is Vanilla

## Issue

Neither dragging the application to the "hot edges" nor the Windows Key Arrow Shortcuts (`Win+Right Arrow`, `Win+Left Arrow`) will move the application window into Windows' useful "semi-maximized" states. (Half-screen layouts in Windows < 10, also quadrants in Windows 10)

**Comment by arcanis** [comment]
Also, <kbd>Win</kbd>+<kbd>Up Arrow</kbd> should maximize the window, but currently has no effect.

**Comment by berwyn** [comment]
Could this have anything to do with redirecting the resize events to the pty? Electron has native support for these events, so I can't help but think Hyper's resize logic might be interfering somehow

**Comment by JAForbes** [comment]
Yeah this behaviour comes for free in a default electron app, so maybe there's a `preventDefault` somewhere?

**Comment by paulcbetts** [comment]
This is fixed in #1307

**Comment by kwonoj** [comment]
Specifically https://github.com/zeit/hyper/pull/1307/files#diff-2018087f584c4398b5c3a23fc0e5f9dbR142 in #1307 - setting `transparent: true` in windows will block aero snap features.

**Comment by matheuss** [comment]
#1307 👌

**Comment by srchulo** [comment]
I seem to be seeing this issue, where dragging to the left or right won't snap, and windows left and right won't work either.

**Comment by srchulo** [comment]
Windows up and down work for me, though.

**Comment by rickbrunstedt** [comment]
@srchulo If you have "hyper-tabs-enhanced" installed, remove that and then try again. It gave me the same problem..

**Comment by srchulo** [comment]
@rickbrunstedt thanks! That did the trick. Sad that I can't use hyper-tabs-enhanced.

**Comment by vaaski** [comment]
Just ran into the same thing, equally as sad that it doesn't work with hyper-tabs-enhanced.
@henrikdahl do you know about this?
