### ISSUE TITLE
htop colors

### ISSUE THREAD

**Issue by mqudsi** [zeit/hyper#1129]
Hello,

Running hyper 1.0.0 on Windows 1607 under bash.exe, attempting to launch htop. The colors appear inverted, though I'm not sure why since I haven't specified any custom colors for htop. Kindly see the attached screenshot.

(not the htop is worth a damn on WSL, it shows only junk data. It was just a quick test of the color and redraw capabilities of hyper.)

![image](https://cloud.githubusercontent.com/assets/606923/21111261/50eadb7a-c066-11e6-8f87-a42a96da899d.png)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
