### ISSUE TITLE
"A Javascript error occured in the main process" windows install

### ISSUE THREAD

**Issue by bitttttten** [zeit/hyper#1130]
- **OS version and name**:  Windows 10 
- **Hyper.app version**: 1.0.0
- **Link of a dump with the contents of your .hyper.js**:  [dump](http://hastebin.com/udaxorukoz.js)

## Issue
I'm trying to install Hyper by running hyper-Setup-1.0.0.exe and I get the above error. Also[ here's a screenshot](http://i.imgur.com/Q8deraX.png) of the full error.

Hyper.exe also stays running as a process after this dialog closes. If I run the set up again after closing the dialog I get a different error, although if I kill the Hyper process through Task Manager and run the setup.exe again then I get the same error included in the screenshot.

**Comment by stefanivic** [comment]
@bitttttten can you try to run the setup as an admin ?

**Comment by bitttttten** [comment]
I ran `npm cache clean` and I was already running it as an Administrator. 

[This is the log](http://hastebin.com/jojiniqegu.txt) I get if I try to run it again without closing the hyper.exe instances that are lefting hanging.
