### ISSUE TITLE
Hyper.app does not load zsh correctly on 1.0.0, did before (errors in devtools)

### ISSUE THREAD

**Issue by Connorelsea** [zeit/hyper#1131]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  MacOS Sierra 10.12
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Connorelsea/1200e058e19e683653100277f6997a26

## Issue

Hyper.app does not load zsh correctly on 1.0.0, did before.

This is how iTerm 2 opens. Using my zsh configuration. Hyper.app opened like this before version 1.0.0.

![image](https://cloud.githubusercontent.com/assets/1844458/21111378/e5c86532-c066-11e6-91f4-4a96b68c7e96.png)

This is how the terminal opens using Hyper.app, seemingly not using zsh.

![image](https://cloud.githubusercontent.com/assets/1844458/21111332/9d5f92ca-c066-11e6-9a4e-7f439399da0d.png)

Here is the devtools output:

![image](https://cloud.githubusercontent.com/assets/1844458/21111366/d77fd3a2-c066-11e6-95e8-f7875aaf90c9.png)

This happens if I type stuff:

![image](https://cloud.githubusercontent.com/assets/1844458/21111434/2117ea72-c067-11e6-8aaa-8ce46267d851.png)

**Comment by Connorelsea** [comment]
Update:

It seems as if this is loading zsh, but is not loading it correctly. I wonder why my two terminals look differently.

![image](https://cloud.githubusercontent.com/assets/1844458/21111645/166d4d28-c068-11e6-9374-f9eab10615be.png)

**Comment by dotcypress** [comment]
Fixed in https://github.com/zeit/hyper/pull/1111
Stay tuned ;-)
