### ISSUE TITLE
Linux keyboard short-cuts need an overhaul.

### ISSUE THREAD

**Issue by radicaled** [zeit/hyper#1132]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: 1.0.0
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Just checked out the 1.0.0 of Hyper. It looks cool, but basically most of the keyboard short-cuts for Linux have problems.

To start with, on Linux, terminal programs use a variety of combinations of CTRL+([a-z1-9]), so having those be menu accelerators is a problem. Terminals in Linux prefix all of the accelerators with "SHIFT" in order to get around this issue. CTRL+C (copy) becomes SHIFT+CTRL+C. The only exception for this appears to be "CTRL+0" which is used for resetting font size. Guess CTRL+0 is off limits for terminal applications for some reason, or just isn't used.

Also, tab navigation is broken in Ubuntu Linux: CTRL+ALT+(LEFT, RIGHT, UP, DOWN) is currently reserved for virtual desktop navigation. If you have virtual desktops enabled then that keystroke will take you to another desktop rather than switching tabs. I think Gnome Shell uses the same keybindings for virtual desktop navigation. 

In general, on Linux, CTRL+PGUP and CTRL+PGDN are the keybindings for navigation between tabs.

There are a lot of little issues here and there on Github (ctrl+a doesn't work here, ctrl+x doesn't work there) so I thought it might be better to have a single issue detailing all of the broken accelerators rather than a ton of little ones.

I looked at `accelerators.js`, but it's currently doing a ternary check on whether the operating system is Mac or not. I'm actually not quite sure what the cleanest approach for OS detection (and behavior switching) is for that file, which is why this is more of a Github issue and less of a patch.

**Comment by maximumdata** [comment]
Agreed, I got quite a shock when I tried to ctrl+w to search for something in nano!

**Comment by radicaled** [comment]
@CodeTheory I feel like this is a bug more than an enhancement -- some of the accelerators render Hyper unusable under Linux when it comes to certain programs.

**Comment by CodeTheory** [comment]
Good point @radicaled. Re-labeled 😄

**Comment by nemith** [comment]
ctrl-Z doesn't work as well.  It seems that assumptions from OSX where Mod got mapped to CTRL.

**Comment by WoodyWoodsta** [comment]
Possible dupe and additional discussion in https://github.com/zeit/hyper/issues/1069#issuecomment-264415774

**Comment by elchinot7** [comment]
I been used **ctrl-a** as prefix for **tmux**, however in a Hyper terminal ctrl-a select all text. This simple issue is stopping me from use Hyper as my every-day terminal app.

**Comment by ppot** [comment]
CLOSED IN #1876
