### ISSUE TITLE
Where is the config file stored, on Windows?

### ISSUE THREAD

**Issue by ryancole** [zeit/hyper#1134]
I just installed on Windows. For whatever reason, I immedietly opened the config file, via the `File` menu, and saw that there was a setting to specify which shell to use. I typed in `powershell` and saved. Now hyperterm fails to bring up any shell, etc.

Where is this config file stored? I need to undo that change.

**Comment by stefanivic** [comment]
@ryancole It is stored in the default user directory : C:\Users\{userName}\.hyper.js . Just edit it and point to direct powershell path : C:\\\Windows\\\System32\\\WindowsPowerShell\\\v1.0

**Comment by ryancole** [comment]
Thanks!

**Comment by crumdev** [comment]
Also I found that the '--login' shell argument prevents powershell from opening. Try removing it and open the terminal again.

**Comment by weeksdev** [comment]
Looks like in hyper 3 the default location has changed to `C:\Users\{userName}\AppData\Roaming\Hyper`.  Just wanted to make note of that in case others run into same issue

**Comment by mujina93** [comment]
Could anybody update the new path for windows in the guide? (https://hyper.is/)
Currently this is shown: `$Env:AppData/Hyper/.hyper.js`

**Comment by gerardbosch** [comment]
Hi there, IMHO the new configuration location hardens its location and user backup. It is a quite annoying directory for a so important file. Why not something more obvious directory such as the previous `C:\Users\USER\.hyper.js` or `C:\Users\USER\.hyper\hyper.js`?

My `C:\Users\USER\AppData\Roaming` directory is 428MB. I don't think this is a "configuration" directory and I don't need to backup. If I want to move no a new environment is very annoying to locate every application configuration directory. I don't think Windows (or at least its applications) works or respect something like Linux XDG Base Directory Specification.

P.S. I'm just a newcommer to Hyper, and all I can say is 😍 😍 😍
