### ISSUE TITLE
Hard reload on windows sets the background color to transparent

### ISSUE THREAD

**Issue by ansballard** [zeit/hyper#1135]
1. Clean install
1. Open hyper
1. `Ctrl`+`Shift`+`R`
1. Hyper reloads with a transparent background
    - No errors in the console
    - `~/.hyper.js` is unchanged
1. Closing and re-opening hyper fixes the background

---

Hyper 1.0.0
Electron 1.4.7
win32 x64 10.0.14393

**Comment by Rahh1112** [comment]
Can confirm this issue.

Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/12601769/21115108/eb25ea60-c096-11e6-9250-fec8fb136ab2.png)

**Comment by stefanivic** [comment]
@ansballard  @Rahh1112  Thanks for the issue report but the bug is already mentioned here : https://github.com/zeit/hyper/issues/1026 . If you could post in there that would be awesome!
@CodeTheory

**Comment by ppot** [comment]
Closing in favor of #1026

**Comment by ansballard** [comment]
Oops, sorry about that. Assumed it was a new issue since official Windows support just dropped. I'll pile onto #1026, thanks!
