### ISSUE TITLE
Press and hold keys on OSX causes suggestions popup

### ISSUE THREAD

**Issue by chrisnojima** [zeit/hyper#1137]
- **OS version and name**: OSX 10.12.1
- **Hyper.app version**: 1.0.0.1303
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: NA
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Just updated to 1.0.0, now when I'm in neovim if i press and hold down the 'L' key instead of repeating the movements, it also flickers the popup to enter 'ł'. It also seems to affect all keys as pressing and holding jkli keys seems sluggish. Was fine before this and is still fine in iterm. See attached gif which captures a subset of the popups flashing

![press hold neovim](https://cloud.githubusercontent.com/assets/516435/21115950/71520ef4-c081-11e6-9df8-8b14e051edab.gif)

**Comment by ppot** [comment]
@matheuss  Related to hyperCaret

**Comment by jessemillar** [comment]
Same issue here. Experienced on the same OS inside normal `vim`.

**Comment by xvalentino** [comment]
Noticed this too. Anyone have any ideas as to why this would happen here and not in iTerm? You can also disable this on a per app basis. https://gist.github.com/rastasheep/bfc8266eeb58b899054c

**Comment by xvalentino** [comment]
We could probably use this. Maybe in a plugin? https://github.com/electron/electron/pull/8084

**Comment by detj** [comment]
Yeah, this is pretty annoying. Solved it by running

```
defaults write co.zeit.hyper ApplePressAndHoldEnabled -bool false
```

This should be make in to a plugin.

**Comment by roolebo** [comment]
`systemPreferences.setUserDefault` from electron can be used to disable `ApplePressAndHoldEnabled` as @xvalentino pointed out.

However I think it should be part of core rather than a plugin. Accent pop-up is designed for input fields where caret doesn't move when user holds a key. Hyper caret behaviour is different, it always moves, so there's no point to have the pop-up window as it appears and disappears without letting user to select an accent.

**Comment by sukima** [comment]
This is still happening with Hyper 2.0 on Mojave. Is there a reason this was closed and abandoned?

**Comment by AndresCuervo** [comment]
@sukima This was fixed in 2017 but broke again recently. Looks like @chabou fixed it a few days ago, see https://github.com/zeit/hyper/issues/3317 This fix should be live whenever v2.1.1 comes out.

**Comment by jflatow** [comment]
This still seems to be a real issue in Hyper 3.x.x

**Comment by jasongaare** [comment]
Also seeing this in Hyper 3.0.2
