### ISSUE TITLE
Post-install update - Reload causes unresponsive terminal

### ISSUE THREAD

**Issue by AverageZ** [zeit/hyper#1139]
### Steps:

1. Wanted to update my macbook config to match my work computer, open preferences
2. Update plugins from
```
plugins: [
    "hyperpower"
]
```
to:
```
plugins: [
    "hyperpower",
    "hyperyellow",
    "hyperline",
    "hypercwd"
]
```
3. Wait for the message that I can reload: reload
4. Completely unresponsive terminal window
    * can't use key commands other than cmd-n which creates another unresponsive terminal
    * full restart (system and hyper) doesn't fix it

The same config on my work computer works fine (Mac Pro 2013) with latest Hyper

Hyper 1.0.0
Electron 1.4.7
darwin x64 15.0.0

<img width="722" alt="screen shot 2016-12-12 at 4 00 25 pm" src="https://cloud.githubusercontent.com/assets/9088088/21116578/1e87fb18-c084-11e6-81a0-6a7ff01fe1a6.png">

**Comment by AverageZ** [comment]
<img width="474" alt="screen shot 2016-12-12 at 4 02 31 pm" src="https://cloud.githubusercontent.com/assets/9088088/21116666/6bfc0b50-c084-11e6-8910-21accc83e208.png">
After a third reload I could open dev tools

**Comment by AverageZ** [comment]
@ppot I think I sorted it:

When I checked the hyper.js config file I noticed that all my config colors had been right padded with an empty space, fixed.

**Comment by ppot** [comment]
Great! Il close!
