### ISSUE TITLE
Resizing tmux panes with mouse in wide terminals

### ISSUE THREAD

**Issue by shannonmoeller** [zeit/hyper#1140]
- **OS version and name**: macOS 10.12.1
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Is Vanilla
- **Relevent information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I am still having issues with resizing tmux panes with the mouse. Resizing works as expected for small terminals, but when the width and height exceeds a certain amount, mouse interactions begin printing out characters. At first I thought it only affected vertical resizing, but it appears to happen when the mouse-dragging happens in any direction past the 80th character column or so.

![image](https://cloud.githubusercontent.com/assets/155164/21117061/3f8fe2d8-c086-11e6-91d7-ff6ce4ecd1dd.png)
![image](https://cloud.githubusercontent.com/assets/155164/21117106/61bd22d0-c086-11e6-885a-9debf40d0036.png)

Possibly relates to #846 and #875.

**Comment by jsangilve** [comment]
I'm having this issue as well. Tmux's vertical resize bind doesn't work.

**Comment by shannonmoeller** [comment]
Bump.

**Comment by elithrar** [comment]
Ditto.

* At 3584 × 2270 (retina) the ability to resize splits via the mouse no longer functions.
* Works at 1904 × 2270 and does not appear to mis-inject characters.
* Injects characters at 3390 × 2270.

Hyper Version 1.1.0 (1.1.0.1408), tmux 2.3

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by shannonmoeller** [comment]
Confirming as fixed. Thanks!
