### ISSUE TITLE
Plugin-Update does not work when Shell is set to Fish

### ISSUE THREAD

**Issue by hoffi** [zeit/hyper#1142]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.1
- **Hyper.app version**: 1.0.0.1303
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [My .hyper.js](https://gist.github.com/hoffi/7c4277ddfa4dc893fed2ad2d668f60b4)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: None
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When i configure fish as my shell in `.hyper.js` the plugin update always fails. 
The problem is [this line](https://github.com/zeit/hyper/blob/master/app/plugins.js#L239) which executes `npm prune && npm install --production` in the configured shell. When i change this to `npm prune; and npm install --production` it works for me.

Maybe the best would be to not run it directly on the configured shell and use something like for the preferences: `bash -c "exec env npm prune && npm install --production"`

**Comment by einfallstoll** [comment]
I can confirm executing a `bash` then editing the settings works.

**Comment by hoffi** [comment]
#1065
