### ISSUE TITLE
Powerline generating line breaks in 1.0.0

### ISSUE THREAD

**Issue by ChrisW-B** [zeit/hyper#1145]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra 10.12.2 Beta (16C63a)
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ChrisW-B/e20639eb07357a6701c6bdd57e63c6fd
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

When powerline is installed, a line break is generated after each character is typed. I believe this has to do with how powerline checks to see if the prompt needs to be changed, but it should be happening on the same line. A screenshot is attached 
![screen shot 2016-12-12 at 5 52 03 pm](https://cloud.githubusercontent.com/assets/2490974/21120138/db80bc32-c093-11e6-8616-62c41f571602.png)
Thanks for any help you can provide!

*edit*: I should also note that this happens on resize, which makes sense if its an issue with replacing the current powerline text

**Comment by dotcypress** [comment]
@ChrisW-B could you try to reproduce this issue on [this branch](https://github.com/dotcypress/hyper/tree/unicode-perfomance-fix)?

**Comment by ChrisW-B** [comment]
Still there: 
![screen shot 2016-12-13 at 10 10 03 am](https://cloud.githubusercontent.com/assets/2490974/21145477/79617b0c-c11c-11e6-8600-126f666b4de7.png)

**Comment by ChrisW-B** [comment]
Seems to have been my fault, as it is working well after a clean powerline install. Not sure why it only affected Hyper, but I'm going to close
