### ISSUE TITLE
Vibrancy effect changes on full reload

### ISSUE THREAD

**Issue by colepeters** [zeit/hyper#1146]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [click here](https://gist.github.com/colepeters/799f2c77e1bf7eaf0387087992251bba)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: No, this requires a plugin which sets the `setVibrancy()` of the window

## Issue

**NB: I used the phrase 'full plugin reload' in the screenshots below, before realising it's just 'full reload'. Sorry for any confusion.**

I’ve noticed that the effect of `setVibrancy()` changes when using a plugin which sets the vibrancy and doing a full reload. For example, here’s an instance of hyper with no customisations except for adding the [hyper-simple-vibrancy](https://github.com/matheuss/hyper-simple-vibrancy) plugin:
![image](https://cloud.githubusercontent.com/assets/1713932/21120576/f52e8278-c0bf-11e6-99a8-ac7ae7d1d390.png)

If I now do a full reload (`Shift-Cmd-R` on macOS), then after the reload my window looks like this:
![image](https://cloud.githubusercontent.com/assets/1713932/21120614/24a27f50-c0c0-11e6-8d60-1fd6fb518fd2.png)

Here’s another example using a theme plugin I’m working on locally. I’m setting the following relevant configs in my plugin:

```js
module.exports.onWindow = browserWindow => browserWindow.setVibrancy('ultra-dark');

module.exports.decorateConfig = config => {
  return Object.assign({}, config, {
    backgroundColor: 'rgba(41,43,46,0.666)',
    …
```

With this plugin loaded, here’s what things look like when opening a new window:
![image](https://cloud.githubusercontent.com/assets/1713932/21120674/69af7c1a-c0c0-11e6-8597-f31fc5493953.png)

However, after doing a full reload the background looks more vibrant:
![image](https://cloud.githubusercontent.com/assets/1713932/21120692/8564a322-c0c0-11e6-8fdc-612770c083c7.png)

I’ve tried inspecting for differences using the dev tools to see what might be happening to trigger the change in appearance after a full reload, but nothing’s grabbing my eye.

Interesting to note that after a basic reload (`Cmd-R` on macOS), there are no changes to the background. It’s only the full reload that triggers the change — then opening a new window goes back to the initial washed-out/less vibrant appearance.

I’m happy to help solve this if I can, but I’m not really sure where to look. The vibrancy appearance after the full reload seems to be a lot more pleasing than the alternative, so if there’s a way to get it always looking that way without the full reload, that would be great.

Thanks as always for all the awesome work on Hyper, especially on shipping 1.0!

**Comment by colepeters** [comment]
After searching a little bit more, wondering if #873 is related at all…?

**Comment by dotcypress** [comment]
I bet that https://github.com/zeit/hyper/issues/1026 is related to this too 😎

**Comment by albinekb** [comment]
@colepeters why did you close this? 🤔

**Comment by colepeters** [comment]
Oops! Mistake.

**Comment by albinekb** [comment]
👌  @colepeters, I asked because your initial post was so good and descriptive 👍  thanks <3

**Comment by timothyis** [comment]
This should be fixed now. Please re-open if I'm incorrect!
