### ISSUE TITLE
Rounded corners on main window

### ISSUE THREAD

**Issue by ryanpager** [zeit/hyper#1148]
## Issue
Is there a way in the css to disable rounded corners on the main window -- or is that due to macs rounding of the application window by default. I tried overriding with the css and termCss in .hyper.js, but nothing seemed to work.

Reason for this is I try to doc the terminal to the top of the screen, and the rounded corners are making me insane. 

Any help with this would be great!

**Comment by CodeTheory** [comment]
Please follow the issue template, knowing some information from there would have helped.
What OS are you on?

**Comment by ryanpager** [comment]
Sorry about the missing template, here are the details.

Version: Latest (1.0)
Operating System: Mac 10.11.2
Gist to .hyper.js: https://gist.github.com/ryanpager/4ab0622e3ee6f0c6c6fd57f377ea1c54

**Comment by CodeTheory** [comment]
@ryanpager It is not possible to get rid of rounded corners on Mac OS unfortunately. This is an upstream limitation and we can't fix it 😞

**Comment by ryanpager** [comment]
That was my thought too -- bummer. Thanks for the help!
