### ISSUE TITLE
Application > Preferences only works on OS X

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#115]
Ubuntu 16.04

`$EDITOR` is not set normally on Linux, you can use the alternatives system on Debian at least to get the default text editor. On Windows you can probably just launch the file as a child_process and the default program will open.

![image](https://cloud.githubusercontent.com/assets/2193314/16889461/7b9c5b8c-4a9b-11e6-9743-1c3aa4ac804a.png)

**Comment by lo1tuma** [comment]
It is also not working for me under macOS using zsh.

**Comment by jimthedev** [comment]
There are alternatives to using $EDITOR https://github.com/lahmatiy/open-in-editor

With that said, prompting the user to set $EDITOR is probably the best option since then they'd be able to choose which they prefer.

**Comment by saitheexplorer** [comment]
@lo1tuma are you getting an error when using zsh? i was getting an error with the `#` character that was not being parsed as a comment (zsh: bad pattern: #)

i added `set -k` to my .zshrc and that fixed it.

http://unix.stackexchange.com/a/33995

**Comment by MrRio** [comment]
Fixed in this PR by adding a fallback https://github.com/zeit/hyperterm/pull/517

**Comment by flybayer** [comment]
This was fixed by #736 :boom:

**Comment by flybayer** [comment]
Wait, I think I misunderstood the issue. It looks like #517 actually fixed it.

**Comment by CodeTheory** [comment]
Looks like it should be fixed in the newest release. Please re-open if what I'm saying is false.
