### ISSUE TITLE
Windows Installer not Creating Shortcuts

### ISSUE THREAD

**Issue by matankb** [zeit/hyper#1151]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: gist.github.com/matankb/6da6a994c6a8886fab751440b0741ab7
- **Relevent information from devtools**: N/A (no errors/warnings)
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

The windows installer didn't create a start menu or desktop shortcut when ran. I also can't find anything in `C:/Program Files`, making it impossible to re-launch Hyper (asides from reinstalling). However, the uninstall part of the Control Panel does list Hyper as one of the installed apps. `hyper_plugins` and `.hyper.js` also exist.  Is this intended? If so, where are the `.exe`s kept?

Thank you!

**Comment by stefanivic** [comment]
@matankb Hyper is installed in C:\\Users\\{userName}\\AppData\\Local\\hyper. Try to find it there.

**Comment by matankb** [comment]
@stefanivic Found it, thank you!

**Comment by ljfio** [comment]
Can I just say that this issue happens every time that I install Hyper on Windows from the installer?
To fix this I think that you need to use `%LocalAppData%\hyper\Hyper.exe` instead of using the `%UserProfile%` environment variable when creating the shortcuts

**Comment by Stanzilla** [comment]
Hrm, the electron-builder version that Hyper uses is pretty old, `13.6.0` maybe try with the latest? `17.9.0`
