### ISSUE TITLE
Auto-complete breaks

### ISSUE THREAD

**Issue by warpdesign** [zeit/hyper#1155]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 (14986)
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla
## Issue

When using `tab` to complete directories, it seems it gets lost after pressing tab a few times.

When typing `cd at` and tab several types here is what happens:

![hypertermcomplete](https://cloud.githubusercontent.com/assets/199648/21123376/8b1281a0-c0d8-11e6-81b4-78c812006f0a.gif)

If that helps, diretories matching `at` are:
- athenajs
- athenajs-es5
- athenajs-gods

**Comment by dotcypress** [comment]
@warpdesign could open dev tools and copy html code with this issue?

**Comment by ryancole** [comment]
Can confirm happening for me, as well. Same symptoms as shows in the animated GIFs above.

```
Windows 10 (Build 14393)
Hyper version 1.0 (via Windows installer)
```

**Comment by ppot** [comment]
@warpdesign  Go ya. Just tested the app on windows for the first type. Got to see this tab problem.

**Comment by ppot** [comment]
This is related to the space of hterm in the currentRow somehow. I will test it.

**Comment by ryancole** [comment]
@ppot I also just noticed that this happens within applications such as `node`. If I've got the node.js REPL running, and I'm typing in some code, the cursor and text hop from left to right as shown in the GIFs above.

**Comment by ppot** [comment]
@ryancole  On windows/linux or OS X?

**Comment by ryancole** [comment]
@ppot Windows 10 (Build 14393)

**Comment by ryancole** [comment]
![node](https://cloud.githubusercontent.com/assets/484801/21297074/94530a2c-c53e-11e6-9ff7-3965d2040ccb.gif)

Here's a GIF of me just trying to get the issue to appear. On the first and second lines I type in, everything is fine. On the third and fourth lines, I press up arrow to recall the past line and the issue appears. On the third entry, moving the cursor back across the text caused it to get garbled and unreadable. On the fourth entry it simply appeared off to the right, similar to the above GIFs.

**Comment by maetthew** [comment]
FWIW, I'm having this issue also and from what I can tell it seems to have something to do with the pace at which you are tabbing.

If you press slowly, like 0.5-1s between keypresses, it seems to work as normal. But if you speed up, i.e spam the key, or keeping TAB pressed, it seems as if Hyper can't catch the keypresses fast enough and sooner or later it will insert an actual TAB.

**Comment by rbnlffl** [comment]
Same issue. Windows 10, Hyper 1.1.0. I can also reproduce it when tabbing _relatively_ slow.

![sffwf](https://cloud.githubusercontent.com/assets/6851646/22613330/b5686c6c-ea77-11e6-8e60-d399d9c3ac6f.gif)

**Comment by gregorygenova** [comment]
Hi,

I have the same issue on MacOS Sierra 10.12 and latest version of hyper (1.3.3).
For me the issue comes to my zsh theme (hyperzsh).
I remove hyperzsh theme and it's ok now.

Have a nice day.

**Comment by yousefissa** [comment]
I am having the same issue on MacOS Sierra. Has anyone figured out a fix?

**Comment by timothyis** [comment]
Can anyone confirm that this issue is fixed in the most recent release? cc @yousefissa @gregorygenova @warpdesign 🤞

**Comment by yousefissa** [comment]
I have not seen it yet, but I will post back if I do! @timothyis

**Comment by albinekb** [comment]
Thanks! Please re-open if you encounter this in 2.x 👍
