### ISSUE TITLE
PS1="〉" terminal prompt glitches

### ISSUE THREAD

**Issue by folletto** [zeit/hyper#1156]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- macOS 10.12.1
- Hyper.app 1.0.0.1303
- default .hyper.js
- Dev Console error: `__WEBPACK_IMPORTED_MODULE_0_hterm_umdjs__.hterm.TextAttributes.splitWidecharString` 
([full stack screenshot](https://cloud.githubusercontent.com/assets/4389/21123075/573dbc46-c0ce-11e6-9aac-ae9ece9b79fa.png))
- vanilla Hyper

## Issue

When I updated to Hyper 1.0 (from a previous 0.x I can't recall, which worked) the prompt looked off. What's worse, some operations didn't work properly either: 

1. the color of the prompt leaked.
2. preferences didn't open, just duplicated the same content of the original tab and crashed them all if I attempted to close one ([screenshot](https://cloud.githubusercontent.com/assets/4389/21123128/b12572b2-c0ce-11e6-835c-b2d9bd6305f3.png)).
3. CMD+W and CMD+T seem not working / work randomly.

I hunted the issue down, and removing piece by piece every element in my custom PS1 prompt, I identified it breaks when I add this character: `〉`. 

Specifically, the smallest `bash` prompt that breaks is: 

```
PS1="〉"
```

Might be useful:

```
$ echo -n 〉| hexdump
0000000 e2 8c aa                                       
0000003
```

The same happens with:

```
PS1="〉"

$ echo -n 〉| hexdump
0000000 e3 80 89                                       
0000003
```

And other random characters:

```
PS1="、"
PS1="ㄐ"
PS1="㈑"
```

If I change the prompt to anything else, it works. Similarly, if I keep my prompt but I just remove that character, it works again.

Also: I can't copy paste the above PS1 commands into Hyper either: the paste itself "breaks" at the character.

**Comment by dotcypress** [comment]
Hopefully fixed in https://github.com/zeit/hyper/pull/1111

**Comment by dotcypress** [comment]
@folletto could you try build Hyper from [this branch](https://github.com/dotcypress/hyper/tree/unicode-perfomance-fix) and try again?

**Comment by folletto** [comment]
I confirm that branch fixes the issue, but not completely. 

The cursor becomes offset by roughly a single space:

Typing `ll` in Hyper (that `unicode-perfomance-fix` branch):

![screen shot 2016-12-13 at 01 53 48](https://cloud.githubusercontent.com/assets/4389/21124470/15ff574a-c0d7-11e6-8a0f-a06528fdf8cc.png)

Typing `ll` in Hyper 1.0 (with the bug mentioned here):

![screen shot 2016-12-13 at 01 55 37](https://cloud.githubusercontent.com/assets/4389/21124500/43957f68-c0d7-11e6-82bf-54ca9cf732c0.png)

Typing `ll` in Hyper 1.0 (with a `PS1="$ "` prompt):

![screen shot 2016-12-13 at 01 57 20](https://cloud.githubusercontent.com/assets/4389/21124555/916baa5a-c0d7-11e6-9705-30c1a72b803f.png)

Typing `ll` in Terminal:  

![screen shot 2016-12-13 at 01 54 04](https://cloud.githubusercontent.com/assets/4389/21124485/32862a1a-c0d7-11e6-9af5-1758d1ba4660.png)

**Comment by dotcypress** [comment]
@folletto but this space provided by `PS1="〉"`, right?

**Comment by adityavm** [comment]
not sure if this is related, but my prompt is:

```
%{$fg_bold[blue]%}〉%{$fg_no_bold[white]%}%p%{%F{247}%}%c ·%{$reset_color%}
```

and my hyper is a blank window

![screen shot 2016-12-13 at 9 16 27 am](https://cloud.githubusercontent.com/assets/80849/21126882/0ea0707c-c115-11e6-8dbc-0316f27e0b18.png)

**Comment by folletto** [comment]
With Hyper 1.0.1 (that had https://github.com/zeit/hyper/pull/1111 merged) now the prompt has the visual glitch of the space, but at least doesn't break functionality (at least to the extent I tested it).

Current 1.0.1 (notice the misplaced space):

![cap-](https://cloud.githubusercontent.com/assets/4389/21582381/fadac49c-d04c-11e6-9878-f060a4358aaf.gif)

**Comment by cirqueit** [comment]
Want hyper to be my daily driver, but the cursor's off-by-one position is really annoying. 
Happening on Ubunutu, using bash and running tmux.

**Comment by storvik** [comment]
Having the same problem as @folletto with 1.0.1 when spawning a tmux session. Invoking the tmux prompt (C-b :) fixes all preceding lines (shifting them one character to the right again), but when entering a new command it's back to being off to the left by one. Using zsh and powerlevel9k. 

<img width="285" alt="screen shot 2017-01-03 at 07 19 39" src="https://cloud.githubusercontent.com/assets/3438604/21601074/e20b5a46-d185-11e6-8037-96df627c1771.png">

All space between left and right prompt is also removed. Everything works as expected when not in a tmux session.

<img width="333" alt="screen shot 2017-01-03 at 07 28 54" src="https://cloud.githubusercontent.com/assets/3438604/21601121/9141e4d0-d186-11e6-9fb0-9756795f7149.png">

Icon bug is likely related to #1327

**Comment by jrop** [comment]
I don't know if this pertains to this issue or not, but I am getting an out-of-place cursor when updating to the latest Hyper (1.1.0.1408):

![gif](http://i.imgur.com/kRKwVqc.gif)

(sorry for the slow replay...I don't know why it plays back so slowly)

**Comment by jrop** [comment]
#1332 seems to be related to this.  But there seems to be something more fundamentally wrong:

My PS1 looks like this: `"%B%F{green}~%f %F{cyan}λ%f%b "`

Note that the %b (&lt;/bold>) occurs **before** the trailing space.

When running outside of TMUX, the generated HTML is:

```html
<x-row><span style="color: rgb(0, 186, 19); font-weight: bold;">~</span><span style="font-weight: bold;"> </span><span class=" unicode-node" style="color: rgb(0, 181, 189); font-weight: bold;">λ</span> <span style="color: rgb(239, 41, 41); font-weight: bold;">asdf</span></x-row>
```

However when running inside TMUX, the generated HTML is instead:

```html
<x-row><span style="color: rgb(152, 195, 121); font-weight: bold;">~</span><span style="font-weight: bold;"> </span><span class=" unicode-node" style="color: rgb(86, 182, 194); font-weight: bold;">λ</span></x-row>
```

...until I type a character, it becomes:

```html
<x-row><span style="color: rgb(152, 195, 121); font-weight: bold;">~</span><span style="font-weight: bold;"> </span><span class=" unicode-node" style="color: rgb(86, 182, 194); font-weight: bold;">λ </span><span style="color: rgb(224, 108, 117); font-weight: bold;">asdf</span>         </x-row>
```

Note that it puts the space **within** the bold span with the λ character, which is wrong.  According to my PS1 string, the space occurs after the bold ends.

Another note, even if the string was in the bold markup, this problem would be fixed if #1332 were fixed.

**Comment by adworacz** [comment]
Oh thank god, I'm not the only one. I'm using the latest (1.2.1.1527) and experiencing this issue when I use TMUX. It's really quite infuriating and works just fine in iTerm.

**Comment by adworacz** [comment]
This is still occurring with 1.3.1. In fact, tmux use in hyper seems quite broken as even my status bar at the bottom is rending oddly.

**Comment by jrop** [comment]
@adworacz I've sadly had to stop using hyper altogether.  I am keeping an eye on this issue, however, hoping that the devs fix this!  From what I understand, once they switch to xterm.js, this might fix itself (#1275).

**Comment by adworacz** [comment]
@jrop I have to agree. I'm continuing to use iTerm for the time being, as I need tmux support in order to work properly.

Thank you for pointing out the potential migration to xterm.js, I'll be sure to track it.

**Comment by hugomd** [comment]
I also have the same issue

**Comment by jrop** [comment]
@adworacz My specific issue is gone in [version 1.3.3](https://github.com/zeit/hyper/releases/tag/1.3.3).

**Comment by folletto** [comment]
Thanks for the update, I checked: the issue is still present in v1.3.3.

**Comment by adworacz** [comment]
I can't replicate my issue on 1.3.3.

At least, not yet. Will keep experimenting, but thank you for fixing the core issue.

**Comment by MelkorNemesis** [comment]
I still keep getting this error on 1.3.3.

**Comment by ultraN** [comment]
I'm getting the same error in 2.0.0 ...

**Comment by albinekb** [comment]
Please open a new issue for 2.0 @ultraN
