### ISSUE TITLE
Terminal becomes non-responsive

### ISSUE THREAD

**Issue by NileshPS** [zeit/hyper#1157]
Executing long running programs like find, locate etc seem to  hang the terminal window. Meta function keys like Ctrl-c, Ctrl-X also stopped working. Platform is linux mitn 18 sarah.

**Comment by perry-mitchell** [comment]
I also get this issue, but it's not after just long-running processes. If I leave my terminal open (idle) for a long period, and then try to <kbd>Ctrl</kbd>+<kbd>t</kbd> to open a new tab, Hyper **freezes** completely, and won't even respond to the close button. I have to then use `xkill` to close the process.

I'm running vanilla Hyper, 1.0.0, on Ubuntu 16.04..

**Comment by perry-mitchell** [comment]
Seems it only takes 1 evening of leaving it running to lock the terminal:

![image](https://cloud.githubusercontent.com/assets/3869469/21340614/719fa442-c690-11e6-97d6-96ef0d045b8f.png)

(running webpack in one, nothing in the other). Lag occurs on my macbook pro, but it completely dies on Ubuntu.

**Comment by remy** [comment]
I just saw the same thing. I tried `imgcat 1mbfile.png` and it completely hung for about 30-45 seconds:

![https://cloudup.com/c_Y1Bhpo_Sa](https://cloudup.com/c_Y1Bhpo_Sa)

I tried the same thing with `cat 1mbfile.png` and it hung in the same way, making hyper completely unresponsive (i.e. can't event `ctrl+c` the session).

**Comment by yousefissa** [comment]
Has anyone found a solution? mine freezes when I have a ssh instance up performing actions.

**Comment by torch2424** [comment]
@yousefissa Same here, my ssh sessions often times get frozen.

**Comment by JoaoFOliveira** [comment]
Here too. On OSX Terminal, you terminate the remote connection via "~."

Doesn't seem to work on Hyper, and I have to restart the whole thing.

**Comment by kshitijb** [comment]
Mine hangs randomly. And I have to close the app and restart all the processes running in all the tabs. It seems like a very common issue. I guess I will have to stick to mac terminal until this is fixed.

**Comment by Gimi** [comment]
I found that Hyper will hang once run a long run command in it and switch to other apps and switch back to it. This is very annoying.

---
OS version and name: macOS 10.11.6
Hyper.app version: 1.3.3.1754

**Comment by divyanshu013** [comment]
Can confirm for v2.1.1 too on Fedora 27 x64

Seems to happen more often if I use multiple tabs, especially if some servers are running in each tab. After it becomes unresponsive have to run `pkill hyper` to close hyper

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by ankur2002** [comment]
Also I think one alternative would be to just reload the terminal. It still retains all the tabs and your session history as well.
