### ISSUE TITLE
Deleting emojis on command line adds �

### ISSUE THREAD

**Issue by JamsheedMistri** [zeit/hyper#1160]
- **OS version and name**: MacOS 10.12 Sierra
- **Hyper.app version**: 1.0.0 (the latest)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/MistriHD/d87b27bb9ae5e63d0b636d836858a5e8
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: I believe this can be reproduced in vanilla.
## Issue
The 1.0.0 update supports emojis, so I tried it out. I pasted the 😂 emoji in, and it worked. Then I hit the "backspace" key, and it replaced 😂 with �. I can't delete � unless I do ^C.

**Comment by dotcypress** [comment]
Hey @MistriHD 
Yep, we still have this weird stuff.

We will patch `hterm.Screen.prototype.deleteChars` in future. 😉
