### ISSUE TITLE
Current running process doesn't appear in tab title

### ISSUE THREAD

**Issue by smably** [zeit/hyper#1162]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: vanilla config
- **Relevent information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla.

## Issue
I expected the process name to show in the tab title as it does in most other terminals. Instead, it's always "Shell" unless explicitly set. The current behaviour seems to have been introduced in this PR: #892.

I'm not sure whether this is the intended behaviour (#49 seems to suggest that it is), but regardless, it's an unexpected omission of a feature that seems to be standard among other terminal apps. I'm used to being able to figure out which is my vim tab just by looking at the tab bar!

**Comment by audunolsen** [comment]
I too experience this exact issue.

**Comment by ppot** [comment]
@smably Can you tell me if vim is on the left side of text?    `vim npm-debug.log@ppot` is what i get.

**Comment by audunolsen** [comment]
There's a discussion on a related topic here where I've found a workaround: [hyper/issues/1188](https://github.com/zeit/hyper/issues/1188#issuecomment-267203900)

It should be applicable to your use case.
![screenshot 2016-12-15 12 26 57](https://cloud.githubusercontent.com/assets/16224137/21222399/f8765a4c-c2c1-11e6-8ca0-36b61aeb2f64.png)

**Comment by zpnk** [comment]
I'm seeing this too. Hyper 1.0.0 on Yosemite and the tabs just display "Shell".

@audunolsen The workaround you posted in #1188 does work for me - thanks for that. Just sucks to have to add a bunch of code to the profile to get a necessary feature to work.

It seems to me like #892 should have fixed this?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
