### ISSUE TITLE
Different width between braces and character with font hermit

### ISSUE THREAD

**Issue by nasyxx** [zeit/hyper#1163]
## Issue

![screen shot 2016-12-13 at 1 17 36 pm](https://cloud.githubusercontent.com/assets/5007613/21128553/ffb12526-c136-11e6-9737-e00bcd00e66f.png)

I really love this font [hermit](https://github.com/pcaro90/hermit), hope someone can fix it.

my [.hyper.js](https://gist.github.com/nasyxx/4136c579eeae66e699cb5012d3932b4c)

**Comment by dotcypress** [comment]
Seems `hermit` is broken 😢 

![hermit](https://cloud.githubusercontent.com/assets/1333916/21129166/d1a3bf68-c0b4-11e6-8a96-8f8763140d24.gif)
