### ISSUE TITLE
Error updating plugins

### ISSUE THREAD

**Issue by urkopineda** [zeit/hyper#1166]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1 x64, v6.3.9600
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [LINK](https://gist.github.com/urkopineda/7e48770b52b0fa18897237053dcde730)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I have an error at start, says that plugins cannot be updated, see log (and the log isn't where is pointing to, '~\.hyper-plugins\npm-debug.log'. I can reproduce the bug not only restarting the app but going to menu, 'Plugins' -> 'Update All Now'.

In my particular case, I have a Windows 8.1 **without administrator rights** at work so I think that limitation is causing the problem.

And, of course, amazing app, it's superb!

**Comment by sallar** [comment]
I have the same issue. Everything is broken on all my Mac machines.

**Comment by jonathandelgado** [comment]
Same issue on Windows 10 with admin rights, I'll try to do some more digging.

**Comment by jonathandelgado** [comment]
Found the problem.

I was getting the error:
```
{ Error: Command failed: npm prune && npm install --production
bash: /s: No such file or directory

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Looking into the `install` function, I noticed the path was correct, but the shell was interpreting it incorrectly. Commenting out the `shell` argument resolved the issue ([line 243 currently](https://github.com/zeit/hyper/blob/a5b457ed13d649be41255310f08f59ac3464769b/app/plugins.js#L242)). I had my shell set to `bash.exe`, but the default was also causing issues.

Not going to throw in a PR because i'm not sure how modifying the shell will effect other operating systems, but hopefully this comment helps.

**Comment by sallar** [comment]
@jonathandelgado I fixed the problem exactly like that but I wasnt sure how that was related so I didnt say anything. mine was set to fish

**Comment by AndrewIngram** [comment]
Yes, i'm using fish and am having this issue

**Comment by OJFord** [comment]
> I have searched the issues of this repo and believe that this is not a duplicate

Did you really? q.v. #312

**Comment by jfrolich** [comment]
Same issue here using fish

**Comment by ryanpcmcquen** [comment]
This looks like a duplicate of:

https://github.com/zeit/hyper/issues/312
https://github.com/zeit/hyper/issues/443

**Comment by urkopineda** [comment]
Closing in favor of #312

**Comment by ifyour** [comment]
reinstall and delete profiles ( ~/.hyper.js  and   .hyper_plugins folder ).

it's work for me.

```
- windows 7
- hyper 2.0
```
