### ISSUE TITLE
Accent marks as unknown character

### ISSUE THREAD

**Issue by urkopineda** [zeit/hyper#1167]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1 x64, v6.3.9600
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [LINK](https://gist.github.com/urkopineda/7e48770b52b0fa18897237053dcde730)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I have an issue with the accent marks in Spanish, they appear as a unknown character (It seems to be related to encoding) I leave a screenshot, thanks!

![captura](https://cloud.githubusercontent.com/assets/9933709/21131451/0adb807c-c10f-11e6-8403-11661309803c.PNG)

**Comment by dotcypress** [comment]
@urkopineda could you paste some Spanish characters to comment, i'll try on my branch

**Comment by urkopineda** [comment]
@dotcypress, here are:
- á é í ó ú
- ñ ç

That character from screenshot should be 'Versi**ó**n'. Thanks!

**Comment by Nickdouille** [comment]
Hello there.
Same here in french : 
```
Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits r�serv�s.
```

é, à, è, ù, ç, ê

**Comment by martin-damien** [comment]
Same here in french, under MAC OS X (also under Linux)

![capture d ecran 2016-12-19 a 16 13 20](https://cloud.githubusercontent.com/assets/295478/21317614/29cc40b0-c606-11e6-910f-1b0d5dcb5c13.png)

**Comment by apeyroux** [comment]
Same here in french under Ubuntu
![capture du 2017-01-17 19-47-02](https://cloud.githubusercontent.com/assets/1078530/22034832/e5ab06d8-dced-11e6-901a-bcd316e10c18.png)

**Comment by matheuss** [comment]
I can't reproduce this 🤔 Accented chars works fine for me on macOS, Linux and Windows 😥

**Comment by apeyroux** [comment]
```
alex@laptop:~$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=fr.UTF-8
LANGUAGE=fr_FR
LC_CTYPE="fr.UTF-8"
LC_NUMERIC="fr.UTF-8"
LC_TIME="fr.UTF-8"
LC_COLLATE="fr.UTF-8"
LC_MONETARY="fr.UTF-8"
LC_MESSAGES="fr.UTF-8"
LC_PAPER="fr.UTF-8"
LC_NAME="fr.UTF-8"
LC_ADDRESS="fr.UTF-8"
LC_TELEPHONE="fr.UTF-8"
LC_MEASUREMENT="fr.UTF-8"
LC_IDENTIFICATION="fr.UTF-8"
LC_ALL=
```

**Comment by ezequieltejada** [comment]
Same thing in my computer:

ezequiel@ezequielkit ~ $ uname -a
Linux ezequielkit 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

ezequiel@ezequielkit ~ $ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=es_419.UTF-8
LANGUAGE=
LC_CTYPE="es_419.UTF-8"
LC_NUMERIC=es_AR.UTF-8
LC_TIME=es_AR.UTF-8
LC_COLLATE="es_419.UTF-8"
LC_MONETARY=es_AR.UTF-8
LC_MESSAGES="es_419.UTF-8"
LC_PAPER=es_AR.UTF-8
LC_NAME=es_AR.UTF-8
LC_ADDRESS=es_AR.UTF-8
LC_TELEPHONE=es_AR.UTF-8
LC_MEASUREMENT=es_AR.UTF-8
LC_IDENTIFICATION=es_AR.UTF-8
LC_ALL=

**Comment by Camotubi** [comment]
Im also having this issue.
OS: Linux mint 18.1 - Mate
![pantallazo-2017-02-14 02-02-38](https://cloud.githubusercontent.com/assets/4031324/22918741/c42ea6d2-f259-11e6-95bb-a17325967dbc.png)
Imágenes, Música. Any character with a an Accent  isnt being displayed.

**Comment by rbe1733** [comment]
Same issue on MacOS X Sierra 10.12.3

export LANG=fr_FR-UTF-8 make the character with an accent looks without instead of the ??.
é becomes e, à becomes a, ...

I can't write é or any other accent in Hyper.
Tried to change the font but no effect.

**Comment by nacimgoura** [comment]
Same issue with accent.
No solution ?

**Comment by aminnairi** [comment]
Hyper 1.4.8 (stable) on Windows 10 (1709) w/ Git Bash.

Solved by adding the `env.LANG` property with value `fr_FR.UTF-8`.

```javascript
    // for environment variables
    env: {
        TERM: 'msys',
        LANG: "fr_FR.UTF-8"
    },
```

Tested in `vimtutor` which displays diacritic french characters properly now.

![vimtutor](https://user-images.githubusercontent.com/18418459/32491336-a2a13d98-c3b6-11e7-9396-38034d5d92ae.png)

**Comment by rbe1733** [comment]
Works also on MacOS High Sierra.
@aminnairi Thanks for the tip

But do not configure TERM to msys. Not recognized on MacOS X.

**Comment by aminnairi** [comment]
This is a specific environment variable for Windows. Don't pay attention to that if you are on GNU/Linux or Mac OSX or UNIX.
