### ISSUE TITLE
No Menu on Debian (Gnome Shell)

### ISSUE THREAD

**Issue by tblaisot** [zeit/hyper#1168]
- **OS version and name**: Debian 8.6
- **Hyper.app version**: 1.0.0 (from .deb)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: fresh install
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Nothing special
- **The issue is reproducible in vanilla Hyper.app**: fresh install
## Issue

Looking at picture from the new version it seems that I should have a hamburger menu on the left of the toolbar.
I can use Ctrl+T shorcut to open tabs but I don't have any menu for others actions.

![bug](https://cloud.githubusercontent.com/assets/3236741/21133470/38e5e7c8-c119-11e6-9548-6a5339c632a1.png)

The prompt is broken due to fresh install without fonts etc.. for demo

**Comment by lukasredynk** [comment]
Same for Fedora 25 on Gnome3+X11, no menu. I've also were unable to use "hamburger menu".

**Comment by Specro** [comment]
Did you set `showHamburgerMenu: true` in the config? Related #1118

**Comment by tblaisot** [comment]
After a little bug which make me lose all my config and my installed plugin it worked...
Thanks
