### ISSUE TITLE
version 1.0.0 (and all previous versions) hangs when running tree command from /

### ISSUE THREAD

**Issue by kajalsinha** [zeit/hyper#1169]
Not as fast as native terminal in ubuntu/or any other *nix platform. Try using tree command from / , it hangs and makes native terminal Laugh on hyper slowness.

**Comment by iamstarkov** [comment]
> Not as fast as native terminal in ubuntu/or any other *nix platform.

Of course, its not.

> it hangs and makes native terminal Laugh on hyper slowness.

Can i ask you to reword it in more respective way?

**Comment by iamstarkov** [comment]
> Try using tree command from / 

on a kind of serious note, can you describe your machine spec and node, npm, hyper versions

**Comment by nbolten** [comment]
I think this is related to issue #1157 (and likely other similar issues, I'm just having trouble finding them).

The issue: any command that produces a lot of text to the terminal (stdout, etc) can cause the terminal to become unresponsive. There are two different 'unresponsive' states:

* If I hit Ctrl + c fast enough (to kill the process mid-stream), I can still scroll through the text output, but hotkeys have no apparent effect - Ctrl + w, Ctrl + t, do nothing. Attempting to execute subsequent commands also has no apparent effect - `clear` and `exit` do nothing.

* If I don't hit Ctrl + c for a very large amount of output (like `find /`), the terminal freezes entirely. Scrolling is not possible and animations freeze (I turned on `hyperpower` to test).

To reproduce: 
1. Open hyper (of course)
2. Run any command that produces a lot of stdout, for example `find /`.
3. `hyper` quickly becomes unresponsive.

I'm running on ubuntu gnome 16.04.1, so this may be a linux-specific issue. I haven't looked at the code yet to see why this might be happening, but it definitely seems like an issue related to rendering - trying to render too much text all at once in a single view.

This is a breaking-level issue, as it means the terminal can become unresponsive while executing common commands. For example, if I am using `hyper` to remote into a server with `ssh` and run `find node_modules` in a node program with lots of dependencies, my entire session will be lost. It's currently preventing me from using `hyper` at all.

Thanks for all your hard work! I'm happy to provide tests and more details.

**Comment by cHolzberger** [comment]
Same Problem here on macOS,
Machine 6x 3,46 GHz, 64 GB RAM  
find / kills hyper. 

Node Version: v7.2.1
NPM Version: 3.10.9
Hyper Version: 1.0.0

**Comment by deitch** [comment]
Same problem here on macOS. I trigger it when I accidentally dump a binary file to stdout, e.g. `cat somefile_I_didnt_know_was_binary`

**Comment by catskull** [comment]
Same problem: OSX 10.12.3, hyper 1.3.1.

**Comment by petermbenjamin** [comment]
I can replicate this as well with Hyper 1.3.1 on two platforms:
- OSX 10.12.3 (15" MBPr 2015, 512GB HDD, 16GB RAM) 
- Ubuntu 17.04 (ASUS Q500a 4th-gen quad-core i7, 512 GB HDD, 8GB RAM)

Steps:
1. Open Hyper
1. `curl https://api.github.com/search/repositories?q=javascript`

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
