### ISSUE TITLE
Weird characters when running ZSH on Hyper

### ISSUE THREAD

**Issue by enriquemorenotent** [zeit/hyper#1171]
I just installed Hyper 1.0. When I open Hyper and activate zsh as my shell, I get this weird characters.

If I open zsh in another terminal, for instance Terminator, they all look alright.

![screenshot from 2016-12-13 10-19-46](https://cloud.githubusercontent.com/assets/368842/21134407/094f7b8c-c11e-11e6-9245-b748c1aef81d.png)

**Comment by albinekb** [comment]
Looks like you need to set your `fontFamily` to a font that's [powerline-patched](https://github.com/powerline/fonts)
here is info on how to set your `fontFamily` https://hyper.is/#cfg

**Comment by enriquemorenotent** [comment]
The solution to my problem was to add this line on the settings:
    fontFamily: '"Droid Sans Mono for powerline", Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',

I am not sure if this had an effect on it working or not, but before doing that I tried other things like installing this fonts (https://github.com/powerline/fonts) or running `sudo apt-get install fonts-powerline`

**Comment by L-A** [comment]
For posterity, here are the necessary steps:

What you need is indeed any Powerline-compatible font. It must be installed (any way you like, Font Book is fine).

Then it must be the active font-face in Hyper.

If the font is named "Droid Sans Mono For Powerline", it has to be there completely, since "for powerline" is part of the name, not a suffix of sorts.

Your setting is 👍 

That's it!

**Comment by enriquemorenotent** [comment]
What is weird is that when I set the font to "Ubuntu Mono" in the default system terminal, the characters look fine, but when I set it on Hyper, they do not.

I am not sure if there is some weird wiring going on under the hood, but the I have never had this trouble with any other terminal (I have tried "Terminator" and "Cool Retro Term"). They all could show the characters without any trouble.

Maybe Hyper needs to do some extra automatic configuration?

**Comment by softmonkeyjapan** [comment]
Same problem here. I'm using the `Menlo Regular for Powerline` font on my iTerm2 with zsh and it display correctly:

![screen shot 2016-12-15 at 5 30 59 am](https://cloud.githubusercontent.com/assets/2499912/21195317/6c0d5aea-c287-11e6-9939-ff0611b638b6.png)

I have change the font on `~/.hyper.js` configuration file:
![screen shot 2016-12-15 at 5 32 56 am](https://cloud.githubusercontent.com/assets/2499912/21195357/94e169e8-c287-11e6-8a2e-d1fcc9d72801.png)

But the display is still broken:
![screen shot 2016-12-15 at 5 34 09 am](https://cloud.githubusercontent.com/assets/2499912/21195399/be36f4e8-c287-11e6-9a07-408526aff6c2.png)

Will try dig into the problem a bit more later and see how we can fix that.

**Comment by softmonkeyjapan** [comment]
Ok so I just changed the font to another Powerline font (I'm using `Inconsolata-g for Powerline` instead of `Menlo Regular for Powerline`) and seems to work fine now:
![screen shot 2016-12-15 at 5 45 39 am](https://cloud.githubusercontent.com/assets/2499912/21195781/598d3abe-c289-11e6-9fc4-9e831e02dc84.png)

**Comment by L-A** [comment]
@softmonkeyjapan What happens if you name it "Menlo for Powerline"?

[The regular weight doesn't have "Regular" in its name](https://github.com/abertsch/Menlo-for-Powerline).

**Comment by softmonkeyjapan** [comment]
Yep indeed it works fine. The `Regular` needed to be removed. It works fine thanks for the feedback.

**Comment by enriquemorenotent** [comment]
For me "Menlo for Powerline" does not give me any result :/

**Comment by lalabuy948** [comment]
Well, I'm having same issue. I tried to install other fonts, same result.

![screen shot 2018-08-05 at 4 42 41 pm](https://user-images.githubusercontent.com/24271777/43687027-0ab3c656-98cf-11e8-9801-c5ae571f7652.png)
