### ISSUE TITLE
Cannot open dev tools + make bg transparent

### ISSUE THREAD

**Issue by Reda-bx** [zeit/hyper#1173]
- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: Hyper 1.0.0
## Issue
1 - When I try to open dev tools it only show a white screen
2 - Cannot make bg transparent

![screenshot from 2016-12-13 10-30-54](https://cloud.githubusercontent.com/assets/12598261/21136934/98c940d0-c11f-11e6-8d10-3322d08f9088.png)

**Comment by colepeters** [comment]
Having this issue as well. I also found that if you detach the dev tools from the terminal window, things go back to normal in the terminal view (background etc).

**Comment by jsangilve** [comment]
I'm also having this problem in Debian Stretch (testing)

**Comment by L-A** [comment]
@CodeTheory I suggest marking this as `upstream`. I've seen this before in other apps, AFAIK it's an Electron / Chromium thing.

The devtools can't be **in** a transparent window. Detaching them will allow the window to render properly.

**Comment by CodeTheory** [comment]
This actually makes sense @L-A. We've had the same problem with Kap.
@matheuss Could we detach the devtools window if the window is transparent? Or by default?

**Comment by matheuss** [comment]
@CodeTheory done https://github.com/zeit/hyper/commit/a0a84841580c78682cc34001ce5c4df285e857ed

**Comment by Reda-bx** [comment]
okay dev tools is fixed, but the transparent background still not working on ubuntu
