### ISSUE TITLE
Terminal does not clear in all cases

### ISSUE THREAD

**Issue by JoaoFOliveira** [zeit/hyper#1177]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX Sierra
- **Hyper.app version**: 1.0.0.1303
- **The issue is reproducible in vanilla Hyper.app**: ls; man zip; ls; vtop;

## Issue
Sometimes the screen clears for the cursor to get back on top, and in case of vtop, the cursor returns to the beginning of the terminal but it isn't cleared.

Example:

![vtop](https://cloud.githubusercontent.com/assets/2836017/21143264/d5c305b6-c13d-11e6-8240-5c16bdf63034.gif)

**Comment by ppot** [comment]
@JoaoFOliveira Can you and list of plugins. And test without the plugins ?

**Comment by JoaoFOliveira** [comment]
Only had the 'hyperline' plugin activated. Tested without it, same results.
