### ISSUE TITLE
Change realod accelerator

### ISSUE THREAD

**Issue by brunoqueiros** [zeit/hyper#1178]
- **OS version and name**: Ubuntu 14.04 LTS 64-bit
- **Hyper.app version**: 1.0.0

## Issue
Could we change the reload accelerator to something different than `Ctrl+R`? Because it's overwriting the reverse-i-search bash feature.

[https://www.gnu.org/software/bash/manual/html_node/Commands-For-History.html](https://www.gnu.org/software/bash/manual/html_node/Commands-For-History.html)

**Comment by jokeyrhyme** [comment]
I've been using Hyper on macOS, so I didn't notice this at first. Command+R is the reload keyboard shortcut on macOS. But this is definitely a conflict on Windows and Linux.

I use Hyper on ArchLinux with Gnome, and there doesn't seem to be a menu or anything. Maybe we need to be sure there is another means of reload before unbinding / changing the keyboard shortcut?

**Comment by Rainbowlemon** [comment]
+1, have just found this app and can't really use it without reverse-i-search!

**Comment by materemias** [comment]
actually makes it unusable on my linux desktop while i love it on my mac

**Comment by ppot** [comment]
close in #1876
