### ISSUE TITLE
The Services menu is empty

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#118]
Ubuntu 16.04

![image](https://cloud.githubusercontent.com/assets/2193314/16889546/1f731da4-4a9c-11e6-85f8-a3347362db8b.png)

**Comment by micrub** [comment]
Same in Ubuntu 14.04.

**Comment by micrub** [comment]
Seem that the is nothing implemented yet, just an a place holder hot menu item: 
https://github.com/zeit/hyperterm/search?utf8=%E2%9C%93&q=services

**Comment by matheuss** [comment]
What is supposed to be there?

**Comment by chabou** [comment]
Services menu is not empty if you have text selected. (Maybe something has been fixed)
Same services than iTerm2
