### ISSUE TITLE
Windows Git Bash cursor position / character width issue

### ISSUE THREAD

**Issue by mtwalsh** [zeit/hyper#1180]
I type some text and then use the arrow keys to go back a few characters and then when I advance it re-paints the text but a few characters forward.  I'm also not able to bring the cursor right back to the start of the text:

![weird](https://cloud.githubusercontent.com/assets/1246553/21151764/8d282bf6-c15b-11e6-9754-dcd3fab7ac47.gif)

Hyper 1.0.0
Electron 1.4.7
win32 x64 10.0.14393
Shell: Git Bash v2.11.0

**Comment by jonathandelgado** [comment]
Related to #1174

**Comment by mtwalsh** [comment]
I'm not getting the same issue when using the Windows Command Prompt, just when using Git Bash as the shell.

**Comment by dotcypress** [comment]
@mtwalsh could you try to reproduce on [this branch](https://github.com/dotcypress/hyper/tree/unicode-perfomance-fix)?

I don't have Windows PC to test :(

**Comment by jonathandelgado** [comment]
@dotcypress Just tried it with that branch, can still reproduce it.

This might be an upstream issue with `pty.js`. I mentioned in #1174 that this problems occurs with the VSCode integrated terminal as well.

**Comment by mtwalsh** [comment]
Yes, same issue for me on that branch I'm afraid.

**Comment by mtwalsh** [comment]
I'm pleased to report this has been fixed in v1.2.1.

Thank you!
