### ISSUE TITLE
Alt-backspace deletes two consecutive words

### ISSUE THREAD

**Issue by liancheng** [zeit/hyper#1183]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X Yosimite 10.10.5
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/liancheng/93972ca54deb3ae582a830cf5b994e82
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue

Set `config.modifierKeys.altIsMeta` to `true`, then type the following contents in ZSH (`_` is the cursor):

```
$ a b c_
```

Now press `alt-backspace`, and both `b` and `c` are deleted:

```
$ a _
```

The same thing also happens to Cloud 9 terminal, so I'd assume that this is something related to some underlying framework shared by both projects.

**Comment by ppot** [comment]
It does also on cmd+backspace

**Comment by tibotiber** [comment]
This is the same as #1361 which provides more details and other related issues.

**Comment by timothyis** [comment]
I think this should be fixed now! Please let us know if it's not
