### ISSUE TITLE
Question about Process

### ISSUE THREAD

**Issue by obrassard** [zeit/hyper#1184]
On mac, I noticed that there was a lot of "Hyper Helper" processes running with different PID and I think it have an impact on battery life. I don't know if it is normal...
Look at the following screen shot of Activity Monitor were there are more than 10 process all called "hyper helper":
<img width="977" alt="screenshot" src="https://cloud.githubusercontent.com/assets/17227551/21158087/d9618db2-c149-11e6-9425-ac56f03ed373.png">
Thanks!
-

Hyper 1.0.0
Electron 1.4.7
darwin x64 16.1.0

**Comment by c0b41** [comment]
Dups #474

**Comment by ppot** [comment]
Yes Dups
