### ISSUE TITLE
Shortcuts break when using Alt key as Meta

### ISSUE THREAD

**Issue by anmoljagetia** [zeit/hyper#1185]
- **OS version and name**: MacOS Sierra
- **Hyper.app version**: 1.0.0

I am using the `"modifierKeys" : { altIsMeta: true }` property in my config, and the keyboard shortcuts to switch between panes (or any other that requires the ALT key stop working. 

Also, is there anyway in which I can change the default key-bindings?

**Comment by ppot** [comment]
Hey! Sorry for the delay. Found your issue while adding closing issue. This will be fixed in #1509. Thanks for using Hyper!

**Comment by ppot** [comment]
close in #1876
