### ISSUE TITLE
Add ability to toggle pane fullscreen

### ISSUE THREAD

**Issue by fixe** [zeit/hyper#1187]
iTerm allows this when using command-shift-enter. Probably the thing I miss the most.

**Comment by ppot** [comment]
@fixe You sure it's not `cmd+enter` ?

**Comment by evanxd** [comment]
@ppot , That is `cmd+enter`on iTerm.

**Comment by alexfedoseev** [comment]
I'm trying to implement it via plugin, but looks like I can't do anything w/ panes via public apis. I'll try to implement it in the core.

**Comment by alexfedoseev** [comment]
https://github.com/zeit/hyper/pull/1326

**Comment by ppot** [comment]
See https://github.com/chabou/hyper-pane
