### ISSUE TITLE
Background Transparency with BLUR

### ISSUE THREAD

**Issue by omarojo** [zeit/hyper#1189]
- **OS version and name**:  OSX 10.11.6
- **Hyper.app version**: 1.0.0.1303

## Issue

How can I get that transparent blur effect on the background color, that I see in the screenshot you posted in Product Hunt, specifically in the OSX version. 

https://www.producthunt.com/posts/hyper-1-0-0

**Comment by dotcypress** [comment]
@omarojo check it out: https://github.com/matheuss/hyper-simple-vibrancy

**Comment by omarojo** [comment]
nice ! :)

**Comment by dotcypress** [comment]
@omarojo maybe you will be interested in material hyper theme 😉 

<img width="640" alt="hyper-material" src="https://cloud.githubusercontent.com/assets/1333916/21167023/63bc12ac-c15e-11e6-8694-c3a1b5c4afa6.png">


https://github.com/dotcypress/hyper-material

**Comment by linonetwo** [comment]
How can I  do this on Windows?

**Comment by ppot** [comment]
@linonetwo You can't this is vibrancy. Strictly internal of OSX. Not of hyper

**Comment by ppot** [comment]
@omarojo Closing since you got the answer to your question.

**Comment by Azzhoe** [comment]
@dotcypress I am trying to get the blurry background affect. I am on Mac OS High Sierra with the latest Canary build and also have Material Theme installed. However I cannot install the Hyper-simple-vibrancy-plug. I'm getting an error. This is what I have in my hyper.js config file...

`  //plugins: [],
    plugins: [
    'hyper-material'
    'hyper-simple-vibrancy'
  ],`

**Comment by keeganjk** [comment]
Is this possible on Linux?

**Comment by linonetwo** [comment]
@keeganjk  Seems its using MAC OS' feature.

**Comment by SpaceHexagon** [comment]
What if this sort of approach was used? https://github.com/arkenthera/electron-vibrancy
