### ISSUE TITLE
win10 error

### ISSUE THREAD

**Issue by suhaotian** [zeit/hyper#1190]
![image](https://cloud.githubusercontent.com/assets/6512574/21166164/c105af9c-c1de-11e6-8be0-de92a6624f1f.png)

-
![image](https://cloud.githubusercontent.com/assets/6512574/21166198/f4168604-c1de-11e6-8388-a4e43b9b4fcc.png)

Hyper 1.0.0
Electron 1.4.7
win32 x64 10.0.14965

**Comment by matheuss** [comment]
@suhaotian any steps to reproduce?

**Comment by chabou** [comment]
@suhaotian and can you try to reproduce with 1.1.0 version

**Comment by suhaotian** [comment]
I'm sorry. Now I don't develop in win platform
