### ISSUE TITLE
Hamburguer Menu is not showing

### ISSUE THREAD

**Issue by juangl** [zeit/hyper#1192]
## Issue

![screenshot from 2016-12-13 19-56-23](https://cloud.githubusercontent.com/assets/1887029/21167299/2f9690e8-c171-11e6-91df-16804259124d.png)

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Archlinux with GNOME shell
- **Hyper.app version**: 1.0.0

- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/juangl/74346eb89777775d4f841149ef16b20f

- **Relevent information from devtools** :
 
I get the next warning:
`Unknown OSC code: "1"`

- **The issue is reproducible in vanilla Hyper.app**:

**Comment by CodeTheory** [comment]
Hi there. The hamburger menu is hidden by default on linux. You can enable it in your `.hyper.js` file here: https://gist.github.com/juangl/74346eb89777775d4f841149ef16b20f#file-hyper-js-L33 by setting `showHamburgerMenu` to `true`.

**Comment by juangl** [comment]
Thank you. Everything is ok.
