### ISSUE TITLE
Chinese characters display errors

### ISSUE THREAD

**Issue by damfu** [zeit/hyper#1194]
- **OS version and name**: macOS 10.12.1
- **Hyper.app version**: 1.0.0 (1.0.0.1303)
- **Link of a Gist with the contents of my .hyper.js**: https://gist.github.com/damfu/11f94e9f6cc957cb0c9aae18b59753c9
- **Relevent information from devtools**:
> (re)loading renderer plugins
total init time 212.42999999999998
Unknown OSC code: "1"
Unknown OSC code: "1"
Uncaught ReferenceError: context is not defined
Unknown OSC code: "1"
Uncaught ReferenceError: context is not defined
Unknown OSC code: "1"
- **The issue is reproducible in vanilla Hyper.app**: Is Vanillala

Hyper
![image](https://cloud.githubusercontent.com/assets/3362116/21168001/9c3b90fc-c1eb-11e6-8e4c-e4797cfd8bd5.png)

macOS Terminal
![image](https://cloud.githubusercontent.com/assets/3362116/21168141/ab0bff1c-c1ec-11e6-8862-b2231512e76b.png)

After upgraded to 1.0, some files or folders and any text containing Chinese characters won't display.
Is this a bug or something? Please help.

**Comment by dotcypress** [comment]
@damfu could you give example of Chinese characters?
i'll check.

**Comment by damfu** [comment]
Thanks. 👍 
你好
谢谢

**Comment by dotcypress** [comment]
I see following on my branch

<img width="213" alt="screen shot 2016-12-13 at 7 41 06 pm" src="https://cloud.githubusercontent.com/assets/1333916/21168860/398b4f58-c16c-11e6-8f8f-7c9f0de4bb14.png">


Seems fixed in https://github.com/zeit/hyper/pull/1111 😎

**Comment by damfu** [comment]
Awesome! Thx for your following up.

**Comment by damfu** [comment]
I think it's same problem as #1131

**Comment by CodeTheory** [comment]
Hi @damfu are you still experiencing this issue?

**Comment by CodeTheory** [comment]
Due to the inactivity of this issue, I'm going to close this. Please re-open if this is still an issue.

**Comment by jiashuw** [comment]
@CodeTheory still seeing the same issue here
