### ISSUE TITLE
No menu bar in fedora?

### ISSUE THREAD

**Issue by BharatKalluri** [zeit/hyper#1195]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: fedora 25
- **Hyper.app version**: 1.0.0
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla Hyper.app

## Issue
Maybe I am stupid and not able to understand where to look, but on my fedora using the latest hyper.rpm There is no visible menubar. The rightclick acts as a paste shortcut and the middle mouse button acts as a paste shortcut(?).

The alt button does not show the menu bar, Since I cannot rightclick and copy or use ctrl+c or use ctrl+shift+c to copy, this is literally making the terminal unusable for me :-( , Is there a shortcut edit file which can be modified?

The app itself is awesome, thanks!

**Comment by WoodyWoodsta** [comment]
Had that issue since the re-structure of the titlebar and tabs. There is, however, a hamburger menu, which for some reason is disabled by default on Linux. It can be enabled by placing the following in your config file (`~/.hyper.js`):

```javascript
showHamburgerMenu: true
```

**Comment by BharatKalluri** [comment]
Thanks @WoodyWoodsta , still the ctrl+shift+c for copy does not work, I saw The issue for restructing the linux shortcut keys, hope they act fast.
Closing the issue.

**Comment by omilun** [comment]
hey guys . i am using hyper on debian . 
i dont need menu bar and any buttons .
i set showWindowControls: 'false', and showHamburgerMenu: 'false', but i have both of them on window.
