### ISSUE TITLE
macOS: repeated character input shows flickering accented char input dialog

### ISSUE THREAD

**Issue by tsabirgaliev** [zeit/hyper#1198]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.1
- **Hyper.app version**: Hyper.app 1.0.0.1303
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default .hyper.js
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

![hyperbug-2](https://cloud.githubusercontent.com/assets/225910/21171277/07a3b424-c1f5-11e6-8f5b-47aaa96aae9a.gif)

**Comment by ajacksified** [comment]
First thing I did was open up the config file in vim; I held down `l` for a second and saw this. Latest hyper.app (1.0.0.1303),  OSX 10.12.1.

**Comment by ppot** [comment]
closing in favor of #1137

For now, you can disable this feature system-wide with the following command:

defaults write -g ApplePressAndHoldEnabled -bool false
