### ISSUE TITLE
[windows] Control characters not working! 

### ISSUE THREAD

**Issue by pi0** [zeit/hyper#1200]
Many windows users are using cygwin to use linux utilities such as vim, nano, zsh and many more.
It seems current implementation does not supports it (no TTY is allocated on windows).
Any plan on this ? :))

PS: i'm willing to start helping and working on this.
PSS: Thanks for your nice work :))

Env:
```
Hyper 1.0.0
Electron 1.4.7
win32 x64 10.0.14936
```

**Comment by stereokai** [comment]
@pi0 any reason not to use Bash on Ubuntu on Windows? (what a terrible name 😄)

**Comment by pi0** [comment]
@stereokai But who loves that BoUoW stack ?? :)) Here is a comparison with same [dotfiles](https://github.com/pi0/dotfiles) between Cygwin mintty and latest hyper build:

- Commands normally won't work unless first i type `bash` then other commands as normally windows build does not understands TTY .bash somehow simulates that.
- Keyboard shortcuts in tty (ctrl,alt,..) are impossible to work in simulated environment

![image](https://cloud.githubusercontent.com/assets/5158436/21183961/8260d050-c21f-11e6-8c3a-464ec056ea4b.png)

![image](https://cloud.githubusercontent.com/assets/5158436/21184020/cff1f344-c21f-11e6-9fa3-aa742c6269d3.png)

As a suggestion why not using some tty aware engine inside hyper for windows like [paradoxxxzero/butterfly](https://github.com/paradoxxxzero/butterfly) ? I had a very good and smooth experience with it on windows ..

Thanks :)

**Comment by airtonix** [comment]
it doesn't matter what shell you use, the control characters just plain don't do anything on windows.

**Comment by pi0** [comment]
@airtonix Agree Butterfly is python daemon but it also uses js for terminal emulation :)) Maybe we can use that js to support control characters...

**Comment by stereokai** [comment]
Well I'm following this because it's very interesting. Could it be related to [Up arrow key does not work in bash.exe #1127](https://github.com/zeit/hyper/issues/1127)?

**Comment by ppot** [comment]
close in #1876
