### ISSUE TITLE
Hyper web browser not working on windows

### ISSUE THREAD

**Issue by fdrx** [zeit/hyper#1201]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows 8.1
- **Hyper.app version**: 1.0.0

## Issue
Hyper browser not working on windows

**Comment by reflog** [comment]
same on linux

**Comment by ppot** [comment]
Can you be more specific? No url navigation for exemple?

**Comment by reflog** [comment]
Typing www.google.com doesn't open the embedded browser

**Comment by xtalx** [comment]
OS version and name: windows 7

Hyper.app version: 1.0.0

typing in a url doesn't open the embedded browser (it produces a 'command not found'). I tried in 3 different shells [cmd, git bash, powershell].

**Comment by damien122** [comment]
OS version and name: windows 10 x64

Hyper.app version: 1.0.0

also for me the same problem, I have tryed it with git bash and cmd. I got the prompt "command not found"

**Comment by ppot** [comment]
`[cmd, git bash, powershell]` supported shell are bash, fish, zsh. Can you print me the result with `cmd, poweshell, got bash` @xtalx
