### ISSUE TITLE
macOS: Use command "ls -al" Issue

### ISSUE THREAD

**Issue by jasperamos** [zeit/hyper#1202]
- **OS version and name**: MacOS Sierra 10.12.1(16B2555)
- **Hyper.app version**: 1.0.0（1.0.0.1303）
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [PressMe](https://gist.github.com/jasperamos/e298ec4ead46196137acc2a0d15e06e6)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A

## Issue
Please see [Gif file](http://imgur.com/NIA5VCP)
- type ls -al
- sometimes you can see rm.sh, sometimes you can see go.sh. but actually it should show up both.

**Comment by OJFord** [comment]
This is not an `ls` issue, it's a pane size issue, and likely due to your shell (which is what?).

Notice how when some output is hidden, the last line of stdout was clipped and your prompt ended up on the end.

**Comment by jasperamos** [comment]
![2016-12-16 00 15 38](https://cloud.githubusercontent.com/assets/9114091/21231907/d4054bd8-c324-11e6-84e8-830dd433f626.png)

1. I think i use the default shell.
1. this issue is not happened on default terminal (weird)
1. on hyper.app, i just need quick repeat ls -al command, and i can see lost some file list on the hyper.app.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
