### ISSUE TITLE
Plugin Request: Typing/sending input into multiple panes

### ISSUE THREAD

**Issue by dannynimmo** [zeit/hyper#1203]
Being able to type into two or more sessions at once is such a useful feature of iTerm2 ([explaination here](http://korishev.com/blog/2014/02/28/iterm2-broadcast-input/)). It would be great to be able to replicate this in Hyper.

Is this even possible for a plugin?

**Comment by kingmomo** [comment]
I use [hyper-pane](https://www.npmjs.com/package/hyper-pane) + [hyper-broadcast](https://www.npmjs.com/package/hyper-broadcast) to do exactly what you are saying.

**Comment by albinekb** [comment]
This is available as plugins, @kingmomo linked two nice ones 👍

**Comment by chabou** [comment]
Amazing plugins 😎 :trollface:

**Comment by kingmomo** [comment]
@chabou i have to agree! :clap:
