### ISSUE TITLE
Incorrect displaying of cyrillic symbols

### ISSUE THREAD

**Issue by skad0** [zeit/hyper#1204]
- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 1.0.0.1303
- **config file .hyper.js**: [here](https://gist.github.com/skad0/7f607b875c8b8840cb7f2f38f9561ae1)
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
When i'm trying to type russian symbols, i get some weird effect like on screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/974119/21180748/73f11f20-c20b-11e6-8442-b92fd74d8396.png)

`абвгд`

The same, when I'm trying to type special symbols like `˚¬∆˙`

Seems like it was [fixed](https://github.com/zeit/hyper/issues/1070), but now it isn't.

**Comment by kleinfreund** [comment]
I can copy the characters you mentioned and `echo` them in my Hyper terminal window without problems (I’m on Ubuntu 16.04, Hyper 1.0.0).

**Comment by nomaed** [comment]
Work for me on Version 1.0.0.1303 on Sierra 10.12.2

**Comment by skad0** [comment]
I tried on OS X El Capitan 10.11.6, with clear install of Hyper 1.0.0.1303 and got the same result :-(

**Comment by lamartire** [comment]
ubuntu 14.04, hyper 1.0.1, same trouble.

**Comment by Realetive** [comment]
Problem solved with
```
export LANG=ru_RU.UTF-8
export LC_CTYPE=ru_RU.UTF-8
```
in to your `.bash_profile` or `.zshrc`
