### ISSUE TITLE
Key repeat broken for uppercase letters

### ISSUE THREAD

**Issue by vikfroberg** [zeit/hyper#1208]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS 10.11.6 and macOS**: 
- **Hyper.app 1.0.0**: 
- **Link of a [Gist](https://gist.github.com/vikfroberg/4f47d79997a97acff69fb8c6c3d3c17a) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Key repeat broken when using shift + letter

**Comment by ppot** [comment]
Do you have a picture?

**Comment by cameronhimself** [comment]
I'm having the same issue and I can report that there's nothing to take a picture of. You just don't get key repeat when holding down a letter key and shift at the same time.

**Comment by ppot** [comment]
ok, I see what you mean. Thanks

**Comment by cameronhimself** [comment]
I think this may be related to the OS character viewer you get when holding down keys. I took a quick screengrab of what it looks like when I hold down different keys: https://media.giphy.com/media/l0MYAzQDK9xPFSm5O/giphy.gif

It's kind of a lousy quality gif, so I'll summarize what's happening:

- `a`: repeating character, but slower than in Terminal.app and the character viewer flashes up for an instant on each repeat.
- `d`: repeating character, but slower than the normal key repeat in Terminal.app.
- `E` (`shift`+`e`): only character viewer—no repeating character.
- `D` (`shift`+`d`): no character viewer or key repeat.

Here's what happens with the same characters in this GitHub text editor. I'm assuming this is the OS behavior in text editing contexts:

- `a`: character viewer only.
- `d`:  nothing at all (no repeat or character viewer).
- `E`: character viewer only.
- `D`: nothing at all.

And finally, here's what happens with the same keys in Terminal.app, which is the functionality I was expecting:

- `a`: repeating character, no character viewer.
- `d`:  repeating character, no character viewer.
- `E`: repeating character, no character viewer.
- `D`: repeating character, no character viewer.

**Comment by ppot** [comment]
related to #1137

```
For now, you can disable this feature system-wide with the following command:

defaults write -g ApplePressAndHoldEnabled -bool false
```
