### ISSUE TITLE
Cannot drag view when Developer Tools open

### ISSUE THREAD

**Issue by theblindprophet** [zeit/hyper#121]
When opening Developer Tools via: Top Bar -> View -> Toggle Developer Tools

Cannot drag view around screen when clicking and holding `<header>`.

Works when Developer Tools are not open.

**Comment by mauro-oto** [comment]
Looks like it's related to https://github.com/electron/electron/issues/3647

**Comment by CodeTheory** [comment]
Yes, unfortunately, this is upstream.
