### ISSUE TITLE
cd.. produces a blank white screen

### ISSUE THREAD

**Issue by GameGamer43** [zeit/hyper#1210]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.12.2
- **Hyper.app version**: 1.0.0.1303
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
Unknown OSC code: "1"
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
Unknown OSC code: "133"
Unknown OSC code: "1337"
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
Unknown OSC code: "133"
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
Unknown OSC code: "133"
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
Unknown OSC code: "133"
Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
```
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Open Hyper.app and type the following:
```
cd..
``` 
You will get a blank white screen.

**Comment by CodeTheory** [comment]
Oh wow... Can reproduce.

**Comment by marclundgren** [comment]
I recorded the symptom here: http://recordit.co/z5IgNy5KgR

**Comment by ppot** [comment]
<img width="567" alt="screen shot 2016-12-14 at 12 34 30 pm" src="https://cloud.githubusercontent.com/assets/5577409/21193272/b7c36b84-c1f9-11e6-9a4d-8250de9f6983.png">

**Comment by corozco4** [comment]
I just noticed that is actually no related with the "cd", it seems to be related with two dots ".." after any character or word.

Example:

...
d..
bagre..

**Comment by andreafalzetti** [comment]
It happens the same with `cd ..ll`

**Comment by oxfn** [comment]
Got the same issue when typed `дд` instead of `ll` (in Russian layout). Exceptions are similar 
![2016-12-19-hyper-wsod](https://cloud.githubusercontent.com/assets/641896/21316058/2223d936-c610-11e6-9c39-f7521d47ed58.png)

**Comment by rauchg** [comment]
URL handling has been vastly [improved on `1.0.1`](https://twitter.com/rauchg/status/815010770618437632)! Thanks for the reports 🙏
