### ISSUE TITLE
hyper should be put on the PATH upon install

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#1211]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: 1.0.0

## Issue

`hyper` should be put on the `PATH` so it's more accessible.

You can do this on Linux by adding either a symlink or script at `/usr/bin/hyper` that points to `/opt/Hyper/hyper`

**Comment by kas** [comment]
This helped me be able to launch Hyper from dmenu. Thank you!

**Comment by archon810** [comment]
Same, but for Windows.

**Comment by chabou** [comment]
Fixed in v2 :)

**Comment by albinekb** [comment]
Tracking this for first launch in windows over here: https://github.com/zeit/hyper/issues/2823
