### ISSUE TITLE
Add --help command line args

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#1212]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.10
- **Hyper.app version**: 1.0.0

## Issue

`/opt/Hyper/hyper --help` simply runs the app, it should tell you what command line arguments are available (if any) as well as app name/version/etc.

**Comment by radix** [comment]
I suppose this should be closed since a PR has been merged adding --help support
