### ISSUE TITLE
Window control buttons in Ubuntu appears like in Windows

### ISSUE THREAD

**Issue by LestaD** [zeit/hyper#1215]
- **OS version and name**: Ubuntu 16.04.1 
- **Hyper.app version**: v1.0.0
- My **.hyper.js** is default

## Issue

Hyper:
![image](https://cloud.githubusercontent.com/assets/5620073/21202796/e8c334aa-c260-11e6-841b-a725750ba1c3.png)

For example _terminator_ with Radiance ubuntu theme:
![image](https://cloud.githubusercontent.com/assets/5620073/21202817/02ad7646-c261-11e6-9a6e-93eb236e1bac.png)

With Ambiance theme:
![image](https://cloud.githubusercontent.com/assets/5620073/21202847/24b89f2c-c261-11e6-9646-3f746b0669b2.png)

**Comment by CodeTheory** [comment]
This is intentional, though we will look into creating a specific window control styling for Ubuntu.

**Comment by iamstarkov** [comment]
that is sad

**Comment by iamstarkov** [comment]
@CodeTheory what is the reasoning behind that choice?

**Comment by CodeTheory** [comment]
It wasn't so much a choice @iamstarkov, but a limit on time. We didn't have enough time to go through each system to match their designs and support them so we settled with the windows inspired control design. 
Though I will personally submit work to support more system designs. ❤️

**Comment by iamstarkov** [comment]
@LestaD can you share screenshots of terminator with several tabs and panes?

**Comment by LestaD** [comment]
@iamstarkov 
![image](https://cloud.githubusercontent.com/assets/5620073/21206660/9a534922-c274-11e6-8030-ddf74d0befaa.png)
![image](https://cloud.githubusercontent.com/assets/5620073/21206682/bb1c9e7e-c274-11e6-91c3-0395dc8c639b.png)
Panels

**Comment by LestaD** [comment]
@iamstarkov 
![image](https://cloud.githubusercontent.com/assets/5620073/21206711/d7942aae-c274-11e6-9b87-7b419b18a123.png)
Tabs

**Comment by LestaD** [comment]
@iamstarkov 
![image](https://cloud.githubusercontent.com/assets/5620073/21206755/06e60840-c275-11e6-84ad-4eaa4cbe7e58.png)
Tabs in default terminal
