### ISSUE TITLE
how to set "treate ambiguous-width characters as double width"?

### ISSUE THREAD

**Issue by foxundermoon** [zeit/hyper#1219]
i am use powerline font under tmux,so it bring to sonme wrong.

![wx20161215-142436](https://cloud.githubusercontent.com/assets/2764106/21213951/aee6263a-c2d2-11e6-8fea-15ac4a5e4fb4.png)

under the iterm2 , i am set the "treate ambiguous-width characters as double width" option can resolve the  problem.
Hyper 1.0.0
Electron 1.4.7
darwin x64 16.1.0

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
