### ISSUE TITLE
High CPU usage on windows 

### ISSUE THREAD

**Issue by oleynikandrey** [zeit/hyper#1221]
Just started Hyper Terminal uses about 13% of CPU on Windows 10. 

![image](https://cloud.githubusercontent.com/assets/1157958/21215949/277430f6-c2b5-11e6-8e80-61520f013f4f.png)

-

Hyper 1.0.0
Electron 1.4.7
win32 x64 10.0.14393

**Comment by stereokai** [comment]
And that is only the main process. I have 4 **additional** processes running
![processes](https://cloud.githubusercontent.com/assets/2685357/21216905/07f018ec-c2b2-11e6-8dbd-fe21b0973215.PNG)

What shell are you using with Hyper? (Options: cmd - default, powershell, native bash, maybe others I  don't know). Are you using plugins? Try to disable them if you do and report back.

**Comment by oleynikandrey** [comment]
I have made no changed to default settings of Hyper. So it use cmd as shell and no plugins at all.

**Comment by iframeskills** [comment]
+1; also experiencing this issue. 
default install and not even running anything ...

**Comment by omnicons** [comment]
Also experiencing this, though it is more pronounced when I get into zsh going up to about 7% usage

**Comment by giggio** [comment]
I also experienced, and also just the default experience. Made it unusable, had to close it and stop using. I will wait for a later release.

**Comment by cdhunt** [comment]
Just updated to 1.3.0 and CPU utilization is still quite high. About 30% constantly across the 4 processes. Also Windows 10 build 14393. I'm using Powershell.exe. [My Config](https://gist.github.com/cdhunt/75b0162aa4cb1f11ce2b592e8c324bfa).

**Comment by cdhunt** [comment]
FWIW, after letting the window site idle for a couple of hours, I found CPU utilization to be near 0. I don't know really how long. That and JS profiling shows nothing leads me to believe it's some background task that evetually finishes or times out.

**Comment by cdhunt** [comment]
And I let it sit over night and it's still using 30%+ CPU this morning. /shrug

**Comment by mloffer** [comment]
This also happens to me on Win 10, but only when I install hyper-tabs-enhanced. As soon as I remove it, CPU usage goes back to normal.

![cpu](https://cloud.githubusercontent.com/assets/666696/25077891/cdd326c2-22e2-11e7-8d2d-ae317f4506ec.PNG)

**Comment by chabou** [comment]
@cdhunt Can you try with a vanilla HyperApp. Without any (hyper-tabs-enhanced) plugin?

**Comment by cdhunt** [comment]
I was just testing and I can corroborate disabling `hyper-tabs-enhanced` reduces CPU usage to ~0%.

**Comment by chabou** [comment]
Great!
So we can close this issue (other feedbacks are old).

But feel free to reopen if last version of Hyper has a high CPU usage without any plugin.

**Comment by MartyGentillon** [comment]
Transferred issue to hyper-tabs-enhanced repository as https://github.com/henrikdahl/hyper-tabs-enhanced/issues/13.

**Comment by pcnate** [comment]
I had a similar issue. I would verify if you have `hyper-material-theme` installed

**Comment by idanshimon** [comment]
this still happend on hyper 2.0.0. stable with hyper-tabs-enhanced plugin installed my CPU goes upto 100% 
once i removed the hyper-tabs-enhanced plugin it resolved and cpu went down to 30%~

**Comment by CosmicCatnap** [comment]
Can confirm this still happens on hyper 3.0.2 on Windows build 18362.388
Turns my laptop into a leaf blower with just cmd open. Installed today and made no changes to the settings or configuration.

**Comment by Marko721** [comment]
Also confirming - build 1909. Used like 70% of my cpu.
