### ISSUE TITLE
Cannot run Hyper with bash on Windows

### ISSUE THREAD

**Issue by sarneeh** [zeit/hyper#1222]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64bit
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/sarneeh/8a2e4dc4651dcf5faa3c610fa86cd676
- **Relevent information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Hey!

I've just installed Hyper on my windows machine but it's not working as thought it will. I've been using the windows subsystem feature (having bash and all linux features on windows) and I wanted to use it with Hyper. I understood, that the config `shell` option gives me the possibility to run some custom shell. So i've entered the the path to `bash`. But it keeps saying "File not found" :( Am i miunderstanding something, or is something going wrong out there?

![issue](https://i.imgur.com/gD1LkiR.png)

**Comment by Specro** [comment]
You forgot the extension: `shell: 'C:\\Windows\\System32\\bash.exe'` 😄

**Comment by fibo** [comment]
yeah, finally a good terminal on Windows

**Comment by sarneeh** [comment]
@Specro Oh my god... You're right. Thanks a lot! :D
