### ISSUE TITLE
Hanging / slow on windows 7 64 bit 

### ISSUE THREAD

**Issue by ceddlyburge** [zeit/hyper#1223]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7 professional service pack 1 64 bit
- **Hyper.app version**: 1.0.0
- **The issue is reproducible in vanilla Hyper.app**:Yes

## Issue
Hyper is unusably slow for me or is hanging on load, I can't see it or type anything in.

This is a picture of a part of the screen where Hyper is running, and you can see that it is not redrawing itself
![capture](https://cloud.githubusercontent.com/assets/13573831/21219859/65df747e-c2ae-11e6-9ef3-c0c32b6b59fe.PNG)

**Comment by NIPanag** [comment]
Experiencing the exact same issue here.

**Comment by ppot** [comment]
@ceddlyburge  @NIPanag  Can you be more specific ? While running large output? For exemple?

**Comment by NIPanag** [comment]
@ppot Could you clarify that "running large output" part?

**Comment by ppot** [comment]
See #571

**Comment by NIPanag** [comment]
Unrelated in my case. Simply starting Hyper up makes it so the renderer hangs (I assume).
![](https://5.lithi.io/eUne.png)
Pictured above is what happens when I drag a window over the invisible hyper window.

**Comment by ceddlyburge** [comment]
I'm not running anything. This happens on startup so I can't enter any
commands.

**Comment by cakenggt** [comment]
I am having this issue as well. The hyper window opens up invisibly, and the only way I can see that there actually is a window is by minimizing and restoring it using the task bar, which I then see a menu bar fly up and down. However, nothing is rendered in the window, making it look like nothing is actually there. This happens after a fresh computer restart as well.

**Comment by mikeumus** [comment]
Messing with the compatibility settings for the program I was able to get the black box (Hyper) showing once. But it's now even showing for me on Windows 7 Enterprise.

**Comment by cakenggt** [comment]
This is still an issue for me with version 1.01

**Comment by eucaos** [comment]
Same issue here, hyper is unusable slow on windows 7 64 bit.

**Comment by doberkofler** [comment]
Same issue here

**Comment by JarnoNijboer** [comment]
@andersrydman I see you have Aero disabled? Could you check if Hyper does launch when you turn Aero on?
I ask this because when Hyper creates an frameless Electron BrowserWindow, with transparency [explicitly](https://github.com/zeit/hyper/blob/master/app/index.js#L142) turned on.
However there several [limitations](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#limitations) for frameless, transparent windows in Electron.
My hypothesis is that the window isn't shown because of these limitations.

**Comment by e1r0nd** [comment]
@JarnoNijboer enabling Aero works for me, thank you. (Window 7 Ultimate 64-bit)

**Comment by cakenggt** [comment]
@JarnoNijboer This worked for me too. (Windows 7 64-bit)

**Comment by ceddlyburge** [comment]
Selecting an aero theme worked for me as well.

**Comment by NIPanag** [comment]
Disabling transparency worked for me.

**Comment by JarnoNijboer** [comment]
I have created issue #1345 as an (partial) solution for this.

**Comment by andersrydman** [comment]
@JarnoNijboer I can confirm it does work once I turned Aero on. Thanks.
