### ISSUE TITLE
[Windows] Interruption during installation causes corrupt registry entries

### ISSUE THREAD

**Issue by Specro** [zeit/hyper#1224]
- **OS version and name**: Windows
- **Hyper.app version**: 1.0.0

## Issue

I'm not sure if this should have a separate issue but that's where issues like #1133 and #1165 stem from. 

During installation of Hyper on Windows Squirrel runs Hyper mid-install to add context menu entry/desktop icon. Sometimes it runs quickly and is almost impossible to notice. Other times it takes up to 5s. If the user thinks that installation is finished and closes Hyper window during this time the creation of registry entries is interrupted and causes corrupted registry entries.

I'm not sure how to handle this but maybe the user should be notified somehow beforehand or the installation process should be more intuitive.

**Comment by linonetwo** [comment]
360 will interrupt this, so If I forget to close 360, I have to edit my regedit.
