### ISSUE TITLE
Keyboard arrow buttons are not working

### ISSUE THREAD

**Issue by sarneeh** [zeit/hyper#1225]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64bit
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Default
- **Relevent information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Just like in the title - I can't make them working. When i enter any command and want to fix a typo - I can't move the cursor with the arrow buttons. Nor can i do the same i.e. in `vim`. Am i missing something?

**Comment by blackwellops** [comment]
This is a duplicate.
[https://github.com/zeit/hyper/issues/1127](https://github.com/zeit/hyper/issues/1127)

**Comment by ppot** [comment]
Closing for #1127
