### ISSUE TITLE
Terminal broken on opening URLs

### ISSUE THREAD

**Issue by noxowe** [zeit/hyper#1226]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 1.0.0

- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: https://gist.github.com/noxowe/1e9b863d022cf0ba29bf5cb930cbb0e6
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
When you type in any URL (say twitter.com) and hit enter when you try to open a new tab or switch tabs the whole terminal freezes and soon your whole computer does too

**Comment by albinekb** [comment]
Is this still a problem? @noxowe
