### ISSUE TITLE
Adding padding to x-row breaks cursor position in terminal

### ISSUE THREAD

**Issue by manuelbieh** [zeit/hyper#1227]
- [✅] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [✅] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10, latest stable build
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: `    termCSS: 'x-row { padding-top: 4px;}',`
- **Relevent information from devtools**: http://imgur.com/a/TooMS
- **The issue is reproducible in vanilla Hyper.app**: ?

## Issue
I added some padding to each line in the term window but now the cursor position is totally broken. With each linebreak the difference between actual cursor position and the position the cursor should be at is increased by the amount of the padding. 3 new lines = 12px, 10 new lines = 40px, etc ...

**Comment by AaronFlower** [comment]
I face the same problem!

**Comment by spoike** [comment]
This issue has been earlier found in #75

**Comment by timothyis** [comment]
`termCSS` is deprecated and `x-row` no longer exists due to the removal of hterm in favour of xterm.js
