### ISSUE TITLE
Hangs on large node/npm tasks.

### ISSUE THREAD

**Issue by Nicholaiii** [zeit/hyper#1231]
- **OS version and name**: Windows 8.1
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Nicholaiii/5f3deb151929bd9f27ccf0a62d541294
- **Relevent information from devtools**: Not sure if applies?
- **The issue is reproducible in vanilla Hyper.app**: Straight out the box. Changed background colour only.

## Issue
Hello team. I love to see the software on Windows. When I run large tasks with npm or node such as installing or running a large project, it "hangs up". Does not become unresponsive but shows no signs of progress where cmd, cmder and git bash has no problems. Doesn't matter if I run bash inside. Process quits as expected on CTRL-C.

(also a weird side note, the font color (cursorColor) turned purple after a successful `npm install` (read: nothing to install), was previously white)

**Comment by ppot** [comment]
Closing for #571 :)

**Comment by Nicholaiii** [comment]
Not the same issue, not the same problem and not the same experience :)

**Comment by Nicholaiii** [comment]
Let me clarify; Renderer does not lag and this happens even before a large stream of output. DevTools also does not get disconnected and the app (or the renderer) _does not crash_

**Comment by ppot** [comment]
` When I run large tasks with npm or node such as installing or running a large project, it "hangs up". ` Could you make a gif of this action than. Since the "hangs up" happen generally when hterm is not fast enough to render the output. So the hterm catch the 'ctrl+c' event and the pty action stop when hterm get his process right.
