### ISSUE TITLE
urls are not hyperlinks

### ISSUE THREAD

**Issue by anthonyettinger** [zeit/hyper#1233]
If I ssh to a server with hyper and start screen, hyperlinks that show in the terminal are no longer active links.

**Comment by anthonyettinger** [comment]
actually they don't work anywhere. Is there a keyboard command to enable http hotlinks? I did not see anything in settings.

In iterm2 I just do `cmd+hover` on a link to make it a hyper link. Would be nice to have same behavior.

**Comment by pdxmike** [comment]
@anthonyettinger Try adding 'hyperlinks' in the plugins section of ~/.hyper.js 

[https://github.com/zeit/hyperlinks](https://github.com/zeit/hyperlinks)

**Comment by albinekb** [comment]
As @pdxmike said, you can use https://github.com/zeit/hyperlinks :) closing
