### ISSUE TITLE
Menu only show when maximized on Ubuntu

### ISSUE THREAD

**Issue by RomuloPBenedetti** [zeit/hyper#1234]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04 LTS 
- **Hyper.app version**: 1.0.0 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/RomuloPBenedetti/09c06cbdba7bbbfed16584f5d21554fc
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A 
- **The issue is reproducible in vanilla Hyper.app**:  Vanilla

## Issue

I've configured my ubuntu to show menu in title bar, It's the only relevant setting I believe can be a cause of this problem.

**Comment by saule1508** [comment]
Hello,

On Fedora the menu does not show at all. With the previous version (0.8) there is a normal menu, I've seen from the release notes that this got changed to an hamburger menu in 1.0 but when I run 1.0 on Fedora there is no menu at all.

Thanks

**Comment by swhammack** [comment]
This is also an issue in Arch running Cinnamon as desktop environment. Can't see the menu maximized or any other way.

**Comment by penance316** [comment]
I have seen the same issue on Linux Mint XFCE desktop ( no hamburger menu even with config set to true )

**Comment by saule1508** [comment]
As indicated in #1266, editing .hyper.js in the home directory and adding this in the config object solved the problem on Fedora
```
module.exports = {
  config: {
     showHamburgerMenu: true,
     // default font size in pixels for all tabs
     fontSize: 14,
     etc..
```

**Comment by albinekb** [comment]
@RomuloPBenedetti can you see if @saule1508 's solution does it for you? :) I think it's intended. Re-open if i'm wrong.
