### ISSUE TITLE
High CPU load with hyperpower plugin on Linux

### ISSUE THREAD

**Issue by bryantee** [zeit/hyper#1237]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint Kernel 4.8.8-040808-generic
- **Hyper.app version**: 1.0.0
- **Contents of your .hyper.js**: [GitHub Gist here](https://gist.github.com/bryantee/9167d96b6c276486dce3efaad7f0477a)
- **Relevent information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue

Getting abnormally high CPU usage (25%+) using 1.0.0 .deb package on Linux Mint and enabling `hyperpower` plugin. When disabled, everything seems normal. I am using oh my zsh.

![screenshot from 2016-12-15 15-38-54](https://cloud.githubusercontent.com/assets/10674447/21245170/469a4096-c2de-11e6-9276-49ea9e81c394.png)

**Comment by zanedev** [comment]
Might be related to this same issue on macosx: https://github.com/zeit/hyper/issues/574

**Comment by dankonino** [comment]
I love that plugin, it needs to be fixed xD.

**Comment by kkuhle** [comment]
I've tried to use this on Mac and it's awesome, but causes my laptop to get very hot and fans to come on which I assume is from the cpu utilization so I'm not able to use it.
