### ISSUE TITLE
paste url to PDF and hit enter

### ISSUE THREAD

**Issue by anthonyettinger** [zeit/hyper#1238]
Hyper constantly asks to download.

`$ http://www.fonerbooks.com/poster.pdf [enter]`

MacOS (latest Hyper)

Have to kill hyper

**Comment by ppot** [comment]
@rauchg download link? Never had this. @anthonyettinger Picture?

**Comment by moskyb** [comment]
@ppot: 
<img width="1280" alt="screen shot 2017-01-11 at 8 31 20 am" src="https://cloud.githubusercontent.com/assets/15753101/21821431/7c51bd54-d7d8-11e6-9a2f-6f7897e69584.png">

After hitting enter:
<img width="1280" alt="screen shot 2017-01-11 at 8 31 31 am" src="https://cloud.githubusercontent.com/assets/15753101/21821433/7c585f42-d7d8-11e6-8f93-95f47cf66e8b.png">

After pressing "Cancel"
<img width="1280" alt="screen shot 2017-01-11 at 8 31 34 am" src="https://cloud.githubusercontent.com/assets/15753101/21821434/7c5f48b6-d7d8-11e6-980b-0e49607b0f7b.png">

Error message shown after quitting using Cmd-Q
<img width="421" alt="screen shot 2017-01-11 at 8 30 58 am" src="https://cloud.githubusercontent.com/assets/15753101/21821438/7edfab12-d7d8-11e6-91ed-300aaae57fa4.png">

**Comment by timothyis** [comment]
This isn't the case anymore 🙌
