### ISSUE TITLE
Issue setting Bash shell through Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by Artillect** [zeit/hyper#1240]
- **OS version and name**: Windows 10
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Artillect/96aee3a67e29726ed5ac801265735bcc
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

When I set my shell to /usr/local/bin/zsh (with zsh installed, I know it works because I've been using bash and zsh through command prompt) I get an error that says this:

![capture](https://cloud.githubusercontent.com/assets/8906201/21248292/e47becc2-c2ea-11e6-89db-d837e54f5f49.PNG)

> A JavaScript error occurred in the main process
> 
> Uncaught Exception:
> Error: File not found:
>     at Error(native)
>     at Server.<anonymous> (C:\Users\oreo4\AppData\Local\hyper\app-1.0.0\resources\app\node_modules\pty.js\lib...:9)
>     at emitOne (events.js:96:13)
>     at Server.emot (events.js:188:7)
>     at Pipe.onconnection (net.js:1459:8)

**Comment by ebemunk** [comment]
Hi, not sure if this applies to your case, but when running from windows you have to set `shell` to the location of bash.exe. I was having the same issues but setting `shell: 'C:\\Windows\\System32\\bash.exe'` works for me. I've set zsh as the default terminal in ubuntu so it automatically opens that, but if you want to specify that in the settings I don't know how.

**Comment by Specro** [comment]
You have to launch zsh in your `~/.bashrc` when bash starts since zsh is not a Windows compatible shell:
```
if test [ -t 1 ]; then
exec zsh
fi
```

**Comment by rmobis** [comment]
Alternatively, you can specify the the `['-c', 'zsh']` args on Hyper's `shellArgs` config option to automatically start zsh.

**Comment by Artillect** [comment]
@ebemunk Your fix worked! Thank you!

@specro I had already done that, as I said, zsh works fine

**Comment by albinekb** [comment]
Seems like this is resolved? @Artillect re-open if I'm wrong :)
