### ISSUE TITLE
Cannot edit preferences in Windows 10.

### ISSUE THREAD

**Issue by josephdburdick** [zeit/hyper#1243]
echo Attempting to open ^%userprofile^%\.hyper.js with notepad

 echo If it fails, open it manually with your favorite editor!

 start notepad "%userprofile%\.hyper.js"

➜  jb  echo Attempting to open ^%userprofile^%\.hyper.js with notepad
Attempting to open ^%userprofile^%.hyper.js with notepad
➜  jb
➜  jb  echo If it fails, open it manually with your favorite editor!
If it fails, open it manually with your favorite editor!
➜  jb
➜  jb  start notepad "%userprofile%\.hyper.js"
zsh: command not found: start

-

Hyper 1.0.0
Electron 1.4.7
win32 x64 10.0.14393

**Comment by stefanivic** [comment]
@josephdburdick You are using Bash on Windows with Zsh, what is happening is that Hyper is trying to open Notepad trough it with the start command that doesn't exist in zsh. 

You have two options : 
1. Open the .hyper.js manually by using explorer and going into `C:\\Users\\username\\.hyper.js`
2. Using cd to go into `/mnt/c/Users/username/` and then using vim, nano or what ever terminal editor you are using to edit the file.

**Comment by josephdburdick** [comment]
Ok, thank you very much for the explanation @stefanivic !
