### ISSUE TITLE
Shell option has no effect

### ISSUE THREAD

**Issue by con-ssc** [zeit/hyper#1244]
- [X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/con-ssc/26cd65a2888cf26953a801e0799a9ae4
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: no errors
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Adding shell: "C:\\cygwin64\\bin\\zsh" to the .hyperterm.js config does not open zsh shell at that location on startup.

**Comment by Specro** [comment]
You need double slashes and an extension on Windows: `shell: "C:\\cygwin64\\bin\\zsh.exe` 😄

**Comment by con-ssc** [comment]
@Specro If you had looked at the gist, you would've seen, there are double slashes ;)

**Comment by Specro** [comment]
Yeah sorry, I missed that 😄 Also the shell option should be in the config section.

**Comment by con-ssc** [comment]
@Specro Ah okay, that was the fault then. Thank you for your help. Would it be possible to have a json schema for the config?
