### ISSUE TITLE
Start up tasks

### ISSUE THREAD

**Issue by linonetwo** [zeit/hyper#1245]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows10
- **Hyper.app version**: 1.0

## Issue
There seems to be no way to config a startup task, works likes .bashrc in Linux.

I switch from cmder, Used to run
```
chcp utf-8
alias cnpm=npm --color=always --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist $*
```
on start up. Now Hyper seems to have no way to do this.

**Comment by maxshaw** [comment]
plugin "hyper-startup".
