### ISSUE TITLE
"Full Reload" makes text and bg render white

### ISSUE THREAD

**Issue by Nicholaiii** [zeit/hyper#1248]
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 17 Cinnamon
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Nicholaiii/af6be3e0233da8ee0a37744c12c77861
- **Relevent information from devtools**: `No definition for keyCode: 229` is the only thing I have.
- **The issue is reproducible in vanilla Hyper.app**: Yes! :)

## Issue
When doing a full reload the app renders the background and text white. Everything is okay upon restart.

**Comment by ppot** [comment]
close in #1262
