### ISSUE TITLE
Scrollbar doesn't work on Windows

### ISSUE THREAD

**Issue by inikulin** [zeit/hyper#1251]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/inikulin/52773bf4facf3394666edc937b882ddc
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
I don't know if it's a by design behavior, but it's impossible to scroll terminal by dragging a scrollbar with mouse. At the same time, it's possible to scroll using mouse wheel, but it's only useful unless you have relatively short logs.

**Comment by cthedot** [comment]
Same on Win10.

**Comment by mattpardee** [comment]
Same on Mac

**Comment by TraceyK14** [comment]
Can confirm this issue.

OS: Windows 10
Hyper: 1.0.1

**Comment by atomdmac** [comment]
+1
OS: Mac Sierra
Hyper 1.1.0 1408

**Comment by AWulkan** [comment]
Same for me.
Windows 10
Hyper 1.2.1

**Comment by thasmo** [comment]
Mintty uses `shift+scroll` to scroll much faster which is really great and Mintty also has no scrollbar.

**Comment by jazoom** [comment]
Yeah, this is painful

**Comment by inikulin** [comment]
> I meant to comment a while ago and forgot. This isn't a bug, as it turns out the scroll bar was never meant to function, it was purely there for aesthetics.

Mmm, design over usability, As far as I remember it always works quite well (it's not).

**Comment by joeSaad** [comment]
any updates on this issue?

**Comment by albinekb** [comment]
Anyone that tested `canary`? I think this might be fixed. 2.0.0 will be released 🔜

**Comment by chabou** [comment]
@joeSaad thank you for your feedback

**Comment by Elderry** [comment]
Seems this should already be fixed, but my scrollbar is still missing:

![capture](https://user-images.githubusercontent.com/1892221/39390444-31116764-4ac7-11e8-9299-c91ba4ae72bb.JPG)

OS version: Windows 10 Pro Build 16299.402
Hyper version: 2.0.0-stable
Hyper config: [Address](https://github.com/Elderry/config/blob/master/Settings%20-%20Hyper.js)

**Comment by nickjj** [comment]
I am using Windows 10 Pro 18.09 and Hyper 2.1.0-canary.2 and the scrollbar is completely hidden for me too. This is with the default theme and the `hyper-one-light` theme too, so I'm thinking this probably isn't a theme related issue.

**Comment by Stanzilla** [comment]
Should be fixed in newer versions
