### ISSUE TITLE
Use a different shell for updating plugins and editing the config file

### ISSUE THREAD

**Issue by piscisaureus** [zeit/hyper#1256]
I have configured hyper so that it opens an ssh (actually mosh) session to a remote server.

That works beautifully, except that editing the configuration file doesn't work any more, and I constantly get 'plugin update failed' errors. That's expected - after all the config file and plugins aren't stored on the remote server, but locally.

I'd like to be able to configure a different shell for actions that need to be run locally. I think it'd even work to just always use `/bin/sh` for the purpose invoking nano/npm.

This is somewhat related to #1142 and #1166 - users reporting the same issue when using fish rather than bash as the default shell.

Because you asked, I'm using the latest master (25fcf3a6a4ec6abaeeaf17a1f6681e4c025483af) on mac.

**Comment by rauchg** [comment]
Makes sense. I think wrapping the editing command with `sh` is a very good idea. Thanks for filing this issue @piscisaureus

**Comment by OJFord** [comment]
cf. #901

**Comment by OJFord** [comment]
Is there a workaround for updating plugins other than changing shell and back? (I haven't had any until today, when I found `keymap` and `hyperlink`, but of course they won't install...)

i.e. can I run some `npm` command somewhere?

**Comment by ilkka** [comment]
@OJFord as a workaround I found you can set `shell` to e.g. `zsh`, then execute fish through `shellArgs`:

```
shellArgs: ['-c', '/usr/local/bin/fish', '--login'],
```

The update mechanism doesn't use `shellArgs`, only the value of `shell`.
