### ISSUE TITLE
Linux Commands on Windows.

### ISSUE THREAD

**Issue by wilburpowery** [zeit/hyper#1257]
Is it possible to get Linux commands If I'm using the app on Windows 10?

**Comment by ptrkrlsrd** [comment]
Although I'm not entirely sure about this, as I'm not using Windows, I belive you can use Linux commands if you're using Bash instead of CMD.

**Comment by ppot** [comment]
@wilburpowery This is called BashOnWindows You can search to enable bash in your windows 10. 
This is not hyper related thought.

**Comment by aoozdemir** [comment]
@wilburpowery I'm using BashOnWindows. So far, so good actually. To use it with hyper, after the installation, type bash, and enter.

**Comment by scshepard** [comment]
Hi all,

I'm a bit confused here; I run the "application" called "Bash on Ubuntu On Windows"; I also use a Windows 10 X Windows server; inside bash you can type: export DISPLAY=:0   and run graphics orientated programs as well.

Thanks!

________________________________

**Comment by jamdev** [comment]
If you install Ubuntu on Windows, you can set shell as 'c:\\windows\\system32\\bash.exe' in Hyper's preferences. It will then use bash as default.

**Comment by albinekb** [comment]
>If you install Ubuntu on Windows, you can set shell as 'c:\\windows\\system32\\bash.exe' in Hyper's preferences. It will then use bash as default. (You need to use double backslashes).

This should probably be documented somewhere? cc @matheuss

**Comment by ryzokuken** [comment]
@albinekb Perhaps in `~/.hyper.js` as a comment above the `shell` variable?

**Comment by Stanzilla** [comment]
If you are using GitForWindows, you have to add `YOUR_GIT_FOLDER\\usr\\bin\\bash.exe`

**Comment by matheuss** [comment]
There's some ways to achieve that, but I'd recommend https://msdn.microsoft.com/en-us/commandline/wsl/install_guide 😄 

@albinekb I kinda documented this: https://github.com/zeit/hyper/commit/d54fa3889b4b9d7e48334e9fdd71b13889653187 Do you think it's enough? 🤔
