### ISSUE TITLE
Links in app

### ISSUE THREAD

**Issue by binjospookie** [zeit/hyper#1265]
I can open a link in hyper.

<img src="http://bit.ly/2hVucOo" />

**Comment by kleinfreund** [comment]
I don’t understand what your issue is. Please clarify.

**Comment by szhu** [comment]
Here's a question I have (and might be what they were asking): How do you make Hyper not do that?

**Comment by kleinfreund** [comment]
@szhu Not do what?

**Comment by szhu** [comment]
How do you make Hyper not navigate to a URL when you enter it at the prompt? It appears to do this by default.

**Comment by kleinfreund** [comment]
This is intended. It’s a feature. What do expect when entering a URL in a Terminal?

**Comment by pertrai1** [comment]
@kleinfreund - this is a great feature. A question I have is how do you close the URL once you have navigated to it?

**Comment by ppot** [comment]
@pertrai1 with my last PR 🍾  #1287

**Comment by albinekb** [comment]
Closing this as this is intended.. if you still think this is an issue @binjospookie we could add a flag for it in the config, please re-open if so 😄
