### ISSUE TITLE
Pressing CTRL + SHIFT + C doesn't copy the text on the terminal

### ISSUE THREAD

**Issue by sunilkumarc** [zeit/hyper#1267]
The copy feature on Windows version of hyper doesn't work. Pressing CTRL + SHIFT + C doesn't do any action.

**Comment by ppot** [comment]
closing for #1121

**Comment by matheuss** [comment]
Yo @sunilkumarc please test #1406 🙌

**Comment by sunilkumarc** [comment]
Works now. You guys are great.
