### ISSUE TITLE
Send command to all panes

### ISSUE THREAD

**Issue by vdclouis** [zeit/hyper#1270]
iTerm has the ability to send one command to all panes using `cmd shift i`.
Is this possible in Hyper?
Cheers!

**Comment by SShah2601** [comment]
Seconding this. It would be nice to be able to send to all panes in a window (including split panes) to allow to control multiple systems.

**Comment by roginfarrer** [comment]
This!! I work across three different repos, that usually need to be on the same branch. In iTerm, it's very easy to fetch/merge/commit/pull/checkout across all three very quickly this way.

**Comment by timothyis** [comment]
This is available via a plugin! https://hyper.is/plugins/hyper-broadcast
