### ISSUE TITLE
Pressing modifier key while select loses selection

### ISSUE THREAD

**Issue by deitch** [zeit/hyper#1274]
- [ X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 1.0.0 (1.0.0.1303)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/deitch/46e1eec3dfa20f68525bafce87e4f87d

## Issue
Selecting part of text, then pressing a modifier key, loses selection.

1. Highlight a character, some words, or several lines of text
2. Slide your pointer somewhere else
3. Try to Shift-Click, which normally keeps the existing text selected and _also_ selects the text in between the selected text and the pointer.

As soon as you press `Shift` (or `Ctrl` or whatever) the selection is lost. This makes it impossible to select a large range of text, or one that scrolls across multiple screens.

If I misunderstood something about the config, or you need any tests, more than happy to.

**Comment by ppot** [comment]
closed in  PR #1218

**Comment by deitch** [comment]
Thanks @ppot. 👍 

What version of hyper does it land in? Love to test it.

**Comment by ppot** [comment]
@deitch 1.0.1 soon

**Comment by deitch** [comment]
@ppot I have 1.0.1.1369 and it still is an issue:

1. Highlight some lines
2. Scroll a bit (or don't, doesn't matter(
3. Try to extend the highlight by hitting `Shift` and then mouse-click
4. The second you hit `Shift`, it loses the existing selection

Interestingly, `Command` and `Alt/Option` no longer lose existing selection, only `Shift` and `Ctrl`.

**Comment by ppot** [comment]
@deitch Yeah I fixed those. Weird that shift lose selection. 'it's due to the caret focus' -.- Gonna need to fix those.

**Comment by deitch** [comment]
> 'it's due to the caret focus'

Huh? I don't understand?

**Comment by ppot** [comment]
https://github.com/zeit/hyper/blob/master/lib/components/term.js#L157
https://github.com/zeit/hyper/blob/master/lib/hterm.js#L368-L373

**Comment by deitch** [comment]
Thx
