### ISSUE TITLE
Very slow paste with `zsh-autosuggestions` enabled

### ISSUE THREAD

**Issue by caesar** [zeit/hyper#1276]
With `zsh-autosuggestions` enabled, pasting is very slow – I see each character appear, one character every few ms. The same applies to opening the config file with `Cmd+,` – I see each line of the message "typed" and then executed, over a period of about 2 seconds, before the file opens.

Without `zsh-autosuggestions` I don't notice this, so obviously that software is partly to blame, but Hyper is also a factor here because pasting is instant in iTerm even with `zsh-autosuggestions`.

I believe this is because Hyper sends each character of a pasted string individually, whereas iTerm must be sending the whole string at once.

---

Hyper 1.0.0
Electron 1.4.7
darwin x64 15.6.0

**Comment by xvalentino** [comment]
Anyone have any ideas of how this can be done?

**Comment by vvo** [comment]
Quick note, on the standard terminal app on osx we have the same issue so I would say any time we use zsh-autosuggestions we are screwed and this is not a specific issue of hyper?

**Comment by xvalentino** [comment]
oh, you're very right. I didn't think I ran into this in iTerm, but I also do there.

**Comment by xvalentino** [comment]
https://github.com/zsh-users/zsh-autosuggestions/issues/141

**Comment by balta2ar** [comment]
Fixing delays on zsh-autosuggestions is, of course, necessary to do, but on the other hand, I believe https://github.com/zsh-users/zsh/blob/master/Functions/Zle/bracketed-paste-magic could be of great help here. In fact, I've experienced the same issue with Midnight Commander for a really long time. I described my unsuccessful hacking attempts here: https://github.com/zsh-users/zsh-autosuggestions/issues/136#issuecomment-220615998. Maybe similar technique could be employed here?

**Comment by sn0wyfall** [comment]
I'm experiencing this and I'm fairly sure that I don't have `zsh-autosuggestions` enabled. This does however only occur with zsh – with bash it pastes much faster. I'm unsure how to diagnose my issue. Any pointers would be appreciated!

**Comment by timothyis** [comment]
I'm pretty sure this should be okay with the latest version! Please let us know if it's not fixed.

**Comment by mportela** [comment]
echo $ZSH_VERSION
5.3

still very slow when pasting a large string.... :(

**Comment by sn0wyfall** [comment]
Same. 

    $ echo $ZSH_VERSION
    5.3

**Comment by fmeng** [comment]
very slow when pasting a large string
$ echo $ZSH_VERSION
5.3

**Comment by hriddhidey** [comment]
Same here. Excruciatingly slow while pasting long cURLs in zsh with zsh-autosuggestions enabled.
I really don't know why this issue is closed. It's very much still open.
$ echo $ZSH_VERSION
5.3

**Comment by uv-w** [comment]
mkdir $ZSH_CUSTOM/lib/

`
cp $ZSH/lib/misc.zsh $ZSH_CUSTOM/lib/.
vi $ZSH_CUSTOM/lib/misc.zsh
`

I commented the following lines, but you can remove it or change the if condition.

#if [[ $ZSH_VERSION != 5.1.1 ]]; then
#  for d in $fpath; do
#       if [[ -e "$d/url-quote-magic" ]]; then
#               if is-at-least 5.1; then
#                       autoload -Uz bracketed-paste-magic
#                       zle -N bracketed-paste bracketed-paste-magic
#               fi
#               autoload -Uz url-quote-magic
#               zle -N self-insert url-quote-magic
#      break
#       fi
#  done
#fi
Thanks and sorry for the question description, without the knowledge that I was using zsh this made the task to help me impossible to accomplish.

from：https://apple.stackexchange.com/questions/312795/zsh-paste-from-the-clipboard-a-command-takes-a-few-second-to-be-write-in-the-ter

**Comment by fredleger** [comment]
Seems that since some recent version the same workaround than the one suggested by @uv-w can be achieved by setting : `DISABLE_MAGIC_FUNCTIONS`=`true`

**Comment by polaroidkidd** [comment]
> Seems that since some recent version the same workaround than the one suggested by @uv-w can be achieved by setting : DISABLE_MAGIC_FUNCTIONS=true in .zshrc

works perfectly. Thank you @fredleger

**Comment by huwllewellyn** [comment]
This worked for me: https://gist.github.com/magicdude4eva/2d4748f8ef3e6bf7b1591964c201c1ab

**Comment by williamclot** [comment]
Thanks @huwllewellyn, this fix worked for me.

**Comment by danielzaiser** [comment]
@huwllewellyn worked like a charm, thanks

**Comment by adamdoescode** [comment]
@uv-w's suggestion worked for me where `DISABLE_MAGIC_FUNCTIONS=true` failed to fix the problem. I am using iterm with zsh 5.8 on a 2020 13' mac intel processor.

**Comment by AmjadHussainSyed** [comment]
you need to surround true with double quotes

**Comment by kohane27** [comment]
@adamdoescode @AmjadHussainSyed 

You don't need to manually add it; it's an option in the default. You just need to uncomment the following line in `.zshrc`:
```
# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"
```

**Comment by adamdoescode** [comment]
> 
> 
> @adamdoescode @AmjadHussainSyed
> 
> You don't need to manually add it; it's an option in the default. You just need to uncomment the following line in `.zshrc`:
> 
> ```
> # Uncomment the following line if pasting URLs and other text is messed up.
> DISABLE_MAGIC_FUNCTIONS="true"
> ```

My experience is that this does not work. I don't know why, but only the other solution proposed by @uv-w works for me. Interestingly, I've had this problem on both iTerm in MacOS and on Windows in WSL2 Terminal.

**Comment by timhae** [comment]
> > @adamdoescode @AmjadHussainSyed
> > You don't need to manually add it; it's an option in the default. You just need to uncomment the following line in `.zshrc`:
> > ```
> > # Uncomment the following line if pasting URLs and other text is messed up.
> > DISABLE_MAGIC_FUNCTIONS="true"
> > ```
> 
> My experience is that this does not work. I don't know why, but only the other solution proposed by @uv-w works for me. Interestingly, I've had this problem on both iTerm in MacOS and on Windows in WSL2 Terminal.

What was the suggestion by @uv-w ? It seems like they removed it/changed their name.
