### ISSUE TITLE
Support html in output

### ISSUE THREAD

**Issue by marcbachmann** [zeit/hyper#128]
I wanted to write an extension that converts urls into clickable links. But it looks like there's no way to render html.
![link](https://cloud.githubusercontent.com/assets/431376/16889797/6d60e94a-4ae9-11e6-86aa-0f77d9c85a34.gif)

**Comment by marcbachmann** [comment]
Related to https://github.com/zeit/hyperterm/issues/101

**Comment by marcbachmann** [comment]
Maybe it's a bad idea to modify the output. We can also convert the links on hover or CMD+hover.
Like iTerm is doing it.

**Comment by arronhunt** [comment]
+1

**Comment by MrRio** [comment]
See this: https://github.com/zeit/hyperlinks

**Comment by Dorian** [comment]
Having some sort of special API for rendering HTML would be (like rendering colors) would be super awesome, e.g. I really really want to be able to link to github pull requests from `#123` in my github pull requests lists (custom script I wrote).

**Comment by chabou** [comment]
I think we can close it.
@Dorian I think it can be possible to do this with some [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code). Xterm uses this to let scripts change window/term title. A plugin can intercept this sequences and use meta data inside (like URL)
