### ISSUE TITLE
character can't show as expected

### ISSUE THREAD

**Issue by jacklisheng** [zeit/hyper#1280]
I'm using macSerria, hyper 1.0.0 (1.0.0.1303), when i edit something with vim, there are some strange character like this:

<img width="382" alt="2016-12-20 7 34 26" src="https://cloud.githubusercontent.com/assets/24641416/21349243/ce5861f0-c6eb-11e6-8688-3b8331894d7d.png">

**Comment by kleinfreund** [comment]
What is a *strange* character in this example? Can’t quite follow you.

**Comment by jacklisheng** [comment]
like: 
";0;95m8 and "64;83;95m1

**Comment by MatthiasWinkelmann** [comment]
Those are fragments of control string, probably from the syntax colouring (c. f. https://en.wikipedia.org/wiki/ANSI_escape_code#Colors).
