### ISSUE TITLE
commandline parameter for windows installer

### ISSUE THREAD

**Issue by chantisnake** [zeit/hyper#1281]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows 10 version 1607 build 14393.576
- **Hyper.app version**: 1.0.0

## Issue

is there a windows installer command line parameter to allow silent install (most app has `/S` as slient), and a parameter to not popup hyper when the install is finished.

I want to create a [chocolatey](https://chocolatey.org/) package for this app, the silent install parameter is required.

**Comment by albinekb** [comment]
That would be if https://github.com/electron-userland/electron-packager has support for it, don't know 😄

**Comment by chantisnake** [comment]
Thank you for replying, I will try to figure it out.

**Comment by chantisnake** [comment]
I found a reference here: https://github.com/Squirrel/Squirrel.Windows/pull/187

`-s` do work for the installer, but after install, the hyper app pops up. I don't know this behavior (the app starts running immediately after the install) is due to the packager or the app.

**Comment by chantisnake** [comment]
I found the reference here https://github.com/Squirrel/Squirrel.Windows/issues/859

Thank you.

**Comment by chantisnake** [comment]
a little follow up, the package is up, and waiting to be approved https://chocolatey.org/packages/hyper/1.0.1
