### ISSUE TITLE
Cannot open Hyper from Context menu. 

### ISSUE THREAD

**Issue by ConstantinChirila** [zeit/hyper#1283]
- [X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 64bit
- **Hyper.app version**:  1.0.0
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I love the feature of gitbash to open it through the context menu in the folder where you are working; beats writing the whole path. I was happy to see hyper.js having that feature but it seams it doesn't work, and can't really understand why.

So when you right click to ope hyper in a particular folder, and click it: 
![layer 4](https://cloud.githubusercontent.com/assets/11059262/21358682/5ac4b122-c6d1-11e6-93ac-2e2d527b78ad.png)

I get this error: 
![layer 3](https://cloud.githubusercontent.com/assets/11059262/21358694/64c41154-c6d1-11e6-8543-63c1373c46fd.png)
"This file does not have a program associated with it for performing this action. Please install a program or, if one is already installed, create an association in the Default Programs control panel."

I tried everything, when to the default programs panel but nothing there, i reinstalled it, i even removed the key from the regedit. Nothing. Still doesn't work.
Any ideas or help would be deeply appreciated!

Thank you!
Constantin Chirila

**Comment by ConstantinChirila** [comment]
Adjusted my search query and found some other issues similar to mine, so i guess this is a duplicate.

**Comment by isseiler** [comment]
I had this issue after a few reinstalls, you can fix it by re-adding the keys in the regedit following the comment here: https://github.com/zeit/hyper/issues/1314#issuecomment-287252163

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/1133
