### ISSUE TITLE
Pressing the shift key deselects any currently selected text

### ISSUE THREAD

**Issue by naturalethic** [zeit/hyper#1284]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- **OS version and name**: OS X El Capitan 10.11.6
- **Hyper.app version**: 1.0.0.1303
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/naturalethic/008938f8120a1b5e580a8a4f1097e477
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
After selecting some text with the mouse, pressing the shift key deselects the text.  This prevents beginning a selection, scrolling up or down, and then shift-selecting to complete the range.  Thus, it is currently impossible to select more text than can fit in the currently viewable scroll region.

**Comment by ppot** [comment]
Fixed in #1218

**Comment by naturalethic** [comment]
So much for my search-fu -- thanks @ppot
