### ISSUE TITLE
Cmd+v file path into hyper shell

### ISSUE THREAD

**Issue by felixekn** [zeit/hyper#1285]
- **OS version and name**: MacOS 10.12.2
- **Hyper.app version**: 1.0.0.1303

## Request
Mac terminal allows the user to cmd+c a directory or file and cmd+v the path to said directory or file into a terminal shell. I use this feature extensively to quickly move between directories that I'm too lazy to get to via command line. It would be helpful if Hyper.app had this feature.

**Comment by ppot** [comment]
But you already can?

**Comment by timneutkens** [comment]
@ppot stops to reproduce:
1. go to finder
2. click on a file/directory
3. cmd + c
4. open terminal
5. cmd + v
6. you will see a full file/directory path pasted

Same steps in Hyper will only paste the file/directory name

Idk how they implemented that feature / if it's possible to read paste content.

**Comment by derrickpelletier** [comment]
I have a branch for this done but need someone to test the windows side. The `win32` condition is implemented but untested at all. Let me know if you can help, you can find me on the slack channel as `@derrick`!
