### ISSUE TITLE
Chrome extension/web app

### ISSUE THREAD

**Issue by christianbundy** [zeit/hyper#129]
Is it possible to run this in a browser? I'm on Chrome OS and hoping to upgrade from hterm.

**Comment by jokeyrhyme** [comment]
Related to #1362

**Comment by christianbundy** [comment]
Thanks!

**Comment by henrikdahl** [comment]
@christianbundy Continued in #1362 ✌️

**Comment by matheuss** [comment]
Actually this was the first issue, so the other one is a duplicate 😅
