### ISSUE TITLE
Release download very slow

### ISSUE THREAD

**Issue by Jameskmonger** [zeit/hyper#1290]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: N/A
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue
When downloading from the site (https://hyper-updates.now.sh/download/win), the download is very slow. It appears to be downloading at about 5 megabytes every minute and often times out.

**Comment by albinekb** [comment]
![image](https://cloud.githubusercontent.com/assets/5027156/21389578/c65c760c-c782-11e6-89cd-9a0538bf6973.png)

**Comment by albinekb** [comment]
Looks like the issue is on your end 😄

**Comment by Ulimn** [comment]
@albinekb Your reply is infuriating. From Europe, the download speed is under 100KB/s. Tested from Hungary and Germany.

**Comment by albinekb** [comment]
Someone commented but removed their comment, this is the download speed from sweden, europe. Seems fine?

![image](https://user-images.githubusercontent.com/5027156/36201555-9c8d61c6-1180-11e8-9b2a-cc752f59b3ee.png)

**Comment by Jameskmonger** [comment]
Seems fine for me now, albeit from a totally different network (still in the UK)

**Comment by albinekb** [comment]
Still fast in  🇸🇪 
![image](https://user-images.githubusercontent.com/5027156/36226582-84357d22-11ce-11e8-9829-287abf66576d.png)

**Comment by albinekb** [comment]
Doh, I know what the issue was/is. The link you have in you initial message is to the old update server hosted at now.sh, now.sh is US-only and the code was written to proxy the github download  (don't ask me why), that meant pretty slow download speeds, I'm seeing 300KB/S in 🇸🇪 .  Everything should be alright now as all the new links use github releases direct link, which is on a CDN (s3).
