### ISSUE TITLE
Windows Snap not working

### ISSUE THREAD

**Issue by johnsonjo4531** [zeit/hyper#1292]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS Version:** Windows 10, Version: 1511, OS Build: 10586.494
- **hyper version:** 1.0.0 
- **Gist link of .hyper.js:** https://gist.github.com/johnsonjo4531/fa6bac85704e3b21fb8077dd3a1aaaff: 
- **Debugger messages:** N/A _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **Reproducible on vanilla hyper:** Yes 

## Issue

Windows snap doesn't seem to work on windows 10 with hyper. The snap feature generally uses windows key+arrow key configuration and does not seem to work with hyper at the time. It is working for every one of my other apps just not hyper.

**Comment by jamdev** [comment]
I am also experiencing this issue.

**Comment by ppot** [comment]
What its Windows Sanp? Exemple?

**Comment by johnsonjo4531** [comment]
@ppot https://blogs.windows.com/windowsexperience/2015/06/04/arrange-your-windows-in-a-snap/#zMZtzjvivbPsE6p2.97 check out the snap assist section's gif it shows where you drag the window to the edge and it snaps and then it shows a snap-assist snap (where you select from available apps to snap a window in the remaining area). Hyper doesn't show up on snap-assist, it also doesn't work with the hotkey, and last of all it doesn't snap when you drag the window to the edge. I'm sure they are all related and due to the same problem.

**Comment by ppot** [comment]
@johnsonjo4531  I would tell this is a duplicate of #1128

**Comment by johnsonjo4531** [comment]
Yes, I would agree it is.
