### ISSUE TITLE
color variable for split pane borders only

### ISSUE THREAD

**Issue by dimitrieh** [zeit/hyper#1296]
Is there such a variable or how to do it otherwise with css?

```
    termCSS: `
       .spllitpane_dividers {
         background-color: red;
       }
    `,

```
doesn't seem to work

**Comment by CodeTheory** [comment]
`.splitpane_divider` should be the class you're looking for there. Looks like you have a few spelling mistakes in the selector you provided. 
I also think this should be within the `css` propert.
Could you try this instead: 
```js
css: `.splitpane_divider { background-color: red; }`,
```

**Comment by dimitrieh** [comment]
@CodeTheory 
```
css: `.splitpane_divider { background-color: red !important; }`,
```

did the trick! thanks!
