### ISSUE TITLE
Hyper quit unexpectedly

### ISSUE THREAD

**Issue by himynameisdave** [zeit/hyper#1297]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS X 10.11.5
- **Hyper.app version**: Version 1.0.0 (1.0.0.1303)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/himynameisdave/8a95c1f718dffc58aa511ffabdd80af9
- **Relevent information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Mac was asleep, then on wakeup I was greeted with this Apple standard warning!

<img width="472" alt="screen shot 2016-12-21 at 6 50 09 pm" src="https://cloud.githubusercontent.com/assets/4298089/21413823/0a1fb120-c7af-11e6-9e3f-ceb9a8242d7f.png">

Skimming through the contents of the generated report, I can't see anything that seems too out of place... 🤔  I was then able to restart it and get back to work.

I had two windows open, both fullscreen and both subdivided into three "windows" each, making six shells total. Most of these were running some background processes (like docker and grunt) at the time I noticed the issue.

**Comment by albinekb** [comment]
Did you have any other screens connected/disconnected when this happened? @himynameisdave

**Comment by himynameisdave** [comment]
Yes, one external monitor was connected at the time.
