### ISSUE TITLE
Glitches in display when using arrow keys

### ISSUE THREAD

**Issue by con-ssc** [zeit/hyper#1298]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.0.0
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
When using the arrow keys to navigate a current command, hyper display is glitching from time to time, the code is correct though if you know where your cursor should actually be.
![image](https://cloud.githubusercontent.com/assets/8189808/21422758/8cb95d9a-c839-11e6-99a3-9a3f131989f7.png)

**Comment by walston** [comment]
I've actually experienced a similar issue in the default Terminal.app...
this may be an issue with `oh-my-zsh`, i'd check their repo for possible duplicate issues

**Comment by jonathandelgado** [comment]
Related to #1174, #1180. Possibly fixed by https://github.com/Tyriar/pty.js/issues/10.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
