### ISSUE TITLE
Suddenly it stopped to work

### ISSUE THREAD

**Issue by juanbrujo** [zeit/hyper#1299]
Inspecting, I found that `shell` config makes Hyper crash. Removed that line and it's ok.

`shell: '/Library/WebServer/Documents/'`

-

Hyper 1.0.0
Electron 1.4.7
darwin x64 15.6.0

**Comment by jamo** [comment]
Shouldn't the shell point to a binary?
```
    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    shell: ''
```

**Comment by Deseao** [comment]
Did you mean to have Hyper open in that directory? Because that's not what the shell: config does. Maybe just add a cd /Library/WebServer/Documents to a bashrc or something

**Comment by juanbrujo** [comment]
🤔 interesting. thanks a lot. closing.
