### ISSUE TITLE
Control hjkl keys are bound to arrow keys

### ISSUE THREAD

**Issue by rmurai0610** [zeit/hyper#1300]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- **OS version and name**: <OS X El Capatin 10.11.5 >
- **Hyper.app version**: <1.0.0>
- **The issue is reproducible in vanilla Hyper.app**: Yes
## Issue
Control hjkl keys are bound to arrow keys.
They are mapped to ^[[D^[[B^[[A^[[C when typed after cat command.
Also these are not the case in other terminal emulators.

**Comment by rmurai0610** [comment]
Sorry it was to do with my tiling manager not Hyper

**Comment by albinekb** [comment]
@rmurai0610, just curious, what tiling window manager are you using on OS X? 😱 I didn't know that existed!

**Comment by tbodt** [comment]
@albinekb I think it's called KWM. https://github.com/koekeishiya/kwm

**Comment by rmurai0610** [comment]
@tbodt @albinekb 
Yes I use kwm as tiling manager
