### ISSUE TITLE
Hyper shows a white screen on startup and errors on quit

### ISSUE THREAD

**Issue by ChrisCinelli** [zeit/hyper#1302]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **MacOsX 10.11.6 (15G1212)**: 
- **Version 1.0.0 (1.0.0.1303)**: 
- **CMD+SHIFT+I on Mac OS does not work** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **Is Vanilla**: 

## Issue

I just downloaded Hyper. This is what I see:

<img width="543" alt="screen shot 2016-12-22 at 3 27 51 pm" src="https://cloud.githubusercontent.com/assets/153101/21443653/e7808380-c85b-11e6-851c-97b73fc013ad.png">

When I try to quit I get a few of this error (always the same). Once I was able to quit with 8 "OK"s , another time it took 28:

<img width="423" alt="screen shot 2016-12-22 at 3 33 07 pm" src="https://cloud.githubusercontent.com/assets/153101/21443766/6aa70392-c85c-11e6-8328-13cdb821c092.png">

**Comment by marcialca** [comment]
I seem to have this seem issue, is there any info?

**Comment by Alex0007** [comment]
I have white screen on Linux when enter `cd ...` command

**Comment by ChrisCinelli** [comment]
It seems solved on 1.0.1 and Mac Os X Sierra

**Comment by ppot** [comment]
Yeah  #1262
