### ISSUE TITLE
Open terminal from current folder

### ISSUE THREAD

**Issue by dmaisano** [zeit/hyper#1305]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 x64bit
- **Hyper.app version**: Version 10.0.14393
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I have recently downloaded the hyper app for windows since I use it as my main terminal in macOS and the app does work fine. However the issue I am reporting is that the in the context menu the hyper shortcut does not work. Ideally what it should do is open the app with the current directory selected from the context menu. (see below)
![hyper-issue-1](https://cloud.githubusercontent.com/assets/17837521/21459731/e34978fe-c90e-11e6-8adb-d46ee747baea.png)

Attached below is the following error that I see when I click on the option in the context menu.
![hyper-issue-2](https://cloud.githubusercontent.com/assets/17837521/21459814/a7c535ec-c90f-11e6-9778-eea15d81aa9b.png)

If anyone has any similar issues and has found a way to work around this please share. Hopefully this is enough information, if not I would be able to provide more.

**Comment by stefanivic** [comment]
This issue has already been discussed in : 
https://github.com/zeit/hyper/issues/1133
https://github.com/zeit/hyper/issues/1283

The solution : 
https://github.com/zeit/hyper/issues/1133#issuecomment-267668669

@ppot @CodeTheory

**Comment by dmaisano** [comment]
Thanks will look into it!
