### ISSUE TITLE
Issue with `npm xmas`

### ISSUE THREAD

**Issue by love4shen** [zeit/hyper#1309]
- **OS version and name**: macOS Sierra Version 10.12.2 (16C67)
- **Hyper.app version**: Version 1.0.0 (1.0.0.1303)

## Issue
`npm xmas` does not format well on `Hyper`, but does on `Terminal.app`

Snapshots:

![screen shot 2016-12-25 at 3 24 21 pm](https://cloud.githubusercontent.com/assets/8073063/21472768/bdbf131a-cab6-11e6-8c88-ebd15439ce27.jpg)
![screen shot 2016-12-25 at 3 24 30 pm](https://cloud.githubusercontent.com/assets/8073063/21472767/bdbb861e-cab6-11e6-9541-00b4d8a1b930.jpg)

**Comment by timneutkens** [comment]
Hi,
Could you try using the default theme? For me it renders nearly correct
<img width="369" alt="screen shot 2016-12-25 at 21 47 17" src="https://cloud.githubusercontent.com/assets/6324199/21472846/d99c6710-caeb-11e6-9c9c-21016441f5a9.png">

**Comment by gluons** [comment]
Same here on Windows.

- NPM 3.10.9
- Hyper 1.0.0
- Electron 1.4.7
- win32 x64 10.0.14393

**Nearly nothing:**
![2](https://cloud.githubusercontent.com/assets/4688092/21484283/9fa9548c-cbc2-11e6-9954-7fdd0204c35d.png)

**On Powershell:**
![1](https://cloud.githubusercontent.com/assets/4688092/21484289/b7bfecd4-cbc2-11e6-9f95-219d2c33fa1c.png)

**Comment by jokeyrhyme** [comment]
Working great here...

-   [hyper-snazzy](https://github.com/sindresorhus/hyper-snazzy) theme
-   [hack](https://github.com/chrissimpkins/Hack) font
-   Hyper 1.1.0 (1.1.0.1408)
-   `npm` 4.1.2
-   macOS Sierra 10.12.3 Beta (16D30a)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
