### ISSUE TITLE
Hyper angular-cli optimization

### ISSUE THREAD

**Issue by Mrtcndkn** [zeit/hyper#1311]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 

## Issue
When using angular-cli for angular 2 hyper's performance is poor.When i run the command ng serve hyper is slowing down noticeably.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
