### ISSUE TITLE
Suggestion: Ability to change theme from command line for each separate Hyper.

### ISSUE THREAD

**Issue by playeren** [zeit/hyper#1313]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue

First off - I love Hyper! It has almost entirely replaced Powershell on my Windows machine, and a super nice addition to gnome-terminal on my Ubuntu box. Thank you!

My favorite plugin is Hyperlayout, as it enables me to monitor several boxes in one window.

![image](https://cloud.githubusercontent.com/assets/1401603/21501340/559ffb40-cc47-11e6-87a6-03dc220762c9.png)

But it's hard to distinguish each box from the other, without the ability to change themes for each Hyper. 

So, I would love to able to set a theme directly from the command line - or maybe just be able to change certain variables like background color. 

Here's an example of a workspace where I use multiple gnome-terminals, and different profiles, specific to each box:

![screenshot from 2016-12-27 15-34-49](https://cloud.githubusercontent.com/assets/1401603/21501777/00b76c72-cc4b-11e6-9b7e-aaf3e4bee728.png)

**Comment by albinekb** [comment]
This looks like you want? Closing for now, reopen if not.
https://github.com/chabou/hyper-autoprofile

**Comment by playeren** [comment]
Yes, that looks great! Thanks!

**Comment by chabou** [comment]
Do not hesitate to give me your feedback ! I could not test it in many configurations/situations. Issues welcome ;)

**Comment by albinekb** [comment]
Also, have a look at this: https://github.com/bnb/awesome-hyper for more awesomeness!
