### ISSUE TITLE
Context menu item does not work in drives other than the system partition

### ISSUE THREAD

**Issue by umstek** [zeit/hyper#1314]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 1607 Build 14393.576 Windows 10
- **Hyper.app version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevent information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

The context menu item: `Open Hyper Here` doesn't work when clicked in partitions other than where the software is installed. I read the issues #1133, #1305 and #1283 but this is different from those: an error is not displayed, but **Hyper** opens with the default directory as selected directory in console.  

I guess this is happening because Windows doesn't change the drives with `cd` command, but with the `<drive letter>:` itself.

**Comment by lightning-zgc** [comment]
Yeah，I catched the same problem.
I fixed it with "regedit".Just use "Run->regedit" to find "HKEY_CLASSES_ROOT\Directory\Background\shell\Hyper\command" add data "C:\Users\YOUR_USER_NAME\AppData\Local\hyper\app-1.3.1\Hyper.exe "%V""
Hope the source code be updated and fixed soon!

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/1133

**Comment by turkeyphant** [comment]
Having this same issue even after verifying the registry entry and rebooting.
