### ISSUE TITLE
Dropping an external image to hyper screen causes failure

### ISSUE THREAD

**Issue by anonrig** [zeit/hyper#1319]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Latest OS X
- **Hyper.app version**: Latest
## Issue
Dropping an image from Chrome to Hyper disables the usage of Hyper. It just shows the image and nothing else.

Best,
Yagiz

**Comment by albinekb** [comment]
What did you expect to happen? @anonrig (apart from hyper not freezing)

**Comment by anonrig** [comment]
@albinekb Actually, I believe its better to just add the image's URL to terminal.
