### ISSUE TITLE
Help Creating a Plugin to Run Commands on Startup

### ISSUE THREAD

**Issue by DanInglis** [zeit/hyper#1321]
Hello, there is currently no way to run commands automatically before hyper starts so I want to make a plugin to do this.

I'm trying to use the onApp method and send a command to the terminal. Something like:

exports.onApp = (app) => {
    app.runCommand('echo Hello World');
}

I've looked through the docs and there I can't think of a good way to implement this.

Any input is greatly appreciated :)

**Comment by ppot** [comment]
You can't by that way. At the time the terminal isn't rendered so you can't invoke pty actions.

**Comment by DanInglis** [comment]
Hi again, I tried a different approach using middleware and exec (similar to https://github.com/hharnisc/hypercwd) which doesn't work because exec creates a new shell and i want the modifications to be done to main shell. Is there a way i can send commands to the shell using process (like u can to the child-process using exec)? 

Also is there a way I can access the terminal directly and write to it? Like this from term.js:
write(data) {
    this.term.io.writeUTF8(data);
  }

Thanks

**Comment by curz46** [comment]
Might this be possible with the `onWindow` method?

https://github.com/zeit/hyper/blob/5773a83dc3211bd76efe4803176ab8b3df4a14be/app/index.js#L310
https://github.com/zeit/hyper/blob/7df5cbac0832ab2e14b20d9fb3a7e371bf2018ae/app/session.js#L73

Perhaps you could use `window.sessions` and run `Session#write(data)` on each?

**Comment by DanInglis** [comment]
@curz46 I ran with your idea for a bit and came across this issue.

`exports.onWindow = function (win) {`
  `win.sessions.get(uid);  //works fine`
  `win.sessions.get(uid).write('blah');  //crashes`
`};`

I'm guessing we don't have access to the write function. I tried bypassing write and just doing `win.sessions.get(id).pty.stdin.write('hi');` but that doesn't work either

Is there some way I can use the function `rpc.on('data', ..)` perhaps?
https://github.com/zeit/hyper/blob/5773a83dc3211bd76efe4803176ab8b3df4a14be/app/index.js#L256

**Comment by curz46** [comment]
I managed to get it write to the terminal with this:
```
exports.onWindow = function (window) {
    setTimeout(() => {
        window.sessions.forEach(session => {
            session.write('clear')
        })
    }, 2500)
}
```
The timeout was the minimum milliseconds I had to wait for it to be visibly written to the terminal. I can't actually find an API method that is called once a session has completely loaded, so maybe you'll have to constantly query if a new session is available using `setInterval` or something. Note that the command here isn't sent, I'm not sure how to fake an "enter".
https://gyazo.com/16f85392fd827ef667865a245bafee88

**Comment by DanInglis** [comment]
You can enter by sending the hex code for enter/return to the terminal the same way you wrote to the terminal. `session.write('\x0a');`

Also I was able to get output with a Timeout as low as 1000. I'm on OSX Sierra, maybe that has something to do with it.

This is my current code and it works perfectly:

`exports.onWindow = function (win) {`
 `     setTimeout(() => {`
 `       win.sessions.forEach(session => {`
`            session.write('echo hello world');`
`            session.write('\x0a');`
`        })`
`    }, 1000)`
`};`

I have created a git repo if you would like to work together on this: https://github.com/DanInglis/hyper-run
