### ISSUE TITLE
White screen when running bash script

### ISSUE THREAD

**Issue by benjaminprojas** [zeit/hyper#1323]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra
- **Hyper.app version**: Version 1.0.0 (1.0.0.1303)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/benjaminprojas/e9ebb7065b3df1e792304b1f53fe84fa
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
I am just trying to run a bash script.  When I type `bash firstrun.sh` the screen goes fully white:
![image](https://cloud.githubusercontent.com/assets/962530/21567375/b449818c-ce79-11e6-903f-7da6d4329788.png)

![image](https://cloud.githubusercontent.com/assets/962530/21567381/bc6522ae-ce79-11e6-9b0b-f4c5b4982ffe.png)

At that point I can't do anything.  When I try to quit I get this error:

![image](https://cloud.githubusercontent.com/assets/962530/21567390/cb9b77dc-ce79-11e6-8409-477ce580fd11.png)

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at WebContents.send (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/api/web-contents.js:93:15)
    at sendToEmbedder (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:121:16)
    at WebContents.<anonymous> (/Applications/Hyper.app/Contents/Resources/electron.asar/browser/guest-view-manager.js:128:7)
    at emitOne (events.js:101:20)
    at WebContents.emit (events.js:188:7)
```

**Comment by ppot** [comment]
Related to URL interpretation: solved in #1259
