### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by LuisSchulte** [zeit/hyper#1324]
How can I connect my windows pc with Hyper via SSH to my Raspberry Pi with Raspbian? I'm sorry, I've no idea how I could do that and i found nothing on google.

Happy new year 2017

**Comment by einfallstoll** [comment]
I'm not sure what your knowledge level is, therefore I try to explain as much as I can:

A terminal (like `Hyper` or `cmd`) is just an interface to operate with your computer. You can for example move files around and delete them. To be able to do just that there has to be an application that does just that. If you want to delete a file there has to be an application installed called `del.exe`, luckily this is some sort of standard and Windows already includes lots of useful application like `del.exe`. So if you type `del my_file.txt` it will look up for the application `del.exe` within all the directories you specified in the environment variable `PATH` execute that application and apply all the parameters (`my_file.txt` in the example) to that application.

This means in conclusion that if you want to use an application `ssh` you have to "install" it before. As far as I know the easiest way to use `ssh` on Windows is to install `putty.exe`.

**Comment by LuisSchulte** [comment]
Ahhh... 

This is an aha-moment for me. Thanks for your answer. I already using Putty, but I thought I can use Hyper for SSH instead of Putty, because it looks better with all the plugins.

Now I've learnt something new again.
