### ISSUE TITLE
Icons cut off in 1.0.1

### ISSUE THREAD

**Issue by controversial** [zeit/hyper#1327]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.2
- **Hyper.app version**: 1.0.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/controversial/d08d16c4fd1c9df8
- **Relevent information from devtools** N/A

## Issue
In Hyper 1.0.1, many rendering issues have been fixed, but one has been introduced: many of the icons in my prompt are cut off 😢  See the right prompt here:

<img width="1529" alt="screen shot 2017-01-01 at 3 45 03 pm" src="https://cloud.githubusercontent.com/assets/10377391/21583047/4b7799b8-d03c-11e6-919c-17e696cdbeae.png">

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
