### ISSUE TITLE
Paste with ctrl-v doesn't work properly

### ISSUE THREAD

**Issue by juicygoose** [zeit/hyper#1328]
When doing a copy paste, the paste part on hyper only works if I right click + ctr-V. Only a ctr-v will never work.

-

Hyper 1.0.1
Electron 1.4.7
win32 x64 6.1.7601

**Comment by superherointj** [comment]
Copy something (a text).  Try to paste using:
1) Ctrl+V => Doesn't work.
2) mouse right click => Doesn't work.
3) Menu - Edit - Paste => Works

** Note: There is a shortcut in Menu item for paste. And this shortcut doesn't work. (CTRL+V)

-

Hyper 1.0.1
Electron 1.4.7
win32 x64 10.0.14393

**Comment by deyvisonrocha** [comment]
On Linux too, same behavior!

**Comment by matheuss** [comment]
Yo @juicygoose @deyvisonrocha please test #1406 🙌

**Comment by shersh** [comment]
It's still no working =(
