### ISSUE TITLE
Full refresh makes terminal transparent

### ISSUE THREAD

**Issue by juicygoose** [zeit/hyper#1329]
Full refresh triggers the invisibility of the terminal, only borders can be seen 
-
![image](https://cloud.githubusercontent.com/assets/15606243/21589235/1662cc2a-d0f0-11e6-8d06-788d4bafa955.png)

Hyper 1.0.1
Electron 1.4.7
win32 x64 6.1.7601

**Comment by albinekb** [comment]
Does this happen with the default config and no plugins?

**Comment by matheuss** [comment]
This should have been fixed by https://github.com/zeit/hyper/pull/1262 😰 😩

**Comment by juicygoose** [comment]
I just have plugin hyperpower!

**Comment by ppot** [comment]
Yeah @matheuss  Should had been! Hmm.... @juicygoose Can you remove `hyperpower` ?   and test again?

**Comment by juicygoose** [comment]
Sure Im trying

**Comment by juicygoose** [comment]
Still occurring without any plug in ...

**Comment by deividfortuna** [comment]
Same problem here too. 
Win7 x64

**Comment by JarnoNijboer** [comment]
This seems a duplicate of #1026

**Comment by maghrout** [comment]
The same problem is happening to me and it isn't allowing me to add any plugins it just crashes and says check dev tools but I can't because it reloads almost invisible!

**Comment by Stanzilla** [comment]
@ppot @rauchg this is still happening, even without any plugins.

Full reload => fully transparent window

**Comment by ppot** [comment]
Can you tell what OS are you on @Stanzilla

**Comment by Stanzilla** [comment]
@ppot Windows 8.1

**Comment by Stanzilla** [comment]
Anyone looking into this? it's pretty annoying :(

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
