### ISSUE TITLE
BrowserWindow property "backgroundColor" doesn't treat rgba() values correctly

### ISSUE THREAD

**Issue by theblindprophet** [zeit/hyper#133]
Inside `.hypterm.js` you can specify a background color by name, hex, or rgb.
# B3B20808 = rgba(178, 8, 9, 0.5)

Hex version **works** for body but **not** for header.
rgba() version does **not work** as expected.

Hex:

<img width="854" alt="screen shot 2016-07-15 at 7 19 02 pm" src="https://cloud.githubusercontent.com/assets/7903413/16890896/0513f2ec-4ac1-11e6-8067-67bba3c06c96.png">

rgba():

<img width="851" alt="screen shot 2016-07-15 at 7 16 49 pm" src="https://cloud.githubusercontent.com/assets/7903413/16890853/b95c92a0-4ac0-11e6-8e74-5e61bcaa284b.png">

**Comment by Banjerr** [comment]
Just noticed this as well. I wasn't sure if might be a limitation of Electron. But I also didn't know that hex values or names could be used, so I'm gonna try the hex now; that might be good enough for me. Great work though!

**Comment by chabou** [comment]
I just tried and it seems fixed.
Feel free to reopen
