### ISSUE TITLE
Bluescreen when closing a tab of Windows 10 bash shell (APC_INDEX_MISMATCH)

### ISSUE THREAD

**Issue by prappe** [zeit/hyper#1330]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro Insider Preview - Build 14986.rs_prerelease.161202-1928
- **Hyper.app version**: 1.0.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/prappe/98b4788f1619d2163cf9bf78f84f40f5
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

I configured hyper to launch the Windows 10 bash shell (or, well, _"Linux Subsystem"_, which sounds cooler), and it appeared to work correctly at first, but then disaster struck. I tried nano and encountered a few problems:
- no cursor movement with arrow keys
- typing occasionally didn't work (but was limited to one line because of no cursor movement anyways)
- no hotkeys or key combinations (ctrl+w etc) work

But now, I can't really use it at all. vi didn't work either, with similar problems as nano, but I'm also still learning it, so I may have messed something up that prevented it from working.
However, the main problem is that when I attempt to close a tab that is running the bash shell, no matter if it's in the middle of processing something or not, I get a bluescreen with the stop code `APC_INDEX_MISMATCH`. Here is a link to an analysis of a dump file from a bit ago, on 1.0.0: https://gist.github.com/prappe/c430b3e5f4252d36ce328586a3198a33
Any more info you need or help you can provide is greatly appreciated.

**Comment by ppot** [comment]
`no cursor movement with arrow keys` related to bashOnWindows problem. Not hyper
`for hotkeys there is issues oppened`

**Comment by paulcbetts** [comment]
There's nothing Hyper can do here, this is an issue with WSL. File it on the WSL repo, they can have a look and hopefully fix it by the next build

**Comment by prappe** [comment]
That's a shame. I'll go submit the issue over there, then. Thanks anyways, you two.
