### ISSUE TITLE
unicode-node css style

### ISSUE THREAD

**Issue by enguerran** [zeit/hyper#1332]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra 10.12.2
- **Hyper.app version**: 1.0.1.1369
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/enguerran/c7c56adcaca07b9679daad7328d8bbfd
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: [zsh](http://www.zsh.org/) + [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) + [bullet-train theme](https://github.com/caiogondim/bullet-train-oh-my-zsh-theme)

## Issue

I have a `unicode-node` style issue: on the left, the actual css rule with `unicode-node { display: inline-block; }`, on the right, a modified css rule with `unicode-node { display: inline; }`.
My custom emojis (goat + gust of wind) are better aligned on the right.

Do you think it is a issue on hyper or may it be a issue on another element in my terminal stack (MacOS + hyper + zsh + oh-my-zsh + bullet-train + Powerline font)?

<img width="1440" alt="screen shot 2017-01-03 at 16 33 06" src="https://cloud.githubusercontent.com/assets/701648/21612808/e4240f56-d1d2-11e6-898d-227c22602384.png">

**Comment by tkisme** [comment]
same result,and unicode-node { display: inline; } works

**Comment by storvik** [comment]
Same goes for me, but.. 

Changing `inline-block` to `inline` fixes icons, but the cursor shifts (due to icon widths?). 
<img width="483" alt="screen shot 2017-01-06 at 10 53 57" src="https://cloud.githubusercontent.com/assets/3438604/21714713/ba71fbe8-d400-11e6-9752-58835b179a66.png">

Turning on newline in the prompt makes it bearable. This also makes tmux usable again, see my comment here #1156. As long as you dont split the window vertically 
<img width="958" alt="screen shot 2017-01-06 at 11 09 41" src="https://cloud.githubusercontent.com/assets/3438604/21714888/9979b16e-d401-11e6-9acd-a478c370ecf6.png">

**Comment by ohc192** [comment]
I found this to be driving me nuts with the vim plugin airline. everything renders correctly in this terminal except for the trigram for heaven glyph used to display the line numbers at the bottom. You can see what i'm talking about in this other issue for more information. I've attached a screenshot with the css patched for the unicode node so you can see what i'm referring to.

broken:
<img width="881" alt="screen shot 2017-01-09 at 1 46 29 am" src="https://cloud.githubusercontent.com/assets/7446183/21758891/d303a1e8-d60d-11e6-89f0-becf4f1d4eef.png">

patched:
<img width="874" alt="screen shot 2017-01-09 at 1 47 09 am" src="https://cloud.githubusercontent.com/assets/7446183/21758890/d3030e54-d60d-11e6-9a66-4d27b4381aa1.png">

**Comment by schmittyjd** [comment]
If i might ask. Where are you guys setting this in your ``.hyper.js`` file? So far I have tried setting it in css and termCss but neither has worked, if i change it from the dev console it does work however

**Comment by FunkySamuel37** [comment]
@schmittyjd 
this will be work, but I don't know why it will not working after i use this `hyperterm-retro` plugin
```
termCSS: `
  span.wc-node.unicode-node {
    display: inline;
  }
`
```

**Comment by enguerran** [comment]
I close the issue because new versions are out and if there is still an issue, someone will reopen it.
