### ISSUE TITLE
Hyper glitched out

### ISSUE THREAD

**Issue by christoga** [zeit/hyper#1333]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac OS X 10.11.6**: 
- **Hyper.app 1.0.1 (1.0.1.1369)**: 
- **https://gist.github.com/christoga/d5c16ecb8b76c35143fd00695a877f54**: 
- Dev Console Error: <br>**Unknown OSC code: "1"** 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
I've used the same configuration as I used in the old Hyperterm app, somehow it doesn't work how it was supposed to work, is there something wrong that I miss/did?

Preview: http://imgur.com/a/18Jtr

**Comment by albinekb** [comment]
If you move your config, and restart hyper (to get the default config) Do you still get this problem? @christoga

**Comment by christoga** [comment]
I don't know what happen, but somehow it doesn't show the glitch anymore. Thanks for helping tho @albinekb
