### ISSUE TITLE
How to detect when a window is split vs new tab vs new window?

### ISSUE THREAD

**Issue by DanInglis** [zeit/hyper#1335]
I am creating a plugin and I need to detect a split, new tab and new window. I tried using the onWindow function but that only seems to run on when hyper first opens.

Also, how would I determine the uid of the new window?

Thanks

**Comment by chabou** [comment]
You should use a middleware and intercept some action types:
* TERM_GROUP_REQUEST (new tab or new window if it is the first TermGroup)
* SESSION_REQUEST or SESSION_ADD (new pane)
