### ISSUE TITLE
Unicode characters are crowded together, display unreadable

### ISSUE THREAD

**Issue by fcharlie** [zeit/hyper#1336]
No matter what font I choose, hyper Chinese it is displayed, is crowded with。

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04 x86_64

- **Hyper.app version**: Hyper 1.0.1
- **Link of a [.hyper.js](https://gist.github.com/fcharlie/c0f00aa0194d858a96a0f7a19d3688cb) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

![2017-01-04 10-16-52](https://cloud.githubusercontent.com/assets/6904176/21630137/5c17ce62-d269-11e6-8fba-4583a7cf1cc3.png)

**Comment by audunolsen** [comment]
I can replicate this issue on macOS Sierra 10.12.1 on hyper 1.0.1 when displaying emojis.

**Comment by dionisokan** [comment]
Same issue can be replicated on Hyper 1.0.1, macOS 10.12.2 displaying CJK characters.

**Comment by wesbos** [comment]
Same here - started with 1.0.1 

![](http://wes.io/ieom/content)

**Comment by BirkhoffLee** [comment]
Same here

**Comment by tibotiber** [comment]
+1, started with Hyper 1.0.1, on MacOS 10.12.2, using powerline font
<img width="319" alt="screen shot 2017-01-10 at 11 14 54 pm" src="https://cloud.githubusercontent.com/assets/5635553/21811667/7ba6c7e8-d78b-11e6-9a62-933b4ab0c8b8.png">

**Comment by ohc192** [comment]
I think it's the same issue as I noted in issue (unicode node css style #1332), you can fix it temporarily doing what I did to change the unicode-node css.

**Comment by jasondewitt** [comment]
I have the same problem on Debian Jessie on Hyper 1.1.0
[.hyper.js](https://gist.github.com/jasondewitt/c8bbbcbd223d264099f01e518b02dc76)

![hyper](https://cloud.githubusercontent.com/assets/30046/21826054/afbafbca-d74b-11e6-8324-a77aaf02563e.png)

**Comment by maxshaw** [comment]
```
.unicode-node {
    width: 1.15em;
}
```

**Comment by tibotiber** [comment]
needs reopening, see 2e58e56

**Comment by Shadowys** [comment]
Unicode display still doesnt work. I'm using the WSL and I tried to see if it was a problem with WSL, but apparently the pantheon-terminal that I'm running WSL shows it just fine.

From hyper:
![image](https://cloud.githubusercontent.com/assets/2587165/26289435/a751b5a2-3ed2-11e7-9c21-f612cfdb8df1.png)

From WSL-xserver-pantheon-terminal
![image](https://cloud.githubusercontent.com/assets/2587165/26289439/b53b4796-3ed2-11e7-8167-5ae1ce7eedf9.png)

**Comment by lucasqueiroz** [comment]
Is there any updates on this?
In the current version of hyper, unicode chars are still cowded together, but they at least show correctly when you don't have a background color. But that also happens with the default terminal in ubuntu, so I'm not really sure what to do...
If anyone knows any fix for that, please let me know

**Comment by Shadowys** [comment]
@lucasqueiroz i have since used xserver on windows to host pantheon-terminal instead

**Comment by lucasqueiroz** [comment]
@shadowys hmmm... Is it as "personalizable" as hyper? With the transparency on mac and etc? (I also use a macbook so I wanted to have it in both computers...)

**Comment by Shadowys** [comment]
http://dobsondev.com/2014/02/21/customizing-your-terminal

I believe on a Mac iterm2 should be what you need. Hyper is what I might use on Windows because there is not many good terminals but now that  Linux terminals can run on it I don't see the need to use hyperterm. 

I just chose pantheon term because I'm familiar with it but there are tons of emus there u can pick and choose.

**Comment by lucasqueiroz** [comment]
None of them are as "customizable", they don't have nice themes and stuff (and the title bar doesn't get "themed" either...). I really wish this was fixed...

**Comment by Shadowys** [comment]
I'm not sure what you mean by customization. [Suckless terminal](http://st.suckless.org/) allows you to compile the themes you want, GNOME terminal allows you to customize the themes and stuffs etc etc

Unless you mean customizing the GUI, which would then be different, and there are GTK skins for that.

**Comment by lucasqueiroz** [comment]
I mean like hyper themes and plugins

**Comment by DuIslingr** [comment]
hyper quite simply is the best terminal for theming and stuff. no other terminal can really compete. especially once hyper works out a lot of its kinks and stuff it currently has. Usability wise it does have a ways to go still.

**Comment by carlosvigil** [comment]
![screen shot 2017-07-25 at 3 29 11 pm](https://user-images.githubusercontent.com/18217279/28589912-17db06cc-714e-11e7-816f-addebeae2f46.png)

**Comment by Smona** [comment]
I've managed to hack together a fix for my powerline use case:
![2018-02-12_16-50-12](https://user-images.githubusercontent.com/7091399/36124215-dea58eac-1014-11e8-96c5-a3146874286a.png)

``` css
.unicode-node {
  position: relative;
  height: 96%;
  padding-top: 1px;
  margin-top: -1px;
}
```

Since the issue complicates when you change the width of unicode characters (messing up the cursor position), i just moved them on top of the other characters and adjust the alignment manually. You might need to change the values a bit depending on your font settings and I don't think it would help with unicode language characters, but it solves the powerline issue.

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
