### ISSUE TITLE
Option to retain directory on pane split

### ISSUE THREAD

**Issue by jakearchibald** [zeit/hyper#1337]
iTerm has a nice little feature where new windows/tabs/splits will use the same directory as their parent.

Personally I like new tabs & windows to start in `~`, but I like split panes to start in the same directory as their parent.

Loving Hyper so far!

**Comment by pete-otaqui** [comment]
There's a plugin for that.

https://www.npmjs.com/package/hypercwd

See this list:

https://github.com/bnb/awesome-hyper

**Comment by jakearchibald** [comment]
omg I went through that list but missed that one. Sorry!
