### ISSUE TITLE
Feature request: Don't require the user to have `npm` installed (for plugins)

### ISSUE THREAD

**Issue by sdegutis** [zeit/hyper#134]
I don't have `npm` installed, so I couldn't use any plugins unless I install `npm`, which I don't want to do.

If HyperTerm aims to be a stand-alone app, it should either come with its own plugin system, or come with its own `npm` stuff internally, which the user doesn't need to know about.

**Comment by SilverEzhik** [comment]
You really won't survive long in this webscale world without npm.

**Comment by sdegutis** [comment]
@SilverEzhik Not every developer using a terminal is a web developer. Some of us more crazy ones still enjoy writing stuff in C ;)

**Comment by SilverEzhik** [comment]
@sdegutis Well, I guess I just don't really see anybody using this without being neck-deep in webtech.

**Comment by mkscrg** [comment]
Big :+1: for reducing HyperTerm's system requirements. Seems in-progress from #381 #282 #277

**Comment by pcattori** [comment]
👍 especially since the [install instructions](https://github.com/zeit/hyper#usage) do not mention `npm` at all. Even if it were documented, still would be nice if I wasn't exposed to the `node`/`npm` dependency as a user

**Comment by MAPESO** [comment]
@sdegutis @mkscrg  @pcattori  This problem is already solved in the **Canary version 9** ❤️ 
![hyper canary 9](https://user-images.githubusercontent.com/16585386/34961523-319f6cfc-fa05-11e7-8e14-f9f7d298c083.png)

**Comment by sdegutis** [comment]
Cool! So there’s no external dependencies?

**Comment by MAPESO** [comment]
@sdegutis Nop, you should just download hyper and update to the **Canary version** ❤️ 🎉

**Comment by chabou** [comment]
v2 is out 🎉
