### ISSUE TITLE
Bash on Windows Keypresses

### ISSUE THREAD

**Issue by Rapidfire66** [zeit/hyper#1342]
When using the Windows 10 Linux Subsystem (Bash on Windows), and using Hyper, Cannot use my arrow keys to navigate through command input and when using nano.

Link to .hyper.js: https://gist.github.com/Rapidfire66/f0f9872b5f9f1f80a0a88784a4c4aa73

**Comment by zbuttram** [comment]
Duplicate of #1127, real issue is with the WSL itself at Microsoft/BashOnWindows#111

**Comment by albinekb** [comment]
Closing, duplicate of #1127, thanks @zbuttram! ⭐️
