### ISSUE TITLE
Improvements to the browser

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#1344]
- `target=_blank` links should open in a new full browser tab
- cmd+click should open in a new full browser tab
- cmd+R should refresh
- there should be a subtle indicator of focus
- hovering a link should render a chrome-like bottom-left link overlay
- quitting the browser doesn't give focus back to the owner term
- hovering the top portion of the screen could reveal a simple overlay toolbar

I think these are changes we might want to ship in our first core plugin `hyperweb` as opposed to bloating `hyper`.

Tagging @CodeTheory and @evilrabbit to start working through some designs

**Comment by stefanivic** [comment]
@rauchg we should also focus on getting the browser to work on Linux and Windows, as it's not working at the moment. :D

**Comment by ppot** [comment]
@stefanivic Can you explain why it's not working?

**Comment by stefanivic** [comment]
@ppot on Windows https://github.com/zeit/hyper/issues/1403 on Linux you just get a white screen.

**Comment by therealplato** [comment]
I ran `screen` and then `http://isup.me`.

I can't figure out how to close the browser and return to my terminal prompt / screen session.

I tried cmd-w, ctrl-w, esc, backspace expecting one of these to work. I can close the terminal tab, but reattaching `screen -x` brings the browser window back.

**Comment by stefanivic** [comment]
@therealplato try `ctrl+shift+c`

**Comment by therealplato** [comment]
thanks. figured out the behavior. 1.1.0.1408 on OSX Sierra:

>Given I have typed `http://isup.me` at the hyper prompt and pressed enter and see the browser:
When I press control-C
Then I expect the browser to quit
But actually it stays open

>Given I have typed `http://isup.me` at the hyper prompt and pressed enter and see the browser:
When I click the browser, and *then* press control-C
Then the browser quits, as expected
