### ISSUE TITLE
Accent encoding

### ISSUE THREAD

**Issue by theiThomas** [zeit/hyper#1348]
- **OS version and name**: macOS Sierra
- **Hyper.app version**: 1.0.1.1369

## Issue

The accents are badly encoded.
examples : é -> `<C3><A9>`
                   ô -> `<C3><B4>`

**Comment by matheuss** [comment]
Could you provide more info? 🤔 When this happens?
![screen shot 2017-01-06 at 4 31 24 pm](https://cloud.githubusercontent.com/assets/4721750/21728499/aa3c8702-d42d-11e6-8a9b-d47c1f21be57.png)

**Comment by theiThomas** [comment]
Sometimes i have :[
![capture d ecran 2017-01-06 a 19 39 56](https://cloud.githubusercontent.com/assets/2513160/21728738/12503932-d448-11e6-961e-8a09d2421b62.png)
](url)

é -> e??

Sometimes i have :[
![capture d ecran 2017-01-06 a 19 40 21](https://cloud.githubusercontent.com/assets/2513160/21728755/25bf1196-d448-11e6-92c3-866301e0c698.png)
](url)

**Comment by slogmen** [comment]
Same problem here with german umlauts(äöü). I'm using hyper after a clean Install without plugins and with zsh on macOS 10.12.2 and QWERTZ(German) keyboard layout.

**Comment by chabou** [comment]
seems related to locale
```
chabou@DeLorean: ~
$ locale
LANG="fr.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=


chabou@DeLorean: ~
$ ls /tmp/dévelop
'/tmp/d'$'\303\251''velop'

chabou@DeLorean: ~
$ export LANG="fr_FR.UTF-8"

chabou@DeLorean: ~
$ ls /tmp/dévelop
/tmp/dévelop
```

But there is a strange thing (in bahs and zsh):
```
chabou@DeLorean: ~
$ ls -l /tmp/dévelop
-rw-r--r-- 1 chabou wheel 0 jan  7 16:55 /tmp/dévelop

chabou@DeLorean: ~
$ ls -l /tmp/
total 0
-rw-r--r-- 1 chabou wheel 0 jan  7 16:55 develop
```
Does not happen in Terminal.app

**Comment by YugoCode** [comment]
Is there any update? Still cannot write or display German Umlaute (ä,ö,ü,ß).

**Comment by schneyra** [comment]
Same for me.

**Comment by chabou** [comment]
@schneyra We're tracking this work over here (with workaround explained): #607 
There is an outdate PR here: https://github.com/zeit/hyper/pull/605
