### ISSUE TITLE
Cannot type Chinese characters

### ISSUE THREAD

**Issue by BirkhoffLee** [zeit/hyper#1351]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.2 (16C67)
- **Hyper.app version**: Version 1.0.1 (1.0.1.1369)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/BirkhoffLee/8a6a812de8395ed4bc0662e9bd8ea424
- **Relevant information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
```
No definition for keyCode: 229
```
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

I'm a Chinese user, and I type some Chinese characters in my terminal for sure. I just tried Hyper today and found that I cannot type any Chinese characters into Hyper terminal. Here's a video comparison:

How it should be:
![capto_capture 2017-01-07_07-46-45_pm](https://cloud.githubusercontent.com/assets/8148095/21741486/5211f202-d512-11e6-945c-4d451969920e.gif)  

What Hyper does:
![capto_capture 2017-01-07_07-44-32_pm](https://cloud.githubusercontent.com/assets/8148095/21741488/545149a0-d512-11e6-9515-a43b42a871b6.gif)

I'm using a third-party Chinese Pinyin input here: http://pinyin.sogou.com/mac/
I've also tried the built-in Chinese Pinyin input but It's still not useable for Hyper.

**Comment by alexskc** [comment]
Also affects Linux Japanese input. ibus input is ignored completely.

**Comment by maxshaw** [comment]
same bug for ace editor.

**Comment by krlight** [comment]
Same problem on macOS 10.12.2 with Hyper 1.1.0. Neither Japanese nor Chinese input works.

**Comment by dingyi** [comment]
yeah same here.

![Uploading Screen Shot 2017-01-26 at 21.17.28.png…]()

**Comment by neetopia** [comment]
same bug, just installed Hyper today

**Comment by haio** [comment]
same bug

**Comment by jeantimex** [comment]
+1

**Comment by haio** [comment]
#1535

**Comment by gsklee** [comment]
Maybe related: #1536

**Comment by yueqianzhang** [comment]
+1

**Comment by wy-z** [comment]
+1

**Comment by umisama** [comment]
+1

**Comment by Mesamo** [comment]
+1

**Comment by ShineSmile** [comment]
#2014 
`No definition for keyCode: 229`

**Comment by TomazWang** [comment]
+1

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
