### ISSUE TITLE
Powerline symbols not rendering correctly

### ISSUE THREAD

**Issue by BirkhoffLee** [zeit/hyper#1352]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.2 (16C67)
- **Hyper.app version**: Version 1.0.1 (1.0.1.1369)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/BirkhoffLee/8a6a812de8395ed4bc0662e9bd8ea424
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N
/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

This explains everything. Look at the branch symbol.  
![screen shot 2017-01-07 at 8 02 42 pm](https://cloud.githubusercontent.com/assets/8148095/21741543/4662cd6c-d514-11e6-81ae-7168c1537383.png)

**Comment by wesbos** [comment]
Same issue reported over at 

https://github.com/zeit/hyper/issues/1336
