### ISSUE TITLE
Tmux copy mode issues

### ISSUE THREAD

**Issue by Addisonbean** [zeit/hyper#1358]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.2
- **Hyper.app version**: 1.0.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Addisonbean/08a522b984ea26b4c67a71584caf0030
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: requires tmux (using tmux version 2.3)

## Issue

When using tmux with mouse support (`set-option -g mouse on`), tmux only recognizes the mouse if used on the first 95 columns. After that, trying to click or drag on the screen inside of tmux causes weird characters to be entered. It seems like the characters entered depend on the row I click or dragging on. This does not happen when using keyboard shortcuts to use tmux's copy mode, only when using the mouse. Here is a gif of me clicking and dragging on various places on the screen to show what happens:

![](http://g.recordit.co/uhWAkHqNCs.gif)

Also, yanking text in tmux occasionally causes it to disappear, but highlighting it again with tmux will bring it back. Here is an example of that:

![](http://g.recordit.co/ctbzUGCUnb.gif)

To clarify, the only text that disappears is what I copied, not what was pasted. It does not consistently happen either, it seems to depend on the location that I copy from. I also tried copying text without the mouse in copy mode with the keyboard shortcuts, and the same thing happened.

Here is a gist of my `~/.tmux.conf` incase that helps: [~/.tmux.conf](https://gist.github.com/Addisonbean/04fae7c50b62456c28fd7cfc08c45e5c)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
