### ISSUE TITLE
Relying on SESSION_PTY

### ISSUE THREAD

**Issue by rgbkrk** [zeit/hyper#136]
I'd love to use this in tandem with special escape codes from, e.g. IPython/Jupyter to display inline interactive graphics and tables. I noticed that an extension can listen in on `SESSION_PTY`, though I'm wondering if I would need to get some later aggregation and reduction on PTY data.

Do you have any tips for using the shell output data or otherwise?

**Comment by chabou** [comment]
Yes, you need to aggregate PTY data (with ANSI escapes) like this plugin: https://github.com/chabou/hyper-autoprofile
