### ISSUE TITLE
Incorrect cyrillic filenames

### ISSUE THREAD

**Issue by lamartire** [zeit/hyper#1363]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 14.04
- **Hyper.app version**: 1.0.1
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
All cyrillic names not correctly rendered.

![image](https://cloud.githubusercontent.com/assets/13414205/21760037/09e98fe6-d65a-11e6-8cee-febb7e3f49d5.png)

**Comment by sashamjolnir** [comment]
as mentioned at #1204 you should add
```
export LANG=ru_RU.UTF-8
export LC_CTYPE=ru_RU.UTF-8
```

in to your .bash_profile or .zshrc

![2017-01-11 13 30 52](https://cloud.githubusercontent.com/assets/8746547/21835667/336fdfec-d802-11e6-977a-d251e2fcda79.png)

**Comment by lamartire** [comment]
@sashamjolnir yeah, it's work!
Thank you! :cake:
