### ISSUE TITLE
Cannot build Hyper.app

### ISSUE THREAD

**Issue by alberto2000** [zeit/hyper#1365]
- **OS version and name**: macOS Sierra 10.12.2
- **Hyper.app version**: 1.0.1.1369
- https://gist.github.com/alberto2000/195891691d35643abb47e928330255f1

After running `$ npm run pack` I get this error (I exchanged my name and identity hash for ***):

> Rebuilding native production dependencies for arch x64
Packaging for darwin x64 using electron 1.4.7 to dist/mac
⚠  Mac Developer is used to sign app — it is only for development and testing, not for production
Signing app (identity: Mac Developer: *** (***))
> Error: Failed to pass Gatekeeper: : Error: Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache /Users/alberto2000/Desktop/hyper/dist/mac/Hyper.app
/Users/alberto2000/Desktop/hyper/dist/mac/Hyper.app: rejected

`Error: Failed to pass Gatekeeper:` is the crux here I guess - what is the issue here?

**Comment by alberto2000** [comment]
I managed to bypass this issue by disabling Gatekeeper completely - more of a hack obviously: https://www.tekrevue.com/tip/gatekeeper-macos-sierra/

**Comment by albinekb** [comment]
Something must be up with your setup, maybe old xCode? (it's used to sign the .app)

**Comment by alberto2000** [comment]
Latest Xcode 8.2.1 and it's working, incl. provisioning profiles etc. (I have an app running on the app store) ...

**Comment by henrikdahl** [comment]
@alberto2000 Still experience this on 1.3.0 with yarn?
