### ISSUE TITLE
Realtime stdout creates new lines for progressive updates rather than replacing lines

### ISSUE THREAD

**Issue by colepeters** [zeit/hyper#1367]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.2
- **Hyper.app version**: 1.0.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A, happens regardless of `.hyper.js`
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 👍🏻

## Issue
First off: I’ve searched the issues here for anything that might be a duplicate, but as I don’t 100% know the correct terminology, I may have missed something.

I’ve noticed that some CLI apps which generate realtime output involving ‘status updates’ (in my example below, [`gsutil`](https://cloud.google.com/storage/docs/gsutil) for GCP) will end up generating new lines for every ‘progress’ update instead of updating the progress line. For example, in iTerm, when I run a process to sync a directory on my machine with a directory in my Google Cloud storage, I get a new line for every file uploaded, but there’s only one stdout line for the overall sync progress, which is updated in realtime — this is the behaviour I expect:

![iTerm](https://cloud.githubusercontent.com/assets/1713932/21778871/0d252402-d69d-11e6-8053-c47cf0be0fbf.png)

Conversely, when I run the same operation in Hyper, a new stdout line is generated for every progress update:

![Hyper](https://cloud.githubusercontent.com/assets/1713932/21778910/36dd95fe-d69d-11e6-9501-6d344d4c9b05.png)

I’ve noticed this with other CLI apps, e.g. npm, yarn, etc, where progress is piped in realtime to stdout.

Could this be fixed? Would love to not have stdout be so noisy for these sorts of things. Happy to provide any extra info if needed. Thanks!

**Comment by colepeters** [comment]
Just for reference, here’s another occasion where this happens. This is while downloading and installing packages from `brew`:

![screen shot 2017-01-16 at 19 34 21](https://cloud.githubusercontent.com/assets/1713932/21996566/ca6df108-dc22-11e6-8d3e-567691f70407.png)

**Comment by ljfio** [comment]
Looks like the same problem was happening in #601

**Comment by colepeters** [comment]
This appears to be fixed in Hyper 1.2.1. Thanks!

**Comment by colepeters** [comment]
This seems to be happening again. Not sure which version it reappeared in, but here’s an example:

Webpack build running in iTerm:
![image](https://cloud.githubusercontent.com/assets/1713932/25893159/aa9129ea-356e-11e7-8511-b6ea230fc232.png)

Same, running in latest Hyper (1.3.2, macOS 10.12.4):
![image](https://cloud.githubusercontent.com/assets/1713932/25893178/c173ef6c-356e-11e7-9601-4ed172788232.png)

**Comment by colepeters** [comment]
Update: I've just noticed something flaky about this — if I increase the width of my Hyper window, the stdout seems to update the single line as it should. Screenshot below shows what happens on initially running my Webpack build, and the line at the bottom is the line that started stream updates after resizing:

![image](https://cloud.githubusercontent.com/assets/1713932/25907158/9871eb2a-359e-11e7-97fc-f891c31c1708.png)

A colleague of mine (@rmhowe) recently noticed similar behaviour on vertical splits — so I'm thinking this now has something to do with the width of the window/split compared to the length of the output, perhaps?

**Comment by colepeters** [comment]
This is still an issue in 1.4.3. Any updates?

**Comment by 1um** [comment]
As a workaround, I'm using [Tmux](https://github.com/tmux/tmux/wiki) inside the terminal, which seems handles it perfectly.

**Comment by jcheng31** [comment]
I'm seeing the same issue on 1.4.8 running on Manjaro: when the width is narrower than the output line, it creates new lines. Resizing the window so the output fits entirely on one line fixes it.

**Comment by deleteme** [comment]
This problem is particularly bothersome for those who use vi mode bindings (j/k) to browse history.

**Comment by chabou** [comment]
@deleteme what is your hyper version?
If you are using v1.4.8, can you install our last canary by adding `updateChannel: 'canary'` in your config file and retry?

**Comment by deleteme** [comment]
It's fixed in canary, thank you! ([before](https://user-images.githubusercontent.com/9389/36163292-ce3bb4b8-109d-11e8-9608-d3b1d8d8fe31.gif), [after](https://user-images.githubusercontent.com/9389/36163299-d2d58184-109d-11e8-9303-26c0d4959236.gif))

**Comment by chabou** [comment]
Thank you for your confirmation :pray:
