### ISSUE TITLE
Manually install plugins? 

### ISSUE THREAD

**Issue by mikeumus** [zeit/hyper#1368]
All plugins are getting blocked for me from my works proxy. Is there a way I could put the source folders of the plugins in the right spot and they run?  😇

**Comment by chabou** [comment]
you can use `~/.hyper_plugins/local/`folder to put source (some of them needs to be built) and add its name in `localPlugins`array in `~/.hyper.js` config file

**Comment by mikeumus** [comment]
The theme install this way worked. `hypernpm` and `hyperpaste` didn't work but pasting doesn't work for me regardless even with `Control + Shift + V` on Windows 7 yet it seems. `hyperterm-visor` kind of works. Thanks @chabou ! :smile: :+1:

**Comment by blackwellops** [comment]
Where can you specify HTTP proxy settings for npm (Windows)? This is possible in Atom via `~/.atom/.apmrc.`

**Comment by ZakTaccardi** [comment]
this is the problem: https://github.com/zeit/hpm/issues/48

**Comment by rcassola** [comment]
How to install the https://github.com/dracula/hyper manually?

I'v placed the diretory under ~/.hyper_plugins/local/ and added the folder name to localPlugins on .hyper.js but didn't work.

Any help? Thanks

**Comment by ZakTaccardi** [comment]
@rcassola what's the error? are you missing an npm module?

you can `npm install <module-name>` inside the `local/<plugin-name>/` any missing npm modules.

**Comment by rcassola** [comment]
Thank you @ZakTaccardi, it worked!!!
