### ISSUE TITLE
Save split panes

### ISSUE THREAD

**Issue by tinganho** [zeit/hyper#1369]
It would be good if Hyper could remember how I split the panes.  In iterm2 I can save the splits and open the splits.

**Comment by lmichailian** [comment]
A good plugin for [this](that https://github.com/timolins/hyperlayout)

**Comment by ppot** [comment]
This is taken care in PR #945

**Comment by NeonWizard** [comment]
This should be re-opened. The pull request was abandoned, and the suggested `hyperlayout` plugin is now unmaintained and broken.

**Comment by NeonWizard** [comment]
@ppot Are you planning on finishing your pull request any time soon? Or should this issue be re-opened?
