### ISSUE TITLE
Hyper doesn't stop processes when closing

### ISSUE THREAD

**Issue by NetOperatorWibby** [zeit/hyper#1370]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
---
- **macOS Sierra**
- **Hyper.app version 1.0.1**
- **Relevent information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**
---
## Issue

First, there are typos in Issue creation: "fulfil" and "Relevent".

Second, when there are running scripts, like `mongod`, they don't actually stop running when I close Hyper. I discovered this by running into errors when trying to start it again. My app doesn't run if Mongo isn't running, which is how I found out that my initial Mongo instance never stopped.

Now that I think of it, Hyper should prompt the user that s/he still has something running and ask if s/he wants to continue shutdown, like Terminal does.

**Comment by rauchg** [comment]
@NetOperatorWibby totally agree re: warning. Didn't realize processes don't get shutdown, that's strange. Are you sure it's not because `mongod` forked?

**Comment by NetOperatorWibby** [comment]
@rauchg I'm not sure, my experience with Mongo is 1) start the database so I can 2) do stuff. I don't know about forking and things like that.

**Comment by rauchg** [comment]
OK I was just able to verify this bug! Thanks for bringing it to my attention

**Comment by NetOperatorWibby** [comment]
No problem! I've been playing around with Hyper for a couple hours now, this is neat! About to push a theme to npm soon.

**Comment by aryzing** [comment]
Same issue here. I usually spawn several webservers using node. When I close and reopen, I find that the ports are still in use b/c the previous instances have not been killed on exit.

**Comment by rauchg** [comment]
@Tyriar how do you handle this with `node-pty`?

**Comment by Tyriar** [comment]
Nothing changed from the old pinned pty.js commit.

I had a similar report in vscode but I believe that was because the program was creating a detached process. https://github.com/Microsoft/vscode/issues/18385

**Comment by cappslock** [comment]
Yeah, this is a big one... especially if you run multiple panes, each login shell is still shown via `ps`.

Partial `ps` output with sensitive data removed:
```
PID TTY           TIME CMD
23673 ttys001    0:00.59 /bin/zsh --login
26273 ttys001    0:00.01 /bin/bash -e ./tunnel.sh
26276 ttys001    0:00.09 python3 ./tunnel.py
23911 ttys002    0:00.00 /bin/zsh --login
23912 ttys002    0:00.01 cat
25738 ttys002    0:00.00 /bin/zsh --login
25740 ttys002    0:00.00 /bin/zsh --login
25741 ttys002    0:00.00 /bin/zsh --login
25743 ttys002    0:00.00 /bin/zsh --login
25744 ttys002    0:00.01 cat
25747 ttys002    0:00.01 /Library/Developer/CommandLineTools/usr/bin/git -c gc.auto=0 fetch
25971 ttys003    0:00.34 /bin/zsh --login
26201 ttys004    0:00.00 /bin/zsh --login
26202 ttys004    0:00.01 cat
26364 ttys004    0:00.00 /bin/zsh --login
26366 ttys004    0:00.00 /bin/zsh --login
26367 ttys004    0:00.00 /bin/zsh --login
26369 ttys004    0:00.00 /bin/zsh --login
26370 ttys004    0:00.01 cat
26373 ttys004    0:00.03 /Library/Developer/CommandLineTools/usr/bin/git -c gc.auto=0 fetch
```

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by NetOperatorWibby** [comment]
The issue doesn't appear to be happening. Sweet!

**Comment by jakemumu** [comment]
just stumbled upon this using hyper with Ruby on Rails & a gem called sunspot solr. 

I'm on hyper 3.2.0, quitting hyper left an open process running which requires a kill to the port to stop

**Comment by paseaf** [comment]
I'm on Hyper 3.0.2. Closing a hyper tab doesn't stop process from running when there are multiple panes with multiple processes in the tab. Seems it only stops the process in the focused pane of the previous tab.
Steps to reproduce the issue:
1. open hyper
2. run program 1
3. open a new pane with `ctrl + shift + d`, in the new pane run program 2.
4. open a new tab with `ctrl + shift + t`
5. close the previous tab via the `close` button without switching to it
6. run program 1 again: the previous port was blocked

**Comment by Spy474** [comment]
I have the same problem as @paseaf on WIndows. I did the exact same steps as him, and I can close the process. Trying to run a server side on port 5000, and it still open somewhere else (a previous Hyper Window that I closed)

**Comment by Stanzilla** [comment]
kinda depends on which version you are using. the last release is super old so you'd have to be on a CI version to get something remotely working. also plugins always break things.
