### ISSUE TITLE
Non-ASCII characters sometimes not rendering in the prompt in new windows/tabs

### ISSUE THREAD

**Issue by FabriceCastel** [zeit/hyper#1371]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.2
- **Hyper.app version**: 1.0.1
- **The issue is reproducible in vanilla Hyper.app**: Set up your prompt to include "∆" then open multiple new terminal window and tabs until you notice that character rendering as "�".

## Issue
The reproduction steps sum it up; sometimes when you open a new window or tab, the prompt will print with non-ASCII characters displayed incorrectly as �. This seems to happen 20-30% of the time.

I'm using the fish shell. I highly doubt that's the issue but I figured it would be worth mentioning on the off chance that it was somehow related.

<img width="224" alt="screen shot 2017-01-09 at 7 45 36 pm" src="https://cloud.githubusercontent.com/assets/2886675/21789601/3caa13e8-d6a4-11e6-9832-5fbe69013314.png">

**Comment by ppot** [comment]
Fixed in #1366
