### ISSUE TITLE
BEAM cursor type too wide

### ISSUE THREAD

**Issue by FabriceCastel** [zeit/hyper#1372]
Short and sweet: the BEAM type caret is too wide and overlaps with text. This should only be a styling issue with an easy fix for anyone who knows where to look. Did a cursory search for BEAM in the codebase but couldn't follow it back to the matching CSS to submit a PR :(

<img width="102" alt="screen shot 2017-01-09 at 10 13 02 pm" src="https://cloud.githubusercontent.com/assets/2886675/21792598/ed073e82-d6b8-11e6-8b5b-2b5ae7051f7a.png">

**Comment by L-A** [comment]
PR sent earlier today!  → https://github.com/zeit/hyper/pull/1389

![cursor shapes](https://cloud.githubusercontent.com/assets/861964/21865496/54dcf66c-d814-11e6-933d-bcdf80c97030.gif)

**Comment by paulthealien** [comment]
@L-A you beat me to it.

**Comment by albinekb** [comment]
#1389 merged, Thanks  @L-A & @paulthealien!

**Comment by rauchg** [comment]
We're going to revert this, and introduce opacity later.
