### ISSUE TITLE
Hyper does not show menus on Fedora 25 with Gnome

### ISSUE THREAD

**Issue by possebon** [zeit/hyper#1373]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 25 Kernel 4.8.15
- **Hyper.app version**: the latest downloaded yesterday (09/01/2017)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/possebon/0b1a0169dc28e264bbc55c10278e96f0
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: http://imgur.com/a/07CkU
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
After downloading the Hyper.app I run with sucess but there are no menus. I tried on Windows and MacOS with success, but on Linux (at least on my workstation), it does not work as expected.

This is the screenshot of my screen: http://imgur.com/a/xl50w

I saw a video on Youtube of Hyper running on Fedora 25 without any problems.

**Comment by stefanivic** [comment]
@possebon in ~/.hyper.js set the showHamburgerMenu to true. 
So it's `showHamburgerMenu : true,`

**Comment by possebon** [comment]
Thanks for you reply.

I changed but did not showed the menu anyway.

I just downloaded the version 1.1.0 too, and did not work either.

**Comment by bryantee** [comment]
@possebon I just got it working myself on F25. Make sure you're not using quotes as `true` should be a boolean not a string.

**Comment by possebon** [comment]
I got it working too now. It was the true value that I was using quotes.

Thanks Bryan.
