### ISSUE TITLE
How to setup windows powershell in config file

### ISSUE THREAD

**Issue by damien122** [zeit/hyper#1374]
Hi, 
I want to use windows powershell with hyper but can't find any information how to setup the config file.
I tried this
```
shell: 'powershell.exe',
shellArgs: ['--login'],
```

but the window just closing immediately.

**Comment by damien122** [comment]
ok problem is fixed. 
the arguments list should be empty.
```
shell: 'powershell.exe',
shellArgs: [''],
```

**Comment by albinekb** [comment]
I think you need the full path to `powershell.exe`?

**Comment by damien122** [comment]
the full path is not needed because powershell.exe is known system wide because it is inside system32 folder, or a link to powershell is inside system32 folder.
This is also the reason why you can call powershell.exe if you press Win+R.

**Comment by jmreicha** [comment]
This should really be in the docs somewhere...
