### ISSUE TITLE
ssh on windows

### ISSUE THREAD

**Issue by andrewbanchich** [zeit/hyper#1375]
Any chance you could implement SSH for Windows users? I know Secure SSH is a Chrome-based terminal that allows us to SSH on Windows, so maybe Hyper could allow for something similar?

**Comment by Specro** [comment]
Hyper is just an interface for a shell. You should use something like OpenSSH or PuTTY(has a cli called Plink if you really want to use command line), or packages that include ssh like Gow, CygWin or MSYS 👌

**Comment by andrewbanchich** [comment]
@Specro Yes, but I think they force you to  use their own terminals to have the ability to use SSH. I am thinking since [Chrome Secure Shell](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?hl=en) already does this, is a Chrome Web App, and allows for using SSH on Windows, that it would be able to be integrated with Hyper since Hyper in an Electron app.

**Comment by zusamann** [comment]
I'm using git bash, and it lets me ssh without any problems

**Comment by andrewbanchich** [comment]
@zusamann Still doesn't open in Hyper though. I want to use Hyper.

**Comment by maxshaw** [comment]
@andrewbanchich just install git for windows. and add "C:\Program Files\Git\usr\bin" to PATH.
including ssh, sftp ...

**Comment by maxshaw** [comment]
same bug for ace editor. haha

**Comment by andrewbanchich** [comment]
I added "C:\Program Files\Git\usr\bin" to PATH, restarted Hyper, and tried to run "ssh mywebsite.com" and it says `'ssh' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by andyeskridge** [comment]
If you edit your .hyper.js config file to match the snippet below you should have no problems using ssh.

```js
// the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
// if left empty, your system's login shell will be used by default
shell: 'C:\\Program Files\\Git\\bin\\bash.exe',

// for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
// by default ['--login'] will be used
shellArgs: ['--login', '-i'],
```

**Comment by andrewbanchich** [comment]
@andyeskridge  Worked perfectly! Thank you!

**Comment by Sispheor** [comment]
It would be very nice to have same features as https://termius.com/.

**Comment by deadstar1** [comment]
you may like this https://www.linode.com/community/questions/413/i-get-the-error-permission-denied-publickey-when-i-connect-with-ssh
