### ISSUE TITLE
Cursor remains in old tab when changing tabs

### ISSUE THREAD

**Issue by moskyb** [zeit/hyper#1380]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.2
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/moskyb/d4e5204b9cc107662196e1fdc2e3de82

## Issue

After changing tabs, if I don't click on the new tab window, the cursor will remain in the previous tab, allowing me to run commands in that tab without it being in focus.

Ideally, when the user changes a tab, the cursor should automatically change with the tab.

**Comment by chabou** [comment]
Only for the first tab change, after adding a tab no ?

**Comment by jokeyrhyme** [comment]
Yeah, these are my steps to reproduce:

1. start with a new window, with the default Tab 1
2. create a new tab (I use Command+T), we'll call it Tab 2
3. observe that keyboard focus is in Tab 2
4. switch back to Tab 1 (I click the header)
5. observe (via cursor style) that keyboard focus is not in Tab 1 as expected
6. type a few letters
7. observe that the letters do not appear in Tab 1 as expected
8. switch to Tab 2
9. observe that the letters typed in step 6 did not end up here either (good)
10. switch to Tab 1
11. observe (via cursor style and typing a few keys) that keyboard focus is now in Tab 1 as expected (good)

It would appear that the problem begins somewhere between steps 4 and 5. /shrug

**Comment by matheuss** [comment]
I fixed this via https://github.com/zeit/hyper/commit/e5c076e82fa142c22c264738edc7db0a0c2c2907 and https://github.com/zeit/hyper/commit/f8d5dcd060c069ec39a97906d42a9593c3055f8f 😄 Will be shipped this week :v:

**Comment by jokeyrhyme** [comment]
@matheuss Ooo, nice! Yay!
