### ISSUE TITLE
CTRL + C to discard the current command does not work

### ISSUE THREAD

**Issue by tinganho** [zeit/hyper#1382]
There is one issue already for <kbd>CTRL</kbd> + <kbd>C</kbd> not working for interrupting a running program: #1121. Though, this is not related to it.

Whenever, I type something wrong or I want to run another command, I type <kbd>CTRL</kbd> + <kbd>C</kbd> to discard the current command.
```shell
$ ohh shiet, I typed something wrong #CTRL + C
$ dir
```
Apparently, it doesn't work in Hyper on Windows.

**Comment by tinganho** [comment]
It would be good with a proper QA. It seems like many simple things is missing right now. Otherwise, a quite promising product.

**Comment by rauchg** [comment]
Yep we're already tracking this isssue via `node-pty`. It's not a matter of QA in this case, but we're always trying to improve across the board. Thank you!

**Comment by CodeTheory** [comment]
For the record, this looks like the issue in `node-pty` if anyone wants to view it. https://github.com/Tyriar/node-pty/issues/7

**Comment by tinganho** [comment]
@CodeTheory That's terminating a process. My issue is just discard the command.
