### ISSUE TITLE
Pressing F11 (fullscreen) produces tilde character (`~`) instead

### ISSUE THREAD

**Issue by aryzing** [zeit/hyper#1388]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [settings](https://gist.github.com/aryzing/33f081d92d13cfa82e0c0b52bda54d13)
- **Relevent information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla
## Issue

Pressing F11 to go full screen does not work. Instead, a tilde character is typed into the command prompt.

**Comment by radare** [comment]
Same happens on OSX, expected keycode is CMD+enter, like iTerm does, but it does nothing, it is needed to use the mouse and press the (+) button of the window to get full screen. Is there any way to configure that keybinding?

**Comment by MEDIUM-ch** [comment]
Same on Windows. This is in the main menu so should have a Keyboard shortcut too and as it is common probably F11  (or/and maybe platform specific to Windows ALT+ENTER). A core functionality should be Keyboard accessible IMHO.

**Comment by ppot** [comment]
closed in #1876
