### ISSUE TITLE
Tab switching with Alt+[1-9] does not work

### ISSUE THREAD

**Issue by Isotop7** [zeit/hyper#1390]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: archlinux on lts kernel (4.4.41)
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Isotop7/5a692f0527037819bed66a74576e6323
- **The issue is reproducible in vanilla Hyper.app**: :+1: 

## Issue

When i use [irssi](https://irssi.org/) and want to switch tabs with ALT + [1-9] nothing happens.

**Comment by ppot** [comment]
@Isotop7  Can you tell me if other commands including `Alt` work?

**Comment by Isotop7** [comment]
@ppot like other alt-shortcuts in irssi or in general?

**Comment by ppot** [comment]
@Isotop7 In general

**Comment by Isotop7** [comment]
@ppot Im afraid i dont have any other cli tool that uses alt key combinations...

**Comment by ppot** [comment]
Fixed in my update ;)

**Comment by nvisser** [comment]
@ppot Could you elaborate which version that update is? I'm running Hyper 1.2.1 on Arch Linux and do not have this working yet.

**Comment by ppot** [comment]
@nvisser This is included inside the Rebuild branch. Not the current Master since it's not merged or near to be merged. As i'm currently integrating it inside Master as Parts. Starting with flexible-keymap

**Comment by dweidenfeld** [comment]
Not working on Arch / Version: Hyper 2.0.0-canary.8 (stable).
Is there any update about this?

**Comment by chabou** [comment]
Fixed in canary by https://github.com/zeit/hyper/pull/2330

You can change key in .hyper.js config file
