### ISSUE TITLE
When resizing window, text doesn't fit properly.

### ISSUE THREAD

**Issue by micopc** [zeit/hyper#1391]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When I resize the window, I expect the text inside it to readjust to the windows size but it doesn't.

![gif_hyper](https://cloud.githubusercontent.com/assets/13283635/21873503/d0c84600-d83c-11e6-9e9f-7c5e897b9d3a.gif)

**Comment by matheuss** [comment]
#476 😅
