### ISSUE TITLE
How to change default windowSize on macOS isn't apparent/explained

### ISSUE THREAD

**Issue by theBigDalt** [zeit/hyper#1393]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.2
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/dlduvio/cc2cbace5d10297c25c8042172daa67a
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

This is a small issue, but how to change the default window size isn't readily apparent or explained, at least for macOS. For me on macOS, I had to put the windowSize variable and the accompanied value (without quotation marks) in a newly created winCfg: { }, after digging through Hyper's source on GitHub. My suggestion would be to put in an empty winCfg: { }, along with a comment explaining its purpose in the default .hyper.js as is done with 'environment variables' already. 

Again, I'm not sure if this is an issue only on macOS, but it was a little bit frustrating nonetheless to need to dig through the source to figure out.

**Comment by pablopunk** [comment]
For me it's working on macOS Sierra without needing `winCfg`

Keep in mind these numbers mean **pixels**, not rows/columns, as explained [here](https://hyper.is/#cfg)

<img width="580" alt="screen shot 2017-01-16 at 7 00 52 pm" src="https://cloud.githubusercontent.com/assets/4324982/22002999/51ab42b0-dc1e-11e6-9242-7c3ad3e05d7b.png">

**Comment by gtsiolis** [comment]
This is not reproducible anymore. `winCfg` is not required for this. You only need to add the following:

```shell
windowSize: [570, 390],
```

Using the values `[570, 390]` will also make the size closer to the default size of the Terminal.app. 

/cc @matheuss

**Comment by theBigDalt** [comment]
This issue can be closed. It seemed it was an issue with my setup specifically and was fixed in an update. I dont know why it wouldn’t recognize my windowSize parameters before, but has worked properly without a hitch since i reported the issue. 

Thank you to the Zeist crew and all other contributors. I still use Hyper as my main terminal and its always been fantastic.

**Comment by theBigDalt** [comment]
This issue can be closed. It seemed it was an issue with my setup specifically and was fixed in an update. I dont know why it wouldn’t recognize my windowSize parameters before, but has worked properly without a hitch since i reported the issue. 

Thank you to the Zeist crew and all other contributors. I still use Hyper as my main terminal and its always been fantastic.
