### ISSUE TITLE
Copy/Paste doesn't work on Windows 10

### ISSUE THREAD

**Issue by gonzalocasas** [zeit/hyper#1394]
1. Open Hyper.app on Windows 10
2. Try to copy something from the console output using keyboard shortcuts
3. or.. try to paste something into it
4. notice that neither works
5. cry a little...
6. open PowerShell console as workaround, and cry a little more.

Hyper 1.0.1
Electron 1.4.7
win32 x64 10.0.10586

**Comment by zusamann** [comment]
Try a right click if ctrl+v doesn't work

**Comment by gonzalocasas** [comment]
Ok, I don't wanna sound too bitch-y, but this is super basic functionality that doesn't work out of the box. Right-click didn't work for me either. And on a clean install of Windows, `.js` files are associated with notepad + the fact that the preferences file uses linux new-lines = i-cant-change-preferences!-fuck-this-shit-mode. And it's a pity because I use Hyper.app on my mac and it's freaking awesome, but on Windows it seems completely neglected. 

At some point I get it, like, why would any decent person develop on Windows; but well... then why make it an Electron cross-platform app if the second largest platform is not really taken care of much :)
`</rant>`

Anyway, keep up the awesome job on mac, and if you have time, try to make the life of Windows devs a little less miserable at some point! :D

**Comment by gluons** [comment]
Similar issue: #1328

**Comment by matheuss** [comment]
Yo y'all please test #1406 🙌

**Comment by jongalloway** [comment]
💯 on #1406. I'm running CI builds (e.g. installer from https://ci.appveyor.com/project/appveyor-zeit/hyper/build/1.0.458/artifacts) and very happy. copy/paste works, preferences command opens folder with preferences file selected (open in non-notepad editor of your choice), several other Windows specific PR's have been merged and some other good ones under review. Next official release is going to be awesome.

**Comment by gluons** [comment]
Thanks. I've tried it from appveyor. It works very well! 😄

**Comment by damiandennis** [comment]
Works ok for Windows 7 however when you copy on multiple windows it looses focus and switch back to the first one which is a real pain for the flow of typing.

**Comment by thdjoker** [comment]
ctrl+shift+V works for me.

**Comment by Altamashsbr** [comment]
> ctrl+shift+V works for me.

Thanks a lot

**Comment by AstroCodeMir** [comment]
> ctrl+shift+V works for me.

mine too :) windows 10

**Comment by slashwhatever** [comment]
> ctrl+shift+V works for me.

Soooo a different key binding to 99.9% of all other apps? Great.
