### ISSUE TITLE
Environment variables on .hyper.js env prop not being applied

### ISSUE THREAD

**Issue by leocavalcante** [zeit/hyper#1396]
`env` not being applied.
Any tips?

![image](https://cloud.githubusercontent.com/assets/183722/21896284/fe6a8ac4-d8cc-11e6-8d0e-08649a9379f5.png)

Hyper 1.1.0 on Windows 7

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by avindra** [comment]
Seems to work fine in v2
