### ISSUE TITLE
Tabs In fullscreen are not full width anymore

### ISSUE THREAD

**Issue by acondiff** [zeit/hyper#1399]
There is still margin left for the traffic lights on the tabs container when Hyper is in fullscreen. Traffic lights are not displayed so it is just an empty gap. Margin should return when menubar is evoked by mousing to the top of your screen.

**Comment by jonikorpi** [comment]
Additionally, the traffic lights have no background when the auto-hiding menubar appears and pushes them down: 
<img width="1280" alt="screenshot 2017-02-06 13 40 29" src="https://cloud.githubusercontent.com/assets/621255/22645892/1e81736e-ec72-11e6-82a2-6799ce7c484b.png">

**Comment by ppot** [comment]
Fixed in https://github.com/ppot/hyper/issues/9
