### ISSUE TITLE
Extensions API

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#14]
Continuing from the "Allow custom stylesheet" thread (#10).

The way I want to do this is directly with the JS extensions API. You would basically register a plugin that registers CSS. 

The sample extension we'll have is one that makes the theme light during the day and dark at night. This will show off adding CSS and also adding a bit of JS logic, so it's a good all-around example.

I'll probably use webpack in the example build step so that you can `require('./something.css')`. People that want to use sass can simply use a sass loader or add another step to get the `.css` from the `.sass`.

**Comment by rauchg** [comment]
As far as how someone register their extensions, I was thinking about having `$HOME/hyperterm.json`.
It would look as follows:

```json
[
  "@hyperterm/preserve-pwd",
  "hypersolar"
]
```

This has a few purposes:
- **Sharability**. "👨: Why does your hyperterm look so cool!? "👩: Here, have my `hyperterm.json`".
- **Configurability and extensibility in one**. If you want to remove functionality, simply remove a core plugin. Plugins admit optional parameters:
  
  ```json
  ["hypersolar", { "useWeatherAPI": true, "zipCode": 94123 }]
  ```
- **Declarative installation**. Kind of like the amazing `.vimrc` based extensions solutions (I use NeoBundle). When you make changes to the file, that triggers the installation or removal of the NPM modules.

**Comment by rauchg** [comment]
As far as the API, I'm going to experiment with the following: plugins simply expose a function that is invoked with the main `<HyperTerm>` component to decorate.

This would give plugins complete control over the customizability of the terminal. They could register `componentDidMount`, add stuff to `render`, etc.

**Comment by chabou** [comment]
Outdated
