### ISSUE TITLE
Tabs font stack unavailable to plugins

### ISSUE THREAD

**Issue by henrikdahl** [zeit/hyper#1401]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.12.2 macOS Sierra
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Tabs font stack isn't available through any variable:

https://github.com/zeit/hyper/blob/12ae25a60b800efdd19205a0f259bd53c1668273/lib/components/tabs.js#L70-L73

Would be neat to be able to access it easily so that you can rely on it in plugins. Currently if you just copy the stack manually it wouldn't update if Hyper ever decides to change it.

**Comment by albinekb** [comment]
I'll make a PR on sunday 🎉

**Comment by henrikdahl** [comment]
@albinekb 👋 😅
