### ISSUE TITLE
Cannot download the source code for the 1.1.0 version

### ISSUE THREAD

**Issue by caliber01** [zeit/hyper#1402]
The links for source code archives for the 1.1.0 release that can be found on the releases page seem not to be working for me (both zip and tar.gz). I hope this is a relevant kind of issue to be submitted here.

**Comment by jamo** [comment]
It's probably related to issues GitHub has been recently experiencing: http://status.github.com/

**Comment by onbjerg** [comment]
GitHub content servers are down it seems. Everything related to GitHub has died on my end, except for the website.

**Comment by matheuss** [comment]
It's back now 🎉
