### ISSUE TITLE
How to close browser

### ISSUE THREAD

**Issue by OJFord** [zeit/hyper#1405]
I didn't even realise Hyper had a built-in browser, until I accidentally opened a page in it just now.

I can't figure out how to close it and return to the session - so this is either a request for better documentation/visibility in menu, or to implement such a thing.

**Comment by daliborgogic** [comment]
Close with  `Ctrl + c `

**Comment by kandros** [comment]
had same issue, a dismissable notification on open would be great

**Comment by matheuss** [comment]
We will move the `webview` feature into a core plugin – it'll come with lots of improvements! For now, <kbd>Ctrl</kbd>+ <kbd>C</kbd> is the way to got 👌 
Thanks for the report @OJFord @kandros 🙌

**Comment by OJFord** [comment]
I did try <kbd>Ctrl</kbd>+<kbd>C</kbd> (after a while - because I was worried it was going to quit the pane and I'd lose history) but it didn't work.

I don't know why I was worried to try it now I look back on it though, I wouldn't have worried about quitting any other process... I suppose I just didn't know what had happened - I assumed it was some weird bug and not a feature, made possible by the nature of Electron. Was only finding other issues here mentioning "browser" that gave it away!

Thanks anyway.
