### ISSUE TITLE
appimage icon not registering with desktop

### ISSUE THREAD

**Issue by andrewbanchich** [zeit/hyper#1407]
On Arch Linux, Hyper's .AppImage icon is broken when registering with the desktop. I've tried manually creating a .desktop file, but couldn't get the icon to load. I just installed `appimaged` which automatically looks in various paths for AppImage files and registers them. It correctly registered Hyper, but the icon is still broken.

To test if this was just Hyper or something else, I tried installing Etcher in the same way, which worked and the icon loads fine.

**Comment by probonopd** [comment]
You may be running into a known issue with `appimaged`, https://github.com/probonopd/AppImageKit/issues/328. Any help appreciated.
