### ISSUE TITLE
Error updating plugins

### ISSUE THREAD

**Issue by eduplessis** [zeit/hyper#1408]
- **10 64bit Windows**: 
- **1.1.0**: 
- **Is Vanilla**: 
## Issue

When opening Hyper or trying to click on the menu update all plugin... 

![hyperbug](https://cloud.githubusercontent.com/assets/398245/21964292/59068464-db17-11e6-9562-f157969fe127.jpg)

**Comment by matheuss** [comment]
@eduplessis could you share the contents of such `.log`?

**Comment by eduplessis** [comment]
there's no npm-debug.log

but I think I know why node wasn't installed on my machine...

**Comment by eduplessis** [comment]
yeah that was the case.... I've installed node and it's working

**Comment by chabou** [comment]
Maybe error message should be more precise. If npm is not available : no logfile will be written.
