### ISSUE TITLE
Splitting causes vim to not return to full screen

### ISSUE THREAD

**Issue by cmwall** [zeit/hyper#1411]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.12.2 Sierra
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cmwall/d973398d4b998237ca2f460e33359165
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Not sure

## Issue

When opening a split view with CMD + D, and then closing that view with CTRL + D, I open up vim and the application doesn't render vim at 100%:

![image](https://cloud.githubusercontent.com/assets/13528491/21965287/56b67646-db22-11e6-9a9e-88bcb8231c8e.png)

**Comment by pho3nixf1re** [comment]
I can confirm this issue. The steps to reproduce above consistently cause this issue with vim (nvim).

**Comment by weslleyaraujo** [comment]
I can also confirm the issue ✋

my vim version is `7.4.1910`

**Comment by dusty** [comment]
For me this doesn't just happen with vim, it happens with everything on the screen.

OSX 10.12.3
Hyper Version 1.1.0 (1.1.0.1408)

![Video](http://g.recordit.co/fz3nOWYyfs.gif)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
