### ISSUE TITLE
Query re: app direct download

### ISSUE THREAD

**Issue by zusamann** [zeit/hyper#1413]
I have a a rather foolish query, but are the download files available on the website always up to date with the latest master branch. I want to remain in sync with the latest changes but don't want to clone the git repo and pull new code and run the app from my terminal. 

So how long should I wait to download the app from the website after a merge has been made into the master branch? 

Thanks 😁

**Comment by jamo** [comment]
The releases from hyper.is should be always up-to-date with latest release of hyper: https://github.com/zeit/hyper/releases/latest

**Comment by matheuss** [comment]
@zusamann as @jamo said, the links on [hyper.is](http://hyper.is) are just a proxy to the latest release. If you want to try the latest features of `master`, I'd suggest that you build it from source 🙌

**Comment by zusamann** [comment]
Ok will keep an eye on releases, thanks!
