### ISSUE TITLE
Opening Developer Tools makes the window undraggable

### ISSUE THREAD

**Issue by LoganDark** [zeit/hyper#1414]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 1.1.0.1408
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Here](https://gist.github.com/LoganDark/a6b558278204ab04329e2a0b33a3f09b)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:
```
(re)loading renderer plugins
index.html:34 total init time 176.15000000000003
bundle.js:32264 Unimplemented DEC Private Mode: 1034
```
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Opening Developer Tools by toolbar or keyboard shortcut makes the app window undraggable. A full refresh does not resolve the issue, an app restart is required. Other windows are not affected, however other tabs are.

**Comment by LoganDark** [comment]
@ppot I actually believe this is an Electron issue, not a Hyper one.

**Comment by ppot** [comment]
@LoganDark Thats why I closed it. There is already an issue for this.

**Comment by LoganDark** [comment]
OK
