### ISSUE TITLE
Korean letters spacing incorrectly.

### ISSUE THREAD

**Issue by jof4002** [zeit/hyper#1415]
![hy2](https://cloud.githubusercontent.com/assets/635334/21979788/db60ddda-dc23-11e6-8e6a-59800f32a78f.png)

When a new session start, korean letters space incorrectly. When I slipt window, old one's spacing become right, but new one's spacing incorrect again
-

Hyper 1.1.0
Electron 1.4.7
win32 x64 10.0.10240

**Comment by krazyeom** [comment]
I had same issue. I've tried to use Korean Font. but it can not solve this problem.

**Comment by krazyeom** [comment]
there is something bug to calculate width of .unicode-node.

.unicode-node {
    display: inline-block;
    vertical-align: top;
    width: 7px;
}

if i removed or unchecked width line, it is collectry displayed on the screen.

**Comment by youngminz** [comment]
Workaround: Add the following to the hyper.js file.

```
termCSS: '.wc-node { width: 16px !important; overflow: hidden; }
```

Explanation: Check the width of rendered English characters in Developer Tools. You can double this value to this setting. At the end, it seems that the same character appears twice. Set overflow to hidden.

Result: 

![image](https://cloud.githubusercontent.com/assets/5145369/22768688/10e79204-eec7-11e6-9314-f646594c1261.png)

**Comment by silverlod** [comment]
in my hyper.js file
````javascript
termCSS: 'span.unicode-node {width:12px;}'
````
set width to font size

**Comment by syolin** [comment]
changing the font width affects other parts :(

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
