### ISSUE TITLE
ANSI escape codes do not wrap correctly

### ISSUE THREAD

**Issue by LoganDark** [zeit/hyper#1416]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 1.1.0.1408
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Here](https://gist.github.com/LoganDark/a6b558278204ab04329e2a0b33a3f09b)
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:
```
(re)loading renderer plugins
index.html:34 total init time 176.15000000000003
bundle.js:32264 Unimplemented DEC Private Mode: 1034
```
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
![](https://cloud.githubusercontent.com/assets/4723091/21979916/ceb1e2a2-db95-11e6-9fc0-5bc4e9b9da66.png)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
