### ISSUE TITLE
Can't build from 1.1.0 tarball on Arch Linux - Uncaught ReferenceError: __webpack_exports__ is not defined

### ISSUE THREAD

**Issue by aabmass** [zeit/hyper#1418]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Arch Linux**: 
- **1.1.0 release**: 

- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I made the Arch Linux AUR package for hyper. I noticed it stopped working after a rebuild, nothing opens. So I followed the dev instructions and tried debugging a bit. I did

* Downloaded 1.1.0 tarball
* Extracted it and went into directory
* `npm install`
* `npm run dev`
* In a separate terminal, `npm run app`

  The electron window opens with nothing showing. I opened the electron dev tools and the console shows:
  ```
  Uncaught ReferenceError: __webpack_exports__ is not defined                  bundle.js:2286
  total init time 120.87000000000006
  ```

The funny thing is, if I use `yarn install` instead of `npm install`, everything works.

Any ideas on what's causing this? I would guess its a Linux specific issue with the build setup.

**Comment by LestaD** [comment]
I have too problem on ubuntu 16.04

**Comment by micopc** [comment]
Having the same issues on macOS Sierra

**Comment by srimajji** [comment]
Windows 10 as well. Fortunately `yarn install` works :)

**Comment by aabmass** [comment]
After doing a little research, the `package.json` asks for `webpack@2.2.0-rc.3` but npm actually installed `├─┬ webpack@2.2.0-rc.7` yesterday, as you can see from the npm output above. I tried again today and npm decided to resolve a different version, `├─┬ webpack@2.2.0` and still not work. Yarn, however, installed the correct version `webpack@^2.2.0-rc.3`.

To fix this with npm, from a clean copy of `1.1.0`, I explicitly installed the right version after the initial install and the bundle works fine.
```bash
npm install
# waiting...
npm install webpack@2.2.0-rc.3
```

And it confirms it installed the rc.3
```sh
└─┬ webpack@2.2.0-rc.3 
  ├─┬ enhanced-resolve@3.0.3
  │ └── memory-fs@0.4.1 
  └── memory-fs@0.3.0 
```

Then I am able to run the app and it works fine. Can anyone confirm that explicitly installing `webpack@2.2.0-rc.3` with npm fixes this for you, too?

**Comment by aabmass** [comment]
Also, I'm running npm version `4.1.1`.

**Comment by aabmass** [comment]
Alright, I see the real issue is webpack/webpack#3980 and is caused by LazyParseWebpackPlugin. Removing that plugin from the webpack config altogether fixes the problem. From the webpack issue:

> This is caused by the LazyParseWebpackPlugin. It's not compatible. But as it's now enabled by default you don't need it anymore.
cc @TheLarkInn

**Comment by matheuss** [comment]
Thank you @aabmass – fixed!
