### ISSUE TITLE
CTRL+- to decrease font size doesn't decrease from the current font size value

### ISSUE THREAD

**Issue by maetthew** [zeit/hyper#1419]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  None
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: None
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Using CTRL+- resizes the font size either from the size on startup, or the value from last font size decrease instead of decreasing from the current font size

Reproduce:

Start hyper > Starts with 12px font size
![image](https://cloud.githubusercontent.com/assets/810218/22002587/8ae8b89e-dc4d-11e6-9d9b-7dc04749767f.png)

Press CTRL+(Minus) one time > Reduces fontsize from 12px to 11px
![image](https://cloud.githubusercontent.com/assets/810218/22002589/8dc11fde-dc4d-11e6-982f-187afff37499.png)

Press CTRL+(Plus) 5 times > Increases fontsize 5 times (the exact number is not visible >12px it seems) but let's assume 16px
![image](https://cloud.githubusercontent.com/assets/810218/22002599/92c6fdbe-dc4d-11e6-9176-a803fe766e55.png)

Press CTRL+(Minus) one time > Reduces fontsize from 11px to 10px
![image](https://cloud.githubusercontent.com/assets/810218/22002606/9750cdf6-dc4d-11e6-8862-6efeab29dafc.png)

**Comment by henrikdahl** [comment]
Can't reproduce this in 1.3.0, still having an issue?

**Comment by nmbradford** [comment]
I can reproduce this exact behaviour on vanilla and on all versions I've used (currently 1.4.3).  Windows 10.

**Comment by srikrishnacj** [comment]
I too have the same problem. 
Using Windows 10 latest update.
Hyper 1.4.8(stable)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
