### ISSUE TITLE
Unusable if a non-monospace font is set by mistake

### ISSUE THREAD

**Issue by mohsen1** [zeit/hyper#142]
I was trying to make my Powerline based font work that all of the sudden:

![screen shot 2016-07-15 at 6 03 47 pm](https://cloud.githubusercontent.com/assets/543633/16891880/80c843da-4ab6-11e6-91f2-eae0037c9ffd.png)

The cursor location is not accurate anymore.

**Comment by jasonpincin** [comment]
Did you get the powerline font working?

**Comment by mohsen1** [comment]
@jasonpincin yeah see #144

**Comment by chabou** [comment]
Outdated
Please try with our v2 and feel free to open a new issue
