### ISSUE TITLE
Bad behaviors with Chinese.

### ISSUE THREAD

**Issue by SidKwok** [zeit/hyper#1420]
<img width="442" alt="a7d81216-6d8d-4d0d-830f-c4a1b6752ad9" src="https://cloud.githubusercontent.com/assets/13268747/22004248/39114480-dc95-11e6-8d30-1e5ccac6dd91.png">

os version: macOS 10.12.2
hyper version: 1.1.0

**Comment by LoganDark** [comment]
getting weird characters pooped all over my terminal

![](https://puu.sh/tskzW/bb26769a5d.png)
![](https://puu.sh/tskBk/0ce21ab430.png)

**Comment by LoganDark** [comment]
![](https://puu.sh/tsKn3/6c2eec071c.png)

**Comment by f1238762001** [comment]
@SidKwok 
Try this css :
termCSS: '.unicode-node{width: 12px !important}',

12px is my font size, you can change to your configuration.

**Comment by SidKwok** [comment]
@f1238762001 
But it will also cause this issue:
<img width="64" alt="2030c653b9392690eea4a994e27648e2" src="https://cloud.githubusercontent.com/assets/13268747/22416309/af988b04-e708-11e6-882b-edff11e4f50d.png">

the cursor is blinking inside the characters.

**Comment by LoganDark** [comment]
@f1238762001 the issue is the weird chinese characters appearing out of nowhere.

**Comment by droyuki** [comment]
@SidKwok I got the same problem, did you fix this ?

**Comment by SidKwok** [comment]
@droyuki
You can try the CSS way, but it will cause the cursor issue.

**Comment by LoganDark** [comment]
@SidKwok do you have a solution for the random *extra* characters being pooped all over my terminal while sshing? doesn't appear otherwise

**Comment by droyuki** [comment]
@SidKwok you can try `.wc-node{width: 14px !important}` , this will not change your cursor.

**Comment by SidKwok** [comment]
@droyuki
Thanks!
