### ISSUE TITLE
Unable to download latest version on Windows

### ISSUE THREAD

**Issue by patoncrispy** [zeit/hyper#1422]
https://hyper-updates.now.sh/download/win returns a 404. This perhaps isn't the best place to report this - please advise if this is so!

**Comment by Erwyn** [comment]
It does for any platform I have to add.

**Comment by pablopunk** [comment]
I think it's solved now.

**Comment by matheuss** [comment]
It's working now 🎉

**Comment by patoncrispy** [comment]
Saaa-weeet! :)
