### ISSUE TITLE
Select pane shortcut cycles through open applications instead

### ISSUE THREAD

**Issue by navarurh** [zeit/hyper#1423]
Reproduce as follows
> open Hyper
> create a new tab [ctrl+shift+e]
> press ctrl+alt+tab to cycle through panes

OS : Ubuntu 16.04LTS
-

Hyper 1.1.0
Electron 1.4.7
linux x64 4.4.0-47-generic

**Comment by DzeryCZ** [comment]
I have the same issue on Windows machine. 

I think that the shortcut should be changed from `Ctrl+Alt+Tab` to e.g. `Ctrl+Win+Tab`.

---

OS: Windows 10 Creator's Update
Hyper 1.3.3

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
