### ISSUE TITLE
Running nano from Hyper on Windows, doesn't allow me to exit with CTRL+X.

### ISSUE THREAD

**Issue by pauldotknopf** [zeit/hyper#1424]
- **OS version and name**: Windows 10
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/pauldotknopf/bade93c56650f8fcff41c063b44a15e0
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Running nano from Hyper on Windows, doesn't allow me to exit with CTRL+X.

**Comment by stefanivic** [comment]
@pauldotknopf the shortcut for doing this on Hyper is `ctrl+shift+x`.

**Comment by pauldotknopf** [comment]
Is that specific to nano? Or, must all C+X commands (which work in normal cmd) also have shift?

**Comment by stefanivic** [comment]
@pauldotknopf Yes, i do believe so. For example copy is `ctrl+shift+c`

**Comment by arcanis** [comment]
Is it a wontfix? This is breaking quite a few applications (for example, the default Emacs configuration uses <kbd>Ctrl+x</kbd> as default modifier) .. :(

**Comment by ppot** [comment]
close in #1876
