### ISSUE TITLE
Hyperterm stuck at opening index.html

### ISSUE THREAD

**Issue by jekku** [zeit/hyper#1426]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Arch Linux x64
- **Hyper.app version**:  1.1

## Issue
Shows the following:

```
running in prod mode
electron will open file:///usr/lib/hyper/resources/app/index.html
```

and gets stuck there forever

**Comment by aabmass** [comment]
See #1418

**Comment by matheuss** [comment]
Thank you @aabmass 🙌
