### ISSUE TITLE
Arrow keys and scroll not functioning properly in windows.

### ISSUE THREAD

**Issue by mustafabbas** [zeit/hyper#1428]
Arrow Keys do not function on the terminal. For example if I press the up arrow key I cannot get the previous command I entered. Also in an application like vim I cannot use the arrow keys to move around the editor. In addition as I scroll though an editor like Vim only the last line is scrolled on the screen while the other lines are static. For example lets say my terminal shows lines 1-20 on my screen when I start scrolling the lines shown on the screen are 1-19 and then line 40 instead of lines 20-40.

Hyper 1.1.0
Electron 1.4.7
win32 x64 10.0.14393

**Comment by matheuss** [comment]
@mustafabbas which shell are you using? `bash`?

**Comment by mustafabbas** [comment]
yes

**Comment by matheuss** [comment]
Please check #1127 🙌
