### ISSUE TITLE
Generated dist app doesn't open a window

### ISSUE THREAD

**Issue by miguelcg** [zeit/hyper#1429]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X El Capitan v10.11.6
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: -
- **Relevant information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: -
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
I've just cloned the repo, `cd` into hyper folder and ran: `npm install` followed by `npm run dist`.
A folder `dist` is generated containing another folder with the app file `Hyper`. When I open this file I don't see the app. I can see on the top bar the name `Hyper` but even if I try to open a new window/tab nothing happen. It's like the window is invisible.

**Comment by matheuss** [comment]
Closed via https://github.com/zeit/hyper/commit/26167ab38a3dc1ab22c9afd975c8575ea80cb062 – #1418
Thank you @miguelcg for bringing that to our attention on [zeit.chat](https://zeit.chat) 🙌
