### ISSUE TITLE
White text on a white screen

### ISSUE THREAD

**Issue by jorgebucaran** [zeit/hyper#1430]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate, but I may be wrong.

- **OS version and name**: macOS
- **Hyper.app version**: Version 1.1.0 (1.1.0.1408)
- **Shell**: fishshell

### White text on a white screen

<img src="https://cloud.githubusercontent.com/assets/56996/22136245/ad52ba4e-df16-11e6-91bd-cc0bdf3e1e77.png" width=400 />

Manually editing /Users/$USER/.hyper.js fixed the issue, but I usually never need to do this when using other terminals. Editing the color was difficult too since I couldn't see a thing! :D

```json
    foregroundColor: '#fff',
    backgroundColor: '#000',
```

My foreground color is set to "`normal`", in fish

```fish
echo $fish_color_command 
normal
```

which I assume translates to white or black depending on the background color? I can confirm both Terminal.app and iTerm.app pick the right color.

**Comment by MAPESO** [comment]
@JorgeBucaran I could try this problem in the *stable* or *canary* version.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
