### ISSUE TITLE
UI freezes on huge input.

### ISSUE THREAD

**Issue by JostCrow** [zeit/hyper#1432]
- Ubuntu 16.10
- Hyper 1.1.0
- https://gist.github.com/JostCrow/c9d84cdc7be554215d35ef79dc32860b
- Can't open the dev tools. (it froze)
- The issue also happens with no plugins

## Issue
When printing a huge amount of data in the terminal (a base64 encoded image) The terminal completely freezes. It will not respond any longer.

I opened multiple tabs. In all the other tabs the process is still running.

To make it easier. This is a copy of the base64 string.
https://gist.github.com/JostCrow/638ba613e494c1b68fd98dbdbedcad43

Seen the size I can understand that it fails

**Comment by matheuss** [comment]
Please check #687 🙌
