### ISSUE TITLE
Takes a lot of memory and sometimes CPU.

### ISSUE THREAD

**Issue by alduro** [zeit/hyper#1433]
Hyperterm is awesome but it takes a lot of memory. Hyper Helper uses 1Gb for 4 opened tabs.
Don't like to go back to iTerm2 👎 
Is it me only or anyone else ?

**Comment by francisl** [comment]
e.g.

`grep -R "b..t" *` in a project directory.

iterm2 finished the grep in 10 sec. I needed to kill hyper after 3 min.

Memory was 6gb and never got collected.

**Comment by alduro** [comment]
Yes exactly. Ag command on vim that uses grep underneath neverends.

**Comment by francisl** [comment]
Just to be clear, I didn't kill hyper (the application) but the grep process. I continued using hyper for a couple of hours, and it never reclaimed the memory.

**Comment by alduro** [comment]
Yes, same here.

**Comment by isgj** [comment]
I made a test (a small program that prints 10000 lines, **nothing special**) and this are the results
![schermata del 2017-02-09 19-39-45](https://cloud.githubusercontent.com/assets/20517048/22800887/bc8223fa-ef02-11e6-9148-ccf46098b26d.png)

**Comment by FynnZW** [comment]
Same here. Tried using ack and I couldn't even abort anymore with `ctrl`+ `c`.
Had to restart the terminal. This is recurring.

iTerm2 is able to do the same task without crashing.

**Comment by emirotin** [comment]
I've recently had an issue on Win 10 with Hyper > Bash on Windows > Zsh > Oh-my-zsh (+ pure)
The 5 idle tabs (with git repos open) were eating 99% CPU.

**Comment by JonDum** [comment]
My poor RAM :(

<img width="827" alt="screen shot 2017-07-31 at 3 50 23 pm" src="https://user-images.githubusercontent.com/191920/28801792-ff031b1c-7607-11e7-951c-072a0a8496da.png">

**Comment by Dayjo** [comment]
I regularly have this problem running webpack builds or other build processes. Often to the point where the entire app crashes completely and I have to force quit. 

IF there's some specific information I can provide I shall fetch it.

**Comment by Dayjo** [comment]
@Stanzilla is there a particular reason this is closed? Can we provide more specific data to help resolve the problems people have?

**Comment by Stanzilla** [comment]
Mostly that it's outdated and stale and the canary version already has new versions of xterm (and soon electron) that should help with this

**Comment by Dayjo** [comment]
Great, thanks for the update.
