### ISSUE TITLE
Can't Ctrl+Shift+C to copy 

### ISSUE THREAD

**Issue by Mehuge** [zeit/hyper#1437]
because selection is cleared as soon as Ctrl or Shift is pressed

Hyper 1.0.0
Electron 1.4.7
win32 x64 6.3.9600

**Comment by stefanivic** [comment]
@Mehuge This is actually fixed in : https://github.com/zeit/hyper/pull/1406 .
You can build it now from source or wait for a new release of Hyper (soon).

**Comment by matheuss** [comment]
@Mehuge thanks for reporting – I'm preparing the next release right now, should be out early this week 😄
