### ISSUE TITLE
Incorrect font settings

### ISSUE THREAD

**Issue by mohsen1** [zeit/hyper#144]
I see an small gap between my characters that shows up in certain zoom levels. 
- I'm using [Sauce Code Pro for Powerline](https://github.com/powerline/fonts/tree/master/SourceCodePro) font
- I see this issue at 13px and 12px zoom levels
  ![screen shot 2016-07-15 at 6 10 15 pm](https://cloud.githubusercontent.com/assets/543633/16891922/a2788462-4ab7-11e6-8d0a-920e9080d7e5.png)\

**Comment by wesbaker** [comment]
I'm getting a similar look when using Hack for Powerline.

**Comment by taohex** [comment]
![image](https://cloud.githubusercontent.com/assets/1678003/24484938/82b6c002-1533-11e7-8713-d0d4c7e94238.png)
non-monospace font and Chinese is broken.

**Comment by chabou** [comment]
Please try our v2
