### ISSUE TITLE
Duplicated command

### ISSUE THREAD

**Issue by charlespeters** [zeit/hyper#1441]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.2
- **Hyper.app version**: 1.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/charlespeters/51c8d2a5e3393bdd9cb64b44a0ec743e
- **Relevant information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

i'm often getting commands duplicated after i run them, not sure what the error is here the only thing i've seen is that the duplicate commands are wrapped in an `<x-row>`  component with the line-overflow attribute, when none of the other `<x-row>`  components have that attribute.

```markup
<x-row line-overflow="true">
<span>cat</span><span style="font-weight: bold; font-style: italic;">%</span><span>                                                                                                                                                        </span>
</x-row>
```

Example:

<img width="514" alt="screen shot 2017-01-22 at 4 18 16 am" src="https://cloud.githubusercontent.com/assets/4588060/22182426/107f9eb8-e05a-11e6-994a-42d7cd2e2ceb.png">

**Comment by scottcorgan** [comment]
I can confirm this is happening as well. 

- Hyper `1.2.1`
- Zsh
- Pure theme
- No Plugins

<img width="391" alt="screen shot 2017-02-16 at 7 34 51 am" src="https://cloud.githubusercontent.com/assets/974723/23021535/6c39af40-f41a-11e6-9850-254654f5ff73.png">

This also happens to me in VSCode, so I'm assuming it's not technically a Hyper only thing.

**Comment by charlespeters** [comment]
@scottcorgan have you had any fixes?

**Comment by charlespeters** [comment]
can also confirm that it's still an issue in the new hyper release `1.2.1`

<img width="520" alt="screen shot 2017-02-16 at 11 28 26 am" src="https://cloud.githubusercontent.com/assets/4588060/23037430/28399370-f43b-11e6-92d7-d64deeb9561f.png">

**Comment by mos8580** [comment]
Getting the same problem with zsh, with the native one and the homebrew version. Does not happen with bash.

**Comment by charlespeters** [comment]
still experiencing this on 1.3.0

@mos8580 @scottcorgan what about you?

**Comment by mos8580** [comment]
@charlespeters @scottcorgan I am still experiencing it, however I just disabled oh-my-zsh (by moving the ~/.oh-my-zsh directory) and the issue does not appear...

**Comment by charlespeters** [comment]
okay i think i've finally figured this out

my main issue was not with hyper, it was with my `.zshrc` in misspelling what i was setting `$TERM` to be.

**Comment by marcraminv** [comment]
* Hyper 1.3.2
* Zsh
* Pure theme
* No Plugins
Still experiencing
<img width="314" alt="captura de pantalla 2017-05-10 a las 22 11 24" src="https://cloud.githubusercontent.com/assets/13021787/25919027/b4f9b8a2-35cd-11e7-9948-42bdb3e4499e.png">
