### ISSUE TITLE
Use :zap: lightning emoji in repo description on Github

### ISSUE THREAD

**Issue by jancborchardt** [zeit/hyper#1447]
Currently it says just:

> A terminal built on web technologies

But much nicer would be with an emoji. We do that for every repo of [Nextcloud](https://github.com/nextcloud) and especially for Hyper it also fits cause the logo / lightning is a common emoji:

> :zap: A terminal built on web technologies

Just add the `:zap: ` in the beginning. ;)

**Comment by leo** [comment]
I personally don't like it at all that so many people are cluttering GitHub's carefully thought-out and good-looking UI by putting random stuff in places where it doesn't belong.

But that's just my take on this... 😅 

If you have any feedback that provides value in terms of readability or allowing people to discover what Hyper is more easily, I would be very happy to implement this. But I doubt that any form of emoji helps in that place. 😊 🙏

**Comment by jancborchardt** [comment]
Well, it is sort of an icon for the repository. Just a playful thing. :) At the very least it helps to stand out and acts as a sort of marketing for Hypers snappiness (as the lightning is used in the logo). As soon as there is an emoji for "terminal" I'd say that definitely "provides value in terms of readability or allowing people to discover what Hyper is more easily".

Interface design often evolves based on hacks like these, so I wouldn't be surprised if at some point it's possible to add logos/icons to a repository.
Meanwhile, a bunch of people are already doing it with the Emojis: https://github.com/trending?since=monthly
