### ISSUE TITLE
CTRL key doesn't work for copy and paste

### ISSUE THREAD

**Issue by ph98** [zeit/hyper#1452]
- im using ubuntu 16.04
in hyper ctrl key not work and i cant use it for copy pase and ... (ctrl+c , ctrl+v)

when i select some text if i press ctrl then hyper deselect them.
is it a bug or i missing something?

sorry for my poor english :-)
Hyper 1.1.0
Electron 1.4.7
linux x64 4.4.0-59-generic

**Comment by stefanivic** [comment]
@ph98 the shortcut for copy/paste in hyper is `ctr+shift+c` and `ctrl+shift+v`

**Comment by ph98** [comment]
@stefanivic i know that :-)
but the problem is ctrl key when I'm trying to copy and paste ...
it not work for me! 
i try to disable all plugin i have but still the problem not solved

**Comment by stefanivic** [comment]
@ph98 yeah, this was fixed in : https://github.com/zeit/hyper/pull/1406 So you can either build from source or wait for the 1.2.0 update.

**Comment by ppot** [comment]
close in #1876
