### ISSUE TITLE
Error: EPERM operation not permitted ... on windows 10

### ISSUE THREAD

**Issue by SinaKarimi7** [zeit/hyper#1453]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Enterprise 10.0.10586
- **Hyper.app version**: 1.1.0

## Issue

Hi there. i wanna install lastst version and : 
![image](https://cloud.githubusercontent.com/assets/16350906/22286553/e04201b6-e304-11e6-94a4-a0a615c3fc44.png)
what can i do for solve this problem?!

**Comment by joshbnntt** [comment]
Having the same exact problem.

- OS version and name: Windows 10 Enterprise Version 1607
- Hyper.app version: 1.1.0

**Comment by gifteddiz** [comment]
Same issue 
- Windows 10
- Hyper 1.3.1

**Comment by RobertSmart** [comment]
Same here

Using version 1.3.3 on windows 10.

Very annoying, but does seem to clear after closing several of the dialogs

**Comment by Mohamed3on** [comment]
Same, windows 10.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by Gabriellavoura** [comment]
Same

**Comment by mrg0lden** [comment]
Same here as well v2.0.0
