### ISSUE TITLE
Refresh slows to a crawl with split panes

### ISSUE THREAD

**Issue by alexanderkoumis** [zeit/hyper#1456]
How to reproduce:
 
1. Split pane into two or more panels
2. wget a big file (a gig?) in each pane (file should be big enough so that the wget download animation from the first download is still happening when you start the second wget).

The FPS for each pane slows to ~1 FPS and sometimes completely stops.

**Comment by eamodio** [comment]
I've seen the same thing with split panes just over time get VERY slow (and often the helper process is using a lot of memory ~1GB)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
