### ISSUE TITLE
Ctrl+C, Ctrl+V shortcuts no longer working in v1.1.0

### ISSUE THREAD

**Issue by cjb5790** [zeit/hyper#1458]
- **OS version and name**: Windows 10 Pro v1511
- **Hyper.app version**: v1.1.0

## Issue
Ever since updating to v1.1.0, I can no longer use Ctrl+C to copy or Ctrl+V to paste. The context menu options still work, but the shortcuts do nothing.

**Comment by therealscottcarlow** [comment]
Can confirm, keyboard shortcuts for copy/paste are not functional in hyper. It's fine in other terminals.

Running on GNU/Linux with zsh. Hyper version 1.1.0

**Comment by yonson2** [comment]
I can also reproduce this issue on my machine.
Running 1.1.0 on a fresh Arch install.

**Comment by maxknu** [comment]
Confirming on windows 10, shortcuts do not work.

**Comment by therealscottcarlow** [comment]
Actually, should have looked at other open issues. I'm pretty sure this is related to #1452. This issue should probably be merged or closed as a duplicate.

**Comment by atulodra** [comment]
Yeah this should be merged to #1452 and hopefully the fix will be applied in v1.2.0  or smth. Paste via Ctrl+C works for me if at first I select all with Ctrl+A and then do the paste shortcut.

**Comment by jacola** [comment]
Same problem on W7. I can paste when the turquoise install window is still being displayed, but once the install is done, I cannot paste.

```
Hyper 1.1.0
Electron 1.4.7
win32 x64 6.1.7601
```

**Comment by Seminioni** [comment]
Thats why I dont use Hyper anymore...

**Comment by mykytanikitenko** [comment]
I have the same problem in Windows 10

**Comment by kleinfreund** [comment]
This issue is still around. When will this be fixed? Copying stuff from the command line is kinda critical.

**Comment by renanpvaz** [comment]
Same problem here using Windows 8

**Comment by nealoke** [comment]
Same problem (windows 10)

**Comment by Kev-CS** [comment]
Same problem on Linux Mint 18.1 with zsh

**Comment by Zignd** [comment]
Same problem on Ubuntu 16.04.1 LTS with zsh.

**Comment by cjb5790** [comment]
This appears to be related to some focus issues. Even though the window has focus, the cursor does not. If I double click a few times on the cursor, focus comes back to the line and the Ctrl+V shortcut works again.

**Comment by AWulkan** [comment]
This still doesn't work with Windows 10 in the new Hyper 1.2.1 version. I thought it was fixed.

**Comment by cjb5790** [comment]
v1.2.1 actually has resolved this for me on Windows 10.

**Comment by kleinfreund** [comment]
> v1.2.1 actually has resolved this for me on Windows 10.

@cjb5790 Can confirm this, too, on Ubuntu. Should be in the changelog.

**Comment by StandardNerd** [comment]
I use Hyper version 1.3.1 on Arch Linux and pasting still doesn't work.

**Comment by kleinfreund** [comment]
To clarify, <kbd>Ctrl</kbd><kbd>C</kbd> still does not copy but deselect the selected text. <kbd>Ctrl</kbd><kbd>V</kbd> does work.

**Comment by benjamin-rood** [comment]
I'm not trying to pile on, but I just want to point out that in **all flavours of Ubuntu 16 when using Zsh**, the only keyboard shortcuts I can reliably get to work in the expected fashion is <kbd>Ctrl</kbd>+<kbd>N</kbd> and <kbd>Ctrl</kbd>+<kbd>R</kbd>. 

Using <kb>Super</kbd> plus the documented shortcuts makes no difference.

I'm a regular user of hyper on macOS where it works exactly as expected, so I know what a great little terminal emulator this is.

Update: Changed scope to properly include currently supported versions of Ubuntu.

**Comment by ppot** [comment]
#1509

**Comment by ppot** [comment]
closed in #1876
