### ISSUE TITLE
Can't render italics

### ISSUE THREAD

**Issue by anrddh** [zeit/hyper#1460]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.2
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/awesomeaniruddh/7129bf3d86b515e139ec5b68ec4c57df
- **The issue is reproducible in vanilla Hyper.app**: Yep
## Issue

![screen shot 2017-01-27 at 21 30 20](https://cloud.githubusercontent.com/assets/5279150/22393610/d423fedc-e4d7-11e6-8856-049c00b212f0.png)

^ The same file in iTerm2:
<img width="682" alt="screen shot 2017-01-27 at 21 31 03" src="https://cloud.githubusercontent.com/assets/5279150/22393612/f01c1e80-e4d7-11e6-9611-4072fc42bd98.png">

The italics aren't rendering: HyperTerm renders the comments with a ugly grey background.

**Comment by audunolsen** [comment]
I too would like to see this addressed.

**Comment by albinekb** [comment]
Is this still an issue in 2.0?

**Comment by audunolsen** [comment]
It is. Currently using the font Menlo which has an italic set.

You can determine if a terminal supports italics by running this command:

> echo -e "\e[3m foo \e[23m"

Hyper does not render italics, while Apple's terminal do.

<img width="852" alt="screenshot 2018-04-19 12 27 40" src="https://user-images.githubusercontent.com/16224137/38986622-49e63766-43cd-11e8-9de8-36106c81fe15.png">

**Comment by albinekb** [comment]
Seems like xterm doesn't support italics, this is a screenshot from your test command in VS Code (that also uses xterm for rendering)
![image](https://user-images.githubusercontent.com/5027156/38989284-91396472-43d6-11e8-9902-6c187ad08313.png)

**Comment by albinekb** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/580

**Comment by flybayer** [comment]
I just opened a pull request to xterm that adds support for italic! https://github.com/xtermjs/xterm.js/pull/1422

**Comment by lyndsysimon** [comment]
Any idea when we'll see this in the release version of Hyper?

**Comment by lokesh-krishna** [comment]
Any update regarding this?

**Comment by lyndsysimon** [comment]
@lokesh-krishna Well, it seems like the underlying issue was with xtermjs, not Hyper, and that the issue has a fix in place. The `canary` branch shows to be using a version of xtermjs with the fix included, but the lastest full release was 2.0.0, which doesn't include it.

If you want this to be applied through your OS's package manager, you'll have to wait for the 2.1.0 release to go live and your OS's repositories to update their version. Otherwise, you can download [2.1.0-canary.2](https://github.com/zeit/hyper/releases/tag/2.1.0-canary.2) and it works today :)

**Comment by lokesh-krishna** [comment]
I just installed the 2.1.0-canary.2 release and tested italics support by entering `echo -e "\e[3m foo \e[23m"`. The output was the same as earlier and not in italics. Does this require any additional configuration?

**Comment by oguzbilgic** [comment]
@lokesh-krishna were you able to solve the issue? I'm on v2.1 stable but italics are still not working

**Comment by lokesh-krishna** [comment]
I'm on 2.1.0-canary.3 now and even this version doesn't support italics.
So no, haven't been able to solve this.

**Comment by audunolsen** [comment]
This may be slightly off topic, but hyper now successfully displays italics (canary) for me — except in vim/neovim. I wonder if anyone is familiar with this? @anrddh You reported this with screenshots explicitly showing Neovim, has this resolved for you?

<img width="873" alt="screenshot 2019-01-25 23 48 06" src="https://user-images.githubusercontent.com/16224137/51777357-0b4e3400-20fd-11e9-8378-69682ba44485.png">

**Comment by jasonoverby** [comment]
@audunolsen I am experiencing the same issue where italics are present except for vim/neovim

**Comment by ntwb** [comment]
I just came looking to see if Hyper supported italics, it appears v2.1.2 is working for me:

![Screen Shot 2019-03-22 at 5 30 54 pm](https://user-images.githubusercontent.com/1016458/54804763-c1329a80-4cc8-11e9-9074-64878f8f4113.png)

Above with the Input Mono font, below with Operator Mono font

![Screen Shot 2019-03-22 at 5 33 27 pm](https://user-images.githubusercontent.com/1016458/54804779-d5769780-4cc8-11e9-9c69-be6a4b5a4385.png)

**Comment by audunolsen** [comment]
This may be slightly of topic for this issue, but I was able to resolve my own spesific problem; Vim and pretty much everything but Neovim was able to display italics. I wanted italics specifically for Neovim. I ran [the following script](https://gist.github.com/sos4nt/3187620) which I was fortunate enough to stumble across. The script fixes the terminals' escape sequences for italics. This should probably be addressed by xterm, so this workaround can be avoided.

**Comment by jrieko** [comment]
Hyper 3.0.2 (stable) here, italics don't work, neither from `echo -e "\e[3m foo \e[23m"`, or in vim.

I've tested with fonts Menlo and Ubuntu Mono, which do have an italic typeface.

**Comment by Stanzilla** [comment]
Can you try with a CI build of current canary or maybe compile one yourself?

**Comment by thenerdlawyer** [comment]
i am having this issue with 3.02 stable and canary. Tried numerous fonts with italic typefaces including Input Mono, Menlo, and MesloLGS NF.

Running ubuntu on WLS

**Comment by yuntan** [comment]
I'm having this issue with 3.02 (stable) for both WebGL and Canvas renderer, and 3.1.0-canary.1 for Canvas renderer. I'm using Victor Mono font. I'd run `echo -e "\e[3mitalic\e[23m"` on WSL Ubuntu on Windows 10 (1909).

**Comment by ceoshikhar** [comment]
> I'm having this issue with 3.02 (stable) for both WebGL and Canvas renderer, and 3.1.0-canary.1 for Canvas renderer. I'm using Victor Mono font. I'd run `echo -e "\e[3mitalic\e[23m"` on WSL Ubuntu on Windows 10 (1909).

Same here! did you find a fix?

**Comment by markpanado** [comment]
> This may be slightly of topic for this issue, but I was able to resolve my own spesific problem; Vim and pretty much everything but Neovim was able to display italics. I wanted italics specifically for Neovim. I ran [the following script](https://gist.github.com/sos4nt/3187620) which I was fortunate enough to stumble across. The script fixes the terminals' escape sequences for italics. This should probably be addressed by xterm, so this workaround can be avoided.

This solves my problem! Italics are now rendering with vim-gruvbox. Thank you!
