### ISSUE TITLE
Mirror working directory when splitting or opening a new tab

### ISSUE THREAD

**Issue by Jonas-Drotleff** [zeit/hyper#1461]
When working in a certain directory (e.g. `~/directory/subdirectory/`), splitting the panel or opening a new tab should (maybe with a special key combination) mirror the working directory so that you don't have to navigate to it first.

This is particularly helpful when you need to run multiple commands in one directory simultaneously and don't want to `cd` all the time.

**Comment by matheuss** [comment]
@Jonas-Drotleff there's a very nice plugin for that: [hypercwd](https://github.com/hharnisc/hypercwd) 😄
