### ISSUE TITLE
Error when opening hamburger menu in Windows 10

### ISSUE THREAD

**Issue by lyzs90** [zeit/hyper#1462]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home 64-bit (10.0, Build 14393)
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/lyzs90/879d7195202c78d2cf0ca96ff97c13b6
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I'm running into the following error when I click on the hamburger menu:
![hyper](https://cloud.githubusercontent.com/assets/13202538/22412361/a336be3c-e6e8-11e6-9f9a-d308b1d375bc.PNG)

Reinstalling the client and/or removing plugins does not resolve the issue.

**Comment by rlfbckr** [comment]
I have the same  error. Hyper app 1.2.1 Windows 10 (64 bit).

**Comment by rlfbckr** [comment]
This seems to be related to Windows 10 DPI scaling. The error occurs only if a custom scaling factor (eg. 133% ) is set.

**Comment by pcdude2143** [comment]
Made a fix for this. Can someone review and merge? Thanks.
