### ISSUE TITLE
Hyper intermittently does not print special characters on Mac OS X when the US International Keyboard is selected

### ISSUE THREAD

**Issue by alxie** [zeit/hyper#1463]
Mac OS X has a different way of treating special characters when the "US International" keyboard is selected: If I want to type the plain simple tilde symbol "\~", I need to press the "\~"+space. This is needed because you could apply the tilde to a letter (example: ã õ), so the first time I push the tilde key, it actually "buffers" the symbol for the next action (where "space" prints the tilde symbol alone).

On Hyper, specially when I'm typing fast and on a slow ssh connection, the tilde symbol (and others, like "`", """, "'") some times gets stuck inside the cursor shape:
![screen shot 2017-01-30 at 12 12 13 pm](https://cloud.githubusercontent.com/assets/7647054/22426279/d5596732-e6e5-11e6-9ee4-6bdd88735d04.png)

When this happens, I need to push the tilde key again **several times** before it "unstucks" from the cursor shape into a normal tilde. 

-

Hyper 1.1.0
Electron 1.4.7
darwin x64 16.3.0

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
