### ISSUE TITLE
Paste issues

### ISSUE THREAD

**Issue by Chokollis** [zeit/hyper#1464]
You need to click into the line to paste any type of text. I was wondering if this kind of pasting a wanted behavior? 

-

Hyper 1.1.0
Electron 1.4.7
win32 x64 10.0.14393

**Comment by therealscottcarlow** [comment]
#1458 and #1452 already reference this problem. If you build from Master it is already fixed as is slated for inclusion in the 1.2 release.

**Comment by CodeTheory** [comment]
This is fixed in an upcoming release and already mention elsewhere. Closing this in favour of previous references 😄
