### ISSUE TITLE
Traversing Hyper with the mouse

### ISSUE THREAD

**Issue by citrusui** [zeit/hyper#1466]
__This is a rather niche issue, so apologies if you have trouble understanding it.__

Is it possible to configure a setting that would allow a user to change the position of their cursor using the mouse pointer? Similar to the JavaScript console in Chromium?

I've never wondered why Terminals don't allow you to traverse with the mouse; perhaps someone can shed some light on this...

**Comment by matheuss** [comment]
@citrusui that's a thing I'd be very interested to see on Hyper. I'd be very interested on implementing it too, but unfortunately I'm incredibly busy lately

**Comment by matheuss** [comment]
Actually @citrusui there's already #316 (thanks @timneutkens) 😄

**Comment by citrusui** [comment]
Whoops! My apologies.

**Comment by matheuss** [comment]
Don't worry 🙌
