### ISSUE TITLE
Problem with hyper and fish using previous argument

### ISSUE THREAD

**Issue by celebrion** [zeit/hyper#1467]
- **OS version and name**: Mac OS 10.12.2
- **Hyper.app version**: 1.1.0.1408
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue
Using _fish_ as default shell you should be able to press Alt+arrowUp for command completion with argument from previous command (in a similar way that you use **!*** in bash). This does not work in Hyper at all. Upon pressing Alt+arrowUp nothing happens at all.

This is an absolute dealbreaker considering a switch from iTerm3 to Hyper.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
