### ISSUE TITLE
Terminal Locks with Continuous Output

### ISSUE THREAD

**Issue by brentgann** [zeit/hyper#1470]
I am on the latest version of Hyper.app.

I was evaluating the application and noticed that when I run "yes" command, it locks up the entire terminal and you are unable to interact with any part of the terminal with keyboard commands. You can not even CNTRL-C to stop the command.

**Comment by TheSuperFly** [comment]
Might be related with #571

**Comment by ppot** [comment]
Closing in favor of #555
