### ISSUE TITLE
mystery close issue

### ISSUE THREAD

**Issue by theskillwithin** [zeit/hyper#1472]
- [yes ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [yes ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: osx sierra 10.12.3
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/theskillwithin/6327b302bc8aea31db930f4239f9429c
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
If I Quit hyper.app then reopen it, all the sudden any options disappear the only single option there is: Hyper > Quit Hyper.   the Shell, Edit, View, etc... all disappear.  and I am unable to open up a new Hyper Window.  The only way I have found to fix this is to delete all the node_modules then npm i and launch hyper.

**Comment by moimikey** [comment]
do you have two versions of node installed?

**Comment by albinekb** [comment]
@theskillwithin is this working with the latest hyper?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
