### ISSUE TITLE
Hyper fails to load bash on Windows 10

### ISSUE THREAD

**Issue by citrusui** [zeit/hyper#1476]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10, build 1607
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: <https://gist.github.com/anonymous/1e07e052548d8c853f174e3809c2e20d>
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

On Windows 10, Hyper seems to fail to initialize the bash shell.

Running Bash from the Linux subsystem works fine, but running it from Hyper does not...

![hyperapp-err](https://cloud.githubusercontent.com/assets/9056756/22553921/607f80ba-e92c-11e6-8845-bf24cde52676.png)

Moving `.hyper.js` to another location temporarily fixes this problem, but, of course, calls `cmd.exe` instead...

![hyper-cmd2bash](https://cloud.githubusercontent.com/assets/9056756/22554120/0704170c-e92d-11e6-9780-5fb35ee3d6ab.png)

Because I am using the Linux subsystem , I thought perhaps Hyper did not like that my `.hyper.js` was using LF line endings. However, neither CRLF not LF endings had any effect. I theorize that since I am getting the "File not found" error, perhaps Hyper is failing to locate my user directory.

I have uninstalled Hyper several times, and removed it's app directory (`%appdata%/Local/hyper`). Removing the app and it's various settings did not fix anything.

The output from `lsb_release` may be of some help... perhaps Ubuntu 16.10 is causing issues?

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety
```

**Comment by matheuss** [comment]
@citrusui can you, on cmd.exe, run `where bash` and then change the value of your `shell` in the `.hyper.js`? 😄

**Comment by citrusui** [comment]
I don't have my Windows box immediately available, but I should be able to test either in a couple of hours or by tomorrow. Should've filed this bug yesterday 😖

**Comment by citrusui** [comment]
Okay, so setting `shell` to `C:\\Windows\\System32\\bash.exe` works as expected now! Unfortunately that means I have to use a separate `.hyper.js` for macOS and Linux.

Perhaps a setting like `win.shell` could be added? Windows is the only OS using the `.exe` extension for executables.

**Comment by Anahkiasen** [comment]
Since this is a JS file and not a JSON file, is there not an environment variable that can be used, more simply? Like

```js
'shell': process.env.OS === 'Windows' ? 'C:/System32/bash.exe' : '/usr/local/bin/bash',
```

Or something? Or would that not work depending on how Hyper loads the configuration

**Comment by Stanzilla** [comment]
```
shell: 'C:\\Windows\\System32\\wsl.exe',

// for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
// by default ['--login'] will be used
shellArgs: [],
```
