### ISSUE TITLE
Developer Tools Blank on Linux Ubuntu 16.04

### ISSUE THREAD

**Issue by dabfleming** [zeit/hyper#1477]
I'm still seeing #664 

Any time I open the dev tools they are just a blank white area of the window. I can click and cause things to happen, but can't see any of the controls.

Screenshot appears to be in device mode. Note the white area around and on the right of the actual terminal.

![image](https://cloud.githubusercontent.com/assets/3885717/22557594/f5cd2a62-e938-11e6-894a-da5e34494dcf.png)

Hyper 1.1.0
Electron 1.4.7
linux x64 4.4.0-59-generic

**Comment by CodeTheory** [comment]
@fearphage @flybayer is this happening for you guys?

**Comment by fearphage** [comment]
I cannot confirm, but I'm on 16.10 (x64). I would add the tag `regression`. This was working previously.

![image](https://cloud.githubusercontent.com/assets/23887/22832665/8b03e4ae-ef74-11e6-99cf-a3c1f9a1e114.png)

**Comment by flybayer** [comment]
Dev tools work for me on Ubuntu 14.04.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
