### ISSUE TITLE
Zsh: URL not recognized without protocol

### ISSUE THREAD

**Issue by maki-chan** [zeit/hyper#1481]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS X 10.11
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/maki-chan/79a0738c433d93378a6058450e5fa02d
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Whenever I input an url without the protocol, e.g. `google.com` it does not open the website in Hyper as I would expect it from the demo on the main page, but it says `zsh: command not found: google.com` instead (yes, I am using zsh, oh-my-zsh from Homebrew to be more exact). I always need to write `http://google.com` for it to work.

**Comment by ppot** [comment]
@maki-chan This is expected in the current implementation. This will be updated later on as of #1099

**Comment by Stanzilla** [comment]
That feature was removed.
