### ISSUE TITLE
Application freezes when running code with infinite loops

### ISSUE THREAD

**Issue by FlashTheDash** [zeit/hyper#1484]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.4 Beta
- **Hyper.app version**: 1.1.0 (1.1.0.1408)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/FlashTheDash/af69762f8303672effabf9b9dcdc2a47

## Issue

The entire application freezes when running code with infinite loops in python.  No keyboard shortcuts work, so I can't use keyboard interrupt to stop the script.  If I have an infinite loop in my code, then I have to force quit the application to do anything.

Arbitrarily long `for` loops run just fine.

If I use terminal.app, then keyboard interrupt works just fine.

an example of some code that would cause the application to freeze:

```python

while True:
    #anything can be inside the loop
    print("hello")

```

**Comment by ppot** [comment]
Referencing this to #555
Might be different so I won't close it yet.

**Comment by akabab** [comment]
where are we with this ?

**Comment by eshanmind** [comment]
Same issue a year later, it turns out that the same issue exists with java, and it only happens if you are printing something inside the loop, if it's a silent infinite loop, you can still `^C` it.

**Comment by chabou** [comment]
It has been really improved in our upcoming v2 (currently available on our canary update channel).
