### ISSUE TITLE
Possible to access Hyper from WebBrowser Externally?

### ISSUE THREAD

**Issue by kalzi** [zeit/hyper#1486]
Hyper is a Beautiful and engaging!!! I am no developer, but curious to check if its possible to access Hyper over webbrowser over the network? I suspect this may be possible as Hyper is built using webtechnologies, but I couldnt find any help around this topic. 

Kindly post/direct to any procedures on this subject if this is possible.

**Comment by pahakalle** [comment]
that would be a fairy big security risk. So i i doubt it is possible or ever will.

**Comment by ppot** [comment]
Yeah. @rauchg This would include security risk. However @kalzi you can still access your PTY session over ssh.

**Comment by kalzi** [comment]
Well.. I totally agree on the security banner, however, my idea is to host hyper over a bare docker container with limited tools for log views etc., which shall sit behind a restricted URL. I can understand the usecases are very limited, i tried `wetty` and honestly I would prefer *Hyper* in all its glory. 

Any guidance on this will be much appreciated if one thinks this is possible.

**Comment by bobswift** [comment]
Can you reconsider this? Why is this anymore of a security risk than wetty? Security is not an issue on a private network or running as a docker image with controlled access, etc....

**Comment by albinekb** [comment]
@bobswift can't you use SSH to connect to remote session?
