### ISSUE TITLE
JavaScript error when trying to resize (Ctrl + Shift + R)

### ISSUE THREAD

**Issue by vaporwavie** [zeit/hyper#1487]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/vaporwavie/1dccbb87b8c7c93d41b5743b474f2aae
- **The issue is reproducible in vanilla Hyper.app**: Only hpm plugin is installed.

## Issue

I tried to reverse-search a command, which didn't work (tried <code>CTRL + R</code>). Then I tried using a SHIFT as combination and a weird glitch happened. I forced it one more time and it returned me this error:
![JavaScript err](http://i.imgur.com/JyWheeB.png)
And after I pressed "OK", Hyper just went crazy:
![Hyper glitch](http://i.imgur.com/8ysF9Wl.png)

That's it. Reloading it solves the inconvenience, but I believe this should be fixed :smile:.

**Comment by ppot** [comment]
@vaporwavie version 2?

**Comment by vaporwavie** [comment]
<pre>Hyper.app version: 2.0.0</pre>
Yep

**Comment by ppot** [comment]
mmmm... curent tag is 1.1.0

**Comment by vaporwavie** [comment]
Oh, yes! My bad. I misunderstood hpm version with hyper's lol. Gonna edit it ASAP. 
<pre>Hyper.app version: 1.1.0</pre>

**Comment by ppot** [comment]
should work. close in #1876
