### ISSUE TITLE
Incompatible with CJK Input Method

### ISSUE THREAD

**Issue by haphap** [zeit/hyper#149]
```
    <!-- Please succinctly describe your issue and steps to reproduce it. -->
```

There is no entry bar appeared for CJK Input Method
        -

```
    HyperTerm 0.4.5
    Electron 1.2.5
    darwin x64 15.5.0
```

**Comment by egoist** [comment]
I set the element `<x-screen>` `contenteditable` to `true` and it works, but some cjk words just overlap together and cursor position is not right while typing, seems it an hterm issue

![hterm](https://cloud.githubusercontent.com/assets/8784712/16949018/c4a47ca4-4dea-11e6-8df5-2a06abbd4bb5.gif)

**Comment by lovemyliwu** [comment]
yes, I also met this issue.

can't input any CJK char!

please fix it.

**Comment by outsideris** [comment]
As I was digging this problem, it seems like [hterm](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm)'s problem. I couldn't find any solution for that. Anybody has some idea or hint to address it?

**Comment by geekdada** [comment]
https://github.com/sourcelair/xterm.js supports CJK character.

Maybe this project can help https://tsl0922.github.io/ttyd/

**Comment by chabou** [comment]
Please try our v2 🎉
