### ISSUE TITLE
Colored text flashes on hover/blur of term window

### ISSUE THREAD

**Issue by mykytanikitenko** [zeit/hyper#1490]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
![hyper text color artefacts](https://cloud.githubusercontent.com/assets/21988176/22731059/0224efa8-edf2-11e6-9d3e-2c1269132957.gif)

- **OS version and name**: Win10 64 
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: I haven't changed it
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Gif attached

**Comment by srimajji** [comment]
@CodeTheory I noticed this in v1.1.0 as well however i haven't run into this issue in v1.2.0 (compiled from master)

**Comment by ppot** [comment]
inTEresting.

**Comment by r4dian** [comment]
Reproduced in 1.2.0 downloaded from hyper.is
(Win 10, 64 bit, default config)

**Comment by chabou** [comment]
Disabling transition on close tab icon, fix this.
`transition: opacity .2s ease, color .2s ease, -ms-transform .25s ease, -webkit-transform .25s ease, transform .25s ease, background-color .1s ease;`
Strange side effect

**Comment by chabou** [comment]
It is not a Windows bug: reproduced on Mac OSX
