### ISSUE TITLE
Floating mode

### ISSUE THREAD

**Issue by patrick91** [zeit/hyper#1491]
Hi 👋🏾

I was wondering if we could have floating mode, similar to what [Helium](https://github.com/JadenGeller/Helium) does.

This is probably only OS X related, but I;d like to summon hyper from anywhere, even from fullscreen apps, without jumping to any other spaces, I just'd like to have hyper showing in the exact space I'm in. 

Helium has also support to [floating over spaces](https://github.com/JadenGeller/Helium/pull/108).
I know this is based on electron, so I'm not sure if it can be implemented directly.

**Comment by CodeTheory** [comment]
Hi there!
This can definitely be implemented as a plugin. One exists here: https://www.npmjs.com/package/hyperterm-overlay

**Comment by patrick91** [comment]
@CodeTheory thanks! Unfortunately this doesn't work as expected, when I'm using a fullscreen app I get to another space when opening hyper via the shortcut. I'll have a look at the code and see if we can fix this :)

**Comment by ChadTaljaardt** [comment]
Any update on this?

**Comment by patrick91** [comment]
@ChadTaljaardt hey! not really I tried to hack a bit with Electron but I haven't managed to create a proper floating window, I'm sure I'm doing something wrong with the OSX flags, but I didn't have too much time to test.

**Comment by ChadTaljaardt** [comment]
I can see if i can figure anything out after i reinstall my laptop :)

**Comment by patrick91** [comment]
Don't know if will help, but I was doing some tests here: https://github.com/electron/electron/blob/master/atom/browser/native_window_mac.mm#L680

but I haven't managed to get the right flags/settings :)

**Comment by zacharyrs** [comment]
Just curious whether anyone figured this out?
