### ISSUE TITLE
Advocacy on Alternative.to

### ISSUE THREAD

**Issue by dandv** [zeit/hyper#1495]
Hyper has had zero reviews on Alternative.to, a site many use often to look for alternatives to software they've been using but have grown frustrated with.

http://alternativeto.net/software/hyperterm/reviews/ can use some help :)

**Comment by CodeTheory** [comment]
Thanks for the issue, but I don't think this is an issue directly related to fixing or improving Hyper.

**Comment by dandv** [comment]
I was just trying to help Hyper be more discoverable.
