### ISSUE TITLE
Zoom problem

### ISSUE THREAD

**Issue by zhaoyao91** [zeit/hyper#1496]
I have split one tab into 4 views.
If I press `ctrl +`, the selected view will be zoomed in.
But if I press `ctrl -`, all 4 views will zoomed out.

**Comment by ppot** [comment]
Why would you want to zoom in and out? What OS? 

Can you fill the required information?

**Comment by zhaoyao91** [comment]
windows 10 64 bit
1.1.0(latest release)

I just see that hyper offers this function so have a try.

**Comment by ppot** [comment]
Can you make a gif?

**Comment by ppot** [comment]
I would need to see this.

**Comment by hyperparsa** [comment]
Im experiencing this too, I made a vid: https://drive.google.com/file/d/0BzDvdTnpkF38RkNjM0ZTWlhLN3M/view?usp=drivesdk

**Comment by standarddeviant** [comment]
I'm also experiencing this behavior. Win10 64 bit, hyper version 1.4.3 (stable).

**Comment by Axle7XStriker** [comment]
I would like to take up this issue. Since I am new to this project can you tell me the workflow of the project.

**Comment by sergiorojasa** [comment]
I would like to work on this issue.

**Comment by QZSAMA** [comment]
After I check the realease stable version (1.4.8) and also the resource code on windows 10 64 bit platform, the issue is already fixed. But the this issue post haven't been closed.
