### ISSUE TITLE
When URL entered into prompt, website opens in terminal

### ISSUE THREAD

**Issue by Merlin04** [zeit/hyper#1498]
- [checkmark] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [checkmark] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.10
- **Hyper.app version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Merlin04/19001e6f21e80a6141ff5965f5997d6c
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: total init time 288.81499999999994
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When you type in a url and press enter, the website replaces the terminal. Pressing ctrl-c exits it.

**Comment by albinekb** [comment]
This is a built in feature of hyper

**Comment by timneutkens** [comment]
It's an intended feature. Please watch the video on https://hyper.is/
