### ISSUE TITLE
paste multiplies after after refresh

### ISSUE THREAD

**Issue by chrisdrackett** [zeit/hyper#1504]
- **OS version and name**: 10.12.3
- **Hyper.app version**: 1.1.0

## Issue

If I refresh hyper and then try and paste the clipboard will come through twice. If I refresh again it'll come through 3 times, etc.

**Comment by chrisdrackett** [comment]
sorry, I think this is an issue with `hyper-paste`

**Comment by delcore92** [comment]
I'm experiencing the same issue. 
https://github.com/krzkaczor/hyperterm-paste/issues/6
