### ISSUE TITLE
Messed around in preferences and accidentally typed something in. 

### ISSUE THREAD

**Issue by Turboxide** [zeit/hyper#1505]
I was trying to install the hyperpower plugin, and then I went to Edit -> Preferences and then I typed in something on accident and saved it without realizing I did. As a result I'm getting an error, which hasn't been fixed by uninstalling and reinstalling hyper.

Here's the error message I recieve: http://prntscr.com/e8gocc

Does anyone know what I can do to fix this, I wasn't able to find any other place to find help, so I tried this. I apologize if I've made any mistakes, I'm new to git/GitHub.
-
---------------------------------------------------------------------------------
UPDATE: Ignore that, I found the javascript file I accidentally typed into. 
---------------------------------------------------------------------------------

Hyper 1.1.0
Electron 1.4.7
win32 x64 10.0.14393

**Comment by albinekb** [comment]
Hello @Turboxide, good that you found that! 🎉 
I would suggest you to join the great zeit communtiy on slack: [![Slack Channel](https://zeit-slackin.now.sh/badge.svg)](https://zeit.chat/)
We have a channel called #hyper where you can ask questions/get help

🍌
