### ISSUE TITLE
Timestamps?

### ISSUE THREAD

**Issue by kuoppa** [zeit/hyper#1507]
Is there a way to enable timestamp on when commands are fired? I would like to know when I do my commands during a day.

**Comment by chabou** [comment]
It is a shell feature not a terminal feature.
I recommend you to search how to achieve this with bash or zsh prompt/history

**Comment by kuoppa** [comment]
Thanks

**Comment by xjunior** [comment]
@chabou I thik that @kuoppa is looking for something similar to iTerm's Timestamps (cmmd+shift+e), as described in their official page. This is how it looks like:

![image](https://user-images.githubusercontent.com/8156/90022771-4d13e080-dc89-11ea-98f6-ec21819b8163.png)

This is shell agnostic

**Comment by xjunior** [comment]
What's nice about having this on the terminal instead of on `$PROMPT` is that it can be toggled-on/off. On my mac I usually keep it off until I need it for any particular reason.

**Comment by rndbblnn** [comment]
+1 for this
