### ISSUE TITLE
Vibrancy not working

### ISSUE THREAD

**Issue by BerniWittmann** [zeit/hyper#1508]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.3 
- **Hyper.app version**: Version 1.1.0 (1.1.0.1408)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/BerniWittmann/0dfd00a2cb1d69fbfa48d2e31102cb97
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: No only with hyper-simple-vibrancy plguin

## Issue
Hey, somehow my vibrancy stopped working.. I tried a clean install with the newest Hyper.app and only installed the [hyper-simple-vibrancy](https://github.com/matheuss/hyper-simple-vibrancy) plugin. But still the vibrancy is broken: See Screenshot below

Really hope you can help me 😃 

<img width="1268" alt="screenshot hyper" src="https://cloud.githubusercontent.com/assets/17594215/22954228/85373234-f315-11e6-999d-0b71f900a398.png">

**Comment by BerniWittmann** [comment]
Oh God, I feel kind of dumb right now..

I somehow had 'reduce transparency' enabled in my settings 

*eats hat*

**Comment by lucasbento** [comment]
@BerniWittmann hey, I believe you would be glad to know that this just solved the problem I have been trying to fix for about 3 hours in a totally different project, thank you so much for this.

More than 3 years later and I'm the one feeling dumb.
