### ISSUE TITLE
1.2.x breaks interactive keyboard navigation in git bash on Windows

### ISSUE THREAD

**Issue by duanemck** [zeit/hyper#1514]
Windows 7
Using git bash as the terminal
When I open VI, it does not render correctly and I am not able to navigate (the cursor does not move at all)
If I do a git log or pipe something to less, I am not able to scroll the list

---
Hyper 1.2.1
Electron 1.4.7
win32 x64 6.1.7601

**Comment by Padelas649** [comment]
Same issue here (Windows 7 & git bash), VI responds E388: Couldn't find definition

**Comment by philemn** [comment]
Same issue here as well (Windows 7 & git bash), E388: Couldn't find definition in vi

**Comment by jmcmellen** [comment]
I was having this problem as well until I set the environment var TERM=msys. I think it was set to cygwin which worked in 1.1.0. Maybe that will help you?

**Comment by philemn** [comment]
@jmcmellen That does appear to be the issue.  I'm not sure where the TERM environment variable is being set though.  It appears to be set to `xterm-256color` upon starting the hyper process.  If I manually change it after start, I am then able to scroll.

**Comment by Padelas649** [comment]
@jmcmellen I have tested it on win 7, not working. The issue occurs when I edit a remote file through ssh, with local files vi works great.

**Comment by duanemck** [comment]
Setting TERM to msys was a a mixed bag for me. Less and git log worked nicely but  VI didn't even render properly.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
