### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by EBazarov** [zeit/hyper#1517]
Thanks for **Hyper terminal** !

My favorite terminal app ❤️  

- **OS version and name**: macO Sierra 10.12.2
- **Hyper.app version**: 1.2.1 (1.2.1.1528)

## Issue

I had a trouble with `~` and `|` character, on my french keyboard and I found why.

So, I like to use _tmux_ and for more comfortable switching between panels I have putted in config file of **hyper** this line :

```
modifierKeys: { cmdIsMeta: false, altIsMeta: true }
```

After this change I have noticed that, shortcuts alt+n for `~` and alt+shift+L for `|` doesn't work. Looks like setting `altIsMeta: true` somehow affect this.

Cheers

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
