### ISSUE TITLE
Open new window with a config file

### ISSUE THREAD

**Issue by ohardy** [zeit/hyper#1518]
Now, I am working on a few projects which have a tmuxp config file.
Each config opens a few tab/panes and execute some commands like running MongoDB server, test units, web server, etc.

It would be really cool if I could just do :
```
hyper -c ./.hyper.js
```
so I can switch from iTerm2/tmux to Hyper

**Comment by schmic** [comment]
@ohardy Wouldn't it be better/easier to be able to configure multiple shells and define one while starting?

**Comment by ohardy** [comment]
@schmic I work with many teams so I need the project config file to be in git repository for each project, so each worker just have to load the config and everything just works

**Comment by ohardy** [comment]
Found a solution with hyperlayout plugin : https://github.com/timolins/hyperlayout :)
