### ISSUE TITLE
Accidental open of websites

### ISSUE THREAD

**Issue by Anzumana** [zeit/hyper#1520]
Hey,
when i accidentally opened a website inside hyper.
Is there a way that i can go back to the previous screen?
I usually close the tab and reopen it and attach to tmux again.
This seems a bit weird to me though.

**Comment by albinekb** [comment]
try pressing `ctrl+c` when in a browser-tab, it should close it. @Anzumana

**Comment by Anzumana** [comment]
yep that fixed it thanks :)
