### ISSUE TITLE
Unicode Input with Telex or Cangjie

### ISSUE THREAD

**Issue by txt8888** [zeit/hyper#1522]
- [ ] I am on the [1.2.1 (1.2.1.1528)](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [Unicode Telex / Cangjie Input Methods](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra version 10.12.3
- **Hyper.app version**: 1.2.1 (1.2.1.1528)

## Issue
I am unable to type Vietnamese or Chinese characters in Hyper.

In MacOS, when I switched Input method to Telex (Vietnamese), or Cangjie (Chinese), the keyboard input behaved very very odd.  Most if not all the intended characters will not show.

For Cangjie, the IME suppose to popup a small windows to allow me to select the Chinese character, but that small window popped up on the upper corner of the Hyper term and immediately disappear.

I can however view files that contain Chinese or Vietnamese character.  Though the Chinese characters are very close to each other with a bit overlapping.

**Comment by lucasqueiroz** [comment]
For the last part of this issue, it is related to the unicode problem ( #1857 #1769 [...] There are a lot of issues with this...)
I hope someone fixes unicode problems soon

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
