### ISSUE TITLE
E349: No identifier under cursor

### ISSUE THREAD

**Issue by mikeumus** [zeit/hyper#1524]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7 Professional
- **Hyper.app version**: 1.2.1, 1.3.0, 1.3.1
- **Plugins**: none
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mikeumus/be010c495302c4caad5b9ff019be4794

## Issue

In Windows 7 Professional, when I `vim .hyper.js` and try to arrow around the document I, the arrow/cursor is unresponsive (doesn't change position) and a pink error at the bottom of VIM shows this message:

```
E349: No identifier under cursor
```

![vim-error-hyper-js](https://cloud.githubusercontent.com/assets/57934/23026631/dce2348c-f42f-11e6-86c0-489b4f5d481a.png)

**Comment by mikeumus** [comment]
Vim still doesn't work on Windows 7 Professional in version 1.3.0

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
