### ISSUE TITLE
More portable control key awarness (windows and linux)

### ISSUE THREAD

**Issue by KalenAnson** [zeit/hyper#1525]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Windows 10: 
- 1.2.1: 
- Vanilla: 
- *N/A: 
- Is Vanilla: 

# Issue

First - I love Hyper and am using it mainly on Windows where I need to crowbar Windows to run bash. The terminal emulator UI is awesome.

## The Question
Why does the hyper app use `control` keys to do anything at all? I am not aware of another terminal emulator that does anything but pass `control` key codes straight to the shell unless they are paired with another key such as `shift` or `alt`.

I know that the `control` key is used heavily on Windows applications as the shortcut dejour, but hyper is a __terminal emulator__ and these kinds of applications inherently need a different type of `control` key usage.

### Consider:
When running a bash shell in hyper on a Windows machine:

1. Running `tmux` with standard alt binding of `ctrl - a` as the `tmux` leader does not work. Hyper eats `ctrl - a` and instead helpfully selects all the text in the current pane.
2. Using simple bash shortcuts such as `ctrl-p` to get last command (up arrow replacement) and then `ctrl - n` to get the next command in history (down arrow replacement) is awkward. Hyper eats `crtl - n` and creates a new window.
3. Bash job control. </3 My heart breaks even now, hyper eats `ctrl - z`.
4. Don't even try to run `vim` as any combo of `ctrl` and one of the following `n,t,e,o,w,z,x,v,k,r,m` will disappear into hyper and do magical things.

### Suggestion:
Can we configure hyper to ignore `control` keys all together? There are so many problems with running a `sh` shell (bash, zsh, etc) and having the terminal emulator eat your control keys. (I am aware that this is mainly a problem with the Windows flavor of hyper).

Personally I would be fine with just having the option to disable the hyper control keys, but a case could be made for remapping them to something else so as not to lose features.

I think this issue touches on a lot of others around here as well (copy/paste for example which has just recently been improved).

## Edited
I updated the issue name and added the section below to help clarify what seems to be the issue.

## Related Issues
#1200 (Control characters not working!)
#1120 (1.0.0 release broke some keybindings) Uncertain
#1047 (Text Navigation with control keys)
#833 (Most common readline keybinding don't work (ctrl-a, ctrl-e, ctrl-w etc.) )
#422 (unable to page scroll using alt using tmux) Possibly related
#233 (Tmux bind `)

**Comment by hf** [comment]
I completely agree and has made working with Hyper impossible for me at this time.

**Comment by niedzielski** [comment]
This is also a problem on Linux. For example, if I want to type ctrl-r to perform a reverse history look up or if I have my .inputrc configured to for ctrl-left / right (see also #1047), among other bindings, these are all intercepted.

**Comment by LukeFlynn** [comment]
I also am using Bash on Ubuntu for Windows. Over the years, working in a *nix environment, I've become very familiar with control-a to jump to the beginning of a line, etc. This works fine in the actual wrapper around bash.exe, but not in hyper.

**Comment by elchinot7** [comment]
I been used `CTRL-a` as prefix for tmux, however in a Hyper terminal `CTRL-a` selects all text. This simple issue is stopping me from use Hyper as my every-day terminal app.

**Comment by dawnerd** [comment]
Keep running into this after switching between my mac and linux desktop.

**Comment by webframp** [comment]
Hyper works great on macOS for me, but this is also keeping me from switching to it as my default on Windows 10

**Comment by samrocksc** [comment]
I use Ctrl-a for tmux as well.  It's a pretty popular configuration for screen/tmux/monad users.

**Comment by adambair** [comment]
Bash on Windows; recently switched from OSX to Windows. I use tmux, vim, and multitude of other console apps. Tried out hyper, worked great on OSX but on Windows it's impossible to do actual work because it swallows the CTRL key. 

:facepalm:

**Comment by Kerwood** [comment]
Sooooo... No solution to this ?

**Comment by ppot** [comment]
@Kerwood You can try latest master I included keymaps

**Comment by ppot** [comment]
close in #1876
