### ISSUE TITLE
Text gets 

### ISSUE THREAD

**Issue by Tresky** [zeit/hyper#1528]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- OSX Sierra
- Hyper.app v1.2.1
- My hyper.js is still default
- N/A
- Vanilla

## Issue
From time-to-time, Hyper will essentially take a "snapshot" of some text in my terminal and burn it into the background of the terminal. It is worth noting that it seems to be almost random. Sometimes it happens, other times it doesn't. Likewise, after it happens, it seems to go away after a few minutes of remaining in use.

Please see this [Imgur Album](http://imgur.com/a/rCuVy) for a few screenshots of the issue in action.

I can also point out, as the album demonstrates, the issue becomes _more_ prominent as the background transparency gets closer to zero. Likewise, the issue becomes _less_ prominent as the background transparency gets closer to one.

**Comment by byronpolley** [comment]
+1

**Comment by chabou** [comment]
Thanks for the report 🙏 . 
We're tracking this work over here: #2719

**Comment by Tresky** [comment]
@chabou Thanks for the redirection. :+1:
