### ISSUE TITLE
Weird behaviour when opening config on Windows

### ISSUE THREAD

**Issue by Stanzilla** [zeit/hyper#1529]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Stanzilla/e776f86ed2b919fdfd7a2fc3d9d6de49
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

![hyper_2017-02-16_19-10-00](https://cloud.githubusercontent.com/assets/75278/23034363/def87c58-f47b-11e6-9f88-532fc6253bef.png)

When opening the config, a new tab is opened and gets a lot of echos, is this the correct behaviour? From the text it is looking like it's failing a few times but notepad is actually opened.

Should opening the config even spawn a new tab at all?

**Comment by stefanivic** [comment]
@Stanzilla you are opening the config using the Bash, that's why it only echoes the text as `start notepad` is not a valid bash command. Your best option is to manually go to `c:\\Users\\yourUser\\.hyper.js` and edit it.

**Comment by jonathandelgado** [comment]
Looks like #1510 reverted the previous windows fix for this.

**Comment by stefanivic** [comment]
@jonathandelgado it wasn't really a fix, it just opened the directory instead of directly opening the editor. I am trying to find a better fix as we speak.

**Comment by Stanzilla** [comment]
@stefanivic it does that with cmd as well
![hyper_2017-02-20_00-47-17](https://cloud.githubusercontent.com/assets/75278/23107986/3e47521a-f706-11e6-9f6e-dd95def964c6.png)

**Comment by Stanzilla** [comment]
Can the process of trying to open it be done in background though? Also the echo, currently looks like a debug print left there by accident, if you ask me :D

**Comment by stefanivic** [comment]
@Stanzilla We got this merged : https://github.com/zeit/hyper/commit/36f96abb1d28ba85ebe678df2e87268b66aaf018 So now, it will check which shell you are runing and open with coresponding option. The `echo` is there just to notify you what is going on, but i will look into it, how we can make it nicer...

**Comment by MartyGentillon** [comment]
Related: https://github.com/zeit/hyper/issues/901

**Comment by MartyGentillon** [comment]
Of course, that doesn't work with powershell, which has a different syntax for environment variables ($Env:variableName).  

Also, notepad?? it can't make sense of Unix style line endings, which is the default for the preferences file.  It might make sense to look that up from the configuration (or environment)

**Comment by albinekb** [comment]
@MartyGentillon the line-ending issue was fixed with https://github.com/zeit/hyper/pull/1713

**Comment by Stanzilla** [comment]
My main gripe with this was the echo anyway, so if we could make the settings open without any echo or new tab spawning, that would be great

**Comment by albinekb** [comment]
Yes I think that would be better, use something like https://github.com/sindresorhus/opn ?

**Comment by stefanivic** [comment]
I don't think we really need any addition library to solve this, you can remove the echo frome the code and still have it working. But to be honest i think the best option would be to replace the echo and have a notification pop up.

**Comment by chabou** [comment]
I think opn is a good solution. With this, editing config directly uses an OS feature and do not depend on a shell/term feature.

**Comment by MartyGentillon** [comment]
@albinekb The line endings are only one of very many reasons to dislike the choice of notepad when other editors are available.  Roughly speaking, the editor should be controllable either though the editor environment variable or configuration.

As for using a library rather than the shell, vastly simplifies the logic and error proofs the solution.  Suddenly there is no need for a "which shell are you running" guessing game to decide how to include the environment variable.

**Comment by MartyGentillon** [comment]
Alternately, Gordon's solution is interesting:

https://github.com/zeit/hyper/pull/1736

**Comment by chabou** [comment]
Another reason to launch editor with node/lib: #417

**Comment by MartyGentillon** [comment]
One other advantage of the library approach: it works even when you have sshed into another machine.

**Comment by Stanzilla** [comment]
Is this even remotely correct? https://github.com/Stanzilla/hyper/commit/f2d8b4b3e2f53664e83ed3d5423e647f4f8026d0

(first timer here)

**Comment by chabou** [comment]
Ok guys, I found a solution: https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenitemfullpath

We don't need a lib, Electron will do it for us :)
Thank you @Stanzilla for your PR, it helps me to think about it.

**Comment by chabou** [comment]
Another reason to launch native editor: https://zeit-community.slack.com/archives/C1TMVKPFH/p1493735061557196
Some people doesn't know how to save.

**Comment by MartyGentillon** [comment]
Not to mention that not all systems come with nano....
