### ISSUE TITLE
Clarify in config that new values are added over time

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#1531]
At the top, perhaps. And to refer to https://hyper.is for the most up-to-date info

**Comment by schmic** [comment]
@rauchg Will/Are those changes be automatically be merged into an existing configuration?

**Comment by rauchg** [comment]
We can't do that easily, so I don't think so. Unless we venture into extending the config, adding comments and then run it through `prettier` for styling…

**Comment by rauchg** [comment]
To clarify, it's pretty doable, but would add substantial complexity to the codebase. I think we might be better off just saying "To see all available config flags, please refer to https://hyper.is" at the top of the file
