### ISSUE TITLE
Error with plugins in Windows?

### ISSUE THREAD

**Issue by craigb** [zeit/hyper#1534]
I run Hyper.js and I get the following notification:

![image](https://cloud.githubusercontent.com/assets/59184/23044090/8feada84-f453-11e6-93e8-54914717fda5.png)

I try to look for said file and it doesn't exist.
```
 Directory of ~\.hyper_plugins

02/16/2017  12:56 PM    <DIR>          .
02/16/2017  12:56 PM    <DIR>          ..
02/16/2017  12:56 PM    <DIR>          local
02/16/2017  02:23 PM               231 package.json
               1 File(s)            231 bytes
```

I'm assuming this is a windows-specific error since the path in the notification uses '/' instead of '\'.

Hyper 1.2.1
Electron 1.4.7
win32 x64 10.0.14393

**Comment by craigb** [comment]
Dupe: https://github.com/zeit/hyper/issues/1395

**Comment by gluons** [comment]
It happened to me too. I just clean uninstall Hyper for installing latest 1.2.1.
Fresh install Hyper 1.2.1 got this error.
