### ISSUE TITLE
Bunch of Chinese characters together.

### ISSUE THREAD

**Issue by xiamu14** [zeit/hyper#1535]
- [x] I am on the latest Hyper.app version

- [x]  I have searched the issues of this repo and believe that this is not a duplicate

- window 10
- window powershell
- Hyper.app v1.2.1

**Issue**
[screenshot](http://static.ohf2e.com/issue.JPG)
Just look this, bunch of Chinese characters together

**Comment by xiamu14** [comment]
添加选项

**Comment by rauchg** [comment]
We are working on improving support for international characters and emoji!

**Comment by xiamu14** [comment]
I will always wait until the software better.

**Comment by HereChen** [comment]
My terminal is really in mess. 0_0

![tim 20170421104817](https://cloud.githubusercontent.com/assets/6745477/25260679/7d30a9a0-2680-11e7-822a-32875cd33b16.png)

**Comment by MartyGentillon** [comment]
I noticed the issue HereChen is referring to where the terminal decides to wrap around the edge after certain characters are displayed (It does it for me after logging this very repository).  Reminds me a little of an old tube tv set with the horizontal alignment off. 

I am pretty sure that it is in the underlying hterm library.

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
