### ISSUE TITLE
Long listings trap cursor below frame, pausing listing, and paging

### ISSUE THREAD

**Issue by inestyne** [zeit/hyper#1538]
Windows 10 + Vanilla hyper 1.2.1

On initial download and load first command i ran 'dir /s' and the listing paused after several pages and required me to start hitting keys. Cursor and prompt where there after trapped below the bottom of the frame requiring restart. This behaviour is consistent on cmd.exe and ssh bash sessions. Anything that displays a long listing results in this same state.

Terminal is beautiful and buttery smooth, pinning this to my task bar in hopes you guys both understand whats happening and fix it. 

:)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
