### ISSUE TITLE
Plugin Install not working in Windows Version 1.2.1

### ISSUE THREAD

**Issue by martinwolf** [zeit/hyper#1539]
Hey,

installing plugins isn't working in Version 1.2.1 on Windows 10.
It works fine in Version  1.1.0 but it gets automatically updated to 1.2.1.
It's a fresh install, I only added `'hyperterm-atom-dark'` to the plugins.

Any ideas?

Cheers!

Hyper 1.2.1
Electron 1.4.7
win32 x64 10.0.14393

**Comment by henrikdahl** [comment]
Most likely a dupe: #1513 

Try specifying a shell in your config, if it's the same issue then that should work as a temporary fix ✌️

**Comment by martinwolf** [comment]
I tried `shell: 'C:\\Windows\\System32\\cmd.exe',` as well as `shell: 'C:\\Windows\\System32\\bash.exe'`. Both work, but plugins don't get installed.

**Comment by henrikdahl** [comment]
Try building hyper from master and see if its fixed

**Comment by martinwolf** [comment]
Oh well, I was too fast, it actually works with the `cmd.exe`. Sorry.

**Comment by henrikdahl** [comment]
Maybe close this since it's a dupe?
