### ISSUE TITLE
No UI to scroll the terminal

### ISSUE THREAD

**Issue by tomkiss** [zeit/hyper#1540]
Hello,

There have been [similar issues](https://github.com/zeit/hyper/issues/565) previously but I cannot find this same issue.

On MacOS Sierra 10.12.3 and Hyper 1.2.1 - when the System Preference is set to "_Show Scrollbars: Always_", this preference is not respected in Hyper and there are no scrollbars displayed.

Hence, when using a Wacom tablet, there are no scrollbars available at all. 

Additionally in this scenario, as there appears to be no Page Up/Page Down key support, I can't find a way to scroll the terminal at all; short of plugging a mouse in.

Bit of an accessibility issue. Apologies if there is something/or a setting I've missed. 

Very much enjoying using Hyper apart from this :)

**Comment by henrikdahl** [comment]
It's because it's relying on hterm that basically fakes the scrollbar. I'm fairly sure this would require a lot of work.

**Comment by baptistebriel** [comment]
Having issues clicking on the scrollbar to just jump on a spot in the window, or just drag it.

**Comment by jamtur01** [comment]
Actually I am not sure #1497 is the fix. I see the same problem on 1.2.1 on 10.12.3 on a MBP. It's not limited to a tablet.

**Comment by tomkiss** [comment]
@baptistebriel Not sure if you mean you are having issues or if you're implying I should do what you're suggesting. But to confirm, there is no scrollbar when a cursor hovers over hyper terminal, only when the mouse wheel is scrolled. When there is a scrollbar, it's non-interactive (because, as mentioned above, it's a "fake" scrollbar).

**Comment by henrikdahl** [comment]
@tomkiss Implementing so that it shows on hover is fairly easy but it might have performance concerns, cc @rauchg 

Being able to drag and scroll it sounds like a lot of work considering how it's done.

**Comment by MartyGentillon** [comment]
Scrolling with the keyboard works with shift + page-up/page-down/home/end

**Comment by hpcnpatel** [comment]
On MacOS Terminal, unselect the Secure Keyboard Entry fro the menu. Scrolling in Terminal should work then. Happened to me.

**Comment by jamtur01** [comment]
Can confirm this seems to be working in 2.0.0 Canary 8.

**Comment by ankitshah009** [comment]
Confirmed seems to be working in 2.0.0.Canary 11. 
However, within screen session on a remote server, the scrolling doesn't seem to work. Any method to enable the functionality.

**Comment by timothyis** [comment]
I'm not sure about the last issue mentioned with screen session on a remote server, but this issue seems to be resolved. Thanks for the contribution, everyone 👍
