### ISSUE TITLE
Right paste not working on macOS and Linux

### ISSUE THREAD

**Issue by possebon** [zeit/hyper#1548]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.3 and Linux Mint 18.1
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/possebon/698852f6fe2d4a716f8f59c2844fd146

- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
![image](https://cloud.githubusercontent.com/assets/257745/23087805/45a10d70-f55e-11e6-82ef-a1afaea46d73.png)

- **The issue is reproducible in vanilla Hyper.app**: I disabled all plugins and the issue still occurs.

## Issue
When I try to use the right click of mouse, the content of clipboard is not pasted. I confirmed that the content is on clipboard with the CMD+V on macOS or CTRL + V on Linux.

**Comment by Specro** [comment]
You have to add `quickEdit: true` to your config 😄

**Comment by possebon** [comment]
@Specro I added the quickEdit: true and does not work, at least on macOS. I can't make tests on Linux now.

**Comment by possebon** [comment]
@Specro I confirm that the `quickEdit: true` does not work on Linux too.

This parameter is not on documentation, right?

**Comment by allruiz** [comment]
I can confirm too, it's not working for me.

**Comment by R3J3CT3D** [comment]
Captain here !

You need to add `copyOnSelect:false` and `quickEdit: true`

**Comment by albinekb** [comment]
@possebon @allruiz , did you get it working after following the instructions above?

**Comment by possebon** [comment]
@albinekb Yes, it's working. Thanks.

**Comment by allruiz** [comment]
@albinekb It works. Thank you.

**Comment by albinekb** [comment]
Nice 👌 Closing
