### ISSUE TITLE
Vim colors

### ISSUE THREAD

**Issue by delvedor** [zeit/hyper#155]
Hi!
I love the idea of this terminal, it has great potential! :)

I'm using the 0.4.5 version, and when I open vim I get this:
![screen shot 2016-07-16 at 10 00 24 am](https://cloud.githubusercontent.com/assets/4865608/16893566/7a37823e-4b3c-11e6-98ad-88597e7ccac7.png)

Have you got any idea?
This is my [.vimrc](https://github.com/delvedor/dotfiles/blob/master/.vimrc).

**Comment by martinwolf** [comment]
Mine does look similarly awful. Would also be interested in any ideas.
Other than that I like the idea of this terminal, too.

**Comment by delvedor** [comment]
I guess the problem is the *colorscheme*.
I'm using solarized-dark and if I disable it I get the (I guess) correct hyperterm color scheme.

**Comment by nkzawa** [comment]
Try the following settings if you use solarized-dark. It fixed the issue for me.

https://gist.github.com/nkzawa/970f75de0f9f8b05524d99452dfabd54

**Comment by delvedor** [comment]
It works!
Vim has still some not color related issues, but thank you.

@nkzawa can I use your code to make a hyperterm plugin? :)

**Comment by nkzawa** [comment]
@delvedor awesome! no problem to use the code.

**Comment by swaincreates** [comment]
This seems to be a problem if vim uses any`colorscheme` with `background=dark`. I have the same issue using solarized dark as well as with colorscheme one from https://github.com/rakr/vim-one. The above fix doesn't seem like a true fix for this issue. 

You might expect using the `hyperterm-solarized-dark` package would make it work well, but it doesn't.

**Comment by zmb3** [comment]
Should this be reopened?  Vim colors are definitely not behaving correctly.  This is one of the only blockers keeping me from switching to hyper.

**Comment by swaincreates** [comment]
Yea I agree, I checked back a few months after my last comment to check and see if this was fixed. Maybe reopen issue, @delvedor ?

**Comment by TooTallNate** [comment]
I have this issue as well. Reopening.

**Comment by lerouxb** [comment]
I'm using a dark colorscheme in hyper and hemisu in vim. It was also totally unusable in hyper just like the comments above. I got around it by keeping `background=dark` in .vimrc and setting `colorscheme default`, then in .gvimrc I override it to `colorschem hemisu`. Now it at least works fine in the terminal and things are unchanged in MacVim.

I do most of my coding in MacVim, so I just need vim in the terminal to at least work, so this works pretty well for me.

**Comment by rainerborene** [comment]
Same here.

**Comment by patricklewis** [comment]
I'm experiencing the same issue with incorrect colors in Vim/Neovim using base16 color schemes for:

Hyper - https://github.com/winneon/hypersixteen
Vim - https://github.com/chriskempson/base16-vim

**Comment by martinwolf** [comment]
Any progress here? I'm using the nova hyperterm theme as well as vim with the nova color scheme and get a weird grey background.

https://trevordmiller.com/projects/nova

**Comment by martinwolf** [comment]
`set notermguicolors` in my `.vimrc` worked for me. It fixed the weird vim background.

**Comment by HustLion** [comment]
@martinwolf tried your method, but no luck. Still weird...

![image](https://cloud.githubusercontent.com/assets/12825646/23553758/258a118a-005d-11e7-8b1a-078f62b9138d.png)

**Comment by oscarmorrison** [comment]
+1

**Comment by dvonrohr** [comment]
+1

**Comment by hamidraza** [comment]
+1

**Comment by albinekb** [comment]
@oscarmorrison @dvonrohr @hamidraza please use the 👍  button for that **.**

**Comment by welnanick** [comment]
Is there any progress on this?

**Comment by welnanick** [comment]
Is there any progress on this?

**Comment by vnikk** [comment]
is vim completely unusable in hyper now, or are you not using colorschemes?

**Comment by welnanick** [comment]
@vnikk you just have to find a colorscheme that works. Unfortunately most themes with a dark background don't work. I do think they are working on making sure colors work correctly in 2.0

**Comment by albinekb** [comment]
Yes, please try 2.0, it's not released yet, but you can get it now to test it out. Read more at https://zeit.co/blog/canary 👍 

It *should* fix most of the problems, as we switched terminal rendering lib from legacy`hterm` to the same lib that VS Code uses, `xterm.js`, which is much more actively developed and maintained.

**Comment by xrisk** [comment]
I'm running vim 8.0 and adding `set termguicolors` to my vimrc works perfectly. Also make sure your vim isn't in vi-compatible mode.

**Comment by welnanick** [comment]
@xrisk That is the temporary work-around I have been using. It works for most color-related things in vim, but not all.

**Comment by TomazWang** [comment]
`set termguicolors` won't work for me. It makes my vim colorless. I'm using vim 8.0 and hyper 1.4.8 as well. hyper 2.0 has the same problem too.

**Comment by chabou** [comment]
@TomazWang Thank your for your feedback.
`set termguicolors` is not possible anymore because our next v2 stable release will not support truecolor due to xtermv3

I'm closing this issue in favor of https://github.com/zeit/hyper/issues/2294

**Comment by AplBoiCun** [comment]
So, still is there no solution?

**Comment by colemars** [comment]
Was there ever a solution to this?

<img width="579" alt="Screen Shot 2019-10-31 at 8 09 36 PM" src="https://user-images.githubusercontent.com/42340374/67999651-6d067600-fc1a-11e9-956c-68a1901f4504.png">
<img width="603" alt="Screen Shot 2019-10-31 at 8 09 23 PM" src="https://user-images.githubusercontent.com/42340374/67999652-6d9f0c80-fc1a-11e9-9730-7a0aab6db790.png">

**Comment by gabroo** [comment]
Hi, I'm getting some weird behavior with the border color leaking into the frame on vim 8.2 hyper 3.0.2

Setting `termguicolors` property does not change the behavior

Screenshot of vimrc (showing the issue):

<img width="1428" alt="Screen Shot 2020-06-12 at 12 18 40 AM" src="https://user-images.githubusercontent.com/6046841/84475969-4d204180-ac42-11ea-9a20-0609b88076b5.png">

**Comment by Warns** [comment]
`set background=dark` and `set termguicolors` kind of fixed it for me as it blends in with Hyper's default colors just fine.

If you're unsure if your env supports `set termguicolors` you may set it as the following:

`if (has("termguicolors"))
  et termguicolors
endif`

**Comment by Delfador42** [comment]
Here are 2 workarounds
Workaround 1:
- Install hyper-background: `$ hyper i hyper-background`
      - Docs for hyper-background: https://www.npmjs.com/package/hyper-background
- Take a screenshot of your desired background color and set your background image as that screenshot in your .hyper.js config file
Example of .hyper.js:
Note: The background image setting is inside the config object as explained in hyper-background docs
![image](https://user-images.githubusercontent.com/46577890/101120985-fc6c1e80-35bc-11eb-820c-3987b5b61e0f.png)

Workaround 2:
- In your .vimrc set your vim background to transparent:
```
"Overrides the color scheme background and makes it transparent      
 autocmd ColorScheme * highlight Normal ctermbg=None                                          
 autocmd ColorScheme * highlight NonText ctermbg=None
```
- Change the background of hyper to the desired background-color

********************************
Before: 
![image](https://user-images.githubusercontent.com/46577890/101121707-c9c32580-35be-11eb-8251-ab40c2e22ce5.png)

After:
![image](https://user-images.githubusercontent.com/46577890/101121740-dd6e8c00-35be-11eb-8c82-fdc516e4eb7e.png)
