### ISSUE TITLE
Rendering issues with webpack-dashboard

### ISSUE THREAD

**Issue by controversial** [zeit/hyper#1555]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.2
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/controversial/d08d16c4fd1c9df81e722db3913c6dcf)

## Issue

#639 describes issues with blessed, but that looks like it was an issue with rendering of braille characters, which was fixed. I'm seeing a lot of issues with rendering [`webpack-dashboard`](https://github.com/FormidableLabs/webpack-dashboard) (another [`blessed`](https://github.com/chjj/blessed) app). 

Running `webpack-dashboard -- webpack-dev-server` in Terminal.app:

<img width="682" alt="screen shot 2017-02-19 at 10 42 32 am" src="https://cloud.githubusercontent.com/assets/10377391/23103863/576d7d30-f690-11e6-8aff-5138d830f867.png">

Running the same command in Hyper:

![screen shot 2017-02-19 at 10 24 03 am](https://cloud.githubusercontent.com/assets/10377391/23103866/69bb66a0-f690-11e6-9f82-2b0f821c5dfc.png)

**Comment by controversial** [comment]
If I make the window wide enough that nothing has to wrap inside the boxes, it looks a bit better, but still not right
![screen shot 2017-02-19 at 12 23 19 pm](https://cloud.githubusercontent.com/assets/10377391/23104568/5ac062fa-f69e-11e6-952c-28e2ed830c16.png)

**Comment by mashaal** [comment]
I'm experiencing the same with the `react-blessed` dashboard demo 
![screen shot 2017-03-06 at 9 13 16 pm](https://cloud.githubusercontent.com/assets/6100364/23605671/bfa50b70-02b1-11e7-8ffe-0c808d21c214.png)

**Comment by Anahkiasen** [comment]
I think `vtop` also has this issue, the layout just disintegrates bit by bit over time

**Comment by mashaal** [comment]
It seems to be a whitespace issue -- blessed allows a custom fill character for boxes, it defaults to whitespace which does not render properly in hyper. Switching to any other character has much better results.

![screen shot 2017-03-08 at 9 22 08 am](https://cloud.githubusercontent.com/assets/6100364/23680907/031f5e7a-03e1-11e7-8a7d-dd6976ca9319.png)

**Comment by enriquecaballero** [comment]
+1

**Comment by rubencodes** [comment]
So is this a Hyper issue or a blessed issue?

**Comment by controversial** [comment]
Given that this works properly in other terminal apps, I think it's safe to call this a Hyper issue.

**Comment by Kiruchi** [comment]
For information, the same behaviour happens with `pm2` with something like `pm2 list`or `pm2 monit`.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
