### ISSUE TITLE
Background transparency not working as expected.

### ISSUE THREAD

**Issue by imaginationac** [zeit/hyper#1556]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Professional 64-bit
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/imaginationac/74f42ffa21e41c4a797beaab70b5fa76
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

After updating to 1.2.1, background transparency/alpha does not behave as expected. Was working on 1.1.0.

**Comment by henrikdahl** [comment]
Do you mean vibrancy? ✌️

**Comment by imaginationac** [comment]
@henrikdahl No.

In `.hyper.js`, when changing the the value of `background-color` to something like `rgba(0, 0, 0, 0.5)` I expect to the background to be at 50% opacity, and to be able to see through the windows to any programs or the desktop. That not longer happens for me.

**Comment by henrikdahl** [comment]
Transparency still works on macOS, I don't have Windows so someone else needs to confirm there.

**Comment by imaginarny** [comment]
I have just updated to 1.2.1 from 1.1.0 and I'm experiencing the very same problem.

**Comment by Zx-EvM** [comment]
I have the same problem. I use Windows 10 Professional x64 Version: 1607 Build: 14393.693 and Hyper 1.2.1

**Comment by mil1i** [comment]
Also experiencing this. Win 10 Pro x64: 1607, Hyper 1.2.1.

**Comment by alshdavid** [comment]
In Windows 10, also experiencing this issue

**Comment by imaginationac** [comment]
Issue still present as of 1.3.1.

**Comment by Zx-EvM** [comment]
@imaginationac you can read this comment in same issue https://github.com/zeit/hyper/issues/1638 by @cvandal it's work

**Comment by MartinMuzatko** [comment]
I'm on MacOSX.
I also have this issue. When I remove my old .hyper.js file, and let hyper create a new one, it does not work. After a few quit and reopens, and full reloads, the previous terminal persists in the background . The layers build up and then they eventually make the window look full opaque.

![image](https://cloud.githubusercontent.com/assets/2950505/25281340/5dc5e968-26ad-11e7-89c1-425b242b212e.png)

The layers are gone again, if I dump the .hyper.js file and let hyper create a new one for me.

**Comment by ed-alertedh** [comment]
Same problem with Hyper 1.3.3, Windows 10 build 15063.483

**Comment by incomingstick** [comment]
Still an issue in 1.4.8 (Windows 10 v1709 Build 16299.192)

**Comment by adammacias** [comment]
Not working here too ```Windows 10 v1709 Build 16299.248``` ... ```Hyper 1.4.8```

**Comment by niceKamrul** [comment]
Not working with windows 10

**Comment by albinekb** [comment]
It's not supported on windows.

**Comment by lucleray** [comment]
I think this can be solved using `browserWindow.setOpacity` ([electron doc](https://electronjs.org/docs/api/browser-window#winsetopacityopacity-windows-macos)).

It is compatible with Windows and MacOS. It was added in electron in this PR : https://github.com/electron/electron/pull/10667

I made a plugin for hyper using it : [hyper-opacity](https://github.com/lucleray/hyper-opacity) 🙂

**Comment by tomperys** [comment]
> I think this can be solved using `browserWindow.setOpacity` ([electron doc](https://electronjs.org/docs/api/browser-window#winsetopacityopacity-windows-macos)).
> 
> It is compatible with Windows and MacOS. It was added in electron in this PR : [electron/electron#10667](https://github.com/electron/electron/pull/10667)
> 
> I made a plugin for hyper using it : [hyper-opacity](https://github.com/lucleray/hyper-opacity) 🙂

This plugin doesn not work for me with hyper 3.0.2
