### ISSUE TITLE
getStylesheet doesn't hot reload

### ISSUE THREAD

**Issue by henrikdahl** [zeit/hyper#1557]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: `10.0.3 macOS Sierra`
- **Hyper.app version**: `1.2.1`
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: `Default`
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: `N/A`
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

https://github.com/zeit/hyper/blob/21bd2a7bf138700d310a5b9dac249ba7bc78ee39/lib/components/term.js#L228

None of getStylesheet hot reloads. So if you change borderColor, the scrollBar which initially takes its color from the borderColor won't hot reload.

**Comment by henrikdahl** [comment]
Looking further into this, getStylesheet does hot reload but only when termCSS is changed in config. Meaning when you change cursorColor it won't be updated unless you also change termCSS.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
