### ISSUE TITLE
Top-down terminal option

### ISSUE THREAD

**Issue by baptistedonaux** [zeit/hyper#1558]
Your project is really nice and I would like play with it but I miss an option to use Hyper like Guake and allows to use it like top-down terminal.

I have no idea about how integrated this into Gnome, Unity, macOS but I think that many developers have skills and would like have this feature.

**Comment by henrikdahl** [comment]
https://www.npmjs.com/package/hyperterm-overlay

**Comment by baptistedonaux** [comment]
Thanks but only for macOS.

**Comment by henrikdahl** [comment]
Should be fairly simple to PR Windows support. I think this feature should remain a plugin and not part of Hyper by default ✌️
