### ISSUE TITLE
Typing 'exit' doesn't quit Hyper

### ISSUE THREAD

**Issue by Jamesking56** [zeit/hyper#1561]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X El Capitan (10.11.6)
- **Hyper.app version**: 1.2.1 (1.2.1.1528)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Jamesking56/dfa7735174e81e6a7c68025e991da460
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Open up Hyper, type in `exit` and press enter. Hyper still exists in Dock and is still open. When last window is closed, the app should quit (like other Mac apps do)

**Comment by henrikdahl** [comment]
Which apps? Not even terminal fully quits.

**Comment by Jamesking56** [comment]
iTerm 2 does which is the closest comparison to HyperOn 20 Feb 2017 5:42 p.m., Henrik <notifications@github.com> wrote:Which apps? Not even terminal fully quits.

**Comment by ppot** [comment]
on  bash. Typing `exit` do close the session. If no sessions are open it will close the window.

**Comment by sumnermic** [comment]
@Jamesking56 other apps like the Terminal.app itself will upon `$ exit` only **close window, CMD + W**. Similar terminal apps like bash, iTerm(2) do not **Quit, CMD + Q**, but instead only 'close window'.

**Comment by matheuss** [comment]
>When last window is closed, the app should quit (like other Mac apps do) 
That's false 🤔 No app closes when the last window is closed on MacOS – it's a standard to still leave the app on the Dock when all windows are closed.

**Comment by matheuss** [comment]
The app should only quit when the user explicitly tells it to quit – with CMD+Q for example.

**Comment by cblecker** [comment]
For anyone following this:
I prefer a terminal workflow to quit when I type "exit" on the last window as well. So I went ahead and created a plugin to do it. Issues/PRs are welcome.
https://github.com/cblecker/hyper-quit

**Comment by albinekb** [comment]
Great @cblecker! Make sure to add it to the list: https://github.com/bnb/awesome-hyper ❤️
