### ISSUE TITLE
[Discussion] Yarn or npm?

### ISSUE THREAD

**Issue by gsklee** [zeit/hyper#1567]
This is kind of a follow-up to 70822a31b531d8555db65b1ef9b7e781ac958ed5. As a potential contributor, I'd like to make sure that I am picking up the right tool to help building this project; let's clarify the package manager of our choice.

The clarification can help us do some further actions to prune the repo, including:

* Removal of either `.npmrc` or `yarn.lock`
* Add more explicit info to the **Contribute** section inside the readme

**Comment by stefanivic** [comment]
@gsklee For that commit, as i said in the comment, i think it was before some release as the builds on yarn were failing, so the quickest solutions was to switch to npm. Regarding Travis builds i consider that the core team should decide what is best for them.

For contributing i think that both should be included as we have now, and that the contributors should decide what they want to use. Yarn is still fairly news and i do consider that there are a fair number of people outhere who use npm. These are just my two cents, i am open to discussion.

**Comment by chrisbujok** [comment]
I agree with @stefanivic that both should be supported in terms of contributing.

**Comment by mike-morrison** [comment]
If you are going to support both, you probably should add yarn.lock to .gitignore.  Otherwise, people using yarn could get the yarn locked dependency versions which would be different from someone just doing an npm install.

**Comment by chrisbujok** [comment]
I think it's actually not recommended to gitignore the yarn.lock file ([yarn docs](https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control))

**Comment by gsklee** [comment]
Apparently the best way is to simply pick one and ask all contributors to stick to it; since `yarn` is deterministic and `npm` is not, those who use `npm` can and will end up with different dependency trees with those using `yarn` from time to time. This will certainly become an issue when developers collaborate on a single project.

@chrisbujok `npm shrinkwrap` is not synonymous to `yarn.lock` because it cannot guarantee a deterministic resolution further up your dependency tree.

**Comment by Dolemike** [comment]
@chrisbujok Correct it is not recommended, but it would be your only option if you wanted yarn and npm to pull the same deps.  I agree with @gsklee I would pick yarn and forget about npm.  That seems to be the trend.

**Comment by matheuss** [comment]
Yarn's back 🎉 a82d8acaa7a73925c55e97bb548c307dc53b22e2 + d9fe9486729c3e00b147c6e6a46b3e96fab5c842

**Comment by matheuss** [comment]
Bonus: d521e8e162846d00d08b08f080ea8d87c04a63f4
