### ISSUE TITLE
EPERM: operation not permitted, lstat

### ISSUE THREAD

**Issue by darsain** [zeit/hyper#1568]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] Found similar error reported in #946, but I believe that this is not a duplicate
- **OS version and name**: Win 10
- **Hyper.app version**: 1.2.1-1.3.1
- **.hyper.js**: https://gist.github.com/anonymous/9a1a7aa2b8ee2708d5cf9f3803cb7794
- **Relevant information from devtools**: nothing reported in console
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Errors like these happen sporadically when I use the OS and various apps, and they change some files located under `%HOME%/*` while Hyper is running in the background:

![image](https://cloud.githubusercontent.com/assets/538801/23163947/15280b56-f835-11e6-8ef8-4dac07d0a38b.png)

![image](https://cloud.githubusercontent.com/assets/538801/24198233/4fa67592-0f05-11e7-8738-dc72e0c5b535.png)

It seems like Hyper is watching user's home folder to spy on `.hyper.js` changes, and whenever something happens there it does `lstat` on the changed file. This operation might not be permitted on some files, which results in `EPERM` error window popping up and annoying me considerably 😢.

I think that watching of anything under user's home folder should be isolated to only the paths relevant to Hyper and completely ignoring any event not relevant to it, since watching everything there might (apart of throwing these errors) cause performance issues in the future.

**Comment by darsain** [comment]
So this keeps happening sporadically not just because of Inkscape. Whenever I do some directory operations, like deleting bunch of stuff, there's a chance this error pops up when Hyper is running.

**Comment by darsain** [comment]
I've updated the opening post to maybe clarify the cause of the issue.

**Comment by elkaz** [comment]
I'm experiencing the same issue on Windows 10.

**Comment by saulmadi** [comment]
Same here :(

**Comment by jota12x** [comment]
Just happened to me :(. Any fixes on this case?

**Comment by Mohamed3on** [comment]
Facing this issue on Win10 too, seems to happen randomly.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
