### ISSUE TITLE
screen not clearing using Cygwin

### ISSUE THREAD

**Issue by agodlydeciple** [zeit/hyper#1570]
When using Cygwin as shell provider.  Whenever `clear` command is entered, the cursor moves, but nothing on screen is actually cleared and it causes an overwrite on the screen.

> Hyper 1.2.1
> Electron 1.4.7
> win32 x64 6.1.7601

**Comment by fmiras** [comment]
How did you install Cygwin on hyper?

**Comment by gsklee** [comment]
Dupe of #1559

**Comment by agodlydeciple** [comment]
@fmiras you install Cygwin normally and then you just reference the shell in the `.hyer.js` file.

you can reference the .bat file as the shell, or reference the shell directly.
```javascript
    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instad of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: 'Z:\\ConsoleZ\\cygwin64\\bin\\bash.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login', '-i'],
```

Since this is a duplicate (I did check to see if this issue had been submitted before), I will close this out and follow #1559

**Comment by fmiras** [comment]
@agodlydeciple thanks for the tip!
