### ISSUE TITLE
UI gets repeated all over the place?

### ISSUE THREAD

**Issue by polds** [zeit/hyper#1575]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.4 Beta
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/polds/b195ca548c0901425b8bc0898e86048c
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A?
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I know my `.hyper.js` says otherwise but I can reproduce this entirely on vanilla Hyper.app, sometimes when starting a new tab or interacting with it the UI gets repeated all over the place. The gif below shows me adding a plugin which encourage the issue to happen faster

![fun](https://cloud.githubusercontent.com/assets/2372558/23232649/4fc3386a-f909-11e6-9a17-ba9ebb35ae52.gif)

**Comment by gsklee** [comment]
Here's a wild guess... plugins have authored states / middleware compositions in a wrong way such that the existence of peer plugins is not considered.

Does this error happen when you only have one plugin installed at all? Does it happen when you have more than two plugins?

**Comment by polds** [comment]
Yeah I can see it with no plugins installed, one plugin, two, etc.

**Comment by polds** [comment]
Interestingly, I've just discovered as long as I have the `hyperborder` plugin installed this doesn't happen. Without that plugin it almost always happens.

**Comment by Blindmikey** [comment]
I see something similar, when I ssh into a linux machine from windows' hyper install. And nano any file, or run `top` Lots of distortion, lots of capitol `B`s and `~`s too, hard to edit files through hyper this way. File scrolling ends up displaying only half a block of text, sometimes text position is incorrect until I resize hyper or move cursor over text. 

Will see if hyperborder solves any of my issues.

**Comment by Rawnly** [comment]
I've seen the same effect when full reloading with new theme, i'll check `hyperborder` too

**Comment by matheuss** [comment]
#1602
