### ISSUE TITLE
Calling "Command + Shift + R" on macOS causes Hyper to freak out

### ISSUE THREAD

**Issue by ryan4888** [zeit/hyper#1579]
Pretty self explanatory. I found this because I use "Command + Shift + R" a lot for development, and I found that when hitting it, by accident, in Hyper made it freak out. The following is a screen cap of it's behavior during this.

![image](https://cloud.githubusercontent.com/assets/10523324/23278886/fda9fad6-f9e0-11e6-9e04-b57811526266.png)

**Comment by chabou** [comment]
Same for me : only when you have opened devtools before.
Closing/opening/closing devtools (dock mode) fixes this glitch.
Maybe an electron/devtools issue ?

**Comment by gsklee** [comment]
@chabou I can reproduce this without opening the devtools.

**Comment by landsman** [comment]
Same issue

**Comment by matheuss** [comment]
#1602
