### ISSUE TITLE
Virustotal is detecting viruses.

### ISSUE THREAD

**Issue by Andnopomc** [zeit/hyper#1580]
**I am very paranoid with my computer and was a little suspicious when virustotal came up with some "positives"** [_Results_](https://www.virustotal.com/en/file/b1fc1d464f0c5d0b67b53394cdc6db6f73a624103a9b1740463558880777f800/analysis/) I was wondering if someone could confirm if this is a true or false positive.

**Comment by henrikdahl** [comment]
https://github.com/electron/electron/issues/4485

**Comment by matheuss** [comment]
We'll be signing the `.exe` for the next release 👌 Other than that: yes, it's a false positive.

**Comment by Andnopomc** [comment]
That is what I thought. Virtualbox, Nodejs, and lots of things were coming up as a false positive. Signing will be nice if you do it next release.

**Comment by richkeenan** [comment]
I'm getting this with the latest version 1.3.2.
https://www.virustotal.com/en/file/f6fc7f361c43b2202403d75ac80abffb62e0df995311aad3b4830f4e60042294/analysis/

**Comment by I-keep-trying** [comment]
Oh OK, I'm glad it's a false positive. They are saying it's a [trojan](https://www.virustotal.com/en/file/6975a24e37fb9234e9e0467e08634b1e39c5435dc3ec0e0ad9c2bf2ea0bf3e75/analysis/) now! 

I really like hyper, and I _just_ installed it, I didn't want to un-install it.
