### ISSUE TITLE
Clicking in tmux pane makes it to go into scroll mode

### ISSUE THREAD

**Issue by ylogx** [zeit/hyper#1582]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  MacOS Sierra
- **Hyper.app version**: 1.2.1.1528
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Default
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

### Expected: 
Tmux pane stays in command mode.

### Actual:
Tmux goes into scroll mode.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
