### ISSUE TITLE
Plugins Existances

### ISSUE THREAD

**Issue by ppot** [zeit/hyper#1584]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

After working on #1509  accessibility and restructuring the plugins structure I came across this critical error. Since we keep plugins inside a config `plugins: []` , we notice the change of file state and process to `updatePlugins` if  `cache.get('hyper.plugins') !== id` and then updating the plugins.

However since we test for file change we can have `cache.get('hyper.plugins') === id`   [https://github.com/zeit/hyper/blob/master/app/plugins.js#L165](url) and not triggering `updatePlugins`.

We actually have `cache.get('hyper.plugins') !== id`. The reason is that if we remove plugins manually from `.hyper_plugins/node_modules/` we will result on not having one installed there.
Not triggering the install since the file `.hyper.js` didin’t change and  the cache also but actually:

#### Plugins directory
```
~ ❯ ls -la .hyper_plugins/node_modules
total 0
drwxr-xr-x  2 ppot  staff   68 Feb 25 18:21 .
drwxr-xr-x  5 ppot  staff  170 Feb 24 21:09 ..
~ ❯
```

If we look closely at [https://github.com/zeit/hyper/blob/master/app/plugins.js#L41-L44](url)
We `getPaths` and then `requirePlugins`.

The `getPaths` [https://github.com/zeit/hyper/blob/master/app/plugins.js#L266](url) will return a list of `Paths`.
```
{ plugins: [ 'hyper-statusline' ], localPlugins: [] }
{ plugins: [ '/Users/ppot/.hyper_plugins/node_modules/hyper-statusline' ],
  localPlugins: [] }
```
This will lead to plugins loading error 
```
[Notification] Plugin error!: Plugin "hyper-statusline" failed to load (Cannot find module '/Users/ppot/.hyper/plugins/node_modules/hyper-statusline')
{ Error: Cannot find module '/Users/ppot/.hyper/plugins/node_modules/hyper-statusline'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/ppot/DEV/Hyper/ppot/hyper/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
```

We actually can't `requirePlugins` since [https://github.com/zeit/hyper/blob/master/app/plugins.js#L292](url) will throw error.

**Comment by iamstarkov** [comment]
prob related #312

**Comment by chabou** [comment]
outdated
