### ISSUE TITLE
Powerline fonts not loading at all on Windows

### ISSUE THREAD

**Issue by flxw** [zeit/hyper#1585]
Hi all,

thanks for bringing a great terminal Emulator on to Windows! With the Linux Subsystem I am loving it - it even has gruvbox.

Unfortunately though, the vim-airline fonts (from https://github.com/powerline/fonts) do not render correctly, and the way it looks the font does not even get loaded (see the second ugly screenshot with the offset cursor when only having set <i>monospace</i> as font. Might hyper perceive the font names differently or only want to load system fonts?!

See the badly/incorrectly rendered font here:
![image](https://cloud.githubusercontent.com/assets/942398/23338385/e5239d3e-fc09-11e6-9d4b-c493f0564b7c.png)

With only the Powerline font set everything breaks:
![image](https://cloud.githubusercontent.com/assets/942398/23338395/06bb4cc6-fc0a-11e6-9a76-34f3e1bca5ab.png)

#186 Reports a similar issue, but the fixes suggested there are for unixoid Systems
and not for Windows. The fonts are installed, but at this point I am not sure where the error might arise from?

---
My System specs:
Hyper 1.2.1
Electron 1.4.7
win32 x64 10.0.14393

---

My .hyper.js: https://gist.github.com/flxw/8916660d9d730729382baa6702736310
My fontsize is set to 12.5 - changing this value does not change anything.

**Comment by thasmo** [comment]
@flxw Using e.g. [Fira Code](https://github.com/tonsky/FiraCode) works for me (Powerline Characters and Ligatures) on Windows.
`fontFamily: '"Fira Code", monospace'`

**Comment by flxw** [comment]
Thanks thasmo! That's a lovely font, but it unfortunately doesn't change anything for me.
This bug is a real showstopper for me 👎 With Fira, it looks similar to the not-loaded-font-issues above.

![image](https://cloud.githubusercontent.com/assets/942398/23382198/8a507664-fd41-11e6-9497-d2ec5dd09ae4.png)

**Comment by cdhunt** [comment]
@flxw I'm using a Powerline font as well in Windows. No issues, here.. Did you install the font(s) using the install script or some other method?

**Comment by flxw** [comment]
Hey @cdhunt, that's really great news! I installed the fonts like this:

1. Download from https://github.com/powerline/fonts
2. Extract, and click "Install" on the context-menu. I do have admin rights on my machine

![image](https://cloud.githubusercontent.com/assets/942398/23825409/a834500a-0689-11e7-9e0a-272049c8d463.png)

**Comment by DanielGGordon** [comment]
@cdhunt could you show me the values I need to put into my .hyper.js file? Kind of annoying I can't just select the font from a drop down menu or something.

**Comment by cdhunt** [comment]
@DanielGGordon Here is my config. 

https://gist.github.com/cdhunt/75b0162aa4cb1f11ce2b592e8c324bfa

I don't imagine it would make a difference, but for what it's worth, I used the install.ps1 in the zip to install all of the PowerLine fonts.

**Comment by DanielGGordon** [comment]
So I didn't install all of them - also I wanted to use some nerd font like [this one](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/complete/Fura%20Code%20Regular%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf), but I don't know what value to put in the config to point to this font.

**Comment by cdhunt** [comment]
I believe however the name is displayed in `Control Panel\Appearance and Personalization\Fonts`

**Comment by flxw** [comment]
Hey guys. I used the install script and - whatever the reason may have been in the end - it **disappeared** for me with **version 1.3.1**. Now the special characters are rendered somewhat incorrectly, but that's a duplicate of #1630, so I'd suggest to close this issue.

Here are my configurations: https://gist.github.com/flxw/424a4eb3609efcdfe4f953dccf6f21eb
The relevant part in .vimrc was to to set `let g:airline_powerline_fonts=1`

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
