### ISSUE TITLE
Hyper config crash

### ISSUE THREAD

**Issue by dkfiresky** [zeit/hyper#1586]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.3
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default hyper config
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Hyper config replaced with the default one after trying to use `require` statement inside it.
Does it possible to require other modules within the config?

**Comment by ppot** [comment]
No, it's not made for this. Take it as a `.json` files but with comments

**Comment by dkfiresky** [comment]
Why it's not `.json` then? Why this is so confusing?

**Comment by ppot** [comment]
See Issue https://github.com/zeit/hyper/issues/289
