### ISSUE TITLE
Error updating plugins when using zsh

### ISSUE THREAD

**Issue by brunjick** [zeit/hyper#1587]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X El Capitan 10.11.6
- **Hyper.app version**: 1.2.1.1527
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Maybe related to this issue https://github.com/zeit/hyper/issues/1584. Using zsh shell as default, plugins doesn't install, unless I explicitly set `shell: 'zsh'` in configuration.

**Comment by jleeothon** [comment]
This might might be related to https://github.com/zeit/hyper/issues/1513.

**Comment by brunjick** [comment]
@jleeothon Oh, yes, it's the same issue, I missed it because it is closed, I guess this PR will fix it in the next release?
https://github.com/zeit/hyper/pull/1565

**Comment by CodeTheory** [comment]
Yup, same issue. Do you mind closing this one @brunjick? 😄
