### ISSUE TITLE
Less command not scrolling properly via mouse/touchpad

### ISSUE THREAD

**Issue by c0mpute** [zeit/hyper#1590]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Antergos Linux (4.9.11 kernel)
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/c0mpute/5d5e20dcabd80e93f35a6995f35964f5
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Hi,

I have an annoying problem when using the less command in Hyper. In any other terminal, I can scroll through the contents of the file in less using the touchpad. However, in Hyper, the touchpad scrolls the contents of the terminal history instead of the contents of the file in less. [This](https://superuser.com/questions/455212/how-to-make-mouse-wheel-scroll-the-less-pager-using-bash-and-gnome-terminal) superuser post explains it the best, but the root problem there has something to do with the LESS environment variable, which is the same in all terminals.

My guess is Hyper consumes all the mouse events before reaching less, which results in scrolling the terminal instead of the contents of the file.

**Comment by zsol** [comment]
Try this plugin: https://www.npmjs.com/package/hyperterm-alternatescroll

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
