### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by jasonhr13** [zeit/hyper#1591]
Is there an issue with your hosting? Downloads not working

**Comment by pggalaviz** [comment]
I think github is having an issue with S3 assets, trying to install Hyper via brew shows it's a package on S3 and it's timing out...

**Comment by matheuss** [comment]
Yeah, the whole internet is partially down at the moment :conf

**Comment by bntzio** [comment]
Yeah, I'm trying to re-download hyper and no luck.

I know what's happening to the internet these days @matheuss 😓

**Comment by pggalaviz** [comment]
Now my organizations' and Github's profile pictures are gone! And can't upload a new ones...

**Comment by bntzio** [comment]
@pggalaviz really? now that's really strange.

**Comment by albinekb** [comment]
It's the s3 issue and it isn't really strange, everyone is using it @pggalaviz

**Comment by bntzio** [comment]
From [Github Status](https://status.github.com) page: **"We are investigating issues serving web hooks as well as assets on GitHub.com."**

**Comment by pggalaviz** [comment]
From what I can see not everybody is having the profile picture issue, guess all I can do is wait.

**Comment by bntzio** [comment]
Download links working now.
