### ISSUE TITLE
Hyper error A javascript error occurred in the main process

### ISSUE THREAD

**Issue by habby1337** [zeit/hyper#1594]
the problem is that.
 when I try to install the program gives me a lot of java scripts errors 

![screenshot_1](https://cloud.githubusercontent.com/assets/21222491/23481396/7b85d74c-fecb-11e6-99f2-4fb6bed0d86e.png)

[Screenshot](http://image.prntscr.com/image/3241717b8786497d835fe129e2173682.png)

Hyper 1.2.1
Electron 1.4.7
win32 x64 10.0.14393

**Comment by fmontes** [comment]
Having the same issue.

**Comment by habby1337** [comment]
so how should I solve it?

**Comment by albinekb** [comment]
Do you have the exact same problem @habby1337 ?

**Comment by habby1337** [comment]
@albinekb yes, the same

**Comment by coreh** [comment]
![image](https://user-images.githubusercontent.com/418473/32401998-4123f04e-c102-11e7-9d87-1394b8d28aa0.png)

Also hitting this, both on 1.4.8 and 2.1

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: File not found: 
    at new WindowsPtyAgent (C:\Users\coreh\AppData\Local\hyper\app-2.1.0\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\coreh\AppData\Local\hyper\app-2.1.0\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:45:24)
    at spawn (C:\Users\coreh\AppData\Local\hyper\app-2.1.0\resources\app.asar\node_modules\node-pty\lib\index.js:27:12)
    at Session (C:\Users\coreh\AppData\Local\hyper\app-2.1.0\resources\app.asar\session.js:52:18)
    at initSession (C:\Users\coreh\AppData\Local\hyper\app-2.1.0\resources\app.asar\ui\window.js:95:24)
    at Server.Window.rpc.on.options (C:\Users\coreh\AppData\Local\hyper\app-2.1.0\resources\app.asar\ui\window.js:98:7)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Server.ipcListener (C:\Users\coreh\AppData\Local\hyper\app-2.1.0\resources\app.asar\rpc.js:33:11)
    at emitTwo (events.js:106:13)

[OK]
```

**Comment by CodeTheory** [comment]
Closing this as a fix seems to be found and due to inactivity since. Please let us know if you have any remaining/other issues! Also feel free to ask questions in https://zeit.chat 🎉

**Comment by driden** [comment]
Had the exact same issue on w7
Anyway, I wanted Hyper for PowerShell and my shell config was wrong.

had this: shell: '**`**C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe**`**'
instead of this (remove backticks): 
shell: 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'

**Comment by MehamudhaAfreen** [comment]
Am facing the same problem. there's no text on the screen except for if a open a new tab it throws out the same error. not able to do any with it..how can i solve it ?

**Comment by euntaik** [comment]
I had the same issue and my .hyper.js had shell set as bash.
Changed below line
`shell: 'bash',`
to
`shell: '',`

in file `%APPDATA%\Hyper\.hyper.js`

**Comment by dc769319** [comment]
I fix this error by running cmd.exe as administrator

**Comment by rstacruz** [comment]
This is happening to me right now and the fixes in this thread don't help. Let me try to find out more.

**Comment by drone1** [comment]
> EDIT: It was some plugins that made this mess up, I just emptied out the plugins list.

FWIW, my .hyper.js file has an empty array for both plugins and localPlugins, and I get symlink errors.

**Comment by Ebrahitc1983** [comment]
Hi guys and girls, sorry i'm new to this whole thing but can some tell me has anyone found a solution to the problem yet ?

**Comment by mdirshaddev** [comment]
> Hi guys and girls, sorry i'm new to this whole thing but can some tell me has anyone found a solution to the problem yet ?

Well technically you have to uninstall all the plugins you have.

**Comment by ankitraj311** [comment]
> the problem is that.
> when I try to install the program gives me a lot of java scripts errors
> 
> ![screenshot_1](https://cloud.githubusercontent.com/assets/21222491/23481396/7b85d74c-fecb-11e6-99f2-4fb6bed0d86e.png)
> 
> [Screenshot](http://image.prntscr.com/image/3241717b8786497d835fe129e2173682.png)
> 
> Hyper 1.2.1
> Electron 1.4.7
> win32 x64 10.0.14393




Simply open the CMD with Admin.
And Run the following command  -----



C:\WINDOWS\system32>hyper i hyper-clean
hyper-clean installed successfully!

C:\WINDOWS\system32>hyper install hyper-clean
hyper-clean is already installed

C:\WINDOWS\system32>hyper i hyper-clean
hyper-clean is already installed

C:\WINDOWS\system32>hyper list
hypercwd
hyper-clean



Now Remove the New plugin which you recently installed. If don't know then remove all the plugin other then "hyper-clean" .
Volllaa Problem Solved.

You have to uninstall the plugin in the following way, Down below.


C:\WINDOWS\system32>hyper u hypercwd
hypercwd uninstalled successfully!

**Comment by ankitraj311** [comment]
> Hi guys and girls, sorry i'm new to this whole thing but can some tell me has anyone found a solution to the problem yet ?

Simply open the CMD with Admin.
And Run the following command  -----



C:\WINDOWS\system32>hyper i hyper-clean
hyper-clean installed successfully!

C:\WINDOWS\system32>hyper install hyper-clean
hyper-clean is already installed

C:\WINDOWS\system32>hyper i hyper-clean
hyper-clean is already installed

C:\WINDOWS\system32>hyper list
hypercwd
hyper-clean



Now Remove the New plugin which you recently installed. If don't know then remove all the plugin other then "hyper-clean" .
Volllaa Problem Solved.

You have to uninstall the plugin in the following way, Down below.


C:\WINDOWS\system32>hyper u hypercwd
hypercwd uninstalled successfully!

**Comment by ankitraj311** [comment]
> Had the exact same issue on w7
> Anyway, I wanted Hyper for PowerShell and my shell config was wrong.
> 
> had this: shell: '{backtick}C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe{backtick}'
> instead of this (remove backticks):
> shell: 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe'

Simply open the CMD with Admin.
And Run the following command  -----



C:\WINDOWS\system32>hyper i hyper-clean
hyper-clean installed successfully!

C:\WINDOWS\system32>hyper install hyper-clean
hyper-clean is already installed

C:\WINDOWS\system32>hyper i hyper-clean
hyper-clean is already installed

C:\WINDOWS\system32>hyper list
hypercwd
hyper-clean



Now Remove the New plugin which you recently installed. If don't know then remove all the plugin other then "hyper-clean" .
Volllaa Problem Solved.

You have to uninstall the plugin in the following way, Down below.


C:\WINDOWS\system32>hyper u hypercwd
hypercwd uninstalled successfully!

**Comment by ranadawar** [comment]
Another reason for this "maybe you don't have installed git yet in your pc.

**Comment by lizrivera18** [comment]
Why happen this? 
![image](https://user-images.githubusercontent.com/104868812/166654221-cac947c9-e811-4512-8dc0-d3d5022bfce8.png)
![image](https://user-images.githubusercontent.com/104868812/166654593-1505ce1d-5e7f-4ab3-9583-05d6596f34ce.png)

**Comment by DDASSS** [comment]
> Hi guys and girls, sorry i'm new to this whole thing but can some tell me has anyone found a solution to the problem yet ?

Go to `Edit > Preferences` in Hyper; it will open `.hyper.js` file. Just set shell: `'<path>'` path properly.

**Comment by felipeversiane** [comment]
![error](https://user-images.githubusercontent.com/111650483/219108509-02d45978-cadb-4f5a-b478-b493d1ec658c.png)

**Comment by felipeversiane** [comment]
![image](https://user-images.githubusercontent.com/111650483/219108557-801dc923-9f62-46c0-a65f-8fd666e5d65d.png)
anyone now how to fix this ?

**Comment by U-rex13** [comment]
Solution for Hyper Terminal Error 
If hyper doesn't open after changing the Preferences, just follow these steps:

1) open explorer and go to C://user/**YOUR USERNAME**/AppData/Roaming/hyper
    and open the ".hyper.js" File with a Text-Editor.

    (in case you don't see the AppData Folder, change the View -> Folder Options -> View -> scroll down and search for "show hidden files, folders etc" and check this radio button.)

2) in ".hyper.js" file, look (below the colour section) for the line
    "shell: 'C:\\Program files\\Git\\git-cmd.exe'"

    IF YOU CHANGED THE DIRECTORY THROUGH THE GIT INSTALL PROCESS:
    enter your Path to this line. example: D:\\Anywhere\\else\\Git\\git-cmd.exe

3) Now hit save and try to start hyper again. It should be working now!

**Comment by CodeWithAnu47** [comment]
> 
same error

**Comment by reubence** [comment]
Guys i ran powershell in administrator mode and it fixed this issue
