### ISSUE TITLE
Support for WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by alshdavid** [zeit/hyper#1596]
Is there a way to point Hyper to run WSL on Windows 10?

**Comment by Fumler** [comment]
Open %UserProfile%/.hyper.js and change line 67 to ```shell: 'bash.exe'```

**Comment by Zx-EvM** [comment]
Change line `shell: ''` in `%USERPROFILE%/.hyper.js` file to `shell: 'C:\\Windows\\System32\\bash.exe'`

**Comment by davemackintosh** [comment]
Any reason this wouldn't carry the bash_profile with it?

**Comment by matheuss** [comment]
@davemackintosh I can't recall right now but there's a reason – I'd like to _fix_ it tho

**Comment by hikurangi** [comment]
why is adding `shellArgs: ['~'] necessary?

1. It means that I can't open hyper.js in a folder with the context menu (it will send me to ~, not the folder I've right-clicked in from explorer).

2. if I specify ['/'] or any other valid WSL folder name ['/mnt/c/Users/CheeseBoy9000/Documents'], hyper.js quits with a "No such file or directory" error.
