### ISSUE TITLE
error updating plugins

### ISSUE THREAD

**Issue by simonmurdock** [zeit/hyper#1603]
- **OS version and name**: Windows 10
- **Hyper version**: 1.2.1
- **node version**: 6.10.0
- **npm version**: 3.10.10

- **The issue is reproducible in vanilla Hyper app**: fresh install on OS X and windows both fail with this error every time I start hyper

## Issue
I've seen this mentioned in some old tickets but didn't find a suitable resolution. In my case a fresh install today on two machines/operating systems gives me this error every time I start hyper out of the box
```
Error updating plugins
Check '~/.hyper_plugins/npm-debug.log' for more information
```
However that file does not exist. I figured 2 of machines can't be configured incorrectly enough to break your application so worth reporting

**Comment by henrikdahl** [comment]
Dupe: #1513

**Comment by simonmurdock** [comment]
but that's closed @henrikdahl is using a .bat the recommended fix?

**Comment by henrikdahl** [comment]
@simonmurdock Have you tried defining a shell in your config? ✌️

**Comment by simonmurdock** [comment]
@henrikdahl I tried using `cmd.exe` and `C:\\Windows\\System32\\bash.exe` as described in `.hyper.js`, but no luck, same exact behaviour

**Comment by henrikdahl** [comment]
@simonmurdock It's already fixed on the master branch, we're just waiting for a release.

**Comment by dipaktelangre** [comment]
I have spent an hour to find the workaround for the plugin not working, but unfortunately nothing workout for me on windows 10 and Hyper 1.2.1. Please fix this as soon as possible. Its very nice terminal specially for windows.

**Comment by timneutkens** [comment]
@dipaktelangre @henrikdahl new release coming in :soon:. Stay tuned 👍

**Comment by DavidBurela** [comment]
I've done a fresh install of Hyper 1.3.1, my first time ever using it.  And on launch I get this error.  I set bash.exe as my shell of choice. relaunch it, issue still persists. Windows 10.

**Comment by DrLonnieJonesPFMP** [comment]
I'm running 1.3.3 and the first time after installation it ran correctly, but after that I started to see the error.
Running Windows 10 Pro x64
