### ISSUE TITLE
Shortcut key to open terminal quickly

### ISSUE THREAD

**Issue by eness** [zeit/hyper#1604]
I've been using ConEmu for a while and it has a pretty useful feature mentioned as "Quake Mode" which enables you to set a hotkey to bring the terminal quickly in front of your screen. For example I usually bind on windows) CTRL + " key as quake mode key and whenever I press this key (assuming you've already run the terminal) the console immediately comes upfront.

Is there any that kind of plugin or setting in hyper that enables that feature? Or we might open a feature request if accepted.

**Comment by levsthings** [comment]
Not related to your question but may I ask how did you get ConEmu working with Hyper? I'm using cmder and if I point it's executable as the shell, it opens up on a separate window.

**Comment by SpencerLynn** [comment]
+1. I would also enjoy a hotkey to "summon" the hyper window, similar to the "quake mode" feature of ConEmu.

**Comment by eness** [comment]
@levsthings I suppose it doesn't make sense trying to attach one terminal into another, as both they are just similar tools. What you can do is to attach a shell (such as git-bash) directly into Hyper.

**Comment by levsthings** [comment]
@eness I finally managed to include ConEmu in Hyper after all, there are plenty of benefits. Running services like mongodb requires the command line, git-bash doesn't cut it. In ConEmu, you have access to both bash and command line, powershell all together.

**Comment by ppot** [comment]
@SpencerLynn  Can you make a gif?

**Comment by SpencerLynn** [comment]
I found this GIF on the internet.
![Quake](http://1.bp.blogspot.com/-Cu3DReXcuZU/VbViZ1Yc7BI/AAAAAAAATlU/63Fw4PHrCxQ/s1600/cmder.gif)

In addition to the toggle of using "quake mode" to summon the prompt, there is an animation duration setting. I use 0 so the window is only brought to the front (with no vertical animation). 

I think the feature of having the window "summon"-able would be a great touch.

**Comment by Idered** [comment]
There're plugins for that:

https://www.npmjs.com/package/hyperterm-summon
https://github.com/CWSpear/hyperterm-visor

**Comment by SpencerLynn** [comment]
@Idered Thanks for finding those! I just saw the issue and +1'd the idea (obviously without looking for existing plugins). Thanks!

**Comment by ppot** [comment]
Closing in favor of plugin. Thanks for the information.

**Comment by Delphin10** [comment]
If you are on ubuntu try this

- Go to keyboard settings and scroll down to the bottom
- Click on (+) Add Custom Shortcut
- Set 

1. Name: whatever you want (hyper for example)
2. Command: hyper
3. Shortcut: It's up to you (<kbd>crtl+T</kbd>)

**Comment by marcosdipaolo** [comment]
> If you are on ubuntu try this
> 
> * Go to keyboard settings and scroll down to the bottom
> * Click on (+) Add Custom Shortcut
> * Set
> 
> 1. Name: whatever you want (hyper for example)
> 2. Command: hyper
> 3. Shortcut: It's up to you (crtl+T)

and to make it toggle the terminal? like that we can only open it, if you press again it opens another one

**Comment by SpiderUnderUrBed** [comment]
Hyperterm-visor is deprecated. They archived the repository. I would also perfer not to have NPM or that stuff on my system, maybe there would be utility in native support?

**Comment by SpiderUnderUrBed** [comment]
Sorry, I forgot that all plugins use npm as this is a NPM based project, sorry again.
