### ISSUE TITLE
Wrong indent in the window, Chinese characters are squeezed.

### ISSUE THREAD

**Issue by jingkangy91** [zeit/hyper#1606]
- When I start hyper, the shell prompt and cursor are at the right side and the middle of the terminal, not at the left side which they should be.
- If you type a wrong command, like 'ls', it will indent to the right side again; until you type an exist command, e.g. 'git', the cursor will come back to the left side.
- Chinese characters are squeezed together.

Hyper 1.1.0
Electron 1.4.7
win32 x64 10.0.15048

**Comment by j84lee** [comment]
same here, Chinese characters are squeezed together.

**Comment by dr2009** [comment]
```bash
vim ~/.hyper.js
```

```
termCSS: '.wc-node{width: 16px !important}',
```

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
