### ISSUE TITLE
Question: Run command on terminal initialization

### ISSUE THREAD

**Issue by levsthings** [zeit/hyper#1607]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Win 10**
- **1.2.1**

## Question

I'm trying to use Hyper with cmder/conemu and to get it working properly I need to run a .bat file after terminal initialization. Is there any functionality available that will help me auto-execute a command on startup?

**Comment by levsthings** [comment]
**Update**
There's a plugin called [hyper-startup](https://www.npmjs.com/package/hyper-startup) that can do this but at this moment [I couldn't get the plugin to work](https://github.com/curz46/hyper-startup/issues/1) with Windows command line.

**Comment by levsthings** [comment]
**Update**
There's a plugin called [hyper-startup](https://github.com/curz46/hyper-startup) that can do this without an issue.

**Comment by spences10** [comment]
@levsthings can you tell me what the `.bat` was as I want to do the same with my Windows 10

**Comment by ppot** [comment]
@spences10 just call the `.bat` from the command. you can add list of commands in your script.

**Comment by spences10** [comment]
@ppot what `.bat` do I call from where?

This is really frustrating me now as I recall I found this mentioned somewhere else and I just changed some of the `.hyper` settings and it worked

I'm obviously having a bad Google fu day

I since deleted my hyper install as I was getting errors and didn't make a backup of my `.hyper` file
