### ISSUE TITLE
Cannot type command normally with Windows 10's Chinese IME

### ISSUE THREAD

**Issue by hungys** [zeit/hyper#1611]
- [V] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [V] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Anniversary Update
- **Hyper.app version**: 1.2.1

## Issue

When typing command in Hyper with Windows 10's **Chinese IME**, two keystrokes result in only one character on the terminal. For example, when I type in `sudo`, it only shows `sd`.

PS. But it works correctly after switching to English-only IME.

![](http://i.imgur.com/rN5uBe9.png)

I have seen some related issues (e.g. #66 #1006), but it seems that there is still some problem on Windows.

**Comment by karocksjoelee** [comment]
same here

**Comment by HelloWorld017** [comment]
This problem also occurs in Korean IME (In my case, Microsoft IME 2010).
In Korean input mode, no Hangul characters (Korean characters) are entered but each second English keys are entered. But, when I change to English input mode, characters are entered normally.

**Comment by charles-passille-smartnets** [comment]
Doesn't work with Japanese Windows(10) IME, nor Google's IME input.

**Comment by chabou** [comment]
Can you try with `xterm` branch?

**Comment by charles-passille-smartnets** [comment]
@chabou I've had the hardest time compiling in windows, but i finally got it.
Unfortunately the `xterm` branch does not solve this issue, no :(

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
