### ISSUE TITLE
Setting bell to false doesn't prevent sounds on Window 10

### ISSUE THREAD

**Issue by pheuter** [zeit/hyper#1613]
- **OS version and name**: Windows 10 Pro
- **Hyper.app version**: 1.2.1 **or** 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Basically the default but with `bell: false`.
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue

Setting the `bell` attribute to `false` in my **.hyper.js** does not prevent the terminal from producing sounds whenever I tab-complete or do other actions.

**Comment by Jenuma** [comment]
I am experiencing the same issue. Windows 10.0.10240.

**Comment by Ouro17** [comment]
Same here on Win version 1607, 14393.693

**Comment by francoiscote** [comment]
same on macOS 10.12.3

**Comment by sixclones** [comment]
Same on macOs 10.12.3

**Comment by nwcas** [comment]
Yeah can confirm this, pretty annoying issue but probably a system level thing. I can get it silent if I disable all windows sounds. Disabling some of them seems to move the sound around to different ones until I get a default beep but the option to set to false or the folder hack above doesn't work for me. Im one who prefers a flash to a beep, dunno if someones done a plugin for that already I haven't checked as yet.

**Comment by nwcas** [comment]
I gotta say as feedback this is an awesome terminal for windows, combined with bash for windows 10 it really provides that awesome terminal experience for windows that I get from linux and osx, absolute god send and believe me I spent countless hours fudging with the other emulators to get a good experience, the best I found being cmdr other than this but it and the others all have show stopping issues. I found this terminal purely by chance reading an issue about powerline fonts, its a shame I didn't come across it earlier, I guess it doesn't get a lot of press as yet but it should!

**Comment by wmhilton** [comment]
This. Is. Driving. Me. Insane. 🙉 Have always had this problem though. Windows 10 user.

**Comment by wmhilton** [comment]
Alright. After building hyper from source and commenting out the bit in `hterm.Terminal.prototype.ringBell` where it calls `oldRingBell`... it still rings. It must be something about Windows... but strange that I have no such problem in Git Bash or ConEmu or plain old cmd.

**Comment by wmhilton** [comment]
Alright. On Windows it plays the Default Beep sound, which for some reason I had set to Windows Background.wav instead of Windows Default.wav. I changed Default Beep to play Windows Ding.wav which is much quieter. Now *lots* of programs (including Chrome's find & replace) sound less jarring.

Hopefully that info helps somebody.

**Comment by pheuter** [comment]
What I finally found that worked for me is creating `~/.inputrc` in WSL bash and setting `set bell-style none`.

**Comment by jieverson** [comment]
@pheuter are you using /bin/bash or /bin/zsh? Cause I'm using zsh, and that does not seems to fix for me.

**Comment by pheuter** [comment]
@jieverson Right, I had to use bash for it to work. Didn't work when I was on zsh or fish. Would love to know if you find an equivalent fix for those shells.

**Comment by therealplato** [comment]
Thanks for the workaround @pheuter! I've switched to this fast wooden knock; see also the related tags. http://soundbible.com/605-Wood-Whack.html

**Comment by looselyrigorous** [comment]
I've also got a hacky solution (if you want to turn it off) for Windows. Just mute it in the Volume Mixer. Hyper was showing up as 'Console Window Host' there.

**Comment by remy** [comment]
Apparently zsh needs this `unsetopt beep` (though I've not tested it, I'm using bash on windows, and the `set bell-style none` worked for me). ([source](https://dustri.org/b/my-zsh-configuration.html))

**Comment by gmazlami** [comment]
@remy Your solution did it for me with zsh / oh-my-zsh. I just added `unsetopt beep` to my `.zshrc`. Thanks a lot!!

**Comment by lylejantzi3rd** [comment]
Thanks, @remy! None of the other solutions I tried worked and this has been driving me nuts for days.

**Comment by sghiassy** [comment]
On a OS X I cheated. I just went to 

`System Preferences -> Notifications -> Hyper -> Play sound for notifications`

and disabled the checkbox.

**Comment by JohnAllen** [comment]
@sghiassy's solution didn't work for me.  The box is already unchecked!

**Comment by sghiassy** [comment]
@JohnAllen - Looking over my `.hyper.js` config file, I also had `bell: false` set in the config. Perhaps they're needed in combination with one another??

**Comment by JonathanNathanson** [comment]
@remy unsetopt beep in the .zshrc is a great solution - thank you! this was driving my colleagues around me absolutely mad..!

**Comment by ptessier** [comment]
@sghiassy What you are referring is **disabling the sound** for the **notification banners** in the corner of your screen. We can see an example of this when `hyper.js` reloads the configuration.

**Comment by swetli** [comment]
None of the workarounds worked for me on windows 10. I had to completely disable the sounds for the windows theme to get rid of the bell sound( Right click on the desktop->Personalize->Themes->Sounds->No Sounds)

**Comment by rcowles3** [comment]
On Windows 10, I went to Notifications and actions settings, and then just turned off notifications from Hyper and it worked.

**Comment by ozbonus** [comment]
On Windows 10 the bell is the "Critical Stop" sound, so change that and you'll change the bell.

If you're thinking about setting it to silent, I've got bad news for you. At least on my machine doing that instead caused a *booop* sound to be played, and I couldn't find a way to silence that.

My solution: Set Critical Stop to a softer sound. I settled on ding.wav, which is in the list of default Windows sounds (as has been since Windows 95, I think).

Another solution: Try setting Critical Stop to a silent wav file.

It's a sad work-around, but I hope it brings relief to some of you.

**Comment by sim186** [comment]
Setting the critical stop sound to a silent wav file worked for me, thanks to ozbonus ([https://github.com/zeit/hyper/issues/1613#issuecomment-369208180](url))

**Comment by davidgilbertson** [comment]
Just turning off notifications for Hyper (in Window's "Notifications & actions" settings) stops the bell (and the notification).

![image](https://user-images.githubusercontent.com/4443482/39080035-05115488-456a-11e8-8517-d473e656a720.png)

**Comment by whywaitwebs** [comment]
~/.inputrc did nothing for me, I had to set it in /etc/inputrc

What an absolutely annoying issue, I want to commit an atrocity.

**Comment by android2221** [comment]
@jasperandrew 's solution worked for me in git bash as well :)

**Comment by jtackaberry** [comment]
It's a fine workaround if you never ssh anywhere.

**Comment by TheNexusDesigns** [comment]
just wanted to say thanks @jasperandrew this worked 💯

**Comment by Monsieur-Moony** [comment]
I'm using Zsh via Bash on Windows (WSL) - the solution by @remy fixed the beeps on the shell, but for vim I also had to add `set visualbell` to ~/.vimrc.

**Comment by gerchicov-bp** [comment]
@jasperandrew ok, what about OSX? Must I recreate a separate ticket for the same issue but for other platform?

**Comment by kalumkalac** [comment]
I use Hyper on Windows with WSL. The workaround with `~/.inputrc` stated by @pheuter worked in that case, but when I ssh to a remote host, it still bells.

Turning the sound notification off for this app did not help in that case.

The two other workarounds works. Either use a softer or even a silent wav in the *Critical Stop* sound setting, or in my case, muting the Hyper *Console Window Host* application in the *Volume Mixer*.

**Comment by DanPallas** [comment]
I had this problem with powershell. I use psreadline and was able to disable the bell with `Set-PSReadlineOption -BellStyle None`

**Comment by Suhail** [comment]
I set mine to Default Beep -> None on Windows 10's Sound Control Panel. Noise went away.

**Comment by ekreutz** [comment]
Amazingly annoying issue. I tried hyper some months ago and found it to be slow at that point. Now, with the WebGL renderer it seems more responsive but apparently still has crazy quirks like this.

Had to turn off notification sounds in macOS preferences to get around this... 😄

**Comment by gbvaz** [comment]
All I did was mute bash app on windows volume mixer
![image](https://user-images.githubusercontent.com/7118638/59165555-217cef80-8af4-11e9-97c1-db4dab2ed1fa.png)

**Comment by chpmrc** [comment]
It's worth noting that @pheuter's workaround works with SSH too, you just have to create/update ~/.inputrc in the remote host as well.

**Comment by Stanzilla** [comment]
should no longer happen with CI builds of canary and the next release
