### ISSUE TITLE
I changed the shell in config to '/desktop' and now it won't open.

### ISSUE THREAD

**Issue by joshpitzalis** [zeit/hyper#1614]
When I try and open hyper it open for a split second and then closes as a pop up in the top right says 'Plugin Load error', 'hyperterm-working-directory failed to load in the render process. Check dev console.'

BUt I can't check the console but it automatically closes down before I can do anything.

I tried uninstalling everything and re-installing everything but the same problem crops up.

I can't open hyper to change it back and fix the problem.
-

Hyper 1.2.1
Electron 1.4.7
darwin x64 16.4.0

**Comment by hugomd** [comment]
@joshpitzalis Open Terminal.app and edit the shell in `~/.hyper.js` from there.

**Comment by albinekb** [comment]
or just remove `~/.hyper.js` and it will reset to the default

**Comment by joshpitzalis** [comment]
You guys are fantastic. Thank you very much.
