### ISSUE TITLE
Open hyper on startup/by shortcut

### ISSUE THREAD

**Issue by balazsorban44** [zeit/hyper#1615]
Hi! I would like to run hyper on startup. What is the command for this? And is it possible to set the beginning position and size too? I also want to open it by a shortcut on a specified position.

Thanks

I am on Ubuntu 16.04

**Comment by Erazihel** [comment]
Hi, there's the `hyperterm-visor` plugin that'll let you open `Hyper` using a shortcut at a specified position.

Check the package [here](https://www.npmjs.com/package/hyperterm-visor).

**Comment by balazsorban44** [comment]
Thanks!
