### ISSUE TITLE
Characters appearing on watching programs when cmd + tab in/out of hyper

### ISSUE THREAD

**Issue by Sinequanonh** [zeit/hyper#1618]
as well on my nodejs programs, gulp watchers and so on, those `^[[O` appear 
<img width="440" alt="capture d ecran 2017-03-09 a 22 43 48" src="https://cloud.githubusercontent.com/assets/14036376/23772199/67631914-051a-11e7-8b7e-7196d8859543.png">

A few minutes later without any change on my side:
<img width="615" alt="capture d ecran 2017-03-09 a 22 49 15" src="https://cloud.githubusercontent.com/assets/14036376/23772272/a942f142-051a-11e7-8a5f-b740525eb3ba.png">

Is there a way to get rid of it?
Thanks! 🙌

**Comment by Sinequanonh** [comment]
It actually happens when I `cmd + tab` in `^[[I` and out `^[[O` of hyper.

**Comment by teddy-error** [comment]
What shell are you running?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
