### ISSUE TITLE
Echo text being included on .hyper.js edit using VIM

### ISSUE THREAD

**Issue by rizowski** [zeit/hyper#1619]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX Sierra V 10.12.3
- **Hyper.app version**: 1.3.0.1614 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  https://gist.github.com/rizowski/dc846b7d73313ba7b4ee250d45fabf89 
- **Relevant information from devtools**: `Mac OS: CMD + ,`
- **The issue is reproducible in vanilla Hyper.app**: Not Vanilla

## Issue
When I hit `CMD + ,` to edit the preferences I get some of the echo statements prepended on top of my config. See screenshot:

![screenshot 2017-03-09 14 06 52](https://cloud.githubusercontent.com/assets/574835/23771038/b590b5f8-04d2-11e7-903b-9817cbcb9dda.png)

I am using `vim` as my editor. If I execute the command the hyper uses to open `.hyper.js` I do not get this. The command being `bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'`

This issue didn't start happening until I upgraded to 1.3.0.

**Comment by boobiq** [comment]
same thing is happening with default EDITOR being nano
<img width="919" alt="screen shot 2017-03-10 at 11 08 58" src="https://cloud.githubusercontent.com/assets/429225/23791076/fcf331f0-0581-11e7-98df-676905d167ef.png">

**Comment by henrikdahl** [comment]
Solved https://github.com/zeit/hyper/pull/1633 ✌️
