### ISSUE TITLE
First line cutted

### ISSUE THREAD

**Issue by Rawnly** [zeit/hyper#1620]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: `macOS Sierra 10.12.3`
- **Hyper.app version**: `1.3.0` 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Vanilla [`.hyper.js`](https://gist.github.com/Rawnly/4e80b9fea4c400bd62c86e1508efd251)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
![schermata 2017-03-10 alle 00 52 10](https://cloud.githubusercontent.com/assets/16429579/23776014/e2c85a18-052b-11e7-985b-06971fbb17c0.png)

- **The issue is reproducible in vanilla Hyper.app**: **Yes**

## Issue

**Shell**: `oh-my-zsh`
**Reproducible in bash**: *Yes*

The first line of the screen is cutted. 
![schermata 2017-03-10 alle 00 47 54](https://cloud.githubusercontent.com/assets/16429579/23776029/f51d7266-052b-11e7-89c6-8114986218cc.png)

**Comment by henrikdahl** [comment]
That definitely doesn't look like vanilla `.hyper.js`

Care to share your config? ✌️

**Comment by Rawnly** [comment]
@henrikdahl updated the issue, btw this is the [vanilla configuration](https://gist.github.com/Rawnly/4e80b9fea4c400bd62c86e1508efd251)

The only thing who i changed is the `font-size: 24`

**Comment by antoinerey** [comment]
I don't know if it's related or not but I noticed the caret is not properly aligned anymore (You can clearly see this on the @Rawnly's screenshot above. It appeared during the last update (1.3.0)

**Comment by Rawnly** [comment]
@antoinerey Yes I confirm, I didn't say anything because the line cut is more relevant for me

**Comment by Rawnly** [comment]
Fixed on [`237595c`](https://github.com/zeit/hyper/commit/237595cec83f1d3796e1f625bd8ca97a1cd1d443)
