### ISSUE TITLE
Extra Chinese character.

### ISSUE THREAD

**Issue by SidKwok** [zeit/hyper#1623]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: mac os 10.12.3
- **Hyper.app version**: 1.3.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
up is terminal.app, down is hyper.
<img width="226" alt="31e3f558-5607-4664-ac64-da3b7d8d508b" src="https://cloud.githubusercontent.com/assets/13268747/23783458/a6c6559a-0596-11e7-9c8d-b055c8772f88.png">
run `ll` in both terminal.app and hyper.

I think the pic can illustrate my issue well.

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
