### ISSUE TITLE
How to upgrade my hyper.app?

### ISSUE THREAD

**Issue by LitoMore** [zeit/hyper#1624]
I didn't find the `Check For Updates` button on menu bar.

Go to [hyper.is](https://hyper.is) and redownload it?

**Comment by mikeumus** [comment]
@LitoMore, for me a green card shows in the lower right asking to click to upgrade and then it upgrades itself. Which OS/version of Hyper are you on?

**Comment by matheuss** [comment]
@LitoMore it should update itself automatically on all platforms. 

Since you didn't fill the issue template (please don't do that – it's very important to provide the necessary info for us), I'm closing this – please open a new issue with more info! 🙏

**Comment by haoyangnz** [comment]
@LitoMore have you resolved this issue? I have opened #1661 for the same issue.

**Comment by puranjayjain** [comment]
@matheuss It doesn't for `*.deb` installed version on Ubuntu

**Comment by mojoaxel** [comment]
Maybe this is interesting t some of you...I wrote a little update tool for linux, that downloads the newest .deb and installs it:

https://gist.github.com/mojoaxel/4fa8947905472818a72a97c113b535ae
