### ISSUE TITLE
Vibrancy and opacity not working in linux

### ISSUE THREAD

**Issue by telmen** [zeit/hyper#1625]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: Hyper 1.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/telmen/3ab5f895b0b4134029724f78ba08bff7
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Vibrancy or opacity not working on linux at all,
![screenshot from 2017-03-10 15-28-24](https://cloud.githubusercontent.com/assets/6022423/23786153/4fb82372-05a6-11e7-9a08-dd7a02972c19.png)
any suggestion?

**Comment by Rawnly** [comment]
Try another theme, like `hyper-material-theme` by @equinusocio, add the extra settings and enable vibrancy.

**Comment by telmen** [comment]
It's not working, I guess vibrancy not possible on linux

**Comment by c0b41** [comment]
@telmen vibracy only support macOS [ref](https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions)

**Comment by stefanivic** [comment]
Yeah, vibrancy is MacOS only, what you can do is start Hyper with `--enable-transparent-visuals --disable-gpu` and put `rgba(0, 0, 0, 0.8)` in `hyper.js` under `background-color`.

**Comment by telmen** [comment]
Yeah, it gives transparency effect to hyper. Thanks. 👍

**Comment by Zx-EvM** [comment]
@stefanivic how to start hyper with keys `--enable-transparent-visuals --disable-gpu`?. Where I need to write this if I using Windows?

**Comment by equinusocio** [comment]
@Zx-EvM Just make a shortcut and edit the link by adding flags
https://superuser.com/questions/29569/how-to-add-command-line-options-to-shortcut

**Comment by Zx-EvM** [comment]
@stefanivic @equinusocio thanks. It's doesn't work on Windows. Apparently hyper.is team did not implement support for opacity/transparent/vibrancy on Windows.

Or do you have it working?

**Comment by telmen** [comment]
Hm, electron doesn't provide windows and linux. For linux, its because gpu driver

**Comment by jcdino** [comment]
Hi, i know the thread is closed, but i proved the flags in arch linux and nothing happens more that to get darker if i increase the transparency but full opacity.

![screenshot_20170908_065742](https://user-images.githubusercontent.com/10819999/30206913-0696c26e-9464-11e7-9440-08fac76facb1.png)

**Comment by albinekb** [comment]
Then it's probably not supported in Arch linux 😢  @jcdino

**Comment by stefanivic** [comment]
If i remember, there was something about Electron dropping the transparent support on Linux, but don't quote me on this one.

**Comment by chabou** [comment]
FTR: https://github.com/electron/electron/issues/2170#issuecomment-217405460

**Comment by stepanvanzuriak** [comment]
Maybe this can help: https://github.com/electron/electron/issues/2170#issuecomment-355144344 ?

**Comment by lalitmee** [comment]
When I am trying the command `hyper --enable-transparent-visuals --disable-gpu` to start hyper in **Ubuntu 16.04**, it is showing this output. Please help me.

- Output 

```
❯  hyper --enable-transparent-visuals --disable-gpu
The option "enable-transparent-visuals" is unknown. Here's a list of all available options: 

  Usage: hyper [options] [command]
  
  Commands:
  
    <default>                    Launch Hyper
    d, docs, h, home             Open the npm page of a plugin
    help                         Display help
    i, install                   Install a plugin
    ls, list                     List installed plugins
    lsr, list-remote, ls-remote  List plugins available on npm
    s, search                    Search for plugins on npm
    u, uninstall, rm, remove     Uninstall a plugin
  
  Options:
  
    -h, --help     Output usage information
    -v, --verbose  Verbose mode (disabled by default)
  
```

**Comment by Alfian5229** [comment]
> When I am trying the command `hyper --enable-transparent-visuals --disable-gpu` to start hyper in **Ubuntu 16.04**, it is showing this output. Please help me.
> 
>     * Output
> 
> 
> ```
> ❯  hyper --enable-transparent-visuals --disable-gpu
> The option "enable-transparent-visuals" is unknown. Here's a list of all available options: 
> 
>   Usage: hyper [options] [command]
>   
>   Commands:
>   
>     <default>                    Launch Hyper
>     d, docs, h, home             Open the npm page of a plugin
>     help                         Display help
>     i, install                   Install a plugin
>     ls, list                     List installed plugins
>     lsr, list-remote, ls-remote  List plugins available on npm
>     s, search                    Search for plugins on npm
>     u, uninstall, rm, remove     Uninstall a plugin
>   
>   Options:
>   
>     -h, --help     Output usage information
>     -v, --verbose  Verbose mode (disabled by default)
>   
> ```

yeah, me too

**Comment by Sin13** [comment]
> 
> 
> When I am trying the command `hyper --enable-transparent-visuals --disable-gpu` to start hyper in **Ubuntu 16.04**, it is showing this output. Please help me.
> 
>     * Output
> 
> 
> ```
> ❯  hyper --enable-transparent-visuals --disable-gpu
> The option "enable-transparent-visuals" is unknown. Here's a list of all available options: 
> 
>   Usage: hyper [options] [command]
>   
>   Commands:
>   
>     <default>                    Launch Hyper
>     d, docs, h, home             Open the npm page of a plugin
>     help                         Display help
>     i, install                   Install a plugin
>     ls, list                     List installed plugins
>     lsr, list-remote, ls-remote  List plugins available on npm
>     s, search                    Search for plugins on npm
>     u, uninstall, rm, remove     Uninstall a plugin
>   
>   Options:
>   
>     -h, --help     Output usage information
>     -v, --verbose  Verbose mode (disabled by default)
>   
> ```
as described [https://github.com/vercel/hyper/issues/1625#issuecomment-285774582](url) its not a command.

you should put them in the target box of a shortcut. don't bother though! i tried that and didn't get any transparency effect :(
