### ISSUE TITLE
Error on loading configuration file

### ISSUE THREAD

**Issue by damienbidaud6** [zeit/hyper#1626]
Hello

Since the new reales 1.3.0 when I try to change my configuration file I have a error after saving the new file who say: 

`An error occurred loading your configuration (/Users/bidaudd/.hyper.js): Unexpected identifier`

And the change are not apply after that.

I try to reinstall the app and I still have the error 

I am on OSX 10.11.6
The version of the app is the 1.3.0
Link of a gist of my `.hypper.js` : https://gist.github.com/damienbidaud6/722ae817784e92ad10a0d76e2b9c033e 

Thanks for the help.

**Comment by boobiq** [comment]
I believe it's because #1619 which adds text at the beginning of your configuration and it can't be parsed correctly.

**Comment by damienbidaud6** [comment]
I remove the text and it's work but after I save it's add again. It's possible to disable this behaviour?

**Comment by boobiq** [comment]
You have to remove that text it adds every time (they have to fix this bug) or you can edit **.hyper.js** file manually by running `vim ~/.hyper.js` (or any other editor), this bug only happens when you press **CMD+,** to open preferences

**Comment by damienbidaud6** [comment]
Ok thanks

**Comment by henrikdahl** [comment]
Closing since this is fixed in 1.3.1 ✌️
