### ISSUE TITLE
After some time after start rendering tab contents doesn't work properly

### ISSUE THREAD

**Issue by boobiq** [zeit/hyper#1628]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.3
- **Hyper.app version**: 1.3.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: vanilla config
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I'm not sure how to reproduce it, but everytime I start Hyper, it works fine, but after some time (seconds/minutes) it stops rendering content of tabs. I can open/close new tabs and when I do something it executes normally (for example I echoed text to file and checked it in different terminal), but I can't see anything, only cursor

<img width="223" alt="screen shot 2017-03-10 at 11 15 09" src="https://cloud.githubusercontent.com/assets/429225/23791341/d85b7b44-0582-11e7-843c-e653120d0638.png">

When I close all tabs and open new one, it again works fine. It didn't happen until I upgraded to 1.3.0

**Comment by henrikdahl** [comment]
Any output in console when this occurs?

**Comment by nwykes** [comment]
I'm seeing this as well.  No errors in console.  The terminal stops rendering.  Commands are still accepted and run.  For example `exit` will close the non rendering window.

**Comment by boobiq** [comment]
@henrikdahl I get this in console at the moment it happens

<img width="912" alt="screen shot 2017-03-13 at 08 49 15" src="https://cloud.githubusercontent.com/assets/429225/23845708/04247584-07ca-11e7-8b41-9b1902ec80f0.png">

I pretty printed bundle.js and it's happening here:

<img width="953" alt="screen shot 2017-03-13 at 08 49 41" src="https://cloud.githubusercontent.com/assets/429225/23845715/132d5654-07ca-11e7-870f-33696f5e1cf3.png">

**Comment by CarlosLlongo** [comment]
Hi, I'm having the same issue:
`Uncaught TypeError: Cannot match against 'undefined' or 'null'.`
To me it usually happens when I tipe `exit` in a split pane or in a tab. All other splits and tab will no longer render any content. If I open a new window, that one will work, but as soon as I exit in a tab or split in the new window, it wil also stop rendering.

OS: OS X El Capitan 10.11.6
Hyper: 1.3.1.1628
Config file: https://gist.github.com/CarlosLlongo/05e5fea0a7c361c4bb4a55e03dd8261d

**Comment by phillipchan2** [comment]
I'm getting similar error when opening a new tab. 

![screen shot 2017-03-17 at 3 59 49 pm](https://cloud.githubusercontent.com/assets/16655109/24065770/c8ae2a0e-0b2a-11e7-9216-3fa7164b5fd1.png)
![screen shot 2017-03-17 at 3 59 39 pm](https://cloud.githubusercontent.com/assets/16655109/24065769/c8adfea8-0b2a-11e7-9b52-602ac124a284.png)

**Comment by joaojusto** [comment]
Same thing for me on Hyper 1.3.1

Everytime I close a split or pane I get this error:

<img width="801" alt="screen shot 2017-03-18 at 13 09 22" src="https://cloud.githubusercontent.com/assets/4236592/24072267/57bbefcc-0bdc-11e7-9e0d-70214363540d.png">

Which on the minified bundle happens here:

<img width="800" alt="screen shot 2017-03-18 at 13 12 56" src="https://cloud.githubusercontent.com/assets/4236592/24072278/a8f206ba-0bdc-11e7-89eb-2d328f7b8d29.png">

**Comment by psimyn** [comment]
Had a quick look in debugger, got this so far:

The line that is erroring is [addSessionData](https://github.com/zeit/hyper/blob/master/lib/actions/sessions.js#L56) being called with 'logout'

The `exit` command triggers the action and then deletes the session immediately - https://github.com/zeit/hyper/blob/8ec362652c795e2cb03e5381ab66dba12ab939ae/app/index.js#L240

**Comment by phillipchan2** [comment]
I discovered that this was one of the plugins I was using that was causing this, not hyper itself. I just commented out each one and doing a hard refresh Cmd + Shift + R until the problem resolved.

**Comment by andrroy** [comment]
In my case, I have the same problem even without any plugins installed.

**Comment by andrroy** [comment]
@psimyn Did you do any more research on what causes the problem? If no one is actively working on this issue, I might take a swing at it. Right now, this issue is preventing me from using Hyper

**Comment by CarlosLlongo** [comment]
Hi @andrroy , I believe there is a pull request pending merge that would fix this issue:
https://github.com/zeit/hyper/pull/1698
It's pending a review to be merged. Maybe you can take a look at the fix and review it?

**Comment by andrroy** [comment]
@CarlosLlongo Awesome, I will have a look at it this weekend 🙂
