### ISSUE TITLE
Closing splitted view throws error sometimes

### ISSUE THREAD

**Issue by Nighthawk22** [zeit/hyper#1629]
- **OS version and name**: macOS Sierra 10.12.2
- **Hyper.app version**: 1.3.0.1614
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Nighthawk22/8fe19bd6aeaa4e000f7fdc0b64e09686
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
<img width="800" alt="screenshot at marz 10 11-21-21" src="https://cloud.githubusercontent.com/assets/11962722/23791559/b8bb6082-0583-11e7-84d8-fb7c575942d7.png">

## Issue
I alway open a new splitted view with `CMD + d` and close it with `ctrl + d`. In some cases the console throws the error above on *closing* the view and afterwards hyper does not load a new shell even when closing and opening a new splitted view.

Sadly I did not find an exact way when this happens but its annoying. 
![marz-10-2017 11-27-43](https://cloud.githubusercontent.com/assets/11962722/23791802/b9243b6a-0584-11e7-8aac-3ceefd90ce5b.gif)

**Comment by timja-kainos** [comment]
This is happening to me as well. Except it happens on every split I try and open
The only changes to my hyper config are the cursor and the solarized-dark them.

My hyper version is `1.3.1 (1.3.1.1628)`

**Comment by CarlosLlongo** [comment]
I'm having the same issue. I believe this is the same as #1628

**Comment by Nighthawk22** [comment]
Yes seems very similar.

**Comment by timja-kainos** [comment]
I can confirm when pretty print the error happens on the same line as in the other issue

**Comment by Nighthawk22** [comment]
I close this issue because of duplication
