### ISSUE TITLE
Doesn't render prompt with powerline fonts (Meslo LG) correctly on 1.3.0

### ISSUE THREAD

**Issue by boobiq** [zeit/hyper#1630]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.3
- **Hyper.app version**: 1.3.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/boobiq/ca066b41e0a915d80c783c18b41e4ad3
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: only when using Powerline prompt and font (at least "Meslo LG S for Powerline")

## Issue
Since upgrading to 1.3.0, shell prompt (I'm using fish shell) with powerline fonts doesn't render correctly, it works fine on 1.2.1

1.2.1 (correct)
<img width="85" alt="screen shot 2017-03-10 at 11 26 58" src="https://cloud.githubusercontent.com/assets/429225/23791887/11fceb9c-0585-11e7-8ad3-542ab0d9b669.png">

1.3.0 (wrong)
<img width="87" alt="screen shot 2017-03-10 at 11 27 04" src="https://cloud.githubusercontent.com/assets/429225/23791898/1939968a-0585-11e7-842d-2465fa793c54.png">

**Comment by iovis9** [comment]
Same OS and version as @boobiq, but with Fira Code:
![screen shot 2017-03-10 at 13 22 25](https://cloud.githubusercontent.com/assets/6660202/23795236/befc6994-0594-11e7-9450-a527c0e63fe4.png)

**Comment by nwykes** [comment]
I had this problem as well after upgrading to 1.3.0.

Adding a line height resolved it for me.

```
termCSS: 'x-row > span { line-height: 1.2em; }',      
```

**Comment by cdhunt** [comment]
Likewise on Windows 10 build 1607 with Fira. And the line-height css via @nwykes resolved it for me as well.

**Comment by matheuss** [comment]
Thanks for reporting guys! https://github.com/zeit/hyper/commit/237595cec83f1d3796e1f625bd8ca97a1cd1d443

cc @rauchg

**Comment by samuelhorwitz** [comment]
I'm seeing this also (but I'm using ZSH). I'm on 1.3.1. I disabled all plugins.

![screen shot 2017-03-10 at 5 45 00 pm](https://cloud.githubusercontent.com/assets/1251501/23816179/6744d34c-05b9-11e7-9ce0-de55548a1154.png)

**Comment by boobiq** [comment]
yeah, it still persists even in 1.3.1 for me as well

**Comment by flxw** [comment]
Same here, my issue transformed itself :)

**Comment by cdhunt** [comment]
I changed my line height to 1.25em to clean it up.
