### ISSUE TITLE
3/8/2017 Update freeze tmux clipboard

### ISSUE THREAD

**Issue by nikisix** [zeit/hyper#1632]
- **OS version and name**: OSX 10.11.5 (15F34)
- **Hyper.app version**: Version 1.3.0 (1.3.0.1614)

3/8/2017 Update causes hyper to freeze after using tmux to copy some text to the clipboard. The tmux session itself does not freeze. I can log into the session from another terminal, but it does cause hyper to freeze.
Thanks for an awesome new terminal!

**Comment by x** [comment]
I'm seeing this as well. It seems to raise the following in the developer console
```
Uncaught TypeError: Failed to execute 'extend' on 'Selection': parameter 1 is not of type 'Node'.
```

**Comment by x** [comment]
I tried to dig in with the uncompiled version, but this is a little outside my expertise. Here's the stack trace I'm getting.
```
index.js?bb83:13177 Uncaught TypeError: Failed to execute 'extend' on 'Selection': parameter 1 is not of type 'Node'.
hterm.Terminal.copyStringToClipboard                                  @ index.js?bb83:13177
hterm.VT.OSC.(anonymous function)                                     @ index.js?bb83:15805
hterm.VT.dispatch                                                     @ index.js?bb83:14851
parseOSC                                                              @ index.js?bb83:15426
hterm.VT.interpret                                                    @ index.js?bb83:14610
hterm.Terminal.interpret                                              @ index.js?bb83:11699
__WEBPACK_IMPORTED_MODULE_2_runes___default.forEach.rune              @ hterm.js?8d14:148
__WEBPACK_IMPORTED_MODULE_1_hterm_umdjs__.hterm.Terminal.IO.writeUTF8 @ hterm.js?8d14:146
write                                                                 @ term.js?9937:183
action                                                                @ write-middleware.js?63c9:11
action                                                                @ effects.js?3a42:11
action                                                                @ plugins.js?f831:381
effect                                                                @ sessions.js?9e58:66
action                                                                @ effects.js?3a42:13
action                                                                @ plugins.js?f831:381
(anonymous function)                                                  @ sessions.js?9e58:52
requestAnimationFrame                                                 @ index.js?fdfc:87
```

To reproduce. I think this is the tmux command that's triggering the issue https://github.com/x/.dotfiles/blob/master/tmux.conf#L41

The same thing happens when I try instead,
```
bind-key -t vi-copy 'y' copy-pipe "pbcopy"
``` 

As far as I can tell, when `copyStringToClipboard` gets called in hterm, `anchorNode` and `focusNode` seem to be `null`.

**Comment by nwbt** [comment]
Hyper Version: 1.3.1 (1.3.1.1628)
OS: macOS Sierra (10.12.3)

Same errors as above (in devtools): `Uncaught TypeError: Failed to execute 'extend' on 'Selection': parameter 1 is not of type 'Node'. bundle.js:47`

![screen shot 2017-03-19 at 11 00 10 am](https://cloud.githubusercontent.com/assets/1912365/24082925/402049d2-0c93-11e7-917a-d7ed7ca2a328.png)

**Comment by eloop** [comment]
Hyper Version: 1.3.1 (1.3.1.1628)
OS: macOS Sierra (10.12.3)

I see the same issue running emacs and trying to C-w (kill-region).
![screen shot 2017-04-19 at 10 51 13 am](https://cloud.githubusercontent.com/assets/16974/25158771/43ec5e2a-24ee-11e7-947b-263593affdd7.png)

**Comment by jrhorn424** [comment]
I'm seeing this issue as well. AFAIK, I'm still using the `reattach-to-user-namespace` hack for tmux on macOS.

- macOS 10.12.4 (16E195)
- Hyper Version 1.3.1 (1.3.1.1628)

**Comment by x** [comment]
Still seeing this on the latest build

- OSX 10.12.3
- Hyper Version 1.3.2

**Comment by jkzing** [comment]
It seems this still happen on latest version
* macOS 10.12.1
* Hyper Version 1.3.3 (1.3.3.1754)

Is there anything I can do to help solve this issue? This really stops me from using hyper. 😭

**Comment by ppot** [comment]
Should be better once we switch to Xterm. Insted of monkey patching hterm

**Comment by eloop** [comment]
And this is still present for Hyper version 1.4.2 stable, OSX 10.12.6.

**Comment by DuIslingr** [comment]
@ppot Whats the estimated timeframe on switching to xterm?

**Comment by ppot** [comment]
Next big release I should say. We have a branch opened currently.

**Comment by eloop** [comment]
Still an issue for 1.4.4.
