### ISSUE TITLE
chocolately points at version 1.1.0 instead of 1.3.1

### ISSUE THREAD

**Issue by lukeapage** [zeit/hyper#1634]
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue
Chocolately points at 1.1.0 instead of 1.3.1. The readme/website could alternately point at the github releases instead of chocolately.

See also https://github.com/zeit/hyper/pull/1631

**Comment by air** [comment]
Looks like they're held up in the choco system? https://chocolatey.org/packages/hyper#versionhistory

**Comment by fallmake** [comment]
Yeah, 1.3.1 awaits moderation. Clone + local build an option for you?

**Comment by air** [comment]
The direct download option linked on hyper.is is fine, no build needed.

**Comment by MartyGentillon** [comment]
This is resolved.  The current chocolatey package is version 1.3.1.

**Comment by chabou** [comment]
Thank you
