### ISSUE TITLE
hyper is spelled hyperr on the .deb release of 1.3.1? 

### ISSUE THREAD

**Issue by jmfgdev** [zeit/hyper#1635]
Not an issue with the program but hyper is misspelled on the deb release, even the file is named "hyperr_1.3.1.deb". I'm assuming this is a mistake. It seems like no one checks the files that are going to be released as the latest? It would be good to have at least 1 other person check the release. I think @matheuss made the commit with the typo.

**Comment by matheuss** [comment]
> It seems like no one checks the files that are going to be released as the latest

Wrong, I rename them manually due to an issue with our release flow.

Fixed, thanks for pointing it out
