### ISSUE TITLE
https://github.com/zeit/hyper/releases/download/1.3.1/hyper-1.3.0-x86_64-linux.AppImage throws a 404

### ISSUE THREAD

**Issue by jmfgdev** [zeit/hyper#1636]
If one goes to download hyper 1.3.1's app image .AppImage, they won't be able to for the time being since it redirects to a  github 404.

https://hyper.is/#installation
Check the download for .AppImage it should be a 404 for you aswell.

The only developer I know of to @ is @matheuss 
I don't use .AppImage but some people might need that file.

**Comment by leo** [comment]
Closed with https://github.com/zeit/hyper/pull/1679

**Comment by jmfgdev** [comment]
This is actually still happening and the issue hasn't been fixed yet @leo I can't download the app image

**Comment by leo** [comment]
We'll add this soon!

https://hyper-latest.now.sh/
