### ISSUE TITLE
Launching Hyper from Spotlight causes default shell setting to be ignored

### ISSUE THREAD

**Issue by jd20** [zeit/hyper#1637]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **macOS Sierra 10.12.3**: 
- **1.3.1**: 
- **https://gist.github.com/jd20/0d4fd28e7df69f830fa7fa378a434c8b.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **Yes**: 

## Issue
I've changed my default shell using chsh to Homebrew-installed zsh, which is added to /etc/shells (as `/usr/local/bin/zsh`). However, when launching Hyper from Spotlight, I've noticed my shell reverts to bash. Launching Hyper from the Dock, I get ZSH like I'd expect. I don't notice this behavior with Terminal.app (launching from dock or Spotlight, I get ZSH as my default shell).

**Comment by tbremer** [comment]
I came to file the same issue. Shell only changes after logout.

With Terminal and iTerm2 the shell changes on the next instance (new Tab or new Window).

I never tried launching from the Dock, mainly because it's out of sight, out of mind.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
