### ISSUE TITLE
Using "Segoe UI Light" as font displays the cursor wrongly

### ISSUE THREAD

**Issue by ismaelestalayo** [zeit/hyper#1639]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10 1607 14393.693 (not running in fast or slow ring)
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [link](https://gist.github.com/ismaelestalayo/40aa32bd371655bcacebc22fa30993d0)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is vanila

## Issue

When using Segoe UI Light as the main Font for Hyper, the cursor is displayed in the wrong location, so for example when I open Hyper and type 'a' for example, i see this (being _ the cursor):

$ a                    _

For now i'll just use monospace Font, if anyone has a suggestion for the best Font for Hyper in Windows, i'd appreciate it.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
