### ISSUE TITLE
Paste not working if backspace hit in cursor home position

### ISSUE THREAD

**Issue by fallmake** [zeit/hyper#1641]
1. Put cursor in home position on commandline
2. Hit backspace
3. Paste doesn't work anymore before leaving cursor home position (e.g. by entering something).

checked with default shell (cmd) and powershell.exe, same behavior

Hyper a35f39f
Electron 1.4.15
win32 x64 10.0.14393

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
