### ISSUE TITLE
Problem initializing fish shell on Ubuntu 16.04

### ISSUE THREAD

**Issue by emredjan** [zeit/hyper#1645]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/emredjan/9d9dc9723cef12e08ce6fa01d44dfe17
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Issue reproducible with or without addons.

## Issue
When configured to use the 'fish' shell (`shell: '/usr/bin/fish',` in config), hyper 1.3.1 (and 1.3.0) shows a blank screen which does not respond to typing commands, seemingly cannot initialize the shell. If I switch back to 'bash' (`shell: '/bin/bash',`), everything's alright, I can even run fish from bash and no problems.

Fish was working prior to 1.3.0 (1.2.1 to be exact).

![image](https://cloud.githubusercontent.com/assets/389091/23833194/8c0c6502-0742-11e7-9db0-ed7167a5b26a.png)

**Comment by Zx-EvM** [comment]
Try `chsh -s /usr/bin/fish` and continue to use `shell: '/bin/bash',`

**Comment by emredjan** [comment]
@Zx-EvM changing the login shell works, thanks.
But that still doesn't explain why hyper can't initialize a different shell (since version 1.3.0)

**Comment by tamagokun** [comment]
Similarly, I have used `chsh` to switch to `zsh` and set `shell` in `hyper.js` to `zsh`, but yet whenever I open up Hyper, it still defaults to bash.

**Comment by meffect** [comment]
can you change to fish shell manually via bash prompt?

**Comment by emredjan** [comment]
@meffect yes I can. only problem is initializing fish on hyper startup

**Comment by Nighthawk22** [comment]
@emredjan Does the console show any error? Looks very similar to  #1628

**Comment by emredjan** [comment]
@Nighthawk22 it looks like it, but not quite same. Here are the errors I get:

![image](https://cloud.githubusercontent.com/assets/389091/24080756/75958b7e-0ca5-11e7-96b6-e535f42ab218.png)

![image](https://cloud.githubusercontent.com/assets/389091/24080744/4bd7b5e6-0ca5-11e7-8f56-b45ce486a1f0.png)

**Comment by towicode** [comment]
just btw I'm having the same issue.

**Comment by junghyuneun** [comment]
I have the same issue, I think it has to do with how both fish and hyper tries to set the foreground / background color and depending on which one gets to set it first it either loads or doesn't load.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
