### ISSUE TITLE
Double click on title bar doesn't resize the window

### ISSUE THREAD

**Issue by alejandrofloresm** [zeit/hyper#1646]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS Sierra (10.12.3)
- **Hyper.app version**: Version 1.3.1 (1.3.1.1628)

## Issue
The problem is when double clicking on the title bar of the app the window doesn't resize (maximize or return to previous size), this behaviour is normal on Mac OS apps.

**Comment by cg-cnu** [comment]
Tested on centos 7 KDE and its working fine; 
Could be a mac specific issue.

**Comment by lukeapage** [comment]
It does not work for me on windows...

**Comment by albinekb** [comment]
I think this might broke when @matheuss introduced the hamburger/when we made hyper work on other platforms than macOS, shouldn't be that hard to fix :)
