### ISSUE TITLE
Copy on select

### ISSUE THREAD

**Issue by przemyslawpluta** [zeit/hyper#1647]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS 10.11.4**: 
- **Hyper 1.3.1**: 

More like a future request but it would be good to add an option so that text is automatically copied if selected.

**Comment by iamstarkov** [comment]
https://hyper.is/#cfg

![screen shot 2017-03-13 at 12 57 08](https://cloud.githubusercontent.com/assets/559321/23853380/9610851a-07ec-11e7-9de1-f41e48c1cf6e.png)

**Comment by albinekb** [comment]
Closing this as the functionality you're looking for is already implemented, if you're looking for something else, please re-open 🎉  @przemyslawpluta
