### ISSUE TITLE
support older macOS versions

### ISSUE THREAD

**Issue by 1-61803** [zeit/hyper#1650]
Since it's html/js/css based, I wanted to give it a run, but it's targeted for `10.9`. I'm on 10.8 and changing the minimum OS version in the `Info.plist` allows it to launch but it cannot open new windows nor do anything useful in the application.
Please, since it's a terminal built on web technologies target the lowest possible OS version, or provide some hints to compile it.

**Comment by albinekb** [comment]
I think we use several things that's only supported in electron that's targeted on newer OS.

Curious question: Why don't you upgrade to latest macOS?

**Comment by 1-61803** [comment]
Could you double-check if those things aren't supported in `electron` targeting, say `10.8` or `10.6`?

As for your question re not upgrading: I use OS X for usability. This and the overall quality of the OS declined since `10.9` — I downgraded from `10.9`, tried recently `10.12` in a vm: awful. There's a clear break between cat series and location series, between a still-then somewhat niche product and business for the masses. For security, I have a tinfoil hat and some savvy helps too.

I wouldn't be amazed if `hyper` compiles for `XP` but cannot for `10.8`.

**Comment by matheuss** [comment]
@1-61803 Chrome only supports 10.9 and later – nothing we can do about it 👌

**Comment by 1-61803** [comment]
@matheuss, how does Chrome fit in this equation?

**Comment by matheuss** [comment]
@1-61803 Electron is based on Chrome

**Comment by 1-61803** [comment]
@matheuss, oh yeah, *googled* Chromium, "open-source"…good riddance
