### ISSUE TITLE
Lost context menu option after update

### ISSUE THREAD

**Issue by aulneau** [zeit/hyper#1651]
- **OS version and name**: Windows 10 64-bit
- **Hyper.app version**: 1.3.1

Hey there!

Love the work you all do. Just wanted to give you a heads up that when I updated through the notification in Hyper, I lost my context menu functionality. (Open Hyper here no longer works)

![hyper-context](https://cloud.githubusercontent.com/assets/11803153/23867639/3156fc3a-07e2-11e7-8d37-95510bb724da.PNG)

Thanks!

-a

**Comment by ChiefORZ** [comment]
Yah, defenenitely a bug. i always have to re-add the Registry Entry `REG_SZ="C:\Users\%username%\AppData\Local\hyper\app-1.3.1\Hyper.exe" "%V"` at `\HKEY_CLASSES_ROOT\Directory\Background\shell\`

**Comment by chabou** [comment]
Fixed by #1831
