### ISSUE TITLE
macOS 10.10.5 vim navigation with hjkl keys is slow

### ISSUE THREAD

**Issue by curioussavage** [zeit/hyper#1653]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.10.5
- **Hyper.app version**: v1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: using default (oops, I did clearly have a theme)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  NA
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

I have noticed that on macOS only when using the HJKL keys to navigate around a file there is a noticeable delay every time you press a key to move. Even when holding down the key its very jumpy. 

I think this gif should show it clearly, first I navigate with hjkl then with the arrow keys.

![vim slow hjkl](https://cloud.githubusercontent.com/assets/7064600/23873683/19ee684a-07f0-11e7-88d0-6a665f573fc1.gif)
 
edit: It looks like this affects other software in the terminal when scrolling with those keys. eg. tmux scrolling through history.

**Comment by iamstarkov** [comment]
> edit: It looks like this affects other terminal apps when scrolling with those keys. eg. tmux scrolling through history.

do you mean this behaviour is not unique to hyper?

**Comment by curioussavage** [comment]
@iamstarkov  no, just not unique to vim in hyper.

**Comment by andrepolischuk** [comment]
@curioussavage you can disable macOS press-and-hold:

```sh
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
```

It's help for me.

**Comment by roolebo** [comment]
#1137 could be related

**Comment by curioussavage** [comment]
Can confirm #1137 is the same. Closing my issue as duplicate.
