### ISSUE TITLE
Not showing scroll bar 

### ISSUE THREAD

**Issue by ansarirahilJP** [zeit/hyper#1654]
Whenever i need to check previous data on console i could not find scroll bar to scroll up I'm using hyper on Windows 8.1 64bit 

Hyper 1.2.1
Electron 1.4.7
win32 x64 6.2.9200

**Comment by cg-cnu** [comment]
@ansarirahilJP Its working fine on centos 7 with hyper 1.3.1.
Can you try the latest release?

**Comment by MartyGentillon** [comment]
This is a duplicate of https://github.com/zeit/hyper/issues/1540

**Comment by ppot** [comment]
Closing for #1540
