### ISSUE TITLE
Block select using ctrl + alt

### ISSUE THREAD

**Issue by cg-cnu** [zeit/hyper#1655]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: CentOS Linux release 7.1.1503 (Core) 
- **Hyper.app version**: 1.3.1
## Issue
Feature request:
Holding down the ```Ctrl+Alt``` while dragging the left mouse button should select block of text. 
![blockselect](https://cloud.githubusercontent.com/assets/2767425/23898159/00849b86-08d6-11e7-9ac9-859c7080be98.png)

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2697
