### ISSUE TITLE
Resizing the window cause some prints to disappear

### ISSUE THREAD

**Issue by PowerSnail** [zeit/hyper#1657]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10, Insider Build 15055 (running BashOnWindows)
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/PowerSnail/1c557ad36e536fc318252f5009c42750

## Issue

After running some color test scripts (like [this](https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh)), resizing the window will cause the printed color bars to disappear. More precisely, this happens when the resulting column number is less than the length of color bars. 

Thanks!

**Comment by jdsimcoe** [comment]
Mine does this as well.

**Comment by dcalhoun** [comment]
This is likely captured by #476, correct? If so, this issue should likely be closed.
