### ISSUE TITLE
Plans to Support True Command + A + Command C Workflow?

### ISSUE THREAD

**Issue by bobber205** [zeit/hyper#1658]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MAC OS Latest
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/bobber205/0dc98345dbc2b28e417d5e650952a3ba
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
First I wanna say I am generally enjoying. 
For some reason when I wanna copy all of my terminal output, I am used to every other terminal app I've used supporting Command A to select ALL text then Command C to copy.

Hyper.js only copies what's visible, making it basically impossible to copy all of my terminal output into a gist or another editor (usually for formatting).

Please tell this is coming soon!

**Comment by ppot** [comment]
@bobber205 Can you give an example as a gif? On my macOS this is working fine.

**Comment by albinekb** [comment]
On macOS you can use `cat file.js | pbcopy` to copy the contets of file.js to clipboard, but this issue should still be fixed anyway :smie
