### ISSUE TITLE
Command+F Support

### ISSUE THREAD

**Issue by bobber205** [zeit/hyper#1659]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MAC OS Latest
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/bobber205/0dc98345dbc2b28e417d5e650952a3ba
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Will Hyper.js soon support searching the terminal output?
Command+F does nothing. :(

**Comment by ppot** [comment]
Closing in favor of #140
