### ISSUE TITLE
Resizing terminal does not fill previously-run content

### ISSUE THREAD

**Issue by spetri** [zeit/hyper#1660]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **MacOS, latest version**
- **Version 1.3.1 (1.3.1.1628)**

## Issue
When resizing the terminal, the previously-run content does not fill in the space until new commands are issued. Often times, it's nice to be able to expand the terminal to have better readability over what was just run, but in hyper's case, I'd need to resize the browser, then rerun it.

**Comment by ppot** [comment]
closing for #476
