### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by haoyangnz** [zeit/hyper#1661]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 14.04
- **Hyper.app version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/haoyangnz/86ccf05681a143876e3bdadfb4fb8172
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I see a red message on the bottom right saying Version 1.3.1 is availble. I want to upgrade my hyper.js to 1.3.1. I'm wondering how to upgrade it (other than reinstalling it). I see in #1624 that hyper.js can auto upgrade itself. I can't figure out how to let it auto upgrade.

**Comment by jmfgdev** [comment]
@haoyangnz Ubuntu supports .deb files, thats the current best method AFAIK. Yes there has been suggestions that it can auto update, but I've never been able to. Why is this closed may I ask?

**Comment by haoyangnz** [comment]
@jmfgdev #1624 was closed because the issue didn't have the checklist.

**Comment by mojoaxel** [comment]
> I can't figure out how to let it auto upgrade.

Maybe we need a new issue for "Auto update"!?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by mojoaxel** [comment]
BTW, I wrote a little update tool for linux, that downloads the newest .deb and installs it:

https://gist.github.com/mojoaxel/4fa8947905472818a72a97c113b535ae
