### ISSUE TITLE
'clear screen' removes content of the screen from the history

### ISSUE THREAD

**Issue by cg-cnu** [zeit/hyper#1662]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: CentOS Linux release 7.1.1503 (Core)
- **Hyper.app version**: 1.3.1

## Issue
```clear``` and   ```ctrl + L``` along with clearing screen removes the contents of screen from the history. 
Scrolling up shows only the old history.

**Comment by rauchg** [comment]
Good catch! I really want to fix this

**Comment by jakeheis** [comment]
As a temporary/partial hack I've found that `alias clear="for i in {1..$(tput lines)}; do echo; done; clear;"` helps, though View -> Clear still loses the screen content

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
