### ISSUE TITLE
Update electron to fix High-DPI/Low-DPI blurryness issues

### ISSUE THREAD

**Issue by JohannesRudolph** [zeit/hyper#1664]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Win 10
- **Hyper.app version**: 1.3.1
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
Hyper currently makes use of electron v1.4.15 which, due to an old version of Chromium, has problems moving from hi-dpi to low-dpi monitors on windows and vice-versa. 

Upgrading to electron 1.5 or 1.5/1.6 will fix this issue as they are based on Chromium v55/v56. Many other electron-based Apps have similar issues: https://github.com/Microsoft/vscode/issues/1896#issuecomment-282662942

**Comment by chabou** [comment]
PR welcome :)

**Comment by Stanzilla** [comment]
Can be closed

**Comment by albinekb** [comment]
We're running latest electron now 👌

**Comment by JohannesRudolph** [comment]
I switched back to hyper 2 today and am totally delighted this is fixed now. Great job, thank you!!!
