### ISSUE TITLE
question: Event emitter/listener for change in active session?

### ISSUE THREAD

**Issue by jxom** [zeit/hyper#1666]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

Hello,

I was just wondering if there was any way to listen for changes in active session? There are events for 'session add', 'session data', 'session exit', etc. But is there anything like 'session set active'? Or is this functionality not yet implemented?

Thanks!

**Comment by ppot** [comment]
@jxom Yes, you can listen in your middleware for `SESSION_SET_ACTIVE` see https://github.com/zeit/hyper/blob/master/lib/actions/sessions.js#L101

**Comment by jxom** [comment]
Sorry about the late reply. Yes that's true, but I'm not able to access `window.rpc` (as I want to emit an event to the app) within `middleware`... Thought's on how I'd overcome this?

**Comment by chabou** [comment]
RCP Event or a Redux action ?
For a Redux action you can use `store.dispatch()` in middleware

**Comment by jxom** [comment]
An RPC event :) My end goal is to emit an event to the main electron app (which is not React...) every time a session becomes active.

**Comment by jxom** [comment]
Yeah, I get that. However, my end goal is to keep track of the window uid within the `onWindow` method. From my understanding `middleware` is in the scope of the renderer, whereas `onWindow` is in the scope of the electron app, meaning that I cannot access variables to and from those methods. Here is an example:

```javascript
let currentUid;

exports.onWindow = (win) => {
  ...
  win.setSomething(new SomeObject({
    click: () => {
      console.log(currentUid);
    }
  }));
  ...
}

exports.middleware = store => next => (action) => {
  switch (action.type) {
    case 'SESSION_SET_ACTIVE': {
      currentUid = action.uid; 
    }
  }
  return next(action);
};
```  

The only way I can think of solving this would be through something like a `session set active` event (which does not exist). Which I can then utilise in my `onRendererWindow` method:

```javascript
exports.onRendererWindow = win => {
   win.rpc.on('session add', ({uid}) => {
      win.rpc.emit('set uid', uid);
   });
};
```

Correct, or am I misunderstanding something?

**Comment by chabou** [comment]
In you case, I think you can can get focused electron window in middleware with something like :
```javascript
const { BrowserWindow } = require('electron');

exports.middleware = store => next => (action) => {
  const win = BrowserWindow.getFocusedWindow();
  win.rpc.emit(...);
};

**Comment by jxom** [comment]
Just tried that possible solution within my `middleware` method, however, I'm getting the error:
```javascript
Cannot read property 'getFocusedWindow' of undefined
```

Although, if I put it in my `onWindow` method. `BrowserWindow` seems to be defined...

**Comment by chabou** [comment]
Ok normal: middleware is in the Renderer.
Maybe like this ?
```javascript
const { BrowserWindow } = require('electron').remote;

exports.middleware = store => next => (action) => {
  const win = BrowserWindow.getCurrentWindow();
  win.rpc.emit(...);
};
```

**Comment by jxom** [comment]
The above solution didn't work for me either. Even though `win.rpc` was defined, the event wasn't being caught in my main process. Though, I did find a solution - I can use the `window` global variable (didn't know it was global!) within my renderer process to then emit the event (`window.rpc.emit(...)`).
