### ISSUE TITLE
Windows 10 context menu Open Hyper here remains after uninstalling

### ISSUE THREAD

**Issue by laur1s** [zeit/hyper#1668]
extremely annoying, how can I fix that?
Windows 10 x64

**Comment by albinekb** [comment]
Here's a guide to do that: http://www.thewindowsclub.com/remove-click-context-menu-items-editors

@laur1s 

We should make hyper clean that up on uninstall, I'm not too into the windows side of hyper/electron, but feels like it should be supported.

**Comment by laur1s** [comment]
The uninstall leaves so many things, that should be definitely removed. I had to remove config files, plugins, etc., manually. Furthermore, context menu did not reset after reinstallation, and  I still can't open hyper from it. I guess I'll have to use regedit for fixing that

**Comment by chabou** [comment]
Fixed by #1831
