### ISSUE TITLE
Customizing my prompt?

### ISSUE THREAD

**Issue by istx25** [zeit/hyper#1669]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version.
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS Sierra Version 10.12.3 (16D32)
- **Hyper.app version**: Version 1.3.1 (1.3.1.1628)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/istx25/c85c6e49b21dcf24219963bda0614df2
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: I think so?

## Issue

Hi there,

I'm new to customizing my terminal (by myself/without someone just doing it for me) and I was wondering if someone could explain how I can change the "prompt" (though that may not be the correct terminology).

I would like to change:

```
Willows-MacBook-Pro:Desktop graysen$ 
```

to just say:

```
graysen ~/Desktop $ 
```

![screen shot 2017-03-15 at 12 59 19 pm](https://cloud.githubusercontent.com/assets/6799989/23960766/384a4b48-097f-11e7-97a0-a6651f287966.png)

Thanks in advance.

**Comment by ppot** [comment]
You need to update your PS1

**Comment by iamstarkov** [comment]
thats nothing have to do with Hyper

**Comment by matheuss** [comment]
@istx25 please google about `customize PS1 bash` 👌

**Comment by istx25** [comment]
I didn't know that, @iamstarkov. Thanks @ppot and @matheuss. I'll do that.

**Comment by iamstarkov** [comment]
@istx25 thats fine. sorry for being harsh a bit, didnt mean that, was in a hurry. sorry again

**Comment by istx25** [comment]
@iamstarkov alright. i'm brand new to this kind of customization so that's why I didn't know. happy that I got an answer quickly though. :) got the results I was after:

![screen shot 2017-03-15 at 8 23 06 pm](https://cloud.githubusercontent.com/assets/6799989/23976348/6a189fd8-09bd-11e7-9450-32585aa0e2ec.png)
