### ISSUE TITLE
Issue after using Hyper for Windows with dual monitor

### ISSUE THREAD

**Issue by joselitojunior1** [zeit/hyper#1672]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/joselitojunior1/98ad91410f1f6d318f6c2f19a1e6d0bc
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
When you open Hyper on a secondary monitor, and then unplug it, the Hyper windows "stays on" the "secondary monitor". If I don't move it back to the main monitor, I can't access the Hyper Window

### Steps to reproduce:
- Connect an external monitor
- Open Hyper
- Move Hyper Window to the external monitor
- Close Hyper
- Unplug the external monitor
- Try to open Hyper again
- Hyper opens, but on the "external monitor" position, inaccessible.

**Comment by ppot** [comment]
Closing for #1608
