### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by aryzing** [zeit/hyper#1673]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04 LTS
- **Hyper.app version**: Hyper 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/aryzing/33f081d92d13cfa82e0c0b52bda54d13
- **Relevant information from devtools** `Uncaught TypeError: Cannot match against 'undefined' or 'null'.`
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
On ocasion, when splitting resplitting (with Ctrl-E or Ctrl-O) and then closing one of the recently opened terminals (with Ctrl-D) the whole app will become unresponsive to any keystrokes. The message error reported by the dev tools is

```
Uncaught TypeError: Cannot match against 'undefined' or 'null'.
```

Let me know if I can provide additional details to pin down the issue.

**Comment by Nighthawk22** [comment]
Same issue as #1629 and #1628

**Comment by aryzing** [comment]
Closing due to duplicate.
