### ISSUE TITLE
Window Decorations OS Default

### ISSUE THREAD

**Issue by ASAPHAANING** [zeit/hyper#1675]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 16.04**: 
- **1.3.1**: 
- **Default config**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Is it possible to force Hyper to use OS default window panel / window decorations?

**Comment by alberto2000** [comment]
This might be similar to https://github.com/zeit/hyper/issues/1683

**Comment by ASAPHAANING** [comment]
It certainly is. Closing this thank you alberto.

**Comment by alberto2000** [comment]
@ASAPHAANING I'm thinking of writing a plugin for this would you be interested in contributing? See the other issue https://github.com/zeit/hyper/issues/1683 where I got the native window title bar and frame to work. But now I want to remove the "header" from hyper and move its content which is the working directory or running app name into the native title bar

**Comment by ASAPHAANING** [comment]
@alberto2000 I would for sure contribute :)

**Comment by alberto2000** [comment]
@ASAPHAANING cool :) let's communicate via email then, ping me at hello@riccardolardi.com

**Comment by a-eid** [comment]
any chances that you're finished with that plugin?

**Comment by alberto2000** [comment]
@a-eid sadly no, I was completely suck in by work so had to freeze this project for the moment
@ASAPHAANING I'm so sorry we couldn't meet in CPH! Let's try another time :)
