### ISSUE TITLE
Window freezes when displaying lengthy output from commands

### ISSUE THREAD

**Issue by geoffrepoli** [zeit/hyper#1681]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.3 (16D32)
- **Hyper.app version**: 1.3.1.1628
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/geoffrepoli/a6a1454e39bf825b5692ed7fe4745182)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Sometimes I've seen `Uncaught TypeError: Cannot read property 'wcNode' of undefined` and other times the window is entirely locked up and there's no relevant Console messages.
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Since about the past week or so I've noticed certain large blocks of text will cause my active window to completely freeze. For example, returning the output of the command `dscl . read /users/<username>` will always cause the window to lock up.

Sometimes it'll look like this, where the cursor will still be blinking, I can still scroll, I can close the window, I cannot interact with the shell (e.g., `ctrl`+`c` is not being recognized:
![terminal window](https://i.imgur.com/2MekMXH.png)
![devtools with warning](https://i.imgur.com/N06KAHs.png)

Other times the window will completely lock up, and I am unable to interact with it whatsoever. In these cases, the devtools console does not show any errors:
![devtools no warning](https://i.imgur.com/JcMcc2F.png)

I've tried with the default .hyper.js, launched without my .bash_profile, to same effect. This issue does not occur in Terminal.app.

**Comment by geoffrepoli** [comment]
Kept the frozen window open for a few minutes. Eventually the rest of the output printed.

`Handling of 'mousewheel' input event was delayed for 77385 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.`
`Handling of 'wheel' input event was delayed for 77386 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.`

![devtools main thread](https://i.imgur.com/q5fpw48.png)

**Comment by geoffrepoli** [comment]
Can likely merge this with [#687](https://github.com/zeit/hyper/issues/687). Seems to be a scrollback buffer issue. This issue did not exist for me prior to version 1.3.

**Comment by alexh** [comment]
Still having this issue

**Comment by DickyT** [comment]
Still having this issue. Terminal frozen when trying to extract tons of files from a tarball

**Comment by octalmage** [comment]
@DickyT I'm on canary v2.1 and running "seq 10000000" freezes my term. and it takes a while to recover.
