### ISSUE TITLE
How to show native title bar and close icon on Arch Linux / Gnome?

### ISSUE THREAD

**Issue by alberto2000** [zeit/hyper#1683]
I guess most people wanted the contrary / to hide the title bar - now I'm asking if it's possible to have an option to let electron show the native window title bar. Is it possible? Thanks

This might be similar to https://github.com/zeit/hyper/issues/1675

**Comment by alberto2000** [comment]
I figured if switching the browserDefaults frame value to true also for linux process platform, the windows will have the native frame and therefore title bar and menu. Now I'd like to move the working directory title from where it is originally to the native title bar title - so the window has the same, native configuration as any other linux app in my desktop environment, see screenshots comparing my current hyper build to gnome terminal:

![My current hyper build](http://i.imgur.com/RtDV4Mw.png)

![Gnome terminal](http://i.imgur.com/3v9Vld2.png)

**Comment by a-eid** [comment]
how did you get the default os decorations to work?

**Comment by jcrben** [comment]
If you're on Linux and you don't have the native title menu, then you may not be able to get to the menu at all. You need to enable `showHamburgerMenu` - discussed at https://github.com/zeit/hyper/issues/1266.

**Comment by Stanzilla** [comment]
Here you go https://www.npmjs.com/package/hyper-native-window-decoration
