### ISSUE TITLE
404 for Linux download from button at https://hyper.is/ even though website/index.html is correct

### ISSUE THREAD

**Issue by colinkeenan** [zeit/hyper#1685]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

None of the above is relevant to this issue because I haven't installed it yet. That's the issue. Your download link for Linux is still wrong on the actual website. It goes to https://github.com/zeit/hyper/releases/download/1.2.0/hyper-1.3.1-x86_64-linux.AppImage which is a 404 error. If I copy and paste the download location from line 605 of website/index.html that you updated 2 days ago, the download works perfectly. Nobody will do that though, of course. The purpose of the link is so that people knowing nothing about github can download the package from your static website.

**Comment by gathrlabs** [comment]
Here's the currently working link until the website/index.html is amended: 
[https://github.com/zeit/hyper/releases/download/1.3.1/hyper-1.3.1-x86_64-linux.AppImage](url)

**Comment by kenjitoyama** [comment]
This is currently broken.

The current link at hyper.is is https://github.com/zeit/hyper/releases/download/1.3.1/hyper-1.3.0-x86_64-linux.AppImage. but it should have been https://github.com/zeit/hyper/releases/download/1.3.1/hyper-1.3.1-x86_64-linux.AppImage (notice the mismatched version in the filename).

**Comment by albinekb** [comment]
Fix here: https://github.com/zeit/hyper/pull/1690

Go to https://hyper-latest.now.sh to see

**Comment by erhathaway** [comment]
@albinekb the fix has been merged but the hyper website (https://hyper.is/#installation) still doesn't have the updated link for the AppImage

**Comment by albinekb** [comment]
Aha thanks @erhathaway, @matheuss can you deploy? 🙏
