### ISSUE TITLE
Command prompt customized for git causes strange behavior.

### ISSUE THREAD

**Issue by venedie** [zeit/hyper#1686]
Hyper is behaving strangely when the command prompt is customized to show git branch. It blocks or works very slowly. Works fine when not in location under git. I tested this issue on Mac and Windows and both behave the same: laggy and glitchy when in git repo and work fine outside it. Shell is zsh with oh-my-zsh and ys theme (tested also on other themes).

![Screencapture of the laggy window](https://cloud.githubusercontent.com/assets/235299/24083676/f12868f2-0cdb-11e7-9e71-5f1e9b27490a.png)

-

Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.14393

**Comment by zsol** [comment]
do you have the same problem without hyper?
Try opening the builtin terminal app and see if the issue is there too.

**Comment by venedie** [comment]
I usually use iTerm2 on macOS and don't have this issue. I'll try to test it on other apps.

**Comment by sladiri** [comment]
A customised bash on Windows behaves fine.
`export PS1="\u@\h:\[\e[36;40m\]\W\[\e[m\]\[\e[30;43m\]\`parse_git_branch\`\[\e[m\] "`

**Comment by venedie** [comment]
This issue seems to be unrelated to Hyper, thankfully.
