### ISSUE TITLE
Freshly opened with trailing space

### ISSUE THREAD

**Issue by TurtleP** [zeit/hyper#1689]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Antergos Linux (Arch Linux) 4.10.4-1-ARCH
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Here](https://gist.github.com/TurtleP/0711d6b2839fae471455d0b7133eb12a)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Opening Hyper seems to be doing [this](http://i.imgur.com/bwUc00M.png) to my prompt. Not sure if it's because of the PS1 or hyper, but [gnome-terminal](http://i.imgur.com/BT9muyR.png) is not having the issue. Just to clarify, I removed all plugins from the .hyper.js and it still persists.

Only thing I'm certain of it being is that Hyper, while is *is* remembering the last size of the window, the PS1 isn't getting the correct value for $(COLUMNS). I can post the PS1 if necessary.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
