### ISSUE TITLE
Right click 'Inspect Element'

### ISSUE THREAD

**Issue by eoinmurray** [zeit/hyper#169]
This would be really useful for people trying to write custom css styles; especially since the dev tools are already available.

**Comment by kazzkiq** [comment]
I think a better approach would be making this feature available on dev builds (or under a switch on app preferences).

This way mainstream users don't happen to accidentally open the Inspect window, and it will still be available to those who want to debug their terminal plugins in "window-mode" and in "real-time".

**Comment by albinekb** [comment]
A workaround is to use this button: 
![image](https://cloud.githubusercontent.com/assets/5027156/17453343/029e2134-5b7b-11e6-9fd4-c17ff9e22bf9.png) and then click on a element to make the dev-tools focus it.

I don't really know what's stopping right-clicking an element, maybe we could enable right-clicking when the dev-tools is open?

**Comment by chabou** [comment]
Closed in favor of #265
