### ISSUE TITLE
shrug (`¯\_(ツ)_/¯`) rendering weirdness

### ISSUE THREAD

**Issue by davethegr8** [zeit/hyper#1692]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX 10.11.6
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/davethegr8/ee03422b43dab9c8529b425d2b796c34
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:
N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I've just noticed some weirdness with some character sequences. I have a folder that contains the following files:

![screen shot 2017-03-23 at 1 44 02 pm](https://cloud.githubusercontent.com/assets/55392/24269554/eb9ea374-0fce-11e7-93b0-456d85fcce8b.png)

In Hyper, when I `ls` in the directory I get this output:

![screen shot 2017-03-23 at 1 45 42 pm](https://cloud.githubusercontent.com/assets/55392/24269589/0b5f9114-0fcf-11e7-9ee5-e6cd86702779.png)

```
$ ls
(╯°□°）╯︵ ┻━┻                              ¯\_( y o l o )_:¯                           ಠ_ಠ
(ﾉ✿◕ヮ◕)ﾉ*:･ﾟ✧                              ¯\_(ツ)_:¯                                  ┻━┻ ︵ヽ( ` Д ´ )ﾉ︵ ┻━┻
test.js                                     ᕕ( ᐛ )ᕗ                                     ┬─┬ノ( º _ ºノ)ノ
test.php                                    ┐(￣ー￣)┌
```

The notable differences: 
- some instances of `/` are replaced with `:`
- not all of the files are aligned properly
- there is an extra `ノ` on ` ┬─┬ノ( º _ ºノ)`

Some (but not all) of these appear to not be specific to Hyper (this is in OSX Terminal):

![screen shot 2017-03-23 at 1 49 13 pm](https://cloud.githubusercontent.com/assets/55392/24269690/85a2c3ec-0fcf-11e7-8e45-2f289436167d.png)

```
(╯°□°）╯︵ ┻━┻                              test.php                                    ᕕ( ᐛ )ᕗ                                     ┻━┻ ︵ヽ( ` Д ´ )ﾉ︵ ┻━┻
(ﾉ✿◕ヮ◕)ﾉ*:･ﾟ✧                              ¯\_( y o l o )_:¯                           ┐(￣ー￣)┌                                  ┬─┬ノ( º _ ºノ)
test.js                                     ¯\_(ツ)_:¯                                  ಠ_ಠ
```

**Comment by migmuni** [comment]
I am experiencing something similar. The shrug in my terminal does not have it's special characters spaced properly and actually causes the cursor to be off. 

![screen shot 2017-04-15 at 10 59 17 am](https://cloud.githubusercontent.com/assets/18077583/25064914/fd505e74-21ca-11e7-8d52-51a7cc144a4a.jpg)

**Comment by davethegr8** [comment]
This does not repro on 2.0.0 stable. (osx 10.13.4)

![screen shot 2018-04-17 at 9 16 29 am](https://user-images.githubusercontent.com/55392/38882824-1525876a-4220-11e8-8408-b66d9b9728a1.png)

**Comment by chabou** [comment]
@davethegr8 Thank you for your feedback 🙏
