### ISSUE TITLE
really nice start of program

### ISSUE THREAD

**Issue by x8core** [zeit/hyper#1693]
So, i edit preferences and now after program start i see just that. Perfect.

https://monosnap.com/file/dvtwao5DDVdcQKPbaiaej3CDFcjkVH

How to make on Hyper something like "reset factory settings"?

**Comment by henrikdahl** [comment]
Delete ´.hyper.js´ in ´~´

**Comment by albinekb** [comment]
Yes, the current solution is to delete `.hyper.js` and restart hyper, this will re-create the original config 🎉  Re-open if it didn't work.
