### ISSUE TITLE
Feature Request: Find/Search on screen or buffer

### ISSUE THREAD

**Issue by andradei** [zeit/hyper#1697]
## Feature request

Add Find/Search on screen or buffer feature.

I believe a lot of people find this feature useful when reading walls of text in stdout.

**Comment by MartyGentillon** [comment]
Alternately, this might be able to be written as a plugin....

**Comment by kyleshay** [comment]
duplicate of #1697

**Comment by andradei** [comment]
@kyleshay Thanks for the reference, that other issue is exactly what I agree with. Closing this.
