### ISSUE TITLE
How to install fonts, specifically on windows

### ISSUE THREAD

**Issue by Thebigbignooby** [zeit/hyper#1701]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

This is what I have in my `.hyper.js`

```
"fontFamily": '"Fira Code", "Roboto Mono", monospace',
```

however, it looks like monospace is being used. I presumed this would configure the fonts auto-magically, but I conclude that I must first install the fonts, and I'm ok with that . . . except I have no clue how to do this.

Do I need to install them on my windows system ?
Is there a special way to install fonts only for hyper ?
Where do I put font-files I download ?
Any font-file formats recommended ? (I don't mean mono, but .ttf or something else ?)

I think there should be some guide in the docs explaining how to do this on the different platforms (windows, linux, macos)  to save users from having to hunt through the web and hyper issues.

I came accross people mentioning powerline fonts . . . Is this what I should use ? I understand from their docs that powerline fonts is only for powerline.

**Comment by therealplato** [comment]
yes, install them to windows, i don't have immediate access to windows box to check - but from memory:
- hit win+r for Run dialog
- type `fonts` and press enter
- drag and drop downloaded font files into the fonts folder to install

yes, powerline fonts add some special characters used to make powerline prettier

ttf is great, woff (web open font format) is also fine

my favorite programming font is [inconsolata](http://levien.com/type/myfonts/inconsolata.html)

**Comment by DanielGGordon** [comment]
I suggest testing out [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts). You just need to download the .ttf file and then open it - the Windows font viewer should give you an option to install the file. 

Make sure you download a font with 'Windows Compatible' in the name.

**Comment by Thebigbignooby** [comment]
@DanielGGordon thanks for the tip, I will give that a look :)

**Comment by Thebigbignooby** [comment]
This worked like a charm, really easy. Is it this easy on linux ? :D

**Comment by therealplato** [comment]
awesome!
please close the issue @Thebigbignooby

**Comment by airstrike** [comment]
Dropping font files into `C:\Windows\Fonts` requires admin access, though some tools exist to allow users to temporarily install fonts without escalation. These get written to the font cache and are available until the next reboot, but not visible to Hyper.
