### ISSUE TITLE
Cannot type any Chinese word in Hyper.

### ISSUE THREAD

**Issue by Steven0811** [zeit/hyper#1702]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate (not sure)

- **OS version and name**:  macOS 10.12.3
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Link](https://gist.github.com/Steven0811/25412efe08f8ab60ac131afed632bf66)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I found a weird thing that when typing some Chinese word in Hyper, it comes a problem bothering me so much since I started using old version until now.The point is I can't input any Chinese word in here.

I have tried install clean Hyper on Linux(ubuntu 16.04), however this problem still shows again no matter in different operating system .

So I captured a .gif screenshot that you guys can easy to know what was I talking about.

![mar-25-2017 19-34-23](https://cloud.githubusercontent.com/assets/4948562/24321870/15383b36-1192-11e7-8bc5-0175b16e99ca.gif)

This is a screenshot when I want to input Chinese word "中文測試" and "中文輸入", but the wrong single word keeps repeating. It makes me can't input Chinese folder name or path. 

I've seen some related issues (e.g. #1420 ), therefore it still can't be solved.

**Comment by cuyu** [comment]
Just meet the similar issue of Chinese typing. Mine is I cannot type the Chinese characters, only get the English characters instead.

**Comment by willin** [comment]
want 

mark and watch

**Comment by Sanster** [comment]
As far as I know hyper use [hterm](https://chromium.googlesource.com/apps/libapps/+/HEAD/hterm) which not support input CJK (Chinese, Japanese, Korean) character :cry: . Another library [xterm.js](https://github.com/sourcelair/xterm.js/) (which is used by VSCode) has support for CJK.

**Comment by ppot** [comment]
We are in the process of switching form hterm to xterm

**Comment by L3au** [comment]
👍  What's the state now ?

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by yuezy3** [comment]
I love hyper, but the character display and input are a big issue. when displaying CJK character, it crowed together, and you just can't input those CJK char.  Hope the fix come faster.

**Comment by Steven0811** [comment]
ok, here is a good news.

I saw that Hyper team are working on it, check out the Pre-release this [2.0.0](https://github.com/zeit/hyper/releases/tag/2.0.0). The lastest Pre-release version is [2.0.4](https://github.com/zeit/hyper/releases/tag/2.0.4).

It's support CJK right now, but still a lot of problem needs to fix. So if anyone needs,you can try it.

![screen shot 2017-09-28 at 1 30 09 am](https://user-images.githubusercontent.com/4948562/30927910-9418363a-a3ec-11e7-9437-0537da35e947.png)

**Comment by yuezy3** [comment]
@Steven0811 I have heard that the xterm.js are better than hterm respecting the Unicode support, and hyper are swithing to xterm.js now. Is this reason that the display are seem correct now?

**Comment by Steven0811** [comment]
@yuezy3 Yes, It seems like this reason.

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
