### ISSUE TITLE
Plugin Load Error

### ISSUE THREAD

**Issue by BenjaminHoegh** [zeit/hyper#1703]
<img width="328" alt="skaermbillede 2017-03-25 kl 14 54 54" src="https://cloud.githubusercontent.com/assets/22152591/24322783/0ed75db6-116b-11e7-9e69-9fbd7c6b1889.png">

Hyper 1.3.1
Electron 1.4.7
darwin x64 16.5.0

**Comment by zsol** [comment]
you're better off opening an issue at https://github.com/Kikobeats/hyper-flat

**Comment by CodeTheory** [comment]
Thanks @zsol. Seems like a plugin issue and the issue has been inactive for some time. Let us know if you have any issues with vanilla Hyper 🙏
