### ISSUE TITLE
Printing chr(14) (Shift Out/Control-N) makes terminal unreadable

### ISSUE THREAD

**Issue by replomancer** [zeit/hyper#1704]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Ubuntu 16.04 and Windows 10
- Hyper 1.3.1
- Is Vanilla.

## Issue
Printing chr(14) (e.g. when cating a file) results in a mess:

```bash
lukasz@lukasz-XPS-L421X:~$ python -c "print chr(14)"

┌┤┐▒⎽≥@┌┤┐▒⎽≥-XPS-L421X:·$ ⎼␊⎽␊├
```
The command typed above is "reset" (it works).

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
