### ISSUE TITLE
Terminal colours not working correctly with bash on Windows

### ISSUE THREAD

**Issue by jameshclrk** [zeit/hyper#1706]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jameshclrk/83bf7c015a08c508426220b17d1eda04
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
After running a command that outputs colours to the terminal, the text in the terminal is inverted.
This doesn't happen in any other terminals I've tried.
Hyper:
![Hyper](https://i.imgur.com/iUN01nO.png)
cmd.exe:
![cmd](https://i.imgur.com/13TGHFw.png)
powershell:
![powershell](https://i.imgur.com/NOSKdtf.png)
mintty:
![mintty](https://i.imgur.com/QAllQYV.png)

**Comment by sladiri** [comment]
I had to reset my CMD colors before the colours in bash on Windows behaved normally. After that I could use a theme for Hyper.
https://www.sevenforums.com/tutorials/401170-command-prompt-restore-default-personalization-settings.html

**Comment by chilblane** [comment]
I'm noticing what I believe is the same issue in Bash on Ubuntu on Windows, using vanilla Hyper.app (default index.js). Here's a screenshot of a directory view:

![image](https://user-images.githubusercontent.com/1987274/28253160-f8729d0e-6a54-11e7-8695-35b5ce40b801.png)

The directory labels (example: `node_modules`) are using `blue` as foreground and `green` as background. The same blue is used for the path's background color and the green is used as the text color for the files. In the vanilla theme, this isn't unreadable enough for me to notice as unusual at first, but with different themes you can see how significant of an issue it is:

hyperterm-atom-dark
![image](https://user-images.githubusercontent.com/1987274/28253219-31d0615c-6a56-11e7-85ab-378ca5d9cfe4.png)

hyper-solarized-dark
![image](https://user-images.githubusercontent.com/1987274/28253212-08071140-6a56-11e7-9a98-48a4e4933ab6.png)

In the case of the latter theme, you can see in this [related issue](https://github.com/ghosh/hyper-solarized-dark/issues/10) what the directory colors are supposed to look like. The background orange is apparently what the git branch status uses.

**Comment by Elderry** [comment]
I agree that this problem is caused by WSL, because on my PC, some other terminal emulators also encountered this.
Integrated Terminal of Intellij Idea:
<img width="423" alt="1" src="https://user-images.githubusercontent.com/1892221/28257973-0cf4bfc6-6b01-11e7-8fa2-cd9ffc0205ee.PNG">
Integrated Terminal of Visual Studio Code:
<img width="388" alt="2" src="https://user-images.githubusercontent.com/1892221/28257918-b0915398-6b00-11e7-9509-6d844a7cdf8c.PNG">

**Comment by jameshclrk** [comment]
@chilblane The directory colours there are a different issue, it is to do with Bash on Ubuntu on Windows setting permissions incorrectly by default.

That can be solved be fixing the umask. See Microsoft/BashOnWindows#352
Of course, you'll have to fix the permissions for each directory already affected, but new ones should be fixed.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by Elderry** [comment]
I'm afraid that this issue remains in the 2.0 version.
OS version: Windows 10 Pro Build 16299.371

Expected rendering:
![correct](https://user-images.githubusercontent.com/1892221/39103563-139bb4ec-46de-11e8-97a6-9d6d580c35f9.JPG)

**Comment by Stanzilla** [comment]
Thanks for reporting back!

**Comment by Elderry** [comment]
Yes, vscode has the same problem.
![vs](https://user-images.githubusercontent.com/1892221/39159288-646c7262-4797-11e8-98e4-d80bdeffaf60.JPG)

**Comment by leonelsr** [comment]
It is still happening. @Stanzilla did you mark the issue on xterm.js? I couldn't find it, but it would be nice to know the status of this...

Interesting fact: it works like a charm not only on PowerShell but also on plain old cmd.exe. This is indeed a xterm.js only bug 😢

**Comment by Stanzilla** [comment]
No, I never filed an issue for that :(

**Comment by vinzloh** [comment]
this worked for me and it wasn't too complicated, so thought I'd share :) scroll down to the section about `dircolors`:

https://medium.com/@Andreas_cmj/how-to-setup-a-nice-looking-terminal-with-wsl-in-windows-10-creators-update-2b468ed7c326
