### ISSUE TITLE
Window freezes up when closing tab via `exit` command.

### ISSUE THREAD

**Issue by mrapogee** [zeit/hyper#1707]
- Create a hyper window
- Create new tab
- Close tab be entering `exit`

The window freezes up, while the command I enter do work (if I enter `enter` again to close the first window it exits) the screen does not update. It works again if I hit `cmd+shit+r` to full reload but not just reload with `cmd+r`.

Hyper 1.3.1
Electron 1.4.15
darwin x64 16.4.0

**Comment by MrRio** [comment]
What shell are you using? I don't seem to get this.

**Comment by mrapogee** [comment]
I'm using Fish shell.

**Comment by chabou** [comment]
@mrapogee Do you see something in dev-tools ?
Duplicate #1628 ?

**Comment by mrapogee** [comment]
Yes, it's a duplicate of #1628 and #1719
