### ISSUE TITLE
Emacs not suported

### ISSUE THREAD

**Issue by regisbsb** [zeit/hyper#1708]
Install emacs 64 bits 
http://ftp.heanet.ie/mirrors/gnu/emacs/windows/emacs-25.1-2-x86_64-w64-mingw32.zip

call `emacs -nw`

get error

![image](https://cloud.githubusercontent.com/assets/886819/24384675/8fc1d37c-135d-11e7-9aab-8c693e6210bc.png)

Running bare without any plugins
-

Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.15063

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
