### ISSUE TITLE
Scroll bar can not drag

### ISSUE THREAD

**Issue by zhea55** [zeit/hyper#1709]
1. I run my react project
2. Webpack print a lot of message
3. I want drag the right scroll bar to scroll up, check the compile info.

but the scroll bar can't drag. Please fix, thanks!

Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.14393

**Comment by Ra1da35ma** [comment]
Please this is important as a primary feature not a __plugin__

-------
thanks

**Comment by MartyGentillon** [comment]
This is a duplicate of https://github.com/zeit/hyper/issues/1251

**Comment by Ra1da35ma** [comment]
okay. If its a duplicate. close it

**Comment by chabou** [comment]
@MartyGentillon you are on fire! 🔥 Thank you for your help!
