### ISSUE TITLE
hope support eastern language

### ISSUE THREAD

**Issue by TaoJinjin-Thomas** [zeit/hyper#1710]
it is not display well with other language ，chinese、japanese.. 
-
Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.14393

**Comment by david50407** [comment]
![image](https://user-images.githubusercontent.com/841969/27319802-c8b8980a-55c5-11e7-8448-cc979c10cfcc.png)

Like this, all full-width words all have only half-width space to display.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
