### ISSUE TITLE
Repeated prompt using fish shell with two line prompt theme

### ISSUE THREAD

**Issue by hutruhup** [zeit/hyper#1714]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.3
- **Hyper.app version**: 1.3.1.1628
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Repeated prompt using fish shell with two line prompt theme when first opened. But works fine when opening a new tab. I tried several other prompt themes. It seems the problem only exist with prompt with more than two lines. And there is no problem with iTerm2.
Using [Pure](https://github.com/rafaelrinaldi/pure) installed by Fisherman. Fish shell settings are default. Other plugins are pure, getopts, z, bass, transfer.
![First Open](https://cloud.githubusercontent.com/assets/26748166/24420430/de15db0a-13c0-11e7-9239-6828d12969ab.png)
![New Tab](https://cloud.githubusercontent.com/assets/26748166/24420435/e15ee734-13c0-11e7-9347-bde4aed1d13b.png)

**Comment by sholladay** [comment]
I have the same setup and problem. It definitely seems like a Hyper problem. I cannot reproduce it using this setup in Terminal.app.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
