### ISSUE TITLE
Ctrl-A on Windows does not move to beginning of line

### ISSUE THREAD

**Issue by ivanoats** [zeit/hyper#1716]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10 Insider Fast Ring**: 
- **1.3.1**: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

On Windows, Ctrl-A is mapped to Select All. Maybe this is the desired effect and the default. But it's a bit disorientating, I was expecting the normal readline (emacs-style) shortcuts to work, taking me to the beginning of the line. 

Is this by design? Or would you consider it an issue?

**Comment by KalenAnson** [comment]
see #1525 Definitely a problem

**Comment by ppot** [comment]
close in #1876
