### ISSUE TITLE
Opening another tab when some process is started locks the opened tab

### ISSUE THREAD

**Issue by vincaslt** [zeit/hyper#1717]
I'm starting a server in one tab, so that process runs indefinitely, and open another tab. The newly opened tab is locked, as in I can't type anything or run anything. I must open another window if I want to do this. Is it intended? And how do I overcome it?

**Comment by phillipchan2** [comment]
I discovered that this was one of the plugins I was using that was causing this, not hyper itself. I just commented out each one and doing a hard refresh `Cmd + Shift + R` until the problem resolved.

**Comment by MartyGentillon** [comment]
For future reference, which plugin?

**Comment by MartyGentillon** [comment]
Also, if you filed an issue on it, could you link it?

Thanks,
Marty

**Comment by Arro** [comment]
`hyperterm-tabs` was causing this for me.
