### ISSUE TITLE
Exiting the shell freezes current instance.

### ISSUE THREAD

**Issue by entrptaher** [zeit/hyper#1719]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

This is a duplicate of https://github.com/zeit/hyper/issues/1707, but with additional details. 

- **OS version and name**: Ubuntu 16.04 LTS
- **Hyper.app version**: 1.3.1
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Check below.
- **The issue is reproducible in vanilla Hyper.app**: Yes.

## Issue

Creating a new TAB and exiting that tab freezes the current hyper instance. 

Here is the gif to show what I mean. I was typing but it was not showing anything. 
![peek 2017-03-30 06-35](https://cloud.githubusercontent.com/assets/8284972/24482470/31e206fc-1513-11e7-8746-67f9c4d93dbe.gif)

another one,
![peek 2017-03-30 06-48](https://cloud.githubusercontent.com/assets/8284972/24482717/4c171f60-1515-11e7-9d71-dce183d049c9.gif)

If I close it by clicking the exit button, it works fine and devtools shows this comment, 
`ignore pty exit: session removed by user`

Then the following errors were produced on devtools when I entered `exit`.
![screenshot from 2017-03-30 06-48-53](https://cloud.githubusercontent.com/assets/8284972/24482696/279185d6-1515-11e7-9186-544afdbc664b.png)

This **DOES HAPPEN** on vanilla hyper term. I am actually typing things, but it's just not showing anything.

![peek 2017-03-30 06-57](https://cloud.githubusercontent.com/assets/8284972/24482864/354a1e80-1516-11e7-827e-a2716dc069d3.gif)

Again, this error.
![screenshot from 2017-03-30 06-59-24](https://cloud.githubusercontent.com/assets/8284972/24482900/6dbd958a-1516-11e7-935c-8a733a29dca7.png)

Opening a new tab after that error produces this,
![screenshot from 2017-03-30 07-10-57](https://cloud.githubusercontent.com/assets/8284972/24483183/1e8c3082-1518-11e7-8d1d-1644a2ecf6d4.png)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by tomasdev** [comment]
Perhaps related to #3736
