### ISSUE TITLE
Hyper ignores Ctrl + R to search command history on Windows

### ISSUE THREAD

**Issue by Yohanna** [zeit/hyper#1720]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Yohanna/a0d658095d3bcbb36497ff231d20d9cf
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
* Hyper ignores `Ctrl+r` when using PowerShell or Bash on Windows. Normally in PowerShell when you press `Ctrl+r` you can search your command history like you do on Linux. This does not work in Hyper.

**Comment by KalenAnson** [comment]
See #1525. Definitely a problem.

**Comment by rkmax** [comment]
Not working at Archlinux either

**Comment by alokmandloi** [comment]
Yeah , it seems to refresh the page instead.

**Comment by garyx** [comment]
Just ran into this issue, ctrl-r should let me access the command line history but hyper eats it regretfully.

**Comment by ppot** [comment]
I like your `regretfully` 😂. However it solved in the current master.

**Comment by rkmax** [comment]
I'll wait for the next release to use hyper I can't live without this

**Comment by garyx** [comment]
What's the timetable for next version release?

**Comment by ppot** [comment]
closed in #1876. @garyx  @rkmax Hope before end on month!

**Comment by saravanabalagi** [comment]
Is this issue closed as it's fixed in #1876 and is now working in Hyper? It doesn't work for me. I'm lost in #1876 and don't know how to get <kbd>Ctrl</kbd><kbd>R</kbd> working.
