### ISSUE TITLE
[Debian][GNOME] Terminal uses custom borders instead of system default

### ISSUE THREAD

**Issue by sergiofenoll** [zeit/hyper#1723]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS + version**: Debian 9.0 Stretch
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/sergiofenoll/ff30d218845501a1ac5e6b170b09e44d
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

1) The terminal uses a custom border/buttons which don't mix too well with my current theme. Not a huge issue but it'd be nice to know how to change it :)
What I'm referring to:
![image](https://cloud.githubusercontent.com/assets/22411874/24579436/02425822-16f6-11e7-9888-588f2fe55c8a.png)

2) Is there a way to enable font ligatures? I use Fira Code as monospace font and it has some nice ligatures I'd like to have on my terminal. 

3) Transparency doesn't seem to be working. backgroundColor is set as 'rgba(0,0,0,0.8)' but it looks solid black.

**Comment by mnpenner** [comment]
I think more important than the style inconsistency is that you can't access the menu bar if you have 

```
Settings > Appearance > Show the menus for a window > In the window's title bar
```

...because the window's title bar doesn't show. Took me quite awhile to figure out where all the options were hiding.

**Comment by duard** [comment]
Same on my system. 

![screenshot from 2017-04-08 13-15-24](https://cloud.githubusercontent.com/assets/36894/24830483/7566545e-1c5d-11e7-91b7-83ff26bf96f2.png)

**Comment by Lindenk** [comment]
This seems to be a long standing issue #1059

**Comment by SergioGeeK7** [comment]
I'm experimenting the same issue, it would be nice at least to change the direction of [maximixe, minimise, close] buttons to left or right

**Comment by bgw** [comment]
I made a plugin to work around this issue: https://github.com/bgw/hyper-native-window-decoration

![screenshot](https://user-images.githubusercontent.com/180404/33337776-ed43172c-d428-11e7-9446-35191e87fad4.png)

**Comment by Stanzilla** [comment]
Wontfix for now, please use the above plugin :)
