### ISSUE TITLE
Can not type Korean in Linux

### ISSUE THREAD

**Issue by BeyondLimitation** [zeit/hyper#1725]
OS: Ubuntu Linux 16.04.1 LTS 64-bit
Hyper: hyper-1.3.1-x86_64-linux.AppImage

**Issue**
(I didn't install this for test.)
My issue is that i can not type korean. Here is a image.
![image](https://cloud.githubusercontent.com/assets/10960326/24586498/7cfa6d56-17dd-11e7-9858-1bedda441df7.png)

Check right-top, as you can see i was typing korean. But i can't type any koreans whereas bash terminal can.

How to solve this issue? If Hyper doesn't support Korean would please do that?

**Comment by albinekb** [comment]
let's track korean in #410
