### ISSUE TITLE
Compatibility with Bash on Ubuntu on Windows ?

### ISSUE THREAD

**Issue by yvan-sraka** [zeit/hyper#1726]
Hello,

I recently installed [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about), and I'm really sad: because the terminal provided by Windows is the classic old `CMD.exe`, so I wonder about how it would be possible to use this Bash under WSL (Windows Subsystem for Linux) inside Hyper?

Thank you very much,

**Comment by ZacBlanco** [comment]
I just did this last night. Go into `.hyper.js` settings and modify the `shell` property to be `bash.exe`

**Comment by albinekb** [comment]
as @ZacBlanco said, replace `shell` in your  `.hyper.js` to `bash.exe`

Re-open if you need more help @yvan-sraka, closing this as it seems resolved 👌

**Comment by DanielGGordon** [comment]
Or you can just enter in the command `bash` when you want to enter the WSL
