### ISSUE TITLE
Broken behaviour for bell characters

### ISSUE THREAD

**Issue by rosszurowski** [zeit/hyper#1729]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

* **OS version and name**: macOS Sierra 10.12.3
* **Hyper.app version**: Hyper 1.3.1

## Issue

Hyper doesn't respond to [bell characters](https://en.wikipedia.org/wiki/Bell_character) unless the window that echoed them is focused. Hyper windows only sound the bell once focus returns to the window, which removes the ability to [use them as notifications for long-running commands](http://apple.stackexchange.com/a/56602). It's also inconsistent with existing terminal emulators.

To try it for yourself:

```bash
# Run this command, but switch focus away from Hyper quickly
sleep 1 && tput bel
```

A second, but closely related issue is that there's no visual feedback for bell characters.

On macOS, other terminal emulators provide a visual indication if a bell was echoed while the window was unfocused, such as a dock bounce or notification badge. It'd be nice for Hyper to be consistent with them.

This would also help users who disabled the `bell` option in their `~/.hyper.js` config. Echoing a bell character while that option is disabled provides no feedback. The bell sound is never made.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
