### ISSUE TITLE
Character width/alignment issues with blessed/webpack-dashboard

### ISSUE THREAD

**Issue by mnpenner** [zeit/hyper#1731]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: Hyper 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [gist](https://gist.github.com/mnpenner/f6a9d39a8505fc1f2f22578b217b8fcb)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes. Occurs with all plugins disabled and default font.

## Issue

[webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard) is not rendering correctly. It works fine in GNOME Terminal. webpack-dashboard is built with [blessed](https://github.com/chjj/blessed). I tried some of the [blessed examples](https://github.com/chjj/blessed/tree/master/example) and they also have rendering issues.

Hyper:

![image](https://cloud.githubusercontent.com/assets/1112998/24773620/bda1472c-1aca-11e7-981c-bd64fa338db9.png)

GNOME:

![image](https://cloud.githubusercontent.com/assets/1112998/24774077/70958f0e-1acc-11e7-8ae2-7efeac01ea77.png)

Hyper:

![image](https://cloud.githubusercontent.com/assets/1112998/24774094/7c056eb8-1acc-11e7-8718-b5d5b03efd2e.png)

GNOME:

![image](https://cloud.githubusercontent.com/assets/1112998/24774101/865ebe64-1acc-11e7-9285-f7e47e8b36f8.png)

[This example](https://github.com/chjj/blessed/blob/master/example/simple-form.js) actually *does* render correctly, but Hyper is not showing the mouse-over effect when you put your cursor over the buttons. They are, however, still clickable.

![image](https://cloud.githubusercontent.com/assets/1112998/24774154/be636e2c-1acc-11e7-8cf5-332586f025c4.png)

**Comment by chabou** [comment]
Duplicate #1555 
Do you have really searched an existing isuue with 'webpack-dashboard' or 'blessed' 😛  ?

**Comment by mnpenner** [comment]
@chabou Sorry, I was searching for character/alignment issues. Wasn't expecting there to be one specifically webpack-dashboard already; didn't think it was that popular. My apologies! Closing in favour of the other ticket.

**Comment by chabou** [comment]
ahah :) no problem!
