### ISSUE TITLE
New lines are created for progressive updates rather than replacing the old ones

### ISSUE THREAD

**Issue by ingro** [zeit/hyper#1732]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro build 1703 (creators update)
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: is vanilla

## Issue
After updating Windows 10 to the last version (creators update) I wanted to try again hyper.app with the improved bash for window. Unfortunately it seems like progressive updates are broken, new lines are constantly created instead of replacing the old ones and even the cursor is far off its position. Since I wasn't using hyper.app from some times I first disabled all the plugins and the created a fresh .hyper.js config file, but nothing changed. I attached a screenshot to better show the problem.

![hyperlines](https://cloud.githubusercontent.com/assets/879431/24804562/1d8a1b5c-1baf-11e7-8216-f8fff295483a.jpg)

**Comment by jcolesio** [comment]
I'm seeing the same issue after the creators update.

**Comment by myktra** [comment]
+1. For me – when using `yarn`. Though cursor position is stable for me.

**Comment by siziyman** [comment]
After trying to work around the same issue I've discovered that line breaks "break" at exactly 160 terminal chars  width Hyper window regardless of font size or anything else, at least at my own PC.
I can provide screenshots or record a screencast to show apparent difference in behaviour at 159 and 160 characters (making window larger doesn't help, apparently).

**Comment by Jofagi** [comment]
I observed the same behavior as @siziyman.
I'm running on Win10 with Creator's Update. The problem doesn't show up on another Win10 PC which does not yet have the Creator's Update.

**Comment by MartyGentillon** [comment]
What is your $TERM variable set to?

**Comment by MartyGentillon** [comment]
Well, it's doing this with yarn and powershell.

**Comment by MartyGentillon** [comment]
Also, this seems to result in the offset console bug as well.  I have to suspect that it is an issue in the underlying hterm library.

**Comment by MartyGentillon** [comment]
Interestingly enough, this is only happening with the progress bar.  It does not happen with the spinner.

Given that this is also triggering the console offset bug, I suspect that it is the combination of some strange width character and clear line that causes this.

**Comment by jcolesio** [comment]
has there been any progress on this issue?

**Comment by MartyGentillon** [comment]
I suspect that this is going to be fixed when we finish replacing the underlying terminal library.

**Comment by gluons** [comment]
Same problem on PowerShell with Creator Update. It maybe [Yarn](https://github.com/yarnpkg/yarn) issue? Does anyone report to Yarn?
> I test on my working laptop. I don't have Windows laptop at my home.  😅

<img width="780" alt="default" src="https://cloud.githubusercontent.com/assets/4688092/25979937/b6d41964-36f5-11e7-8fe8-cc21093fc0f8.PNG">

**Comment by gluons** [comment]
Related issue: yarnpkg/yarn#2530

**Comment by m4r1vs** [comment]
has anyone an idea when this will be fixed?

**Comment by gluons** [comment]
Fixed by yarnpkg/yarn#4317. 🎉

We can wait for Yarn newer version.
Or test by grabbing the artifact from https://ci.appveyor.com/project/kittens/yarn/build/3769/job/3owvdyefkpofp10x/artifacts

<img width="682" alt="default" src="https://user-images.githubusercontent.com/4688092/30464167-1c6f19a6-99fa-11e7-8851-0d1ececd8a9f.PNG">

**Comment by chabou** [comment]
@gluons Thank you for your feedback!
