### ISSUE TITLE
True Color not working on Bash on Windows

### ISSUE THREAD

**Issue by PowerSnail** [zeit/hyper#1733]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Default
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: None
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Bash on Windows supports 24bit true colour with Truecolour escape codes. Running [test script](https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh) that I found [here](https://gist.github.com/XVilka/8346728), the following are results from 

1. Bash on Windows 
<img width="717" alt="1" src="https://cloud.githubusercontent.com/assets/7428673/24807412/154e3cda-1b86-11e7-90ca-887066a7937f.PNG">

2. Hyper. (CMD starts by default, type `bash`, and run the script)

 
<img width="651" alt="capture" src="https://cloud.githubusercontent.com/assets/7428673/24807416/179b467c-1b86-11e7-8a32-36536796f218.PNG">

**Comment by eoinmurphy** [comment]
This might be a noob question, but do you have a `bash` terminal simply because you're running Windows 10? I've always used the *Git Bash* terminal on Windows, so having Hyper limited to the default terminal is a little saddening.

**Comment by chabou** [comment]
@eoinmurphy You can configure the shell you want. Just set `shell` parameter in config file.

@PowerSnail Having 24-bit color could be hard to achieve. Some other term app have some tricks: http://conemu.github.io/en/BashOnWindows.html#wslbridge We need to test `hterm` compatibility with 24bit colors.

**Comment by MartyGentillon** [comment]
It does look like xterm.js is working on this (for whenever that transfer is done...)  https://github.com/sourcelair/xterm.js/issues/484

**Comment by MartyGentillon** [comment]
also, related: https://github.com/zeit/hyper/issues/364

**Comment by Stanzilla** [comment]
https://github.com/xtermjs/xterm.js/issues/484

**Comment by trusktr** [comment]
Bump.

The screenshot shows that although I've selected text in NeoVim, it looks as if nothing is selected (not just ugly, but negative impact on perceived functionality):

![bad_color](https://user-images.githubusercontent.com/297678/36067996-72cddc70-0e7f-11e8-976f-a2b08ceeff51.PNG)

**Comment by blark** [comment]
Would really like to see true color support. Been using this on WSL since it came out, and on my other platforms (Linux and Mac) so all my configs are set for it. I'd really like to switch to Hyper but true color is too nice to give up :)

**Comment by b0rski** [comment]
And powerline is failing as well and probably because of this :/ See https://github.com/zeit/hyper/issues/2470.

**Comment by bokub** [comment]
Color support is even worse on my computer: unsupported colors are just hidden.
I use windows 10 too and Hyper 1.4.8

![screenshot](https://user-images.githubusercontent.com/17952318/38454049-16fe2500-3a60-11e8-9bd1-74cd913e9bf4.PNG)

**Comment by mhamrah** [comment]
Ditto- this is a problem in hyper and vs code's integrated terminal. Here's a simple color output function and a screenshot.
```
 colors() {
	for COLOR in {0..255}
	do
	    for STYLE in "38;5"
	    do
		TAG="\033[${STYLE};${COLOR}m"
		STR="${STYLE};${COLOR}"
		echo -ne "${TAG}${STR}${NONE}  "
	    done
	    echo
	done
}
```
![image](https://user-images.githubusercontent.com/91162/38461984-5075538e-3aac-11e8-87cd-b4bbf0f77f97.png)

**Comment by JSn1nj4** [comment]
Having the same issue, though I notice that both Hyper and ConEmu, when using Git Bash, have to run it via `C:\\Program Files\\Git\\git-cmd.exe --command=usr/bin/bash.exe -l -i`.

When I run the same color test script linked by the OP, the true color support works in `C:\Program Files\Git\git-bash.exe`. But when I run it in a bash session started inside of `git-cmd.exe` instead, the color output is broken. Same if I start CMD, run `\Program Files\Git\bin\bash.exe`, and then run the test script again.

This makes me wonder if it's more a CMD issue than an issue with Hyper.

@blark is this an issue for you when using Hyper on Linux or Mac?

**Comment by Jaykul** [comment]
Well, yes -- of course it's an issue with Windows' conhost.  But to be clear, that's the underlying console subsytem that **all** console apps run in. In other words, it's **the** core difficulty of implementing something like hyper on Windows, and it's not just a problem with a few particular apps or ways of running them.

Bottom line: although the console subsystem has seen major improvements in the Windows 10 era (to support ANSI escape sequences, among other things), it's still not based on input/output pipelines the way PTY works on posix subsystems.

That's why things like [mintty](http://mintty.github.io/) (and [wslbridge](https://github.com/rprichard/wslbridge), which just wraps mintty) make a difference -- when you run apps through them, if the app supports it, then it behaves as though it were running "remotely" (e.g. over SSH) via a pipe (the Linux way, if you will).

However, that's not the native way to write or run console apps in Windows, and most *interactive* Windows console apps --like Python, when used as a REPL-- don't work when run in mintty or other similar emulators.

**Comment by meijieru** [comment]
So any workground?

**Comment by MrKumaPants** [comment]
Bump

**Comment by eromoe** [comment]
Finally know why vim colorscheme and theme looked werid
![image](https://user-images.githubusercontent.com/3938751/54339142-eabb4880-466e-11e9-81c7-c4dd2f55fbc6.png)

**Comment by Stanzilla** [comment]
should work in CI builds of canary and the next release
