### ISSUE TITLE
RightClick Context Menu after uninstalling the app still contains the Hyper link

### ISSUE THREAD

**Issue by fuaxio** [zeit/hyper#1734]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 7 SP1
- **Hyper.app version**:  1.3.1

## Issue
RightClick Context Menu after uninstalling the app still contains the Hyper link.
Any way to remove it?
![wwss](https://cloud.githubusercontent.com/assets/13122476/24818232/30a24e50-1bfd-11e7-80b4-072c639021a7.png)

**Comment by fuaxio** [comment]
nvm solved the issue.
But installer needs to be improved

**Comment by btd** [comment]
This issue still actual with 1.3.3, just got it at Win 10

**Comment by fuaxio** [comment]
@btd you need to tweak some reg values by searching for "hyper". Do it very cautiously as a wrong reg value deleted might mess your system.
