### ISSUE TITLE
Opening vim always produces junk characters/hash? on cursor position.

### ISSUE THREAD

**Issue by remy** [zeit/hyper#1737]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Yosemite OSX 10.10.3 (14D136) 
- **Hyper.app version**: Version 1.3.1 (1.3.1.1628)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://git.io/vSoSn
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: I'm able to replicate with all plugins disabled.

## Issue

Strange hash junk appears in vim upon opening. Goes away on a clear `ctrl+l` but consistently appears.

Vim: 8 - [full build info](https://git.io/vSoSl)

<img width="737" alt="screen shot 2017-04-09 at 09 35 36" src="https://cloud.githubusercontent.com/assets/13700/24836012/a038cb66-1d08-11e7-9b56-473f54e0ac0c.png">

Happy to mess with my config to help diagnose.

Doesn't happen in iTerm2 or Terminal.

**Comment by larsbs** [comment]
I think is a duplicated of https://github.com/zeit/hyper/issues/1037

**Comment by remy** [comment]
Yep, agreed. Same issue.
