### ISSUE TITLE
How do I use 'git' command and linux command like 'ls','mkdir','touch' on Windows version?

### ISSUE THREAD

**Issue by FateRiddle** [zeit/hyper#1744]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
How do I use 'git' command and linux command like 'ls','mkdir','touch' on Windows version?

**Comment by LoganDark** [comment]
You can't. Try cygwin or bash on ubuntu on windows.

**Comment by albinekb** [comment]
I recommend using bash on Ubuntu on Windows

**Comment by LoganDark** [comment]
I do too.

**Comment by albinekb** [comment]
Closing this as it's not an issue with Hyper itself,
If you need more help I suggest you to join the Zeit Community slack 👼 
[![Slack Channel](https://zeit-slackin.now.sh/badge.svg)](https://zeit.chat/)

**Comment by LoganDark** [comment]
yeah, not sure a missing `git` command is Hyper's fault.
