### ISSUE TITLE
Last line of console output doesn't display.

### ISSUE THREAD

**Issue by MartyGentillon** [zeit/hyper#1746]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue
On windows, with certain zooms and certain fonts (and slightly randomly), the last line of the terminal output fails to render.  This is caused by a bug in the underlying hterm library which has an available patch.

Fix:  https://github.com/zeit/hyper/pull/1745

**Comment by MartyGentillon** [comment]
https://github.com/zeit/hyper/pull/1745 has been merged.  This issue is resolved.

**Comment by MartyGentillon** [comment]
Fix has been rolled back

https://github.com/zeit/hyper/pull/1817

**Comment by MartyGentillon** [comment]
Regressions leading to rollback:

https://github.com/zeit/hyper/issues/1803
https://github.com/zeit/hyper/issues/1816

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
