### ISSUE TITLE
Keyword highlighting in bash on Windows

### ISSUE THREAD

**Issue by Mohamed3on** [zeit/hyper#1747]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.1

## Issue

Hello, I was wondering if it's possible to have keyword highlighting on bash on Windows, since the default is too bland.
![image](https://cloud.githubusercontent.com/assets/12295159/25071638/d810c62e-22bc-11e7-8067-b535e7a0453c.png)
I'm not sure if it's related to Hyper, but I didn't know where else to ask.
Thank you for this great app!

**Comment by CodeTheory** [comment]
I don't think it's possible for bash right now. https://superuser.com/a/868720
