### ISSUE TITLE
Preserve folder location when creating new panes

### ISSUE THREAD

**Issue by MartinMuzatko** [zeit/hyper#1748]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS X (El Capitan)
- **Hyper.app version**:  Version 1.3.1 (1.3.1.1628)
- **Link of a Gist with the contents of your .hyper.js**: [hyper.js gist](https://gist.github.com/MartinMuzatko/652935b48f042b8d29f255879adf046b)
- **The issue is reproducible in vanilla Hyper.app**: yes, always, with and without plugins

## Issue
When creating a new pane (split horizontally/vertically) I do not get to continue from the same location in the new pane. Instead, I land in `~`.

So far, I haven't found a plugin or config item to enable this behavior.

**Comment by elrumordelaluz** [comment]
@MartinMuzatko try [`hypercwd`](https://github.com/hharnisc/hypercwd)

**Comment by MartinMuzatko** [comment]
@elrumordelaluz  brilliant! thank you a lot :)
