### ISSUE TITLE
Remove huge lines of username

### ISSUE THREAD

**Issue by smartclash** [zeit/hyper#1749]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: WINDOWS 10
- **Hyper.app version**:  1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: http://bit.ly/2pweRqK
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

My Hyper is connected with **Bash on Windows** and it really works well than expected. But now the only problem is that the username + path in the terminal nearly takes a line and it kind of feels akward for me. 

![capture](https://cloud.githubusercontent.com/assets/16922883/25141621/b3f91ea0-2481-11e7-8e76-2332e14f37a2.PNG)

I want my Hyper Terminal to look something like this : 

![Capture](https://cloud.githubusercontent.com/assets/6755555/18163794/6737759e-7045-11e6-9117-41f7f343d43e.gif)

I searched everywhere, got into the core app but still i am unable to find a solution for this. Is there any kind of packages or hacks I could use to produce the result I wanted?

**Comment by CodeTheory** [comment]
There's ways to theme your Bash terminal. It's really nothing to do with Hyper itself. 

Example: https://github.com/Bash-it/bash-it/wiki/Themes

**Comment by smartclash** [comment]
@CodeTheory No matter what, I've tested multiple themes but still, there is no change to the theme itself. My terminal looks the same even after restart and reload.

Themes tested with : 
- https://github.com/equinusocio/hyper-material-theme
- https://github.com/dotcypress/hyper-material
- https://github.com/nauzethc/hyperterm-material-theme

**Comment by MartyGentillon** [comment]
Bash themes and Hyper themes are very different things.  Hyper is the terminal emulator, and has no control over the prompt string (beyond what font it is rendered in).  Bash is the shell program, and controls what your prompt string contains.  In bash, your prompt string is determined by the PS1 environment variable.  Bash-it is a series of bash functions that includes themes that change your prompt string.  You should read up on it.

**Comment by smartclash** [comment]
@MartyGentillon Thanks a lot for making me understand
