### ISSUE TITLE
Add Font Weight option to config

### ISSUE THREAD

**Issue by kurisubrooks** [zeit/hyper#175]
Along with setting the font family and size, there's currently no way to set the font weight without adding custom css. I hope you can support this in the future.

**Comment by matthewconstantine** [comment]
In the meantime, here's a workaround:

```js
termCSS: 'x-row {font-weight: 100}',
```

**Comment by IamSwap** [comment]
Any idea on how to apply it on directory font weight?

**Comment by BobbieGoede** [comment]
I'm also still looking for a way to only apply this on directory font weight..

**Comment by asthas** [comment]
@matthewconstantine I tried adding font-weight property . But it seems like the hterm package doesn't support font-weight property. Should I overwrite hterm's package set method? Any other way around it? Any suggestion would be appreciated.

**Comment by drasbeck** [comment]
`termCSS: 'x-row {font-weight: 100}',` is deprecated in Hyper 2.1.1 (canary)

**Comment by mingjie-evbg** [comment]
Working in 2.0.4 (stable)
`termCSS: '.terminal {font-weight: lighter} .terminal .xterm-bold {font-weight: normal}'`

**Comment by brandon93s** [comment]
Added in #2669.

**Comment by chabou** [comment]
@brandon93s Thanks!
