### ISSUE TITLE
Scroll a window with keys

### ISSUE THREAD

**Issue by 0x80** [zeit/hyper#1750]
Is it possible to scroll a window using the keyboard? I can't seem to find any mention or plugins about this.

If not, I think it would be a welcome feature.

**Comment by MartyGentillon** [comment]
see https://github.com/zeit/hyper/issues/1540 and https://github.com/zeit/hyper/issues/42

**Comment by chabou** [comment]
I found that you can use key begin/end or page up/down but with `shift` key

**Comment by 0x80** [comment]
@MartyGentillon Thanks. Those issues are more about scrollbars with #1540 mentioning keys as a fallback, so no duplicates I suppose.

@chabou I am using a macbook, so I don't have those physical keys. The normal page up/down behaviour is fn+up/down but that doesn't have a mapping in Hyper. It acts the same as normal up/down. And the same goes for begin/end, which I guess would be fn+left/right.

**Comment by cbrwizard** [comment]
Shift+fn worked for me on mac, @0x80

**Comment by 0x80** [comment]
@cbrwizard Awesome! I don't think I've ever used shift+fn+key for a shortcut before, so I must have not even thought about trying that out 😄

**Comment by cbrwizard** [comment]
@0x80 yeah it's a bit counter intuitive but I'm used to all apps having different shortcuts so I've tried everything hehe
