### ISSUE TITLE
Windows 10: Run Shell As Administrator

### ISSUE THREAD

**Issue by jonwilks** [zeit/hyper#1752]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Build 15063.138
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jonwilks/adb66d80dc86cd7076a3ef43a943d4eb
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue

Hi, 

Feature Request OR Help Wanted: 

I spend a lot of time in elevated Command Prompt's & PowerShell's working with Docker. I really want to use Hyper but I have not found a good way to launch Hyper to Command Prompt or PowerShell with admin privileges.

I have tried the following several ways with different syntax (not shown in .hyper.js)and still come up short. Maybe someone can show me the way here or possibly we need a new feature.

- Track down cmd.exe and try to set to always admin. 
   - Fail
- Track down powershell.exe and try to set to always admin.
   - Fail
- Modify shortcuts to run as administrator & call shortcut from .hyper.js. 
   - Fail

Any help is appreciated & thanks for Hyper its very cool.

**Comment by MartyGentillon** [comment]
You might consider http://blog.lukesampson.com/sudo-for-windows

**Comment by jonwilks** [comment]
Thanks @MartyGentillon looks like a potential solution. I would also bank on MS addressing this in the next few years given there renewed focus on the shell.

**Comment by BlairLeduc** [comment]
Use Ctrl-Shift Left-Click when launching with the mouse, or if typing when searching from the start menu, Ctrl-Shift-Enter. You should see the User Account Control dialog to give Hyper permission to launch as admin.

**Comment by albinekb** [comment]
did you get this working? @jonwilks

**Comment by jonwilks** [comment]
@albinekb - I did not try sudo for Windows. I ended up going with ConEmu and configuring it to default to an admin PowerShell

**Comment by nnyegaard** [comment]
I know this is closed but if anybody wants a solution without changing.

Tested on Windows 10:

1. Open the start menu and search for hyper
2. Right click on the entry and select "Open file location"
3. Right click on the shortcut and select properties
4. Select Compatibility
5. Under settings check "Run this program as an administrator"

Now hyper will start in admin mode.

**Comment by HauntedSmores** [comment]
@nnyegaard Actually I think that's for running as admin when your in compatibility mode.

// previous steps
4. Click Advanced...
5.  Check "Run as Administrator"

**Comment by nnyegaard** [comment]
@HauntedSmores I don't see the "Run as Administrator" under Advanced. 

Is there any problems with running in compatibility mode?

Maybe under Security something needs to be changed?

**Comment by HauntedSmores** [comment]
@nnyegaard Really? Just to be clear its the Advanced button in the Shortcut tab. Its 1 of only two things in the advanced dialogue for me. I have no idea if there's any detriments to running in compatibility mode, but I wouldnt want to run something in a mode set for a different version of windows if I dont have to.

**Comment by nnyegaard** [comment]
@HauntedSmores Ah found it under Shortcut tab.

Thanks for the info!

**Comment by RichardBronosky** [comment]
In summary:

1. Open the Start menu and search for `hyper`
1. Right click on the entry and select "Open file location"
1. Right click on the shortcut and select "Properties"
1. Click "Advanced..." under the "Shortcut" tab
1. Click "Run this program as an administrator"

Now hyper will start in admin mode.
![screenshot_25](https://user-images.githubusercontent.com/13620/46488815-c90d8980-c7d1-11e8-845a-00086e1568c8.png)

**Comment by elangelo** [comment]
i would prefer it if hyper could just launch certain tabs as administrator. running everything as admin seems wildly over the top.

**Comment by MrAcalf** [comment]
[Using CMDER into hyper js ](https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration) you can run power shell as administrator without great efforts. Just configure cmder to run as administrator as default and then redirect hyper js to open it.

<img src="https://i.imgur.com/dCFqcnF.png" width="500" alt="Cmder on Hyper" />
