### ISSUE TITLE
Cursor position is incorrect when prompt includes multi-byte character

### ISSUE THREAD

**Issue by SSteve** [zeit/hyper#1754]
This is my bash prompt
`PS1='\[\033[0;33;44m\]\w\[\033[0m\] \! 🎵  '`

The cursor is positioned incorrectly in Hyper:

<img width="176" alt="screen shot 2017-04-20 at 11 28 03 am" src="https://cloud.githubusercontent.com/assets/523551/25246416/733e766c-25bc-11e7-80df-81171d53a99a.png">

It is correct in Terminal:

<img width="278" alt="screen shot 2017-04-20 at 11 28 39 am" src="https://cloud.githubusercontent.com/assets/523551/25246434/892c5818-25bc-11e7-9603-b2de7a561326.png">

If I change `🎵` to `$` in my prompt, the cursor is positioned correctly in Hyper:

<img width="137" alt="screen shot 2017-04-20 at 11 29 35 am" src="https://cloud.githubusercontent.com/assets/523551/25246487/abf09df0-25bc-11e7-8ecd-9ac8685e83cc.png">

-

Hyper 1.3.1
Electron 1.4.15
darwin x64 15.6.0

**Comment by chabou** [comment]
Duplicate #1506
