### ISSUE TITLE
experiencing ghost text when launching vim

### ISSUE THREAD

**Issue by lsternlicht** [zeit/hyper#1755]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- OS version and name:  Windows Server 2016

- Hyper.app version: 1.3.1

- Link of a Gist with the contents of your .hyper.js: [Gist](https://gist.github.com/lsternlicht/d84c741cde937e0a36bc50596aae6c7b)

- Relevant information from devtools (CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere): None

- The issue is reproducible in vanilla Hyper.app: Yes

## Issue
I am seeing ghost text after launching vim with a file parameter.

Here is an example:

![hyper_ghosting_text](https://cloud.githubusercontent.com/assets/128432/25249867/7dc55e50-25e1-11e7-93b7-d2cfa3341a94.gif)

**Comment by khoanguyen96** [comment]
something similar is happening for me as well. occurs when i type text that wraps to the next new line.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
