### ISSUE TITLE
Problem with write long text/command in console. Hyper does not jump to a new line

### ISSUE THREAD

**Issue by Zx-EvM** [zeit/hyper#1756]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Version 1703 Build 15063.332
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Zx-EvM/972184c95f9eb17da34883955f7c345f
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

I record a gif to show what happens when I write long text or command in console:

![demo](https://cloud.githubusercontent.com/assets/20873402/25654882/a4026110-2fa7-11e7-93fa-1f571640ffaf.gif)

I use Windows 10 Subsystem for Linux and ZSh.

My `.bashrc` file on gist https://gist.github.com/Zx-EvM/d7690301fca4df0fa9b5b1b40ffd1c55#file-bashrc-L5

So, when I run hyper I get the ZSh shell on startup. But if I use default Windows CMD in `.hyper.js` config:

```
shell: 'C:\\Windows\\System32\\cmd.exe',
```

and run bash/zsh manually by using `bash` command this issue not present (not present with default bash shell and not present with ZSh shell).

I was try to reproducible this without any hyper plugins and nothing changed, also try to disable ZSh on startup.

## Edit:

My screen resolution `1920x1080`.

In my config I have `windowSize: [1171, 688],`. If I set a lower resolution, for example: `windowSize: [770, 470],` this issue not present.

But it will be cool if in the future it will be fixed.

**Comment by mrpeu** [comment]
I have the same problem, independent of the resolution, on macOS Sierra, every versions of Hyper I tried 1.4.3-2.0.3.

Except this, really sweet project!

**Comment by Zx-EvM** [comment]
Seems like this issue not present in Hyper 1.4.8 https://github.com/zeit/hyper/releases/tag/1.4.8 on Windows 10. @mrpeu can you reproduce this bug in Hyper 1.4.8 on your macOS Sierra?

**Comment by mrpeu** [comment]
@Zx-EvM Yes it was still happening on 1.4.8. I'm now on 2.0.3 and it is still there.

**Comment by lucleray** [comment]
I'm seeing the same issue.

macOS sierra 10.12.6
hyper 2.0.0

![demo-bug-hyper](https://user-images.githubusercontent.com/6616955/38990127-5c027660-43d9-11e8-9da5-1e08e2ebb3b0.gif)

**Comment by Stanzilla** [comment]
I would say that this is a configuration issue with your shell, I just tried it with zsh on Windows 10 and it worked just fine, see https://dl.dropboxusercontent.com/s/2l5kc8awep62oj4/2018-04-24_01-35-40.webm

**Comment by mwheeler** [comment]
Just giving a little feed-back before I un-sub from this issue (as I no longer use Hyper).

This issue was definitely still present on Windows 10 w/ 2.0.0 as of February... I had this same issue since last year, and it went unfixed for so long that I don't even use Hyper anymore as a result of this issue making quite a lot of applications unusable (vim, autocomplete, writing long paths, tmux via ssh for remote terminals whose size was larger than the hyper terminal, etc etc).  I was never able to find a work-around.

**Comment by shellj** [comment]
I have the same issue on Windows 10 Subsystem for Linux, and i test, when the shell is `bash`, it works fine, but when i changed to `zsh`, i got the issue.

**Comment by ThYpHo0n** [comment]
+1 happens to me too on latest Hyper stable on Win10 with WSL

```
shell: 'C:\\Windows\\System32\\wsl.exe',
plugins: [
    'hyper-opacity',
    'hyper-pane',
    'hyper-hide-scroll',
],
```

**Comment by itshikanov** [comment]
happens to me too on 3.3.0 stable.

        shell: 'C:\\Work\\cygwin-test\\Cygwin.bat',
