### ISSUE TITLE
colors for linux subsytem on windows 10 are not editable and have a lot of background red

### ISSUE THREAD

**Issue by xtianus79** [zeit/hyper#1758]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
windows 10 creators update
- **Hyper.app version**: 
latest
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

my colors when entering into the linux subsystem are weird and have a red background on the lettering... how do I get rid of that.  it is not on any of my other cmd's

**Comment by MartyGentillon** [comment]
Please provide some screenshots.

**Comment by sladiri** [comment]
This seems the same as https://github.com/zeit/hyper/issues/1706

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
