### ISSUE TITLE
Plugins failing to install

### ISSUE THREAD

**Issue by fatmanmclone90** [zeit/hyper#1759]
I've installed plugin 'hyperline' by editing the hyper.js file

 plugins: ["hyperline"]

On re-launching Hyper, it throws errors:

`799 verbose stack Error: systeminformation@3.17.2 install: `node-gyp rebuild`
799 verbose stack Exit status 1
799 verbose stack     at EventEmitter.<anonymous> (C:\Users\chris\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
799 verbose stack     at emitTwo (events.js:106:13)
799 verbose stack     at EventEmitter.emit (events.js:191:7)
799 verbose stack     at ChildProcess.<anonymous> (C:\Users\chris\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
799 verbose stack     at emitTwo (events.js:106:13)
799 verbose stack     at ChildProcess.emit (events.js:191:7)
799 verbose stack     at maybeClose (internal/child_process.js:886:16)
799 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
800 verbose pkgid systeminformation@3.17.2
801 verbose cwd C:\Users\chris\.hyper_plugins
802 error Windows_NT 10.0.14393
803 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chris\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
804 error node v6.10.2
805 error npm  v4.0.5
806 error code ELIFECYCLE
807 error systeminformation@3.17.2 install: `node-gyp rebuild`
807 error Exit status 1`

Using Windows 10, node v6.10.2, npm 4.0.5, hyper 1.3.1

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
