### ISSUE TITLE
Cancel issue

### ISSUE THREAD

**Issue by colinwphillips** [zeit/hyper#1760]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **Latest version**: 

## Issue

The download link is broken on the website and in the readme.md.
The download link was broken but no longer is. Please cancel issue.

**Comment by CodeTheory** [comment]
It _is_ or _isn't_ broken?

**Comment by colinwphillips** [comment]
No, sorry it is not. It was only down and linked to a 404 page on your site for 5 minutes.
