### ISSUE TITLE
tput customization issue with hyper (Using MING64/git-bash Console)

### ISSUE THREAD

**Issue by Tchoupinax** [zeit/hyper#1765]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1
- **Hyper.app version**: 1.3.1 (Downloaded this morning)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Tchoupinax/81f5fdfaeb9673b07639487a4e6639fb

## Issue

Hello, 

I Would customize my MINGW64 console throught Hyper and i found an issue.
I used this script found on the internet for the test : 
```bash 
#!/bin/bash
#tputcolors

echo
echo -e "$(tput bold) reg  bld  und   tput-command-colors$(tput sgr0)"

for i in $(seq 1 7); do
  echo " $(tput setaf $i)Text$(tput sgr0) $(tput bold)$(tput setaf $i)Text$(tput sgr0) $(tput sgr 0 1)$(tput setaf $i)Text$(tput sgr0)  \$(tput setaf $i)"
done

echo ' Bold            $(tput bold)'
echo ' Underline       $(tput sgr 0 1)'
echo ' Reset           $(tput sgr0)'
echo
```
On my git-bash console i have the expected result : 
![image](https://cloud.githubusercontent.com/assets/9136206/25473365/84c45c26-2b2f-11e7-9f29-804d08d07d2a.png)

Howerver with Hyper i have this : 
![image](https://cloud.githubusercontent.com/assets/9136206/25473400/a3f82e2e-2b2f-11e7-854f-5e5cbe6db6c0.png)

As you can see, "underline" does not work at all... and some color can't be "bold".
How can i resolve this issue. I would like to use bold magenta :3 

Thank you for your time.
Regards,

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
