### ISSUE TITLE
Unresponsive terminals and window, when closing tab with Ctrl+D

### ISSUE THREAD

**Issue by joakin** [zeit/hyper#1766]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - Version 1.3.1 (1.3.1.1628)
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX 10.11.5 (15F34)
- **Hyper.app version**: Version 1.3.1 (1.3.1.1628)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/joakin/d22afb83f702b1971ede77549fbfcf27
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
`Uncaught TypeError: Cannot match against 'undefined' or 'null'.effect @ bundle.js:formatted:1544`
- **The issue is reproducible in vanilla Hyper.app**: Yes. Removed my .hyper.js and still broke

### Steps
1. Open hyper (check responsiveness with `ls`)
2. Open a tab with Cmd+T (check responsiveness with `ls`)
3. Close tab with Ctrl+D
4. Back to initial tab. Tab is unresponsive. Can't write on it. Cmd+T opens new tabs but they don't initialize.
  * Problem persists until the whole window is closed.

![sessions-undefined-after-ctrl-d](https://cloud.githubusercontent.com/assets/657839/25475247/65e389ce-2b36-11e7-8a0b-86a7afc07277.gif)

### Debugging info
When checking the devtools, there's a typeerror comming from the line

```js
const {shell: L} = U().sessions.sessions[F]
```

Where F (the session id) doesn't exist in the sessions part of the state tree:

![screen shot 2017-04-27 at 10 40 10 am](https://cloud.githubusercontent.com/assets/657839/25475319/ac87d65a-2b36-11e7-8e2c-246d4feccb89.png)

So the destructuring blows up.

---

This behavior worked on previous versions if I recall correctly, given I always close tabs with ctrl+D and didn't notice it before. (I cycle to hyper seasonally to see how it is faring so I'm not sure what the previous version I used extensively was).

Let me know if you need more info!

**Comment by torzuoliH** [comment]
Same behavior using Cmd+w ?

**Comment by joakin** [comment]
Sorry forgot to mention it. Closing using CMD+W doesn't seem to show the
problem.

**Comment by andrroy** [comment]
@joakin I had the same problem as you, but it got fixed in #1698. What happens if you pull down the latest version from master and run it? Do you still have the same problem?

**Comment by joakin** [comment]
@andrroy Tried latest master (0797f38) and it seems to work fine, so it seems fixed as you suspected!

Going to close then, I'll wait for a release 😄 . Thanks!
