### ISSUE TITLE
Keep windows distribution

### ISSUE THREAD

**Issue by Fedeorlandau** [zeit/hyper#1768]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX Sierra
- **Hyper.app version**: Last
## Issue
Hi guys, how are you?

I want to know if there is any way to keep the windows distribution. I would like to start my hyperterm split on three.
Is this possible?

Thanks!

**Comment by zusamann** [comment]
Have you tried this? https://www.npmjs.com/package/hyperlayout

**Comment by Fedeorlandau** [comment]
Thanks!
