### ISSUE TITLE
Blows up when trying to print a long line.

### ISSUE THREAD

**Issue by mruhlin** [zeit/hyper#1770]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS Sierra 10.12.3
- **Hyper.app version**: 1.3.1.1628
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mruhlin/d099e0dd089c53eb49b1948b114b1267
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: "Uncaught TypeError: Cannot read property 'wcNode' of undefined"  (uh, it's minified, but the code looks like it's trying to do something related to splitting the long string into multiple lines.
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I'm working in a ruby cli and printing large objects.  At a certain size, the UI just stops printing mid-string and hangs.  I've tested it out locally just by making big strings, and it appears to be somewhat varied in how big the line is before it blows up.

- open new hyper window
- open new ruby console: `irb`
- print a string that is made up of 1000 Xs: `puts "X" * 1000`.  This one works
- print a string that is made up of 10000 Xs `puts "X" * 10000`. This one breaks.  UI appears to hang.  Opening developer tools shows the console error "Uncaught TypeError: Cannot read property 'wcNode' of undefined".

Substitute larger numbers if 10000 works for you.  In my testing I've seen it handle 5000 just fine some times and blow up at 1250 other times.

Note that I am able to echo large lines from bash, cat a long single-line file, etc no problem.  So there might be something unique to ruby going on here?

**Comment by mruhlin** [comment]
Found #1681, which seems to be the same as this.  
Not sure if I agree with the resolution there linking it to #687.  #687 is about things being slow whereas this is about things outright breaking.

**Comment by mruhlin** [comment]
You know what, I might need to take back my last comment.  I tried this again on 1.3.2, and am no longer able to reproduce the exception.  I mistook slow output for another occurrence of the exception.  It eventually finished.

**Comment by chabou** [comment]
Reproduced on v1.3.3.
I'm reopening it because of your good and simple HTR!
And #687 seems to be more a general performance question.

**Comment by jaller94** [comment]
`echo {0..10000}` hangs up Hyper for many minutes. The macOS terminal doesn't even lag.

`echo {0..1000}` takes about 5 seconds for me to display.

Output of `echo {0..1000}`:
```
real    0m0.047s
user    0m0.037s
sys     0m0.001s
```

**Comment by jaller94** [comment]
Just tried the pre-release 2.0.4.

It has very little overhead for displaying long lines.

`echo {0..1000000}` is not a problem anymore.

**Comment by chabou** [comment]
Thank you for you feedback
