### ISSUE TITLE
Garbled text

### ISSUE THREAD

**Issue by tjru** [zeit/hyper#1771]
![image](https://cloud.githubusercontent.com/assets/16164908/25512891/a65ea51a-2c03-11e7-9ccc-8ddce3e6605b.png)

-

Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.14393

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
