### ISSUE TITLE
Unix based shell on Windows?

### ISSUE THREAD

**Issue by samuelmrp** [zeit/hyper#1773]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

First of all, sorry, not like a real Issue, is more like a question/suggestion.

There is any plugin or any way to use Hyper like a unix based bash (git bash for windows) ? Except for the Windows Subsystem option?

I have the git bash for windows but love the look and feel of Hyper!

Thank you,
 Samuel

**Comment by lucasbrewer** [comment]
Yes, there is a way.
Change the .hyper.js file (Edit->preferences) where it says shell add the path to git-bash's shell "*path-to-git*\bin\sh.exe"

Hope this helps

**Comment by tvbarajas** [comment]
If you want to use the "Bash on Windows on Ubuntu" feature with Hyper, make the following changes in your .hyper.js file:
```
shell: 'C:\\Windows\\System32\\bash.exe',
shellArgs: ['--login'],
```

-Travis

**Comment by Zx-EvM** [comment]
@tvbarajas known issue https://github.com/zeit/hyper/issues/1756

**Comment by spences10** [comment]
Hi, I found [this](#1252) which points hyper to Git allowing for those commands 👍 

```javascript
    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    shell: 'C:\\Program Files\\Git\\git-cmd.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],
```

Thanks @faleij 👍

**Comment by samuelmrp** [comment]
Both solutions of @spences10  and @lucasbrewer worked for me, but there is a problem when I commit, the vi or vim don't work correctly, when I try to use arrow keys to navigate through the text it show an error "E349: No identifier under cursor" I will spend some time trying to find a workarround but if anyone has the solution, please share! :)

Thank you all

**Comment by dustincjensen** [comment]
Is the "git shell" compatible? I like the fact that when you go into a git folder it gives you the status of the directory in the prompt.

**Comment by samuelmrp** [comment]
Yes it is!

Except for that bug I mentioned.

**Comment by KadeG** [comment]
@samuelmrp Do I have also experienced the bug with vi/vim when using the git bash shell. Did you find a workaround?

**Comment by Zx-EvM** [comment]
https://github.com/zeit/hyper/issues/2385

**Comment by samuelmrp** [comment]
Unfortunately not :(

 

 




Samuel Pereira
Desenvolvedor .NET
 <mailto:samuel.pereira@asteria.com.br> samuel.pereira@asteria.com.br
Fone: +55 (11) 3645-3720 / Cel: +55 (35) 8808-2150
