### ISSUE TITLE
Gaze is adding all folders in HOME to watch list

### ISSUE THREAD

**Issue by paulbouwer** [zeit/hyper#1776]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

<p>

- **OS version and name**: Windows 10 (16179)
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Default 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Relevant to the following `hyper` issues:
- [#1688 - Can't install on windows 10](https://github.com/zeit/hyper/issues/1688)
- [#1568 - EPERM: operation not permitted, lstat](https://github.com/zeit/hyper/issues/1568)
- [#1499 - Unable to run Hyper 1.1.0 on macOS](https://github.com/zeit/hyper/issues/1499)
- [#1136 - Unable to launch hyper 1.0.0 even after reinstall in Ubuntu 14.04](https://github.com/zeit/hyper/issues/1136)

Relevant to the following `gaze` issues:

- [#214 - Gaze.prototype._addToWatched repeating readDir of same directory on each call](https://github.com/shama/gaze/issues/214)
- [#239 - fs.lstatSync doesn't handle specific Windows REPARSE POINTS](https://github.com/shama/gaze/issues/239)

About 2 weeks ago I started seeing the following when starting **hyper**. I wasn't sure what had changed. It was not a new **hyper** version, but I had just upgraded to the **16176** Windows Insider build - although I'm also sure that didn't cause it - confused ... I started investigating.

![image](https://cloud.githubusercontent.com/assets/318622/25552644/b16bc89a-2ce2-11e7-95ce-23a134670b1f.png)

The only item being added to **glaze** from **hyper** for watching seems to be the `.hyper.js` file in the user's `HOME` folder. But I noticed (after putting tons of logging into **glaze**) that it added the `.hyper.js` file to its watch list, but then also added all the sub-folders in my `HOME` folder too. This is caused by the following logic within **glaze**:

- [shama/gaze/blob/v1.1.2/lib/gaze.js#L272-L298](https://github.com/shama/gaze/blob/v1.1.2/lib/gaze.js#L272-L298)

Once **glaze** starts watching additional folders in the `HOME` folder, there are a number of permission and other types of errors that start happening for various users. In my case above, the **OneDrive** folders have a specific `REPARSE POINT` which causes the `fs.lstatSync` call made by **glaze** to throw a `EINVAL` error. I'm adding issues to the **glaze** and **node** repos for this.

If **hyper** could ensure that only the `.hyper.js` file was watched, then I believe that all of the referenced issues would be resolved.

**Comment by MartyGentillon** [comment]
With the new configuration setup, this shouldn't cause a problem after https://github.com/zeit/hyper/pull/1509.  (Config files are moving into a directory.)

**Comment by albinekb** [comment]
We don't use `gaze` anymore 👍

**Comment by darsain** [comment]
@albinekb any ETA on when this might ship? been annoyed by error popups this issue is triggering for half a year now :)

**Comment by albinekb** [comment]
@darsain can you please try hyper 2.0, read how to change your updateChannel at https://zeit.co/blog/canary 👍 🙏 If that doesn't resolve it, let's reopen 👍
