### ISSUE TITLE
Cursor keep blinking when move

### ISSUE THREAD

**Issue by ooJerryLeeoo** [zeit/hyper#1777]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS sierra 
- **Hyper.app version**: 1.3.1 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [here](https://github.com/ooJerryLeeoo/dot-files/blob/master/.hyper.js) 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N 
- **The issue is reproducible in vanilla Hyper.app**: `Is vanilla` 

## Issue

Here's an example:

![2017-04-30 08_48_11](https://cloud.githubusercontent.com/assets/20783502/25560435/125b3b3c-2d87-11e7-8c40-442c68d8a846.gif)

**Comment by drasbeck** [comment]
Issue is present in Hyper 1.4.8 (stable).

**Comment by chabou** [comment]
Fixed in canary
