### ISSUE TITLE
Possible wrong value in the LANG variable

### ISSUE THREAD

**Issue by borela** [zeit/hyper#1778]
This [line](https://github.com/zeit/hyper/blob/aa7e79a0399fddefe67c248a0d5a9b13bb27659b/app/session.js#L27) sets the `LANG` variable to `en_us.UTF-8`, but it should be `en_us.UTF8` without the hyphen.

My mother tongue is portuguese and by having the hyphen, causes text wrapping issues when the text has special characters `áãéíóú` like so:
![screenshot 2017-04-30 21 58 48](https://cloud.githubusercontent.com/assets/11317458/25569639/4a97ed3c-2df1-11e7-8a86-ef595fb7d733.png)

When I manually set the `LANG` variable in the `.hyper.js` config, it fixed those issues. My settings are:

```js
module.exports = {
  config: {
    env: {
      LANG: 'en_us.UTF8',
      TERM: 'msys'
    },
    fontSize: 12,
    fontFamily: 'monaco',
    cursorShape: 'BLOCK',
    padding: '12px 14px',
    cursorColor: '#f06292',
    shell: 'C:\\Program Files\\Git\\git-cmd.exe',
    shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],
  },
  plugins: [
    'hyper-blink',
    'hyperterm-tabs',
    'hyperterm-paste',
    'hyperterm-tab-icons',
    'hyperterm-material-theme'
  ],
  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
}
```

Windows 10 x64
I didn't test it on Linux or Mac.

**Comment by Stanzilla** [comment]
https://perlgeek.de/en/article/set-up-a-clean-utf8-environment looks like the hyphen is correct?

**Comment by borela** [comment]
[glibc should normalize both values](https://superuser.com/questions/999133/differences-between-en-us-utf8-and-en-us-utf-8) that  so `UTF-8` would have the same effect as `utf8`, but that is not happening on Windows 10. If I use `en_US.UTF-8` it has the same effect of just `en_US` and the wrapping issue appears.

I am not sure if this is an issue on how environment variables are passed or in a DLL from windows.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
