### ISSUE TITLE
Nano error on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by cbentle** [zeit/hyper#1779]
When nano text editor is open you cannot use ctrl+x to close out nano.
Simply launch hyper, run the bash command on Windows 10 using Bash on Ubuntu on Windows, run "nano hello.cpp" once nano is open try to exit nano using ctrl+x, nothing happens.

-

Hyper 1.3.1
Electron 1.4.15
win32 x64 10.0.14393

**Comment by ppot** [comment]
Closing for #1424
