### ISSUE TITLE
.bashrc should be used by default on Linux

### ISSUE THREAD

**Issue by WoodyWoodsta** [zeit/hyper#178]
Ubuntu 16.04 - `bash`

Hyperterm appears to be sourcing `.bash_profile` out of the box, but not the `.bashrc` found in the home directory. I'd say that `.bashrc` should be the first shell config to be sourced.

**Comment by Tyriar** [comment]
bash appears to be getting launched as a login shell.

**Comment by Tyriar** [comment]
`--login` should probably be an option that's off by default https://github.com/zeit/hyperterm/blob/master/session.js#L23

**Comment by WoodyWoodsta** [comment]
Removing that flag works for me :+1:

**Comment by efegurkan** [comment]
#572 solves it. You can add -i as shellargs on current master.

**Comment by flybayer** [comment]
I think this can be closed, right?
