### ISSUE TITLE
JOE Editor and Hyper, disabling shortcuts for proper use

### ISSUE THREAD

**Issue by ClaymoreTF2** [zeit/hyper#1782]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Manjaro Linux x86_64
- **Hyper.app version**: latest

## Issue

I have problems using the JOE Editor, which is my main code/text editor.
When pressing CTRL+K my terminal clears itself, and it's one of the basic modifiers in that editor.
Is there a way to completely disable hotkeys temporarily, so that the editor becomes usable again?

**Comment by ppot** [comment]
This will be resolved once #1509 lands.

**Comment by ppot** [comment]
close in #1876
