### ISSUE TITLE
horizontal split - window resize does not keep cursor within window

### ISSUE THREAD

**Issue by rdewolff** [zeit/hyper#1785]
## Info 

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.3
- **Hyper.app version**: Version 1.3.1 (1.3.1.1628)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/rdewolff/58f29aa7cc3c5a282e15793d0fa2d387
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A - **The issue is reproducible in vanilla Hyper.app**: ?

### Actual state

When splitting the pane horizontally and resizing the window, the cursor disappear. Seems like the re-render of the windows content is not done correctly on the part on the bottom.

### Wanted state

When the windows is split horizontally and resized to a smaller size, the cursor should always stay visible.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
