### ISSUE TITLE
Buffer issue when using window manager

### ISSUE THREAD

**Issue by lesseradmin** [zeit/hyper#1786]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.12.5 Beta (16F71b) + macOS Sierra
- **Hyper.app version**: 1.3.1 (1.3.1.1628)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

When the Hyper window gets moved around too much there is a buffer issue that results in the following:
![image](https://cloud.githubusercontent.com/assets/7121943/25731303/a54d8004-310a-11e7-9b2e-9d7863836685.png)
On the right side of the window there are extra prompts.

I thought initially that this could be because of the window manager or because of zsh or tmux, but I tested it with iTerm and the MacOS Terminal.app and this did not happen.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
