### ISSUE TITLE
Clickable http links in the term

### ISSUE THREAD

**Issue by alexandrebodin** [zeit/hyper#1787]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X El Captain v 10.11.6
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [my config](https://github.com/alexandrebodin/dotfiles/blob/master/.hyper.js)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Hello there !

This issue is more of an enhancement idea : **I would love to be able to click a http link directly in the term when `Cmd`is pressed.**

This behaviour is available in iTerm. 

I would love to open a PR if you are open to it !

**Comment by albinekb** [comment]
This does what you're asking for: https://www.npmjs.com/package/hyperlinks

see the awesome https://github.com/bnb/awesome-hyper for more!

**Comment by alexandrebodin** [comment]
@albinekb Great thanks !

**Comment by albinekb** [comment]
🎉  @alexandrebodin
