### ISSUE TITLE
Regression in Windows titlebar design compared to Mac OS

### ISSUE THREAD

**Issue by 19lmyers** [zeit/hyper#1795]
The old Windows design detailed in this pull request appeared to be much more functional than the current one. However, it appears it was removed because it caused an issue with the buttons not being clickable.

Why can't you just flag the buttons as non-draggable on the old design, so they can receive click events?
The main thing irritating me about this app right now is that the tab bar is below the title bar, an obvious regression from the Mac OS version.

**Comment by Stanzilla** [comment]
Which PR are you talking about?

**Comment by 19lmyers** [comment]
Sorry, the link didn't copy correctly:

https://github.com/zeit/hyper/pull/946#

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
