### ISSUE TITLE
Session persistence

### ISSUE THREAD

**Issue by a-x-** [zeit/hyper#1797]
Is it easily implementable to persist session by name with tabs and panes layout and, opened directories with directories and commands history and launched utilities?

JFYI, there is partial persistence in iTerm for layout and directories.

**Comment by ppot** [comment]
Is PR #945 what you want?

- Commands history. Not doable.
- Lunched utilities. NO since you're script are started by hand.

**Comment by a-x-** [comment]
Whoa!
