### ISSUE TITLE
Win10 Installer assertion failed for winpty.dll (1.3.1)

### ISSUE THREAD

**Issue by jollygardener** [zeit/hyper#1798]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 1511 (build 10586.873)
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I am installing hyper for the first time (v1.3.1) on Win10 and getting an error message from the installer (attached).  I have node v6.10.2 and npm 4.6.1.
![screen shot 170426 at 09 20 am](https://cloud.githubusercontent.com/assets/24298415/25436855/7950aa32-2a8c-11e7-92c2-8d6dd8809e66.PNG)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
