### ISSUE TITLE
Older sessions become unusable after closing newer sessions with "exit"

### ISSUE THREAD

**Issue by kkuhle** [zeit/hyper#1800]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

In Windows: if I open 2 or more tabs > type exit until I return to the first session > typing is not view able

In Mac: same behavior.  More annoyingly, if I split the window vertically or horizontally, behavior is a bit more sporadic.  When typing exit to close sessions at some point (usually quickly) all terminals become unusable as in I am unable to view any text.

**Comment by chabou** [comment]
Duplicate #1628 and normally already fixed in master.

**Comment by kkuhle** [comment]
Thanks.  Sorry for reporting the duplicate.  I'm a bit of a noob to github.  Does fixed in master mean that the fix will be included with the next release or is there build available that I would be able to test this out?

**Comment by chabou** [comment]
No problem for duplicates. This issue has many way to occurs (`ctr+d` or `cmd+w` or `exit`)

'Fixed in master' means that fix has been integrated in master branch and will be landed with next release. 
You can test last build for current master here for Windows: https://ci.appveyor.com/project/appveyor-zeit/hyper/build/1.0.757/artifacts

**Comment by kkuhle** [comment]
I tested the windows hyper and it seems to work great. I am using this on my Mac more right now. Any chance there is a build for Mac I could try?
