### ISSUE TITLE
Hyper window has gone, and wont come back

### ISSUE THREAD

**Issue by mrsideshowjack** [zeit/hyper#1802]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: win10 1607
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default (fresh install)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: Vanilla

## Issue

Some time ago, I think after I unplugged a monitor or something, the Hyper window went 'off screen', however trying to get it back has proved impossible. I'm not sure if this is a Hyper issue or a issue with windows in general, but this has never happened to any other programs. 

Things I have tried: 
* `alt + tab`  'ing to Hyper and then `win + up/down/left/right`
* cascading all windows
* show windows stacked
* uninstalling and reinstalling hyper

[screencap of issue](https://d3dr1ze7164817.cloudfront.net/items/3N3a0L051r3H220C3F3l/Screen%20recording%202017-05-09%20at%2011.22.41%20AM.gif)

[Trying to fix with cascade windows](https://cl.ly/060u2y1k1t1W/Screen%20recording%202017-05-09%20at%2011.09.44%20AM.gif)

**Comment by chabou** [comment]
Thank you for your feedback.
Closed in favor of #1869
