### ISSUE TITLE
Underline cursor disappeared after upgrade to hyper 1.3.2

### ISSUE THREAD

**Issue by ooJerryLeeoo** [zeit/hyper#1803]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS sierra 10.12.4 
- **Hyper.app version**: 1.3.2 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Here](https://github.com/ooJerryLeeoo/dot-files/blob/master/.hyper.js) 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A 
- **The issue is reproducible in vanilla Hyper.app**: `Is Vailla` 

## Issue

The underline cursor disappeared after upgrade to hyper 1.3.2

**Comment by chabou** [comment]
Reproduced.
I've have a wrong height on `cursor-node`: 1397px (whatever window size is)

**Comment by slavapavlutin** [comment]
I have the same issue. In my case it seems like `cursorNode` height is calculated based on the baseline of `scrollPort`, which results in it being too large.

![screen shot 2017-05-10 at 2 06 04 am](https://cloud.githubusercontent.com/assets/854141/25876407/9c7808d6-3525-11e7-8643-a572daaedcb2.png)

**Comment by samholmes** [comment]
Same issue.

**Comment by chabou** [comment]
You can temporaly fix it by adding this to your config:
`termCSS: '.cursor-node{height:14px !important}',`

**Comment by slavapavlutin** [comment]
@chabou  where `height` equals your `fontSize`.

**Comment by chabou** [comment]
yes obv.
Thank you for this precision and for having precisely pointing the source of this regression.

**Comment by ryanlloydfrench** [comment]
Whoops, I just created an issue for this. Must have been writing the same time as you..

**Comment by bryantee** [comment]
With `'hyper-materialshell'` plugin set, I can't see cursor as BLOCK or UNDERLINE, even with the fix  @chabou suggested.

**Comment by jake-wies** [comment]
Just noticed this today and came to open an issue. Originally thought it was something with the [hyper-blink](https://github.com/amio/hyper-blink) plugin. Will try the workaround 👍
