### ISSUE TITLE
When cursorShape is 'UNDERLINE', cursor disappears.

### ISSUE THREAD

**Issue by ryanlloydfrench** [zeit/hyper#1804]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **10.12.4 macOS Sierra** 
- **1.3.2** 
- **https://gist.github.com/ryanlloydfrench/e30d17c0d9e109aeadf93586d6b012f2** 
- **Is Vanilla** 

## Issue

I just updated to a new version of Hyper '1.3.2' and my cursor disappeared after updating. I noticed that the cursor only disappears when `cursorShape: 'UNDERLINE'` in .hyper.js

**Comment by chabou** [comment]
Duplicate #1803
