### ISSUE TITLE
UNDERLINE cursor not visible

### ISSUE THREAD

**Issue by sublistic** [zeit/hyper#1806]
After updating to the latest version, `cursorShape: 'UNDERLINE'` does not work - there is no cursor visible. Other options (BLOCK & BEAM) display the cursor fine.

It might have something to do with the height of the cursor, which seems to be set to 1797px, whereas other cursors have a height of 18px.

-

Hyper 1.3.2
Electron 1.4.16
darwin x64 15.6.0

**Comment by Bertieio** [comment]
Im having the same problem with block. It flashes up on the screen the length of the console window then disappears

**Comment by chabou** [comment]
Duplicate #1803. You'll find a workaround there
