### ISSUE TITLE
Glitches while displaying Powerline fonts in tmux session

### ISSUE THREAD

**Issue by jsynowiec** [zeit/hyper#1815]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.4
- **Hyper.app version**: 1.3.2 (1.3.2.1744), 1.3.3 (1.3.3.1754)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/jsynowiec/142de1114b2e9584e0f5ef4b0591b19e)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

While displaying tmux session there is a problem with Powerline fonts (see attached screenshot). Everything is more ore less displayed correctly without active tmux session.

Tested with Hack, Inconsolata and Fira Code fonts. Results are the same.

![screenshot 2017-05-12 11 25 51](https://cloud.githubusercontent.com/assets/1029142/25992581/4561fcee-3707-11e7-8200-63fe23e6f7e4.png)

**Comment by KMontag42** [comment]
Same thing on Ubuntu 16.04 as well (vanilla Hyper)

**Comment by jsynowiec** [comment]
Updating tmux to 2.5 via Homebrew removed this issue. Closing.
