### ISSUE TITLE
Bump version for 1.3.3 in app/package.json

### ISSUE THREAD

**Issue by aabmass** [zeit/hyper#1818]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Arch Linux: 
- 1.3.3: 
- Is Vanilla: 

## Issue

Looks like the version didn't get bumped in `app/package.json` for 1.3.3: https://github.com/zeit/hyper/blob/1.3.3/app/package.json#L5

This causes "Version 1.3.3 is available. Performance improvements 🚀" to show up when you start the app.

**Comment by aabmass** [comment]
Oh, I see it was already bumped in 0080f1da81373964b3631065e27cbf4b7a535d0d but that was after the release and 1.3.3 tag

**Comment by albinekb** [comment]
it's 1.3.3 in master now, and next release we'll do it right 👍
