### ISSUE TITLE
Hyper goes into web browser when command is a URL. Intended?

### ISSUE THREAD

**Issue by davidbrazdil** [zeit/hyper#1820]
Hi,
Just noticed that when I execute a command that is a URL, e.g. "http://www.google.com/". Hyper replaces the terminal tab with a browser window and loads the web page. There's no address bar and no obvious way how to go back to the terminal. Is this intended?

Cheers,
David

**Comment by davidbrazdil** [comment]
Version is 1.3.2.1744

**Comment by ppot** [comment]
Yes this is intended and will be moved to plugin later on. You can close this by clicking the pane and closing it with `ctrl+c`

**Comment by albinekb** [comment]
duplicate of https://github.com/zeit/hyper/issues/1761
