### ISSUE TITLE
Consume massive battery (caused by hyperpower)

### ISSUE THREAD

**Issue by fuchenxu2008** [zeit/hyper#1823]
-When Hyper is running, the battery icon on the status bar of my Mac indicates that Hyper.app is using massive energy.

Hyper 1.3.3
Electron 1.4.16
darwin x64 16.5.0

**Comment by chabou** [comment]
Please use issue template...

Is it reproductible with vanilla Hyper?
Is there a command running in Hyper?

**Comment by fuchenxu2008** [comment]
Sorry, I'm new here...
- I'm using the latest version of Hyper.app.
- I have plugins 'hyper-snazzy','hyperyellow','hyperpower' installed.
- I can reproduce the issue even without any commands running.

**Here is the issue:**
![](https://o6wamt4oj.qnssl.com/8c9130586964e2f99841260e094ee4fd.png)

**Comment by chabou** [comment]
In this issue https://github.com/zeit/hyper/issues/474, some users have fixed this by removing `hyperpower`. Can you try ?

**Comment by fuchenxu2008** [comment]
Okay, thanks for that!

**Comment by chabou** [comment]
Can you confirm that your issue is related to ˋhyperpower`?

**Comment by fuchenxu2008** [comment]
Yeah, thanks. It turns out to be the problem. When that plugin was enabled, the energy impact was stabilized at about 60-70. After I removed it, it is at most no more than 5 now. (No command running).

**Comment by fuchenxu2008** [comment]
### Here's the screenshot for illustration: 
![energydrain](https://cloud.githubusercontent.com/assets/15119847/26052119/fdf359ec-3996-11e7-9f54-a9736e5ab446.jpg)

**Comment by fuchenxu2008** [comment]
### Here's another thing:
I tried to use PopClip and Alfred on my Mac to implement quick actions with Hyper, but since it is built with Electron and it doesn't support AppleScript. I came up with an alternative and developed this.
[Hyper-PopClip-Alfred-Extension](https://github.com/fuchenxu2008/Hyper-PopClip-Alfred-Extension) 
Where should I share it? Thanks.

**Comment by albinekb** [comment]
Sweet! @fuchenxu2008 ✨✨✨ here is the place: https://github.com/bnb/awesome-hyper

**Comment by albinekb** [comment]
Closing this issue as you got it down by removing **hyperpower** 👌

**Comment by fuchenxu2008** [comment]
Ok, thanks !😀
