### ISSUE TITLE
fontSize option does not work

### ISSUE THREAD

**Issue by VijayVj7** [zeit/hyper#1824]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by VijayVj7** [comment]
I've seen the latest version of the application.Felt inconvenient in seeing the appearance with such small fonts

**Comment by chabou** [comment]
Can you send a screenshot ?
Font-size is configurable... Did you try ?

**Comment by VijayVj7** [comment]
Hi ChaBau,

Here is the screenshot below,
By default the fonts are too small to see, I had to zoom in and zoom out.I
tried for configuring the font-size but couldn't find out.

[image: Inline image 2]

Please let me know for configuring the font -size from UI

Thanks

**Comment by chabou** [comment]
I can't see your screenshot.

Please read [documentation](https://hyper.is/). You need to change `font-size` setting in your config file `~/.hyper.js`

**Comment by ig92** [comment]
@seewhy17 confirmed. Changing fontSize does not work

**Comment by thedch** [comment]
@chabou your link to the documentation is just the main page of the hyper website. I can't find any documentation. 

The only instructions:

> The config object seen above in ~/.hyper.js admits the following

And "seen above" does not seem to point to anything. There are no specific instructions regarding the `hyper.js` file. 

I set mine up as:

```
$ cat ~/.hyper.js
module.exports = {
    config: {
        'fontSize': 12
    }
}
```

But this does not seem to do anything.

**Comment by pwaterz** [comment]
FYI on version 2.0.0 using the deb package, fontSize doesn't have any affect. This ticket should be reopened.

**Comment by pwaterz** [comment]
It ended up being the theme I was using. I switched themes and fontSize started working...

**Comment by albinekb** [comment]
Yes, I can confirm it's working for me..

**Comment by gaianote** [comment]
I used a theme plugins: ["verminal"], and when I deleted it, the fontSize started working right away.

**Comment by albinekb** [comment]
Please open an issue over at verminal @gaianote

**Comment by ruucm** [comment]
Agree. This issue depends on which theme you use.

When I changed my theme from verminal, it's fontSize option started not working

**Comment by milky2028** [comment]
It's not ideal, but you can fix this manually by going to .hyper_plugins/node_modules/verminal/index.js and changing the fontSize at line 13 to whatever you want it to be (if you're using verminal). This would be overwritten if an update to the theme is issued. The path and line number would be different if you're using a different theme.

**Comment by hados99** [comment]
I also encountered same problem - from other terminal to verminal.
I could change fontSize after I added verminal object to config object
I refered Verminal documentation - https://github.com/defringe/verminal#%EF%B8%8F-configure

**Comment by alexgby** [comment]
> I used a theme plugins: ["verminal"], and when I deleted it, the fontSize started working right away.

It works for me too.

**Comment by brandtrock** [comment]
This is not a Hyper issue, but a Verminal issue. Verminal requires its own object to be set within Hyper's config object. According to Verminal's documentation, at the time of this posting, you need to do this:

> Verminal aims to deliver a beautiful experience out of the box. However, you can override the font-family or font-size specified by Verminal.
> Open ~/.hyper.js in your favorite editor.
> Add a verminal object to the config object and specify fontFamily and/or fontSize.
> Example
```
verminal: {
    fontFamily: '"My favourite font"',
    fontSize: 16
}
```
This fixes the issue we have all been experiencing.

**Comment by joaovian06** [comment]
> It's not ideal, but you can fix this manually by going to .hyper_plugins/node_modules/verminal/index.js and changing the fontSize at line 13 to whatever you want it to be (if you're using verminal). This would be overwritten if an update to the theme is issued. The path and line number would be different if you're using a different theme.

Thanks, this work for me
