### ISSUE TITLE
Undo and Redo keys does not work 

### ISSUE THREAD

**Issue by lione17** [zeit/hyper#1828]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.11.6  OSX El Capitan
- **Hyper.app version**: 1.3.3 (1.3.3.1754)

## Issue

Everything work just fine, except those two keys, Undo and Redo. When i press down <kbd>Command</kbd>+<kbd>Z</kbd> or <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> nothing going to happens while the Edit section on the menubar going to fires .

**Comment by ELLIOTTCABLE** [comment]
I have to wonder what's expected, here — both by the reporter, and by the authors.

What can you meaningfully *undo*, from the perspective of the emulator? This would need tight integration with the shell, at the very least — and with any programs you invoke, to be more complete.

About the only useful ‘undo-related’ feature I can think of, is if Hyper saved closed windows' scrollback for some period of time (1m?), and ⌘Z could create a new window, then restore the window's scrollback and a simple set of known state ($PWD, maybe other env-vars?) … “Recently closed tabs” for the terminal.

That's honestly pretty ambitious, though, and probably not what the O.P. means. These menu-items should probably be removed entirely. (Terminal.app, for reference, has them; but they're greyed out when interacting with a standard terminal-window. They activate when the preferences-window is opened, and allow you to undo up into a stack of preferences-modifications … but Hyper doesn't even have a preferences-window.)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
