### ISSUE TITLE
cd<tab> outputs "cdcd" and can only backspace the second "cd"

### ISSUE THREAD

**Issue by ryanseys** [zeit/hyper#183]
There's a bug where if you hit tab after you've already typed a full command, it will autocomplete the command twice however you can only backspace until the second instance is removed, not the original one typed.

**Comment by sebinsua** [comment]
I have this exact same bug, though it happens with all commands.

I am using `zsh` with `oh-my-zsh` and these plugins:

```sh
plugins=(zsh-syntax-highlighting zsh-autosuggestions bgnotify colored-man-pages last-working-dir rand-quote osx brew autojump git github npm atom)
```

**Comment by ryanseys** [comment]
To clarify, it happens with all commands for me too and I do use zsh so
that might be the issue.

**Comment by rdewolff** [comment]
Same issue here, very annoying.

**Comment by albinekb** [comment]
Is this only happening in zsh? Can't reproduce with fish or bash..

**Comment by rdewolff** [comment]
yep with zsh

**Comment by lordgiotto** [comment]
I can confirm that i've this issue with zsh too. 
It happens if _tab_ any command (a complete command, not a portion, without a space after it: for instance `ls`_tab_, `cd`_tab_, `git`_tab_).

**Comment by lordgiotto** [comment]
Ok, it a locale issue. Related to #441

**Comment by kevinrambaud** [comment]
bump, same thing for me, using also zsh

**Comment by rdewolff** [comment]
This works for me now.

**Comment by sajadghawami** [comment]
still having the same issue!

**Comment by urbantrout** [comment]
Try adding this to your .zshrc

```
# You may need to manually set your language environment
export LANG=de_AT.UTF-8
```

**Comment by chabou** [comment]
Seems fixed.
Feel free to reopen
