### ISSUE TITLE
JSON response is not displayed properly

### ISSUE THREAD

**Issue by Aaron-A** [zeit/hyper#1830]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **macOS Sierra version10.13.4**
- **Hyper.app 1.3.3 (1.3.3.1754)**
- **The issue is reproducible in vanilla Hyper.app**

## Issue
When making a get request the response data is being cutoff in the terminal view. 

```javascript
const username = "mav3r1ck"
const https = require('https');
const request = https.get(`https://teamtreehouse.com/${username}.json`, response => {
    console.dir(response.statusCode);
    let body = "";
    //Read the data
    response.on('data', data => {
        console.log('data', data.toString());
        body += data.toString();
    });
    response.on('end', () => {
       console.log(body); 
    });
});
```

<img width="669" alt="screen shot 2017-05-15 at 7 27 40 am" src="https://cloud.githubusercontent.com/assets/6710841/26055783/4cf815a2-3940-11e7-8fa8-ec2d2af2f29d.png">
<img width="708" alt="screen shot 2017-05-15 at 7 26 18 am" src="https://cloud.githubusercontent.com/assets/6710841/26055784/4fa3a6c2-3940-11e7-8043-620c221ddfd6.png">

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
