### ISSUE TITLE
Archive in release is not up-to-date

### ISSUE THREAD

**Issue by enguerran** [zeit/hyper#1834]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I realized that https://github.com/zeit/hyper/archive/1.3.3.tar.gz does not contain the correct version of the source code.

**Comment by enguerran** [comment]
Related: https://github.com/zeit/hyper/issues/1818#issuecomment-308315638

**Comment by albinekb** [comment]
We have set up new release procedures and now have a `canary`branch too, this issue wont' (hopefully) happen again, thanks for reporting! 👍
