### ISSUE TITLE
can't input Chinese

### ISSUE THREAD

**Issue by pua4pai** [zeit/hyper#1836]
hi dear:

- I use input method software input  Chinese
![](http://i2.muimg.com/588926/3c6854b92a98cedd.png)

Hyper 1.3.3
Electron 1.4.16
darwin x64 15.6.0

**Comment by shuishoudage** [comment]
I would like to PR this issue, Any collaborator of this project could help me get started?

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
