### ISSUE TITLE
Clear and vim don't work with MINGW64

### ISSUE THREAD

**Issue by stefan-rink** [zeit/hyper#1837]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10** 
- **Hyper 1.3.3** 
- **Using MINGW64 by git-bash** 

## Issue

I'm using MINGW64 from the git-bash. 
If I type the command 'clear', my cursor jumps to the beginning of the window, but the text doesn't disappear:

![image](https://cloud.githubusercontent.com/assets/12150273/26145631/6d0db1ea-3aed-11e7-82a0-c110713d3254.png)

I have similar issues using vim in my bash. If I try to delete a char, my cursor moves, but the chars doesn't disappear, too. 
In vim I get another error, when moving the cursor with the arrow keys:

![image](https://cloud.githubusercontent.com/assets/12150273/26145818/303c67f6-3aee-11e7-955c-ad024caa6358.png)

**Comment by RokasMuningis** [comment]
By any chance you found solution to it?

**Comment by FreshICEtee** [comment]
The clear error is a duplicate of:
https://github.com/zeit/hyper/issues/1809

The error isn't fixed, yet, but you can temporarily clear the complete window with `Ctrl` + `Shift` + `K`.

For the cursor problem in vim I don't have a solution.

**Comment by SammyIsra** [comment]
Quick question, sorry that it is unrelated. I am trying to make Hyper use the mingw64 console, how did you make that happen?

**Comment by meoknu** [comment]
in hyper.js file put

    // for environment variables
    env: {
		TERM: "cygwin"
	},

**Comment by Stanzilla** [comment]
^ your solution
