### ISSUE TITLE
Can't clear the screen (CMD+K) on an "active" terminal

### ISSUE THREAD

**Issue by johnnorris** [zeit/hyper#1838]
In previous versions you could `CMD+K` to clear the terminal at any point, but now it appears you can only do this if the terminal isn't "active". E.g. if you're tailing a log, or if `gulp watch` is running, you cannot now clear the screen, but instead `^L` is output.

-

Hyper 1.3.3
Electron 1.4.16
darwin x64 16.5.0

**Comment by ppot** [comment]
Closing for #1808
