### ISSUE TITLE
Cursor position trouble when changing data on SESSION_PTY_DATA action on Plugin

### ISSUE THREAD

**Issue by jieverson** [zeit/hyper#1839]
Hello,

I'm working on a plugin.
There are times when I need to intercept SESSION_PTY_DATA actions, and change their data.
But, when I do, Hyper keep the cursor at position it was expect to be if I didn't changed data.

You can try with this plugin:

```
exports.middleware = (store) => (next) => (action) => {
  if('SESSION_PTY_DATA' === action.type){
    action.data = action.data.replace('hello world', "hi")
  }
  next(action)
}
```

Now load it, and try typing on prompt: `echo hello world baby boy`.
You will see the plugin working, but during the writing, you you can confirm the bug when typing `space` (' ') right after typing `baby `.
```
# echo hi baby          _
```

It also happens every time you type `space` (' ') later on.

Any idea?

[EDIT:] I don't think this might be the problem, but just noticed that when user input `space`, data from SESSION_PTY_DATA action just contains `' '`, and not the whole line.

**Comment by HelloWorld017** [comment]
I am also experiencing this problem while rewriting default prompt to powerline.

**Comment by HelloWorld017** [comment]
Finally I found it. The issue is because of ANSI escape code. If you dump the data, you can find texts like

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
