### ISSUE TITLE
JavaScript error being thrown on open

### ISSUE THREAD

**Issue by sethmoore** [zeit/hyper#1840]
Open Hyper

![image](https://cloud.githubusercontent.com/assets/2317590/26203154/10ef2d38-3ba8-11e7-80bd-131ca871589c.png)

Also happens when opening a new tab and when trying to perform some commands.  This error was not happening yesterday.

I've had some colleagues test and verify this behavior as well.

-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.14393

**Comment by KuroTsuto** [comment]
Have you tried setting the `"shell"` field in your preferences file to an absolute path?

**Comment by sethmoore** [comment]
So found out that this only happens when powershell is set as the default shell.  If I default to command prompt and then open powershell everything works ok.

**Comment by habby1337** [comment]
so how should I solve it?

**Comment by albinekb** [comment]
Try setting cmd as your default prompt @habby1337

**Comment by habby1337** [comment]
@albinekb how do you do it?

**Comment by habby1337** [comment]
@albinekb from what I saw, as default I have the cmd and not the powershell

http://prntscr.com/gqc1ef (screenshot it's in Italian)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
