### ISSUE TITLE
Calc causes "Unknown token character" and "M is undefined" errors.

### ISSUE THREAD

**Issue by externl** [zeit/hyper#1846]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Seirra 10.12.5
- **Hyper.app version**: Version 1.3.3 (1.3.3.1754)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: defaults
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: nothing in console
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue
When I run `calc` I see lots errors printed after the command is executed. This does not happen with `Terminal.app` or `iTerm2.app`. The errors seem different every time.

Eg.
```
$ calc "100+1"
        101
Unknown token character '?'

$ calc "100+1"
        101
Unknown token character ''

$ calc "100+1"
        101
Unknown token character ''

$ calc "100+1"
        101
"M" is undefined
```

calc info:
```
$ calc -v
C-style arbitrary precision calculator w/custom functions (version 2.12.5.0)
```

**Comment by chabou** [comment]
reproduced with oh-my-zsh and vanilla bash... What the hell is that??

**Comment by externl** [comment]
Same thing with `clac -p`.I wonder if calc prints some extra characters after the value.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
