### ISSUE TITLE
Hyper does not run

### ISSUE THREAD

**Issue by soleera** [zeit/hyper#1849]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Hardened Gentoo (Linux kernel 4.9.24) 
- **Hyper.app version**: 1.3.3 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Attempting to launch hyper from the terminal or dmenu does not open a new window and does not print any messages to stdout. This behaviour is consistent for both version 1.3.3 compiled from source, as well as all the 1.3.x app images.

I am using a minimalistic Wayland compositor called [sway](https://github.com/SirCmpwn/sway) with XWayland enabled. I have also tested Hyper in X with twm, however the problem persists.

**System Information:** https://gist.github.com/albinekb/f24c2b9dac9f382b444258db3f8b7e91

**Comment by albinekb** [comment]
Does other electron apps work? Desktop.github.com for example

**Comment by soleera** [comment]
I tried Gitkraken and I'm getting the same results. I'm guessing that means it could be an issue with electron then...

**Comment by soleera** [comment]
Perhaps [this](https://electron.atom.io/docs/tutorial/supported-platforms/) is the issue... I am able to compile electron from source successfully, but that won't help if Hyper explicitly uses the pre-compiled electron binaries.

**Comment by soleera** [comment]
It looks like other electron apps are having similar issues; Gitkraken has the same problem as hyper, Discord segfaults without opening, and Atom doesn't successfully compile. I think all of this suggests an issue with electron on my system; I've opened a [bug report](https://bugs.gentoo.org/show_bug.cgi?id=619528) over on Gentoo's Bugzilla, so it might be a good idea to wait and see if it's a distribution specific issue before we worry about anything else.

Also thanks for making the gist, that completely slipped my mind! (I've got the Octopatcher plugin on my browser, so I didn't realise how inconvenient it might be for others).

**Comment by soleera** [comment]
It looks like the culprit in this case is grsecurity; I'm using the hardened-sources  kernel which contains the grkernsec patches. These unfortunately break the functionality of packages which include the chromium eclass such as electron. Therefore it's not possible to use electron apps on kernels with grkernsec patches.
