### ISSUE TITLE
Windows Script Host

### ISSUE THREAD

**Issue by balmungsama** [zeit/hyper#1854]
I go to Edit > Preferences, and I get a Windows Script Host error

Script: C:\Users\john\.hyper.js
Line: 5
Char: 1
Error: "module" is undefined
Code: 800A1391
Source: Microsoft JScript runtime error

-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by albinekb** [comment]
Duplicate of https://github.com/zeit/hyper/issues/1812 thanks for reporting
