### ISSUE TITLE
PROPOSAL: New blank line on Enter key press

### ISSUE THREAD

**Issue by mazyvan** [zeit/hyper#1855]
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

Hi, this is actually not an issue. But unfortunately I have no time for making a pull request.

I really think that while a process is running is very useful that on a enter/intro key press appear a new empty line. This is the native behavior in git-bash for example.

Hyper at the present time
![image](https://cloud.githubusercontent.com/assets/10915753/26289272/40d9cd5a-3e64-11e7-923d-765db6d6ff96.png)

Now, in Git-bash you can easily create a separator doing this.
![image](https://cloud.githubusercontent.com/assets/10915753/26289357/fcfb3cbc-3e64-11e7-8cac-f578bf8dca9a.png)

Thanks and keep it up. It's a great project

**Comment by nitsakh** [comment]
Hello, I would like to work on this feature request. All help is appreciated!

**Comment by nitsakh** [comment]
@mazyvan Do you have an example case where I can reproduce the issue? Unfortunately, I wasn't able to repro the issue with my own tests. So if there's some specific case, that will be helpful.

**Comment by MartyGentillon** [comment]
You can use any commands that print multiple lines of output.  `ping -t 8.8.8.8` seems like a pretty good candidate.  Then just hit enter while it is running, do you get blank lines?

**Comment by MartyGentillon** [comment]
Also, this only seems to affect Windows.  The bug is almost certainly in a lower level component, most likely the winpty library, or perhaps even the windows kernel.

**Comment by MartyGentillon** [comment]
(It also happens in Conemu an the default windows console...)

**Comment by nitsakh** [comment]
Ahh! My bad! I didn't realise that this is a Windows only issue. I checked on mac, which worked!
Unfortunately, I do not have access to windows currently, so will pass this one on.
Some one with Windows access is free to take this up. Sorry about that!

**Comment by chabou** [comment]
You're right @MartyGentillon. Good catch.
@nitsakh Thank you too, to have tried to reproduce.
Nothing that we can do, so I'm closing this issue. Feel free to comment.
