### ISSUE TITLE
Border radius

### ISSUE THREAD

**Issue by kodekrendel** [zeit/hyper#1860]
Can't set border-radius in Ubuntu.

Tried `borderRadius: '10px'` in `.hyper.js`with no success.

**Comment by albinekb** [comment]
Duplicate of #1674

**Comment by kodekrendel** [comment]
@albinekb how is that duplicate, if that issue is UNSLOVED and CLOSED? Fuckoff hyper.

**Comment by albinekb** [comment]
#1674 isn't closed? @kodekrendel 
![image](https://cloud.githubusercontent.com/assets/5027156/26487816/4c58bcf4-4201-11e7-8545-ccd7950cca42.png)
