### ISSUE TITLE
Ctrl+C closes Hyper on Windows

### ISSUE THREAD

**Issue by Arood** [zeit/hyper#1861]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

(unless I've been looking for the wrong thing)

- **OS version and name**:  Windows 10
- **Hyper.app version**: 1.33
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Arood/6e7fae0ef37ecb4b437f0e094570542c
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Unsure, see my .hyper.js if you consider it "vanilla enough"

## Issue
When pressing Ctrl+C in bash (git-bash) it makes the whole Hyper window close instead of just the running application. This doesn't happen in any other terminal that I know of. Maybe (and hopefully) I just made my .hyper.js wrong, if that's the case I'd love know how to fix it.

**Comment by albinekb** [comment]
You have 
```
    shell: 'C:\\Program Files\\Git\\git-cmd.exe',
    shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],
```
In your config, do you want to use bash or git-cmd?

**Comment by Arood** [comment]
@albinekb I want to use the mingw bash that's included with Git on Windows. The config is from https://github.com/zeit/hyper/issues/1252.

**Comment by Arood** [comment]
Finally figured it out. Turns out it was a bug in the git implementation of the mingw bash, which has been fixed in a newer update. So if anyone has the same problem and finds this issue: make sure you have the latest version of Git for Windows installed.

**Comment by albinekb** [comment]
👌
