### ISSUE TITLE
Move cursor with mouse click

### ISSUE THREAD

**Issue by HawkonDK** [zeit/hyper#1864]
**Hyper is an awesome console**, but I was hoping that it will learn from the plugins and people out in the world to make it more user-friendly than other console's

E.g when you write a command, you are only allowed to use the arrow to navigate when you wanna edit something. There is a plugin for the editor there lets you use `alt + mouse click ` to move the cursor in the position you wanna edit. This should be normal in Hyper just without the need for press `alt`

In fact, Hyper should be the solution people go to, to get a console there are better than others because it doesn't follow the old weird rules from the 1990

**Comment by dimatter** [comment]
what is your ~~problem~~ issue?

**Comment by HawkonDK** [comment]
more a request than a problem. Hyper are an amazing console. Why? because it lets you install plugins so you are able to make the console more modern and make so it is able to use the mouse.

To make it short. It will be amazing if Hyper added support for moving the cursor by using the mouse, as a standard _(and without the need to hold `alt` down)_

**Comment by chabou** [comment]
As you mentioned it, [hyper-alt-click](https://github.com/adamscybot/hyper-alt-click) do what you need. Maybe it will become a core-plugin in the future.

Thank you for your feedback.

**Comment by HawkonDK** [comment]
tbh it should be a core-plugin, terminals UX are from the 1990 and will be amazing to get one there just add a little of the 2017 to it

**Comment by albinekb** [comment]
I'm ok with adding APIs to make this easier to achieve.

**Comment by ortonomy** [comment]
So, this is covered here: https://github.com/zeit/hyper/issues/316 ?
