### ISSUE TITLE
Hyper for Windows download is slow 

### ISSUE THREAD

**Issue by phiilu** [zeit/hyper#1866]
- **OS version and name**:  Windows
- **Hyper.app version**: latest

## Issue

I try to download the Windows version for hyper, but the download is really slow.
I am downloading from Austria and my download speed ist (max) 50 mbit/s. 
Is there a problem with the now servers?

![image](https://cloud.githubusercontent.com/assets/8149519/26416288/a6831e92-40b5-11e7-9164-d0aea314b0f2.png)

![image](http://beta.speedtest.net/result/6323141803.png)

**Comment by albinekb** [comment]
I don't know where the code for `hyper-updates` lives, I guess it's closed source 😄 
![image](https://cloud.githubusercontent.com/assets/5027156/26480554/ddd4efee-41da-11e7-91fd-db88203dae9d.png)

Some months ago I made this https://hyper-latest.now.sh/ (source https://github.com/zeit/hyper-latest)

As seen in the picture I've done a redirect to github, and let them take care of serving the file.

@rauchg should we change updates to the new download site?

**Comment by leo** [comment]
We're simply using [nuts](https://github.com/GitbookIO/nuts) for that! That's the source code (no repo for any of our update servers, since they only require env vars).

**Comment by nusairafnan** [comment]
guys just try using a vpn. I tried setting my location to hongkong or singapore i guess and the downloads were pretty fast for me...
