### ISSUE TITLE
Open Hyper in Current Folder (macOS)

### ISSUE THREAD

**Issue by IanCarrasco** [zeit/hyper#1868]
I have been a long time user of hyper on windows, but I have recently switched to mac and have found no clear method to launch a hyper terminal from a folder. This then leads to a tedious process of having to "cd" to the specified folder. Is there a feature that does this that I am missing or has it not been implemented yet? Other than that, the terminal works great.

Thank You.

**Comment by ppot** [comment]
@IanCarrasco Unfortunately, at the moment you can't set `cwd` for that matter. Hyper wont open at the specific `cwd`. You can see if some plugins have that specific `feature`.

**Comment by Stanzilla** [comment]
Example of such plugins: https://github.com/hharnisc/hypercwd

**Comment by htkoca** [comment]
Can one make an automator service that calls hyper with specific arguments? I've seen this done for other terminals like iTerm2. In fact, it is possible to create an instance of hyper with a different starting directory programmatically. See: https://github.com/htkoca/cdto or https://github.com/ealeksandrov/cdto

**Comment by albinekb** [comment]
In macOS you can just type "cd <drag folder here>" and it will insert the correct path, this is the "mac" way of doing things, you can drag any folder/icon in finder and it should work :)

**Comment by htkoca** [comment]
It's a good solution 👍 but doesn't address exactly what this issue is about.

**Comment by IanCarrasco** [comment]
Guys I finally solved it. Here is a guide I made to implement the solution. https://gist.github.com/IanCarrasco/60364134e2649fb0d94751b7a04f25b1

**Comment by htkoca** [comment]
We can potentially skip using `cd_to` by just executing: `open '/path/to/hyper' '/path/to/current/directory'` in apple script's syntax. Not fluent in applescript but it should be possible !

**Comment by nikitakatchik** [comment]
IMO just put the workflow file from this archive to your ~/Library/Services folder and then use this service in keyboard preferences to bind a shortcut.
[New Hyper Tab at Folder.workflow.zip](https://github.com/zeit/hyper/files/1800038/New.Hyper.Tab.at.Folder.workflow.zip)

**Comment by xezian** [comment]
In Hyper I type: `pwd|pbcopy`, press ⌘T, then `cd ` + ⌘V.  Takes about 3 seconds, but I realize it's a workaround.

**Comment by TodorTotev** [comment]
> IMO just put the workflow file from this archive to your ~/Library/Services folder and then use this service in keyboard preferences to bind a shortcut.
> But this will open a tab for selected folder, not the current one. Similar to default Terminal services.
> [New Hyper Tab at Folder.workflow.zip](https://github.com/zeit/hyper/files/1800038/New.Hyper.Tab.at.Folder.workflow.zip)

Love you brother

**Comment by Campano** [comment]
> IMO just put the workflow file from this archive to your ~/Library/Services folder and then use this service in keyboard preferences to bind a shortcut. But this will open a tab for selected folder, not the current one. Similar to default Terminal services. [New Hyper Tab at Folder.workflow.zip](https://github.com/zeit/hyper/files/1800038/New.Hyper.Tab.at.Folder.workflow.zip)

Thank you so much! The execution of the apple script makes it a bit slow though, there's actually a "Open Finder Items" in Automator, which lets you open the item with the app of your choice, it seems more efficient.

Ideally, the workflow could be improved by selecting the parent folder when the item is a file and not a folder..

[hyper.workflow.zip](https://github.com/vercel/hyper/files/7685313/hyper.workflow.zip)

**Comment by sddale** [comment]
These solutions work, but I find it inconvenient that they need a directory to be selected.

This opens finder's cwd in Hyper instead:

```AppleScript
on run {input, parameters}
	tell application "Finder"
		set currentDir to (target of front Finder window) as text
	end tell
	tell application "Hyper"
		open (currentDir)
		activate
	end tell
end run
```

Set "Workflow receives" to "Automatic (Nothing)" in Automator.
