### ISSUE TITLE
Closing vertical split causes a render bug in the remaining window 

### ISSUE THREAD

**Issue by luisherranz** [zeit/hyper#1875]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.5
- **Hyper.app version**: 1.3.3
- **The issue is reproducible in vanilla Hyper.app**: Yes, no plugins are installed

## Issue

When you close a Split Vertical panel the remaining window doesn't use the full space until it is resized. Since this is harder to explain than to see, I've made a video:
https://youtu.be/wluZV9hWarM

**Comment by tdeschryver** [comment]
I've taken a look and noticed that when the check at [term.js#L74](https://github.com/zeit/hyper/blob/master/lib/components/term.js#L74) is removed, the window will be resized. Removing the check seems a bit hacky tho...

**Comment by gtklocker** [comment]
Also seeing this issue.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
