### ISSUE TITLE
Emacs crashes when killing text (Ctrl + W)

### ISSUE THREAD

**Issue by vidjuheffex** [zeit/hyper#1881]
Mark text with Ctrl + SPC, go to end of text selection: CTRL+W. Everything freezes right there.

Doesn't happen through Terminal so I'm guessing its Hyper. Maybe from trying to access a clipboard?

-

Hyper 1.3.3
Electron 1.4.16
darwin x64 15.6.0

**Comment by ppot** [comment]
#1509

**Comment by kgrimes2** [comment]
Same thing happens to me with C-k.

**Comment by julianwyz** [comment]
This happens to me as well with both `Ctrl-W` and `Ctrl-K` and also when copying a region of text with `Meta-W`.

This is the error message that appears in the console:

![screen shot 2017-08-14 at 10 02 39 am](https://user-images.githubusercontent.com/11424657/29275183-428b64c2-80d8-11e7-8d46-208a38320754.png)

Im running Hyper 1.3.3 and macOS 10.12.6

**Comment by ppot** [comment]
close in #1876
