### ISSUE TITLE
'yes' command hangs application

### ISSUE THREAD

**Issue by stonegray** [zeit/hyper#1882]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  macOS 10.12.4 (16E195)
- **Hyper.app version**: 1.3.3 and 1.6.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Occurs on clean install 
- **Relevant information from devtools**: Writes nothing, devtools does not respond to commands.
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

**To reproduce:**
- Run hyper on macOS and type 'yes' in a second tab
- Try to switch to another tab or close the current tab

**Expected Behaviour:** 
- Closes tab

**Observed Behaviour:**
- Does nothing, hangs application. 

`C+c` does not exit the command as expected. Pressing `⌘+q` will close the app after a few minutes. New tabs cannot be opened. 

Running `yes > /dev/null &` does not cause the application to hang.

**Comment by chabou** [comment]
Duplicate #555 
Thank you for your feedback. We have a lot of perfomance issues. We are expecting to improve that soon.
