### ISSUE TITLE
Style (bold, color) is not reset after a command

### ISSUE THREAD

**Issue by sylvainlap** [zeit/hyper#1883]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.3
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
After a command that have bold or colored text output, the next prompt keeps this style.

For example, with `now`, `now ls` outputs a list with bold character. Atfer that output, my prompt and all other outputs are bold.

![capture](https://cloud.githubusercontent.com/assets/8457604/26554769/355c2912-4492-11e7-9cb5-781a834925cc.PNG)

I think that my prompt should bo back "unbold".

**Comment by chabou** [comment]
@sylvainlap Can you confirm that it does not happen on native powershell console ?

**Comment by sylvainlap** [comment]
Indeed, it happens in native `cmd`.

**Comment by chabou** [comment]
So, it is a `Powershell` bug and I think we can close this issue.
Feel free to comment if not.
