### ISSUE TITLE
Customizing the row markup with class names

### ISSUE THREAD

**Issue by ghost** [zeit/hyper#1885]
Is it possible to add custom class names to the `x-row` elements somehow? And maybe even get the current input/prompt row's value? I'd like hide all input rows but the last one, which can't be done in a way I'd like it with just CSS it seems.

**Comment by MartyGentillon** [comment]
Really, not with `:nth-child()`?

https://css-tricks.com/extremely-handy-nth-child-recipes-sass-mixins/

**Comment by Jesprj** [comment]
@MartyGentillon Nope, because the position of the current input row changes after any output. If the "current input row" just had a class on it to target it that'd solve the problem.
