### ISSUE TITLE
stdout of `gocode` is invisible in terminal, but is pipable

### ISSUE THREAD

**Issue by therealplato** [zeit/hyper#1887]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows 10 home x64
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/therealplato/adeb4a3b51622368c558550435f013fb
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I'm trying to get golang completion working in vim. It uses [nsf/gocode](https://github.com/nsf/gocode) for a completion engine. I have run `go get -u -ldflags -H=windowsgui github.com/nsf/gocode` as per readme. Debugging steps for indicated `gocode set` ought to output useful information. 

As shown in the gist, `gocode set` does output information to Git Bash's default terminal.
`gocode set` does not show any output in Hyper.
`gocode set | wc` indicates the pipe was not empty.
`gocode set > asdf` populates the file with ascii text

What's going on? Or to my immediate goal, has anyone successfully accomplished go code completion in Hyper?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by BaileyJM02** [comment]
Bump. 
v2.0.0

Still exists for me, even running a simple `ftm.Println("Some stuff")` doesn't work.

**Comment by BaileyJM02** [comment]
Update: Updated to canary and works so keep up the good work!
