### ISSUE TITLE
error updating plugins

### ISSUE THREAD

**Issue by narenkaru** [zeit/hyper#1888]
![capture](https://cloud.githubusercontent.com/assets/5405431/26595339/a21323ec-459d-11e7-9843-c2e75ddc61a9.PNG)

-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by Stanzilla** [comment]
What is your defined shell? Are you on npm@5?

**Comment by albinekb** [comment]
If you post the file `~/.hyper_plugins/npm-debug.log`, we'll know what's going on

**Comment by frankyonnetti** [comment]
@Stanzilla I am on npm@5 and having the same problem.

**Comment by Stanzilla** [comment]
Yeah it's caused by npm@5, I cannot say what exactly fails yet

**Comment by narenkaru** [comment]
I can’t even find the log file at all.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Stanzilla** [comment]
yeah the file is never generated, another bug.

**Comment by kadrach** [comment]
I'm experiencing the same issue, fresh install of Hyper 1.3.3 on Windows (default shell is cmd.exe), happens on first start. Haven't touched anything Hyper related. While a `.hyper-plugins` folder structure is generated, it only contains a `package.json` and an empty `local` folder.

**Comment by Stanzilla** [comment]
@kadrach npm@5 as well?

**Comment by jochim-van-dijck** [comment]
I'm having the same issues also on npm v5.
Removing all files but `package.json` and running `npm install` in `.hyper_plugins` fixes the plugins.

**Comment by Stanzilla** [comment]
master now includes a fix for that

**Comment by ppot** [comment]
#1896
