### ISSUE TITLE
Microsoft JScript runtime error when opening Preferences

### ISSUE THREAD

**Issue by MitjaBezensek** [zeit/hyper#1891]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10 Pro Build 15063
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/MitjaBezensek/66c04cafac4d76cfe10d5882186f84d9
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**:  Yes. This is a clean install of Hyper, and tried to access Properties the first time it launched.

## Issue

I just installed Hyper from the website, it's the first install on the computer. After the installation I started Hyper and wanted to check the Preferences that are available. When I click on the Preferences button in the menu I get the following error:
![image](https://cloud.githubusercontent.com/assets/2523721/26623792/253a0e60-45ef-11e7-8c43-f27a210bc4c0.png)

**Comment by christophert** [comment]
This happens because Hyper tries to launch hyper.js with the default app associated with the .js extension. Change the default app in the control panel to a text editor and it should open up properly.

**Comment by MitjaBezensek** [comment]
Yep, this worked.
