### ISSUE TITLE
White Text on White background when using vibrancy

### ISSUE THREAD

**Issue by chrisdrackett** [zeit/hyper#1894]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS 10.12
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/chrisdrackett/c41d4d078e82515e43c9d92b0afe5068

- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: NA
- **The issue is reproducible in vanilla Hyper.app**: No

## Issue

When using a theme that uses vibrancy (like https://github.com/nachoaIvarez/hyper-vibrant for example) highlighted text (like the options in nano) will show up white on white. I've verified by removing everything from hyper-vibrant except for the line setting the window as vibrant:

`module.exports.onWindow = browserWindow => browserWindow.setVibrancy('dark');`

This is similar to https://github.com/zeit/hyper/issues/883

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by Hemphill** [comment]
This wasn't resolved in v2, it's still happening today. Same with #883
