### ISSUE TITLE
change to relative layout 

### ISSUE THREAD

**Issue by fantasticcmm** [zeit/hyper#1895]
To be honestly, this is a awesome project.

But, i have a quest, why using 'fixed' instead of 'relative'.

![image](https://cloud.githubusercontent.com/assets/18608661/26720139/a88fb9b0-47b9-11e7-80d0-763ec38e0409.png)

this problem make hyper hardly embedded into other div.
tips: my english is poor, so never mind!

**Comment by ppot** [comment]
@fantasticcmm Can you follow the issue template? Thanks!

**Comment by fantasticcmm** [comment]
I don't know "flow the issue template" means.

my question is simple. 

code：https://github.com/zeit/hyper/blob/master/lib/containers/hyper.js

line： 123

![image](https://user-images.githubusercontent.com/18608661/26917561-537c32da-4c61-11e7-803f-08c0ddda6b66.png)

I want to use hyper as a part of another project. So，i embed hyper into a div. For the reason of hyper using 'absolute' instead of 'relative', so it's hardly to let hyper on right position.

I have to change hyper source code，and change all 'absolute' to 'relative'。

**Comment by ppot** [comment]
```
<!--
  Hi there! Thank you for discovering and submitting an issue. 

  Before you submit this; let's make sure of a few things. 
  Please make sure the following boxes are ticked if they are correct.
  If not, please try and fulfil these first.
-->

<!-- Checked checkbox should look like this: [x] -->
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

<!-- 
  Once those are done, if you're able to fill in the following list with your information,
  it'd be very helpful to whoever handles the issue.
-->

- **OS version and name**: <!-- Replace with version + name -->
- **Hyper.app version**: <!-- Replace with version -->
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: <!-- Gist Link Here -->
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: <!-- Replace with info if applicable, or N/A -->
- **The issue is reproducible in vanilla Hyper.app**: <!-- Replace with info if applicable, or `Is Vanilla`. (Vanilla means Hyper.app without any add-ons or extras. Straight out of the box.) -->

## Issue
<!-- Now feel free to write your issue, but please be descriptive! Thanks again 🙌 ❤️ -->

```

**Comment by albinekb** [comment]
Not really needed for this one @ppot 😄  I think you can override that setting via your .hyper.js?

**Comment by ppot** [comment]
@albinekb I am the Hyper 👮

**Comment by fantasticcmm** [comment]
Thanks for reply.
