### ISSUE TITLE
Hyper.is Does not recognize some characters

### ISSUE THREAD

**Issue by Ellebkey** [zeit/hyper#1905]
I use a spanish keyboard and sometimes I have to use accents and the letter "ñ" but when I tyoe it instead of the character shows: (args:1)

http://imgur.com/a/vGNYd

-

Hyper 1.3.3
Electron 1.4.16
linux x64 4.8.0-36-generic

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
