### ISSUE TITLE
PROPOSAL: <input type="text"> or <textarea>-like entry mode

### ISSUE THREAD

**Issue by brandonros** [zeit/hyper#1906]
Apologies if I just don't know how to do this either in regular shells or this app, but I do believe it's missing and would be a great feature. I'm not even sure if it is specific to this package in any way.

### Use case

Imagine you are typing a medium length command. Not long enough to do that "create this command in your text editor" mode, but a good sized command. Let's use `git checkout -- source/js/app/foo/foo/foo/foo.js`

Say you want to replace `/foo/foo/foo/foo.js`. If it was a `<textarea>` or `<input type="text">` field on a web page, you'd just select it, and start typing without any nifty keyboard shortcuts, etc.

Right now, in the app (or any terminal), your cursor doesn't follow what you select. I know there's the keyboard shortcut to move your cursor, but then you still have to start deleting characters.

I don't think it'd be too hard to make? How would you guys go about implementing it? Maybe a plugin? I could give it a whirl if we think it's a good idea/isn't already achievable.

**Comment by Willamin** [comment]
It would be interesting to see a package that would allow a keyboard shortcut to pop up a window to type / easily edit a command, not unlike [hyperterm-safepaste](https://github.com/zsol/hyperterm-safepaste)'s multiline paste.

For what it's worth, if you're using bash, by default the keyboard shortcuts are the same as in emacs. You shouldn't have to delete characters when moving your cursor around. 
https://ss64.com/bash/syntax-keyboard.html

**Comment by timothyis** [comment]
We switched the dom out for a 2d canvas render, so it'd be best as an xterm.js plugin I think! Also you can now select a position in the input with alt+click

**Comment by brandonros** [comment]
> Also you can now select a position in the input with alt+click

You can select a position, but you can't select a block of text and replace it with new text like you can with a textarea or input.

What would it take to develop this? I would use this 100 times on a daily basis.
