### ISSUE TITLE
Double letters with autocompletion

### ISSUE THREAD

**Issue by qmosselm** [zeit/hyper#1907]
- **OS version and name**: macOS Sierra 10.12.5
- **Hyper.app version**: 1.3.3.1754
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [https://gist.github.com/qmosselm/d50611e38b41d1a385ad5debf836f13d](https://gist.github.com/qmosselm/d50611e38b41d1a385ad5debf836f13d)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: [http://www.hostingpics.net/viewer.php?id=337502Capturedecran20170606a034719.png](http://www.hostingpics.net/viewer.php?id=337502Capturedecran20170606a034719.png)
- **The issue is reproducible in vanilla Hyper.app**: No, the issue append with zsh activated.

## Issue
So there is the issue. I have zsh in my Terminal and when I want to use the autocompletion with the Tab key, the first two letters of the word I was typing keep on the screen and stay there until I hit Enter.
I've uploaded a picture to show you : [http://www.hostingpics.net/viewer.php?id=296923Capturedecran20170606a033905.png](http://www.hostingpics.net/viewer.php?id=296923Capturedecran20170606a033905.png)
I also have uploaded a picture of the "source code" in the developer tools to show you that the doubled letters are in the code too.
I only have this issue with zsh because there isn't this sort of autocompletion with bash.
I hope this will help you fix this.
Have a good day.

Quentin

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
