### ISSUE TITLE
try putting Chinese characters into your console

### ISSUE THREAD

**Issue by yaolet** [zeit/hyper#1909]
Don't you ever consider CJK users? 

-

Hyper 1.3.3
Electron 1.4.16
darwin x64 16.4.0

**Comment by yaolet** [comment]
i've dug into the issue list and yes this is a duplicate

i am not impressed by Hyper and all these theme personalization and art stuff are irrelevant, if I cannot properly input my commands.

It is horrifying that a web-tech based app does not consider multi-lingual issue in its design and even more horrifying that such major issue receives such low priority simply because people in Zeit does not speak CJK.  Ask help if you don't know how to deal with this but at present i don't think anyone in Asia at least will use hyper for more than a second after realizing its incapability.

**Comment by chabou** [comment]
Yes, we're struggling with CJK.
A PR was landed https://github.com/zeit/hyper/pull/1536 but reverted.
There is another attempt here: https://github.com/zeit/hyper/pull/1873
Hyper relays on `hterm` and it seems realy hard to patch it correctly.

People in Zeit are reaaaaaaally busy at this moment, so: yes, your help will be reaaaaally appreciated ;) 

I'm closing this issue but feel free to particpate to PRs and other issues related.
