### ISSUE TITLE
Plugins not installing

### ISSUE THREAD

**Issue by bnb** [zeit/hyper#191]
Plugins won't install for me at this point. 

Console log from fresh open:

```
(re)loading renderer plugins
Error: Cannot find module '/Users/tierney/.hyperterm_plugins/node_modules/hyperpower'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Applications/HyperTerm.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at file:///Applications/HyperTerm.app/Contents/Resources/app/build/dist/bundle.js:1:10828
    at Array.map (native)
    at P (file:///Applications/HyperTerm.app/Contents/Resources/app/build/dist/bundle.js:1:10779)
    at Object.<anonymous> (file:///Applications/HyperTerm.app/Contents/Resources/app/build/dist/bundle.js:1:11881)
    at __webpack_require__ (file:///Applications/HyperTerm.app/Contents/Resources/app/build/dist/bundle.js:1:119)
[Notification] Plugin load error: "hyperpower" failed to load in the renderer process. Check Developer Tools for details.
total init time 173.95
Unimplemented DEC Private Mode: 1034
```

**Comment by marcbachmann** [comment]
The new version got released a few hours ago. Please try that one.

**Comment by chiefy** [comment]
Same here, just installed it `Version 0.6.0 (0.6.0)`:

```
bundle.js:1 Error: Cannot find module '/Users/najewicc/.hyperterm_plugins/node_modules/hyperterm-snazzy'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Applications/HyperTerm.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at file:///Applications/HyperTerm.app/Contents/Resources/app/build/dist/bundle.js:1:10828
    at Array.map (native)
    at P (file:///Applications/HyperTerm.app/Contents/Resources/app/build/dist/bundle.js:1:10779)
    at Object.<anonymous> (file:///Applications/HyperTerm.app/Contents/Resources/app/build/dist/bundle.js:1:11881)
    at __webpack_require__ (file:///Applications/HyperTerm.app/Contents/Resources/app/build/dist/bundle.js:1:119)(anonymous function) @ bundle.js:1
bundle.js:5 [Notification] Plugin load error: "hyperterm-snazzy" failed to load in the renderer process. Check Developer Tools for details
```

**Comment by marcbachmann** [comment]
The update only gets triggered on json config change and every 5 hours.
Maybe we can save the notifications somewhere in a log. Then you'll see when something went wrong.

**Comment by bnb** [comment]
When I opened this morning, it didn't work - opened again a bit later, the same. Opened a third time, and my plugins suddenly loaded. So, working it seems.

**Comment by chiefy** [comment]
@marcbachmann , I guess that's why I am confused - I updated my `~/.hyperterm.js`, added some plugins to the list, saved, and the `package.json` had 0 dependencies. Seems like a bug ❓

**Comment by nmn** [comment]
I'm having an even more annoying problem:

1. I do a fresh install of Hyperterm. Everything works.
2. I edit the config file to add the `hyperpower` plugin, and get the notification saying plugins are being updated.
3. I wait for a really long time and nothing happens.
4. I trigger a reload and get the error above.
5. If I trigger a full-reload or close and open the app, it freezer and stop responding. What's worse, the shell stops working even in Terminal. This is only fixed by a system restart.


---

If I go into the `.hyperpower_plugins` folder and `npm i -S hyperpower`, it actually starts working. So it seems like a problem with permissions. That said, the app still doesn't respond.

**Comment by bnb** [comment]
@nmn Had to re-install because I had switched to zsh. Seems we need zsh setup and troubleshot instructions.

**Comment by linonetwo** [comment]
I'm using zsh and get into this too, package.json is not updated.

**Comment by awayken** [comment]
I have this issue on Windows, too. I'm using 1.0.0. I had to delete my `.hyper_plugins/package.json` file and restart Hyper. It regenerated the package.json and installed the plugin I needed.

**Comment by davidcsz** [comment]
Ran in to this when I modified `shell` prior to installing plugins. Plugins installed normally when launching Hyper with the default shell path, then I was free to change the shell path back.

**Comment by lednhatkhanh** [comment]
Can confirm that this is happening with windows 10, hyper 1.1.0

**Comment by jmreicha** [comment]
Getting this as well.  Windows 10, hyper 1.1.0.

**Comment by smithtimmytim** [comment]
I'm having this problem too. Deleting the `.hyper_plugins` folder doesn't fix it.

**Comment by edtorba** [comment]
Still happening on Windows 10, hyper 1.2.1

**Comment by ivansf** [comment]
happening here as well.. Tried using bash.exe and cmd.exe. It tells me to check the logs but they don't exist

**Comment by philkunz** [comment]
+1

**Comment by edtorba** [comment]
After adding plugin to plugins array, I've noticed that they do get added to package.json, but not getting installed.

**Comment by ajinkyai** [comment]
+1

**Comment by gonzalobustos** [comment]
I'm experiencing this issue as well...

macOS 10.12
hyper 1.2.1

**Comment by brunocascio** [comment]
> macOS 10.12
> hyper 1.2.1

Same problem

**Comment by skend** [comment]
> Instead, I used Hyper to run npm install in the .hyper_plugins folder, relaunched Hyper, and the plugins work just fine.

This worked for me except I'm still getting a Windows notification when I start Hyper or try to update any plugins. The error message is: `Error updating plugins. Check '~/.hyper_plugins/npm-debug.log' for more information.` This file does not exist.

**Comment by spilth** [comment]
Manually running `npm install` in `~/.hyper_plugins/` got my Hyper plugins to install correctly.

This is on macOS 10.12.3 and Hyper 1.2.1.1528.

**Comment by altsanz** [comment]
> Manually running npm install in ~/.hyper_plugins/ got my Hyper plugins to install correctly.

Worked for me. I'm using git bash.

**Comment by dmaisano** [comment]
> > Instead, I used Hyper to run npm install in the .hyper_plugins folder, relaunched Hyper, and the plugins work just fine.

> This worked for me except I'm still getting a Windows notification when I start Hyper or try to update any plugins. The error message is: Error updating plugins. Check '~/.hyper_plugins/npm-debug.log' for more information. This file does not exist.

I am having the same issue on macOS sierra with hyper version: 1.2.1.
Manually installed in my case some themes to the "~/.hyper_plugins" via npm install, the themes/plugins do load without any issues however it throws the plugin update error

**Comment by Aerz** [comment]
I solved this problem specifying my shell `shell: '/bin/bash',` or `shell: 'bash',` in `~/.hyper.js`

After that, Hyper automatically create the `npm-debug.log` file, `node_modules` folder and download plugins. 

macOS Sierra 10.12.3
Hyper latest version

**Comment by edtorba** [comment]
Solved problem by specifying shell, `shell: 'cmd.exe'` in `~/.hyper.js'`. Hyper automatically started installing and removing plugins without any errors. Beforehand, tried to set it to `bash.exe` and `powershell.exe` - which made no difference.

Windows 10, Hyper 1.2.1

**Comment by nimaen** [comment]
In windows 10, I've encountered the same problems (that could for other OSs as well).
I manage to install some hyper extensions, so here is what you should do.

1. As stated in some comments here, go in the *.hyper_plugins* folder in your home folder.
2. Delete the *node_modules* folder if present.
3. Open a PowerShell and go in this *.hyper_plugins* folder.
4. Run `npm i --production`, you will have proper errors here (they can also be found in the npm-error.log).

A quick shortcut to your errors would be to install node-gyp via `npm i -g node-gyp` and windows binaries of Python with a version > 2.xx and < 3.xx, currently 2.7.
They are both needed to compile native module.

You should now be able to install nearly everything, hopefully if the hyper extensions is compatible with windows.

**Comment by chabou** [comment]
Solved in [1.3.0](https://github.com/zeit/hyper/releases/tag/1.3.0) with 3df8274

**Comment by yaroslavya** [comment]
Im on version 1.3.1. Doesnt solve it for me. After I change the hyper.js and reload I see the following error message: 
Plugin load error:
hyperline failed to load in the renderer process

I`m on Windows 8.1. the only plugin I`ve added was the hyperline.
Tried the workaround from @nimaen but it gave me some more errors so I`ve just left it till better times.
Let me know if more details are needed.

**Comment by ppot** [comment]
@yaroslavya If #1509 doesn't solve it. Feel free to create new issue.

**Comment by Maamun** [comment]
i set my shell `shell: '/bin/zsh'`, in `~/.hyper.js`, but Hyper seems to be ignoring it. It's set to zsh but I get shell in Hyper while I get zsh in iTerm?

**Comment by MehdiAlouafi** [comment]
Hey there, personally I use fish, I solve this issue (which happened after installing the hyperterm-past plugin) by setting my shell to `/usr/local/bin/fish` in `~/.hyper.js` and, this is the crucial part, I did a `npm install`into the `.hyper_plugins` directory

**Comment by charandas** [comment]
For me, I had to downgrade from npm@5 to npm@4.

**Comment by voydz** [comment]
@charandas Same for me, after a `npm install -g npm@latest-4` everything works again.

**Comment by ppot** [comment]
We are working on releasing with NPM@5 fix

**Comment by equinusocio** [comment]
Same problem even afeter `npm install -g npm@latest-4`. I can't install any plugin.

**Comment by frenchbread** [comment]
+1

**Comment by Giovannang** [comment]
Test npm update in ~/.hyper_plugins

**Comment by duizabojul** [comment]
Test npm update in ~/.hyper_plugins

**Comment by chabou** [comment]
Will be definitely resolved by #381

**Comment by wachunei** [comment]
Just had to fix this again, in case anyone runs into this:
* `cd ~/.hyper_plugins`
* `rm -r node_modules package-lock.json`
* `npm i`

**Comment by equinusocio** [comment]
@wachunei We have to do this every plugin is added/remove :(

**Comment by uloco** [comment]
@wachunei For me, deleting the `package-lock.json` and running `npm i` is sufficient. How about telling hyper to ignore the lockfile when running `npm install` with the `--no-shrinkwrap` flag?

**Comment by ppot** [comment]
@uloco the `--no-shrinkwrap` flag is added in merge #1896

**Comment by awaisabir** [comment]
From what I know I had the same error when I tried to install a package. Some people suggest downgrading the npm version to 4 and running `npm install` on `C:\Users\%USERNAME%\.hyper_themes`. However I found it unnecessary to downgrade your npm version. I just did `yarn install` in the same directory and everything worked completely fine. Hope this fixes some of the issues.

Cheers :beers:

**Comment by satyanshu19** [comment]
For me the problem was npm creating package-lock.json file. It started working after disabling this
`` npm config set package-lock false ``

**Comment by wachunei** [comment]
@awaisabir AFAIK next time hyper tries to install packages will fall into the same issue and you'll have to do this again by hand, so that might not be an actual solution.

@satyanshu19 here you are setting your global configuration to not use package-lock files, which might not be what you really want for other projects.

**Comment by dsslimshaddy** [comment]
even after plugins are successfully installed it dont show up in the menubar.

**Comment by AndrianMauricio** [comment]
I tried everything in here and nothing worked. I'll be back in a year to see if anything has changed.

**Comment by mattyod** [comment]
as a work around added a ```.npmrc``` file to ```~./.hyper_plugins/``` containing the line:

```
package-lock=false
```

**Comment by mdanics** [comment]
having this problem too, mac os 10.12.5, hyper 1.3.3

**Comment by equinusocio** [comment]
Any update?

**Comment by ppot** [comment]
We are working on the release at the moment. Thanks for your support and patience 💪

**Comment by alexmccabe** [comment]
This has just happened to me, out of the blue. Super upsetting :(

**Comment by mdanics** [comment]
@ppot any eta for the release?

**Comment by alexmccabe** [comment]
I received the update, but it didn't solve the issue for me. I have removed the `node_modules` directory as well as the `package-lock.json` file, however the app still crashes on launch with some plugins. 

Does this now fall on the plugin devs to solve?

**Comment by mdanics** [comment]
@alexmccabe I had to click 'Plugins' in the menu and then 'Update' for things to start working

**Comment by alexmccabe** [comment]
Unfortunately not for me, the app doesn't even launch far enough to get any menu items at all.

**Comment by ppot** [comment]
i'm working on a better install of plugins. But you can try to remove the `~/hyper_plugins` and restart the app after.

**Comment by alexmccabe** [comment]
Unfortunately this didn't work either, so I am going to go and open a ticket on the one plugin that is still failing! Thank you. This is my favourite terminal, and I am happy I can use it again.

**Comment by chabou** [comment]
@ppot 
> i'm working on a better install of plugins.
What is the problem with current install of plugins ?

@alexmccabe Yes, this is a plugin code error. For the record, which plugin is broken?

This issue concerning plugin installation is definitely fixed and released 🎉

**Comment by alexmccabe** [comment]
@chabou The offending theme is `hyper-material-theme`. There is an issue on their repo regarding this, but they're claiming everything is fine. I would mark this issue as resolved, as every other plugin behaves as expected.

**Comment by chabou** [comment]
another feedback about `hyper-material-theme`: https://github.com/zeit/hyper/issues/2080

**Comment by thaiminhlien** [comment]
Had same problem here.
Changed bash config but not working.

**Comment by chabou** [comment]
Can your explain your problem @thaiminhlien?
There is a lot of feedbacks here and all problems are supposed to be fixed (even `hyper-material-theme`).

Can you explain exactly what happens and give us some informations about your OS, hyper config etc ?

**Comment by alexmccabe** [comment]
As of latest update of both Hyper and hyper-material-theme, it's all working again for me! 😊

**Comment by thaiminhlien** [comment]
@chabou  the latest version is working fine.

**Comment by hpcodecraft** [comment]
I had the same issue on hyper 1.4.8 (OS X). Installing the plugins manually by running ```yarn``` in the ```.hyper_plugins```folder solved it for now.

**Comment by chabou** [comment]
@hpcodecraft This issue is fixed.
You should have another problem. Can you open an issue with all needed informations (asked in our issue template)?
Thanks 🙏

**Comment by hpcodecraft** [comment]
@chabou Thanks for your reply - Actually I think it may have been only a misconfiguration of NPM on my side... If I should run into it again I'll create an issue.
