### ISSUE TITLE
Something in hyper is trying to read my google drive folder

### ISSUE THREAD

**Issue by amiram** [zeit/hyper#1910]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Enterprise 64bit Version 1703 build 15063.332
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/amiram/bc91a1c9cfd8a051d53a0f3cd864b169
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Hard to reproduce. Not sure.

## Issue

I just added google drive to my pc and suddenly I see a message box with this error every few minutes. Looks like hyper is messing with my personal folders.
The folder mentioned below is used by google drive for downloads. This is a temp folder so it can be removed sometimes. I guess that the error happens when the folder is removed.
Why hyper is looking at this folder?

A JavaScript error occurred in the main process

`Uncaught Exception:
Error: ENOENT: no such file or directory, lstat 'C:\Users\****\GoogleDrive\.tmp.drivedownload\tmpquykku.drivedownload'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Gaze._addToWatched (C:\Users\****\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:292:14)
    at Gaze._internalAdd (C:\Users\****\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:206:10)
    at C:\Users\****\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:419:16
    at Array.forEach (native)
    at C:\Users\****\AppData\Local\hyper\app-1.3.3\resources\app\node_modules\gaze\lib\gaze.js:415:12
    at FSReqWrap.oncomplete (fs.js:123:15)
`

**Comment by chabou** [comment]
The only thing that is watched is your config file in your user directory.
I can't figure out why your GoogleDrive is messing with this watcher.

**Comment by albinekb** [comment]
Maybe symlinked config to your google drive? 🤔

**Comment by albinekb** [comment]
I think we should replace gaze with https://www.npmjs.com/package/node-watch

**Comment by ppot** [comment]
@albinekb Do the PR, I will review it ;)

**Comment by amiram** [comment]
@albinekb There is no such symlink. The config and the google drive folder are in the same directory, so maybe the watch was over the directory instead of the config file itself.

**Comment by alexilyaev** [comment]
+1 for replacing Gaze, not sure node-watch vs. chokidar.

Some ref:  
http://kabaehr.de/blog/Replacing-slow-gulp.watch-task/
