### ISSUE TITLE
Plugins not found

### ISSUE THREAD

**Issue by apertureless** [zeit/hyper#1917]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.5
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/apertureless/45357feb3740c7b324eb22fbdd802b83) with the contents of your .hyper.js**: https://gist.github.com/apertureless/45357feb3740c7b324eb22fbdd802b83

## Issue
Plugins are not found. 
I have to delete the `./hyper_plugins/node_modules` and re-run a yarn install. However after some time, (i guess automatically checks? ) it breaks again.

It also breaks if I try to **Plugins -> Update All Now**.

Running npm 5.0.3 and node 8.

![](https://i.imgur.com/L7eMWxB.png)
![](https://i.imgur.com/u4MfZTz.png)

**Comment by chabou** [comment]
Our plugin system is broken with npm@5 (but fixed in master). Will be shipped in our next release!
Thank you for your patience ;)

**Comment by chabou** [comment]
Duplicates #1888 😃
