### ISSUE TITLE
Refresh hotkey (Ctrl + R) on Windows blocks Vim redo

### ISSUE THREAD

**Issue by jlmakes** [zeit/hyper#1919]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro N 10.0.15063
- **Hyper.app version**: 1.3.3
- **The issue is reproducible in vanilla Hyper.app**: Yes.

## Issue

OSX distinguishes between Ctrl and Cmd, but Windows tends to use Ctrl for both scenarios.

In this instance, the Cmd&nbsp;+&nbsp;R refresh hotkey in OSX Hyper, becomes Ctrl&nbsp;+&nbsp;R in Windows Hyper—which takes precedence over the Vim redo command (Ctrl&nbsp;+&nbsp;R on both platforms).

The ability to change the Hyper hotkeys may be a large feature request, so perhaps just changing the Refresh hotkey on windows to Shift&nbsp;+&nbsp;R? I'm not sure what the solution is, but I didn't see this issue brought up and I want raise awareness for fellow developers using Windows (with new Linux subsystem).

**Comment by chabou** [comment]
The ability to change the Hyper hotkeys has been implemented here https://github.com/zeit/hyper/pull/1876
And will be shipped in next release :tada:

Default Windows hotkey will be `ctrl+shift+R` for refreching

**Comment by jlmakes** [comment]
My dreams....... 😢 .....are all..... 😭 ....coming true!

**Comment by ppot** [comment]
Thanks ❤️ Glad to made your dreams coming true!
