### ISSUE TITLE
Open Hyper in current directory doesn't work.

### ISSUE THREAD

**Issue by Mohamed3on** [zeit/hyper#1920]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Hyper.app version**:  1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  https://gist.github.com/Mohamed3on/602ceb1fc90839d0ee282bfd432a2610
- **The issue is reproducible in vanilla Hyper.app**:  Yes.

## Issue

When I try to open hyper in a directory using the context menu in a right-click, it opens in the default directory instead. I've tried with cmd and Powershell as shells, same result.
This is what I have in my registry

>  (HKEY_CLASSES_ROOT\Directory\Background\shell\Hyper\command)

:
`"C:\Users\Mohamed\AppData\Local\hyper\Hyper.exe" %V`
It used to work before, I don't know what broke it.

**Comment by Specro** [comment]
It should be `"C:\Users\Mohamed\AppData\Local\hyper\Hyper.exe" "%V"`. Did this happen after you updated Hyper or just out of nowhere? I feel like a Windows update could also be the cause 🤔

**Comment by Mohamed3on** [comment]
@Specro it doesn't make any difference, I tried both variations. I'm not sure if an update caused it as it updates automatically and I don't keep track of updates.

**Comment by Specro** [comment]
Try this `"C:\Users\Mohamed\AppData\Local\hyper\app-1.3.3\Hyper.exe" "%V"` The next release should fix this issue.

**Comment by Mohamed3on** [comment]
@Specro Worked! Thank you.
