### ISSUE TITLE
Hyper fails to load on a dual boot

### ISSUE THREAD

**Issue by TsundereBug** [zeit/hyper#1921]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.04 GNOME Shell 3.24
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Default
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
When dual booting from windows to linux, hyper fails to load because `.gvfs` is like vantablack if normal file info was a rainbow.

**Comment by TsundereBug** [comment]
Note: this only happens on booting Ubuntu for the first time? I haven't reproduced on any other distro.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
