### ISSUE TITLE
Unneccesary new version notification

### ISSUE THREAD

**Issue by saih792** [zeit/hyper#1922]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Hardened Gentoo (Linux kernel 4.9.24) 
- **Hyper.app version**: 1.3.3 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/soleera/eee16492ff6915ba9bc6c46ccaf269bb) 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

When using hyper compiled from the 1.3.3 release source, a red notification window opens in the bottom right which says "Version 1.3.3 is available. Performance improvements 🚀", despite the fact that I am running version 1.3.3. This is not reproducible when using the AppImage.

**Comment by albinekb** [comment]
Did you download the source from the releases tab? see https://github.com/zeit/hyper/issues/1834

**Comment by soleera** [comment]
Yes, the .tar.gz one to be precise.

**Comment by soleera** [comment]
Ah, I just checked hyper-1.3.3/app/package.json and it has this:
`"version": "1.3.2"`
So it'll be the same issue as that one.

**Comment by Stanzilla** [comment]
Yeah, this issue https://github.com/zeit/hyper/issues/1818

**Comment by soleera** [comment]
Do we know if it's just the version tag that wasn't bumped, or is the code also from 1.3.2?

**Comment by albinekb** [comment]
Don't know actually 😄  this is not an issue with the built ones, so probably the code in the .tar.gz is 1.3.2

**Comment by soleera** [comment]
I just checked, and if you look at the 1.3.3 tag the most recent commit is [this](https://github.com/zeit/hyper/commit/1096519e93b7af905f2dd364ee3bb14a30f1af47), which immediately precedes the version bump commit [here](https://github.com/zeit/hyper/commit/0080f1da81373964b3631065e27cbf4b7a535d0d). So the fix would be to add the 1.3.3 tag to that version bump commit and then create a new 1.3.3 archive which includes it (or just sed the version tag in the source code before compiling =P)

**Comment by mojoaxel** [comment]
I noticed a similar issue: I'm on 2.0.0-canary and getting the "Please update to 1.4.8" message.

![image](https://user-images.githubusercontent.com/600565/38807989-cd3004ea-417e-11e8-9281-ed60300dfc5d.png)

**Comment by albinekb** [comment]
@mojoaxel if you downloaded the canary release from the releases, you need to update ´~/.hyper.js´ to use canary channel, here's the issue for that: https://github.com/zeit/hyper/issues/2704

**Comment by chabou** [comment]
Fixed in v2 🎉
