### ISSUE TITLE
Clear not working on ssh session

### ISSUE THREAD

**Issue by andreacivita** [zeit/hyper#1924]
Hi! 
Using hyper i got this error. While i'm connected by SSH to a server (remote or local), i can't use clear command. If i try, i have to exit from ssh session, clear again and re-login.

**Comment by albinekb** [comment]
- What error?
- What platform
- Version of hyper
- Any plugins?

Steps to reproduce?

*Please fill in the [issue template](https://github.com/zeit/hyper/blob/master/.github/issue_template.md)*

**Comment by andreacivita** [comment]
+ Error: typing "clean" in ssh session make crash of view
+ Platform: windows 10
+ Version: latest
+ No plugin

I attach a screen of error
![1](https://user-images.githubusercontent.com/4959092/27102411-7536cf0c-5085-11e7-9f38-4275b1db41b2.png)
![2](https://user-images.githubusercontent.com/4959092/27102412-753970cc-5085-11e7-9b47-517d220c0913.png)

As you can see, executing clear command does not clear hyper, but create this horrible crash.

**Comment by gaganjyot** [comment]
Facing same issue in running bash in hyper on windows
What error? unable to clear the screen
What platform -> Windows 10
Version of hyper -> probably 1.3.3 ( downloaded from hyper.is today ).
Steps to reproduce -> Type sommethign, enter some commands. type clear and enter. Or even ctrl + l

**Comment by theluk** [comment]
+1

**Comment by AngelVkz** [comment]
The problem still

**Comment by chabou** [comment]
@andreacivita @gaganjyot
What is the shell of your remote host?

@AngelVkz 
Please give us more details: your OS, reproductible without any plugin, screenshot etc...

**Comment by andreacivita** [comment]
@chabou bash

**Comment by ARGibson** [comment]
I am also having this issue

- Error: Screen is not cleared when using SSH (either when using tools like nano/vim or when using 'clear' directly)
- Platform: Windows 10 Enterprise
- Version: Latest (1.4.8)
- Plugins: `['hyperterm-paste','hyperline','hyperterm-alternatescroll','hyper-tab-icons','hyper-pane','hyperterm-material','hyperterm-transparent-bg']`

The problem occurs without plugins so I have already ruled any of the ones listed out, appears to be an issue with Hyper itself.

To demonstrate, if I have a clear (ha!) screen inside an ssh session:
![image](https://user-images.githubusercontent.com/119761/31282585-ea17768a-aaaa-11e7-8fdd-7248cf68ff41.png)

And then I open a file in nano:
![image](https://user-images.githubusercontent.com/119761/31282627-0bbe63ca-aaab-11e7-9d25-fd8bf408aa8c.png)

**Comment by ARGibson** [comment]
After a bit of digging around I came across a similar issue being reported in Git For Windows (
https://github.com/zeit/hyper/issues/1559) which referenced Hyper and adding the TERM environment variable to hyper.js under the env section with a value of either 'cygwin' or 'msys' appears to solve the issue, it certainly has for me.

**Comment by andreacivita** [comment]
@ARGibson could you tell us how did you fix? Possibly step-by-step :)

**Comment by jusdeleon** [comment]
Having this issue too.

What error? - Unable to clear the screen on SSH session
What platform - Windows 10 SL
Version of hyper - 1.4.8
Any plugins? None
