### ISSUE TITLE
Pasted text gets copied twice in git repository

### ISSUE THREAD

**Issue by artivilla** [zeit/hyper#1929]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra v10.12.5
- **Hyper.app version**: v1.3.3 (1.3.3.1754)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/artivilla/a011e4dfc4e474554f21f5339770f1e7
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: `Unknown OSC code: "1"`
- **The issue is reproducible in vanilla Hyper.app**: Not sure how to do that

## Issue
If I paste any text using `cmd+V` or using raw-paste as I have `hyperterm-paste` installed, it get's pasted twice. Only occurs when I'm checked into a git repository. Here's an example:
`application core-linting-fixes 32d ▲ ➜ hyperterm-pastehyperterm-paste`

**Comment by CodeTheory** [comment]
Hi @artivilla. If you disabled the hyperterm-paste app, does this problem still occur? If not then it's an issue for hyperterm-paste.

**Comment by artivilla** [comment]
@CodeTheory I can't reproduce this issue anymore. If it does occur again, I'll try what you recommended and post in the appropriate repo. Thanks :)
