### ISSUE TITLE
Directory listing, rows are not aligned 

### ISSUE THREAD

**Issue by mazedlx** [zeit/hyper#1930]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.1
- **Link of a [Gist](https://gist.github.com/mazedlx/f09d718080410b302be4846c4d9ff672) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

When using Hyper (doesn't matter as CMD or Bash on Windows/ZSH) the directory listing alignment gets messed up when in fullscreen. See the screenshots, haven't changed anything in the settings.

### This is ok (non-fullscreen)

![ok](https://user-images.githubusercontent.com/9453522/27082056-9b9fddc4-5043-11e7-8632-cecdea9fdc06.PNG)

### This isn't (fullscreen, look at the right side, those numbers should be at the beginning of the previous line)
![nok](https://user-images.githubusercontent.com/9453522/27082082-b00724c0-5043-11e7-99b9-721dc6c9a0d5.PNG)

**Comment by Codimale** [comment]
I'm not a regex expert but I think it might be a regex issue. Can anyone confirm?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
