### ISSUE TITLE
Need to escape the parentheses when dragging in a location

### ISSUE THREAD

**Issue by heathflohre** [zeit/hyper#1933]
I often cd into different directories by dragging the location from the Finder into the terminal window. Hyper escapes the spaces, but doesn't escape parentheses, like Dropbox\ \(Work\)/Development.

1. Start a session
2. Type 'cd '
3. Drag a folder location that contains a parentheses in the name into Hyper
4. A return give, "bash: syntax error near unexpected token `('"
-

Hyper 1.3.3
Electron 1.4.16
darwin x64 16.6.0

**Comment by albinekb** [comment]
Fixed in master 👌
