### ISSUE TITLE
Cursor renders in the wrong position after rapidly navigating in vim

### ISSUE THREAD

**Issue by kkuhle** [zeit/hyper#1936]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: <Windows 10>
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
When I rapidly navigate in vim within hyper, the cursor is in the wrong position.  See below where I am using the x key to delete characters.

![Alt Text](http://i.imgur.com/DcrUrPI.gif)

I believe this is only occurring when the window is large enough.  I am typically in full screen.

**Comment by albinekb** [comment]
The plugin `hyperpower` is reported to have very high CPU usage: see [here](https://github.com/zeit/hyper/search?q=hyperpower&type=Issues&utf8=%E2%9C%93) 

Can you try removing that and see if it's still a problem?

**Comment by kkuhle** [comment]
I tried removing that, but unfortunately still has the issue.  In fact I've un-commented all plugins > restarted hyper and this issue persists.

I am unable to replicate this on Mac

**Comment by albinekb** [comment]
Can you try https://code.visualstudio.com/ built in terminal? If it's there too then it's a windows issue

**Comment by kkuhle** [comment]
I'm unable to dupe in in vscode terminal.  I also have the ubuntu bash for windows installed and I am unable to duplicate it there.

**Comment by kkuhle** [comment]
I just installed hyper on my home desktop and I'm unable to duplicate this issue.  

I've renamed my .hyper.js and then reinstalled 1.3.3 and am still having this issue.  I'm not sure what else could be causing this very weird issue.  Seems to be specific to something I've got going on this workstation though.

**Comment by yousefissa** [comment]
Also having this issue.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
