### ISSUE TITLE
sed: couldn't write 73 items to stdout: Broken pipe

### ISSUE THREAD

**Issue by pchomik** [zeit/hyper#1940]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla
## Issue

I recorded video about this issue: https://drive.google.com/open?id=0B9IyOoD-vB_Yd3d1c01uR3kwQU0

I'm using fzf application available here: https://github.com/junegunn/fzf
Command syntax "cd **" comes from this application.

I don't have such issue when I'm using different terminal e.g. terminator.

Thanks for help

**Comment by chabou** [comment]
Thank you for your detailed feedback!
I didn't kno `fzf`! Awesome!
But I can't reproduce your problem. It works fine in Hyper for me 😞

**Comment by pchomik** [comment]
How can debug this problem because I have it on second computer with fresh installation?

**Comment by chabou** [comment]
Can you try to reproduce with `master`? If your problem occurs, can you try with `xterm` branch ?
This branch is very experimental but this is our WorkInProgress to adopt `xterm.js` and replace `hterm`.

**Comment by pchomik** [comment]
I tried with master - same issue.
I will try with xterm and I will let you know.

**Comment by pchomik** [comment]
In xterm branch problem looks the same.
I discovered that problem is visible only in $HOME directory or root directory. Problem some how depend on number of files/directories.
I modified fzf script from
```
if ! declare -f _fzf_compgen_dir > /dev/null; then
  _fzf_compgen_dir() {
    command find -L "$1" \
      -name .git -prune -o -name .svn -prune -o -type d \
      -a -not -path "$1" -print 2> /dev/null | sed 's@^\./@@'
  }
fi
```
to version which excludes hidden directories
```
if ! declare -f _fzf_compgen_dir > /dev/null; then
  _fzf_compgen_dir() {
    command find -L "$1" \
      -name .git -prune -o -name .svn -prune -o -type d \
      -a -not -path '*/\.*' -not -path "$1" -print 2> /dev/null | sed 's@^\./@@'
  }
fi
```
Error is not visible but after selecting some entry my Enter is not working. I have to press Ctrl+C to go forward.
I recorded two more videos:
* fzf2-modified - to show that error doesn't not exist but problem with Enter stays
  https://drive.google.com/open?id=0B9IyOoD-vB_YbElvVzlBSDRieWs
* fzf3-from-home-and-not - to show that problem depends from number of directories
  https://drive.google.com/open?id=0B9IyOoD-vB_YRUVublVlM2ZwaGM

**Comment by pchomik** [comment]
Today I was able to confirm that error depend on number of files.
If you look carefully you will see that fzf is counting files. Error appears only if counter is still increasing. Everything is ok when I wait for counter and then press Enter. Error appears when I press Enter when fzf is scanning directory.
In addition in other terminal I see delay between Enter and path completion.

**Comment by pchomik** [comment]
I found how to fix my problem. 
I excluded all hidden directories and node_modules directories from search. I found that I have many node.js projects and number of directories inside node_modules is huge.
Please treat this issue as minor.

**Comment by chabou** [comment]
thank you so much for your fully qualified feedback ❤️
