### ISSUE TITLE
Unattached Developer Tools window 

### ISSUE THREAD

**Issue by saadq** [zeit/hyper#1941]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra Version 10.12.2
- **Hyper.app version**: Version 1.3.3 (1.3.3.1754)
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Awhile back, I had accidentally made my dev tools pop out into a separate window:

<img width="1166" alt="screen shot 2017-06-16 at 10 52 12 am" src="https://user-images.githubusercontent.com/5678694/27231811-e2e5f2aa-5281-11e7-9c7a-abd1a2ee7a0b.png">

Normally, in apps like Chrome and Atom, I can long-click the 3 dots at the top right of the dev tools to change its position. However, when I do so in Hyper, there are no options there:
<img width="1140" alt="screen shot 2017-06-16 at 10 52 43 am" src="https://user-images.githubusercontent.com/5678694/27231868-0e5538c4-5282-11e7-87af-57a6391f275f.png">

Is there any way to attach it back to the terminal? I've tried reinstalling hyper and I haven't done any configuration in my `.hyper.js` at all.

**Comment by saadq** [comment]
Actually as a strange sidenote – I just tried uninstalling and reinstalling (this time I installed it from `brew`), and it was able to fix the devtools. However, there was a message to install the latest version (**1.3.3**), and once I did the devtools was unattached again.

**Comment by pablopunk** [comment]
I think this is the default in hyper

**Comment by saadq** [comment]
But when in version 0.8.1 (the version that's initially installed with Homebrew), you have the ability to change its position:

![screen shot 2017-06-16 at 11 06 49 am](https://user-images.githubusercontent.com/5678694/27232649-d2846e70-5284-11e7-9432-1a171648fb7e.png)

However, once I upgrade to Version 1.3.3, the developer tools is now popped out and you no longer have the ability to change its position. Is this intentional/expected behavior?

**Comment by ppot** [comment]
@saadq We introduced this since this produced the frame not able to be moved from an upstream chrome bug.

**Comment by CodeTheory** [comment]
Looking into this a bit more, looks like a recent Electron version disabled this for some circumstances. Will close this issue because I don't think it's crucial to Hyper's development and seems to be upstream.
