### ISSUE TITLE
Opening Preferences launches R-Studio!?!

### ISSUE THREAD

**Issue by AllanLRH** [zeit/hyper#1943]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X 10.10.5 Yosemite 
- **Hyper.app version**: Version 1.3.3 (1.3.3.1754)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/AllanLRH/ae3291fd8231a974e898c82ffc47d334 (Never modified manually)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
When opening the preferences, wether from <kbd>Cmd</kbd>+<kbd>,</kbd> or by clicking _Hyper_ –> _Preferences_, R-studio seems to launch, and this box appears:
![hp](https://user-images.githubusercontent.com/2641327/27247002-90ee80d8-52f5-11e7-93bd-48a726e38cf7.png)

This error seems so weird to me, that I made a video of it to convince you it's true:
[r-studio-hyper.mov.zip](https://github.com/zeit/hyper/files/1082108/r-studio-hyper.mov.zip)

**Comment by chabou** [comment]
Certainly because RStudio is associated with `.js` filetype

**Comment by AllanLRH** [comment]
Yes, of course it was -_-
I use Sublime Text for everything, and usually opens everything from Terminal, so it didn't even occur to me that it could be the source of the error.
