### ISSUE TITLE
Can't open preferences.

### ISSUE THREAD

**Issue by cj81499** [zeit/hyper#1945]
I tried to open the preferences and got this error:

![image](https://user-images.githubusercontent.com/9152032/27255304-905087e2-5369-11e7-824d-d25a92e921bc.png)

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by chabou** [comment]
Duplicate of #1812 thanks for reporting.
Fixed in master and will be shipped in next release

**Comment by cj81499** [comment]
Sorry for the repeat. Thanks for the quick help!

**Comment by chabou** [comment]
No problem. With a new release you wouldn't have to repeat an issue... Sorry for this delay.
