### ISSUE TITLE
Feature: Add overlay panel like iTerm 2

### ISSUE THREAD

**Issue by equinusocio** [zeit/hyper#1948]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue
It would be awesome have the overlay panels feature like iTerm 2.

**Comment by albinekb** [comment]
Like https://github.com/Bareflank/hypervisor  ?

**Comment by equinusocio** [comment]
Yes, hyperterm-overlay. Something built with the app and configurable through preferences.

**Comment by albinekb** [comment]
It's already a plugin, shouldn't be in the core.

**Comment by equinusocio** [comment]
So? If there is a plugin it can't be implemented natively with the app? Those plugins are full of bugs and unsupported.
- hyperterm-overlay is built for Hyper.app >= 0.7.0 (o.O) and latest release 7 months ago
- Both plugins provide a different solution than one i mentioned. I term2 provide both windows and overlay panel with differents tabs and sessions.

**Comment by albinekb** [comment]
Yep, that's doable as a plugin, we are actually going to break out most functions as plugins (core plugins), to make it easier to maintain :)
