### ISSUE TITLE
Hyper opened once, never again, even after reinstalls

### ISSUE THREAD

**Issue by javislaterlp** [zeit/hyper#1950]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default, I didn't modify
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
I just installed Hyper (from official site) and it opened, so I pinned it to the taskbar and closed, to later install hyper-pokemon (via hpm, just like https://github.com/hyper-pokemon/hyper-pokemon). Now It won't open, and clicking just spawns new "Hyper" processes but nothing appears. I tried to uninstall-reinstall the exact same way, and It appears the initial image (the greenish gif) but then it stops and Hyper doesn't open (but the processes are still there). There isn't a single error displayed so I can't provide you with more info/screenshots. Literally nothing, just background.

**Comment by jamo** [comment]
Maybe the plugin broke it? 
Try removing/resetting config (~/.hyper.js and ~/.hyper-plugins on unix)

**Comment by javislaterlp** [comment]
Worked! thank you. I removed any reference to the plugin, then reinstalled and it's ok
