### ISSUE TITLE
Unable to kill hyper process upon crash in windows

### ISSUE THREAD

**Issue by brucedjones** [zeit/hyper#1952]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **1.3.3**: 
- **Link of a [Gist](https://gist.github.com/brucedjones/cab0864c85f3cae230625daa06b65fa3)**: 
- **N/A** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
On Windows 10 Hyper crashes after being idle for some time. I haven't figured out the steps to reproduce this crash yet, however every time it does crash I'm unable to kill the process. I go through task manager and kill every hyper process I can, but the two processes related to the unresponsive terminal window will not end.

Edit: If I try to kill the process with [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) I get the message "Error opening Hyper.exe: Access is denied. This happens even when running process explorer as admin.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
