### ISSUE TITLE
Issue Updating Plugins

### ISSUE THREAD

**Issue by justinhazzard** [zeit/hyper#1954]
Everything seems to work except for the "Update all now" function in the Plugins menu. I don't particularly need to update any plugins but I cannot avoid this because the application seems auto-update on startup. 

Also, "Preferences" doesn't seem to work for me. Instead I am greeted JScript runtime error stating that "'module' is undefined" (Code 800A1391) at line 5 in the Script C:\Users\js\.hyper.js .

I hope these issues can be resolved because I really enjoy the application and can deal with a slightly annoying error message on startup for the time being.

Peace,
Justin

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by betoflakes** [comment]
Same Here

**Comment by lui-habl** [comment]
Yup, me too

**Comment by chabou** [comment]
There are 2 issues here.
"Updating plugin issue": If you have npm@5, it duplicates #1888 (already fixed in master)
"Preferences": It duplicates #1812 (already fixed in master).
Conclusion: we need a release.

Feel free to comment if I missed something
