### ISSUE TITLE
Preferences opens Fluid.app?

### ISSUE THREAD

**Issue by ylluminate** [zeit/hyper#1955]
Whenever I open preferences in app (cmd-, or go to the menubar and click it from there) in macOS, the app opens Fluid.app instead of an actual preferences for Hyper... Any thoughts on this?

**Comment by CodeTheory** [comment]
Hyper preferences open in your default text editor, which is sounds like is Fluid.app for you.
Hyper doesn't have any preferences UI 😄

**Comment by ylluminate** [comment]
LOL, that's really wild. Fluid.app isn't my default text ed, so..... Wow, I'm going to have to look into this deeper I guess.

**Comment by CodeTheory** [comment]
Would be really good to see what you discover. There's a lot of logic that goes into opening the default text editor (including logic for different platforms). Please let us know! cc @albinekb @chabou

**Comment by ylluminate** [comment]
Well, just for kicks and giggles I tried this here in hopes to make sure that TextMate was my default editor, but it didn't solve the issue:
```
/usr/libexec/PlistBuddy -c 'Print CFBundleIdentifier' /Applications/TextMate.app/Contents/Info.plist
defaults write com.apple.LaunchServices LSHandlers -array-add '{LSHandlerContentType=public.plain-text;LSHandlerRoleAll=com.macromates.TextMate;}'
```

Still opening with Fluid.app.

**Comment by CodeTheory** [comment]
I'm not expert in this, but I'm pretty sure Hyper tries to use the app associated with the `$EDITOR` env variable. What's assigned to that?

**Comment by ylluminate** [comment]
`echo $EDITOR` -> `mate -w`

**Comment by CodeTheory** [comment]
Okay, looking into this a bit more.
The logic for opening the preferences is located here: https://github.com/zeit/hyper/blob/master/app/config/open.js
This file uses Electron's `shell` API for opening files in their default manner. I'm not totally sure how Electron handles this so there must be something set somewhere in your system that defines Fluid.app as the default text editor for the .js file type.

If you open a js file elsewhere, does it open with Fluid.app?

**Comment by ylluminate** [comment]
You hit it on the head. I'm not a js dev (prefer Opal to going nuts with js proper on our apps) so I never really open js from Finder. Was able to 'Change All...' for .js to TextMate and now it's firing off.  Thanks for finding that!

**Comment by jdsimcoe** [comment]
I have Vim set as my default editor in `zsh` but Hyper continues to open Coda whenever I do `cmd + ,`. Any ideas on how to resolve this?

**Comment by albinekb** [comment]
How have you set `vim` as your editor?  We use the OS default editor, not `EDITOR` env variable @jdsimcoe

**Comment by jdsimcoe** [comment]
Ahhhh... that is my problem I guess. I have it set in my `env` variable.

**Comment by albinekb** [comment]
Yeah we changed that :) But will be revisiting this soon, with an inline editor like VS Code has as default, and options to use the current way or the old way (vim) to chose from 👍 @jdsimcoe

**Comment by reorx** [comment]
@albinekb how is the inline editor plan going? the fact that a terminal emulator opens its preference file in another app looks weird and stupid, and annoys me every time I hit `cmd + ,` subconsciously.
