### ISSUE TITLE
hyper.is broken after manually adding plugins

### ISSUE THREAD

**Issue by matswainson** [zeit/hyper#1956]
## Issue
I tried copying and pasting a friends plugin set up my hyper preferences file.

Following this, unfortunately, I managed to break hyper - and this is all I see when opening now:

<img width="430" alt="screen shot 2017-06-23 at 14 05 37" src="https://user-images.githubusercontent.com/6138172/27481482-11cbbae6-581d-11e7-9cff-51873d0aa204.png">

After removing from the Applications directory, and re-installing multiple times from the .dmg file, I am stuck in the same broken state as before.

- **OS version and name**: macOS Sierra 10.12.5
- **Hyper.app version**: 1.3.3

**Comment by math2001** [comment]
What is the content of the `~/.hyper.js`? I'm not sure that when you un-install hyper it removes it. If the problem indeed comes from it, then it would explain why re-installing was useless.

**Comment by RedDuckss** [comment]
I can confirm this happens on Windows as well. I am running Windows 10 and have the same issue, Hyper is stuck in a broken state even after multiple re-installs. I have even gone in and removed every file and folder relating to Hyper I can find after uninstalling but everything is still broken.

**Comment by heroheman** [comment]
Same problem here (windows 10). Adding plugin with `hpm` or adding it in the pluginarray in my `.hyper.js` is not installing anything. Only after removing the `.package-lock.json` and doing a separate `npm i` does the trick.

**Comment by dandevri** [comment]
@heroheman Think this has something to do with the lastest npm version `5.0.3`. I think (but correct me if I am wrong) it nows installs from the package-lock file by default. A temporary fix for me was to:
* Add the plugins to you're `.hyper.js` file
* Navigate to the `.hyper_plugins` folder
* Remove `package-lock.json` and `node_modules`
* Open up the terminal
* `cd` into the `.hyper-plugins` folder
* run `npm i`

This will build a new package-lock.json file and creates the node_modules directory with the right packages for the plugins to run.

**Comment by IronLu233** [comment]
I used a theme called [hyper-material-theme](https://www.npmjs.com/package/hyper-material-theme) and met the same problem.

I removed this theme, and restart it. Hyper worked correctly.

I think there are some bug in your extensions.

What extensions did you install?

**Comment by math2001** [comment]
+1 @IronLu233. I haven't tested hyper-material-theme, but indeed, a buggy theme will prevent the hyper window from showing up (learned this the hard way while creating mine 😄)

**Comment by matswainson** [comment]
Removing the theme as @IronLu233 suggested has fixed my issue.

(I thought that by uninstalling hyper, the configuration file from my previous set-up would also have been removed.)

Thank you all for the great responses! Much appreciated.
