### ISSUE TITLE
Cannot start hyper with fish shell

### ISSUE THREAD

**Issue by jvrdom** [zeit/hyper#1961]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04.2 LTS Xenial
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jvrdom/5a84f6b24cf674fbe25b92dde3254b79
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: When run the app in dev console appears:

**Uncaught TypeError: Cannot read property 'substr' of null** on conditional 
`if ('rgba' == I.substr(0,4))` on `function N.colors.crackRGB.
`
- **The issue is reproducible in vanilla Hyper.app**: No, with vanilla works fine. It happens with some plugins, in my case with those:

* hypercwd
* hyper-statusline
* hyper-material-box
* hyper-pane

## Issue

When in my config set the shell to "/usr/bin/fish" and run the app, no cursor appears and i can't do anything, but if i ran `/usr/bin/fish` as a command work perfectly.

**Comment by albinekb** [comment]
If it works in vanilla, then it’s one of your plugins. Can you narrow it down to which one and post your issue there? I beleive this is not an issue with hyper itself as it works without plugins.

**Comment by jvrdom** [comment]
@albinekb Thanks for the quick response, I try the plugins one at a time and the error happens, so I have to post an issue in every plugin :sweat_smile: 

Thanks!

**Comment by CodeTheory** [comment]
@jvrdom Instead of posting in issue in every plugin, try and isolate the plugin that causes the issue and then post an issue to that plugin.

**Comment by UltCombo** [comment]
I'm on latest Hyper version (1.4.3) on Ubuntu GNOME 16.04 with latest Fish shell (2.6.0-1~xenial), and I'm experiencing this same issue 100% of the time:

```
Uncaught TypeError: Cannot read property 'substr' of null
    at Object.t.colors.crackRGB (bundle.js:47)
    at Object.t.colors.mix (bundle.js:47)
    at r.TextAttributes.syncColors (bundle.js:47)
    at r.TextAttributes.setDefaults (bundle.js:47)
    at r.VT.CSI.m (bundle.js:47)
    at r.VT.dispatch (bundle.js:47)
    at r.VT.parseCSI_ (bundle.js:47)
    at r.VT.interpret (bundle.js:47)
    at r.Terminal.interpret (bundle.js:47)
    at l.forEach (bundle.js:41)
```

Please reopen the issue.

**Comment by UltCombo** [comment]
I just forked the repository, cloned, installed deps and ran Hyper in dev mode. Weirdly enough, it's working fine. Then I built the binaries and installed the `.deb` file through `dpkg` and the issue is back! (I made sure to purge the old Hyper installation before installing the generated deb file)

So it seems to be an issue in the build process, likely in the minifier or bundler.

**Comment by UltCombo** [comment]
I've removed `babel` from the `dist` script and the error persists... I've also removed `NODE_ENV=production` from the `build` script and the issue still persists:

```
Uncaught TypeError: Cannot read property 'substr' of null
    at Object.lib.colors.crackRGB (bundle.js:35116)
    at Object.lib.colors.mix (bundle.js:35098)
    at hterm.TextAttributes.syncColors (bundle.js:48690)
    at hterm.TextAttributes.setDefaults (bundle.js:48631)
    at hterm.VT.CSI.m (bundle.js:50974)
    at hterm.VT.dispatch (bundle.js:49503)
    at hterm.VT.parseCSI_ (bundle.js:49351)
    at hterm.VT.interpret (bundle.js:49262)
    at hterm.Terminal.interpret (bundle.js:46351)
    at __WEBPACK_IMPORTED_MODULE_2_runes___default.forEach.rune (bundle.js:34316)
```

So the issue is either in the electron-builder or perhaps I'm missing something.

**Comment by UltCombo** [comment]
I've been trying to run Hyper from the AppImage now, and I noticed that sometimes (rarely) it does not throw an error and works as expected. It's most likely due to a race condition in the app startup logic.

**Comment by UltCombo** [comment]
At `hterm.TextAttributes.prototype.setDefaults`, both received arguments (`foreground`, `background`) are `null`. Perhaps the issue is in the `hterm` dependency?

**Comment by UltCombo** [comment]
Tried to update the `hterm-umdjs` dependency to the latest published version (`1.2.0` which wraps hterm `1.63.sha.a543c06`) as well as building `hterm-umdjs` with the latest hterm (1.71.sha.a3b8fec) and this issue is still not fixed... At least the error looks different (but still the same problem) 😅 

```
Uncaught TypeError: Cannot read property 'startsWith' of null
    at Object.t.colors.crackRGB (bundle.js:47)
    at Object.t.colors.mix (bundle.js:47)
    at r.TextAttributes.syncColors (bundle.js:47)
    at r.TextAttributes.setDefaults (bundle.js:47)
    at r.VT.CSI.m (bundle.js:47)
    at r.VT.dispatch (bundle.js:47)
    at r.VT.parseCSI_ (bundle.js:47)
    at r.VT.interpret (bundle.js:47)
    at r.Terminal.interpret (bundle.js:47)
    at l.forEach (bundle.js:41)
```

**Comment by chabou** [comment]
🤔 
Can you try this with `xterm` branch ?

**Comment by chabou** [comment]
Did you try to remove all your plugins?

**Comment by UltCombo** [comment]
> Did you try to remove all your plugins?

Yes, I was using a clean install without any plugins.

> Can you try this with `xterm` branch ?

Sure, I'll try tonight.

**Comment by UltCombo** [comment]
I've just checked out the `xterm` branch and built the `.deb` package, Hyper starts fine with fish now! Thanks @chabou 😄

Though, I noticed there's are issues with vertical split panes in the xterm branch with fish. This is a different issue though, so I'll report it separately.

Just wondering, is there a tracking issue or roadmap to merge xterm branch into master?

**Comment by chabou** [comment]
@UltCombo Not yet, but we really want to put `xterm` on Canary update channel ASAP
🔜
