### ISSUE TITLE
Hyper redirects on entering an URL

### ISSUE THREAD

**Issue by Shivang-Bhandari** [zeit/hyper#1964]
<img width="540" alt="screen shot 2017-06-30 at 2 57 16 am" src="https://user-images.githubusercontent.com/16368588/27711178-f1d31572-5d3f-11e7-8ed7-0ab59cacc4ac.png">
<img width="540" alt="screen shot 2017-06-30 at 2 57 29 am" src="https://user-images.githubusercontent.com/16368588/27711180-f3c44982-5d3f-11e7-9d15-b06d22da35cd.png">

**Comment by CodeTheory** [comment]
@Shivang-Bhandari Are you talking about the website opening within Hyper? This is the intended behaviour...
Also please fill out the issue template so we know what you're talking about. 2 screenshots and no text isn't very helpful.
