### ISSUE TITLE
Words and cursor get in a mess when I change the default fontFamily

### ISSUE THREAD

**Issue by jeasonstudio** [zeit/hyper#1965]
Just like this.
![image](https://user-images.githubusercontent.com/17971291/27725312-4aa1efd0-5da8-11e7-9451-d39e852b2cfe.png)

By the way, I'm using WSL.
How can I fix this?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
