### ISSUE TITLE
curl --request has some issue

### ISSUE THREAD

**Issue by nahkar** [zeit/hyper#1969]
When I work with curl and make **"curl --request"** I get a wrong result.
![](http://joxi.net/Q2KKL8F4GxjW2j.jpg)

**Comment by chabou** [comment]
I can't reproduce.
It would have been better to use our issue template.
Please reopen an issue and give us all informations asked in this template (OS, Hyper version, Hyper config, reproductible with a vanilla Hyper, etc...).
