### ISSUE TITLE
Plugins not showing up

### ISSUE THREAD

**Issue by dsslimshaddy** [zeit/hyper#1970]
Im installing plugins using hpm. the plugins are also added in hyper.js file. but plugins are not working.

for example i installed hyperline. it didnt show up status bar.

the plugins option in menu only has `Update all Now`

**Comment by DuIslingr** [comment]
This has already been fixed in master. Either build it yourself or wait for the next release.

**Comment by dsslimshaddy** [comment]
im getting error when doing `yarn run dist`. `yarn run app` is fine.

the error is something related to gyp ERR

**Comment by DuIslingr** [comment]
I cant help you there. I don't build it myself. I only know the issue about the plugins has been fixed based on other issues that are now closed regarding it. you will have to show the whole error for better assistance.

**Comment by dsslimshaddy** [comment]
#1971  i have opened the issue.

**Comment by dsslimshaddy** [comment]
solved it by going to `./hyper_plugins` and doing a `yarn install`
