### ISSUE TITLE
[Linux] [GNOME] [Ubuntu] Adding or Removing Plugins Causes Window Manager to Restart

### ISSUE THREAD

**Issue by niedzielski** [zeit/hyper#1972]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu GNOME v17.04
- **Hyper.app version**: v1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/niedzielski/4f29cdce01598b3bfdda31c02f128c14
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Vanilla + any plugin

## Issue
1. Edit ~/.hyper.js to add or remove a plugin. For example, hyper-one-light or hyper-papercolor.
1. Save the changes.
1. Observe that GNOME restarts.

When changing something as simple as a color scheme, restarting Hyper is fine. However, restarting the window manager is very unexpected, heavyweight, risky behavior. I lost all my windows when this happened while I was first configuring Hyper and GNOME crashed instead of restarted (and again while I was on a video call with a colleague and Hyper was in the background and decided to auto-upgrade a plugin). Ideally, restarting GNOME should be unnecessary, but if it is required, a warning prompt should be shown first. This is a particularly poor experience because plugins auto-update (I don't think this is configurable).

On a happier note, thanks for making such a cool terminal!

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
