### ISSUE TITLE
npm installing packages - error

### ISSUE THREAD

**Issue by joneslloyd** [zeit/hyper#1975]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.5 (16F73)
- **Hyper.app version**: Version 1.3.3 (1.3.3.1754)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/joneslloyd/ffa7dacb33e31db9a6b4b8f813e1df81
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: https://gist.github.com/joneslloyd/bf16f81c84294c7a4e2d9b0f41b571ae
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Running `npm install <any-hyper-package>` gives the following output:
```
lloyd-macbook:~ joneslloyd$ npm install hyperline
npm WARN saveError ENOENT: no such file or directory, open '/Users/joneslloyd/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/joneslloyd/package.json'
npm WARN joneslloyd No description
npm WARN joneslloyd No repository field.
npm WARN joneslloyd No README data
npm WARN joneslloyd No license field.

+ hyperline@0.6.1
updated 1 package in 0.945s
```
(And the package is not active in Hyper)

I'm using Mackup to get my Hyper settings from my other machine, where everything is running correctly, but paths (etc.) are the same.

**Comment by CodeTheory** [comment]
You're trying to install hyper extensions via npm on in your user directory?

If you follow the instructions here: https://hyper.is/#extensions it says you should add the name of the plugin you want in your .hyper.js config file and it will install your extensions.
Alternatively you can use [hpm](https://github.com/zeit/hpm) to install modules to hyper from your command line like you're trying to do with npm.

**Comment by joneslloyd** [comment]
Ah sorry! I just followed the instructions to the right here: https://www.npmjs.com/package/hyperline
(But they are auto-generated).

I guess my error is not the above then, because the extensions are all in my .hyper.js file, yet won't install.

Is the debug info already provided sufficient?

**Comment by joneslloyd** [comment]
Actually - Solved. `npm config set package-lock false` sorted it (removed `package.json`'s lock file).
