### ISSUE TITLE
Cannot install plugins

### ISSUE THREAD

**Issue by colepeters** [zeit/hyper#1976]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.5
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [link](https://gist.github.com/colepeters/d623f9819fb54245a877d3f487fc65c0)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: See screenshot
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue
NB: I have seen other issues regarding plugin installations but not of this specific problem.

My Hyper is no longer installing plugins. I have tried deleting and re-downloading Hyper, removing my `.hyper_plugins` directrory, starting from a fresh `.hyper.js` config, all to no avail. Whenever I add plugins to my `plugins` array, I get the following errors for every plugin:

![image](https://user-images.githubusercontent.com/1713932/27833974-e92beeea-60cc-11e7-90e3-d0cfbc686063.png)

`ls -a` from `.hyper_plugins`:
```shell
drwxr-xr-x  2 cole  staff    68B  4 Jul 15:15 local
-rw-r--r--  1 cole  staff    76B  4 Jul 15:22 package-lock.json
-rw-r--r--  1 cole  staff   350B  4 Jul 15:22 package.json
```

Contents of `package.json`:
```json
{
  "name": "hyper-plugins",
  "description": "Auto-generated from `~/.hyper.js`!",
  "private": true,
  "version": "0.0.1",
  "repository": "zeit/hyper",
  "license": "MIT",
  "homepage": "https://hyper.is",
  "dependencies": {
    "hypercwd": "latest",
    "hyperlinks": "latest",
    "hyperterm-paste": "latest",
    "hyper-space": "latest"
  }
}
```

Running `npm i` doesn't install any of the packages listed in `dependencies`. It seems to just exit the process successfully without installing anything.

Help!

**Comment by karlhorky** [comment]
I think this may have something to do with the lockfile that was introduced with npm 5.

On `npm i` I get `up to date`:

```sh
➜  ~ cd ~/.hyper_plugins
➜  .hyper_plugins l
total 16
drwxr-xr-x   5 k  staff   170B  4 Jul 17:44 .
drwxr-xr-x+ 57 k  staff   1.9K  4 Jul 17:45 ..
drwxr-xr-x   2 k  staff    68B  9 Apr 21:47 local
-rw-r--r--   1 k  staff    76B  4 Jul 17:44 package-lock.json
-rw-r--r--   1 k  staff   271B  4 Jul 17:44 package.json
➜  .hyper_plugins cat package.json
{
  "name": "hyper-plugins",
  "description": "Auto-generated from `~/.hyper.js`!",
  "private": true,
  "version": "0.0.1",
  "repository": "zeit/hyper",
  "license": "MIT",
  "homepage": "https://hyper.is",
  "dependencies": {
    "hyperterm-atom-dark": "latest"
  }
}
➜  .hyper_plugins npm i
up to date in 0.442s
```

After manually deleting the lockfile and re-running `npm i`, plugins seem to be working again.

```sh
➜  .hyper_plugins rm package-lock.json 
➜  .hyper_plugins npm i
npm notice created a lockfile as package-lock.json. You should commit this file.
added 1 package in 0.558s
➜  .hyper_plugins l
total 16
drwxr-xr-x   6 k  staff   204B  4 Jul 17:45 .
drwxr-xr-x+ 57 k  staff   1.9K  4 Jul 17:45 ..
drwxr-xr-x   2 k  staff    68B  9 Apr 21:47 local
drwxr-xr-x   3 k  staff   102B  4 Jul 17:45 node_modules
-rw-r--r--   1 k  staff   317B  4 Jul 17:45 package-lock.json
-rw-r--r--   1 k  staff   271B  4 Jul 17:45 package.json
```

**Comment by karlhorky** [comment]
I guess @wachunei came to a similar conclusion in #191:  https://github.com/zeit/hyper/issues/191#issuecomment-309854692

**Comment by dsslimshaddy** [comment]
i also got this issue #1970 . as you said `npm i` did not install packages but by using `yarn install` it installed everything .

**Comment by wachunei** [comment]
I think it is not right to go into the folder and run `yarn`, this will generate its own lockfiles and will not be in compliance with hyper package manager.

According to the code [`npm` is the package manager](https://github.com/zeit/hyper/blob/master/app/plugins.js#L245), so any attempt to fix this issue should be done using https://github.com/zeit/hyper/issues/191#issuecomment-309854692, until #1896 is included in a next release.

**Comment by karlhorky** [comment]
@wachunei your solution can be simplified a bit:
- you don't need to remove the `node_modules` directory
- maybe: the `--no-shrinkwrap` option didn't seem to do anything special for me (still doesn't fix the problem permanently)

**Comment by chabou** [comment]
Will be definitely resolved by #381

**Comment by colepeters** [comment]
Thanks for the heads-up @chabou, and apologies if this issue was a duplicate and added too much noise. :)

**Comment by chabou** [comment]
No problem @colepeters. Thank you so much for your feedback.
More releases, less duplicates. That's our fault.
