### ISSUE TITLE
Fresh install doesn't start (beachball)

### ISSUE THREAD

**Issue by Archetrix** [zeit/hyper#1977]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac OS X 10.12.5**: 
- **Can't access Hyper version info because it hangs on first start. Downloaded from hyper.is today.**: 
- **.hyper.js is there, but since i did not edit yet ... distribution version**: 
- **N/A -->
- **Is Vanilla**: 

## Issue

I've just heard of hyper and downloaded it from hyper.is about 40 minutes ago. Installed and started but now i see beachball and the app is not responding any more. Kept it running while searching for clues (hyper.is and other issues here).
I have not yet changed anything in configs as i just wanted to do a first run.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
