### ISSUE TITLE
Edit -> Preferences -> Error: 'module' is undefined

### ISSUE THREAD

**Issue by mcandre** [zeit/hyper#1978]
In Windows 10 Pro, hyper shows an error popup when selecting Edit -> Preferences. Is there a specific Windows build to trick Microsoft JScript into recognizing this keyword, or is Node.js required or something?

**Comment by gmazlami** [comment]
I can confirm, I have the same issue on Windows 10 Pro, Hyper Version 1.3.3

**Comment by chabou** [comment]
Thank you for your feedback.
duplicates #1810
