### ISSUE TITLE
Ctrl-C & Git Log

### ISSUE THREAD

**Issue by nomad3k** [zeit/hyper#1979]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: n/a
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
I've tried this on a Mac, and I'm unable to reproduce it.  It relates to git and the effects of using `Ctrl-C` to break out of commands.

1. `cd` into a Git repo.  You'll need one with at least a few commits in the history.
1. type `git log --graph --decorate --all` to see the commit history
1. You now have the `:` prompt and can page through the data.
1. Instead of typeing `q` to quit use `Ctrl-C`
1. You are now back at the prompt.  (On a Mac nothing happened)
1. Type `git status` - This should work fine.
1. Type `git status` - This time, when you start typing, the prompt will change to a `:` and the command has had the first letter removed when executing.  Some kind of `'it' is not a valid command` will popup.
1. You will then intermittently swap between the proper and `:` prompt.  You can break out of the cycle by repeatedly typing `qq` at the prompt and eventually be returned to normal operation.

Hope this helps, as I'm loving Hyper.

**Comment by patrickjm** [comment]
I also have this bug

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
