### ISSUE TITLE
ConEmu as the Shell & other small issues

### ISSUE THREAD

**Issue by jerome724** [zeit/hyper#1980]
Good day folks,

OS: Windows 10
Hyper: Latest (1.3.3)

I would like too use [ConEmu](https://conemu.github.io/) as the shell in Hyper, but i can't get it to work. Does anyone got it working? If yes, how? I tried multiple variants and different ``shellArgs`` without any luck.

Right now I'm using bash which is working pretty fine, but somehow my terminal isn't "colored", tried it with and without a theme. Do i have to enable the colors manually? I have value the the ``force_color_prompt`` set to ``yes`` in my ``.bashrc``.

Other issue is that i have to install all the plugins manually into the ``.hyper_plugins`` directory with ``NPM``, when i don't do that the plugins are not installed, tried it with [HPM-CLI](https://www.npmjs.com/package/hpm-cli) but that same here without any luck, plugins are not installed. When i remove a plugin from my list it gets removed from the ``.hyper_plugins/node_modules`` folder.

**Comment by chabou** [comment]
ConEmu is not a Shell. It is a terminal like Hyper. It doesn't make any sense.

Plugin installation issue is certainly because you have npm@5. It will be fixed in next release

**Comment by jerome724** [comment]
Thanks @chabou!
