### ISSUE TITLE
Use reactive config on Windows?

### ISSUE THREAD

**Issue by Infinitylsx** [zeit/hyper#1982]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I hope I'm not totally missing something and I'm going to sound like a total idiot with this!

So far I really love Hyper! Running Windows 7 - the default cmd is disgusting, I was so happy when I discovered hyper. But as seen on the official app website the user can type "vi .hyper.js" to get an 'in window' version of the system settings, allowing you to change them to your liking and get a _live_ response. Is this only possible on Unix systems? I tried and I received an error as vi is not a Windows command. After doing research I tried to install vim and do the same with that but it resulted in the same error.

Receiving a live feedback is very appealing to me, even though I have the capability to edit the file itself - it just adds a convenience factor. Is this simply not available on Windows systems, or am I missing something?

Thank you all in advance!

**Comment by mapitman** [comment]
To edit your config, just type `CTRL`-`,`

It should launch the config file in your default text editor.

**Comment by sanguine8082** [comment]
Correct, windows CMD does not have `vi` installed.  If you want to use this or other UNIX commands, you could install something like Git Bash or cygwin on your computer.
