### ISSUE TITLE
Unmap Ctrl-M from Minimizing

### ISSUE THREAD

**Issue by Chinggis6** [zeit/hyper#1984]
I have [`clink`](https://github.com/mridgers/clink) and [`PSReadline`](https://github.com/lzybkr/PSReadLine) installed on Command Prompt and PowerShell, respectively, to provide `readline` library, and I do use all its shortcuts including <kbd>Ctrl-M</kbd> as/for/rather than/instead of <kbd>Enter</kbd>.

I know there's <kbd>Ctrl-J</kbd> for the same end but I'm used to <kbd>Ctrl-M</kbd>.

How could I unmap <kbd>Ctrl-M</kbd> from minimizing Hyper and make it to do `accept-line` /  `Enter` if it will not fall back to `readline` shortcuts unmapped?

I'm on Windows 10 using Hyper 1.3.3.

**Comment by ppot** [comment]
close in #1876
