### ISSUE TITLE
Uncaught (in promise) Error: not supported - Windows 10 WSL

### ISSUE THREAD

**Issue by lloydstubber** [zeit/hyper#1985]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Version 1703 / OS Build 15063.413
- **Hyper.app version**:  1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/lloydstubber/18e7f729acca45826498419925c1e754
- **Relevant information from devtools**: Running it out of the WSL via `C:\\Windows\\System32\\bash.exe` and in the ~/.bashrc I've defaulted it to zsh. Also using [n](https://github.com/tj/n) (installed via the WSL) for Node versioning.
- **The issue is reproducible in vanilla Hyper.app**: Running hyperline and hyperblue plugins.

## Issue
- When opening the terminal, the dev tools fire off the same error every second. This does not effect using the terminal at all though?

Error
```
Uncaught (in promise) Error: not supported
    at process.nextTick (C:\Users\USERNAME\.hyper_plugins\node_modules\systeminformation\lib\network.js:169:21)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
- When trying to update plugins I get an error `Check ~/.hyper_plugins/npm-debug.log` but nothing is there.

**Comment by LucaT1** [comment]
Your plugin hyperline is not compatible with Windows. Try removing it

**Comment by lloydstubber** [comment]
That fixed it! Thanks @LucaT1
