### ISSUE TITLE
[No issue] Custom Hotkeys and Title of the Terminal / Tab

### ISSUE THREAD

**Issue by ghost** [zeit/hyper#1987]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64 Bit
- **Hyper.app version**: latest, 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/1e5a508ccd123ddbb3844e7f647e5306

## question

I switched from Cmder to Hyper, with Cmder i had a hotkey ``ctrl+\``` which focused the terminal when it was in the background. Now i would like to have the same hotkey for hyper, but can't figure out how i could do that. Could someone give me a hint where i have to look? The [docs](https://hyper.is/) didn't helped me.

Second question: how can change the title of the Hyper itself? At the moment it is always ``Hyper``, i would like to change it to something like ``<username> - <current directory>``, same for the tab name.

**Comment by JonDum** [comment]
```
Second question: how can change the title of the Hyper itself? At the moment it is always Hyper, i would like to change it to something like <username> - <current directory>, same for the tab name.
```
Same thing on OS X. It'd be great if shell's title carried over to the minimized window's title.

<img width="399" alt="screen shot 2017-07-24 at 11 02 49 am" src="https://user-images.githubusercontent.com/191920/28537514-02749724-7060-11e7-981b-9b424d6fc0a9.png">
