### ISSUE TITLE
Using vim on windows causes lots of key conflicts

### ISSUE THREAD

**Issue by garetmckinley** [zeit/hyper#1989]
There are a ton of conflicts with hotkeys when using vim in hyper that render it unusable on windows currently :( the apps I've used with vim-mode in the past usually have a setting to disable internal key conflicts with vim.

Is there a way to rebind hyper keys? If not, a setting for this might be best.

Examples:

Ctrl+w (move between viewports) - closes the window
Ctrl+r (redo) - reloads the window

**Comment by ppot** [comment]
Can you test the lastest master?

**Comment by ppot** [comment]
#1876 fix this

**Comment by garetmckinley** [comment]
I'll give it a shot after work today, thanks for the work you put into this!

It looks like that PR is for remapping keys, is it also possible to unbind keys by setting the bind as an empty string? Asking because certain commands (like reload window) are useless to me. Plus I'm in the same boat as @TalAmuyal where I use tmux/vim for everyday coding, so I'd rather unbind the conflicts instead of binding them to another key that will conflict with something else.

**Comment by ppot** [comment]
@garetmckinley You can set your own bind keys

**Comment by ppot** [comment]
@garetmckinley Bump?

**Comment by garetmckinley** [comment]
I'm pretty confused with the keymappings. I have hyper 1.3.3 installed, and adding this to my `.hyper.js` configuration option doesn't unbind the ctrl+r hotkey

```json
keymaps: {
  "window:reload": ""
}
```

Am I missing something? If I try to bind it to something else (like `ctrl+e`), it stays bound to ctrl+r.

**Comment by thisguychris** [comment]
I'm gonna add `Ctrl-N` here for vim's auto completion.

**Comment by ppot** [comment]
@garetmckinley @thisguychris  Here is the catch. The PR I mentioned is in master. And therefore is not in 1.3.3 release but will be in next. You can use latest master and tell me if the issue persist.

**Comment by garetmckinley** [comment]
Ah okay, but I will be able to unbind keys using the method I tried? I'll test out the master branch shortly

**Comment by ppot** [comment]
yes you will be able to set other keys. Not unbind them in the sens of removing them

**Comment by garetmckinley** [comment]
So if I pass a blank string `""` to the keybind, it won't bind it to nothing?

My main concern is that literally every key is prebound to something else in both vim, emacs, and tmux. So if anyone wants to use hyper as their primary terminal for programming in vim/emacs, they're going to have a hard time. The only workaround I see is binding these functions to long combinations that will never get used. But that seems counter productive.

Sorry if I'm being difficult about this lol, I'm just trying to figure out if it's possible to use hyper for my daily dev work. I use a combination of neovim and tmux, and literally every key is bound to something.

**Comment by ppot** [comment]
@garetmckinley The goal of keymaps is to allow modification of the keys and also allow you to extend it. More on this is to change defaults to remove conflict with vim, emac, nvim powered keybinding and to allow you to change the default of the file.

**Comment by garetmckinley** [comment]
I feel like maybe you're misunderstanding what I'm saying. Programs like vim already have functions bound to every single key on the keyboard (including `ctrl` combinations). So the only solution would be to choose a less important vim command to override with the hyper bind.

Either way though, you're still going to be overriding a function. That's why programs like tmux require you to press `ctrl+b` before issuing a tmux command --because they know that using vim within tmux would be impossible otherwise since there's no free keybindings.

Is there a specific reason you're against allowing unbinding a key by passing an empty string?

**Comment by garetmckinley** [comment]
Ah gotcha, so it's more of a limitation with the keybinding logic? Again, I'm just trying to wrap my head around the issue. Sorry if it came off like I'm complaining, hyper is a great app that I really would like to use daily.

**Comment by ppot** [comment]
The goal of the keymap is to be flexible and enable the developer the possibility to set their own binding to the commands-keys

**Comment by thisguychris** [comment]
@ppot I'll check it when I get home, when I enabled Onedrive hyper app won't open anymore.

also is there a canary release of hyper? I saw this on my twitter feed:
https://twitter.com/rauchg/status/895008387049467904

**Comment by ppot** [comment]
Yes eventually. working to

**Comment by Stanzilla** [comment]
So we have a keymaps system where everything is customizable, does this help you? See https://hyper.is/#keymaps
