### ISSUE TITLE
Default selection colours are difficult to see. Seem to be black on dark-grey.

### ISSUE THREAD

**Issue by sebinsua** [zeit/hyper#199]
Default selection colours are difficult to see. Seem to be black on dark-grey.

_e.g._

<img width="432" alt="screen shot 2016-07-17 at 12 46 59" src="https://cloud.githubusercontent.com/assets/152098/16900391/c0042a76-4c1b-11e6-9b02-c7251c4d8e2a.png">

I am using `zsh` with `oh-my-zsh` with these plugins:

``` sh
plugins=(zsh-syntax-highlighting zsh-autosuggestions bgnotify colored-man-pages last-working-dir rand-quote osx brew autojump git github npm atom)
```

(Note, you can also see the bug mentioned in issue 24/183 in the screenshot.)

**Comment by WoodyWoodsta** [comment]
Possibly related: https://github.com/zeit/hyperterm/issues/177

**Comment by mauro-oto** [comment]
Should be closeable after merge of #272

**Comment by henrikdahl** [comment]
Selection now takes its color from cursorColor and is more visible https://github.com/zeit/hyper/commit/600f815dffe6fd835dfef5e3fde568a09bd286db ✌️
