### ISSUE TITLE
Can't toggle focus between terminals as windows.

### ISSUE THREAD

**Issue by mdfederici** [zeit/hyper#1990]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OSX 10.11.6**: 
- **1.3.3**: 
- **vanilla**: 
- **vanilla** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

Are there shortcut keys for previous/next window that i'm somehow missing? i can't find them. So i'm not using tabs or split panes or anything. I open a hyper terminal and then hit cmd + n to create a new one and i want to cycle between the two. Under the window menu, there is an option for 'select previous/next pane' but that doesn't seem to do anything. It's at least not toggling cursor focus between my two windows.

**Comment by delliot** [comment]
You're on macos? You can cycle between windows of the same application by pressing cmd-`
cmd-tab goes between applications, cmd-` goes between windows.

You'll find this helpful in a number of applications.

I am also confirming this works in macos 10.12.5

**Comment by mdfederici** [comment]
@delliot protip! i'm sort of new to the mac world thanks. Do you know the difference then between 'select next tab' and 'select next pane'?
