### ISSUE TITLE
Clear screen and history

### ISSUE THREAD

**Issue by dpo** [zeit/hyper#1991]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.5
- **Hyper.app version**: 1.3.3.1754
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/7c17c932cf7fe93724f09340fec4687a
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A?
- **The issue is reproducible in vanilla Hyper.app**: Haven't tried because of an issue where Hyper doesn't download plugins.

## Issue

This is related to #23. The OSX Terminal supports `printf '\33c\e[3J'`, which clears the screen together with history, but Hyper doesn't seem to honor this command. I'm not sure how standard it is, but if it is standard, I think it would be good to support it.

I see that `Cmd-k` is implemented but doesn't clear history. #23 mentions the possibility of `Shift-Cmd-k`, but that doesn't work for me. Has it been implemented under another key combination?

Thanks!

**Comment by saadq** [comment]
It actually did before, but a recent update broke the standard clear behavior. The issue is open [here](https://github.com/zeit/hyper/issues/1808). For now, I think <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd> works in order to clear the terminal along with the history.

**Comment by dpo** [comment]
Thanks. `Ctrl+Shift+K` does clear terminal and history but there's a strange delay after pressing the key combination and the terminal prompt doesn't come back until after I press `Return` another time.

`printf '\33c\e[3J'` is very useful as it can be included in scripts.
