### ISSUE TITLE
Unable to run with JS debugger

### ISSUE THREAD

**Issue by chhschou** [zeit/hyper#1993]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: master version/1.3.1 installed
## Issue
Hi there, I would like to get involved in developing a plugin for hyper, but I'm struggling to have hyper running in debugger, or attach a debugger to the hyper process (it doesn't seem to stop at a `debugger;`). Any helpful hints? I would like to debug in vscode if possible.

**Comment by Anzumana** [comment]
i myself have not done much with vscode but you should be able to open the developer devtools using the shortcut alt+ cmd + i.
For me this opens the chrome dev tools.

Let me know if this helps.
Feel free to ask in slack and see if any of the other developers as a neat setup to connect to vscode.
Otherwise i recommend to follow the readme to start the electron app and watch for file changes.
Don't  just run the app.

**Comment by ppot** [comment]
@chhschou In order to debug Hyper while building your plugin, you need to run it from master. Not from the `bundled` application.

**Comment by chhschou** [comment]
Thanks for the help I finally got around to trying it out again. Love the new xterm in 1.4.2.
I manage to get debugging working in vscode with this in my launch.json:
```
{
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "program": "${workspaceRoot}/app/index.js",
      "protocol": "inspector"
}
```

**Comment by albinekb** [comment]
Is there any interest in describing how to do this in the readme?

**Comment by chhschou** [comment]
Yes! I certainly think it would for noobs like me to get involved. Perhaps something like this before the **Known issue that can happen...** section. Happy to submit a PR with below as starting point. 

#### Debugging in Visual Studio Code
Create launch.json as per [official instruction](https://code.visualstudio.com/docs/editor/debugging). Add below to launch.json and select the "Electron Main" configuration to debug.
```
{
      "type": "node",
      "request": "launch",
      "name": "Electron Main",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "program": "${workspaceRoot}/app/index.js",
      "protocol": "inspector"
}
```

**Comment by chabou** [comment]
Yes @chhschou!
We can maybe add a `.vscode/launch.json` in repository?
I know that some devs do not use VSCode but it is not a problem and could facilitate dev on-boarding.

@albinekb What do you think about it?
