### ISSUE TITLE
New Ubuntu on Windows doesn't run properly like the legacy 'bash' tools

### ISSUE THREAD

**Issue by ow** [zeit/hyper#1994]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
Windows 10 Insider Preview 16232

- **Hyper.app version**: 
1.3.3

- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
https://gist.github.com/ow/0d5dc5a432210560e5200e818f8ade5d

- **The issue is reproducible in vanilla Hyper.app**: 
[x]
## Issue

Microsoftt is changing how bash on Windows works to use new, encapsulated appx containers so you don't need to run an entire VM to access them. Instead of launching bash from C:\Windows\system32\bash, now it's a universal command for the distro you're using, i.e `ubuntu` and you're thrown into your machine. This is because you're now able to run different distros alongside each other — and it means `bash.exe` is to be discontinued.

This doesn't work in Hyper, because you need the absolute URL. Before, I launched it using the method that's documented, but now it seems there's no reliable way to launch Bash on Windows. I did some hunting, and the Ubuntu executable lives in your appdata now, so for me, it's at `C:\Users\hi\AppData\Local\Microsoft\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\Ubuntu.exe` but even using that with escaped `\` doesn't work, with Hyper launching and immediately closing.

Has anyone else run into this? I realize it's on a preview version of Windows, but this is a few weeks out from shipping to the world and replaces the legacy `bash` method.

BTW — I can get in for now by opening Hyper with cmd, then typing Ubuntu.

**Comment by ow** [comment]
Could be that if you try jump in via another tool, like Gitbash, that you get a `permission denied` error

**Comment by LucaT1** [comment]
Try with `cmd.exe /k bash`

**Comment by ow** [comment]
@LucaT1 the point is that the `bash` command is no longer relevant (and that also doesn't work, even for legacy)

**Comment by colbin8r** [comment]
@ow What if you use `cmd.exe /k ubuntu && bash` or something like that? Also, is there an MSDN article or something that discusses this change in the Insider build?

**Comment by bitcrazed** [comment]
A few things here: 

In order to support multiple distros, we needed to update the command-line tooling:
  * `bash.exe` now runs your "default" distro
  * `wslconfig.exe` can be used to list & set your default distro (See `wslconfig /?` for details)

We're looking into making some improvements to our tooling to better support the scenario above: Bear with me.

**Comment by ow** [comment]
Awesome, @bitcrazed — great clarification and un-sticks me here! Seems like a good workaround in the meantime is setting a default via `wslconfig` which means lots of people can just use what's already documented, but maybe somehow we can make it clearer somewhere!
