### ISSUE TITLE
Installation errors dialog text isn't copyable

### ISSUE THREAD

**Issue by bitcrazed** [zeit/hyper#1997]
- [X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 build ~16240
- **Hyper.app version**: 1.3.1 & 1.3.3

## Issue
Can't copy text from an error dialog presented during installation:
![image](https://user-images.githubusercontent.com/961950/28142823-925422e4-6717-11e7-8aba-7d90aa939489.png)

Text is read-only, non-selectable, non-copyable.

It'd be great if this dialog supported select & copy, and/or "submit this bug" error reporting.

**Comment by mofux** [comment]
Unfortunately, this is the last resort fallback dialog that comes from electron if there is an exception in the main process. There is nothing we can do to change this dialog, but to fix the bugs that cause it 😅
