### ISSUE TITLE
Bash on Windows - Set default startup directory

### ISSUE THREAD

**Issue by shawnlan** [zeit/hyper#1998]
Here is my settings:
```
shell: 'C:\\Windows\\System32\\bash.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],
```

The startup directory is the Windows' user's home directory, not the linux user's home directory (`cd ~`). How can I change it?

**Comment by harangue** [comment]
You can always add a `cd` to your `~/.bash_profile`!

**Comment by gluons** [comment]
Change `['--login']` to `['~', '--login']`.

**Comment by omartin2010** [comment]
this `['--login']` to `['~', '--login']` didn't work for me. Perhaps because I'm using zsh, so I had for now to do the cd business in .zshrc... not great but it works.
