### ISSUE TITLE
Pasting when clipboard is empty or anything that's not text

### ISSUE THREAD

**Issue by swordbeta** [zeit/hyper#200]
When pasting when the clipboard is empty or pasting anything that's not text (such as images), gives us the following error:

```
λ ~/ master 
bracketed-paste-magic:zle:41: not enough arguments for -U
```

Using arch and zsh 5.2, latest hyperterm version.

**Comment by albinekb** [comment]
Hello @swordbeta, i can't reproduce this on OS X `10.11.6` with the latest release, it's possible that this has been solved since you posted your issue.

Can you please check if you still get this error with the latest release `0.7.1`?

Thanks 👋😊

**Comment by swordbeta** [comment]
Updated hyperterm and it's still happening. It's only happening inside `zsh`, I'm running on version `5.2` which is the latest available.

**Comment by ppot** [comment]
@swordbeta Could you try using the default zsh configuration? Maybe its zsh-plugins related?
