### ISSUE TITLE
404 On hyper.is on `Download Hyper for Linux`

### ISSUE THREAD

**Issue by alex-bender** [zeit/hyper#2002]
I didn't find how to contact anyone from team so posting it here:
`Download` link for `Linux` on the index page gives 404 error:
https://github.com/zeit/hyper/releases/download/1.2.0/hyper-1.3.1-x86_64-linux.AppImage

**Comment by saschahenger** [comment]
downloading for other os isnt possible either

**Comment by 4goodapp** [comment]
for the meantime, you can get the AppImage file for other Linux distro from [the release page](https://github.com/zeit/hyper/releases).

**Comment by albinekb** [comment]
Fixed some time ago! 🎉
