### ISSUE TITLE
Please make possible install via npm

### ISSUE THREAD

**Issue by mariusa** [zeit/hyper#2003]
Most JS tools, including heroku toolbelt for example, can be installed cross-platform with
npm install -g hyper

and then it just works. Please enable install via npm too, to make it simple getting started.

Thanks!

**Comment by CodeTheory** [comment]
I'm sorry but I don't see how this would be possible. Hyper is a .app with a UI, Heroku Toolbelt is a CLI. I don't think there's ever been an app like Hyper installed via npm (correct me if I'm wrong).

**Comment by CodeTheory** [comment]
Sorry again, but I was completely wrong! I was informed that this was possible so I'm re-opening so we can consider it!

Took me a while to understand how it would be possible. Didn't make sense to me at first. Let's see what the community thinks 😄 

cc @matheuss @rauchg @leo @chabou

**Comment by jbergstroem** [comment]
I believe homebrew or similar is a better place for applications -- I don't see atom in npm.

**Comment by DuIslingr** [comment]
You could use Snap. https://snapcraft.io Can be used on most distros, not just Ubuntu

**Comment by afturner** [comment]
+1 for homebrew. npm should not be used for these kind of applications.

**Comment by LucaT1** [comment]
@afturner homebrew is already avaible trough the cask addon as you can see in the README.md

**Comment by afturner** [comment]
@LucaT1 I'm aware, just reiterating support

**Comment by CodeTheory** [comment]
I think we've gotten what would be the majority of opinions on this matter.

Thanks for the issue and the responses, everyone. We'll make a bigger effort to be on the popular package manager made for apps like Hyper, per platform. ❤️
