### ISSUE TITLE
cmd+, (OSX preferences shortcut) launches a Fluid app instead of opening  ~/.hyper.js

### ISSUE THREAD

**Issue by animalphase** [zeit/hyper#2006]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: mac os x 10.12.5
- **Hyper.app version**: 1.3.3 (1.3.3.1754)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/animalphase/4cd9a1ca75842d15582661b7591b05de
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

[Fluid](http://fluidapp.com/) is an app that allows you to create standalone apps that just load a website in their own app menu. I have one set up for noisli.com. 

For some reason, pressing the `cmd+,` shortcut, or selecting **Hyper > Preferences…* from the menu, launches this Noisli Fluid app instead of opening up the hyper config file at  ~/.hyper.js

This issue persists when plugins are commented out and Hyper is restarted. This also occurs on a fresh install.

**Comment by CodeTheory** [comment]
Hi. Can you take a look at #1955 and tell me if that issue is the same as yours?

**Comment by animalphase** [comment]
@CodeTheory hi! yes the fixed described in that issue fixed it! sorry for the duplicate entry. strange that in my case, it was opening a specific fluid app rather than the Fluid.app root program.

**Comment by CodeTheory** [comment]
No problem for the duplicate! Github's issue search can be a pain sometimes.

If you ever find out the cause of _why_ it's doing that, I'd love to know 😄

**Comment by animalphase** [comment]
@CodeTheory i will make sure to comment back here if i do find out!
