### ISSUE TITLE
[Windows 8, Git-Bash] Colored output not working

### ISSUE THREAD

**Issue by FrankySnow** [zeit/hyper#2009]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 8.1
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/FrankySnow/a01a66e37c5aa08d9e48097d4ea4387e
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`.

## Issue
Hi,
when I execute a command which normally shows a colored output (via PHP, like `composer` or `phpunit`), I get no colors. When I force colored output (with `composer --ansi`or `phpunit --colors=always`), the ANSI escape sequences are shown instead of interpreted. The UNIX commands (like `ls --color`) are working fine.
When I use Git-Bash directly, everything works fine too.

Any help is greatly appreciated.

**Comment by math2001** [comment]
Just having a guess, set the environment variable `term` to `cygwin` in your `.hyper.js`:

```js
env: {
    TERM: "cygwin"
},
```

**Comment by FrankySnow** [comment]
@math2001 Thank you for your attempt, but this doesn't work. Nothing has changed.

**Comment by math2001** [comment]
Is there any other command that doesn't work (for example `git`).

**Comment by FrankySnow** [comment]
I tried with `git` and `npm` : both commands are outputted with colors. 
I think that the issue has something to do with how PHP commands are 
piped to hyper...

**Comment by math2001** [comment]
> I think that the issue has something to do with how PHP commands are
piped to hyper...

You should propably put that in your first message (edit it), it'll be easier for other people to help you out.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by pwsandoval** [comment]
@FrankySnow Could you solve it?, With version 2 the colors are still not shown.
