### ISSUE TITLE
Cannot type special characters

### ISSUE THREAD

**Issue by ksprwhite** [zeit/hyper#2010]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux/ubuntu gnome 16.10
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ksprwhite/048b3d190401f7d0734e20a71aa4d6c9
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: ![http://i.imgur.com/8ywafn3.png](http://i.imgur.com/8ywafn3.png)

`No definition for keyCode: 229`

## Issue

I can't type/paste special characters, the lang is "es_EC.UTF-8", when paste text with special characters, these characters are omited.

expected result (gnome terminal):

![http://i.imgur.com/1JDhCSw.gif](http://i.imgur.com/1JDhCSw.gif)

hyper result:

![http://i.imgur.com/NOXI5xW.gif](http://i.imgur.com/NOXI5xW.gif)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
