### ISSUE TITLE
Chinese Characters overlap problem

### ISSUE THREAD

**Issue by tenCats** [zeit/hyper#2012]
-

Hyper 1.3.3
Electron 1.4.16
darwin x64 15.6.0

When I output some Chinese chars in shell, it goes like:
![image](https://user-images.githubusercontent.com/6828552/28300585-0f2f2d32-6bb3-11e7-8942-b6ab281aa9ce.png)

Not sure if other languages have the same problem.

**Comment by TopGrd** [comment]
same issue here

**Comment by JameJJ** [comment]
![image](https://user-images.githubusercontent.com/12341577/28397210-c8f55630-6d32-11e7-9fbb-3f226cfc259e.png)
you can setting termCSS in .hyper.js

**Comment by 18601673727** [comment]
@JameJJ Not perfect, but better.

**Comment by JameJJ** [comment]
@18601673727 哈哈

**Comment by liverloop** [comment]
@JameJJ thanks

**Comment by JameJJ** [comment]
@liverloop 客气啦

**Comment by Songkeys** [comment]
change `wc-node` into `unicode-node` could be better :D

**Comment by NHibiki** [comment]
@JameJJ Good Though! However, Considering it might cause cursor to display in a wrong position if there is unicode in input row (for example some themes used in zsh), I am thinking if it is possible to fix the issue in script rather than customized css.

**Comment by lampui** [comment]
@JameJJ It helps, thanks

**Comment by hojas** [comment]
and can't input Chinese

**Comment by Pythonfo** [comment]
in windows, add .unicode-node{width: unset !important} to termCSS

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
