### ISSUE TITLE
Vim Spacing Issue

### ISSUE THREAD

**Issue by yousefissa** [zeit/hyper#2018]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac OS Sierra 10.12.5**: 
- **1.33*: 
- **Link of a [Gist](https://gist.github.com/yousefissa/57fb7c476129b0f180d9512c440dd3df) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app - Yes!**: 

## Issue

Hello, 

As you can see, there is a cursor mismatch when typing. It's extremely annoying. The first two variable declarations are fine because I closed and opened out of the file, but when using Vim there seems to be a spacing problem. Visually it's annoying and confusing, but the file is saved perfectly fine and the text is correct. Any ideas?

![image](https://user-images.githubusercontent.com/5174173/28434171-083ddf76-6d54-11e7-86e7-cd838af86d94.png)

**Comment by ryanhann** [comment]
I have a similar issue. Hyper won't allow me to type spaces in Vim.

**Comment by albinekb** [comment]
@yousefissa I guess this is fixed? 👍

**Comment by mtslzr** [comment]
Running 1.4.8 on macOS High Sierra, and experiencing this same issue.
