### ISSUE TITLE
Changing colors when the title changes.

### ISSUE THREAD

**Issue by rahulpilani** [zeit/hyper#2022]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  OS X 10.12
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/rahulpilani/dc9d489fec7cd1376e5ec9e334569963
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
I have attached the gist I have so far. I want to change the terminal colors every time the title has a particular sequence of characters, in this case "aws.prod". I can't find an easy way to attach a class to the Terms, TermGroup or Term component, and not even sure it's the right way. Some guidance would be helpful. I have limited knowledge of React and ES6, so I might be missing something silly.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
