### ISSUE TITLE
App interface has dissappeared but app still RUNS in the background.

### ISSUE THREAD

**Issue by dmalto** [zeit/hyper#2023]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 8.1 Windows 64 bit
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

After installing a couple of plugins, app interface has dissappeared but app runs in background. Uninstalling and reinstalling does not seem to work.

**Comment by ppot** [comment]
What do you mean by app interface?

**Comment by dmalto** [comment]
The terminal does not load but the application still appears in the processes list... after a long time some sort of error appears. I think installation of one of the plugins did it... will try to do more troubleshooting

**Comment by ppot** [comment]
Alright, keep me posted.

**Comment by BartNetJS** [comment]
I have the sam issue on Win 10
Hyper starts, the icon appears on the taskbar and in the task manager, but I can't bring the app in front
Did uninstall, removed .hyper.js and the plugin folder
Tried also with the canarie version, same issue

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
