### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by lordvault** [zeit/hyper#2025]
- When im running background process the console for long time, the console stop the work. 
At this moment i had 3 tabs:
1 Tab (splited in 4):
 - Tomcat (with tail on log, using run) (i think i have always this open when hyper fail)
 - Java Mission Control
 - Folder A (a console with a path)
 - Folder B (a console in a path directory)
2 Tab :
 - "less" comand with a log file
3 Tab: 
 - Console in a path. 
------------------------------------------- I lock the computer and after login again after like 30 minutes, the console was on black totally without any tab or text on it. 

Hyper 1.3.3
Electron 1.4.16
linux x64 4.4.0-83-generic

**Comment by ppot** [comment]
Can you please add more informations in order to know the specifics details of the problems! Thanks!

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
