### ISSUE TITLE
Text being rendered same color as background

### ISSUE THREAD

**Issue by libertylocked** [zeit/hyper#2029]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 (win32 x64 10.0.15063)
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/LibertyLocked/7a8c6dcf688e6749d30485750806d743
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: See below
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
When launching Hyper terminal, or after resizing, all existing text on the term somehow gets wrapped in `<span>` with color being the same as background color.

- Run Hyper
- The copyright info is not visible because it has the same color as the background.

![bug0](https://user-images.githubusercontent.com/1425794/28651395-abf3da8a-724f-11e7-999a-3a1d7dffbf0d.png)

- The text somehow got wrapped in `<span>` with color `rgb(0, 0, 0)` (same as background)

![bug1](https://user-images.githubusercontent.com/1425794/28651445-f0dfe13e-724f-11e7-915f-232476cbb731.PNG)

- The text afterwards shows up correctly

![bug3](https://user-images.githubusercontent.com/1425794/28651476-17299ace-7250-11e7-8d2d-87cbd8fac1fa.png)

![bug4](https://user-images.githubusercontent.com/1425794/28651478-1d90af4c-7250-11e7-95b8-f7a3dc90fae6.png)

- It also occurs when the window is resized.

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by nonconvergent** [comment]
I have the same issue, though different colors on Hyper 1.3.3.1754 on OS X Sierra.
![screen shot 2017-08-08 at 10 19 51 am](https://user-images.githubusercontent.com/673983/29076404-7247bf8a-7c23-11e7-853b-ce2b799c4508.png)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
