### ISSUE TITLE
RPM Dependencies missing

### ISSUE THREAD

**Issue by grturner** [zeit/hyper#2030]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora Rawhide
- **Hyper.app version**: <1.1.3>
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Not Applicable
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Not Applicable
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
The hyper rpm file has a missing dependency. Hyper looks for NPM on startup however it is not listed as a requirement under your RPM spec. Adding that dependency to the specfile should flag package managers to install npm along with hyper.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
