### ISSUE TITLE
Unable to use with "Windows Store" Unbuntu

### ISSUE THREAD

**Issue by cfjedimaster** [zeit/hyper#2031]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cfjedimaster/7494afcd1b04a98a103cfa7c191fb933
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: None as it crashes immediately.
- **The issue is reproducible in vanilla Hyper.app**: Um, ok, honestly didn't test. I think it will make sense in a bit. ;)

## Issue
I was using WSL (WIndows Subsystem for Linux) and today upgraded to the "Windows Store" release of Ubuntu. Doing so adds a new .exe to your system, ubuntu.exe. I have confirmed that Visual Studio Code can correctly use this as the integrated shell. When used in Hyper, it loads and then immediately crashes.

**Comment by cfjedimaster** [comment]
Ok, thanks to Scott Hanselman of Microsoft, here is the fix.

For shell, use cmd.exe
For args, use: /c ubuntu

And then it works.

**Comment by hikurangi** [comment]
This used to work - it's now broken with build 16281.rs3. I'm using Hyper.js 1.4.3 and those shell and args strings.

**Comment by albinekb** [comment]
@hikurangi can't you just type "zsh" to get to zsh when you're in bash? 🤔  and then if that works just add it to the args like `bash -c "zsh"`?

**Comment by hikurangi** [comment]
@albinekb thanks for the workaround. 

1) Typing "zsh" does launch zsh successfully when I'm in bash. 
However...
2) following that, I've tried using the shellArgs you mentioned, and Hyper quits immediately on launch as it did in my original reply.

So I can get it to work in a somewhat painful way (#1), but I think the important takeaway here is that (for me) Hyper 1.4.3 doesn't want to open the Windows Store Ubuntu using the shellArgs supplied by @cfjedimaster on 16281.rs3.

**Comment by hikurangi** [comment]
fwiw `cmd.exe` and `/c ubuntu` work on 16288.1

**Comment by brennanfee** [comment]
I'm on the Fall Creator's Update and was able to get it working.  I have it working using either 'bash.exe' (which works by making sure you have a default "linux" set with wslconfig) or 'ubuntu.exe'.  The trick was setting the shell args to [], not [''].
