### ISSUE TITLE
Printing ASCII characters causes hyper to display weirdly

### ISSUE THREAD

**Issue by OmgImAlexis** [zeit/hyper#2033]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.3 (16D32)
- **Hyper.app version**: Version 1.3.3 (1.3.3.1754)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/OmgImAlexis/7c0e711e14a11f5b6c66a023381a1456
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:
![screen shot 2017-07-28 at 1 47 51 pm](https://user-images.githubusercontent.com/6525926/28702406-eb2b5d2a-739b-11e7-9369-4f06046c3022.png)

- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

![screen shot 2017-07-28 at 1 49 40 pm](https://user-images.githubusercontent.com/6525926/28702393-ccb6d34c-739b-11e7-9f6b-ce61a81c8f09.png)
![screen shot 2017-07-28 at 1 49 35 pm](https://user-images.githubusercontent.com/6525926/28702394-ccbd154a-739b-11e7-8fce-1f994906cc94.png)

To reproduce you will need nodejs and npm.
`npm install request && node index.js`

```js
const request = require('request');

request({
    method: 'GET',
    url: 'https://getframe.herokuapp.com/api/accounts',
    headers: {
        authorization: 'Basic NTk3YWI4MmYyMTY0NGIwMDA0OTg0M2QzOjYwZjVhYWY0LTUwZTEtNDhmZi04OTEzLTJmYWQ2M2EwNzgyMQ==',
        dnt: '1',
        connection: 'keep-alive',
        'cache-control': 'no-cache',
        accept: 'application/json',
        'content-type': 'application/json',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
        'accept-language': 'en-AU,en;q=0.8,en-GB;q=0.6',
        'accept-encoding': 'gzip, deflate, br',
        pragma: 'no-cache'
    },
    json: true
}, (error, response, body) => {
    if (error) {
        throw new Error(error);
    }
    console.log(body);
});
```

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
