### ISSUE TITLE
Question: How do I access config from `exports.middleware` handler?

### ISSUE THREAD

**Issue by yonilerner** [zeit/hyper#2034]
- [ X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Hyper.app version**: 1.3.3

I have some config setup in `exports.decorateConfig`, and ofc I want the user to be able to also customize it themselves. How do I actually access the "final" config from a middleware handler?

**Comment by ppot** [comment]
you can access the config  by `app.config`
see https://github.com/zeit/hyper/blob/master/app/index.js#L60

**Comment by yonilerner** [comment]
@ppot Thats what I thought at first, but when I try to use that, it only contains the config from `~/.hyper.js`, and not any of the decorated config from `exports.decorateConfig`

**Comment by ppot** [comment]
Can you print your code or link? And also what you'r trying to do?

**Comment by yonilerner** [comment]
@ppot  My code is here: https://github.com/yonilerner/hyper-triggers/blob/master/index.js#L33 `e.remote.app.config.hyperTriggersMatchers` is undefined.
The only way I know how to access `app.config` is from `electron.remote.app.config`. Maybe theres a better way I dont know of?

What Im trying to do is something similar to what iTerm2 has with triggers, where when text matching a list of regexes appears in the console to create a desktop notification. I have a couple defaults, but ofc ideally it would be configured in `~/.hyper.js`. You can see Ive done a hack to make it work so far.

Thanks!

**Comment by yonilerner** [comment]
@Stanzilla Closed... why? To be honest, I've moved off of this already, but I'm wondering if theres a solution to this.
