### ISSUE TITLE
Please add support for non-English languages (Russian needed now)

### ISSUE THREAD

**Issue by RussianSwiss** [zeit/hyper#2036]
Please add support for non-English languages (Russian needed now)

**Comment by seriouslyfluffy** [comment]
Ты имеешь ввиду локализацию или поддержку русского языка в командах?

**Comment by dotWaldemar** [comment]
![2018-03-15 13 50 20](https://user-images.githubusercontent.com/25832802/37461673-d381c49a-2857-11e8-946c-9063365c46a4.png)

**Comment by dotWaldemar** [comment]
This`s fix with

```bash
export LANG=ru_RU.UTF-8
export LC_CTYPE=ru_RU.UTF-8
```

in to your .bash_profile or .zshrc

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
