### ISSUE TITLE
Support ssh:// url scheme handling

### ISSUE THREAD

**Issue by threesquared** [zeit/hyper#2039]
Are there any plans to support opening `ssh://` links.? 

I have tired setting Hyper as the handler with [duti](https://github.com/moretension/duti) which opens the app but does not ssh to the address. It would be nice if Hyper could set itself as the default handler like iTerm does.

**Comment by ppot** [comment]
never used this. What it does when you click on the `ssh://`

**Comment by threesquared** [comment]
It opens the terminal and begins a ssh session with the address you supplied.
![screen recording 2017-08-03 at 12 51 pm](https://user-images.githubusercontent.com/892142/28920696-cebc57bc-784a-11e7-86f3-8db41c0bcbee.gif)

**Comment by niklasfink** [comment]
Hey, what's the status on this?
I request a priority increase to *medium* please 🙂

**Comment by paavolastudio** [comment]
Would love to see this as well, as this is the only thing making hyper unusable for me day-to-day.

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/pull/2516
