### ISSUE TITLE
Tab not autocompleting 

### ISSUE THREAD

**Issue by joe-scotto** [zeit/hyper#2041]
OS: MacOS Sierra (10.12.12 Beta 16C48b)
Hyper Version: Version 1.3.3 (1.3.3.1754)
Gist: https://gist.github.com/joe-scotto/7a5c81f5d9eb6ca7313e43597b7dbf50

Pressing tab is not autocompleting. I'm using oh-my-zsh.

**Comment by miguelmich** [comment]
I'm experiencing the same issue with the last release v1.4.2

**Comment by miguelmich** [comment]
Nevermind, restarting the app solved the issue :)
