### ISSUE TITLE
Tooltip issue when using visor

### ISSUE THREAD

**Issue by revelt** [zeit/hyper#2042]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.6
- **Hyper.app version**: 1.3.3.1754

## Issue
Hi all,
When the cursor is `hover`'ed over the tab for long enough, a tooltip pops up with the same text as the tab's label:

![tooltip](https://user-images.githubusercontent.com/8344688/28923043-7585293a-7854-11e7-9f2d-fb5244249ff4.png)

This is annoying as sometimes it appears accidentally and also, sometimes there's no way to get rid of that tooltip (except by `hover`ing again over tab long-enough to cause a new tooltip which removes old, stuck-one).

I'm using `hyperterm-summon` so it might cause those weird scenarios where tooltip was on and mouse was on the tab, but `hyperterm-summon` hid the window and cursor was moved and now the window is back on, this time with stuck tooltip:

![hover_issue](https://user-images.githubusercontent.com/8344688/29120672-4e6089c2-7d03-11e7-8e12-26b7cccb0927.gif)

In theory, what if we **removed the tooltip from tabs completely**? Or is that part of Electron and therefore will inevitably be there forever?

**Comment by CodeTheory** [comment]
Wouldn't you agree that it's useful for truncated tab titles? 
![image](https://user-images.githubusercontent.com/1695613/28923617-8c7baf40-7856-11e7-9f36-52f0f1f3a8fd.png)

**Comment by revelt** [comment]
That's a good point. Having said that, is it possible to enable tooltip only upon truncation? As a part of truncation functionality? Because otherwise it's redundant, isn't it?

**Comment by jbergstroem** [comment]
Thinking that consistency is more important than being "smart" here.

**Comment by revelt** [comment]
I uploaded the quick screenshot of the stuck tooltip. Here it is again:

![hover_issue](https://user-images.githubusercontent.com/8344688/29120695-6eac0364-7d03-11e7-9e5c-09e1326767a1.gif)
