### ISSUE TITLE
Code To Prevent mousedown Event From Being Stopped, Prevents Hterm From Seeing The Event

### ISSUE THREAD

**Issue by LtSquigs** [zeit/hyper#2045]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OSX Yosemite 10.10.5
- **Hyper.app version**: 1.3.3 1754
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/LtSquigs/16c015040dc9f5ed885c26d900b3e007)
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Hey debugged this issue when I was experiencing some odd behaviour with tmux and hyper.

There is a bug in this logic here:

https://github.com/zeit/hyper/blob/93b2229ff58313ecc058e81e3e665ef5f20706a6/lib/hterm.js#L278

From what I can tell this logic is supposed to prevent the `mousedown` event from being supressed, so that terminal applications that rely on it will see the event. 

But this logic never calls `oldOnMouse` after overriding `preventDefault`. This means that, while `preventDefault` will not stop the `mousedown` event, hterm will never actually see the `mousedown` event, preventing it from sending the appropriate mouse tracking escape codes.

This causes issues with mouse tracking in several applications, but most notably tmux. If you enable mouse mode in tmux and use hyper, you will notice that when you click into a tab it enables the scroll mode, but never disables it. This is because its only seeing one of the mouse events (`mouseup`), by fixing this line to call the old mouse event function this fixes this problem.

This issue is also caused by this logic problem: https://github.com/zeit/hyper/issues/2020

I would submit a PR, but I'm not familiar enough with your code base to know why this change was made in the first place, hopefully fixing this should not be too complicated :)

**Comment by joakim5937x** [comment]
@LtSquigs While this fixed the problem for me on linux for some reason it does not fix it on windows and I cant figure out why. 

Tested on Linux mint and tmux 
and bash on windows with tmux,
