### ISSUE TITLE
Unable to start terminal process

### ISSUE THREAD

**Issue by PandawanFr** [zeit/hyper#2046]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Version 1607
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [https://gist.github.com/PandawanFr/cb1021689e17435e4e5a648358230413](https://gist.github.com/PandawanFr/cb1021689e17435e4e5a648358230413)
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Untested

## Issue

Hello,
I am unable to use the context menu to open Hyper. When I do, "Open Hyper Here", the app crashes and tells me "Unable to start terminal process" as you can see [here](https://gyazo.com/5a37c8def4326186299d78a5c0859372). The window does end up opening, but it is blank and I am unable to type or do anything on it. 

Here is a screenshot of the full error
![Imgur](http://i.imgur.com/NljO66z.png)

Also, here's my registry key for the Context Menu
`HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\Background\shell\Hyper\command` is set to
`"C:\Users\panda\AppData\Local\hyper\Hyper.exe" --process-start-args="-p %V"`

Thanks!

Edit: Opening hyper normally (from start menu) works fine so I don't think it's a problem with my installation.

**Comment by PandawanFr** [comment]
It appears to be due to the -p argument in the registry.  After I removed it, it worked fine.

I had copied that from an issue on this repo, I don't know if the -p is supposed to do anything. But if so, then I guess it needs to be fixed. If not, then it's all good.

**Comment by MartinMuzatko** [comment]
![image](https://user-images.githubusercontent.com/2950505/31330094-3bf4e10c-acdd-11e7-9356-5a6bc3f2cc49.png)

This does not resolve the error for me.
I tried the above changes to the registry
