### ISSUE TITLE
Asking about design question of hyper.

### ISSUE THREAD

**Issue by zhaoyi0113** [zeit/hyper#2049]
I am working as a software engineer and currently am creating a nodejs project to use node-pry. I am facing some troubles on using node-pty. And I found you published a project https://github.com/zeit/hyper.git which is doing something interested me. I use hyper as a terminal and found it works really awesome. So I wonder whether you can give me some suggestions regarding below questions:

How do you emulate a terminal in nodejs? I read the source code and found you are using node-pry to listen on the `data` output stream in the session.js. But what I don’t understand is how you manage the input and output from pty. Since everything you typed into pty will come out from the `data` output stream. How do you filter out the input and only show output to the front end.

In your project, I see all the ui source code is under lib directory. What I am confused is about how you render the pty output to the terminal component. I debugged the code but I couldn’t find which component is react to the message from pty output. For example, when I type a bash command in hyper and hit enter, I can see the `SESSION_PTY_DATA` is triggered in the reducer. But no other containers get re-rendered for this action. It would be great if you can point out somewhere in the UI containers for reacting to the pty output event. 

How do you manage the ANSI character? I can see that some output is encoded as ANSI character. But I couldn’t find any where in your source code to translate this characters. 

Appreciate your help on that.

**Comment by LucaT1** [comment]
The data and ansi escape codes are handled by `hterm` wich listens on data from the pty and then writes it to the ui. If you're interested in builing such an application you should check out [xterm.js](github.com/sourcelair/xterm.js) for the rendering and handling of the input, wich btw Hyper is currently migrating to. Xterm is used also by Microsoft's VS Code and if you're more into react you can take a look at [my project](https://github.com/vterm/vterm) for some reference. The xterm documentation can be found [here](https://xtermjs.org/docs).

**Comment by zhaoyi0113** [comment]
Hi LucaT1, 

Thanks for your reply. I will look at the xterm project. And could you let me know how UI components render the pty output? I have debugged the source code but couldn't find any containers re-rendered based on `SESSION_PTY_DATA` action.

**Comment by LucaT1** [comment]
In hyper `hterm` renders the pty data(NOTE: hterm is dead), and that's why i'd suggest to use xterm.js. You should look at xterm.js to see how it renders the data

**Comment by zhaoyi0113** [comment]
Thanks for your help. I will have a look at xterm.
