### ISSUE TITLE
I want to run a plugin

### ISSUE THREAD

**Issue by SpaceNoodles01** [zeit/hyper#2052]
I just downloaded and installed a plugin into Hyper, what i should do now to make this plugin actually works?

**Comment by Stanzilla** [comment]
Wait for the next release or build from `master`

**Comment by saadq** [comment]
I think he might mean that he installed a community plugin for `hyper`. @SpaceNoodles01 If this is the case, it should hot reload for you (or you can just try to manually restart `hyper`.) If you're still having issues, could you mention which plugin you're talking about?

**Comment by Stanzilla** [comment]
Plugin installation is broken in the current release though

**Comment by saadq** [comment]
Oh, didn't realize. Thanks for the info.

**Comment by SpaceNoodles01** [comment]
Solved, the hyper.js file was incomplete :P
