### ISSUE TITLE
Feature Request: Move Tabs and switch tabs shortcut

### ISSUE THREAD

**Issue by stefnats** [zeit/hyper#2054]
Hi,

i'd love to see two features:

1. Move Tabs by dragging (like in Chrome / Firefox / iTerm)
2. Switch Tabs by either `⌘` + `←` or `→` (using `CTRL` on Windows)

**Comment by ppot** [comment]
1. Dragging is a current issue see #911
2. Shortcut are currently bind to the Hyper menu and will be customizable in the next release :)

For any other questions feel free to comments!
