### ISSUE TITLE
Switching between tabs

### ISSUE THREAD

**Issue by sagarduwal** [zeit/hyper#2064]
- open multiple tabs
- switch to another window and again switch to hyper
- switching tabs to other tabs with shortcut keys,  requires to manually clicking on the tab on the top and then using the keys
- then manually focus to workspace

I was hoping to be able to use shortcut keys from anywhere without manually focusing to tabs or workspace.

Hyper 1.3.3
Electron 1.4.16
linux x64 3.13.0-117-generic

**Comment by ppot** [comment]
From anywhere? Even from other app? I don't really understand your anywhere.

**Comment by johhansantana** [comment]
I'm using Hyper 1.4.2 and I can't switch tabs using the shortcuts anymore (ctrl+tab, ctrl+shift+tab)

**Comment by ppot** [comment]
@johhansantana For the moment you still need to focus an active window.

**Comment by johhansantana** [comment]
@ppot I think I am focusing the hyper window

steps:

1. Open hyper with 2 tabs
2. Ctrl+tab while focusing hyper (it will not work, instead, it will just regular tab where you type)

**Comment by JayyWalker** [comment]
@ppot I'm also having the same issue as @johhansantana. I could ctrl+tab to the next tab and shift+ctrl+tab to the previous. 

I am using Hyper 1.4.2 on OSX.

**Comment by ppot** [comment]
@johhansantana What i'm saying is: Try with only one Tab open `it should work`. Then on 2 tab it should only switch between tabs which is the bug.

**Comment by CrixuAMG** [comment]
Having the same issue.
I'd like to add that typing while the new tab has no focus (yet) causes any commands to be executed in the previous tab! This is a very big issue for me,  and would like to know if it can be fixed soon.

@ppot please let me know if anything is possible within the next few days, or if I should temporarily switch to a different cli while this issue is getting fixed?

**Comment by kingmomo** [comment]
For me this works on Hyper 1.4.8 (stable)

To switch between hyper tabs:
> on mac: cmd+shift+[ and cmd+shift+]
> on win: ctrl+shift+[ and ctrl+shift+]

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
