### ISSUE TITLE
i input clear command then show  and bad text

### ISSUE THREAD

**Issue by jiangxianfu** [zeit/hyper#2069]
my computer is windows 7 ,but i get the git/usr/bin for linux command 

when i input clear ,show text is very bad.
![1](https://user-images.githubusercontent.com/1614027/29150864-ef0bf29c-7daf-11e7-8c89-eb2ca7198edd.png)

![image](https://user-images.githubusercontent.com/1614027/29150895-198a68f0-7db0-11e7-91da-7c2ec9e197fd.png)

Hyper 1.3.3
Electron 1.4.16
win32 x64 6.1.7601

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
