### ISSUE TITLE
Text left over from last reneder

### ISSUE THREAD

**Issue by ItamarGronich** [zeit/hyper#2071]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.6
- **Hyper.app version**: 1.3.3.1754
- **My config**:  [.hyper.js](https://gist.github.com/ItamarGronich/ce3a2b8307504a2717f71354cd60f91b)

## Issue
Experiencing some render issues with hyper.

Sometimes, when I do some scrolling or any action that makes the terminal move it's rows, I get text overlapping. 
It's as if the text remains in it's original position and duplicates to the new position and overlaps.
Sometimes it automatically corrects after a second or two, but sometimes it remains stuck there until I reload the terminal.
Heres a screenshot of the overlapping text:
<img width="513" alt="screen shot 2017-08-09 at 18 12 21" src="https://user-images.githubusercontent.com/14963977/29155369-6e1a117e-7da4-11e7-8c34-e9ef035a0c70.png">
I love hyper term and it's extensibility but i can't use it like this.

**Comment by third774** [comment]
I experienced this same issue and experimented with turning off all plugins which seemed to have fixed it.

So I went through all of my plugins and isolated it to `hyperterm-cursor`.

I noticed you don't have that plugin installed, but if you can isolate which of your plugins is causing it perhaps we can help track down the root cause?

**Comment by rabbewalter** [comment]
I am experiencing a similar thing where moving out of editing (saving and exiting vi/nano) files and moving away from MySql will leave parts of the latest render below the current cursor line, which is also a bit misplaced.

OSX: 10.12.6
Hyper: 1.4.8 (stable)
Plugins: 'hyper-dracula'
No additional changes has been made to my conf file.

**Comment by lemongrassnginger** [comment]
I believe I'm experiencing a similar problem. When I enter vim, the text file overlaps the previous render from the console.

I'm using bash and terminal that comes with git for windows https://git-scm.com/downloads (something called Mintty?)
OS: Windows 10
Hyper 1.4.8 (stable)

In the screenshot below, Hyper is on the left and the git-bash terminal is on the right, both opening similar text files in vim. Hyper overlaps the text with what was previously rendered in the command prompt:

![image](https://user-images.githubusercontent.com/12435157/32119181-56ab3a00-bb4c-11e7-9d60-3089ff677605.png)


config:

```
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // Choose either "stable" for receiving highly polished,
    // or "canary" for less polished but more frequent updates
    updateChannel: 'stable',

    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for â–ˆ
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    //
    // Windows
    // - Make sure to use a full path if the binary name doesn't work
    // - Remove `--login` in shellArgs
    //
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
    //
    // Powershell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: 'C:\\Program Files\\Git\\git-cmd.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: [],

  keymaps: {
    // Example
    // 'window:devtools': 'cmd+alt+o',
  }
};
```

**Comment by glipecki** [comment]
@ItamarGronich try adding TERM variable as described in https://github.com/zeit/hyper/issues/1924
It worked for me ;-)

**Comment by stu-b-doo** [comment]
I think @glipecki 's suggestion has fixed a similar issue for me. I'm using bash that comes with git for windows. I set the TERM variable by adding the following line to my bashrc:

`export TERM=cygwin`

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
