### ISSUE TITLE
Finding text in the terminal

### ISSUE THREAD

**Issue by sagarduwal** [zeit/hyper#2072]
**Find** feature doesn't seem to be present currently.

-

Hyper 1.3.3
Electron 1.4.16
linux x64 3.13.0-117-generic

**Comment by saadq** [comment]
There's an issue already open for this: #140

For now, I think there's a package that adds some basic support for this. It's called [hyper-search](https://github.com/jaanauati/hyper-search).

**Comment by sagarduwal** [comment]
Thanks ! @saadq

**Comment by sagarduwal** [comment]
Though, doesn't seem like hyper-search works for linux system I am using. Ubuntu-14.04

**Comment by ppot** [comment]
duplicate of #541
