### ISSUE TITLE
How do I disable plugins updating notification?

### ISSUE THREAD

**Issue by guy-kdm** [zeit/hyper#2073]
-

Hyper 1.3.3
Electron 1.4.16
darwin x64 16.7.0

**Comment by Stanzilla** [comment]
You can't.

**Comment by guy-kdm** [comment]
Might be useful not to have them in the first place, don't see how it's a useful distraction

**Comment by afturner** [comment]
@guy-kdm I agree... I feel like it should be an optional opt-in feature. No real benefit is gained from the notification. Perhaps we could adopt a system similar to Atom, where updates are shown in the bottom right.

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2431
