### ISSUE TITLE
Hyper handles concatenated truecolor ANSI escapes incorrectly

### ISSUE THREAD

**Issue by daveio** [zeit/hyper#2074]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.6 (16G29)
- **Hyper.app version**: 1.3.3 (1.3.3.1754)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/daveio/e70b23f6189d73c0ea3e10a9b201fe8d
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Hyper does not support concatenated ANSI truecolor escape codes correctly.

Example: `\033[0;38;2;0;135;175;48;2;88;88;88;22m HELLO THERE `

Hyper fails to render this correctly, ignoring the `48` code to start the second sequence.

![image](https://user-images.githubusercontent.com/66192/29223623-22432436-7ebf-11e7-84bc-6aad9bbf9d54.png)

However, if the second sequence is (incorrectly) prefixed by a 0, Hyper renders as it should the original example.

Modified example: `\033[0;38;2;0;135;175;0;48;2;88;88;88;22m HELLO THERE `

![image](https://user-images.githubusercontent.com/66192/29223689-663e02fa-7ebf-11e7-965a-59e6db26822b.png)

The original example and the modified example, as accurately rendered by iTerm2 3.1.beta5:

![image](https://user-images.githubusercontent.com/66192/29223785-b378f7c8-7ebf-11e7-9000-d71746ce0338.png)

As you can see, the modified example causes iTerm2's rendering to be incorrect, but that's to be expected since it's invalid anyway.

**Comment by chabou** [comment]
Will be fixed by replacing `hterm` by `xterm` (hyper v2)

**Comment by daveio** [comment]
@chabou any idea of an ETA on that? Is there a v2 prerelease available at all?

**Comment by chabou** [comment]
there is a WIP `xterm` branch. (I checked your issue on this branch).
But no ETA 😞

**Comment by daveio** [comment]
@chabou Thanks for that - I'll build that branch for now. Appreciate your time 👍

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
