### ISSUE TITLE
Nano editor not exiting

### ISSUE THREAD

**Issue by jagroop** [zeit/hyper#2075]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS Ubuntu 15.10**: 
- **Hyper.app 1.3.3**: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Nano editor not exiting properly after saving the file

when I create a new file 
```bash
$ nano test.py
```

after making some changes I hit ```CTRL + O``` and press Enter (it saves the file), after saving the file when trying to __EXIT__ by pressing ```CTRL + X```, it doesn't work, I have to restart the terminal every time. please tell me how to fix it THANKS.

**Comment by retrixe** [comment]
`Ctrl + Shift + X` because `Ctrl + X` is mapped to Cut.

**Comment by jagroop** [comment]
thanks @retrixe
