### ISSUE TITLE
Error accessing preferences

### ISSUE THREAD

**Issue by mviens** [zeit/hyper#2077]
I opened the menu, clicked Edit, and then clicked Preferences.  I received this error:
-
![image](https://user-images.githubusercontent.com/8459232/29243872-f1e0724e-7f5e-11e7-9495-215f2b6e17fe.png)

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by ppot** [comment]
Did you add a plugin? What when there is no plugin installed. Please follow the issue instructions.

**Comment by bstoney** [comment]
This happens in windows when `.js` files are associated with the Windows Script Host. You may have to open the preferences file directly `notepad %USERPROFILE%\.hyper.js` or something similar. Or you can change your `.js` file association to a text editor.

**Comment by 01binary** [comment]
I re-associated .js file with my favorite IDE (VSCode) and the problem is fixed (thanks!)

http://www.thewindowsclub.com/change-file-associations-windows
