### ISSUE TITLE
TypeError Cannot read property 'theme' of undefined

### ISSUE THREAD

**Issue by jordan-miguel** [zeit/hyper#2080]
Whenever I try to open hyper, this error pops up, I am extremely lost. 
![screen shot 2017-08-13 at 21 10 02](https://user-images.githubusercontent.com/14114089/29253059-122c841c-806c-11e7-8c0c-8139f745d32f.png)

**Comment by jordan-miguel** [comment]
Managed to open hyper.js in terminal and remove the material theme plugin. Perhaps a bug with this particular theme?

**Comment by saadq** [comment]
Yeah, I'm pretty sure it's an issue with that theme, I think I had something similar happen to me when I used it. 

To be sure, try using a different theme and check if it works.

**Comment by ppot** [comment]
@jordan-miguel Would be appreciated to add your config. Also condidering in slack I helped debug the same behavior for `hyper-material-theme`.

If it's the case. You need to follow the instruction of the plugins by following the configurations part of https://github.com/equinusocio/hyper-material-theme.

**Comment by chabou** [comment]
You should open an issue in plugin repo
