### ISSUE TITLE
Long-running sudo commands made sudo unresponsive in all terminal emulators

### ISSUE THREAD

**Issue by VPM-DavidM** [zeit/hyper#2082]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOs Sierra 10.12.6
- **Hyper.app version**: 1.3.3
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
Using the stock Hyper app with no modifications whatsoever, executing a long-running `sudo` command (e.g. a `vagrant up` command that requires `sudo` for one of its build steps) eventually causes `sudo` commands to hang indefinitely system-wide. This includes running other commands that invoke `sudo` themselves and attempting to run `sudo` directly or indirectly in other terminal emulators. The issue does not present itself when carrying out the same steps using other terminal emulators.

A system restart solves the issue.

**Comment by chabou** [comment]
Thank you for your feedback @VPM-DavidM.
When command hang indefinitely, is there an error thrown in Hyper dev-tools?
Do you know if long-running command is really blocked or if it is only its outputs that is invisible?

I didn't achieve to reproduce it...

**Comment by VPM-DavidM** [comment]
@chabou Thanks for looking into it.

The long-running command that was started within Hyper is fine and continues to run without issue.

The problem is trying to run other commands. If I later try to use `sudo` in either Hyper, Terminal or iTerm (and presumably others -- those are just the ones that I have on my system), the new `sudo` command hangs; it does not complete nor does it output anything.

For additional context: this issue only seems to manifest itself after the initial long-running `sudo` command has been active for an hour or more, and only occurs when the long-running command is run within Hyper, not any of the other terminal emulators.

As soon as I switched back to using iTerm from Hyper, the problem disappeared.

Unfortunately I don't have any errors from Hyper dev-tools. If I have a couple of hours to spare I'll run it again and see if there are any.

**Comment by CodeTheory** [comment]
Like #1157 perhaps?
