### ISSUE TITLE
can't see proper hilight in vim's omni completion popup menu

### ISSUE THREAD

**Issue by thisguychris** [zeit/hyper#2084]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 (Build 162757.1)
- **Hyper.app version**:  1.3.3 (from appveyor artifact)
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

![image](https://user-images.githubusercontent.com/532797/29289212-208a5068-816e-11e7-9f4c-c3b0c91b08df.png)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by beatwade** [comment]
env windows10 using wsl bash
issue stills exist in working with nvim 
![image](https://user-images.githubusercontent.com/6858148/45543298-cbba3600-b846-11e8-87e0-cc60c47bcee0.png)
![image](https://user-images.githubusercontent.com/6858148/45543311-d83e8e80-b846-11e8-8795-2f49100c595e.png)
