### ISSUE TITLE
Feature Request: Logging command names when invoked

### ISSUE THREAD

**Issue by saadq** [zeit/hyper#2085]
Because #1876 has brought keymaps to `hyper`, it would be cool if there was an easy way to figure out the names of commands so that you could create a keybinding for it. One suggestion is to maybe have a `logCommands` option in your `.hyper.js` which is `false` by default. When `true`, every time you do a command, the name of that command will be logged to the console.

Do you all think this would be a good feature to have in `hyper`, or do you think it would just be better as a plugin?

**Comment by saadq** [comment]
Kind of related so I'll just ask here instead of opening a second issue, but would you all be interested in possibly adding a table to the website with the default commands and keybindings that Hyper provides? Something like:

![screen shot 2017-08-15 at 2 05 45 am](https://user-images.githubusercontent.com/5678694/29303938-4b4ea7a0-815e-11e7-9eb8-d17a55231abe.png)


I just did it quickly so a lot command descriptions would need to be fixed/improved (or removed entirely if you think they're redundant). 

The default keys are hardcoded in right now, but it would be pretty simple to just have a placeholder like `{{super}}+,` and then just do a text replace of `{{super}}` to `cmd` or `ctrl` based on which OS the user is on (which it looks like the site is already checking).

The windows and linux keybindings seem to be completely equivalent except for one, `window.minimize` which is <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>m</kbd> on linux and <kbd>ctrl</kbd>+<kbd>m</kbd>, so that would be the one keybinding that would need to be manually changed with JS.

Would you all be interested in this or do you think it's too much clutter? If it is something that you would be interested in adding, I would also suggest that the **Configuration** section be moved above the **Keymap** section though, as it should probably have precedence.

**Comment by chabou** [comment]
We need documentation, you're right.
Maybe a link to keymap files like https://github.com/zeit/hyper/blob/master/app/keymaps/darwin.json is enough? Easier to maintain, imo.

A `logCommands` option seems too specific. A `debug` option is maybe better to show some internals (commands included).
