### ISSUE TITLE
Cmd/Alt+arrow key cursor navigation stops working

### ISSUE THREAD

**Issue by anentropic** [zeit/hyper#2087]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- macOS Sierra 10.12.6 
- 1.3.3.1754 
- https://gist.github.com/anentropic/13c0ca542e03866e9dd6b93ca6d3702d 
- N/A 
- Is Vanilla 

## Issue

macOS style text navigation using the Cmd/Alt+arrow keyboard shortcuts only works intermittently.

I have not worked out what action causes it to start or stop working.

For a while I actually thought it maybe wasn't enabled in Hyper (I previously used iTerm2 and it had to be specifically configured to work) but then for a while it was working for me.

**Comment by ravangen** [comment]
If you were to use different keyboard shortcuts, does it continue to start/stop working intermittently?

You can customize the keyboard shortcuts using `keymaps` in `.hyper.js`. See [docs](https://hyper.is/#keymaps).

```javascript
module.exports = {
  config: { ... },
  keymaps: {
    'tab:prev': 'cmd+alt+left',
    'tab:next': 'cmd+alt+right'
  },
  ...
}
```

**Comment by Stanzilla** [comment]
So we have a keymaps system where everything is customizable, does this help you? See https://hyper.is/#keymaps
