### ISSUE TITLE
Long running commands hang Hyper

### ISSUE THREAD

**Issue by AlienHoboken** [zeit/hyper#2089]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX Sierra 10.12.1
- **Hyper.app version**: 1.3.3
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
When running a long-running command, hyper will hang. Hyper becomes unresponsive to Ctrl+C and other tabs are inaccessible as the application has hung. 

For example, try running `cat /dev/random`

The first several random bytes will display then Hyper hangs. Expected behavior would be to continue receiving the random bytes and be able to terminate when finished.

**Comment by CodeTheory** [comment]
Like #1157 perhaps?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
