### ISSUE TITLE
Track progress

### ISSUE THREAD

**Issue by ppot** [zeit/hyper#2090]
In order to follow continuous development of Hyper. This issue will track goals of current implementation on my side.

This being said, I will list priority of issues and functionality involved in the process. And i will list the current state of advancing of each work components.

On the current state, I will work on session restoration. In order to do so I need to rework the background architecture of Hyper as of the internals of the lib on the UI which are bound on Redux.

Since the start of Hyper we included many fix to solve different type of issues or requests for the community using the project https://zeit.co/blog/the-hyper-plan

Like many project evolving it need maintenance and in the current state, before the codebase becoming bigger and more complexe, it need restructuration and documentation. I will start to work on those as of the functionality evolve and this in small chunk. The small chunk will each be included with the required documentation and which components are affected.

Comments are welcome!

**Comment by mofux** [comment]
@ppot The `xterm.js` dev crew has a really nice way to track progress and issues. They create version milestones e.g. `1.3.4` for every release, and then they assign issues to these milestones. This way you have a backlog of activity between issues and versions, and you also have a roadmap for following releases. On top, you can always see what is still needed until the next version can be released, which also helps external contributors to work towards that version. I would propose to try the same for hyper

**Comment by Tyriar** [comment]
The xterm.js process is basically a lite version of [vscode's iteration plans](https://github.com/Microsoft/vscode/wiki/Development-Process#iterations); put issues/PRs on the milestone that are planned for it, and before releasing review and push things off if they didn't make it.

I wouldn't recommend going with an iteration plan-like system unless you really need that sort of coordination (when the team is sufficiently large), as it does take additional effort to manage.
