### ISSUE TITLE
builds for 1.3.4 and/or 1.4.0 releases ?

### ISSUE THREAD

**Issue by jokeyrhyme** [zeit/hyper#2091]
I just noticed that we have newer releases that I wasn't previously aware of (1.3.4 and 1.4.0):
https://github.com/zeit/hyper/releases

Are there known issues with them that discourages using them?
What is the process for getting those convenient download links for pre-built binaries?

**Comment by CodeTheory** [comment]
Feel free to use them. We're currently preparing them for release. 😄 

Releasing creates binaries. Your Hyper will notify you when there's an update.

**Comment by jokeyrhyme** [comment]
@CodeTheory awesome, thanks :)
