### ISSUE TITLE
Maximizing Hyper in 2nd screen moves the window to the main screen

### ISSUE THREAD

**Issue by axelitus** [zeit/hyper#2094]
While having 2 monitors (I'm guessing with more this happens too) and wanting to maximize Hyper in the 2nd monitor, hitting the maximize button always moves Hyper to the main screen and maximizes the window there, not in the 2nd monitor.

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by ppot** [comment]
Interesting.... Can you try with atom and tell me how it work?

**Comment by chabou** [comment]
Can you try with our last release [1.4.3](https://github.com/zeit/hyper/releases/tag/1.4.3)?

**Comment by axelitus** [comment]
I'll try later this day and get back to you with the results.

**Comment by axelitus** [comment]
I can confirm this works as expected in version 1.4.3 which is the latest at the moment. Thank you!

I've tried to minimize, restore, maximize and they all work great (even with the Ctrl+Win+Up and Ctrl+Win+Down shortcuts. The Shift+Ctrl+Win+Left and Shift+Ctrl+Win+Right shortcuts work also fine for placing Hyper at either half of the screen). The only small bug I sometimes, while restoring, the window position would change. But I couldn't reproduce it (I mean I don't know what combination of movements yields that bug and it may be related to windows and not directly to Hyper).

I'll close this issue now as it is working fine.

**Comment by axelitus** [comment]
See also related issue #2095 if you experience those issues with Hyper.
