### ISSUE TITLE
Using Windows 10 screen edge sweet spots does not work

### ISSUE THREAD

**Issue by axelitus** [zeit/hyper#2095]
Trying to use the Windows 10 "drag to sweet spots" at the edge of the screen sides to attach to half of the screen or at the top edge spot to maximize the window do not work for Hyper.

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by SergioLuis** [comment]
Moving the window with the Windows keyboard key + direction keys doesn't work either. This is specially annoying when Hyper is left out of the screen. I can't get it back, and every time hyper launches, it does so outside of the visible bounds of the screen. So, right now I'm not able to use Hyper.

Can someone at least tell me where does Hyper store its window position between application launches? If not, I'll dig into the code myself, but somebody might help me out... 😄

**Comment by shaaaaawn** [comment]
I'm having the same issue with Windows Keys. Seems odd, don't have this issue with other Electron apps.

**Comment by axelitus** [comment]
This is already working in the latest version 1.4.3, I can confirm that. Please see #2094 also for reference as I think they were related.

**Comment by chabou** [comment]
@axelitus After reading your comment in #2094, I was desesperatly  searching this issue. That was because you had already closed it 😍 
Thank you so much! 🙏

**Comment by axelitus** [comment]
Haha sorry, helping a bit to clean up the open issues. I've also referenced this issue from #2094 for anyone that comes across that has any of the issues described in one or the other.
