### ISSUE TITLE
I set HamburgerMenu = True but nothing shows up

### ISSUE THREAD

**Issue by SolarAquarion** [zeit/hyper#2096]
ArchLinux
1.3.3
https://gist.github.com/anonymous/6f033755c44ba71dd5d5535b15872a31

Is Vanilla

I do not have a "AppMenu" therefore i need settings as an actual thing that is part of the window

**Comment by saadq** [comment]
Shouldn't it be `true` instead of `'true'`?

**Comment by SolarAquarion** [comment]
I tried all ways and all of them failed including like ``

**Comment by CodeTheory** [comment]
@SolarAquarion You've tried even without any quotes at all?

**Comment by SolarAquarion** [comment]
Yes
