### ISSUE TITLE
Get rid of `border-radius` in fullscreen mode (macOS)

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#21]
Hopefully the fullscreen events fire in the main browser `window` to make this easier.

**Comment by rauchg** [comment]
@montogeek you can take a look at this one if you'd like!

**Comment by montogeek** [comment]
@rauchg I actually like the border but it will take a look!

**Comment by rauchg** [comment]
@montogeek I like the border, but do you think the `-radius` makes sense ?

**Comment by montogeek** [comment]
@rauchg It already has a `border-radius`, I like it that way

**Comment by rauchg** [comment]
Yeah it's not *bad*, but for example Chrome and others make their borders rectangular when going fullscreen.

**Comment by hharnisc** [comment]
In fullscreen with no radius, looks pretty sweet!

![screen shot 2016-07-06 at 6 37 16 pm](https://cloud.githubusercontent.com/assets/1388079/16637937/b3c1ce74-43a8-11e6-865d-a71b3fd5e5b2.png)

**Comment by kaicataldo** [comment]
Thoughts on removing the border entirely in fullscreen mode? I think it looks a lot cleaner and has a more native feel without (and would match the behavior of other applications like iTerm).

**Comment by CodeTheory** [comment]
I actually really like HyperTerm fullscreen without the border + border-radius 
![image](https://cloud.githubusercontent.com/assets/1695613/18818752/6ed30444-8382-11e6-9041-5aa1e9791191.png)

Seems really attractive.

**Comment by kaicataldo** [comment]
Yeah! Though I still like the border around tabs when are there are multiple tabs.

**Comment by kube** [comment]
Is this possible now ?
Any class added when in mac fullscreen mode ?

**Comment by rauchg** [comment]
@kube I wonder if this applies: https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen

**Comment by kube** [comment]
I just tried to add `:fullscreen` on `.tabs_nav` in my own CSS, and it does not work.

So I tried from the Developer Tools to add manually a new rule with `:fullscreen` but Chromium does not seem to accept it (rule is not added).

I then tried with `:webkit-fullscreen`, `:full-screen`, and `:webkit-full-screen`, without success.

To be sure, I added manually a new rule with `:hover` and the rule was correctly added.

So I guess Electron does not support this at the moment.

I tried this on both the version from the website, and the version on `master`.

**Comment by kube** [comment]
I rapidly looked the code on the repo, and there seems to be a `UI_WINDOW_MAXIMIZE` Action.

I did not find where this action is actually dispatched (where it listens for a Window maximize or fullscreen event)

Maybe using this Action and State `ui.maximized` boolean to toggle a `.hyper-fullscreen` CSS class at the React root component would be a solution ?

Then we could create custom CSS rules like this :
```
.hyper-fullscreen nav.tabs_bar {
  background-color: black;
}
```

**Comment by rauchg** [comment]
Yep @kube (not to be confused with [kubo](https://en.wikipedia.org/wiki/Kubo_and_the_Two_Strings)). I strongly suggest creating a plugin!

You could call it: `hyper-borderless-fullscreen` :P
