### ISSUE TITLE
Bug with auto-updates and multiple windows

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#210]
I ran into an issue twice where if you have two windows open, the `Install` link from the auto-update notification doesn't work. 

Would be really nice to look into this!

**Comment by dfrankland** [comment]
Seems to be the same issue here https://github.com/electron/electron/issues/3837

**Comment by albinekb** [comment]
I'm thinking that it would be a good idea to fix this when #403 has landed, that way we can use that functionality to make sure the user is ready for a restart 👀

**Comment by chabou** [comment]
It has been fixed
