### ISSUE TITLE
Error: Command failed: npm prune && npm install --production

### ISSUE THREAD

**Issue by boyedarat** [zeit/hyper#2100]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: It is stock, no modifications
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When running Hyper for the first time the following error is generated. I've tried all the fixes provided with similar issues reported on this error, but none of them works. It seems to be looking for an install of NPM? Also npm-debug.log doesn't exist.

Error output:
C:\Users\st4r\AppData\Local\hyper\app-1.3.3>Hyper.exe

C:\Users\st4r\AppData\Local\hyper\app-1.3.3>
plugins have changed / not init, scheduling plugins installation
running in prod mode
electron will open file://C:\Users\st4r\AppData\Local\hyper\app-1.3.3\resources\app\index.html
Checking for notification messages
No matching notification messages
Error: Command failed: npm prune && npm install --production
'npm' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[Notification] Error updating plugins.: Check `~/.hyper_plugins/npm-debug.log` for more information.

**Comment by boyedarat** [comment]
I managed to fix this error by installing Node.js. Is Node.js required to be installed separately for this software to work? There was no mention anywhere that a separate install of Node.js was required. Also there is no npm install provided with hyper, could not find any of the npm files in the hyper install.

**Comment by chabou** [comment]
`node` and `npm` are not required anymore since 1.4.0 :tada:
