### ISSUE TITLE
Error in run

### ISSUE THREAD

**Issue by bestgustavo30** [zeit/hyper#2104]
Every time I run Hyper or try to update plugins a windows notification pops with the next text
Error updating plugins
Check '~/.hyper_plugins/npm-debug.log' for more information.
and the npm-debug.log file doesn't exist

-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by CodeTheory** [comment]
You mean the issue presented at #2004?

**Comment by bestgustavo30** [comment]
Oh sorry I forgot check open issues
yep #2004 and #312, Both describe my problem well
this is a clean installation of Hyper 1.3.3, first time in this PC

**Comment by ppot** [comment]
I will close as duplicated.
