### ISSUE TITLE
ctrl + w / ctrl + a / deally all keymaps should be configurable

### ISSUE THREAD

**Issue by orangecms** [zeit/hyper#2106]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: GNU/Linux 4.9.24 with grsecurity
- **Hyper.app version**: 1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/orangecms/f7ccf196e85698cf35a01130ef7c2b8f
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:
```
(re)loading renderer plugins
total init time 1634.5550000000005
```
- **The issue is reproducible in vanilla Hyper.app**: yes :cry: 

## Issue
I have a serious problem. I'd usually just use a pure tty. But I am a web developer, so I work on an actual desktop. I tried this awesome terminal emulator, and I love the hyperpower plugin. It reminds me of activate-power-mode, which I used in Atom. Now I switched to Vim, and I need the ctrl + w keybing there for switching between the panes. Aside of it, I use tmux, and in tmux as well as some other tools like screen and minicom, I need the ctrl + a keybinding. They are being used, however, by Hyper. I couldn't find an option to disable them. I tried the `modifierKeys` options to fix that, but it didn't change anyhitng. :/

Addendum:
I did see other issues raised around keymaps. They are close to what I would prefer, but not fully. I am trying to run from the current master branch, but the build process is very complicated. I would prefer to just have a tiny bundle (not 350MB, rather like 20MB max) that I can just run with Electron, and build everything from source. I am building Electron from source as well, and I have a Makefile in progress for Hyper.

**Comment by sindrenm** [comment]
See https://github.com/zeit/hyper/pull/1876. :smile:

**Comment by chabou** [comment]
Default keymaps have changed to prevent shell and command line conflict 🎉 

You can use build from CIs if you want to test master.
Really curious about your `Makefile`. I think I missed the point.

I'm closing this issue but we can continue to discuss here
