### ISSUE TITLE
Cannot quit / save in nano (CTRL+O, CTRL+X)

### ISSUE THREAD

**Issue by mlosh** [zeit/hyper#2107]
- [+] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [+] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 17.04 Zesty Zapus**: 
- **1.3.3**: 
- **https://gist.github.com/mlosh/7e178e5cb81f7c9044d7a031c3435079**: 
- **N/A**
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by albinekb** [comment]
Duplicate of https://github.com/zeit/hyper/issues/1121
