### ISSUE TITLE
Feature Request: Bash like features for windows

### ISSUE THREAD

**Issue by JOS654** [zeit/hyper#2115]
Hi, I'm quite new to Github, so apologies if this issue doesn't belong here.

First of all congratulations for hyper is a beautiful and very powerfull tool.

Unfortunately in windows due to the lack of native bash, hyper lacks some critical features like tab autocompletion for commands.

If you could implement something like this project to hyper it would make it the best terminal application for windows in my opinion.

https://mridgers.github.io/clink/

Kind regards

**Comment by afturner** [comment]
Hey dude! Hyper is a terminal emulator and really shouldn't be used to add functionality to the underlying shell. 

Instead, I would recommend using git bash and setting it as your default Hyper shell. Here's a little tutorial on git bash:
https://openhatch.org/missions/windows-setup/open-git-bash-prompt

**Comment by Mohamed3on** [comment]
Maybe use Bash on Windows, install zsh and oh-my-zsh?
I have tab auto-completion and autosuggestion that way.

**Comment by JOS654** [comment]
Thanks for the suggestions, following that I found this guide to configure it: https://evdokimovm.github.io/windows/zsh/shell/syntax/highlighting/ohmyzsh/hyper/terminal/2017/02/24/how-to-install-zsh-and-oh-my-zsh-on-windows-10.html
Cheers

**Comment by ppot** [comment]
Closing since it's answered and related to bash on windows
