### ISSUE TITLE
Rebind CTRL+SHIFT+C to CTRL+C? [Windows]

### ISSUE THREAD

**Issue by isseiler** [zeit/hyper#2116]
Is there a technical reason or FAQ that states why this cannot be done?

Anyone that has used a computer for longer than a year must be able to feel how jarring it is to move the well known CTRL+C or command+C over to CTRL+SHIFT+C like wise with the paste command.

I am aware of  CopyOnSelect setting but I cannot support terrible UX designs and it should of never existed by default for Windows' CMD.

The keymap plugin unfortunately doesn't support this from what I've seen and I don't see any option in the hyper.js file that would allow this.

I would like to move the control break to CTRL+X and remove the need for shift entirely.

Can I modify the hotkeys in hyper-master\app\keymaps\win32.json file and just rebuild Hyper?

**Comment by ppot** [comment]
@isseiler Why would you do this. You can just in `hyper.js` on master

```
keymaps: {
...
}
```

see #1876

**Comment by isseiler** [comment]
Thanks...please show me where this is specified or mentioned in the Hyper docs for educational purposes.

Zero results of that config option existing in:
.hyper.js
https://hyper.is/#cfg
https://github.com/zeit/hyper/blob/master/readme.md

**Comment by ppot** [comment]
@isseiler We commented it in the wait of release. It's intended

**Comment by isseiler** [comment]
Okay, does this look right then? Or is it supposed to be in the standard config? Does the stable release support keymaps?

module.exports = {
  config: {

... #other stuff

},
keymaps: {
  "editor:copy": "ctrl+c"
  }

};

**Comment by ppot** [comment]
@isseiler Only master support keymaps for now

**Comment by isseiler** [comment]
I was able to make a build of the `master` repo and run an unpacked compiled version of Hyper but every time I hit ctrl+c it just puts in ^c or cancels to.

Any ideas?

**Comment by ppot** [comment]
might be related to cmd?

**Comment by isseiler** [comment]
What do you mean?
