### ISSUE TITLE
Text overlap

### ISSUE THREAD

**Issue by FAKER-A** [zeit/hyper#2119]
-

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

![image](https://user-images.githubusercontent.com/25676164/29709307-68f3afe0-89be-11e7-864c-1179a4f5b2e9.png)

**Comment by OmgImAlexis** [comment]
Duplicate of https://github.com/zeit/hyper/issues/283

**Comment by CodeTheory** [comment]
Thanks @OmgImAlexis. Closing in favour of #283.
