### ISSUE TITLE
A guide in order to open hyper at current folder using Automator.

### ISSUE THREAD

**Issue by IanCarrasco** [zeit/hyper#2120]
# How to open hyper at current directory.

1.Go to the forked cd\_to github repository and download the latest release.(zipped) [Download From Github](https://github.com/ealeksandrov/cdto/releases/tag/2_8_0). 

2.Within cd\_to, open the Hyper folder and drag the cd_to.app file into your Applications folder ![MacDown Screenshot](https://image.ibb.co/i3s6rk/Screen_Shot_2017_08_25_at_10_47_16_AM.png).

3.Now open up Automator and create a new service.
File>New>Service(gear icon).Be sure to save the service with an effective name like "Hyper Terminal at Folder"
![MacDown Screenshot](https://image.ibb.co/dxUQj5/Screen_Shot_2017_08_25_at_10_53_22_AM.png)

4.Finally create a Run Shell Script command from the utilities panel and type in ```open /Applications/cd_to.app```
![MacDown Screenshot](https://image.ibb.co/fU84Bk/Screen_Shot_2017_08_25_at_10_56_03_AM.png)

If everything worked out properly when you click run it should open a Hyper terminal instance at the Applications folder where automator is located.

# Creating a Shortcut for the Service
1.Go to System Preferences>Keyboard. And in the services pane find the service that has the same name as your automator script. Then assign a new short cut by clicking Add Shortcut. I used Control + Cmd + H as several shortcuts are already taken within Finder.
![MacDown Screenshot](https://image.ibb.co/kdwrrk/Screen_Shot_2017_08_25_at_11_04_25_AM.png)

If your shortcut is not working immediately go click it manually once a folder is selected from Finder's menubar and the keyboard shortcut should be activated. As the service is only available on file/folder contexts. 
![MacDown Screenshot](https://preview.ibb.co/fq4cWk/Screen_Shot_2017_08_25_at_11_09_55_AM.png)

**Comment by neonmori** [comment]
Drag the cd_to app from Application folder to toolbar while pressing CMD key will make the app become a button. Every time you click the button it will open the current folder in hyper.

**Comment by IanCarrasco** [comment]
Nice addition.

**Comment by chabou** [comment]
This issue should be mentioned in documentation. (PR Welcome)
Thank you so much for this tutorial 😍
