### ISSUE TITLE
Cursor problem and Chinese character displayed incorrectly.

### ISSUE THREAD

**Issue by QwQ11** [zeit/hyper#2124]
Using the WSL and oh-my-zsh.
1. The cursor is not in the correct position.
![default](https://user-images.githubusercontent.com/13375959/29813124-8d4eb298-8cdb-11e7-9e3e-4542f5b6a2e3.png)
I haven't type anything, but once you type a word, the cursor will back to right position, it is easy to see it before it is not where it should be. This problem also appears the last character you typed is a space.
![default](https://user-images.githubusercontent.com/13375959/29813187-e1bce868-8cdb-11e7-9c42-6a9fb5a2ebbf.png)

2. Can not display Chinese character correctly, seems this problem still not being fixed.
![default](https://user-images.githubusercontent.com/13375959/29813442-ac4fa3e0-8cdc-11e7-8373-666742db31a0.png)
what's worse, using the `clear` command.
![default](https://user-images.githubusercontent.com/13375959/29813478-c9c77894-8cdc-11e7-95d5-eded04f5f2ff.png)

character: 你好

----

Hyper 1.3.3
Electron 1.4.16
win32 x64 10.0.15063

**Comment by chabou** [comment]
Can you try to reproduce with [v1.4.3](https://github.com/zeit/hyper/releases/tag/1.4.3) ?

**Comment by LitoMore** [comment]
@chabou I can reproduce this bug with v1.4.3 .

### Expected behavior

<img width="605" alt="e-hyper" src="https://user-images.githubusercontent.com/8186898/30009052-d99b0ffe-9157-11e7-9430-ee7db8a2cfae.png">

### Actual behavior

<img width="603" alt="a-hyper" src="https://user-images.githubusercontent.com/8186898/30009071-f58ef388-9157-11e7-9959-2f03c3554806.png">

### How to reproduce this bug on macOS

Use `Terminal.app` or `iTerm.app`:

```bash
$ echo 你好 > sample
```

Then use `Hyper.app`:

```bash
$ cat sample
```

**Comment by lucasqueiroz** [comment]
When pasting the character in the terminal, in 1.4.3, the bug also happens:
<img width="936" alt="screen shot 2017-09-04 at 09 01 55" src="https://user-images.githubusercontent.com/29466590/30025633-c9e4b7fc-914f-11e7-8829-da48e6f4630c.png">

**Comment by chabou** [comment]
Will be fixed in 2.0.0 thanks to `xterm`
I tried your example with our `xterm` branch, and it works like a charm:
![capture d ecran 2017-09-04 a 19 55 27](https://user-images.githubusercontent.com/4137761/30035518-4a161d02-91ab-11e7-87e8-556a760769e4.png)

**Comment by timothyis** [comment]
@QwQ11 Could you try this on the latest version of Hyper? I think your issue should be fixed! 🙏

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
