### ISSUE TITLE
error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by matthewkturner** [zeit/hyper#2134]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Debian 9 (Stretch)
- **Hyper.app version**: 1.4.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: n/a
- **Relevant information from devtools** n/a
- **The issue is reproducible in vanilla Hyper.app**: Won't launch

## Issue
hyper fails to launch from *.deb dpkg install to launch and throws...

`hyper: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory`.

*.AppImage seems to work just fine, but figured I would share this in the event any one else had issues.

**Comment by WoodyWoodsta** [comment]
Same thing as well. It also basically undid half my system (almost every electron related apps, `libc++`, wingpanel indicators...).

**Comment by quagliero** [comment]
Same here. `Requires the REMOVAL of the following packages: google-chrome-stable indicator-application libappindicator1 libindicator7 slack-desktop`

**Comment by WoodyWoodsta** [comment]
@quagliero - Ah. The link on the site is wrong then!

**Comment by quagliero** [comment]
@WoodyWoodsta Aha! You are correct. Downloading the 64-bit .deb from hyper.is gives you the i386 package. Maybe it wasn't a brain fart then (well, only partial) :smile: 

I guess that should be opened as a separate issue?

**Comment by WoodyWoodsta** [comment]
I would say that the above issue is very much related! I had all the same symptoms :)

**Comment by chabou** [comment]
Download link has been fixed.
Sorry for this mistake and these side effects
