### ISSUE TITLE
Update to 1.4.0 changed hyperborder Theme

### ISSUE THREAD

**Issue by cytryn** [zeit/hyper#2135]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac OS X 10.12.6**: 
- **Hyper.app 1.4.0**: 

## Issue
After the update the `hyperborder` theme now does not respect my background color. It used to be only colored border, now it colors the whole terminal

![image](https://user-images.githubusercontent.com/735750/29890618-a0443530-8d9e-11e7-943c-3d8a2e0cdc0b.png)

also, I can't type things like `vim ~/.zshrc`, it wont let me type `~`. I know there are other issues about this but they are all fixed and closed, but it seems to have resurfaced again:

![image](https://user-images.githubusercontent.com/735750/29890746-05bd6170-8d9f-11e7-8cb3-fc05489b0b14.png)

Is there something I missed in the update?

**Comment by leo** [comment]
Have you considered that the plugin needs to be updated?

**Comment by chabou** [comment]
`hyperborder` plugin depends on `hyper_main` css class. But we only have `_main` class now 🤔 
Certainly a regression.

Same for `hyper_header` `hyper_terms` etc..

**Comment by cytryn** [comment]
@leo yeah, good point. I am pretty new to zsh+hyper so I am sorry about the noob question. Though that hyperborder was pretty basic and would not be affected by any update before being tweaked.

What about the `~` and other special characters like `'` and `"`?

**Comment by leo** [comment]
https://github.com/zeit/hyper/issues/2140
