### ISSUE TITLE
Not able to write any composed characters

### ISSUE THREAD

**Issue by bukinoshita** [zeit/hyper#2140]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.6
- **Hyper.app version**: 1.4.1

## Issue
Not able to write `'` and `"`.
![kapture 2017-08-30 at 16 53 55](https://user-images.githubusercontent.com/6929565/29894631-fc6ba88e-8da3-11e7-9481-755e4cabd8ae.gif)

**Comment by chabou** [comment]
Can you try without any plugin ?

**Comment by bukinoshita** [comment]
just tried, same result

**Comment by tleunen** [comment]
Same issue since the recent 1.4.x

I'm using the "US international - PC" keyboard on mac, and both the single quote and double quote are now failing to work properly.

This uses to work fine on 1.3.x

**Comment by cytryn** [comment]
+1 I have the same issue

**Comment by lidin** [comment]
Can confirm this issue on my Swedish keyboard. Seems like all accent characters (~, ¨, ´, `, etc.), that is symbols requiring an additional keystroke to be written out, are subject to this.

**Comment by chabou** [comment]
Reproduced with a french keyboard for symbols requiring an additional keystroke as mentioned by @lidin.
I've found a weird "workaround": hitting same character or click left with mouse (focusing seems to release catched char). But impossible to compose ñ for example 😞

**Comment by chabou** [comment]
Regression was introduced by upgrading electron in this commit:
https://github.com/zeit/hyper/commit/e09a7f717d515ec5ba3395cc3c7f232a238aa7ce

**Comment by JoJordens** [comment]
Looks like this is the case with all dead keys. ~ ' " ^ etc

**Comment by albinekb** [comment]
I can type ' and ", but have problem with key compositions like ` and  ~  (on swedish keyboard)

it would be helpful if you added what keyboard layout you're using when you get the problem with " and ' as I cannot reproduce this.

**Comment by wellyal** [comment]
I was able to press `'` and then space. But the newest version took that off from me :'(

**Comment by mdeboer** [comment]
Same problem here, U.S. International - PC keyboard layout. Can't write `'`, `"` and `~`. Seems like all characters that are composed with more than one key are bugged.

What's a terminal without ~? 😕

**Comment by mdeboer** [comment]
W00t @chabou you're a legend, can't wait to try this!

**Comment by chabou** [comment]
Shipped in [v1.4.3](https://github.com/zeit/hyper/releases/tag/1.4.3).
@mdeboer Please confirm that your issue is resolved

**Comment by bukinoshita** [comment]
@chabou working just fine with me, thanks!

**Comment by leo** [comment]
🎉

**Comment by wellyal** [comment]
@chabou you're a hero. thx!!!!

**Comment by albinekb** [comment]
:tada:

**Comment by mdeboer** [comment]
@chabou I updated and tried today, it works perfectly for me! 👍
