### ISSUE TITLE
Linux: ctrl+v not working on 1.4.2

### ISSUE THREAD

**Issue by raphaklaus** [zeit/hyper#2141]

**Comment by miguelmich** [comment]
Did you tried Ctrl + Shift + V? I think this has to be with #1876

**Comment by miguelmich** [comment]
btw: if you want to know what are the [available keymaps](https://github.com/zeit/hyper/tree/master/app/keymaps)

**Comment by raphaklaus** [comment]
Ctrl+ Shift + V works, but I almost right that ctrl+v worked in the latest releases.

**Comment by hyphaene** [comment]
I'll extend this : 

     "pane:splitVertical": "ctrl+right",
      "pane:splitHorizontal": "ctrl+down",
      "pane:close": "ctrl+w",
      "editor:undo": "ctrl+z",
      "editor:redo": "ctrl+y",
      "editor:cut": "ctrl+x",
      "editor:copy": "ctrl+c",
      "editor:paste": "ctrl+v",

none of these work !

**Comment by miguelmich** [comment]
@hyphaene I'm on Ubuntu 16.04 with the same version and it worked for me, did you try restarting the app?

**Comment by miguelmich** [comment]
Yes, the same here @raphaklaus it was working that way before the last two releases, maybe with #1876 things changed.

**Comment by hyphaene** [comment]
@miguelcg 

Yep, I did .

Here is my.hyper.js file content : 

```
module.exports = {
  config: {
    fontSize: 14,
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorShape: 'BLOCK',
    cursorBlink: false,
    backgroundOpacity: 0.6,
    css: '',
    termCSS: '',
    showHamburgerMenu: true,
    showWindowControls: '',
    // padding: '12px 14px',
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: true,
    paneNavigation: {
      debug: false,
      hotkeys: {
        navigation: {
          up: 'alt+up',
          down: 'alt+down',
          left: 'alt+left',
          right: 'alt+right',
        },
        jump_prefix: 'ctrl+alt', // completed with 1-9 digits
        permutation_modifier: 'shift', // Added to jump and navigation hotkeys for pane permutation
        maximize: 'alt+enter',
      },
      showIndicators: false, // Show pane number
      indicatorPrefix: '^⌥', // Will be completed with pane number
      indicatorStyle: {
        // Added to indicator <div>
        position: 'absolute',
        top: 0,
        left: 0,
        fontSize: '10px',
      },
      focusOnMouseHover: true,
    },
    keymaps: {
      "pane:splitVertical": "ctrl+right",
      "pane:splitHorizontal": "ctrl+down",
      "pane:close": "ctrl+w",
      "editor:undo": "ctrl+z",
      "editor:redo": "ctrl+y",
      "editor:cut": "ctrl+x",
      "editor:copy": "ctrl+c",
      "editor:paste": "ctrl+v",
    },
  },
  plugins: [
    'hyperterm-tabs',
    'hyper-pane',
    'hyperlinks',
    'hyper-simple-highlight-active-session',
    'hyper-nord-wall',
    'hyperborder',
    'hyperline',
    'hyper-tabs-enhanced',
    'hyper-tab-icons',
    'gitrocket',
    'hyper-alt-click',
  ],
  localPlugins: [],
};
```

do you notice anything ?

The app runs perfectly well besides the keymaps ( no errors or anything )

I'll open another issue if needed, but it seemed related to this topic ..

**Comment by miguelcg** [comment]
@hyphaene I think you mentioned the wrong user :)

**Comment by miguelmich** [comment]
@hyphaene yes, I think **keymaps** should be outside of **config**, try to put it below `localPlugins: [],`

**Comment by hyphaene** [comment]
@miguelcg  my bad !

@miguelmich Perfect ! I didn't notice ... thanks !

**Comment by chabou** [comment]
It is better to not use `ctrl+[a-z]` as default keymaps, because it is reserved to shell and command line programs.
But you can change it easily.
