### ISSUE TITLE
Panes no longer work as intended after 1.4.2 update

### ISSUE THREAD

**Issue by kjullien** [zeit/hyper#2145]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 26
- **Hyper.app version**: 1.4.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default with : ```plugins: [
        "hyper-chesterish",
        "hyper-tabs-enhanced",
        "hyper-statusline",
        "hyperterm-overlay"
],```
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: YES

## Issue
Hello,

I have been using panels/panes on Hyper with the following shortcuts for a while :
- `CTRL+SHIFT+E` for horizontal panel
- `CTRL+SHIFT+O` for vertical panel
- `CTRL+W` to close a focused panel

The issue I have is that since I updated to 1.4.2 only horizontal splitting works, no more vertical.
Also I cannot close a focused panel with `CTRL+W`, if I try `CTRL+SHIFT+W` it simply closes Hyper altogether.

Am I the only one experiencing this issue ?

**Comment by yann-jacquet** [comment]
Hi guys! 
Version 1.4.2 here too and same problems with my panes. You are not alone in this mate !

**Comment by chabou** [comment]
It seems that default shortcuts have changed:
https://github.com/zeit/hyper/blob/1.4.2/app/keymaps/linux.json

You can [remap](https://hyper.is/#keymaps) them, but we should consider to change defaults.

Strange behaviour with `ctrl+shift+w`

@yann-jacquet what is your OS and hyper config?

**Comment by chabou** [comment]
There is a separated issue for closing pane (`ctr+shift+w`): #2156

@yann-jacquet @kjullien Can you give us your opinion there?

**Comment by yann-jacquet** [comment]
My OS is a Ubuntu Gnome 17.04 and default hyper config ! 
Okay switching issue !

**Comment by kjullien** [comment]
The new shortcuts that @chabou referenced do work.
I guess this means that this issue can be closed, I will add a commit to specify the shortcuts changed somewhere in the docs if I have some time.
I do experience the #2156 bug though.
