### ISSUE TITLE
Title text should be truncated not multiline

### ISSUE THREAD

**Issue by morajabi** [zeit/hyper#2148]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version

- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- **OS version and name**: macOS Sierra 10.12.5
- **Hyper.app version**: 1.4.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Nothing special, if it's necessary I'll provide.
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Title text should be truncated not multiline like this:
<img width="370" alt="screen shot 2017-08-31 at 5 26 15 pm" src="https://user-images.githubusercontent.com/12202757/29924373-fdda179a-8e71-11e7-9e3c-0e27804218c2.png">

**Comment by albinekb** [comment]
@henrikdahl didn't you fix this ages ago 🤔

**Comment by chabou** [comment]
Reproduced.
After changing current directory to have a long path in title, resize windows.

**Comment by morajabi** [comment]
If you tell me where to start, I can try fixing it myself in a PR!

**Comment by chabou** [comment]
You can inspect DOM/CSS with dev-tools and find a way to fix it.
Certainly add a `text-overflow: ellipsis;` somewhere.

Note: when you have severals tabs, header structure is different and title is ok. You can see how it works and make the same thing when there is only one tab.

**Comment by sabrown84** [comment]
Is this issue still open? Is there any guidance on how to solve this?

**Comment by albinekb** [comment]
this is fixed and will be released in 2.x  :) @sabrown84

**Comment by sabrown84** [comment]
Thank you @albinekb for letting me know. I'm glad it got resolved.
