### ISSUE TITLE
not possible to rebind "alt+cmd+left/right"

### ISSUE THREAD

**Issue by iamstarkov** [zeit/hyper#2149]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra 10.12.6
- **Hyper.app version**: Hyper 1.4.2 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/iamstarkov/c45ee5a8288ee3e3a8e70ff10c5fc1b5
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: reproducible with _vanilla_ hyper https://gist.github.com/iamstarkov/a466ec30b010f2ae22891f96e0ff483f.

## Issue

Hello, I'm trying to rebind `pane:prev/next` to be more iTerm2-ish (`alt+cmd+left/right`), but `alt+cmd+left/right` key is already binded for `tab:prev/next`, so i rebinding it as well:

```js
module.exports = {
  keymaps: {
    'tab:prev': 'ctrl+shift+tab',
    'tab:next': 'ctrl+tab',
    'pane:prev': 'alt+cmd+left',
    'pane:next': 'alt+cmd+right',
  },
  config: {},
};
```

And it seems like Electron catches up with updated keys (shows new keys in the menu), but hyper doesnt care and continues to switch tabs instead of panes.

![screen shot 2017-08-31 at 15 56 54](https://user-images.githubusercontent.com/559321/29926926-1751ec82-8e65-11e7-9e38-f0306152f2ca.png)
![screen shot 2017-08-31 at 15 56 43](https://user-images.githubusercontent.com/559321/29926927-17589852-8e65-11e7-96db-f33d95d64aa2.png)

PS. hyper.is needs to reference [available shortcuts](https://github.com/zeit/hyper/blob/master/app/keymaps/darwin.json) from [documentation page](https://hyper.is/#keymaps)

**Comment by beauallison** [comment]
I'm able to reproduce this - I'm running macOS Sierra 10.12.5.

Potentially related but I can't also rebind the `tab:new` key to `ctrl+t` - doing so updates the text but the key does not work.

**Menu Item**
![image](https://user-images.githubusercontent.com/14225594/29950673-ad7e38d2-8f00-11e7-9561-3de85920e916.png)

**hyper.js**
```javascript
module.exports = {
  config: {},
  keymaps: {
    'tab:new': 'ctrl+t',
  },
};
```

**Comment by ppot** [comment]
I found the bug.
Related to uiActions. `https://github.com/zeit/hyper/blob/master/lib/actions/ui.js#L128`

**Comment by ppot** [comment]
Look like it started woking normally. Without doing anything.

**Comment by ppot** [comment]
This is more complicated.... It's related to termGroups... Which need a whole revamp.  

@iamstarkov I tried with your binding. And the pane work on a single tab.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you! Also take a look at https://hyper.is/#keymaps
