### ISSUE TITLE
Bad displaying when run yarn

### ISSUE THREAD

**Issue by radi-cho** [zeit/hyper#2151]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate _(hopefully)_

- **OS version and name**: Windows 10 (Microsoft Windows v10.0.15063)
- **Hyper.app version**: Latest - 1.4.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Click Here](https://gist.github.com/radi-cho/1f8cb43b59abd469bc29a4974bbf3951)
- **The issue is reproducible in vanilla Hyper.app**: It exist in vanilla

## Issue

When I run `yarn` or `yarn add` or whatever the "'`Loading dots`'" are big and they cover a part of the previous line. This isn't very important issue, but I believe that Hyper will look better after fix...

![image](https://user-images.githubusercontent.com/12954909/29936722-e81fc214-8e8b-11e7-9e46-32d9348d9ec1.png)

**Comment by radi-cho** [comment]
Any updates? @rauchg

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
