### ISSUE TITLE
Implement Readline Keybindings

### ISSUE THREAD

**Issue by computersarecool** [zeit/hyper#2154]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] This is actually a duplicate of #1716 but that was closed without explanation.

- **Windows 10**
- **Hyper.app version 1.4.2**
- **I am using the default .hyper.js**
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
On every terminal emulator I have ever used these [keyboard shortcuts](https://ss64.com/bash/syntax-keyboard.html) are implemented.  They come from [GNU](http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html) and handle basic things like: going to the beginning of line, going to the end of line etc.

Right now Hyper (incorrectly in my opinion) maps Ctl-a to select all.  There has been some progress in implementing keymaps in hyper but looking at the list [here](https://github.com/zeit/hyper/blob/master/app/keymaps/win32.json) I do not see any place where things such as go to beginning of line are even addressed.

There is also no documentation on how to do this.  It seems like there is not a shortcut for `go to the beginning of line` available.

Shouldn't hyper  implement the same keyboard shortcuts as other terminal emulators and if it can not, should at least expose the default Readline keybindings?

Issue #1716 raises this same issue, but not is restricted to just the Ctl-A issue.
#1876 Claims to fix this issue but there is:

A. No description of what is changed

B. When you look at what is implemented by keymapping there is no explanation about how to implement readlines keybindings.

**Comment by ppot** [comment]
@computersarecool Hello there. Thanks for making an issue. Let me clear things out or you a little bit on what #1876 provide.
#### First
`It seems like there is not a shortcut for go to the beginning of line available.`
This is currently handled by default inside `hterm` and since we are moving to `xterm` it will be integrated automatically. 
#### Second
`Bash Keyboard Shortcuts`  are not Keymaps for the app. They are keybinding for Bash. The goal of keymaps is to provide a non intrusive configuration for defaults that are customizable and not overriding `defaults` of internal app such as `emacs`, `vim`, `nvim`, `nano` and so on.
#### Third
B. What are you referencing by `how to implement deadlines keybindings.` ?

**Comment by computersarecool** [comment]
`This is currently handled by default inside hterm`

Sounds good but [mosh for Chrome](https://github.com/rpwoodbu/mosh-chrome/blob/16ea9badcf81ca60e28984c5e0bffcb86958c3ca/mosh_app/mosh_window.js#L29) and [Secure Shell for Chrome](https://chromium.googlesource.com/apps/libapps/+/master/nassh/doc/FAQ.md#What-is-Secure-Shell) both use `hterm` and do not have this problem with keybinding.  Are you sure that it is not a WebKit issue here?

For your ***Second** point:  That distinction makes some sense but if that's what #1876 does I think that closing issues like #833 and #1716 is a mistake because it doesn't actually address those issues.

The main point here is this:

I use a terminal emulator to access programs, mainly `emacs`.  I would like all key combinations to be passed to the shell that I am running. When I have run bash on:
Terminal, iTerm2, xTerm, Terminator, Mosh for Chrome, Secure Shell, PuTTY, Cygwin, Ubuntu for Windows etc. `C-a` goes to the beginning of the line.  On Hyper it does not.  I do not know why Hyper is intercepting any keycommands but it seems like a bad idea (or at least something that should be toggle-able).  

The idea is that you can run Bash from Hyper, and run emacs within bash and your keys go directly to the program (they don't interfere with Hyper and select all text on the screen or anything like that at all).  Can we make this possible?

**Comment by ppot** [comment]
Like we say. This will be much more easier to implement once we switch to `xterm`.  Since `hterm` steel the key actions. I currently did hack some of it see: https://github.com/zeit/hyper/blob/master/lib/hterm.js#L236-L242

**Comment by computersarecool** [comment]
Cool. I appreciate your work.  I am really into this idea because I am hoping for a cross platform terminal emulator that just works.

Still, I think this issue should be left open until `xterm` is working.

**Comment by computersarecool** [comment]
Is there any way I can track the progress of this or possibly help?
I am waiting to switch to Hyper until this is implemented and can't wait.

**Comment by chabou** [comment]
I think this is fixed since new keymapping and not using `ctrl+[a-z]` shortcut anymore.

**Comment by chabou** [comment]
@computersarecool Can you check our last canary and confirm that it's suits your needs?

**Comment by computersarecool** [comment]
My preliminary testing shows this as working on Windows when you set the `shell` to `bash.exe`.
Nice!
Thanks so much.
