### ISSUE TITLE
Vibrancy doesn't seem to be working

### ISSUE THREAD

**Issue by leo** [zeit/hyper#2155]
@evilrabbit reported this:

<img width="1080" alt="screen shot 2017-09-01 at 12 18 42 am" src="https://user-images.githubusercontent.com/6170607/29965328-7552c006-8f0d-11e7-93e5-64cadc642b8c.png">

**Comment by chabou** [comment]
Vibrancy works great with `hyper-simple-vibrancy`
@evilrabbit what is your hyper config?

**Comment by chabou** [comment]
@evilrabbit has confirmed that it is fixed
