### ISSUE TITLE
Close session conflicts with quit hotkey

### ISSUE THREAD

**Issue by MarkDaviesEsendex** [zeit/hyper#2156]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- OS: Windows 10
- Hyperjs version: 1.4.2
- hyper.js file: https://gist.github.com/MarkDaviesEsendex/f4d80724973952a4e5d27ba1c9b40713

## Issue
The CTRL+SHIFT+W hotkey is used for both close session and quit meaning that I have to close a tab with x button or middle mouse click

**Comment by chabou** [comment]
oups 😊 
Thank you for your feedback

**Comment by louislva** [comment]
Would CTRL+SHIFT+W for window and CTRL+ALT+W for session be suitable?

**Comment by chabou** [comment]
`ctrl+alt`is not a suitable modifier. See https://github.com/zeit/hyper/issues/2179#issuecomment-327690367
We should find another shortcut

**Comment by peterdanis** [comment]
I suggest:
"window:close": "ctrl+shift+q" (q as quit)
"pane:close": "ctrl+shift+w"
