### ISSUE TITLE
terminal hides when not in focus

### ISSUE THREAD

**Issue by derekedelaney** [zeit/hyper#2157]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.12.6 Mac OS
- **Hyper.app version**: 1.4.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/derekedelaney/4261849a3e235bf8489fe7683fa5af3d
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

Hyper hides the window if it is not in focus. 
If click anywhere else it hides itself.

http://recordit.co/0CVwzvoJJP
Above is a link to a screen grab where I click on hyper, then click on finder and it goes away.

This only started happening when i upgraded to 1.4.2

**Comment by chabou** [comment]
This issue is not reproductible with a vanilla Hyper.app.
I reproduced it with your config and found that is a problem with `hyperterm-summon` plugin. Commenting it fixed this issue.

Please open an issue in [hyperterm-summon](https://github.com/Soutar/hyperterm-summon) repository
