### ISSUE TITLE
Make mouse wheel events scroll through `less`, `git log` and `get diff` style output

### ISSUE THREAD

**Issue by hharnisc** [zeit/hyper#216]
Really miss this feature from Terminal.app

When you're viewing scrollable output with Terminal.app you're able to use the mouse wheel or trackpad to scroll through the content.

**Terminal.app**

![scrollterminal](https://cloud.githubusercontent.com/assets/1388079/16903730/bfce6442-4c4b-11e6-8be8-8f41fc0ddb56.gif)

**HyperTerm**

![scrollhyperterm](https://cloud.githubusercontent.com/assets/1388079/16903733/cab85566-4c4b-11e6-868c-59ff88f2b23b.gif)

It seems like this might be possible to make a plugin for this, and possibly be a candidate for a default plugin.

**Comment by lkzhao** [comment]
Checkout this guys. [hyperterm-alternatescroll](https://github.com/lkzhao/hyperterm-alternatescroll)

**Comment by matmunn** [comment]
This plugin no longer appears to work

**Comment by orcinus** [comment]
@MAPESO It doesn't.

**Comment by chabou** [comment]
Just tested with our v2 and it works great on macOS.

**Comment by orcinus** [comment]
Have you tested on Windows?

**Comment by chabou** [comment]
@orcinus no, the original poster was talking about Terminal.app.
Please open an issue if Windows native terminal handles it and not Hyper.

**Comment by orcinus** [comment]
Sending scroll and mouse messages to local apps and the remote host is not a Terminal.app specific feature. Right now, things like tmux mouse events, tmux buffer scroll etc. don't work at all in Hyper on Windows. As in there is *no* mouse messaging support *of any sort*. It's not a matter of "Windows native terminal handling it" or not handling it. It's a feature missing in Hyper.

Finally, the issue / request as reported was:
> Make mouse wheel events scroll through `less`, `git log` and `get diff` style output

not:
> Make Hyper behave as Terminal.app on Mac OS

But fine, i'll create a new issue.

**Comment by chabou** [comment]
> Make mouse wheel events scroll through less, git log and get diff style output
It works perfectly on macOS (platform of the original poster). So this issue is fixed.

There is some existing issue with tmux, do not create a new one please.
