### ISSUE TITLE
Chrome uninstalled after installing Hyper

### ISSUE THREAD

**Issue by lucasqueiroz** [zeit/hyper#2161]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04
- **Hyper.app version**: 1.4.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: I had just installed Hyper, so the default .hyper.js
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Whenever I install Hyper on my Ubuntu, it uninstalls Chrome. And when I install Chrome again, it uninstalls Hyper. No clue what is happening.
That doesn't happen in macOS or Windows (Because I tried on all of them).

**Comment by chabou** [comment]
Same feedback on slack: https://zeit-community.slack.com/archives/C1TMVKPFH/p1504126071000375

What is your installer? hyper_1.4.1_i386.deb from https://hyper.is?

**Comment by lucasqueiroz** [comment]
Yes, that's the one I'm using. I'll try with homebrew, the .AppImage and the .deb from github releases (though I think the last one might be the exact same one as in http://hyper.is, but doesn't hurt to try)

**Comment by lucasqueiroz** [comment]
I just tried with the .deb for amd downloaded through GitHub, seems to fix the issue.

**Comment by chabou** [comment]
Seems to be a side effect of https://github.com/zeit/hyper/issues/2150
