### ISSUE TITLE
.hyper.js file lost

### ISSUE THREAD

**Issue by janat08** [zeit/hyper#2162]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
Windows 10
- **Hyper.app version**: 
1.3.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
Can't find it
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 
Is Vanilla
## Issue

.hyper.js is not found at install location which happens to be in appdata/local while I'd rather it be in programs folder.

**Comment by chabou** [comment]
`.hyper.js` is located in your `%HOMEPATH%`.
You can edit it without knowing its location, using Hyper menu `Edit -> Preferences...`. 

We want to support XDG https://github.com/zeit/hyper/pull/1595

**Comment by janat08** [comment]
preferences don't open anything, don't know whats homepath.

**Comment by chabou** [comment]
`%HOMEPATH%` is an environnement variable, set based on the value of the home directory.

`.hyper.js` should be located in `c:/Users/<username>/`
But Windows hides system files and files starting with a point are considered as a system file.
Change your option to show these files.

**Comment by leo** [comment]
He seems to be looking in the wrong location - @chabou just commented with the right one.

**Comment by ashburry-chat-irc** [comment]
%USERPROFILE% is the home directory which includes the c:\ 
Where is the same as %HOMEDRIVE%%HOMEPATH%  (c:\ and \users\username)
Opening Edit -> Preferences creates the .hyper.js file. But if you open preferences twice the second one is blank. The shortcut keys are CTRL+Comma.

**Comment by HectorEnrique** [comment]
**apparently the route is not that 'users/useranme'. I am not using Windows 10 either, and apparently it is in AppData/Local, but in AppData/Roaming/Hyper, I share the image**

**Traduce esto en español Latino**: al parecer la ruta no es esa 'users/useranme'. Estoy usando Windows10, y al parecer tampoco esta en AppData/Local, sino en `AppData/Roaming/Hyper`, Les comparto imagen

![image](https://user-images.githubusercontent.com/103299718/222624320-b43d01bd-ce40-47af-94fd-4461be847a21.png)
