### ISSUE TITLE
osx-alt(aka option)+arrow behaviour

### ISSUE THREAD

**Issue by jhoogeboom** [zeit/hyper#2163]
When using alt+arrow in terminal.app I can move around to breaks in the command:

![2017-09-03 16 45 52](https://user-images.githubusercontent.com/1828504/30004004-a4f8696c-90c7-11e7-979b-7733adfdb68b.gif)

but in hyper, it produces text:

![2017-09-03 16 46 23](https://user-images.githubusercontent.com/1828504/30004007-ab37e866-90c7-11e7-8087-e5d2b8c7f99e.gif)

How do I get it to behave like the osx terminal?

**Comment by Spaxe** [comment]
This seems to have been fixed in v2.0.0 stable!
