### ISSUE TITLE
Crash when closing the last tab using Close Session

### ISSUE THREAD

**Issue by Xemiru** [zeit/hyper#2165]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7 Home Premium
- **Hyper.app version**: 1.4.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/Xemiru/03604fcb85cab6d1b1dd94329642206b)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Hyper crashes when you try to use the `File > Close Session` option whether through its menu or through its keyboard shortcut while it only has one tab open.

```
[Microsoft Visual C++ Runtime Library]
Assertion failed!

Program:
...acked\node_modules\node-pty\build\Release\pty.node
File: ..\src\win\pty.cc
Line: 261

Expression: pc != nullptr
```

Not sure if this is Hyper's fault, but it isn't a serious issue either.

**Comment by F21** [comment]
Seems to e a duplicate of #2143

**Comment by Xemiru** [comment]
Moving my details and closing in favor of that issue, then.
