### ISSUE TITLE
Problems on Chinese Support

### ISSUE THREAD

**Issue by csujedihy** [zeit/hyper#2172]
1. Unable to type chinese. The input method window pops up and disappears immediately. 
 2. After Chinese characters are pasted, they cannot be correctly displayed.
![image](https://user-images.githubusercontent.com/6022514/30036534-ecee3dd4-9179-11e7-9cd8-6be6d27de829.png)
3. After deleting Chinese characters, same here.
![image](https://user-images.githubusercontent.com/6022514/30036567-2f72f212-917a-11e7-8de0-def71636c58f.png)

        -
        Hyper 1.4.2
        Electron 1.6.12
        darwin x64 16.7.0

**Comment by chabou** [comment]
Will be fixed in 2.0.0 when `hterm` will be replaced by `xterm.js`

**Comment by csujedihy** [comment]
@chabou Awesome!

**Comment by jaywcjlove** [comment]
`2.0.0-canary.10` @chabou  Not successfully repaired

**Comment by albinekb** [comment]
What's the issue @jaywcjlove as we don't know chinese it's **almost impossible** for us to fix it :/

**Comment by jaywcjlove** [comment]
@albinekb Chinese can not input.
![loading io](https://user-images.githubusercontent.com/1680273/35151115-01241c66-fd58-11e7-9a42-fe5d08108db6.gif)

**Comment by albinekb** [comment]
Are you sure that's canary? @jaywcjlove `hyperpower` plugin shouldn't work there..

**Comment by jaywcjlove** [comment]
@albinekb Remove the plug-in, Chinese or can not input.

![loading io](https://user-images.githubusercontent.com/1680273/35153923-49ea9442-fd63-11e7-900a-cb60132862f1.gif)

**Comment by albinekb** [comment]
You need to test with `canary`, hyper 2.0.0-canary. It's using a much more modern library for rendering and also key composition. Download it from the releases tab https://github.com/zeit/hyper/releases/tag/2.0.0-canary.10
https://github.com/zeit/hyper/releases/tag/2.0.0-canary.10
https://github.com/zeit/hyper/releases/tag/2.0.0-canary.10

@jaywcjlove 🙂

**Comment by jaywcjlove** [comment]
@albinekb  I confirm using the `2.0.0-canary.10` version test.

**Comment by jaywcjlove** [comment]
My system information: 

- [x] mscOS High Sierra  version 10.13.2
- [x] [Hyper-2.0.0-canary.10.dmg](https://github.com/zeit/hyper/releases/download/2.0.0-canary.10/Hyper-2.0.0-canary.10.dmg)

@albinekb

**Comment by csujedihy** [comment]
@jaywcjlove I'm using 2.0.0 and I have no problem on typing Chinese.

**Comment by jaywcjlove** [comment]
@csujedihy I do not know what to do? My download is up to date. Never installed before.

**Comment by jaywcjlove** [comment]
Update the system to restart the computer. No problem. 

@albinekb Thank you!

**Comment by jaywcjlove** [comment]
Update the system to restart the computer. No problem. 

@albinekb Thank you!
