### ISSUE TITLE
Error + Fix: Color hsl(167, 83%, 47%) is invalid

### ISSUE THREAD

**Issue by rolbr** [zeit/hyper#2174]
When launching Hyper, I get a Windows Notification `Color hsl(167, 83%, 47%) is invalid`. The application launches, but the console window remains blank (black).

This can be fixed by removing the semicolon on the end of line 15 in `.hyper.js`
        -
        Hyper 1.4.3
        Electron 1.7.5
        win32 x64 10.0.15063

**Comment by henrikdahl** [comment]
Where did you get your config? `Color hsl(167, 83%, 47%)` is not present nor added into the default config by Hyper.

Maybe you copied someone's config. However it's not an issue with Hyper hence closing ✌️
