### ISSUE TITLE
Opening a new tab throws an uncaught exception

### ISSUE THREAD

**Issue by cfjedimaster** [zeit/hyper#2175]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cfjedimaster/7cfe0d2e70ae217c6e06eaf32e545a79
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: No, and also not reproducible w/ plugins installed. It appears as if it was a one time event, but I wanted it logged in case I run into again.

## Issue
Opening a new tab threw this error:

A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Unable to start terminal process: CreateProcess failed
    at new WindowsPtyAgent (C:\Users\ray\AppData\Local\hyper\app-1.4.3\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\ray\AppData\Local\hyper\app-1.4.3\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:45:24)
    at spawn (C:\Users\ray\AppData\Local\hyper\app-1.4.3\resources\app.asar\node_modules\node-pty\lib\index.js:26:12)
    at Session (C:\Users\ray\AppData\Local\hyper\app-1.4.3\resources\app.asar\session.js:45:18)
    at initSession (C:\Users\ray\AppData\Local\hyper\app-1.4.3\resources\app.asar\ui\window.js:90:23)
    at Server.Window.rpc.on.options (C:\Users\ray\AppData\Local\hyper\app-1.4.3\resources\app.asar\ui\window.js:93:7)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Server.ipcListener (C:\Users\ray\AppData\Local\hyper\app-1.4.3\resources\app.asar\rpc.js:34:11)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by chabou** [comment]
Thanks for your feedback

**Comment by Mohamed3on** [comment]
I can reproduce this, I'm using Hyper 1.4.3 on Windows 10 with oh-my-zsh (Zsh on Bash on Windows). This only happens when using Bash as the shell though, new tab works fine using CMD.

**Comment by cfjedimaster** [comment]
And it is back for me now too.

**Comment by chabou** [comment]
@cfjedimaster can you confirm that was due to open Hyper in a directory instead of the default directory ?

**Comment by cfjedimaster** [comment]
I'm away from the machine where the issue is cropping up, but do you mean - what directory I was in currently in the active tab? Or where I opened Hyper? If the later, I opened it via the Start menu.

**Comment by Mohamed3on** [comment]
So, adding -p to the registry command makes 'Open Hyper here' always open in the default directory, so it's not really a fix.

**Comment by Mohamed3on** [comment]
The error message for me is quite similar:
```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Unable to start terminal process: CreateProcess failed
    at new WindowsPtyAgent (C:\Users\Mohamed\AppData\Local\hyper\app-1.4.3\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\Mohamed\AppData\Local\hyper\app-1.4.3\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:45:24)
    at spawn (C:\Users\Mohamed\AppData\Local\hyper\app-1.4.3\resources\app.asar\node_modules\node-pty\lib\index.js:26:12)
    at Session (C:\Users\Mohamed\AppData\Local\hyper\app-1.4.3\resources\app.asar\session.js:45:18)
    at initSession (C:\Users\Mohamed\AppData\Local\hyper\app-1.4.3\resources\app.asar\ui\window.js:90:23)
    at Server.Window.rpc.on.options (C:\Users\Mohamed\AppData\Local\hyper\app-1.4.3\resources\app.asar\ui\window.js:93:7)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Server.ipcListener (C:\Users\Mohamed\AppData\Local\hyper\app-1.4.3\resources\app.asar\rpc.js:34:11)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
```
Setup and reproduction:
Hyper 1.4.3
Windows 10
Bash on Windows as shell (with zsh)
Open hyper in directory then open a new tab.

**Comment by Mohamed3on** [comment]
Update: The issue just happened to me with a cmd shell that's been open for a while too, and I had to close/reopen it.

**Comment by cakenggt** [comment]
This is also happening with me. Same error message and trace as above.

Setup and reproduction:
Hyper 1.4.4
Windows 7 Professional
Empty shell property in `.hyper.js` with `['--login']` as shellArgs
Open hyper from start menu

**Comment by johnwebbcole** [comment]
Getting the same error when trying to split the view or open a new tab:

      Hyper 1.4.4
      Electron 1.7.6
      win32 x64 10.0.15063

My shell is git-bash

![image](https://user-images.githubusercontent.com/230922/30442211-5b339ce8-9941-11e7-996b-0173bb7d93f9.png)

**Comment by nomad3k** [comment]
I was just about to report this issue.  I can reliably reproduce it using mocha.  If I have a tab that's running `mocha --compilers js:babel-core/register src/**/*.test.js --watch --growl`.  Then when I click Split Horizontally I get the very same exception as @johnwebbcole above.

**Comment by luukverhoeven** [comment]
When opening a new tab from menu or shortcut this error is thrown

![image](https://user-images.githubusercontent.com/995760/30535382-7288ed48-9c62-11e7-8c52-316eba85f3ac.png)

**Comment by johnwebbcole** [comment]
After @nomad3k mentioned it, I've noticed that this only happens after running a npm script.

Trying to narrow it down, whenever I run my development build `npm run dev` or build for production, this happens.  Since I'm building a large Vue app, this doesn't narrow it down, so I tried some simpler commands.

Here are steps to reproduce:
  * open hyper, create a new tab or split the view - **it works**
  * install vue-cli `npm install -g vue-cli`
  * open a new tab or split the view - **it fails**

If you already have `vue-cli` installed, reproduce this way:
  * open hyper, create a new tab or split the view - **it works**
  * `vue init simple somenewproject
  * `cd somenewproject`
  * `npm i`
  * create a new tab or split the view - **it fails**

I'm sure there are other things that trigger it, as @nomad3k used mocha, but these are my steps to reproduce on Windows 10.

**Comment by Mohamed3on** [comment]
The error is still present in 1.4.8.

**Comment by MartinMuzatko** [comment]
Yep. Happens with new tab, splits etc.

**Comment by MartinMuzatko** [comment]
I got some more information.
After resetting my .zshrc and .hyper.js file, everything works fine!
I think the SSH-agent was the problem.

**Comment by Mohamed3on** [comment]
@MartinMuzatko Hmm, but the error happens even if I use CMD as the shell.

**Comment by MartinMuzatko** [comment]
Now the problem only happens when splitting while running an NPM command or after that.

**Comment by FlorianDewulf** [comment]
I doesn't happen when it's a new window but if I do something in the term, I always have the error if I want to split vertically / open a new tab.
It's very annoying, it should be a priority imo, but it's been more than a month now :(

**Comment by pattacini** [comment]
I agree it's somewhat annoying. Tabbing and splitting are practically unusable.
I was enthusiastic to leave `Console2` in favor of `hyper` on my Windows and I'm trying hard to resist the urge to go back in the hope that this bug will be sorted out very soon 😉

**Comment by cakenggt** [comment]
I don't use npm commands very often at all, and it happens to me if I try to make a new tab when the hyper console opens (it opens at my C:\Users\username folder). However, if I cd into another directory, I can make a new tab. Additionally, if I run a .bat script, I can't create a new tab anymore.

**Comment by Radiergummi** [comment]
After taking some hints from the comments, I removed the `hypercwd` plugin which seems to have solved this issue for me.

**Comment by pattacini** [comment]
@Radiergummi that's correct; it worked also for me.

**Comment by cfjedimaster** [comment]
Seems to work for me too. Still needs an official fix imo.

**Comment by johnwebbcole** [comment]
Same here, removing hypercwd fixes it

**Comment by lsuarez-tiempo-dev** [comment]
I really wanted this to work ,  Hope it get's fixed soon . 
I'm not sure what adding -p to the registry means. could somebody elaborate please?

**Comment by ivictbor** [comment]
Just installed fresh hyper. Opening new tab was working for me before I added `hypercwd`. Now it shows mentioned error.

**Comment by janat08** [comment]
how to remove hypercwd?

**Comment by Stanzilla** [comment]
@janat08 remove it from your `.hyper.js` plugins section

**Comment by janat08** [comment]
would be nice if they would've reversed the deletion/comment once fixing it.

**Comment by thisisalessandro** [comment]
Still dealing with this :-/

**Comment by imdario** [comment]
Confirmed, it's hypercwd's fault if you create a new tab while connected to a remote SSH server (at least, for me).

@janat08 (and anyone who stumbles in this issue while looking for the error): type "hyper u hypercwd" in your hyper shell and it will be gone.

**Comment by franciscobern** [comment]
Perfect "hypercwd" removed, fixes it.

**Comment by dazrave** [comment]
Removing `hypercwd` worked for me also.

**Comment by Radiergummi** [comment]
Would everyone mind just using the +1 reaction instead of adding new "me too" comments? There's a lot of people involved in this thread that get useless notifications while they wait for an official fix. Thanks guys.

**Comment by giggio** [comment]
This is the related hypercwd error: https://github.com/hharnisc/hypercwd/issues/51
This issue should be closed and locked. There is nothing else to do here.

**Comment by Michkail** [comment]
to remove hypercwd, u can use "hyper uninstall hypercwd" or remove from .hyper.js, if u confuse, u can click on the top of left -> tab "edit" -> tab "preference"

**Comment by naman9199** [comment]
After removing the "hypercwd" terminal works fine. However, opening a new tab takes me to the home directory. I am unable to decide between two options because both of these functions are necessary developers.
