### ISSUE TITLE
Bug report - Unknown bug

### ISSUE THREAD

**Issue by duytrung** [zeit/hyper#2177]
Hi!

- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.3 Stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Startup display a message:

![image](https://user-images.githubusercontent.com/2046672/30090534-3edcf610-92f3-11e7-8192-0a883752530f.png)

**Comment by CodeTheory** [comment]
@duytrung It says that the error originates in the `.hyper.js` file. Can you paste its contents here please?

**Comment by mdonlan** [comment]
@CodeTheory I just had this issue as well and the solution to #1996 worked for me. When you click preferences it tries to open the .js file but if there is not a system default it will fail. There is a check for this at the bottom of /app/config/open.js that tries to prevent this but it doesn't seem to be working.

`  module.exports = () => hasDefaultSet()
    .then(yes => {
      if (yes) {
        return shell.openItem(cfgPath);
      }
      console.warn('No default app set for .js files, using notepad.exe fallback');
      return openNotepad(cfgPath);
    })
    .catch(err => {
      console.error('Open config with default app error:', err);
      return openNotepad(cfgPath);
    });`

**Comment by CodeTheory** [comment]
Thanks @mdonlan. Closing this as a duplicate in that case!
