### ISSUE TITLE
Create a Contribute.md file

### ISSUE THREAD

**Issue by Lavanaya** [zeit/hyper#2187]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

Contribute.md file is not present in github code repository of hyper. All related matter is present in readme file. Kindly make a separate Contribute.md

**Comment by chabou** [comment]
There isn't a lot of thing about contributing and I think it is better to have it directly in README.

Btw, your contriubtions will be very welcome do not hesitate to search `Good for beginners` issues.
