### ISSUE TITLE
[xterm] Vertical split panes don't work well with Fish

### ISSUE THREAD

**Issue by UltCombo** [zeit/hyper#2190]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu GNOME 16.04
- **Hyper.app version**: 1.4.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/UltCombo/e5d06a11401cf69f7268480e9ef54cc8
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: Nothing unexpected.
- **The issue is reproducible in vanilla Hyper.app**: No, it's specific to the xterm branch.

## Issue

When using Fish shell with the xterm branch build, vertical split panes appear to be rendered off-screen. Upon closing the visible pane, it reveals the split pane with the following console output:

```
Welcome to fish, the friendly interactive shell
<W> fish: Current terminal parameters set terminal size to unreasonable value.
<W> fish: Defaulting terminal size to 80x24.
```

**Comment by chabou** [comment]
Yes, this is the last known problem. It doesn't related to fish.
For now, terms can't be vertically reduced (which is necessary to have an horitzontal split)

Thank you to have tested this branch and for your feedback.

**Comment by chabou** [comment]
Fixed in `xterm` branch 🎉

**Comment by UltCombo** [comment]
Nice!! Awesome, thanks. 😄
