### ISSUE TITLE
Keymap definition must not require ordered keys

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2195]
For now, keymap definition should be ordered to be matched:
https://github.com/zeit/hyper/blob/48f5b6e08fac1a768d721a3b31f19693ffe0d65a/lib/utils/keymaps.js#L5-L34

If a shortcut definition has an other order than `cmd` -> `ctrl` -> `shift` -> `alt` -> `other key`. It won't work.

We should normalize keymaps internal and normalize keys in the same way before comparing.
Maybe something like: `key.split('+').sort().join('+)`?

**Comment by wilsontayar** [comment]
Hi @chabou, are you currently working on this? 
I can send a PR soon.
