### ISSUE TITLE
Syntax Error: Use of const in strict modem (Linux)

### ISSUE THREAD

**Issue by breescorner** [zeit/hyper#2197]
Ubuntu 14.04
Hyper v. 1.43 64bit
[Gist](https://gist.github.com/breescorner/f3689a8a1a05207e4326948b3507118b) 
issue is reproducible in vanilla Hyper.app: YES
## Issue

Not sure what this means:

`/usr/lib/node_modules/hpm-cli/index.js:3 const fs = require('fs') ^^^^^ SyntaxError: Use of const in strict mode.     at Module._compile (module.js:439:25)     at Object.Module._extensions..js (module.js:474:10)     at Module.load (module.js:356:32)     at Function.Module._load (module.js:312:12)     at Function.Module.runMain (module.js:497:10)     at startup (node.js:119:16)     at node.js:935:3`

**Comment by CodeTheory** [comment]
Looks like this is an issue with [hpm](https://github.com/zeit/hpm). cc @matheuss @chabou 

In what context does this error occur @breescorner?

**Comment by breescorner** [comment]
It seems like it's always when I try to issue a command with npm and hpm.
