### ISSUE TITLE
npmRegistry is beign ignored

### ISSUE THREAD

**Issue by danielo515** [zeit/hyper#2198]
-  [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Hyper.app version**:         Hyper 1.4.3
- **Electron**: 1.7.5
- **OS version and name**:        darwin x64 16.7.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/danielo515/74316bd5946db3ff7b89a7eed18116a3

- **The issue is reproducible in vanilla Hyper.app**: I guess

## Issue

I use a private npm registry on my laptop. Checking the logs of plugins installation I can see that it is failing because it is trying to use the npm private registry and fails with an authentication error (not sure why because I can install any npm package from the console because I'm actually logged in). So I tried to override the npm registry on the hyper configuration. After changing it and a couple of restarts (even totally closing hyper) it stills trying to reach my private npm registry.
They only way I make this work was creating an .npmrc file manually on the plugins directory

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
