### ISSUE TITLE
Copy/paste directory path

### ISSUE THREAD

**Issue by jq-87** [zeit/hyper#2199]
- **OS version and name**: 10.12.5 - MacOS Sierra
- **Hyper.app version**: 1.4.3

## Issue
In iterm2 I am able to copy a directory and paste into iterm2 to get the full path.
This does not seem to work in Hyper.

BUT if i drag a directory into Hyper I DO get the full path.

Would be nice if copy/paste worked - getting the path that way is faster for me.

**Comment by CodeTheory** [comment]
Hi. Thanks for the report.

Is this the same issue as #1285? 
If it is, would you mind if I closed this issue a duplicate and directed you over there?

**Comment by jq-87** [comment]
I'll close this - somehow i missed that item.
