### ISSUE TITLE
Hyper.js crashes on Windows with shell set to PowerShell

### ISSUE THREAD

**Issue by MattHoneycutt** [zeit/hyper#2200]
This is a new bug for me since upgrading to 1.4.4.  

With the shell set to Powershell, launching Hyper.js will exit immediately after launching.  It looks it's passing "--login" to "powershell.exe" even though I've cleared my shellArgs config setting, which causes PowerShell to error out. 

It looks like, in 1.4.4, if shellArgs === [], it defaults back to ['--login']. 

Doing "shellArgs: ['']" resolves the issue.

        -
        Hyper 1.4.4
        Electron 1.7.6
        win32 x64 10.0.15063

**Comment by chabou** [comment]
Thank you so much for your feedback.
This is a regression due to https://github.com/zeit/hyper/pull/2126

We will fix ASAP

**Comment by MattHoneycutt** [comment]
No problem!

**Comment by iamdevlinph** [comment]
Doesn't seem to help in the case of `wsl.exe`
