### ISSUE TITLE
Dragging window while maximized in Windows 10 doesn't reset maximized status

### ISSUE THREAD

**Issue by axelitus** [zeit/hyper#2203]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 version 1703
- **Hyper.app version**: 1.4.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/axelitus/742ad5ce3359b9c22bba547ca2b1f8ed
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
When Hyper is maximized and one drags the window to move it, the normal behavior is that the window gets "restored" (looses the maximized status). This does not happen for Hyper.

The Hyper window gets moved to the new coordinates, but the window is still "maximized".
![2017-09-13_16h35_39](https://user-images.githubusercontent.com/732441/30401929-98d00b22-98a1-11e7-8da4-dd500c137584.png)

So dragging the window again and trying to "attach" to the Windows sweet spots does not work (because it is already maximized). The "restore" button must be clicked and then the maximize button again.

What should happen is that when Hyper get's dragged, the "restored" window status should be set.

**Comment by wilsontayar** [comment]
Hmm... For me everything is working as expected.
By looking at your .hyper.js file it seems that you are using some plugins.
Do you mind testing this without them?

I guess this code takes care of that: 
https://github.com/zeit/hyper/blob/master/app/ui/window.js#L154

For reference, here's my vanilla hyper:
![maximized_hyper](https://user-images.githubusercontent.com/5078285/30506884-e239ec14-9a55-11e7-8d26-5fa05e9a7a67.gif)

**Comment by chabou** [comment]
cc @axelitus

**Comment by axelitus** [comment]
I'll reset the hyper.js file, but I need to do this on monday to do this on the same computer.

In my laptop that I'm currently on it works as expected, exactly as @wilsontayar image (I'm using latest version 1.4.6 here though).

**Comment by axelitus** [comment]
Indeed I can confirm this is happening due to a plugin installed. I removed my `hyper.js` config file and started with a clean one and it's working flawlessly. I'm going to try and pinpoint which one of the plugins caused this issue, but for now, I'll close this as it's obviously not Hyper's issue. Thanks, @wilsontayar and @chabou!

**Comment by axelitus** [comment]
It seems the plugin 'hyper-tabs-enhanced' was causing all of my issues (#2094, #2095 and this one). I have removed that plugin and now it's working fine. This is my new [hyper.js file](https://gist.github.com/axelitus/bfaf0e82fa07eb7677d80261aba428db).
