### ISSUE TITLE
Error on launch Windows 10 clean install

### ISSUE THREAD

**Issue by fmontes** [zeit/hyper#2205]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/fmontes/f3d2e2c2d69cbf37ad917b5fc487dc74
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Vanilla
## Issue
I've been getting this error on my Surface Pro with Windows 10 since version 1.X I tried everything and no luck:

![2o20s9](https://user-images.githubusercontent.com/751424/30411762-5d2d3534-98d0-11e7-926c-9640795f0b85.png)

**Comment by chabou** [comment]
Please remove your `.hyper.js` config file located in your home and retry.

**Comment by fmontes** [comment]
@chabou that did the trick, thank you very much.
