### ISSUE TITLE
Reset config file (~/.hyper.js)

### ISSUE THREAD

**Issue by DaWeirdBeard** [zeit/hyper#2211]
Hi
Is there any way to reset the config file (~/.hyper.js) to the defaults from when I downloaded it?

**Comment by albinekb** [comment]
Yep just delete the file `rm ~/.hyper.js` and restart Hyper 🎉  @DaWeirdBeard

**Comment by ayushbahuguna** [comment]
Thanks it worked..:-))

**Comment by Dev-Gandhi** [comment]
thanks it worked.

**Comment by ledlamp** [comment]
well I deleted .hyper.js but now i cant start hyper :confused:
![](https://o66s.qonq.gq)

i guess ill just have to manually copy and paste it from https://github.com/zeit/hyper/blob/canary/app/config/config-default.js

**Comment by ledlamp** [comment]
whoop; configuration file is actually in `C:\Users\me\AppData\Roaming\Hyper` on windows

**Comment by afzaalnazir9** [comment]
it worked thanks

**Comment by rascode** [comment]
Had the same issue and resolved it by removing the malformed config file by running `rm ~/.hyper.js`.  Restarted Hyper and presto!

Really think this error should be more specific.  Sure there are others out there pulling their hair out over this.

**Comment by abhijithabhiakl** [comment]
thanks a lot, that worked

**Comment by arvind-kumar-avinash** [comment]
Thank you. It worked.

**Comment by gianargamosa** [comment]
It should be `rm $Env:AppData/Hyper/.hyper.js` on windows.
