### ISSUE TITLE
Automatic choco update

### ISSUE THREAD

**Issue by chantisnake** [zeit/hyper#2212]
Moves from pull request #1631 .

Hi, I am the maintainer of chocolatey package of hyper.

I have an update script at chocolateyPackage: https://github.com/chantisnake/chocolateyPackage/blob/master/UpdateScript.ps1

This script uses my powershell package: [github2choco](https://github.com/chantisnake/github2choco)

If you have someone good at powershell in your development team, I would love to assist you guys to create your own automation script.

If you guys cannot take over the choco package, I will still love to maintain the choco package, but I cannot guarantee that the choco package will be up-to-date all the time.

**Comment by wilsontayar** [comment]
I might be able to help here. 
I did some research and it seems we need to create another repository and find a way to run the ps1 file in AppVeyor on every release... Is this correct? :)

**Comment by chantisnake** [comment]
I don't really think you need another repo.

If you want you can put a folder in your current repo with the update script and package.

**Comment by albinekb** [comment]
Sounds like an awesome plan 👍

**Comment by Stanzilla** [comment]
Pull Requests welcome :)
