### ISSUE TITLE
Context menu always opening on root directory

### ISSUE THREAD

**Issue by manojmkhanna** [zeit/hyper#2214]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/manojkhannakm/59c059cc1b6654159bfbbce7f3ed14a1
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I'm using Zsh on Windows 10. Up until 1.4.3 the context menu "Open Hyper here" was opening on the correct directory but after 1.4.4 its always opening on the root directory.

**Comment by aotik** [comment]
Same issue here, couldn't find a fix with Regedit either.

**Comment by manojkhannakm** [comment]
@chabou After updating to 2.0.2, its working fine on folders but not on drives like C: or D:

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2369
