### ISSUE TITLE
Downloads are failing

### ISSUE THREAD

**Issue by apmeyer** [zeit/hyper#2215]
Might be a temporary issue, but the Mac download from https://hyper.is is failing. Installing via brew is also failing.

```
curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection refused
Error: Download failed on Cask 'hyper' with message: Download failed: https://github.com/zeit/hyper/releases/download/1.4.4/hyper-1.4.4-mac.zip
Error: Install incomplete.
```

![screen shot 2017-09-15 at 8 57 11 pm](https://user-images.githubusercontent.com/482635/30508269-780e378e-9a58-11e7-9a2c-1c88af6b6fe0.png)

**Comment by chabou** [comment]
Thank you for your feedback.
It seems to be a temporary issue. Works great now.

**Comment by apmeyer** [comment]
Actually, it's still failing for me through brew and through direct download on the website. Same error messages as above. Maybe a regional/CDN thing?
