### ISSUE TITLE
Setup Hyper.js by default on OS X 

### ISSUE THREAD

**Issue by Yourdigitalheart** [zeit/hyper#2216]
Hello I am trying to setup Hyper.js by default on OS X 10.12.6. I am trying many app Magic launch and a bash script Nothing works for me.

Someone has an idea?

**Comment by chabou** [comment]
> by default

What do you mean?

**Comment by Insidebox** [comment]
I mean when for example: If  I open one ssh connection from digital ocean or other its my old terminal by default. I Want Hyper.js for all . 
![screen shot 2017-09-17 at 7 21 31 pm](https://user-images.githubusercontent.com/23500739/30520727-2dc71f24-9bde-11e7-9697-17df6ae95f67.png)
![screen shot 2017-09-17 at 7 21 46 pm](https://user-images.githubusercontent.com/23500739/30520729-2e74b0c6-9bde-11e7-8dce-552d4792cd07.png)
![screen shot 2017-09-17 at 7 21 53 pm](https://user-images.githubusercontent.com/23500739/30520728-2e502026-9bde-11e7-9f7c-c38506018b1a.png)
Thanks

**Comment by Stanzilla** [comment]
So you want hyper to register as a url handler for ssh?

**Comment by ZakTaccardi** [comment]
Yes - how can I get the OS (mac) to use `Hyper.app` instead of `Terminal.app` by default?

**Comment by iwd-sys** [comment]
Try http://www.rubicode.com/Software/RCDefaultApp/

**Comment by chabou** [comment]
This is now possible with our canary (upcoming v2). Thanks to: https://github.com/zeit/hyper/pull/2516

**Comment by ZakTaccardi** [comment]
@chabou can we get a better guide on how to enable hyper.js to be the default terminal app?

**Comment by nazmifeeroz** [comment]
I was googling on this but couldn't find a proper answer. I finally figured it out myself. Hope this will help.

There isn't a way in MacOS system preferences to configure the default app for terminal `.command` files. 

The trick here is to create a `.command` file and set the app default for that file extension to be the `hyper` app.

1. Create a `.command` file in your hyper/item/terminal
![image](https://user-images.githubusercontent.com/26022852/54402550-61a42000-4707-11e9-80ae-e574b9c6f2f5.png)

I'm using Vim to create and edit the file. You may use the `touch` prompt

2. Open the folder in finder
![image](https://user-images.githubusercontent.com/26022852/54402587-83050c00-4707-11e9-8aac-f2ff84ae0c4d.png)

3.  Right click on the file and click on Get Info
![image](https://user-images.githubusercontent.com/26022852/54402692-e1ca8580-4707-11e9-9987-cb2ecd830ae9.png)

4. Under the Get Info tab, change to Hyper app (dropdown > others > enable all applications)
![image](https://user-images.githubusercontent.com/26022852/54402743-222a0380-4708-11e9-8bfe-019cad16fa03.png)

5. After selecting the hyper app, be sure to click on Change All under the Get Info tab.

Now hyper app is set as default on OS X!

**Comment by romulobastos** [comment]
Works fine, here! Thank you :)

**Comment by Skarf4U** [comment]
@nazmifeeroz What Theme / Plugin do you using?
Your Terminal looks very nice!

**Comment by nazmifeeroz** [comment]
@Skarf4U 
thanks. i used zsh with powerline to configure my terminal. i have a repo with steps you can follow, https://github.com/nazmifeeroz/zshrc-config
