### ISSUE TITLE
watchFile() requires a listener function error

### ISSUE THREAD

**Issue by vblinden** [zeit/hyper#2218]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows [Version 10.0.15063]
- **Hyper.app version**: 1.4.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/vblinden/dc82be27a6102cd03b241ee46b737a26
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  Hyper does not open.
- **The issue is reproducible in vanilla Hyper.app**: I think so, I never changed settings or installed plugins (for except maybe font-size).

## Issue

When I try to open Hyper, it gives me the following error: 

![capture](https://user-images.githubusercontent.com/1420356/30512284-284dc52c-9aec-11e7-98b6-ce6332fbc373.PNG)

I am running node version 8.4.0. Hyper doesn't open. It just gives the error and when I press OK, everything closes.

**Comment by Vigilante13** [comment]
Same problem for me

**Comment by TimothyCole** [comment]
Same problem, Same version.
Was working 20 minutes ago but stopped after I restarted for the update.

My Config: https://gist.github.com/TimothyCole/a1595328f8cd6edfce13d09d9d8c86a8

**Comment by mikewesthad** [comment]
Ditto for me with Windows 10 and hyper 1.4.5. You can install 1.4.4 and get it working again... but there's no way to disable auto-update (afaik) so things will get borked again within a few minutes when auto-update kicks in.

**Comment by CodeTheory** [comment]
We're on it. Thanks for the reports!

**Comment by chabou** [comment]
v1.4.5 has been disabled.

**Comment by mikewesthad** [comment]
Confirmed that it's working if I reinstall 1.4.4 again. Thanks for that quick fix! It's always a jarring transition to have to go back to regular old cmd or git bash...

**Comment by chabou** [comment]
Fixed by [v1.4.6](https://github.com/zeit/hyper/releases/tag/1.4.6).
Sorry for the trouble.
