### ISSUE TITLE
About Chinese font problem

### ISSUE THREAD

**Issue by kanting** [zeit/hyper#2221]
-
        Hyper 1.4.3
        Electron 1.7.5
        Chinese fonts spacing is too narrow ,but English fonts don't this problem.
        Could you tell me how to correct hyper.js file fixing it ？

**Comment by chabou** [comment]
Google translate:
> 中文文字左右间距变小，造成文字重叠，英文字体没有这种情况

"Chinese text left and right spacing becomes smaller, resulting in overlapping text, English font does not have this situation"

I think this duplicates #2124 
@kanting Can you confirm me that I've understood your issue?

**Comment by kanting** [comment]
Yeah, the translation is right, I have the same problem about the issue #2124.

**Comment by CodeTheory** [comment]
I think then we should close this as a duplicate. Thanks for confirming the report though!
