### ISSUE TITLE
Does not support Chinese input

### ISSUE THREAD

**Issue by sanonz** [zeit/hyper#2228]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS X
- **Hyper.app version**: 10.12.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
When I use the Chinese input method in the terminal, the input to the terminal is the English alphabet, and these English letters can not be deleted and operated.

**Comment by Val-istar-Guo** [comment]
![2017-11-25 21 36 26](https://user-images.githubusercontent.com/12405937/33231024-ebeabe68-d228-11e7-8aef-72705932baae.gif)

when i input chinese, only get some letters T_T

**Comment by Chen-Hu** [comment]
same on windows 10

**Comment by Val-istar-Guo** [comment]
This problem seems to be fixed in 2.0.0-canary.8 version

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2322
