### ISSUE TITLE
Close tab with middle click does not seem to work on MacOS (possible regression)

### ISSUE THREAD

**Issue by xeroxoid** [zeit/hyper#2230]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra 10.12.6
- **Hyper.app version**: 1.4.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/xeroxoid/7d97ee14893e6efb611492569fce97a8
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
As the title suggests, middle-clicking with a mouse on an open tab does not do anything.
Expected: close the tab as per https://github.com/zeit/hyper/pull/286 and https://github.com/zeit/hyper/issues/117

**Comment by jonaswindey** [comment]
I can confirm this issue still exists even on `2.0.4` (pre-release)

**Comment by borela** [comment]
Not working on Windows 10 too, hyper 2.0.0.

**Comment by gilad215** [comment]
Any news on this? Deal breaker for me.

**Comment by chabou** [comment]
@gilad215 if this is a deal breaker for you, please help us to fix it 🙏

**Comment by parktheredcar** [comment]
Chromium doesn't trigger the click event on middle click. Bound to mouseup instead, which matches the behavior of other editors including vscode, sublime text, and webstorm. PR submitted.

**Comment by jonaswindey** [comment]
Any news on that PR? Still not working ATM
