### ISSUE TITLE
Set a different icon for canary releases

### ISSUE THREAD

**Issue by leo** [zeit/hyper#2231]
As discussed on #hyper-dev in [zeit.chat](https://zeit.chat), we want a special icon for the canary version. In turn, we need to have electron-builder pick up a different config when building those releases to ensure the new icon gets used... 😊 

I mean passing a flag (not sure which one it is) to tell electron-builder to produce a different output. And then, in CI, we would have to make it run that for canary releases.

**Comment by chabou** [comment]
Fixed by 43242cf663722377df500ac706b4c4e4b42616ad

**Comment by chabou** [comment]
Tested on Mac and Windows
