### ISSUE TITLE
Vibrancy for Windows

### ISSUE THREAD

**Issue by dreszczyk** [zeit/hyper#2232]
Can we use [this](https://github.com/arkenthera/electron-vibrancy)?

**Comment by albinekb** [comment]
Don't think so, see this comment: https://github.com/electron/electron/issues/8532#issuecomment-300715940

The repo you are linking to is older than that, when it was supported for a brief moment, then it got removed in the chrome core I believe.

I'm closing this as a duplicate, here is the main thread for vibrancy/opacity on windows: https://github.com/zeit/hyper/issues/1638

**Comment by DRSDavidSoft** [comment]
@albinekb I know this is a duplicate, but for future visitors, as a reference [this](https://github.com/23phy/electron-acrylic) could work.
