### ISSUE TITLE
Not Displaying on Windows 10

### ISSUE THREAD

**Issue by kelechifletcher** [zeit/hyper#2237]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Reinstalled Hyper 1.4.6 and the app window is not being displayed even though I can see that is running on the task manager. I originally thought it was just opening off screen, for which the typical solution is to cascade all windows... However this didn't work. When I hover over the hyper icon on my task bar or open task view, it shows that the console window is being displayed. I'm inclined to believe this is a Windows problem... but I'm not sure.

![image](https://user-images.githubusercontent.com/17681633/30658609-ea710ed6-9e00-11e7-9d3e-2f5d3169fca1.png)

![image](https://user-images.githubusercontent.com/17681633/30658650-087a9320-9e01-11e7-9b4f-cc09d373ea36.png)

![image](https://user-images.githubusercontent.com/17681633/30658812-8a466e2e-9e01-11e7-81c9-d5cdf6543639.png)

**Comment by Stanzilla** [comment]
Which Win10 version are you on? Latest release or Insider?

**Comment by kelechifletcher** [comment]
Latest release

**Comment by kelechifletcher** [comment]
This appeared to be Windows bug. I tried opening Hyper again with extended displays and it displayed on the other screen. Thanks Microsoft...

**Comment by wasabigeek** [comment]
For what it's worth, I'm having the same issue right no, can't seem to fix it...
