### ISSUE TITLE
Wrong proportions on icon in "About" window

### ISSUE THREAD

**Issue by leo** [zeit/hyper#2238]
As you can see, it's stretched:
<img width="284" alt="screen shot 2017-09-20 at 20 30 57" src="https://user-images.githubusercontent.com/6170607/30661150-5e3873b2-9e43-11e7-8c38-ed2721238a83.png">

**Comment by minachuong** [comment]
<img width="426" alt="screen shot 2017-09-22 at 2 27 36 pm" src="https://user-images.githubusercontent.com/14868216/30765008-46cf3868-9fa2-11e7-8a2a-fb71187c9354.png">
Left the original icon in the directory figuring it might be useful in the future

**Comment by leo** [comment]
@minachuong What exactly do you mean? How did you do this? cc @evilrabbit

**Comment by minachuong** [comment]
@leo I added a file in the static directory that was a png that had square dimensions of 96x96. The original icon was 87x76. Looks like whatever is handling the icon in the dialog box stretches the image if the image does not have square dimensions
