### ISSUE TITLE
[v2] macOS Unicode input not working

### ISSUE THREAD

**Issue by remmythical** [zeit/hyper#2239]
- [x] I am on the [2.0.0 prerelease](https://github.com/zeit/hyper/releases/tag/2.0.0) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra (10.12.6)
- **Hyper.app version**: 2.0.0
- **The issue is reproducible in vanilla Hyper.app**: yep

## Issue

Since v2 the macOS systemwide unicode input is not working anymore. It is used to type emoji and all other kinds of symbols.
Reproduce: 
1. Open the unicode input (ctrl-cmd-space or Edit -> "Emoji & Symbols" in the menu bar).
2. The input will open in the bottom left corner of the screen (rather than beyond the cursor where it should be)
3. Clicking on any symbol has no effect.

I guess this is because of the change from hterm to xterm.js. [When you search for "mac input" in this repo](https://github.com/zeit/hyper/search?q=mac+input&type=Code&utf8=%E2%9C%93) you'll find a comment on macOS emojis in hterm.js that could be related.

**Comment by chabou** [comment]
Thank you for your feedback 🙏

**Comment by albinekb** [comment]
I got a plugin that you can use as a workaround: https://github.com/albinekb/hyper-emoji, cross platform

**Comment by petarmihaylov** [comment]
This effect extends past emojis. Cyrillic  and other Unicode characters are pasted as their raw symbols:

¼ is displayed as:  <00c2><00bc>
µ is displayed as: <00c2><00b5>

**Comment by mbbroberg** [comment]
👋 Still a challenge. Please ping me if you have a proposed fix you want tested. I'm loving Hype and close to having it as my default terminal, but I like emojis too much to skip out on this one 😄
