### ISSUE TITLE
[v2] Term is black & white if colors aren't configured

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2240]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue
If `colors`are not configured in config file or if a plugin partially replace them, no default color is applied.

**Comment by albinekb** [comment]
This is fixed? @chabou

**Comment by lucasqueiroz** [comment]
Not sure if someone already opened an issue for this, or if this is related to this one, but I don't wanna open a new issue about colors... Theme colors are kinda "white"...

**Comment by chabou** [comment]
yes fixed
