### ISSUE TITLE
Error while installing a plugin

### ISSUE THREAD

**Issue by omarmhaimdat** [zeit/hyper#2243]
<img width="532" alt="screen shot 2017-09-20 at 11 27 33 pm" src="https://user-images.githubusercontent.com/2160742/30671365-6e5e5ffc-9e5e-11e7-9caf-f5a410b12542.png">
        

## How I got this problem:

I installed hyper a couple of days ago, installed some themes, changed the shell, and then worked with it without any bug or glitch and not even some lag. Worked just perfectly!

And then figured I could add some cool plugins, so I added some, and then I guess I restarted hyper because of an update, and then suddenly every time I installed a new plugin (via hpm), I got the pop-up box (ScreenShot above).

- OS Version 10.12.6
- MacBook Pro 2.3 GHz Intel Core I7 | 16GB
- Hyper 1.4.7
- Electron 1.7.6
- darwin x64 16.7.0

**Link of a Gist with the contents of the .hyper.js:** https://gist.github.com/omarmhaimdat/0aa32ff5f9455303a0b1f1eb79cacc77

**Comment by MAPESO** [comment]
@albinekb  @CodeTheory  **hpm** will have to investigate because it is causing errors in stable and canary versions. I'll see if I can correct this problem.

**Comment by MAPESO** [comment]
@omarmhaimdat  If you are going to customize Hyper I recommend you do it through the **hyper.js** file 😄

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by omarmhaimdat** [comment]
I think the problem has been solved, Good Job \

--------------
Omar MHAIMDAT
