### ISSUE TITLE
HyperPower plugin not working in 2.0.2

### ISSUE THREAD

**Issue by 1412321** [zeit/hyper#2245]
I just updated to Hyper version 2.0.2. And HyperPower isn't working anymore. It still working if I changed back to version 1.4.6

**Comment by albinekb** [comment]
We need more information here to know if this is a bug with Hyper or HyperPower itself, most likely HyperPower will need to be updated to work with `xterm`

**Comment by 1412321** [comment]
#### Still not working with version 2.0.3
I just updated to 2.0.3 and it's still not working.
I use `hpm` to install **hyperpower** and get this error

**A JavaScript error occurred in the main process**
```
Uncaught Exception:
Error: Error reading configuration: `module.exports` not set
    at _extract (/opt/Hyper/resources/app.asar/config/init.js:8:11)
    at _init (/opt/Hyper/resources/app.asar/config/init.js:31:18)
    at exports._import (/opt/Hyper/resources/app.asar/config/import.js:43:15)
    at FSWatcher.onChange (/opt/Hyper/resources/app.asar/config.js:18:11)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:194:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1392:12)
```

**Comment by viktor-evdokimov** [comment]
I have the same issue on 2.0.3

**Comment by MAPESO** [comment]
@1412321 @albinekb  if you are using the stable version of hyper (1.4.7) I recommend that you add the hyperpower plugin in the hyper.js file

hpm causes a bug with hyperpower, and in version 2.0.3 does not work.

**Comment by balazsorban44** [comment]
I have the same issue!

**Comment by MAPESO** [comment]
@balazsorban44 which problem you have?

**Comment by balazsorban44** [comment]
Hyperpower plugin not working in v2.0.x versions of Hyper. Although almost all the plugins seem to be broken for me at least. There is not a single one which works as before.

**Comment by MAPESO** [comment]
@balazsorban44 We made a change in the *Hyper core* that causes problems with some add-ons we are working to solve that problem. For the moment, I recommend that you move to the stable version 😸

**Comment by Stanzilla** [comment]
HyperPower is no compatible with Hyper v2, see https://github.com/zeit/hyperpower/releases/tag/1.0.0
