### ISSUE TITLE
[v2] Switching tabs using cmd/ctrl + 1 / 2 / 3 / etc

### ISSUE THREAD

**Issue by timneutkens** [zeit/hyper#2247]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue

In v2 it's not possible to switch tabs using cmd/ctrl + 1 / 2 / 3 / etc

**Comment by h93xV2** [comment]
Have you tried replicating this behavior with dev tools open?

For what it's worth, these commands work fine on my current system.

**Comment by timneutkens** [comment]
@h93xV2 yep I did try all cases, @chabou mentioned he knows what's causing it, so he'll have a look 👍

**Comment by oliverjam** [comment]
I have the same issue on Canary (macOS Sierra). The shortcuts were working fine before updating to Canary. Seems related to #2279

**Comment by chabou** [comment]
@oliverjam What is your keyboard layout?
It should be definelty fixed in v2.1.0 canary 🤔 
What is your canary version?

**Comment by timneutkens** [comment]
@chabou It's indeed fixed 👌

**Comment by oliverjam** [comment]
@chabou Apologies, for some reason my Hyper was out-of-date. Just manually updated and this is fixed 👍
