### ISSUE TITLE
Save and restore window size after restart

### ISSUE THREAD

**Issue by someanon** [zeit/hyper#2249]
- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/someanon/e45a11f297f38882cc3eac5c9053d2af
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: resize to needed size, maximize, close hyper, open hyper

## Issue
If hyper closed in maximized state after restart it doesn't restore the common size. Istead it restores maximized size (as it was common) but not maximized state and shifted bottom-right a little from top-left screen corner.

I think hyper should start maximized state if it closed so. And it should save and restore common size after maximized close, so if i minimize maximized window after restart it would become common size before restart.

Maybe it would be better to make optional parameter in .hyper.js for window size of any new hyper windows and option for start maximized if it closed so before.

**Comment by bernardoleite** [comment]
I believe this has been fixed already in canary.

**Comment by albinekb** [comment]
Hi! Can you try canary and see if the new behaviour is what you're expecting. To learn how to try out canary, see https://zeit.co/blog/canary

We're working on getting all of the great changes and improvements released to the stable channel ASAP.

**Comment by someanon** [comment]
Not fixed in 2.0.0-canary.8 in windows 10. May be i need to adjust some settings?

**Comment by Stanzilla** [comment]
Follow here https://github.com/zeit/hyper/pull/2382

**Comment by someanon** [comment]
So i need to wait merge?

**Comment by Stanzilla** [comment]
Yes!
