### ISSUE TITLE
[v2] Some Mac keystrokes (delete-word, jump-to-beginning, etc) don't work anymore

### ISSUE THREAD

**Issue by luisherranz** [zeit/hyper#2251]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX 10.11.3 
- **Hyper.app version**: 2.0.2
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

On all OSX text editors:

- Cmd+LeftArrow and Cmd+RightArrow jump to the beginning and end of the line.
- Cmd+BackSpace delete the entire line.
- Alt+Backspace delete the previous word.

That used to work on Hyper 1, but it doesn't work on Hyper 2 anymore.

The only thing which is still working is:

- Alt+LeftArrow and Alt+RightArrow jump to the next or previous word.

**Comment by Moeriki** [comment]
Same on 2.0.3.

Also CMD + SHIFT + LEFT / RIGHT to switch tabs. And if you use `hyperterm-tabs` re-ordering tabs also stopped working with shortcut.

**Comment by qkdreyer** [comment]
Any updates for this issue ? (see also https://github.com/zeit/hyper/issues/1361)

**Comment by chabou** [comment]
Fixed in canary branch with: https://github.com/zeit/hyper/pull/2426
It will be landed in next canary release

**Comment by bboure** [comment]
thanks @chabou

**Comment by saamalik** [comment]
What about these keystrokes: `alt+b` jump backwards, `alt+f` to jump forward, `alt+.`, etc? 

These don't seem to work on the latest canary build. Using Mac OSX--and I did also try it with `modifierKeys: { altIsMeta: true }` in `.hyper.js` but no bueno.

**Comment by Stanzilla** [comment]
@saamalik can you try again with the latest version and if it is still broken, create a new issue please?

**Comment by saamalik** [comment]
@Stanzilla tried on Canary 9. Opened up #2578 to track. Thanks!
