### ISSUE TITLE
Window sizing issues with multiple tabs on 2.0.2

### ISSUE THREAD

**Issue by richsilv** [zeit/hyper#2252]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version | **I'm on v2.0.2**
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.04
- **Hyper.app version**: 2.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/richsilv/d462c71e9089f7c25aeb36cb4aaa49cc
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue
I've observed two separate issues with tab sizing in version 2.0.2:

* Opening a new (second or more) tab does not correctly resize the embedded terminal to fill the available space, leaving it occupying only a portion in the top left of the screen.

![screenshot from 2017-09-21 12-21-54](https://user-images.githubusercontent.com/3180526/30693431-7e7c0042-9ec7-11e7-906a-dedf3f987c2b.png)

* Resizing one open tab and then moving to another leaves the newly-opened tab blank until the page is resized.

![screenshot from 2017-09-21 12-07-43](https://user-images.githubusercontent.com/3180526/30692980-8a28498e-9ec5-11e7-8bae-d3824587ffcd.png)

**Comment by djhi** [comment]
I reproduced it on Ubuntu 16.04 too.

**Comment by dcalhoun** [comment]
I've experienced this on macOS 10.12.6 as well.

**Comment by Stanzilla** [comment]
Reproduced on Windows as well https://dl.dropboxusercontent.com/s/gmlpceuwd2i1byw/2017-11-03_22-34-18.webm

**Comment by chabou** [comment]
@Stanzilla 🤔  your video doesn't show this same bug
And I think that these bugs have been fixed by https://github.com/zeit/hyper/pull/2273 (landed in v2.0.3)

**Comment by Stanzilla** [comment]
Oh oops, true. Making a new one then.

**Comment by richsilv** [comment]
Agreed, this is fixed by #2273 - I'll close.
