### ISSUE TITLE
Option quickEdit is missing in docs

### ISSUE THREAD

**Issue by mojoaxel** [zeit/hyper#2254]
It looks to me the option **quickEdit** is [not documented](https://github.com/zeit/hyper/blob/master/website/index.html)  on the [website](https://hyper.is/#cfg). Is this intended?

**Comment by albinekb** [comment]
No, PR welcome 👍  Thanks for reporting :)

**Comment by mojoaxel** [comment]
@albinekb What about the v3 branch? Is it going to be rebased on master or do I need to create a new PR?

**Comment by albinekb** [comment]
You don't have to do a PR there, it will be rebased 👍 Most likely we will have a website refresh before that. 👌
