### ISSUE TITLE
Hyperline Plugin Not Working in v2.0.2 on Ubuntu

### ISSUE THREAD

**Issue by shindesharad71** [zeit/hyper#2255]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04.3
- **Hyper.app version**: 2.0.2

## Issue
Hyperpower and Hyperline Plugins not working

**Comment by pberden** [comment]
Same here.
OS version and name: macOS Sierra 10.12.6
Hyper.app version: 2.0.2

**Comment by albinekb** [comment]
Hyperpower is tracked here: https://github.com/zeit/hyper/issues/2245

**Comment by albinekb** [comment]
We need more information here to know if this is a bug with Hyper or Hyperline itself, most likely Hyperline will need to be updated to work with Hyper 2.0.

**Comment by lucasazevedoqx** [comment]
Same problem here with the 'hyperpower'. I believe the problem occurs because the new version (since 2.0.0) changed the html structure. I don't know how the plugin works.

**Comment by 416serg** [comment]
any updates here? 👍

**Comment by albinekb** [comment]
@416serg see https://github.com/zeit/hyper/issues/2284

**Comment by 416serg** [comment]
Hyper 1.4.7 (stable)
```
Plugins: 
  hyper-statusline (1.7.3),
  hyperterm-paste (1.1.0),
  hypercwd (1.1.1),
  hyperterm-tabs (1.3.5),
  hyper-quit (1.0.2)
```

Am I missing something? @albinekb

**Comment by albinekb** [comment]
I don't know about all of those plugins, but no, it looks allright, and hyperline should work with 1.4.7, otherwise open an issue over there 👍  @416serg   

I would also recommend you to try the plugins one by one to rule out any bad plugins

cc @henrikdahl @timneutkens

**Comment by 416serg** [comment]
With just `hyper-statusline` 😢 

I'll open up an issue there as well, hopefully it'll get resolved, thanks @albinekb!

![screen shot 2017-09-25 at 12 56 08 pm](https://user-images.githubusercontent.com/3760543/30820787-fcae6b5e-a1f0-11e7-80f8-08a7de367e39.png)

**Comment by MAPESO** [comment]
@albinekb @shindesharad71  It would be appropriate to change the title of the problem, I was checking the problem and you can install themes like plguings. **The only problem is that some are incompatible.** 😄

**Comment by Stanzilla** [comment]
Yup, please go here https://github.com/Hyperline/hyperline/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
