### ISSUE TITLE
Themes not showing any color in 2.0.1

### ISSUE THREAD

**Issue by jaredgalanis** [zeit/hyper#2256]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 26

- **Hyper.app version**: 2.0.1

- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 

https://gist.github.com/jaredgalanis/4b3d090a5ea90f9ceee115cdf33f2b32

- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
```
bundle.js:1 (re)loading renderer plugins
bundle.js:1 Plugin hyper-monokai-vibrancy (1.0.6) loaded.
index.html:35 total init time 245.73499999999999
```

- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`. 

## Issue

Any theme I try to include in the plugins section of the hyper.js file appears to be loaded (see console output above), but colors are not applied to the terminal on a full reload or a quit and restart of the application. 

Note, the node_modules in the hyper_plugins directory does contain the relevant theme file. 

This has only occurred after an update to Hyper v2.0.1.

**Comment by Stanzilla** [comment]
Duplicate of https://github.com/zeit/hyper/issues/2240?

**Comment by jaredgalanis** [comment]
I was not using 2.0.1 as I thought. The update to 2.0.1 fixed this issue for me. Thank you!
