### ISSUE TITLE
how to open hyper config file on windows 7

### ISSUE THREAD

**Issue by lZzozZl** [zeit/hyper#2257]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7 Ultimate x64
- **Hyper.app version**: 1.4.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Cannot open .hyper.js
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: ?
- **The issue is reproducible in vanilla Hyper.app**: I have NPM and GIT installed before i instal Hyper

## Issue
Sorry for my stupid question but how can i open that hyper.js config file on my windows 7 PC?

I realize that i need to open that file with some kind of editor in the terminal so i found a bat script to open my sublime text editor with command

This is the script in my bat file located in windows directory.
@start "sublime" "%ProgramW6432%\Sublime Text 2\sublime_text.exe" %*

so after i add this bat file which is called sublime.bat ive open the terminal again and write :
sublime ~/.hyper.js 

it open my sublime with tab that is called .hyper.js but nothing was written in that file.

Can someone explain what and how can i open hyper configuration file?

**Comment by Stanzilla** [comment]
Use the menu? File => Edit => Preferences

**Comment by lZzozZl** [comment]
I've got error
Script: C:\Users\User\.hyper.js
Line: 5
Char: 1
Error: 'module' is undefined
Code: 800A1391
Source: Microsoft JScript runtime error

**Comment by Stanzilla** [comment]
Use notepad instead of the script host to open it

**Comment by lZzozZl** [comment]
Thanx allot
