### ISSUE TITLE
[v2] copyOnSelect and quickEdit not working with v2

### ISSUE THREAD

**Issue by mojoaxel** [zeit/hyper#2260]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

* **OS version and name**: ubuntu linux 16.04 64x
* **Hyper.app version**: canary branch ([tag 2.0.2](0502bbfc79d5421e0a6758ea671b7bb19d76c1cb)) - both custom build and release.
* **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mojoaxel/a55766b1b6efc1f1802d1e43dab96919

## Issue
* [ ] **copyOnSelect** is not working with the current v2.0.2. Selecting a text is not copying it to the clipboard.
* [ ] **quickEdit** is not working with the current v2.0.2. It looks like right-click events are not handled at all.

**Comment by nacimgoura** [comment]
Same error.

**Comment by albinekb** [comment]
@nacimgoura, please use the reactions that github has introduced some years ago 👌 
![image](https://user-images.githubusercontent.com/5027156/30742801-2c6fe8ca-9f9b-11e7-8e16-ee4873484af1.png)

**Comment by luukverhoeven** [comment]
Same error here

**Comment by albinekb** [comment]
@luukverhoeven, please use the reactions that github has introduced some years ago 👌 
![image](https://user-images.githubusercontent.com/5027156/30742801-2c6fe8ca-9f9b-11e7-8e16-ee4873484af1.png)

**Comment by nacimgoura** [comment]
Why was the issue closed?
I still have the problem on version 2.0.4 with ubuntu 16.04.
