### ISSUE TITLE
Yarn instructions for Ubuntu 17.04

### ISSUE THREAD

**Issue by Bost** [zeit/hyper#2263]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.04
- **Hyper.app version**: e30cbac (I just cloned the repo)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

```
$ sudo apt install --yes graphicsmagick icnsutils xz-utils
# ... dependencies installed
$ yarn --version
0.27
$ ls -la # I just cloned the repo and I'm in the hyper home directory:
total 652
drwxrwxr-x  13 bost bost   4096 Sep 22 11:31 ./
drwxrwxrwx 125 bost bost   4096 Sep 22 11:18 ../
drwxrwxr-x   9 bost bost   4096 Sep 22 11:19 app/
-rw-rw-r--   1 bost bost    525 Sep 22 11:19 appveyor.yml
drwxrwxr-x   2 bost bost   4096 Sep 22 11:19 assets/
drwxrwxr-x   2 bost bost   4096 Sep 22 11:19 bin/
drwxrwxr-x   2 bost bost   4096 Sep 22 11:19 build/
-rw-rw-r--   1 bost bost    503 Sep 22 11:19 circle.yml
-rw-rw-r--   1 bost bost    188 Sep 22 11:19 .editorconfig
drwxrwxr-x   8 bost bost   4096 Sep 22 11:27 .git/
-rw-rw-r--   1 bost bost     24 Sep 22 11:19 .gitattributes
drwxrwxr-x   2 bost bost   4096 Sep 22 11:19 .github/
-rw-rw-r--   1 bost bost    160 Sep 22 11:19 .gitignore
drwxrwxr-x   9 bost bost   4096 Sep 22 11:19 lib/
-rw-rw-r--   1 bost bost   1069 Sep 22 11:19 license.md
drwxrwxr-x 814 bost bost  36864 Sep 22 11:31 node_modules/
-rw-rw-r--   1 bost bost   4313 Sep 22 11:31 package.json
-rw-rw-r--   1 bost bost 315982 Sep 22 11:31 package-lock.json
-rw-rw-r--   1 bost bost   3822 Sep 22 11:19 readme.md
drwxrwxr-x   4 bost bost   4096 Sep 22 11:19 test/
-rw-rw-r--   1 bost bost    649 Sep 22 11:19 .travis.yml
drwxrwxr-x   2 bost bost   4096 Sep 22 11:19 .vscode/
-rw-rw-r--   1 bost bost    961 Sep 22 11:19 webpack.config.js
drwxrwxr-x   3 bost bost   4096 Sep 22 11:19 website/
-rw-rw-r--   1 bost bost 210039 Sep 22 11:19 yarn.lock
-rw-rw-r--   1 bost bost     18 Sep 22 11:19 .yarnrc
$ yarn
ERROR: There are no scenarios; must have at least one.
$ yarn run dev
ERROR: [Errno 2] No such file or directory: 'run'
```

???

**Comment by albinekb** [comment]
Looks like you have a problem with `yarn`, maybe look for help @ stackoverflow? This does not seem to an issue with this repo? 🤔

**Comment by albinekb** [comment]
Next time, try a google search for your errors.

First result for `ERROR: There are no scenarios; must have at least one.`

[Yields this](https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365)

>You've got the wrong yarn 😄 The Yarn you're executing comes from the cmdtest package: http://manpages.ubuntu.com/manpages/xenial/man1/yarn.1.html. Uninstalling cmdtest should fix this.

Closing, feel free to join the community slack if you need more help.

**Comment by Bost** [comment]
> Next time, try a google search for your errors.

Next time try to write on what *exactly* your software depends on :-(
I think reporting a valid issue in your project was a waste of time. I feel like I won't use/collaborate on/contribue to/etc. your project anymore.

**Comment by albinekb** [comment]
![image](https://user-images.githubusercontent.com/5027156/30744556-dd1fc5e4-9fa2-11e7-8519-9419c1274106.png)

It says in the readme the link to the yarn you need to install, is it unclear,then tell us and we'll fix it! :)

**Comment by albinekb** [comment]
I don't see how that is unclear, so please tell me so we can improve   ❤️

**Comment by albinekb** [comment]
@Bost

**Comment by albinekb** [comment]
@Bost ?

**Comment by albinekb** [comment]
I'm closing this here, now people with the same problem can search the issues and find this one to fix it, if we see a lot of people coming here we need to clarify the installation of `yarn` on latest ubuntu, but I think it's pretty clear if you follow the link to yarnpkg.org.
