### ISSUE TITLE
[v2] Does not work when you enter a web page

### ISSUE THREAD

**Issue by MAPESO** [zeit/hyper#2268]
- **OS version and name**: macOS Sierra - 10.12.6
- **Hyper.app version**: 2.0.3 (canary)

when I try to enter the website, nothing happens. It also does not release any error message.

put this problem with the **label v2**. To isolate the problems of the **canary** version with those of the stable version.

**Comment by VonKavalier** [comment]
I have that issue too, how can it be resolved ?

**Comment by chabou** [comment]
Can you describe: "enter a web page"?

**Comment by VonKavalier** [comment]
Well, typing a URL, as `https://google.com`
I mean, when he says "enter" that's what I understand and that's also my problem.

I looked on the "hyperlinks" plugin repository, and it appears that the fact your terminal add colors to the URL prevents the script to run and therefore doesn't display the webpage.

This plugin also doesn't seems to be maintained so I don't know what will happen for this issue.
