### ISSUE TITLE
Some powerline characters are being displayed smaller than it should

### ISSUE THREAD

**Issue by cesaraaron** [zeit/hyper#2269]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.6 
- **Hyper.app version**: 2.0.2

For example the arrow of the robbyrussell theme.

In hyper:
![screen shot 2017-09-23 at 8 52 10 am](https://user-images.githubusercontent.com/20180899/30774246-db66b466-a03c-11e7-9bc4-92ac9fe6ca77.png)

iTerm:
![screen shot 2017-09-23 at 8 51 57 am](https://user-images.githubusercontent.com/20180899/30774250-e8532cae-a03c-11e7-956e-275d3c0599af.png)

terminal:
![screen shot 2017-09-23 at 8 57 49 am](https://user-images.githubusercontent.com/20180899/30774274-515b1a68-a03d-11e7-891b-3d9b11f3e597.png)

Same font and size.

**Comment by MAPESO** [comment]
Did you make this comparison with **stable version _1.4.7** ? 

There is also the possibility of modifying the font size with the file hyper.js

**Comment by cesaraaron** [comment]
Modifying the font size doesn't work.

![screen shot 2017-09-23 at 10 37 49 pm](https://user-images.githubusercontent.com/20180899/30779497-08e7d1e0-a0b0-11e7-8037-76c9d7f655dc.png)

How it should:
![screen shot 2017-09-23 at 10 40 53 pm](https://user-images.githubusercontent.com/20180899/30779517-54f6505c-a0b0-11e7-9aad-bd7d5f235e40.png)

**Comment by MAPESO** [comment]
@cesaraaron  I just checked the problem, it does not work as it should. robbyrussell theme does not resize, clearly **this is a bug in version 2.0.2 canary.**

<img width="1280" alt="screen shot 2017-09-24 at 00 26 26" src="https://user-images.githubusercontent.com/16585386/30779788-da6c4462-a0bf-11e7-83a7-21a55b7b4f28.png">

**Comment by lucasqueiroz** [comment]
Hmm, for me its resizing correctly...

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
