### ISSUE TITLE
No scroll bar in canary version

### ISSUE THREAD

**Issue by spences10** [zeit/hyper#2270]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/spences10/72d7572314e5c4645f0daa63ba0ea5a9
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Works on 1.4.7 with same config

## Issue

The scroll bar on 1.4.7 here:
![2017-09-23_li](https://user-images.githubusercontent.com/234708/30774722-28514286-a07f-11e7-91ea-60778bb9115f.jpg)

Version where the issue is:
![image](https://user-images.githubusercontent.com/234708/30774779-2c711e9e-a080-11e7-902b-1730d82deaa2.png)

Run the same command to get the same output and I now can't scroll 😢 

![2017-09-23 3 _li](https://user-images.githubusercontent.com/234708/30774872-5fee004c-a081-11e7-9ced-1b2f4a2a0204.jpg)

There is no terminal output and it's the same with the one plug in I have on there disabled:

![image](https://user-images.githubusercontent.com/234708/30774920-04f5999c-a082-11e7-9c00-33bdfbe8794c.png)

Thanks

**Comment by MAPESO** [comment]
@spences10 This definitely does not happen with the macOS version. I will review the problem with the version of windows 10.
<img width="1280" alt="screen shot 2017-09-24 at 14 04 46" src="https://user-images.githubusercontent.com/16585386/30785773-75caba76-a131-11e7-83bf-9e640b6a3b45.png">

**Comment by MAPESO** [comment]
@spences10 **_version 2.0.3 is available_**, can verify if the Scroll problem persists.

**Comment by spences10** [comment]
Yeah, still persists @MAPESO 

Seems that there's not a great deal of Windows users for Hyper then? Or I'm a special snowflake 😄 

![image](https://user-images.githubusercontent.com/234708/30786841-27442c96-a174-11e7-8079-85e79fc66297.png)

All the things disabled 

Thanks

**Comment by MAPESO** [comment]
@spences10  Thanks for reporting the problems in Windows version. The idea of Hyper is that it is a nice terminal that can be **cross-platform** :)

**Comment by MAPESO** [comment]
I was doing tests and if the scroll appears, but the behavior is not correct.
![21979483_1144989762311279_620262679_n](https://user-images.githubusercontent.com/16585386/30787370-683e99c0-a14c-11e7-8ae0-11104da5a91e.png)

**Comment by spences10** [comment]
@MAPESO can you share a gist to the settings you are using so I can try the same?

**Comment by MAPESO** [comment]
@spences10  I'm using **_canary version 2.0.3_**. 
To have the scroll appear, you have to press enter in that way to force the scroll.
![22015409_1145171582293097_1946935164_o](https://user-images.githubusercontent.com/16585386/30794956-cf33db92-a190-11e7-929f-c8a27e5b4065.png)

**Comment by spences10** [comment]
@MAPESO enter a command first then enter, yes I understand 👍 

Will the shell I'm using cause any issues?

I'm using bash and git bash not powershell

**Comment by MAPESO** [comment]
@spences10 I would have to try to use the same configuration as you have, to rule out issues with git bash. The shell I'm using is the Ubuntu.

**Comment by spences10** [comment]
This appears to be working for me on the latest version now, feel free to close @MAPESO

**Comment by albinekb** [comment]
Thanks @spences10
