### ISSUE TITLE
Colors doesnt work like expected

### ISSUE THREAD

**Issue by pedrofilho20** [zeit/hyper#2271]
Idk if its a problem of the hyper, but I would love to have the default theme on the "Bash for Windows", and seems that it changes the colors..

![image](https://user-images.githubusercontent.com/13142568/30777765-ecb4d2d2-a098-11e7-9879-7d5c7aa4bfc2.png)

Is it normal? How can I change this?

Tks

**Comment by MAPESO** [comment]
Could you tell me the version of **_Hyper_** :)

**Comment by MAPESO** [comment]
@pedrofilho20 Been testing with the topics of https://hyperthemes.matthi.coffee/, The page specializes in the theme for mac OS. You could customize Hyper through hyper.js file

If you customize Hyper that is in the **stable version that would be 1.4.7.** the Canary version has some minor flaws.

it would be a good idea to have a page for Windows themes :)

**Comment by pedrofilho20** [comment]
I'm on the lastest version for windows (the one that made me restart the app), and any theme make this thing work as expected..

**Comment by MAPESO** [comment]
@pedrofilho20  The themes are working, but they do not fit the design that Hyper has for Windows. I just checked with some themes and it does not look like in **macOS**.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
