### ISSUE TITLE
plugins problems

### ISSUE THREAD

**Issue by rapha8l** [zeit/hyper#2276]
Hi,
Since 2.0.2 and now 2.0.3, installing and uninstalling plugins give this (debian testing)

A JavaScript error occurred in the main process
Uncaught Exception:
Error: Error reading configuration: `module.exports` not set
    at _extract (/opt/Hyper/resources/app.asar/config/init.js:8:11)
    at _init (/opt/Hyper/resources/app.asar/config/init.js:31:18)
    at exports._import (/opt/Hyper/resources/app.asar/config/import.js:43:15)
    at FSWatcher.onChange (/opt/Hyper/resources/app.asar/config.js:18:11)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:194:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1392:12)

Also hyperline-magus stopped to work in 2.02 and as I can't install it anymore I can't paste the error message, sorry

**Comment by Stanzilla** [comment]
ok? more details please.

**Comment by MAPESO** [comment]
@rapha8l I need details on platform where you run hyper like the version. That way it will be easier for me to detect your problem :)

**Comment by rapha8l** [comment]
Sure, what kind of details can I add ? (it's x86_64 and 4.12.0-2 kernel)

**Comment by MAPESO** [comment]
@rapha8l  Could show hyper.js file

It would be great if you detail the operating system already be Linux, Windows and Unix :)

**Comment by jwhitmarsh** [comment]
Just got the same error after uninstalling a plugin then installing a different one.

OS: macOS
hyper: 1.4.7
hyper.js: 
```js
module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: '12',

    // font family with optional fallbacks
    fontFamily: '"Meslo LG L for Powerline", Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',

    // terminal cursor background color (hex)
    cursorColor: 'rgba(255,255,255,0.8)',

    // color of the text
    foregroundColor: 'rgb(86, 190, 84)',

    // terminal background color
    backgroundColor: 'rgba(2, 43, 54, 0.8)',

    // border color (window, tabs)
    borderColor: 'rgba(255,255,255,.1)',

    // custom css to embed in the main window
    css: 'header.t_header {background: transparent!important;}',

    // custom padding (css format, i.e.: `top right bottom left`)
    termCSS: '',

    // custom padding
    padding: '0px 0px',

    // some color overrides. see http://bit.ly/29k1iU2 for
    // the full list
    colors: [
      '#002834',
      '#dc322f',
      '#859901',
      '#b58901',
      '#268bd2',
      '#d33682',
      '#2aa198',
      '#eee8d5',
      '#839496',
      '#cb4b16',
      '#3d713a',
      '#83773b',
      '#839496',
      '#839496',
      '#93a1a1',
      '#93a1a1'
    ],

    windowSize: [1500, 850],

    // plugin config
    paneNavigation: {
      showIndicators: false,
      hotkeys: {
        navigation: {
          up: 'command+alt+up',
          down: 'command+alt+down',
          left: 'command+alt+left',
          right: 'command+alt+right'
        }
      }
    },
    summon: {
      hideDock: true,
      hideOnBlur: false
    }
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hypersolar`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [`hyperlinks`, "hyper-pane", "hyperterm-summon", "hyper-statusline"],

  // in development, you can create a directory under
  // `~/.hyperterm_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
}
```

**Comment by rapha8l** [comment]
Ok, so Debian Gnu/Linux
hyper                                 2.0.3-2347 
my hyper.js

// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 15,

    // font family with optional fallbacks
    fontFamily: 'FantasqueSansMono, Hack, Hasklig, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    //cursorColor: 'rgba(248,28,229,0.8)',
    cursorColor: 'rgba(232,232,232,0.8)',
//    cursorColor: 'rgba(0,0,0,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#d3d3d3',

    // terminal background color
    backgroundColor: '#000000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: true,

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#201E24',
      red: '#2D2B30',
      green: '#3F3D40',
      yellow: '#413C3E',
      blue: '#423E41',
      magenta: '#4E4A4B',
      cyan: '#6E6765',
      white: '#837E81',
      lightBlack: '#837C78',
      lightRed: '#89827D',
      lightGreen: '#A7A099',
      lightYellow: '#C2BEC1',
      lightBlue: '#C3BCB2',
      lightMagenta: '#CBC5BA',
      lightCyan: '#E3DDD2',
      lightWhite: '#EFE8DC'
    },


          modifierKeys: {ctrlIsMeta: false},

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
:   env: {},

    // set to false for no bell
    bell: 'visual',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};

**Comment by MAPESO** [comment]
@rapha8l @jwhitmarsh Try uninstalling hyper and reinstall it. If the error is resolved or persist let me know.

**Comment by rapha8l** [comment]
Hi, removing and installing 2.0.4 gives me the same error
Should I also remove my .hyper.js and .hyper_plugins ?

**Comment by MAPESO** [comment]
@rapha8l Delete the files, if the problem persists let me know 😄

**Comment by rapha8l** [comment]
Hi,

Same after removing all files, purging and reinstalling hyper 2.0.4

**Comment by rapha8l** [comment]
Strangely, it seems my last try to install a plugin worked (maybe)
Though for hyperline-magus I get : 
bundle.js:1 (re)loading renderer plugins
bundle.js:1 Plugin hyperline-magus (0.6.0) loaded.
bundle.js:1 TypeError: Cannot read property 'string' of undefined
    at hyperlineFactory (/home/xxx/.hyper_plugins/node_modules/hyperline-magus/dist/hyperline.js:230:33)
    at decorateHyper (/home/xxx/.hyper_plugins/node_modules/hyperline-magus/dist/hyperline.js:124:52)
    at y.forEach (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:2115)
    at Array.forEach (native)
    at getDecorated (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:2055)
    at Object.render (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:1:2931)
    at k (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:4:55481)
    at beginWork (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:4:56969)
    at e (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:4:69619)
    at k (file:///opt/Hyper/resources/app.asar/renderer/bundle.js:4:70127)
y.forEach @ bundle.js:1
bundle.js:4 [Notification] Plugin error: hyperline-magus: Error occurred in `decorateHyper`. Check Developer Tools for details
index.html:35 total init time 321.42999999999995

**Comment by albinekb** [comment]
That's most likely a problem with the plugin `hyperline-magus`, try removing it and see if the issue dissapears 👍  @rapha8l

**Comment by rapha8l** [comment]
the "decorateHyper error is surely related to hyperline-magus, though the main error still happens, with any random plugin I try
I've just tried hypercwd and hyperlayout

**Comment by MAPESO** [comment]
@rapha8l @jwhitmarsh Are using the package manager on Hyper, to install the plugins?  or you are doing it through the hyper.js file

it is not normal for this error to continue after deleting everything🤔

**Comment by rapha8l** [comment]
I use hpm to install plugins

**Comment by MAPESO** [comment]
@rapha8l hpm causes conflicts with canary version 2.0.4
if you are going to install plugins I recommend you do it through the **hyper.js** file

This solution is temporary, which is needed to solve some errors with hpm. If the error persists let me know 😄

**Comment by rapha8l** [comment]
Ok thanks, the problem was also present in 2.0.2 and 2.0.3

**Comment by willdavidow** [comment]
I'm having the same problem - I've uninstalled hyper `2.0.4` and all plugins and config files multiple times.

Here's the developer console output, which seems specific to the `hyperline` plugin (or one of its dependencies):

```
(re)loading renderer plugins
bundle.js:1 Plugin hypercwd (1.1.1) loaded.
bundle.js:1 Plugin hyper-statusline (1.7.3) loaded.
bundle.js:1 Plugin hyperline (0.6.1) loaded.
bundle.js:1 Plugin hyper-search (0.0.6) loaded.
/Users/me/.hyper_plugins/node_modules/hypercwd/configParse.js:5 hypercwd: no 'config.hypercwd' object found in ~/.hyper.js - see https://github.com/hharnisc/hypercwd#configuration for configuration details
bundle.js:1 TypeError: Cannot read property 'string' of undefined
    at hyperlineFactory (/Users/me/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:223:33)
    at decorateHyper (/Users/me/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:124:52)
    at y.forEach (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:2115)
    at Array.forEach (native)
    at getDecorated (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:2055)
    at Object.render (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:2931)
    at k (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:55481)
    at beginWork (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:56969)
    at e (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:69619)
    at k (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:4:70127)
y.forEach @ bundle.js:1
bundle.js:4 [Notification] Plugin error: hyperline: Error occurred in `decorateHyper`. Check Developer Tools for details
index.html:35 total init time 161.29000000000008
```

**Comment by thedataking** [comment]
I'm also seeing this problem on Hyper 2.0.4 on macOS 10.13 with plugins purged and installed thru `.hyper.js`.

**Comment by ErickTucto** [comment]
Hello @rapha8l ... I have equals problem ... help

**Comment by MAPESO** [comment]
@ErickTucto @thedataking I recommend **removing hyper and reinstalling** it, if the error persists let me know.

**Comment by Empty2k12** [comment]
I uninstalled Hyper, deleted `.hyper.js`, `.hyper_plugins/` and I am getting the same error:

```
Uncaught Exception:
Error: Error reading configuration: `module.exports` not set
    at _extract (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:8:11)
    at _init (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:30:18)
    at _import (/Applications/Hyper.app/Contents/Resources/app.asar/config/import.js:38:15)
    at FSWatcher.onChange (/Applications/Hyper.app/Contents/Resources/app.asar/config.js:18:11)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:194:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1392:12)
```

**Comment by sitano** [comment]
having the same problem, fresh install, fresh configs. Ubuntu 16.04.3 LTS.

**Comment by pickledrick** [comment]
osx Sierra fresh install same problem

**Comment by chabou** [comment]
I think that this error occurs only at first launch if config file is missing (and created).
We should not trigger an error in this case.

**Comment by rapha8l** [comment]
Hi, the error appears even with a config file

**Comment by bgrieder** [comment]
OS Sierra: Install with `brew cask` or direct download  
node: 8.5.0; npm 5.3.0; Hyper 1.4.8 (stable); hpm, 2.0.1

Same issue 

    Uncaught Exception:
        Error: Error reading configuration: `module.exports` not set
             at _extract (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:8:11)

**Comment by jonathantneal** [comment]
I had this issue until I uninstalled `hyperline`. Here was the error log from Developer Tools:

```
bundle.js:1 Error: Cannot find module 'prop-types'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Function.c._load (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:8001)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:134:18)
    at __webpack_require__ (~/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:20:30)
    at Object.<anonymous> (~/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:149:69)
    at __webpack_require__ (~/.hyper_plugins/node_modules/hyperline/dist/hyperline.js:20:30)
```

**Comment by jeffscottward** [comment]
Same problem.

**Comment by e-nouri** [comment]
I am really not sure if this will work for anyone having this problem, but this is what i did and it worked for me after reloading. change all of the plugins name to use ```` instead of `""` or `''`, example:
`plugins: [`hyperlinks`, "hyper-pane", "hyperterm-summon", "hyper-statusline"],` this will not work.

`plugins: [`hyperpower`, `hyperlinks`, `hyper-pane`, `hyperterm-summon`, `hyper-statusline`],` this will work fine.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
