### ISSUE TITLE
Update directly from app

### ISSUE THREAD

**Issue by dsslimshaddy** [zeit/hyper#2278]
Instead of going to github downloading release , there should be an option to update directly from app.

**Comment by Stanzilla** [comment]
Hyper already does auto updates.

**Comment by MAPESO** [comment]
@dsslimshaddy  What version of hyper do you have? Hyper already implements automatic updates, there is no need to do what you did :)

**Comment by shahzeb1** [comment]
Is there a way to update to pre-release version from within Hyper, or by running a command? Or is going to the [releases page](https://github.com/zeit/hyper/releases/tag/2.0.3) the only way of doing this?

**Comment by MAPESO** [comment]
@shahzeb1 You have to add this **updateChannel: 'canary'** in the file hyper.js

That way you will have **version 2.0.3**  :)

**Comment by albinekb** [comment]
@MAPESO @shahzeb1 keep in mind that doing that will change to `canary` channel, which **can** be unusable at times, so if you need stability, please don't change to `canary`.

**Comment by MAPESO** [comment]
@albinekb You're right, I needed to detail this point. I am sorry
