### ISSUE TITLE
[Issue] Jumping Between Tabs

### ISSUE THREAD

**Issue by vinkla** [zeit/hyper#2279]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13 Beta (17A360a)
- **Hyper.app version**: Hyper 2.0.3 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://github.com/vinkla/dotfiles/blob/master/.hyper.js
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

In version 2.0+ jumping between tabs with the keyboard shortcut <kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>←</kbd> or <kbd>→</kbd> no longer works. This works fine in Hyper version 1.0+ as it does with Chrome tabs. Any idea why this behaviour changed between version 1 and 2?

**Comment by viktor-evdokimov** [comment]
Can reproduce, although i don't have any of your plugins installed and have `hyper-clean` instead. Also I can't really use new tabs once they are open. and I am using `fish` as my shell.
Also not only CMD+ALT+arrows do not work, CMD+1-2-3 do not  work too.

**Comment by albinekb** [comment]
It's a bug @vinkla version 2 is `canary`, meaning it's not ready yet 👍 but thanks for reporting so we can keep track of when this is fixed 🎉

**Comment by vinkla** [comment]
> It's a bug @vinkla version 2 is canary, meaning it's not ready yet 👍 but thanks for reporting so we can keep track of when this is fixed 🎉

Sorry, didn't mean to complain. Just wanted to report it and let you know.

**Comment by albinekb** [comment]
Didn't take that as a complaint, just want to make sure everyone understands that 2.0 is not `stable` yet 👍  @vinkla

**Comment by antonydb** [comment]
For those keyboard users you can use <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>[</kbd> or <kbd>]</kbd> in the meantime.

**Comment by vinkla** [comment]
> Keyboard users you can use CMD + SHIFT + [ or ] in the meantime.

Yeah, that is true. That will work fine on English keyboards but sadly not on Swedish ones.

**Comment by vinkla** [comment]
I've tried to create custom keyboard shortcuts but without success.

<img width="780" alt="screen shot 2017-10-10 at 19 53 31" src="https://user-images.githubusercontent.com/499192/31401960-c4a611b6-adf4-11e7-8770-8ae844b3678a.png">

**Comment by vinkla** [comment]
This is fixed in Hyper 2.0.0-canary.8 (canary).
