### ISSUE TITLE
Running vim produces a strange row of text at the top.

### ISSUE THREAD

**Issue by shahzeb1** [zeit/hyper#2281]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.6
- **Hyper.app version**: 1.4.7

## Issue

![image](https://user-images.githubusercontent.com/1383831/30786939-33e61f5e-a133-11e7-9c1f-8107374e0e31.png)

Running `vim` produces a strange top bar of random text within hyper. Doesn't happen in other terminal applications.

**Comment by MAPESO** [comment]
Could you give me more details to reproduce the error :)

**Comment by shahzeb1** [comment]
Sure thing.

I simply `cd` into a folder and run `vim <filename>.js`

The vim plugin called [vim-airline](https://github.com/vim-airline/vim-airline) is installed.

**Update**: Really strange but I am unable to reproduce the error (the top bar is no longer showing up.
![image](https://user-images.githubusercontent.com/1383831/30787276-d14cc95e-a139-11e7-9334-bfdfe56589a2.png)

**Comment by TooTallNate** [comment]
I don't think you meant to close this. Also I've run into this as well.

**Comment by shahzeb1** [comment]
Feel free to open it back up. 

I simply closed it because I thought it was a one-off type of an error. But if you're having it too, it's best to keep the issue open.

**Comment by dpo** [comment]
Same as #1037? I've been having this issue for a while.

**Comment by TooTallNate** [comment]
Yes, let's close this one then.
