### ISSUE TITLE
Even after updating it is asking to update

### ISSUE THREAD

**Issue by NullPointerLab** [zeit/hyper#2282]
-
        Hyper 2.0.2
        Electron 1.7.6
        win32 x64 6.3.9600

**Comment by MAPESO** [comment]
@NullPointerLab  You can detail the operating system with which Hyper runs.

**Comment by borekb** [comment]
I'm seeing this after every start:

![image](https://user-images.githubusercontent.com/101152/30898746-1c7c0654-a35d-11e7-97cc-ef780fdaef86.png)

**Comment by NullPointerLab** [comment]
I am using windows 8.1 with AMD A10 processor

**Comment by MAPESO** [comment]
@NullPointerLab I just run the tests on my computer, hyper is not updated to the stable version after having indicated it in the hyper.js file 🤔

I will try to solve the bug

The only solution I offer at this time is to remove hyper and reinstall it in its stable version.

**Comment by MAPESO** [comment]
@NullPointerLab I can not replicate that errror on my computer.

Could remove Hyper and reinstall. If the error persists let me know.

**Comment by borekb** [comment]
@MAPESO So what is "stable" at the moment? The About dialog says that 2.0.4 is "stable" but it's marked as pre-release here on GitHub. Also, I think that I've seen the prompt to update even when I changed my channel to "canary" but I'm not 100% sure.

**Comment by MAPESO** [comment]
@borekb When the change is made to the canary version then it is passed to the stable. The dialog box will tell you that **version 2.0.4 is stable,** but it is a bug that will be fixed.

The message bug that prompts you to update even when such a change has already been made, is not displayed when you change to canary.

**Comment by Stanzilla** [comment]
That hiccup should be fixed now, please report back if it isn't
