### ISSUE TITLE
ctrl+v not pasting after latest update

### ISSUE THREAD

**Issue by dsslimshaddy** [zeit/hyper#2290]
before update it was good.

Now i have to press `ctrl+shift+v`  which ain't good.

**Comment by albinekb** [comment]
What update? Are you using `stable` or `canary`, what OS? please fill in the issue template :)

**Comment by dsslimshaddy** [comment]
im using `Hyper version 2.0.3` `Ubuntu 16.04`

**Comment by chabou** [comment]
Shortcut has changed.
Please use `ctrl+shift+v` or redefine it in your config file.

You can see all Linux shortcuts here: https://github.com/zeit/hyper/blob/1f2419fe52657e361aa1e146896a0c9c6d943d2e/app/keymaps/linux.json#L26

**Comment by ekulabuhov** [comment]
If someone is not sure how to redefine keymaps:
1. Open ~/.hyper.js
2. Add keymaps section:

```js
module.exports = {
  config: { ... },
  keymaps: {
    "editor:copy": "ctrl+c",
    "editor:paste": "ctrl+v"
  },
  ...
}
```
3. No need to restart hyper as it watches config file for changes.
