### ISSUE TITLE
Heavy Lag When Running Hyper With Chrome, Visual Studio Code, and other javascript applications

### ISSUE THREAD

**Issue by lichen545** [zeit/hyper#2292]
I'm experiencing heavy performance lag when running Hyperterm alongside any application that also runs javascript (Chrome, Firefox, Visual Studio Code). All applications will freeze for ~5 seconds every few seconds when Hyperterm is running concurrently with these applications, but when I close Hyperterm the performance issue goes away. I've had this issue with every version of Hyper I've installed, and I've already reset my OS and reinstalled all my applications twice to no avail, is anyone else experiencing the same issue?

- Windows 10 Build 15063.608
- Hyper v.1.3.1, v.1.4.7, v1.4.8

**Comment by PerStirpes** [comment]
Can you post your `.hyper.js` config

**Comment by MAPESO** [comment]
@PerStirpes I don't think this problem is related hyper.js 🤔

@lichen545 I have windows 10 but I do not experience such a flaw. You could show me the **hyper.js** file

**Comment by lichen545** [comment]
Here is my .hyper.js file: 

`// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: 'C:\\Windows\\System32\\bash.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [
    `hyperpower`,
    `hyperborder`,
    `hypercwd`,
    `hyperborder`,
    `hyper-blink`,
    `hyperterm-tab-icons`,
    `hyperterm-cursor`
  ],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
`

**Comment by MAPESO** [comment]
@lichen545  You could specify the characteristics of your computer.

**Comment by albinekb** [comment]
hyperpower is known to cause huge performance issues, please try to disable all plugins and run vanilla hyper to see if the problem is still there.

**Comment by lichen545** [comment]
@albinekb I disabled hyperpower and the issue went away, thanks for the tip!

**Comment by albinekb** [comment]
Good to hear @lichen545! 🎉 
Open an issue over at https://github.com/zeit/hyperpower about the performance issue, it's fixable 😺
