### ISSUE TITLE
Ubuntu 14.04 not launching.

### ISSUE THREAD

**Issue by tzsk** [zeit/hyper#2298]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version 2.0.4
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS Ubuntu 14.04**: 
- **Hyper.app 2.0.4**: 

## Issue

I installed from `.deb` and before that, I installed all the required `apt-get` from the list provided in Read Me. Now when I click on the Hyper App it does not open.

Then I tried running `$ hyper` from the terminal to launch Hyper but it throws this error:
```bash
A JavaScript error occurred in the main process
Uncaught Exception:
Error: watch /home/kazi/.hyper.js ENOSPC
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1410:19)
    at Object.fs.watch (fs.js:1436:11)
    at _watch (/opt/Hyper/resources/app.asar/config.js:36:19)
    at Object.exports.setup (/opt/Hyper/resources/app.asar/config.js:84:3)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:63:8)
    at Object.<anonymous> (/opt/Hyper/resources/app.asar/index.js:252:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

```

**Comment by MAPESO** [comment]
@tzsk Hi, I'll take a look at the installation problem you have.

**Comment by albinekb** [comment]
`ENOSPC` means that there is no space on the drive.

- Do you have space left?
- Permission issue?

**Comment by tzsk** [comment]
@albinekb I don't know why it is giving that error because -

- **Low Disk Space?** - No. I have about 700GB free space available in the Disk.
- **Permission Issue?** - Yes, maybe, when I ran `sudo hyper` then Hyper launched perfectly but in ROOT mode and there is no Menu Icon at the top left corner of the Window.

I have also installed the `.exe` in my Separate Windows Machine. It all works but not quite perfectly. When I go to `Edit > Preferences` it shows the following error:

```
Script:   C:\Users\Kazi\.hyper.js
Line:     5
Char:     1
Error:    'module' is undefined
Code:     800A1391
Source:   Microsoft JScript runtime error
```
I have no IDEA what's going on.

**Comment by ZaLiTHkA** [comment]
I'm experiencing the same issue here, Linux Mint 18.2 (based on Ubuntu 16.04). Disk space is not an issue, and my user owns both the `.hyper.js` file and `.hyper_plugins/` directory recursively.

1.4.8 ran fine, it's only after I installed 2.0.4 that I started getting this.. For what it's worth, I don't have any problems running 2.0.4 on my Win10 PC at work, but my Linux laptop and desktop at home both have this issue.

**Comment by albinekb** [comment]
This config edit error `...Source:   Microsoft JScript runtime error...` is because windows *redacted* and has a bad default program for .js files, to fix this, change the default program for all .js files to your editor: https://www.cnet.com/how-to/how-to-set-default-programs-in-windows-10/

**Comment by ZaLiTHkA** [comment]
@albinekb, is this issue not related to Linux? The OP states his operating system is Ubuntu and I've said I'm running Linux Mint (based on Ubuntu).

**Comment by albinekb** [comment]
Yes, the initial issue is something with ubuntu and the node `fs` apis/filesystem. But the other windows issue described with `JScript` is another one that's known 👍  @ZaLiTHkA

**Comment by hollowdoor** [comment]
I'm having what might be a similar problem. On Ubuntu 17.10 when starting hyper it does not appear graphically, but it still shows as a running process in the system monitor.

I go this error when running hyper from the default terminal:

```
The module '/opt/Hyper/resources/app/node_modules/pty.js/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
A JavaScript error occurred in the main process
Uncaught Exception:
Error: `pty.js` failed to load. Typically this means that it was built incorrectly. Please check the `README.me` to more info.
    at createPtyJsError (/opt/Hyper/resources/app/session.js:11:32)
    at Object.<anonymous> (/opt/Hyper/resources/app/session.js:17:9)
    at Object.<anonymous> (/opt/Hyper/resources/app/session.js:97:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```

It's a different error from the OP's, but I'm starting here just in case.

**Comment by Zamerick** [comment]
OS: Elementary OS Loki (Based on Xenial)
Hyper.app :2.0.0.- canary 11, and 1.4.8.

I'm experiencing this issue as well. I've tried mucking with the permissions on .hyper.js, but so far no luck.

**Comment by ezequieltejada** [comment]
Having the same issue:

OS: Linux mint 17.1
Hyper.app: (latest available through the webpage: "hyper_1.4.8_amd64")

**Comment by antcodd** [comment]
This is because of running out of inotify watchers on the machine. This happened to me on my very first time using hyper. I see similar non-fatal messages in VSCode and other programs sometimes with many files open and to be honest the stack trace gives a fairly good hint.

This should be handled gracefully (presumably by just not watching the file for changes) as it happens all the time on development machines and definitely shouldn't prevent startup!

For people with this issue, see for example https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers for instructions on how to increase this limit.
