### ISSUE TITLE
Hi There,

### ISSUE THREAD

**Issue by jasonsalzwedel** [zeit/hyper#2299]
-
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 6.1.7601

**Comment by timneutkens** [comment]
Hi :wave:

**Comment by albinekb** [comment]
Hi 👋  `ls` is a linux command, it does not work out of with windows. There are several options for you to enable this on windows though.

So yes, this is expected 👍

**Comment by albinekb** [comment]
duplicate of #2300

**Comment by maverickcapstone** [comment]
cmder does it out of the box, but anyway:

1. Hyper -> Edit -> Config
2. CTRL + F "shell", use this: C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe
3. Set shellArgs: ['']
4. If hyper doesn't crash, gj, you now have the privilege of basic functionality in your terminal.
