### ISSUE TITLE
Support of linux commands on windows.

### ISSUE THREAD

**Issue by jasonsalzwedel** [zeit/hyper#2300]
Hi there,

I was expecting to be able to use Linux commands such as "ls" on my Windows machine through hyper, but get the following response when I enter 'ls'.

'ls' is not recognized as an internal or external command,
 operable program or batch file.

Is this a bug or is it expected behaviour?

Cheers,

Jason
 -
 Hyper 1.4.8
 Electron 1.7.8
 win32 x64 6.1.7601

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 6.1.7601

**Comment by MAPESO** [comment]
@jasonsalzwedel  I'll take a look at your problem :)

**Comment by albinekb** [comment]
Hi 👋  `ls` is a linux command, it does not work out the box with windows. There are several options for you to enable this on windows though.

So yes, this is expected 👍

**Comment by albinekb** [comment]
We should have a readme/section on the website for windows users about this, the different options and how to configure them. PR welcome as I'm not using windows nor know all the options with pro/cons 👍

**Comment by MAPESO** [comment]
@albinekb [Here's the file :)](https://github.com/MAPESO/hyper-windows/blob/master/windows.md)

**Comment by jasonsalzwedel** [comment]
Thanks for the help! 
Have the GIT Bash up and running.

**Comment by AmnonSkladman** [comment]
Sorry to necro an old issue but I tried the above and it didn't work.

This is the code in my configuration for Hyper.js:

```
    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    //
    // Windows
    // - Make sure to use a full path if the binary name doesn't work
    // - Remove `--login` in shellArgs
    //
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
    //
    // PowerShell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: 'C:\\Program Files\\Git\\git-cmd.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
    // by default `['--login']` will be used
    shellArgs: ['--login', '--command=usr/bin/bash.exe', '-l', '-i'],
```

However, things like `ls` and `clear` are still not recognized in Hyper (but they are in Git Bash). Am I doing something wrong, or maybe misunderstanding something?

Win 10 64-bit
Hyper 3.0.2
git-scm 2.21.0
