### ISSUE TITLE
Vim Flickering

### ISSUE THREAD

**Issue by Juici** [zeit/hyper#2301]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Juici/705244c98a5cead114530712825a9633
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Flickering of the status line in vim when scrolling through text. https://gfycat.com/UnselfishChiefApe

This may seem to only happen a bit, but that's because of the bad recording. It in fact does this weird flicker downwards every time I scroll down a line in vim. However there is no weirdness when I scroll up.

I have tested this in mintty and in the windows prompt and cannot reproduce this flickering.

**Comment by MAPESO** [comment]
@Juici I'll take a look at your problem.

**Comment by timothyis** [comment]
@Juici This should be fixed in v2. Please let us know if you still have this issue.
