### ISSUE TITLE
Bash for Windows colors are unreadable with default terminal theme

### ISSUE THREAD

**Issue by MAPESO** [zeit/hyper#2304]
- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.8 and 2.0.3 (canary)

![p](https://user-images.githubusercontent.com/16585386/30987373-703733ea-a45c-11e7-9efb-e6aab334325a.jpg)

**Solution**

```
$ LS_COLORS='ow=01;36;40'
$ export LS_COLORS 
```

For the moment this will help the default theme that has Hyper ☹️
I know that the improvement is not much but at least it becomes a little more readable.

![22091643_1147173082092947_947001639_n](https://user-images.githubusercontent.com/16585386/30988334-c03697c0-a45f-11e7-8996-db60cdc14537.png)

**Comment by albinekb** [comment]
same issue as described here https://github.com/Microsoft/vscode/issues/7556  🤔  seems similar at least,
