### ISSUE TITLE
Session is not becoming full using shift+cmd+ENTER. 

### ISSUE THREAD

**Issue by djalmaaraujo** [zeit/hyper#2308]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13 (17A365)
- **Hyper.app version**: Hyper 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

When I was using iTerm and pressed shift+cmd+enter the actual session would be focused and pressing again gets back to the original screen configuration. Here's a gif showing this functionality. 

I am not sure if this is an iTerm feature or tmux, but it's super helpful when you have multiple sessions in the same window.

![GIF](http://g.recordit.co/Rd4pvajTcb.gif)

**Comment by MAPESO** [comment]
@djalmaaraujo Is a function that asks a lot in Hyper, it is working on that.

**Comment by chabou** [comment]
@djalmaaraujo `hyper-pane` plugin has this feature. You should use it ;)
