### ISSUE TITLE
How to properly set custom colors on hyper.js?

### ISSUE THREAD

**Issue by cytryn** [zeit/hyper#2309]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS High Sierra 10.13
- **Hyper.app version**: 1.4.8

I am trying to set up my own colors like:

```
colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff',
      materialRed: '#ff1744',
      materialPink: '#f50057',
      materialPurple: '#d500f9',
      materialDeepPurple: '#673ab7',
      materialIndigo: '#3f51b5',
      materialBlue: '#2979ff',
      materialLightBlue: '#00b0ff',
      materialCyan: '#00e5ff',
      materialTeal: '#009688',
      materialGreen: '#00e676',
      materialLightGreen: '#00e676',
      materialLime: '#cddc39',
      materialYellow: '#ffeb3b',
      materialAmber: '#ffc400',
      materialOrange: '#ff9100',
      materialDeepOrange: '#ff3d00',
      materialBrown: '#795548',
      materialGray: '#9e9e9e',
      materialBlueGray: '#607d8b',
    },
```

It works just fine, but I keep getting warnings like:

![Warnings](https://cl.ly/1j3q1v2B0x0C/Image%202017-09-29%20at%203.22.12%20PM.png)

How should I properly set them to avoid the warnings?

**Comment by MAPESO** [comment]
@cytryn What is the problem with colors by default? 
The link to **"Warnings"** is broken 😄

**Comment by MAPESO** [comment]
@cytryn I just applied your configuration with version 1.4.8 (stable) but I did not present the problem 🤔

Could you show me the hyper.js file?

<img width="1280" alt="screen shot 2017-09-29 at 14 01 16" src="https://user-images.githubusercontent.com/16585386/31031745-2ab99984-a51f-11e7-838d-b77189711a07.png">

**Comment by chabou** [comment]
@cytryn I don't understand what you're are trying to do. Are you adding colors for your own plugin? If not, what behaviour do you expect by adding these new colors?

**Comment by cytryn** [comment]
@MAPESO and @chabou thanks for the response. 

I forgot to mention that I am using the `hyperline` plugin as the following and I use the colours to configure its visuals:

```
hyperline: {
      color: 'black',
      plugins: [
        {
          name: 'hostname',
          options: {
            color: 'materialOrange'
          }
        },
        {
          name: 'memory',
          options: {
            color: 'materialGreen'
          }
        },
        {
          name: 'uptime',
          options: {
            color: 'materialOrange'
          }
        },
        {
          name: 'cpu',
          options: {
            colors: {
              high: 'materialRed',
              moderate: 'materialYellow',
              low: 'materialGreen'
            }
          }
        },
        {
          name: 'network',
          options: {
            color: 'materialLightBlue'
          }
        },
        {
          name: 'battery',
          options: {
            colors: {
              fine: 'materialGreen',
              critical: 'materialRed'
            }
          }
        }
      ]
    },
```

**Comment by MAPESO** [comment]
@cytryn The problem has to be **hyperline** 🤔

**Comment by chabou** [comment]
Did you tried to specify color directly like this?
```
        {
          name: 'hostname',
          options: {
            color: '#ff9100'
          }
        },
```

**Comment by cytryn** [comment]
@chabou it does not work if I set colors directly =/

so this must be a hyperline issue. How can I contact its developer?

**Comment by MAPESO** [comment]
@timneutkens Look

**Comment by cytryn** [comment]
Any updates on this?

**Comment by Stanzilla** [comment]
https://github.com/Hyperline/hyperline

**Comment by AkhilMukkamala** [comment]
@cytryn Can I have your .hyper.js file please ? That looks Great.

**Comment by cytryn** [comment]
@AkhilMukkamala https://gist.github.com/cytryn/5d857b5f70c97e73ae0c191b3ef7770e
