### ISSUE TITLE
Specify plugin version in config

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2311]
If you specify `<plugin>@next` in config, it works great for `.hyper_plugins/package.json`: `next` is use and not `last`. But Hyper try to access `.hyper_plugins/node_modules/<plugin>@next/` and not 
 `.hyper_plugins/node_modules/<plugin>/`

**Comment by PerStirpes** [comment]
@chabou I'm confused, did you fix this with #2312? Or is help wanted?

**Comment by chabou** [comment]
Yes! It has been fixed by #2312.
Thank you for your help proposal
