### ISSUE TITLE
[windows] hitting alt-backspace causes duplicate to be sent to shell

### ISSUE THREAD

**Issue by vvuk** [zeit/hyper#2313]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Hyper.app version**:  1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/vvuk/8b5892ad87f05f9fd977cf977c9b61a4
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**:  Yes

## Issue

With at least `bash.exe` from `msys2/mingw64`, pressing `alt-backspace` causes the key sequence to be sent to the shell twice.  For example, typing "foo bar" and hitting `alt-backspace` should only delete "bar", but "foo" gets deleted as well.

**Comment by MAPESO** [comment]
@vvuk You could take a screenshot of your problem so that others can entenderlo better 😄 
I will take a look at your problem, when I have relevant information i will let you know.

**Comment by PerStirpes** [comment]
Hey @vvuk I'm not a windows guy and you probably already saw this but maybe it could help https://github.com/zeit/hyper/issues/1559  ?
