### ISSUE TITLE
electron planned deprecations 

### ISSUE THREAD

**Issue by PerStirpes** [zeit/hyper#2314]
Planned Breaking API Changes:
The following list includes the APIs that will be removed in Electron 2.0.
There is no timetable for when this release will occur but deprecation warnings will be added at least 90 days beforehand.

1. The `titleBarStyle:`option `hidden-inset`  is deprecated and `hiddenInset` should be used https://github.com/electron/electron/pull/9769
// Deprecated
https://github.com/zeit/hyper/blob/c9b508ff9a051b0559791309da282133bcc6319c/app/ui/window.js#L22

2. [webFrame](https://github.com/electron/electron/blob/493cfd38d66d8411f00d56a8d73582aad6d81c5e/docs/tutorial/planned-breaking-changes.md#webframe)
// Deprecated
https://github.com/zeit/hyper/blob/c9b508ff9a051b0559791309da282133bcc6319c/lib/index.js#L21
// Replace with
`webFrame.setVisualZoomLevelLimits(1, 1)`

**Comment by ppot** [comment]
When new electron release will be made, we will integrate the required modifications.

**Comment by albinekb** [comment]
Thanks for the info @PerStirpes 💟
