### ISSUE TITLE
Terminal as a library?

### ISSUE THREAD

**Issue by atrauzzi** [zeit/hyper#2317]
Does hyper by any chance break down such that I could integrate it as a viewer for terminal output in my own electron applications?

I'd like to offer the nicest output possible and obviously would like to avoid getting mired in terminal specifics. Especially when it comes to cross platform.

**Comment by albinekb** [comment]
In the future maybe, but in short term, no. There's too much to fix 😄  PR(s) welcome 👍

**Comment by albinekb** [comment]
But if you just want a simple viewer, use xterm.js (that's what we use in hyper 2.x)

**Comment by atrauzzi** [comment]
Awesome, I'll give that a shot!  Definitely takes a lot off my plate and helps me avoid reinventing the wheel.

Would love some day to be able to integrate hyper, but this will do in the meantime.

**Comment by albinekb** [comment]
We're focusing on fixing bugs and releasing 2.0, after that we can tackle breaking it up into a frontend-only version of `hyper` that could be used in Atom, web pages (over sockets) etc. and an electron version of hyper that uses that lib.

But as I see it now it's pretty far off @atrauzzi. Too many other important things (bugs and compatibility) that blocks.

**Comment by atrauzzi** [comment]
No problem at all, my use case is so simple, it won't hinder me.  If/when that day comes, I'll be there ;)
