### ISSUE TITLE
Right clicking the mouse in Hyper v2.+ doesn't paste the clipboard contents 🙃 

### ISSUE THREAD

**Issue by spences10** [zeit/hyper#2318]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro v1703
- **Hyper.app version**: @latest
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://github.com/spences10/dotfiles/blob/master/.hyper.js
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

Right clicking the mouse in Hyper v2.+ doesn't paste the clipboard contents 🙃 

I have downgraded to Hyper v1.+ now

Thanks for all the awesome work 👍

**Comment by bcorcoran** [comment]
I know it would take some getting use to, but you should be able to press CTRL+SHIFT+C/V to  copy/paste in Hyper on windows. CTRL+C is reserved for interrupt and [CTRL+V](https://en.wikipedia.org/wiki/Control-V) is not related to pasting at all.

**Comment by spences10** [comment]
@bcorcoran but, but, it works in v1.4.8 why no workee in v2.+ 🙃

**Comment by chabou** [comment]
Fixed buy #2392
