### ISSUE TITLE
neovim disploay is not correct

### ISSUE THREAD

**Issue by allegewhd** [zeit/hyper#2320]
-
        Hyper 1.4.8
        Electron 1.7.8
        darwin x64 17.0.0

        neovim: v0.2.1-dev installed by `homebrew` on macOS high sierra. 
My os language is Japanese. It seems that Asian characters(Japanese) do not displayed correctly. 

![jietu20171003-150450 2x](https://user-images.githubusercontent.com/507625/31111997-38fd30ac-a84c-11e7-8720-272ee68d0dad.jpg)

**Comment by chabou** [comment]
Please give us some explanation. Or maybe a iTerm/Terminal screenshot comparison.
Can you try to reproduce on 2.X canary release?

We don't speak japanese/chinese/Korean... Hard to understand your issue

**Comment by allegewhd** [comment]
Sorry about that. On v2.0.4, everything looks well:)

**Comment by chabou** [comment]
Glad to know that ! :tada:
