### ISSUE TITLE
problem with the hyper-match plugin

### ISSUE THREAD

**Issue by MAPESO** [zeit/hyper#2321]
- **OS version and name**: macOS high sierra and Windows 10
- **Hyper.app version**: 1.4.8 and canary version(2.0.4)

Disables writing in Hyper
 
Windows 10
![22219451_1149860821824173_744382452_o](https://user-images.githubusercontent.com/16585386/31116021-20168c94-a7ea-11e7-9d46-80dcb5d03d2a.png)

macOS
<img width="1280" alt="screen shot 2017-10-02 at 19 48 30" src="https://user-images.githubusercontent.com/16585386/31116040-30f6d2b2-a7ea-11e7-93e6-d2b72f84b287.png">

**Comment by chabou** [comment]
This issue should be opened in plugin repo
