### ISSUE TITLE
[v2] CJK languages not working

### ISSUE THREAD

**Issue by simba3447** [zeit/hyper#2322]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.1
- **Hyper.app version**: 2.0.4(canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/simba3447/3cda5d01834a6ace320d40ed1f8277dd
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: YES

## Issue

I'm using canary version and CJK languages don't work.
CJK file names are replaced with question marks. 
And when I type CJK, they are displayed as utf-8 unit code style(This error occurs when I use distributed version, not when I build v2 source and run it.).
I tested for Korean, Chinese, Japanese and All of them didn't work.
I hope this could be fixed 😢
<img width="655" alt="2017-10-03 7 10 47" src="https://user-images.githubusercontent.com/17214451/31120240-a842a682-a86e-11e7-9fb8-9936e5a6f065.png">
![capture](https://user-images.githubusercontent.com/17214451/31120264-c1094964-a86e-11e7-83db-c14941501ffc.gif)

**Comment by chabou** [comment]
Please your `locales` and retry with our last canary.

**Comment by trainto** [comment]
@chabou 
I tried canary.15, but it's still not fixed at all.
I'm on macOS and it's Korean version.
Every file name with Korean characters are dispalyed with question marks like ???????.txt,
and when i try to type any Korean characters, it displays exactly same with attached screenshot above.

**Comment by trainto** [comment]
@chabou
I found work-around for this.
I just checked my locale, which is "ko_KR.UTF-8", and set this to env option in .hyper.js like
env: {LANG: 'ko_KR.UTF-8'}

and everything works fine~~~

Maybe it could be made to detect system locale and set it to .hyper.js automatically when the .hyper.js first created.

**Comment by Stanzilla** [comment]
Good info about macOS issues with Korean and Japanese: https://github.com/zeit/hyper/issues/586#issuecomment-263837464

**Comment by Paalon** [comment]
Which version of hyper fixes this behavior?

**Comment by ypresto** [comment]
I still get `??????` by `ls` for file name with Japanese characters.
I'm using Hyper 2.0.0 (stable).

**Comment by chabou** [comment]
@ypresto your specific issue should have been fixed in our last canary. Thanks to https://github.com/zeit/hyper/pull/2913

**Comment by ypresto** [comment]
Updated to canary and confirmed fix! Thanks!

**Comment by Beingbook** [comment]
By default `Hyper 2.1.2` on Mojave is not able to input and composition Korean.
Adding `env: {LANG: 'ko_KR.UTF-8'}` as afore comment fix this.
