### ISSUE TITLE
Bug - Emacs added caracters

### ISSUE THREAD

**Issue by rohidjetha** [zeit/hyper#2326]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS High Sierra**: 
- **Hyper.app 2.0.4**: 

## Issue

I have an issue, when i'm connecting in SSH to my server and want to do some modifications on a file with emacs, the time that the file is opening in emacs, if I want to go down on the file and I push the bottom arrow, a "B" is written at the beggining of the file.

**Comment by rgstephens** [comment]
I'm using Sierra and Hyper 2.0.4 and couldn't duplicate this issue when I ssh into a Debian system and edit a file with emacs.  Down arrow worked correctly, no "B" written to the file.

**Comment by rohidjetha** [comment]
I made a GIF so you can see.

Here's the GIF: http://recordit.co/qisLZuwDjX

I click on down arrow just after I launch my command and it write a "B"

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by rgstephens** [comment]
Fixed!  Thanks.
