### ISSUE TITLE
Autocomplete causes command to be displayed twice

### ISSUE THREAD

**Issue by codeofsumit** [zeit/hyper#2328]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra
- **Hyper.app version**: Hyper 1.4.8 (stable)

## Issue

![hyper bug](https://user-images.githubusercontent.com/2399810/31173192-e5409de4-a906-11e7-9006-8109958bf647.gif)

When I press `tab` to autocomplete / choose a directory, the typed command is doubled. It still works but it’s wrong visually.
Using v1.4.8 but I have this since I started using hyper some months ago.

**Comment by TotomInc** [comment]
Having the same issue... No status since october?

**Comment by mrpinkcat** [comment]
Me too... Did you found a fix ?

**Comment by chabou** [comment]
Can you give us your LANG env var: `echo $LANG`

I fixed this issue with this workaround: https://github.com/zeit/hyper/issues/283#issuecomment-370566088

**Comment by mrpinkcat** [comment]
`fr.UTF-8`

Thanks

**Comment by chabou** [comment]
YES! We found this bug. I have no idea why LANG is wrongly set and how this side effect happens... But this is a real progress!

**Comment by TotomInc** [comment]
Thanks @chabou, I've set my `.zshrc` to export my `$LANG` to `fr_FR.UTF-8` and it now works fine!

**Comment by Hecsall** [comment]
Same error and exporting the right LANG in my .zshrc solved the issue.
Just to write down for other people:

While having the issue, "echo $LANG" was printing 
**it.UTF-8**

Then i added "export LANG=it_IT.UTF-8" at the bottom of my .zshrc file, restarted the terminal, and then "echo $LANG" printed
**it_IT.UTF-8**

After this the issue was solved

**Comment by chabou** [comment]
@Hecsall Thank you for your confirmation 🎉 

We need to enforce defaut right locales. There are some related but maybe outdated PRs.
But It should be definitely fixed soon without user action required
