### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jq-87** [zeit/hyper#2329]
- **OS version and name**: 10.12.5 - MacOS Sierra
- **Hyper.app version**: 1.4.8

## Issue
In iTerm I can search hit (cmd + f) to search my current window.

Is there no search in hyper?

**Comment by MAPESO** [comment]
@jq-87 Here are the plugins for hyper, I could search to see if anyone in the community already did.

https://github.com/bnb/awesome-hyper

**Comment by amorriscode** [comment]
@jq-87 Here is a plugin for search in Hyper: https://github.com/jaanauati/hyper-search

**Comment by jq-87** [comment]
^ That plugin seems to have issues - it does not work for me and other people are also saying the same thing.

They have an open issue:
https://github.com/zeit/hyper/issues/1121

**Comment by MAPESO** [comment]
@jq-87 The developer will need to update the plugin.

**Comment by Stanzilla** [comment]
We also have this https://github.com/zeit/hyper/pull/1793 but not sure if @stephencookdev is willing to update it.

**Comment by jq-87** [comment]
ok I will close this - since #1793 exists
