### ISSUE TITLE
[Canary] shortcuts not working

### ISSUE THREAD

**Issue by patrik-piskay** [zeit/hyper#2333]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Sierra
- **Hyper.app version**: 2.0.4 (Canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/patrik-piskay/94385f24014c0fed1c65bd3fed68469c
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Video: https://cl.ly/1P2l2K1j3009

Shortcuts are not working for me, it's not very clear on the video as there is no visible indicator of keys pressed but after creating 4 tabs and trying to switch between them with `cmd+1/2/3/4`, nothing happens. Also after typing some characters, trying to `alt+backspace` or `cmd+backspace` should remove the whole string but only native backspace behaviour happens (deleting only one char).

Thanks!

**Comment by viktor-evdokimov** [comment]
There is existing ticket for this https://github.com/zeit/hyper/issues/2279, it also mentions that as a workaround right now you can use `CMD + SHIFT + [ or ] `
