### ISSUE TITLE
Open new tab on same dir

### ISSUE THREAD

**Issue by pedrorijo91** [zeit/hyper#2334]
- [X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- OS X 10.12.6
- 1.4.8 stable

## Issue
I'm been looking but couldn't find an option to open a new tab on the same dir as current tab (it always opens a new tab at home dir). Is there any config for this? Or should I look for some plugin?

**Comment by MAPESO** [comment]
@pedrorijo91 You can search in this list of plugins 😄 

https://github.com/bnb/awesome-hyper/pull/284
