### ISSUE TITLE
Title text override buttons

### ISSUE THREAD

**Issue by dungwinux** [zeit/hyper#2336]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 64-bit
- **Hyper.app version**: 1.4.8 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/dungwinux/f86c153d9a9821dff6c62ca5aa558ab9
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

While I was trying to reach the limit of characters in Title, the title text overrided [Minimize] Button and [Maximize] Button. Although the button could still be interact with but the visual is horrible.
![image](https://user-images.githubusercontent.com/23451424/31329214-36b24f56-ad03-11e7-809e-3533b88b1630.png)
What I did was writing this line:
>`title testtttttttt`
and increasing number of the 't' characters.

**Comment by chabou** [comment]
Thank you for your feedback.

Fix has already been merged into master/canary https://github.com/zeit/hyper/pull/2289
And it will be landed in next stable|canary release

**Comment by jonorozcoc** [comment]
![image](https://user-images.githubusercontent.com/8442497/51859445-1f648200-2305-11e9-9134-18befac8900d.png)

Windows 10
hyper 3.0.0 canary 6
