### ISSUE TITLE
Is there a `apt get` or `brew install` option for Hyper?

### ISSUE THREAD

**Issue by spences10** [zeit/hyper#2339]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: w10 with WSL
- **Hyper.app version**: 1.4+
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Is there a `apt get` or `brew install` option for Hyper?

This is a [duplicate](https://github.com/zeit/hyper/issues/799) which has been closed but there doesn't seem to be a package in either Linuxbrew or via `apt get`

Thanks

**Comment by albinekb** [comment]
#799 is not closed? 🤔  

No, not as of now. 

- Windows .zip with installer, you get auto updates
- macOS: Just download the latest .zip or .dmg and run the app, no setup required.
- Linux: AppImage maybe? We we're looking at doing a Snap also, but as none of the core team use linux it went into the sand.

Build from source is your best option for now.. AFAIK (And that's why people chose to use linux, right? 🤔  😄 )

**Comment by spences10** [comment]
touché

**Comment by albinekb** [comment]
We should still try to make it easier @spences10 😎  Do you have any suggestions?

**Comment by spences10** [comment]
@albinekb I'm no `apt get` packager and it not a rabbit hole I can go down right now. 

And as no one else on the core team is either then I guess this will remain so until someone else with the requisite skills to do so decides that they want it available via `linuxbrew`/`homebrew` or `apt get`. 

But they'd probably compile it from source 🤷‍♂️ 

Thanks all the same

**Comment by jcrben** [comment]
For linux users, there is a nix package (https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/hyper/default.nix):
`nix-env -i hyper`

Nix does work on darwin, so it's possible that this package could be made cross-platform... I'll probably look into that eventually.
