### ISSUE TITLE
On Windows, Edit --> Preferences returns JScript errror 

### ISSUE THREAD

**Issue by musikele** [zeit/hyper#2340]
On windows 10, clicking on Menu --> Edit --> Preferences... I receive an error from Winddows Script Host:

Script: c:\Users\miche\.hyper.js 
Row: 1
Character: 1
Error: <incomprensible characters> it's not defined 
Code: 800A1391 
Origin: Microsoft JScript run-time error 

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by albinekb** [comment]
Yes, you need to change your default editor for `.js` files, see https://msdn.microsoft.com/en-us/library/hy2sthf1(v=vs.100).aspx for reference :)

We will make this better in the future, but for now this is the best solution.
