### ISSUE TITLE
All text turns to unrenderble unicode.

### ISSUE THREAD

**Issue by cjavad** [zeit/hyper#2341]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Elementary os loki 0.4.1 
- **Hyper.app version**:  I am on the latest version 2.0.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Yop here](https://gist.github.com/JavadSM/c103a1971020e0034b20f30c70a0d309)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: [Another Gist](https://gist.github.com/JavadSM/6b2c9bf84a6e9302aa92f01e9ffc78f0)
- **The issue is reproducible in vanilla Hyper.app**:  Yes

## Issue

Yeah so what happend is that i  typed:
    cat /etc/*
and then this happend 
![skaermbillede fra 2017-10-10 15 40 50](https://user-images.githubusercontent.com/22474016/31390381-091421e2-add4-11e7-9067-78b9d19f974e.png)
![skaermbillede fra 2017-10-10 15 44 17](https://user-images.githubusercontent.com/22474016/31390382-092e0346-add4-11e7-9328-3d4a7962eee0.png)
![skaermbillede fra 2017-10-10 15 51 31](https://user-images.githubusercontent.com/22474016/31390383-09504ece-add4-11e7-866e-ed1ff45b9e88.png)
![skaermbillede fra 2017-10-10 15-40-28](https://user-images.githubusercontent.com/22474016/31390384-09690658-add4-11e7-91e8-70c27612075b.png)
![skaermbillede fra 2017-10-10 15-40-39](https://user-images.githubusercontent.com/22474016/31390385-098169be-add4-11e7-8c2b-59729ceff0b4.png)
![skaermbillede fra 2017-10-10 15-40-40](https://user-images.githubusercontent.com/22474016/31390386-099aad20-add4-11e7-8728-353cc128fafa.png)
![skaermbillede fra 2017-10-10 15-40-42](https://user-images.githubusercontent.com/22474016/31390387-09b2d53a-add4-11e7-8978-b9725f48beff.png)
I dont know if it is the same on windows or macos or just a problem with elementary patheon gtk
but what happens is that all text after reading some kind of binary/unicode file goes nuts.

and yes its completely reproducible in linux.

**Comment by JavadSM** [comment]
On a note it might have something to do with the recent unicode/css problem

**Comment by JavadSM** [comment]
Ups
