### ISSUE TITLE
hyper does not take current working dir

### ISSUE THREAD

**Issue by qtbit** [zeit/hyper#2343]
When I run Hyper.exe (in env path) from a working directory, it starts with default directory `C:\Users\<user_name>` (home dir) and not with the current working directory Hyper is started from.

**Comment by MAPESO** [comment]
@qtbit  Could you tell me the version of your operating system.

**Comment by qtbit** [comment]
Windows 10, node v8.5.0

**Comment by qtbit** [comment]
It's the same as opening a new tab with Ctrl+Shift+T. It opens in default location `C:\Users\<user_name` and does not copy the path from the previous tab where I was before :-(

**Comment by lemongrassnginger** [comment]
I'm having a similar problem. 

Trying to start Hyper from a script by adding it to the PATH variable but I can't find a way to set the working directory so it keeps opening up in the default directory.  

Windows 10. Hyper v1.4.8 (stable), No plugins

**Comment by lemongrassnginger** [comment]
if for example I want to open Hyper from a directory in Windows Explorer I can select "Open Hyper here" from the context menu. If I open Hyper from the command line in that directory, it defaults to my home directory

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/1213
