### ISSUE TITLE
Windows SyntaxError notification is truncated

### ISSUE THREAD

**Issue by dirocco** [zeit/hyper#2346]
- **OS version and name**:  Windows 6.1.7601
- **Hyper.app version**: 2.04
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
The SyntaxError notification is cut off in Windows 7, making it difficult to figure out how to find the error.

![hyper-error](https://user-images.githubusercontent.com/281000/31444441-3d132042-ae6a-11e7-818d-057dcbc9a0a2.png)

**Comment by albinekb** [comment]
Nice catch @dirocco 

We should move everything after `:` to the sub-text like the config update.
