### ISSUE TITLE
"The is no script engine for file extension ".js". error when accessing Preferences, Windows 7

### ISSUE THREAD

**Issue by 2hands10fingers** [zeit/hyper#2349]
-
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 6.1.7601

I can't seem to get this to work. I just downloaded Hyper for the first time on my Windows 7 64-bit machine. When I click Preferences, I get the error "There is no script engine for file extension ".js".

**Comment by MAPESO** [comment]
@2hands10fingers  Hi, I'll take a look at your problem. Could you share a photo of the problem 😄

**Comment by 2hands10fingers** [comment]
@MAPESO Here you go. https://imgur.com/a/0iDyn

It happens immediately after clicking "Preferences" or using the Hot Key for that

**Comment by albinekb** [comment]
This error is from your **OS**, **windows** in this case. You need to set a default editor for .js files as **microsofts** default is not capable of showing the source. https://support.microsoft.com/sv-se/help/4028161/windows-10-change-default-programs
