### ISSUE TITLE
updateChannel config param should be hot reloaded

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2351]
When user change `updateChannel` setting to `'canary'`, for example, it should change Hyper behaviour instantly and should not require a restart.
Feed URL should be changed on the fly, and a new update check should occur directly after this config reload.

**Comment by MAPESO** [comment]
@chabou The idea is pretty good. But vscode when updated asks to restart 🤔

**Comment by chabou** [comment]
This not what I meant.
User should obviously restart after an update.
What I meant is to not have to restart Hyper after a config change.

**Comment by MAPESO** [comment]
@chabou  I understand :D

**Comment by chabou** [comment]
https://zeit.co/blog/canary
I don't want to read, for `Now desktop`
>Once the preference is checked, it will be applied immediately - no restart required.

and for `Hyper`
> After that, restart the application

**Comment by KevinRLeC** [comment]
Been looking into this for the last couple days. The code isn't a big change but it seems like testing the `autoUpdater` is more difficult than I originally expected. Code signing on Mac is all new to me! Is there a way to test that this is working without getting a `Developer ID Application` so code signing works properly? It's quite expensive to enroll in the program through Apple.

**Comment by Stanzilla** [comment]
Fixed with https://github.com/zeit/hyper/pull/2408
