### ISSUE TITLE
Change install dir

### ISSUE THREAD

**Issue by ftaut** [zeit/hyper#2352]
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hey guys,

i couldnt find any related issue to my question. But if its still a duplicate please excuse me.
I wonder if its possible to install hyper on a usb drive.

Is there any command to specify the installation folder?

Thank you

**Comment by AndyBitz** [comment]
I don't think that there's a way specify the install path.
You can however, after installing, copy the hyper directory to your usb drive and use it as a portable version.

Folder ist at `%userprofile%\AppData\Local\hyper`.

**Comment by Stanzilla** [comment]
Nope, Squirrel.Windows does not and never will (https://github.com/Squirrel/Squirrel.Windows/issues/1002) allow this.

**Comment by DRSDavidSoft** [comment]
@Stanzilla That's too sad, I hope they change their opinion for at least adding a CLI option to specify the path.

**Comment by Stanzilla** [comment]
I don't think so, the whole goal of Squirrel was a one stop shop solution that works out of the box. There is a consideration to be made to maybe switch to NSIS since that would also fix some other problems we have AND is the preferred supported installer in electron-builder anyway.
