### ISSUE TITLE
Cursor position wrong, happens very often [close me, was an oh-my-zsh issue]

### ISSUE THREAD

**Issue by guy-kdm** [zeit/hyper#2353]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **macOS Sierra 10.12.6**: 
- **1.4.8**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/guy-kdm/2b30268dbf0b21795e5ce6a446564656
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 

## Issue
Hi guys, for the past few days cursor positioning, particularly in line overflow and word move/delete (option+backspace) situations gets out of hand very often, to the point of hyper not being usable. 
<img width="455" alt="screen shot 2017-10-12 at 16 18 09" src="https://user-images.githubusercontent.com/5744717/31497957-52feda68-af69-11e7-8bb8-3a0a72570ad4.png">
Happens in vscode's integrated terminal and regular hyper. 

Love,

**Comment by yousefissa** [comment]
@guy-kdm Did you figure out how to fix this?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
