### ISSUE TITLE
Preferences Broken

### ISSUE THREAD

**Issue by joebologna** [zeit/hyper#2355]
-
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 6.1.7601

When trying to open preferences menu (select the menu or Ctrl-,), I get this error:

Windows Script Host
Script: C:\Users\joeb\.hyper.js
Line: 5
Char: 1
Error: 'module' is undefined
Code: 800A1391
Source: Microsoft JScript runtime error.

I'm running Windows 7 Enterprise

**Comment by MAPESO** [comment]
@joebologna This topic is already done, I ask you to close this topic. https://github.com/zeit/hyper/issues/2349

**Comment by MAPESO** [comment]
This error is from your OS , windows in this case. You need to set a default editor for .js files as microsoft 's default is not capable of showing the source. https://support.microsoft.com/sv-se/help/4028161/windows-10-change-default-programs

feel free to re-open if you need more help than that.
@albinekb

**Comment by joebologna** [comment]
I see... I wasn't aware Hyper was trying to open a .js file so I could edit it. Set .js to open using Atom :) - works now.
