### ISSUE TITLE
UTF-8 encoding & `zh-Hans` bug?

### ISSUE THREAD

**Issue by xgqfrms-gildata** [zeit/hyper#2356]
-
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.15063

# UTF-8 encoding & `zh-Hans` bug?

![image](https://user-images.githubusercontent.com/29531779/31530023-e1eb485a-b00f-11e7-9020-4c87d32280dc.png)

**Comment by chhschou** [comment]
Might be OS specific, it works fine in Ubuntu 16.04 (hyper version 2.0.3)

**Comment by albinekb** [comment]
Try switching to canary https://zeit.co/blog/canary (2.x.x), where we have switched out hterm to xterm.js which handles this better.

**Comment by cybertk** [comment]
Same issue here with

```
Hyper 1.4.8
Electron 1.7.8
win32 x64 10.0.15063
```

**Comment by cybertk** [comment]
Confirmed v2.1.1 fixed this issue

**Comment by albinekb** [comment]
@xgqfrms-gildata can you confirm 2.x is working for you too and close if it does? 🙂  Thanks!
