### ISSUE TITLE
Preferences Menu is not opening.

### ISSUE THREAD

**Issue by rpofficial** [zeit/hyper#2361]
Preferences menu is not opening but showing this window.
![screenshot_1](https://user-images.githubusercontent.com/28060683/31577333-2f4097fc-b12a-11e7-8b9b-41f5cd525752.png)

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.15063

**Comment by Stanzilla** [comment]
Duplicate

**Comment by albinekb** [comment]
thanks @Stanzilla 

here's the solution @rpofficial https://github.com/zeit/hyper/issues/2355#issuecomment-336414688
