### ISSUE TITLE
Unkillable frozen window

### ISSUE THREAD

**Issue by rubdub** [zeit/hyper#2362]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Version 1.4.8: After a few times waking up and sleeping my surface book with hyper open, the terminal windows goes completely unresponsive and I can't kill it via task manager as shown in the below screenshot.

https://imgur.com/a/3sDst

The only way to kill the window is to restart windows 10. 

Any thoughts?

**Comment by MAPESO** [comment]
@rubdub  Hi 😸 I recommend that you **remove the hyper and reinstall** it. If the error persists, let me know.

**Comment by rubdub** [comment]
Hi, I'm still running into the terminal freezing. Any diagnostics, I should look at?

**Comment by albinekb** [comment]
>The only way to kill the window is to restart windows 10.

Sounds like you have a problem with your OS too 😁

**Comment by rubdub** [comment]
Everything else on the machine seems fine. This is the first time I've had a window I can't kill (even via powershell). I tried updating to 2.0.4 as well as building from the lastest on the canary branch. I ran into new error where if I split the window (ctrl+shift+e) and resize the frame, I get a pop up saying "Plugin error, plugins decorating Termgroup have been disabled because of a plugin crash. Check Developer Tools for details." I do and I find this:

https://imgur.com/a/GZBc4

I not running any plugins. Only what I believe to be a clean installation.

**Comment by pauldariye** [comment]
I'm having a similar issue. The hyper window freezes completely and is unresponsive.

**Comment by rubdub** [comment]
The freezing issue happens with version 2.0.4 as well.

**Comment by divyanshu013** [comment]
Can confirm for v2.1.1 too on Fedora 27 x64

Seems to happen more often if I use multiple tabs, especially if some servers are running in each tab. After it becomes unresponsive have to run `pkill hyper` to close hyper

**Comment by drhacko** [comment]
even the `yes` binary breaks hyper because it's so bad at handling.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by guigo2k** [comment]
Hyper version 2.1.2

Running `terraform apply` will freeze Hyper, however, the process will keep running, despite the UI is completely unresponsive.

**Comment by timeyr** [comment]
The problem still persists, currently on Hyper 3.0.2
