### ISSUE TITLE
Hyper config gets overwritten if there's an error

### ISSUE THREAD

**Issue by kbrgl** [zeit/hyper#2363]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13 High Sierra
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: got overwritten by hyper
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
<img width="912" alt="screen shot 2017-10-16 at 11 38 11 am" src="https://user-images.githubusercontent.com/13417496/31597554-9d99b7e6-b266-11e7-8a4e-5cd399312829.png">

- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

When I update my `~/.hyper.js`, Hyper says 'Plugins Updated' and overwrites my config to the default config.
This doesn't happen each time. I'm not when exactly this happens: sometimes on a regular config update, sometimes on a syntax error, etc. Oddly, when I do put an intentional syntax error in my config then it says 'Hyper Configuration Reloaded' and doesn't complain about the syntax error at all. 

This time, I updated a font, and it said 'Plugins Updated' and overwrote the config.

I've completely reinstalled Hyper multiple times, but nothing seems to fix the issue. I'd got it running for a while by installing a much older version, and then updating to the latest version.

Edit: this always happens after Hyper complains of a syntax error

**Comment by kbrgl** [comment]
I'd like to work on this issue. Can someone give me some pointers on where to start?

**Comment by chabou** [comment]
Duplicates #2015 (Fixed in v2)
