### ISSUE TITLE
Error updating plugins. 

### ISSUE THREAD

**Issue by Rawnly** [zeit/hyper#2366]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate (hopefully).

- **OS version and name**: MacOS 10.13
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/Rawnly/4e80b9fea4c400bd62c86e1508efd251/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: True

## Issue

Hi, after I've installed some plugins it gives me this error, I've tried to delete all of them but it is still here. It happens a few seconds after the startup.

I thought to ask here before do a fresh install.

<img width="331" alt="screen shot 2017-10-17 at 16 08 50" src="https://user-images.githubusercontent.com/16429579/31669600-d3709dcc-b355-11e7-92c4-caa0b26a09d6.png">

**Comment by MAPESO** [comment]
@Rawnly  Hi, possibly the plugins that are causing problems are cached, I recommend removing Hyper and reinstalling, it if the problem persists let me know

**Comment by RichDonnellan** [comment]
You could also try removing `node_modules` and `package-lock.json` from `.hyper_plugins` and then reinstall using your package manager of choice. Make sure you're in the `.hyper_plugins` directory when doing so.

**Comment by Rawnly** [comment]
> You could also try removing node_modules and package-lock.json from .hyper_plugins and then reinstall using your package manager of choice. Make sure you're in the .hyper_plugins directory when doing so.
&mdash; @RichDonnellan  

I've did it but still got the error, so, I've solved it by removing Hyper and reinstalling it.
