### ISSUE TITLE
Console prompt can't keep up

### ISSUE THREAD

**Issue by NomNuggetNom** [zeit/hyper#2368]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 x64 Build 15063
- **Hyper.app version**: 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/NomNuggetNom/b71dcd3984117c1a949315339b48f03b
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When the console receives a large number of lines quickly, it desyncs and stops scrolling down, essentially breaking the prompt. For example, when running the following:
```bash
for ((i=1; i<=5000; i++)); do
   echo $i
done
```
My console never makes it to the end. For example:
![Console](http://nom.codes/i/r/rkxBM)

In fact, even when I try to force the prompt down, it [doesn't make it](http://nom.codes/i/r/6OuB6) all the way ([normal prompt](http://nom.codes/i/r/nbXW9) for reference). The scroll bar also stops working - I have to scroll up first to be able to scroll down.

This happens when using a git bash shell and when using the native Windows shell.

**Comment by albinekb** [comment]
Hi! Thanks for creating this issue. We are working hard on the soon-to-be-released 2.0 version of hyper. One of the main upgrades is our terminal rendering library. In 1.x we use `hterm`, 2.x will be shipped with `xterm.js`, which is a much more mature library, and gives us better performance out-of-the-box. 

We have also implemented "debouncing/throttling" of the terminal stream, which helps a lot.

Id like you to try this in 2.x and see if you notice any difference, you can read on how to try 2.x via our `canary` release channel here: https://zeit.co/blog/canary

**Comment by albinekb** [comment]
Here's more on this topic: https://github.com/zeit/hyper/issues/687

**Comment by NomNuggetNom** [comment]
Hey @albinekb, thanks for the quick reply. Great news! The problem is totally fixed in 2.x - could not reproduce it at all. 👍

**Comment by albinekb** [comment]
Let's close this one, performance will be even more increased with xterm.js 3 (released in some months), it renders using webgl/canvas. 

🙌
