### ISSUE TITLE
Hyper starts in my User folder instead of $HOME for Zsh on Windows

### ISSUE THREAD

**Issue by OmriSama** [zeit/hyper#2369]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10,  Build 1709
- **Hyper.app version**: Latest

Here is my hyper.js file:
https://gist.github.com/OmriSama/5193f8bfff4371369cc3ae3d30f56781

## Issue

Hi everyone. I spent a good chunk of time today updating my Windows 10 to the latest version so I could use `wsl.exe` instead of `bash.exe`; now I have `zsh` set as my default shell and after getting annoyed with Cmder I decided to give Hyper another try (although start up times are slow, it does look really nice).

An issue:

Albeit slow, context menu "Open Hyper Here" works fine.
What doesn't work fine is a normal startup from say, a shortcut I have on the Taskbar. My default shell is set to `wsl.exe` and yet still, my normal terminal window starts in `$HOME` while my Hyper decides to start up in `Users/myusername`. 

This is really confusing and I have no idea why it's doing this. I'm very tempted to get the Dev build going so I can maybe debug it? But I was hoping someone here would have insight first...

Thanks everyone

**Comment by albinekb** [comment]
one step of the issue template is to copy your .hyper.js contents to a gist (or similar), could you do that? 

1. So everyone can know and reproduce your env, how you have configured wsl.exe for example (in .hyper.js)
2. So i can see if you have added `--login` or not to shellArgs and not have to ask you 👍 

https://github.com/zeit/hyper/blob/canary/app/config/config-default.js#L92

**Comment by OmriSama** [comment]
@albinekb hi! I added it in the OP. Let me know :)

**Comment by mwcarew** [comment]
Having the same issue but I'm on canary. https://gist.github.com/mwcarew/1562f88dd6af1d233d7704044714638b

**Comment by jimv3** [comment]
If I do this "shellArgs: ['~']" then hyper launches in my WSL home on Windows instead of the Windows user directory.

**Comment by mwcarew** [comment]
I'm not on my home PC for a while and can't mess with this, but would that affect my launch location if I'm right-clicking in Explorer to use the context option "Open Hyper here"? I'd imagine I'd now start in my home directory regardless.

**Comment by jimv3** [comment]
On my machine it opens in my WSL home even from explorer.

**Comment by mwcarew** [comment]
OK yeah. Not quite the behavior I'm hoping for from it.

**Comment by sandangel** [comment]
How can I set an default startup folder like D:\Works instead of '~'
I'm using Git bash because wsl is very slow on node process

**Comment by Stanzilla** [comment]
See also https://github.com/zeit/hyper/issues/1133

**Comment by MadushanLamahewa** [comment]
Open .zshrc file using vim or nano, at the bottom, add :  
`cd ~`
Save and restart Hyper Terminal

**Comment by benc-uk** [comment]
Fix I found was to use this `shellArgs: ['-c', 'cd ~ && zsh']`

**Comment by mrchief** [comment]
@benc-uk solution is nice! I can keep bash and use zsh in hyper (better than `chsh` to zsh). Note that if you use shell args, make sure your shell points to  `'C:\\Windows\\System32\\bash.exe'`. Pointing it to `'C:\\Windows\\System32\\wsl.exe'` will cause hyper to quit as soon as it launches.

**Comment by benhillis** [comment]
If you're trying to use wsl.exe, keep in mind it has it's own argument parsing rules (which are different than bash.exe which passes everything along to /bin/bash).
```

    shell: 'C:\\Windows\\System32\\wsl.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
    // by default `['--login']` will be used
    shellArgs: [],
```

**Comment by benc-uk** [comment]
The wsl.exe method is a lot better than my workaround :)

**Comment by mrchief** [comment]
@benc-uk That depends. E.g., I use fish/zsh shell. If I change my shell to fish/zsh via `chsh`, and then use `wsl.exe`, what I found is not everything works as expected - especially with node version manager switching versions, or installing node modules. However, if I launch bash and then switch to fish/zsh (either manually or via bashrc), things work a lot better.

Further, if there are scripts/packages that expect bash to behave like bash, `chsh` kind of interferes with that.

**Comment by richeney** [comment]
Slight variant of Ben's that I've just tested out.  It replaces the current shell rather than going into a child shell:
```
    shell: 'C:\\Windows\\System32\\bash.exe',
    shellArgs: ['-c', 'cd ~ && exec $SHELL'],
```

**Comment by benc-uk** [comment]
I was just revisiting my hyper.js config and the bash.exe route I was using bugged me slightly. 
After some trial and error the most elegant solution I've found so far is this
```
    shell: 'C:\\Windows\\System32\\wsl.exe',
    shellArgs: ['~']
```
It's better IMO than starting bash to then launch another shell, the startup seems fractionally faster

**Comment by Stanzilla** [comment]
`bash.exe` is deprecated anyway, everything should go through `wsl.exe`

**Comment by TJVaughn** [comment]
This is my shell:
`shell: 'C:\\Windows\\System32\\bash.exe',`

I removed the `--login` from 'shellArgs' and added the code below
`shellArgs: ['-c', 'cd ~/../../mnt/d/hauck/code/react-apps/ && exec $SHELL'],`

Now it opens to the file I desire.

**Comment by Stanzilla** [comment]
@TJVaughn stop using bash.exe, wsl.exe instead

**Comment by HymanZHAN** [comment]
@Stanzilla If that's the case the `hyper.js` config file should be updated accordingly. Otherwise, the helper text makes it quite confusing. Last time I checked it still said the following:
```js
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
```

@benc-uk Thanks for your answer. `wsl.exe` with `~` shellArgs works perfectly with zsh.

**Comment by Stanzilla** [comment]
Yup!

**Comment by blisst** [comment]
This was the best solution for me if I wanted to start in D:\Coding

    shell: 'C:\\Windows\\System32\\bash.exe',
    shellArgs: ["-c", "cd /mnt/d/Coding && exec /mnt/c/Windows/System32/wsl.exe"]

**Comment by emmiep** [comment]
I find this really annoying, but I found one possible solution. [Running `[distribution.exe]`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#launch-wsl-by-distribution) instead of `wsl.exe` or `bash.exe` always make you start in `$HOME`.

For instance, I'm using Debian so I'm having this configuration

```js
{
  shell: "debian.exe",
  shellArgs: []
}
```

The downside is if you switch your default distribution you have to update `.hyper.js`, but if you only ever use one distro it's probably not a big deal.

**Comment by dracos** [comment]
That works for starting directly, but breaks the right click "Open Hyper here" link; it always opens the home directory.
What worked for me was to alter the shortcut you have (on the taskbar, wherever) so that its target is `...Hyper.exe \\wsl$\Ubuntu\home\matthew` (changing to your own distro/homedir of course). This maintains it working from Explorer and launches in the linux home directory when starting that shortcut directly.

**Comment by ProcrastinatingEntrepreneur** [comment]
> Adding `cd ~` to your .zshrc causes problems elsewhere (e.g. using WSL Bash in VSCode). Simple fix I found was to use this in my hyper config
> 
> ```
> shell: 'C:\\Windows\\System32\\bash.exe',
> shellArgs: ['-c', 'cd ~ && zsh']
> ```


Thank you! You solved all my problems!

**Comment by pgThiago** [comment]
@benc-uk You da best. Thank you!!

**Comment by nessun-dorma** [comment]
`shellArgs: ['-d','distroName','--cd','~']` Works ✌️

**Comment by moralesddios** [comment]
shellArgs: ['~', '-d', 'Debian'] Works!!
