### ISSUE TITLE
Can you implement SSH agent forwarding?

### ISSUE THREAD

**Issue by ryanmortier** [zeit/hyper#2373]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 1709 Build 16299.19
- **Hyper.app version**: 1.4.8

## Issue
Is there any way to implement SSH agent forwarding when sshing to a server using Hyper?

This is the one thing I'm missing from being able to replace PuTTY completely.

Many Windows applications seem to be able to use SSH agent forwarding of PuTTY private keys like SQLyog, WinSCP, etc.

**Comment by chabou** [comment]
For command line tool, this is a shell issue.

You need to do something like this: https://help.github.com/articles/working-with-ssh-key-passphrases/#auto-launching-ssh-agent-on-git-for-windows

For other GUI tool, you need to have your Putty `Pageant` launched
