### ISSUE TITLE
Extensions that only expose a `decorateBrowserOptions` method throws Plugin error

### ISSUE THREAD

**Issue by UltCombo** [zeit/hyper#2377]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu GNOME 16.04.3
- **Hyper.app version**: 2.0.4 (pre-release)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: (only includes a local plugin)
- **Relevant information from devtools** no errors in the console
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

When developing a plugin that only exposes a `decorateBrowserOptions` method, for instance:

```js
exports.decorateBrowserOptions = options => options;
```

Hyper will throw the following error and prevent the plugin from loading:

```
Plugin error!
Plugin "plugin name" does not expose any Hyper extension API methods
```

It is possible to work around the issue by exposing any other API method that does not necessarily have meaningful effects.

**Comment by albinekb** [comment]
Fix will come with next canary release, and later in 2.x (stable) 👍 Thank you again @UltCombo for taking your time to write this issue and the accompanying fix (PR)! 🥇

**Comment by UltCombo** [comment]
No problem. 😄 Thanks for reviewing so quickly and for the awesome project! 🏆

**Comment by albinekb** [comment]
It's awesome because people like you 👊  @UltCombo 
Open Source Teamwork 💯
