### ISSUE TITLE
I wonder how to play with it?

### ISSUE THREAD

**Issue by WandyLau** [zeit/hyper#2379]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I found this terminal is cool and I install it in my mac. But I can not find anything to start to play.
No doc, doc tutorial and no examples. How can I start playing this?

**Comment by albinekb** [comment]
Hyper website, including (old-ish) docs https://hyper.is/

Examples are all over the web, search for `hyper` in npmjs.org for example 👍  there's one here https://github.com/zeit/hyperpower

**Comment by albinekb** [comment]
![image](https://user-images.githubusercontent.com/5027156/31847273-58b2a0b4-b619-11e7-8737-472bd2835613.png)

We also have this section at the bottom of the readme, where you can find an example theme, and a link to `Awesome Hyper` - a list of awesome plugins and themes for hyper.

**Comment by WandyLau** [comment]
Thanks for your reply. Yes, I saw these things. But I didnot found any example to start this shell, and how to use it. There are so many pages and examples telling everything about the plugin, how to install it and how cool they are. What I want to know is how to start the shell as what is shown in the examples after the installation. your link does do include this info.

**Comment by basedjux** [comment]
Well.. I guess a question would be is:
Did you install Hyper via building it from source? Or from installing the binary (via the dmg)?

**Comment by basedjux** [comment]
Because both should build a `Hyper.app` and you just have to double click it to run it

**Comment by WandyLau** [comment]
Yes, I found it the lauchpad. Thanks.
