### ISSUE TITLE
unable to scroll up in emacs in Mac

### ISSUE THREAD

**Issue by dongwangdw** [zeit/hyper#2380]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac sierra 10.12.6
- **Hyper.app version**: Hyper 1.4.8

## Issue

I get used to emacs. But I can not use touch pad now, and I can only use up and down arrow. I can not use touch pad to go down directly. And when the terminal is not full screen I can not scroll up to see the content up, and i can also only use the arrow to go down or go up lines. 

Did I miss some config?

**Comment by ShumailAhmed123** [comment]
Hi,
I am computer Science student. I am new to GitHub and I would like to make my first contribution. Anyone here please help me or guide to make my first contribution.
Thanks

**Comment by WandyLau** [comment]
@ShumailAhmed123 Learn to learn. This is the best way.
