### ISSUE TITLE
Hyper is unresponsive when Bash is passed interactive argument

### ISSUE THREAD

**Issue by jonathanbell** [zeit/hyper#2384]
[ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
[ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

**OS version and name**: Ubuntu 16.04
**Hyper.app version**: 1.4.8
**Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/jonathanbell/ec301f638c79196878e955485f132305
**Relevant information from devtools**: 
```
total init time 218.47000000000003
```
```
Uncaught TypeError: Cannot read property 'substr' of null
    at Object.t.colors.crackRGB (bundle.js:47)
    at Object.t.colors.mix (bundle.js:47)
    at r.TextAttributes.syncColors (bundle.js:47)
    at r.TextAttributes.setDefaults (bundle.js:47)
    at r.VT.CSI.m (bundle.js:47)
    at r.VT.dispatch (bundle.js:47)
    at r.VT.parseCSI_ (bundle.js:47)
    at r.VT.interpret (bundle.js:47)
    at r.Terminal.interpret (bundle.js:47)
    at l.forEach (bundle.js:41)
```
**The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

When using  /bin/bash as my shell interactively (`shellArgs: ["-i"]`) Hyper is extremely unresponsive. Typing into the window does nothing. Occasionally, when Hyper is launched it will work after 5 minutes or so but it still has a very slow response to input. I would like to use Bash interactively because I want to source my `.bashrc` file when Hyper is launched. The file is sourced when Hyper launches but the terminal is not usable (cannot type inside the terminal window).

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
