### ISSUE TITLE
How to use Ubuntu.exe for shell config since Windows 10 Fall Creators Update?

### ISSUE THREAD

**Issue by Zx-EvM** [zeit/hyper#2385]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Version: 1709 Build: 16299.19
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Zx-EvM/00466f23dfa35a4a9d0092192c2f955d
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Since Windows 10 Fall Creators Update we need to install Windows Subsystem for Linux from Windows Store: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

I have installed Ubuntu: https://www.microsoft.com/store/p/ubuntu/9nblggh4msv6

For now in `hyper.is` I can use only `shell: 'C:\\Windows\\System32\\bash.exe'`

Today I created issue in Bash on Ubuntu on Windows repository with question about where is `Ubuntu.exe`: https://github.com/Microsoft/BashOnWindows/issues/2586

So, that's really works with VSCode, but when I use this path in `shell` config:

`shell: 'C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps\\ubuntu.exe'`

then hyper terminal just closes.

**Comment by KunalKene1797** [comment]
Try just "bash.exe" though I prefer using "bash" command on power shell to launch bash!

**Comment by Zx-EvM** [comment]
@KunalKene1797 I need to use `ubuntu.exe`. Bash now works fine with `shell: 'C:\\Windows\\System32\\bash.exe'` in config.

**Comment by seppeel** [comment]
```
C:\Users\seppe>ubuntu /?
Launches or configures a linux distribution.

Usage:
    <no args>
      - Launches the distro's default behavior. By default, this launches your default shell.

    run <command line>
      - Run the given command line in that distro, using the default configuration.
      - Everything after `run ` is passed to the linux LaunchProcess call.

    config [setting [value]]
      - Configure certain settings for this distro.
      - Settings are any of the following (by default)
        - `--default-user <username>`: Set the default user for this distro to <username>

    clean
      - Uninstalls the distro. The appx remains on your machine. This can be
        useful for "factory resetting" your instance. This removes the linux
        filesystem from the disk, but not the app from your PC, so you don't
        need to redownload the entire tar.gz again.

    help
      - Print this usage message.
```

**Comment by lycandroid** [comment]
It works if you also set shellArgs: [].  You also don't need absolute path to ubuntu.exe.

    shell: 'ubuntu.exe',
    shellArgs: [],

**Comment by Zx-EvM** [comment]
@lycandroid there is one problem with this. At least on windows with your solution `wsl` will startup with "~" https://github.com/Microsoft/WSL/issues/2587

There is another solution:

```
shell: 'C:\\Windows\\System32\\cmd.exe',
shellArgs: ['--login', '-i', '/c wsl'],
```

**Comment by lycandroid** [comment]
@Zx-EvM Not certain why that is considered a problem in the context of starting a new shell in hyper.   What directory do you want it to start in?

**Comment by Zx-EvM** [comment]
@lycandroid I want to start in current directory where I run Hyper (from context menu):

![29-10-2017 03-28-36](https://user-images.githubusercontent.com/20873402/32142677-52f65a80-bc59-11e7-9b7d-2c0c6d93920f.png)

**Comment by lycandroid** [comment]
OK, but you can just set it to run wsl.exe directly:

    shell: 'wsl.exe',
    shellArgs: [],

**Comment by Zx-EvM** [comment]
I didn't thought about that we can just remove `--login` flag. Thanks.

But why do we need this flag in the config?

**Comment by Zx-EvM** [comment]
@lycandroid I didn't thought about that we can just remove `--login` flag. Thanks.

But why do we need this flag in the config?

**Comment by Zx-EvM** [comment]
@lycandroid I didn't thought about that we can just remove `--login` flag. Thanks.

But why do we need this flag in the config?

**Comment by Zx-EvM** [comment]
@lycandroid I didn't thought about that we can just remove `--login` flag. Thanks.

But why do we need this flag in the config?

**Comment by lycandroid** [comment]
@Zx-EvM

> But why do we need this flag in the config?

You don't.   --login is just the default because its an arg for bash to make it a "login shell".   wsl.exe gives you a login shell automatically.

**Comment by nightwolfz** [comment]
If you are getting an error when launching "bash.exe" but "ubuntu.exe" works, that means your default distro is not configured.

You can solve it by checking which distro's are installed with:

`wslconfig.exe /l`

and then setting default distro with:

`wslconfig.exe /s Ubuntu`

Enjoy fixed `bash.exe` !

**Comment by jacobrillema** [comment]
Big thing for me was shellArgs, it will not take the single quotes '' and needs to be just the brackets. I tested this with setting up a different shell than bash and it works correctly for me. Note you may to update your comments in the .hyper.js file. wsl.exe is the preferred method on the fall creators update as it will adhere to the default shell in the /etc/passwd file for the given user.

```
shell: 'wsl.exe',

// for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
// by default `['--login']` will be used
shellArgs: [],
```
