### ISSUE TITLE
ssh+tmux in a fresh window in Hyper 2.04 seems to use incorrect dimensions

### ISSUE THREAD

**Issue by jokeyrhyme** [zeit/hyper#2386]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13.1 Beta (17B35a)
- **Hyper.app version**: 2.0.4 (stable) (**note**: this should probably say "pre-release")
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://github.com/jokeyrhyme/dotfiles/blob/master/config/hyper.js
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: yes, happens after restarting Hyper with an absent ~/.hyper.js file

## Issue

ssh+tmux in a fresh window in Hyper 2.04 seems to use incorrect dimensions

## Steps To Reproduce

1. launch Hyper, and resize to 90x60 (characters, not pixels)
2. create a new Hyper window (although I think this happens with new tabs, too)
3. `ssh` to an Ubuntu box (14.04 in this case, not sure yet if this is distribution specific), with remote account defaulting to `bash`
4. `tmux`
5. observe that tmux only occupies the top 20 or 25 rows of the Hyper window, with the tmux status bar appearing half-way up the window instead of at the bottom
6. resize the window to 90x59 or 90x61
7. observe that tmux now properly occupies the full window

Alternatively:

6. instead of manually resizing the window, just leave the window alone for a few minutes

## Notes

-   I did try `ssh`ing from macOS to itself, and could not reproduce this, but I'm using zsh+oh-my-zsh+pure and goodness knows what else, so maybe there's something in the (default) bashrc on my usual SSH target?

-   it's really odd to me that just leaving the window alone seems to correct things, although it might be part of Hyper design (interrogating window dimensions might be an expensive operation?)

**Comment by jokeyrhyme** [comment]
I just tried copying my ~/.tmux.conf from my MacBook to the remote host, and I'm still seeing the reported behaviour, so I think I can rule out that difference between the two

**Comment by jokeyrhyme** [comment]
Hmmm, I just had this occur with `aws s3api help` on macOS with my environment variables including PAGER=less

1. new Hyper tab
2. `aws s3api help`
3. observe only the top portion of the window being used and ":" pager command prompt appearing approximately mid-way up the window/tab instead of at the bottom

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
