### ISSUE TITLE
Using a transparent background results in ghosting artifacts

### ISSUE THREAD

**Issue by pgsill** [zeit/hyper#2387]
I've tried using a transparent bg through the `hyper-transparent` package and through a rgba background color on hyper's settings. Both show this behavior.

![img](https://i.imgur.com/f6w2bpb.png)

```
        Hyper 1.4.8
        Electron 1.7.8
        darwin x64 16.7.0
```

This is mentioned in issue #87, but I found no other issues that talk about this, specifically.

**Comment by albinekb** [comment]
Id like you to try this in 2.x and see if you notice any difference, you can read on how to try 2.x via our `canary` release channel here: https://zeit.co/blog/canary

in 2.x we have replaced the terminal rendering engine, and it also uses a more up to date electron, which could have fixed this already.

If you get the same issues in canary, we need to look into this.

Thanks! 👍

**Comment by deleteme** [comment]
This problem still exists on canary.

**Comment by chabou** [comment]
@deleteme Was it after a `Reload`?

**Comment by deleteme** [comment]
It can happen after a reload. It's more noticeable after changing tabs. In case it helps, I have a custom text-shadow style. The bug looks like the text-shadow persists between tabs. Resizing the window clears the artifacts.

```
    termCSS: '* { text-shadow: 0 1px 5px rgba(0, 0, 0, 0.5) }',
```

**Comment by chabou** [comment]
@deleteme What is your exact Hyper version?
In our last canary, this setting should not apply, because we are using xtermv3 that uses canvas instead of DOM to render text.

**Comment by deleteme** [comment]
I am using version `Hyper 2.0.0-canary.11 (canary)`. You're right. There is no text-shadow applied to the text anymore, which is unfortunate because this was why I started using hyper in the first place.

**Comment by chabou** [comment]
Yes this is unfortunate 😞 
But this is the cost of performance 🚀 
`xterm` v3 (backed by canvas) is really amazing.
But yes, less customizable.

**Comment by EinarJohansson** [comment]
I'm still getting ghosting text problems when using a transparent background color. Is there any solution? 
OS: Mac OS High sierra 10.13.6
Hyper version: 3.0.2
backgroundColor: 'rgba(161,163,162,0.6)'
![Skärmavbild 2020-12-20 kl  12 14 09](https://user-images.githubusercontent.com/19911867/102711849-eea4e180-42bc-11eb-8018-e854ebdc3484.png)
