### ISSUE TITLE
No linux background transparency since 1.3.3 on AppImage Release file

### ISSUE THREAD

**Issue by justUmen** [zeit/hyper#2394]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Archlinux
- **Hyper.app version**: 2.0.4 and 1.4.8 and 1.3.3
- **The issue is reproducible in vanilla Hyper.app**: Just change "backgroundColor" in .hyper.js

## Issue

I'm enjoying the background transparency of the `AppImage` hyper `1.3.3`.

    ./hyper-1.3.3-x86_64-linux.AppImage --enable-transparent-visuals --disable-gpu

But since, all others version of the AppImage doesn't seems to support transparency. (same for 2.0.4)

    ./hyper-1.4.8-x86_64.AppImage --enable-transparent-visuals --disable-gpu

Only change I made in `.hyper.js` : 

    backgroundColor: 'rgba(0,0,0,0.1)',

**Comment by albinekb** [comment]
I think this is because chrome (thus electron) stopped supporting transparency without disabling gpu-acceleration on windows & linux, can't find the link right now, but if you search for `transparency` in the issues you should be able to find it  👍

**Comment by justUmen** [comment]
https://github.com/electron/electron/issues/8532#issuecomment-300715940 ?
So I guess nothing you can do... keep up the good work !

**Comment by albinekb** [comment]
Exactly @justUmen, I think there are hyper plugins that forces gpu acceleration to disable, to get transparency, but I wouldn't recommend it, it's not worth disabling gpu acceleration for transparency imho 👍

**Comment by albinekb** [comment]
You feel alright with closing this? there are already multiple other issues about transparency 👍

**Comment by justUmen** [comment]
Sure ! And 666 issues isn't a great number...

**Comment by albinekb** [comment]
😂  Indeed not, thanks 🎉
