### ISSUE TITLE
Cannot paste on latest version 2.0.4 (Windows10)

### ISSUE THREAD

**Issue by Glutch** [zeit/hyper#2397]
Could not paste on version 1.4~ upgraded to 2.0.4, still cannot paste. Shows up as "^V"
Having severe problems with copying too, works 1/10 of my tries
Windows 10 x64

**Comment by derrickpelletier** [comment]
on windows 10 x64, canary, I get a `^V` when i press `ctrl + v`.
I get a paste when I press `ctrl + shift + v`.

I don't use windows frequently though, so limited experience.

**Comment by ineeve** [comment]
That is normal behaviour on Windows platform. I think that this should not be labelled as a bug.

**Comment by NomNuggetNom** [comment]
As @ineeve said, this isn't a bug, it's the default behavior. If you like using ctrl+v, edit your `.hyper.js` file:
```js
  keymaps: {
    'editor:paste': 'ctrl+v'
  }
```
You can find other actions [here](https://github.com/zeit/hyper/blob/canary/app/keymaps/win32.json)

**Comment by Glutch** [comment]
@NomNuggetNom Thank you! Why is this the default behavior instead of ctrl+v?

**Comment by NomNuggetNom** [comment]
I think it's to be consistent with copying, with uses `ctrl+shift+v`. `ctrl+c` is used to stop programs and such. Generally, it's to avoid conflicts with native uses.

**Comment by moso** [comment]
Isn't it normal Windows behaviour to paste when you right-click inside the terminal?

**Comment by kasper3** [comment]
With keymaps suggestion by @NomNuggetNom, ctrl+v is working, thanks @NomNuggetNom!

However, the following pattern doesn't work:

* past some text and do NOT press [Enter] yet
* press backspace till the beginning of line
* paste again

doesn't work

> till the beginning of line

if you paste something, backspace few times but not till the beginning of line, then paste, it works.
if you type something, backspace till the beginning, then paste, it works as well.
if you paste something, backspace till the beginning, then type something (even a single space), then paste, it still works.

Something goes wrong with {paste} -> {clear the whole line} -> {paste again}

**Comment by kasper3** [comment]
> That is normal behaviour on Windows platform

Sounds like normal behavior "of Hyper". In Windows 10 ctrl+v does the pasting in powershell and cmd natively. Would be nice if defaults are set accordingly.. element of least surprise etc.

**Comment by derrickpelletier** [comment]
@drjonnicholson can you confirm with your plugins disabled? Happy to fix this if it's a core bug, but I don't have windows installed atm and don't want to bother until confirmed :)
