### ISSUE TITLE
Preferences doesn't work

### ISSUE THREAD

**Issue by okonomiyaki3000** [zeit/hyper#2401]
-
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 6.1.7601

Neither selecting "Preferences" from the Edit menu nor pressing "Ctrl-," gives anything like a preferences window or dialog. Just nothing happens.

**Comment by naim42** [comment]
Clicking "Preferences" opens your `~/.hyper.js` file with the default app. You have to tell Windows to use your editor to open `.js` files, otherwise it won't work :)

**Comment by NomNuggetNom** [comment]
For Windows, it should probably try and launch using `notepad.exe` as a fallback. Not sure if there is a way to detect that though.

**Comment by albinekb** [comment]
@NomNuggetNom I've tried my best to do this already, but apparently my solution is not bulletproof:
https://github.com/zeit/hyper/blob/canary/app/config/open.js#L10-L24

**Comment by MAPESO** [comment]
@albinekb I think this problem should be closed.

**Comment by albinekb** [comment]
Feel free to re-open if it doesnt work after selecting default editor 👍
