### ISSUE TITLE
Hyper asks me to *upgrade* to 1.4.8 but I am on 2.0.4

### ISSUE THREAD

**Issue by lijunle** [zeit/hyper#2402]
- [x] I am on the ~[latest](https://github.com/zeit/hyper/releases/latest)~ 2.0.4 Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows Server 2016
- **Hyper.app version**: 2.0.4
- ~~**Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: ~~
- ~~**Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: ~~
- **The issue is reproducible in vanilla Hyper.app**: YES.

## Issue

![image](https://user-images.githubusercontent.com/1296500/32089966-8b9a6a6a-bb1f-11e7-82ea-19060978d459.png)

## After Restart

After restart, it looks like Hyper is not really *upgrade* to 1.4.8. The version is still 2.0.4.

**Comment by Stanzilla** [comment]
How did you install hyper? Did you download the canary installer from github releases?

**Comment by lijunle** [comment]
Yes. I am originally installing 1.4.8 version, then download the EXE from
release page. Close my 1.4.8 version, run the EXE, wait a while and I get
2.0.4.

**Comment by Stanzilla** [comment]
Okay that is sort of a known problem then. The config does not get updated when you use the Canary installer, valid bug. If you want to keep using the canary (2.x) version you will have to edit your config file and set `updateChannel: 'canary',`

cc @chabou

**Comment by lijunle** [comment]
Awesome! Actually I look for kind of config before download the release but
find nothing, it could better to mention this config somewhere.
