### ISSUE TITLE
Cursor jumps to previous line after using nano

### ISSUE THREAD

**Issue by AndreFCruz** [zeit/hyper#2405]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.12.6
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [hyper.js](https://gist.github.com/AndreFCruz/87eb3cfe6276931c8e549940030af146)
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: yes, reproduced in vanilla Hyper

## Issue
On a filled terminal window, after using nano to view some file the cursor often jumps to a previous line.

![out](https://user-images.githubusercontent.com/13498941/32137641-aecb1e56-bc1b-11e7-96d9-f157b1c032fa.gif)

This is just a visual bug, as whatever command I use next will work as intended, but show up on top of the previous line.

I am able to reproduce this 3/4 times. The gif shows I'm using hyperline, but after disabling it I was still able to reproduce the bug.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
