### ISSUE TITLE
Selection hilight is always black

### ISSUE THREAD

**Issue by sladiri** [zeit/hyper#2407]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Version 1709
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/sladiri/881312de58fa6e7685a6d24a733f3e9e
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: In the developer tools, the selected portion of a row has no different CSS class than the rest of the row.
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
When I hilight text inside the terminal, the selection background-colour is black. With the default theme with background-colour black, this means that the selection is not distinguishable from not-selected text.

I am probably missing something obvious, but how can this colour be changed?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
