### ISSUE TITLE
Terminal periodically stops updating

### ISSUE THREAD

**Issue by josephby** [zeit/hyper#2410]
After I've used Hyper for a while it will stop showing what I type, as I type it. This occurs from the plain vanilla windows command line. This also happens while running other shells in other environments. The only solution is to restart Hyper.

        
        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by Magneticmagnum** [comment]
I have several people at my company experiencing the same issue.

**Comment by albinekb** [comment]
Hi! Can you try and see if the issue is also present in 2.x? see how to try it now at zeit.co/blog/canary

**Comment by josephby** [comment]
Ok. Testing 2.x today. Will let you know what I find. Thanks for responding.

**Comment by josephby** [comment]
Appears fixed in 2.x
