### ISSUE TITLE
Change shell dynamically

### ISSUE THREAD

**Issue by jperezruiz** [zeit/hyper#2411]
Hi!
thanks for this awesome terminal. This isn't an issue, is a question (support)
I usually need to work with different shells.
Now (for what I saw), hyper only allow configuring 1 shell, I've been thinking about creating a plugin that allows having different shells and configurations.
I made some test and I found addSession function, I tried to modify the shell dynamically but it doesn't work, so I would ask: It is possible to change dynamically the shell to init? 
Thanks!

**Comment by Jay1** [comment]
I expected 
`  shell: {
              'C:\\Windows\\System32\\bash.exe',
              'C:\\Windows\\System32\\cmd.exe'
            },`

to open multiple tab with multiple shells, akin to ConEmu behavior

**Comment by gutierri** [comment]
@Jay1 good! I think of something like that too.
 ```shell: {
	[
		'bash.exe',
		'--login'
	],
}```

**Comment by Stanzilla** [comment]
Please follow https://github.com/zeit/hyper/issues/1147
