### ISSUE TITLE
Auto-update invokes onUnload but not onApp for installed plugins

### ISSUE THREAD

**Issue by dcalhoun** [zeit/hyper#2415]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13
- **Hyper.app version**: 2.0.4 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [dotfiles](https://github.com/dcalhoun/dotfiles/blob/master/hyper.js)
- **Relevant information from devtools**: No apparent errors.
- **The issue is reproducible in vanilla Hyper.app**: Yes, but not necessarily relevant.

## Issue
The [auto-update interval](https://github.com/zeit/hyper/blob/8aa7d90ff1df47cab3d1a6c9ee52cb03a7b45a95/app/plugins.js#L142) invokes [`onUnload` for all installed plugins](https://github.com/zeit/hyper/blob/8aa7d90ff1df47cab3d1a6c9ee52cb03a7b45a95/app/plugins.js#L111) via [`clearCache`](https://github.com/zeit/hyper/blob/8aa7d90ff1df47cab3d1a6c9ee52cb03a7b45a95/app/plugins.js#L70), but does not run [`onApp`](https://github.com/zeit/hyper/blob/8aa7d90ff1df47cab3d1a6c9ee52cb03a7b45a95/app/index.js#L211) via [`watchers`](https://github.com/zeit/hyper/blob/8aa7d90ff1df47cab3d1a6c9ee52cb03a7b45a95/app/plugins.js#L88) unless a plugin has changed. This behavior results in soutar/hyperterm-summon#30.

## Questions
- Is this intended or a bug?
- If this is intended behavior, should I not "clean up" after a plugin (e.g. removing event listeners) during [a plugin's `onUnload` method](https://github.com/soutar/hyperterm-summon/blob/2.0.4/index.js#L14)?

If this is considered a bug, I'm happy to investigate a fix, but wanted to understand the desired plugin architecture first. Thanks.

**Comment by dcalhoun** [comment]
@rauchg @leo I'm happy to explore a resolution to this issue, if I can receive feedback on the desired behavior. Thanks. 😊

**Comment by chabou** [comment]
Seems to be a bug.
I'll happy to accept a PR for this ;)

`onUnload` method should be called only on removed plugins imo.
