### ISSUE TITLE
sometimes I see Windows ugly scrollbars

### ISSUE THREAD

**Issue by divvs** [zeit/hyper#2419]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS**:  **Windows 10** 1703
## Issue
See details below (with gif) 🢛

![why](https://user-images.githubusercontent.com/32578645/32350894-de429a6e-c045-11e7-8e9b-caa567e54df4.png)

**Comment by Stanzilla** [comment]
List your plugins please

**Comment by divvs** [comment]
@Stanzilla [hyperterm-panda](https://www.npmjs.com/package/hyperterm-panda), [hyperline](https://www.npmjs.com/package/hyperline), gitrocket and hyperpower. Scrolls exist both with/without this plugs. It's not significant, but better to remove them, no? Appears and disappears

**Comment by chabou** [comment]
Thank you for your feedback and your screencast but please use our issue template.

Without that, we are forced to spend time to ask you all the tings are mentioned in our issue template.
We need to know if you can reproduce without any plugin...
We need to know your Hyper version..

Please reopen an issue with all issue template informations filled.

**Comment by chabou** [comment]
Oh sorry, I misread :)

**Comment by chabou** [comment]
Can you try to reproduce on our `canary` version (v2.0.4)?

**Comment by divvs** [comment]
@chabou yea. just wait

**Comment by divvs** [comment]
@chabou nice!  😊
![hypergethyped1](https://user-images.githubusercontent.com/32578645/32357322-ee5c2b48-c065-11e7-8c24-c64dd045f327.gif)

**Comment by chabou** [comment]
Yes!
Thank you for your feedback
