### ISSUE TITLE
.hyper.js is initialized with [object Object]

### ISSUE THREAD

**Issue by coreh** [zeit/hyper#2423]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10.0.16299.19
- **Hyper.app version**: 2.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/coreh/02cf6bc06e276531f4ed3a7b55b9f469
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Vanilla

## Issue

Whenever I start hyper after having deleted `.hyper.js`, it generates a new file. However, instead of generating a file with sample config, it just prints out `[object Object]` on the file

**Comment by Stanzilla** [comment]
This got fixed in 2.1.1 thanks for the report though :)

**Comment by coreh** [comment]
That was fast! Thanks
