### ISSUE TITLE
Hyper is stuck on update

### ISSUE THREAD

**Issue by Huvik** [zeit/hyper#2428]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac 10.13.1**: 
- **1.4.8**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Huvik/4047ec8cdac40d1f8706f218a28c25a8
- **Relevant information from devtools** _(CMD+ALT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes
## Issue
I have problem with hyper updating on canary channel. After update hyper is stucked on loading and can't load at all. Only possible solution is to remove it and install again. I am using latest stable version of hyper.

Video: https://streamable.com/kfvrh

**Comment by jamespgrant3** [comment]
@Huvik  Have you been able to get past this? Hyper updated for me tonight, while I was running an ionic server. I am now experiencing the same issue.

**Comment by afturner** [comment]
this is also happening to me

**Comment by Stanzilla** [comment]
That was a hiccup that should be fixed now.
