### ISSUE TITLE
Can't copy from inside tmux

### ISSUE THREAD

**Issue by oquirozm** [zeit/hyper#2439]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS High Sierra 10.13
- **Hyper.app version**: 2.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/oquirozm/2b46265d5992151c40a8678eecb3c182
- **The issue is reproducible in vanilla Hyper.app**: Yes.

## Issue
I haven't been able to copy any text from inside a tmux session. Selecting text with alt + select didn't work.

**Comment by berndlosert** [comment]
I have a similar issue, but inside GNU screen.

**Comment by dominikmueller** [comment]
Might have similarity with #2429. -> copy/paste problems..

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by AntonNiklasson** [comment]
I'm having some issues with this still. I'm using Hyper 3.0.2 with tmux 2.9.

**Comment by jszroberto** [comment]
Same issue, dealbreaker for me. I will start using iTerm2 again :(

**Comment by marsjane** [comment]
just modify your `hyper.js` as follows:

> `macOptionSelectionMode: 'force',`

it works for me, refer to [https://github.com/vercel/hyper/issues/3592](url)

**Comment by jackluo923** [comment]
> just modify your `hyper.js` as follows:
> 
> > `macOptionSelectionMode: 'force',`
> 
> it works for me, refer to [https://github.com/vercel/hyper/issues/3592](url)

This does not work for me.

**Comment by helbing** [comment]
> just modify your `hyper.js` as follows:
> 
> > `macOptionSelectionMode: 'force',`
> 
> it works for me, refer to [https://github.com/vercel/hyper/issues/3592](url)

It was not working for me. 🙁

**Comment by MirkoManojlovic** [comment]
For anyone that struggles with this, I've setup vim like copy/paste from this article here 

https://dev.to/iggredible/the-easy-way-to-copy-text-in-tmux-319g

and set `copyOnSelect: true`

and it is working 🥳 

Version: `Hyper 3.3.0 (stable)`

tmux.conf file

```bash
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

# Turn on vim mode
setw -g mode-keys vi

# Copy-paste like vim
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
```
