### ISSUE TITLE
Add CSS class to hyper main window when running elevated/admin/sudo

### ISSUE THREAD

**Issue by Xapphire13** [zeit/hyper#2441]
I often have admin and non-admin hyper terminals open at the same time (some of my teams development stack requires admin user). It would be great if the admin window had a CSS class I could use in my `.hyper.js` CSS config.

I coded up a naive implementation of this feature to demonstrate the benefits:

![image](https://user-images.githubusercontent.com/3392349/32480962-2f0b97d6-c346-11e7-8ea0-7bb66d80b3eb.png)
Notice how my regular terminal has a magenta border, whereas the admin one has a red border.

The benefit here is that, at a glance, i know which terminal is an admin one and which isn't.

**My code**
This code is far from what it should be in order to achieve this, I'm just not familiar with the code base currently. Ideally I would utilize the react render function to add the CSS class based on a value in the local state.

_app/index.js_
```js
hwin.webContents.on('did-finish-load', () => {
  isElevated().then(elevated => {
    if (elevated) {
      hwin.webContents.send('isElevated');
    }
  });
});
```

_lib/index.js_
```js
ipcRenderer.on('isElevated', () => {
  document.getElementsByClassName('hyper_main')[0].classList.add('elevated');
});
```

_.hyper.js_
```js
    css: `
      .hyper_main:not(.elevated)::before {
        display: block;
        content: "";
        position: absolute;
        width: 100%;
        height: 100%;
        top: -1px;
        left: -1px;
        border: 1px solid magenta;
      }

      .hyper_main.elevated::before {
        display: block;
        content: "";
        position: absolute;
        width: 100%;
        height: 100%;
        top: -1px;
        left: -1px;
        border: 1px solid red;
      }
    `,
```

**Comment by chabou** [comment]
It should be done as a plugin because it will only work on Windows/Powershell. In other OS/Shell, you normally have to elevate your privilleges directly into shell and not running Hyper as superadmin.

You can create a plugin or you can add this feature to https://github.com/chabou/hyper-autoprofile

Do not hesitate to ask help if needed.

**Comment by Xapphire13** [comment]
Thanks for the info. I was looking at existing plugins and I feel it probably better fits the [hyperborder](https://github.com/webmatze/hyperborder) plugin.
