### ISSUE TITLE
[PowerShell] PSReadLine menu completion hotkey does not register

### ISSUE THREAD

**Issue by yoav-lavi** [zeit/hyper#2444]
- **OS version and name**: Microsoft Windows 10 Enterprise Build 15063
- **Hyper.app version**:  2.1.1 (canary)
- **The issue is reproducible in vanilla Hyper.app**:  Yes

## Issue

When using PowerShell on Hyper, the PSReadLine `Ctrl + Space` hotkey for the completion menu does not trigger.  If the hotkey itself is changed to another key, it registers on Hyper (which shows the problem is likely specifically with `Ctrl + Space`).

**Comment by Stanzilla** [comment]
https://superuser.com/questions/1088250/windows-10-linux-bash-shell-ctrlspace-doesnt-set-mark-in-emacs?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
