### ISSUE TITLE
[PowerShell + CMD] fzf (Windows) does not work on Hyper 

### ISSUE THREAD

**Issue by yoav-lavi** [zeit/hyper#2445]
- **OS version and name**: Microsoft Windows 10 Enterprise Build 15063
- **Hyper.app version**:  2.1.1 (canary)
- **The issue is reproducible in vanilla Hyper.app**:  Using a theme plugin

## Issue
When using the `fzf` command on both PowerShell and CMD, Hyper returns `character set not supported`.
This does not reproduce in a normal PowerShell or CMD window.
[fzf repo](https://github.com/junegunn/fzf)

**Comment by peterdanis** [comment]
Check https://github.com/junegunn/fzf/issues/963#issuecomment-313876740. There is a Hyper specific solution.

**Comment by yoav-lavi** [comment]
The solution specified works, although it may be beneficial for the windows version to set this automatically so it'll work out of the box.
