### ISSUE TITLE
Preferences won't load (mac)

### ISSUE THREAD

**Issue by c-lawlz** [zeit/hyper#2446]
In the menu bar, click Hyper > Preferences.
It then loads Atom, showing a blank window.

  
        -
        Hyper 1.4.8
        Electron 1.7.8
        darwin x64 16.7.0

**Comment by c-lawlz** [comment]
Update: Changing my default .js editor to "Sublime Text" works around the issue, as referenced here: [https://github.com/zeit/hyper/issues/1955](url)

I am leaving this open, because it seems to be an Atom related issue.
Any idea as to why Atom choked?

**Comment by e-e** [comment]
Similar problem on windows, although for me atom does not open. When I click on preferences, nothing happens.

**Comment by MAPESO** [comment]
@c-lawlz the link is *broken*.

**Comment by MAPESO** [comment]
@chabou @albinekb The hyper.js file opens normally in Atom. 
@c-lawlz I can not find the error you indicate.

<img width="1280" alt="screen shot 2017-12-05 at 03 53 37" src="https://user-images.githubusercontent.com/16585386/33600778-e7c80ca2-d96f-11e7-9430-dd4528bb61c2.png">

**Comment by albinekb** [comment]
It works for me with atom as default editor 🤔 Can't reproduce

**Comment by MAPESO** [comment]
@albinekb Apparently it was an error on the part of the user 😈

**Comment by c-lawlz** [comment]
Thanks to everyone who replied here.  I just re-tested this, and Atom now loads as it should.
My guess is Atom has updated since I posted about this, 28 days ago.

> @albinekb Apparently it was an error on the part of the user 😈

It's completely possible there was a config issue on my end.  I have switched .js files to load in Sublime to Atom and back again many times since then.

**Comment by albinekb** [comment]
Sorry for the inconvenience @c-lawlz 🙉  and thanks for raising this issue. Glad it got resolved 👍
