### ISSUE TITLE
Launch different shell in a new  tab / pane

### ISSUE THREAD

**Issue by ryantheleach** [zeit/hyper#2450]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- [x] I am on the [latest website release](https://releases.hyper.is/download/win) Hyper.app version

- **OS version and name**: OS Name	Microsoft Windows 10 Pro 10.0.14393 Build 14393
- **Hyper.app version**: Hyper1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ryantheleach/8d43cc5fd71d5c028e60077edcd4f36f
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Can be reproduced with vanilla, even though I currently have plugins installed.

## Issue
Is it possible to either create a plugin, or have support for multiple shells?

e.g. I run Windows and Hyper is an amazing experience for running Bash/linux subsytem on windows.
However, occasionally in order to fix an issue I am having regarding windows server administration, due to information available online it's just easier to drop to powershell or cmd.

Is it be possible to launch a tab that contains a different shell?

Possible duplicate: https://github.com/zeit/hyper/issues/2411 , https://github.com/zeit/hyper/issues/1147 , 
Related issue: https://github.com/zeit/hyper/issues/2438 ,

**Comment by JosefBH** [comment]
how can i do it please ? how can i run a different shell in a different tab in hyper ?
