### ISSUE TITLE
Background opacity (with rgba) not working on Ubuntu 17.10

### ISSUE THREAD

**Issue by Jeffarese** [zeit/hyper#2451]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.10
- **Hyper.app version**: 2.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Jeffarese/65bd9e3d48f2f4bfaf4453f82d246d4e
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I'm trying to lower the opacity of the background color, using `backgroundColor: 'rgba(0,0,0, 0.5)'` but it's not working, the background has 100% opacity no matter what.

If I change to another color (not caring about the opacity) it works, but it ignores the opacity.

**Comment by SergioGeeK7** [comment]
opacity is not supported by electron on linux/windows. just in mac

**Comment by albinekb** [comment]
We should probably put a notification when a user tries to get transparency in windows/ubuntu and link to the comment by electron.

**Comment by chabou** [comment]
Adding a comment in config file should be ok

**Comment by Jeffarese** [comment]
Yeah, I didin't know this. With a comment in the config file it would have been enough.
