### ISSUE TITLE
Unable to copy git log (v2.1.1)

### ISSUE THREAD

**Issue by jackmellis** [zeit/hyper#2456]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 16.05**: 
- **2.1.1**: 

## Issue
I've just upgraded (straight from 1.x). when I `git log` and attempt to copy the hash of the last commit (`ctrl + shift + c` or via the context menu) the clipboard is populated with `on always false [./node_modules/redux/es`.

Any idea what the cause would be?

**Comment by BenMagyar** [comment]
This is resolved in the latest canary release 👍 .
