### ISSUE TITLE
Typing "clear" to clear the terminal doesn't work

### ISSUE THREAD

**Issue by francesco-albanese** [zeit/hyper#2460]
-
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.14393

I am using Hyper with git bash and when I execute the command "clear" to clear the terminal it doesn't work. It still shows all the preceding lines of code and if you start typing something else it overlaps with existing text.

![image](https://user-images.githubusercontent.com/10304505/32826242-e7534062-c9e7-11e7-80bc-72c9d89d2032.png)

**Comment by chabou** [comment]
Thank you for your feedback.
Can you try to reproduce with our `canary` release ? (by setting `updateChannel: canary` in your config)

**Comment by francesco-albanese** [comment]
Sure, I am gonna try that and let you know

**Comment by francesco-albanese** [comment]
Just tried what you suggested and it's still happening.
This is my config object:

`// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: '"Fira Code", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: 'x-screen x-row { font-variant-ligatures: contextual; }',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: 'C:\\Users\\f.albanese\\AppData\\Local\\Programs\\Git\\git-cmd.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--command=usr/bin/bash.exe', '-l', '-i'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: ["hyperpower", "hyperterm-material", "hyper-search"],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: [],
  updateChannel: "canary"
};
`

**Comment by chabou** [comment]
Can you confirm me that v2.1.1 was installed after your config change and that the issue is still here ?

**Comment by francesco-albanese** [comment]
Actually no, the version is still 1.4.8 (stable)

**Comment by chabou** [comment]
`updateChannel` param should be in `config` section.
I didn't notice this when you sent your config, sorry.

**Comment by francesco-albanese** [comment]
Moved updateChannel in config section, still no luck. Version is still 1.4.8

**Comment by francesco-albanese** [comment]
Updated Hyper to version 2.1.1 , the problem still occurs

**Comment by scote** [comment]
I have the same issue on 2.1.1.

**Comment by chabou** [comment]
Thanks for the report 🙏 . 
We're tracking this work over here: #2316

**Comment by ni7in** [comment]
the same issue still there, I configured git bash with hyper, everything works okay, except one thing when I try to clear my terminal, with the '**clear**' command It doesn't, and the cursor comes to the top of the lines and overlaps previous one. [Screenshot](https://i.gyazo.com/3dacb0f353ba061aed0aa9f5f580896e.png)
