### ISSUE TITLE
Power typeing mode

### ISSUE THREAD

**Issue by streamich** [zeit/hyper#2461]
Please add "power typing" mode.

https://atom.io/packages/activate-power-mode

thx

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac
- **Hyper.app version**: @latest

**Comment by chabou** [comment]
There is a plugin, but only compatible with stable release (for now): https://github.com/zeit/hyperpower
