### ISSUE TITLE
Open Hyper windows in tabs not display all contents in the windows

### ISSUE THREAD

**Issue by duytrung** [zeit/hyper#2462]
- **OS version and name**: Windows 10
- **Hyper.app version**: 2.1.1

## Issue
I expand the hyper windows to max size and run neovim in the command line. It did not display the status line in the bottom of the screen if I open new windows as tab. 

Please fix this issue when open new windows as tab. It should show the whole screen instead of shifting the windows down with the tab size above.

Thanks

**Comment by chabou** [comment]
Can you add some screenshots?

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
