### ISSUE TITLE
Resizing window corrupts non-active tabs

### ISSUE THREAD

**Issue by ctuffli** [zeit/hyper#2464]
- [x] Your Hyper.app version is **2.1.1**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

N/A
  - **Is the issue reproducible in vanilla Hyper.app?**

Yes
## Issue

1. Launch Hyper
2. Create a second tab
3. Resize the window
4. Switch back to the first tab and notice the command prompt is displayed as if the console width is 1 character.
5. Typing the enter key redraws the screen and displays a normal prompt

![image](https://user-images.githubusercontent.com/807942/32912168-114f6400-cac3-11e7-93e9-81f9995144b0.png)

 - **Hyper version**: undefined "2.1.1"

 - **OS ARCH VERSION:** win32 x64 10.0.16299
 - **Electron:** 1.7.9  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** xterm-256color

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "canary",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "true",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "shell": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
  "shellArgs": [],
  "env": {},
  "bell": false,
  "copyOnSelect": true
}

          {
  "plugins": [
    "hypersolar-dark"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by Stanzilla** [comment]
Duplicate of https://github.com/zeit/hyper/issues/2421

**Comment by ctuffli** [comment]
Ugh, sorry, I missed that :(
Yup, this is a dupe.
