### ISSUE TITLE
chinese font wrong width,can't use ime to input

### ISSUE THREAD

**Issue by vzex** [zeit/hyper#2466]
![image](https://user-images.githubusercontent.com/4971777/32943413-ff17f914-cbc6-11e7-9b6f-6aa137bac165.png)
Please lookat the pic, I can't use ime to input chinese words, but can only paste
![image](https://user-images.githubusercontent.com/4971777/32943501-51c63ebe-cbc7-11e7-9cef-8f3e1ae6b553.png)
and if i use backspace to delete words, something goes wrong...
![image](https://user-images.githubusercontent.com/4971777/32943537-68f590b2-cbc7-11e7-9cdd-eba535457872.png)

**Comment by chabou** [comment]
Hi there, thanks for reporting an issue!
Unfortunately, we need the information that was listed out in template when you created the issue to really help solve your problem. For now, we'll close your issue and wait for you to comment/re-open the issue with the template information filled out from https://github.com/zeit/hyper/issues/new
