### ISSUE TITLE
Flicker before autoscroll during `ping`

### ISSUE THREAD

**Issue by lorensr** [zeit/hyper#247]
On top is Terminal, on bottom is hyperterm. On bottom, the latest ping line flickers on the bottom blank line before moving up the screen. On top, the latest line just appears on the line above the bottom line. The top looks/feels smoother to me 😊

https://www.dropbox.com/s/0qbsv9jbajt056j/hyperterm-ping.mov?dl=0

**Comment by MAPESO** [comment]
@chabou  @timothyis  This problem is already solved ?

**Comment by ppot** [comment]
Resolved with xtermjs. Closing
