### ISSUE TITLE
Prevent canary update notification for stable Linux users.

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2476]
## Context
On Linux, we don't use autoUpdater (and `hazel`) because it is not compatible.
Instead, we are making some request to a news feed `https://hyper-news.now.sh` with some params:
https://github.com/zeit/hyper/blob/5d0c6355e12ec8d9a89182556fa73227374b488f/app/notifications.js#L19-L24

## Problem
`updateChannel`  is not given as parameter. That's why stable users currently see notification about v2.1.1 release 😞 

## Solution
We should use this news feed only for important messages and not as an autoUpdater fallback.
Update notifications for linux should use same feed (`hazel`) than autoUpdater and notify users if update is available without downloading archive.

**Comment by leo** [comment]
Agreed @chabou 👍

Can you explain more about how we would use hazel on linux to notify users? Because I don't think `autoUpdater` works at all on that platform, so we can't use it to trigger notifications.

**Comment by chabou** [comment]
I would like to abstract electron's `autoUpdater`: 
* On macOS/Windows, just configuring autoUpdater.
* On linux: fetching Hazel's URL by ourselves (with same frequency) and triggering the same rpc 'update available' call than autoUpdater `update-downloaded` event. I can retrieve needed informations from `name` and `notes` fields of Hazel response.

We only need to implement `checkForUpdates()` and event emitting. Easy game.

**Comment by leo** [comment]
Yea, that would probably the best solution. Great 👍

**Comment by javihero** [comment]
Is this fixed? I'm currently on a loop (my update channel is set to stable):
- I install 1.4.8, and It shows me the message to download 2.0.0-canary.8
- I install 2.0.0-canary.8 and It shows me the message to download 1.4.8

**Comment by KogAtlas** [comment]
I'm also seeing this on 2.0.0-canary.8

**Comment by ZeFifi** [comment]
Same problem as @javihero here!

**Comment by chabou** [comment]
@javihero @KogAtlas @ZeFifi @novafacing : You need to install `2.0.0-canary.X` AND set your `updateChannel: 'canary'`.

Stable notifications are broken on Linux (in 1.4.8). It will be definitely fixed when 2.0.0 will be stable.

Notifications for stable (v1.4.8) availability when you are running a manually installed canary without switching update channel config, is attended.

**Comment by edwinramirez** [comment]
Has this been fixed?
I'm using Hyper 2.0.0 (stable) on Ubuntu 18.04 LTS. I have my updateChannel set as `updateChannel: 'stable',`
But every time I start Hyper I get a red boxed notification announcing the availability of Version 2.1.0-canary.1 
There is no way to permanently dismiss this notification and I don't know why I'm getting notified about it in the first place.

**Comment by MichaelFrieze** [comment]
I would also like to figure out how to deal with this notification.

**Comment by milos201** [comment]
Samer here, it is very annoying...
