### ISSUE TITLE
Connecting to mongodb using the mongo cli and closing the tab prevents new tabs from starting

### ISSUE THREAD

**Issue by lelandcope** [zeit/hyper#2479]
- **OS version and name**: macOS High Sierra v10.13.1
- **Hyper.app version**: 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [hyper.js](https://gist.github.com/lelandcope/f4f699ee2297defd67f959ccdf9b30f7)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Tried with plugins and vanilla (I also use oh-my-zsh as my shell)

## Issue
1) Open hyper
2) Open a new tab and connect to a remote mongo instance using the mongo cli
3) Close the tab without exiting mongo cli
4) Open a new tab
5) All new tabs hang and never allow me to start typing. The only way to make it work correctly again is to quit hyper

**Comment by lelandcope** [comment]
Looking a little deeper it might be the same issue as this [ticket 1370](https://github.com/zeit/hyper/issues/1370). It looks like when you close the tab its not stopping the mongo process where as when I do it in terminal it does.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
