### ISSUE TITLE
Right click the selection to automatically insert selected text

### ISSUE THREAD

**Issue by alexpana** [zeit/hyper#2480]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.1.1 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: default config
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: none
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

Most of the linux terminal emulators I've worked with and cmder on windows automatically insert the selected text when right clicking the selection. From what I can tell, hyper.js requires two right clicks (one for copy and one for paste). I've tried setting `copyOnSelect: true` in the `.hyper.js` config file, but it didn't help.

Is this something that would be considered for implementation? Or, if not, what would be the simplest way to implement it via a plugin?

**Comment by Stanzilla** [comment]
You want `quickEdit: true,`
