### ISSUE TITLE
Hyper fails to build on Linux: How should I understand these error messages as?

### ISSUE THREAD

**Issue by whitestone8214** [zeit/hyper#2481]
1. With 'npm install':

> [user@myhost hyper]$ npm install
> npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
> 
> > rabin-bindings@1.7.3 install /home/user/techno/hyper/node_modules/rabin-bindings
> > prebuild-install || node-gyp rebuild
> 
> prebuild-install info begin Prebuild-install version 2.3.0
> prebuild-install info looking for local prebuild @ prebuilds/rabin-bindings-v1.7.3-node-v59-linux-x64.tar.gz
> prebuild-install info looking for cached prebuild @ /home/user/.npm/_prebuilds/https-github.com-develar-rabin-bindings-releases-download-v1.7.3-rabin-bindings-v1.7.3-node-v59-linux-x64.tar.gz
> prebuild-install http request GET https://github.com/develar/rabin-bindings/releases/download/v1.7.3/rabin-bindings-v1.7.3-node-v59-linux-x64.tar.gz
> prebuild-install http 404 https://github.com/develar/rabin-bindings/releases/download/v1.7.3/rabin-bindings-v1.7.3-node-v59-linux-x64.tar.gz
> prebuild-install WARN install No prebuilt binaries found (target=9.2.0 runtime=node arch=x64 platform=linux)
> make: 디렉터리 '/home/user/techno/hyper/node_modules/rabin-bindings/build' 들어감
>   CXX(target) Release/obj.target/rabin-bindings/bindings.o
>   CXX(target) Release/obj.target/rabin-bindings/src/rabin.o
>   CXX(target) Release/obj.target/rabin-bindings/src/rabin_wrap.o
>   SOLINK_MODULE(target) Release/obj.target/rabin-bindings.node
>   COPY Release/rabin-bindings.node
> make: 디렉터리 '/home/user/techno/hyper/node_modules/rabin-bindings/build' 나감
> 
> > electron-chromedriver@1.7.1 install /home/user/techno/hyper/node_modules/electron-chromedriver
> > node ./download-chromedriver.js
> 
> 
> > husky@0.14.3 install /home/user/techno/hyper/node_modules/husky
> > node ./bin/install.js
> 
> husky
> setting up Git hooks
> done
> 
> 
> > uglifyjs-webpack-plugin@0.4.6 postinstall /home/user/techno/hyper/node_modules/uglifyjs-webpack-plugin
> > node lib/post_install.js
> 
> 
> > electron@1.7.9 postinstall /home/user/techno/hyper/node_modules/electron
> > node install.js
> 
> 
> > undefined postinstall /home/user/techno/hyper
> > electron-builder install-app-deps && yarn run rebuild-node-pty
> 
> electron-builder 19.43.0
> Installing app dependencies for linux:x64 to /home/user/techno/hyper/app
> Error: /usr/bin/node exited with code 1
> Output:
> 
> > node-pty@0.7.3 install /home/user/techno/hyper/app/node_modules/node-pty
> > node scripts/install.js
> 
> 
> Error output:
> sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
> gyp ERR! System Linux 4.9.61-1-lts
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/user/techno/hyper/app/node_modules/node-pty
> gyp ERR! node -v v9.2.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! node-pty@0.7.3 install: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the node-pty@0.7.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/user/.npm/_logs/2017-11-22T01_19_20_300Z-debug.log
> 
>     at ChildProcess.childProcess.once.code (/home/user/techno/hyper/node_modules/builder-util/src/util.ts:228:14)
>     at Object.onceWrapper (events.js:254:19)
>     at ChildProcess.emit (events.js:159:13)
>     at maybeClose (internal/child_process.js:943:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> From previous event:
>     at spawn (/home/user/techno/hyper/node_modules/builder-util/src/util.ts:191:3)
>     at installDependencies (/home/user/techno/hyper/node_modules/electron-builder/src/util/yarn.ts:90:3)
>     at /home/user/techno/hyper/node_modules/electron-builder/src/util/yarn.ts:18:11
>     at Generator.next (<anonymous>)
> From previous event:
>     at installOrRebuild (/home/user/techno/hyper/node_modules/electron-builder/out/util/yarn.js:32:21)
>     at /home/user/techno/hyper/node_modules/electron-builder/src/cli/install-app-deps.ts:58:42
>     at Generator.next (<anonymous>)
> From previous event:
>     at installAppDeps (/home/user/techno/hyper/node_modules/electron-builder/out/cli/install-app-deps.js:51:21)
>     at then (/home/user/techno/hyper/node_modules/electron-builder/src/cli/cli.ts:49:4)
>     at runCallback (timers.js:800:20)
>     at tryOnImmediate (timers.js:762:5)
>     at processImmediate [as _immediateCallback] (timers.js:733:5)
> From previous event:
>     at Object.args [as handler] (/home/user/techno/hyper/node_modules/electron-builder/src/cli/cli.ts:49:4)
>     at Object.runCommand (/home/user/techno/hyper/node_modules/yargs/lib/command.js:228:22)
>     at Object.parseArgs [as _parseArgs] (/home/user/techno/hyper/node_modules/yargs/yargs.js:1013:30)
>     at Object.get [as argv] (/home/user/techno/hyper/node_modules/yargs/yargs.js:957:21)
>     at Object.<anonymous> (/home/user/techno/hyper/node_modules/electron-builder/src/cli/cli.ts:43:15)
>     at Module._compile (module.js:641:30)
>     at Object.Module._extensions..js (module.js:652:10)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)
>     at Function.Module.runMain (module.js:682:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:613:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 255
> npm ERR! undefined postinstall: `electron-builder install-app-deps && yarn run rebuild-node-pty`
> npm ERR! Exit status 255
> npm ERR! 
> npm ERR! Failed at the undefined postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/user/.npm/_logs/2017-11-22T01_19_20_548Z-debug.log
> [user@myhost hyper]$

2. With 'yarn':

> [user@myhost hyper]$ yarn
> yarn install v1.3.2
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@1.1.2: The platform "linux" is incompatible with this module.
> info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
> info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
> info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
> info 7zip-bin-win@2.1.1: The platform "linux" is incompatible with this module.
> info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> $ electron-builder install-app-deps && yarn run rebuild-node-pty
> electron-builder 19.43.0
> Installing app dependencies for linux:x64 to /home/user/techno/hyper/app
> Error: /usr/bin/node exited with code 1
> Output:
> yarn install v1.3.2
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> Error output:
> error /home/user/techno/hyper/app/node_modules/node-pty: Command failed.
> Exit code: 1
> Command: node scripts/install.js
> Arguments: 
> Directory: /home/user/techno/hyper/app/node_modules/node-pty
> Output:
> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> gyp info it worked if it ends with ok
> gyp info using node-gyp@3.6.2
> gyp info using node@9.2.0 | linux | x64
> gyp info spawn /usr/bin/python2
> gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args   'binding.gyp',
> gyp info spawn args   '-f',
> gyp info spawn args   'make',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/user/techno/hyper/app/node_modules/node-pty/build/config.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> gyp info spawn args   '-I',
> gyp info spawn args   '/home/user/.electron-gyp/iojs-1.7.9/common.gypi',
> gyp info spawn args   '-Dlibrary=shared_library',
> gyp info spawn args   '-Dvisibility=default',
> gyp info spawn args   '-Dnode_root_dir=/home/user/.electron-gyp/iojs-1.7.9',
> gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
> gyp info spawn args   '-Dnode_lib_file=/home/user/.electron-gyp/iojs-1.7.9/<(target_arch)/iojs.lib',
> gyp info spawn args   '-Dmodule_root_dir=/home/user/techno/hyper/app/node_modules/node-pty',
> gyp info spawn args   '-Dnode_engine=v8',
> gyp info spawn args   '--depth=.',
> gyp info spawn args   '--no-parallel',
> gyp info spawn args   '--generator-output',
> gyp info spawn args   'build',
> gyp info spawn args   '-Goutput_dir=.' ]
> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
> gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
> gyp ERR! System Linux 4.9.61-1-lts
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/user/techno/hyper/app/node_modules/node-pty
> gyp ERR! node -v v9.2.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> 
>     at ChildProcess.childProcess.once.code (/home/user/techno/hyper/node_modules/builder-util/src/util.ts:228:14)
>     at Object.onceWrapper (events.js:254:19)
>     at ChildProcess.emit (events.js:159:13)
>     at maybeClose (internal/child_process.js:943:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> From previous event:
>     at spawn (/home/user/techno/hyper/node_modules/builder-util/src/util.ts:191:3)
>     at installDependencies (/home/user/techno/hyper/node_modules/electron-builder/src/util/yarn.ts:90:3)
>     at /home/user/techno/hyper/node_modules/electron-builder/src/util/yarn.ts:18:11
>     at Generator.next (<anonymous>)
> From previous event:
>     at installOrRebuild (/home/user/techno/hyper/node_modules/electron-builder/out/util/yarn.js:32:21)
>     at /home/user/techno/hyper/node_modules/electron-builder/src/cli/install-app-deps.ts:58:42
>     at Generator.next (<anonymous>)
> From previous event:
>     at installAppDeps (/home/user/techno/hyper/node_modules/electron-builder/out/cli/install-app-deps.js:51:21)
>     at then (/home/user/techno/hyper/node_modules/electron-builder/src/cli/cli.ts:49:4)
>     at runCallback (timers.js:800:20)
>     at tryOnImmediate (timers.js:762:5)
>     at processImmediate [as _immediateCallback] (timers.js:733:5)
> From previous event:
>     at Object.args [as handler] (/home/user/techno/hyper/node_modules/electron-builder/src/cli/cli.ts:49:4)
>     at Object.runCommand (/home/user/techno/hyper/node_modules/yargs/lib/command.js:228:22)
>     at Object.parseArgs [as _parseArgs] (/home/user/techno/hyper/node_modules/yargs/yargs.js:1013:30)
>     at Object.get [as argv] (/home/user/techno/hyper/node_modules/yargs/yargs.js:957:21)
>     at Object.<anonymous> (/home/user/techno/hyper/node_modules/electron-builder/src/cli/cli.ts:43:15)
>     at Module._compile (module.js:641:30)
>     at Object.Module._extensions..js (module.js:652:10)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)
>     at Function.Module.runMain (module.js:682:10)
>     at startup (bootstrap_node.js:191:16)
>     at bootstrap_node.js:613:3
> error Command failed with exit code 255.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> [user@myhost hyper]$

Because of these errors, currently I cannot build and run Hyper.
Node.js is 9.2.0, and Electron is 1.6.15.

**Comment by blackhands77** [comment]
안녕하세요, 한국인인것 같은데 맞나요?
저는 대학생인데 학교에서 오픈소스에 대해 배우다가 직접 기여에 참여해보라고 과제가 나와서 찾던 도중 hyper를 보고 팀원들과 주제로 삼았는데요,
저희는 ubuntu에 설치하려하니 설치를 하려면 Debian package repository를 거칠 필요가 있다고 하더군요. 저희는 이렇게 설치했습니다.
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn

Hi, I think you are Korean, right?
I'm a university student and I learned about opensource software at class.
And term project is "do contribution" with your team.
So, we choose the project subject 'Hyper'
We are going to install it on ubuntu linux and need to go through the Debian package repository to install it.
We installed following code.

**Comment by whitestone8214** [comment]
@blackhands77 Thanks for answer. But I use Arch Linux, so answer for me would be different a bit ^_^;

Anyway now I found an answer for me after some struggle with code:

> cd app && yarn install --production
> cd ..
> yarn # Here is main build step that described in README ;)
> (...)

Now I can run Hyper, though that why the build process couldn't be completed in just one shot of 'yarn' is still mystery...
