### ISSUE TITLE
Command-Up Arrow does not work (macOS)

### ISSUE THREAD

**Issue by KimMichaelJones** [zeit/hyper#2486]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra Version 10.13.1
- **Hyper.app version**: Hyper 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/KimMichaelJones/d2771cfad7dc302f34342de5d20d1728.js

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Command-Up Arrow does not work (macOS). Standard behaviour on macOS Terminal is to jump to top of screen text (including text that has scrolled off the top of the screen) when pressing cmd+up. Apple describes this as "Jump to previous mark", https://support.apple.com/en-ca/guide/terminal/keyboard-shortcuts-trmlshtcts/mac. I use this constantly and for me a deal breaker, please look at adding this.

**Comment by chabou** [comment]
Amazing, I didn't know that Terminal adds mark automatically at each prompt.
It could be very hard to achieve in Hyper...

What we can do easier, it is iTerm behaviour. Let's user manually add some marks and navigate through them.

Thank you for your feedback

**Comment by cuining** [comment]
I also encountered similar problems. ⇧⌘ + ↑ can not switch tabs

**Comment by mxlje** [comment]
I found this issue via Google. It’s marked completed but as far as I can tell this is not implemented? Thanks!
