### ISSUE TITLE
Failure in the spacing between the cursor and the text entry when changing the font by "Ubuntu"

### ISSUE THREAD

**Issue by hanercamilo** [zeit/hyper#2494]
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Failure in the spacing between the cursor and the text entry when changing the font by "Ubuntu":

This is the ScreenShot:

https://drive.google.com/file/d/1XilWpEpcwp6KxtpZxIwHAhI9mE8kRLUs/view?usp=sharing

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
