### ISSUE TITLE
React Developer Tools and Redux DevTools embed in Hyper.js by default.

### ISSUE THREAD

**Issue by spider8** [zeit/hyper#2496]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 + Bash on Ubuntu on Windows
- **Hyper.app version**: 1.4.8

## Issue
Incorporate these tools by default to facilitate the process of writing and debugging extensions and a better understanding of how Hyper.js works.

**Comment by chabou** [comment]
These extensions are already embed in `Hyper` in dev mode.
Dev mode is really better to writing and debugging extensions.

**Comment by albinekb** [comment]
Maybe we should document that @chabou ? 🤔

**Comment by spider8** [comment]
How do i use the dev mod?
