### ISSUE TITLE
NPM commands cause ugly highlight

### ISSUE THREAD

**Issue by frogr** [zeit/hyper#2498]
![image](https://user-images.githubusercontent.com/24354711/33290211-cece1b32-d376-11e7-99cc-19e3aefe25a4.png)

Navigating to a directory and then running any npm commands (test, install, etc) creates a weird blue highlight over text and continues to do that for the entirety of that buffer instance. 

![image](https://i.imgur.com/dx5yDw5.png)

I uninstalled all plugins and tried again, same problem. I tried searching around but couldn't find a quick fix. If there are any other bits of information I can provide, let me know! 😄 
        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.15063

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
