### ISSUE TITLE
Windows - Hyper starts off screen and can't move

### ISSUE THREAD

**Issue by osvaldolove** [zeit/hyper#2500]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro v1703 Build 15063.726
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I have recently upgraded to a monitor with a larger resolution and Hyper starts off-screen. All my attempts to move the application on screen fail. These include right mouse clicking the taskbar and selecting "Cascade Windows", "Show Windows Stacked", "Show Windows Side by Side".
With other apps you can shift right mouse click an application in the taskbar and you get a context menu with the "Move..." option. This context menu does not appear with Hyper.

Example of the "Move" option from Spotify.
![image](https://user-images.githubusercontent.com/3800572/33311757-be2d8b4e-d41d-11e7-9014-3c3e7a8a1a19.png)

I have tried re-installing Hyper and deleting my .hyper.js but to no avail. I also scoured my registry for references to window location for Hyper but couldn't anything.

**Comment by osvaldolove** [comment]
I have since found out about `config.json` and have deleted and allowed Hyper to recreate this and it has resolved my issue. Also seen that [#2459](https://github.com/zeit/hyper/pull/2459) may fix this issue.

Feel free to close off this issue.
Thanks...

**Comment by srijansood** [comment]
Which `config.json` are you referring to? I'm having a similar issue that I'm trying to fix.

**Comment by osvaldolove** [comment]
It should be in `C:\Users\{your_user_here}\AppData\Roaming\Hyper` on Windows 10.

**Comment by srijansood** [comment]
Deleting it fixed my issue too, thanks!
Turns out, (re)installing Hyper with a monitor attached to the laptop wrote negative values for windowsPosition in` config.json`, causing an invisible application window.

**Comment by miketwo** [comment]
I didn't have to delete it -- just closed all Hyper windows and then changed the `windowPosition` to be 0,0
```
	"windowPosition": [
		0,
		0
	],
```
But it worked! Thanks so much!
