### ISSUE TITLE
Bell setting not working

### ISSUE THREAD

**Issue by kandalf** [zeit/hyper#2513]
Bell cannot be disabled.
Documentation says:
```
 // set to false for no bell
 bell: false,
```
But it doesn't work. Even with the setting above bell still sounds.

Hyper 1.4.8
Electron 1.7.8
darwin x64 17.2.0

**Comment by sddhrthrt** [comment]
I'm on windows 10 with Hyper, bell set to false still doesn't work.

**Comment by ShaggyDev** [comment]
#2938 currently in progress that should restore control of the bell option. Stay tuned ;D

**Comment by danielyang1009** [comment]
bell cannot be disabled.

Hyper 2.1.1 (stable)
Mac OS X 10.14.2

However on mac you can just disable `Play sound for notifications` in Notifications setting.
