### ISSUE TITLE
Creating tasks like in Conemu?

### ISSUE THREAD

**Issue by DJviolin** [zeit/hyper#2518]
Is it possible to create tasks like in Conemu and choosing them from menu? For example this Conemu task creating an MSYS2 instance window with MINGW64 as an admin:

```
set CHERE_INVOKING=1 & set MSYSTEM=MINGW64 & set "PATH=%ConEmuDrive%\msys64\usr\bin;%PATH%" & %ConEmuBaseDirShort%\conemu-msys2-64.exe -new_console:p %ConEmuDrive%\msys64\usr\bin\bash.exe --login -i -new_console:aC:"%ConEmuDrive%\msys64\msys2.ico"
```

**Comment by MAPESO** [comment]
@DJviolin I think it is not possible

**Comment by albinekb** [comment]
You could make a plugin that does it, the docs is at https://hyper.is
