### ISSUE TITLE
Constant "Error fetching updates" notifications

### ISSUE THREAD

**Issue by sethlopezme** [zeit/hyper#252]
Each time hyperterm fails to check for updates, it creates a system notification ("Error fetching updates"). It seems that hyperterm checks every 10-15 minutes or so, leading to the annoyance of many new system notifications.

In my case, it's likely due to the necessary ports being blocked at work, but there could be a number of other reasons why hyperterm might not be able to check for updates. Would it be better to have hyperterm fail silently when checking for updates?

Edit: Some sort of exponential backoff could be good for this, as well.

**Comment by montogeek** [comment]
Or stop checking for updates after X failed attempts :)

**Comment by ahutchings** [comment]
I'm getting this as well. Looks like the autoupdater feed URL uses a .sh top-level domain. That is likely to be blocked in many work environments. Would it be possible to switch to a more common TLD?

**Comment by alanhussey** [comment]
Here's a screenshot of the error. If someone can direct me to the location of a log file, or something else that would help in debugging this, I'd be happy to help.

<img width="320" alt="screen shot" src="https://cloud.githubusercontent.com/assets/383725/17004489/16b4edc2-4e8a-11e6-9e97-5fb57bfed2f8.png">

**Comment by rwwagner90** [comment]
I'm also having this issue

**Comment by controversial** [comment]
I've got the same issue. It varies between "the request timed out," "the network connection was lost," and something like "could not locate bundle" (I didn't catch the exact message)

**Comment by jcreamer898** [comment]
Getting a similar error...

![](http://d.pr/i/eNvg+)

**Comment by controversial** [comment]
@jcreamer898 That's the one I've got (or, rather, one of the three). Any idea what causes this @rauchg ? The developer console doesn't have any information besides a lot of repeated `Cannot read property 'shell' of undefined` errors

**Comment by albinekb** [comment]
Possibly have them hosted on github (when signing works)?

**Comment by rauchg** [comment]
This should be resolved shortly. We switched to a new builder mechanism that introduced a minor mismatch

**Comment by sethlopezme** [comment]
I have gotten a lot of different error messages. I think this screenshot includes them all. I received notifications for all of these (and more) within the past hour.

![image](https://cloud.githubusercontent.com/assets/5733658/17146936/6b0bd2f2-532e-11e6-8482-a84305f6749a.png)

**Comment by rauchg** [comment]
Apologies 🙈

**Comment by alanhussey** [comment]
Looks like the latest release has resolved this, at least for me.

**Comment by controversial** [comment]
Me too

**Comment by auszone** [comment]
+1

**Comment by chabou** [comment]
Fixed
