### ISSUE TITLE
Theme colors are not applied correctly in windows

### ISSUE THREAD

**Issue by husainaloos** [zeit/hyper#2524]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 x64
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/husainaloos/a12023e11cce623b72e639a411ceeb92
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

In windows, I have tried multiple themes. None of them seem to work. I have tried multiple themes, and even two themes at the same time. The only thing that is applied is the background color, font color, and the color of the cursor. The path color is not changed.

![image](https://user-images.githubusercontent.com/4754802/33668588-d37791ea-da65-11e7-8c84-507312cc2bbb.png)

Is this a windows issue? or am I doing something wrong?

**Comment by ManuelVargas1251** [comment]
Solution seems to be to reset your command prompt properties. I used option two from [this comment](https://github.com/zeit/hyper/issues/1706#issuecomment-302873966) in a related issue  and it fixed my problem.

**Comment by husainaloos** [comment]
@ManuelVargas1251 I tried option 2 and 3 and both didn't work. I noticed that there were talking about the linux subsystem. I am using the normal cmd.

**Comment by MAPESO** [comment]
@husainaloos @ManuelVargas1251 Some themes are **not compatible with Windows**, the subject which you are trying to apply has transparency. The effects of transparencia do not have results in the versions windows.

This problem is related to Electron and not Hyper 😞

**Comment by nzvtrk** [comment]
@husainaloos this problem has been solved for me after i wrote shell path in .hyper.js
Its work for me on windows10 and windows7

**Comment by chabou** [comment]
For text color, themes only concern background/foreground color and ANSI colors. CMD doesn't use any ANSI colors.
But yes, it will work with a configured shell on WSL or GitBash/Cygwin.

Coloring path is a shell feature, not a terminal feature.

**Comment by Chokerino** [comment]
@husainaloos did u get it working for cmd?

**Comment by husainaloos** [comment]
@Chokerino No. I don't use hyper anymore.
