### ISSUE TITLE
Hyper can’t handle non-monospaced fonts

### ISSUE THREAD

**Issue by henryhadlow** [zeit/hyper#2525]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.6 (16G1036)
- **Hyper.app version**: 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/henryhadlow/3d5a5ec3dd4284d2dbd558f1288d3915
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Change font to non-monospaced

## Issue

If you change the font to non-monospaced, the cursor doesn’t stay with the end of the line.

<img width="164" alt="screen shot 2017-12-06 at 15 46 07" src="https://user-images.githubusercontent.com/2234084/33670704-92ab1ece-da9d-11e7-922b-e34ad0c50c47.png">

This is because it moves a specific number of px with every character, but with a non-monospaced font, certain characters are wider.

Now I know you’re thinking 'what kind of person uses a non-monospaced font in their Terminal' but wait!

iA writer have released a [really nice 'duospaced' font](https://github.com/iaolo/iA-Fonts/tree/master/iA%20Writer%20Duospace), based on IBM’s new [Plex type family](https://ibm.github.io/type/).

This is mainly monospaced, but uses 1.5x spaces for the characters `m`, `w`, `M` and `W`.

I’m using it in Sublime Text and it’s great, much easier to read.

**Comment by albinekb** [comment]
The reason why terminals and editors use monospaced font is so that the code will line up, if you have 1.5x chars, it will shift that row by 0.5x char widths, which will make two lines that have the same amount of characters in them, not line up:

```
this line has 23 chars.
this lime has 23 chars.
```
the line with `m` 1.5x spaced will render kinda like this:
```
this line has 23 chars.
this lime  has 23 chars.
```

So even if we supported it, it wouldn't make sense? 🤔

**Comment by qobilidop** [comment]
Just to add another motivation, support for non-monospaced fonts is necessary for powerline fonts, otherwise, [some glyphs won't render nicely](https://github.com/bhilburn/powerlevel9k/wiki/Troubleshooting#icons-are-cut-off), which is the case for hyper.

**Comment by Thatkookooguy** [comment]
You can try [Powerline fonts](https://github.com/powerline/fonts) which are monospace fonts modified with extra characters for things like that

Follow the installation guide for the fonts. After that, you can change to that font in the config like so:
```
fontFamily: '"Ubuntu Mono derivative Powerline"'
```
You can also add fallback fonts like so:
```
fontFamily: '"Ubuntu Mono derivative Powerline", <other_font>'
```

**Comment by qobilidop** [comment]
@Thatkookooguy thanks for the suggestion.

**Comment by albinekb** [comment]
How does other terminals handle this? @qobilidop 
The only way I can think of is to treat all chars as monospaced and just let them overflow the box into the next one? Because shifting rows other than at the columns would break so many things (cursor nav, terminal-width reporting etc)

**Comment by qobilidop** [comment]
@albinekb Sorry I'm don't know the internal working of Hyper and other terminals, but I know that VS Code's terminal handles my fonts correctly.

**Comment by albinekb** [comment]
That's a good sign as we will handle the fonts exactly like VS Code's terminal does it. VS Code uses xterm version **3**. We're currently using version **2.x** in canary, but before the sharp release of hyper 2 we will most likely have migrated to the latest xterm **===** your fonts will work like in VS! 🎉

**Comment by Thatkookooguy** [comment]
usually, the terminal expects a monospaced font. don't think any terminal handles non-monospace. you might be able to set those fonts for the terminal, but the terminal won't fix the difference. it assumes the font it uses is monospaced as far as I know

**Comment by qobilidop** [comment]
@albinekb I tried the xterm3 version, and it indeed fixed my font issues. Thanks for the great work. I'm looking forward to the new release!

@henryhadlow Sorry I have hijacked your threads for my own issue, although I feel they are related in the first place.

**Comment by dougmaitelli** [comment]
Just a short update here, I am facing some issues related to non monospaced fonts even in the latest canary version.

FuraCode NF Mono:
![image](https://user-images.githubusercontent.com/1277391/36485289-20918934-171c-11e8-987a-44444c0ccf5a.png)

FuraCode NF:
![image](https://user-images.githubusercontent.com/1277391/36485214-eb531e90-171b-11e8-9638-771dd027bbd3.png)
