### ISSUE TITLE
Always hide scrollbar

### ISSUE THREAD

**Issue by dweidenfeld** [zeit/hyper#2526]
- **OS version and name**: Arch Linux
- **Hyper.app version**: Canary
- No Plugins installed

## Issue
Is there a way to disable the scrollbar completely?
Don't get me wrong, it is working great, but I don't need it because I am more the keyboard guy 😄 

thanks ;)

**Comment by albinekb** [comment]
add
```
    // custom CSS to embed in the main window
    css: '.xterm-viewport { overflow: hidden; }',
```
to your `.hyper.js`

It will not disable the scroll since the scroll is simulated in xterm2 (used in canary), so this will just make the virtual scroll layer not show the faked scrollbar 👍
