### ISSUE TITLE
Warn about `npm install` attempt without the electron flags

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#253]
https://github.com/zeit/hyperterm/blob/master/scripts/install.sh#L3-L11

We can probably do a `preinstall` that warns for example if `npm_config_disturl` is not `electron`?

**Comment by dfrankland** [comment]
It's probably a good idea to create a [per-project config file `.npmrc`](https://docs.npmjs.com/files/npmrc#per-project-config-file) that has all the necessary configurations set. For example it could have these settings that would be used each time `npm` is used:

`hyperterm/.npmrc`
```
arch = x64
disturl = https://atom.io/download/atom-shell
runtime = electron
target = 1.2.5
build_from_source = true
```

Then you would be able to remove the [`hyperterm/scripts/install.sh`](https://github.com/zeit/hyperterm/blob/master/scripts/install.sh) script.

**Comment by albinekb** [comment]
Since `.install.sh` got removed, is this still an issue?

**Comment by chabou** [comment]
Feel free to reopen if this is still an issue
