### ISSUE TITLE
app.Tray closes itself

### ISSUE THREAD

**Issue by tarutin** [zeit/hyper#2534]
- **OS**: MacOS 10.13.2
- **Hyper.app**: Hyper 2.0.0-canary.8 (stable) (and I'm try stable version 1.4*)
- **Gist**: https://gist.github.com/tarutin/2ee23e7ef55ae2ebd32bca0111b73787

## Issue

Hi,
I found a little strange bug when develop plugin [hyper-tray](https://github.com/tarutin/hyper-tray): system tray closes itself after 1 minute on app started.

**Comment by MAPESO** [comment]
@tarutin Hi, thanks for having developed a complement for **hyper**. I will check your problem 😄

**Comment by MAPESO** [comment]
@tarutin  We are not using system tray. Maybe a Hyper behaviour is breaking it 🤔

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
