### ISSUE TITLE
Problems when resizing in single tab mode.

### ISSUE THREAD

**Issue by ineeve** [zeit/hyper#2535]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows10 1709
- **Hyper.app version**: 2.0.0-canary.8 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/ineeve/8cb729e7a39071eaebfca0fa90fb867a)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Hyper resizing is still not working well on Windows. Text is cutoff causing loss of information.
The issue happens at least when using PowerShell or CMD on Windows, haven't tried with other shells. 
How to reproduce:

1. Write something into the shell.
2. Resize quickly left and right.

Before resizing:
![Before resizing](https://user-images.githubusercontent.com/18349054/33795012-5da64b98-dccf-11e7-8c2a-7f44271541f0.PNG)

After resizing:
![After resizing](https://user-images.githubusercontent.com/18349054/33795013-626aae8a-dccf-11e7-9b08-5682947904ed.PNG)

**Comment by MAPESO** [comment]
@ineeve We are aware of the problems that Hyper has when resizing in the versions of OS X, Linux and Windows. We are working on it 😼 

Thanks for making the report.
