### ISSUE TITLE
How to open hyper with a shortcut in Windows 10? 

### ISSUE THREAD

**Issue by Hixon10** [zeit/hyper#2536]
When we are using default terminal, we can use some shortcut like **ctrl + shift + T** for opening terminal. What is the best way to do this for hyper in Windows 10? 

I know, that there are many 3d party software, which can listens hotkeys event and do some shit. But it is unreliably.

**Comment by Stanzilla** [comment]
CTRL + Shift + T works just fine in Hyper, what exactly do you mean?

**Comment by Hixon10** [comment]
@Stanzilla I am sorry, I did typo. I mean, **ctrl + alt + T** hotkey, which is opened a default terminal.

**Comment by peterdanis** [comment]
You can use [hyperterm-summon](https://github.com/Soutar/hyperterm-summon) plugin. Or put your hyper app on taskbar and run start it with `Win+number` key, for example if hyper app is 3rd in row on your taskbar, hit `Win+3` keys together and it will start the app or switch directly to it (if already running).

**Comment by Hixon10** [comment]
thank you

**Comment by TomYeoman** [comment]
> 
> 
> You can use [hyperterm-summon](https://github.com/Soutar/hyperterm-summon) plugin. Or put your hyper app on taskbar and run start it with `Win+number` key, for example if hyper app is 3rd in row on your taskbar, hit `Win+3` keys together and it will start the app or switch directly to it (if already running).


No way have I just found this shortcut out after all these years on windows, works a treat with terminal always set as 1!

**Comment by DoctrNikhil** [comment]
> > You can use [hyperterm-summon](https://github.com/Soutar/hyperterm-summon) plugin. Or put your hyper app on taskbar and run start it with `Win+number` key, for example if hyper app is 3rd in row on your taskbar, hit `Win+3` keys together and it will start the app or switch directly to it (if already running).
> 
> No way have I just found this shortcut out after all these years on windows, works a treat with terminal always set as 1!

This is fantastic shortcut for windows 10.
