### ISSUE TITLE
Hyper.js CONFIG move in Root programm?!

### ISSUE THREAD

**Issue by mrG0bliN** [zeit/hyper#2540]
windows 10 x64
Hi guys, my madness is to carry all my programs on a flash drive, and then take it with me, because after two weeks of setup, other programmers also want such a cool terminal and the same cool code editor as me, and I'm greedy and do not want with whom he shares.

By this, any possible crutches I move the config files to myself in one folder, most often to the root of the installed program.

Tell me please how can I move my config from: AppData \ Roaming \ Hyper \
to: The root of the program.

**Comment by mrG0bliN** [comment]
so sad' 

> opened this issue 7 days ago · 0 comments

**Comment by ppot** [comment]
❤️  here one 😄 -> On a more serious note, we talked before on a way to save settings and sync them on your github and pull them. For the moment I can't of a best way to do so. Maybe on new installation a way to import existing settings.. I can't tell yet.

**Comment by albinekb** [comment]
What we could do is have a startup flag or environmental variable to override the config dir on startup, you could then point hyper to read the config from a specified location on startup. Something like `HYPER_CONFIG_DIR` maybe?

**Comment by mrG0bliN** [comment]
dead project 
close
