### ISSUE TITLE
Have to press enter twice after "exit"

### ISSUE THREAD

**Issue by Dids** [zeit/hyper#2541]
- **OS version and name**: macOS High Sierra (10.13.2)
- **Hyper.app version**: Hyper 2.0.0-canary.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Dids/95f0df9f1f3f336cbc811ac34264a619
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
```
bundle.js:1 (re)loading renderer plugins
bundle.js:1 Plugin hyper-materialshell (1.6.1) loaded.
bundle.js:1 Plugin hyper-quit (1.0.2) loaded.
index.html:35 total init time 113.00999999999999
```
- **The issue is reproducible in vanilla Hyper.app**: Yes, happens with and without plugins, on both stable and canary update channels. Only tested on 2.x versions though.

## Issue
I always have to press `Enter` twice after typing in `exit`, to exit/close the current Hyper session/window.

This happens on two different machines, but they are using the same configuration file.

**NOTE:** I've tested with and without plugins, which made no difference, so it's unlikely plugin related. Also worth noting that I've tested with and without `canary` updates, but still only with 2.x versions.

**Comment by Dids** [comment]
Just to update on this, it doesn't actually have to be the `Enter` key after pressing it once when executing `exit`, as it can be any virtually any key, so it's kinda like it's just pausing there.

**Comment by standage** [comment]
I've been experiencing this ever since the upgrade to OS 10.13.

**Comment by midgethoen** [comment]
I'm having the same issue. in case its of any relevance:

https://github.com/zeit/hyper/issues/2545#issuecomment-351423471

> to verify that te process has indeed ended I tried the same procedure in terminal.app and iterm2
which work as expected. (iterm2 closes tab/window, terminal.app shows [Process completed])

**Comment by lee-dohm** [comment]
Confirmed using macOS 10.13.2 and Hyper v1.4.8 (stable) with a completely blank configuration.

**Comment by tborychowski** [comment]
same here. 
That's the last issue that stops me from switching from iTerm 😄

**Comment by lee-dohm** [comment]
I was also just able to reproduce this using Hyper 2.0.0-canary.8 (stable) on macOS 10.13.2 using the same reproduction steps as above.

**Comment by MindTooth** [comment]
Not sure if it's related to canary.9, but I haven't had this issue the past couple of days.

**Comment by Dids** [comment]
Confirmed working.

**Comment by xychu** [comment]
Could anyone kindly point out which commit fix this bug? Like to learn from it :-)
