### ISSUE TITLE
Have to hit ctrl-d twice to close window/tab

### ISSUE THREAD

**Issue by midgethoen** [zeit/hyper#2545]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OSX 0.13.2
- **Hyper.app version**: 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://github.com/zeit/hyper/blob/canary/app/config/config-default.js
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: YES

## Issue
I need to hit ctrl-d twice to cause a tab/window to close.  
My set up is very vanilla: just hyper + oh-my-zsh on a fresh machine...

this is a video of me reproducing:

![untitled](https://user-images.githubusercontent.com/4599476/33946175-5fd05efe-e021-11e7-897d-8b0654185159.gif)

this is me hitting: cmd+n, 2x cmd+t, 6x ctrl+d  

not sure what is going on or how to troubleshoot this. any help would be appreciated.

**Comment by midgethoen** [comment]
in addition to the info above. 

to verify that te process is indeed ended I tried the same procedure in  terminal.app and iterm2
which work as expected. (iterm2 closes tab/window, terminal.app shows `[Process completed]`)

**Comment by midgethoen** [comment]
Turns out my issue search was too narrow: this is most likely a duplicate of: 2541

closing this one now

**Comment by albinekb** [comment]
Thanks for reporting this @midgethoen 🙌 And yes, looks like the same issue. Thanks for closing this, let's look at it in the other issue 👍
