### ISSUE TITLE
Send notification when a task finishes

### ISSUE THREAD

**Issue by divyanshu013** [zeit/hyper#2546]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 27 Linux x64
- **Hyper.app version**: 2.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/divyanshu013/810214867d0bae583ea5d7bd0d203af7
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: NA
- **The issue is reproducible in vanilla Hyper.app**: NA

## Issue

I am looking for a way to send notification from hyper after a task is finished, for example after `npm install` finishes or some operation say, copying a directory or running an update on system is finished. How can I extend hyper to achieve this? Thanks!

**Comment by albinekb** [comment]
I think this is better handled by your shell, if you're using [fish shell](https://fishshell.com/) and [fisherman](https://fisherman.github.io/) it's as easy as doing `fisherman install done`, (https://github.com/fisherman/done)

I think there's similar plugins for zsh and bash?

**Comment by divyanshu013** [comment]
Thanks @albinekb, I took a look and found https://github.com/t413/zsh-background-notify to be just what I needed. Was a simple matter of adding `bgnotify` to my .zshrc in `plugins`. Works like a charm.

Appreciate the help, closing the issue :smile_cat:

**Comment by albinekb** [comment]
Glad I could help ☺️
