### ISSUE TITLE
Transparent background when Hyper background color is set to white

### ISSUE THREAD

**Issue by christopherdwhite** [zeit/hyper#2547]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13.2
- **Hyper.app version**: Hyper 2.0.0-canary.8 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/christopherdwhite/b055aacca0a3223628d0fe3ed3964490
- **Relevant information from devtools**

![Dev Tools](https://api.monosnap.com/rpc/file/download?id=NqwO5rKjDf4x4hgWQlHrihroS9sjLp)

- **The issue is reproducible in vanilla Hyper.app**: Not quite but close, if I start with vanilla and only change lines 9 and 31 to `updateChannel: 'canary',` and `backgroundColor: '#FFF',` respectively the issue is reproducible. Here is a [gist of the tweaked vanilla version](https://gist.github.com/christopherdwhite/bb3b2401cadf4160384453d523702f0c)

## Issue
For some reason my Hyper configuration started having a problem a couple of days ago where a white background color is showing up entirely transparent.

![Screenshot](https://api.monosnap.com/rpc/file/download?id=Tb1kcg98kzybViLQ6fktD4Qy9kBRlx)

It was working fine previously and I didn't take note of whether there was an update or other change before it started happening (I'm assuming it was canary 8); I did not change .hyper.js at the time.

A couple of additional notes:

- Making any changes to .hyper.js temporaily fixes the issue on any open windows, new windows however start transparent again. Neither a **Reload** nor a **Full Reload** temporarily fixes the issue.
- The issue only begins happening after restarting following the green `Version 2.0.0-canary.8 read. Improved live reloading, keymaps and sweeter cursors!` banner shows up. If I set it back to stable or delete .hyper.js and change the background color it works fine (at least after Hyper switches back to stable and the green `Version 1.4.8 ready.` banner appears)
- The only background color I've tried that has an issue is white, `backgroundColor: '#FFF',` and `backgroundColor: 'hsla(0, 100%, 100%, 1)',` have the issue, but using `000`, `111` or even `DDD` all work fine, no transparency.
- I mentioned this in the Slack channel and said I thought it was due to `-webkit-backface-visibility: hidden;` on the `body` but I think this was a red herring, I mistook setting it explicitly for a fix when it was just temporarily working after a configuration update and reloaded window.
- I had to do a nuke and pave of my OS after it first began happening due to an unrelated iCloud Drive problem and I then copied my .hyper.js over to the new system along with all my other dotfiles, it continued happening on the fresh new system.
- The .hyper.js file is symlinked from my local dotfiles repo to `~/` but I confirmed that it was unrelated when I deleted the file to get back to vanilla.

This is how it looks with a vanilla config set to canary and a white background, it also illustrates that it works as expected on windows open when a config update is reloaded and that additional new windows are back to transparent.

![Vanilla](https://api.monosnap.com/rpc/file/download?id=9nL7Rn10gEDsBQeE3aM5TCCeTR4g6S)

You may notice from my earlier screenshot that other UI elements with a white background color explicitly set such as the active tab do not have any issue. 

Likewise, explicitly setting the body background color to white in the CSS entirely fixes the issue:

```js
// custom CSS to embed in the main window
css: `
    body {
        background-color: #FFF
    }
`,
```

**Comment by MAPESO** [comment]
@christopherdwhite It is strange that the **canary 8** version "breaks" with transparency.

**Comment by christopherdwhite** [comment]
@MAPESO yeah definitely a strange one, the fact that it only seems to break when set to white seems like the weirdest part to me.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by jcklpe** [comment]
@christopherdwhite  Hey Chris would you happen to know how to make this happen on purpose? Does it still do this for you? https://github.com/zeit/hyper/issues/3267

**Comment by christopherdwhite** [comment]
@jcklpe Other than what I wrote in the original report I don't recall the details, you could probably reproduce the issue by putting the code snippet above into your configuration. That said, I haven't gone back to test it with newer versions, it may have been fixed.
