### ISSUE TITLE
Font rendering bug back on Canary 8

### ISSUE THREAD

**Issue by lucasqueiroz** [zeit/hyper#2548]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra (10.13.1)
- **Hyper.app version**: Canary 8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/lucasqueiroz/e2ca507927bc7b358afc86c89f22489f
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

On Hyper Canary 7, the font renders correctly for some special characters:
<img width="1271" alt="screen shot 2017-12-14 at 10 46 57" src="https://user-images.githubusercontent.com/29466590/33993953-d946cb6c-e0bf-11e7-9883-55365cd8ec51.png">

But on Canary 8, the font bugs:
<img width="1269" alt="screen shot 2017-12-14 at 10 45 12" src="https://user-images.githubusercontent.com/29466590/33993969-e44ff614-e0bf-11e7-8f48-73ac9763e1f0.png">

**Comment by lucasqueiroz** [comment]
It now happens on canary 7 too. It is weird because at first, it works fine. But after some time, it starts happening again.

**Comment by chabou** [comment]
Can you try to reproduce with last canary (which uses xtermv3)

**Comment by chabou** [comment]
I will pretend that is has been fixed in v2.
Do not hesitate to add some comment if not

**Comment by lucasqueiroz** [comment]
I didn't see the previous comment, sorry! It has been fixed after the xterm update :)
