### ISSUE TITLE
Can't use ctrl+h as a keymap command

### ISSUE THREAD

**Issue by wordofchristian** [zeit/hyper#2549]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.1 
- **Hyper.app version**: 
![screenshot 2017-12-14 09 25 39](https://user-images.githubusercontent.com/555044/34005745-c80b1510-e0b0-11e7-9ffe-8802dab513c7.png)

- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/wordofchristian/e45ba23b795fe81e0b0bcf862e6a0ac9
## Issue
I'm trying to change the keyboard shortcuts for `pane:next` and `pane:prev` to `ctrl+L` and `ctrl+H` respectively.

```
  keymaps: {
    "pane:next": "ctrl+l",
    "pane:prev": "ctrl+h"
  },
```

The `ctrl+L` works but the `ctrl+h` does nothing.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
