### ISSUE TITLE
Weird manpage output

### ISSUE THREAD

**Issue by sholladay** [zeit/hyper#2553]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.1
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/sholladay/85bddc67eb9c7071f9006d62ce166953
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: I believe so, but not sure. My config is very close to default.

## Issue

Running `man node` outputs two weird lines at the beginning that do not appear when I run the same command in Terminal.app.

```
`R' is a string (producing the registered sign), not a macro.
`R' is a string (producing the registered sign), not a macro.
NODE(1)                                         Node.js                                         NODE(1)

NAME
       node - Server-side JavaScript runtime

SYNOPSIS
...
```

The weird part is this:
```
`R' is a string (producing the registered sign), not a macro.
`R' is a string (producing the registered sign), not a macro.
```

**Comment by silverwind** [comment]
This is likely a issue with node's manpage, see https://github.com/nodejs/node/issues/18434

**Comment by sholladay** [comment]
Huh okay, interesting. Figured it was Hyper cause it worked fine through Terminal.app for me (using the same shell, etc).

I think we should keep this open until I have a chance to test with that patch. But it looks promising!

**Comment by silverwind** [comment]
In your case, I suspect that `terminal` invokes a different shell environment which maybe has a different manpager set up. try comparing the output of `env` in both terminals.

**Comment by Alhadis** [comment]
When `man` runs and finds a manual page to display, it passes it through `troff` to generate SGR-encoded output fit for terminal display. It calls `troff` with preconfigured command-line switches, one of which is to suppress all error messages (specifically, `-Wall`). See the options section in `troff(1)` and 
check what's been set in `/etc/man.conf`:

~~~
TROFF         /usr/local/bin/groff -Tps     -mandoc
NROFF         /usr/local/bin/groff -Tutf8   -mandoc  -Wall
~~~

**Comment by silverwind** [comment]
@Alhadis Thanks for the pointer. I just compared the defaults in macOS and Linux and `groff` emits the warnings in both cases, but in Linux it appears that the `man` utility supresses printing them when the output is a pager. I can see them via `man node > /dev/null`. It appears the `man` utility on macOS does not have that functionality.
