### ISSUE TITLE
Failed to replace env in config: ${APPDATA}

### ISSUE THREAD

**Issue by saravanaselvan** [zeit/hyper#2554]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1 Pro
- **Hyper.app version**: 1.4.8
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla
## Issue
Whenever I open the app I get "Error updating Plugins". Yarn-error.log has the below error trace:

```
  Error: Failed to replace env in config: ${APPDATA}
      at value.replace (C:\Users\xxxx\AppData\Local\hyper\app-1.4.8\resources\bin\yarn-standalone.js:78029:13)
      at String.replace (<anonymous>)
      at envReplace (C:\Users\xxxx\AppData\Local\hyper\app-1.4.8\resources\bin\yarn-standalone.js:78024:16)
      at C:\Users\xxxx\AppData\Local\hyper\app-1.4.8\resources\bin\yarn-standalone.js:30292:73
      at Generator.next (<anonymous>)
      at step (C:\Users\xxxx\AppData\Local\hyper\app-1.4.8\resources\bin\yarn-standalone.js:91:30)
      at C:\Users\xxxx\AppData\Local\hyper\app-1.4.8\resources\bin\yarn-standalone.js:102:13
      at <anonymous>
```
Tried setting a new environment variable APPDATA based on the 'npm config list' prefix property. Not working. 

**Config file updates (.hyper.js):**

1. shell: `C:\\windows\\system32\\cmd.exe`
2. Removed `--login` from shellArgs

**Comment by MAPESO** [comment]
@saravanaselvan Try to remove hyper and reinstall.

If the error persists, let me know 🙏

**Comment by saravanaselvan** [comment]
@MAPESO Unfortunately even after reinstalling the error is still there :-(

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Also remember to post your full config file. Thank you!
