### ISSUE TITLE
Can't open preferences on Windows (default WScript.exe not properly detected)

### ISSUE THREAD

**Issue by schlamar** [zeit/hyper#2557]
I'm getting an error from Windows Script Host when opening the preferences:

    'module' is undefined

in ~\.hyper.js

My guess: WScript.exe is the default for JS files, which is not properly detected in https://github.com/zeit/hyper/blob/cb8b72a319789f5f74b7044b8be36cfe26471417/app/config/open.js. It's not clear for me what this module is actually doing (promises, resolve, ?!). Here is the relevant registry configuration which is read in open.js:

    [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.js]

    [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.js\OpenWithList]
    "a"="firefox.exe"
    "MRUList"="ab"
    "b"="notepad++.exe"

    [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.js\OpenWithProgids]
    "JSFile"=hex(0):

Versions:

        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 6.1.7601

**Comment by albinekb** [comment]
Wow, thanks for those keys. I wrote that confusing code you linked. I will see what I can do with this information and at the same time try to simplify the code using async/await instead of the old school promises. 👍

**Comment by albinekb** [comment]
Fixed in latest canary https://github.com/zeit/hyper/releases/tag/2.0.0-canary.11 🎉
