### ISSUE TITLE
Unable to scroll manpages via mousewheel

### ISSUE THREAD

**Issue by sholladay** [zeit/hyper#2558]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.1
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/sholladay/85bddc67eb9c7071f9006d62ce166953
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: I suspect so, but haven't tried yet.

## Issue

Manual pages are not scrollable with the mouse wheel (or at least a trackpad on a Macbook Pro).

```
man node
```

... for example.

The down arrow on the keyboard works. And once I have arrowed down, I can scroll back up with the mouse wheel.

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/1842
