### ISSUE TITLE
Hyper can't open cmder

### ISSUE THREAD

**Issue by guiscaranse** [zeit/hyper#2559]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [https://gist.github.com/guiscaranse/5f21257b7a195b09b8067d2582190ed1](https://gist.github.com/guiscaranse/5f21257b7a195b09b8067d2582190ed1)
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I am not able to execute cmder inside Hyper. It just takes me to the default cmd. I've used the tips in this [guide](http://blog.bsinky.com/programming/tools/2017/06/11/using-cmder-with-hyper.html) but wasn't able to reproduce the cmder inside hyper.

**Comment by albinekb** [comment]
What is the issue? What should happen? How to reproduce? What's not working? What should be fixed in Hyper?

Please read [this](https://github.com/tomchentw/react-google-maps#getting-help)

**Comment by guiscaranse** [comment]
> What is the issue? What should happen? How to reproduce? What's not working? What should be fixed in Hyper?
Sorry If I was unclear. Using the ´.hyper.js´ it is possible to set a custom terminal as seen [here](https://gist.github.com/guiscaranse/5f21257b7a195b09b8067d2582190ed1#file-hyper-js-L87-L95). Cmder is a custom terminal for windows that implements a lot of useful features, it uses Conemu for hosting the cmd with the custom features.
Pointing Hyper to use the comemu wrapper doesn't do anything, I am not sure if it is a problem with hyper itself or with the conemu wrapper. To reproduce, install cmder and use my ´.hyper.js´ provided above. 
For me, it seens like Hyper just ignore the start script and takes user to cmd. As cmd is the default shell on windows.
Not sure tho where to fix exactly, but the real question is if someone tried to use an alternative shell instead of cmd or powershell and if worked indeed as reported [here](http://blog.bsinky.com/programming/tools/2017/06/11/using-cmder-with-hyper.html)

**Comment by guiscaranse** [comment]
Well, not sure why but restarting the computer did the trick.

**Comment by albinekb** [comment]
Thanks for adding that information 🙂  @guiscaranse Also sorry if I sounded rude, it wasn't meant like that. Awesome to hear that restarting did the trick, if you find that it's coming back, please feel free to re-open this issue and I will take a 👀

**Comment by guiscaranse** [comment]
It's okay :)

**Comment by DRSDavidSoft** [comment]
For future visitors: no need to restart the whole computer, just reload the Hyper window.
