### ISSUE TITLE
System cannot find path

### ISSUE THREAD

**Issue by NodeEra** [zeit/hyper#2564]
Just installed it and it says that the system cannot find path. Yes I tried running as Administrator and there is still the error.
        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.17063
![screenshot 1](https://user-images.githubusercontent.com/34990908/34464524-3b275104-ee48-11e7-9a82-44ede8e5ce11.png)
x64 10.0.17063

**Comment by MAPESO** [comment]
@NodeEra Hi, What shell are you using? 😸

**Comment by MAPESO** [comment]
@NodeEra The shell that I'm using is **Ubuntu**
![26610681_1209796539163934_2119756364_o](https://user-images.githubusercontent.com/16585386/34527837-8443c680-f06c-11e7-8d9e-43b5421075a7.png)

**Comment by chabou** [comment]
Please attach your config file (as asked in template issue). Note for later: this is important to fill issue template. It prevents some round trip between the community and you to obtain enough informations to reproduce your issue.

**Comment by Stanzilla** [comment]
```
    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instad of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    // shell: 'C:\\Windows\\System32\\cmd.exe',
    shell: 'C:\\Windows\\System32\\wsl.exe',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: [],
```

for WSL on Windows. If your problem was something different, please open a new issue and be more precise.
