### ISSUE TITLE
Not able to find the application installed in Program Files

### ISSUE THREAD

**Issue by mittalyashu** [zeit/hyper#2565]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: Don't know

**Comment by chabou** [comment]
Like most of Electron apps, Hyper is installed in AppData: `C:\Users\<username>\AppData\Local\hyper`

**Comment by mittalyashu** [comment]
It is not showing in Programs & Features.

![image](https://user-images.githubusercontent.com/29014463/34514286-b4ce63e8-f092-11e7-8518-7f38efa1c7d1.png)

**Comment by chabou** [comment]
It does on my Win10:
![image](https://user-images.githubusercontent.com/4137761/34514931-0d273024-f070-11e7-821f-eb63274fb68f.png)
🤔

**Comment by albinekb** [comment]
@mittalyashu it shows for me too, can you please try to install it again and see if your issue persists. Thanks

**Comment by MAPESO** [comment]
![26613818_1209789585831296_2003941057_o](https://user-images.githubusercontent.com/16585386/34527314-d621ac30-f06a-11e7-9287-fa3095766be8.png)

@mittalyashu Maybe installed Hyper wrong 😢

**Comment by mittalyashu** [comment]
https://www.useloom.com/share/4b6523c057724f8fa9115fb4784748af

I have checked again and now is showing, but when I installed (yesterday) that time it was not showing on the list.
