### ISSUE TITLE
Config setting to choose terminal emulation type?

### ISSUE THREAD

**Issue by thoughton** [zeit/hyper#2567]
Hi,

New user here. I was just wondering whether there's a `.hyper.js` setting to select the desired terminal emulation type?

For example, in the OS X Terminal app I have `Declare terminal as` in its Preferences set to `xterm-16color`, and ideally I'd like a way to set Hyper to use the same too.

Cool project by the way - thanks!

**Comment by chabou** [comment]
In `.hyper.js` config file, you have a `env` object setting. You can override terminal type by adding a TERM entry:
```
  ...
  env: {
    TERM: 'xterm-16color'
  }
  ...
```

**Comment by thoughton** [comment]
I'm not an expert, so I could be mistaken, but it was my understanding that the user generally should not set the `$TERM` (or `$COLORTERM`) environment variables manually, via startup scripts or otherwise. Rather, it should (I think) be the terminal application itself that sets those environment variables to reflect its own settings.

For example, on the same system, when running the `Terminal` app I see the following:
```
$ export |grep TERM=

declare -x TERM="xterm-16color"
```
(Presumably reflecting my aforementioned Preferences setting.)

However, in `Hyper` I see this:
```
$ export |grep TERM=

declare -x COLORTERM="truecolor"
declare -x TERM="xterm-256color"
```
So presumably there's something internal within Hyper that's setting these different values according to the emulation type it's using, but unlike with Terminal there doesn't seem to be a way for me to change that (internal) setting...

**Comment by thoughton** [comment]
Ah, perhaps you're right. I'll be honest, it still feels wrong to me - it feels like there should be a setting in .hyper.js to tell it the terminal type and then when the config is loaded it sets the relevant environment variables as required - but I'm happy to close this now, as it's quite likely I'm misunderstanding how these things are meant to work.

**Comment by lcamilo15** [comment]
I was getting a terminal error when using cygwin as a terminal, the following did the trick for me. This is for Windows 10. 

     alias clear='_TERM=$TERM;TERM=cygwin;/usr/bin/clear;TERM=$_TERM';
