### ISSUE TITLE
Chinese font can't be well display

### ISSUE THREAD

**Issue by caocanx** [zeit/hyper#2569]
-
        Hyper 1.4.8
        Electron 1.7.8
        darwin x64 17.3.0

When I edit a php file that include chinese font, I find the chinese word can't be displayed clearly. Hope someone can help me.

**Comment by chhschou** [comment]
Please try the `2.0.0-canary.8` release (please see https://github.com/zeit/hyper/releases). It has better support for Chinese.

**Comment by caocanx** [comment]
Thank you, it solved my problem.

**Comment by albinekb** [comment]
Great to hear @caocanx 👍
