### ISSUE TITLE
Open Hyper running a set of tabs

### ISSUE THREAD

**Issue by GabrielDuarteM** [zeit/hyper#2570]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 
- **Hyper.app version**: 1.4.8 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/anonymous/e5aa67e2434b3092bb4f21cb72f7bd33) 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A

## Issue

I'm currently trying to switch from `Cmder` to `Hyper`, but there is one feature that I don't know if it's present on Hyper, that is open a set of tabs through cmd line.

Currently, when I start my pc, I have a shortcut to open Cmder with two executables running in two different tabs. Is there any way to do that on Hyper? Something like executing `Hyper.exe 'execA.bat' 'execB.bat'` and with that, Hyper opening and running both execs in separate tabs?

**Comment by ppot** [comment]
For the moment you can take a look at Hyper layout on awesome hyper

**Comment by Stanzilla** [comment]
Or follow progress at https://github.com/zeit/hyper/pull/945
