### ISSUE TITLE
No able to clear console with git bash shell

### ISSUE THREAD

**Issue by darekf77** [zeit/hyper#2572]
In config, I have:
`shell: 'C:\\Program Files\\Git\\bin\\bash.exe'`
Everything is working fine, expect when I type: **clear**.
Output is still on console screen...

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.15063

**Comment by darekf77** [comment]
![bug_hyper](https://user-images.githubusercontent.com/7131693/34827329-0d80eb3a-f6da-11e7-95ff-04757c43e6b1.gif)

**Comment by pwsandoval** [comment]
Same, any solution?

**Comment by rianquinn** [comment]
Dup: https://github.com/zeit/hyper/issues/2715

**Comment by rianquinn** [comment]
I can confirm that `env: { TERM: 'cygwin' }` fixes this issue
