### ISSUE TITLE
Issue with `font-smoothing` in canary 9

### ISSUE THREAD

**Issue by vinkla** [zeit/hyper#2574]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.2 (17C205)
- **Hyper.app version**: Hyper 2.0.0-canary.9 (canary)

## Issue

Since version 2.0.0-canary.9 I'm seeing issues with font smoothing in Hyper. Some text appears to be antialiased and other as sub-pixel? This was not the case in canary eight.

<img width="770" alt="screen shot 2018-01-09 at 7 34 42 pm" src="https://user-images.githubusercontent.com/499192/34736860-a652bbb6-f574-11e7-8a9c-fff05014736f.png">

Please let me know if there is anything else I can provide to help debug this issue!

**Comment by MAPESO** [comment]
@vinkla The problem is related **Xterm 3**, for the moment there is not a solution 😞 
when we have the solution to the problem I will let you know.

**Comment by chabou** [comment]
@vinkla Thanks to #2669 you'll be able to disable/force bold font.
In your example, your prompt is normal and your `.git` folder is bold
