### ISSUE TITLE
Unexpected behavior when pressing the DELETE key

### ISSUE THREAD

**Issue by williambulin** [zeit/hyper#2577]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 1709 (and Arch Linux aswell)
- **Hyper.app version**: Hyper 2.0.0-canary9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/underscoreFami/64895a6b5458ac475cc12d9f7b7b68c2
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I have just installed Hyper on Windows 10 and on my Arch Linux machine and both seems to have the same problem resulting in an odd behavior when pressing the DELETE key.

Examples:
- In cmd.exe (Windows 10), pressing the DELETE key will add a 'd' character instead of removing the character
- In WSL/Arch Linux (running ZSH), pressing the DELETE key will remove a complete word instead of removing a single character
- In WSL/Arch Linux (inside the Nano editor), pressing the DELETE key will display the count of words, lines and characters instead of removing the character

Pressing CTRL+D removes the character as expected from the DELETE key though.

**Comment by Stanzilla** [comment]
Fixed when https://github.com/zeit/hyper/pull/2575 gets merged.
