### ISSUE TITLE
modifierKeys altIsMeta on Canary 9 build

### ISSUE THREAD

**Issue by saamalik** [zeit/hyper#2578]
- [x] I am on the latest Hyper.app version
- [x] I have searched the issues of this repo and believe that this is not a duplicate * (there were but closed now)

HI guys,
I'm on the latest `canary.9` build of hyper. Unfortunately, the `altIsMeta` modifier is not working as expected. Whenever the key combinations `alt+f` (move word forward), `alt+.` (last argument of the previous command) are pressed, some random silly looking special character is added. 

I'm on Mac OSX and trying to use the Option button as the _alt_ key. Here is the relevant section from the `.hyper.js`:

```
module.exports = {
  config: {
    modifierKeys: { altIsMeta: true },
...
}
```

**Comment by saamalik** [comment]
Related bugs:
https://github.com/zeit/hyper/issues/330 (Closed now)
https://github.com/zeit/hyper/issues/2251

**Comment by saamalik** [comment]
Can anyone else please confirm the same issue?

**Comment by albinekb** [comment]
Hello @saamalik! This is probably due to the upgrade of the terminal rendering/handling lib `xterm` to the latest v3. I don't know exactly why this has stopped working but thanks for reporting!

**Comment by saamalik** [comment]
Corresponding issue on underlying terminal: xtermjs/xterm.js#487

**Comment by saamalik** [comment]
Found a temporary solution. Add the following to your `~/.inputrc` file:
```
"ƒ": forward-word
"∫": backward-word
"≥": yank-last-arg
```

And restart your terminal (or run `bind -f ~/.inputrc`). It's a temporary solution since still other bashrc shortcuts do not work (e.g: `alt+1`, `alt+2`, ..). Hopefully a more generic solution is found.

**Comment by saamalik** [comment]
@albinekb proposed fix in underlying xterm.js library: [Mac OSX: altIsMeta support](https://github.com/xtermjs/xterm.js/pull/1225

**Comment by albinekb** [comment]
A w e s o m e  work @saamalik 🙏 😍
