### ISSUE TITLE
Canary9 is throwing exception in Windows.

### ISSUE THREAD

**Issue by lijunle** [zeit/hyper#2580]
It happens every time when I launch Hyper.js. Tried to delete `.hyper.js` file but no luck.

The error message is

```
Cannot read property value of undefiend
```

![image](https://user-images.githubusercontent.com/1296500/34762217-f9d238d6-f621-11e7-83c6-377cdda67e37.png)

**Comment by MAPESO** [comment]
@lijunle I will review your problem, when I have relevant information I will let you know 😸

**Comment by bcorcoran** [comment]
Did you change the default editor for .js extension?

**Comment by MAPESO** [comment]
@lijunle You could specify in more detail the version of your operating system 🙏

**Comment by bcorcoran** [comment]
Pretty sure this is the default program for .js on windows being the script execution process instead of notepad or something like that. Change .js to open with notepad by default (or any other text editor) and it will go away.

**Comment by MAPESO** [comment]
@bcorcoran This error is too recurrent in the Windows version. I'll have to fix it somehow.
@lijunle try to open the **hyper.js** file in a notebook.

If the error persists, let me know 🙏

**Comment by lijunle** [comment]
> Did you change the default editor for .js extension?

Yes, it is opened by VSCode. I have changed the default editor long time ago, don't think that is the cause.

**Comment by lijunle** [comment]
> You could specify in more detail the version of your operating system 🙏

It is on Windows Server 2016.

**Comment by MAPESO** [comment]
@lijunle Try to remove hyper and reinstall it. I can not replicate the error you have 😞

**Comment by lijunle** [comment]
I did that. 😢 Besides, I removed the folder under `C:\Users\...\AppData\Roaming\Hyper`.

What else folder may be used as cache?

**Comment by chabou** [comment]
This is not related to your config file.
This exception is thrown while it tries to add hyper directory to user path in registry.

I think that is because you haven't any `Path` user env var. Can you try to verify and create a `Path` variable if needed: https://msdn.microsoft.com/en-us/library/bb726962.aspx ?

Hyper should obviously handle this case but I want to be sure that this is the cause of your issue.

**Comment by lijunle** [comment]
Hmm... I have user variable named `PATH`. After manually change it to `Path`, the problem is resolved!

**Comment by chabou** [comment]
Oh ! thank you for your feedback.
I'll fix that.

**Comment by lijunle** [comment]
Besides, I think it could better not to enforce a user have the `PATH` variable.

**Comment by chabou** [comment]
yes obviously :)

**Comment by ed-alertedh** [comment]
For the benefit of anyone that may be googling it: it seems that canary9 may be unable to update itself to canary10 on Windows. I was getting the update ready notification appearing every time I restarted hyper. The workaround was to manually install canary10.

I totally understand this is an unstable release channel, but it seems there are many people on the canary channel to benefit from the xterm.js integration, so I felt this note might help a couple of people out!
