### ISSUE TITLE
Can't get any powerline font to be used in Hyper. Default to consolas.

### ISSUE THREAD

**Issue by JonWallsten** [zeit/hyper#2581]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **2.0.0-canary.9**: 
- **https://gist.github.com/JonWallsten/7ab3164fca765c942e5f79e758582c2f**: 
- **N/A** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **Is vanilla**: 

## Issue

I can't get any Powerline font to work. I've installed several of them. But Hyper always skips the font and moves on to the next in the font family list. I've tried fonts from "powerline/fonts" and NerdFonts. I've checked and made sure the font is installed and shows up in the font list in for example Word. I've copied the font-name from the list in work and pasted in the config. Still doesn't work. All other pre-installed windows fonts I've tried works. But not any of the powerline fonts. This is the result:

![image](https://user-images.githubusercontent.com/5993909/34769224-6efc8c08-f5fd-11e7-8c24-2a985d68db14.png)

I'm using Hyper and Oh-my-zsh with the Agnoster theme.

I've searched plenty of thread and everyone seems to have got it to work. But nothing I've tried has changed the outcome.

**Comment by JonWallsten** [comment]
And for some reason after opening Windows commander and running "bash", then opening Hyper it just started working. I have no idea why, and I'm not going to waste any more time trying o figure it out.

**Comment by Kitaharakasusa** [comment]
I meet the same problem, but your solve project isn't work for me.
