### ISSUE TITLE
Specify cursor selection/highlight colour

### ISSUE THREAD

**Issue by cooperaj** [zeit/hyper#2582]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS High Sierra
- **Hyper.app version**: 2.0.0-canary.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/cooperaj/0b7810f87b9fa969921ea36ce82d45ad)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: None
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I'm unable to figure out what the correct incarnation to specify the selection colour. Cursor colour I can manage but the selection colour remains a resolute light purple colour.

![screenshot 2018-01-10 11 25 51](https://user-images.githubusercontent.com/400210/34770637-8791c46c-f5f9-11e7-97a4-0280331bb44c.png)

I've searched around on the xterm.js project too but can't find anything there either. This *must* be something thats been solved.

**Comment by chabou** [comment]
Add a `selectionColor: <color>` in your config :)

There is no documentation yet. 😞 

I encourage you to backup your config file, remove it and launch Hyper. A new default config file will be created with all new settings.

**Comment by cooperaj** [comment]
Thats the one :)

Something I'm confused about is the versioning of Hyper. Around the web I see versions referred to as 2.1 and 2.0.4 but on the project there is just the 2.0.0-canary versions.

Thanks for the help.

**Comment by chabou** [comment]
We have changed our versionning and introduced `-canary` suffix.
All `2.0.0-canary.X` are newer than `2.0.X` and `2.X.X` previously distributed on canary channel.

Sorry for this confusion

**Comment by antoineneidecker** [comment]
As @chabou mentioned, the solution is to add `selectionColor: 'rgba(R_Intensity, G_Intensity, B_Intensity, Opacity)'` to the config section in your hyper.js file (often found at ~/.hyper.js)
