### ISSUE TITLE
Custom Bell on Windows Powershell not working

### ISSUE THREAD

**Issue by MichelYpma** [zeit/hyper#2585]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 64bit
- **Hyper.app version**: 1.8.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When i add a bellSoundURL to my .hyper.js and restart Hyper i still keep hearing the default hterm/audio/bell instead of any custom publicly hosted mp3 file. At least on Windows when using PowerShell as the shell. I've tried several files, different locations to host it, and even a local filesystem path. Should it be working on Windows or is that only working on unix systems?

**Comment by ShaggyDev** [comment]
#2938 currently in progress that should solve this issue. Stay tuned ;D
