### ISSUE TITLE
High Memory Usage

### ISSUE THREAD

**Issue by noclip32** [zeit/hyper#2586]
- Hyper uses ~90MB of memory which is unusually high.
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by chabou** [comment]
What is your config file?
Please try without any plugin.

BTW 90MB of memory usage is not so high imo.

**Comment by noclip32** [comment]
I don't have any plugins running

**Comment by CodeTheory** [comment]
Hi, thanks for the issue. 90MB is normal so I'm going to close this issue. 
Let us know if you have any other problems.

**Comment by leo** [comment]
Don't quote me on this, but aren't apps using as much memory as they get allocated by the OS?

Like, if you have 32GB RAM Hyper might even be using multiple GB. 🤷‍♂️
