### ISSUE TITLE
Pasted text has background making text illegible.

### ISSUE THREAD

**Issue by cooperaj** [zeit/hyper#2588]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS High Sierra
- **Hyper.app version**: 2.0.0-canary.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/cooperaj/04a74c985bae1f890212dad31a153baa)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: None
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
When pasting in text to the terminal a white background is set that makes the pasted content illegible.

![screenshot 2018-01-11 10 42 08](https://user-images.githubusercontent.com/400210/34821560-17650096-f6bc-11e7-9b8d-36adf33ee91c.png)

However, if more characters are entered after the pasted content the white background disappears

![screenshot 2018-01-11 10 43 08](https://user-images.githubusercontent.com/400210/34821604-3a6e8166-f6bc-11e7-8e44-09ce635d7255.png)

On a vanilla install this doesn't happen because the text inverts

![screenshot 2018-01-11 10 45 41](https://user-images.githubusercontent.com/400210/34821769-ab823528-f6bc-11e7-9e98-563731fa6d1d.png)

**Comment by cooperaj** [comment]
I guess this could be the theme stopping the inversion from happening but I don't know how it would do that. 

Text in a ncurses UI selection box also suffered a similar issue.

**Comment by JesseLeite** [comment]
I've been getting this for a while too.  Doesn't seem to happen in bash, but does with zsh + oh-my-zsh.

![2018-02-22 10 55 13](https://user-images.githubusercontent.com/5187394/36548706-fc3f6314-17be-11e8-8d3f-9e73655969fd.gif)

It seems both the text and background color of pasted text uses `foregroundColor` in my hyper config.

**Comment by Stanzilla** [comment]
Please open an issue with the theme you are using.

**Comment by ikopyl** [comment]
#hotpotato
