### ISSUE TITLE
The content area of the terminal does not stretch to the edge of the window (minus padding)

### ISSUE THREAD

**Issue by cooperaj** [zeit/hyper#2589]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS High Sierra
- **Hyper.app version**: 2.0.0-canary.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/cooperaj/04a74c985bae1f890212dad31a153baa)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: None
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

![screenshot 2018-01-11 10 54 19](https://user-images.githubusercontent.com/400210/34822136-c9bfdae4-f6bd-11e7-9dfc-7a7969f03f57.png)

As you can see in the above window the content area of the terminal seems smaller than the bounds of the window - padding. The selection area shows the extent of the content area but you can also see the folder 'private' is truncated to 'privat'

This seems theme unreleated

![screenshot 2018-01-11 10 57 43](https://user-images.githubusercontent.com/400210/34822281-4a249738-f6be-11e7-93c4-7bb6d1c04fe5.png)

**Comment by MindTooth** [comment]
I have the same issue with canary.9.  It don't stretch all the way to the right.
<img width="1920" alt="screen shot 2018-01-11 at 13 39 03" src="https://user-images.githubusercontent.com/33870508/34825933-d301e680-f6d4-11e7-8403-cec3e174b4b1.png">

**Comment by bgw** [comment]
The issue is that hyper and xterm.js deal with character widths slightly differently.

Possible fix: #2594

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
