### ISSUE TITLE
How can I downgrade and prevent automatic hyper updates?

### ISSUE THREAD

**Issue by rickarubio** [zeit/hyper#2591]
Hi,

I've run into an issue where hyper auto-upgraded itself and now I am facing compatability issues when clicking/scrolling inside of hyper and neovim.

What is the best way to lock hyper down to a specific version and prevent automatic updates?

I'm currently looking into editing a cask file and trying to re-install to a lower version -- is there a better way?

**Comment by rickarubio** [comment]
If there is currently no way of setting this, is this something other people may find useful? I was poking around in the code and perhaps we could have an option in in the hyper configuration file to enable/disable automatic updates. Thoughts? Yes/No ?

**Comment by chabou** [comment]
It is not a healthy thing to permit disabling automatic updates.

The best solution is to fix this regression.
Can you open an issue with all informations needed to reproduce? (Which versions are concerned etc..)

Thank you
