### ISSUE TITLE
cursorBlink don't work on canary 9

### ISSUE THREAD

**Issue by dougmaitelli** [zeit/hyper#2596]
- **OS version and name**: Windows 10
- **Hyper.app version**: Canary 9

## Issue
On the new canary 9 update the parameter cursorBlink does not work anymore. Even when true the cursor is static.

**Comment by chabou** [comment]
My fork is up-to-date with xterm v3.
What let you think that my fork hasn't the cursorBlink feature?

**Comment by dougmaitelli** [comment]
Hi @chabou, sorry, maybe it was my mistake since I did just a short look on it, but using the github search it showed no results in your repo for "cursorBlink" but it did return results in xterm repo.

**Comment by dougmaitelli** [comment]
Actually, I did run the search again, and the problem is actually that I can't run a search on your fork. Sorry for my mistake, as I said, just did a short look before and misunderstood the page. Anyway, the issue still exists, and the source seems to be from this xterm upgrade from 2.9 to 3.

**Comment by chabou** [comment]
You're right. I don't know why my fork is not indexed yet 🤔 

I just found a way to reproduce. 
Blinking will works in first pane if you create a second.

I'll try to fix it ASAP
