### ISSUE TITLE
Disable linux auto update notifications

### ISSUE THREAD

**Issue by passcod** [zeit/hyper#2599]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: ArchLinux
- **Hyper.app version**: 1.4.8 (and canary.8 too)

## Issue

It should be possible (with a config line) to disable the update notification.
Constantly having to close that notification is really annoying.

Perhaps like this:

```
    // choose either `'stable'` for receiving highly polished,
    // or `'canary'` for less polished but more frequent updates.
    // set to `false` to disable update notifications
    updateChannel: false,
```

**Comment by MAPESO** [comment]
@passcod  Hi, It is not a good idea to turn off automatic updates. The best solution is to fix this regression 😸

**Comment by passcod** [comment]
Um, automatics updates do not work on Linux and I do not expect them to work. I expect to update Hyper like any other linux package, the normal way. I would like to tell Hyper to kindly stop telling me about updates.

**Comment by MAPESO** [comment]
@passcod Ok, I will talk with the team about the problem :)

**Comment by MegaGM** [comment]
Any news? :3

**Comment by mchipp** [comment]
Agreed. I came here looking for a solution to exactly this. I'm running stable but I'm annoyed by having to close the alert about the latest Canary build every single time I launch Hyper.

**Comment by therealmarkchipp** [comment]
Agreed. I came here looking for a solution to exactly this. I'm running stable but I'm annoyed by having to close the alert about the latest Canary build every single time I launch Hyper.

**Comment by passcod** [comment]
@therealmarkchipp that's a related issue but not the same: I believe there's an bug/regression currently where canary builds are advertised to stable users.

**Comment by therealmarkchipp** [comment]
True enough. But I still +1 your initial request to hide the alerts.

**Comment by Kaeltis** [comment]
Agreeing on this, when installing Hyper via a package repository (for example AUR) the constant update notifications are pretty annoying.

**Comment by AndrewNoskov** [comment]
Yay, guys! Easy hack:
`css: `
  .notifications_view {
    display: none;
  }
``.
Add this to 

> .hyper.js

**Comment by olsonpm** [comment]
I just created a very simple plugin [hyper-disable-new-version-notification](https://www.npmjs.com/package/hyper-disable-new-version-notification).  It just always negates the redux state which triggers the new version notification.  This way you don't have to use css to disable *all* notifications ;)

**Comment by passcod** [comment]
Also, because I've always wondered but too polite/uncertain to ask: @MAPESO who _are_ you?

You spoke as if you had a position of sorts among Hyper devs, but you have no badge so it's hard to tell. I couldn't really see many contributions. You have commented on a handful of issues, though, so... maybe? But it's _super unclear_. You're not on ZeitHQ's About page. Your github makes no mention of belonging to the Zeit org, or anything.

All I know is: you said you'd "speak to the team", and then nothing happened, _and then nothing happened_, **and then nothing happened**.

Zeit/Hyper team, if you see this, maybe clarify?

👋

**Comment by olsonpm** [comment]
@passcod - chill man.  This software is free, nobody's obligated to follow up on anything.  Sometimes people forget, sometimes they get busy, or even stop caring, it just doesn't matter.  If you want a follow up to something then ask politely.

**Comment by passcod** [comment]
@olsonpm sure, ok

**Comment by Stanzilla** [comment]
https://github.com/zeit/hyper/issues/2431
