### ISSUE TITLE
Configuring Window Drop-shadow

### ISSUE THREAD

**Issue by tjfwalker** [zeit/hyper#260]
I'm fond of the [the Numi calculator app](https://numi.io/) aesthetic and want to see if HyperTerm could be made to look similar. I noticed that HyperTerm windows feature a more prominent box-shadow and I was unable to determine how to adjust the property. How is this done?

<img width="652" alt="san_shadow-numi" src="https://cloud.githubusercontent.com/assets/2547625/16930249/2aa1f5a0-4cf0-11e6-8ff5-76e930cbf8c2.png">
<img width="572" alt="shadow-hyperterm" src="https://cloud.githubusercontent.com/assets/2547625/16930248/2a9e0d14-4cf0-11e6-8280-b802f956a1a8.png">

**Comment by tjfwalker** [comment]
Additionally, I've noticed that the HyperTerm windows' drop-shadows change depending on wether or not the window is focused. How is this behavior adjusted?

**Comment by tjfwalker** [comment]
@CodeTheory any word on this?

**Comment by chabou** [comment]
This shadow (on Mac only) is driven by `hasShadow` property of [Electron BrowserWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md)
Make a plugin to disable this should be quite simple

**Comment by romainwn** [comment]
I made a plugin for it [hyper-drop-shadow](https://github.com/romainwn/hyper-drop-shadow) 🎉

**Comment by chabou** [comment]
Awesome!
@romainw Great work!

**Comment by gusbemacbe** [comment]
@chabou 

On LInux, there is no drop shadow and I want to enable it. I did a lot of search and did not find the solution.
