### ISSUE TITLE
Hyper crashing on win

### ISSUE THREAD

**Issue by kasper3** [zeit/hyper#2604]
Using https://github.com/lhmouse/nano-win (downloaded from https://files.lhmouse.com/nano-win/), it works on cmd/powershell. But when i use Hyper and just run `nano`, it crashes hyper.

**Comment by albinekb** [comment]
Hello, please fill in the  https://raw.githubusercontent.com/zeit/hyper/canary/.github/issue_template.md issue template so we have all information to reproduce.
