### ISSUE TITLE
how to stop hyper update notifications?

### ISSUE THREAD

**Issue by arshdkhn1** [zeit/hyper#2605]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Lubuntu 17.10
- **Hyper.app version**: Hyper version 1.4.8
## Issue
I always get this update notification at the bottom when I open hyper.
![screenshot 2018-01-13 21 32 20](https://user-images.githubusercontent.com/16819670/34907864-691ab2fa-f8ab-11e7-919f-d905e4212e00.png)

I clicked on this notification and downloaded the canary version but when I opened canary version I got a same notification for the version(1.4.8) on which I was already at before updating to canary.

How do i stop these update notifications and why is this recursive update thing going on?

**Comment by chabou** [comment]
Argh. Sorry for that.
Please set `updateChannel: 'canary'` in your config file. It will stop to announce you 1.4.8 when 2.0.0-canary.X will be installed.

**Comment by arshdkhn1** [comment]
Thanks, I wonder why I got update notification for `canary release` when updateChannel was stable.

**Comment by Arttse** [comment]
How to stop showing annoying canary update notifications in `1.4.8` version?
Option `updateChannel: "stable"` doesn't work.

**Comment by jaller94** [comment]
* OS version and name: MacOS 10.13
* Hyper.app version: Hyper version 2.0.0-cannery.11
* Update channel: `'canary'`

I am getting the 1.4.8 (stable) update notification.

**Comment by Valkhir** [comment]
I'm getting update notifications for new canary version even though I am on stable channel. Very annoying - I'd rather not have an update notification than seeing an incorrect one every time I start the program., especially since  it appears the only way to close the notification is to use the mouse.

**Comment by albinekb** [comment]
@Valkhir Can you double check your `updateChannel` in your `~/.hyper.js` ? That should not happen. Please open another issue if you have `stable` and still are getting canary notifications. Thanks

**Comment by arshdkhn1** [comment]
@albinekb 
![image](https://user-images.githubusercontent.com/16819670/36323384-c70f284c-1376-11e8-8457-3ceffcc18596.png)

**Comment by justUmen** [comment]
This is not a solution but you can just hide them in the configuration, it's what I did :
`css: '.notification_indicator{display:none;}',`

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

Also: https://github.com/zeit/hyper/issues/2431

**Comment by Boycce** [comment]
@justUmen Thanks works great! Although i do think there should be a setting for this.
