### ISSUE TITLE
Default --supports-dual-gpus=true (Hyper disabling iGPU (OSX))

### ISSUE THREAD

**Issue by ethanx94** [zeit/hyper#2607]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OSX 10.13.2**: 
- **Hyper.app version 1.10.16**: 
- **.hyper.js (default config)**: 
- **Relevant information from devtools: N/A** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **Is Vanilla**: 

## Issue
I noticed that Hyper, as well as many other Chrome/Electron based apps, were actively disabling the iGPU in my MacBook. I am running an eGPU which would normally not be an issue but the entire laptop display goes black and on the external display performance is brought to a crawl. Therefore I'm proposing a supports-dual-gpu switch to be added to the main index.js that seems to remedy this problem.
This may also alleviate another issue with artifacting on a vanilla MacBook Pro that has discrete graphics without a performance hit. (Although I have not been able to reproduce that issue to test this theory)
See this potentially related issue here: #747

Let me know your thoughts, if adding a switch into the main app/index.js is an issue maybe we can support adding a .hyper.js configuration variable to append commandLine switches instead.

**Comment by Greenek** [comment]
This is already fixed in v2.0.0-canary and I believe old versions won't be supported anymore.

**Comment by ethanx94** [comment]
My mistake, I listed 1.10.16 but I actually cloned down the latest canary branch to make these modifications. Without that flag the app is completely unusable in an eGPU setup (A setup which will become more common soon as Apple has officially released a developer eGPU kit). If the change is too invasive or if it seems like it may cause unintended side effects maybe we could go with the second option of a config variable.

**Comment by ethanx94** [comment]
....On further inspection, although I feel like this is a Chrome issue. I was able to remedy the problem by changing the order of my dGPU/eGPU set up. This fixed graphics switching as it now falls back to the factory AMD card. That being said others with MacBooks which lack a dGPU may still be affected by this.
If you know that Google has removed the --supports-dual-gpus flag from more recent versions of Chromium/Chrome feel free to disregard this pull. Although if I have time I might write up something to read in a config variable for appendSwitch arguments to be passed in to meet this edge case if that is something that might benefit the project.

**Comment by mckernanin** [comment]
Still an issue on latest version

**Comment by mckernanin** [comment]
@Stanzilla has this been resolved?

**Comment by Stanzilla** [comment]
In theory yes, which version are you seeing this issue on? Also probably fixed with the Electron 6 update.

**Comment by mckernanin** [comment]
<img width="866" alt="Screenshot 2019-09-30 15 46 39" src="https://user-images.githubusercontent.com/6300047/65919442-860cd480-e399-11e9-9741-0b17cbd7a867.png">

**Comment by Stanzilla** [comment]
Can you try with a build from this PR? https://github.com/zeit/hyper/pull/3785
