### ISSUE TITLE
Cursor would not move when long press on 'j' or 'k' for VIM.

### ISSUE THREAD

**Issue by CrisLi** [zeit/hyper#2610]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.13.2
- **Hyper.app version**: Hyper 2.0.0-canary.9 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

When I use vi or vim in the Hyper, the cursor would not move when long press on 'j' or 'k'. I have to hit 'j' one-time after one-time. When I use iTerm, there is no problem.

**Comment by davemkirk** [comment]
I think this is related to this upstream issue (https://github.com/zeit/hyper/issues/2297).

**Comment by chabou** [comment]
Thanks for the report 🙏 . 
We're tracking this work over here: #2297
