### ISSUE TITLE
Raw URIs opens the website inside a hyper window.

### ISSUE THREAD

**Issue by noudadrichem** [zeit/hyper#2611]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.13.2 (High Sierra)
- **Hyper.app version**: 1.4.8 (stable) — Plugins: none

## Issue

When I type/paste a raw URI inside my PS1 line and press enter, it opens that URI. See: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16288476/34949387-41426bea-fa10-11e7-806e-7c4fae993656.gif)

This happened to me when I copied a pull request link given by a push to bitbucket. 
I was to fast and accidentally pasted it inside Hyper and pressed Enter.

**Comment by CodeTheory** [comment]
Hi! Thanks for the issue. This is the intended behaviour 😄

**Comment by noudadrichem** [comment]
Wiew, oke!  Quick response! +1 for that.

How do I get back to my previous terminal view?
If this is non existent. See this as a feature request. 😊

**Comment by noudadrichem** [comment]
Got an answer on Twitter.

Ctrl-C it is. Awesome!
