### ISSUE TITLE
Terminal height not right, line offscreen

### ISSUE THREAD

**Issue by WeslleyNasRocha** [zeit/hyper#2615]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version (*canary*)
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: DeepinManjaro 17.1.1
- **Hyper.app version**:  2.0.0-canary.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/WeslleyNasRocha/eaaa52c58e2907b80d749c6f3fdb254f)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

When the scroll bar appear, the last line stays off screen, and i cant see anything
![image](https://user-images.githubusercontent.com/19312651/35031587-b6c7add6-fb4a-11e7-9ac8-97f934d0722e.png)

**Comment by dliuzzi** [comment]
I'm on the latest canary (2.0.0-canary.10) and I see this as well:

![hyper](https://user-images.githubusercontent.com/143884/35125326-8550df2e-fca9-11e7-8695-06056b682183.png)

When ithappens I fix it by pressing F11 twice (going into fullscreen mode and out again.)

**Comment by WeslleyNasRocha** [comment]
in the latest canary, at least in Manjaro, it got fixed

**Comment by dliuzzi** [comment]
I can confirm that at least on Windows this is not fixed, even in the latest canary.

This issue is a duplicate of #2468 anyways, so I'll follow up there.
