### ISSUE TITLE
Scroll in splited windows does not work

### ISSUE THREAD

**Issue by VladimirHumeniuk** [zeit/hyper#2616]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint
- **Hyper.app version**: 2.1.1

## Issue

Scroll in splited windows does not work sometimes:
![](https://w3tls.net/4l4TL2f1d04a1dfe724a7f71678657090c6caa.png)

**Comment by chabou** [comment]
Please install last canary: https://github.com/zeit/hyper/releases/tag/2.0.0-canary.9
(We have changed our versioning 2.0.0-canary.9 is newer thant 2.1.1)

**Comment by VladimirHumeniuk** [comment]
@chabou 
![](https://w3tls.net/4l4TL2235a13047b1ac67d9f437e19a8adcfc6.png)

**Comment by VladimirHumeniuk** [comment]
@chabou  Yepp, everything is fine in canary. Thanks.
