### ISSUE TITLE
Square blocks

### ISSUE THREAD

**Issue by drinkingChai** [zeit/hyper#2620]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS High Sierra 10.13.2
- **Hyper.app version**: 1.4.8
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
I'm having this square block show up on hyper next to ~
And the ~ is also in a blue block

<img width="337" alt="screen shot 2018-01-18 at 10 41 57 am" src="https://user-images.githubusercontent.com/15708080/35106503-5e827532-fc3c-11e7-9f48-61043bcd445e.png">

I have Oh My Zsh installed and my iTerm looks like this

<img width="346" alt="screen shot 2018-01-18 at 10 42 26 am" src="https://user-images.githubusercontent.com/15708080/35106538-7b77c700-fc3c-11e7-99fe-7ba685a9fd3d.png">

I found this issue on inspecting it. There's an `Unknown OSC code: "1"` on both the ~ and the block. But I'm not sure what to do with it.

<img width="776" alt="screen shot 2018-01-18 at 10 46 30 am" src="https://user-images.githubusercontent.com/15708080/35106720-f7f69932-fc3c-11e7-91b8-ba7a5c3ef52c.png">

I'm not sure if I'm missing a font. Thank you!

**Comment by tiferrei** [comment]
Hey, you need to make sure you're using a font that includes the glyphs you want to use. You can either change the font to one that works, or add the glyphs to a normal font using tools like [nerd-fonts](https://github.com/ryanoasis/nerd-fonts).

**Comment by drinkingChai** [comment]
Hey @tiferrei thanks for the reply.

I may have missed something but I installed nerd-fonts with brew. Then I went to iTerm to see which font it's running: Meslo LG M DZ Regular for Powerline. I added that as the first item with double quotes on fontFamily settings.

But no joy :( Also tried just Meslo.

**Comment by drinkingChai** [comment]
Marking as resolved after installing Menlo for Powerline, and adding that as the first option for fontFamily. Thanks!
