### ISSUE TITLE
Unable to run youtube-dl.exe in Hyper, works fine in other terminals

### ISSUE THREAD

**Issue by nerdinja** [zeit/hyper#2622]
- [x] I am on the [latest] Hyper.app version
- [x] I have searched the [issues] of this repo and believe that this is not a duplicate

- **OS version and name**: 

- **Hyper.app version**: 

- **Link of a [Gist] with the contents of your .hyper.js**:

- **Relevant information from devtools**: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by nerdinja** [comment]
Somebody on irc just told me to give it a shot using "./youtube-dl.exe <url>" instead of "youtube-dl.exe <url>" and that worked like a charm, so this is no longer an issue. Thanks, though!

**Comment by albinekb** [comment]
Glad you got it working and thanks for updating us 🙂 Have a great day @nerdinja 👋
