### ISSUE TITLE
"X update is available" popup is horrifically annoying

### ISSUE THREAD

**Issue by novafacing** [zeit/hyper#2624]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I'm on Ubuntu 16.04, KDE. I have canary 2.0 and 1.4.8 but every time I'm on 1.4.8 it tells me I can get canary 2.0, and every time I'm on 1.4.8 it tells me I need 1.4.8 because of some chromium vulnerability! I respect wanting to provide updates but the notification is beyond obnoxious.

**Comment by chabou** [comment]
Thanks for the report 🙏 . 
We're tracking this work over here: #2476
