### ISSUE TITLE
Emojis using zero-width joiners shown as multiple emojis

### ISSUE THREAD

**Issue by 16patsle** [zeit/hyper#2625]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.2
- **Hyper.app version**: 1.4.8 and 2.0.0-canary.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/16patsle/91998bf232afdc19b491be6dd07e1c6d
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes, both stable and canary

## Issue
Using emoji characters that consist of several characters combined with zero-width joiners does not work. The emoji it consists of is shown instead.

I'm using emojis in my bash prompt, and this was how I discovered the issue.
In the image below: how this should look (at the top, in iTerm) versus how it looks in Hyper (bottom)
<img width="169" alt="hyper-emoji" src="https://user-images.githubusercontent.com/7686840/35195139-2e82ab6a-febf-11e7-95d4-605c03340030.png">

This screenshot is using canary (2.0.0-canary.10). When using stable (1.4.8), only the first of the three show up.

**Comment by Stanzilla** [comment]
Hey @16patsle could you do us a favor and test that in another terminal that uses xterm.js? The Visual Studio Code terminal is one of those. If you find that the issue exists there as well, please open an issue at https://github.com/xtermjs/xterm.js/ and/or take a look if https://github.com/xtermjs/xterm.js/issues/1059 already is what you are seeing.

**Comment by 16patsle** [comment]
Problem exists in the integrated terminal in VS Code too. After searching a bit, I found that this issue seems to be for the same problem.
https://github.com/xtermjs/xterm.js/issues/942

Doesn't seem like it's solved yet, in the mean time, I'm going back to a more boring bash prompt.

**Comment by decembre** [comment]
On firefoxv56.2.13 / Win 10.
from:
[](https://emojipedia.org/emoji-zwj-sequences/)
Work:
🏳️‍🌈 Rainbow Flagdon't work:
🏴‍☠️ Pirate Flag 
◯‍◯‍◯‍◯‍◯ Olympic Rings
🤼🏿‍♀️ Women Wrestling, Type-6
👯🏻‍♀️ Women With Bunny Ears Partying, Type-1-2

**Comment by Stanzilla** [comment]
Can you try with a CI build of current canary or maybe compile one yourself?

**Comment by 16patsle** [comment]
@Stanzilla Tried with canary build 2472 from CircleCI, and it still shows as multiple emojis
<img width="105" alt="Skjermbilde 2019-10-13 kl  13 11 17" src="https://user-images.githubusercontent.com/7686840/66714748-147e4e80-edbb-11e9-8dfa-a2355e6bc8dd.png">

**Comment by Stanzilla** [comment]
@Tyriar should this work with xterm 4.1 in the canvas renderer?

**Comment by Tyriar** [comment]
I think this is https://github.com/xtermjs/xterm.js/issues/942

**Comment by ortonomy** [comment]
! why was this closed.. still a problem today.

iTerm: 
<img width="48" alt="image" src="https://user-images.githubusercontent.com/6688676/180604413-947b110c-73d4-4cb9-a6a1-bd05c535a2a3.png">

hyper:
<img width="49" alt="image" src="https://user-images.githubusercontent.com/6688676/180604417-7e9bdc1d-51ab-45da-8145-5b8a514f8e0e.png">
