### ISSUE TITLE
Update prompt for version 2.1.1 to 1.4.8

### ISSUE THREAD

**Issue by irzan2010** [zeit/hyper#2626]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/irzan2010/9e5258c0857f8d4304c43957fcae201a
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

My Hyper keep show update to version 1.4.8, meanwhile my Hyper version is 2.1.1 (which I believe the latest version of Hyper).
This is really weird because when I check latest version on GitHub release, there are no version 2.1.1. The latest stable version is 1.4.8 and canary version is 2.0.0.
Here is my screenshot : http://prntscr.com/i3pxqz
Beside that, when I click Restart on update notification, it will restart Hyper but not updating to 1.4.8, it still remain on version 2.1.1.

Is this a bug? Or should I uninstall my Hyper and re-download version 1.4.8 ?

**Comment by chabou** [comment]
We have changed our versionning. Canary are now: `2.0.0-canary.X`

If you want to remain on 1.4.8, set `updateChannel: 'stable'` (or remove it) and reinstall stable version (no need to uninstall before imo).

But I really encourage you to test our last canary (2.0.0-canary.10) and open issue if some issues lead you to rollback to stable.

**Comment by irzan2010** [comment]
Thanks for the quick response.
I just uninstall my 2.1.1 and install 2.0.0-canary.10. So far there is no problem. The only little problem is with my Avast Free AV, which is scan every new software installed on my computer and caused some failure installation when I abort the scan process. I recommended to disable temporarily if you have Avast Free like me.
