### ISSUE TITLE
Error on split from SSH tab

### ISSUE THREAD

**Issue by aaronr0207** [zeit/hyper#2627]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home x64
- **Hyper.app version**: 2.0.0 Canary 10 (I had tested stable version too)
- **Link of a [Gist] ** (https://gist.github.com/) https://gist.github.com/aaronr0207/bce1edefc196361853f72c7a5b693a51
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**:  I think no because I am using Git Bash shell
## Issue
When I'm running a ssh session to my Homestead VirtualBox (using Git bash shell) and I try to split the cli into multiple tabs it displays following error (just when the target tab is running ssh, working as expected on the other created tabs)

I have tried to disable "related" plugins.

![image](https://user-images.githubusercontent.com/7554753/35211858-70f1a994-ff58-11e7-9a95-d7a4f2ed5acf.png)

**Comment by chabou** [comment]
I'm using gitbash on windows too and I can't reproduce :(

**Comment by aaronr0207** [comment]
Maybe related to homestead? Is there something that I can attatch here to add some clarify?

**Comment by chabou** [comment]
I'll try to reproduce with a Vagrant, but I don't think it could be related... We'll see

**Comment by aaronr0207** [comment]
I just notice that maybe I made a typo what I am trying to do is **ctrl+ D** 
What I am doing is: 
-start Hyper.exe
-type: homestead ssh 
-press enter
-press ctrl+D
