### ISSUE TITLE
Support the Windows 10 resize edges and corner grabbing

### ISSUE THREAD

**Issue by guiscaranse** [zeit/hyper#2630]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro
- **Hyper.app version**: 1.4.8
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`. 
## Issue

A normal window behaviour would been touching the screen corners with the form and it resizing to a pre-defined space. You can test it as using any native Windows program by touching the upper edge and the right/left ones. But with Hyper, it just doesn't do anything. Also, pressing `Super Key + directional keys` doesn't reproduce any expected behavior (resizing).

**Comment by chabou** [comment]
It works for me on canary.

Add: `updateChannel: 'canary'` to your hyper config to install it.

**Comment by guiscaranse** [comment]
Tested on canary, the corner grab seens working fine but not the resize edges when touching the screen corners.
