### ISSUE TITLE
HyperJS 2.0.0 shows default electron icon

### ISSUE THREAD

**Issue by joedborg** [zeit/hyper#2634]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Ubuntu 18.04
- 2.0.0-canary.11

## Issue
Just updated from 1.4.8 to 2.0.0-canary.11 using the Linux debian release.  Once updated, the logo changed from the hyperJS logo to the default electron one.

**Comment by teonik** [comment]
Confirmed on 
- Debian 9 (Stretch)
- Gnome 3.22.2
- Hyper 2.0.0-canary.11

**Comment by VladimirHumeniuk** [comment]
Same here (Linux Mint)
