### ISSUE TITLE
hyper preference edit

### ISSUE THREAD

**Issue by alaminmishu** [zeit/hyper#2635]
-
        Hyper 2.0.4
        Electron 1.7.8
        win32 x64 6.1.7601

this file does not have a program associated with it hyper terminal font option can't change

**Comment by albinekb** [comment]
Hello! Thanks for the report. This should be fixed in the latest canary release: https://github.com/zeit/hyper/releases/tag/2.0.0-canary.11 can you try that and see if it works? Thanks
