### ISSUE TITLE
Pasting + Enter race condition

### ISSUE THREAD

**Issue by kentor** [zeit/hyper#264]
When I paste and press enter in succession really fast, the command executed is the one as if I haven't pasted.

For example if I have typed this in my shell

```
$ git show 
```

then i paste a sha (say `398c4ca`) with cmd+v and press enter really quicky, the command that actually gets ran is just `git show` and not `git show 398c4ca`.

This does not happen on iTerm2.

**Comment by aleclarson** [comment]
I'm also experiencing this. Is there an easy way to ensure a paste is completed before the return keypress is handled?

**Comment by matheuss** [comment]
I'm also experiencing it 😕

**Comment by chabou** [comment]
Can't reproduce.
If I press enter really quickly after a paste, it is discarded.

Feel free to reopen

**Comment by kentor** [comment]
discarded?

anyway just tested and this seems to have been fixed

**Comment by chabou** [comment]
Yes: I tried and Enter key is ignored if it is pressed to quickly after a paste.
