### ISSUE TITLE
Two icons in taskbar (windows 10)

### ISSUE THREAD

**Issue by mittalyashu** [zeit/hyper#2643]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 1
- **Hyper.app version**: 1.4.8 (Stable)

Getting two icons on the taskbar

![image](https://user-images.githubusercontent.com/29014463/35482573-7794bbb0-045d-11e8-81e6-b18a417ba5ee.png)

**Comment by ppot** [comment]
Is it the same instance or different version of Hyper?

**Comment by albinekb** [comment]
This happens to VS Code too on my windows machine, seems to be something with updates and how the pinning system works in windows.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
