### ISSUE TITLE
dircolors are different when inside tmux

### ISSUE THREAD

**Issue by oquirozm** [zeit/hyper#2644]
- **OS version and name**: MacOS High Sierra 10.13.2
- **Hyper.app version**: 1.4.8
- **My .hyper.js**: https://gist.github.com/oquirozm/5b4b4b1a53522781b32369553be06d4a

## Issue
dircolors differs when used in and out of tmux. Here are two screenshots:

**[Inside tmux](https://image.ibb.co/n9m3Dm/Screen_Shot_2018_01_28_at_3_02_21_PM.png)**

**[outside tmux](https://image.ibb.co/eN1QR6/Screen_Shot_2018_01_28_at_3_02_53_PM.png)**

**Comment by ppot** [comment]
Please update image link. They are not working.

**Comment by oquirozm** [comment]
@ppot updated

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
