### ISSUE TITLE
Canary version not opening on macOS

### ISSUE THREAD

**Issue by fabiospampinato** [zeit/hyper#2646]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 10.13.3 macOS
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
``` javascript
module.exports = {
  config: {
    updateChannel: 'canary'
  }
};
```
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I just can't run Hyper canary. I wanted to try it out because of the xterm integration, so I put `    updateChannel: 'canary'` in my config, a message told me to restart in order to get the new version and after that Hyper just won't open. I only get `Hyper` written in the menubar with the only option being `Quit`.

I've tried manually downloading other canary version and I always get the same effect.

Downgrading to v1.4.8 worked.

**Comment by DesWurstes** [comment]
I have the same problem too. It opens, after a few seconds it says "Version 1.4.8 has been downloaded. Click this to install.", then it reverts back to 1.4.8.

**Comment by Dog** [comment]
I haven't gone through your upgrade path, but I have gotten the canary build to work on Mac by following the directions for contributing in the README. If you want to go ahead and play with it, perhaps that route will work for you.

**Comment by chabou** [comment]
@DesWurstes Your problem is not exactly the same. I suspect that you haven't change/add your config setting `updateChannel` to canary.

@fabiospampinato Can you try to retry with our last canary? I can't reproduce your issue 😞

**Comment by fabiospampinato** [comment]
@chabou same problem.

**Comment by fabiospampinato** [comment]
Closing since v2.0.0 works.
