### ISSUE TITLE
How to open Hyper in the working directory

### ISSUE THREAD

**Issue by mittalyashu** [zeit/hyper#2649]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 1.4.8

## Issue
How to open hyper in the working directory?

![2018-01-30_21-21-15](https://user-images.githubusercontent.com/29014463/35575922-b4519ec2-0603-11e8-8477-a9da46a16972.gif)

**Comment by spences10** [comment]
There is a [plugin] for this but it has never worked for me 🙃 

Take a look at [awesome-hyper] there may have been something added since I last checked 👍 

[plugin]: https://www.npmjs.com/package/hypercwd
[awesome-hyper]: https://github.com/bnb/awesome-hyper#productivity

**Comment by Stanzilla** [comment]
https://github.com/hharnisc/hypercwd
