### ISSUE TITLE
Add context menu

### ISSUE THREAD

**Issue by akashnimare** [zeit/hyper#265]
Add menus like open new tab, copy, paste, close tab, open tab etc on right click in hyperterm.

**Comment by sindresorhus** [comment]
Check out [`electron-context-menu`](https://github.com/sindresorhus/electron-context-menu) if you want a good starting point. Easily extendable.

**Comment by akashnimare** [comment]
@sindresorhus @rauchg is it a good idea to make a plugin for this or it should be a default feature of hyperterm ?

**Comment by sindresorhus** [comment]
I think it should be default, so plugins can be able to modify it.

**Comment by akashnimare** [comment]
Sounds good.

**Comment by mnpenner** [comment]
In particular, I'd like to be able to right-click hyperlinks and then copy them.

**Comment by rickycodes** [comment]
Opened https://github.com/zeit/hyper/pull/2001
