### ISSUE TITLE
The app window appears for a second and get disappear.

### ISSUE THREAD

**Issue by suhaibaffan** [zeit/hyper#2651]
I am using MacBook Air, I am not able to use the app. The moment I open the window appears for a second and gets disappear.
        Hyper 1.4.8
        Electron 1.7.8
        darwin x64 17.3.0

**Comment by benjamindenboer** [comment]
I have this too, only when setting a custom shell path, though. When `shell` is left empty, it works for me.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
