### ISSUE TITLE
Emoji cannot be entered / pasted into hyper in Windows 10

### ISSUE THREAD

**Issue by nt3rp** [zeit/hyper#2653]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro (Version 1709, Build 16299.192)
- **Hyper.app version**: 1.4.8.
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/nt3rp/5c945addf2d4fcce3b9e2c4f53092dcd
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes, in the default shell and in the bash shell

## Issue

When attempting to enter an emoji character (e.g. 👍 ) into Hyper, it appears as question mark characters (e.g. ��). This happens whether copy-pasting emoji, or using the Windows 10 touch keyboard.

If the emoji is contained in a file, it will display properly.

**Comment by balcsida** [comment]
This is no longer occurs for me with the latest canary releases, 2.0.0-canary.16 and 2.0.0-canary.15:
![image](https://user-images.githubusercontent.com/1768446/38469443-1cd70442-3b55-11e8-8005-8eb190d34415.png)
I think when they switched using native font stack, it resolved this issue as well.

**Comment by albinekb** [comment]
We switched to xterm.js instead of outdated hterm, @balcsida Hyper 2.x renders on canvas more accurately now 👍

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
