### ISSUE TITLE
Console not scrolling down automatically when command executed

### ISSUE THREAD

**Issue by saravanaselvan** [zeit/hyper#2655]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 8.1 Pro
- **Hyper.app version**: 1.4.8
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
The console is not automatically scrolling down when a command is executed. For example: If I type git status it is not showing the result. Only if I manually scroll down or press 'Enter' multiple times it is displayed. Screenshot attached:

![image1](https://user-images.githubusercontent.com/2334555/35719507-bbb36a70-080f-11e8-8866-22649c70a825.png)

![image2](https://user-images.githubusercontent.com/2334555/35719510-c208a002-080f-11e8-9d9d-33504ce3a112.png)

**Comment by sarah-appsheet** [comment]
This started happening to me this month. Windows 10, Hyper 1.4.8, no plugins, no recent changes to preferences.

**Comment by 2Kayo** [comment]
This used to happen to me, but it seems to be fixed after I enabled "Override high DPI scaling behavior. Scaling performed by Application" in the Compatibility section of the .exe's properties.

**Comment by sarah-appsheet** [comment]
Hm. I enabled that setting, but I'm still seeing the issue.

**Comment by saravanaselvan** [comment]
@2Kayo Thanks very much. It seems to be working for me.

**Comment by aantron** [comment]
I likewise have this issue, and the compatibility setting did not fix it.

**Comment by milesjhl** [comment]
Update: the fix I posed earlier didn't actually fix the issue, but it did make it much less common for me. I still experience it when the console is printing a lot of output on its own, like when running a local server or something.

**Comment by aantron** [comment]
I can confirm this. It seemed to make it less common for me as well, but alone I wasn't sure if that was chance or some kind of bias on my part. It still breaks though, especially when scrolling `less` around (using the arrow keys).

**Comment by saravanaselvan** [comment]
Yes. For me too the same. Now it has got reduced. When it occurs, I had to close and re-open the app to fix it. 

On a different note. Has anyone faced this issue before - https://github.com/zeit/hyper/issues/2554

**Comment by chrisharrington** [comment]
I'm also having this problem.
