### ISSUE TITLE
Handling selection when editing file in Vim

### ISSUE THREAD

**Issue by kenorb** [zeit/hyper#2656]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.6 (Sierra)
- **Hyper.app version**: 1.4.8
- **Default configuration.
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes.

## Issue

I have a problem selecting the text and copy into clipboard. In different terminals, e.g. iTerm, selection while editing in Vim can be done by pressing Alt and clicking on the text. In Terminal, it's by pressing FN and clicking. This works in Vim as well.

In Hyper, I've tried the following steps:

1. Edit some long file in Vim, e.g.`vim /var/log/system.log`.
2. Now I want to select the text by double clicking and copying using CMD-C, below are my attempts.
3. Double click while pressing FN key, the text getting selected for short period, then disappears. Sometimes the screen flashes, and it tries to execute some Vim commands, resulting in errors like: E354: Invalid register name: '~@<fd>'.
4. Double click while pressing Shift, it result in not expected selection. So the method is to click once without pressing any key to set the starting point, then double clicking while pressing Shift. But the selection disappears while moving the mouse.
5. Double click while pressing Alt, it also results in execution of some random Vim commands.

In some other files with code, when clicking, the file get scrolled up (never down, whenever I click), so it's not possible to select anything. Same issue with scrolling when not pressing any key. I'm using VIM - Vi IMproved 8.0.

The issue is about how mouse interaction and ability to copy while editing the file in Vim within Hyper terminal.

**Comment by albinekb** [comment]
Can you try the canary release? It got tons of changes regarding the shortcuts and how the terminal I handled

**Comment by kenorb** [comment]
Related: #95

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
