### ISSUE TITLE
Plugins Install but do not activate

### ISSUE THREAD

**Issue by willricketts** [zeit/hyper#2657]
# Issue
Installing a plugin manually or with [hpm-cli](https://www.npmjs.com/package/hpm-cli) results in a successful package installation, but no package effects once it's install.ed

# Reproduction Steps
1. Install plugin
2. Notice it doesn't work 🤷‍♂️ 

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by MAPESO** [comment]
@willricketts Hi, hpm-cli is having some problems. In the version canary hyper that will soon be stable, we integrate a hyper-core cli that works much better. I invite you to try it 😸

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
