### ISSUE TITLE
Running $EDITOR fails when not a command

### ISSUE THREAD

**Issue by bevacqua** [zeit/hyper#266]
In `zsh` and others I could set `EDITOR=subl -w`. In HyperTerm I get:

![screen shot 2016-07-18 at 15 44 14](https://cloud.githubusercontent.com/assets/934293/16932896/7e7e03ae-4cfe-11e6-9a9c-886923b5a83d.png)

Ignore the ugly glyphs, setting up a new mac and battling with fonts 😅

**Comment by booc0mtaco** [comment]
Similar problems when using Fish shell
![screen shot 2016-07-18 at 16 49 15](https://cloud.githubusercontent.com/assets/3056447/16934051/b12dc59c-4d07-11e6-9faf-af8f84f3e11a.png)

Maybe this command should be invoked with a shell wrapper, to prevent any issues with custom configuration?

**Comment by squanto** [comment]
with `zsh`, I can set `EDITOR=subl` or `EDITOR='subl'` on hyperterm and iterm and have `$EDITOR ~/.hyperterm.js` work. `export EDITOR='subl -w'` fails with "`zsh: command not found: subl -w`" on both iterm and hyperterm, and sourcing `export EDITOR=subl -w` fails with `.zshrc:export:64: not valid in this context: -w` on both as well. I don't think it's a hyperterm specific issue.

I don't think it's a hyperterm-specific issue. Hope this helps.

**Comment by albinekb** [comment]
From fish:
```
➜  ~ $EDITOR ~/.hyperterm.js && exit
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
fish: $EDITOR ~/.hyperterm.js && exit
```

**Comment by ekmartin** [comment]
This has been fixed since this, as it now executes `bash -c 'exec env ${EDITOR:=nano} ~/.hyper.js'`.
