### ISSUE TITLE
[macOS] Auto update downgrades canary to stable version

### ISSUE THREAD

**Issue by UltCombo** [zeit/hyper#2660]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13.2
- **Hyper.app version**: 2.0.0-canary.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: (reproducible with default config)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: does not apply
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

I've downloaded and installed the canary release from https://github.com/zeit/hyper/releases. Soon after running it, an auto-update notification pops up displaying "a new version available" (1.4.8 stable). Restarted Hyper a couple times and my canary version was downgraded to the stable version.

**Comment by albinekb** [comment]
Hi! This is a known "bug", the problem is that your config still says `updateChannel: 'stable'` so hyper will try to get the latest stable. You need to open your `.hyper.js` and add `canary` to updateChannel. see https://zeit.co/blog/canary for more info on how to do that 👍

**Comment by UltCombo** [comment]
Indeed, my `.hyper.js` comes from a very old installation, it was missing the `updateChannel` key. Thanks @albinekb! 😄
