### ISSUE TITLE
Can't install RPM on Knoppix

### ISSUE THREAD

**Issue by kenorb** [zeit/hyper#2661]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Linux Knoppix v8.1
- **Hyper.app version**:  2.0.0
- Related: GH-799

## Issue

```
$ sudo rpm -i hyper-2.0.0-canary.11.x86_64.rpm 
rpm: RPM should not be used directly install RPM packages, use Alien instead!
rpm: However assuming you know what you are doing...
error: Failed dependencies:
	libnotify is needed by hyper-2.0.0_canary.11-2746.x86_64
	libappindicator is needed by hyper-2.0.0_canary.11-2746.x86_64
	libXScrnSaver is needed by hyper-2.0.0_canary.11-2746.x86_64
	/bin/sh is needed by hyper-2.0.0_canary.11-2746.x86_64
```

**Comment by albinekb** [comment]
Can you try to build from source? Instructions are here :) https://github.com/zeit/hyper#contribute

**Comment by chaseleinart** [comment]
@kenorb I'm on Ubuntu, not Knoppix, but did you try installing it with Alien, rather than rpm directly? I'm not familiar with RPM, so if that's not a preferred option, I'll try to reproduce on a Knoppix VM.

**Comment by kenorb** [comment]
Sorry, I won't be able to re-test on Knoppix, it was my temporary OS, now I'm back on macOS.

**Comment by albinekb** [comment]
Thanks 👍 Then I'm closing this off for now, if anyone in the future wants help getting it running on Knoppix, feel free to reopen 🙏
