### ISSUE TITLE
Windows 10 cannot access Preferences menu due to MS JScript error 

### ISSUE THREAD

**Issue by petercr** [zeit/hyper#2662]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
I just installed a fresh version of Hyper Terminal. And after opening the terminal which loads the default `cmd.exe` everythings seems to be working. But when I press `Ctrl + ,`  or go to the menu and click `Open Preferences` to open the settings menu I get Microsoft JScript runtime error. And so I am not able to edit any of the settings. 

#### I'm not sure if this is a Microsoft error or a Hyper error

Here is a picture of the error I am receiving. 
![ms jscript error](https://user-images.githubusercontent.com/26460352/35818635-98d35658-0a6e-11e8-9fb1-e1779af5c197.jpg)

**Comment by brandon93s** [comment]
A fix for this (#2631) has been merged into the canary branch, but is not in the latest release. To fix this for the release build, you can set a default program for "JavaScript" files in System Settings:

![image](https://user-images.githubusercontent.com/4730164/35819817-c96a1218-0a71-11e8-93c2-b0aeb0649a62.png)

Alternatively, you can manually open `C:\Users\{YOUR_USER}\.hyper.js` in your text editor to edit your preferences.

**Comment by petercr** [comment]
Great thanks for getting back to me so quickly. I did search through the issues to see if I could find the same one, but I wasn't looking in the canary branch just the main one. 
Thank you the issue has now been fixed, everything is working great 👍 👏

**Comment by albinekb** [comment]
Awesome 🙏
