### ISSUE TITLE
Hyper stuck at opening index.html

### ISSUE THREAD

**Issue by PleasedSkin** [zeit/hyper#2664]
I am on the latest Hyper version (1.4.8).

- OS version and name : Windows 10 64-bit (1709).
- Hyper version : 1.4.8

## Issue
Shows the following:

```
running in prod mode
electron will open file://C:\Users\myUserName\AppData\Local\hyper\app-1.4.8\resources\app.asar\index.html
```
and gets stuck there forever.

There is no error message but Hyper does not launch.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
