### ISSUE TITLE
Multiple error messages are displayed for same error, if multiple tabs & panel are open

### ISSUE THREAD

**Issue by livey0u** [zeit/hyper#2668]
- [ x] I am on the [2.0.0-canary.11](https://github.com/zeit/hyper/releases/tag/2.0.0-canary.11) Hyper.app 2.0.0-canary.11
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 2.0.0-canary.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/livey0u/88e670d9ad3734e6aa57825416179247
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: https://gist.github.com/livey0u/85e1c8bbfde32f54dc7f310727f7c08e
- **The issue is reproducible in vanilla Hyper.app**: Not sure

## Issue
There was some issue(see the 2nd gist file). Because of that, an error is displayed at the beginning(ie: when there is only one tab). After launching a few tabs & panels, if a plugin is installed or the configuration is reloaded, the same error is displayed number of tabs & panels times. I think, the same is true for notifications also.

**Comment by chabou** [comment]
Your issue is due to a bad plugin (ie. `hyper-autoprofile`), developped by a bad bad developper (ie. me) 😛.

Can you try to add a `autoProfile: {}` in your hyper config file?

Do you mind to open an issue in plugin repository: https://github.com/chabou/hyper-autoprofile

**Comment by chabou** [comment]
@livey0u: Fixed in `hyper-autoprofile` v1.0.1. 
Thank you for your feedback 🙏
