### ISSUE TITLE
Output incomplete or not correct

### ISSUE THREAD

**Issue by brucedjones** [zeit/hyper#2671]
- [x] I am on the canary11 Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Windows 10 
- Canary 11 
- default hyper.js
- N/A
- Is Vanilla

## Issue

I have noticed that when a program outputs at a high frequency the output is either incomplete or doesnt appear at all. The best example i can give for this is the following python script, this is handy because it actually gives an error.

Doing something similar with c++ just results in the output being suppressed at some point.

```powershell
C:\Users\Bruce>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a=0
>>> while(True):
...     print(a)
...     a=a+1
...
0
1
2
3
4
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
OSError: raw write() returned invalid length 6 (should have been between 0 and 3)
4
```

**Comment by chabou** [comment]
Repoduced only on Windows (on GitBash).
Works great on macOS.

Seems related to win-pty.

**Comment by duttaditya18** [comment]
@chabou The exact same code you wrote works fine on Canary 11, Hyper, ZSH, Win 10 V-1709

**Comment by brucedjones** [comment]
Forgot to mention that I'm noticing incomplete output in powershell too with canary11, but am not in a position to test that code with ps for a few days.

**Comment by brucedjones** [comment]
Seems to be fixed in canary 15 with powershell
