### ISSUE TITLE
CMD + R breaks Hyper

### ISSUE THREAD

**Issue by kuoppa** [zeit/hyper#2674]
When pressing CMD + R when window is active it breaks the app. it clears all texts and no tab is working except the one you're in. So it results in a reboot of the  app.

- **OS version and name**: 10.13.1 High Sierra
- **Hyper.app version**: 1.4.8

**Comment by lesce** [comment]
I can take a look 👀

**Comment by kuoppa** [comment]
This still breaks Hyper. Even in 2.0.0.

**Comment by chabou** [comment]
Reload and ForceReload will be removed soon

**Comment by graciano** [comment]
Is there a way to configure it to do nothing when I press cmd+R?

**Comment by timothyis** [comment]
Possibly by registering a custom keymap, although I'm not sure @graciano

**Comment by timothyis** [comment]
I'm going to merge this issue into #921. I feel like this issue belongs in the same realm.
