### ISSUE TITLE
Getting canary notifications even when updateChannel is stable.

### ISSUE THREAD

**Issue by arshdkhn1** [zeit/hyper#2678]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Lubuntu 17.10
- **Hyper.app version**: 1.4.8

## Issue

![image](https://user-images.githubusercontent.com/16819670/36323391-ccacd7f4-1376-11e8-9de1-051082219d1a.png)

Even when I change updateChannel to stable, I get notifications for stable version.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
