### ISSUE TITLE
chinese fonts has some error

### ISSUE THREAD

**Issue by MiYogurt** [zeit/hyper#2682]
![image](https://user-images.githubusercontent.com/10082395/36339044-49ec6506-13f7-11e8-97bc-1fed8cc10fe4.png)

![image](https://user-images.githubusercontent.com/10082395/36339047-6c720e5a-13f7-11e8-9dbb-5c3079573c11.png)

![image](https://user-images.githubusercontent.com/10082395/36339048-81de2d3c-13f7-11e8-8c51-3068e37019ae.png)

![2018-02-17 15 33 58](https://user-images.githubusercontent.com/10082395/36339062-0e34f432-13f8-11e8-9d26-8587aacd25f9.gif)
![2018-02-17 15 33 02](https://user-images.githubusercontent.com/10082395/36339063-0effad4e-13f8-11e8-8bd5-4dad3db3d73c.gif)

![image](https://user-images.githubusercontent.com/10082395/36339096-d2ebdfca-13f8-11e8-925e-a5569a26c4c5.png)

have some config can fix they error?

**Comment by albinekb** [comment]
Hi! Try hyper canary, read how to enable it @ https://zeit.co/blog/canary  

add `updateChannel: 'canary'` to your .hyper.js

**Comment by MiYogurt** [comment]
yes 3q, it's work for me . but it look like v2 did not finish
