### ISSUE TITLE
Allow remapping keys, like iTerm does 

### ISSUE THREAD

**Issue by amisarca** [zeit/hyper#2683]
An very useful feature of iTerm is that it allows remapping certain keys. It would be really cool if hyper allowed remapping the keys in a similar fashion 

<img width="933" alt="screen shot 2018-02-18 at 20 53 46" src="https://user-images.githubusercontent.com/648130/36356759-4d1da9ae-14ee-11e8-89e0-860ff7a8d78a.png">

**Comment by Ichtaina** [comment]
+1

**Comment by albinekb** [comment]
What are you missing from our keymap in config? https://hyper.is/#keymaps
