### ISSUE TITLE
2.0.0-canary.12 is broken 

### ISSUE THREAD

**Issue by VladimirHumeniuk** [zeit/hyper#2686]
Hi guys, looks like you broke app in last canary release. Scroll and vertical split does not work after update.

**Comment by albinekb** [comment]
Yes we broke it intentionally. Sorry for the inconvenience. You can switch to the stable release by chaning `updateChannel: 'stable'`

No this is a regression, thanks for reporting. We're on it.

**Comment by chabou** [comment]
Fixed by https://github.com/zeit/hyper/commit/52ac609c6ecacc2801da84203f617e0f7a0ca91f

New canary incomming

**Comment by chabou** [comment]
Broken by https://github.com/xtermjs/xterm.js/pull/1208
