### ISSUE TITLE
Reset splits either side of a divider to an even ratio on double click of the divider

### ISSUE THREAD

**Issue by timothyis** [zeit/hyper#2687]
## Enhancement
Would be great if double clicking the divider between two splits would reset those two splits to an even size. Otherwise you have to drag and guess.

![image](https://user-images.githubusercontent.com/1695613/36427984-957b5bd4-1646-11e8-9a5e-5a71ee8dbded.png)

**Comment by maikwoehl** [comment]
I think `` hyper/lib/components/split-pane.js `` ist the relevant part. 

I will take some time of my break at work to think about it. 

Maybe I will come up with a solution. 

Please don't assign me yet. I don't know if I can find time to contribute. But I will try.

**Comment by lesce** [comment]
@maikwoehl I can take a look also , if you haven't started it .
I already have a working prototype , could probably create a PR today 
Let me know what your status is on this

**Comment by lesce** [comment]
added a PR for this , would love some feedback on it @maikwoehl @timothyis

**Comment by timothyis** [comment]
Merged in #2692 🎉 

Huge thanks to you @lesce ❤️ and for your review and interest @maikwoehl 👏 

I hope we see you contributing again 🙏
