### ISSUE TITLE
Semi-transparent background not working as expected

### ISSUE THREAD

**Issue by bboure** [zeit/hyper#2688]
How to reproduce:

1.  I have `2.0.0-canary.13`
2. I have this line in my `.hyper.js`
````js
backgroundColor: 'rgba(0, 0, 0, .7)',
````
3. I open hyper and see a completely transparent background
4. I open preferences, background becomes completely black
5. I click on hyper to regain focus, background becomes as expected (semi-transparent black)

**Comment by JesseLeite** [comment]
Same here 😢

![screen shot 2018-02-20 at 10 04 49 am](https://user-images.githubusercontent.com/5187394/36431408-84d32f26-1625-11e8-943a-3fe25cc7cb88.png)

**Comment by chabou** [comment]
Reproduced

I noticed something:
If you edit your config again and save, background color is ok 😞

**Comment by JesseLeite** [comment]
@chabou yeah I noticed that too.  However upon restarting, it's transparent again.  Also "background color is ok" doesn't seem totally true...

![screen shot 2018-02-20 at 10 16 33 am](https://user-images.githubusercontent.com/5187394/36432068-3a379928-1627-11e8-947b-5ddce4a588cd.png)

It doesn't seem to matter whether I set opacity to 0.6 or 0.9, it renders the same on save.

**Comment by chabou** [comment]
Oh, I didn't noticed that.

Thank you 🙏 

Investigating...

**Comment by chabou** [comment]
`2.0.0-canary.14` incoming

**Comment by chabou** [comment]
Really sorry for this regression 😞

**Comment by JesseLeite** [comment]
@chabou no problem, and thank you!
