### ISSUE TITLE
Bug on opening, can't do anything as if it doesn't load fully

### ISSUE THREAD

**Issue by jghielmi** [zeit/hyper#2690]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows10
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [https://gist.github.com/jghielmi/837085d68cf80ec098c8557737258e57](url)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
When I open Hyper I can't type anything and it is stuck like that :
![hyper_2018-02-21_16-04-40](https://user-images.githubusercontent.com/14925932/36487426-200873a6-1721-11e8-9e63-d387551754e4.png)

But when I open a new tab or window everything works properly.
Also some plugins like mactabs arn't working but I don't know why, they launch but don't take effect.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
