### ISSUE TITLE
Export the text as ctrl + s doesn't exist in HyperTerminal

### ISSUE THREAD

**Issue by mhamdan95** [zeit/hyper#2693]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: <macOS HighSierra 10.13.2>
- **Hyper.app version**: < hyper 1.4.8 >
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 

Issue
Hi guys, when I open HyperTerminal I don't find "export the text as file" (like when I do ctrl + s) and it's very important as much in Terminal, then I want to know if anyone had already found this feature and I'm ready to participate your propositions

**Comment by ppot** [comment]
export text as ?

**Comment by lesce** [comment]
as a file , iterm2 and Terminal.app has this feat
first I ever heard of it too

**Comment by mhamdan95** [comment]
@ppot sorry, yes it's as file

**Comment by mhamdan95** [comment]
@lesce thanks for your participation

Then do you have any idea about the solution?

**Comment by lesce** [comment]
@mhamdan95 I can take a look tomorrow

**Comment by chabou** [comment]
Perfect idea for a plugin.
Saving a selection or all history 😍

**Comment by mhamdan95** [comment]
@chabou that's true, thanks a lot :+1:

**Comment by mhamdan95** [comment]
hey guys, I didn't fix the feature yet, but I developed my ideas, and finally I found the root of the feature, it's in the folder app -> renderer in the file bundle.js 

We have to add some operation to make work the "Export the text as"
Need your help 😟

**Comment by mhamdan95** [comment]
@chabou @lesce @ppot 
Hi guys, do you have any proposition please?

**Comment by neil-orans** [comment]
@NicholasMorrison and I will be working on this issue in the coming weeks.

**Comment by mhamdan95** [comment]
yeaaah @neil-orans it will be just amazing, we can exchange our ideas together ;)

And I added the "save as" in the program but without the functionality. Then actually we have to do the function that makes the "save as" run.

**Comment by chabou** [comment]
Be sure to target our canary version (our upcoming v2).

**Comment by NicholasMorrison** [comment]
@chabou If we simply pull from the canary branch and test our plugin with that version, would this suffice? Or is the canary version subject to a lot more change? The plugin mainly relies on being able to access the "term" object that is passed down to the _onTerminal function in most React Components that are implemented as hyper plugins. If the organization of the contents of the term object could possibly change a lot in the coming release of v2, then we will need to revise the plugin a bit.

**Comment by chabou** [comment]
It will be enough to test upon current canary (This should be our last canary before shipping our v2).
You'll still have access to Terminal instance (thanks to `onTerminal` hook), but be careful: `xtermjs` is now used instead of `hterm` as underlying terminal lib.

**Comment by neil-orans** [comment]
the onTerminal hook doesn't seem to be working/executing if we use the script in the canary. Is this a known issue?

**Comment by chabou** [comment]
@neil-orans Thank you so much for this plugin.
Do not hesitate to submit it to our store: https://github.com/zeit/hyper-site/wiki/Submitting-a-new-plugin-or-theme-to-Hyper-Store

**Comment by neil-orans** [comment]
No problem! Credit also goes to @NicholasMorrison since much of this code was produced via pair-programming. Once we can do a little more testing, we will release and publish the 1.0.0 to npm and submit it to the hyper-store. Thanks for your help along the way @chabou!
