### ISSUE TITLE
Crashes when trying to use Powershell as the login shell.

### ISSUE THREAD

**Issue by abhi18av** [zeit/hyper#2694]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
I'm on the stable release 
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **CetnOS 7**: 
- **Hyper version 1.4.8**: 
- **https://gist.github.com/abhi18av/19951176d337d2d28ef6499c93f3bb41**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

The Hyperterm crashes upon trying to set the login shell to Powershell

```sh

> which pwsh
/usr/bin/pwsh
```

**Comment by stefanivic** [comment]
@abhi18av there was an issue with `shellArgs: ['--login'],` causing issues on Windows for Powershell, can you try to remove `['--login']` and check if it works.

**Comment by abhi18av** [comment]
Yup, it works fine after the suggested changes. :+1:

**Comment by abhi18av** [comment]
Thanks @stefanivic :)
