### ISSUE TITLE
gpu is always active when Hyper is active

### ISSUE THREAD

**Issue by crostine** [zeit/hyper#2695]
- [v] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [v] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10**
  - **OS Name**	Microsoft Windows 10 Home
  - **Version**	10.0.16299 Build 16299
  
- **1.4.8 stable**
- **[Gist of .hyper.js](https://gist.github.com/crostine/d77f046d6fd440f1d309ab41793d9253)**
- **N/A**
- **Is Vanilla**

## Issue

at first I was curious about why my laptop fans are on when I have Hyper.js open.
so after a little bit of monitoring with task manager I can see that the GPU is always on. and by always i literally mean always, not the integrated with cpu gpu but the other gpu, my GTX 1050.
I'm not sure if this is by design or just something that slipped through, but all I can tell is that Hyper is using atleast 300MB of memory and a <1% spike in gpu rendering every minute.

**Comment by MAPESO** [comment]
@crostine You can try in the canary version, maybe the consumption of the cpu is lower.

**Comment by crostine** [comment]
I found it, when I tried to force Hyper to use the integrated card though NVidia control panel, it was already set to prefer the dedicated gpu. 
I changed this to automatic/global setting and the dedicated gpu is now turned off.

**Comment by albinekb** [comment]
Great to hear this got resolved. Thanks for updating us and closing 👍

**Comment by nurikabe** [comment]
@crostine Same problem here. Can you elaborate on what you did to fix?

**Comment by crostine** [comment]
1. Open up NVIDIA Control Panel
2. Select "Manage 3D settings" in the left menu
3. Select the "Program Settings" tab
4. Use the dropdown to find Hyper (if its not listed there are no different settings from global settings)
_Here I noticed that the selected preferred graphics processor was on "High-performance NVIDIA processor"_
5. Change this option to "Use global setting" or "Integrated graphics"
6. Click "Apply" in the lower right corner

I hope this helps
