### ISSUE TITLE
How to call `yarn build` after plugin installation? 

### ISSUE THREAD

**Issue by krzema12** [zeit/hyper#2696]
I develop a plugin: https://github.com/krzema12/hypergravity

I use yarn and webpack to bundle several .js files into one index.js file that resides in the root directory of my plugin and is loaded by Hyper. Currently, with every change in the source code, I need to recompile this index.js file and add it to the commit. Rebuilding is done after I do `yarn build`. 

My aim is `yarn build` to be executed automatically when someone downloads or updates my plugin, so that the compiled and potentially minified /index.js does not reside in git repo.

How can I achieve it?

For reference: https://github.com/krzema12/hypergravity/issues/8

**Comment by albinekb** [comment]
I think you should publish a prebuilt version of your package, you should only have webpack as a development dependency. In development, just run your webpack manually with --watch, would that work? So you should just build as normal and add `files` to your package.json, only publishing the **built** files. Hope that makes sense. I can see if I can find a guide 👍

**Comment by krzema12** [comment]
Thanks for the pointer, I played with `.gitignore` and `.npmignore` a bit and I'm further towards having it the proper way. Now, `/index.js` is ignored by git, but not by npm.

The only thing left is to ensure that there's the compiled `index.js` in the root directory. Otherwise, after calling `npm publish`, the compiled JavaScript **won't be** in the npm package. Are you aware of any mechanism that does this check? Ideally `npm publish` and `yarn publish` should fail if there's no `/index.js`.

**Comment by albinekb** [comment]
You should add your build script to `"scripts": { "build": "here" }` and it will be run automatically on `yarn/npm publish`. If you can't configure your build to output in the root, you can add `"main": "path/to/index.js"` to your package.json and it should work 👍

**Comment by krzema12** [comment]
Works like a charm.
For future reference, here are the exact changes I made to achieve it: https://github.com/krzema12/hypergravity/commit/d4df36f63ff00e3cc46d956c6aa3db461b967591

Thanks for your time!

**Comment by albinekb** [comment]
Glad i could help and good luck! 😊👌🤘
