### ISSUE TITLE
Weird Scrolling Issue with other Applications

### ISSUE THREAD

**Issue by gurpreetshanky** [zeit/hyper#2699]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

OS version and name: Windows 10-1709(16299.248
Hyper.app version: 1.4.8

When hyper is active it interferes with scrolling issues in other programs like Sublime Text or Vscode (Literally makes them unusable). But if I close or even minimize Hyper, scrolling works fine. I also tried running Hyper with NVIDIA graphics card instead of integrated intel GPU. Same result. Also just affects win32 applications not the UWP applications.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by gurpreetshanky** [comment]
Sadly the problem is still there with Hyper 2.0.

**Comment by albinekb** [comment]
That is super weird @gurpreetshanky, is there anyone that can reproduce?

**Comment by gurpreetshanky** [comment]
@albinekb Found the culprit. Hyper tabs enhanced plugin was slowing Hyper and was using 30% GPU. Removing it works fine. Anyone using Hyper on Windows, avoid this plugin.
