### ISSUE TITLE
Bell broken in canary

### ISSUE THREAD

**Issue by aditya0099** [zeit/hyper#2707]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: canary.14

## Issue

When looking through the code trying to solve issue #1613, I found that the bell is broken on all platforms. After editing config, the file `lib/components/term-group.js` adds the bell property to props here:
https://github.com/zeit/hyper/blob/76beaa32f5f3285bc8f7083fff8cd722ba97f60a/lib/components/term-group.js#L82 But when it is passed to the file `lib/components/term.js`, where the new terminal is created, it is not actually used. For this reason, the terminal doesn't seem to be making any sound regardless of the setting on Mac and Linux. This may have happened during the switch from hterm to xterm.

On windows, the sound that plays depends on which terminal is being used. By default, hyper uses cmd, so the bell sound is the default bell sound for cmd. If the terminal is switched to bash (Linux subsystem), the bell sound is again the default sound for bash on Windows. PowerShell doesn't seem to have a bell by default, so if PowerShell is used, no bell sound is heard.

If the bell is not desired, a temporary solution to this may be to use PowerShell by default if the operating system is Windows 10, as this will disable the sound.

**Comment by Stanzilla** [comment]
@aditya0099 Do you want to make a PR to fix this?

**Comment by ShaggyDev** [comment]
@Stanzilla @aditya0099 There is an open pull request that is addressing this issue currently #2938. Stay tuned ;D
