### ISSUE TITLE
Some improvements ?

### ISSUE THREAD

**Issue by justUmen** [zeit/hyper#2709]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Arch
- **Hyper.app version**: 1.4.8

## somes recommendations

(1) - Allow transparency above 90%, now opacity <0.1 in "hyper.js" turn the background white.
(2) - Being able to change the window title (useful to have several instances and focus using window title)
(3) - Being able to launch a command or script on launch (to use `ranger` for example on a separate instance of hyper)
(4) - Problems with some output : `yes y` just destroy Hyper for me, Ctrl+c can't recover.

For (2) and (3) and `ranger` as an example, it is easy to do with lxterminal :
`lxterminal -t RangerTitle -e ranger`

You are doing an amazing work, thank you and good luck !

**Comment by timothyis** [comment]
Hi! 1 and 4 should be fixed with the latest release. 2 and 3 already have issues open 🎉 

#284 #462
