### ISSUE TITLE
Support for multi-line selection

### ISSUE THREAD

**Issue by kenorb** [zeit/hyper#2710]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 10.13.2
- **Hyper.app version**: Hyper 1.4.8 (stable)

## Issue

Given the output of the following command:

    seq 1 200 | xargs

there is a problem selecting a line. When double clicking on the line, it isn't selected as the whole.

For example, when I'm in _Terminal_ app, double clicking in the middle of the output, it select the whole line correctly:
<img width="571" alt="screen shot 2018-02-25 at 15 29 54" src="https://user-images.githubusercontent.com/266306/36643264-d46096ea-1a40-11e8-9adb-c8f630b2f1f0.png">

In _Hyper_, it selects only part of the line:

<img width="668" alt="screen shot 2018-02-25 at 15 30 57" src="https://user-images.githubusercontent.com/266306/36643268-ee0cfb4c-1a40-11e8-9544-41b5b0731180.png">

This is trouble, especially when copying one long line and it's not the same, as there are random whitespaces added in the middle when the line breaks.

**Comment by chabou** [comment]
Thanks for your feedback :pray:
It will be fixed in our v2 that will be shipped very soon.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
