### ISSUE TITLE
First run produces an temporary error

### ISSUE THREAD

**Issue by ricknox** [zeit/hyper#2712]
## Information card

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: darwin x64 17.4.0
- **Hyper.app version**: Hyper 1.4.8 (Electron 1.7.8)
- **Contents of the .hyper.js file**: [1258180b739509563cbbf3687f47e3bd](https://gist.github.com/ricknox/1258180b739509563cbbf3687f47e3bd) 
- **The issue is reproducible in vanilla Hyper.app**: yes
- **Relevant information from devtools**:
<img width="584" alt="screen shot 2018-02-26 at 11 07 04" src="https://user-images.githubusercontent.com/33787256/36664830-2a635488-1ae6-11e8-93b6-4eab904692d4.png">

## Issue

When downloaded and installed Hyper.app from the [Hyper website](https://hyper.is/) and opened as the first time, I'm getting the following notification:

![screen shot 2018-02-26 at 11 06 27](https://user-images.githubusercontent.com/33787256/36664944-7a002b24-1ae6-11e8-9ed1-e48ecb9280d6.png)

After quitting Hyper.app and re-opening the application seems to fix the notification. The warning in the dev tools console: `Unimplemented DEC Private Mode: 1034` remains.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
