### ISSUE TITLE
Can't map command+left to tab:prev (Mac OS)

### ISSUE THREAD

**Issue by joncalhoun** [zeit/hyper#2723]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS High Sierra (v10.13.3)
- **Hyper.app version**: v1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/joncalhoun/7c8643f65bce7a8d2480888f21f724a2 (but the only relevant portion is below)

```js
module.exports = {
  keymaps: {
    'tab:next': 'command+right',
    'tab:prev': 'command+left'
  }
};
```

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: This is reproducible in vanilla.

## Issue

When I attempt to assign the `command+left` or `command+right` keymappings to `tab:next` and `tab:prev` it doesn't work. The commands continue to perform their old operations - `editor:moveBeginningLine` and `editor:moveEndLine`

If I change the keyboard shortcut to something else - say `command+shift+9` and `command+shift+8` for next and prev and restart hyper they work fine, so I suspect the issue has something to do w/ the fact that these keyboard shortcuts are already assigned to something. I have tried to add different keymaps for those commands in an attempt to remedy the issue to no avail.

I'd be happy to try to help with a PR, but I don't have the slightest clue on how to develop hyper and would need help getting started. Thanks!

**Comment by chabou** [comment]
It reproduced your issue with v1.4.8
But this is already fixed in our canary (future v2).

**Comment by joncalhoun** [comment]
@chabou Sorry - I didn't see the canary build and should have tested it first. Thanks for the help.

**Comment by chabou** [comment]
Do not be sorry! This v2 would really be shipped!

**Comment by ariabuckles** [comment]
Hi! I'm seeing this issue on 2.0 and 2.1-canary. Any chance this could be reopened?

I'd also be interested if someone knows what changes fixed this problem in 2.0-canary.

Thanks!

**Comment by dodoatsalesforce** [comment]
I have the same issue in v2.0.0. macOS High Sierra. 
Mapping `'tab:prev': 'command+left'` doesn't work but mapping `'tab:prev': 'command+shift+left'` does. Any idea? Is someone else seeing this?

**Comment by robin850** [comment]
Hi there,

This issue seem to be back. With v2.1.0 and the following configuration, it doesn't work:

~~~json
keymaps: {
  "tab:next": "Cmd+Right",
  "tab:prev": "Cmd+Left"
}
~~~

I tried to replace `Cmd` with `Command` and `command` but without any luck.
