### ISSUE TITLE
As a new user I missed a good manual.

### ISSUE THREAD

**Issue by tonksol** [zeit/hyper#2730]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by tonksol** [comment]
I didn't know that I need to install node.js and didn't know that I need to install something in VS code. So examples of how to set up hyper for different (frequently used) code editers would be nice :)

**Comment by jaydh** [comment]
A lot of this depends on your operating system and package manager managing dependencies for you. Hyper does not have a VS Code dependency. Maybe you're confusing that with electron (a dependency for both VS Code and hyper)

**Comment by tonksol** [comment]
Okay, that's a pitty. Because I find it hard too use as a complete newbie. But once somebody helped me to set it up I am very happy with it. Thank you for your response :) And keep up the good work!

**Comment by albinekb** [comment]
Hyper also does not need nodejs to be installed, we ship our own `yarn` to install plugins and use the shipped `node` inside electron to run it 👍
