### ISSUE TITLE
Hyper Helper renderer hangs and uses 100% CPU

### ISSUE THREAD

**Issue by kenorb** [zeit/hyper#2731]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 10.13.2
- **Hyper.app version**: Hyper 1.4.8 (stable)

## Issue

I did some action, like pasting or something which caused _Hyper_ terminal to go wild. For over 12h it's using 100% CPU and over 10G of virtual memory and it doesn't seem to unclog. I can switch to the app, but any interaction with it is not possible. It's like it's processing something very heavily.

Here are few details:

```
$ pstree 8188
--- 08188 kenorb /Applications/Hyper.app/Contents/Frameworks/Hyper Helper.app/Contents/MacOS/Hyper Helper --type=renderer --no-sandbox --primordial-pipe-...
$ ps wuax 8188
USER     PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
kenorb  8188  81.5  5.6 11998660 942436   ??  R    22Feb18 883:43.03 /Applications/Hyper.app/Contents/Frameworks/Hyper Helper.app/Contents/MacOS/Hyper
```

I did `sudo spindump 8188` on it, and I'm attaching the file for analysis: [Hyper_Helper_8188.spindump.txt.gz](https://github.com/zeit/hyper/files/1778588/Hyper_Helper_8188.spindump.txt.gz)

It seems it's stuck on:

    Thread 0x3db812           DispatchQueue <multiple>  Thread name "CrRendererMain"                        
    1000 samples (1-1000)     priority 31-91 (base 31)  cpu time 9.681s

and:

```
948  v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 509 (libnode.dylib + 2365901) [0x10c5bc9cd]
  948  v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 175 (libnode.dylib + 4997039) [0x10c83efaf]
```

Few things which are repeating:

```
1    v8::internal::Factory::LookupSingleCharacterStringFromCode(unsigned int) + 4 (libnode.dylib + 5027108) [0x10c846524] (running)
1    v8::internal::Factory::LookupSingleCharacterStringFromCode(unsigned int) + 37 (libnode.dylib + 5027141) [0x10c846545] (running)
1    v8::internal::Factory::LookupSingleCharacterStringFromCode(unsigned int) + 58 (libnode.dylib + 5027162) [0x10c84655a]
 *1    ??? (kernel + 2391136) [0xffffff8000447c60] (runnable)
1    v8::internal::Factory::LookupSingleCharacterStringFromCode(unsigned int) + 126 (libnode.dylib + 5027230) [0x10c84659e] (running)
1    v8::internal::Factory::LookupSingleCharacterStringFromCode(unsigned int) + 136 (libnode.dylib + 5027240) [0x10c8465a8] (running)
```

and

`v8::internal::SlicedString::SlicedStringGet(int) + 8 (libnode.dylib + 8117960) [0x10cb38ec8] (running)`

I don't have reproducible steps, but it happens from some time to time.

**Comment by MAPESO** [comment]
@kenorb I can try it in the canary version 🙏

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
