### ISSUE TITLE
Can't edit preferences

### ISSUE THREAD

**Issue by PlanetVaster** [zeit/hyper#2734]
First time installing and I get an error everytime I try to edit my preferences saying "module not installed"
        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by MAPESO** [comment]
@PlanetVaster can provide more information 🙏

**Comment by MAPESO** [comment]
@PlanetVaster It is a very frequent problem in the windows version, since it tries to execute the file 
`.hyper.js`.  in the canary version it is configured to open notepad or any text editor that has been previously configured

**Comment by MAPESO** [comment]
@PlanetVaster  You can change to the Canarian channel by adding this line of code to the .hyper.js file: `updateChanel:  'canary'`

**Comment by itssimple** [comment]
Another solution would be to change the default action for .js-files in Windows, to open in your favorite JavaScript-editor. When I configured so that .js-files opened in Visual Studio Code, this problem went away.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
