### ISSUE TITLE
Styled-jsx migration

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2737]
I would love to replace `aphrodite` by `styled-jsx`.
It would be more consistent to use Zeit tool :)

**Comment by MAPESO** [comment]
@chabou I'm using styled-jsx in my electron application 😍

**Comment by chabou** [comment]
🤔

**Comment by timothyis** [comment]
I've begun work on this here: https://github.com/zeit/hyper/tree/styled-jsx
