### ISSUE TITLE
[CLI] Do not automatically prefix package name when installing

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2739]
For now, CLI automatically adds `hyper-` prefix when installing/uninstalling plugins.
`hyper i pane` do exactly the same thing than `hyper i hyper-pane`.
But if user wants to install a plugin with a non standardized name like `hyper i hyperline`, it will try to install `hyper-hyperline`.
It leads to some security problems. If someone forks `hyperline`, adds some malicious code and published it as `hyper-hyperline`...

Please remove any automatically prefixing in CLI.

**Comment by chabou** [comment]
@MAPESO this is a major issue and I really want to fix it and ship it ASAP.
Do you know when you'll have time to work on that?

**Comment by MAPESO** [comment]
@chabou Hi, I am struggling to solve this problem, I would appreciate it if you could help me 🙍

**Comment by albinekb** [comment]
@MAPESO I did it while I had some spare time. You can look at #2757 to see what needed to be done 👍 ✅

**Comment by MAPESO** [comment]
@albinekb Thanks ❤️ 🙏
