### ISSUE TITLE
SSH url scheme handling should not be added on dev mode

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2740]
Since #2516, Hyper is set as default program to handle `ssh://` url scheme.
It should not be done on dev mode.
Condition should be added here:
https://github.com/zeit/hyper/blob/0162a9f84dab44a5be395f4faf7579217822e5a6/app/index.js#L186-L195

cc @antonioalmeida

**Comment by ajomadlabs** [comment]
Can I take up this issue

**Comment by antonioalmeida** [comment]
Sure @ajomadlabs, you just need to check `isDev`, before applying the change

**Comment by ajomadlabs** [comment]
@antonioalmeida Since this is my first issue, can you provide some resource, where to start off

**Comment by diogotorres97** [comment]
@ajomadlabs literally do:
 if (! isDev){ line 188,189} 
else 
nothing;

Same thing to second case

**Comment by antonioalmeida** [comment]
https://github.com/zeit/hyper/blob/0162a9f84dab44a5be395f4faf7579217822e5a6/app/index.js#L186-L195

 As @chabou mentioned, in this area you should check if Hyper is running on dev mode, and prevent the chances if so. To do this, you can check `isDev`'s value, similar to what is done here:
 https://github.com/zeit/hyper/blob/0162a9f84dab44a5be395f4faf7579217822e5a6/app/index.js#L88-L108

Is that clear?

**Comment by ajomadlabs** [comment]
I followed the contribution guidelines but I am unable to set up. I am encountering with the following error
![errorhyper](https://user-images.githubusercontent.com/21251118/37132946-9028929c-22b6-11e8-86f0-daedd256f3af.png)

**Comment by ajomadlabs** [comment]
@chabou I created a pull request https://github.com/zeit/hyper/pull/2745. Please do suggest me changes if any

**Comment by antonioalmeida** [comment]
@chabou no problem! 👍 
good job @ajomadlabs
