### ISSUE TITLE
Question: Change shell to use in runtime

### ISSUE THREAD

**Issue by jperezruiz** [zeit/hyper#2741]
Thank for bring us an amazing tool.
I would like to ask you a question, is possible to modify at runtime the shell to use?.
I usually work with Git bash but I also need Windows Powershell, I would like to develop a plugin that allows configuring multiples shells, similar to ConEmu tasks. I made some debugging and as far as I saw is not possible to change the shell in runtime.
If you have enough time, could you please confirm me if is possible?
Thank you!

**Comment by chaseleinart** [comment]
@jperezruiz - Hi Javier - It looks like there is currently an issue with community Feedback wanted under  #1147 - Does that address this and your earlier issue #2411 ?

**Comment by Stanzilla** [comment]
Please follow here https://github.com/zeit/hyper/issues/1147
