### ISSUE TITLE
Ctrl + N breaks Hyper on Windows

### ISSUE THREAD

**Issue by Furetur** [zeit/hyper#2744]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: latest stable (8 march 2018)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: vanilla. no plugins

## Issue

On windows when you press ctrl+N and enter (^N enter) it breaks the text font permamently

**Comment by chabou** [comment]
Hi there, thanks for reporting an issue!
Unfortunately, we need the information that was listed out in template when you created the issue to really help solve your problem. For now, we'll close your issue and wait for you to comment/re-open the issue with the template information filled out from https://github.com/zeit/hyper/issues/new
