### ISSUE TITLE
built-in hyperlinks alternative not working properly

### ISSUE THREAD

**Issue by SirWindfield** [zeit/hyper#2748]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X Sierra 10.12.6
- **Hyper.app version**: Hyper 2.0.0-canary.14 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/SirWindfield/32176f589d86e1897a540ef92e365104
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
It looks like the built-in `hyperlinks` alternative in v2 has still some errors/bugs. The link does not get highlighted using another color as `hyperlinks` did it in version 1.4 of Hyper. 
Clicking a link and holding the CMD/Control key does not open the link within Hyper itself but rather in the default browser.

I am not sure if these features have already been added or are on some kind of Todo list already. Just wanted to make sure :smile:

**Edit:** 
Here are two images of hyper 1.4 and 2.0 showing the differences:
<img width="1280" alt="screen shot 2018-03-09 at 17 21 28" src="https://user-images.githubusercontent.com/5113257/37217656-66525c4c-23be-11e8-914e-1ad591bb27f5.png">
<img width="1280" alt="screen shot 2018-03-09 at 17 16 46" src="https://user-images.githubusercontent.com/5113257/37217661-69266986-23be-11e8-8516-e087d2d5ff5b.png">
<img width="1280" alt="screen shot 2018-03-09 at 17 22 43" src="https://user-images.githubusercontent.com/5113257/37217701-83671016-23be-11e8-82b6-9d871341630c.png">

The first one is hyper running on version 1.4, the second one on 2.0 canary. The third one is the CMD/Control click on the link that will open the url within hyper itself.

**Comment by chabou** [comment]
Thank you for your feedback!

After some discussions about some security concerns, we abandoned the idea of browsing websites directly in Hyper.

Electron webview is not enough secure (old Chrome version, potential API leaks in website JavaScript context...).

We are really unhappy to remove this shining feature, but as a terminal app, security is non-negotiable.

**Comment by gustavoFreireS** [comment]
I did a local plugin to reproduce the older behavior using an iframe component, Am I still vunerable to this kind of security problems?
![img_0679](https://user-images.githubusercontent.com/8769796/44348901-25ab2400-a472-11e8-84aa-dc750a5cb590.JPG)

**Comment by albinekb** [comment]
There's so much going on in electron so I would say, yes you're vulnerable if you open web pages in electron. Will it matter? Most likely not.

**Comment by kevin-roan** [comment]
https://www.electronjs.org/docs/latest/api/webview-tag#nodeintegration what about this..? it's been 3 years na? why not bring back the feature

**Comment by Meqr1** [comment]
https://www.electronjs.org/docs/latest/api/webview-tag#nodeintegration

guys you need to bring back the feature. btw if you want to use this feautre you can see this -
https://dev.to/craftzdog/getting-side-by-side-preview-in-a-terminal-app-hyper-20ii

but i would love to see this feature in official app back again

**Comment by RyadMM** [comment]
was this feature even integrated back in the app?
