### ISSUE TITLE
A JavaScript error occurred In the main process

### ISSUE THREAD

**Issue by Hero-here** [zeit/hyper#2749]
-
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

![snipaste_2018-03-10_21-12-39](https://user-images.githubusercontent.com/14844769/37242646-14f5503a-24a8-11e8-8ce2-7d30017c68f8.png)

**Comment by MAPESO** [comment]
@Hero-here Could you provide more information about the problem 😅

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
