### ISSUE TITLE
mac ctrl+minus does not resize text properly

### ISSUE THREAD

**Issue by jonassteinberg1** [zeit/hyper#2750]
I have reviewed the issues and believe I am the first to report this
- Hyper version: 1.4.8
- OS: OSX 10.12.6 (although the server I noticed this on is CentOS 6.9 which I was ssh'd into, but I don't believe that is relevant? Hyper is installed and running from OSX 10.12.6 )
- Hyper config (it's stock) [gist](https://gist.github.com/jonassteinberg1/ebea0f3c400d5bc588370f5292fa363b)
- Issue is reproducible in vanilla hyper.

## Issue

Ctrl+minus does not put text on one line so as to make it legible. 

1) Hyper.  Last column text spills over on to next line.  Normal.

![image](https://user-images.githubusercontent.com/7853938/37245668-9c3b89ae-2450-11e8-9b5d-64c260c794d0.png)

2) Hyper.  Ctrl+minus does not bring spilt text onto same line.

![image](https://user-images.githubusercontent.com/7853938/37245678-abc65ade-2450-11e8-90eb-a6985543f95f.png)

3) iterm.  Same as 1)

![image](https://user-images.githubusercontent.com/7853938/37245681-b8b95246-2450-11e8-987c-50af9ee07c97.png)

4) iterm.  Ctrl+minus brings spilt text on to same line: legible.

![image](https://user-images.githubusercontent.com/7853938/37245683-c14e157c-2450-11e8-8d0e-fe4e378415d9.png)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
