### ISSUE TITLE
Support for xterm 3.2.0?

### ISSUE THREAD

**Issue by saamalik** [zeit/hyper#2751]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

Hi all -- xterm released the latest version [xterm 3.2.0](https://github.com/xtermjs/xterm.js/releases/tag/3.2.0) a few days ago. Any plans to support this latest version?

I also attempted to change xterm dependency to 3.2.0 but looks like the scrolling behavior has changed.

**Comment by saamalik** [comment]
I found the xterm commit which broke the scroll behavior in Hyper: xtermjs/xterm.js@dc759a93bc7753fcd733a06fbb3a67220120876b.

Verified by reverting the commit. Anyway, the proper solution is to probably figure out how to incorporate scrollbar changes into Hyper.

/cc @chabou

**Comment by saamalik** [comment]
argg -- looks like this was already reported by @chabou at #2686.

**Comment by chabou** [comment]
We need to support this latest version.
Indeed we had some layout problems due to CSS changes with xterm v3.1.0.
But we had some pane width issue too.

We really need to tackle this ASAP
