### ISSUE TITLE
Opening new tab does not resize window properly

### ISSUE THREAD

**Issue by devansh08** [zeit/hyper#2752]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version | Latest canary
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 16.04**: 
- **Hyper 2.0.0-canary.16 (canary)**: 
- **N/A** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 

## Issue

On opening a new tab window height does not update/change automatically which causes lines at the bottom (specially vim status line) to basically vanish. The window resizes if switch between the tabs. Also on closing a tab windows height does not change and causes everything to move up a few lines.

Here's a GIF showing what happens:
![peek 2018-03-11 18-57](https://user-images.githubusercontent.com/21225957/37253938-4d9415f0-255e-11e8-9a07-250a3b84b8b3.gif)

**Comment by hochbrian** [comment]
Yep, I see exactly the same behavior on Windows 10 with the latest Canary build.

**Comment by moso** [comment]
Exists in v2.1.0-canary.2 aswell. I can even confirm that it exists in vanilla Hyper with no themes or plugins installed.

I'm using Ubuntu 18.04, so I guess it's OS-independent.

**Comment by rolurq** [comment]
I'm having the same issue on debian with hyper 2.0.0, also, when I close a tab, keeping only one tab, the height of the window stays the same, as if the tab still exists.

**Comment by devansh08** [comment]
This seems to have been fixed in version 3.0.2, on my machine at least (Arch Linux). I am closing this issue assuming it has been fixed for everyone else as well.

**Comment by pcnate** [comment]
confirmed to work on Ubuntu Pop!_OS

**Comment by moso** [comment]
Confirmed to work in both Ubuntu Budgie 19.04 and Windows 10.
