### ISSUE TITLE
How to add a command to the CommandRegistry from a plugin?

### ISSUE THREAD

**Issue by tastycode** [zeit/hyper#2754]
I'm trying to build the autocomplete functionality in iTerm into hyperterm. It's not clear to me how to get access to the command registry to register my own commands so that others will be able to bind my autocomplete action to whatever they'd like.

I ended up usinng `decorateTerms` to get a ref to the terms object, which ought to have `registerCommands` available as a property (https://github.com/zeit/hyper/blob/canary/lib/components/terms.js#L19). When I inspect the constructor of the terms object being passed to ref, I get an instance of the `exposeDecorators` constructor, which doesn't have the commandregistry accessible.

I'm going to have to hardcode my trigger for now until I get some guidance on how to add commands to hyperterm through a plugin. 

Any suggestions?

**Comment by chabou** [comment]
@tastycode We wrote a non yet published documentation about writing plugins.: https://github.com/zeit/hyper/blob/plugin-doc/PLUGINS.md#keymaps

Please give us your feedback about it. Is it clear? Is there some points to develop?

Thank you in advance. 🙏

**Comment by tastycode** [comment]
It wasn't immediately apparent what `this.terms` was being invoked in the context of. I'm assuming that's from something like 

```javascript
exports.decorateTerms = ( Terms, { React } ) => {
   return class extends React.Component {
     componentDidMount() {
         // i have access to this.terms here from the ref call in the passed HOC
      }

      render() { 
         return <Terms ref={terms => this.terms = terms } {...this.props}/>
      }
   }
}
```

Thanks for the notes about the keybindings, that'll definitely be helpful. Though, I remember trying the above and not seeing a `registerCommands` available on the terms. It seemed i was getting an "exposeDecorator" terms instead.

In other news, I noticed this tidbit later in the page
```
Hyper v2 uses xterm.js instead of hterm. It means that PTY ouput renders now in a canvas not with a hackable DOM structure. For example, plugins can't use TermCSS anymore in order to modify text or links style. It is now required to use only available configuration params that will be passed down to xterm.js.
```
I had a ton of trouble finding any sort of a cannonical state anywhere that would tell me exactly what's on the screen. It seemed that hterm was dispatching SESSION_PTY_DATA and SESSION_ADD_DATA events through redux and those ended up getting passed to `write` or `onData` calls on the hterm instance. E.g. If I typed `test`. I would get a redux action for `t` `e` `s` then `t`. Nowhere in the session, or ui state tree could I find what I had just typed. 

Since I'm working on autocomplete, I need to be able to index all the text on the screen. So I resorted to this gruesome hack.

```
exports.reduceSessions = (state, action) => {
  if (action.type === 'SESSION_PTY_DATA') {
    const hypercompleteStatePrev = state.hypercompleteState || {
      lines: []
    }
    const prevLines = hypercompleteStatePrev.lines
    const frameDocument = document.querySelector('iframe').contentWindow.document
    const currentLines = [...frameDocument.querySelectorAll('x-row')].map( row => row.innerText )
    const nextLines = R.takeLast(LINE_LIMIT)(R.uniq([prevLines, ...currentLines]))

    return state.set('hypercompleteState', {
      lines: nextLines
    })
  }
  return state
}
```

Will there be a better way to get access to all the text on the current term in 2.0?

**Comment by linonetwo** [comment]
@tastycode  For input recording, you can have a look at [hyper-history](https://github.com/garyxuehong/hyper-history) or my [refactored implementation](https://github.com/linonetwo/hyper-cli2gui/blob/master/src/store/reducers.js).

But I don't know how to execute a command after you have made some autocomplete.
