### ISSUE TITLE
Command + Tab does not open new tab

### ISSUE THREAD

**Issue by designMoreWeb** [zeit/hyper#2755]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS High Sierra 
- **Hyper.app version**: Hyper 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:https://gist.github.com/designMoreWeb/3fc18d2b49dbfaefbe8b6cc82785d351
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:N/A
- **The issue is reproducible in vanilla Hyper.app**: Both for me

## Issue

Command + Tab does not open a new tab for me instead it reloads the existing tab. I am not sure what is causing this I tried disabling the plugins I have as well but the issue still exists

**Comment by MAPESO** [comment]
@designMoreWeb  Hi, You can try to delete hyper and try again. I'm testing your plugins but my hyper is still running normally :(

**Comment by MAPESO** [comment]
@designMoreWeb If the problem persists, let me know 🙏

**Comment by chabou** [comment]
For me, `command+tab` is used by OS to switch between application... 🤔 

@designMoreWeb I'm not sure to understand your issue. Do you mean `command+t`?

**Comment by designMoreWeb** [comment]
@chabou yeah I mean command+t my bad lol

**Comment by chabou** [comment]
Are you sure that your finger doesn't hit the `R` key right by `T` key?
Because `cmd+r` is supposed to reload app...

Can you try with another keyboard?

**Comment by designMoreWeb** [comment]
@chabou I will give it a try once I am back home I am away from my main laptop where the issue is occuring

**Comment by designMoreWeb** [comment]
<img width="422" alt="screen shot 2018-03-13 at 11 48 18 pm" src="https://user-images.githubusercontent.com/5986856/37382482-6ec61d38-2719-11e8-9a40-929b750d927a.png">

So I deleted and re-installed hyper twice both times running through clean installs and I am getting this error when editing the preferences not sure what steps to take.

**Comment by damien122** [comment]
@designMoreWeb did you try Ctrl + Shift + T ? On windows it is the combination to open a new tab in hyper.

**Comment by Thebigbignooby** [comment]
I am on windows, and get the following error when I try to open a new tab

![hyper--bug-new-tab](https://user-images.githubusercontent.com/4172090/39039612-1dd6d162-4486-11e8-9758-321d4d1bf464.PNG)

**Comment by albinekb** [comment]
@Thebigbignooby can you please open a new issue and fill in the issue template? That will help us know what that could be about.

**Comment by Thebigbignooby** [comment]
https://github.com/zeit/hyper/issues/2889

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
