### ISSUE TITLE
Function Keys not send to shell

### ISSUE THREAD

**Issue by damien122** [zeit/hyper#2760]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Version 10.0.16299.248
- **Hyper.app version**: 1.4.8 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [https://gist.github.com/damien122/9e88c17f3ecc7d13c64558ef76caa243](https://gist.github.com/damien122/9e88c17f3ecc7d13c64558ef76caa243)

## Issue

Hi,
I have found an issue that hyper dont't send some function keys (F1, F2, F3, F4, F7, F8) to my WSL ubuntu shell. Espasially I see this problem when I use htop in my shell. By pressing F4 for filter running programms nothing happen, but when I press F10 htop close and so on.
My idea was that hyper uses this f-keys for it self and I tryed to overwrite it with the "keymaps" values in my hyper.js settings file. But I could not find the original functions which should be triggerd.
Can someone reproduce this problem? I have this on two different windows pcs.

I use the Ubuntu WSL form Windows 10 store, not the "bash" implementation from dev. tool.

**Comment by d3lm** [comment]
I am experiencing the same a forward delete of text on a Mac. When I press `Fn + Delete` it prints `~` to the terminal. Is it only me or do you have the same issue?

**Comment by damien122** [comment]
@d3lm I tryed your solution, to use bash instead of fish (in my case, its the same as zsh) but nothing changed. I got the same behavior. If I start my linux environment from an tipicall windows terminal then all F Keys works as expected, but in Hyper not.

**Comment by Ricq** [comment]
Same here. Tried using `htop` and `mc` (Midnight Commander) in Ubuntu on Windows using Hyper, but the function keys aren't working. I think they're being intercepted by Chromium.

Any way that we can let the function keys pass through to the console? Or otherwise, a trick through which we can use another command and make that send the function key to the shell?

**Comment by efelippe** [comment]
Same here, Fn keys does not send to shell (bash or zsh) on Windows WSL Ubuntu.

**OS version and name:** Windows 10 Version 10.0.17133.0
**Hyper.app version:** Hyper 2.0.0-canary.16 (canary)

**Comment by leolara** [comment]
More than a year and nobody attended to this?

Should I stop using this shell? Any good alternatives for Windows 10 Linux subsytem

**Comment by paulochf** [comment]
I've just realized this problem, but it's sad it made the first birthday.

Looking forward to some solution. I'm having to close the output and run the command again to avoid scrolling with page up/down to the top/bottom when opening big streams in `less`.

**Comment by damien122** [comment]
Looks like this bug will never be fixed. So I switched to the new windows terminal.

**Comment by mig8447** [comment]
> I've just realized this problem, but it's sad it made the first birthday.
> 
> Just to remember that some current laptops have Home/End to require the Function key.
> 
> I'm having to close the output and run the command again to avoid scrolling with page up/down to the top/bottom when opening big streams in `less`. Funny thing is I can use Fn+Up/Dn for PgUp/Dn, but not Fn+Left/Right for Home/End.
> 
> Looking forward to some solution.

@paulochf did you ended up finding a solution for this?
