### ISSUE TITLE
No app for this action opening preferences

### ISSUE THREAD

**Issue by jkutianski** [zeit/hyper#2762]
When I try to open preferences appears this error

![image](https://user-images.githubusercontent.com/1901108/37441734-96c345fe-27e1-11e8-9039-67739f08b2be.png)

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by MAPESO** [comment]
@arojunior in the canary version it is configured to open notepad or any text editor that has been previously configured. You can change to the Canarian channel by adding this line of code to the .hyper.js file: `updateChanel: 'canary'`

**Comment by MAPESO** [comment]
@jkutianski If the problem persists, tell me 😸

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!

**Comment by jkutianski** [comment]
Works perrrrfect! Problem solved. Thanks!
