### ISSUE TITLE
Set as default terminal in Ubuntu

### ISSUE THREAD

**Issue by baborlelefan** [zeit/hyper#2764]
Hi,
I'm a new user of Hyper and I love it. I'd like to know how to set it as my default terminal. I've tried sudo update-alternatives --config x-terminal-emulator but I didn't find it...

Thanks for your help

**Comment by chaseleinart** [comment]
@baborlelefan Try running to command below to add Hyper to your config. If that doesn't work, can we please see the output from the command you ran?

sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /opt/Hyper/hyper 50

**Comment by baborlelefan** [comment]
It worked, thanks a lot for your answer

**Comment by chaseleinart** [comment]
@baborlelefan Excellent - would you mind marking the issue as Closed?

**Comment by chabou** [comment]
@chaseleinart Thank you so much for your help 🙏

**Comment by yashlalwani** [comment]
It Worked as a charm! Thank You so much :D

**Comment by MrRomo** [comment]
great¡¡¡ finally, that works. thanks

**Comment by pSnehanshu** [comment]
How can we switch back?

**Comment by chaseleinart** [comment]
@pSnehanshu If you run the command: sudo update-alternatives --config x-terminal-emulator, you'll see what x-terminal emulator choices and their paths are available. The command: sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /path/to/term 100, where /path/to/term is an alternative terminal emulator, should then assign the highest priority to whichever terminal you supplied.

**Comment by omkar-dsd** [comment]
Just to make it clear. (same as above)

If you run the command:
```bash 
sudo update-alternatives --config x-terminal-emulator
```
 you'll see what x-terminal emulator choices and their paths are available. The command:
```
sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /path/to/term 100
```
where **_/path/to/term_** is an alternative terminal emulator, should then assign the highest priority to whichever terminal you supplied.

**Comment by pSnehanshu** [comment]
@omkar-dsd @chaseleinart This is the output of the first command
<pre>update-alternatives: warning: /etc/alternatives/x-terminal-emulator is dangling; it will be updated with best choice
There is only one alternative in link group x-terminal-emulator (providing /usr/bin/x-terminal-emulator): /opt/Hyper/hyper
Nothing to configure.</pre>
What should I do next?

**Comment by chaseleinart** [comment]
@pSnehanshu  Did you try running the second command listed in omkar-dsd's most recent message?

**Comment by gurrenPizza** [comment]
Thanks! It worked on @omkar-dsd's second command, as @chaseleinart commented above. I just used the AppImage file path on the /path/to/term and solved it.

**Comment by PatricSPires** [comment]
Thanks, guy. It's worked perfectly for me on ubuntu 19.04.

**Comment by CircleOnCircles** [comment]
> Thanks, it work when I press `ctrl + alt + t` but when I click "**Open in Terminal**" at a directory, its still using the default terminal. How do I change the default to hyper?

There are 3 ways of doing it.

Recommended one is, adding this to ur ~/.bashrc file.
```bash
if ps -o cmd= -p $(ps -o ppid= -p $$) | grep -q gnome; then
  nohup hyper $(pwd) &> /dev/null &
  sleep 0.1s
  exit
fi
```
It will cause all gnome-terminal to be replace with `hyper` shell.

**Comment by mhb-machado** [comment]
Thanks dude,this is so fucking helpful!!

**Comment by princek64** [comment]
I'm getting this path error!

`update-alternatives: error: alternative path /opt/Hyper/hyper doesn't exist`

**Comment by khoulyy** [comment]
> @baborlelefan Try running to command below to add Hyper to your config. If that doesn't work, can we please see the output from the command you ran?
> 
> sudo update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /opt/Hyper/hyper 50

it worked. thank u

**Comment by gazambuja** [comment]
Hi, how I can tell Hyper that not open new terminal windows but instead open a new tab?
Expected result: First time open a Hyper terminal window, second time open a new tab and give the focus.

**Comment by dheerapat** [comment]
> Thanks, it work when I press `ctrl + alt + t` but when I click "**Open in Terminal**" at a directory, its still using the default terminal. How do I change the default to hyper?

* open your default terminal and go to setting -> preference -> profile -> command
* and then tick 'run custom command instead of my shell'
* type 'hyper .'
* select preserve working directory as always
* select exit after command

**Comment by FellahAbdel** [comment]
thank you my Dude !
