### ISSUE TITLE
Display wrong in Chinese lang version Windows 10

### ISSUE THREAD

**Issue by EliYao** [zeit/hyper#2766]
Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

Every time open Hyper will got this. 
![snipaste_2018-03-17_22-13-07](https://user-images.githubusercontent.com/7480584/37556412-7c5528d0-2a30-11e8-96ff-02e53eb4b73d.png)

And type command will got this.
![snipaste_2018-03-17_22-17-03](https://user-images.githubusercontent.com/7480584/37556540-ba6284f4-2a32-11e8-8453-7a4f722f4fa2.png)

If remove the width in class, will got corrent display. 
![snipaste_2018-03-17_22-25-37](https://user-images.githubusercontent.com/7480584/37556541-bb83fa02-2a32-11e8-88a3-bc0e2dbe577a.png)

**Comment by linonetwo** [comment]
月经
Fixed in 2.0.0

**Comment by librae8226** [comment]
just awesome @linonetwo

**Comment by gclove** [comment]
That's ok for canary version.  @EliYao

**Comment by EliYao** [comment]
Yes, I found fixed on canary version.

**Comment by ikozo4** [comment]
2.0 is....Solved?
Under the win10 I also is such
