### ISSUE TITLE
Command to install hyperterm plugins

### ISSUE THREAD

**Issue by mikeal** [zeit/hyper#277]
It's kind of clunky to install plugins, it would be great if there were just a hypterm command line to do that kinda stuff.

```
hyperterm install hypertheme
```

**Comment by mxstbr** [comment]
`hpm` by @matheuss is trying to solve that, not sure if that should be in core? https://github.com/matheuss/hpm

**Comment by matheuss** [comment]
I think it would be very cool if `hpm` came along with HyperTerm 😊 Atom, for instance, ships `apm` with the app.

**Comment by mxstbr** [comment]
@matheuss submitted a PR for that (#282), let's see what @rauchg has to say about that!

**Comment by rauchg** [comment]
I'm interested, but I'd like to understand the clunkiness more. Right now you edit a file, you save it, it hot-reloads.

**Comment by matheuss** [comment]
Well, is faster and easier to install a package with a little command 😅 When I first thought of writing `hpm`, I thought "HyperTerm needs something like [`apm`](https://github.com/atom/apm)" 

![hpm](https://cloud.githubusercontent.com/assets/4721750/16961000/02403c48-4dc2-11e6-8a83-a1412f3ef019.gif)

**Comment by booc0mtaco** [comment]
Although it can be assumed that anyone using hyperterm probably understands how to edit the file, something like `hpm` would:

- provide an external mechanism to check for package validity (or search a la `brew search`)
- make scripting a bit easier for dotfile repositories
- drastically reduce the likelihood of typos corrupting the config file entirely during (un-/re-)install

Just a few additional thoughts

**Comment by matheuss** [comment]
Just an update: now we have more commands 😊 
```
❯ hpm --help
[...]
    s, search <query>      Search for plugins on npm
    ls-remote              List plugins available on npm
    d, docs <plugin>       Open the npm page of the <plguin>
```

<img src="https://raw.githubusercontent.com/matheuss/hpm/master/screenshot.gif?v=2" width="629">

**Comment by tunnckoCore** [comment]
In anyway, nowhere in the docs or site is said how to install it. I just see `~/.hyper_plugins` folder, but how packages goes there? Should i just `npm install` the plugins globally or what?

**Comment by matheuss** [comment]
You can add nom package names to the `plugins` array on `.hyper.js` 👌

**Comment by chabou** [comment]
It is planned to ship `hpm` with Hyper

**Comment by SpaceNoodles01** [comment]
After i install a plugin, what i must do to show up what actually the plugin does?

**Comment by chabou** [comment]
v2 is shipped with `hyper` CLI tool that permits to install/uninstall plugins.

**Comment by jwulf** [comment]
Typing `hyper` in hyper just opens another terminal for me... I'm on Hyper 2.0 on Ubuntu 18.04.
