### ISSUE TITLE
Menu doesnt open on windows 

### ISSUE THREAD

**Issue by samuelleeuwenburg** [zeit/hyper#2780]
-
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

![image](https://user-images.githubusercontent.com/2111164/37761099-01c14018-2db9-11e8-9867-aef155c9f6de.png)

Steps to reproduce:

install hyper
open hyper
press `ctrl` `,`  or go to the preferences via the menu

**Comment by pevecyan** [comment]
Set default program for opening .js files to notepad or any other text/code editing software.

**Comment by rossipedia** [comment]
This definitely feels like it's a bug. We shouldn't have to change how our operating system handles .js files in order to use Hyper

**Comment by chabou** [comment]
It has been fixed in canary. If there is not any program associated with `.js` files, it opens notepad.
