### ISSUE TITLE
shellArgs would pass extra ending char with duoble quote

### ISSUE THREAD

**Issue by towertop** [zeit/hyper#2781]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home Basics 64bit
- **Hyper.app version**:  2.0.0 - Canary.14 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**:  Is Vanilla

## Issue
I'm using cmd.exe, the default one on Windows.
The shellArgs does not pass the double-quote mark well to cmd.exe. It seems result in an extra ending one as the cmd.exe complained below:

The problematic settings:
'''
  shellArgs: ['/K "C:\\Users\\Edward\\Git-cmd\\start-ssh-agent.cmd"'],
'''

The cmd.exe outputs:
'''
 '\"C:\Users\Edward\Git-cmd\start-ssh-agent.cmd\""' is not recognized as an internal or external command,operable program or batch file.
'''
It leads to any folder name with a space cannot be used here, for enclosing them with double quote mark would failed.

**Comment by chabou** [comment]
can you try to use something like:
```
shellArgs: ['/K', 'C:\Users\Edward\Git-cmd\start-ssh-agent.cmd']
```

**Comment by towertop** [comment]
@chabou This workaround cannot help the path containing blank spaces. For in Windows, it is convention to enclose them with double quote marks.

I'm new to Hyper and the React underneath which stop me from getting to the code. But I think it's probably a bug or typo.

**Comment by chabou** [comment]
I am aware of this convention and this is a convention shared by all OS.

But shellArgs is not used with string concatenation. This array is passed directly to `node-pty.spawn()` method.

When you says "This workaround cannot help". It means that you tried it without success?

**Comment by towertop** [comment]
I tried many different way to tune that option. Not sure whether I have tried your advice above and I'm not on my Windows laptop right now. I configured shellArgs as:
```
'/K C:\Users\Edward\Git-cmd\start-ssh-agent.cmd'
```
For I had moved my script out of a path with blank space. That was my workaround.

I don't need another workaround and just hope to pointer out a bug. :)

**Comment by chabou** [comment]
Please try my solution.
This is not supposed to be a workaround but the way to use `shellArgs`.
I really want to know if it works and if so, I will try to find a solution to explain to users how to use `shellArgs` correctly.

**Comment by towertop** [comment]
@chabou Yes，I just tried and that way works.

**Comment by chabou** [comment]
Thank you for your confirmation 🎉.

If you want more explanations, when you type a command, the shell (cmd, powershell, bash etc..) split your command line at spaces to extract the command to execute and make an array of remaining arguments. Then it spawns the command passing arguments array. In this case, you need to use (double) quotes or if compatible, escape this space with `\ ` to tell the shell to not split here.

In our case, we are directly specifying an array to pass to command. It means that each argument could contain spaces it will not be split. Even if it has no space it is better to have one arg for `/K` and another one for this option parameter (here, your start-ssh-agent.cmd path).

BTW, this is never a good thing to answer `This workaround cannot help`. If someone asks you to try something (especially if it comes from a project contributor/collaborator/owner), please try it before answering that it is not the right solution. For some minutes, I thought that you tried it and it didn't work. It will prevent some misunderstandings and time wasting. Thank you 🙏 

(please close this fixed issue, I can do it but this is better if it comes from original poster 😉 )

**Comment by towertop** [comment]
Thank you for your kindly explain. You're right. I just got your point till now with using shellArgs as:

```
    shellArgs: ['/K', 'C:\\Program Files (x86)\\Git\\cmd\\start-ssh-agent.cmd'],
```
I didn't need to use double quote mark here as the convention. I was attracted by that extra mark in error message.
