### ISSUE TITLE
cmd-backspace not working on MacOS

### ISSUE THREAD

**Issue by appleton** [zeit/hyper#2782]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.13.3
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/appleton/6e994dd1810bfd3cbdd1947054383d93
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
- **The issue is reproducible in vanilla Hyper.app**: ✅ 

## Issue
The command + backspace keyboard short cut doesn't do anything. From reading https://github.com/zeit/hyper/blob/canary/app/keymaps/darwin.json#L45 I expected it to clear a line of text. I confirmed with a colleague who uses Hyper and they also didn't get the expected behaviour.

I don't _think_ this is a local config issue but I guess I could be wrong? I'd be interested to hear if this works as expected for anyone?

**Comment by RichDonnellan** [comment]
I'm running the same exact setup and `cmd + backspace` **is** working fine for me; all the other combinations work as expected, too.

I peeped your gist, and noticed you have an empty `keymaps` object. Is it possible this is overwriting the default options? Although it had no effect on me, try removing that and test.

**Comment by chabou** [comment]
@appleton linked code lines concern canary release channel.
But I tried your config with stable release and it works very well 🤔

**Comment by chabou** [comment]
@RichDonnellan BTW, thanks for your help 🙏

**Comment by appleton** [comment]
> I peeped your gist, and noticed you have an empty keymaps object. Is it possible this is overwriting the default options (doubt it)? Although it had no effect on me, try removing that and test.

I've tried with and without it, I've also tried manually adding the command to my config like this:

```js
  keymaps: {
    'editor:deleteBeginningLine': 'command+backspace'
  }
```
Unfortunately no luck with any of those options.

> linked code lines concern canary release channel.
> But I tried your config with stable release and it works very well 🤔

Oh whoops. When I [look at the file on the latest stable release](https://github.com/zeit/hyper/blob/4ea9865ba54e5e51a153082f263c742fd87ae7f2/app/keymaps/darwin.json) it doesn't include the cmd-backspace mapping, though I guess it must be implemented somewhere else if it works for you.

I've also just tried swapping to the latest canary release and still no luck. I wonder if this could be something about my system setup since nobody else is having trouble? Other debugging steps I've tried:

1. Start a bash shell with no customisation at all (usually I use ZSH with a [load of customisation](https://github.com/appleton/dotfiles))
2. Start a fish shell with no customisation
3. Update to the latest ZSH

From these steps I'm pretty sure it isn't anything to do with my shell configuration at least.

**Comment by ericbiewener** [comment]
I'm also experiencing this (2.0 stable release). As an additional debugging step to what @appleton tried, I tried overwriting the shortcut with `command+shift+t` in case it was the delete/backspace key that was the problem. No dice. Happy to help debug if anyone's got steps for me to try.

**Comment by SixFingeredAmish** [comment]
Having the same issues.

**Comment by SixFingeredAmish** [comment]
@appleton I couldn’t get Hyper to work either but you can use Zsh keybinds.

Just put this in your .zshrc:
```
# Delete line with cmd-backspace
bindkey '^[w' backward-kill-line
```

**Comment by b0xw00d** [comment]
same issue here

**Comment by RichDonnellan** [comment]
**Update:** I'm configuring a new machine and *did* reproduce this issue. Seems it does nothing with the standard bash shell. I was only able to remedy after installing and setting ZSH as my primary.

@SixFingeredAmish: adding your keybindings to the `.zshrc` had no effect.

**Comment by SixFingeredAmish** [comment]
@RichDonnellan That's weird. It works for me.

**Comment by RichDonnellan** [comment]
> @RichDonnellan That's weird. It works for me.

If you remove that line, will it still work (provided ZSH is your primary)? It did for me. I didn't, however, try using it in a `.bash_profile` when `bash` was set to default.

**Comment by rohmanhm** [comment]
I'm using `fish` and the cmd+delete not working with it.

**Comment by decomoraes** [comment]
Install Oh My Zsh:

https://github.com/ohmyzsh/ohmyzsh

**Comment by gitmaeker** [comment]
> Install Oh My Zsh:
> 
> https://github.com/ohmyzsh/ohmyzsh

Cheers, quickest way to sort this out

**Comment by pantajoe** [comment]
I have the same issue with `fish` on MacOS (`zsh` and `bash` tested briefly as well and it also does not work). I tried testing it on a clean MacOS, and the issue still persists (even without hyper plugins). This is what happens:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/31014018/168438213-9fb6594e-bd93-44e6-ad99-af010cc793f7.png">

Apparently, `cmd+backspace` triggers fish to display the description of the binary that's present and `nothing appropriate` if there is no valid command in the line that is to be deleted.

The rest of the key commands work fine though and I cannot put my finger on it what could be the issue.
Has any one the same issue still with the latest hyper release?

**Comment by pantajoe** [comment]
Apparently, when using a fish shell `cmd+backspace` is the key sequence `\ew`.
And somehow in Hyper when using `\ew`, it triggers the binary `apropos`.

What helps is resetting the `\ew` to the `backward-kill-line` by adding this to your key bindings in `~/.config/fish/functions/fish_user_key_bindings.fish`:

```fish
bind \ew backward-kill-line
```

After opening a new terminal pane, `cmd+backspace` works as expected 🥳

Leaving this here for other users with the same issue in Hyper + Fish.
