### ISSUE TITLE
Is there a working CLI for hyper (for installing plugins)?

### ISSUE THREAD

**Issue by Etregoning** [zeit/hyper#2784]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13.3
- **Hyper.app version**: 1.4.8
- **Link for [My Gist](https://gist.github.com/Etregoning/d6232aac38fa4190ea302a422b4d3951)**

## Issue
I have been looking through the `awesome-hyper` repo, and I wanted to use the hpm-cli package to install plugins. When I visited the npm page for hpm-cli, it says it has been deprecated in favor of hyper's built-in cli. How do I access this cli? There doesn't seem to be any info about this on the main hyper website or in the issues section here.

Is editing `~/.hyper.js` currently the preferred method for installing plugins? Thanks.

**Comment by chabou** [comment]
In our upcoming v2, a `hyper` command will be automatically installed:
```
❯ hyper --help

  Usage: hyper [options] [command]
  
  Commands:
  
    <default>                    Launch Hyper
    d, docs, h, home             Open the npm page of a plugin
    help                         Display help
    i, install                   Install a plugin
    ls, list                     List installed plugins
    lsr, list-remote, ls-remote  List plugins available on npm
    s, search                    Search for plugins on npm
    u, uninstall, rm, remove     Uninstall a plugin
  
  Options:
  
    -h, --help     Output usage information
    -v, --verbose  Verbose mode (disabled by default)
```

**Comment by Etregoning** [comment]
Cool, is it waiting for v2 or will it be on the canary branch before That? Thanks!

**Comment by chabou** [comment]
This is already available on canary update channel :)

**Comment by Etregoning** [comment]
Thanks! I will switch branches then.

**Comment by albinekb** [comment]
Try if it's working without `zsh` (use `bash`), then we can rule out that.

**Comment by Etregoning** [comment]
Nope, even in bash it tells me command not found.

**Comment by chabou** [comment]
Please check your `hyper` version. After setting updates help to canary you have to wait that new version has been downloaded

**Comment by seffyroff** [comment]
I have this issue also - I'm updated to Canary 2.0 (verified in the About box)
`Hyper 2.0.0-canary.15 (canary)
`
Tried running 'hyper --help' from cmd.exe, powershell, wsl.exe, bash.exe and it's not found.

**Comment by chabou** [comment]
https://github.com/zeit/hyper/pull/2342#issuecomment-337761260

On Windows, you need to validate your user env var or reboot your computer 😓

**Comment by seffyroff** [comment]
> @chabou On Windows, you need to validate your user env var or reboot your computer 😓

Rebooted (I had one in the pipe anyway) and it works properly now, thanks!

**Comment by chabou** [comment]
@Etregoning It seems that you have set the right update channel (v1.4.8) but no update has been installed. You need to wait for a little to have this update downloaded and a notification that asks you to restart to install it.

**Comment by Etregoning** [comment]
It has been almost 2 weeks now, how long will it take for this update to install? Is there any way to just uninstall hyper, and install a fresh working version straight from the canary branch?

**Comment by chabou** [comment]
I would have liked to understand why the update has not been installed.
But nevermind, you can install our last canary directly from our release page: https://github.com/zeit/hyper/releases/

No need to uninstall before installing it

**Comment by Etregoning** [comment]
Thank you. I'd be happy to help you with any sort of diagnostics, but you're going to need to tell me where/how to find them!

I will close this issue now, as directly installing hyper solved my problem. Thanks!
