### ISSUE TITLE
Canary.15 broke Hyper with plugins

### ISSUE THREAD

**Issue by danieldunderfelt** [zeit/hyper#2788]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra, 10.13.3
- **Hyper.app version**: 2.0.0 canary.15
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/danieldunderfelt/1334ba3fa66987fff6709ed9e46dbe5a
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: No, Hyper-snazzy and hyper-border installed.

## Issue
I just got an update notification that Canary.15 was available and restarted the app to update. But now the app doesn't work at all, all I see is the red/yellow/green window management buttons. I cannot type anything in the terminal and I can't even grab the top to move it. AFAIK none of the plugins work either.

I will try reinstalling and disabling the plugins to see if it fixes it, but I assume these are the kinds of things in the canary you want to know about!

Thanks!

**Comment by danieldunderfelt** [comment]
Update: Disabling the plugins made Hyper work again, so I've updated the issue title to reflect this. In short, canary.15 is not compatible with plugins, at least mot Hyper-snazzy or Hyperborder.

**Comment by chabou** [comment]
@danieldunderfelt Thank you for your feedback. Our last canary is broken by `hyperborder`.

**Comment by chabou** [comment]
https://github.com/webmatze/hyperborder/issues/43

**Comment by danieldunderfelt** [comment]
I didn't get an error in the console, but yeah, seems like Hyperborder is the culprit.

Thanks! 👍

**Comment by alexjmoore** [comment]
Hyperborder is definitely the culprit - however could Hyper itself handle this kind of issue more gracefully? I didn't get any visible error.

**Comment by artulito** [comment]
First time user here. I tried canary-15 with hyper-cat, hyperpower, hyperline, but nothing worked.

**Comment by danieldunderfelt** [comment]
I'm using it with only the hyper-snazzy theme now and it works. Hyperline has not worked for me at all in v2.

**Comment by chabou** [comment]
`hyper-cat` is totally broken because it used some `hterm` internals
`hyperpower` is broken but I made a PR to make it compatible: https://github.com/zeit/hyper-power/pull/52
`hyperline` is broken and I made some research to understand why: https://github.com/Hyperline/hyperline/issues/150#issuecomment-375955160

I have no idea yet why Hyperborder is broken. We made a lot of effort to detect broken plugins in v2: https://github.com/zeit/hyper/commit/9bd410f1e4e17d547783164f37d76dca2ff60b11

But this is pretty hard to anticipate all problems that plugins can encounter.

**Comment by webmatze** [comment]
The problem with **hyperborder** should be fixed with the latest version 1.0.1 of the plugin.

**Comment by Stanzilla** [comment]
Go update your plugins, everyone. If there is no update, disable for the time being. We are working towards a better solution in https://github.com/zeit/hyper/issues/2633
