### ISSUE TITLE
CLI: Use dev config file

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2789]
When Hyper is in dev mode, local config file has precedence: https://github.com/zeit/hyper/blob/e181e1eb8d5b3044a99a1add728c5bca8b5a14c3/app/config/paths.js#L18-L29

It permits to develop on Hyper without breaking regular one.

It would be great to do something similar for CLI here: https://github.com/zeit/hyper/blob/e181e1eb8d5b3044a99a1add728c5bca8b5a14c3/cli/api.js#L8

Not conditioned to `electron-is-dev`, but maybe to `process.env.NODE_ENV` value or something like that.

**Comment by chabou** [comment]
It would make other PRs, like #2756, easier to develop.

**Comment by tool3** [comment]
i'd like to have a go at this 🙏

**Comment by tool3** [comment]
Opened PR #2792 to address this 😊

**Comment by chabou** [comment]
Fixed by #2792
