### ISSUE TITLE
How do I set the default directory with Windows 10?

### ISSUE THREAD

**Issue by Khaleel** [zeit/hyper#2794]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10.0.16299.309
- **Hyper.app version**: 1.4.8 stable

## Issue

I am using Windows 10.
I want Hyper to open in "D:\Users\kmug7\Dropbox\Dropbox\WEBX\www"

Whenever I start it. I tried editing the preferences. Before it was:

`shellArgs: ['--login'],`

Now it is:

`shellArgs: ['D:\Users\kmug7\Dropbox\Dropbox\WEBX\www'],`

I also tried:

`shellArgs: ['D:\Users\kmug7\Dropbox\Dropbox\WEBX\www', '--login'],`

**Comment by moso** [comment]
Windows needs double-backslashes for some reason.

`D:\\Users\\[...]`

**Comment by Khaleel** [comment]
It still is not working. This my code:
It still is not working. This my code:
It still is not working. This my code:
This is my code. It still is not working?

```

// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // Choose either "stable" for receiving highly polished,
    // or "canary" for less polished but more frequent updates
    updateChannel: 'stable',

    // default font size in pixels for all tabs
    fontSize: 16,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    //
    // Windows
    // - Make sure to use a full path if the binary name doesn't work
    // - Remove `--login` in shellArgs
    //
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
    //
    // Powershell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['D:\\Users\\kmug7\\Dropbox\\Dropbox\\WEBX\\www', '--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [`hyperpower`],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: [],

  keymaps: {
    // Example
    // 'window:devtools': 'cmd+alt+o',
  }
};

```

**Comment by tool3** [comment]
@Khaleel the path you provided in your `.hyper.js` is not a path to bash.exe.

You should set the `shell` prop to your bash.exe, and leave `shellArgs` as `--login` (unless you have other shell args)

If you want to open the terminal in a particular folder then you can use a `.bash_profile` file in your home directory and simply type in the command to `cd` to your desired folder.

Mind you, that every bash/tab you open will start on that folder.

**Comment by chabou** [comment]
@Khaleel Which shell do you want to use? `cmd`? In this case I think taht you should use `/K <cmd>' option:
```
  ...
  shellArgs: ['/K', 'cd /d D:\\Users\\kmug7\\Dropbox\\Dropbox\\WEBX\\www'],
  ...
```

(https://stackoverflow.com/a/60907)

**Comment by Khaleel** [comment]
Thanks for reply dude. Obviously I want to use Hyper and not cmd :)

Khaleel Mughal

**Comment by Khaleel** [comment]
Great it worked! Thanks for putting the reference with the explanation too

**Comment by maracuja-juice** [comment]
I changed the shell to powershell, how can I set the default directory with that?

I tried: 
`'-command "cd C:\\MyPath"`
`'-command "Set-Location C:\\MyPath"`
and of these also without the `""`

**Comment by TimoSta** [comment]
@maracuja-juice I did get this to work for PowerShell with the following configuration:

```js
shellArgs: ['-noexit', '-command', 'Set-Location C:\\projects'],
```

This will launch a PowerShell instance and navigate to `C:\projects`.

**Comment by Suhail** [comment]
How would you do this with git-bash as the default shell?

**Comment by whyboris** [comment]
@Suhail -- alternative solution:
After `git-bash` starts you'll likely be in your home directory (same as `cd ~`)
There, look if you have a `.bashrc` file (do `ls -la`). If not present, create it, otherwise add a new line at the end of the file: `cd ../../Code` (the path to wherever you'd like to start) 😅

**Comment by ThisNameNotUsed** [comment]
I can't start in a different directory at all in CMD / Hyper. I have read all the links and tried these commands out in regular cmd where they work fine.

`shell: '',`
and
`shellArgs: ['/K', 'cd /d C:\\Users\\OPS\\source'],`

**Comment by juanmrodri** [comment]
> @Suhail -- alternative solution:
> After `git-bash` starts you'll likely be in your home directory (same as `cd ~`)
> There, look if you have a `.bashrc` file (do `ls -la`). If not present, create it, otherwise add a new line at the end of the file: `cd ../../Code` (the path to wherever you'd like to start) 😅

Hi!
is it the same to enter to de file by typing "nano ~/.bashrc"?, i mean, its the same file, in case it doesn´t apear there

**Comment by staniel359** [comment]
```js
{
  config: {
    workingDirectory: 'D:\\'
  }
}
```
