### ISSUE TITLE
hyper 1.4.8.exe won't open on windows 10 

### ISSUE THREAD

**Issue by jtcarrasco** [zeit/hyper#2798]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  windows 10 / mac high sierra
- **Hyper.app version**: 1.4.8

## Issue
hyper 1.4.8 
windows 10 

initial install of hyper launched i changed the background color in the hyper.js.  app then wouldn't open.  i did a clean uninstall of the app reloaded it and now app still won't open is this a known issue?  also experiencing this on mac osx.  this is a bare install no plugins added as of yet.

**Comment by yogeshkotadiya** [comment]
just revert your changes in your hyper config file.
Or if that doesn't work then simply delete your config file and relaunch hyper.
config file location Win10 C:\Users\{Current User}\

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
