### ISSUE TITLE
Create options around scrollback buffer

### ISSUE THREAD

**Issue by chiefy** [zeit/hyper#280]
Easy way to crash Hyperterm:

```
find /
```

Since there's unlimited scrollback buffer, memory just keeps getting eaten especially if you're tailing logs or catting large logfiles. It would probably solve the issue if there was an option to limit scrollback (check out iTerm2's options around this)

**Comment by rgl** [comment]
This is a hterm issue that is described at https://crbug.com/220406.

**Comment by ppot** [comment]
I would need to play with this. How far in the scroll back Iterm2's handle ? @chiefy

**Comment by chiefy** [comment]
@ppot iTerm's scrollback buffer is configurable by numbers of lines or "unlimited"

**Comment by cavaliercoder** [comment]
It would also be useful to disable the buffer entirely (as I do in OS X Terminal), so I can use tmux instead for scrollback.

**Comment by chabou** [comment]
@cavaliercoder maybe [hyperterm-alternatescroll](https://github.com/lkzhao/hyperterm-alternatescroll) can help ?

**Comment by rickarubio** [comment]
Is there any way to set the scrollback buffer size / scrollback lines in hyper ? I am running into an issue with hyper 2.0.4 where I can only scroll a few hundred lines at most, but I would really like to be able to scroll back through my terminal output much further than this.

**Comment by AuHau** [comment]
Is there any update on this? The current size of scrollback buffer is not really sufficient...

**Comment by chabou** [comment]
We need to use `xtermjs` `scrollback` option: https://github.com/xtermjs/xterm.js/blob/a3ce881897818d1c61476620e7d037717ca9a68f/src/Terminal.ts#L113

Pretty easy to implement and very useful.

**Comment by chhschou** [comment]
Closed #3056 as #3038 already exists and pending review by @chabou.

**Comment by chhschou** [comment]
This can close, #3038 has been merged.

**Comment by albinekb** [comment]
Thanks for the help @chhschou 🎉

**Comment by jorisw** [comment]
So? What is the option and what kind of values does it take?

**Comment by albinekb** [comment]
@jorisw  It's documented here: https://hyper.is/#cfg
![image](https://user-images.githubusercontent.com/5027156/45495131-eae79380-b772-11e8-8ffd-8cbd7f66fe08.png)

**Comment by sobolevn** [comment]
Is it possible to disable it completely? `Terminal.app` has this mode called "as much as my memory allows".

And I am quite used to it. So, setting any kind of `scrollback` numbers is not the same.

**Comment by kenorb** [comment]
Shouldn't it load from `HISTSIZE` environmental variable as all terminals?

**Comment by jcrben** [comment]
"The value of the HISTSIZE shell variable is used as the number of commands to save in a history list" - https://www.gnu.org/software/bash/manual/html_node/Bash-History-Facilities.html

Seems like that's more your prior shell commands, which is different from the number of rows of output in a terminal.

**Comment by Jason-2020** [comment]
So how to have unlimited scroll?
`scrollback: 0, -1`, or ..?

**Comment by seth100** [comment]
> So how to have unlimited scroll?
> `scrollback: 0, -1`, or ..?

I'm interested in that too! Any feedback please?
Thanks

**Comment by darkguy2008** [comment]
Same here, any way to have it unlimited?

**Comment by skagedal** [comment]
To those here requesting an unlimited option, the config is a Javascript file so you can write:

```
scrollback: Infinity
```
