### ISSUE TITLE
Fresh installation of Hyper does not startup

### ISSUE THREAD

**Issue by rey-allan** [zeit/hyper#2800]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Sierra Version 10.12.6
- **Hyper.app version**: 1.4.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: `.hyper.js` file is the default from a fresh installation.
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Reproducible with vanilla Hyper.app

## Issue

I just installed Hyper for the first time in my Mac, and it won't even start. Opening the app fails with "Syntax Error"; however, the `.hyper.js` file is the default unaltered one.

**Comment by dimitrieh** [comment]
I had a similar problem

![image](https://user-images.githubusercontent.com/429659/39115100-1738f152-46e1-11e8-86fd-61b873fa756e.png)


I had to remove all old/outdated hyper references in my home folder

**Comment by Stanzilla** [comment]
@dimitrieh do you, by chance, have a copy of your hyper.js file from before you upgraded?

**Comment by dimitrieh** [comment]
@Stanzilla I am afraid not anymore.

To be honest, I think i had a `ln -s` softlinked hyper.js file, for which the original I had already deleted 🤔 

Could that be the cause?

**Comment by Stanzilla** [comment]
Well maybe, did you have any plugins listed in that hyper.js file? And was it really a fresh install if you already had a config file before?

**Comment by dimitrieh** [comment]
@Stanzilla 

>  did you have any plugins listed in that hyper.js file?

Almost certain that I did. This was my last hyper file to my knowledge: https://gitlab.com/dimitrieh/dotfiles/commit/413baa274a86b91c523954aee85d50e94ea85055

>  And was it really a fresh install if you already had a config file before?

it was except for the lingering config files...

**Comment by Stanzilla** [comment]
@dimitrieh Ah! Now it starts making more sense, you had some old plugins that are no longer compatible with Hyper v2 and that is why it died on you.

**Comment by dimitrieh** [comment]
It would be nice if there was some alternative messaging in stead of straight up dying 😉

**Comment by Stanzilla** [comment]
Agree :)
