### ISSUE TITLE
Git Bash Clear not working correctly

### ISSUE THREAD

**Issue by ConeyLiu** [zeit/hyper#2801]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **Latest downed form the offical site**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

The git bash not working correctly. After I called `clear`, it just moves the cursor to the top but it does not clear the screen. See as follow:
<img width="866" alt="capture" src="https://user-images.githubusercontent.com/12733256/38227928-391b2780-3733-11e8-8329-e69ab57234a5.PNG">

**Comment by tool3** [comment]
@ConeyLiu the link to the Gist is broken, but I faced the same issue on Windows. 

In your `.hyper.js`  - you should add the `TERM` key with the value `CYGWIN` 
 to the `env` property like so:
```
env: {
  TERM: "cygwin"
}
```

**Comment by ConeyLiu** [comment]
Hi @tool3 , thanks for the help. It works for me.
