### ISSUE TITLE
Agnoster theme in ZSH is not rendering properly in Hyper

### ISSUE THREAD

**Issue by pandaa880** [zeit/hyper#2803]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 16.04 LTS**: 
- **1.4.8**:

**Comment by albinekb** [comment]
Hi, there seems to be an issue with your issue. Please fill in the issue template and provide steps to reproduce 👍
