### ISSUE TITLE
Add a way for plugins to show deprecation to users

### ISSUE THREAD

**Issue by timothyis** [zeit/hyper#2807]
## Enhancement
I was speaking to @wesbos about their theme name `hyperterm-cobalt2-theme` and if they could rename to `hyper-cobalt2-theme` since `hyperterm` hasn't been in use for a long time now. The issue was that there is no way that themes or plugins can notify users, that use the theme or plugin, that the package is deprecated and that a new version under a new name is available (or the package isn't available at all).

A great way to theoretically do this is to provide an in-app notification telling the user that the plugin/theme is deprecated with a link to the npm package with the extended message of why.
Of course, this notification should be dismiss-able, so we might want a way to more permanently display the deprecation somewhere (or disable it upon deprecation).

**Comment by chabou** [comment]
`notify` function is already passed to each decorator.
https://hyper.is/#decorating-components

Is it enough?
