### ISSUE TITLE
Disable auto reload of ~/.hyperterm.js

### ISSUE THREAD

**Issue by matheuss** [zeit/hyper#281]
I'm writing tests for [hpm](https://github.com/matheuss/hpm) and I need to – at least temporarily – disable the auto reload of ~/.hyperterm.js. There is any way to do this?

**Comment by CodeTheory** [comment]
@matheuss Is this still a valid question?

**Comment by chabou** [comment]
@matheuss I think it is still relevant. How do you imagine this? param in config?

**Comment by melMass** [comment]
Especially that it close any running sessions... quite dangerous function

**Comment by MartyGentillon** [comment]
https://github.com/zeit/hyper/pull/1509 doesn't fix this, but anyone who wants to work on this should look at it.

**Comment by ppot** [comment]
@chabou @albinekb Still active.

**Comment by albinekb** [comment]
I'd say either add a config option, after that is set, don't hot reload. Only show a notification "config changed, click here to update". PR welcome?

**Comment by chabou** [comment]
hyper CLI tool works without this because Hyper is waiting some time before reading config after a change event.
