### ISSUE TITLE
deja vu sans hides underscore 

### ISSUE THREAD

**Issue by yoyoys** [zeit/hyper#2812]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- **OS version and name**: ubuntu 17.10
- **Hyper.app version**: 2.0.0-canary.15
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/yoyoys/a0d4dee0cabc82c4ac559ff35b934ab5
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A 
- **The issue is reproducible in vanilla Hyper.app**: Vanilla

## Issue
`deja vu sans mono` is my favorite font for monospace.
and i prefer 14px for console, but the underscore will gone

Here's the screenshots

### 16px
![image](https://user-images.githubusercontent.com/22124891/38420612-f4b4de50-39d6-11e8-98db-07a5dd431837.png)
### 14px
![image](https://user-images.githubusercontent.com/22124891/38420645-05ec4622-39d7-11e8-9d3c-b3841b90c7eb.png)

### build-in terminal 14px
![image](https://user-images.githubusercontent.com/22124891/38420674-20bdaff4-39d7-11e8-93a4-fad881f81aa9.png)

**Comment by chabou** [comment]
I can't reproduce on macOS.
@yoyoys Can you try to reproduce with a vanilla bash?

**Comment by yoyoys** [comment]
thanks.
here is the screenshot

![image](https://user-images.githubusercontent.com/22124891/38427282-64882d9a-39eb-11e8-8a39-d902bc26c092.png)

**Comment by yoyoys** [comment]
it's funny, but i can see underscore in 12px
## 12px
![image](https://user-images.githubusercontent.com/22124891/38427587-3abe4566-39ec-11e8-8944-25d497e8ddc6.png)

**Comment by yogeshkotadiya** [comment]
Can confirm this

- **OS** : Ubuntu 18.04 
- **Hyper** : Hyper 2.0.0 Canary-16

Font Family : DejaVu Sans Mono
Font Size : 14

Default Config
No plugins

![untitled](https://user-images.githubusercontent.com/9676379/38433569-0797bff8-39e9-11e8-9127-c1733ed5dda2.png)

On Windows 10 No Issues ✔️

**Comment by lanthaler** [comment]
I have the same issue on Debian

**Comment by chepner** [comment]
This just became an issue for me today after upgrading to 3.2.0beta3 (sorry, I don't recall which version I upgraded *from*). It's possibly an antialiasing issue, though. Underscores are a nearly invisible gray line with DejaVu sans Mono for Powerline at 10 points. At other sizes (notably, 9 and 11 points), it's a thin but distinct black line. It's also not an issue for DejaVu sans Mono at 10 points (or any other size).

**Comment by hamboomger** [comment]
Found temporary solution(at least works for me): set `fontSize: 13.5`. This way real font size is still 14, but somehow it begins to show underscores.

**Comment by summershrimp** [comment]
not fixed at 2.1 stable

**Comment by summershrimp** [comment]
> Can confirm this
> 
> * **OS** : Ubuntu 18.04
> * **Hyper** : Hyper 2.0.0 Canary-16
> 
> Font Family : DejaVu Sans Mono
> Font Size : 14
> 
> Default Config
> No plugins
> 
> ![untitled](https://user-images.githubusercontent.com/9676379/38433569-0797bff8-39e9-11e8-9127-c1733ed5dda2.png)
> 
> On Windows 10 No Issues 
> 
> **EDIT**
> 
> I have the same issue in VSCode so it seems like it's an Xterm issue
> Changing **"window.zoomlevel" : -0.001** fixed the issue in VSC
> 
> Adding the property like that into hyper config for window zoom will fix this issue.

How to change zoomelevel in hyper.sh?

**Comment by irfanfadilah** [comment]
I can confirm this bug too.

- Ubuntu 14.04
- Font Size 14px

**Comment by mindware** [comment]
I can reproduce on: 
Hyper version 2.1.2 
On Ubuntu 18.04.2 LTS

I simply use CTRL + and there is a zoom level in which the _ is invisible.

**Comment by eddo888** [comment]
on a mac with Deja vu sans mono at 10, the underscore reveals itself if you down/up arrow in the middle of typing (bash complete ish).
To fix the issue I selected "bold" and the underscore appears as typed. 
Weird to say the least.

**Comment by Stanzilla** [comment]
Can you try with a CI build of current canary or maybe compile one yourself?

**Comment by kulaj** [comment]
this still happens, Hyper 3.0.2, Ubuntu 19.10. Deja vu sans should be removed as a fall-back. Undescroes render properly when it is taken out

**Comment by jocull** [comment]
> this still happens, Hyper 3.0.2, Ubuntu 19.10. Deja vu sans should be removed as a fall-back. Undescroes render properly when it is taken out

If it is falling back, what font is it falling back to?

**Comment by bduffany** [comment]
Can confirm that this is still an issue on Hyper version 3.0.2, Ubuntu 20.04. For me, it's only an issue with 12px font size.
