### ISSUE TITLE
Clear command issue

### ISSUE THREAD

**Issue by ricbuz94** [zeit/hyper#2813]
Hi, i've noticed that if i write my things and then type the 'clear' command to clean the terminal, all 
        the prev text remains in backgroud, covering all. To reproduce the issue write something in the 
        command line as a usual(anything). After writing some lines type 'clear'. I don't know if that matters but i use the 
        material theme. Thanks for reading it :)

        -
        Hyper 1.4.8
        Electron 1.7.8
        win32 x64 10.0.16299

**Comment by nurikabe** [comment]
Try setting `env: { TERM: 'cygwin' }`

See https://github.com/zeit/hyper/issues/2715

**Comment by albinekb** [comment]
Please try 2.0.0, it's a lot better 👍

**Comment by monsterkodi** [comment]
This issue is still present in version 2.0.0 on windows.

**Comment by Broadroad** [comment]
@monsterkodi  You can replace this into ~/.hyper.js.          env: { TERM: 'cygwin' }. In windows 10, version 2.0.0, I can fix this problem. Need to restart hyper.

**Comment by albinekb** [comment]
Did that solve it for you or should we reopen? @monsterkodi 🙏
