### ISSUE TITLE
xport: command not found

### ISSUE THREAD

**Issue by marcus-sa** [zeit/hyper#2815]
- 🗹 I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- 🗹 I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 17.10 
- **Hyper.app version**:  Latest
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/marcus-sa/55c30f3dfa13f1f45886da3732676af2
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: ☒

## Issue
All of sudden after restarting my PC, when I open up **Hyper** this error occurres:
`Export: command not found` 

If I open up the native terminal it works fine.

**Comment by chabou** [comment]
I would have thought that you have some `Export` command instead of `export` in your .bashrc/.zshrc... But I can't figure out why it works with native terminal. 😞

**Comment by marcus-sa** [comment]
Unsure whether or not it is `Export` or `export` as it only showed `xport` so I assumed it was either one of them.

**Comment by marcus-sa** [comment]
`xport: command not found`

**Comment by chabou** [comment]
ok, please verify your rc files (`.bashrc`, `.profile`...). I think that you have a typo

**Comment by wiliamtaesunglee** [comment]
i had the same issue and was the .profile were i find the typo
