### ISSUE TITLE
Path environment var are renamed every opening of Hyper.js

### ISSUE THREAD

**Issue by sebastienschoepfer** [zeit/hyper#2817]
- **OS version and name**: Windows 10 Professionnel 1709
- **Hyper.app version**: Hyper 2.0.0-canary.16 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/sebastienschoepfer/cae0cc68f8dcd29add814c81d86df279
- **Terminal inside Hyper**: Powershell 5.1.16299.251

## Issue
Hi all,

I'm facing a strange issue with Hyper. Everytime I open it, it renames my *PATH* environment variable and break all the char with an accent. Here is an example : 

`C:\Users\Sébastien\AppData\Roaming\npm`

become

`C:\Users\S?bastien\AppData\Local\Yarn\bin`

How can I solve it ? 

Thanks in advance for you help.

**Comment by chabou** [comment]
@sebastienschoepfer We're tracking this work over here (with workaround explained): #607
There is an outdated PR here: #605

**Comment by sebastienschoepfer** [comment]
@chabou Thanks you, the workaround provided on these posts are not possible for me as I'm using __PowerShell__.
