### ISSUE TITLE
It's not working after update to version 2

### ISSUE THREAD

**Issue by jdmgarcia** [zeit/hyper#2826]
- [x] Your Hyper.app version is **2.0.0**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "2.0.0"

 - **OS ARCH VERSION:** darwin x64 17.4.0
 - **Electron:** 1.8.4  **LANG:** undefined
 - **SHELL:** /usr/local/bin/zsh   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "#6BC6F9",
  "cursorShape": "UNDERLINE",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false
}

          {
  "plugins": [
    "hyper-snazzy",
    "hyperborder",
    "hyper-blink",
    "gitrocket",
    "hyper-confirm"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by jdmgarcia** [comment]
@ppamorim  it was exactly this plugin, yes!

**Comment by jdmgarcia** [comment]
Yes, I hope so. Thanks for your answers. I close this issue.

**Comment by Xapphire13** [comment]
@chabou, I'm trying to debug why Hyperborder no longer works. Is there a plugin migration guide? Judging by the info on http://hyper.is, the plugin should still work.

When debugging into the Hyperborder code, I see that [decorateConfig(config)](https://github.com/webmatze/hyperborder/blob/3813dd7b6075fe5616823558635636e1ca7e5085/index.js#L35) is now never called by Hyper. Is this an expected API change? That's where the crux of the Hyperborder logic lives.

**Comment by chabou** [comment]
I am pretty sure than `decorateConfig` is working. Most of the themes are using this to set their colors.

There are some good recipes here: https://github.com/zeit/hyper/blob/canary/PLUGINS.md

From what I saw, your css is broken.
