### ISSUE TITLE
Hey the latest update broke the Star-Wars theme.

### ISSUE THREAD

**Issue by vikramsinghal** [zeit/hyper#2828]
- [ ] Your Hyper.app version is **2.0.0**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "2.0.0"

 - **OS ARCH VERSION:** darwin x64 17.5.0
 - **Electron:** 1.8.4  **LANG:** undefined
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "StarWarsTheme": {
    "character": "random",
    "lightsaber": "true",
    "unibody": "false",
    "avatar": "true"
  },
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [
    "hyper-star-wars"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by Darper** [comment]
:+1:

**Comment by vikramsinghal** [comment]
Ran this command (hyper i verminal) and it fixed the issue! :)

**Comment by timothyis** [comment]
Thanks for the issue. If a plugin breaks due to an update of Hyper, the plugin should update to accommodate it, unfortunately. The latest update to Hyper was a big one with many breaking changes and we couldn't avoid some issues with plugins and themes.
