### ISSUE TITLE
Font size value is ignored

### ISSUE THREAD

**Issue by VladimirDev93** [zeit/hyper#2831]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 18.3 64-bit
- **Hyper.app version**: 2.0.0 (Stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist link](https://gist.github.com/VladimirDev93/4a8178066a1052b4ead110a0f0b00440)

## Issue

After navigating to `Hamburger Menu > Edit > Preferences`, and when I edit the `.hyper.js` file and try to define a new custom value for `fontSize`, I save the file and after reloading the terminal, the font size is still the same.

**Comment by levity** [comment]
It may be related to a theme plugin. I noticed that I couldn't change font size or font family, but it started working correctly after I uninstalled the `verminal` theme.

**Comment by albinekb** [comment]
Please open this over at verminal theme repo. https://github.com/defringe/verminal/blob/master/index.js#L18-L21

These lines shows that it will overwrite your fontSize with `12` if you don't set verminal.fontSize

**Comment by VladimirDev93** [comment]
I don't need to open a new issue on that repo because there is a usage guide in the documentation.
https://github.com/defringe/verminal#%EF%B8%8F-configure

Thanks for giving me the link to the repo.

**Comment by levity** [comment]
Thank you @albinekb!
