### ISSUE TITLE
WinPTY agent fails to launch on Windows 7

### ISSUE THREAD

**Issue by codehearts** [zeit/hyper#2832]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7 SP1 64bit
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/codehearts/401f8857f1f817052b187cb119875e32
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Since updating to 2.0.0 Hyper throws an error at startup. When I hit OK on the popup, the window appears but there's no text entry since there's no terminal. I've done this using cygwin bash and powershell as my shell, neither works.

```
Uncaught exception:
Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232
    at new WindowsPtyAgent
...
```

The call stack seems to be `WindowsPtyAgent`<-`WindowsTerminal`<-`spawn`<-`Session`<-`initSession`<-`Server.Window.rpc.on.options`<-`emitOne`<-`Server.emit`<-`Server.ipcListener`<-`emitTwo`. This was working on earlier canaries, I see something changed with winpty so I suspect that's what did it.

**Comment by chabou** [comment]
Do you remember the last canary that works?

**Comment by codehearts** [comment]
I think it was canary 8 or 9, sometime way back

**Comment by codehearts** [comment]
I just verified that canary 8 works for me, but canary 9 throws an unrelated error before throwing the one I've reported here

**Comment by corydeppen** [comment]
Just ran into this on Win10 using the new v2.

**Comment by chabou** [comment]
@corydeppen Is it reproducible each time?

**Comment by corydeppen** [comment]
Yes, it hasn't launched without error yet. I've included the full error and link to my .hyper.js file. I'm also wondering if it may be related to #2865.

```bash
Error: Error launching WinPTY agent: Security check failed: pipe client pid (6944) does not match agent pid (283536)
    at new WindowsPtyAgent (C:\Users\[username]\AppData\Local\hyper\app-2.0.0\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\[username]\AppData\Local\hyper\app-2.0.0\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:45:24)
    at spawn (C:\Users\[username]\AppData\Local\hyper\app-2.0.0\resources\app.asar\node_modules\node-pty\lib\index.js:27:12)
    at Session (C:\Users\[username]\AppData\Local\hyper\app-2.0.0\resources\app.asar\session.js:53:18)
    at initSession (C:\Users\[username]\AppData\Local\hyper\app-2.0.0\resources\app.asar\ui\window.js:102:24)
    at Server.Window.rpc.on.options (C:\Users\[username]\AppData\Local\hyper\app-2.0.0\resources\app.asar\ui\window.js:105:7)
    at emitOne (events.js:115:13)
    at Server.emit (events.js:210:7)
    at Server.ipcListener (C:\Users\[username]\AppData\Local\hyper\app-2.0.0\resources\app.asar\rpc.js:33:11)
    at emitTwo (events.js:125:13)
```

https://gist.github.com/corydeppen/65735150ddc5e869b84555ce4d7548b8

**Comment by UniqueUsr** [comment]
I'm running into the exact same problem as Cory on win10x64 1709.  I can re-install 1.48 and work fine for a day but as soon as it upgrades to 2.0.0 it breaks.  No plugins installed.  Installing clean from 2.0.0 also results in the same error.

**Comment by DavidRHulme** [comment]
I've just experienced this issue on Windows 10 when installing Hyper for the first time.

**Comment by gmarinella9** [comment]
I have the same issue but on Windows 10

**Comment by gmarinella9** [comment]
I solved instilling with choco

**Comment by codehearts** [comment]
So this is odd, but I tried 2.0.0 stable yesterday and this error was no longer an issue. Then it came back after rebooting today, and of course I'm clueless as to what I did that could've caused it.

**Comment by idike** [comment]
![javascripterror_hyper](https://user-images.githubusercontent.com/13204029/42356820-6fa56ba4-8089-11e8-9b6d-6c6497ae057e.PNG)


Windows 10 version 1709

**Comment by kenorb** [comment]
Same here on Windows 10,

Normally Hyper terminal works, but it breaks with above error when you run it as _Administrator_.

![image](https://user-images.githubusercontent.com/266306/43265599-24f2fda2-90e1-11e8-9d04-ba3f486e9c92.png)

Hyper 2.1.0.1138 on Windows 10 Pro.

**Comment by boydjeff** [comment]
I'm seeing this error after the upgrade to Hyper 2.1. I did not see the error in version 2.0. I'm in a corporate environment, and think the issue is related to running McAfee Endpoint Security, as described in the reference @octachrome provided above. 

If I uninstall Hyper2.1 and reinstall 2.0, then the error goes away, but then Hyper automatically upgrade to 2.1. Is there a way to prevent Hyper from automatically upgrading?

**Comment by ljismail0** [comment]
Experiencing the exact same behavior as @boydjeff. Anything we can do? I have tried running as admin with no luck.

**Comment by talentwill** [comment]
> I'm seeing this error after the upgrade to Hyper 2.1. I did not see the error in version 2.0. I'm in a corporate environment, and think the issue is related to running McAfee Endpoint Security, as described in the reference @octachrome provided above.
> 
> If I uninstall Hyper2.1 and reinstall 2.0, then the error goes away, but then Hyper automatically upgrade to 2.1. Is there a way to prevent Hyper from automatically upgrading?

Yes, I also met this issue.  the issue goes away after I roll back it to 2.1-cannary2. But it always prompt to upgrade. and there is not option that can close auto upgrade!

**Comment by parktheredcar** [comment]
What about setting `releases.hyper.is` or `releases-canary.hyper.is` to `127.0.0.1` in your hosts file to work around the updater?

**Comment by aescasiodev** [comment]
The culprit is in McAfee Real-Time Scanning, I tried turning it off and this error never happens, but when turning back on again the error happens again.

**Comment by MLGFarmerElite** [comment]
Can confirm @aescasiodev 's find. When turning it off, error no longer happens.

**Comment by rnagatama** [comment]
For McAfee issue, I got it working by excluding `C:\Users\<User>\AppData\Local\hyper\app-2.1.0\resources\app.asar.unpacked\node_modules\node-pty\build\Release\winpty-agent.exe`  from real-time scanning on McAfee

**Comment by aescasiodev** [comment]
@rnagatama yes, you need to exclude that file from Real-Time Scanning in any Antivirus.
That works.

**Comment by KingNoosh** [comment]
I've also started running into this in 2.1, I'm unable to change my McAfee's settings in my environment, is there an ETA on the fix?

Could it be perhaps due to the executable not being signed?

**Comment by nickhall** [comment]
Same issue here. Error'd and couldn't start. Excluding the file from real-time scanning did the trick. Thank you guys for the fix!

**Comment by talentwill** [comment]
> McAfee Real-Time Scanning



> Do you remember the last canary that works?

hyper-Setup-2.1.0-canary.2 is OK.

**Comment by talentwill** [comment]
> Do you remember the last canary that works?

hyper-Setup-2.1.0-canary.2 is OK.

**Comment by marawanshalaby** [comment]
> For McAfee issue, I got it working by excluding `C:\Users\<User>\AppData\Local\hyper\app-2.1.0\resources\app.asar.unpacked\node_modules\node-pty\build\Release\winpty-agent.exe` from real-time scanning on McAfee

Better to just add **\winpty-agent.exe to your Mcafee exceptions list, so you don't get that same error when hyper auto-updates and changes the `app-2.1.0` folder

**Comment by nguyensonthenoobdeveloper** [comment]
Thanks @rnagatama, it works!

**Comment by holypoli** [comment]
Had the same problem and as @rnagatama suggested to add winpty-agent.exe to the McAfee exceptions worked for me. thanks!

**Comment by boydjeff** [comment]
Well, Hyper now works in my corporate environment with version 2.1.1. I don't have permissions to add exceptions to McAfee Endpoint Security, so I don't know if an exception was added company-wide or if version 2.1.1 somehow just works. Thanks everyone who saw the same behavior and also commented.

**Comment by xsteacy** [comment]
> The culprit is in McAfee Real-Time Scanning, I tried turning it off and this error never happens, but when turning back on again the error happens again.

Deactivated the McAfee Real-Time Scanning and it worked... Put back the R.T.S. and tried to put some files in the exception list and it didn't work... it just appends to work a bit later... weird!
