### ISSUE TITLE
Severe performance issues on Linux

### ISSUE THREAD

**Issue by Tyriar** [zeit/hyper#2833]
- **OS version and name**:Ubuntu 17.10
- **Hyper.app version**: 2.0.0

## Issue

Screen redrawing is painfully slow on Hyper 2 on Linux, I believe this is due to Electron 1.8 https://github.com/electron/electron/issues/11051

FYI Electron 2 is coming up and I still have issues on my Linux box but you can workaround it via the `--ignore-gpu-blacklist` Chromium arg. You may want to allow this (and `--disable-gpu`) to pass the CLI to `/opt/Hyper/hyper`. See https://github.com/electron/electron/issues/12042

**Comment by Tyriar** [comment]
Running `ll`:

![image](https://user-images.githubusercontent.com/2193314/38825200-8b715a18-4160-11e8-9ebf-2b090f4b3a71.png)

Looks like it's an issue on your end too. There's some weirdness on Linux where spawning takes a while sometimes, don't know too much about that problem.

**Comment by Tyriar** [comment]
The setCwd/setGit might be from `Plugin hyper-statusline (1.7.4) loaded.`?

**Comment by Tyriar** [comment]
After disabling hyperline, everything is fine when I launch with: `/opt/Hyper/hyper --ignore-gpu-blacklist`

You should fix this:

```
~/dev/Microsoft/vscode @tyriar/terminal_process_refactor │ ?1±1 ❯ hyper --ignore-gpu-blacklist
The option "ignore-gpu-blacklist" is unknown. Here's a list of all available options:
```

**Comment by chabou** [comment]
Thank you for your feedback @Tyriar 

We'll track our work about passing options to hyper/electron over here: #2839

**Comment by CrazyByDefault** [comment]
Hyper currently uses [args](https://www.npmjs.com/package/args) to handle command-line arguments at runtime, but as far as I could tell, args has no way of handling unknown options. We'll either need to include all of the options that can be passed to Electron manually, or use a different implementation for handling CLI arguments. 

In particular, [yargs](https://www.npmjs.com/package/yargs) seems to have a way of routing the arguments through custom middleware before running the command associated with them.
