### ISSUE TITLE
Error in version 2.0

### ISSUE THREAD

**Issue by MauroNavaLuevanos** [zeit/hyper#2834]
![captura de pantalla 8](https://user-images.githubusercontent.com/19292284/38825025-c903e656-4170-11e8-8c7f-013e99a5e56e.png)

In the new version. the app is empty 😢, but in the 1.4.8 version, it works fine

![captura de pantalla 9](https://user-images.githubusercontent.com/19292284/38825145-2802fc50-4171-11e8-9c6b-0fb2246ce4ec.png)

**Comment by timothyis** [comment]
Hi there, could you provide the information that was asked for in the issue template?
Most notably your OS version and hyper config contents. Thank you.

**Comment by xoche** [comment]
@MauroNavaLuevanos see #2826 #2829, probably is the `hyperborder` plugin

**Comment by chabou** [comment]
Thanks for the report 🙏 . 
We're tracking this work over here: #2826
