### ISSUE TITLE
Ability to change the tab name

### ISSUE THREAD

**Issue by lardissone** [zeit/hyper#284]
It's not high priority but it's something useful.

In some cases you have several commands running in multiple tabs that looks the same but in different projects (example: frontend node dev command and API node dev command).

It would be nice to be able to manually change the name, like Terminal.app on OSX:

![inspector 2016-07-19 09-47-05](https://cloud.githubusercontent.com/assets/59826/16954320/136b5178-4d96-11e6-8999-589f97968859.png)

**Comment by parro-it** [comment]
You may want to check my [hyperterm-title](https://github.com/parro-it/hyperterm-title) plugin. 
It sets the title of tabs in the same way that iTerm does

**Comment by lardissone** [comment]
@parro-it it's great, but it's not exactly what Terminal.app does. You can't manually change the title in this case.

**Comment by CodeTheory** [comment]
Perhaps this is better as a plugin?

**Comment by parro-it** [comment]
> Perhaps this is better as a plugin?

Yes, I agree. it would be great to have a context menu in the tab to add a 'Chnage tab name' item.
It would also be great to write a `change tab color` plugin, I use this feature very often in iterm...

**Comment by kbrock** [comment]
The plugin works great for me.
In bash I have a function to set the title. Besides one tweak, this has been working for me for all other terminal programs as well:

```bash
function title() { echo -e "\033]0;${1:?please specify a title}\007" ; }
```

**Comment by jadaradix** [comment]
@kbrock 👍 I put this in `.bash_profile` and with the [hyperterm-title plugin](https://github.com/parro-it/hyperterm-title) I can set the title as easy as `title "hello hyper"`.

**Comment by kbrock** [comment]
@jadaradix @lardissone I added the sample function over in parro-it/hyperterm-title#3
Hopefully it will be more friendly to others who have this need

**Comment by OJFord** [comment]
IMO this functionality is much nearer 'core' than "install this third-party plugin, add this to your shell config, and then run this command".

**Comment by kbrock** [comment]
@OJFord Think this functionality is already in master and will come out in the next release without the title

**Comment by JoshuaKGoldberg** [comment]
@kbrock does that PR resolve this issue? It looks like a coding update, not a way for users to set tab titles.

**Comment by chabou** [comment]
Agreed. Thanks!

**Comment by urikphytech** [comment]
Is this functionality available in version 2.0.0? I'm on mac and don't see this option anywhere.

**Comment by parro-it** [comment]
It's not an option, you have to set it via shell commands. 
You can see above how...

**Comment by urikphytech** [comment]
Thanks! tl;dr - write ```title NEW_TITLE``` in the terminal

**Comment by terrancecorley** [comment]
Can someone explain how to get this working on a Windows 10 + Git Bash environment?

**Comment by isseiler** [comment]
@terrancecorley 

add your title text to your local bash profile.

https://stackoverflow.com/questions/46458832/how-to-change-title-of-git-terminal-in-windows

**Comment by JanDeDobbeleer** [comment]
For reference, people looking to do this when using PowerShell, you can use this function to achieve the same (and not having it display `Shell` because that's silly)

```powershell
function Set-ConsoleTitle {
    param(
        [string]
        $title
    )
    $escapeChar = [char]27
    return "$escapeChar]2;$title`a"
}

Set-ConsoleTitle PowerShell
```

**Comment by krodelabestiole** [comment]
> 1. Add this line to your .bash_profile file:
>    `function title() { echo -e "\033]0;${1:?please specify a title}\007" ; }`
> 2. reload terminal, or type command: `source ~/.bash_profile`
> 3. type `title NEW_TITLE` to change tab title

hi, I use WSL and this simply doesn't work :
```
function title ()
{
        echo -e "\033]0;${1:?please specify a title}\007"
}
```
in ~/.bash_aliases

after being sourced it just returns an empty line in the console, no change in the tab name :
```
kro@minipoutre ~  title
-bash: 1: please specify a title
kro@minipoutre ~  title 'test'

kro@minipoutre ~
```

I use hyper 2.1.2 and I'm brand new to it. Has anything changed lately ?

**Comment by sjtuzbx** [comment]
> > 1. Add this line to your .bash_profile file:
> >    `function title() { echo -e "\033]0;${1:?please specify a title}\007" ; }`
> > 2. reload terminal, or type command: `source ~/.bash_profile`
> > 3. type `title NEW_TITLE` to change tab title
> 
> hi, I use WSL and this simply doesn't work :
> 
> ```
> function title ()
> {
>         echo -e "\033]0;${1:?please specify a title}\007"
> }
> ```
> 
> in ~/.bash_aliases
> 
> after being sourced it just returns an empty line in the console, no change in the tab name :
> 
> ```
> kro@minipoutre ~  title
> -bash: 1: please specify a title
> kro@minipoutre ~  title 'test'
> 
> kro@minipoutre ~
> ```
> 
> I use hyper 2.1.2 and I'm brand new to it. Has anything changed lately ?



> > 1. Add this line to your .bash_profile file:
> >    `function title() { echo -e "\033]0;${1:?please specify a title}\007" ; }`
> > 2. reload terminal, or type command: `source ~/.bash_profile`
> > 3. type `title NEW_TITLE` to change tab title
> 
> hi, I use WSL and this simply doesn't work :
> 
> ```
> function title ()
> {
>         echo -e "\033]0;${1:?please specify a title}\007"
> }
> ```
> 
> in ~/.bash_aliases
> 
> after being sourced it just returns an empty line in the console, no change in the tab name :
> 
> ```
> kro@minipoutre ~  title
> -bash: 1: please specify a title
> kro@minipoutre ~  title 'test'
> 
> kro@minipoutre ~
> ```
> 
> I use hyper 2.1.2 and I'm brand new to it. Has anything changed lately ?

I'm running into same problem in ubuntu 18.04, looking for help

**Comment by pelayomendez** [comment]
This works for me in Ubuntu 18.04

```
function title(){
  if [[ -z "$ORIG" ]]; then
    ORIG="$PS1"
  fi
  TITLE="\[\e]2;$*\a\]"
  PS1="${ORIG}${TITLE}"
}
```

**Comment by synapse709** [comment]
This should be a possible with a right-click menu

**Comment by PauloB04** [comment]
> This works for me in Ubuntu 18.04
> 
> ```
> function title(){
>   if [[ -z "$ORIG" ]]; then
>     ORIG="$PS1"
>   fi
>   TITLE="\[\e]2;$*\a\]"
>   PS1="${ORIG}${TITLE}"
> }
> ```

I'm using Windows 10 with Hyper version 3.0.2 and **THIS** worked for me! Thanks.

**Comment by catamphetamine** [comment]
After messing with the cryptic `title()` function with no clear directions to where to put it, turns out that changing a title is as simple as typing `title ABC` in the terminal itself.

**Comment by catamphetamine** [comment]
It could have defaulted to the current working directory though, as all other terminals do.
