### ISSUE TITLE
Can't use hyper

### ISSUE THREAD

**Issue by omarmhaimdat** [zeit/hyper#2841]
![screen shot 2018-04-16 at 9 24 11 pm](https://user-images.githubusercontent.com/2160742/38833122-8dd27394-41bc-11e8-8680-fa8b7561354c.png)
<img width="912" alt="screen shot 2018-04-16 at 9 24 08 pm" src="https://user-images.githubusercontent.com/2160742/38833123-8e02bbee-41bc-11e8-8d0f-a7148c7671f3.png">

I got this issue when I received a notification that the new hyper 2.0 is stable, so I updated hyper. Now I can no longer use it !

  - [x] Your Hyper.app version is **2.0.0**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "2.0.0"

 - **OS ARCH VERSION:** darwin x64 17.2.0
 - **Electron:** 1.8.4  **LANG:** undefined
 - **SHELL:** /bin/zsh   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "themeSettings": {
    "opacity": 1,
    "style": "yoda",
    "tabActiveMarker": "💁"
  },
  "fontSize": 13,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "\n      x-screen a {\n      color: blue;\n      }\n \n      x-screen a.hover {\n      text-decoration: none;\n      }\n    ",
  "showHamburgerMenu": "true",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false
}

          {
  "plugins": [
    "hyper-snazzy",
    "hyper-confirm",
    "hyperlinks",
    "hypergoogle",
    "hyper-search",
    "hyper-blink",
    "hyperborder",
    "hyperline"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by timothyis** [comment]
Unfortunately, this is the fault of hyperborder. We've had a few similar issues relating to this too. Please submit an issue to the plugin 😓

**Comment by omarmhaimdat** [comment]
Thank you, it was indeed the fault of hyperborder.

--------------
Omar MHAIMDAT
