### ISSUE TITLE
Hyper 2.0.0 does not preserve as much history

### ISSUE THREAD

**Issue by rwwagner90** [zeit/hyper#2844]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS High Sierra 10.13.4
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
It seems like I used to be able to scroll up a lot and my terminal history was preserved, but now it is very short and I cannot scroll far.

**Comment by jonaswindey** [comment]
Same here. Did you keep your config from Hyper 1 or was it a clean install?

**Comment by Roilan** [comment]
+1

**Comment by rwwagner90** [comment]
@jonaswindey I think I kept my config. My plugins are still there, but unsure if they all function.

**Comment by Roilan** [comment]
Kept my config as well. I had to redownload 1.4.8 because of this.

**Comment by jcoetzee** [comment]
I used a clean config and experiencing the same.

**Comment by rwwagner90** [comment]
As a side note, did anyone think their fonts and colors got heavier?

**Comment by albinekb** [comment]
That's another issue @rwwagner90 if you search for it you'll find it 👍

**Comment by chabou** [comment]
Thanks for the report 🙏 . 
We're tracking this work over here: #280

**Comment by chabou** [comment]
(Using `xtermjs` has reduced this history. We really need to make this size customizable).
