### ISSUE TITLE
Hyper 2.0 shows wrong colors

### ISSUE THREAD

**Issue by rdev** [zeit/hyper#2846]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.3
- **Hyper.app version**: Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [My .hyper.js](https://gist.github.com/rdev/cf844f588232e59b1a502c8f2d8fb51f)
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

I'm using Hyper with Fish shell and [this OMF theme](https://github.com/rdev/omf-theme-one)
And since 2.0 update some colors are displayed incorrectly:

Here's iTerm (Hyper < 2.0 looked the same):
<img width="719" alt="screen shot 2018-04-17 at 10 59 45 am" src="https://user-images.githubusercontent.com/8418866/38846818-07ff1dc4-4231-11e8-98d4-0479be8f460a.png">

And on 2.0.0 the "❯" symbol is cyan:
![screen shot 2018-04-17 at 10 59 49 am](https://user-images.githubusercontent.com/8418866/38846824-0c4ca2c0-4231-11e8-874c-a3bc1514be8d.png)

It seems like `#2bed9b` color from the shell is swapped with `lightCyan` by Hyper

**Comment by albinekb** [comment]
I can't see #2bed9b in your config 🤔

**Comment by rdev** [comment]
@albinekb it's not part of the config, it's in the Fish theme

Check here: 
https://github.com/rdev/omf-theme-one/blob/f47998520622948c7a4259a761c6f7d27d603859/fish_prompt.fish#L1-L12

**Comment by connorwiebe** [comment]
yeah all the colors look faded/washed out for me too in 2.0

**Comment by albinekb** [comment]
@rdev hmmm I wonder why that doesn't work. Thanks for pointing me there

All colors or just bold color? that could be https://github.com/zeit/hyper/issues/2836 @connorwiebe

**Comment by rdev** [comment]
@albinekb all colors

**Comment by chabou** [comment]
@rdev It seems that you fish theme uses TrueColors and this is not compatible yet with our underlying terminal `xtermjs`

@connorwiebe default colors have changed to match iTerm2 theme (and permit use of brightColor). https://github.com/zeit/hyper/pull/2670#issuecomment-382714834

**Comment by ArondeParon** [comment]
Similar issues here with ZSH and Agnoster theme.

**Comment by jackno** [comment]
[Still experiencing this issue](https://github.com/joshdick/onedark.vim/issues/152) with v2.1.2
