### ISSUE TITLE
`hyper` not working Win10

### ISSUE THREAD

**Issue by sebastianks** [zeit/hyper#2851]
I've just installed Hyper and wanted to install "verminal" right away, and tried to use: `hyper i verminal` but I get the error: "'hyper' is not recognized as an internal or external command, operable program or batch file."

For some reason the "hyper" command is not installed on my PC.

Could someone please help me :)

Also - the gif on the frontpage of hyper.is has some nice styling for each line - maybe it's another shell then cmd.exe. How do I get it to be like that?

**Comment by albinekb** [comment]
Have you tried rebooting your PC? 😊 
I think this is a duplicate of https://github.com/zeit/hyper/issues/2823

**Comment by sebastianks** [comment]
Hi @albinekb 
No I had not. Now it's working after a reboot. 

Thank you! :)

**Comment by albinekb** [comment]
Thanks for closing 👍

**Comment by aburgd** [comment]
In case anyone else finds this issue, running `refreshenv` from a Hyper-emulated cmd works too!

**Comment by mattezell** [comment]
Sorry - going to demonstrate my ignorance here.

If I modify my PATH via the built in Windows "System Properties - Environment Variables" UI, I don't have to restart Windows (nor use refreshenv) for those to be picked up - I merely have to restart the shell (close cmd window and start a new instance)... 

Curious if anyone can explain why this isn't true with Hyper? 

Thanks!

**Comment by mattezell** [comment]
Nevermind. Withdrawn - I see how it works, and why my described approach behaves differently after reviewing this: https://github.com/zeit/hyper/issues/2823

Confirmed that one can simply go into the Windows UI and review the path, click OK, and have those take effect without restarting Windows.

**Comment by dmxt** [comment]
Does logging out and in count as rebooting for Hyper? In the past for all sort of reboot requests, log out and in was good enough. But with hyper... it just keep telling me that the cli is already in path but it couldn't open it!
