### ISSUE TITLE
Make Hyper look like advertised

### ISSUE THREAD

**Issue by sebastianks** [zeit/hyper#2853]
Hey

I've installed Hyper on Win10, and looking to make it look like it's advertised.
Mine looks like number "2" image here: https://imgur.com/a/ctEZd ... I am looking to make it look liek image number "1". Is this possible?

(I know it's a theme, but I am thinking of the simple ">". Mine is looking rather ugly ;o)

**Comment by lucasqueiroz** [comment]
You mean the PS1? That is something you can change, but I have no experience with that in Windows, so maybe someone else can help, but I think creating an issue isn't the right way 🤔

**Comment by sebastianks** [comment]
I don't know if that's it - that's why I wrote in here. Also, I haven't found any forum or something like that to answer those questions in, that's why I wrote an issue...

**Comment by albinekb** [comment]
Install verminal, we have a bug currently so you will need to restart your PC before `hyper` command works.

After restarting, install by typing `hyper I verminal` and hitting enter (inside hyper)

then you should get the correct colors.

To change your prompt, It's easy In Mac and linux, I have no idea how to change it on windows, but google for "change window cmd prompt" maybe or "change ps1 windows" 😊

**Comment by sebastianks** [comment]
All the colors of Verminal are not applied, and it doesn't look like it should - at all. I'm not sure if this is because I'm using Windows.

I've managed to install ohmyzsh on Windows now, and it's pretty cool. Still would be nice to have it as simple and stylish as hyper is advertised on the website, but I guess it's not possible on Windows.

**Comment by albinekb** [comment]
I don't know if it's possible on Windows, maybe some other windows user can help you get there 👍 🙌

**Comment by teunissenstefan** [comment]
Does this bug have to do with system variables? If so, shouldn't CDing into the Hyper directory, and then using the command work?
