### ISSUE TITLE
Hyper2 CLI not working with Win10 WSL+ zsh

### ISSUE THREAD

**Issue by kennedy** [zeit/hyper#2862]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Win 10 1709, shell: WSL Ubuntu 16.04.4 LTS
- **Hyper.app version**: 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [my .hyper.js](https://gist.github.com/kennedy/00b5089b1ade405a32b1abe54f21fa2a)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: Configure shell to be bash.exe

## Issue

My goal was to install plugins with the Hyper cli. `hyper i hypercwd`. I am not using Powershell nor gitbash/cygwin, but WSL Bash (ubuntu) + zsh. With my current configuration, I launch zsh after my ~/.bashrc is loaded. I attempted to include the Win10 Hyper CLI location in my ~/.bashrc.

`export PATH="$PATH:/mnt/c/Users/Kennedy/AppData/Local/hyper/app-2.0.0/resources/bin"`

![capture](https://user-images.githubusercontent.com/854543/38906006-2663fc20-4282-11e8-8f39-902d2fb0fc7b.PNG)

But it told me to check out https://github.com/Microsoft/WSL/issues/1494 but I was unsuccessful.

**Comment by mr6volt** [comment]
I solved this by running "hyper i <blah>" commands from cmd.

**Comment by kennedy** [comment]
... i didnt even think of that

**Comment by samdenty99** [comment]
You can alias the hyper command to run through `cmd.exe` by adding

```bash
alias hyper="cmd.exe /c hyper"
```

into your `.bashrc` or `.zshrc`
