### ISSUE TITLE
Use custom css properties on terminal font render ( webkit-font-smoothing )

### ISSUE THREAD

**Issue by alxtz** [zeit/hyper#2864]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.3
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/alxtz/a103d33851cb97c501a65b567feb6cb9

## Issue
In pre 2.0.0 of hyper.js, I'm able to customize the css props of the fonts in hyper.
One of my favorite, is to use `-webkit-font-smoothing` to make the font display more smooth.

#### Before
![image](https://user-images.githubusercontent.com/16031425/38910180-b80e23a8-42fa-11e8-960a-bbaa90af1fb0.png)

#### After
![image](https://user-images.githubusercontent.com/16031425/38910125-7b2eae62-42fa-11e8-8571-5b6d3e765b4f.png)

#### In 2.0.0
![image](https://user-images.githubusercontent.com/16031425/38910228-f29e7dd8-42fa-11e8-8a46-8a8756b1d86c.png)

In 2.0.0, I believe all the `x-row` based css is deprecated, since the term windows is all rendering using canvas.

Is it still possible to do those customization in 2.0.0? The doc only revealed some very basic setup for it. https://hyper.is/

**Comment by alxtz** [comment]
Maybe related to #2601 , is there still no official way to change/hook in to the rendering?

**Comment by Tam** [comment]
+1, would really like to get my fancy ligatures back!
`x-screen x-row { font-variant-ligatures: initial; }`

**Comment by albinekb** [comment]
@Tam support for ligatures is up to xterm sadly. Since switching to canvas rendering ligatures is hard to support. see https://github.com/xtermjs/xterm.js/issues/958

**Comment by alxtz** [comment]
That is so sad..., the only reason I use hyper.js is only for the ability to use css props 🙁

**Comment by Stanzilla** [comment]
So there are actually two problems here, 

@alxtz The `termCSS` setting is now called just `css` so try with that.
@Tam sadly you will have to wait for the xtermjs team to implement that.

**Comment by albinekb** [comment]
Since hyper now renders with canvas, you are correct in that it doesn't change how fonts are rendered, some things can be changed via xterm API.
