### ISSUE TITLE
Error after updating to Hyper 2.0.0

### ISSUE THREAD

**Issue by MTayyabHanif** [zeit/hyper#2865]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64-bit
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/MTayyabHanif/d7757b4cfec919c7fc373069640b34c6)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes I guess, because it was totally fine but crashed right after the minute of updating to 2.0.0.

## Issue
Okay so, I also use Hyper in sublime, there is a package for sublime [Sublime Terminal](https://github.com/wbond/sublime_terminal) which opens up default windows terminal if not defined, and if defined the path of your terminal then it will open yours. 

I was previously using Cmder. But now I started using Hyper for a month, and last day I get an notification from Hyper that 2.0.0 is released, so I updated mine (It was working in sublime till I updated). 

After closing sublime and I opened like usual, I pressed Ctrl+Shift+T (shortkey provided by the package I mentioned above to open terminal), I have provided path to Hyper, I didn't change it as it was working in previous version.

Now take a look at this image you will get the idea:
![Screenshot](https://user-images.githubusercontent.com/22817175/38917233-8cf6a5f6-4303-11e8-8dd3-d3a84673d165.png)

As you can see behind in file I added path to Hyper file, which does exist there, I checked it. and now i'm receiving this error.
I don't know what went wrong. :no_good:

---

**Comment by Krato5** [comment]
the some error i got here , any fix plz ?

**Comment by B-Henderson** [comment]
same error 
OS version and name: Windows10 Enterprise 64-bit
Hyper.app version: 2.0.0

same issue was running npm installed and it crashed and when I reopened I get the error above

**Comment by chabou** [comment]
@MTayyabHanif Is Hyper working as standalone (without Sublime integration)?

**Comment by MTayyabHanif** [comment]
@chabou Yes it does.
I opened it by going in folder and using context menu "Open Hyper here".
And it works like usual.

**Comment by MTayyabHanif** [comment]
@chabou Any workaround found yet?
Just wanna know. 😄

**Comment by ryan-christensen** [comment]
This is the error I got using v2.1.0 (not using Sublime)
![image](https://user-images.githubusercontent.com/17580670/50622799-6067a300-0ecd-11e9-9416-e0d9360d2c96.png)
