### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by marilyn91** [zeit/hyper#2867]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10 v.1709
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Hyper.js](https://gist.github.com/marilyn91/987693e87c61b2f154c0e3412f301ee9)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: no error in the devtools
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

After the installation done, hyper executes and the window appears as below (see photo).

![capture](https://user-images.githubusercontent.com/6699326/38932440-772ee64e-4316-11e8-8cc5-04ca3eaf0297.PNG)

Cordially.

**Comment by timothyis** [comment]
Unfortunately, it's hyperborder that causes this issue. Please submit an issue to them 🙏 
Sorry about that 

Related: #2826
