### ISSUE TITLE
Set hyperlink color

### ISSUE THREAD

**Issue by mjwsteenbergen** [zeit/hyper#2870]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows
- **Hyper.app version**: 2.0.0

## Issue
The new integration of hyperlinks is super cool. The only downside is that all hyperlinks are white. Is there a configuration option to set the color of hyperlinks (when you hover over them)? Something in the order of:
```
   hyperlinkColor: '#1B1E1F',
```

**Comment by Stanzilla** [comment]
https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-web-links something for over there now
