### ISSUE TITLE
How to add plugins to Hyper.is store?

### ISSUE THREAD

**Issue by lacymorrow** [zeit/hyper#2875]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

I would like to add a new plugin to the Hyper.is website: https://github.com/lacymorrow/hyper2-border

**Comment by albinekb** [comment]
You can read how to do it at https://github.com/zeit/hyper-site/wiki/Submitting-a-new-plugin-or-theme-to-Hyper-Store 🎉
