### ISSUE TITLE
Unexpected behavior when pressing the TAB key

### ISSUE THREAD

**Issue by mrgrauel** [zeit/hyper#2878]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.4
- **Hyper.app version**: 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mrgrauel/10c9616b0636657d1f21ea14b2e9aadb
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue
* Open Hyper
* type `rm `
* click on the key `TAB`
* The word `rm` gets displayed twice see the video
 * the second appearance of rm can be deleted but the first cannot

<img width="466" alt="bildschirmfoto 2018-04-19 um 11 40 26" src="https://user-images.githubusercontent.com/148758/38984245-79fb6fae-43c6-11e8-905d-ba68816d0ffa.png">

[Bildschirmaufnahme.mov.zip](https://github.com/zeit/hyper/files/1927534/Bildschirmaufnahme.mov.zip)

**Comment by albinekb** [comment]
Can't reproduce with `fish`, I think you're using `zsh`? Can someone reproduce?

**Comment by mrgrauel** [comment]
Yeah I'm using `zsh` with [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh). Maybe the ticket is a duplicated or related to #2328 but wasn't sure.

**Comment by albinekb** [comment]
Have you tried changing your LOCALE as per https://github.com/zeit/hyper/issues/2328#issuecomment-370590423

**Comment by mrgrauel** [comment]
I tried to change it to `de.UTF-8` and `de-DE.UTF-8` both didn't work, but `en-US.UTF-8` fixed the issue.

**Comment by mistercorea** [comment]
I still couldnt reproduce the problem should close the ticket unless more information can be produced.
