### ISSUE TITLE
Strange behavior Midnight Commander

### ISSUE THREAD

**Issue by kajka** [zeit/hyper#288]
Starting Midnight Commander revealed the strange behavior of the application (for example irssi works fine for me). Has anyone experienced a similar issue? Any fixes?

![2016-07-19-17 17 41-compress](https://cloud.githubusercontent.com/assets/2843796/16955949/d2bcedd0-4dd6-11e6-9370-3116770d26ec.gif)

OS X 10.11.6
HyperTerm 0.6.0

**Comment by gex** [comment]
tmux has the same problem:
![screen shot 2016-07-22 at 01 46 13](https://cloud.githubusercontent.com/assets/15120752/17042484/21b9558a-4fae-11e6-86cc-e381109ec0cd.png)

**Comment by Leonya** [comment]
Would love to see this fixed.

**Comment by albinekb** [comment]
Related to #213

**Comment by ppot** [comment]
@matheuss close

**Comment by damien122** [comment]
@albinekb Could you please explain how a fix about custom keys should fix this error?
