### ISSUE TITLE
2.0.0 update broke hyper-aww plugin

### ISSUE THREAD

**Issue by leighzoer** [zeit/hyper#2883]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hyper-Aww is not working with the update and it sustains my happiness at work. I need it back asap.

**Comment by chabou** [comment]
Please open an issue in plugin repo: https://github.com/stokingerl/hyper-aww/
