### ISSUE TITLE
CLI: Linking must not replace existing file

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2884]
A user can already have a legitimate file/link `/usr/local/bin/hyper`.
https://hyper.sh/

A notification should be issued instead of overwriting.

**Comment by chabou** [comment]
On Linux, even without `Hyper CLI`, a link is created by the package installation. A post-install script is run to point this link to cli shell startup script instead of Electron bin.
If a file/link exists, I think that installation would fail.

On macOS, the link is checked and added at each start. We can't show an annoying notification at each start. Or we need to add an option to disable this check/add. But it seems to be overkill.

A solution could be to silently fail at startup and adding an item menu to manually `Install Hyper CLI command in PATH` with a confirmation/error notification.

**Comment by timothyis** [comment]
I agree with silent fail at startup. I'm not sure what else we could do, other than providing a different path and track that. Which might be too much
