### ISSUE TITLE
Change the tab title in hyper 2.0.0

### ISSUE THREAD

**Issue by bvaldes** [zeit/hyper#2886]
Hi,

I am on OSX but I plan to use Hyper on Windows too because of the new update with xterm.js

I've done a fresh install of hyper 2.0.0 and I would like to change the tab title.

The only answer I found was to Hyper 1.X with the hyperterm-title plugin. The issue is that it doesn't work at all on 2.0.0.

I saw that this plugin was merged with something that you call core but I've no idea what people talk about.

I hope that my question is not stupid. Thanks for the help.

**Comment by Stanzilla** [comment]
What would you like the tab title to say? Something dynamic like the current folder? Which shell are you using inside of Hyper?

**Comment by bdinesh** [comment]
How can we rename the tab title like we want in Hyper 2.0?

**Comment by cr101** [comment]
I'm on Windows 10 and the title for all the tabs is "Shell". Is there a way to change the tab title?

**Comment by rjurney** [comment]
I need this too.

**Comment by cdetrio** [comment]
I'd like this feature (on Mac all tabs also say "Shell"), and be able to set window names too.

**Comment by ankur2002** [comment]
I upgraded to 3.0.2 and now the tab titles don't show up anymore. This seemed to be working on my mac when I was still using version 2.x but it stopped working on 3.x.

Can we restore the tab titles again?

**Comment by dincercelik** [comment]
Same here with 3.0.2 on OSX 10.14.5

**Comment by drbparsons** [comment]
I managed to find a solution that changes the tab titles on Mac to the current directory:

Assuming your default shell is zsh, add this to your ~/.zshrc file:

```
case $TERM in
  xterm*)
    precmd () {print -Pn "\e]0;%~\a"}
    ;;
esac
```

![image](https://user-images.githubusercontent.com/1021530/59541176-0b0dd400-8ef8-11e9-923d-c7a843e720a0.png)

(via http://blog.pengyifan.com/how-to-set-terminal-title-dynamically-to-the-current-working-directory/)
