### ISSUE TITLE
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

### ISSUE THREAD

**Issue by cybertk** [zeit/hyper#2888]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app v2.0.0
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Win10
- **Hyper.app version**: v2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

The issue can be simply reproduced by the following command

```
$ docker.exe run -it --rm ubuntu:14.04 /bin/bash
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

**Comment by RecaaJo** [comment]
Just add 'winpty' in start of your cmd ,Try below:
`$ `winpty` docker.exe run -it --rm ubuntu:14.04 /bin/bash`

**Comment by cybertk** [comment]
Why **Hyper** isn’t compatible with Windows console programs?

**Comment by cybertk** [comment]
I saw winpty is already carried in **Hyper**, why I still need to add `winpty` prefix? And the even worse is that I should install another winpty besides the one carried in **Hyper**.

**Comment by FantomX1** [comment]
happens too at windows linux subsystem

**Comment by dictShuang** [comment]
Just add 'winpty' in start of my cmd.
before:
`docker exec -it kubia-container bash`
after:
` winpty docker exec -it kubia-container bash`

**Comment by alenworld** [comment]
> To anyone potentially having a similar issue with docker, you may not need winpty.
> 
> I followed this guide to install docker on WSL rather than passing through to the windows.exe: https://medium.com/@sebagomez/installing-the-docker-client-on-ubuntus-windows-subsystem-for-linux-612b392a44c4
> 
> Then I changed my `shellArgs` in `.hyper.js` from
> 
> ```
>  shellArgs: ['--login', '-i', '/c wsl'],
> ```
> 
> to
> 
> ```
> shellArgs: ['--login'],
> ```
> 
> Seems to work fine now.

Thank you!

**Comment by brncoding** [comment]
Forget git bash, use your  prompt.  Start > Run > "CMD"  

1 - docker run redis

2 - docker ps -all

3 - Copy the container_id that represents the redis image.

4 - docker exec -it container_id redis-cli.

5 - Done!
