### ISSUE TITLE
Move app version string from app/package.json to root package.json

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2894]
Having version number in root `package.json` will permit to use the full power of https://github.com/zeit/release

**Comment by Manish-Giri** [comment]
I'll take this up, if that's okay.

**Comment by chabou** [comment]
@Manish-Giri Yes please 🙏

**Comment by steven-isbell** [comment]
Bumping this and doing some research. It looks like you'd need the version in both package.json files if you want to keep it in the root. Electron builder only ships the package.json located in `/app`, so it needs the correct version there as well. 

If that's the case, then there's no real benefit in changing where the internal require statements are pointing to, and you could simply duplicate the version in the root package.

Linking the electron builder docs for reference.

https://www.electron.build/tutorials/two-package-structure
