### ISSUE TITLE
Hyper 2.0 Ubuntu 17.10 Screen Draw Issue

### ISSUE THREAD

**Issue by twlatl** [zeit/hyper#2896]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu Budgie 17.10
- **Hyper.app version**: 2.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/twlatl/c67adaa6f02d952939827bcf9b836736
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:  Yes

## Issue
As seen in this video file, in the latest Hyper 2.0 on Linux (Ubuntu Budgie 17.10), the terminal screen blanks and stutters after each character is typed. This wasn't happening on Hyper 1.0 which I was using prior to 2.0 on the same OS & hardware.

https://www.dropbox.com/s/8z09m86keo7sw2g/hyper.mp4?dl=0

**Comment by OmeletHopper** [comment]
I'm getting similar results from my fresh install of Arch running the LXQt desktop.

**Comment by markanthonyuy** [comment]
I have the same issue. I'm using Ubuntu 16.04 LTS

**Comment by jrmypttrsn** [comment]
Same issue on Ubuntu 17.10 with Hyper 2.0.

**Comment by jwulf** [comment]
I have this on 18.04 with Hyper 2.0. Had it on 17.10 as well. I was hoping that Hyper 2.0 and Ubuntu  18.04 would solve it, but they haven't.

**Comment by twlatl** [comment]
Just tried the new canary version - 2.1.0 on Ubuntu 18.04 (standard version). It doesn't seem to have any of the visual ticks the earlier version had. So far, so good. Will keep testing and chime in if any of these issues resurface.

**Comment by garyx** [comment]
Seems to be the same issue as https://github.com/zeit/hyper/issues/2804
