### ISSUE TITLE
altIsMeta does not work on macOS

### ISSUE THREAD

**Issue by dongz9** [zeit/hyper#2902]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version

- **OS version and name**: macOS High Sierra 10.13.4
- **Hyper.app version**: Hyper 2.0.0-canary.18 (canary)

## Issue

From what I read, by setting altIsMeta to true, key combos like alt-f, alt-b should work as I expected. However, it's not the case. I added modifierKeys: { altIsMeta: true } to .hyper.js, but alt-f still generates ƒ.

**Comment by chabou** [comment]
https://hyper.is/#cfg

Should be in a `modifierKeys` key:
```
{
  config: {
	modifierKeys: {
    	altIsMeta: true
    }
  }
}
```

**Comment by dongz9** [comment]
Ah, I forgot to put it in the config section. Thanks!
