### ISSUE TITLE
White Background

### ISSUE THREAD

**Issue by hThoreau** [zeit/hyper#2904]
- **OS version and name**: Subgraph Aaron (based upon Debian Stretch
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/hThoreau/30cc4d9b171a6872e55badf36a4ddbb0

## Issue
Hello there. Ever since 2.0.0-canary-12, My terminal displays white text over a white background.

And that's that.

**Comment by hThoreau** [comment]
So, this was because of a plugin, hyperterm-transparent-bg. And that wasn't listed in the gist I linked in my OP. So I'm sorry for that, I'm closing the Issue.

**Comment by chabou** [comment]
I was pretty sure that a plugin was responsible but perplexed by your gist 😄 
Thank you for your last feedback! 🙏
