### ISSUE TITLE
ANSI escapes shown as question marks when output from Java

### ISSUE THREAD

**Issue by phantamanta44** [zeit/hyper#2905]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 on MSYS2
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/phantamanta44/d8e41084f326b2620e88d77086119267
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Probably; occurs when two installed plugins are disabled.

## Issue
ANSI escapes in output from Java are printed as question marks:
![](https://i.imgur.com/RdrxL4X.png)
The Java version in particular is HotSpot 64-bit 1.8.0_161-b12.

ANSI escapes seem to work in general, as shown by running a simple echo:
![](https://i.imgur.com/7nB9ofx.png)
And oddly enough, they seem to work in the Java program when xargs'd through echo or piped through a no-op sed:
![](https://i.imgur.com/6YqDuIL.png)
This is my bashrc if relevant: https://github.com/sapegin/dotfiles/blob/dd063f9c30de7d2234e8accdb5272a5cc0a3388b/includes/bash_prompt.bash

**Comment by Stanzilla** [comment]
Hey there, could you test this in the Visual Studio Code terminal, please? If it has the same issue, then it is https://github.com/xtermjs/xterm.js/issues/1395

**Comment by phantamanta44** [comment]
Printing in one statement:
![](https://i.imgur.com/8UKaNES.png)

Also seems to occur in VSCode:
![](https://i.imgur.com/FzNSPZr.png)

Then I'll just assume it's xtermjs/xterm.js#1395
