### ISSUE TITLE
Maximise active pane

### ISSUE THREAD

**Issue by aexmachina** [zeit/hyper#2916]
iTerm has a very useful feature: Cmd-Shift-Enter maximises the current active pane, so if you have a window that's split and you just want to focus on one pane for a time, this command makes it fill the whole window, until you press it again and it toggles off.

Thanks for an awesome project!

**Comment by timothyis** [comment]
This is better suited for a plugin, I think. You can already use `hyper-pane` to achieve this: https://hyper.is/plugins/hyper-pane

**Comment by aexmachina** [comment]
Yes, that plugin does provide this feature. Thanks!
