### ISSUE TITLE
Programming Ligatures, Customize Installation, Path Detection

### ISSUE THREAD

**Issue by boxsnake** [zeit/hyper#2920]
Env:
* Win 1703 ver 15063.966
* MSYS2-64
* zsh
* Hyper 2.0.0 stable

Feature Requests:
* First, programming ligatures. (#914) The solutions here do not work for me. I am using Fira Code.
    * Something look weird here:
![image](https://user-images.githubusercontent.com/3257783/39161269-7b50312a-47a2-11e8-94b9-49a688568c11.png)
* Second, when I install Hyper.app, may I customize where to install, and where global/local plugins installed? I do not want the programs and plugins to take my space from driver `C:\`
* Third, I found there is a path detection every time when the app starts. However, if the app didn't found its path in `PATH`, it will add one. I prefer to make an `%BNP_HYPER%` env var, then add `%BNP_HYPER%` to `%PATH%` to make `%PATH%` more readable. In this case, the Hyper.app will still add a new line. E.g.
![image](https://user-images.githubusercontent.com/3257783/39161574-f924b2b4-47a3-11e8-9957-a06eff44bd82.png)

**Comment by timothyis** [comment]
Hi! Thanks for submitting this issue.

The first request is upstream and down to xterm.js support ligatures, of which it already has an open issues: https://github.com/xtermjs/xterm.js/issues/958

The second is a good idea, although I don't know how it would work with Electron.

The third, I'm sure we had an issue for this but I can't find it 🤔

**Comment by RangerMauve** [comment]
Regarding ligatures, there's now an [xterm plugin](https://github.com/xtermjs/xterm-addon-ligatures) that adds support for them.

Would it be possible to include this plugin? Aternately, would you mind giving me some pointers on how I could make a hyper plugin which would add this?

**Comment by tolbertam** [comment]
@RangerMauve I experimented with incorporating `xterm-addon-ligatures` and it does look like getting it to work was pretty easy!  I just followed the instructions in the repository and it seemed to just work.

The module requires xterm 3.6.0 (which looks like #3178 will take care of?), and hyper currently depends on 3.4.1.  I tried xterm 3.6.0 with hyper and it seems to work!  Although the terminal window doesn't fully expand initially (may just be a compatibility issue)

![hyperligature](https://user-images.githubusercontent.com/6889771/44620844-23293f80-a861-11e8-9d43-b24afb9e58e6.png)

The changes for this: tolbertam/hyper@04f1b713a83793ce7fdbd9b4d0d2a07b136214a1 .  Although I suspect these aren't complete, as there should probably be a way of disabling font ligatures, this is a pretty good start.

**Comment by tolbertam** [comment]
Maybe this could be something made available as a plugin instead of being baked in?  I can look into that if that makes sense.

**Comment by tolbertam** [comment]
I was able to make this work as a plugin, but note that it doesn't work with the currently released version of hyper (it will work after xterm is updated to 3.6.0 via #3178).

Plugin can be found here: https://github.com/tolbertam/hyper-font-ligatures and installed via `hyper i hyper-font-ligatures`.

**Comment by RangerMauve** [comment]
That's so awesome @tolbertam!

**Comment by GitSquared** [comment]
Font ligatures support is tracked in #3607

**Comment by boxsnake** [comment]
@timothyis 
If you are using `electron-builder`, you can set this:
```json
{
    ...,
    "build": {
        "nsis": {
            "oneClick": false,
            "allowToChangeInstallationDirectory": true
        }
    }
}
```

**Comment by Stanzilla** [comment]
Can you please split up your issue for the three parts? Ligatures are now supported in the canary CI builds

**Comment by boxsnake** [comment]
> Can you please split up your issue for the three parts? Ligatures are now supported in the canary CI builds

I just separate the second one, since the first is in canary CI, and the third has an existing issue.
