### ISSUE TITLE
Hyperlink is broken with line break

### ISSUE THREAD

**Issue by VdustR** [zeit/hyper#2923]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
    
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
    I searched `hyperlink`, `wrap`

- **OS version and name**: MacOS High Sierra 10.13.4
- **Hyper.app version**: `2.0.0`
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: as default

## Issue

For example if the terminal show a very long URL and wrap like this

```
http://www.a.web.site/some/where/that/url/is/very/very/
long/
```

The hyperlink is `http://www.a.web.site/some/where/that/url/is/very/very/`, but the expected URL should be `http://www.a.web.site/some/where/that/url/is/very/very/long/`.

**Comment by albinekb** [comment]
Looks like this has been fixed upstream in xterm: https://github.com/xtermjs/xterm.js/issues/686, we just need to update our dependency 🤔

**Comment by bartveneman** [comment]
Was this dependency already updated?

**Comment by albinekb** [comment]
We're waiting on https://github.com/zeit/hyper/pull/3214 @bartveneman

**Comment by BPScott** [comment]
The Canary version of Hyper is using xterm 3.4.1, which includes a fix for this. You can jump onto the canary build by adding the following to your [hyper.js preferences](https://hyper.is/#cfg) `updateChannel: 'canary,`
