### ISSUE TITLE
Sluggish when working over an ssh connection 

### ISSUE THREAD

**Issue by StlthyLee** [zeit/hyper#2925]
Hi, This is less of a specific bug and more of a performance issue.

This morning I started giving Hyper 2 a try and for the most part, I really like it. However, I have found a big issue when working over SSH Hyper really starts to struggle, doing things as simple as opening an editor (emacs or nano in this case) Hyper starts to become really unresponsive. to the point where I'm waiting 5-10 seconds for a simple key press to happen. 

I have compared doing the same things with Terminal on the mac there is no issue using Terminal. I will be keeping my eye on Hyper and continuing to use it when working locally. it's just a shame that I can't replace Terminal completely at the moment.

**Comment by albinekb** [comment]
Please fill in the https://github.com/zeit/hyper/blob/canary/.github/issue_template.md
with steps to reproduce, we need to know your OS, how you're connecting etc to be able to reproduce.
