### ISSUE TITLE
High CPU usage on macOS

### ISSUE THREAD

**Issue by herrbischoff** [zeit/hyper#2927]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.4
- **Hyper.app version**: 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: shipped default
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Having lots of output scroll by fast (in this case, running `portsnap fetch update` via SSH on a FreeBSD box) causes very high CPU usage (~180%, up to 250% on a 2014 MBP), while identical output in iTerm (~30%) or Alacritty (~8%) does not.

**Comment by Manubi** [comment]
Same problem with me...  OS version (macOS 10.11.6).
Not possible to use Hyper anymore...

**Comment by albinekb** [comment]
Do you have external graphics? Eg. nvidia dedicated card?

**Comment by herrbischoff** [comment]
<img width="751" alt="screen shot 2018-04-24 at 15 39 56" src="https://user-images.githubusercontent.com/8957346/39190854-c507683c-47d5-11e8-9236-ef1926ef1701.png">

**Comment by albinekb** [comment]
Ok, could you please try the latest canary release? It has disabled Chromium GPU blacklist (for webgl, so doesn't affect us), which has been reported to resolve this on windows 👍

**Comment by Manubi** [comment]
canary release works for me. thanks

**Comment by herrbischoff** [comment]
I have also tried the Canary version and it's far better than Stable. It's still consuming rather large amounts of processing power but in my limited testing it has shown to cut this rate by about half.

However, the reason for this must lie elsewhere because the Chromium GPU blacklist (https://chromium.googlesource.com/chromium/src/gpu/+/master/config/software_rendering_list.json) does not contain my GPU (`0x0d26`). The closest I have found is [this entry](https://chromium.googlesource.com/chromium/src/gpu/+/master/config/software_rendering_list.json#1546) but then again I'm using macOS 10.13.4.

**Comment by martincartledge** [comment]
hyper is still sucking up a lottttt of cpu...(using canary)
![hyper usage](https://user-images.githubusercontent.com/20777066/53033078-7b668600-342d-11e9-8916-d572c250cf41.png)

**Comment by herrbischoff** [comment]
Closing, since this will obviously not be addressed.
