### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by Zauberklavier** [zeit/hyper#2935]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 & OS X 10.13.4
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Zauberklavier/885b636fe50cef5cbd0ee2cd4ce3ee8c
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

Opening Hyper takes 3-5s on a beefy desktop and on a 2015 Macbook Pro alike. Both machines have fast M.2 SSDs in them so I'd expect Hyper to start instantly.

**Comment by thammuio** [comment]
I am observing around 2 seconds delay to load/open each hyper window. Is there any parameters that I can change to make this delay go away.

Thanks in advance,
Suri
