### ISSUE TITLE
Previewing plugins & themes easily. Right now it's very hard and confusing.

### ISSUE THREAD

**Issue by Ornataweaver** [zeit/hyper#2943]
I installed a couple of themes and they stopped Hyper from working properly. I had to uninstall them one by one until I found out which one was causing the trouble.
A checkbox solution or choose list solution might be nice as well.

also check https://github.com/bnb/awesome-hyper.

**Comment by albinekb** [comment]
You can preview them in the hyper store https://hyper.is/themes

**Comment by Ornataweaver** [comment]
But when I installed a couple of themes together, they merged instead of being selectable.
And it was their merge that caused the problem.

**Comment by Cygnusfear** [comment]
would it be possible to use a hyper:// URI scheme for this maybe for one-click install?

**Comment by albinekb** [comment]
We want the merging still though, some themes only change outside appearance and you can stack them to your liking. Using `hyper://` scheme is dangerous...

**Comment by Cygnusfear** [comment]
I have the same opinion, hyper:// could be used to simply install the package? Then it would still allow for merging&mixing?

**Comment by Ornataweaver** [comment]
What do you nice folks say about checkbox? Like in Stylish (https://userstyles.org/).

**Comment by Ornataweaver** [comment]
I suggest checkboxes.
