### ISSUE TITLE
Option (ALT) + Number Keys don't switch windows in irssi

### ISSUE THREAD

**Issue by Azzhoe** [zeit/hyper#2947]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS High Sierra
- **Hyper.app version**: 2.1.0 Canary
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
When hitting Option (ALT) + number keys on a Mac in irssi, it is suppose to switch screens, but it doesn't, instead its giving me weird characters. How can I change this behavior? In the default terminal.app I was able to fix this by checking the option 'Use Option as Meta Key'

**Comment by JohannesBayerAlbert** [comment]
why was this closed? This bug is still existent and not fixed.

**Comment by abonforti** [comment]
Experiencing the same problem

**Comment by LabhanshAgrawal** [comment]
you can set `altIsMeta` in config

**Comment by abonforti** [comment]
With that enabled, I can't anymore do OPT+5 -> ~.
Is there any way to set altIsMeta per Hyper tab, or set which one of the two options assign to altIsMeta?

**Comment by LabhanshAgrawal** [comment]
I think you can use the esc key also
