### ISSUE TITLE
[FeatureRequest] add 'tab:close' action

### ISSUE THREAD

**Issue by txchen** [zeit/hyper#2951]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MACOS 10.13.4
- **Hyper.app version**: 2.0.0

## Issue
Currently there is no 'tab:close' action, so we can only use `ctrl-d` to close a tab. It is not always working, for example, in a dead ssh session, it will not work.
If we can add this action, then we can configure something like: ctrl+shift+t for open a new tab, ctrl+shift+w to close a tab, IMHO, more easy to remember.

**Comment by chabou** [comment]
You can already close a pane with `ctrl+shift+w`. And if you have only 1 pane it will close the tab.
I think that is enough, no?
At least, you just have to use this shortcut multiple times

**Comment by txchen** [comment]
Oh I see, yes, I can use 'pane:close' instead, that's good enough. Thanks!
