### ISSUE TITLE
Right-Click Paste in Split Pane causes Cursor Jump

### ISSUE THREAD

**Issue by bowersjj** [zeit/hyper#2959]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Win10 v1709 Build 16299.402: 
- Hyper 2.0.0 (stable): 

## Issue

After splitting pane, a right-click to paste in any new pane causes the cursor to jump back to the initial pane.

**Comment by bowersjj** [comment]
I just upgraded to v1803. Cursor stays in correct pane after right-click paste.

**Comment by chabou** [comment]
Thank you for your feedback :pray:

**Comment by mindblastr** [comment]
Hi, I'm getting this bug in version 3.0.2 (stable)
