### ISSUE TITLE
unable to open hyper on mac

### ISSUE THREAD

**Issue by pratik705** [zeit/hyper#2960]
- I am unable to open a hyper application. When I try to do so, nothing happens. It was working fine. but, not sure what happened. Suddenly it stopped working. I didn't make any changes to the application.

- **OS version and name**: Mac 10.13.4
- **Hyper.app version**: Hyper2.0

<img width="1680" alt="screen shot 2018-05-01 at 7 57 04 pm" src="https://user-images.githubusercontent.com/2153643/39488338-d7060dfa-4d79-11e8-8f97-7baf48727f70.png">

**Comment by albinekb** [comment]
Try removing your config,  `mv ~/.hyper.js ~/.hyper.js.old`, and restart hyper, it should re-generate the default config 👍

**Comment by onesev** [comment]
This worked for me. Guess it's time to update my config
