### ISSUE TITLE
Windows network drives cannot be found when using hyper

### ISSUE THREAD

**Issue by anthofo** [zeit/hyper#2964]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 7
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/anthofo/c03d54ac6a4c9a51621201439f8f3bf0
- **The issue is reproducible in vanilla Hyper.app**: Can be reproduced in Vanilla

## Issue

Windows network drives does not seem to work when using hyper. I have a network drive (P:) that cannot be accessed when using hyper:

![ordinateur](https://user-images.githubusercontent.com/3809685/39527777-9c3b8f0c-4e22-11e8-9d5a-9579199e0838.jpg)

![prtscr capture_2](https://user-images.githubusercontent.com/3809685/39527951-12a87466-4e23-11e8-8099-07e6aedc587a.jpg)

(The french error says that the drive cannot be found ;) )

While it works great when using cmd.exe:
![cwindowssystem32cmd2 exe](https://user-images.githubusercontent.com/3809685/39527882-e6d38218-4e22-11e8-8447-e65b636e247f.jpg)

Or Cmder: 
![cmd](https://user-images.githubusercontent.com/3809685/39527889-ec4958ee-4e22-11e8-9cef-8e18ca43cffa.jpg)

I tried with a vanilla hyper and I get the same result

**Comment by albinekb** [comment]
Hmm interesting. I think this is an issue with windows? Maybe it uses cached paths for some reason? Don't know..
