### ISSUE TITLE
Big output crashing terminal since 2.0

### ISSUE THREAD

**Issue by philippedes** [zeit/hyper#2965]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04
- **Hyper.app version**: Latest
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/philippedes/6304a6c595ff4c1efaad4c9c2b4b98f6

## Issue

When having a lot of output, the terminal just freezes and never comes back. Issue is only since 2.0 and is not in the 1.4.8 version. 

I got this doing a `mvn clean verify` on my project and the output is always big.

**Comment by albinekb** [comment]
Can you try the canary release? Instructions is at https://zeit.co/blog/canary#hyper, we have disabled chromium GPU blacklist which caused canvas to run on the CPU for certain GPU setups, even though it's working perfectly fine.

**Comment by RilRil** [comment]
@albinekb seems way better on my old macbook thx

**Comment by philippedes** [comment]
2.1.0-canary.1 works great thanks ! Some of my plugins disappeared (I've got a bar at the bottom that went missing) but it didn't crash. I'll close this issue.
