### ISSUE TITLE
Upgrade to Electron v2

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#2966]
Stable v2.0.0 is out: https://github.com/electron/electron/releases/tag/v2.0.0

We need to test Hyper against this version:
- Study commit changelog to detect possible regression
- Benchmark to notice if there is better performance
- Test if we still need to have this PR: https://github.com/zeit/hyper/pull/2895

**Comment by Stanzilla** [comment]
Test version up at https://github.com/zeit/hyper/pull/2967

**Comment by pecastro** [comment]
Another test version at https://github.com/pecastro/hyper/tree/electron_v2
This was to try to work around the issues described in https://github.com/zeit/hyper/issues/3018.
Hyper window now works but performance is horrible ...

**Comment by jcrben** [comment]
Maybe https://github.com/electron/electron/issues/12695 will be fixed by the time you upgrade - wasted a couple hours of my life 😄

**Comment by EfstathiadisDimitris** [comment]
If this isn't resolved I can take that up..Just give me the go...

**Comment by Stanzilla** [comment]
@EfstathiadisDimitris https://github.com/zeit/hyper/pull/2967 is perfectly fine and ready to go

**Comment by juancampa** [comment]
Closing via https://github.com/zeit/hyper/pull/3458
