### ISSUE TITLE
'hyper' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by beNitinhere** [zeit/hyper#2974]
Hi There,
I just install hyper now using executable file and really i am just loving it but while installing new theme in it. It will showing me above error.Well,I know this is related to System Path but i am unable to find out the System Path of hyper in Windows.I also install hyper in my kali system and as expected hyper rolling like a pro Linux. 

Error Message:
```
D:\Sample>hyper i hyper-whimsy
'hyper' is not recognized as an internal or external command,
operable program or batch file.
```

Thanks in advance.

**Comment by diVineProportion** [comment]
You need to update your environment variables. If you have chocolatey you can type 'refreshenv' in your cmd (hyper or cmd)

**Comment by beNitinhere** [comment]
Yo.
Thanks @diVineProportion

**Comment by gmariani** [comment]
So this isn't taken care of when it's installed then is what you're saying?

**Comment by albinekb** [comment]
It is. But windows caches the PATH variable, so you need a system restart or refreshenv for it to work @gmariani

**Comment by gmariani** [comment]
Gotcha

**Comment by albinekb** [comment]
See https://github.com/zeit/hyper/issues/2823 for the issue that tracks a fix so you won't need to reboot in the future 👍

**Comment by GabrielCereals** [comment]
update the environment variables to what? so far this tread has show me how to show them but nothing about updating them, what if i dont have refreshnev or chocolatey? is there a way to update them manually?

**Comment by Slapbox** [comment]
I've got chocolatey but `refreshenv` is no more defined than `hyper` is.
