### ISSUE TITLE
mac menu preference open another app

### ISSUE THREAD

**Issue by jbohart** [zeit/hyper#2993]
- [x ] Your Hyper.app version is **2.0.0**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

on mac after first start if i click on Hyper menu 's Preferences it open's up another app (RStudio in my case).

Thanks.

  - **Is the issue reproducible in vanilla Hyper.app?**

for me yes.
## Issue

Run Hyper. Click on Mac menu item "Hyper" then click on "Preferences" you'll see it open's another app.

 - **Hyper version**: undefined "2.0.0"

 - **OS ARCH VERSION:** darwin x64 15.6.0
 - **Electron:** 1.8.4  **LANG:** undefined
 - **SHELL:** /bin/bash   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by albinekb** [comment]
It will open your OS default app for `.js` files, so in your case you have RStudio set as default app for `.js`, hence why it opens it. 

Here's a guide to change the default app in macOS https://www.imore.com/how-set-mac-app-default-when-opening-file

**Comment by jbohart** [comment]
Thanks - I should have looked at what file is was open!
