### ISSUE TITLE
What has this to do with Microsoft terminal and...

### ISSUE THREAD

**Issue by fittabile** [zeit/hyper#2997]
.. Why conhost.exe has since been somewahy injeected by  usual worm....? 
I mean: aren't you Nazis and do not work with Microosft to maeke Linux better?
Get serious guys: or you will turn into gay henksmen

**Comment by timothyis** [comment]
If you have an actual issue, please let us know. We don't really understand what you're trying to say but it sounds like you're trying to be offensive.
