### ISSUE TITLE
weird behavior when opening vim in a wide window

### ISSUE THREAD

**Issue by jfhbrook** [zeit/hyper#300]
I tried to take a screenshot:

![](http://i.imgur.com/bHWhO3M.png)

That whiteish (should be red, I blame the theme) bar should be all one line on the far right. I have this problem at other scales as well. I haven't been able to reliably edit a file in vim because of this.

Edit: I guess I would say that it's not always rendering certain kinds of whitespace?

**Comment by ppot** [comment]
@jfhbrook Did you try in the curent master?

**Comment by jfhbrook** [comment]
I tried master as of July 19th, and then walked away cause I had to do work.

If you think current master fixed this problem (knowing why you think this would be 💯), I can certainly try using vim with hyperterm sometimes in the next few days.

**Comment by jaredly** [comment]
![image](https://cloud.githubusercontent.com/assets/112170/24822371/ed1f02f4-1bb1-11e7-9b47-4171f7a83e27.png)
this is in latest master, and vim lines are super messed up (this is split pane). I imagine there's some character vim is using that's not been rendered correctly? or some term command

**Comment by chabou** [comment]
Fixed in our v2
