### ISSUE TITLE
Is it possible for a plugin to execute a command in the running shell?

### ISSUE THREAD

**Issue by rfgamaral** [zeit/hyper#3001]
I've took a look at the documentation available and some plugins source code but couldn't find if this is possible to achieve. My question is pretty much the issue title.

Say that you are running `/bin/bash` on Linux or `cmd.exe` on Windows and on some action - `SESSION_ADD` for instance - you execute a command inside the running instance of bash/cmd.exe/whatever and get the output from that command. Is this possible?

My necessity for such thing comes from hharnisc/hypercwd#16, not sure if there's a better way though.

**Comment by linonetwo** [comment]
I don't know the deeper difference of ```SESSION_PTY_DATA``` and ```SESSION_ADD_DATA```, but I do know that ```SESSION_PTY_DATA``` is syncing text from xterm.js to hyper's screen.

So dispatching this:
```js
({ data, uid }) => ({
  type: 'SESSION_PTY_DATA',
  data,
  uid,
  now: Number(new Date()),
});
```
will add text to hyper's screen, but it will not go into xterm, so when hitting return, xterm just don't know you insert some text.

And old ways:
```js
// term is get from decorateTerm's onDecorated
const terminal = term.keyboard.terminal;
terminal.io.sendString('some command');
```
is not working either, since in hyper2.0 there is no ```keyboard``` in term object, ```term.io``` is not found too.

I am also waiting for an answer.

**Comment by linonetwo** [comment]
I get reference in ```decorateTerm``` like this:
```js
export default (Term: ComponentType<*>) =>
  class DecorateTerm extends Component<*> {
    render() {
      return (
        <Term
          {...this.props}
          onDecorated={terminal => {
            if (this.props.onDecorated) this.props.onDecorated(terminal);
            window.CLI2GUI_TERMINAL_REFERENCE = terminal;
          }}
        />
      );
    }
  };
```

And ```window.CLI2GUI_TERMINAL_REFERENCE.term``` is:
![wx20180512-144035](https://user-images.githubusercontent.com/3746270/39954461-941cfc7a-55f2-11e8-8fed-eb4df0527327.png)
There is no function to insert commands.

**Comment by linonetwo** [comment]
Another thread discussing this https://github.com/zeit/hyper/issues/2754

**Comment by linonetwo** [comment]
There is ```term.write()``` hidden in the proto chain, It can write text to xterm.js, but not the real terminal.

**Comment by ivanwonder** [comment]
I think when the user presses a key, the term will dispatch SESSION_USER_DATA action with the key value.
https://github.com/zeit/hyper/blob/a14c55640c47c4e294095e50a610c5e77d2fad22/lib/containers/terms.js#L53
after the main process receives the user input, the value will be written into the corresponding session which I think it is a terminal instance.
https://github.com/zeit/hyper/blob/a14c55640c47c4e294095e50a610c5e77d2fad22/app/session.js#L89

after the data has been handled. the renderer process will receive the output. and dispatch `SESSION_PTY_DATA` and `SESSION_ADD_DATA`, Finally, it will be shown on the canvas.
https://github.com/zeit/hyper/blob/a14c55640c47c4e294095e50a610c5e77d2fad22/lib/store/write-middleware.js#L10

above is my understand. If wrong, welcome to correct me.

**Comment by linonetwo** [comment]
@ivanwonder  So you think this RPC ↓ 
https://github.com/zeit/hyper/blob/canary/lib/actions/sessions.js#L158
will result in this ↓  call?
https://github.com/zeit/hyper/blob/a14c55640c47c4e294095e50a610c5e77d2fad22/app/session.js#L89
I think to understand the relation between I should read more code.

But good news! I found that this plugin is still working:
https://github.com/curz46/hyper-startup/blob/master/index.js
So to execute a command, just
```js
win.sessions.get(uid).write(cmd + '\r');
```
where ```win``` comes from ```onWindow```.

For input recording, you can have a look at [hyper-history](https://github.com/garyxuehong/hyper-history) or my [refactored implementation](https://github.com/linonetwo/hyper-cli2gui/blob/master/src/store/reducers.js).

**Comment by linonetwo** [comment]
It worked:
https://github.com/linonetwo/hyper-cli2gui/blob/8cd54c5c011a7393d9370f6b7a2a05ca3c108618/src/onWindow.js#L6
RPC to it:
https://github.com/linonetwo/hyper-cli2gui/blob/8cd54c5c011a7393d9370f6b7a2a05ca3c108618/src/store/actions.js#L5

So I think this issue can be closed.

**Comment by ivanwonder** [comment]
why do you need a plugin to execute a command, and what problem the plugin wants to resolve.

**Comment by linonetwo** [comment]
@rfgamaral Does ```hyper-startup``` run in Linux subsystem? It is working at least in Mac OS.

**Comment by rfgamaral** [comment]
@linonetwo It doesn't, just tried:

```
  commands: ['echo "hello world"'],

  localPlugins: [
    'hyper-startup'
  ],
```

After launching Hyper with that configuration:

![image](https://user-images.githubusercontent.com/96476/39974596-be84b324-5721-11e8-82f3-3d328a1511a8.png)

**Comment by linonetwo** [comment]
```win.sessions.get(uid).write(cmd + '\r');``` in ```onWindow``` maybe broken in windows or Windows Subsystem for Linux.

**Comment by rfgamaral** [comment]
Even if it worked, I was going to see the output of the command on the Hyper window, right? Because the idea where would be to run a command in the context of the current WSL session, get the output from that command but never show any signs of that to the user.

**Comment by linonetwo** [comment]
Maybe you can try ```import { exec } from 'child_process';```'s exec. And exec in main process, if you have hyper running in WSL.

**Comment by albinekb** [comment]
Yes @linonetwo, you need to send the correct CWD too, check: https://github.com/Hyperline/hyperline/blob/master/src/lib/plugins/git-status.js#L56-L58 how hyperline is doing it.

**Comment by rfgamaral** [comment]
@linonetwo @albinekb Can you help me out with an example of the above please?

**Comment by linonetwo** [comment]
Hey @rfgamaral , try https://github.com/linonetwo/hyper-visual/blob/master/src/onWindow.js#L7

**Comment by rfgamaral** [comment]
@linonetwo I'm trying your plugin to see how ti works but it doesn't even load for me... I've removed all plugins and even started from scratch by removing `.hyper_plugins/node_modules` and `hyper-visual` is installed but it' never loaded when I launch Hyper. There's no error message and the dev tools console is empty.

**Comment by linonetwo** [comment]
@rfgamaral  That's true, https://github.com/zeit/hyper/issues/3013
But it really works in dev mode. You can try using that code into your plugin.
I don't know why my plugin doesn't load. And hyper's developer is too busy to reply.

**Comment by rfgamaral** [comment]
I was testing your plugin first to quickly check if your approach worked or not and how it worked. But maybe you can answer me this quickly... Does your plugin write the command (when you click it on the quick suggestion) to the terminal in a visible way to the user and you also see the output on the same window, correct?

**Comment by linonetwo** [comment]
@rfgamaral Yes. If you want to exec command silently, you can just replace that line of code to ```exec('some command')``` where ``` import exec from 'sub_process'```.

**Comment by albinekb** [comment]
You can read how hyper launches `bash` here: https://github.com/zeit/hyper/blob/9a536722f8b0a43e8f3741a033d519864f55a957/app/session.js#L53-L58 @rfgamaral, it's using `require('node-pty').spawn`, I think you can do the same in your plugin.

**Comment by linonetwo** [comment]
Wait @rfgamaral , I have another idea.
You can use ```win.sessions.get(uid).write(command);``` to execute a command, and prevent the result being printed on the screen by hijacking SESSION_PTY_DATA and SESSION_ADD_DATA action after some EXTCUTE_COMMAND action.
Do you think it's an option?

**Comment by albinekb** [comment]
I think that's the only option if you need to execute it in the exact same session but without printing the result, I think it's better to spawn a new instance where you do your headless queries in 👍

**Comment by rfgamaral** [comment]
@linonetwo It could be, I'd need to test and see how it works.

> I think that's the only option if you need to execute it in the exact same session but without printing the result(...)

I didn't want to need to execute it in the exact same session but to achieve what I need to fix WSL issues on those plugins, I can't think of any other way.

> I think it's better to spawn a new instance where you do your headless queries in

What doesn't work for what I'm trying to achieve. These plugins rely on the current directory for the current session to work. Spawning a new instance starts at the default working directory, which is no good.

**Comment by rfgamaral** [comment]
@linonetwo Just tried to implement your idea but I don't think it will work either. And now that I think about it, writing a command into the running instance is not an option. Some of these plugins rely `SESSION_ADD_DATA` and they do their thing on this action, meaning that I need to execute my code on these actions too and I can't write something to the window if the user itself is typing there.

**Comment by albinekb** [comment]
Maybe you can use the same way as hyper-statusline finds the current working directory by pid? https://github.com/henrikdahl/hyper-statusline/blob/master/index.js#L329-L358 @rfgamaral

**Comment by rfgamaral** [comment]
@albinekb That plugin does not work with WSL. It finds the current working directory by PID on Linux, not on Windows (WSL is Linux but runs under Windows), on Windows reads the prompt instead (which works fine for Command Prompt and PowerShell, but no WSL). That plugin is actually one of the plugins I'm trying to fix with this...

**Comment by Warmachine13** [comment]
> Wait @rfgamaral , I have another idea. You can use `win.sessions.get(uid).write(command);` to execute a command, and prevent the result being printed on the screen by hijacking SESSION_PTY_DATA and SESSION_ADD_DATA action after some EXTCUTE_COMMAND action. Do you think it's an option?

I'm seen this problem but dont work for now any other solution ?
