### ISSUE TITLE
after reload view, the keyboard shortcuts command will executed multiple times.

### ISSUE THREAD

**Issue by ivanwonder** [zeit/hyper#3004]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows10+x64
- **Hyper.app version**: 2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** no
- **The issue is reproducible in vanilla Hyper.app**: execute menu -> view -> reload,  then create new tab. you will find create tow tabs.

## Issue

  https://github.com/zeit/hyper/blob/a14c55640c47c4e294095e50a610c5e77d2fad22/lib/containers/hyper.js#L56
I think when reload view, the method will create a new Mousetrap, because of the mousetrap do not save and is null.

**Comment by chabou** [comment]
Nice catch.

Thank you for your analyze.

**Comment by ivanwonder** [comment]
@chabou another problem after reload is the active area is empty, it should show the cwd of the current tab. you can try to resolve it.

**Comment by DandyDev** [comment]
I'm running on _canary_ and I still have this problem. I've installed Hyper 10 minutes ago, and changed nothing in the configuration so far (except for the `updateChannel`) and installed no plugins.
