### ISSUE TITLE
How can I start Hyper always with a fixed width/height and in the center of the screen (vertically/horizontally)?

### ISSUE THREAD

**Issue by rfgamaral** [zeit/hyper#3011]
Pretty much the question title. Are there settings available to configure Hyper for this?

**Comment by rfgamaral** [comment]
@romainwn Thanks but I just found out that I can just set the `windowSize` property like this: [bevacqua/dotfiles/hyperterm/.hyperterm.js#L7](https://github.com/bevacqua/dotfiles/blob/9175d6ae51f4fdd941b56a6f9deddd8c10dfeed0/hyperterm/.hyperterm.js#L7) to achieve the same thing without a plugin. I might work on something to center the window on the screen and perhaps open a pull request if the team is interested, if not, publish my first plugin. I'll create a new issue regarding that though :)

**Comment by chabou** [comment]
@rfgamaral It needs more testing but from what I see in the code, this undocumented option is used only at first lunch. Then it saves (position/size) last closed window for next window opening.

For what you want, I would suggest you make a PR to [hyper-window-size](https://github.com/romainwn/hyper-window-size) plugin to add an option `center: true` or something like that.

**Comment by rfgamaral** [comment]
@chabou Actually, it always opes Hyper with the size specified. When you use that option, the size won't be saved and reused for the next window opening. Not for me at least :)

I'd say the `windowSize` feature is working properly, why do you say it needs more testing?

**Comment by chabou** [comment]
It needs more testing from me, sorry.

If you're right, we need to document this config option.

**Comment by rfgamaral** [comment]
Well, if it helps and if it makes a difference, I'm on Windows 10 and I've tested this a couple of times. It always opens with the size specified by `windowSize` no matter how much the app is resized and then closed, it doesn't seem to store that size or if it does, it's not taking precedence over `windowSize`. But please, test it yourself to doubl echeck what I'm saying :)

As for the position of the window, that one is definitely being stored and used when launching Hyper again.
