### ISSUE TITLE
[FIXED] Error updating plugins. An unexpected error occurred: "EACCESS: permission denied, scandir '/Users/$USER/.config/yarn...'

### ISSUE THREAD

**Issue by erikrtn** [zeit/hyper#3012]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra 10.13.4
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/erikrtn/7499dd3da2971f73713f88c0b5841a9b
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

1. `Error updating plugins` every time I launch Hyper:
    ![screen shot 2018-05-12 at 5 34 56 pm](https://user-images.githubusercontent.com/1253422/39961835-9bbae662-560c-11e8-926a-db69ec508586.png)    
2. `hypercwd` not working; new tabs do not open in same directory as existing focus tab. 

## Fix

Seemed like an issue with yarn, so I installed yarn via npm (see advice from #858):

```
npm i -g yarnpkg
```

Now the error no longer appears and `hypercwd` is working.

**Comment by chabou** [comment]
Hyper uses an embedded version of `yarn`, but I think there was a problem with your `~/.config/yarn` directory structure/rights and has been fixed by installing yarn globally.

If anybody has same issue, please check these folder rights.

Thank you so much for your feedback :pray:
