### ISSUE TITLE
Unusable Hyper v2 in Linux

### ISSUE THREAD

**Issue by pecastro** [zeit/hyper#3018]
- Linux Fedora 25
- Hyper built of canary branch, also tried hyper-2.1.0-canary.1.x86_64.rpm
- Default hyper.js
- Is Vanilla

Hyper is a bit laggy and completely unusable with rendering issues.

https://www.youtube.com/watch?v=e6SA0yfYqSA

**Comment by pecastro** [comment]
@Stanzilla This issue is specifically about canary Hyper. It was mentioned in the upgrade to v2 for reference only.
So still pretty much unusable if you install via RPM or build of the canary branch.

**Comment by Tyriar** [comment]
@Stanzilla doesn't Hyper have `--disable-gpu-blacklist`? If so, note the problem can go the other way and `--disable-gpu` may alleviate the problem.

**Comment by Stanzilla** [comment]
@Tyriar it does, yeah. 

@pecastro wanna try that? add `disable-gpu` around here https://github.com/zeit/hyper/blob/canary/app/index.js#L90

**Comment by pecastro** [comment]
Nopes still the same.
I forgot to mention that the behaviour in video doesn't happen with Electron 2.0.0 or 1.7.5.

**Comment by Stanzilla** [comment]
oh okay, that's good.

**Comment by pecastro** [comment]
Latest canary build works like a charm.
