### ISSUE TITLE
Cant install any plugin (windows)

### ISSUE THREAD

**Issue by HitarthChudgar** [zeit/hyper#3027]
Whenever I try to install a plugin on hyper I get the following error,

![capture](https://user-images.githubusercontent.com/20516641/40184645-d1d93bf6-5a01-11e8-8d63-d0b57cd892ad.PNG)

**Comment by jaydh** [comment]
The warning you're getting has a typo that has since been fixed and should read "you can't use CLI commands here." You should still be able to install plugins easily by editting the config file

**Comment by chabou** [comment]
@jaydh Thank you. Yes typo has been fixed by #2945 

@HitarthChudgar You can open a regular CMD or PowerShell to execute CLI. (Or yes, editing config manually)
