### ISSUE TITLE
Underscore not showed when typing under fontSize 14

### ISSUE THREAD

**Issue by FirstWorldSlardar** [zeit/hyper#3029]
Hi guys !
To be quick, the underscores are not visible when I type and font size is set to 14. For any other font size  it seems to work otherwise (weird ^^)

*Env*
Ubuntu 16.04
Hyper 2.0.0 and 2.1

Ciao !

**Comment by chabou** [comment]
Please respect our issue template.
And simple search with `underscore` would have shown you that an issue already exists for this: #2812

BTW, thank you for your feedback
