### ISSUE TITLE
truncated string output with emojis

### ISSUE THREAD

**Issue by zeke** [zeit/hyper#303]
Hyperterm is removing the last character of these emoji strings I'm logging. The same code in Terminal.app does not have this effect. I thought maybe it had something to do with some emojis being a composite of two characters, but the truncation seems to be happening on all emojis.

<img width="84" alt="screen shot 2016-07-18 at 10 35 22 pm" src="https://cloud.githubusercontent.com/assets/2289/16974952/4b077b8e-4dff-11e6-967c-fe3cd641b78f.png">

macOS 10.11.4
hyperterm 0.6.0

**Comment by albinekb** [comment]
Can you provide an example to run?

**Comment by zeke** [comment]
```sh
node -e "console.log('🍦 icecream')"
```

In Hyperterm:

![screen shot 2016-07-21 at 2 48 30 pm](https://cloud.githubusercontent.com/assets/2289/17040015/45f460f4-4f52-11e6-9380-a2d8856c2cd5.png)

In Terminal.app:

![screen shot 2016-07-21 at 2 48 51 pm](https://cloud.githubusercontent.com/assets/2289/17040023/4e610ac6-4f52-11e6-8f4f-4f0a06fb167f.png)

**Comment by MichaelArestad** [comment]
I found something similar when using emoji in my prompt.

You can kind of see it under the cursor:
![image](https://cloud.githubusercontent.com/assets/1123119/17061475/4c42dc86-4ff4-11e6-89c9-22ab2997e9bd.png)
If I just hit return, it retains the last character. If I type a command, it replaces them:
![image](https://cloud.githubusercontent.com/assets/1123119/17061534/9eec3130-4ff4-11e6-93bf-ff1810afb61e.png)
![image](https://cloud.githubusercontent.com/assets/1123119/17061556/b27f42e6-4ff4-11e6-8a03-bb66a9829a61.png)

**Comment by scottluptowski** [comment]
@MichaelArestad A few similar issues over at #154

**Comment by chabou** [comment]
fixed

**Comment by zeke** [comment]
Thanks!
