### ISSUE TITLE
Error while installing anything using hyper

### ISSUE THREAD

**Issue by DarkAbhi** [zeit/hyper#3031]
# darkabhi at arch in ~ [19:15:33]
→ hyper i hypercwd     
running in prod mode
electron will open file:///usr/lib/hyper/resources/app.asar/index.html
Failed to symlink Hyper CLI { Error: EACCES: permission denied, symlink '/usr/lib/hyper/resources/bin/hyper' -> '/usr/local/bin/hyper'
  errno: -13,
  code: 'EACCES',
  syscall: 'symlink',
  path: '/usr/lib/hyper/resources/bin/hyper',
  dest: '/usr/local/bin/hyper' }
Checking for notification messages
No matching notification messages

**Comment by DarkAbhi** [comment]
Well IDK why this requires root but it shouldn't

**Comment by jaydh** [comment]
This problem has been raised before. Symlinking to /usr/bin/local should indeed require root privileges. The idea was originally that you could symlink the CLI script to a command that would be run from a shell, but this has created problems for Linux. See [here](https://github.com/zeit/hyper/issues/2998)

On upstream, CLI installation silently fails for linux distributions. I've submitted a PR [here](https://github.com/zeit/hyper/pull/3024) that circumvents this issue if you're interested.

**Comment by DarkAbhi** [comment]
I see good job with the fix 👍

**Comment by think01** [comment]
Congratz for the fix. Hopefully they'll integrate it as soon as possible.
In the meantime, is there any workaround for this issue? I cannot install even a simple theme!

**Comment by kauegimenes** [comment]
@DarkAbhi why this issue was closed? I still have this issue in the last hyper version.
