### ISSUE TITLE
How could I download Hyper if it keeping failed all the times?

### ISSUE THREAD

**Issue by nntoan** [zeit/hyper#3035]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04 - Bionic Beaver
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I can't download the Ubuntu (.deb) version from the bloody AWS link. It's keeping failed all the time, can you please consider to have a mirror link for all releases?

It's weird that this does not happen if I download the Windows or macOS version. :'(

**Comment by nntoan** [comment]
I will close this ticket. Poor me :(

**Comment by albinekb** [comment]
Did you get it working? 🙏 @nntoan

**Comment by nntoan** [comment]
@albinekb Sometimes I'm able to download with 20kb/s, sometimes I can't. The connection will be drop while you downloading.
