### ISSUE TITLE
hyper terminal cannot support fish shell.

### ISSUE THREAD

**Issue by floatflower** [zeit/hyper#3043]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Home
- **Hyper.app version**: Hyper 2.0.0 (stable)

## Issue

I connect with my linux server via SSH, on my server, I use **fish shell** and **powerline**, fish shell features command auto-complete, but on hyper 2.0.0 it cannot support fish shell.
like this: 
![Imgur](https://i.imgur.com/J9B6P9a.png)

**Comment by KirbMountainOfficial** [comment]
Hmm, you must have to manually edit the code.

**Comment by NuclearCookie** [comment]
Using fish shell on without ssh seems to work. I use a fish shell with powerline inside hyper for my daily work.

**Comment by Alxandr** [comment]
Yeah, this seems to be a hyper on windows issue:

![image](https://user-images.githubusercontent.com/112334/42224956-a6fe1394-7edb-11e8-9931-a14090911a5f.png)


In particular, it seems to be an issue with handling of control codes like newline. I see a `⏎` after each command I run.
