### ISSUE TITLE
text search missing

### ISSUE THREAD

**Issue by roccomuso** [zeit/hyper#3050]
Hyper doesn't have a default "search" function built-in and the `hyper-search` plugin has issues and doesn't work with the latest hyper 2.0.0.

**Comment by chabou** [comment]
`xterm` has an addon for this.

We should maybe use it.

**Comment by Tyriar** [comment]
This should be pretty easy to add, you just need a popup with a text box and 2 buttons to hook up to https://github.com/xtermjs/xterm.js/blob/master/src/addons/search/search.ts

**Comment by El-Dringo-Brannde** [comment]
@chabou @Tyriar I could pick up the feature request? Even if it isn't needed in core, I could use the PR for my OSS class.
