### ISSUE TITLE
Option to configure buffer length

### ISSUE THREAD

**Issue by crostine** [zeit/hyper#3055]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows 10 version 1803
- **Hyper.app version**: 2.0.0 stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/crostine/2d3e78e22261b232cc703b26b16bf312
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue

I noticed after updating to 2.0.0 stable that the maximum number of lines in a terminal window changed from something rather large to 999 which is fairly short.
Is there a workaround for this?
Could the number of lines be changed to an option in the config file?

**Comment by chhschou** [comment]
Please see #280 and PR #3056

**Comment by chhschou** [comment]
#3038 that implements an option to configure scollback has been merged.
Please try the new options with the latest Hyper Canary.

**Comment by crostine** [comment]
👍
