### ISSUE TITLE
How reliable is the SESSION_SET_XTERM_TITLE action to read the working directory absolute path?

### ISSUE THREAD

**Issue by rfgamaral** [zeit/hyper#3058]
The `SESSION_SET_XTERM_TITLE` action is dispatched when the xterm title is changed (for instance, `cd` to a different directory triggers this) and it includes the working directory absolute path, prefixed with `user@host`. AFAIK, this comes from [Xterm.js](https://github.com/xtermjs/xterm.js/).

Excluding Windows shells (like Command Prompt or PowerShell), **how reliable would is this event to read the working directory absolute path and use it within plugins?**

I'm asking these because plugins like [hypercwd](https://github.com/hharnisc/hypercwd) and [hyper-statusline](https://github.com/henrikdahl/hyper-statusline) rely on running Linux/Windows commands to read the current working directory absolute path and do their thing. But this doesn't work with Windows Subsystem for Linux (WSL). If instead they read the working directory from the title (for Linux / WSL only), we could get this plugins to work with WSL easily.

Would love some input from @chabou and @Tyriar on this. Everyone feel free to contribute too :)

**Comment by rfgamaral** [comment]
Nevermind, I realized that the xterm title could be something entirely different set by specific shell configurations like Bash or Zsh. This is not reliable at all.

**Comment by Tyriar** [comment]
The `title` event doesn't fire for cwd changes, it changes when the program wants to set the title of the terminal. I'm not 100% sure what programs support this.
