### ISSUE TITLE
Hyper CLI doesn't work on macOS

### ISSUE THREAD

**Issue by sebastianks** [zeit/hyper#3078]
Hey

I've installed Hyper twice now on my brand new Macbook, and even though I restart the machine I can't use `hyper i verminal` or any other commands. What am I doing wrong?

**Comment by Pavel-Durov** [comment]
@sebastianks I just installed on my Mac and it's working fine. 
+ What kind of output do you get? 
+ Can you lunch hyper not through the terminal?

**Comment by MAPESO** [comment]
@sebastianks Hi👋 It would be great if you could provide us with more information to help you 🙏 ❤️

**Comment by sebastianks** [comment]
Hi both. All of a sudden it's working today. Even though I restarted my mac several times it didn't work, but today after turning on my mac it's working just fine. Weird, but great.

Thank you for your time 👍
