### ISSUE TITLE
MacOS: Opt+del deleting 2 words instead of 1.

### ISSUE THREAD

**Issue by cwagner22** [zeit/hyper#3080]
- [x] Your Hyper.app version is **2.0.0**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue

When typing a command:
`Option+left/right` should navigate between each word like it does in the native terminal but instead skip 2 words instead of 1.
`Option+del` should delete 1 word but instead deletes 2.

**Comment by albinekb** [comment]
Could be the same issue as https://github.com/zeit/hyper/issues/2652 that the handlers are being duplicated? 🤔 Can you try `canary` updateChannel? (change in your .hyper.js)

**Comment by cwagner22** [comment]
Working in `canary`, thanks!
