### ISSUE TITLE
Theme color not working

### ISSUE THREAD

**Issue by hg75** [zeit/hyper#3081]
When I install a new theme, the colors do not update. No colors are changed. I have seen some fixes like export CLICOLOR=1, but all that does is make my folders blue when I type cd. Can someone please guide me what changes I need to make that dont hardcode shell configurations/colors, so I can use the themes just like anyone else?

**Comment by albinekb** [comment]
Please fill in the issue template so we can help you. We need to know your OS, version of Hyper and if you have any errors. And your .hyper.js config.
