### ISSUE TITLE
Hyper CLI won't open on MacOS High Sierra

### ISSUE THREAD

**Issue by irislieuw** [zeit/hyper#3082]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS High Sierra v10.13.2
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/irislieuw/83d6e555b368e83cbf65aab5f5e83ad0
- **Relevant information from devtools**: N/A 
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Hyper won't open on my Mac. I've re-installed multiple times but the Hyper app just won't open. I get notifications from Hyper about configurations changing if I try to modify .hyper.js, I can open dev tools, access the Hyper toolbar, but the actual CLI doesn't show up no matter what I try. 

I've tried installing from https://hyper.is/#installation and using brew - both run into the same issue.

Running hyper via terminal on verbose mode shows this: 

```
Iriss-MacBook-Pro:~ irislieuw$ hyper -v
running in prod mode

electron will open file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html

2018-06-12 13:20:36.219 Hyper[3191:86516] *** WARNING: Textured window <AtomNSWindow: 0x7fed00eefa10> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

[3191:0612/132036.227699:ERROR:render_widget_host_view_mac.mm(707)] Failed to create display link.

Checking for notification messages

No matching notification messages
```

Anyone have any idea what could be going wrong?

**Comment by Luttos** [comment]
There is some Osx update available? Actually on 10.13.5 (here), seems the "error" is with window on MacOs

**Comment by ad-on-is** [comment]
Same issue here....
seems like hyper is starting, and you can actually type in commands, but the window is not rendering

**Comment by 311chaos** [comment]
Same for me. Stopped using this a week or so ago because the window is not visible.

**Comment by divyanshu013** [comment]
Hey guys did you find anything on this? I think I'm facing same issue [spectrum](https://spectrum.chat/?t=c1b846d2-d1e6-4a44-8553-7dd19212c7be)

**Comment by divyanshu013** [comment]
Hi team, I forked the repo to try and debug this. I notice the same issue when running in dev mode. The window doesn't appear and there are no error messages in the console. However, when I try to run the app in debug mode via vscode, it works. Any pointers on how I can debug this issue in dev mode? Thanks!

**Comment by jcrben** [comment]
Do you see anything in the mac crash logs?

For me they are in e.g. `/Users/bencreasy/Library/Logs/DiagnosticReports/Electron2018-05-27-100346_sfo-bcreasy-l.crash` - I encountered this for https://spectrum.chat/?t=2fe9e5b0-09cf-489e-a1ba-1765a667147c altho it's a different situation

**Comment by divyanshu013** [comment]
This could be related, will dig around later and get back.

**Comment by divyanshu013** [comment]
Hi @jcrben tried but couldn't find any relevant logs in the directory.

**Comment by robgarden** [comment]
I managed to get my hyper window back by clicking on **Window** -> **Zoom** in the toolbar

**Comment by divyanshu013** [comment]
Woah man, it worked. Now I can get back to hyper instead of the stock terminal. Thanks 😄

**Comment by irislieuw** [comment]
Wow, that also worked for me! Thanks!! 🎉
