### ISSUE TITLE
Symlinks are not followed on macOS

### ISSUE THREAD

**Issue by aakay** [zeit/hyper#3085]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  
- **OS version and name**: macOS High Sierra
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/aakay/3c5316f30a7395b405bcb9a29ff6f448
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
On macOS home folder, my symlinks stopped to be followed. An example can be seen on the screenshot below.

![image](https://user-images.githubusercontent.com/17157374/41402300-3aef5460-6fc2-11e8-97c7-2675f2906cd7.png)

PS: I've removed all plugins and themes, all configs and reinstalled hyper. This is a screenshot from vanilla installation.
PPS: Built-in terminal is working fine.

**Comment by aakay** [comment]
Sorry, it was my fault... Sorry about the inconvenience...

**Comment by thedonquixotic** [comment]
@aakay  How was it your fault? How did you fix the issue? I think I'm having a similar problem.

**Comment by aakay** [comment]
@thedonquixotic In my case, it was pointing to an external, encrypted thumb drive, which was not decrypted and/or mounted at that moment.

**Comment by thedonquixotic** [comment]
Ah not the same issue I'm having then. It's pointing to a different folder on the same drive.
