### ISSUE TITLE
Blank Window on Canary 

### ISSUE THREAD

**Issue by reap-r** [zeit/hyper#3093]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate but has been closed without a valid fix

- **OS version and name**: 4.16.13-2-ARCH
- **Hyper.app version**: 2.1.0-canary.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Link](https://gist.github.com/reap-r/55daf20ee652d90e473f98140882caad)
- **The issue is reproducible in vanilla Hyper.app**: Yes, Breaks event without plugins

## Issue
The screen randomly just blanks out when either using the `ls` or repeatedly using the `cd` command as I've observed. 
![screenshot from 2018-06-20 13-41-41](https://user-images.githubusercontent.com/10115336/41639477-7b6ce1a6-7490-11e8-9821-abb38a5af42b.png)
![screenshot from 2018-06-20 13-41-57](https://user-images.githubusercontent.com/10115336/41639476-7b414bfe-7490-11e8-8bb4-8566368f1535.png)

**Comment by yoannfleurydev** [comment]
If it can help, I have the same issue, this weird black square, but it only appears after unlocking my i3lock lockscreen.

**OS Version and name**: 4.17.5-1-ARCH
**Hyper.app version**: 2.0.0

**Comment by mcornella** [comment]
Same happening on my end using v2 stable, after returning from suspension (after lock screen, as @yoannfleurydev):

![captura de pantalla 1](https://user-images.githubusercontent.com/1441704/43150936-74668eb6-8f6b-11e8-8152-2b745500cb6b.png)

**OS Version and name:** Windows 10 1803 build 17713
**Hyper.app version:** 2.0.0 stable

If I click View > Reload or View > Full Reload nothing happens. Only after I clicked Windows > Toggle Full Reload did I get a screen with the basic outline but no text:

![captura de pantalla 2](https://user-images.githubusercontent.com/1441704/43150838-30ea6946-8f6b-11e8-97d9-0cab02e52b1f.png)

I can't reliably reproduce it though; I think I have to wait a few minutes before going back from suspension to get it to happen again.

**Comment by jdalrymple** [comment]
Any updates on this? I really want to use this terminal, but this is definitely stopping me from doing so.

**Comment by jdalrymple** [comment]
This is still happening for me on the latest release

**Comment by jdalrymple** [comment]
I did some testing locally. I see no errors in the log while debugging. Ill keep looking

**Comment by jdalrymple** [comment]
Hasnt happened to me since the latest update :(

**Comment by abyss7** [comment]
Have this issue on any massive output: simple `tree /` causes it.

If devtools are open, then it shows me a message like "Devtools disconnected from page". Also, in console log of Hyper I can see:

    [17141:0100/000000.039599:FATAL:memory.cc(22)] Out of memory. size=262144

Ctrl+Shift+F5 (Full reload) helps to revive the window, but loses all opened tabs.

**Comment by abyss7** [comment]
It looks like the problem is with scrollback buffer - if I set config option `scrollback: 500` the Hyper lives much longer. Also the number 262144 is 2^18, which looks like exponential allocation of some expanding object - my guess, it's a string to store the scrollback. Another observation is about the scrolling speed: until the command `tree /` doesn't finish the output feed is very-very slow, but it speeds up after all the output is available.

I think I can debug this issue, but I need some technical advise about where I can start - I don't know how to debug Electron applications or xterm.js
