### ISSUE TITLE
plugins not loading

### ISSUE THREAD

**Issue by idanlo** [zeit/hyper#3097]
- [x] Your Hyper.app version is **2.0.0**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**
don't know how to check

## Issue

plugins are not showing so i checked my package.json and saw that none of my plugins are there so i npm installed it manually and it still doesn't load them up. tried reinstalling like 3 times

 - **Hyper version**: undefined "2.0.0"

 - **OS ARCH VERSION:** win32 x64 10.0.17134
 - **Electron:** 1.8.4  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true
}

          {
  "plugins": [
    "hyperborder",
    "hyperterm-terminal",
    "hypercwd",
    "hyperterm-tab-icons",
    "hyper-blink",
    "hyperterm-cursor",
    "hyperpower",
    "hyper-alt-click"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by linonetwo** [comment]
Did you found out why? My plugin is not loading too.

**Comment by idanlo** [comment]
No, I just stopped using hyper

**Comment by MoonCh0w** [comment]
Plugins stopped working for me.

**Comment by linonetwo** [comment]
> Plugins stopped working for me.

@MoonCh0w I got it work by fork a currently working plugin and refactor based on it.
