### ISSUE TITLE
Hyper CLI WSL warning contains a typo

### ISSUE THREAD

**Issue by AlexGustafsson** [zeit/hyper#3102]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro (1803) / WSL (Ubuntu 4.4.0-17134-Microsoft)
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: clean install, uses bash
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

When running hyper cli commands using bash (WSL) a warning regarding lack of support for WSL appears. However, the warning contains a typo:

```diff
- Warning! Due to WSL limitations, you can use CLI commands here. Please use Hyper CLI on cmd,
+ Warning! Due to WSL limitations, you can't use CLI commands here. Please use Hyper CLI on cmd,
PowerShell or GitBash/CygWin.
Please see: https://github.com/Microsoft/WSL/issues/1494
```

**Comment by snaka** [comment]
Typo has been fixed in #2945

**Comment by AlexGustafsson** [comment]
@snaka What’s the policy on closing issues in this repository? Once the change makes it into a released stable version or as quickly as it’s been fixed?

**Comment by albinekb** [comment]
We usually close them when it's merged, so we know what we need to work on :) Thanks for reporting this, it will be released in the next version.
