### ISSUE TITLE
Annoying sounds

### ISSUE THREAD

**Issue by gerchicov-bp** [zeit/hyper#3103]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- OSX 10.13.4
- 2.0.0

## Issue
The app spams with sound on each action. Option to disable sound doesn't work too. The app spams sounds even when you open/edit the configuration file (while it is opened in another application).
In general why do you use default system notifications? It may be easy for you but really annoys users! And why don't you provide an option to disable notifications instead of "disable sounds" which doesn't work?

**Comment by gerchicov-bp** [comment]
@albinekb TextWrangler automatically opens it. I tried these options - the app spammed until I disable the notification sounds completely via global system preferences

**Comment by bootstraponline** [comment]
> it shouldn't spam notifications

The notification spam is for those with the save after delay configuration.

![image](https://user-images.githubusercontent.com/1173057/45333362-c9549500-b543-11e8-87b5-03530aada21e.png)

I had to drop hyper to avoid the spam.
