### ISSUE TITLE
Hyper Errors and graphic problem

### ISSUE THREAD

**Issue by BJ4K3** [zeit/hyper#3109]
- [x] I am on the [latest] Hyper.app version
- [X] I have searched the [issues] of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 19 Tara
- **Hyper.app version**: Hyper 2.0.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  Just installed, no modifications
- **The issue is reproducible in vanilla Hyper.app**: IS Vanilla

Hi, as writed i had just installed hyper after the upgrade from linux mint 18.3 Sylvia to Linux mint 19 Tara, but after that these errors and the cut at the top of every row are appeard.

![screenshot_20180629_230138](https://user-images.githubusercontent.com/24866089/42115128-04c67c60-7bf2-11e8-9c5b-36b1c5e7f35d.png)

**Comment by SandTOfficial** [comment]
Ok, sorry for the inconvenience,I searched for some other time and I found a working solution for the line spacing, but the other errors persist.

**Comment by SandTOfficial** [comment]
Ok, after some hours of research I found a answer to the errors but the line spacing problem persist.

![screenshot_20180630_184012](https://user-images.githubusercontent.com/24866089/42127256-1476407a-7c95-11e8-945b-18a1c67a21bd.png)
