### ISSUE TITLE
allow chaning initial path when launching hyper

### ISSUE THREAD

**Issue by zanona** [zeit/hyper#3110]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.0.0
- **The issue is reproducible in vanilla Hyper.app**:  `Is Vanilla`

## Issue

When using hyper on Windows with WSL like Ubuntu, I use the shell option defined to `shell: 'C:\\Windows\\System32\\bash.exe'` which works great.
However it will always open a terminal window under `/mtn/c/Users/username` instead of `~/` .
It would be nice to have an option where we can define the initial path that is applied once opening a Hyper window. like

`initialPath: '~/'`

**Comment by harryparkdotio** [comment]
This can already be achieved, and has been 'reported' as an issue here before. #1998

**Comment by zanona** [comment]
That's great! Thanks for referencing this and sorry I didn't spot it previously.
