### ISSUE TITLE
MacOS cursor color

### ISSUE THREAD

**Issue by xiaoyu-tamu** [zeit/hyper#3119]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **MscOS High Sierra**: 
- **Hyper.app 2.1.0-canary.2**: 

## Issue

Is there any configuration to change the cursor's color? It's really hard to find the cursor in dark background. I can't take a screenshot because the cursor is not visible in the picture.

**Comment by ravinggenius** [comment]
Switching to a theme with a light background (`hyper-solarized-light`) acts as a temporary "solution", but the default theme renders the mouse pointer virtually invisible.

**Comment by AuHau** [comment]
You can use the workaround presented in #1045
