### ISSUE TITLE
Error while spliting or adding new tab

### ISSUE THREAD

**Issue by aissasell** [zeit/hyper#3121]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 pro
- **Hyper.app version**: 2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/aissasell/4a269e876d4136f4c67588b97d4fc125
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Using Powershell as default command line with the framework oh-my-posh. and i also use the plugins: ['hypercwd', 'an-old-hype']
## Issue
My issue is that the split windows function and the new tab work verry fine till i use a type of watch files command. For example when i run php server from the terminal or i watch scss and css files.. i get this type of error
![screenshot_2](https://user-images.githubusercontent.com/17217604/42431100-40dd3554-833b-11e8-9d74-911aab0b5086.png)

**Comment by Noext** [comment]
same issue using bash as shell on windows 10 1803

**Comment by mdh34** [comment]
uninstalling hypercwd fixed this for me

**Comment by ivanreese** [comment]
Switching from hypercwd to https://github.com/LeanderFS/hypersamewd fixed this issue for me.

**Comment by ppot** [comment]
Closing due to plugin related.
