### ISSUE TITLE
hyper not showing terminal anymore on macOS

### ISSUE THREAD

**Issue by ad-on-is** [zeit/hyper#3128]
After playing around with hyper, it suddenly stopped working. No terminal window is shown. Neither when I start the app, nor when I open a new window or tab.

I tried to reinstall hyper, and I also removed .hyper.js and .hyper_plugins from my home-folder, without success.

Strange behaviour, when I hit CMD+N a few times (to open new windows) and then right-click on the dock icon and click on "Show all windows", that's what it shows.
![image](https://user-images.githubusercontent.com/9553253/42737444-b0e65e06-8873-11e8-98d8-ba3cb619dc3c.png)

Tried both, stable and canary.
macOS 10.13.5

Are there any other files I have to delete?

**Comment by syrkis** [comment]
Also having this issue. I've reset the ~/.hyper.js config file and reinstalled hyper..

**Comment by zachChilders** [comment]
This happened to me as well on windows.  Removing my .hyper.js file resolved it.  No weird plugins or anything.

**Comment by robgarden** [comment]
This fixed it for me: https://github.com/zeit/hyper/issues/3082#issuecomment-426236075
