### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by Webtica** [zeit/hyper#3139]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64Bit - Build 1803
- **Hyper.app version**: 2.0.0 Windows
## Issue
Hi, 
I am trying to install on windows but i get the following error twice during install.
I just downloaded the latest installer from hyper site itself. 

Screenshot: 
https://i.imgur.com/aZqzAfd.jpg

Thanks
Dieter

**Comment by bgrc** [comment]
+1

Screenshot:
https://xings.oss-cn-shanghai.aliyuncs.com/image/hyper.gif

**Comment by Stanzilla** [comment]
disable your plugins
