### ISSUE TITLE
Provide current version number on website

### ISSUE THREAD

**Issue by MartinMuzatko** [zeit/hyper#3153]
## Issue

Hey there. This issue is not related to the software per se.
 
It would be nice to see the latest official version of hyper on the website near the download buttons.
This way, I quickly know if a known bug is already resolved.

Hyper in the shell tells me "2.0" is the latest version, 
Github Releases says 2.1 is the latest one.

Maybe it would be nice to also note what release channel is on which version.

**Comment by thedonquixotic** [comment]
Agreed.

**Comment by albinekb** [comment]
Github tells you 2.0 is the latest stable release:

![image](https://user-images.githubusercontent.com/5027156/43904542-3424ec90-9bef-11e8-8d66-d74c4db26776.png)

**Comment by MartinMuzatko** [comment]
> Github tells you 2.0 is the latest stable release
Duh, I know how to find out what the latest stable release is.
You also add download buttons to the website because you would hate to point your users to "just browse the releases page on github".
I'm talking more about a usability service for your users, not for my personal question.

You can find out the latest version using the github API:
``` json
response = await fetch('https://api.github.com/repos/zeit/hyper/releases')
releases = await response.json()
latestStable = releases.find(release => !release.prerelease)
console.log(latestStable.tag_name)
```

That can be embedded in hyper.is. Or if there is a build setup for hyper.is, you could pass it as environment variable and read it out then.

**Comment by albinekb** [comment]
Yes, that is a valid point 👍 I think we should add it to the website but I was quick and just showed you how to find it, sorry.

**Comment by albinekb** [comment]
We're using next.js for hyper.is, the code is open source over here: https://github.com/zeit/hyper-site

**Comment by MartinMuzatko** [comment]
Yes please. if you can't move it (didn't know github can do that) I'd like to open a new issue.
