### ISSUE TITLE
Constant annoynaces from Hyper on node module plugin issues

### ISSUE THREAD

**Issue by thedonquixotic** [zeit/hyper#3159]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10 with WSL Ubuntu 18**

## Issue
Every single time I open it, it complains about being unable to change node_modules. So I deleted node modules and let it rebuilt stuff but then this happens:

![image](https://user-images.githubusercontent.com/9451726/43746823-26bdc2d8-99ac-11e8-82f9-4090780e0857.png)

I've seen this before. A couple of weeks ago when I first started getting Hyper set back up on my windows machine, and it seemed to mostly go away once I deleted my hyper_plugins folder. Since then I finally got my Linux cloud server up, and spent a bunch of time using a couple of boring native terminals and.... well.... I like Hyper as a project but I'm not sure if this is worth all the trouble, espc as I'm a new developer and when stuff breaks it mostly just confuses me.

 I thought the idea that it was built on web tech, which I'm learning, was rad, meant I could modify stuff on my own etc, but this is just adding a bunch of dead weight to my workflow. 

I'm now downloading and trying out Terminus: https://github.com/Eugeny/terminus

If there is a fix, then I would love to try it but it seems that this thing is adding too much extra weight to my workflow. 

Also, I think a big problem is that a lot of plugins were broken by some of the last couple of updates, and the developers who were working on those plugins went completely MIA. Due to the fact that the default way to install Hyper plugins is via adding it's name to the plugins array in the settings file, when a plugin is abandoned, and someone else takes up the lead with a fork with a different name, it leads to a whole lot of fracturing of the process. There really needs to be a better way to look up information about what plugins are current or supported, more than what NPM based solution etc is currently supplying at least.

**Comment by thedonquixotic** [comment]
Also I've tried out a bit of Terminus and while it lacks some of the features of Hyper, it also has some features Hyper should really look at emulating.

**Comment by chabou** [comment]
This issue has been fixed in our last canary release https://github.com/zeit/hyper/pull/2940

**Comment by thedonquixotic** [comment]
@chabou Thanks! I will try that out.
