### ISSUE TITLE
Error updating plugins in Mojave

### ISSUE THREAD

**Issue by icarlossz** [zeit/hyper#3169]
- [ X ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ X ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Mojave 10.14
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/icarlossz/1aad4988f3744657eb77f0fa5da496a8

## Issue
I updated my computer to the latest beta of MacOS Mojave and the hyper plugins didn't work again with hyper-cli or putting them directly into the hyper.js file. I already used two different versions of hyper, uninstall and install several times and I have the same problem.

<img width="1080" alt="screen shot 2018-08-12 at 10 05 11" src="https://user-images.githubusercontent.com/5649014/44003431-30eaef9a-9e18-11e8-98b1-8d3eb138faaa.png">

**Comment by icarlossz** [comment]
The problem was mine, apparently Mojave comes with some permitting problems, I followed these steps and everything works perfectly!

[https://support.apple.com/es-co/HT203538](https://support.apple.com/es-co/HT203538)

**Comment by sobolevn** [comment]
The same happens to me on older version of macos.
![2018-11-09 11 48 38](https://user-images.githubusercontent.com/4660275/48261501-617dd600-e430-11e8-9f40-85845fb5f49e.png)

I was not able to fix it with the provided article: https://support.apple.com/en-en/HT203538
But, I have disabled notifications sound in the `macos` settings. Now it does not bother me.

It seems like it does not cause any other problems except this notification.
