### ISSUE TITLE
Pane above / Pane below key-bindings

### ISSUE THREAD

**Issue by tomleo** [zeit/hyper#3171]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04.5 LTS (Xenial Xerus)
- **Hyper.app version**: Hyper 2.1.0-canary.2 (stable)

## Feature Request
For pane navigation the only options are `pane:next` and `pane:prev`, however when navigating panes in similar software (i.e. terminator, vim, tmux, ect.) there are options for *pane left*, *pane right*, *pane above*, *pane below*. Having these additional key-bindings is super useful.

**Comment by chabou** [comment]
Please use `hyper-pane` plugin 😉

**Comment by tomleo** [comment]
@chabou it didn't seem like key bindings we're configurable with the `hyper-pane` plugin. Is this not the case? Should I open a feature request on that project page?

**Comment by chabou** [comment]
You can configure hotkeys for each`hyper-pane` like moving up, down, left, right or jump directly to a numbered pane.

Please open an issue in its repo or send a PR if the README is not clear enough 🙏

**Comment by tomleo** [comment]
Opened issue in `hyper-pane` repo.
