### ISSUE TITLE
Support the new ConPTY facility on Windows

### ISSUE THREAD

**Issue by spegoraro** [zeit/hyper#3181]
See: https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/

I haven't filled in the issue template because it's pretty self-explantory :)

**Comment by albinekb** [comment]
Seems very complicated. Why do we need this? @spegoraro Is it custom only for windows...?

**Comment by spegoraro** [comment]
I see now that this issue is more for node-pty as it provides the mechanism used by xterm.js. See Microsoft/node-pty#216 for the relevant issue. Will close this one.

For more information anyway:

Custom only for Windows and only in the insider's build at the moment. The API is fairly simple and it has the advantage of not requiring an off-screen console any more which should provide a decent performance boost.

Quoting the blog post:
>>> 3rd Party Console/Service Developers
If you're a developer working on a stand-alone Console/Terminal app, or are integrating a Console inside of an application, then we strongly encourage you to explore and adopt the new ConPTY API at your earliest convenience: Adopting the ConPTY API (rather than the older off-screen Console mechanism) is likely to eliminate several classes of bugs, while increasing stability, reliability, and performance.
>>>
>>> As an example, the VSCode team currently maintains an issue (GitHub #45693) that tracks several issues caused by Windows' current lack of a Pseudo Console.

**Comment by albinekb** [comment]
Too bad they aren't implementing the standard APIs already existing on macOS and Linux.
