### ISSUE TITLE
SemiBold font variant in Hyper

### ISSUE THREAD

**Issue by mi-lad** [zeit/hyper#3184]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Is there a way to use use different font weights in Hyper? I'd like to use a font which comes in all sorts of variants like ExtraLight, SemiBold, ThinItalic etc but these don't seem to be recognised by Hyper. I tried putting the full name in `fontFamily` or just the weight in `fontWeight` but it does not seem to work.

**Comment by albinekb** [comment]
Yes, you need to set the font name like this: `FiraCode-Light` for FiraCode, I don't know what font installation you're using but it should work.

**Comment by mi-lad** [comment]
Brilliant! Thanks for the tip. (I'm using IBM Plex Mono btw)

**Comment by albinekb** [comment]
Awesome! 🎉
