### ISSUE TITLE
Can't change font size

### ISSUE THREAD

**Issue by ParkSB** [zeit/hyper#3190]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64bit
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ParkSB/2b9625da574818f24322a62452342156
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla.

## Issue

I tried to change a font size by modifying a value of `font-size` in hyper.js file, but the font size doesn't change. Is it a bug or there is another way to change font size?

**Comment by ParkSB** [comment]
It was an issue of theme plugin 'verminal'. The font size works well after delete verminal.

**Comment by zamgill** [comment]
You can apply the font size to overide for verminal. 

See the link below:
https://github.com/zeit/hyper/issues/3343#issuecomment-451235240

**Comment by lpolone** [comment]
Thank you for this information, you helped me.
