### ISSUE TITLE
Underlined text is not shown underlined

### ISSUE THREAD

**Issue by WebReflection** [zeit/hyper#3194]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS High Sierra
- **Hyper.app version**: latest public

## Issue

```sh
node -e 'console.log("\x1B[4mok\x1B[0m")'
```

It should show an underlined __ok__ but it doesn't.

Every native terminal, in Mac, Linux, or even Windows, would show that underlined.

Thanks for fixing this !

**Comment by sobolevn** [comment]
The same happens to me on the latest version.

```
» brew cask info hyper
hyper: 2.0.0 (auto_updates)
```

**Comment by klaussinani** [comment]
Also present on the latest canary `3.0.0-canary.5`:

<p align="left"><img width="50%" src="https://user-images.githubusercontent.com/12670537/51636693-88917180-1f62-11e9-8ba6-c5e28a9c29a9.png"></p>

Text underlined as expected on all previous canary releases, ie `3.0.0-canary.4`:

<p align="left"><img width="50%" src="https://user-images.githubusercontent.com/12670537/51636697-8a5b3500-1f62-11e9-8344-215e7316927d.png"></p>

**Comment by WebReflection** [comment]
is there any interest whatsoever in solving this? Not even a bug label since Aug 27, 2018, I am going to close this as won't fix / no interest, since it's part of my issues but this looks like a dead end. 👋

**Comment by dmohns** [comment]
Hey @WebReflection why can we reopen this issue? It has been reproduced and is still present in the latest version.

**Comment by WebReflection** [comment]
@dmohns because nobody cared so that having this hanging on my issues becomes meaningless. Maybe if others open this issue over and over they'll care to fix it at some point?
