### ISSUE TITLE
chocolatey package for hyper is deprecated

### ISSUE THREAD

**Issue by chantisnake** [zeit/hyper#3206]
I was the maintainer for the [chocolatey](https://chocolatey.org/) package for hyper.
  I am deprecating the chocolatey package for hyper because I no longer have time to maintain it.

  I have requested for another package maintainer here: https://github.com/chocolatey/chocolatey-package-requests/issues/415
  The chocolatey package page for hyper : https://chocolatey.org/packages/hyper

  Sorry for all the inconvenience I have caused.

  (This issue is created automatically, some of the links may be wrong, please inform me if You want me to change them.)

**Comment by Snaptags** [comment]
This issue seems to be obsolete, there is a new maintainer, the choco package is being updated regularly.

**Comment by chantisnake** [comment]
Yes.
