### ISSUE TITLE
Request to quit hyper instead of close on exit on Mac

### ISSUE THREAD

**Issue by binamkayastha** [zeit/hyper#3222]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac 10.13.6 High Sierra
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Not relevant
- **Relevant information from devtools** Not relevant
- **The issue is reproducible in vanilla Hyper.app**: Yes
## Issue

Not a bug more a request. When exiting the Hyper terminal in Mac, I think it should quit instead of closing, and end up having dozens of Hyper apps opened. It's because I use `open -a "Hyper"` attached to a keyboard shortcut when using the program, so I might literally be the only person who has this problem. :P

**Comment by c-bandy** [comment]
The [hyper-quit](https://github.com/cblecker/hyper-quit) plugin can do this for you.

**Comment by binamkayastha** [comment]
OMG this is great thanks!
