### ISSUE TITLE
Can't open Preferences on Windows 10

### ISSUE THREAD

**Issue by mrchief** [zeit/hyper#3223]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Microsoft Windows [Version 10.0.17134.112]**: 
- **2.0.0 (stable)**: 
- **https://gist.github.com/mrchief/d7763ed71f269914f12d66caed51d5de**: 
- *N/A** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **Is Vanilla**: 

## Issue

`File > Edit > Preferences` - nothing happens
`Ctrl + comma` - nothing happens

I see no WSE errors or any dialog of that sort. No errors on devtools console as well.

**Comment by albinekb** [comment]
What is your default program for .js files? Here's how you can check it and change it: https://www.macworld.co.uk/how-to/mac-software/change-default-apps-mac-3656510/

It should open in the default app, but in this case the default app is probably incorrect.

**Comment by mrchief** [comment]
It's not set to anything. In the past I've set it to VS Code since I don't them to execute on double click. What should it be? WSE?

**Comment by mrchief** [comment]
I'm on canary and looks like it needed a restart. It seems that both ways now open preferences (`.hyper.js`) file in notepad (despite what the default app for js files is). It's good that it's opening up something but I was hoping to something of a settings editor rather than a notepad. At least, it'd be better to have it open in VS Code.

**Comment by brandon93s** [comment]
See https://github.com/zeit/hyper/pull/2631 for an explanation of when it will open notepad vs your editor. Setting the default editor for the `js` extension to VS Code should result in the settings opening in that editor.

**Comment by mrchief** [comment]
> Setting the default editor for the js extension to VS Code should result in the settings opening in that editor.

The canary build doesn't do that. It always opens in notepad.

**Comment by brandon93s** [comment]
I'm able to reproduce your describe behavior on Windows 10 / Canary now. This appears to be a regression in the previous fix. I'll try to take a look when I have time.

**Comment by batjko** [comment]
This still (or again) happens in 2.1.0, at least to me.

I had to change my default editor for `.js` files back to notepad (was vscode before).
