### ISSUE TITLE
Maximize Split Pane

### ISSUE THREAD

**Issue by dbpolito** [zeit/hyper#3225]
At `iTerm2` you have a feature to maximize split panels, with `cmd+shift+return`.

I would love to have it here too, i thought about doing a plugin for that but wanted to check here first as i think it makes sense to be a core feature.

**Comment by dbpolito** [comment]
I kept looking and i found https://hyper.is/plugins/hyper-pane which does that in case someone is also looking for this. :+1:

**Comment by albinekb** [comment]
We try to keep as much features out of the core as possible, moving functionallity to plugins. As you found a plugin that helps you with this, I'm closing this here. Thanks for reporting and posting the plugin for others to find! ❤️
