### ISSUE TITLE
Terminal prompt is beyond viewing range

### ISSUE THREAD

**Issue by ayush-sharma** [zeit/hyper#3227]
I'm facing an issue where the current terminal and prompt is beyond the visual range. I am attaching a screenshot. If I type and command and press enter, the command is successfully executed, but I cannot see the cursor or the prompt in my viewing range. It is somewhere "below" on the "next page".

OS Version: Debian 9
Hyper version: Stable and Hyper 2.1.0-canary.2
Dev tools console:

```
(re)loading renderer plugins
bundle.js:1 Plugin hyper-opacity (1.0.0) loaded.
bundle.js:1 Plugin hyper-arc-dark-controls (1.2.0) loaded.
index.html:35 total init time 277.74000000000007
```
![screenshot from 2018-09-29 10-28-56](https://user-images.githubusercontent.com/9398523/46241222-8ebb7b00-c3d2-11e8-8f9e-18d2f9874e25.png)

**Comment by scooby** [comment]
I'm running into this too on Mint 19 Cinnamon, also Hyper 2.1.0-canary.2, with no plugins on a high DPI screen. This seems the same as #628.

Steps to reproduce:

1. Comment out `PS1` line in `.bashrc` to rule odd ANSI codes out. (Doesn't make a difference.)
2. Start hyper.
3. Control shift T to create a new tab.
4. `ls -al`

The prompt is now below the window. (Also, closing the second tab causes the first to have an extra margin.)

Here's a [screen recording](https://github.com/scooby/random/blob/master/dev-tools.ogv) of stepping through elements in dev tools.

**Comment by tabokie** [comment]
Same issue under Windows 10 with latest Hyper 2.1.0-canary.3,
the frame buffer size isn't changing accordingly to tab change. Part of content will be squeeze out of window if user create a new tab from single tab layout; a piece of blank will occur if user go back to single tab layout.
