### ISSUE TITLE
Change the behavior of cmd+k

### ISSUE THREAD

**Issue by joeytrapp** [zeit/hyper#323]
With iTerm2, I was able to overwrite with cmd+k (and cmd+r) did. I would change it from whatever clearing it would do to just send "clear\n" to the current terminal. This would make it play nice with tmux. Is there a way to do the same with HyperTerm or is that something that could be added?

**Comment by marcbachmann** [comment]
there's ctrl+l for that

**Comment by joeytrapp** [comment]
The problem with that is I'm fighting years of muscle memory. That's a me problem, but would be nice if the command could be overwritten.

**Comment by chabou** [comment]
ctrl+l is not really a Term shortcut but a shell one.
We are planning to make shortcuts configurable for Hyper feature (see #1509).
Plugins may use this keymap bindings to implement your feature very easily.

**Comment by MartyGentillon** [comment]
see also https://github.com/zeit/hyper/issues/872

**Comment by ppot** [comment]
Closing since #1876
