### ISSUE TITLE
Can't open hyper if the default shell is wsl.exe

### ISSUE THREAD

**Issue by chiuchiuuu** [zeit/hyper#3232]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla

## Issue

If I set default shell is `wsl.exe`, then hyper can't be open, just show up and quit.

```
 shell: 'C:\\Windows\\System32\\wsl.exe',
```

but if the default shell is `cmd.exe` and I type command `wsl` and it works fine.

**Comment by danisfermi** [comment]
The issue persists if the shell is C:\\Windows\\System32\\bash.exe as well. Additionally, on Running Hyper as administrator, hyper opens up, shows the following error message rather than quitting.
![image](https://user-images.githubusercontent.com/33509082/46421098-0e10bd80-c6f7-11e8-98f5-dd5e42fa7ba2.png)

**Comment by yodurr** [comment]
take a look at the comment by ben hillis in #2369 
If Hyper doesn't pass --login to WSL.exe then it should work.

**Comment by chiuchiuuu** [comment]
@yodurr Thanks! It works!

**Comment by mahaoyang** [comment]
### Solutions   
**set _shellArgs_: ['~'],**

 // PowerShell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: `C:\\WINDOWS\\System32\\wsl.exe`,

    // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
    // by default `['--login']` will be used
    shellArgs: ['~'],

**Comment by Robinnnnnn** [comment]
> ### Solutions
> **set _shellArgs_: ['~'],**
> 
> ```
>  // PowerShell on Windows
> // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
> shell: `C:\\WINDOWS\\System32\\wsl.exe`,
> 
> // for setting shell arguments (i.e. for using interactive shellArgs: `['-i']`)
> // by default `['--login']` will be used
> shellArgs: ['~'],
> ```

Just Confirming this is still the answer 3 years later.
