### ISSUE TITLE
Hyper.is website security error

### ISSUE THREAD

**Issue by justinkahrs** [zeit/hyper#3250]
## Issue

I was looking for Hyper themes and came across this Chrome security error. It's not reproducible in Firefox, but I figured you guys would want to know. Using the latest Chrome for macOS (Version 69.0.3497.100)

![image](https://user-images.githubusercontent.com/24902261/46706039-475d9780-cbe7-11e8-91d9-15ed4663b53e.png)

**Comment by timothyis** [comment]
Thank you for reporting! I have removed the theme causing this issue (due to preloading the image causing this error) and pinged the author for an update
