### ISSUE TITLE
Umlaute "Accent" (ö,ä,ü,...) not correctly represented (-> ??)

### ISSUE THREAD

**Issue by psychos4** [zeit/hyper#3256]
I have the following Problem, the literals are not shown correctly:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/28728398/46920100-377bf400-cfe9-11e8-809c-4f2302694057.png">
Mysterious - for Input (ex. mkdir Überarbeiten)  is working but not for output (ex. ls -la)?!

**Comment by Stanzilla** [comment]
should be fine in recent versions
