### ISSUE TITLE
Unable to click wrapped links

### ISSUE THREAD

**Issue by ahmedu007** [zeit/hyper#3261]
- [✓ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [✓ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14
- **Hyper.app version**:  2.0.0

## Issue
Whenever there is a link in the console that is outputted and wrapped, the wrapped part is not clickable. Using CMD+click only opens the 1st half of the link as opposed to the whole string. Please find the attached screenshots to help understand the bug.
<img width="551" alt="screenshot 2018-10-19 at 11 06 06" src="https://user-images.githubusercontent.com/30743917/47212389-ee80c280-d38f-11e8-93c4-e747ea2f30c6.png">
<img width="568" alt="screenshot 2018-10-19 at 11 06 22" src="https://user-images.githubusercontent.com/30743917/47212390-ee80c280-d38f-11e8-949a-75e2bc585e22.png">
<img width="566" alt="screenshot 2018-10-19 at 11 06 44" src="https://user-images.githubusercontent.com/30743917/47212391-ee80c280-d38f-11e8-9884-f036ce440662.png">
<img width="569" alt="screenshot 2018-10-19 at 11 11 38" src="https://user-images.githubusercontent.com/30743917/47212392-ee80c280-d38f-11e8-9756-a2743a95e475.png">

Please see the last image to reproduce the issue. It works fine if the link is not long enough to be wrapped, or if the terminal is wide enough to hold the link

**Comment by ahmedu007** [comment]
I can try to do a pull request if someone can point me in the direction of where to look, and where could this error be. I'm sorry, I don't have enough experience with electron, but I'd be happy to help

**Comment by chovy** [comment]
I can't click links period. How do you click a link and open in browser? I thought it would be ctrl+click on Linux, but nope. that doens't work.

**Comment by chalkos** [comment]
@chovy for me a simple click is enough to open the url (using 2.1.0-canary.5), and I came here looking for a way to make it open the browser only on ctrl+click. If you manage to find out what is making your links not working, let me know as I would prefer hyper to not show hyperlinks at all.

**Comment by chovy** [comment]
Turns out they were opening the browser just wasn't coming into focus like on a mac.

**Comment by ahmedu007** [comment]
Closing, issue is fixed in version `2.1.1`
