### ISSUE TITLE
Is it possible to set the terminal background color to transparent?

### ISSUE THREAD

**Issue by jcklpe** [zeit/hyper#3267]
I'm trying to update the hyperpunk plugin to be compatible with hyper2. I did this a couple of months ago, and I remember successfully getting it to work correctly by setting some of the css background styling to transparent in order to allow the css animated noise texture show through properly. 

I'm finally getting around to working on the project again, but I'm still seeing a dark solid green color where the term is. I know that the terminal is now rendered in canvas etc, but I also remember getting it to work on Hyper2 in July so I'm curious if something in Hyper2 changed since then? I did go from version 2.0 to a canary build. 

Could anyone point me in the right direction for how I could add transparency to the background so as to properly fix the view the animated noise texture?

I've gone through every single element and div and set it to "transparent" and I can't seem to figure out what I'm missing. Any thoughts?

Also hopefully to make this a bit more clear (I'm not totally cogent at 2 in the morning), here's a pic of how it looks so far: 

![image](https://user-images.githubusercontent.com/9451726/47549474-d34b1100-d8c1-11e8-8adf-c81a09c5c1f5.png)

I'm trying to get the part which is the canvas to be transparent so that the styling of the body background etc with the noise texture comes through properly.

**Comment by jcklpe** [comment]
Closing and moving issue to Spectrum since it seems more relevant there: https://spectrum.chat/?t=1bc79615-8f8a-4431-b56d-784f80951f07

**Comment by slammayjammay** [comment]
Posting here because I don't want to sign up for Spectrum (sorry) and also because there may be an argument for reopening this issue.

Using only the `.hyper.js` config, it's not possible to set the xTerm background transparent without also setting the Hyper app transparent because there's only one `backgroundColor` option. I think it might be a good idea to split that up into two background color options, one for Hyper and one for xTerm.

You can still get a transparent xTerm background via a plugin that makes use of `exports.decorateTerm`. 

```js
exports.decorateTerm = (Term, { React }) => {
    return class TransparentFix extends React.Component {
        onDecorated(term) {
            const xTermInstance = term.term;
            
            // don't know why it doesn't work without setTimeout
            setTimeout(() => {
                // needed if you have a fully opaque hyper backgroundColor, set in .hyper.js
                xTermInstance.setOption('allowTransparency', true);
            
                xTermInstance.setOption('theme', { background: 'transparent' });
            }, 0);
        }
    }
}
```

**Comment by jcklpe** [comment]
@slammayjammay  
Looking at the structure of the code you quoted, I think I see where the code in hyperpunk2.0 should go but I'm not entirely sure. I'm not really a real developer yet, I've just been learning as I go, I'm basically a caveman here just mashing things together, copying and pasting, and breaking shit. 

I recognize the exports.decorateTerm from a chunk of code that's also in the hyperpunk code. I'm guessing that's basically where you're exporting functions for React? So if I copy over the onDecorated stuff into that structure in a way that mirrors the way the other functions are inside the current structure it would look like this:

```
exports.decorateTerm = (Term, {
  React,
  notify
}) => {
  return class extends React.Component {
    constructor(props, context) {
      super(props, context);
      this._drawFrame = this._drawFrame.bind(this);
      this._onTerminal = this._onTerminal.bind(this);
      this._injectStyles = this._injectStyles.bind(this);
      this._div = null;
      this._body = null;
      this._globalStyle = null;
      this._term = null;
      this._intervalID = null;
    }

    _onTerminal(term) {
      if (this.props.onTerminal) this.props.onTerminal(term);
      this._div = term.div_;
      this._term = term;
      this._body = term.cursorNode_.parentElement;
      this._window = term.document_.defaultView;
      this._injectStyles();
      this._intervalID = setInterval(() => {
        this._window.requestAnimationFrame(this._drawFrame);
      }, 80);
    }

    onDecorated(term) {
      const xTermInstance = term.term;

      // don't know why it doesn't work without setTimeout
      setTimeout(() => {
        // needed if you have a fully opaque hyper backgroundColor, set in .hyper.js
        xTermInstance.setOption('allowTransparency', true);

        xTermInstance.setOption('theme', {
          background: 'transparent'
        });
      }, 0);
    }

    _injectStyles() {
      if (this._term) {
        this._term.prefs_.set('background-color', 'transparent');
        this._term.prefs_.set('background-image', 'none');
      }
      this._globalStyle = document.createElement('style');
      this._globalStyle.setAttribute('type', 'text/css');
      this._term.scrollPort_.document_.body.appendChild(this._globalStyle);
    }

    _drawFrame() {
      this._globalStyle.innerHTML = `
        x-screen {
          ${generateTextShadow()}
        }
      `;
    }

    render() {
      return React.createElement(Term, Object.assign({}, this.props, {
        onTerminal: this._onTerminal
      }));
    }

    componentWillUnmount() {
      clearInterval(this._intervalID);
    }
  }


};
```

That however does not seem to work... 😖 hmmm 

Any ideas? I'm sorry to be struggling with such a basic thing. I have been meaning to get back to my React courses lately so that I can finally learn things properly instead of just fiddling blindly, but have gotten sidetracked the last 3 months making the transition to Linux and learning how to integrate myself into a more modern development environment.

**Comment by jcklpe** [comment]
AAAAH SHIT YEAH!

I'm also an idiot. I applied the changes but didn't change the background color in my config. Works perfectly now! Thank you @slammayjammay ! I'm going to commit this to the repo and then publish my first node module! (though I can't really take any credit for this because it's like.... 99% of the work done by other people. But I want it to be accessible to people and stallz seems to have lost interest in the project so it's up to me! )
