### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by EddiG** [zeit/hyper#3281]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mac OS X 10.14.1
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/EddiG/f6198a586c460f73f5c78207d0624859
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

#### How to reproduce
Open 10 tabs and close them.

As you can see on the [video](https://monosnap.com/file/ZSpiVbBwbTd36pQByAgzTxc3BjXnGg) the memory consumption grows really fast and even worse it stays held after closing tabs.
I'm not experienced in Electron but if someone advice how to localize the problem I will be glad to provide additional information.

**Comment by pablopunk** [comment]
For the record, I tried doing this on Linux (elementaryOS 5 - Ubuntu 18.04) and I see no difference in memory usage. I opened a lot of tabs and then closed them, no problems.

**Comment by Binaryify** [comment]
same 
![image](https://user-images.githubusercontent.com/12221718/50370426-23540480-05e1-11e9-9236-d93021469a61.png)

**Comment by Kos-M** [comment]
Hey , im facing same bug , in version 2.1.2 (stable)
OS: win7 64 bit
shell : cyg-win64 (bash)
Behavior: after closing tabs in split view (ctrl+shift+t for open), memory not releazed.(i have 8GB Ram and pc freezes after some time working on )

**Comment by amurchick** [comment]
Same issue, version 3.0.2 (stable)
Renderers: WebGL (39)
Plugins: none

OS: MacOS 10.15.3

Fresh run:
![image](https://user-images.githubusercontent.com/1515699/73916039-31e9a200-48ef-11ea-81bd-b90c1713d13b.png)

Then simply open 9 tabs:
![image](https://user-images.githubusercontent.com/1515699/73916079-45950880-48ef-11ea-9139-df8656264e47.png)
