### ISSUE TITLE
Fails to load scoped plugins

### ISSUE THREAD

**Issue by j-f1** [zeit/hyper#3288]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version (Reproduces on canary and stable)
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.13.2 (17C88)
- **Hyper.app version**: 2.1.0-canary.2 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://github.com/j-f1/dotfiles/blob/bd6f1f5e7ece8db77ae0fcea6688c64ae3fe9b74/.hyper.js
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Seems likely — the issue is with plugin loading.

## Issue

Scoped packages aren’t loaded. When I install `@j-f/hyper-statusline` in my `.hyper.js`, it installs fine, but isn’t activated. I tried debugging, and discovered that the plugin finder strips out everything after an `@` in the package name:

https://github.com/zeit/hyper/blob/f91f111cfb2b218876da032fefde500d27ea07e0/app/plugins.js#L211-L213

Would it be possible to fix this so I can use my plugin with a scoped name?

**Comment by ahutchings** [comment]
Related: #2999

**Comment by erictaylor** [comment]
See: https://github.com/zeit/hyper/pull/3672
