### ISSUE TITLE
Manually Add Hyper to System Environment Variables

### ISSUE THREAD

**Issue by cjmaria** [zeit/hyper#3289]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **2.0.0**: 
- **Is Vanilla**: 

## Issue

How to add hyper to environment variables?
When trying to execute the `hyper` command, I get `'hyper' is not recognized as an internal or external command, operable program or batch file.`
I cannot use refreshenv from choclatey due to administrator restrictions on regedit, but I can add environment variables manually.
What do I add to the system path for this to work?

**Comment by NetherGranite** [comment]
Why is it found in AppData and not Program Files?

**Comment by cjmaria** [comment]
That's a good question, perhaps it has something to do with the fact that hyper is an electron-based app and not a native executable.
