### ISSUE TITLE
Hyper CLI not working correctly on Manjaro Linux when installed from the AUR

### ISSUE THREAD

**Issue by Dakedres** [zeit/hyper#3296]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate (however there is one which is [very similar](https://github.com/zeit/hyper/issues/2849), more on that later).

- **OS version and name**: Manjaro Linux
- **Hyper.app version**: 2.1.0canary2-1 (Installed from the AUR)
- **[.hyper.js](https://gist.github.com/Dakedres/6af8e4fd07dc7a7cc55f3a2dfa90b108)**
- **The issue is reproducible in vanilla Hyper.app**: I highly assume so, the only thing I've done was change the background color.

## Issue
When attempting to use any command from the hyper CLI, I get the following:
```
/home/dakedres/.gtkrc-2.0:4: Unable to find include file: "$HOME/.gtkrc-2.0.mine"
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///usr/lib/hyper/resources/app.asar/index.html
Checking for notification messages
No matching notification messages
```
And it opens a new instance of the terminal, I found this [previously mentioned issue](https://github.com/zeit/hyper/issues/2849) which was very similar, however they were on Windows 10. So I decided to follow the answer to that issue and opened a new instance of the terminal as root (using `sudo hyper`) and try to reinstall the CLI command in PATH. In the Hyper terminal instance I had used to open the root instance, I got the following:
```
[Notification] Hyper CLI instalation: Command is added in PATH only at package installation. Please reinstall.

(hyper:9181): libnotify-WARNING **: 00:38:05.918: Failed to connect to proxy

(hyper:9181): libnotify-WARNING **: 00:38:05.931: Failed to connect to proxy

(hyper:9181): libnotify-WARNING **: 00:38:05.947: Failed to connect to proxy
```
(Yes that typo is accurate to the what it logged)
And it hung for quite a while, so I stopped the process. Judging from the information it gave me, I decided to try and reinstall as root, just in case, to no avail.

 Any help would be greatly appreciated, I'd really like to be able to use Hyper to it's full potential again.

**Comment by mkody** [comment]
The CLI tools must be added to your path.

```sh
export PATH=/usr/lib/hyper/resources/bin:$PATH
```

**Comment by Dakedres** [comment]
Ah it works now, thank you!
