### ISSUE TITLE
Bell Char, No sound (U+0007)

### ISSUE THREAD

**Issue by Gabgab2003** [zeit/hyper#3297]
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version

- **OS version and name**: Windows 7 x64
- **Hyper.app version**: 2.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: vanilla
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
The bell char (\u0007 or alt+7) doesnt play the bell sound, but it works in normal cmd

**Comment by BaldEagleX02** [comment]
I have the same issue.
Hyper version: 2.1.0 stable
OS Version: MacOS 10.14.1

**Comment by SUNYPoly-Steven** [comment]
Is this still an issue? I'm encountering the same thing on Ubuntu 18.04 and Hyper 3.0.2 (stable)

**Comment by Stanzilla** [comment]
Fixed in the canary builds (not released yet)

**Comment by SUNYPoly-Steven** [comment]
Good to know, thanks!
