### ISSUE TITLE
What's up with Nano?

### ISSUE THREAD

**Issue by WeslyG** [zeit/hyper#3298]
Yes i am checked this! 
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

My software
- **OS version and name**: Windows 10 1809
- **Hyper.app version**: 2.0.0 stable
- default shell = linux for windows
(shell: 'C:\\Windows\\System32\\bash.exe',) 

![screenshot_7](https://user-images.githubusercontent.com/12625945/49093689-765ac600-f286-11e8-9e28-133f5c7b9126.png)

## Issue
WHAT'S UP WITH NANO???

Nano's broken! It just doesn't allow me to work, I just want to edit the text! Why does it work in vi?? I want to use nano it's really important to me, why do I see it? I just press the right arrow to move to the right place. I really waited for someone to fix it, and followed the updates. No one uses a nano?

Gif from ssh on vm (centos 7.5)
![4zjdehhbwg](https://user-images.githubusercontent.com/12625945/49093983-1284cd00-f287-11e8-8c4d-c768868a0135.gif)

The same ssh machine on macbook air nano works well. I don't get artifacts.
What happened in windows?

**Comment by robertgrzonka** [comment]
Could you please show your `.hyper.js` config file?

**Comment by WeslyG** [comment]
My config .hyper.js

https://gist.github.com/WeslyG/8efd914e7b462dd9c1704aaeed725daa

**Comment by robertgrzonka** [comment]
Most likely this issue isn't really produced by `Hyper`. Check [here](https://askubuntu.com/questions/24358/how-do-i-get-long-command-lines-to-wrap-to-the-next-line) as this is common problem in `shell` environments which can be easily solved with proper `escaping` and/or `quoting`.

Have you been trying how `nano` works on other console than `Hyper`?

**Comment by WeslyG** [comment]
thanks to everyone, I was able to solve my problem by abandoning Linux for windows in favor of git bash (mingw64) 
Now my config looks like this https://gist.github.com/coco-napky/404220405435b3d0373e37ec43e54a23

And it works perfectly. Maybe later I'll figure out what exactly breaks the system in LFW but so far I'm happy with the result, I think you can close issued. 

And sorry for hate, I was really confused about getting this behavior every time.

**Comment by maurocolella** [comment]
I can definitely relate to the fact that this is free software, and I am rather grateful because it is set to offer a unified terminal experience.

That said, even with the above settings, nano has some issues for me when using ssh. In this case, ssh from a Windows 10 workstation to a Linux server.
