### ISSUE TITLE
Open links in non-default browser

### ISSUE THREAD

**Issue by samselikoff** [zeit/hyper#3310]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

---

Hi! I was wondering if there's a way to make Hyper open links in a specific non-default browser. My default browser is Safari but I'd like links to open in Chrome.

**Comment by danchristian** [comment]
This is something I would be interested in two. I want links to open in Firefox Developer Edition rather than default Firefox.

**Comment by Stanzilla** [comment]
Currently out of scope
