### ISSUE TITLE
Pasted text is initially shown as a random character (2.1.0-canary.3)

### ISSUE THREAD

**Issue by darrylyoung** [zeit/hyper#3315]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version (I'm on Hyper 2.1.0-canary.3 (canary))
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.2
- **Hyper.app version**: Hyper 2.1.0-canary.3 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [Gist](https://gist.github.com/darrylyoung/e5ec47c5681c41b5cea40aeaede95ec4)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla (and also with extras shown in [Gist](https://gist.github.com/darrylyoung/e5ec47c5681c41b5cea40aeaede95ec4))

## Issue
After upgrading to `Hyper 2.1.0-canary.3 (canary)`, text that's pasted from the clipboard is replaced by a seemingly random character. For example, when pasting `git push -u origin master` I saw the following:

<img width="371" alt="screenshot 2018-12-07 at 20 14 14" src="https://user-images.githubusercontent.com/1460800/49668233-cd6a5300-fa5d-11e8-9c11-8563e79282a0.png">

Upon restarting Hyper and trying again I saw a different character:

<img width="370" alt="screenshot 2018-12-07 at 20 24 50" src="https://user-images.githubusercontent.com/1460800/49668372-2cc86300-fa5e-11e8-967a-465e8f5bed3c.png">

As the text is highlighted when being pasted, you can hit the right arrow (for example) to remove the highlight and then the test is shown as expected.

Note that this wasn't happening before upgrading to `2.1.0-canary.3`.

**Comment by chabou** [comment]
Yes, this is the first char typed in term.
Thank you for your feedback 🙏 

It was a known issue (considered as non-blocking).
But it seems that the problem is bigger: https://github.com/zeit/hyper/issues/3314

Any progress will be tracked there.
