### ISSUE TITLE
Double-bite characters not displayed correctly

### ISSUE THREAD

**Issue by mrymtsk** [zeit/hyper#3316]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14
- **Hyper.app version**: 2.1.0-canary.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: vanilla
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
I am not sure if this is only applicable to double-byte characters, but at least Japanese characters are not displayed correctly on v2.1.0-canary.3. I have been experiencing this problem after xterm.js was updated to v3.8.0 #3255.
<img width="1027" alt="screen shot 2018-12-08 at 15 40 47" src="https://user-images.githubusercontent.com/30044015/49682950-6ea9e580-fb00-11e8-87cd-2b00380883f9.png">

**Comment by i-rakoon** [comment]
me too.

OS version and name: Windows10 Build18290 (insider preview)
Hyper.App verison: 2.1.0-canary.3

**Comment by yang4515** [comment]
me too.
OS version and name: macOS Mojave 10.14
Hyper.app version: 2.1.0-canary.3

**Comment by Tyriar** [comment]
This is probably https://github.com/xtermjs/xterm.js/pull/1758 which will be in xterm@3.9.0 released either today or tomorrow.

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/releases/tag/3.9.0

**Comment by mrymtsk** [comment]
Looks like #3319 fixes the issue!

**Comment by rauchg** [comment]
Thanks for reporting @mrymtsk
