### ISSUE TITLE
Cannot type into terminal after update to 2.1.0-canary.3

### ISSUE THREAD

**Issue by AtomicAntimatter** [zeit/hyper#3317]
- [x ] Your Hyper.app version is **2.1.0-canary.3**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

```
Uncaught TypeError: Cannot read property 'x' of undefined
    at Terminal.e.onCursorMove.disposableListeners.push.term.addDisposableListener (bundle.js:1)
    at Terminal.EventEmitter.emit (bundle.js:1)
    at InputHandler.parse (bundle.js:1)
    at Terminal._innerWrite (bundle.js:1)
    at bundle.js:1
```
  - **Is the issue reproducible in vanilla Hyper.app?**

Reinstalling fixes the issue, updating again brings back the issue

## Issue

Keyboard typing does not work in the hyper app. Keyboard typing works everywhere else, including editing preferences.

 - **Hyper version**: undefined "2.1.0-canary.3"

 - **OS ARCH VERSION:** win32 x64 10.0.16299
 - **Electron:** 1.8.8  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 16,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "wsl.exe",
  "shellArgs": [],
  "env": {},
  "bell": "false",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "bellSoundURL": "C:\\"
}

          {
  "plugins": [
    "hyper-flat",
    "hyperpower",
    "hypercwd",
    "hyper-pane"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by roachnt** [comment]
Getting the same problem with same error on Mac, additionally I can't even see anything when I initially open the terminal, just a blank screen.

**Comment by roachnt** [comment]
@AtomicAntimatter I think the hyperpower plugin might be causing the issue. Try uncommenting it in your hyper.js file, then reload and see if that helps.

**Comment by AtomicAntimatter** [comment]
Thanks @roachnt the culprit seems to have been hyperpower. Typing into the terminal works now.

**Comment by AtomicAntimatter** [comment]
Closing issue since it is a duplicate

https://github.com/zeit/hyperpower/issues/63
> Not working with 2.1.0-canary3 #63

**Comment by chabou** [comment]
This is an `Hyper` issue.
Reopening
