### ISSUE TITLE
Allow not joining any update channel

### ISSUE THREAD

**Issue by ricardomatias** [zeit/hyper#3327]
At the moment, the latest beta is broken for me and I wish to revert to a previously working one. The issue is that you cannot opt-out from the update channels (at least I couldn't find any information about it).

**Comment by chabou** [comment]
What is broken? Which canary version exactly? Which OS?

All required/needed informations to understand your issue accurately (even to switch your update channel), are the informations asked in our issue template. Please fill a new issue with these informations and we'll be happy to help you. 🙌
