### ISSUE TITLE
The cursor of vi does not move

### ISSUE THREAD

**Issue by i-rakoon** [zeit/hyper#3331]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows10 build18298 wsl(Ubuntu 18.04.1 LTS)
- **Hyper.app version**: 2.1.0/2.1.0canary.5

## Issue

The cursor movement of vi is not displayed.
lv screen does not appear.

**Comment by HeathLee** [comment]
same issue

**Comment by andrewpaterbrown** [comment]
I also have this issue. I think it's related to the new insider build of windows, but the new console changes are coming to all builds of windows, and this makes vim unusable in hyper.

Definitely makes hyper unusable for me as a developer.

**Comment by andrzejnovak** [comment]
Same issue, cursos stuck in the middle of the screen, not moving in vim.

**Comment by i-rakoon** [comment]
fixed in 3.0.0-canary.1

**Comment by thebadhatter** [comment]
I am having this issue as well. It appears to have been fixed in 3.0.0-canary.1 so I will check back.

**Comment by andrzejnovak** [comment]
@thebadhatter indeed fixed in new canary, for change prompt is invisble, when I exit vi now, but `ls` fixes it for some reason, either way that's not a workflow breaking issue
