### ISSUE TITLE
Issue with spaceship after update to 2.10

### ISSUE THREAD

**Issue by cocoonkid** [zeit/hyper#3335]
`spaceship::section:17: character not in range`

and then it hangs.  Iterm2 still works as expected with ZSH).

**Comment by liuderchi** [comment]
I encountered similar message after bumping hyper from `v2.0` to `v2.1`.

Such message comes from my custom `.zshrc` script expression like this:

```sh
# .zshrc

VCS_GIT_GITHUB_ICON=$'\uF113 '  # setting up icon with unicode
```

One interesting thing is after the CLI prompt is ready, 
I still can print something like `echo $'\uF113 '` with expected result.

Looks like hyper cannot resolve unicode expression at some point of time?

**Comment by drigomen** [comment]
I got `spaceship::section:11: character not in range` after coming back from super user to regular user, then no unicode characters can be rendered until I restart the terminal.
For test, open the terminal, and run

    > sudo -s

Glyphs are ok on superuser session. Then, switch back:

    > su - localuser
    spaceship::section:11: character not in range

Now glyphs cant be rendered. Even by echo:

    > echo $'\uF113 '
    zsh: character not in range
    spaceship::section:11: character not in range

**Comment by cocoonkid** [comment]
Tested 2.1.2

Issues prevail.

**Comment by cocoonkid** [comment]
Is there a way to disable AutoUpdate ? Tried to find it to no avail.

**Comment by cocoonkid** [comment]
I got it to work by using zplugin for all of my plugin management.
I cannot pinpoint what solved it for lack of time but I can really recommend zplugin.

Fastest ZSH experience ever. And Craisis is awesome! My .zshrc is so nice and so clean ;-)
