### ISSUE TITLE
30 Seconds delay when opening new panes & tabs after update

### ISSUE THREAD

**Issue by yevgetman** [zeit/hyper#3346]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.2
- **Hyper.app version**: 2.1.0 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/yevgetman/95ed8c02c42231bdcd504bbf2a586fd9

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I recently updated my Hyper to the latest version (2.1.0) as per notification in the terminal using use. I don't recall my previous version number. 

Having updated, I noticed a delay of _exactly_ 30 second between the time I attempt to open a new pane or tab (via menu or keyboard shortcut) and the time the pane or tab appears in the terminal. 

If I attempt to open multiple panes or tabs in quick succession, all will open immediately after the 30 second delay. 

I have timed the delay and its 30 seconds every time. 

Closing tabs or panes does not incur a deploy and appear to function normally.

**Comment by yevgetman** [comment]
anybody?

**Comment by ohardy** [comment]
I have this problem when I enable hypercwd plugin, cf https://github.com/hharnisc/hypercwd/issues/58

**Comment by LeanderFS** [comment]
I also had this problem when having hypercwd enabled. I noticed the hypercwd wasn't being actively maintained so I took the liberty to quickly write a replacement extension with the same functionality (and even less code). 

You can install it using `hyper i hyper-samewd`

Repository is located here: [hyper-samewd](https://github.com/LeanderFS/hypersamewd)

**Comment by ohardy** [comment]
Thanks i will try your repo :)

**Comment by alburdette619** [comment]
@LeanderFS Starred, thanks for you work

**Comment by yevgetman** [comment]
@LeanderFS this solved the issue for me. Thank you!
