### ISSUE TITLE
RFC: Use the File API to read the pty from the renderer process

### ISSUE THREAD

**Issue by juancampa** [zeit/hyper#3347]
So, I just realized there might be [a way for the renderer process to read from the filesystem directly](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL), I wonder if `node-pty` could be used directly within the renderer process skipping IPC altogether (probably with some modifications).

I've never used this API so if someone has experience and can provide some feedback that'd be helpful.

**Comment by j-f1** [comment]
Looks like that only supports files uploaded via the “select a file” button on web pages. Unfortunately it doesn’t allow arbitrary file access as far as I know.

**Comment by juancampa** [comment]
I was just talking to @chabou and @Tyriar and apparently it's possible to use `node-pty` as-is if `nodeIntegration` is set to true when creating the `BrowserWindow`. Problem is that it opens up a vulnerability, especially with plugins that open webpages.

We'll stick to IPC for now.
