### ISSUE TITLE
Command not found with new Hyper install 2.1.0

### ISSUE THREAD

**Issue by jakewhite1230** [zeit/hyper#3349]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.13.6 High Sierra
- **Hyper.app version**: 2.1.0

## Issue

I installed Hyper 2.0 on one of my machines last week and everything was working great. I went to add it to a new machine for work. It was the latest 2.1.0 release. After install, I tried to add the material theme and was getting ```bash: hyper: command not found```. I searched previous issues and found some stuff about hyper possibly not existing here  ```/usr/local/bin/hyper```, but that wasn't the case. It was there. I grabbed the 2.0.0 copy from my other machine and installed it on my new one, and everything worked fine, even after upgrading to 2.1.0. So there may be an issue with Hyper 2.1.0 and the cli tool

**Comment by JonasKs** [comment]
On Windows you have to restart the machine/refresh environment variables for it to work. Tried restarting your computer?

**Comment by jolaleye** [comment]
Having the same issue. The app installed just fine, but without the CLI. Trying **Plugins > Install Hyper CLI command in PATH** results in the error: **Symlink creation failed: EACCES**.
* _macOS Mojave 10.14.2_
* _Hyper.app 2.1.0_

**Comment by galliv** [comment]
I suppose it depends on Mojave's SIP

**Comment by jolaleye** [comment]
[Installing with Homebrew](https://github.com/zeit/hyper#macos) fixed my issue. I can now use the `hyper` command. Rereading this thread, I think I was actually having a different problem but nonetheless this may help.

**Comment by Nazaire** [comment]
Just had the same issue all I had to do was:
Remove whatever was at /usr/local/bin/hyper
Then re-installed it with **Plugins > Install Hyper CLI command in PATH** and it works fine

**Comment by zotttttttt** [comment]
> Just had the same issue all I had to do was:
> Remove whatever was at /usr/local/bin/hyper
> Then re-installed it with **Plugins > Install Hyper CLI command in PATH** and it works fine

Worked for me. I think this happened because I launched Hyper from my Downloads folder and then moved it into Applications. I think that the link between what had been at /usr/local/bin/hyper and actual Hyper application broke there.

**Comment by zylwendao** [comment]
i have solved this issue , 1, uninstalling hyper.app 2.cd /usr/local/bin/ then remove directory 'hyper' and 'hyperkit' , 3, open hyper.app , finished!

**Comment by abhitrip13** [comment]
the best way is to install homebrew from [brew,sh](url) which basically installs all missing commands in your mac.
1)go to [brew,sh](url), paste the command in your terminal(wait for sometime until it installs)
2)then go to your hyper terminal and using plugins tab in top nav bar and install hyper cli.
3)You are good to go!!
now you can use hyper commands 
for eg< hyper i verminal>

**Comment by Sergioamjr** [comment]
I solved that running this command on my mac
```cmd
sudo ln -s "/Applications/Hyper.app/Contents/Resources/bin/hyper" /usr/local/bin/hyper
```

**Comment by quibbleahr** [comment]
Just in case someone else runs into this issue, on my windows computer, I have Git Bash and created the `/usr/local/bin` directory. Then I hit **Tools >  Install Hyper CLI command in PATH**, restarted and it worked!

**Comment by bschaatsbergen** [comment]
> I solved that running this command on my mac
> 
> ```batchfile
> sudo ln -s "/Applications/Hyper.app/Contents/Resources/bin/hyper" /usr/local/bin/hyper
> ```

Works great, thanks Sergio.

**Comment by jhoanplata** [comment]
> Resolví eso ejecutando este comando en mi mac
> 
> ```batchfile
> sudo ln -s "/Applications/Hyper.app/Contents/Resources/bin/hyper" /usr/local/bin/hyper
> ```

Excelente a 2022, sigue funcionando perfecto, muchas gracias.

**Comment by noor-codes** [comment]
> I solved that running this command on my mac
> 
> ```batchfile
> sudo ln -s "/Applications/Hyper.app/Contents/Resources/bin/hyper" /usr/local/bin/hyper
> ```

This worked for me! Thank You

**Comment by ArmsAndArrows** [comment]
I was also stuck with exact same problem.
 However, after installing Git from https://git-scm.com/downloads on my PC with all default settings, everything started working correctly.

**Comment by Rodrigolqjs** [comment]
> ```batchfile
> sudo ln -s "/Applications/Hyper.app/Contents/Resources/bin/hyper" /usr/local/bin/hyper
> ```

This worked for me. Thanks Sergioamjr!!!

**Comment by bkwilcox100** [comment]
After creating a local bin folder, this finally worked. Thanks!

`sudo ln -s "/Applications/Hyper.app/Contents/Resources/bin/hyper" /usr/local/bin/hyper`

**Comment by synth** [comment]
Symlinking feel weird? On Mac's there is a menu option for this: 
<img width="469" alt="image" src="https://github.com/vercel/hyper/assets/10546/e5fd988e-61a4-4a32-8b21-f317a8461e08">
