### ISSUE TITLE
Has anyone gotten hyper to run in a browser?

### ISSUE THREAD

**Issue by ratacat** [zeit/hyper#3353]
I'm just wondering how hard that might be, seems like nobody has talked about it much.

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by rauchg** [comment]
We definitely want to have a browser build and API. If you're up for working on that, let us know

**Comment by ratacat** [comment]
I don't think that I'm your person for that, I'm guessing its a bit out of my capabilities at the moment as much as I might like to see it done.

**Comment by karocksjoelee** [comment]
I guess it may work that build a local server running , and navigate to localhost:5000 ( for example ) . the cmds will be pass to the local server , and server execute hyper APIs .
