### ISSUE TITLE
2.1.0 not working

### ISSUE THREAD

**Issue by lortega22** [zeit/hyper#3364]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Version 1803
- **Hyper.app version**: 2.1.0
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Hyper has been working fine for me for the past few months, and is/was my go to terminal. However recently it has decided to start autoupdating to version 2.1.0 which seems to not work at all. Like starting up, it crashes. I usually fix this issue by re-running the exe to get 2.0.0 which solves the issue until it auto updates again. My error window says as follows:

Uncaught Exception:
Error: Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232 at new WindowsPtyAgent
(C:\Users\my_name\AppData\Local\hyper\app-2.1.0\resources\app.asar\node_modules\nod....24) at new WindowsTerminal
(C:\Users\my_name\AppData\Local\hyper\app-2.1.0\resources\app.asar\node_modules\nod....24) at spawn
(C:\Users\my_name\AppData\Local\hyper\app-2.1.0\resources\app.asar\node_modules\nod....12) at session
(C:\Users\my_name\AppData\Local\hyper\app-2.1.0\resources\app.asar\session.js:53:18) at initSession
(C:\Users\my_name\AppData\Local\hyper\app-2.1.0\resources\app.asar\ui\window.js:102:24) at Server.Window.rpc.on.options
(C:\Users\my_name\AppData\Local\hyper\app-2.1.0\resources\app.asar\ui\window.js:105:7) at emitOne (events.js:115:13) at Server.emit(events.js:210:7) at Server.ipcListener
(C:\Users\my_name\AppData\Local\hyper\app-2.1.0\resources\app.asar\rpc.js:33:11) at emitTwo (events.js:125:13)

**Comment by Piteryo** [comment]
Has the same issue. Sometimes it works after launching it with admin privileges or in a specific folder but it's weird.

**Comment by i-rakoon** [comment]
While macafee's real time scan is turning ON, i have the same issue.

**Comment by smaccombie** [comment]
Seems to be a problem with antivirus and WinPTY see Microsoft/node-pty#208, this is also a duplicate issue #2832 

Look like you can try:
- Running hyper as admin
- Exempt the hyper folder from any real time scanning
- Trying out Ryan's solution in the MS repo

**Comment by llslim** [comment]
I just up updated to 2.1.1 is there a reason to have AppData/Local/hyper/app-2.1.0 and AppData/Local/hyper/app-2.1.1 directories at the same time? Is it feasible to remove the version from the directory name and have it overwrite the old version? It would suck have to exclude the same winpty-agent.exe files through mcafee real-time scan each time hyper release a new version. Just something to think about.

**Comment by tanuj-05** [comment]
> While macafee's real time scan is turning ON, i have the same issue.

Thanks! I turned it off and was able to run it!

**Comment by acollins1991** [comment]
@llslim fix worked for me, although if there's an update I'll need to exclude the file again due to the directory change.

**Comment by ppot** [comment]
We are on `2.1.2` now. I will close this as it's an old version
