### ISSUE TITLE
hyper-search wont work post last update

### ISSUE THREAD

**Issue by ratulmukherjee4** [zeit/hyper#3366]
hyper-search wont work post last update (v2.1.0).
 
Error on the console is as follows : 

Uncaught TypeError: term.getRowCount is not a function
at HyperSearchTerm.legacySearch
/.hyper_plugins/node_modules/hyper-search/src/containers.js:312:30

**Comment by ratulmukherjee4** [comment]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mojave
- **Hyper.app version**: 2.1.0 (stable)
- **The issue is reproducible in vanilla Hyper.app**:  Yes 
## Issue
hyper-search wont work post last update (v2.1.0).

Error on the console is as follows :

Uncaught TypeError: term.getRowCount is not a function
at HyperSearchTerm.legacySearch
/.hyper_plugins/node_modules/hyper-search/src/containers.js:312:30

**Comment by Sufiane** [comment]
I just happen to install it and it works like a charm on my end.

I have the same setup as you.
Hyper: 2.1
Hyper-search: 0.0.11
OS: Mac OS Mojave 10.14
