### ISSUE TITLE
Add wrapper around window controls (linux)

### ISSUE THREAD

**Issue by jakub-chatrny** [zeit/hyper#3372]
While I was creating [plugin](https://github.com/jakub-chatrny/hyper-macos-mjv-dark-theme) for re-styling window controls (to matching gnome shell theme) I've come around to issue that window controls are just plain `svg` elements. 
You cant change Svg path using css and you can't use `:after` or `:before` either.
Adding `div` wrapper around `svg` element like this:
```                
                <div
                  className={`header_closeWindow ${left ? 'header_closeWindowLeft' : ''}`}
                  onClick={this.handleCloseClick}
                >
                  <svg className="header_shape">>
                    <use xlinkHref="./renderer/assets/icons.svg#close-window" />
                  </svg>
                </div>
```
would allow change style of window controls easily just by using css.

Otherwise a I would have to completly rewrite header via decorator or cover default controls with mine. I can provide PR if feature gets approved.

**Comment by rauchg** [comment]
I'm always +1 on adding more styling possibilities.

**Comment by jakub-chatrny** [comment]
PR is ready [#3392](https://github.com/zeit/hyper/pull/3392)
