### ISSUE TITLE
Messy code for Chinese

### ISSUE THREAD

**Issue by ieiayaobb** [zeit/hyper#3377]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.2
- **Hyper.app version**: 2.1.0(stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ieiayaobb/7c98108c0889eb4226735522f9f75918 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: That part is a canvas, so I cannot get the dom value.
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

![image](https://user-images.githubusercontent.com/1452329/50578661-a8f47180-0e77-11e9-9076-459a05bed9cd.png)
it should be a Chinese value: 'Google 云端硬盘', but it displays as 'Google ????????????'
it runs well when I was using Chinese as my OS language, but when I switch to English, this issue comes out.

**Comment by mu-yu** [comment]
try to set different `fontFamily` which is support Chinese in your `.hyer.js`.
配置文件里面换个字体试试？

**Comment by ieiayaobb** [comment]
@mu-yu it doesn't make sense, I changed to use 'Menlo' instead, the issue is still

**Comment by mu-yu** [comment]
try move powerline fonts to low priority level after Menlo.

**Comment by ieiayaobb** [comment]
Actually, I tried to only leave 'Menlo' only, it still cannot be fixed. 
I even kept each one only of the fonts list, the issue is still.

**Comment by Xwai** [comment]
Maybe there's something wrong with your locale setting. Check your locale setting.
```
$ locale
```
If `LANG=` and `LC_ALL=` is not set, add the following code to your zshrc or bashrc. Make sure source the rc file after adding them.
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
Hope it will help :)

**Comment by ieiayaobb** [comment]
@Xwai it works, thanks a lot

**Comment by songzenghui** [comment]
how to solve it on Window10
