### ISSUE TITLE
Cannot split panes in 3.0.0-canary.1

### ISSUE THREAD

**Issue by olivier-w** [zeit/hyper#3381]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.14.2
- **Hyper.app version**: 3.0.0-canary.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/olivier-w/703cc82128c90bb3016def9a64555477
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: works again when downgrading to 2.1.0 stable

## Issue
Cannot split panes in 3.0.0-canary.1. 

Pressing the key combo (⌘D or ⌘+Shift+D), using the menu items, or the right-click context menus does not work anymore. 

Downgraded to 2.1.0 and it's working again.

**Comment by chabou** [comment]
I think this is caused by `hypercwd`.
Try to remove the plugin.

**Comment by olivier-w** [comment]
You are correct, thanks! Sorry about that.
