### ISSUE TITLE
Hyper keeps writing "Dead"

### ISSUE THREAD

**Issue by Nashuim** [zeit/hyper#3395]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro 1809
- **Hyper.app version**: Hyper 3.0.0-canary.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/Nashuim/21e76442b3a6f873ce75a0b23d05ebce
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Plugins don't seem to affect this

## Issue
This is a rather bizarre bug that started happening once I updated to 3.0.0. 
I have a keyboard with the Portuguese layout: https://en.wikipedia.org/wiki/Portuguese_keyboard_layout#/media/File:KB_Portuguese.svg

Every time I try to type ~, ^ or ´ or ` Hyper seems to write "Dead" instead
![dead](https://user-images.githubusercontent.com/5592694/50761109-75438e00-1261-11e9-9283-40401c6899d9.PNG)

Usually these characters are normally paired with another letter (like ã) only appearing after being followed by one. But regardless of being followed or not Hyper will always add "Dead".

**Comment by garyx** [comment]
I have a similar issue that might be related to this. I am not sure if I should log a separate issue for it. In my case when I hit the AltGr button on my keyboard hyper returns AltGraph as text in the terminal. My keyboard layout is Icelandic and this happens with no plugins enabled. 

Ubuntu 18.04

And I am running the same version 3.0.0 Canary 3 

This happened after the upgrade from 2.1.0 that I had before.

**Comment by garyx** [comment]
I just tested 3.0.0-canary.2 and this is an issue there, however using 3.0.0-canary.1 is fine and I don't see this happening there so this is something that gets introduced in 3.0.0-canary.2 for me at least.

**Comment by Nashuim** [comment]
I can confirm that canary.1 does indeed work so the bugs are likely related

**Comment by jcklpe** [comment]
Pretty sure your terminal is possessed.

**Comment by suvl** [comment]
Having the exact same issue, but with stable

**Comment by onecamp** [comment]
This should be fixed on [3.0.0-canary.5](https://github.com/zeit/hyper/releases/tag/3.0.0-canary.5). Please reopen if it pops up again.
