### ISSUE TITLE
windows height after split

### ISSUE THREAD

**Issue by qxuchn** [zeit/hyper#3397]
- **win10 1809**: 
- **2.1 stable**: 

## Issue
When I split the windows with ctrl+shift+d/e, the new windows always at the end of the windows, and I need scroll up to the top position

**Comment by qxuchn** [comment]
#1785

**Comment by torrieri** [comment]
I have the same problem

**Comment by qxuchn** [comment]
> I have the same problem

I solve it stupid by add `clear` in .bashrc, because I found it will going to the end when I `clear` it. At least we can use it with this method.
