### ISSUE TITLE
Column selection

### ISSUE THREAD

**Issue by jwoertink** [zeit/hyper#340]
In OSX terminal, holding `option` key turns cursor to cross-hair allowing you to highlight by column instead of rows. 
In Terminal:
<img width="234" alt="screen shot 2016-07-21 at 11 01 12 am" src="https://cloud.githubusercontent.com/assets/2391/17033317/773bd46e-4f32-11e6-8268-344a35f16b2f.png">

In HyperTerm:
<img width="180" alt="screen shot 2016-07-21 at 11 01 55 am" src="https://cloud.githubusercontent.com/assets/2391/17033341/95f419e8-4f32-11e6-9135-fdc9decbae77.png">

**Comment by chabou** [comment]
It has been duplicated by #2697. But reference has been added there.
So I am closing this issue.
