### ISSUE TITLE
Hyper Terminal JavaScript Error

### ISSUE THREAD

**Issue by zamgill** [zeit/hyper#3404]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 ver 1803
- **Hyper.app version**: 2.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/zamgill/fe80c14afe1d8ce12f5638040955d609
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Getting the following error when launching hyper. This happens only with v 2.1.1. Hyper version 2.0.0 is working fine but whenever i install 2.0.0 it automatically updates to 2.1.1.
![image](https://user-images.githubusercontent.com/22265437/50928090-aa014200-1427-11e9-9cfa-5f5aaa193dbe.png)

**Comment by EliazTray** [comment]
I also had this problem, and i couldn't reactivate `hyper.exe` anymore.

**Comment by Alexfrits** [comment]
Same here problem here.
- Windows 10;
- Hyper 2.1.1 (issue occured on 2.1.0 too);
- Disabled all plugins (deleted `/.hyper_plugins`);
- deleted `AppData/Local/hyper`;
- deleted `.hyper.js` config;
- Exact same error message.

I Switched to the canary version (3.0.0-canary.4) and it seems to work, but without any plugins or custom config which is kind of useless.

Hope it helps,
if the issue is taken into account I'd be glad to investigate further. 🔍

**Comment by PiaoLiangHXD** [comment]
Same here problem here.

Windows 10;
Hyper version 2.0.0 is working well, but it automatically updates to 2.1.2. I tried other versions, like 2.1.0, 3.0.*, all occurred this error. Which is quite annoying.

**Comment by zamgill** [comment]
This issue was being caused by McAfee AntiVirus. I added exception WinPTY Agent and everything worked fine.

Try disabling you antivirus and see if it starts working, if it does then add exception in your antivirus.

**Comment by Alexfrits** [comment]
Thanks @zamgill,
looks like it could be the same cause. I also have McAffee here, however I won't be able to try your fix because I'm using an enterprise version and I don't have the rights (and it's against the company's policy) to disable my antivirus or even whitelist _WinPTY Agent_.
I may contact my administrator to try and find a solution.

Thanks for the follow up 👍

**Comment by PiaoLiangHXD** [comment]
> Thanks @zamgill,
> looks like it could be the same cause. I also have McAffee here, however I won't be able to try your fix because I'm using an enterprise version and I don't have the rights (and it's against the company's policy) to disable my antivirus or even whitelist _WinPTY Agent_.
> I may contact my administrator to try and find a solution.
> 
> Thanks for the follow up 👍

Exactly the same situation! For me, I delete the folder 2.1.2 and update.exe to stop auto update. It seems work well! I just continue to use 2.0.0. Hope further version could have other solution with WinPTY.

**Comment by Stanzilla** [comment]
should no longer happen with CI builds of canary and the next release

**Comment by Shahinthecoder** [comment]
I deleted McAfee but Hyper keeps crashing with the same message.

**Comment by rahatkar** [comment]
Hyper terminal(version 3.0.2) JavaScript error

**Comment by bet4it** [comment]
@rahatkar Try https://github.com/zeit/hyper/suites/469423654/artifacts/2035140

**Comment by rahatkar** [comment]
Still not working 
It throws error saying "Installation has failed"

**Comment by EbenezerKobinaAcquah** [comment]
> Hyper terminal(version 3.0.2) JavaScript error on window 10 How to fix this error? Reply ASAP

I have the same problem. Did you get the solution?

**Comment by jeal0uspengu1n** [comment]
How is this closed man, opened up hyper maybe after 3 months and now the same error T_T 
PS I dont have any antivirus

**Comment by bet4it** [comment]
@EbenezerKobinaAcquah @jeal0uspengu1n Could you post the screenshot of the error?

**Comment by jeal0uspengu1n** [comment]
So what happened is that I accidentally deleted git from my pc and was trying to run hyper and it was throwing this error, when I installed git (bash) again it got resolved.
PS- The error was same as one in the screenshot!

**Comment by Jiju47** [comment]
Just go to EDIT ---> Preferences and then select all. Just remove the script and add the following script instead and save the file:-

// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'salmon',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: true,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: true,

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false,

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
    
    hyperTabs: {
      border: true,
      tabIconsColored: true,
      activityColor: 'salmon',
      activityPulse: false,
      dirtyColor: 'salmon'
    }
    
  },
  

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: ['hyper-chesterish', 'hyper-tabs-enhanced', 'hyper-always-on-top'],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
