### ISSUE TITLE
High CPU usage, resource leaks, and erratic cursor blinking after splitting panes

### ISSUE THREAD

**Issue by igorsdv** [zeit/hyper#3408]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 29
- **Hyper.app version**: 2.1.1
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

Splitting panes and closing them repeatedly leads to continuous high CPU usage, a memory leak, as well as the erratic cursor blinking behaviour described in #3318 and #3351.

### Steps to reproduce

- Split the pane (horizontally or vertically).
- Close the new pane, leaving the old one in place.
- Repeat 30+ times for a noticeable effect.

A similar effect can be seen when opening and closing multiple tabs as described in #3281.

The memory leak can be confirmed via Developer Tools by going to Memory > Take Snapshot and observing multiple non-GCed instances of type Term (React component) and Terminal (xterm.js classes) even when only one pane remains open.

### Root cause

The issue is caused by unreleased event listeners in xterm.js, and in particular by calling `Terminal.open()` repeatedly on the same instance. **I will be submitting a PR shortly with a fix.**

**Comment by MircoT** [comment]
I have the same issue with this configuration:

**HyperJS Version**: `2.1.1`
```
Plugins: 
  hyper-pane (2.1.3),
  hyper-night-owl (1.1.0),
  hyper-search (0.0.11),
  hyper-blink (1.1.2)
```

OS: macOS `10.14.2`

**Comment by MircoT** [comment]
I found that the new session created is not inserted well:

[https://github.com/zeit/hyper/blob/da535403776f956a9351cffe6f6b2d0fea03d4f5/lib/reducers/sessions.js#L38](https://github.com/zeit/hyper/blob/da535403776f956a9351cffe6f6b2d0fea03d4f5/lib/reducers/sessions.js#L38)

Then, when asking for close the session, such session is not there and you will have the prompt of this error:

[https://github.com/zeit/hyper/blob/da535403776f956a9351cffe6f6b2d0fea03d4f5/lib/reducers/sessions.js#L92](https://github.com/zeit/hyper/blob/da535403776f956a9351cffe6f6b2d0fea03d4f5/lib/reducers/sessions.js#L92)

Probably this is related also to blink problems. Maybe these sessions are completely lost and they will work in background increasing the CPU usage.
