### ISSUE TITLE
Hyper install error

### ISSUE THREAD

**Issue by SergioReis97** [zeit/hyper#3418]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 19.1 Tessa 
- **Hyper.app version**:Hyper 2.1.1 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/SergioReis97/528b980e9f5bdeac3650320340e0e6f6
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Fresh installed hyper from the .deb file and i'm able to run and change default configs, but trying to run something like `hyper i hypercwd` throws some error. 

```$ hyper i hypercwd
/opt/Hyper/resources/bin/cli.js:19146
      getPlugins = memoize(() => getProperties().find((a) => 'plugins' === a.key.name).value.elements),
                                                                                      ^

TypeError: Cannot read property 'value' of undefined
    at memoize (/opt/Hyper/resources/bin/cli.js:19146:87)
    at d (/opt/Hyper/resources/bin/cli.js:19130:22)
    at Object.install (/opt/Hyper/resources/bin/cli.js:19176:37)
    at Args.args.command (/opt/Hyper/resources/bin/cli.js:9934:45)
    at Args.runCommand (/opt/Hyper/resources/bin/cli.js:11318:37)
    at Args.module.exports [as parse] (/opt/Hyper/resources/bin/cli.js:15089:10)
    at main (/opt/Hyper/resources/bin/cli.js:9991:18)
    at Object.module.exports.name (/opt/Hyper/resources/bin/cli.js:10038:1)
    at __webpack_require__ (/opt/Hyper/resources/bin/cli.js:20:30)
    at Ap (/opt/Hyper/resources/bin/cli.js:63:18)```

**Comment by carsy** [comment]
Same here and I'm using Mac.

**Comment by robertgrzonka** [comment]
Hi! Did you manually add `hypercwd` into `localPlugins` in your `.hyper.js`? When you run `hyper i hypercwd` this plugin should be added into `plugins` array like this:

```javascript
plugins: [
  // some plugins
  'hypercwd'
]
```

I guess that this was not your intention.

 Please pop `hypercwd` from `localPlugins` to be an empty array and try run `hyper i hypercwd` once again.

**Comment by SergioReis97** [comment]
Oops, my bad. After tying to install it via the command I was trying to add it manually and forgot to remove it

**Comment by robertgrzonka** [comment]
I'm glad I could help anyway :)

**Comment by SergioReis97** [comment]
Reinstalled to have the default config file, managed to successfully install plugins but found out that something else. after some testing apparently i had removed the default `plugins: [],` array and that started throwing the error. Thanks for the help
