### ISSUE TITLE
Unable to open a new tab or split the window. 

### ISSUE THREAD

**Issue by thebadhatter** [zeit/hyper#3419]
- **OS version and name**: Windows 10 Pro Insider Preview Build 18317.rsprerelease.190111-1556
- **Hyper.app version**: 3.0.0
- **[Gist]**: (https://gist.github.com/thebadhatter/9b32d228664304a141fef25eb1c6398a.js) 

I am unable to open a new tap or split the window.
I get the following error:

![sharedscreenshot jpg](https://user-images.githubusercontent.com/8063814/51342322-9ece9780-1a61-11e9-8490-95de54ef4da0.png)

**Comment by frankieshakes** [comment]
@thebadhatter Any chance you're using the [hypercwd](https://github.com/hharnisc/hypercwd) plugin? If so, you might want to upgrade to the latest version, which includes a fix for being unable to open new tabs.

**Comment by thebadhatter** [comment]
I am! Thank you very much! This did the trick. I was certain I had upgraded my plugins prior to testing. 😣

**Comment by frankieshakes** [comment]
> I am! Thank you very much! This did the trick. I was certain I had upgraded my plugins prior to testing. 😣

Happy to help!

**Comment by onecamp** [comment]
This looks solved. Please let me know if it's not
