### ISSUE TITLE
How to disable link click action

### ISSUE THREAD

**Issue by jstangroome** [zeit/hyper#3426]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro x64 1809
- **Hyper.app version**: 2.1.1

## Issue

When clicking in the terminal window to give focus, or to select text for copying, the click often lands on text that Hyper considers to be a URL and then Hyper opens the URL in my default browser which is unwanted in this scenario.

It appears that pre Hyper 2.x the URL click handler was a separate extension and supported the click being disabled or requiring a modified key to be held while clicking to trigger the navigation:
https://github.com/zeit/hyperlinks#change-click-action

Now that this URL click handling is built into Hyper 2.x, how can I disable the behaviour, or require a modifier key?

**Comment by eromoe** [comment]
Today is my first try to hyper , this really annoy me !  I want a simple way to disable this .

**Comment by gujunhk** [comment]
> Today is my first try to hyper , this really annoy me ! I need a simple way to disable this . Any workaround for now ?

The issue is watched by @ppot .
However, it hasn't be planned.

**Comment by anthonylauzon** [comment]
in ui/window.js:

`
    // xterm makes link clickable
    window.webContents.on('new-window', (event, url) => {
      const protocol = typeof url === 'string' && parseUrl(url).protocol;
      if (protocol === 'http:' || protocol === 'https:') {
        event.preventDefault();
        //shell.openExternal(url); <-----the devil
      }
    });
`

**Comment by anthonylauzon** [comment]
in ui/window.js:
```
    // xterm makes link clickable
    window.webContents.on('new-window', (event, url) => {
      const protocol = typeof url === 'string' && parseUrl(url).protocol;
      if (protocol === 'http:' || protocol === 'https:') {
        event.preventDefault();
        //shell.openExternal(url); <-- comment the devil here
      }
    });
```

**Comment by droope** [comment]
I too would like this behaviour to be disabled or at least configurable. I don't know how to apply @anthonylauzon's patch without having to rebuild the terminal, which I can't do right now :( may try later if I have some time.

**Comment by abroglesc** [comment]
Configurable would be ideal. Coming from iTerm2 they had it to where if I held command, then clicked a link it would open in a browser. Allowing to disable this functionality or add in a modifier like holding command + click link would be amazing!

**Comment by joshwcomeau** [comment]
++ this is the single biggest issue I'm having with Hyper, the server I use fills the window pointless URLs and I can't focus the window without very careful clicking.

Is this something the maintainers are open to? I could maybe open a PR to add a config option, if there's a willingness to merge it.

**Comment by zcaceres** [comment]
I also find this *extremely* frustrating. Ideally it should be configurable or at least only happen with a key press + click action.

**Comment by sydneyitguy** [comment]
👍

**Comment by regs79** [comment]
I think at least a config option for this would be good.

My dev browser isn't the same as my default and they're on different desktops. If I accidentally 
click the link - which can happen just trying to focus on the terminal - I get sent 3 desktops over.

**Comment by edk** [comment]
@anthonylauzon - thank you so much!   you saved my sanity.  i was able to rebuild with your tip.  Luckily it was pretty quick and painless to rebuild.

**Comment by ppamorim** [comment]
Please give us a option to disable this.

**Comment by woutervanwijk** [comment]
+1

**Comment by Groovylein** [comment]
+1

**Comment by danimas** [comment]
Bump up

**Comment by ernie18a** [comment]
+1

**Comment by grgmgd** [comment]
+1

**Comment by shyjal** [comment]
+1
