### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by shani301196** [zeit/hyper#3438]
- [x] Your Hyper.app version is **2.1.1**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

 - **Hyper version**: undefined "2.1.1"

 - **OS ARCH VERSION:** win32 x64 10.0.17134
 - **Electron:** 1.8.8  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 14,
  "fontFamily": "Monaco, Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "\n      .tab_tab {\n        background-color: #1f2329 !important;\n      }\n      .tab_tab.tab_active {\n        background-color: #282c34 !important;\n      }\n    ",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "shell": "/bin/zsh",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "summon": {
    "hotkey": "Cmd+`"
  },
  "hypercwd": {
    "initialWorkingDirectory": "~/Development/Sites"
  },
  "hyperStatusLine": {
    "dirtyColor": "salmon",
    "aheadColor": "ivory",
    "footerTransparent": true
  },
  "hyperTabs": {
    "trafficButtons": true,
    "border": false,
    "tabIconsColored": true,
    "closeAlign": "right"
  }
}

          {
  "plugins": [
    "hyper-tabs-enhanced",
    "hyperterm-atom-dark",
    "hypercwd",
    "hyperterm-paste",
    "hyper-statusline",
    "hyperterm-summon"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by onecamp** [comment]
Closing as no description of the issue was provided. Feel free to reopen with more details
