### ISSUE TITLE
Error launching WinPTY agent: ConnectNamedPipe failed: Windows error 232 at new WindowsPtyAgent 

### ISSUE THREAD

**Issue by michalakis** [zeit/hyper#3442]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows 10  64bit
- **Hyper.app version**: 2.1.1
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A 
- **The issue is reproducible in vanilla Hyper.app**: no add ons on hyper

## Issue
guys I install hyperjs and as soon  as it runs  i get this error. I tried running  it as administrator, but still get  the same error
![2019-01-25 4](https://user-images.githubusercontent.com/7579525/51732469-08b0f780-2087-11e9-9de6-51ee8d9005bc.png)

**Comment by michael-rabbai9** [comment]
I'm having the exact same error on startup after installation. I also tried running as administrator and that did not fix it.

![image](https://user-images.githubusercontent.com/33554119/51795129-7c005980-21ac-11e9-860d-44866d1a83d0.png)

**Comment by ajay340** [comment]
I have the exact same error message as michael-rabbai9 and michalakis.

**Comment by vishnoisuresh** [comment]
I am facing the exact same issue.

**Comment by SlowburnAZ** [comment]
Same issue here...

**Comment by WitoTV** [comment]
Can confirm, same issue here.

**Comment by mmendez512** [comment]
Same issue with new install, and running it as admin did not work.

**Comment by yanlinaung30** [comment]
Same issue

**Comment by ychuckt8** [comment]
Same issue with a new install, and running it as admin did not work.

**Comment by jenaro94** [comment]
Check turning antivirus off, read it on some other post, turned off mcaffe and it worked just fine

**Comment by ychuckt8** [comment]
The Hyper is working while the McAfee turned off, but how to fix so it still works while McAfee is on?

**Comment by jenaro94** [comment]
The issue is being worked on, https://github.com/rprichard/winpty/issues/142

**Comment by ychuckt8** [comment]
Thank you @jenaro94, the link you provided above is working, it fixed the issue.

All,

please follow the link below to fix the Hyper issue:
[https://github.com/Microsoft/node-pty/issues/208](url) and see **rprichard ** commented on Oct 15, 2018.

**Comment by ajay340** [comment]
> Thank you @jenaro94, the link you provided above is working, it fixed the issue.
> 
> All,
> 
> please follow the link below to fix the Hyper issue:
> [https://github.com/Microsoft/node-pty/issues/208](url) and see **rprichard ** commented on Oct 15, 2018.

The link is down, how did you fix the issue with hyper?

**Comment by jenaro94** [comment]
Hello @ajay340 , as I mentioned above I turned McAfee off

**Comment by ychuckt8** [comment]
The link is: [https://github.com/Microsoft/node-pty/issues/208](https://github.com/Microsoft/node-pty/issues/208) and sees ForauDNB's reply.

**Comment by cybertk** [comment]
@ychuckt8  Thank you so much, @FoaruDNB's fix works like a charm, link is here: https://github.com/Microsoft/node-pty/issues/208#issuecomment-463645503
