### ISSUE TITLE
RFC: Session API

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#3446]
# Goal
`Session` and `pty` decoupled. 
Some plugins need more control about Session instances in main process. It would be required, for example, if a plugin want to launch the `pty` in another host (like #2978) or intercept pty stream to duplicate/record/stream/log it.
Interception can already be done with a middleware in renderer process, but having a Session without a `pty` can't.

# Proposal
I would suggest to add a new API entry: `decorateSessionClass(Session)`. A plugin can expose this function that would return a new class that inherit from the (kind of) Session class received in parameter.

If multiple plugins declare this hook, we would finally get a class that have been multiple times inherited. It can lead to some conflicts but this is already the case for other decorate functions.

**Comment by ppot** [comment]
Decoupled architecture: Session into single process. You can attach them from their sessionId which are registered from hyper-core. Enabling background job profiling etc. Event-hook for session notification.  Sometimes you wan't to close the pane but not the shell process inside it.

**Comment by chabou** [comment]
I think that is out of my context. I was only thinking about offer possibility to plugin to modify Session behavior. Sometimes you don't want that a session create a pty and for now, there isn't any way to do this.

With this RFC, you'll be able to achieve your single process isolation with a plugin 😆

**Comment by ppot** [comment]
Yeah. That's what i'm saying as attaching them :). More versatility by having them not strictly bound to the view as a pty-session as of ATM.

**Comment by j-f1** [comment]
Can this be closed?

**Comment by chabou** [comment]
Yes! Thanks!

**Comment by MisterTea** [comment]
@chabou  Is there a PR to track the progress of this RFC?
