### ISSUE TITLE
Hyper (Windows) prevents PC from turning display off, even after being closed

### ISSUE THREAD

**Issue by dlucadou** [zeit/hyper#3459]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro x64 build 17763
- **Hyper.app version**: 2.1.1 stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [hyper.js](https://gist.github.com/dlucadou/1dec3954c48e70b1728df70b9fe57a04)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Whenever I open Hyper, it breaks the ability of Windows to automatically turn the screen off after 10 minutes (which is what I have set in power options).

To reproduce:

1. Open Hyper
2. Close Hyper
3. The display never goes to sleep

This affects my desktop and my Surface (however, it will forcibly go to sleep after 5 minutes so it's not as much of a problem, but with the keyboard up the display remains on for those 5 minutes).

I tried rebooting Windows, opening WSL (the default, command prompt based shell), and closing it. (No other applications are open in the foreground.) After 10 minutes, the monitors were automatically turned off, as expected. Then I opened Hyper and closed it. The displays no longer turn off until I reboot. Hyper does not appear to be hanging around in the background, the process does not remain in process explorer.

**Comment by ppot** [comment]
@dlucadou Lastest stable is : `2.1.2` could you upgrade and try again if it still remain?

**Comment by dlucadou** [comment]
The issue is no longer present, my PC turns off the displays as expected.

**Comment by ppot** [comment]
Great 💪
