### ISSUE TITLE
Request timed out when installing plugins

### ISSUE THREAD

**Issue by lpuglia** [zeit/hyper#3473]
- Windows 10
- Hyper 2.1.2

## Issue
Hello, whenever i try to install something using

```hyper i <package>```

I get:
```
Request timed out
Plugin check failed. Check your internet connection or retry later.
```

Does anyone have any idea how to debug this? My Internet connection is ok and i already set the http, https, ftp and socks proxies.

**Comment by rauchg** [comment]
That's managed by npm. Does npm work for you?

**Comment by lpuglia** [comment]
yes, it does work if i set the proxy with:

```npm config set proxy```
