### ISSUE TITLE
Open hyper here is not working on Windows 10 1809 with PowerShell

### ISSUE THREAD

**Issue by mrg0lden** [zeit/hyper#3477]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10  UPDATE 1809 x64 build 17763.316
- **Hyper.app version**: 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mrg0lden/83a75a7b43b4c60ff85868148680ad4b
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**:  Is Vanilla (except changing to powershell)

## Issue

I updated to Windows 10 1809 recently and also updated to hyper 2.1.2. I'm not sure which upgrade process causes this, but it used to work as expected with same attached .hyper.js file before both updates. Now it opens PowerShell in its directory `C:\WINDOWS\System32\WindowsPowerShell\v1.0`.

**Comment by hgt312** [comment]
I updated to win 10 1809, and I cannot install Hyper by running 'hyper-Setup-2.1.2.exe'.

**Comment by Heegiiny** [comment]
I think I have this issue too.

**Comment by Heegiiny** [comment]
Hyper doesn't opens from folder context menu at all, it opens error window. Hyper opens if I remove "%V" from registry key `\HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\Hyper\command`, but in default foldel. Or it opens after typing `hyper C:\` in run windows with the mentioned folder.

**Comment by Heegiiny** [comment]
I have an issue kinda like this. 

My Windows version is Windows 10 1809 and Hyper version is 2.1.2, but I'm using git-bash.exe instead of powershell. It does the same with empty `shell` parameter, using cmd.exe as a shell.
"Open Hyper here" works fine when I right click on the right pane (folder view) of Explorer or on the desktop. But it fails when I try to right click on a folder in the folder tree in the left pane of Explorer. Hyper doesn't open and the error window appearences on the screen.

**Comment by mrg0lden** [comment]
I want to note that I got this issue has got resolved, but I don't know how.

**Comment by Heegiiny** [comment]
@mrg0lden Can you do "Open Hyper here" with folders in the explorer's sidebar tree?

**Comment by mrg0lden** [comment]
@Heegiiny I actually don't usually use it, but no it doesn't work. I suggest that you make a new issue for this as it's a very specific case. 
I got the error"There's no associated program with this...".
