### ISSUE TITLE
URL-Support for different shells?

### ISSUE THREAD

**Issue by hoffi** [zeit/hyper#348]
Currently the url is only matched if the "unknown command" error matches my local shell.
But when i ssh on a host that runs another shell (i use `fish` locally but `bash` runs on remote) the url is not matched anymore.
Couldn't it just check for all regular expressions?

This also applies for this example: 

```
fish$ bash -c "http://www.google.de/"
```

**Comment by ash02** [comment]
Hi, I'm new to open source and would like to take up this issue.
Could you please tell me where should I start?
Thank You

**Comment by chabou** [comment]
It should have been fixed, thanks to xterm.js
