### ISSUE TITLE
showing current git branch and removing computer name from Hyper

### ISSUE THREAD

**Issue by grantis** [zeit/hyper#3482]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS version: 10.14.1
- **Hyper.app version**: version: 2.0.0-canary. 11 (stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/grantis/b6546c7ce8bff2bcfaba4e5c009c4f28
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: is vanilla

## Issue
Hi Hyper devs, 

I haven't been able to discover how to configure Hyper to display the current working git branch as I've seen on my school linux machines. And I'm not sure how to remove my computers name from the Hyper CLI, Would someone please advise as to how I can get this setup? 

Many thanks

**Comment by ppot** [comment]
Hi, this is done by you're shell. You can look at `zsh` or `fish`

**Comment by kjhx** [comment]
You can configure `bash` to display these types of things by modifying `~/.bash_profile`. There are some sweet tools like [this](https://www.kirsle.net/wizards/ps1.html) that can get you started, and various `.bash_profile`'s I've seen on GitHub that achieve something similar to what you're saying.
