### ISSUE TITLE
Ubuntu 18.04 LTS cannot install any plugins with `hyper i any_plugin`

### ISSUE THREAD

**Issue by nazariyv** [zeit/hyper#3488]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
- **Hyper.app version**: 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/nazariyv/69c8bcec9cb85d6bf06be9941adfca72
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

When I `$hyper i ...` anything, I get the following message:

```nazariy@nazariy-ubuntu:~$ hyper i verminal
Gtk-Message: 12:55:13.630: Failed to load module "canberra-gtk-module"
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///tmp/.mount_hyper-lKoipm/app/resources/app.asar/index.html
Setting Hyper as default client for ssh:// protocol
Checking for notification messages
```

Which opens a new terminal and the old one is awaiting something after the above message. When you close the new terminal, you get back to the old one and the old one stops waiting and just finishes waiting. So you can now start typing new commands. But whatever plugin you are trying to install, you get the same behaviour.

**Comment by elricdesigns** [comment]
Generally that's related to running 32bit electron on a 64bit system.  To rule out the obvious, you might want to run the below in your terminal to determine which hyper to install.

```
node -p "process.arch"
```
It will show 'arm', 'ia32', or 'x64'.  Uninstall hyper, download and reinstall the correct version.  

If that doesn't fix it, you may want to try installing canberra-gtk-module.  Maybe it was missed as a dependancy.

```
sudo apt install libcanberra-gtk-module libcanberra-gtk3-module
```

**Comment by dantehemerson** [comment]
anyone solve it?

**Comment by dantehemerson** [comment]
i have the same error
