### ISSUE TITLE
Uninstalling on Ubuntu 18.04 LTS (having installed from AppImage)

### ISSUE THREAD

**Issue by nazariyv** [zeit/hyper#3492]
## Issue
Sorry for not including all of the above. How does one uninstall Hyper installed through AppImage on Ubuntu 18.04 LTS?

Thanks

**Comment by ppot** [comment]
<img width="846" alt="screen shot 2019-02-20 at 7 45 08 pm" src="https://user-images.githubusercontent.com/5577409/53135135-13f12900-3548-11e9-962b-65b7afa6912a.png">

**Comment by nazariyv** [comment]
what about the changes it has made to .bashrc? I do not know what exactly it changed

**Comment by ppot** [comment]
Why would we tool up your `.bashrc` ? It's your shell profile ;), you use it as any terminal use it. Kind of like `.zshrc` and etc. So no change except if you made some of your own.

**Comment by nazariyv** [comment]
Thanks :)
