### ISSUE TITLE
How to unsplit window?!

### ISSUE THREAD

**Issue by CityOnTheEdgeOfForever** [zeit/hyper#3495]
I accidentally split active window, can't for the life of me find out how to unsplit. Help

**Comment by ppot** [comment]
Close it, either with the `x` action or refer yourself to the keymaps 
https://github.com/zeit/hyper/tree/canary/app/keymaps
or with the menu : Shell close

**Comment by fwoelffel** [comment]
Doesn't `Ctrl+D` close the pane?

**Comment by pcnate** [comment]
I type exit on the new terminal and it exits and removes the new split.

**Comment by curtisj44** [comment]
Is it possible to undo the split without closing a pane?
