### ISSUE TITLE
vim support for windows

### ISSUE THREAD

**Issue by abduwaly** [zeit/hyper#3497]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

**Comment by cjoshmartin** [comment]
@abduwaly Could you explain your issue in more detail?

**Comment by abduwaly** [comment]
oh , I've found out how to use vim in hyper.
`hyper-launch-menu` , this plugin solved my problems.
