### ISSUE TITLE
zoom out crashes

### ISSUE THREAD

**Issue by cwlowder** [zeit/hyper#3498]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows 10 Version 1803 (OS Build 17134.590)
- **Hyper.app version**: Hyper 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cwlowder/5113db7f2314bd250cef010de2f95372
- **Relevant information from devtools** [Violation] 'requestAnimationFrame' handler took 70ms
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
When You zoom out by holding down `ctrl+minus` for a few seconds, hyper will freeze and then crash with the following devtool output:
```
[Violation] 'requestAnimationFrame' handler took 70ms
```
You will need to change your output scope to verbose to see it. This issue occurs with my native command line aswell if I make the shell argument empty in .hyper.js

**Comment by chabou** [comment]
Reproduced. But without holding my keys.
Hyper hangs up with a font-size below 2px. (`hyperpower` is slower below 4px)

I think that xterm doesn't like to have a too small font-size.

We can certainly fix it with a 5px minimum font-size

**Comment by Kacppian** [comment]
Can I pick this up?

**Comment by juancampa** [comment]
@Kacppian please do! :raised_hands:

**Comment by Kacppian** [comment]
Submitted the PR
