### ISSUE TITLE
URLs with only a schema and 2-character TLD hostname with no trailing slash are not clickable

### ISSUE THREAD

**Issue by remino** [zeit/hyper#3503]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.14.3
- **Hyper.app version**: Hyper 3.0.0-canary.8 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/remino/2b9c70ab8111874fe06c9373b41e5eed
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

If a URL has the following, it is not clickable:
- No path and no trailing slash
- No port
- A domain name with less than 3 characters in the TLD (i.e. ccTLDs such as .ca, .jp, and .io)

Example:
- http://example.com
- http://example.com/
- http://example.com:8080
- http://example.com:8080/
- http://example.io:8080
- http://example.io/
- http://example.io:8080/
- http://example.io ← Not clickable

Also see screen recording below:

![urlnotclickable](https://user-images.githubusercontent.com/29999/53547026-3cdd7380-3b71-11e9-9760-82c160c669e9.gif)

**Comment by jschuur** [comment]
Ran into this in 2.1.2 (stable) too when I couldn't click on any of the .io links that ngrok produced.

**Comment by jaraco** [comment]
Similarly, a hyperlink without a TLD isn't clickable. Consider `http://localhost` or `http://name-resolving-in-search-path`.

**Comment by Stanzilla** [comment]
We are now using https://github.com/xtermjs/xterm.js/tree/master/addons/xterm-addon-web-links please try the canary CI builds

**Comment by jaraco** [comment]
I've configured my Hyper.js preferences for the `updateChannel: 'canary'` and I have installed 3.0.1-canary.4, but still many hyperlinks are not clickable. `http://localhost` is not highlighted, but `http://localhostl` and `http://localhost/` are. `http://name-resolving-in-search-path` (even with trailing `/`) also does not get hyperlinked. Similarly `http://example.io` still is not clickable.

Perhaps I don't understand how one would try the canary CI builds.

**Comment by Stanzilla** [comment]
Windows ci.appveyor.com/project/zeit/hyper/builds/28383913/artifacts
macOS: app.circleci.com/jobs/github/zeit/hyper/2831/artifacts

**Comment by jaraco** [comment]
I'm currently on Hyper 3.4.1 and still have this issue. Although `http://localhost` and `http://example.io` now are recognized as hyperlinks, another name without a dot still is not:

- http://name-resolving-in-search-path
- http://otherhost
- http://otherhost/foo

Should I open a new bug for these names?
