### ISSUE TITLE
Adds a lot of newline characters on open

### ISSUE THREAD

**Issue by Haquor** [zeit/hyper#3513]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Windows 10 Pro x64: 
- 2.1.2 

## Issue
I saw a few similar issues with scrolling Here's mine. When I first open Hyper version 2.1.2 from a fresh install, everything appears to work as normal, but as soon as I type, it scrolls all the way down to a blank screen.

![image](https://user-images.githubusercontent.com/737837/54011961-60408980-4142-11e9-87a7-f35f560dfb00.png)
![image](https://user-images.githubusercontent.com/737837/54011988-7b12fe00-4142-11e9-9fda-e8138c9560fa.png)
![image](https://user-images.githubusercontent.com/737837/54012040-b01f5080-4142-11e9-8bba-c951e0400de3.png)

This can only be fixed by pressing ENTER 
The cause of this seems to be a huge chunk of newline characters added on open.
The issue also appears in new tabs & new windows

Any feedback would be appreciated

**Comment by NightWnvol** [comment]
Same issue here✋

**Comment by Haquor** [comment]
> 
> 
> Same issue here✋

Are you having this on completely fresh install? No plugins?

**Comment by NightWnvol** [comment]
- @Haquor I only installed the `hyper-dracula` theme.

**Comment by alexytsu** [comment]
![Screenshot from 2019-07-01 09-41-00](https://user-images.githubusercontent.com/7680266/60403724-7cca6b00-9be4-11e9-966d-d6062e071dde.png)

Similar issue on Linux (Ubuntu 18.04) running Hyper 3.0.2 (stable)

**Comment by danteissaias** [comment]
+1

**Comment by Stanzilla** [comment]
Please try again with a current build
