### ISSUE TITLE
JavaScript error in the main process in Windows 10

### ISSUE THREAD

**Issue by arsari** [zeit/hyper#3520]
I install Hyper 2.1.2 in my Windows 10.  I love the software and work excellent in my MacBook Pro. But, when I try to run Hyper in Windows 10 I get the following windows error message:

![image](https://user-images.githubusercontent.com/22566231/54168448-e6abe280-4444-11e9-8584-091116a97c60.png)

Any possible solution?

**Comment by cjoshmartin** [comment]
I Think #3514 is having a similar problem

**Comment by arsari** [comment]
This work excellent for me.  Just add the file in the McAfee exclude files...

https://github.com/Microsoft/node-pty/issues/208#issuecomment-465624603
