### ISSUE TITLE
Hyper2 Pay site?

### ISSUE THREAD

**Issue by tempusthales** [zeit/hyper#3523]
Hi, sorry, not really an issue, just wanted to ask if this site for hyper2 is legit: https://zeit.co/blog/hyper2 or fake? 

Thanks!

**Comment by f3d0r** [comment]
Yup! [Zeit](https://zeit.co) is the main organization that hosts this repo - that is their blog post announcing features and changes for v2 of Hyper.

**Comment by ppot** [comment]
@tempusthales What do you mean as "Pay" site.
