### ISSUE TITLE
Cannot open new tab/pane

### ISSUE THREAD

**Issue by PhysRex** [zeit/hyper#3532]
- [ ] Your Hyper.app version is **2.1.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

  - **Is the issue reproducible in vanilla Hyper.app?**

## Issue

Sometimes when trying to open a new tab or new pane I get the following error message, and I'm unable to open said tab or pane. However, I can continue to use hyper in the currently opened instances. This especially happens when an ongoing process is already running, or if the computer goes to sleep and I come back to it.

Update:
The error message that pops up (see below) is 
`hyper unable to start terminal process CreateProcess failed at new WindowsPtyAgent` 
I think this might be a duplicate of [issues #2747](https://github.com/zeit/hyper/issues/2747)
![hyper-error](https://user-images.githubusercontent.com/24803126/54774671-a4239c00-4be2-11e9-82c1-d98592d90d53.png)

 - **Hyper version**: undefined "2.1.2"

 - **OS ARCH VERSION:** win32 x64 10.0.17134
 - **Electron:** 1.8.8  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 13,
  "fontFamily": "\"Ubuntu Mono\", \"Roboto Mono\", Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "6px 7px",
  "colors": {
    "black": "#000000",
    "red": "#ff0000",
    "green": "#33ff00",
    "yellow": "#ffff00",
    "blue": "#0066ff",
    "magenta": "#cc00ff",
    "cyan": "#00ffff",
    "white": "#d0d0d0",
    "lightBlack": "#808080",
    "lightRed": "#ff0000",
    "lightGreen": "#33ff00",
    "lightYellow": "#ffff00",
    "lightBlue": "#0066ff",
    "lightMagenta": "#cc00ff",
    "lightCyan": "#00ffff",
    "lightWhite": "#ffffff"
  },
  "MaterialTheme": {
    "theme": "",
    "backgroundOpacity": "1",
    "accentColor": "#64FFDA",
    "vibrancy": "dark"
  },
  "shell": "C:\\Program Files\\Git\\git-cmd.exe",
  "shellArgs": [
    "--command=usr/bin/bash.exe",
    "-l",
    "-i"
  ],
  "env": {
    "TERM": "msys"
  },
  "bell": "SOUND",
  "copyOnSelect": false
}

          {
  "plugins": [
    "hyper-alt-click",
    "hyper-search",
    "hyperdocs",
    "hyper-font-smoothing",
    "hypercwd"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by 0226zy** [comment]
I have the same problem

**Comment by 0226zy** [comment]
try del plugin hypercwd .

**Comment by ivanreese** [comment]
I've switched from hypercwd to https://github.com/LeanderFS/hypersamewd and it solved this issue for me (and performance seems to be better)

**Comment by ppot** [comment]
Plugin related. Closing
