### ISSUE TITLE
Can you use hyper in the browser no electron?

### ISSUE THREAD

**Issue by andreimc** [zeit/hyper#3538]
I want to have a browser based terminal, I’m just wondering if I can use hyper for that or is it tied heavily to electron?

**Comment by ppot** [comment]
Hyper is based with electron.

**Comment by antonholmberg** [comment]
Luckily I don't think that the browser has enough privilege to run general terminal commands. You would need some sort of server that handles the commands of the UI.

And this is basically what electron is as far as I understand, a chromium + node application.

**Comment by cjoshmartin** [comment]
Yeah it should be possible because hyper is based on [xterm.js](https://xtermjs.org/).

**Comment by ppot** [comment]
The question is not to use xterm.js but Hyper. You can use browser powered terminal using xterm.js but not Hyper in the browser.

**Comment by cjoshmartin** [comment]
I sure it possible to render the canvases inside a web browser instead of inside electron.

**Comment by ppot** [comment]
Not from a security standpoint. You want to have your pty and shell sandboxed.

**Comment by jcklpe** [comment]
I'm having trouble getting Hyper to run on a Ubuntu 18.04 machine after I install Nextcloud on it. Could the fact that Nextcloud is running a electron/node server be what is causing the problem?

Related issue here: https://github.com/zeit/hyper/issues/4039

**Comment by Mizan-Al-Sabbih** [comment]
What if we clone the hyper repo then remove Electron.js?

**Comment by ctaperts** [comment]
the use case for this would be a remote server session in the web browser, it would need to be secured with a proxy auth
