### ISSUE TITLE
Encoding of æ,ø,å

### ISSUE THREAD

**Issue by sebastianks** [zeit/hyper#3541]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

MacOS 10.14.3
Hyper 2.1.2 (no plugins)
Hyper config: https://gist.github.com/sebastianks/6312c0b0d6c5cd86a961b50bc8bd0781.js

--- 

I have an issue where Hyper encodes some nordic characters like æ,ø and å. I have no plugins and configurations at all - just plain Hyper.

This is from a `git log`:
```
Author: Sebastian Kolind S<C3><B8>rensen <sebastian@penni.io>
Date:   Mon Mar 25 15:04:28 2019 +0100
```

Can I somehow specify the encoding to utf-8?

**Comment by antonholmberg** [comment]
Could you try adding this in your `.bash_profile` file and then restart hyper

```bash
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

It solved a similar issue that I had.

**Comment by sebastianks** [comment]
@antonholmberg I tried that, but it didn't work, so I tried the obvious one which is `da_DK` since im from Denmark, and that works, but then my Vim is on danish too, which is awkward. I'll have to find a way to overwrite the global LANG and LC_ALL when opening Vim.

**Comment by antonholmberg** [comment]
```bash
alias vim='LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 vim'
```

**Comment by sebastianks** [comment]
@antonholmberg Thank you so much!
