### ISSUE TITLE
`row` and `col` fields in `CursorFrame` seem to be swapped.

### ISSUE THREAD

**Issue by ArtBIT** [zeit/hyper#3542]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Hyper.app version**: 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ArtBIT/0b99714d4f932b1c8a264de781a960a2
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

The `CursorFrame` object, returned by the `onCursorMove` callback, seem to have `row` and `col` swapped.

On the very first line of the terminal, `col` has a value of `0`, and `row` has the value of `23`.
If I hit enter, the `col` has a value of `1`, and `row` has the value of `23`. 

`y` coordinate should be mapped to `row`, and `x` coordinate should be mapped to `col`, not the other way around as in: https://github.com/zeit/hyper/blob/8733ecc84ac63c49f82bba868bbd8dcb6e27455b/lib/components/term.js#L177

**Comment by ppot** [comment]
Could you make a gif of this behavior? Would help. Appreciated.

**Comment by ArtBIT** [comment]
I don't have a visual demo of the problem, but I've linked you to the actual source of the problem:

https://github.com/zeit/hyper/blob/8733ecc84ac63c49f82bba868bbd8dcb6e27455b/lib/components/term.js#L177
```
          const cursorFrame = {
            x: this.term._core.buffer.x * this.term._core.renderer.dimensions.actualCellWidth,
            y: this.term._core.buffer.y * this.term._core.renderer.dimensions.actualCellHeight,
            width: this.term._core.renderer.dimensions.actualCellWidth,
            height: this.term._core.renderer.dimensions.actualCellHeight,
            col: this.term._core.buffer.y, // this should be x
            row: this.term._core.buffer.x // this should be y
          };
```

`X` coordinate identifies in which column we are, and the `Y` coordinate identifies in which row.
![Rows and columns](https://i.imgur.com/FTRTYQL.png)

If the cursor is on line 5, character 23, I expect `CursorFrame.row` to be 5, and `CursorFrame.col` to be 23. In reality, `onCursorMove` returns a `CursorFrame` object with `row` set to 23, and `col` set to 5.

**Comment by ArtBIT** [comment]
I would have made a pull request to fix this, but this is a breaking change, and I don't know how do you handle those.
