### ISSUE TITLE
Hyper does not work with Powershell 6.1.3

### ISSUE THREAD

**Issue by cdmihai** [zeit/hyper#3544]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 1809
- **Hyper.app version**: 3.0.0 Canary 8 and 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cdmihai/aca48f61697004281661ee11a7aee04e
## Issue
By unzipping powershell 6.1.3 (no machine install) and pointing Hyper to its executable, I get the following:
![image](https://user-images.githubusercontent.com/2255729/55040436-935d9680-4fe5-11e9-97ca-29af3878caa9.png)

Hyper 2.1.2 has better formatting:
![image](https://user-images.githubusercontent.com/2255729/55041137-ef75ea00-4fe8-11e9-84fc-a52ddea9bb59.png)

**Comment by ppot** [comment]
Seem like a Cmdlet problem. What are you trying to do? I could test this at my PC with hyper on it.

**Comment by cdmihai** [comment]
I am trying to use the latest [powershell release](https://github.com/PowerShell/PowerShell/releases/tag/v6.1.3) with Hyper. I unzip powershell, point `.hyper.js` to its exe, start up hyper, and I get that on startup.

**Comment by ppot** [comment]
I can't use psh with the lastest version...

**Comment by cdmihai** [comment]
> I can't use psh with the lastest version...
What is psh (perl shell, powershell) and whose latest version are you referring to (powershell, hyper)?

**Comment by ppot** [comment]
`powershell`. I'm on 5 and won't upgrade at work on 6.x for development reason.

**Comment by Stanzilla** [comment]
![image](https://user-images.githubusercontent.com/75278/55283974-e335b800-536d-11e9-9cb7-2602aff25564.png)

**Comment by cdmihai** [comment]
Looks like it's something specific to my machine. I tried it with all combinations, x86 / x64, zip / msi, and I get the same thing. I'll post the fix here when I get some time to debug it.

**Comment by Astrophizz** [comment]
There's some difference between running `pwsh` at launch or after. If pwsh.exe is specified as the shell to run when spawning a new session, hyper crashes with this exception. However, launching pwsh.exe from the default CMD shell works fine.

**Comment by cdmihai** [comment]
@Stanzilla, I suggest you reopen the issue. I am launching powershell via the hyper.js script (link to contents in the description) when getting this error.

**Comment by Stanzilla** [comment]
@cdmihai Just tried again and it still works, make sure you are using

`shell: 'C:\\Program Files\\PowerShell\\6\\pwsh.exe',`

**Comment by Astrophizz** [comment]
I found how to make hyper spawn with `pwsh.exe` and not crash: `shellArgs` needs to be empty. Interestingly the same solution is in another issue for a different error: https://github.com/zeit/hyper/issues/3269#issuecomment-433714051. In his scenario he was using the default `shellArgs: ['--login']`. In contrast, I was using `shellArgs: ['']` as suggested here https://github.com/zeit/hyper/issues/1020#issuecomment-272072997 and here https://github.com/zeit/hyper/issues/2438#issuecomment-342734721. The empty string solution no longer works - probably due to a change in how powershell handles arguments.

**Comment by Astrophizz** [comment]
Unless I'm misreading something, this https://github.com/PowerShell/PowerShell/commit/1523c218a6537ad367f42fcd8ad85711d7596770#diff-72f893ea967967a637206a8b9a6385cbR543 converts the empty string to `null` and guarantees an exception. That change was released with Powershell 6.1.0.

**Comment by cdmihai** [comment]
@Astrophizz, that seems to be the issue, empty string being converted to null which leads to the exception. Using something benign like `shellArgs: ['-NoLogo']` avoids that.
