### ISSUE TITLE
How do I get a correct font name on Windows ??

### ISSUE THREAD

**Issue by eromoe** [zeit/hyper#3545]
Hello, 

I have followed some article installed some font : 

`Fira Code` 
![image](https://user-images.githubusercontent.com/3938751/55054655-974bf000-509b-11e9-9ff5-aba14739c1e6.png)

`Source Code Pro for Powerline`
![image](https://user-images.githubusercontent.com/3938751/55054676-a2068500-509b-11e9-90bd-866c31b039f8.png)

Apparently, the font name don't equal to the filename .  I can only use `Fira Code`  and `Source Code Pro for Powerline` in hyper.

------

Because I am always using  a Nerd Font in msys2 , I found its file name is `DejaVu Sans Mono for Powerline Nerd Font Complete Windows Compatible`
![image](https://user-images.githubusercontent.com/3938751/55055295-8ac89700-509d-11e9-9a30-400cebf1f874.png)

Set in hyper without success . Then I go to the msys2's settings  found 
![image](https://user-images.githubusercontent.com/3938751/55055334-a2078480-509d-11e9-8ae2-6034d13a3b51.png)  in msys2 , finally got `DejaVuSansMonoForPowerline NF` .

So, the question is how can I know a font's name by the installation file `xxxx.ttf` ???  
Perhaps provide a built-in dropdown selector for fonts would be good.

**Comment by BananaAcid** [comment]
... and how to enable ligatures? (see FiraCode)

**Comment by BananaAcid** [comment]
Does that mean, Hyper is not able to use FiraCode?

**Comment by Stanzilla** [comment]
Ligatures will work when we include xterm4 and you use the ligature addon
