### ISSUE TITLE
Node Module updating error everytime i open hyper

### ISSUE THREAD

**Issue by designMoreWeb** [zeit/hyper#3551]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- MacOS Mojave
-  Hyper 3.0.0-canary.8 (canary)
- https://gist.github.com/designMoreWeb/cdc5ef8057a9a5952806a6696aca9124
- There are no errors on the console

## Issue

Hi I am on the latest version of hyper and every time i open it I get this error popup 
<img width="406" alt="Screenshot 2019-04-02 at 10 59 20 AM" src="https://user-images.githubusercontent.com/5986856/55413142-c0a2cb00-5536-11e9-9928-f22d943c160e.png">

<img width="338" alt="Screenshot 2019-04-02 at 11 02 16 AM" src="https://user-images.githubusercontent.com/5986856/55413175-d0baaa80-5536-11e9-93d2-26497ad7290b.png">

and the console shows no errors

**Comment by Stanzilla** [comment]
should no longer happen with CI builds of canary and the next release
