### ISSUE TITLE
Use/Read Windows 10 Environment Variables in Config File

### ISSUE THREAD

**Issue by irfanfadilah** [zeit/hyper#3553]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 2.1.2

## Question

Is it possible to read/use Windows 10 Env Variable inside `.hyper.js`? For example I have Windows Env Variable `PATH_TO_SOMETHING=/path/to/something`, then inside `.hyper.js` I want to use this like `shell: $PATH_TO_SOMETHING/ping/pong.exe`

**Comment by ppot** [comment]
not inside .hyperjs but inside a plugin yes you can.
