### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by kumailn** [zeit/hyper#3563]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **Hyper.app 2.1.2**: 
- **Link of a [Gist](https://gist.github.com/kumailn/81b85e092ea1f12eadf57c637f66e959) with the contents of your .hyper.js**: 
- **N/A** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **Is vanilla**: 

## Issue
Can't install any plugins with the 'i' command in hyper, getting the error 'Error: Line 1: Unexpected token ILLEGAL'

**Comment by jjustin3** [comment]
I figured out how to get plugins working once more. I'm on Windows but this process should be the same for Mac/Linux as well. Try using the config file to add the plugins, and then manually install.

1. Navigate to %appdata%\Roaming\Hyper.hyper_plugins
1. `npm install`

**Comment by kumailn** [comment]
> I figured out how to get plugins working once more. I'm on Windows but this process should be the same for Mac/Linux as well. Try using the config file to add the plugins, and then manually install.
> 
> 1. Navigate to %appdata%\Roaming\Hyper\.hyper_plugins
> 2. `npm install`

I'm on windows, but I don't have a \.hyper_plugins folder, even checked hidden folders. :/
