### ISSUE TITLE
Plugins 'hyperterm-paste' and 'hyperterm-safepaste' refuse to work

### ISSUE THREAD

**Issue by no-simpler** [zeit/hyper#3567]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.14.4
- **Hyper.app version**: 2.1.2 / 3.0.0-canary.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [link](https://gist.github.com/no-simpler/7bf973791cb4281293d13fe8a0b23ab0)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: See below
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
Plugins `hyperterm-paste` and `hyperterm-safepaste` (which modify pasting behavior) each do not work (I install them separately, not together), although they are loaded.

That is, pasting behavior is not modified in any way, e.g., trailing newlines are not removed.

**On `stable`**, dev tools say:

`hyperterm-paste`:

```
Plugin hyperterm-paste (1.1.2) loaded.
```

`hyperterm-safepaste`: 

```
Plugin hyperterm-safepaste (1.0.5) loaded.
```

**On `canary`**, dev tools say:

`hyperterm-paste`:

```
Plugin hyperterm-paste (1.1.2) loaded.
```

`hyperterm-safepaste`: 

```
[Notification] Plugin load error: "hyperterm-safepaste" failed to load in the renderer process. Check Developer Tools for details.
bundle.js:1 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".
```

**Comment by Stanzilla** [comment]
get the authors to update them :)
