### ISSUE TITLE
unable to set default zoom, font size increase doesn't seem to have any effect

### ISSUE THREAD

**Issue by kishorramanan** [zeit/hyper#3572]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **MAC 10.14.4 **: 
- **Hyper 2.1.2**: 

- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Increasing font size from default 12 to 24 doesn't seem to have any effect. Every time I reload 
the font looks as default 12 although font size is set to 24.

There is no option to set the default zoom level. since font size is not being honoured, trying to zoom in is the only alternative but then I have to do this every time I reload

**Comment by jasongaare** [comment]
I have a similar issue, that since upgrading to 2.1.2, Hyper does not respect any changes to my config file, font size, cursor color, background color, etc.

**Comment by kishorramanan** [comment]
Fixed on version 3.0.0
