### ISSUE TITLE
Can't use latest react-dom

### ISSUE THREAD

**Issue by linonetwo** [zeit/hyper#3573]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS 10.14.4
- **Hyper.app version**: Hyper 3.0.0-canary.8 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** : bundle.js:1 Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. （ `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.` ）
- **The issue is reproducible in vanilla Hyper.app**: I'm developing hyper-visual

## Issue

After upgrade react-dom to latest, this error is thrown by hyper's react.

Please upgrade react-dom inside hyper, so plugin developers can use latest styled-components, so latest styled-icons. Thanks!

**Comment by Stanzilla** [comment]
done
