### ISSUE TITLE
unable to open hyper on Ubuntu

### ISSUE THREAD

**Issue by RitikPatni** [zeit/hyper#3574]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 18.04.2 LTS
- **Hyper.app version**: Hyper 2.1.2 .deb release
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: I tried to customize it and that's when the issue appeared after that I haven't been able to locate it.

## Issue

I tried to customize hyper with my own custom config which was working fine for me on windows 10 but as soon as I copied the config file hyper stopped working and at that time I closed the config file. After that I've tried multiple times for a clean install but I was never able to do so.

**Comment by stevematdavies** [comment]
Hyper 3 no longer even installs on Ubuntu 19 either, the .deb file seems to be corrupted

**Comment by RitikPatni** [comment]
Closing this issue as it is working with the new build.
