### ISSUE TITLE
I think hyper-search should be included with the program itself

### ISSUE THREAD

**Issue by iahuang** [zeit/hyper#3577]
It's one of those features that really should be a given in any program, and while I'm glad the plugin exists, I can't think of a reason someone *wouldn't* want to install it

**Comment by kbrock84** [comment]
I don't have it installed and it's easy to install if you want it. What's the benefit of including it?

**Comment by El-Dringo-Brannde** [comment]
Related to #3075?

**Comment by Stanzilla** [comment]
it is now
