### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by StanSkrivanek** [zeit/hyper#3580]
![Screenshot 2019-05-05 at 16 31 31](https://user-images.githubusercontent.com/19324572/57196522-95f0cb80-6f55-11e9-9f44-20ab281c1577.png)
![Screenshot 2019-05-05 at 16 30 52](https://user-images.githubusercontent.com/19324572/57196523-95f0cb80-6f55-11e9-8914-7c98968b1259.png)
![Screenshot 2019-05-05 at 16 49 07](https://user-images.githubusercontent.com/19324572/57196531-b587f400-6f55-11e9-81fe-d0f32bdac0c5.png)

- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

 Hi I have experiencing sudden errors on system when launching Hyper. See  images. I have uninstalled Hyper and reinstalled again. But when I have deleted this plugin (place it on desktop), restart Hyper and tried to install it again, Hyper said that plugin is still installed. Any suggestions? 

Thanks Stan

**Comment by Stanzilla** [comment]
sounds like the plugin authors need to update their plugins
