### ISSUE TITLE
add setting to switch xterm.js' RendererType

### ISSUE THREAD

**Issue by vaaski** [zeit/hyper#3581]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

Please add a setting to choose Xterm.js' [RendererType](https://xtermjs.org/docs/api/terminal/modules/xterm/#renderertype), because of [this](https://github.com/xtermjs/xterm.js/issues/2041)

**Comment by Stanzilla** [comment]
we added that
