### ISSUE TITLE
Settings are not read from ~/.hyper.js

### ISSUE THREAD

**Issue by navinpeiris** [zeit/hyper#3583]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.14.4
- **Hyper.app version**: 3.0.0-canary.9 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/navinpeiris/a2cc6b310478fc78138b4a09a915d767
- **Relevant information from devtools** N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

The latest hyper canary does not seem to load the configuration from `~/.hyper.js` and instead uses the configuration from `~/Library/Application\ Support/Hyper/.hyper.js`.

A current work around is to copy `~/.hyper.js` to `~/Library/Application\ Support/Hyper/.hyper.js`

**Comment by juancampa** [comment]
Already working on a fix. Thanks for reporting!

**Comment by juancampa** [comment]
Fixed in `3.0.0-canary.10`

**Comment by JwanKhalaf** [comment]
I'm on Windows 10 Pro, and we don't have `~/Library/Application\ Support/Hyper/.hyper.js` so I cannot do what the workaround suggests.

But I am facing the same issue, after updating to version 3.0.0, the `.hyper.js` isn't read from `C:\Users\Jwan`

Is there a workaround for this on Windows?

**Comment by carstengehling** [comment]
+1 to @JwanKhalaf I latest Hyper on Windows 10 will not read .hyper.js from c:\Users\<username>\

**Comment by carstengehling** [comment]
@JwanKhalaf workaround for Windows 10 (until fix is out):

1. Go to the folder %APPDATA%
2. Locate the folder Hyper
3. Copy your .hyper.js to this folder. It will already contain a .hyper.js file. It is up to you, if you will overwrite it, keep a backup for later, or merge the two

**Comment by JwanKhalaf** [comment]
Thanks @carstengehling that windows workaround worked for me. <3 Much appreciated.

**Comment by y1y123** [comment]
I downloaded Hyper  3.0.2 today on mac and found that work around suggested above (move ~/.hyper.js to ~/Library/Application\ Support/Hyper/.hyper.js)  is not working. I do not see any difference in terminal after making changes.

**Comment by Xx0w0wxX** [comment]
me neither

**Comment by Lokua** [comment]
Sorry to noisy an old thread but fresh install, neither location works.

**Comment by pm-dev-1** [comment]
I had the same problem. Neither changing ~/.hyper.js. nor the workaround worked for me. 
My solution was finally to navigate to the root directory. There in /Library is the .hyper.js which is responsible for the config. 
Every change there will be applied.
