### ISSUE TITLE
Material-theme bug after updating to latest version of hyper

### ISSUE THREAD

**Issue by dpyzo0o** [zeit/hyper#3588]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  maxOS High Sierra 10.13.6
- **Hyper.app version**:  3.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/dpyzo0o/185a09c53fd258bc04389cce13fec246
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

I have only hyper-material-theme plugin installed. After I updated hyper to 3.0.0, now my terminal looks like this

![Screen Shot 2019-05-06 at 09 39 48](https://user-images.githubusercontent.com/24768249/57212115-ec581b80-6fe2-11e9-8d5d-69d247fde517.png)

I tried to reinstall material-theme plugin and it does not work.

**Comment by jdrprod** [comment]
We submit the same issue in the same time XD

**Comment by lagmanzaza** [comment]
I got the same problem  T_T

**Comment by evolify** [comment]
+1

**Comment by jdrprod** [comment]
How can I have the little cute green arrow ^^ ? @dpyzo0o

**Comment by evolify** [comment]
use zsh as the default shell.

**Comment by dpyzo0o** [comment]
@jdrprod As @evolify said..

**Comment by seisenreich** [comment]
+1

**Comment by jdrprod** [comment]
Does'nt work but no problem ^^ I will search more info later

**Comment by dpyzo0o** [comment]
@jdrprod I also used oh-my-zsh with the default theme. The arrow might come from that.

**Comment by seisenreich** [comment]
+1

**Comment by heijler** [comment]
I have the same issue, it appears to fix itself if I open the developer tools and then close them again:
view -> Developer Tools

**Comment by mattvox** [comment]
Also have the same issue, can confirm temporary fix is to open and close Developer Tools.

**Comment by tmax898** [comment]
Its seems the canvas for the xterm-cursor-layer, sending it to the back, "fixes" it, but obviously sending that layer to the back loses the cursor. As another note, on windows 10 pro ver. 17763 opening and closing the Dev Tools does not temporarily or permanently resolve the issue.
