### ISSUE TITLE
Can not activate themes on 3.0.0

### ISSUE THREAD

**Issue by kmpm** [zeit/hyper#3590]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10, 1809, 64bit
- **Hyper.app version**:  3.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/kmpm/8739b9b501175c39708aabb7ff67dde6

- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A

- **The issue is reproducible in vanilla Hyper.app**: IsVanilla
## Issue
After automatic update to 3.0.0 it looked as if I lost my theme 'hyper-solarized-light'. No big deal tried to reinstall the theme using `hyper i` but even if it installed it did not make a difference on the looks of hyper
Tried to install material and verminal but same thing happened here.
I deleted the old folders from Local and Roaming profile, downloaded 3.0.0 and reinstalled but still cant get themes to apply.

**Comment by vaaski** [comment]
I've also just run into this using a locally installed theme.
You'd think they'd test that before releasing a new version and auto-updating to it

At least the new icon looks better

**Comment by flostadler** [comment]
Same here

**Comment by yair5124302** [comment]
I had configured Hyper to run zsh and oh-my-zsh and it stopped working after auto-upgrade to v3.0.0 - Hyper is running cmd instead of bash

Version 2.1.2 is working properly

**Comment by kmpm** [comment]
> I had configured Hyper to run zsh and oh-my-zsh and it stopped working after auto-upgrade to v3.0.0 - Hyper is running cmd instead of bash
> 
> Version 2.1.2 is working properly

That is most likely related to the relocation of the config file. See #3589

**Comment by yair5124302** [comment]
> > I had configured Hyper to run zsh and oh-my-zsh and it stopped working after auto-upgrade to v3.0.0 - Hyper is running cmd instead of bash
> > Version 2.1.2 is working properly
> 
> That is most likely related to the relocation of the config file. See #3589

Thank you @kmpm 

Indeed issue was raised due to config file location change mentioned [in issue 3589](https://github.com/zeit/hyper/issues/3589#issuecomment-489541288)

After fixing the settings in its new file location I got Hyper back working including theme and oh-my-zsh

**Comment by pcnate** [comment]
indeed, copying the settings from the old to the new is a temporary work around

**Comment by kmpm** [comment]
Copying old settings didn't work for me though. I still have an issue

**Comment by pcnate** [comment]
possibly related to #3602

**Comment by kmpm** [comment]
* Did a uninstall + remove `AppData\Roaming\hyper + remove `AppData\Local\hyper`.
* Reinstall 3.0.0
* `hyper version` = 3.0.0
* `hyper i verminal`
```
C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19153
      getProperties = memoize(() => getParsedFile().program.body[0].expression.right.properties),
                                                                                    ^

TypeError: Cannot read property 'properties' of undefined
    at memoize (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19153:85)
    at d (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19138:22)
    at memoize (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19154:34)
    at d (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19138:22)
    at Object.install (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:19184:37)
    at Args.args.command (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:9934:45)
    at Args.runCommand (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:11318:37)
    at Args.module.exports [as parse] (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:15089:10)
    at main (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:9991:18)
    at Object.module.exports.name (C:\Users\peter.magnusson\AppData\Local\hyper\app-3.0.0\resources\bin\cli.js:10038:1)
```

**Comment by whitecolor** [comment]
It happened to me after update to node 12 from 10.

**Comment by jjustin3** [comment]
I figured out how to get plugins working once more. I'm on Windows but this process should be the same for Mac/Linux as well.

1. Navigate to %appdata%\Roaming\Hyper\.hyper_plugins
2. `npm install`

Just make sure you have the plugins added via `hyper i` or the config file.

**Comment by whitecolor** [comment]
@jjustin3 

Tried it but it doesn't seem to work for me.

**Comment by mikemcbride** [comment]
I think this may be a duplicate of #3500

**Comment by ArfyFR** [comment]
After created the symlink described there: https://github.com/zeit/hyper/issues/3500#issuecomment-490252223 it worked for me ! =)

**Comment by kmpm** [comment]
Closing this as a duplicate of #3500. The symlink workaround worked for me as well.

**Comment by DevOps127** [comment]
> I figured out how to get plugins working once more. I'm on Windows but this process should be the same for Mac/Linux as well.
> 
> 1. Navigate to %appdata%\Roaming\Hyper\.hyper_plugins
> 2. `npm install`
> 
> Just make sure you have the plugins added via `hyper i` or the config file.

Thx man. it works for me.
