### ISSUE TITLE
Hyper 3.0.0 deleted settings/configuration (.hyperjs)

### ISSUE THREAD

**Issue by jakoandersen** [zeit/hyper#3594]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
I was on 2.x.x when it prompted me to restart hyper as 3.0.0 was ready.
Once i did, it wiped my .hyperjs configuration.
Is there any way to get it back?

**Comment by zaigham** [comment]
Same here 😞 . Unfortunately, it seems to be gone.
It could be restored if you have backup.

**Comment by jakoandersen** [comment]
Fortunately I'm on WSL, so I could go into Preferences and change the shell to my bash shell, and copy the contents of my WSL config and paste it over.

**Comment by execb5** [comment]
Basically the same issue, but it didn't wipe the configuration for me, it's just not using it. My `.hyper.js` is safe in my home directory.

Weirdly enough, if I execute `hyper` in hyper, it opens up a window with my configuration loaded.

**Comment by RobotsPlay** [comment]
> Weirdly enough, if I execute `hyper` in hyper, it opens up a window with my configuration loaded.

I copy pasted the config from this window into the config of the original window, closed, re-opened and was good to go.

**Comment by pcnate** [comment]
> Basically the same issue, but it didn't wipe the configuration for me, it's just not using it. My `.hyper.js` is safe in my home directory.
> 
> Weirdly enough, if I execute `hyper` in hyper, it opens up a window with my configuration loaded.

Is it loading the previous version? I noticed that the CLI tool uses the old config rather than the new one.

**Comment by execb5** [comment]
> 
> 
> > Basically the same issue, but it didn't wipe the configuration for me, it's just not using it. My `.hyper.js` is safe in my home directory.
> > Weirdly enough, if I execute `hyper` in hyper, it opens up a window with my configuration loaded.
> 
> Is it loading the previous version? I noticed that the CLI tool uses the old config rather than the new one.

Yes, the CLI tool is opening up the previous version from what I can tell.

![image](https://user-images.githubusercontent.com/6979113/57230172-1c58ec00-6fee-11e9-8783-8d11abfc1707.png)

**Comment by zamgill** [comment]
> * [x]  I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
> * [x]  I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
> * **OS version and name**: Windows 10
> * **Hyper.app version**: 3.0.0
> * **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:
> * **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
> * **The issue is reproducible in vanilla Hyper.app**:
> 
> ## Issue
> I was on 2.x.x when it prompted me to restart hyper as 3.0.0 was ready.
> Once i did, it wiped my .hyperjs configuration.
> Is there any way to get it back?

Looks like the new version is pointing to the settings file in %APPDATA%\Hyper\.hyper.js instead of the old one %USERPROFILE%\.hyper.js.

Just grab your old file from the old location and paste it into the new location to get all your settings back.
