### ISSUE TITLE
v 3.0.0 destroys settings

### ISSUE THREAD

**Issue by dontsave** [zeit/hyper#3598]
I was prompted to update hyper to v3 and now my config is completely reset, likely costing me a number of hours trying to get my settings back to the way they were.

OS: Windows 10
shell: WSL

**Comment by jpdillingham** [comment]
Same here.  Open preferences before clicking to update, then copy things over.

The update should really create a `.hyper.js.old` or something.

**Comment by bobted** [comment]
This happened to me, too. After a quick panic, it looks like the "old" config file still exists, and that `Hyper` is not loading the configuration from the old location (`c:\users\<username>\.hyper.js`).

I've done a quick look at the repo but can't seem to pinpoint where the default config location is.

**Comment by jpdillingham** [comment]
Looks like it moved to `%appdata%\Hyper`.  I can confirm that the old config file is still there.

**Comment by bobted** [comment]
Overwriting `.hyper.js` in `%appdata%` with the file in `%userprofile%` brings back the old configuration.

**Comment by dontsave** [comment]
that did it. phew was worried I'd lost a lot of config. will leave this issue open for a bit for others who I am sure are running into the same issue

**Comment by schmanat** [comment]
I have the same issue.
I copy the ```.hyper.js``` (from version 2.x) to C:\Users\myuser\AppData\Roaming\Hyper but after restart hyper the ```hyper.js```will be ignored again. ```ls -l```will show these output (C:\Users\myuser\AppData\Roaming\Hyper)

```
.hyper_plugins
blob_storage
Cache
GPUCache
logs
webrtc_event_logs
.hyper.js
config.json
Network Persistent State
Preferences
```

**Comment by kmpm** [comment]
This is same as issue #3589

**Comment by terrancecorley** [comment]
Can someone help me resolve this issue on Windows 10?

**Comment by juancampa** [comment]
@terrancecorley, take a look at https://github.com/zeit/hyper/issues/3589#issuecomment-489541288

**Comment by terrancecorley** [comment]
@juancampa Thank you! https://github.com/zeit/hyper/issues/3589#issuecomment-489555285 This did it for me.
