### ISSUE TITLE
Not working with OSX / zsh / oh-my-zsh / powerlevel9k

### ISSUE THREAD

**Issue by sarveshseri** [zeit/hyper#360]
Hi I am using zsh with oh-my-zsh and powerlevel9k theme. I am getting following errors on starting HyperTerm.

`~/.oh-my-zsh/custom/themes/powerlevel9k/functions/icons.zsh:130: character not in range
~/.oh-my-zsh/custom/themes/powerlevel9k/functions/utilities.zsh:86: command not found: print_icon
left_prompt_segment:24: command not found: print_icon                                                                                                                                              
left_prompt_segment:44: command not found: print_icon
prompt_vcs:33: command not found: print_icon
prompt_vcs:34: command not found: print_icon
prompt_vcs:42: command not found: print_icon
left_prompt_end:2: command not found: print_icon
left_prompt_end:6: command not found: print_icon
right_prompt_segment:32: command not found: print_icon
right_prompt_segment:38: command not found: print_icon
right_prompt_segment:32: command not found: print_icon
right_prompt_segment:32: command not found: print_icon`

Is there any way to resolve this ?

**Comment by rpunkfu** [comment]
Please post the output of running the command `locale`

**Comment by sarveshseri** [comment]
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=

**Comment by jorgemartins** [comment]
Adding `export LANG="en_US.UTF-8"` on your `.zshrc` fixes the errors, but does not show the correct icons.

**Comment by brianjking** [comment]
@jorgemartins Thanks, I tried your fixes mentioned in [comment](https://github.com/zeit/hyperterm/issues/360#issuecomment-234925882) to no avail. The `fontFamily` piece specifically caused iTerm and Hyperterm to throw errors.

ANy ideas?

**Comment by brianjking** [comment]
Here's the export of my `locale`

````
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
````

**Comment by brianjking** [comment]
Disregard, got it working.

**Comment by chabou** [comment]
Closing in favor of #607
