### ISSUE TITLE
Extra spacing before separator 

### ISSUE THREAD

**Issue by krothenbaum** [zeit/hyper#3609]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Mojave 10.14.4
- **Hyper.app version**: 3.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/krothenbaum/c70dfdb833ff0573480c2ce07855a11c
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
Using a custom `oh-my-zsh` theme that has a separator Hyper 3 adds an extra 1px space preceding the separator. Hyper 2 handled the separator without the extra space.

![image](https://user-images.githubusercontent.com/7517741/57255869-048f6100-700a-11e9-957a-3191cab97ae7.png)

**Comment by mhall** [comment]
Duplicate of #3575

**Comment by krothenbaum** [comment]
Thanks I didn't find that in my search.
