### ISSUE TITLE
WSL - clear does't work

### ISSUE THREAD

**Issue by snassour** [zeit/hyper#3623]
Hello, while trying to clear the screen on WSL using ZSH and Bash shell, it doesn't completely clear the screen. It was working fine yesterday.

- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by clee231** [comment]
Duplicate of #3596.
I think many of us are experiencing this issue as well.

**Comment by snassour** [comment]
Sorry my bad, closing the issue, not fixed at the moment
