### ISSUE TITLE
Can not create new tab on windows

### ISSUE THREAD

**Issue by whitecolor** [zeit/hyper#3628]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.0
- **NodeJS version**: 12.1.0

At first new tabs can be opened. Then for no known reason it errors when trying to open a new one.

![image](https://user-images.githubusercontent.com/736697/57332525-5c29eb80-7134-11e9-8d88-759788cebb3b.png)

Nothing related in dev console.

**Comment by whitecolor** [comment]
It seems that hyper become to work much worse after update from node 10 to node 12

**Comment by hugs94** [comment]
This issue occurs for me as-well. But only if a terminal is currently running a process.

**Comment by pcnate** [comment]
I have the same issue on Windows 10 on any shell. I do not have the issue on Ubuntu 19.04 with bash.

**Comment by whitecolor** [comment]
Did downgraded to 2.1.2 with disabled upgrade (via host file), too many bugs in 3.

**Comment by dschoeni** [comment]
Can confirm this issue. Update to 3 hasn't been a very smooth process so  far =/

**Comment by codymaust** [comment]
for me, this issue was caused by the `hypercwd` plugin

removed that and restarted hyper, and now it works

**Comment by paseaf** [comment]
...But how do you use `hypercwd` if you remove it?

**Comment by Stanzilla** [comment]
You'd have to write your own plugin or update `hypercwd`
