### ISSUE TITLE
Paste  : ^V

### ISSUE THREAD

**Issue by diomed** [zeit/hyper#3630]
Why can't I simply paste with `Ctrl`+`V`?

When I do `^V` appears. :|

**Comment by tanvinerkar** [comment]
Hi @diomed
If you are using macOS, then you should use cmd+V instead of ctrl+V.
Let me know if it gets resolved.

**Comment by diomed** [comment]
not mac, windows 10

**Comment by tanvinerkar** [comment]
@diomed Alright. I'll give some time to resolve this.

**Comment by diomed** [comment]
I see that paste is Ctrl + Shift + V
but I used without Shift

Is there any good reason why Shift is included in this? 
Isn't  it a bit too much?

**Comment by tanvinerkar** [comment]
I am using Mac, so it is difficult for me to try out all possible hotkey combinations. Will try it out once I get access to a Windows-running system.

**Comment by pcnate** [comment]
I have seen <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd> more than <kbd>Ctrl</kbd>+<kbd>V</kbd> in the terminal world.

**Comment by voronoipotato** [comment]
Ctrl + Shift + V lets you paste, Ctrl + V gets used by programs. If we allow it to be Ctrl + V people will complain about Emacs being broke. I'm sure you can rebind it in settings.

**Comment by diomed** [comment]
@voronoipotato could you please tell me how to rebind it?

**Comment by pcnate** [comment]
In your settings add these two lines inside your keymaps

```
  keymaps: {
  "editor:copy": "ctrl+c",
  "editor:paste": "ctrl+v",
  },
```

All current keymaps are found here https://github.com/zeit/hyper/tree/master/app/keymaps

**Comment by voronoipotato** [comment]
If you do you will likely break existing programs and ask me how to unbind it. It's in the ` ctrl + , `  under keymaps 
``` json
keymaps: {
"editor:paste": "ctrl+v",
}
```

Swim at your own risk...

**Comment by voronoipotato** [comment]
If you feel this resolved the issue for you please close it, because it's not an issue also there's 761 other issues.
