### ISSUE TITLE
256 terminal color support

### ISSUE THREAD

**Issue by codedmart** [zeit/hyper#364]
Does hyperterm support 256 colors? I am using hyperterm-tomorrow-night, base16-tomorrow-night.vim, and base16-tomorrow-night shell themes but unless I have something configured wrong 256 colors are not working. I have tried other themes as well.

<img width="1440" alt="screen shot 2016-07-22 at 6 34 11 am" src="https://cloud.githubusercontent.com/assets/40686/17057333/8e59cd78-4fd6-11e6-9bbc-2862f0835cf0.png">

**Comment by codedmart** [comment]
I was running the script wrong. It seems to be working ok in hyperterm itself, but vim colors are still not correct. Still investigating.

**Comment by codedmart** [comment]
Also to note that vim looks fine and correct in iTerm2.app and Terminal.app.

**Comment by bpinto** [comment]
I also have color issues on vim. They work correctly on Neovim however.

Colours are incorrect with and without `set termguicolors`.

**Comment by tnguyen14** [comment]
I have neovim but 256 colors are not working for me.. Am I doing something wrong?

**Comment by tnguyen14** [comment]
Is there any update on when this will be scheduled for?

**Comment by mak42** [comment]
Same problem here, in iTerm2 vim(nvim) colours look fine, but in hyperterm there wrong.

**Comment by nicholasc** [comment]
Colors work when running tmux with `set -g default-terminal "screen-256color"` in the `tmux.conf`. 

I created a work-around in my `~/.zshrc` that fixes my vim colors. It creates a new tmux session named with the shell's PID and attaches and kill-session call when that shell is closed to cleanup after itself and not gather tons of tmux sessions.

```
alias tmuxn='tmux new-session -s $$'
_trap_exit() { tmux kill-session -t $$; }
trap _trap_exit EXIT
if ! [ -n "$TMUX" ]; then
    tmuxn
fi
```

It's quite dirty but it works for now. I wonder why running tmux fixes the colors. I also wonder if this issue is not linked to hterm itself.

**Comment by Cldfire** [comment]
Same issue here, neovim colors not working correctly in Hyper while they work just fine in Git Bash.

My setup is a bit on the unsupported side though (using Hyper as a frontend for the Windows 10 Linux subsystem bash).

**Comment by nicholasc** [comment]
Adding `set termguicolors` in vim config works here.

**Comment by rbeesley** [comment]
With Hyper, `tput colors` outputs `256` and `$TERM` is set to `xterm-256color`. However, any number of test scripts which use the `\e[`<38|48>`;5;`<0..255>`m`OUT`\e[0m` ANSI codes, shows that the terminal is only supporting 16 colors. Is $TERM set by the terminal, in this case Hyper? This is really playing havoc with my .dircolors and makes using Hyper practically unusable. I have already configured Bash in Bash on Ubuntu on Windows (WSL) and I want to be able to switch back and forth at will.

**Comment by chabou** [comment]
I can't reproduce
![capture d ecran 2017-04-19 a 00 18 16](https://cloud.githubusercontent.com/assets/4137761/25155545/f1ddc9a0-2495-11e7-871e-a12a8c9f3ac0.png)

Maybe only a WSL issue (see #1733)

**Comment by rbeesley** [comment]
@chabou Yes, that could be. I know the Console supports True Color now, but I suspect Hyper and bash.exe are going to have slightly different environments and terminal settings.

**Comment by TsundereBug** [comment]
Does not work with foreground or background

![test](http://www.tsunderebug.com/fetch.php?id=c18m7GuQM-8uVmd4y0Vj6237h1-phlkPFak7kVf_ZzjSpUTkCA8kQC1yL17scXC_UyghLfMeb6JijyZZiJFhkQ)

Windows, using bash.exe and angel-PS1

**Comment by infctr** [comment]
is there any workaround for that? 

how do you, guys, use zsh-autosuggestions? any setting for `ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=[0-7]'` is either too bright, or just the same color as prompt text.  

my setup: win10+cygwin+zsh

**Comment by Stanzilla** [comment]
https://github.com/xtermjs/xterm.js/issues/484

**Comment by kinglouie** [comment]
On the latest 2.0 canary I have the same issue as in the first post from this thread. On 1.4.8, `colortest` from base16-shell works fine.

#### 1.4.8

<img width="800" alt="bildschirmfoto 2018-02-23 um 16 47 31" src="https://user-images.githubusercontent.com/8280409/36603165-3c6cebfe-18ba-11e8-9c74-1b5b54bd1b6b.png">

#### 2.0 canary

<img width="769" alt="bildschirmfoto 2018-02-23 um 16 49 53" src="https://user-images.githubusercontent.com/8280409/36603166-3c861dc2-18ba-11e8-8e28-821298c185d3.png">

**Comment by chabou** [comment]
We're tracking this work over here: #2294
