### ISSUE TITLE
Unable to install themes

### ISSUE THREAD

**Issue by ThatTonybo** [zeit/hyper#3648]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Windows 10 Pro, 1809
- 3.0.2
- [Gist can be found here](https://gist.github.com/ThatTonybo/18d24d58002063ea48f48319c77c0fba)
- N/A
- Yes, reproducible in vanilla Hyper

## Issue
I'm unable to install themes or plugins using `hyper i ..`, as it errors somewhere within the CLI.

![image](https://user-images.githubusercontent.com/28176227/57494386-538c0d80-730c-11e9-8fa9-3c3bf803dad5.png)

**Comment by tats-u** [comment]
Are there any differences from #3620 except for the versions of Hyper?

**Comment by ThatTonybo** [comment]
> 
> 
> Are there any differences from #3620 except for the versions of Hyper?

Doesn't seem like it, just that mine affects themes and plugins.

**Comment by DaneTheory** [comment]
It was an issue with the "rigidity" in the previous version of `getProperties` method and its subsequent use in returning values from `getPlugins` and `getLocalPlugins`. The PR I have up fixes these things.

**Comment by ThatTonybo** [comment]
Sounds good, so just wait for the PR to be merged and this should be fixed?

**Comment by DaneTheory** [comment]
@ThatTonybo yep. Not sure why it hasn't been merged yet.

**Comment by ArgentSun** [comment]
Getting a different theme installation error on macOS Mojave after applying this manual fix https://github.com/zeit/hyper/issues/2829#issuecomment-468933774 for #2829 : 

```
| => hyper i verminal
Disabling Chromium GPU blacklist
running in prod mode
electron will open file:///Applications/Hyper.app/Contents/Resources/app.asar/index.html
2019-09-17 13:54:43.761 hyper[77123:6142813] *** WARNING: Textured window <AtomNSWindow: 0x7fc5b39a7360> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
Setting Hyper as default client for ssh:// protocol
Linking HyperCLI
{ [Error: EEXIST: file already exists, symlink '/Applications/Hyper.app/Contents/Resources/bin/hyper' -> '/usr/local/bin/hyper']
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: '/Applications/Hyper.app/Contents/Resources/bin/hyper',
  dest: '/usr/local/bin/hyper' }
Hyper CLI installation failed File already exists: /usr/local/bin/hyper
Checking for notification messages
No matching notification messages
2019-09-17 13:54:54.152 hyper[77123:6142813] *** Assertion failure in +[SQRLDirectoryManager currentApplicationManager], /Users/sattard/projects/Squirrel.Mac/Squirrel/SQRLDirectoryManager.m:30
Illegal instruction: 4
```

**Comment by Stanzilla** [comment]
closing as dupe
