### ISSUE TITLE
After upgrading to version 3, starting Hyper (with ZSH) results in a '%' being printed to the console

### ISSUE THREAD

**Issue by itsandreramon** [zeit/hyper#3658]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **macOS 13.6 High Sierra**: 
- **Hyper ver. 3.0.2**: 
- **.hyper.js https://gist.github.com/itsandreramon/ec5e313f0d01a95c6ac21235e011ca8f**: 
- **The issue is reproducible when using oh-my-zsh**: 

## Issue
After upgrading to version 3 of Hyper, a % is printed to the console when using oh-my-zsh. I don't think that this is an issue with oh-my-zsh since it behaves normally when using the standard Terminal app. My friend also has this problem and I saw it live when he was updating to the newest version. It looks like this:

<img src="https://i.imgur.com/yT4HPLK.png"
     alt="Image of Hyper Terminal with the % in the first line"
     style="float: left; margin-right: 10px;" />

<img src="https://i.imgur.com/GDO6wcz.png"
     alt="Image of Hyper Terminal with the % in the first line"
     style="float: left; margin-right: 10px;" />

**Comment by z336** [comment]
I have a similar issue after the upgrade as well, except I just see a cursor block and not %

macOS 10.14.4
Hyper 3.0.2 (stable)
Oh My ZSH

Hyper:
![image](https://user-images.githubusercontent.com/19866924/57574298-74d02500-7404-11e9-925a-928cb3c4a10f.png)

Terminal:
![image](https://user-images.githubusercontent.com/19866924/57574304-8e716c80-7404-11e9-8b53-dd4be3ba9c41.png)

**Comment by Kirow** [comment]
duplicate #3586

**Comment by DaneTheory** [comment]
It seems like this is a `zsh` specific issue. It has to do with partial line preservation and, theoretically, should output to either % or # depending on the user running the prompt (i.e. user = %, root = #). For some reason when the user's shell is `zsh` on Hyper's initial init, something is being run that creates a line in the prompt that does not end in a newline. I've been working on a PR that fixes this for Hyper, but haven't found an elegant solution yet. In the interim, edit your `~/.zshrc` file to include `PROMPT_EOL_MARK=""`. Then, either restart Hyper or run `source` on your `~/.zshrc`. This removes the % sign. However, it does not clear the newline the % held. Running `clear` or `reset` will set the prompt's cursor back at the top.

**Comment by DaneTheory** [comment]
@rauchg @chabou @leo @matheuss since you all seem to be the top contributors for Hyper, perhaps you could best aid in crafting a solution for this problem by providing a bit of development context.
Describe the lifecycle of Hyper. From Initial launch => loading configs => render of prompt => etc. => until final "ready" state where the user can begin interacting with the prompt. If you could provide the location of the code that executes each state, that would be helpful as well. Cheers.

**Comment by itsandreramon** [comment]
Seems to be fixed! Thanks!

**Comment by itsandreramon** [comment]
This should fix it: Adding unsetopt PROMPT_SP to .zshrc
