### ISSUE TITLE
ubuntu splitHorizontal keyboard shortcut collision, dont fix

### ISSUE THREAD

**Issue by pcnate** [zeit/hyper#3660]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu Pop!_OS 19.04
- **Gnome Shell version**: 3.32.1
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: N/A
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: true

## Issue
*I do not expect this issue to be resolved by Hyper. I am putting it here and will post my resolution to aid in others who happen to have the issue to find this in a search engine result. I will close it right await. Please don't respond unless you have additional information to resolve the issue (other than not running Gnome)*

<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>e</kbd> collides with an emoji app in Gnome 3.28+

So far I have tried the following:

* Rebind or remove emoji keyboard shortcut hotkey in `IBuss Preferences`
  1. I could only access running `sudo ibus-setup`
  1. go to `Emoji` tab
  1. delete <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>e</kbd> by clicking on the botton on the right and deleting from the subsequent window

**Comment by pcnate** [comment]
#3666

**Comment by binalloy** [comment]
I have the same problem with `ibus-setup`. But I can't fix the issue by deleting the shortcut. Instead, I found `ibus-setup` could run with no problem in the default Ubuntu terminal.
