### ISSUE TITLE
Can't install any plugin

### ISSUE THREAD

**Issue by yuanzhel** [zeit/hyper#3661]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 16.04 LTS Server
- **Hyper.app version**: 3.0.2(stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

When i add plugin in .hyper.js, i will get a error notification:
```
(node:XXXXX)[DEP00005] DeprecationWarning:Buffer() is deprecated due to security and 
usability issues. Please use the Buffer.alloc(), Buffer,allocUnsafe(), or Buffer.from() methods 
instead. error An unexpected error occurred: "https://registry.yarnpkg.com/hyper-material-theme:
ETIMEDOUT"/

```
The XXXXX means the number always change.

Thanks for your time,  hope someone can help me out.

**Comment by travVT** [comment]
I'm getting the same error message when trying to install any plugin with latest version on Windows. I have the latest version of Hyper.

**Comment by yuanzhel** [comment]
@travVT , I checked the error message in .hyper_plugins,  aka yarn-error.log. At the end of the log, i found the real error is time out, so i set my npm through my company proxy, everything works fine now.

**Comment by travVT** [comment]
Thanks @yuanzhel this fixed my issue too! :)
