### ISSUE TITLE
Hyper hangs when closing windows or tabs on Windows

### ISSUE THREAD

**Issue by w1ndy** [zeit/hyper#3665]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- Windows 10 18362.30
- Hyper 3.0.2
- https://gist.github.com/w1ndy/4092529105ebbe80862df3eab4bc7662
- N/A
- **The issue is reproducible in vanilla Hyper.app**: yes
## Issue

I edited 'shell' and 'shellArgs' in the Hyper configuration such that Hyper can connect to a SSH server with vanilla OpenSSH provided by Windows. However, Hyper becomes unresponsive completely when I try to close the tab or window after I have logged into SSH sessions. It seems OK if I close the window immediately without entering the SSH password, but Hyper still hangs for about 5 seconds before it closes.

I've inspected the waiting chain with Task Manager, which indicates that Hyper is blocked on conhost.exe. I'd happy to provide any additional information if needed to resolve this issue. Thank you!

**Comment by volkancakil** [comment]
there are same issue with WSL, powershell, node or python too, if you close hyper without exitting shell

**Comment by PritamSangani** [comment]
I've experienced this, but only when I try to close Hyper when on a WSL session. When I close from my default shell (Powershell) it closes fine. I have noticed that there are often quite a few Hyper processes running and showing in the Task Manager . (I am on Windows 10 Build 18362)

**Comment by w1ndy** [comment]
Upgrading node-pty to 0.9.0 beta seems to resolve this issue. Maybe we shall just wait for Hyper to upgrade its upstream dependencies.

**Comment by pedroCX486** [comment]
@w1ndy You shouldn't have closed the issue, it's still a thing that is happening. I'm having hangs after having Hyper open CMDer inside it.
