### ISSUE TITLE
Settings Change are not being reflected

### ISSUE THREAD

**Issue by Chokerino** [zeit/hyper#3681]
- [ x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hi, I was trying out Hyper and when I try to change the settings in the .hyper.js file they do not get reflected on the terminal. First, I thought this might only be for themes but things such as font-size and shell also are not changing.

**Comment by SwarajG** [comment]
MacOS: 10.14.4
Chrome: 74
It's working fine on the above machine. I am able to change fontSize and other settings from .Hyper.js

Can you please specify the device specification or other useful information to debug?

**Comment by Chokerino** [comment]
@SwarajG I think that was a mistake on my part so I'm sorry for that but I am not able to see font colours, is this because I'm using cmd as my shell?
