### ISSUE TITLE
Unable to downgrade to Hyper 2

### ISSUE THREAD

**Issue by sambrainerd** [zeit/hyper#3682]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  Windows 10
- **Hyper.app version**: 3.0.2 and 2.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  https://gist.github.com/sambrainerd/2ec6b27e030bc30ace6608f13701570f

## Issue ##
I've had trouble clearing screen using Hyper 3.02 with Bash for Windows. I saw that others had this problem as well and decided to downgrade to 2.1.2 instead. However when I install 2.1.2, somehow it installs 3.0.2. Please look into this.

Thanks,
Sam.

**Comment by pcnate** [comment]
you should be able download the source for the release you want to use and compile it but I don't know if there is any guide to doing it. There should be to aid in getting newer devs up and running

**Comment by ppot** [comment]
DL it using : https://github.com/zeit/hyper/releases 

Look for 2.1.2 setup

**Comment by nitinmohan87** [comment]
After I installed 2.1.2, Hyper automatically upgrades to 3.0.2. I tried to purge every configuration files possible. But Hyper keeps updating to the newest version. I am trying to downgrade to 2.1.2 because of this bug https://github.com/zeit/hyper/issues/3638

**Comment by jakelawcheukwun** [comment]
Please give users an option to stop auto-updating or stick to a particular version... My 3.0.2 installation is failing on #3651 and the only way to use hyper is to reinstall 2.1.2 every time
