### ISSUE TITLE
theme not loading

### ISSUE THREAD

**Issue by designMoreWeb** [zeit/hyper#3686]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Mac Mojave**
- **3.0.2**
- **https://gist.github.com/designMoreWeb/cdc5ef8057a9a5952806a6696aca9124**

## Issue

The theme is not loading and i am not sure why

**Comment by codevski** [comment]
Same issue here. Verminal is installed after latest update 3.0.2 it seems like its not compatible or something...

**Comment by pablopunk** [comment]
`hyper-pokemon` works for me on `hyper 3.2.0`

**Comment by pablopunk** [comment]
I see your issue @designMoreWeb , you have `plugins` under `config` object. It should be outside of it:

```js
module.exports = {
  config: {
    ....
  }
  plugins: ['hyper-pokemon'],
  localPlugins: []
}
```

I suggest you start with a fresh `.hyper.js` just in case you modified something else, [copy it from here](https://github.com/zeit/hyper/blob/canary/app/config/config-default.js). Also, you can install plugins and themes like `hyper install hyper-pokemon`, so you don't have to modify the file manually

**Comment by designMoreWeb** [comment]
that fixed it thank you so much

**Comment by pablopunk** [comment]
@designMoreWeb no problem, please close this issue if you don't have any more questions 👍

**Comment by Virtual-Dreamer** [comment]
> I see your issue @designMoreWeb , you have `plugins` under `config` object. It should be outside of it:
> 
> ```js
> module.exports = {
>   config: {
>     ....
>   }
>   plugins: ['hyper-pokemon'],
>   localPlugins: []
> }
> ```
> 
> I suggest you start with a fresh `.hyper.js` just in case you modified something else, [copy it from here](https://github.com/zeit/hyper/blob/canary/app/config/config-default.js). Also, you can install plugins and themes like `hyper install hyper-pokemon`, so you don't have to modify the file manually

by default it's on this format but it still doesn't work

**Comment by WickedWizard3588** [comment]
I'm still having this same issue on Windows 10 64Bit.....

But this happens with both plugins and themes

**Comment by steelx** [comment]
same issue on windows. verminal doesnt load. I tried hyper-pokemon it working.

**Comment by Nzent** [comment]
Same issue with 3.1.4 version 😟

**Comment by LabhanshAgrawal** [comment]
@Nzent can you post your config

**Comment by hazyhazeleyes** [comment]
issue on Big Sur with version of Hyper 3.3.0, just not installing theme :(
