### ISSUE TITLE
3.x Non-interactable

### ISSUE THREAD

**Issue by TobiTenno** [zeit/hyper#3689]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Pro
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [gist](https://gist.github.com/TobiTenno/c4e5fc4ee0073dcb9730598ab1506891)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: ✔️ 

## Issue
Default cmd terminal starts behind hyper, hyper has no text and nothing can be typed inside.  
![image](https://user-images.githubusercontent.com/7128721/58293123-de97e980-7d89-11e9-991e-2b901f22218e.png)

Hotkeys function, such as for opening settings. I've encountered this on all versions 3.0+. If I install 2.1.2, this versions work fine, but the next restart reintroduces the issue as it autoupdates.

**Comment by ShotSkydiver** [comment]
Same issue here :( On macOS El Capitan 10.11.6, Hyper is entirely non-interactable, even after manually trying to disable the webGL renderer.

**Comment by r1chjames** [comment]
Same in Fedora 30. Potentially related is really severe screen corruption within the app.

**Comment by KsRyY** [comment]
Maybe try to build it manually? My manually built version on Manjaro is all ok

**Comment by TobiTenno** [comment]
I did a manual build, still didn't work

**Comment by r1chjames** [comment]
Not sure if there was an issue with an OS component that caused mine to break in Fedora but it started working again after a system update.

**Comment by nhuhoai** [comment]
Same problem with on Win10, Instead of N/A message in console like @TobiTenno, I've got this error:
Uncaught TypeError: Cannot destructure property `uid` of 'undefined' or 'null'.
    at EventEmitter.u.a.on (bundle.js:1)
    at EventEmitter.emit (events.js:182)
    at t.a.ipcListener (bundle.js:1)
    at EventEmitter.emit (events.js:182)

**Comment by TobiTenno** [comment]
ah, the message isn't `N/A`, there is no message

**Comment by nhuhoai** [comment]
> 
> 
> ah, the message isn't `N/A`, there is no message

For sure, I was not misunderstanding but I badly wrote my comment 😉

**Comment by AdamKogut** [comment]
I am having this problem too, but clicking on the shortcut does not work either

**Comment by xenobytezero** [comment]
Having the same issue here. I was getting similar issues with VSCode, until I found a GitHub issue which recommended dissabling ConPTY support, which fixed it. Might be a clue?

Win10 Pro - 1903 - 18362.239

**Comment by Stanzilla** [comment]
should no longer happen with CI builds of canary and the next release
