### ISSUE TITLE
True colors support

### ISSUE THREAD

**Issue by pablopunk** [zeit/hyper#3695]
https://github.com/xtermjs/xterm.js/releases/tag/3.13.0

<img width="1108" alt="57422610-aa3aff80-71c5-11e9-89bc-14e50111b498" src="https://user-images.githubusercontent.com/4324982/58488230-4de65280-8169-11e9-83d9-de51872079d7.png">

**Comment by Tyriar** [comment]
There were big changes in this release that would break the webgl renderer. I've updated for the most part the webgl renderer but the custom patches on top of it (and for the emoji input) would likely need to be redone, also true color doesn't work on it yet.

**Comment by pablopunk** [comment]
@Tyriar you're right, I tried to merge 3.13.0 tag and I get those conflicts. Is there a reason to have a fork with the patches instead of making a PR to xterm directly? Just curious

**Comment by Tyriar** [comment]
@pablopunk there are 2 PRs out on xterm that aren't finished yet https://github.com/xtermjs/xterm.js/pull/1890, https://github.com/Tyriar/xterm.js/pull/5. Also the webgl renderer isn't merged in yet so it may fall behind (I work on xterm not hyper).

**Comment by pablopunk** [comment]
@Tyriar Ok, thanks for the info 🙂. I'll keep this issue open til we get true colors then, I'll update the title

**Comment by pablopunk** [comment]
In case anybody wants to have true colors in the meantime, I built hyper for **Mac** with the new xterm. You can [download it here](https://files-48bvznq0d.now.sh), but keep in mind you'll need to disable WebGL inside your `.hyper.js` and also you won't get emoji support.

**Comment by pablopunk** [comment]
@Tyriar I'm guessing hyper could migrate once [these](https://github.com/xtermjs/xterm.js/milestone/22) are completed?

**Comment by Tyriar** [comment]
@pablopunk I think the plan for Hyper is to wait for v4 yes, true color won't work in the webgl renderer until https://github.com/xtermjs/xterm.js/issues/2249 is done though.

**Comment by SkyaTura** [comment]
@Stanzilla I understand closing #2294 due to duplicity, however, this issue isn't solved yet.

As you suggested on the referenced issue, I tested on latest Canary build and still doesn't work.

Should I open another issue as you mentioned there or this can be used? Or True Colors won't be officially supported?

**Comment by Stanzilla** [comment]
@SkyaTura it should work in the latest CI build from master, can you test it there please?

**Comment by SkyaTura** [comment]
Sorry for my ignorance @Stanzilla, but I didn't found the build you've mentioned anywhere.
However, I've cloned the most recent commit and built myself and worked fine.

You can close it now, again, sorry for reopening it.

**Comment by Stanzilla** [comment]
Yay!
