### ISSUE TITLE
'/bin/bash' not found on Windows 10

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [zeit/hyper#3709]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: I haven't touched it
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
While in the Hyper terminal immediately after installing on Windows, both before and after a restart, any attempt to use the global `hyper` command after previously running `npm i -g hyper` results in:

```
'/bin/bash' is not recognized as an internal or external command, operable program or batch file.
```

<img width="373" alt="Bin Bash Not Found" src="https://user-images.githubusercontent.com/3335181/58725923-5b404e80-83ae-11e9-8ed1-c1347d6b36b5.PNG">

**Comment by abhijithvijayan** [comment]
@JoshuaKGoldberg Try integrating WSL with Hyper.

**Comment by JoshuaKGoldberg** [comment]
@abhijithvijayan I haven't touched WSL in months and don't want to. That's a lot of overhead to be able to run an Electronic app. Is a *nix environment a requirement for Hyper?

Also, what does "integrating" mean here? Could you be a little more informative please?

**Comment by abhijithvijayan** [comment]
Setup Hyper.js to automatically open Ubuntu on Windows

Open up Hyper.js configuration by  typing `Ctrl + ,`
Scroll down to shell and change it to `C:\\Windows\\System32\\bash.exe`

```
// the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    //
    // Windows
    // - Make sure to use a full path if the binary name doesn't work
    // - Remove `--login` in shellArgs
    //
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
    //
    // PowerShell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: 'C:\\Windows\\System32\\bash.exe',
```

This will only work if you installed linux via WSL, I use hyper use my linux shell like this.

**Comment by JoshuaKGoldberg** [comment]
Cool, thanks. This issue was meant as a bug report, so I'll rename it to be asking about how to use WSL and file a new issue for the case of not using WSL.
