### ISSUE TITLE
Window controls gone (Mac)

### ISSUE THREAD

**Issue by bkwilcox100** [zeit/hyper#3715]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Mojave 10.14
- **Hyper.app version**: Hyper v3.0.2 (Stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/bkwilcox100/8fd1c2f023ce36f27df4ff241186ee2a
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

The close, minimize, and maximize buttons are gone. I removed all the plugins and restarted and it didn't change anything. It also displays "(base)" before each prompt.

**Comment by bkwilcox100** [comment]
![Screen Shot 2019-06-03 at 2 19 17 PM](https://user-images.githubusercontent.com/12356605/58828238-9a6adb80-860a-11e9-91d5-d85da6219629.png)

Picture for reference

**Comment by akollegger** [comment]
I had a similar situation. Removing `.hyper.js`  `.hyper_plugins/` and restarting got back to normal for me.

**Comment by bkwilcox100** [comment]
That seemed to work. Thanks!

**Comment by mxfng** [comment]
This issue came up today for me. Removing `.hyper.js` .`.hyper_plugins/` and restarting worked for me as well. Lost some of my customizations, but oh well.

**Comment by nightzirch** [comment]
Adding to this, commenting out all the contents in `.hyper.js` and refreshing or restarting Hyper will indeed bring back the window control buttons. Uncommenting all the contents will then bring back your customizations while still keeping the window control buttons. At least it did for me.

**Comment by zyfyy** [comment]
> 

[hyper-tabs-enhanced](https://github.com/henrikdahl/hyper-tabs-enhanced) might be what I'm looking for 😆
