### ISSUE TITLE
Erreur when creating new tab with Ctr + Shift + T

### ISSUE THREAD

**Issue by sbenzakountradelab** [zeit/hyper#3718]
version: 3.0.2
plugins installed: hyper-cwd, hyper-broadcast
bash utilisé: git bash
os: windows 10 pro

This error occured when i tried to open a new tab:
![image](https://user-images.githubusercontent.com/43436835/58869881-5ede1900-86bf-11e9-98b0-3e0209ba7e1d.png)

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** win32 x64 10.0.17134
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 14,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BEAM",
  "cursorBlink": true,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "C:\\Program Files\\Git\\git-cmd.exe",
  "shellArgs": [
    "--command=usr/bin/bash.exe",
    "-l",
    "-i"
  ],
  "env": {
    "TERM": "cygwin"
  },
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}

          {
  "plugins": [
    "hyper-broadcast",
    "hypercwd"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by sbenzakountradelab** [comment]
I just remarked the bug occured just after i used git

**Comment by austriker27** [comment]
Im also getting this error just after doing a git pull

**Comment by sanfusu** [comment]
I also have this  problem.

**Comment by austriker27** [comment]
To fix my issue I removed the hypercwd plugin

**Comment by sbenzakountradelab** [comment]
Thanks it solve my pb
