### ISSUE TITLE
Tabs are not displayed in the menu

### ISSUE THREAD

**Issue by VincentLanglet** [zeit/hyper#3721]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mojave 10.14.4 
- **Hyper.app version**: Just installed
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:
```
module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 15,
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: 'rgba(248,28,229,0.6)',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: true,
    foregroundColor: '#C7C7C7',
    backgroundColor: '#000',
    selectionColor: '#C7C7C7',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '12px 14px',
    colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#686868',
      lightRed: '#FD6F6B',
      lightGreen: '#67F86F',
      lightYellow: '#FFFA72',
      lightBlue: '#6A76FB',
      lightMagenta: '#FD7CFC',
      lightCyan: '#68FDFE',
      lightWhite: '#FFFFFF',
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    quickEdit: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    hyperline: {
      plugins: [
        "ip",
        "memory",
        "cpu",
        "network",
      ]
    },
  },
  plugins: [
    "hypercwd",
    "hyperline",
    "hyper-quit"
  ],
  localPlugins: [],
  keymaps: {},
};
```

## Issue

Everywhere I see terminal with multiple tabs in the menu (example [here](https://hyper.is/plugins/hypercwd)).

But I only have one tab in my menu, even if I tried to install some tabs plugins.
![image](https://user-images.githubusercontent.com/9052536/58941681-8ba43600-877c-11e9-9f0f-3479f79b7286.png)

Is it a bug or am I doing something wrong ?

**Comment by eidyz** [comment]
Looks like you are just splitting the view not opening new tab to me.

**Comment by VincentLanglet** [comment]
@eidyz You're right. I was using `Cmd + D`, opening a new tab seems to be `Cmd + T`.

Thanks.
