### ISSUE TITLE
Clear Failing Hyper 3.0.2 on Windows 10

### ISSUE THREAD

**Issue by darianhickman** [zeit/hyper#3724]
Hyper 3.0.2
Windows 10 
Clear command failing 
![Screenshot (63)](https://user-images.githubusercontent.com/1481299/59132879-2f334900-892b-11e9-92b4-f1957a987441.png)

**Comment by darianhickman** [comment]
View -> Reload fails to solve the problem.
View -> Full Reload fails to solve the problem too. 
View -> Reset Zoom fails to solve the problem too. 

I killed the hyper.js terminal and restarted.  That cleared the screen.

**Comment by Stetchy** [comment]
Also documented in #3238. What happens if you use Window's `cls` command? Is `clear` a command from git-bash/windows linux subsystem?

**Comment by darianhickman** [comment]
cls works first try. :)

**Comment by Stetchy** [comment]
If you had an alias for `clear` it might be best to set that alias to `cls` for now until the WSL commands work nicely with hyper, I can't see that being too soon unfortunately.

**Comment by arunib** [comment]
I am facing the same issue with Hyper 3.0.2 stable. The clear command as well as the 'ctrl + L' shortcut fails to clear the screen buffer. It works sometimes though.
