### ISSUE TITLE
Pipe character falls below cursor block

### ISSUE THREAD

**Issue by jamo** [zeit/hyper#373]
It seems like the `|` pike character is slightly too low. Without a background color it's not immediately noticeable but with backgroundcolor it seems like it's overflowing out of the row.

`echo -e "\n\033[0;41m test qjyg| \n"`
![echo sample](https://cloud.githubusercontent.com/assets/1354151/17077578/50001fac-50dd-11e6-92ae-d23bb1bbc545.jpg)

And same but comparing to cursor.
![comparing to cursor block](https://cloud.githubusercontent.com/assets/1354151/17077592/b6f628e6-50dd-11e6-8a9a-4737a61a5623.jpg)

I've tried this on both most uptodate release and from running it in devmode. All the settings are default (no `~/.hyperterm.js`).

The amount of overflow varies on different zoom levels, it's either touching to bottom line of the row or even overflowing.

**Comment by jamox** [comment]
I just noticed a small difference in the behaviour between iterm2 and hyperterm, regarding how the   contents of a row is aligned; look at the misaligned right arrow in the airline row

iTerm2
![iterm](https://cloud.githubusercontent.com/assets/1354151/17783015/c8ab4eb2-657e-11e6-874f-3e527a5f27d6.jpg)

Hyperterm:
![hyperterm](https://cloud.githubusercontent.com/assets/1354151/17783038/e9c738f4-657e-11e6-93b9-ef58586f275f.jpg)

It should be using the same font, even thou it looks different...

Not sure if this helps anyone debugging this...

**Comment by bradparks** [comment]
I just upgraded hyper this morning to 1.3.0.1614, and I see this same behaviour, but much worst than shown.

I zoom in my hyper to 22px, 76x63, and see multiple zooming problems now, which weren't there before:
- block cursor shows below the current line the more zoomed in you are
- the topmost line of my terminal is now slightly cut off

![image](https://cloud.githubusercontent.com/assets/185477/23806291/8301fbb8-0597-11e7-8b36-6bb70376c34b.png)

**Comment by henrikdahl** [comment]
@bradparks Issue you're mentioning is fixed in 1.3.1 coming soon ✌️

**Comment by bradparks** [comment]
@henrikdahl - thanks! I just downloaded the update, and it works great again... Much appreciated!

**Comment by chabou** [comment]
![capture d ecran 2017-04-19 a 00 37 07](https://cloud.githubusercontent.com/assets/4137761/25156001/5bf1bd36-2498-11e7-9d7e-8353e40f409f.png)
Fixed
