### ISSUE TITLE
Hide Hyper icon in MacOS top bar

### ISSUE THREAD

**Issue by wdanilo** [zeit/hyper#3734]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Catalina
- **Hyper.app version**: 3.0.2
- **The issue is reproducible in vanilla Hyper.app**: yes

## Issue
When opening the Hyper app, its icon is displayed in the MacOS top-bar (the bar which is always on the top of the screen containing a menu of the running app and icons of utils apps). As far as I can see, there is currently no way to hide this icon, which is rather a bad idea, cause I don't need a "terminal icon" appearing every time I'm starting using the terminal. Am I missing some config option for that?

**Comment by pablopunk** [comment]
Where are you seeing the hyper icon exactly? I'm confused

Can you post a screenshot?

**Comment by wdanilo** [comment]
@pablopunk Of course, you can find the screenshot below (the leftmost icon):
<img width="701" alt="Screenshot 2019-06-20 at 13 24 08" src="https://user-images.githubusercontent.com/1623053/59845942-e2099b00-935e-11e9-88d1-1ced53295ade.png">

**Comment by pablopunk** [comment]
That's weird... I have the same Hyper version and also running Catalina and I can't see that. Did you upgrade to the second Beta of Catalina? I didn't yet

**Comment by evanheckert** [comment]
@pablopunk Interesting, on both beta1 and now beta2 I download Hyper 3.0.2 and it just says "The application Hyper cannot be opened." Any suggestions?

**Comment by pablopunk** [comment]
@evanheckert I'm getting the exact same error. I think it's related to an electron issue in Catalina, but I don't know why homebrew's version does work 🤔 

Try `brew cask install hyper` and see if that one works

**Comment by evanheckert** [comment]
@pablopunk That worked great! Thank you kind sir!

**Comment by pablopunk** [comment]
You're very welcome 🧐

**Comment by wdanilo** [comment]
@pablopunk nope, I did not upgrade yet! But I'd really love to get rid of that icon ;)

**Comment by wdanilo** [comment]
@pablopunk After your reply, I realized that this problem might be connected to my installation of Hyper, so I started to change the config and I've found out the case! The plugin 'hyperterm-overlay' adds such an icon to the top bar ... I'm really sorry for taking your time and thank you for the assistance.
