### ISSUE TITLE
purpose, add new feature: always on top window or floating window

### ISSUE THREAD

**Issue by pookdeveloper** [zeit/hyper#3738]
I wish to use hyper always on top window or floating window.

Thanks :)

**Comment by pookdeveloper** [comment]
I created this pull request for the feature.
https://github.com/zeit/hyper/pull/3740

Thanks

**Comment by rofazayn** [comment]
This [one ](https://github.com/chabou/hyper-always-on-top) might help you.

**Comment by KaKi87** [comment]
Hello, why not offering this option natively ? Thanks
