### ISSUE TITLE
Reset terminal will lead to a crash

### ISSUE THREAD

**Issue by bet4it** [zeit/hyper#3749]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

Way to produce:
1. Open `hyper`
2. Run `reset` command or just `echo -e '\033c'`
3. Try to split window

This bug was introduced in #3409, it seems that after reset, `xterm.js` will reset some properties of `termRef`

**Comment by LabhanshAgrawal** [comment]
Is this issue still there? Tried the steps on macOS(w/ latest canary), faced no issues.

**Comment by bet4it** [comment]
Oh, you are right.
This bug has been fixed sometimes😀
