### ISSUE TITLE
Windows installation fail, 

### ISSUE THREAD

**Issue by duall** [zeit/hyper#3752]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Try to install

## Issue
![](https://i.imgur.com/VCnYb1x.png)
It started failing after update, not working for couple months now, clean reinstall does not help. Hyper directory was deleted before install so dont have hyper.js or any other files.
I know it's not very specific but don't know what files/info to share.

Version 2.1.2 installs and works fine, but autoupdates and crashes.

**Comment by Stanzilla** [comment]
should no longer happen with CI builds of canary and the next release
