### ISSUE TITLE
Drag and Drop for file path not working

### ISSUE THREAD

**Issue by vedantsingh1404** [zeit/hyper#3756]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  MacOS 10.14
- **Hyper.app version**:  3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**:  https://gist.github.com/vedantsingh1404/d1fe1c14eeee391551f33283d8659119
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

The path is not given by the terminal when I drag and drop files.

**Comment by BunnyMan1** [comment]
I'm having the same problem after update to latest version.

**Comment by ledlamp** [comment]
Same on Windows 7 (Hyper 3.0.2, no custom configuration)

**Comment by ledlamp** [comment]
Oh and dupe of #3582

**Comment by qweasd1** [comment]
guys, I create a plugin for this: https://github.com/qweasd1/hyper-drop-file, just  ```hyper install hyper-drop-file```
