### ISSUE TITLE
Terminal goes not responding when I close on windows with zsh.

### ISSUE THREAD

**Issue by RitikPatni** [zeit/hyper#3763]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **WIndows 10 1903**: 
- **Hyper 3.0.2**: 
- **https://gist.github.com/RitikPatni/02bda7bd2236bfb324f0e365a9fbb1f8**: 
- **Can't collect any info as it goes not responding** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **This issue appears when I use zsh as default shell with ohmyzsh**: 

## Issue
I configured my hyper terminal with zsh on windows but after that whenever I try to close it it goes not responding. I've tried to check the console window too but nothing appears there as the app goes not responding.
![Screenshot (2)](https://user-images.githubusercontent.com/16117262/61478784-ece03b80-a9af-11e9-9240-d1cce889e91e.png)

**Comment by EndlessHollow** [comment]
Hello,
I am not sure what is your setup of zsh on windows, but I am using
```
shell: 'wsl.exe',
shellArgs: [],
```
so when you are actually closing it it will kill your wsl aswell.

The second option is to use: `exit`

**Comment by RitikPatni** [comment]
Thanks for the tip. Works well for me

**Comment by tayyabferozi** [comment]
> Hello,
> I am not sure what is your setup of zsh on windows, but I am using
> 
> Hyper.js
> 
> ```
> shell: 'wsl.exe',
> shellArgs: [],
> ```
> 
> so when you are actually closing it it will kill your wsl aswell.
> 
> The second option is to use: `exit`

where am I supposed to write these two lines??

**Comment by RitikPatni** [comment]
@tayyabferozi In your .hyper.js file. You can open it in Preferences. It will be like this [Hyper Config](https://gist.github.com/RitikPatni/02bda7bd2236bfb324f0e365a9fbb1f8)
