### ISSUE TITLE
Typing a URL does not display website

### ISSUE THREAD

**Issue by elricdesigns** [zeit/hyper#3767]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

**OS version and name**
```
macOS Mojave
Version 10.14.5
MacBook Pro (Retina, 13-inch, Late 2013)
```
 **Hyper.app version**
```
Hyper 3.0.2 (stable)
Renderers: WebGL (6)
Plugins: 
  hyper-active-tab (0.0.2),
  hyper-pane (2.1.4)
```
**Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
https://gist.github.com/elricdesigns/a965f9ee18d52cf7f3f3baf8541ae4cf
**Relevant information from devtools**
N/A - no console errors
**The issue is reproducible in vanilla Hyper.app**
yes - also reproduced in Ubuntu 18.04

## Issue

Typing a URL into hyper terminal and pressing enter does not display a site in the terminal window:

e.g.
```
$ http://google.com
bash: http://google.com: No such file or directory
$ https://hyper.is
bash: https://hyper.is: No such file or directory
```

As per the following, this is an intended feature:
https://github.com/zeit/hyper/issues/1498

**Comment by Stanzilla** [comment]
I don't think that's intended anymore
