### ISSUE TITLE
`alt` shortcut not working in windows

### ISSUE THREAD

**Issue by chhanz** [zeit/hyper#3771]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 1903
- **Hyper.app version**:  Hyper 3.0.2 (stable)

## Issue

Hello, i changed keymaps. but not working...

* Change log 
```
  "editor:copy": "ctrl+shift+c",   >>>    "editor:copy": "alt+c", 
  "editor:paste": "ctrl+shift+v",  >>>   "editor:paste": "alt+v",
```
`alt`+c , `alt`+v not working .....
plz, check `alt` shortcut.

* Question
I want to use *Windows key* with shortcut.
But I don't think I can set it up.
Can't you use it?

**Comment by rzambre** [comment]
Hey @chhanz , were you able to fix this? If so, how?

**Comment by chhanz** [comment]
Hello @rzambre .
I didn't fix it. I use shortcut ctl+alt+c or v.
