### ISSUE TITLE
Launch Hyper "Error reading configuration module.exports"

### ISSUE THREAD

**Issue by antoine-morisseau** [zeit/hyper#3802]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 build 18362.239
- **Hyper.app version**: 3.0.2

## Issue

Hyper first didn't work properly with the installer due to the hyper command not found (issue with the ENV) so i uninstalled it and reinstalled it with chocolatey.
But when trying to find the .hyper.js config file i didn't find it and thought of chocolatey specific way of handling application i prefered to uninstall Hyper on chocolatey.
I manually deleted in the AppData/Local the `hyper` folder since i like to have a clean AppData folder when i uninstall things.

Then i tried to reinstall Hyper with the installer and got this error.
i found the #3447 closed but i don't have any `.hyper.js` file on my user folder

![image](https://user-images.githubusercontent.com/3832837/63581755-0caee480-c598-11e9-971e-199ed3b8e8c0.png)

![image](https://user-images.githubusercontent.com/3832837/63582179-df166b00-c598-11e9-9c79-9239b3696b4b.png)

Thanks

**Comment by antoine-morisseau** [comment]
ok found it.
it was a `.hyper.js`empty file in the `AppData\Roaming\Hyper` folder that caused the issue.
I removed the `Hyper` folder and tried another installation and it did well.

**Comment by toby1991** [comment]
> ok found it.
> it was a `.hyper.js`empty file in the `AppData\Roaming\Hyper` folder that caused the issue.
> I removed the `Hyper` folder and tried another installation and it did well.

Facing same problem in `MacOS`

Found a file at  `~/.hyper.js`, and remove it.

**Comment by annamariadaniel** [comment]
@toby1991 How did you manage to do this? When I type ~/.hyper.js in the regular Terminal it says Permission denied. Is there a different way? I am very new to this and kind of lost. I'd appreciate any help. Thanks.

**Comment by toby1991** [comment]
> @toby1991 How did you manage to do this? When I type ~/.hyper.js in the regular Terminal it says Permission denied. Is there a different way? I am very new to this and kind of lost. I'd appreciate any help. Thanks.

So probably the current user you logon has no permission for that directory. ‘.hyper.js’ is the configuration file for hyper, and will locate in the folder in ‘/Users/YOUR NAME/.hyper.js’. 
 
Try sudo?

**Comment by annamariadaniel** [comment]
I can't locate it.
Not sure how to do that.
Thanks for the help anyway! Really appreciate it.

**Comment by BigPesh** [comment]
For those struggling to find the .hyper.js file on macOS, Click on finder, then from the top menu click Go, select Go To Folder, type in `~/.hyper.js` this is a hidden file.

**Comment by GiorgiaCorsetti** [comment]
![image](https://github.com/vercel/hyper/assets/156906190/c46e700d-8730-4599-a2d1-862d4c758ecc)
Hi group, I am facing same issue but seems like I cannot locate the broken file on my windows and whenever I try to reinstall the Hyper file from https://hyper.is/ I still get the JavaScript error. I am kind of stuck.
Can somebody please help?

**Comment by GiorgiaCorsetti** [comment]
![image](https://github.com/vercel/hyper/assets/156906190/e3500796-63fc-4cf1-bd0e-53ea40ac2025)

**Comment by GiorgiaCorsetti** [comment]
![image](https://github.com/vercel/hyper/assets/156906190/e07b5e66-0e02-462f-bb90-ad178b71e58d)

**Comment by the-homeless-god** [comment]
> ok found it. it was a `.hyper.js`empty file in the `AppData\Roaming\Hyper` folder that caused the issue. I removed the `Hyper` folder and tried another installation and it did well.

I think it makes sense to add the info about this path into readme or try-catch handler related to config's parser
