### ISSUE TITLE
Cannot open app on MacOS Catalina

### ISSUE THREAD

**Issue by IgorGanapolsky** [zeit/hyper#3803]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Catalina
- **Hyper.app version**: latest downloaded from website
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 

## Issue
Upon downloading the latest Hyper app from the website, I cannot launch it.  OS complains with 
> The application "Hyper.app" can't be opened

**Comment by henrikmmm1** [comment]
I've got the same issue. What OS version are you running, specifically?

**Comment by henrikmmm1** [comment]
I found a [previous issue](https://github.com/zeit/hyper/issues/3750) that had the same problems as we've encountered. Try installing Hyper via Homebrew;
```
brew update
brew cask install hyper
```
This works on my end.

**Comment by IgorGanapolsky** [comment]
@henrikmmm1 That works.
