### ISSUE TITLE
Hyper crashes on exit if a powershell instance is running from within the default cmd window

### ISSUE THREAD

**Issue by aditya-giri** [zeit/hyper#3804]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10, Version 1903
- **Hyper.app version**: 3.0.2.1510
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/aditya-giri/0128c0e428a2a3b1f20098551795d10d
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A (Not sure where to get info from)
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue
Hyper crashes in the following scenario:
- Open Hyper (defaults to cmd)
- In the cmd prompt, type `powershell` to launch a powershell instance from within command prompt.
- Try to exit Hyper (by closing the window using the X)
- Hyper stops responding and has to be killed.

I looked into the open issues to the best of my ability but found nothing similar. I did however find a couple of issues around setting powershell as the default in hyper.js, but this is not the same scenario. Apologies if this is a known bug.

**Comment by ChunxuYang** [comment]
Having Similar Issue.
Some extra presentations:
- Sometimes after reboot you can fix it, but only for one time.
- type exit in command line may work.
- WSL crashes too.

**Comment by lonesome-rider** [comment]
> 
> 
> Having Similar Issue.
> Some extra presentations:
> 
>     * Sometimes after reboot you can fix it, but only for one time.
> 
>     * type exit in command line may work.
> 
>     * WSL crashes too.

It happens the same to me.

I normally open a few tabs on Hyper and I use WSL in some of them. If I try to close one of these tabs without logging out from WSL first, Hyper crashes and I have to kill the process. It always happens, everytime.

**Comment by clockelliptic** [comment]
Same here, Windows 10 Enterprise. Crashes on every exit, no matter what.

**Comment by aditya-giri** [comment]
Wanna try and fix this myself - can someone point me to a good starting point for investigation? I would do it but I'm a little short on time 😬

**Comment by LabhanshAgrawal** [comment]
Not facing any issue with latest canary, you can try it out from https://github.com/zeit/hyper/suites/594966292/artifacts/4319163

If you still face the issue, can you do the following
open hyper
open one more tab (ctrl+shift+t)
open dev console (ctrl+shift+i)
open powershell/wsl
close that tab

and report if you see any error on dev console

**Comment by LabhanshAgrawal** [comment]
@aditya-giri 
It was fixed in #3781 
Were you able to try out the ci build?

**Comment by aditya-giri** [comment]
@LabhanshAgrawal sorry I havnn't able to try the canary yet. The link seems to be broken. Where can I find the artifacts from CI builds?

**Comment by LabhanshAgrawal** [comment]
get it from the latest run in https://github.com/zeit/hyper/actions?query=event%3Apush+branch%3Acanary

**Comment by aditya-giri** [comment]
Sorry for the delay.
Yeah, it looks good with the latest canary build 👍 
I'm closing the issue.

**Comment by 50l3r** [comment]
I still have the problem in the stable version
