### ISSUE TITLE
Emojis are not displaying

### ISSUE THREAD

**Issue by devhammed** [zeit/hyper#3808]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 19.04
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/devhammed/6505a4cf0e785ebb3c53a666d8a9b073
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Emojis characters are not rendering at all...they renders correctly in Gnome Terminal but not in Hyper, I am using ZSH and Spaceship Prompt.

Gnome Terminal:
![Gnome Terminal](https://i.ibb.co/DQBD8Jf/Screenshot-from-2019-08-30-09-13-58.png)

Hyper:
![Hyper](https://i.ibb.co/P16MrQp/Screenshot-from-2019-08-30-09-13-10.png)

I am using the same font on both `Fira Code` which obviously means it is not a font issue.

I have no clue why this is not working, no errors in DevTools.

:cry:

**Comment by Stanzilla** [comment]
Can you try with a CI build of current canary or maybe compile one yourself? Or setting `webGLRenderer: false,` in the config.

**Comment by devhammed** [comment]
![Screenshot from 2019-10-14 12-45-38](https://user-images.githubusercontent.com/22827908/66749006-93898a80-ee80-11e9-95f8-8e86e154ae6c.png)

I have done that even before opening this issue, check above .hyper.js file.

**Comment by devhammed** [comment]
I have fixed the issue, it is also affecting any Chromium-based apps including Google Chrome. For others facing this issue, follow these steps:

- Add a new font config: `vim ~/.config/fontconfig/conf.d/01-emoji.conf` and paste below snippet:

```xml
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
```
- Restart the application and enjoy!

Tested on Ubuntu, I don't know about other distros but it should work.
