### ISSUE TITLE
Terminal window is create instead to be in the main Hyper window 

### ISSUE THREAD

**Issue by tsukasa696** [zeit/hyper#3811]
![hyper_error](https://user-images.githubusercontent.com/27456027/64080309-cb82a700-ccf2-11e9-977c-6c1d73329127.jpg)

  - [x ] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

N/A

  - **Is the issue reproducible in vanilla Hyper.app?**

First and Fresh Install

## Issue

When i try to open the Hyper  it just open a new terminal windows, the main app windows is just like the image attach if i close that terminal the app close, if i close the app the terminal window just stay there until i close it, so right now my app is a shortcut to the terminal 😞 

 - **OS version and name**: Windows 10 Pro, version 1903, build 18362.295
- **Hyper.app version**: 3.0.2 (stable)
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by tsukasa696** [comment]
answer provide by @Tyriar 
#73790, you need to disable legacy console mode in cmd.exe/conhost's properties.

**Comment by Tyriar** [comment]
👉 https://github.com/Microsoft/vscode/issues/73790#issuecomment-528651073
