### ISSUE TITLE
Graphical Glitch on Windows 10

### ISSUE THREAD

**Issue by SamirJouni** [zeit/hyper#3815]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10 1809 build: 17763.678**: 
- **Hyper 3.0.2 (Stable)**: 
- **[Gist](https://gist.github.com/SamirJouni/d77f85f93bc1751c14a11e3d563f5be7)**: 
- **N/A** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Random graphical glitches that usually happen when resizing the window, or when maximizing window. Some text persists (only graphically) in random locations, when clicked with the left-mouse button, the glitch disappears. 
The glitch also appears when using nano on a remote server. The bottom controls of nano persist (only graphically) even after exiting nano. 

Not sure if the same behavior can be observed on Linux or MacOS. I haven't tested it on either.

###### Glitch
![Image](https://drive.google.com/uc?id=1vB9UqqtiSmTzCB47X61HX8LYZD1PuB8A)

###### After Clicking on the glitch
![Image](https://drive.google.com/uc?id=1eDr9y0qsZkh1TbQvl8nEDEhjErO0fuRy)

**Comment by Wolf2789** [comment]
Happens to me aswell.

Also I've randomly experienced glitch where sometimes last one/two lines of output cannot be seen until I resize window or type in another command or press ^C

**Comment by deuks** [comment]
These are the same as issues #3791 and #3792

**Comment by SamirJouni** [comment]
@deuks Yup, seems so.

**Comment by Matthew-Lewin** [comment]
I am having the same issue. I would be curious to know if anyone isn't having this issue, to see if we can compare configs to see what the issue might be.

**Comment by Stanzilla** [comment]
closing as duplicate
