### ISSUE TITLE
Display an error page when webview URLs can't be loaded

### ISSUE THREAD

**Issue by ekmartin** [zeit/hyper#382]
Right now it just shows a black screen - which can be quite confusing (see #374). Should probably listen to [did-fail-load](http://electron.atom.io/docs/api/web-view-tag/#event-did-fail-load) and display a proper error page (with info that it can be closed with ctrl+c maybe).

**Comment by ShMcK** [comment]
Additionally, consider validating the url with a stronger regex. Currently urls as simple as `> a.ab` are loaded as webviews.

**Comment by albinekb** [comment]
Possibly change the behaviour to only open URLs in webview?https://en.wikipedia.org/wiki/Uniform_Resource_Locator
` scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]`

**Comment by chabou** [comment]
Webview has been removed from Hyper for security concerns
