### ISSUE TITLE
Hyper 3.0.2 crashes to desktop when writing 'git commit -'

### ISSUE THREAD

**Issue by LokiEyes** [zeit/hyper#3827]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 WSL with ZSH
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/LokiEyes/51f6aac2c5f5caf950707c5be50d176d
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: `N/A`
- **The issue is reproducible in vanilla Hyper.app**: Everytime I write `git commit -` or use an alias `gc -`

## Issue

When writing `git commit -` or my alias `gc -` right after pressing a hyphen, Hyper crashes. I tried other commands, but only this causes the problem. Other `git` commands, such as `git add`, work fine. This happens in directories with or without git.

**Comment by Stanzilla** [comment]
Can you try with a CI build of current canary or maybe compile one yourself?
