### ISSUE TITLE
How to see all plugins?

### ISSUE THREAD

**Issue by jeffabailey** [zeit/hyper#3834]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

I skipped this section since it's just a question. If I should ask questions elsewhere please let me know and I'll be happy to do so.

How can I see all of the available plugins for hyper? On the website I only see a way to search and a way to see the recent but not all plugins.

**Comment by t1m0thyj** [comment]
The official list of plugins on the website is indeed quite limited. There is a curated list of awesome plugins for Hyper here: https://github.com/bnb/awesome-hyper. You can also find plugins by searching for the tags "hyper", "hyper.app", or "hyper-plugin" on npmjs.com.

**Comment by jeffabailey** [comment]
Thanks!
