### ISSUE TITLE
Porting app folder to TypeScript

### ISSUE THREAD

**Issue by LabhanshAgrawal** [zeit/hyper#3836]
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

## Issue

Now that #3816 is merged. Files in lib folder (renderer) can be ported to TypeScript.
I want some suggestions and help on porting the app folder. I have explored two approaches

1. Transpile files and copy assets from app to a new folder compiled_app and use that to run and build hyper - #3837 
2. Transpile TS files in the app folder itself  - #3838 

(tsc on file change in approach 2 not working at the moment, despite similar configuration to approach 1)
(need to configure eslint to ignore the generated files in both branches)

Please suggest any other approach that might be useful and any improvements on the above two.

**Comment by ppot** [comment]
If option 2 doesn't introduce breaking change. I would go with migrating file as they are. no need for duplication.

**Comment by Stanzilla** [comment]
Could reuse the dist folder for 1)?

**Comment by ppot** [comment]
I commented on your 1 PR. instead of `compiled_app/` rename it `target/`

**Comment by LabhanshAgrawal** [comment]
> Could reuse the dist folder for 1)?

There would already be some things in there on building, so decided against using it.

**Comment by Stanzilla** [comment]
Which approach do similar apps like Terminus or FluentTerminal use?

**Comment by LabhanshAgrawal** [comment]
Terminus is using awesome-ts-loader with webpack to convert the ts files to js in a dist folder.
Fluent Terminal is using ts-loader with webpack to bundle ts files to bundle.js in a dist folder.

**Comment by Stanzilla** [comment]
In your personal opinion, are those superior solutions?

**Comment by LabhanshAgrawal** [comment]
I tried out building and running Terminus, it also seems to be bundling the files.
Personally I think those are equivalent to approach 1 which I consider better than approach 2.
We can also choose to bundle the files if we want.

**Comment by Stanzilla** [comment]
Sounds good to me!

**Comment by LabhanshAgrawal** [comment]
Should we bundle?

**Comment by Stanzilla** [comment]
I think so, I don't see any downsides to it? Might be a bit slower maybe?

**Comment by LabhanshAgrawal** [comment]
I tried to setup bundling but getting errors with json modules.
```ERROR in ./app/package.json
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"n...'
File was processed with these loaders:
 * ./node_modules/json-loader/index.js
You may need an additional loader to handle the result of these loaders.```
Tried to fix but no luck there.
