### ISSUE TITLE
Administrative rights

### ISSUE THREAD

**Issue by wxr1997** [zeit/hyper#3839]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hi, there! My computer is Windows 10 OS. I want to use hyper instead of cmd.exe directly. Recently, I find when I open hyper, I cannot run some special commands since it tells me I am not running from an elevated command shell which partly because I cannot open hyper with administrative rights.

Please help me and tell me the way or how to set the preferences or something, in order to open hyper with admin rights by easily click on the icon.

**Comment by ppot** [comment]
Just right on the app and run as administrator

**Comment by wxr1997** [comment]
Thank you very much. Is there any way change to admin after left click the app? Cause I just want to make it more ‘programmer’.

**Comment by wxr1997** [comment]
Actually, Since Windows 10 updated just know. It give the option to make click on the icon, open it with admin rights. One can find the priority option in the setting menu when right clicking on it.

**Comment by ppot** [comment]
Like I said; Just right on the app and run as administrator.
