### ISSUE TITLE
Takes too much time to open

### ISSUE THREAD

**Issue by mciparelli** [zeit/hyper#385]
I'm in a Lenovo Y50, using Debian + Gnome Shell. `gnome-terminal` takes ~.5s to load while `hyperterm` takes `2s.

**Comment by freebroccolo** [comment]
How long does it take for chrome to load? Hyperterm uses electron which is based on chrome so chrome is going to be a determining factor in how fast the UI can possibly load.

**Comment by mciparelli** [comment]
https://drive.google.com/file/d/0Bz517xiOtwEFY0x6RS1Wd0pwSWs/view?usp=sharing

Recording kind of delays everything a little bit, but you'll see how there's a 1/2 second difference approx between Chrome and Hyperterm

**Comment by albinekb** [comment]
https://github.com/zeit/hyperterm/pull/153#issuecomment-234307376

**Comment by mciparelli** [comment]
I see. Ok then. It'd be nice to have it open a bit faster but maybe that's a hard thing to do, I understand. It's just that I tend a lot to open the terminal and `cd` to my 'projects' directory and hyperterm usually just catches the 'd' in `cd`, so I just have to wait a little longer :D

**Comment by albinekb** [comment]
That could probably be solved, by starting keyboard capture as soon as the process is started, not when electron is loaded. Then pass the captured keys straight to the actual terminal or trough electron?

**Comment by rauchg** [comment]
I think we should do as much as we can to make it as fast as possible. I like the idea of comparing it to Chrome init!

**Comment by hachre** [comment]
The idea about capturing keyboard early is great. I'd love this on my Mac as well! I have the same problem as the OP. Often opening and instantly starting to type but it swallows the first or first two characters. Seeing it isn't as critical as being able to type into it right away.

**Comment by rumpelsepp** [comment]
> I think we should do as much as we can to make it as fast as possible. 

That's especially important in tiling window managers. You often end up just doing <kbd>super</kbd> + <kbd>return</kbd> to bring up a new terminal, because you forgot that you have already a billions of them open. The startup time of hyper should be improved, as that is a bit of laggy experience right now.

**Comment by chabou** [comment]
Startup time has been improved. (Especially in [v1.1.0](https://github.com/zeit/hyper/releases/tag/1.1.0) release)
Feel free to reopen.

**Comment by hachre** [comment]
Still takes 1.8 seconds to open (version 1.3.1) on my MacBook 12". Apple's Terminal.app takes roughly 0.7 seconds.

**Comment by chabou** [comment]
@hachre and Chrome ?

**Comment by hachre** [comment]
@chabou: Chrome takes only 1.4 seconds. (Even though I have 16 extensions installed)

**Comment by chabou** [comment]
We must improve on it but we have non-compressible Electron bootup time 😞

**Comment by chabou** [comment]
Maybe some good ideas: http://blog.atom.io/2017/04/18/improving-startup-time.html

**Comment by chabou** [comment]
Another way to achieve this: #525

**Comment by NeekSandhu** [comment]
How about when user "closes" Hyper by clicking `x` or `Alt + F4`, Hyper can just hide the `BrowserWindow` instance but keep the process running? Some people might say it'll be a RAM lockup, but I doubt that Hyper is in any way resource intensive.

**Comment by navidR** [comment]
Although it is based on the electron, I think the comparison with Chrome is nonsense. We have to improve the startup time. I understand tweaking electrons internal is not possible. But we can re-architect some part. For example, we can start a hyper service and basically run every terminal as a client to the main service. In that scenario, the startup time of every client should drop to 0.1ms.

**Comment by chabou** [comment]
Bench with http://isitsnappy.com/
From click on dock to shell prompt printed:
v1.4.8: 1.6s
v2.0.0: 1.3s

I think this is ok now :)

**Comment by nebosite** [comment]
I just started my hyper terminal (2.0) and it took 20s on the first try, then 8s on the next 3 tries.  This is unusably slow for me.   My machine is a relatively new z440-  Powershell and Cmd on the same machine come up instantaneously.  

I ran Hyper -v and got this output:

```
C:\Users\erjorge>hyper -v
running in prod mode

electron will open file://C:\Users\erjorge\AppData\Local\hyper\app-2.0.0\resources\app.asar\index.html

[26476:0614/081223.616:WARNING:keyboard_util.cc(165)] Invalid accelerator token: del
[26476:0614/081223.616:WARNING:accelerator_util.cc(62)] ctrl+del doesn't contain a valid key

[26476:0614/081223.620:WARNING:keyboard_util.cc(165)] Invalid accelerator token: del
[26476:0614/081223.620:WARNING:accelerator_util.cc(62)] ctrl+del doesn't contain a valid key

[26476:0614/081225.696:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5

[26476:0614/081225.696:ERROR:cache_util.cc(134)] Unable to move cache folder C:\Users\erjorge\AppData\Roaming\Hyper\GPUCache to C:\Users\erjorge\AppData\Roaming\Hyper\old_GPUCache_000
[26476:0614/081225.696:ERROR:disk_cache.cc(132)] Unable to create cache
[26476:0614/081225.696:ERROR:shader_disk_cache.cc(604)] Shader Cache Creation failed: -2

Checking for notification messages

No matching notification messages
```

**Comment by jamesyale** [comment]
I'm experiencing slow startup from Hyper too but on Windows (Hyper even with the slowness is by far the best terminal emulator here). It seems like the slow startup problem exists across platforms. 

The suggestion to run the main process in the background, letting the RAM take the hit, sounds like a great idea to me, though I've got no idea how practical it is to implement. I'd definitely pay for the feature though.

**Comment by NeekSandhu** [comment]
+1 for always on background process if that makes sense

**Comment by albinekb** [comment]
Both on windows and mac my hyper launches in sub 2 seconds, I think that's acceptable. The question is why you're getting so slow start times 🤔 can you attach your config?

**Comment by jamesyale** [comment]
Config: https://gist.github.com/jamesyale/474cb69731927fddf515043073663a36

**Comment by albinekb** [comment]
Yes it can be improved @ssabpisa. PR's to improve startup perf is welcome 🙌
