### ISSUE TITLE
Hyper not loading .hyper.js config

### ISSUE THREAD

**Issue by samuk190** [zeit/hyper#3855]
I installed hyper v to run with bash, but I change the shell and it doesnt happen anything.
I also tried to change font family to Fira Code and it doesnt work too.
Windows version	10.0.18362 compilation 18362

I'm editing the file on -> AppData\Roaming\Hyper -> .hyper.js

**Comment by samuk190** [comment]
copied config from another guy and it worked

**Comment by Maransatto** [comment]
I did the same but it's still not working here for me. Using MacOS Big Sur.
