### ISSUE TITLE
redux and react devtools no longer working since electron6 update

### ISSUE THREAD

**Issue by LabhanshAgrawal** [zeit/hyper#3859]
Both are working till ab0c8fe13f559ea4808167da056b47c63916ced4
<img width="989" alt="Screenshot 2019-10-12 at 12 17 22" src="https://user-images.githubusercontent.com/16598275/66696518-57242600-ecea-11e9-8641-c94fd3f24d65.png">
<img width="994" alt="Screenshot 2019-10-12 at 12 16 09" src="https://user-images.githubusercontent.com/16598275/66696523-5d1a0700-ecea-11e9-8f79-d38edb6425fc.png">
I have already granted access to file urls.

**Comment by Stanzilla** [comment]
Ugh. @GitSquared any idea?

**Comment by GitSquared** [comment]
@Stanzilla I'm afraid not. It's working fine on my end (on cd655ad).

![Screenshot_20191012_173505](https://user-images.githubusercontent.com/24496417/66703798-e428a880-ed05-11e9-8cd6-b3db52c4b052.png)

I doubt that this could be related to ab0c8fe. Did you reproduce this? Perhaps it's another platform-specific issue (unlikely).

**Comment by LabhanshAgrawal** [comment]
I meant, it's working in ab0c8fe and breaks with the elctron v6 commit

**Comment by Stanzilla** [comment]
It works here as well 
![image](https://user-images.githubusercontent.com/75278/66704518-e4806e00-ed1c-11e9-9fc0-3dde30cf05d2.png)

**Comment by LabhanshAgrawal** [comment]
Checked again, not working for me
Can anyone try on mac?

**Comment by Stanzilla** [comment]
Can you run a `yarn clean && yarn` and try again?

**Comment by LabhanshAgrawal** [comment]
did that, no luck
getting this error on opening React tab
<img width="496" alt="Screenshot 2019-10-12 at 22 04 03" src="https://user-images.githubusercontent.com/16598275/66704720-6633c400-ed3c-11e9-8514-fe9e64397fd3.png">

**Comment by ivanwonder** [comment]
you can check your [react dev tools version](https://electronjs.org/docs/api/browser-window#browserwindowgetdevtoolsextensions).  and try to upgrade your plugin.
https://github.com/zeit/hyper/blob/6deb733d636d925074d6713f9f49d04d9fb9b226/app/index.js#L266
if still cannot resolve, try to locate the problem from upstream.

**Comment by LabhanshAgrawal** [comment]
I'm getting this when I check for devtools extensions
```
{
  'React Developer Tools': { name: 'React Developer Tools', version: '3.3.0' },
  'Redux DevTools': { name: 'Redux DevTools', version: '2.15.3' }
}
```
Redux DevTools started working somehow, React Developer Tools is not working for me yet.

**Comment by ivanwonder** [comment]
the latest React Developer Tools is [4.2.0.](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi)

**Comment by ivanwonder** [comment]
https://electronjs.org/docs/tutorial/devtools-extension?q=addDevToolsExtension

**Comment by LabhanshAgrawal** [comment]
Thanks, I updated the extensions by setting `export UPGRADE_EXTENSIONS=true `
and then `yarn run app`
It's working now.

**Comment by Stanzilla** [comment]
Great we could figure that out!

**Comment by LabhanshAgrawal** [comment]
Others may also experience similar problem, should I add it to readme?

**Comment by Stanzilla** [comment]
Let's wait until someone creates an issue for it

**Comment by ivanwonder** [comment]
I think the better solution is to fix the plugin version.

**Comment by Stanzilla** [comment]
@ivanwonder we rely on electron-devtools-installer and there no newer version of it though

**Comment by ivanwonder** [comment]
now we can get the plugin version installed, and If less than the specified version, notify the developer

**Comment by ivanwonder** [comment]
we should print the version of dev tools extensions on the console to help locate the problem.

**Comment by ivanwonder** [comment]
and provide some tips if the version is too low

**Comment by ivanwonder** [comment]
seemingly the chrome will upgrade your extensions by default.
