### ISSUE TITLE
Yep. First time using it "The application “Hyper” can’t be opened. without error or explanation Had the same error when I tried months before, is this repo dead? Thought that would be fixed :/

### ISSUE THREAD

**Issue by bl1mp** [zeit/hyper#3870]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by Stanzilla** [comment]
Please fill out the issue template

**Comment by edergo** [comment]
@Stanzilla it should be general problem in macOS Catalina. Same is here.
macOS Catalina 10.15 (19A583)

**Comment by Stanzilla** [comment]
There is an open issue for that already https://github.com/zeit/hyper/issues/3750
