### ISSUE TITLE
weird double printing of letters on new mac install

### ISSUE THREAD

**Issue by jcklpe** [zeit/hyper#3878]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Mojave 10.14.6
- **Hyper.app version**: 
3.0.2 Stable
Renderers: WebGL
Plugins: 
  gitrocket (1.0.6),
  space-pull (1.0.13),
  hyper-pane (2.1.5),
  hyper-tabs-enhanced (0.4.2),
  hyperterm-bold-tab (1.0.1),
  hyperterm-dibdabs (0.0.8),
  hypercwd (1.4.0),
  hyper-overlay (1.2.1),
  hyperterm-alternatescroll (1.3.0),
  hyperborder (1.1.1),
  hyper-bloody (0.0.1)
- **Link of a [Gist](https://github.com/jcklpe/configs/blob/master/hyper-js/mac.hyper.js) 
- **Dev Tools:** 
![image](https://user-images.githubusercontent.com/9451726/66962392-7bf40280-f036-11e9-8498-506af368f1d3.png)

## Issue

After using any kind of editor like nano, or file exploer like ranger/mc everything gets all double lined like this: 

![test](https://user-images.githubusercontent.com/9451726/66962141-ea849080-f035-11e9-8a9f-d87d27b2a87f.png)

I've had this mac for like 2 weeks and it's been a problem since I first installed Hyper. I did not report it until today because I couldn't tell what the pattern was but now it's become clear. It's very easy for me to reproduce.

**Comment by Stanzilla** [comment]
Does it work without any plugins enabled?

**Comment by jcklpe** [comment]
@Stanzilla I just double checked and I found from the dev thing that the problem was ` "hyperterm-alternatescroll",`

disabling that got rid of the issue. I'm going to close this but reference in that plugins repo

**Comment by Stanzilla** [comment]
Thanks!
