### ISSUE TITLE
TouchID support

### ISSUE THREAD

**Issue by adam-golab** [zeit/hyper#3885]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **MacOS Mojave**: 
- **3.0.2**: 
- **The issue is reproducible in vanilla Hyper.app**:

## Issue
I'd be awesome to have TouchID support for authenticating on command line tools like `sudo`.
I found this article describing how to enable it for `sudo` command it built-in `terminal`. This method works as well in ITerm2 after enabling `Turn off Prefs > Advanced > Allow sessions to survive logging out and back in` option.

But I see that there is no way to enable it in the Hyper terminal. I'm curious if there is something that I'm missing in the documentation or it's just not implemented yet. I found that's available in the Electron (https://github.com/electron/electron/pull/16707) so it should be able to implement in Hyper as well.

**Comment by Stanzilla** [comment]
Sure, do you want to make a PR for it?

**Comment by nthakor** [comment]
https://www.imore.com/how-use-sudo-your-mac-touch-id 

Try this method. It works on hyper for me.

**Comment by adam-golab** [comment]
Hmm, I was following exactly the same article. Let me check it once again

**Comment by adam-golab** [comment]
You're right @nthakor. I'm using tmux and there is the problem. Tested it once again, this time without running tmux. And it works like a charm. So I think this issue can be closed. Will provide more information for anyone that encounter the same issue with tmux in the future

**Comment by adam-golab** [comment]
For anyone having the same difficulties. I installed `pam_reattach` and it started working in tmux.
Here is the link to mentioned library https://github.com/fabianishere/pam_reattach
