### ISSUE TITLE
[macOS] ls: Operation not permitted

### ISSUE THREAD

**Issue by jsejcksn** [zeit/hyper#3900]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.15 Catalina
- **Hyper.app version**: 3.0.2
- **The issue is reproducible in vanilla Hyper.app**: `Is Vanilla`

## Issue

```
~ % cd ~/.Trash 

.Trash % ls
ls: .: Operation not permitted
```

Certain locations in macOS cannot be accessed (like `~./Trash`, `~/Library/Messages`, etc.).

## Solution

This is due to [data protections](https://www.apple.com/macos/catalina/features/#security) in macOS:

> **Data protections**
> macOS Catalina checks with you before allowing an app to access your data in your Documents, Desktop, and Downloads folders; iCloud Drive; the folders of third-party cloud storage providers; removable media; and external volumes. In addition, you’re asked before an app can perform key logging or capture a still or video recording of your screen.

It can be remedied by enabling Hyper in the list of Apps that have Full Disk Access:

<img width="668" alt="macos-security_and_privacy-privacy-full_disk_access" src="https://user-images.githubusercontent.com/868251/67417837-4ba8e880-f58f-11e9-80db-dbcb7372464e.png">

**Comment by jsejcksn** [comment]
I suggest adding the labels [<kbd>🍎 Platform: Mac</kbd>](https://github.com/zeit/hyper/issues?utf8=%E2%9C%93&q=label%3A%22%F0%9F%8D%8E+Platform%3A+Mac%22) and [<kbd>📜 Type: Guide</kbd>](https://github.com/zeit/hyper/issues?utf8=%E2%9C%93&q=label%3A%22%F0%9F%93%9C+Type%3A+Guide%22)

**Comment by kmru** [comment]
Thanks!
