### ISSUE TITLE
Support opening as an overlay

### ISSUE THREAD

**Issue by mattapperson** [zeit/hyper#397]
It would be great to support opening as an overlay / visor like iTerm2 supports.

![visorcolors](https://cloud.githubusercontent.com/assets/192433/17110483/30a09648-526b-11e6-95b5-b4d61f5b51ce.png)

Being able to access this using a system wide hotkey.
iTerm2 lets you specify the height in rows or to say it should fill the screen.

iTerm2 supports window fade or slide in/out too making it look really nice 😊

**Comment by albinekb** [comment]
https://github.com/CWSpear/hyperterm-visor

**Comment by mattapperson** [comment]
@albinekb more or less... but hyper term needs more APIs to do it right 😊

**Comment by albinekb** [comment]
If so, what APIs are missing?

**Comment by Rickgbw** [comment]
Maybe an API to allow creating hyperterm windows as [`frameless window`](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md), seems a good start...

**Comment by mattapperson** [comment]
@Rickgbw that can already be done.

**Comment by albinekb** [comment]
I would suggest you open a ticket over at https://github.com/CWSpear/hyperterm-visor, discussing what's missing and then opening tickets here with the required APIs to make them happen ⭐

**Comment by Rickgbw** [comment]
@mattapperson looking at [`index.js`](https://github.com/zeit/hyperterm/blob/master/app/index.js) and [`plugins.js`](https://github.com/zeit/hyperterm/blob/master/app/plugins.js), there is not a default option for `frame` on `decorateBrowserOptions`. So using plugins like hyperterm-visor, is not possible make `frame: false` on window creation and it cannot be changed after :/

**Comment by mattapperson** [comment]
@Rickgbw this is how https://github.com/danprince/hypertile/blob/master/index.js#L23

**Comment by Rickgbw** [comment]
@mattapperson you was right! 
I was trying exactly this, but I only make it works when I set an empty value for `titleBarStyle`:

```js
exports.decorateBrowserOptions = (config) => {
	return Object.assign({}, config, {
		titleBarStyle: '',
		frame: false
	});
};
```

...so I created [`hyperterm-overlay`](https://github.com/rickgbw/hyperterm-overlay) plugin. Any suggestions are welcome :)
