### ISSUE TITLE
Document that plugins can require Electron

### ISSUE THREAD

**Issue by mattapperson** [zeit/hyper#398]
This is needed in order to allow show/hide to have proper return of focus 
https://github.com/electron/electron/issues/2640

Alternatively expose an API to do this

**Comment by rauchg** [comment]
We do this? `decorateMenu` ?

**Comment by mattapperson** [comment]
@rauchg negative, at least as far as I can tell... we need to be able to `Menu.sendActionToFirstResponder('hide:');`

**Comment by rauchg** [comment]
OH. I think it'd be cool to pass `{ electron }` as the second parameter for all the browser hooks. What do you think ?

**Comment by rauchg** [comment]
Kinda like we pass `{ React }` to all the renderer ones

**Comment by rauchg** [comment]
`{ electron, app }`

**Comment by mattapperson** [comment]
Seems to me that this should work for this and many other use-cases 😊

**Comment by albinekb** [comment]
Dude, i just came to realise something when i checked out the code in [hyperterm-overlay](https://github.com/Rickgbw/hyperterm-overlay/blob/master/package.json)

The package.json specifies electron@0.4.1, which isn't right, but the thing that's really cool (but a bit unexpected) is [that electron always return internal module when requiring electron](https://github.com/electron/electron/pull/5662)! 💥

**Comment by chabou** [comment]
Yes, we need to document this, because as a plugin author I tried to not requiring `electron` because it is a big dependency. If I knew that...
