### ISSUE TITLE
Confirm closing

### ISSUE THREAD

**Issue by rastasheep** [zeit/hyper#399]
It would be great to have some variation or both (in app or via plugins) of this iTerm features:
- Confirm closing multiple sessions
- Confirm "Quit iTerm2 (⌘+Q) command"

Both of those prevent accidental closing of app (and loosing work if you're not using some multiplexer).

**Comment by d3viant0ne** [comment]
That iTerm feature is the reason why I no longer use it. While it prevents accidental closing of a session, it also blocks things like restarts.

No installed program on the planet should block a system restart command, ever.

**Comment by emmby** [comment]
Hyperterm and iTerm should not block restarts, yes.  However, it would be nice to have an optional warning before a non-restart quit/close-window.  I write this having just now accidentally closed my window twice during long builds.

(This is a particular problem for people with multiple monitors, where it's easy to think one monitor has focus but in fact your other monitors does)

**Comment by denysdovhan** [comment]
Just now I accidentally closed hyper window and that's it. Can't wait when this feature will be added.

**Comment by d3viant0ne** [comment]
@emmby - I agree completely. An `optional` setting would be valuable and as long as it doesn't block things like system restart, on by default would be perfectly fine.

**Comment by andrewchilds** [comment]
I would widen scope a little of this request for a confirmation step to include accidental `cmd+R`, which I just did :man_facepalming:

**Comment by chabou** [comment]
Is protection about hotkeys (quit app, quit pane or refresh app) enough?
Or should we warn if a user is closing app window with red button/cross?

**Comment by chabou** [comment]
@zachflower made a plugin: https://github.com/zachflower/hyper-confirm

**Comment by chabou** [comment]
More work about this will be tracked over #67
