### ISSUE TITLE
Package and themes index

### ISSUE THREAD

**Issue by rastasheep** [zeit/hyper#400]
It would be awesome to have searchable index of packages and themes, which would be based on package tags pulled from https://www.npmjs.com. Searching for "hyperterm-theme" (https://www.npmjs.com/search?q=hyperterm-theme) kind works, but for utils/packages it's a little bit harder. 

This need more investigation what and how Atom's website work.

What do you think?

**Comment by lordgiotto** [comment]
This is what you're looking for https://github.com/matheuss/hpm ;)

**Comment by timneutkens** [comment]
ping @italoacasas you were working on something like this

**Comment by italoacasas** [comment]
Yes,

https://github.com/italoacasas/hyperterm-plugins-service -> API Cloud
https://github.com/italoacasas/hyperterm-plugins-web -> Web (I'm going to open the repo later this week).

The plan for the API Cloud is to be on `api.hyperterm.org` but that is a @rauchg call. If is not possible I'm going to buy a domain.

I think @matheuss is going to use the API on `hpm`

**Comment by rauchg** [comment]
I would love to make it `api.hyperterm.org`! Just tell me how to deploy it

**Comment by matheuss** [comment]
As soon as we have `api.hyperterm.org`, I'm gonna use it @ `hpm` ^~^

**Comment by rastasheep** [comment]
@lordgiotto that's great tool, but it lacks comfort of random eye shopping, and some web ui :)

**Comment by albinekb** [comment]
In addition, it would be nice if we could have it so that you could install plugins directly via the website and hpm (when it's bundled). Like (bitbar)[https://github.com/matryer/bitbar] does it.
`hyperterm://install-plugin?url=<url>`

**Comment by MatthiasWinkelmann** [comment]
I've created a theme browser at [https://hyperthemes.matthi.coffee].(https://hyperthemes.matthi.coffee)

**Comment by chabou** [comment]
You can find plugins here: https://github.com/bnb/awesome-hyper
And `hpm` has a search feature
