### ISSUE TITLE
Javascript error popped up while playing with tabs

### ISSUE THREAD

**Issue by c4milo** [zeit/hyper#401]
![screen shot 2016-07-25 at 4 05 04 pm](https://cloud.githubusercontent.com/assets/41681/17115541/caa54534-5281-11e6-973d-8728386d29cf.png)

**Comment by CodeTheory** [comment]
Do you have any more information that could help identify the issue?

Here's some suggestions for things you could provide to help:
- What were you doing for this error to occur specifically?
- What can others to to replicate the issue?
- Did you look into it at all or have any experience on where the error could be coming from?

**Comment by c4milo** [comment]
>What were you doing for this error to occur specifically?

I just opened a bunch of tabs, then close them all using `Cmd + w`, the last once got closed but the hyperterm window remained. The error happens when I try to write anything from that point. Although, it does not happen consistently which leads me to believe it could be some sort of race condition.

>What can others to to replicate the issue?

I just described it in the answer to the first question

>Did you look into it at all or have any experience on where the error could be coming from?

no

**Comment by rauchg** [comment]
Pretty sure this is fixed in `0.7.0`

**Comment by rauchg** [comment]
Actually no, that's a different bug :P

**Comment by tleunen** [comment]
Just had a similar "JS error" when running my tests for an app (not 100% repro tho :/)

Version 0.7.1 (0.7.1.36)
```
Uncaught Exception:
Error: watch /Users/tleunen/.node-spawn-wrap-32116-47b5d6584f88 ENOENT
    at exports._errnoException (util.js:949:11)
    at FSWatcher.start (fs.js:1433:19)
    at Object.fs.watch (fs.js:1460:11)
    at Gaze._watchDir (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:288:30)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:357:10
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/gaze.js:422:5
    at iterate (/Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:69:5)
    at /Applications/HyperTerm.app/Contents/Resources/app/node_modules/gaze/lib/helper.js:78:11
```

Clicking 'ok' makes my tests to run anyway.

**Comment by whitelynx** [comment]
@tleunen That error looks like it's more related to #444 and #542.

**Comment by chabou** [comment]
Feel free to reopen if this issue is still relevant
