### ISSUE TITLE
problem with agnoster zsh theme in Hyper Terminal

### ISSUE THREAD

**Issue by HujinoKun** [zeit/hyper#4018]
Hi,

Recently, i installed hyper in my laptop under fedora 31, however i've a problem with agnoster theme.

Regarding fonts, I have installed the project’s recommendations. However, some fonts do not work under hyper and works into default terminal.

Any ideas ?

System : Fedora 31
Hyper version : 3.0.2

**Comment by HujinoKun** [comment]
up

**Comment by bet4it** [comment]
Screenshot?

**Comment by HujinoKun** [comment]
Hyper terminal : 

[https://zupimages.net/up/19/49/1929.png](url)

Default terminal :
[https://zupimages.net/up/19/49/pb81.png](url)

**Comment by bet4it** [comment]
You may need to set `fontFamily` in `.hyper.js`

**Comment by HujinoKun** [comment]
Like that :

Go Mono for Powerline
Monofur for Powerline

... ?

https://github.com/powerline/fonts

last time it didn’t work, despite my reload

**Comment by bet4it** [comment]
I use `Hack Nerd Font` and it works well
