### ISSUE TITLE
Cursor not visible since update to xtermjs 4.3

### ISSUE THREAD

**Issue by LabhanshAgrawal** [zeit/hyper#4061]
Since f1b6c9c051c7b2d2a2b470db4363e42822511679 I'm facing this issue, the cursor and text selection both are not visible. Confirmed it by reverting to xtermjs 4.2, no issues in that.

**Comment by ivanwonder** [comment]
You should modify your cursor color value into ‘#000000’, looks like  it doesn’t support ‘rgba()’

**Comment by LabhanshAgrawal** [comment]
Thanks, that fixed it. I couldn't find any open issues on xtermjs about rgba. Is this a bug or they dropped support for rgba(which doesn't make much sense to me).

**Comment by ivanwonder** [comment]
A bug, you can try the ‘rgb’, I think it works too.

**Comment by ivanwonder** [comment]
https://github.com/xtermjs/xterm.js/pull/2560#issuecomment-558703845

**Comment by ivanwonder** [comment]
https://github.com/xtermjs/xterm.js/issues/2620
The issue can be closed now.
