### ISSUE TITLE
update tsc target

### ISSUE THREAD

**Issue by ivanwonder** [zeit/hyper#4080]
@LabhanshAgrawal https://github.com/zeit/hyper/blob/802d6064410b86909b4253943e1c4aee9dd4a679/tsconfig.base.json#L20

https://github.com/microsoft/vscode/blob/f4fc810feaed71661d60b5e41e1ce0d39f3e6747/src/tsconfig.json#L8
It's better to update tsc target to es2017/es2018 because the electron is the latest version and no need to be compatible with older browser.
worth trying and testing.

- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**:

**Comment by LabhanshAgrawal** [comment]
I tried setting ES2017 and didn't face any issues. I think we can go ahead and use it.
