### ISSUE TITLE
[feature] I think the notifications's css can be custom

### ISSUE THREAD

**Issue by stephenkingsley** [zeit/hyper#409]
In the term, the style can changed by edit `~/.hyperterm.js`. but the notifications can not. I think it can add this feature

**Comment by controversial** [comment]
OS X doesn't support this. This is not something hypeterm can control.

**Comment by henrikdahl** [comment]
This isn't possible. Unless you mean the notifications implemented inside the Hyper window, styling them is accessible by classes such as `notifications_view`. Closing since there's no way to implement if you meant the native ones ✌️
