### ISSUE TITLE
Open tab icon?

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#41]
Not everyone is so keyboard oriented

<img width="528" alt="screen shot 2016-07-04 at 4 51 40 pm" src="https://cloud.githubusercontent.com/assets/13041/16571039/9fae25ec-4207-11e6-9534-7d9680622a03.png">

thoughts?

**Comment by rauchg** [comment]
Counterpoint: takes away from the simplicity.

**Comment by montogeek** [comment]
I like the simplicity, people who uses a console actively are definitely keyboard oriented

**Comment by johanbrook** [comment]
One can argue that https://github.com/zeit/hyperterm/issues/40 is redundant if this is deemed redundant too.

**Comment by CodeTheory** [comment]
It's probably best to leave it out for simplicity, but does this terminal take those who are learning to use terminals into account? Is there a way to teach them these things? (Maybe this isn't important, but it's the thing that sprang to my mind)

**Comment by rauchg** [comment]
@johanbrook yes, but the difference is the real state involved is minor in that case.

**Comment by huytd** [comment]
One up vote for this idea, although I never use my mouse in terminal emulators 👍 It's just to make the UI more elegant.

**Comment by Qard** [comment]
If you want to keep the simple look, you could have buttons that fade in when the mouse is over the tab. If you don't use the mouse, you'll never see anything.

**Comment by nmn** [comment]
My vote is to add the button. While I tend to use a keyboard in the terminal too. Sometimes, a mouse click can actually be faster.

That said,  if this can be done with a plug-in that makes the most sense to me.

**Comment by Trickierstinky** [comment]
My vote for 1.

There is actually a button there on my Linux Ubuntu install and it works just that the asset is missing (See my screenshot) 
![linux](http://i.imgur.com/uip4uvs.png)

**Comment by chabou** [comment]
Yes: can be done with a plugin :)
