### ISSUE TITLE
Could you plan to support Korean?

### ISSUE THREAD

**Issue by wonminjeon** [zeit/hyper#410]
👍

**Comment by CodeTheory** [comment]
Could you share what exactly isn't working when writing Korean in HyperTerm?

**Comment by beapeter** [comment]
this is hyperterm.
![2016-07-29 4 06 16](https://cloud.githubusercontent.com/assets/8985959/17240497/cde86618-55a6-11e6-82b2-c40d0daa3aab.png)

this is default terminal.
![2016-07-29 4 07 18](https://cloud.githubusercontent.com/assets/8985959/17240511/dca8a5f0-55a6-11e6-8841-9de9a25d3ddb.png)

**Comment by daktwigim** [comment]
I cannot even type korean on hyperterm...

**Comment by sundancekid1108** [comment]
this is hyper
<img width="538" alt="hyper" src="https://cloud.githubusercontent.com/assets/10703291/26274707/f6f1816c-3d8a-11e7-9ddb-e7f8eb8e763a.png">

this is terminal
<img width="1000" alt="terminal" src="https://cloud.githubusercontent.com/assets/10703291/26274706/f6f14990-3d8a-11e7-81b0-bef73fb75f3d.png">

**Comment by k0626089** [comment]
And it goes absolutely crazy when you try to erase Korean.

![kapture 2017-06-30 at 17 25 29](https://user-images.githubusercontent.com/22045160/27727368-2b2b6558-5db9-11e7-8b63-0b01a9651cfd.gif)

**Comment by mgjo5899** [comment]
I'm not sure how it works with other languages but Hyper doesn't seem to deal with non-English languages in general..?

I'm seeing a broken file name when I do "ls" for a Korean file name

**Comment by chabou** [comment]
please try our v2 :)
