### ISSUE TITLE
Cleaning up package.json

### ISSUE THREAD

**Issue by LabhanshAgrawal** [zeit/hyper#4120]
The package.json has config for multiple other modules namely babel, ava, eslint, electron-builder and husky.
While initially it might've made sense to add the configs to package.json, but now it has become a 350 line behemoth. And looking for anything in it is hard.
We can split it into separate configs for the other modules, which will help clear it up and we will also benefit from autocomplete and explanation for keys from the json schema store for these configs, which is not possible currently, inside package.json.
I can send a [pr](https://github.com/zeit/hyper/compare/zeit:canary...LabhanshAgrawal:config_cleanup) if we want to do this.

**Comment by LabhanshAgrawal** [comment]
@Stanzilla what do you think about it?

**Comment by Stanzilla** [comment]
I'm fine with it!
