### ISSUE TITLE
Extra right padding when using vim

### ISSUE THREAD

**Issue by diovanii** [zeit/hyper#4134]
- [ x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 19.10
- **Hyper.app version**: 3.0.2 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/diovanii/17336b78dfd62209283be66bbd26d8e6
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **When i start Neovim hyper adds a right padding to the window**: 

## Issue
When i start Neovim from Hyper it adds a right padding to the window (even if padding is set to 0)

![print](https://user-images.githubusercontent.com/47093916/71755882-9f775e00-2e6b-11ea-8996-71e35ab12adf.png)

**Comment by iambumblehead** [comment]
same when using mac+hyper+emacs
