### ISSUE TITLE
Oh my Zsh not active when starting console

### ISSUE THREAD

**Issue by jbaccarelli** [zeit/hyper#4149]
I have a really weird issue...

I have installed WSL 2 on windows, then the Ububntu 18.04 system.

If i use the ubuntu app, everything is fine, but when i start Hyper and use bash, it starts WSL with zsh withouth "oh-my-zsh". 
If i try to `source ~/.zshrc` i get:

```
autoload: command not found
bash: /home/jbaccarelli/.oh-my-zsh/oh-my-zsh.sh: line 41: syntax error near unexpected token `('
bash: /home/jbaccarelli/.oh-my-zsh/oh-my-zsh.sh: line 41: `for plugin ($plugins); do'
```

I can't figure out what's the problem... Any ideas?

Thanks for your time and kind regards

**Comment by LabhanshAgrawal** [comment]
can you post your config files?

**Comment by martin-sweeny** [comment]
@jbaccarelli dude you solve this?
