### ISSUE TITLE
Can't open preferences when ssh-add is in .zshrc

### ISSUE THREAD

**Issue by cheshire137** [zeit/hyper#417]
When I hit `Command-,` to open hyperterm's preferences in El Capitan, I see this in the new term tab:

```
Agent pid 67357
echo Attempting to open ~/.hyperterm.js with your $EDITOR
echo If it fails, open it manually with your favorite editor!
bash -c "exec env $EDITOR ~/.hyperterm.js"
Enter passphrase for /Users/cheshire137/.ssh/id_rsa: 
```

When I enter the passphrase for my ssh key, I'm taken to my prompt instead of an editor with hyperterm.js loaded. If I run `bash -c "exec env $EDITOR ~/.hyperterm.js"` manually, it opens vim as expected. I have the following in my .zshrc file:

```
eval $(ssh-agent)
ssh-add ~/.ssh/id_rsa
```

I think one of these is tripping up opening the preferences for hyperterm.

**Comment by rauchg** [comment]
@cheshire137 I think we'll have to move away from the fancy editing technique and instead move this logic into a plugin, and try the `node-open` route instead.

Thanks for the report!

**Comment by chabou** [comment]
in our v2, our config file is open by your default `.js` editor
