### ISSUE TITLE
Flag to disable hyperlinks

### ISSUE THREAD

**Issue by Garethgr** [zeit/hyper#4193]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS High Sierra
- **Hyper.app version**: 3.0.2

## Issue
I am quite new to Hyper (installed it today)
I would like to know if there is a flag to disable hyperlinks found in the terminal.
When I try select them I click them instead and it ends up opening many tabs in my browser.
I see that `hyperlinks` was available for a previous version (this no longer works)

**Comment by LabhanshAgrawal** [comment]
AFAIK there is no config option to disable it.
