### ISSUE TITLE
Cursor does not appear in 3.10-canary.1

### ISSUE THREAD

**Issue by mbentley** [zeit/hyper#4195]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS Catalina 10.15.2
- **Hyper.app version**:  3.1.0-canary.1 (canary)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/mbentley/80d63c46f59a743326ed2afd298a7fc0
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: n/a
- **The issue is reproducible in vanilla Hyper.app**:  yes

## Issue

When upgrading from the latest stable to the latest canary, the cursor no longer shows up on the screen .  I removed my `.hyper.js` to let it generate a new config and it still doesn't show up.  Reverting back to the stable channel fixes that.

I did some playing around with my config and if I use a hex color, it shows up.  If I use a RBGA color, it either disappears or only appears if it is over text.

Cursor with `cursorColor: 'rgba(78,77,0,0.8)',` and my cursor is over the `n` in missing
![screenshot 2020-01-22 at 3 44 30 PM](https://user-images.githubusercontent.com/414445/72932622-219dc880-3d2e-11ea-873b-0ce789503672.png)

Looking fine with a hex value:
![screenshot 2020-01-22 at 3 47 52 PM](https://user-images.githubusercontent.com/414445/72932866-940ea880-3d2e-11ea-9887-6c08da9662ee.png)

**Comment by chabou** [comment]
Thank you for the hex workaround. I can confirm it's work

**Comment by LabhanshAgrawal** [comment]
This started with update to xterm 4.3 #4061 , seems like I had closed the issue without checking properly. https://github.com/xtermjs/xterm.js/issues/2620 addressed it which is closed, will need to check why it's not fixed for us.

**Comment by ivanwonder** [comment]
It has been fixed in master, I think it will be released in the next version. Try the latest beta. https://github.com/xtermjs/xterm.js/blob/master/README.md#beta-builds
