### ISSUE TITLE
Text selection does work in 3.1.0-canary.1

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#4196]
I can't select text anymore
(Using canvas renderer)

**Comment by LabhanshAgrawal** [comment]
I think this is related to the cursor issue, for me it's working as I have selectionColor set in #rrggbbaa

**Comment by chabou** [comment]
yesss! same workaround! Thanks 🙏

**Comment by ShadowFM** [comment]
I have the same issue and as hex coloring I could fix it, hope rgba will work soon again
