### ISSUE TITLE
Can you run GUI apps based on electron(like VSCode, Postman) embedded inside Hyper?

### ISSUE THREAD

**Issue by parrotcar00** [zeit/hyper#4214]
Considering Hyper uses HTML and CSS technologies to draw on screen, I was wondering if I can run VSCode in a small terminal window with all GUI effects and similarly any other electron app like Postman or Slack in a hyper window. It would serve the purpose like a tiled window manager. Tried to search around if it is possible but couldn't find any answers to it!

**Comment by ppot** [comment]
No sorry, can't do that! You have many tilling manager open source however depending of your platform!
