### ISSUE TITLE
CMD is not parented to HYPER process.

### ISSUE THREAD

**Issue by cbuteau** [zeit/hyper#4257]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Windows 10 Enterprise Version 1903**: 
- **Hyper 3.0.2 (stable)**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/cbuteau/f196751828dcef04797306a1b912ce99
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**: 

I removed all plugins from my .hyper.js file and restarted it and it stil has the problem.

## Issue

Hello I recently got the Windows 10 May 2019 update at work.
After HYper would not restart properly.
I said okay weird I will reinstall it.

What I see is this the command window is not parented in Hyper.
I also tried swicthing to Git Bash and it had the same problem.

The only plugin I am really using is init (hyper-init?) which I use to initialize certain tools.

This is what it looks like....
I will swicth to regular command windows in the meantime.

![image](https://user-images.githubusercontent.com/1906839/74365853-e165bf00-4d9c-11ea-92e5-ba33965ad3dc.png)

**Comment by JukkaM** [comment]
I'm facing a similar issue in my Windows 10 PC. I'm using Github Desktop and I have configured hyper as default shell application. If I launch hyper from Github Desktop, hyper is started but the cmd area is blank. I'm using the latest Github Desktop and hyper (3.0.2). There are no errors in Developer tool console.

**Comment by cbuteau** [comment]
I switched to Windows Terminal Preview in the meantime...goodbye hyper you were fun for awhile...
