### ISSUE TITLE
Buffer() is deprecated Error on update plugins

### ISSUE THREAD

**Issue by DanielTamkin** [zeit/hyper#4258]
- [x] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:

N/A

  - **Is the issue reproducible in vanilla Hyper.app?**

This error started occuring during class, haven't had the time to reproduce on vanilla.

## Issue

Since a few days ago i've been getting this strange error:
![Hyper error](https://user-images.githubusercontent.com/9532762/74376852-77531700-4da8-11ea-8720-855de945e8c7.png)

I have done no changes to my config in a few months, possible update bug?
Wish i could provide more info off the bat but i haven't messed with my installation in months so not present in the hyper ecosystem.

I see that his is a similar dup of #3595 & #3722, however there are no present remedies for this persistant error from what i'm finding in the issues.

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** win32 x64 10.0.17763
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "\"Fira Code\", Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "0px 12px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "C:\\Windows\\System32\\bash.exe",
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true,
  "summon": {
    "hideDock": false,
    "hideOnBlur": false,
    "hotkey": "Alt+Q"
  },
  "systray": {
    "hotkey": "Alt+W"
  }
}

          {
  "plugins": [
    "hyper-sync-settings",
    "hyperocean",
    "hyperterm-dibdabs",
    "hyper-autohide-tabs",
    "hyperterm-summon"
  ],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by ppot** [comment]
Duplicated. Will keep 3722 opened

**Comment by brcmesquita** [comment]
I had the same problem here.

The problem is complicated to discover, but it is more than obvious.

We install "hyper" on Windows, via Windows, and then we want to install plugins etc via WSL (Bash Linux). It will not work!

To resolve, go back to the default configuration of Hyper (deleting ".hyper.js") where it will open with the "cmd" Windows again. Install all the plugins you want, and only after that you change to WSL by default.

Applause! kkkkkkkkkkk
