### ISSUE TITLE
Feature request: enable keyword completion in Vim

### ISSUE THREAD

**Issue by rafaelrinaldi** [zeit/hyper#426]
For some reason, keyword completion doesn't work in Vim when I'm running HyperTerm (neither `<C-N>` nor `<C-P>`). Not sure what's happening but it's a feature I use a lot so I would love to have it available.

**Comment by albinekb** [comment]
Related to: #213

**Comment by chabou** [comment]
Presumed to have been fixed by #1006
Feel free to reopen
