### ISSUE TITLE
Get error "cannot find the 'nam' command" when I run plugins>update all now

### ISSUE THREAD

**Issue by Sosullivan** [zeit/hyper#429]
Get error "cannot find the 'nam' command" when I run pluginsupdate all now
-

HyperTerm 0.7.0
Electron 1.2.8
darwin x64 15.6.0

**Comment by ekmartin** [comment]
Closing this for now. Let me know if you can still reproduce the bug in the latest release and I'll reopen.

**Comment by cgumb** [comment]
I get the same error, as do all these people it seems: https://github.com/zeit/hyper/issues/89
