### ISSUE TITLE
Hyper Terminal Not Opening after installation Windows 10.

### ISSUE THREAD

**Issue by SajjanKarn** [zeit/hyper#4317]
### Hey Guys I used to love The Hyper Terminal.. IT was working fine and i uninstalled it for some reasons..
Now I recently installed it and performed cleaned installation. It doesn't open any window..

_Please Help Me Guys!_

![Capture](https://user-images.githubusercontent.com/49333264/75038977-bb989280-54df-11ea-88c2-07a0eecee71f.PNG)

**Comment by lemarier** [comment]
Hi !

Can you try running the app from command line and see if you got any error?

**Comment by SajjanKarn** [comment]
Hey Guys I have found the solution

1.) Open the CMD as Administrator
and run this...

gpupdate /force

then uninstall hyper and remove its folder from these directories..
%appdata% and %localappdata%

Install Hyper Again

and then restart your PC. Problem Solved!

**Comment by mrghasemi1992** [comment]
@SajjanKarn Thanks for your solution. It works for me.

**Comment by gv706** [comment]
> Hey Guys I have found the solution
> 
> 1.) Open the CMD as Administrator
> and run this...
> 
> gpupdate /force
> 
> then uninstall hyper and remove its folder from these directories..
> %appdata% and %localappdata%
> 
> Install Hyper Again
> 
> and then restart your PC. Problem Solved!

Thank You..It worked for me

**Comment by Yuvaan1182** [comment]
@SajjanKarn Thank BROTHER for your solution.
it helped me

**Comment by viswaviswesh** [comment]
Thanks! Brother It Helped Me .
