### ISSUE TITLE
Escape key does not work in latest canary build on MacOS

### ISSUE THREAD

**Issue by LudwigThePig** [zeit/hyper#4332]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Mojave 10.14.6
- **Hyper.app version**: Canary (Feb 19th ish release)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: [link to  gist](https://gist.github.com/LudwigThePig/babee9574312f8cc97642fb941a24769)
- **Relevant information from devtools**  N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue

In the latest canary build, the escape key no longer performs the desired behavior (like exiting a mode in vim). I believe this is mapped to the `close()` dispatcher.

I dug around and I think it has something to do with [this commit](https://github.com/zeit/hyper/commit/c337288efa74acec63f4ba37f1abbd2f469f068b) or some commit around that time.

If I switch back to the stable release, the exit button works.

Let me know if you'd like me to provide any other details or dig a little deeper.

Cheers,
Morgan

**Comment by lucactusss** [comment]
It also happens with Linux OS (Ubuntu 19.10) and with the latest canary build

**Comment by saamalik** [comment]
Use `Ctrl+[` like a champ instead! =)

**Comment by bntzio** [comment]
Yep, it's happening to me as well.

**Comment by brandonpittman** [comment]
Back to iTerm…

**Comment by AaronRobinson** [comment]
And me

**Comment by nyc-tinker** [comment]
Can confirm also MacOS catalina doesn't work.  Can confirm that <Esc> works in regular terminal, so it's a hyper-specific issue

**Comment by peppy** [comment]
As the current canary build is broken, I'd propose doing a new canary release with the fix included.

**Comment by LabhanshAgrawal** [comment]
New release might take some time, you can use the build from [CI](https://github.com/zeit/hyper/actions?query=branch%3Acanary).

**Comment by LabhanshAgrawal** [comment]
@LudwigThePig 
Were you able try out the ci build?

**Comment by peppy** [comment]
Can confirm it works again on the latest CI build.

**Comment by AaronRobinson** [comment]
Works for me after fresh download

**Comment by LabhanshAgrawal** [comment]
@LudwigThePig can you also try it and close this issue if everything's good.

**Comment by saamalik** [comment]
Fixed it for me too!

**Comment by andreasvirkus** [comment]
@LabhanshAgrawal This is still broken on the latest canary (`3.1.0-canary.4`) on macOS 11.1, `Ctrl+[` is the workaround for now i suppose.

**Comment by LabhanshAgrawal** [comment]
There's some issues blocking releases, you can get the ci build from https://github.com/vercel/hyper/actions/runs/461548454
