### ISSUE TITLE
Stopped loading config'd bash shell, loads cmd regardless after win10 update

### ISSUE THREAD

**Issue by cradbold** [zeit/hyper#4354]
- [X] Your Hyper.app version is **3.0.2**. Please verify your using the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
  - [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

  ---
  - **Any relevant information from devtools?** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:
Not much logged... don't see any errs

  - **Is the issue reproducible in vanilla Hyper.app?**
n/a -- the whole point is I'm commonly overriding cmd --> bash

## Issue
I've had hyper working fine for a few weeks now after setting up WIN10 as a WSL2-Ubuntu dev env.  Took some time off, came back & updated WIN10... At some point, Hyper stopped honoring the shell config:
shell: `C:\\Windows\\System32\\bash.exe`,

Just defaults to WIN10 shell.  Looks to be ignoring it completely in the snippet below, but I've confirmed it is specified.

Could this be part of the issue?  Location of config is reportedly this path:
```C:\Users\[me]\AppData\Roaming\Hyper\.hyper.js```

I tried to manually save it to ~/.hyper.js -- but got a notification that the path has changed to the ...Roaming\Hyper... path above.  The config auto-reported below (?) is not the config that comes up from the hamburger --> Edit --> Preferences.

 - **Hyper version**: undefined "3.0.2"

 - **OS ARCH VERSION:** win32 x64 10.0.19041.113
 - **Electron:** 3.1.3  **LANG:** undefined
 - **SHELL:** undefined   **TERM:** undefined

  <details>
    <summary><strong> ~/.hyper.js contents</strong></summary>
      <pre>
        <code>
          {
  "updateChannel": "stable",
  "fontSize": 12,
  "fontFamily": "Menlo, \"DejaVu Sans Mono\", Consolas, \"Lucida Console\", monospace",
  "fontWeight": "normal",
  "fontWeightBold": "bold",
  "lineHeight": 1,
  "letterSpacing": 0,
  "cursorColor": "rgba(248,28,229,0.8)",
  "cursorAccentColor": "#000",
  "cursorShape": "BLOCK",
  "cursorBlink": false,
  "foregroundColor": "#fff",
  "backgroundColor": "#000",
  "selectionColor": "rgba(248,28,229,0.3)",
  "borderColor": "#333",
  "css": "",
  "termCSS": "",
  "showHamburgerMenu": "",
  "showWindowControls": "",
  "padding": "12px 14px",
  "colors": {
    "black": "#000000",
    "red": "#C51E14",
    "green": "#1DC121",
    "yellow": "#C7C329",
    "blue": "#0A2FC4",
    "magenta": "#C839C5",
    "cyan": "#20C5C6",
    "white": "#C7C7C7",
    "lightBlack": "#686868",
    "lightRed": "#FD6F6B",
    "lightGreen": "#67F86F",
    "lightYellow": "#FFFA72",
    "lightBlue": "#6A76FB",
    "lightMagenta": "#FD7CFC",
    "lightCyan": "#68FDFE",
    "lightWhite": "#FFFFFF"
  },
  "shell": "",
  "shellArgs": [
    "--login"
  ],
  "env": {},
  "bell": "SOUND",
  "copyOnSelect": false,
  "defaultSSHApp": true,
  "quickEdit": false,
  "macOptionSelectionMode": "vertical",
  "webGLRenderer": true
}

          {
  "plugins": [],
  "localPlugins": []
}
        </code>
      </pre>
  </details>

**Comment by LabhanshAgrawal** [comment]
make a copy of your config somewhere and delete the ones in ~ and appdata, Hyper will create the config file again.
You can make your changes to that file.
try this and then we can see if it resolves the issue

**Comment by Stanzilla** [comment]
Also use wsl.exe instead of bash.exe

**Comment by cradbold** [comment]
Seeing a lot of instability around it now after also trying reinstall in addition to above suggestions -- rogue processes, won't-starts.  Gonna move on to something else, but I enjoyed it when it was working for me!

![Screenshot (4)](https://user-images.githubusercontent.com/2042966/76723466-983ebd00-6704-11ea-836c-f316a97f4ddc.png)

**Comment by cradbold** [comment]
Full uninstall including 'AppData/Roaming/Hyper' + restart (i.e. kill rogue processes) + full reinstall finally did the trick.  Thanks for suggestions (bash --> wsl also, which needed --login config removed)
