### ISSUE TITLE
chrome OS support?

### ISSUE THREAD

**Issue by nathgit** [zeit/hyper#4376]
is this compatible with Chrome OS's implementation of Linux (official)?

**Comment by LabhanshAgrawal** [comment]
You can try installing the deb file I suppose.

**Comment by LabhanshAgrawal** [comment]
@nathgit did you try the deb file?

**Comment by nathgit** [comment]
it won't interfere with the builtin terminal, right?

**Comment by LabhanshAgrawal** [comment]
We don't set any defaults or anything so there should be no issues

**Comment by nathgit** [comment]
I was able to install it & I ran a shell script. Do the themes work? I clicked on one of them on the site & there's a message at the bottom that says: "We can't currently find information for this extension 😰
 
View source code" I clicked on a second one & got the same message. Both do have an install button though.

**Comment by LabhanshAgrawal** [comment]
The extensions are installed from npm, the site just lists a few. You can take a look at https://github.com/bnb/awesome-hyper
It lists plugins, themes etc.
To install you need to run `hyper i <plugin-name>` in shell. You might need to click `Install Hyper CLI in path` from the `plugins` menu in hyper first.
Can you close this issue as you were able to install it. If you face any other problem you can open a new issue.
