### ISSUE TITLE
Feature: MOSH: Server-side SSH implementation

### ISSUE THREAD

**Issue by gulakov** [zeit/hyper#438]
I have been trying to hack it with some of my favorite tools:
MOSH
https://mosh.mit.edu/
This is a server-side shell that makes SSH way better/faster by using a TCP socket for realtime control.
@rauchg do you think this can be used with socket.io or a similar tool, for HyperTerm since I mostly need command line / vi tools when i'm logged into a remove web server. The HyperTerm GUI would be on the host, and with mosh it can run as a chrome app or even mobile app, but MOSH-like tool runs on the server. In addition you could include various plugins to simplify webserver admin.

ps. would also be cool to have a guake-style mode, using a key to show/hide as a top overlay full-width

**Comment by albinekb** [comment]
Regarding your ps: #397 
[hyperterm-overlay](https://github.com/rickgbw/hyperterm-overlay)

**Comment by chabou** [comment]
I do not understand this. You can use `mosh` inside your favorite shell inside Hyper.
For me, `mosh` is a telnet/ssh replacement.

Reopen if I'm wrong.
