### ISSUE TITLE
Annoying % at Hyper startup

### ISSUE THREAD

**Issue by KZTN** [zeit/hyper#4400]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu 20.04 LTS
- **Hyper.app version**: 3.0.2 STABLE
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Everytime when the Hyper is launched, a% is printed on terminal output. any clue to contour this? I had a idea to startup with clear bash command to avoid this. Somehow...
![Screenshot from 2020-03-18 16-19-28](https://user-images.githubusercontent.com/6463299/76998700-4d0af100-6934-11ea-895f-c2710e403466.png)

**Comment by LabhanshAgrawal** [comment]
https://github.com/zeit/hyper/issues/2144#issuecomment-326741620

**Comment by KZTN** [comment]
> [#2144 (comment)](https://github.com/zeit/hyper/issues/2144#issuecomment-326741620)

Ok, solved
