### ISSUE TITLE
Lang variable incorrect for Swedish

### ISSUE THREAD

**Issue by jenslind** [zeit/hyper#441]
`app.getLocale()` seems to return only `sv`. But the correct value should be `sv_SE`.
So currently my `LANG` var is `sv.UTF-8` and I can't type `åäö`.
Looking at https://github.com/electron/electron/blob/master/docs/api/locales.md it seems more languages are affected.

**Comment by CodeTheory** [comment]
Typing characters like that is a known issue and should be fixed by #214.
I'll leave this issue open for the `app.getLocale()` returned value issue.

**Comment by albinekb** [comment]
If i open up the inspector (`alt+cmd+i`) and run `require('electron').remote.app.getLocale()`,
i get `en-US`
and LANG is set to`en_US.UTF-8`

however åäö works form me

**Comment by jenslind** [comment]
`åäö` works for me too if my LANG is `sv_SE.UTF-8`

**Comment by albinekb** [comment]
What do you get if you run `navigator.language` in the devtools of hyperterm?

**Comment by jenslind** [comment]
`navigator.language` returns `sv`

**Comment by albinekb** [comment]
Possibly related to https://github.com/electron/electron/issues/5649

**Comment by jenslind** [comment]
I don't think it's a electron bug nor a chromium, but I might be wrong.
However possible solutions that came to my mind:
- Use [os-locale](https://github.com/sindresorhus/os-locale) instead
- Try to get the country code (maybe with [country-language](https://github.com/bdswiss/country-language) or [country-data](https://github.com/OpenBookPrices/country-data))
- Or just use `en_GB` or `en_US` not sure what the downside might be

**Comment by rauchg** [comment]
`os-locale` seems great :D @sindresorhus in this case do you think it would return what we need ? (`sv_SE`)

**Comment by albinekb** [comment]
Does LANG have to be set?
I don't have it set in terminal nor iTerm2 🤔

http://webplay.pro/linux/set-locale-terminal-settings-mac-os-x.html
http://stackoverflow.com/questions/7165108/in-osx-lion-lang-is-not-set-to-utf8-how-fix

If it's not needed then i don't think hyperterm should automatically set it?

**Comment by c0b41** [comment]
same problem, os-locale seems to be okey

![Locale](https://cloud.githubusercontent.com/assets/2834954/17158155/e4a46232-539c-11e6-95ac-3570f8dbf35f.png)

**Comment by TooTallNate** [comment]
> I don't have it set in terminal nor iTerm2 🤔

I have it set by default in my Terminal and iTerm 2... I wonder if it's a bash vs. zsh thing then.

**Comment by sindresorhus** [comment]
> in this case do you think it would return what we need ?

It should, yes. `os-locale` even has fallbacks to read it directly from the system preferences on macOS.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
