### ISSUE TITLE
Unable to move terminal window on Windows 10 + WSL

### ISSUE THREAD

**Issue by michaeljmcd** [zeit/hyper#4426]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows 10 + WSL + VcVxsrv 
- **Hyper.app version**: 3.0.2 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Default Hyper JS (deleted files and tried fresh). 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla 

## Issue

After starting up Hyper on WSL + VcVxsrv, I cannot move or resize the window. Maximize and restore work, but resize doesn't change the window size and I cannot drag the window on the screen or to another monitor. Standard Windows shortcuts, like Win+Arrow don't work either.

There are no errors in developer tools and bringing the window to front with the menu doesn't change anything.

**Comment by LabhanshAgrawal** [comment]
is Hyper installed on windows or wsl?

**Comment by michaeljmcd** [comment]
WSL via the debian package.

**Comment by LabhanshAgrawal** [comment]
You should install Hyper in windows instead and set term to wsl.exe
x11 is not 'officially' supported by wsl https://github.com/Microsoft/WSL/issues/2356 so it might have a few kinks, maybe some apps work but all are not guaranteed to.

**Comment by michaeljmcd** [comment]
Setting it to Windows bash works (config settings below, if they are ever useful to anyone). It still feels odd for X11 not to work. I run gvim, zeal and terminator on X11 every day without issue. Either way, it works.

    shell: 'C:\\Windows\\System32\\bash.exe',
    shellArgs: ['~'],

**Comment by LabhanshAgrawal** [comment]
I agree most of the apps work through Vcxsrv, I have used some of them myself. But I had issues trying to run vs code like that. So maybe it's an issue with electron apps currently as the window frame and dragging are done in a roundabout way for electron apps (ones without the native frame like hyper, vscode etc.)
I think you can close the issue as it's resolved now.
