### ISSUE TITLE
E: The package hyper needs to be reinstalled, but I can't find an archive for it.

### ISSUE THREAD

**Issue by KZTN** [zeit/hyper#4427]
After installing Hyper and running the command https://github.com/zeit/hyper/issues/2764#issuecomment-374437229, i can't execute many funcionalitties in my OS(ubuntu 20.4)

Everytime when I try to download an program via apt-get, i can't complete it. And the problem is showing in every case
E: The package hyper needs to be reinstalled, but I can't find an archive for it.
I tried to reinstal via .deb package and unninstall, but anything changes

Hyper is running normaly
Sometimes I notice with an alert dialog for a crash problem

**Comment by KZTN** [comment]
After a search for simillar issues, I found the solution:
`sudo dpkg --remove --force-all ubuntu-mono`
then
`sudo apt-get update`
Reboot your pc and the hyper was completly removed and able to install again.

**Comment by iLeveller** [comment]
Almost the same message but I am on linux mint tricia and unable to solve E: The package io.solarwallet.app needs to be reinstalled, but I can't find an archive for it.
Tried: sudo rm /var/lib/apt/lists/* -vf after which I tried to update and reinstall but no joy.

Would appreciate any help

**Comment by Honcho1** [comment]
Please have you found any solution for your problem? I am going through the same thing now.

**Comment by anthonydublin** [comment]
> sudo dpkg --remove --force-all ubuntu-mono
Thank you.. Worked to get "jami-all" out for all time
