### ISSUE TITLE
Still getting the $PATH issue on hyperterm@0.7.1

### ISSUE THREAD

**Issue by nachoaIvarez** [zeit/hyper#443]
## Hyperterm Error

 Currently running v0.7.1, getting:

<img width="325" alt="screen shot 2016-07-26 at 19 43 44" src="https://cloud.githubusercontent.com/assets/7253814/17157943/53fc8440-5369-11e6-8f09-e3d15635ad18.png">

This means plugins can't be installed. So plugins can't be used 😞.
## npm

npm is correctly installed, and following @rauchg [reccomendation](https://github.com/zeit/hyperterm/issues/106#issuecomment-233064435):

``` sh
❯ which npm
/usr/local/bin/npm
```

and, to confirm:

``` sh
❯ npm config get prefix
/usr/local
```
## System data:

``` sh
❯ npm -v
3.10.6
```

``` sh
❯ node -v
v6.3.1
```

```
❯ brew cask update
Already up-to-date.
```

```
❯ brew cask update hyperterm
Already up-to-date.
```

**Comment by albinekb** [comment]
Related to #440,
Do you have a different login shell?

**Comment by nachoaIvarez** [comment]
Y use zsh which is set as my login shell, and npm is on my path since running `npm -v` works.

**Comment by albinekb** [comment]
Try doing this:
`cd /tmp`
`npm install shell-env`

```node -e 'require("shell-env")().then((env) => { console.log(`path: ${env.PATH} \n shell: ${env.SHELL}`) })'```

Does that look correct?

**Comment by nachoaIvarez** [comment]
It looks correct, yes:
```sh
path: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/nacho/dev/temp/node_modules/.bin:/Users/nacho/dev/node_modules/.bin:/Users/nacho/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/Cellar/node/6.3.1/bin 
 shell: /bin/zsh
```

I'm really close to trying reinstalling everything.

**Comment by rauchg** [comment]
Last thing: are we correctly diagnosing that npm can't be found, or is that message masking some other type of error :) ?

**Comment by albinekb** [comment]
Does `/bin/zsh -c "/usr/local/bin/npm --help" work?

Yeah @rauchg I'm starting to think there's something else wrong 😕
The plugin installation-function has kinda bad error handling 😁

**Comment by matheuss** [comment]
I think that the message could be masking some other type of error:
```
if (/not a recognized/.test(err.message) || /command not found/.test(err.message)) {
        notify(
          'Error updating plugins.',
          'We could not find the `npm` command. Make sure it\'s in $PATH'
        );
```

https://github.com/zeit/hyperterm/blob/27b2cd718ef07355400d32ecc70dcfeab1a480da/app/plugins.js#L69-L73

**Comment by nachoaIvarez** [comment]
@albinekb: 
```~/dev/temp   
❯ /bin/zsh -c "/usr/local/bin/npm --help"

Usage: npm <command>

where <command> is one of:

... more npm help stuff

npm@3.10.6 /usr/local/lib/node_modules/npm
```

**Comment by tg90nor** [comment]
I have this problem as well. I changed the notify output to get the real error message:

    Command failed: npm prune && npm install --production
    /bin/sh: npm: command not found

So it seems it is trying to use /bin/sh even though /bin/zsh is my login shell

    $ echo $SHELL
    /bin/zsh

The strange thing is that npm should be in the $PATH even if ran by /bin/sh

**Comment by nachoaIvarez** [comment]
@albinekb: Resolved the issue. Oh-My-Zsh was causing the problem, I guess it was messing with the path in some way. I uninstalled it and $PATH and npm not found errors were gone. I reinstalled Oh-My-Zsh again and it's still working. I guess you need a Oh-My-Zsh reinstall after installing Hyperterm.

**Comment by tg90nor** [comment]
It seems the issue for me is I have zsh configured to spawn or attach to a tmux session when i open a terminal.

Not sure how to debug this further though. The tmux attaching is so important I will keep using another terminal.

**Comment by matheuss** [comment]
I use Oh My Zsh here and I did not have to reinstall it after "installing" HyperTerm 😅

**Comment by nachoaIvarez** [comment]
@tg90nor I use tmux attach on login too, without a hassle!

This is the script I have on my `.zshrc`
```sh
# TMUX
tmux attach &> /dev/null;
if [[ ! $TERM =~ screen ]]; then
    exec tmux
fi
```

**Comment by nachoaIvarez** [comment]
@matheuss Weird! But it worked for me! Uninstalling it made my hyperterm plugins install and load with no problem. Then I tried installing Oh-My-Zsh it again and here we are, everything functional. I honestly don't know what happened ¯\_(ツ)_/¯

**Comment by tg90nor** [comment]
@nachoaIvarez did you try to manually update plugins after reinstalling Oh-My-Zsh? HyperTerm will not try to automatically update plugins if it has done so recently.

**Comment by niedzielski** [comment]
I think I'm seeing the underlying cause of this issue manifest in a slightly different way. I do not see my PATH being imported properly. From a shell, `echo $PATH|sed 's%:%\n%g'`:

```
/home/stephen/bin
/home/stephen/opt/racket/bin
/home/stephen/opt/pebble/bin
/home/stephen/opt/pebble/Pebble
/home/stephen/opt/pebble/arm-cs-tools/bin
/home/stephen/opt/flutter/bin
/home/stephen/opt/emsdk
/home/stephen/opt/emsdk/clang/fastcomp/build_master_64/bin
/home/stephen/opt/emsdk/node/4.1.1_64bit/bin
/home/stephen/opt/emsdk/emscripten/master
node_modules/.bin
/home/stephen/.node/bin
/home/stephen/.local/bin
/home/stephen/.cabal/bin
/usr/lib/go/bin
/bin
/usr/local/bin
/usr/bin
/usr/local/games
/usr/games
/home/stephen/opt/android/sdk/tools
/home/stephen/opt/android/sdk/platform-tools
/home/stephen/opt/android/sdk/build-tools/24.0.1
/home/stephen/opt/android/ndk
```

Launched from the same shell, `./HyperTerm`:
```
/usr/local/bin
/usr/bin
/bin
/usr/local/games
/usr/games
```

These PATHs are exported in my ~/.profile which is sourced by the system at login (not by ~/.bashrc or ~/.bash_login). I'm on Debian Stretch.

**Comment by Lindenk** [comment]
If it's any help, I'm also having this problem. On a fresh install, running:

`echo $PATH`
gives:
`/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`
whereas:
`zsh; echo $PATH`
gives:
`/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/lindenk/bin/:/home/lindenk/.cabal/bin/:/home/lindenk/.go/bin/:/home/lindenk/.cargo/bin/`

The problem appears to be my `$PATH` not getting set correctly unless I manually run my shell again. Playing around with my dotfiles, it appears that hyperterm isn't loading `.zshenv` when it starts with `zsh` as the shell.

**Comment by niedzielski** [comment]
I agree. PATH isn't honored:

```
$ export PATH=foo
$ ./HyperTerm
# --- In HyperTerm window now
$ echo "$PATH"
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

**Comment by gurinderhans** [comment]
Is it possible to not require `npm` to be installed on the user's machine? For ex. I use docker for everything, except obviously for GUI applications, just as a way to keep the original system "clean".

I understand that npm is required for installing and updating plugins, maybe npm can be packaged within HyperTerm and its sandboxed?

**Comment by zackhall** [comment]
I am seeing this same "npm not in $PATH" issue, but I'm noticing something very interesting. 

In iTerm and Terminal, I see the following:
```shell
echo $SHELL
/bin/zsh
```

But in HyperTerm, I see:
```shell
echo $SHELL
/bin/false
```

My login shell is set to `/bin/zsh`. I've also set it to zsh in the hyperterm settings. Is this the potential cause of the problem?

I'm on Version 0.7.1 (0.7.1.36).

**Comment by tyrollins** [comment]
I too receive this error and am using zsh (or have it set to be using zsh), which seems to be the one commonality among all posters. I do not have oh-my-zsh installed, and have noticed that when running `npm install` from the .hyperterm_plugins folder all works fine. 

### Curiosities 
---
*note: my login shell and .hyperterm.js are both set to `/usr/local/bin/zsh`. 
```
# From Hyperterm

❯ echo $SHELL
/bin/bash
```
```
# From login shell - Terminal.app

❯ echo $SHELL
/usr/local/bin/zsh
```
Again, my .hyperterm.js file has shell set to `/usr/local/bin/zsh`.

### npm
---
```
❯ which npm
/Users/username/.nvm/versions/node/v6.4.0/bin/npm
```

```
❯ npm config get prefix
/Users/username/.nvm/versions/node/v6.4.0
```

```
❯ npm -v
3.10.3
```

```
❯ node -v
v6.4.0
```

```
❯ $PATH
...
/usr/local/sbin:/Users/username/.rbenv/shims:/Users/username/.nvm/versions/node/v6.4.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by zackhall** [comment]
I have also noticed that when running npm install from the `.hyperterm_plugins` folder all works fine. And for what it's worth, I do have oh-my-zsh installed.

**Comment by bencooling** [comment]
osx: 10.12
hyperterm: 0.7.1.36
nvm: 0.32.0

I tried (without luck) changing my default login shell in my user account under System Preferences to `/bin/zsh` and in `~/.hyperterm.js` reverting `/bin/zsh` back to empty string:

```
    // if left empty, your system's login shell will be used by default
    shell: ''
```

I also tried `brew cask` and downloaded release both complain they cannot find npm command.

**Comment by ryanpcmcquen** [comment]
Also affected on `bash`, Mac OS 10.11:

```
$ echo $SHELL
/bin/bash
$ echo $PATH
/usr/local/Homebrew/bin:/opt/mypaint/bin:/opt/local/bin:/opt/X11/bin:/usr/local/bin
$ which npm
/usr/local/bin/npm
```

**Comment by 0xcaff** [comment]
I fixed this by putting

    source ~/.nvm/nvm.sh

in my `~/.bashrc`.
