### ISSUE TITLE
The State of Hyper vs other Terminal Apps.

### ISSUE THREAD

**Issue by NotMoni** [zeit/hyper#4440]
- [x ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Catalina  10.15.4
- **Hyper.app version**: 3.0.2
- **The issue is reproducible in vanilla Hyper.app**: YES

### State of Hyper

Hyper is very good at what it does. **Make the terminal look good.** It has many extensions. This is a good app for people that use the terminal and dont care about other features. 
 
**The Problems**
As a dev, we need a terminal that has features that dev's need. These are a fast terminal app and a decentralized ecosystem.

We need no make this terminal fast. 
The Terminal app on macOS opens up in 0.3 seconds
While Hyper takes 4 seconds. (Vanilla Hyper + no customize)
When i have 5+ tabs with Hyper It would eventually lead to my terminal becoming unresponsive on occasion. Not too often, but enough to interrupt my workflow.

### The Light

We need to have a version of hyper that is fast, and minimal while making it look good.
This is for all the devs, and users like me and you.

**Comment by Stanzilla** [comment]
Okay but what is the point of this issue? I agree with you on almost everything but it will be impossible to reach native speeds with an Electron stack. Hyper lost the power of ZEIT behind it and is mostly maintained by 1.5 (I'm the .5) people these days.

**Comment by NotMoni** [comment]
@Stanzilla It is ambitious, but ~~remove the electron stack~~, aka remake the app. I am down to help and make a terminal app that takes the pros of hyper and puts it in a fast almost native terminal. Who is the other maintainor? We 3 should make a new terminal app. Even though there are a lot of terminal apps they don't have as customizability as hyper.  **I want to do this**. What about you?

**Comment by Stanzilla** [comment]
That's a bit out of scope for this project. There are a lot of good and native terminals out there for every OS.

**Comment by NotMoni** [comment]
I just want to improve Hyper @Stanzilla

**Comment by Stanzilla** [comment]
Well that's fine, we're always taking Pull Requests :)
