### ISSUE TITLE
Can't install Hyper .deb on Ubuntu 20.04

### ISSUE THREAD

**Issue by chris-c-thomas** [zeit/hyper#4459]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Ubuntu 20.04 Beta**: 
- **Current .deb 3.0.2**: 

## Issue

When I download the available .deb from the website it won't install in Ubuntu's Software application as in the past. An error occurs saying "Failed to Install: not supported".

I haven't done much investigating other than knowing GitHub's Atom editor also seems to be experiencing the same issue [here](https://github.com/atom/atom/issues/20356)

**Comment by chris-c-thomas** [comment]
Nevermind, this is Ubuntu related. [See Here](https://ubuntuforums.org/showthread.php?t=2439893)

**Comment by LabhanshAgrawal** [comment]
you can try the appImage or snap also from https://github.com/zeit/hyper/actions/runs/71249146
