### ISSUE TITLE
Using msys2 shell with hyper

### ISSUE THREAD

**Issue by LazyRen** [zeit/hyper#4462]
I've looked all over the internet for the information, but couldn't find specific guideline for this.

Alomst all bash with Windows use git-cmd.exe.

For those who needs to use msys2, here is what I've done to the `hyper.js`
```shell
shell: 'C:\\msys64\\msys2_shell.cmd',
shellArgs: [
    '-mingw64',
    '-defterm',
    '-no-start',
    '-full-path',
    '-where',
    'C:\\Users\\LazyRen\\dev'
],
```

**Comment by junguler** [comment]
amazing, thank you
