### ISSUE TITLE
hyperjs on canary will not update past 3.0.2 (the most recent stable version)

### ISSUE THREAD

**Issue by epitone** [zeit/hyper#4511]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows 10 Home (Version 10.0.17763 Build 17763)
- **Hyper.app version**: Hyper 3.0.2 (Canary/Stable)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/epitone/78fc95383ebf7b6f7e24536dc1eac7b4
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Yes

## Issue
I think there is _one_ [issue](https://github.com/zeit/hyper/issues/2522) similar to what I have currently from 2017 but it's not quite the same as they could at least get updates downloaded, it seems like I am unable to do even that. I've completely uninstalled hyperjs, removed everything from within the AppData directory just to make double sure that wasn't causing issues, and reinstalled hyperjs but still cannot get canary to update despite me changing the channelUpdate in preferences.

**Comment by LabhanshAgrawal** [comment]
That's because canary release for windows is not there because of a cert issue. You can get the latest build from the [ci](https://github.com/zeit/hyper/actions?query=branch%3Acanary+event%3Apush)

**Comment by epitone** [comment]
Ah, thank you! @LabhanshAgrawal. I didn't realize that was where I needed to get the canary version. Rather than starting a new issue, would you happen to know if there's a workaround for attempting to load WSL bash in Hyper? I set the shell variable appropriately to `C:\\Windows\\System32\\wsl.exe` but it looks like that causes Hyper to crash on startup and I'm not too sure why.

**Comment by LabhanshAgrawal** [comment]
I simply use
```
shell: 'C:\\Windows\\System32\\wsl.exe',
shellArgs: [],
env: {}
```
