### ISSUE TITLE
Download link for Debian not correct

### ISSUE THREAD

**Issue by igotnocans** [zeit/hyper#4559]
Hello,

Just a quick issue, not sure where else to post it. The download link for debian on the main website links to https://releases.hyper.is/download/dev instead of https://releases.hyper.is/download/deb

**Comment by vassbence** [comment]
Thanks for opening an issue, I'll fix it :) [Site's repo can be found here if you are interested](https://github.com/zeit/hyper-site)

**Comment by timothyis** [comment]
Looks like this fix was merged! Closing for now, thanks @vassbence! Please feel free to comment if still broken @igotnocans
