### ISSUE TITLE
Ability to get rid of window header (incl close / minimize / full screen buttons)

### ISSUE THREAD

**Issue by alexfedoseev** [zeit/hyper#459]
Personally I find useless these small circles in the top left corner. They add noise for no profit, b/c anyway everybody use hot keys. My current iTerm looks like this: https://cl.ly/gnbR

What about to make presence of header configurable? (on by default)
And also `border-radius` of the window (now I can't change it via config's css).

**Comment by albinekb** [comment]
I just made a plugin to remove the traffic lights 👼  so clean!
https://www.npmjs.com/package/hyperclean
Add it to your `.hyperterm.js`

**Comment by alexfedoseev** [comment]
@albinekb Looks cool, thanks!

**Comment by NicholasDunham** [comment]
@albinekb Exactly what I was looking for, too. Thank you!

**Comment by efegurkan** [comment]
Is this issue still relevant? Looks like a solution is found.

**Comment by henrikdahl** [comment]
@alexfedoseev shouldn't this be closed? ✌️

**Comment by ppot** [comment]
Yes I will close this. Thanks for your'r feedback! 👍
