### ISSUE TITLE
Fix braille rendering

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#46]
tfw:

![image](https://cloud.githubusercontent.com/assets/13041/16572874/5bef5450-4222-11e6-811c-309dfa376cc8.png)

**Comment by mauro-oto** [comment]
Looks like it's broken in `hterm` as well: https://github.com/MrRio/vtop/issues/60

**Comment by MrRio** [comment]
As the author of vtop I'm keen to see this fixed :P

**Comment by albinekb** [comment]
PR in-progress: #535

**Comment by ppot** [comment]
@matheuss

**Comment by matheuss** [comment]
Thanks @ppot ☺️
