### ISSUE TITLE
Broken lines

### ISSUE THREAD

**Issue by langolf** [zeit/hyper#461]
When I expand any folder in NerdTree sidebar and the arrow symbol is changing, some force breaking lines in hyperterm.

<img width="753" alt="screen shot 2016-07-27 at 14 10 50" src="https://cloud.githubusercontent.com/assets/1225205/17179288/5586d834-5421-11e6-9342-a0d567fef235.png">

**Comment by albinekb** [comment]
Looks like the characters with is not calculated properly, have you tried changing the font?

**Comment by langolf** [comment]
@albinekb Yep, it seems there is a problem with some fonts. Previous screenshot was with Fira Code. Here is Hack

<img width="477" alt="screen shot 2016-07-27 at 19 35 38" src="https://cloud.githubusercontent.com/assets/1225205/17183708/64f1312e-5431-11e6-8263-66cdfbe71728.png">

And this is Consolas

<img width="353" alt="screen shot 2016-07-27 at 19 33 41" src="https://cloud.githubusercontent.com/assets/1225205/17183737/89b731de-5431-11e6-8cbf-f879bcb798aa.png">

**Comment by MrRio** [comment]
![screen shot 2016-07-30 at 16 27 30](https://cloud.githubusercontent.com/assets/47539/17271411/8878ccea-5672-11e6-9c87-5edc64cd7245.png)

Similiar issue is caused in vtop too. Looks like an issue with hterm

**Comment by NerdPad** [comment]
I have a similar issue.

![screen shot 2016-11-01 at 2 07 16 pm](https://cloud.githubusercontent.com/assets/87896/19901204/b273c090-a03c-11e6-9f22-ac6d063cc59f.png)

**Comment by chabou** [comment]
Seems fixed by #1745
On the left v1.3.1, on the right current master
![capture d ecran 2017-04-20 a 00 07 03](https://cloud.githubusercontent.com/assets/4137761/25204384/982c8cac-255d-11e7-9db1-a14026925523.png)

Please reopen if not.
