### ISSUE TITLE
Hyperterm fails to display symbols

### ISSUE THREAD

**Issue by c0debreaker** [zeit/hyper#464]
I'm using Oh-my-git https://github.com/arialdomartini/oh-my-git

Oh-my-git uses non-ascii font for the symbols. I'm currently using Iterm2 and I can specify a non-ascii font. How will I do configure Hyperterm so it will know how to display the symbols?

**Comment by timneutkens** [comment]
You mean a powerline patched font? Like some ZSH themes use? I personally use [agnoster](https://gist.github.com/agnoster/3712874) which requires such a font. If this is what you are seeking you can set it in `~/.hyperterm.js` under `fontFamily:` like so:
<img width="652" alt="screen shot 2016-07-27 at 21 40 41" src="https://cloud.githubusercontent.com/assets/6324199/17189667/ce685eb4-5442-11e6-9207-9f8509032069.png">

This is the result (git branch icon showing up):

<img width="541" alt="screen shot 2016-07-27 at 21 36 30" src="https://cloud.githubusercontent.com/assets/6324199/17189558/3da550e4-5442-11e6-9d8b-a3c687ba7063.png">

**Comment by timneutkens** [comment]
from having a quick look at the repo of oh my git this will solve you issue 👍

**Comment by Craytor** [comment]
@timneutkens How did you get your vim window to style like that? Mine is still plain -.-

**Comment by timneutkens** [comment]
@Craytor That was an external .vimrc I found on the web. It wasn't so great haha. I now use this:
<img width="652" alt="screen shot 2016-08-21 at 22 23 35" src="https://cloud.githubusercontent.com/assets/6324199/17839630/f049d332-67ed-11e6-82cb-52c8de74e11d.png">

```
syntax on " enable syntax highlighting                           
colorscheme onedark " use onedark atom theme https://github.com/joshdick/onedark.vim                                              
set backspace=indent,eol,start                                   
set nocompatible " fixes some weird bugs in insert mode          
set number " show line numbers                                   
set incsearch " search as characters are entered                 
set hlsearch " highlight matches                                 
                                                                 
" move vertically by visual line                                 
nnoremap j gj                                                    
nnoremap k gk 
```

**Comment by Craytor** [comment]
Ah, thanks!

**Comment by tcasey** [comment]
Is there a way to use 2 different fonts? One for reading and one for symbols. (like iTerm 2)

**Comment by jonnybarnes** [comment]
You can download the [symbols-only font](https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf) from the powerline site, see docs for installing: https://powerline.readthedocs.io/en/latest/installation.html#fonts-installation

Then its a case of setting `.hyper.js` to:
```
module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 18,

    // font family with optional fallbacks
    fontFamily: 'PowerlineSymbols, "Operator Mono", monospace',
    ...
  }
}
```

However I now have an issue where they don’t line up properly:

![screenshot from 2016-12-13 16-07-24](https://cloud.githubusercontent.com/assets/108303/21147860/4764016a-c14e-11e6-8cdb-a41a3f9fa742.png)

**Comment by BirkhoffLee** [comment]
Mine doesn't render correctly too:  
<img width="360" alt="screen shot 2017-01-07 at 2 10 51 pm" src="https://cloud.githubusercontent.com/assets/8148095/21739964/e6d217f6-d4e4-11e6-8c18-f4558ed22f2e.png">

**Comment by vdh** [comment]
In iTerm2 I can fix this font incongruity with the Powerline symbols by tweaking the "Non-ASCII Font" size, e.g. 12pt font size with 11pt Non-ASCII font size. But it doesn't look like Hyper has this option?

**Comment by jrisebor** [comment]
I am also having the alignment issue:
![hyper_misaligned](https://cloud.githubusercontent.com/assets/5555367/22475617/81c81c76-e7ad-11e6-95ca-4913726773b3.png)

**Comment by jonnybarnes** [comment]
I got mine working by patching the font myself, see https://github.com/powerline/fontpatcher

**Comment by Eduruiz** [comment]
:+1:

**Comment by chabou** [comment]
We have merged #1745. This PR could solve this issue.
Can you confirm this?

**Comment by ahmadawais** [comment]
Seems fine now. With a little alignment issue 

![](https://i.imgur.com/q6zRaaH.png)

**Comment by verstoff** [comment]
`termCSS: 'x-row {line-height: initial} .unicode-node {position: relative}',` in config works well as temporary fix. Unicode node style needed for icons like fontawesome used through font fallback.

**Comment by diazgilberto** [comment]
I'm using `hack nerd font` and without other settings other than passing the fonts, everything works fine.

      fontFamily: '"Hack Nerd Font", "Operator Mono", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace'

<img width="653" alt="Screen Shot 2019-09-14 at 9 43 32 PM" src="https://user-images.githubusercontent.com/9165819/64915950-c3862680-d738-11e9-991f-e28ff2180606.png">
