### ISSUE TITLE
Can't type ~ character

### ISSUE THREAD

**Issue by sergiovilar** [zeit/hyper#466]
Hello guys,

I can't type the ~ character in Hyperterm in 0.7.1 as in the previous versions. Could someone help me? Thank you so much!

**Comment by albinekb** [comment]
Hello! 

if you try doing
`echo $LANG`
What do you get?

Probably related to #441

**Comment by sergiovilar** [comment]
@albinekb hello! That's what I get:

```
❯ echo $LANG
en_US.UTF-8
```

**Comment by hoffi** [comment]
Can't type the "~" char as well in the latest version.

I'm using fish and locale is set to german:
```sh
LANG=de.UTF-8
```

**Comment by fecabianchi** [comment]
same here... can't type any of those special characters like ~ ' " `

```
❯ echo $LANG       
en_US.UTF-8
```

**Comment by CodeTheory** [comment]
Is it a foreign keyboard? Possibly related/duplicate of #29.

**Comment by fecabianchi** [comment]
nop, a macbook en_us keyboard. but the layout in osx is U.S. International.

**Comment by sergiovilar** [comment]
Tested with CODE Keyboard US International, Pok3r Keyboard US International and Macbook Keyboard En US both with US International layout and DVORAK-QWERTY, same problem.

**Comment by Rickgbw** [comment]
same for me... chars like ~ ' " not work.
US International key board on macbook 15'
`$LANG` returns: `en_US.UTF-8`

**Comment by sergiovilar** [comment]
Maybe somenone at #214 could help us?

**Comment by albinekb** [comment]
@sergiovilar I'm currently rewriting #214... hopefully done soon ™️ I'll ping you when it's ready to test

**Comment by sergiovilar** [comment]
@albinekb Thank you!

**Comment by MrRio** [comment]
This is a good temporary fix until 214 is ready to land. https://github.com/zeit/hyperterm/pull/521
