### ISSUE TITLE
Configuration option to disable bold fonts

### ISSUE THREAD

**Issue by jerep** [zeit/hyper#475]
This is supported in hterm through `enable-bold` and `enable-bold-as-bright` preferences. It would be nice to have them as configuration options in HyperTerm as I'd prefer bold text shown as bright color instead of bold.

**Comment by chabou** [comment]
Perfect feature for a first plugin!

**Comment by swaj** [comment]
I've created a tiny plugin that at least disables bold.  I've test and it works create for me.  Give it a shot and let me know what you think:

https://github.com/swaj/hyper-nobold

**Comment by MartyGentillon** [comment]
That looks like it should do the trick.

**Comment by ivan-krukov** [comment]
By looking into @swaj's plugin, I just used this in my `.hyper.js`:
```js
termCSS: 'x-row > span { font-weight: normal !important; }',
```
Works like a charm

**Comment by chabou** [comment]
@swaj Do not hesitate to add your perfect tiny plugin to [awesome-hyper](https://github.com/bnb/awesome-hyper)!

Thank you for this plugin ❤️

**Comment by chabou** [comment]
FTR: New config settings to disabling/force bold https://github.com/zeit/hyper/issues/475
