### ISSUE TITLE
Resizing window should update terminal display

### ISSUE THREAD

**Issue by dotlouis** [zeit/hyper#476]
As a GIF is worth a thousand words:

Default OSX terminal:
![terminal-resize](https://cloud.githubusercontent.com/assets/1891109/17207137/6327abc0-54b3-11e6-9e5a-d88946e18f10.gif)

Hyperterm:
![hyperterm-resize](https://cloud.githubusercontent.com/assets/1891109/17207150/6e2a8ba0-54b3-11e6-8e9d-6cd60555cc46.gif)

**Comment by sifex** [comment]
Any update on this?

**Comment by matheuss** [comment]
Bumped to `high` since this is very annoying 😛

**Comment by realogicbcleary** [comment]
I think this issue is related to an issue I noticed with panes (#56), so +1.  

> [...w]hen my window manager (amethyst) shrinks Hyper, it seems like it doesn't redraw, so the lower pane gets hidden. My work-around is to do a quick CMD+SH+D + CMD+W, but that hinges on remembering a pane just got hidden.

**Comment by sifex** [comment]
@realogicbcleary Yea, because Hyper uses divs/containers (I'm not too sure, but some sort of HTML Block) for each line. Might have a look how to reflow before Christmas.

**Comment by realogicbcleary** [comment]
@sifex Mine isn't really reflow issue -- rather a more basic `window.onResize(redraw)` type thing -- but I think it'll be resolved as a subset of this issue.

**Comment by wmertens** [comment]
@realogicbcleary I think your issue is separate. This reflow issue is about redrawing all the visible lines so they match the screen width, as well as storing the history in such a way that that is possible. Your issue sounds like a missing resize event…

**Comment by virtualbeck** [comment]
Is there still a pulse on this issue?

**Comment by malonehedges** [comment]
Haven't spent much time with the source code here, but it seems like this could be fixed using the `line-overflow="true"` property on `x-row`s.

![screenshot](http://i.imgur.com/WnyHM0p.png)

**Comment by liwsakilive** [comment]
If OS windows 10 ?

**Comment by baptistebriel** [comment]
+1

**Comment by yjkimjunior** [comment]
+1

**Comment by DreierF** [comment]
+1

**Comment by malonehedges** [comment]
@matheuss is there any development on this? Accepting PRs?

**Comment by epan** [comment]
@malonehedges the issue is labeled `Priority: OMG Maximum` and `Status: Help Wanted` can you save us 💃

**Comment by tjfwalker** [comment]
> _[pokes issue #476 with a stick]_
> I can't tell; is it dead or alive. It's not moving.

ヾ(×_× ) ﾂ

**Comment by malonehedges** [comment]
To clarify, not currently working on this. Don't have the time right now

Still very much in support of this issue though, this is a deal killer for me when I get a stacktrace logged in a small window.

**Comment by controversial** [comment]
Is this planned, even with xterm in Hyper 2.0?

**Comment by dontsave** [comment]
Checking out Hyper for the first time and I have to say that while it's a very cool terminal, it's kind of shocking that it fails to properly resize previous output. It would be great if this got fixed

**Comment by bwobst** [comment]
I'd love to use Hyper but not having this feature is a deal breaker.

**Comment by gixlg** [comment]
> I'd love to use Hyper but not having this feature is a deal breaker.

Same here.

**Comment by ClearCarbon** [comment]
I think hyper is beautiful terminal and I've been watching this issue for a long time, its the last thing I'd need fixing before switching to it.

**Comment by jmordica** [comment]
Love Hyper! Don't love window resize issue.

**Comment by jubby2000** [comment]
I was forced to move to iTerm because of this issue - but would love to come back. Any progress here?

**Comment by ppot** [comment]
@jubby2000 this is now integrated onto xtemrjs which will be available into future releases.

**Comment by nervewax** [comment]
After updating to 3.0.0 it's looking like this is now fixed, thanks to whoever did the hard work and sorted this 👌✨

**Comment by gabrielseibel1** [comment]
Using 3.0.0 and the bug is still there 😞

**Comment by ppot** [comment]
@gabrielseibel1 did you install or update?

**Comment by gabrielseibel1** [comment]
@ppot Fresh install. First time ever using Hyper.

**Comment by gabrielseibel1** [comment]
@ppot Come to think of it, my bug may be slightly different. I'll try to diagnose it more precisely tomorrow, maybe add a gif as OP did.

**Comment by gabrielseibel1** [comment]
@ppot I actually have #1566, not this one.

**Comment by bwobst** [comment]
This is fixed now in 3.0.2.
