### ISSUE TITLE
Can't paste multiple times.

### ISSUE THREAD

**Issue by lucasmouilleron** [zeit/hyper#479]
If pasted once, it is not possible to paste again, unless return is stroked.

**Comment by chabou** [comment]
I can't reproduce. What is your config ?

**Comment by chabou** [comment]
Ok. Reproduced but not systematically

**Comment by chabou** [comment]
Space key seems to unlock paste feature too

**Comment by lucasmouilleron** [comment]
I think it is related to hyperterm-blink.
Can't reproduce if not activated.

@chabou, do you have the hyperterm-blink plugin ? I will leave the ticket open otherwise.

**Comment by chabou** [comment]
I have only a modified version of hyperpower plugin. I deactivated it and I can still reproduce this issue.

I'm using zsh (with oh-my-zsh) but if I launch bash with no configuration, I can't reproduce

**Comment by chabou** [comment]
Reproduced !!
It is related to my zsh plugin https://github.com/zsh-users/zsh-syntax-highlighting
Changing color of the first past (if it is a known command green, red otherwise) may disturb the second past. If I put a space after that, I could paste. I think it is related to color changing initiated by hterm.

**Comment by matheuss** [comment]
Reproduced! Can confirm that is related to the plugin (man this is an awesome plugin, thanks for sharing!).

**Comment by ekmartin** [comment]
Hm, this happens for me too but I don't use the zsh-syntax-highlighting plugin (happens without any plugins as well). Might be something else bundled with oh-my-zsh though.

**Comment by lordgiotto** [comment]
Can confirm it happens also to me with zsh 5.2 and oh-my-zsh.

**Comment by matheuss** [comment]
Yo y'all, could you test on latest master? I might have introduced a fix via #1006 👌

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
