### ISSUE TITLE
SECURITYSESSIONID environment variable

### ISSUE THREAD

**Issue by pwnall** [zeit/hyper#482]
This is the equivalent of #346 for the SECURITYSESSIONID variable.

The following thread shows that it's set up on OSX's Terminal, and not having it set has negative implications.
https://github.com/tpope/vim-fugitive/issues/108#issuecomment-2056776

The following Google Books result says that SECURITYSESSIONID is used by securityd and its use is undocumented. 

https://books.google.com/books?id=jfMqCgAAQBAJ&pg=PA33&lpg=PA33&dq=SECURITYSESSIONID+environment+variable&source=bl&ots=YctPlHiBVn&sig=ZmubroMHz_L1Y2FpzTsSqFyEq3o&hl=en&sa=X&ved=0ahUKEwj3rLLM1ZbOAhVCzWMKHckQCDU4ChDoAQgbMAA#v=onepage&q=SECURITYSESSIONID%20environment%20variable&f=false

Is there any chance this can be forwarded from somewhere?

I'm sorry I can't provide more details, and thank you for hyperterm!

**Comment by ekmartin** [comment]
Hm, seems to be correctly set for me in version 0.7.1?

![image](https://cloud.githubusercontent.com/assets/3536982/17222912/b2490e8c-54fa-11e6-94c7-cf067539b8dd.png)

**Comment by matheuss** [comment]
`v0.7.1` here 
<img width="316" alt="screen shot 2016-07-28 at 2 39 05 pm" src="https://cloud.githubusercontent.com/assets/4721750/17222991/10320b04-54d1-11e6-83f1-cee27e5a7fc4.png">

**Comment by rauchg** [comment]
I don't have it either (bash). How are we supposed to set it ?

**Comment by TooTallNate** [comment]
I _do_ have this by default. Not sure where it comes from, haha.

**Comment by rauchg** [comment]
Heisenv

**Comment by TooTallNate** [comment]
It's even the same value as @ekmartin: `186a7` (not much for an ID…)

**Comment by albinekb** [comment]
Mine is also the same `186a7` in hyperterm & iterm, but nothing is set in terminal..

**Comment by chabou** [comment]
Mine is `186bf` in Hyper and it is the same in Terminal.app iTerm2.

Feel free to reopen if I missed something
