### ISSUE TITLE
Rogue style being applied

### ISSUE THREAD

**Issue by jbw91** [zeit/hyper#483]
I'm writing a light theme for hyperterm (https://github.com/jbw91/hyperterm-material-light) and things are going well, however I've run into an issue where when running `git diff` and scrolling through the diff to the end, where there should be the `(END)` indicator, it is actually all white, therefore blending in with my background. In inspecting that element in the dev tools, I notice there is a `style="color: rgb(250, 250, 250);"` attribute being applied to that element. I can't see anywhere why it would be doing that, it seems to me it should follow the foreground text color. See the screenshot below:

![screen shot 2016-07-28 at 11 46 47 am](https://cloud.githubusercontent.com/assets/5883616/17223318/421ea8ba-54b9-11e6-8fc7-b0679f1f62eb.png)

My code is in this file: https://github.com/jbw91/hyperterm-material-light/blob/d0c3844f52a5b4e51e1d608c9b2737a15fe6fa70/index.js

I can't see anywhere I might have input that style myself, so it seems to me it may be a bug in Hyperterm.

**Comment by matheuss** [comment]
I'm using [hyperpanic](https://github.com/seripap/hyperpanic)
<img width="876" alt="screen shot 2016-07-28 at 2 53 44 pm" src="https://cloud.githubusercontent.com/assets/4721750/17223488/2947246a-54d3-11e6-90d5-c4d277b6285a.png">
🤔

**Comment by matheuss** [comment]
I installed your theme here (from your `master`) and I got the same results as you:
<img width="896" alt="screen shot 2016-07-28 at 3 05 37 pm" src="https://cloud.githubusercontent.com/assets/4721750/17223900/f7f151b8-54d4-11e6-8d07-698a8bc8ac78.png">

**Comment by jbw91** [comment]
Just noticed the same thing in, for example, `nano` with their commands along the bottom, it seems to have a white color style forcibly applied.

![screen shot 2016-07-28 at 2 20 05 pm](https://cloud.githubusercontent.com/assets/5883616/17228021/7c1ded18-54ce-11e6-865c-32a742042bdc.png)

**Comment by chabou** [comment]
I tried your theme and it seems to be fixed
![capture d ecran 2017-04-20 a 01 30 05](https://cloud.githubusercontent.com/assets/4137761/25206552/ee6a19bc-2568-11e7-8683-3cdd7975b2fb.png)

Feel free to reopen.
