### ISSUE TITLE
Improve terminal process name / title extraction

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#49]
Our current method is kinda flawed :\

**Comment by cseelus** [comment]
Yeah … when using NeoVim (or Vim) (both installed via Homebrew) for example, it constantly jumps between `bash`, `Python`, `Ruby` and `nvim`.

**Comment by trashhalo** [comment]
@rauchg how are you extracting the process name? I have been trying to figure out how how to override it.

**Comment by lkzhao** [comment]
@rauchg 
This plugin done by @parro-it seems pretty good at getting the title. 
### [hyperterm-title](https://github.com/parro-it/hyperterm-title/blob/master/index.js)
It grabs the title used by hterm and put it as the tab title. 
Can you take a look? Maybe this should be the default behaviour.

**Comment by parro-it** [comment]
@rauchg: if you'll decide to use my plugin way to set the title as the default, I will be happy to help with a PR

**Comment by rauchg** [comment]
@parro-it my understanding was that only a few programs use the escape code to set the title. Is that not the case?

**Comment by rauchg** [comment]
@parro-it if that technique is sufficient (not sure why I had concluded it wasn't), I would totally love a patch that includes your approach and removes `ps` polling

**Comment by parro-it** [comment]
> @parro-it my understanding was that only a few programs use the escape code to set the title. Is that not the case?

Not at all... E.g. I use zsh with [pure prompt](https://github.com/sindresorhus/pure), it set the title to the `cwd`. VI set it to the name of editing file, etc..

> @parro-it if that technique is sufficient (not sure why I had concluded it wasn't), I would totally love a patch that includes your approach and removes ps polling

I will happily do one soon... :smiley:

**Comment by rauchg** [comment]
@parro-it you'll be improving the performance and UX of Hyper significantly 🙏 thank you, looking forward to it

**Comment by rauchg** [comment]
Also @lkzhao thanks for bringing this to my attention

**Comment by parro-it** [comment]
> @parro-it you'll be improving the performance and UX of Hyper significantly :pray: thank you, looking forward to it

You're welcome, I hope to do a good job :smile:. Process polling is so expensive in term of performance?

**Comment by ppot** [comment]
@matheuss  #892 closed this i think!

**Comment by matheuss** [comment]
Thank you @ppot 😄
