### ISSUE TITLE
Remove `localPlugins` config property in favour of automatic `plugins`

### ISSUE THREAD

**Issue by leo** [zeit/hyper#496]
Instead of using a separate property for local plugins, we should just add the local ones to `plugins` as well and every time the config gets reloaded, HyperTerm will [search for the plugin](https://github.com/zeit/hyperterm/issues/498) and load it if it's there.

If not, it will get installed from npm (or where ever it comes from) automatically.

**Comment by CodeTheory** [comment]
What happens if there's a plugin of the same name, accidentally?

**Comment by leo** [comment]
In this case, you need to rename your local one. All in all, we should enforce this either way because having two plugins of the same name in the config just confuses everyone who's trying to debug a bug that the user discovered and even the user itself.

**Comment by albinekb** [comment]
Confusing? why?

**Comment by leo** [comment]
Because it's not possible to identify the source of certain code pieces then. As an example, I'm more that sure that we'll add a way to allow developers to find out where code comes from via the inspector. And in cases like this, you would see two packages with the same name and that simply isn't helping at all.

**Comment by leo** [comment]
Not clear enough!
