### ISSUE TITLE
Shortcuts don't work in Linux Mint with Cinnamon	

### ISSUE THREAD

**Issue by dleitee** [zeit/hyper#499]
I'm trying to use the shortcuts, example, ctrl + n or ctrl + k, and nothing happens.

What can be the cause?

Thank you.

-

HyperTerm 0.7.1
Electron 1.2.8
linux x64 3.19.0-32-generic

**Comment by reflog** [comment]
same goes for plugin shortcuts. I used visor plugin, added Ctrl-` shortcut and it doesn't respond

**Comment by albinekb** [comment]
That's because it only gets sent to the terminal
https://github.com/zeit/hyperterm/blob/master/lib/hterm.js#L32
I'm working on a fix for this, hopefully done soon 👼

**Comment by brycepj** [comment]
Not unique to your distro (Mint) as far as I can tell -- I'm experiencing the same thing on Ubuntu 14.04.

**Comment by flybayer** [comment]
You currently have to add `Super` to key combo for it to work.

**Comment by flybayer** [comment]
@CodeTheory this is a duplicate of #274
