### ISSUE TITLE
Per plugin configuration and plugin sandbox file system

### ISSUE THREAD

**Issue by FelipeRosa** [zeit/hyper#523]
Hi, I'm building a plugin for loading iTerm2 themes into HyperTerm. I'm wondering if it's possible to save and have a configuration file specific to my plugin. Also if I'm able to access any part of the file system from my plugin's code (like a plugin sandbox or something like that).

Also, suggestions about how to proceed are very welcomed.

Thanks

**Comment by albinekb** [comment]
That's a great plugin idea!

If you need help or want to ask questions about building a plugin, i would suggest you to join the community slack channel: [![Slack Channel](https://zeit-slackin.now.sh/badge.svg)](https://zeit.chat/)

I'm happy to answer any questions over there and help you get started in the right direction!

And to answer your question: There's no sandbox that you need to worry about, your plugin can access the filesystem. *Maybe something we should look into doing?*

About plugin config, I've seen project use an object in the user's regular config file `~/.hyperterm.js`, and some (for example [hyperambient](https://github.com/jamox/hyperambient) that has it's own config file at `~/.hyperambient.json`

**Comment by chabou** [comment]
Answered
