### ISSUE TITLE
Option to disable lion style fullscreen windows on OSX/macOS

### ISSUE THREAD

**Issue by jalvarado91** [zeit/hyper#526]
Currently going into fullscreen mode on OSX does a zoom animation and start a new desktop. 

A desired workflow, however, might be to have a semi transparent background on hyperterm and/or shortcuts to activate it, and have it be full screen 'on top' of the current content of the screen.

iTerm has this option, but I'm not sure if it's possible to do this with the electron windows.

**Comment by CodeTheory** [comment]
I don't think changing the default OS experience is a good idea, nor integrating a feature such as this into the main app. I assume this feature would only be used by a few and suits a plugin more, since that's exactly what plugins are for. 

There might even be a plugin for it somewhere already! 😄

**Comment by kevinSuttle** [comment]
FWIW, I use it in iTerm all the time.

**Comment by karldanninger** [comment]
Yep, would like to see this at some point. Overlayed over sublime would be the best 👍

**Comment by trungdq88** [comment]
This is the only reason I'm have not used Hyper, please make this happen.

**Comment by jalvarado91** [comment]
I've been trying to do some research on the side of how iTerm does this. I haven't really done Cocoa development but it looks like they use a setting for making and NSWindow that makes the fullscreen not open a new space like Lion though I can't really follow much from there. 

[Probably relevant iTerm implementation...](https://github.com/gnachman/iTerm2/blob/7d1cd8b225e2ffbd4ba54b894232f0c11c48aeca/sources/iTermWindowImpl.m#L149)

This would probably have to be added to electron itself, and then used in hyper, but any pointers from anyone would be cool.

**Comment by ppot** [comment]
@jalvarado91 This is diffidently electron related. I suggest you make an issue directly to electron and link it to this curent issue

**Comment by zachflower** [comment]
Quick update on this issue: simple (pre-Lion) fullscreen support has just been added in electron/electron#10254 and will most likely be released in Electron 1.8.x. Electron 1.8.0 is still in beta, so it will probably be a little while before this feature can actually make it into Hyper, but I thought some people would be happy to hear that it's now at least one step closer ☺️
