### ISSUE TITLE
Improvement: sending text (apple script support)

### ISSUE THREAD

**Issue by andrewrech** [zeit/hyper#540]
Hello,

Are there any plans to add a mechanism for sending text from a text editor (such as Apple script support on masOS)?

Thanks

**Comment by princed** [comment]
It would help support opening from Alfred as well.

**Comment by sindresorhus** [comment]
Would need to be supported in [Electron](https://github.com/electron/electron) first. Open an issue about adding AppleScript support there. Electron could maybe piggyback on Chrome's AppleScript support.

**Comment by r3volution11** [comment]
Electron contributors say it's best done through its on node module (https://github.com/electron/electron/issues/4418). There's one now for Electron over at https://github.com/dkfiresky/osap.

**Comment by seyonv** [comment]
This would be a killer feature. Need to switch back to regular old terminal because of this unfortunately :(. Unless there's an ability to execute "do script" commands (so multiple tabs can have code running and executed via applescript)

**Comment by albinekb** [comment]
This is doable as a plugin 😎

**Comment by spencermountain** [comment]
hi folks, here's how i did a work-around.
```osascript
tell application "Hyper"
	activate
	tell application "System Events"
		keystroke "npm run test"
		key code 36  #(presses enter)
	end tell
end tell
```
i couldn't figure-out how to listen for apple-events from node. I think it may involve some funky cocoa stuff maybe. @albinekb unless you know some fancier moves?

**Comment by KingScooty** [comment]
This is a good workaround until native support is here:

https://www.alfredforum.com/topic/10444-change-default-terminal-to-hyperis/

```applescript
on alfred_script(q)
	if (text 1 thru 2 of q) is equal to "cd" then
		do shell script "open -a Hyper " & text 4 thru -1 of q
	else
		do shell script "open -a Hyper ~"
		set appOpen to false
		set nbrOfTry to 0
		delay 0.5
		repeat
			try
				tell application "System Events"
					if exists (window 1 of process "Hyper") then
						set appOpen to true
						exit repeat
					end if
				end tell
			end try
			set nbrOfTry to nbrOfTry + 1
			if nbrOfTry = 20 then exit repeat
			delay 0.5
		end repeat
		if appOpen then tell application "System Events" to keystroke q & return
	end if
end alfred_script
```
