### ISSUE TITLE
Search feature is missing

### ISSUE THREAD

**Issue by rwngallego** [zeit/hyper#541]
I really love hyperterm, do you maybe have plans to add a Search functionality? It would be really nice to have highlighting of the search occurrences also.
## 

HyperTerm 0.7.1
Electron 1.2.8
darwin x64 14.5.0

**Comment by darol100** [comment]
cmd + f should open an windows where the user can search.

**Comment by damienh** [comment]
tried cmd + f but nothing happens.

**Comment by shrift** [comment]
This feature is probably a make or break feature for me. Until I have search, I'll probably stick with OSX's Terminal. :(

**Comment by matheuss** [comment]
Bumped to `Priority: High` since it's a feature available in almost any app that displays some text 😛

**Comment by shrift** [comment]
Thanks!

**Comment by morgz** [comment]
+1

**Comment by ronvenna** [comment]
+1

**Comment by yongzhihuang** [comment]
+9001

**Comment by aleclarson** [comment]
Can we lock this thread? I only want to ping'd when the search feature is added. 😜

**Comment by matheuss** [comment]
zeit.chat is available for further discussion 😄

**Comment by albinekb** [comment]
@timneutkens is working on this 👼

**Comment by chabou** [comment]
There is a PR: https://github.com/zeit/hyper/pull/1793
And there is a plugin too: https://www.npmjs.com/package/hyper-search
