### ISSUE TITLE
Emoji dialog broken 

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#55]
![image](https://cloud.githubusercontent.com/assets/13041/16601973/5c8c520c-42c5-11e6-9ca4-c99f27db9beb.png)

this should render inline to the caret.

**Comment by kurisubrooks** [comment]
Japanese and Chinese IME are also broken, same issue as above.

**Comment by CodeTheory** [comment]
I believe this now works

**Comment by grafa** [comment]
Hi guys,

I can't google out any cheat sheet of hyper term shortcuts so I will try my luck here (I'm sorry). How do I open up the emoji dialog? Also if there is keyboard cheatsheet for Hyper, please refer it to me.

Thank you a lot.

**Comment by kurisubrooks** [comment]
On Mac, Command + Control + Space.

**Comment by grafa** [comment]
Thank you. Any chance on Linux?

**Comment by kurisubrooks** [comment]
Most Linux distros don't have this built in unfortunately. On Ubuntu, there
is an application called EmojiOne Picker, which is quite useful.
Unfortunately that's all I know of for alternatives on Linux.
