### ISSUE TITLE
Resizing window causes duplication of lines

### ISSUE THREAD

**Issue by dka09** [zeit/hyper#554]
When you resize the window, the lines are duplicated but when the window is made wide enough it goes back to one line.

![resize windows causing line issue](http://i.imgur.com/pE4LiXX.gif)

**Comment by ssdong** [comment]
Happens on my OSX Yosemite as well, any one can try on other platforms ?

**Comment by ppot** [comment]
It happens on Iterm2 with zsh also on terminal and the team decided the issue as wont fix.

**Comment by CrashyBang** [comment]
Happening on Ubuntu 16.04

**Comment by chabou** [comment]
I confirm that it happens on Terminal.app
