### ISSUE TITLE
Email renders website

### ISSUE THREAD

**Issue by aaronagray** [zeit/hyper#557]
![example](https://cloud.githubusercontent.com/assets/1110019/17383316/8c5da128-5992-11e6-95fa-852953ab8b48.gif)

I'm not sure if this is expected behavior, but it certainly surprised me when I ran `$(git config user.email)`.

**Comment by MrRio** [comment]
This seems to be any web address that's entered. 

This is a potential security flaw as the page has full access to your node APIs.

**Comment by rauchg** [comment]
@MrRio the `<webview>` should not have access to any node APIs.

**Comment by aaronagray** [comment]
@MrRio The website rendering is a feature. Your security concern was addressed in this issue: https://github.com/zeit/hyperterm/issues/77.

**Comment by freebroccolo** [comment]
@rauch @aaronagray I think the point about `<webview>` not having access to node APIs is incorrect. See the documentation here:

```
For security purposes, webview can only be used in BrowserWindows that have nodeIntegration enabled.
```

In fact, as of electron `1.1.1`, the `<webview>` tag is disabled when `nodeIntegration` is turned off. See [here](https://github.com/electron/electron/pull/5559). There was some discussion about the implication of this [here](https://github.com/electron/electron/issues/6484).

As far as I'm aware, the only real workaround at the moment is to leave `nodeIntegration` enabled but run a [preload script](https://github.com/browserhtml/browserhtml/blob/master/electron-preload.js) to remove the node modules. This is what browserhtml is currently doing. But as mentioned in the issue above, that doesn't fully solve the problem yet.

**Comment by MrRio** [comment]
I jumped the gun a bit on the security concern, apologies. 

This feature feels a bit like a bug to me as I need to hard reload once I'm viewing the page. 

Why would I want this to happen when I could just type 'open google.com'

**Comment by chabou** [comment]
I can't reproduce
Feel free to reopen
