### ISSUE TITLE
Support for Browser mode?

### ISSUE THREAD

**Issue by ecki** [zeit/hyper#561]
Is it planned to also offer a real web page (statically served to browser) version. Maybe with a SSH-via-WebSocket-Tunnel backend from the browser to a destination host? Is it even possible to get HyperTerm runnin in a JS engine inside the browsers?

Especially for the cloud user happiness it would be great to have a zero-install simple terminal window to an hosted server or even command line interface (like for example Apache Karaf offers OSGi commands via SSH).

**Comment by abhishiv** [comment]
Related: Has anyone tried running the UI code in the browser? Does it break?

**Comment by xvalentino** [comment]
I would expect it's possible since there are packages like this https://www.npmjs.com/package/electron-run-in-browser but idk

**Comment by prashanthmadi** [comment]
@xvalentino do you have a sample of hyper running with electron-run-in-browser

**Comment by chabou** [comment]
I think you misunderstood what electron-run-in-browser is doing.

**Comment by xvalentino** [comment]
Oh you're right, electron-run-in-browser is unrelated.

**Comment by gordomium** [comment]
With browser mode shall be awesome!

**Comment by ratacat** [comment]
Has anyone come up on this front?  I'd love to be able to pop Hyper in a browser window with a websock connection to my server. This would be incredible!

**Comment by martinezhermes** [comment]
Looking forward for this +1

**Comment by Stanzilla** [comment]
No plans atm
