### ISSUE TITLE
Session serialization/storage/restoration

### ISSUE THREAD

**Issue by mike-engel** [zeit/hyper#567]
It'd be really nice if when hypertyerm quit, the current sessions were stored somehow, somewhere, so that when hyperterm restarted, they would be restored. This is most helpful during computer restarts or accidental quits. This is also another handy feature that iTerm has.

**Comment by ppot** [comment]
@matheuss This is my PR #945

**Comment by Kentzo** [comment]
@ppot Thank you a lot of that contribution!

My 2 pieces: Terminal.app on macOS along other things like restoring CWD, allows user to customize the process by providing the `TERM_SESSION_ID` into every shell process. If user then quits app with active session, on the next launch all shells will be re-initialized with the same `TERM_SESSION_ID`.

That allows a user to do actually customize the restoration process by doing the following:

1. User can define the `shell_session_save_user_state` function
2. Terminal.app calls that function on exit (as simple as `trap ... EXIT`)
3. In the implementation user dumps whatever shell commands he wishes to execute to `SHELL_SESSION_FILE` (which is _~/.bash_sessions/$TERM_SESSION_ID.session_ for bash)
4. On the next launch that file is sourced and then deleted

You can find the very detailed implementation of that logic in _/etc/bashrc_Apple_Terminal_.

It opens a lot of possibilities for customization by requiring very littler from Hyper itself: just provide some kind of unique ID which it should generate anyway.

**Comment by ppot** [comment]
@Kentzo I like that idea.

**Comment by Stanzilla** [comment]
let's continue here https://github.com/zeit/hyper/pull/945

**Comment by abhishek71994** [comment]
Is this still worked on?
