### ISSUE TITLE
hyperterm crashes when opening new window, and closing that window

### ISSUE THREAD

**Issue by nhemsley** [zeit/hyper#570]
I am running on ubuntu 16.04, via npm start

If I create a new window (via Shell-> New Window, ctrl-n doesnt work for some reason), and then close that new window, either by clicking window close, or typing ctrl-d, hyperterm exits all open windows.

The output as follows, with the 'session not found' appearing after closing the window

> hyperterm@0.7.1 start /home/nick/code/hyperterm
> electron app

running in dev mode
electron will open file:///home/nick/code/hyperterm/app/index.html
ignoring auto updates during dev
ignoring auto updates during dev
session not found by e2044dcc-7588-415d-9a54-9cc832b364af
session not found by null
session not found by null

**Comment by nhemsley** [comment]
If  there is  more verbose logging that I can enable (electron debugging?), I will dig into this more.

Cheers

**Comment by efegurkan** [comment]
This happens on [here](https://github.com/zeit/hyperterm/blob/9d65cb74c09b7a24e0a08195fb73aaef2db2fdad/app/index.js#L174-L206) as a start point for those who wants to play around

**Comment by chabou** [comment]
Probably fixed.
Feel free to reopen
