### ISSUE TITLE
Distinguish plugins and themes

### ISSUE THREAD

**Issue by dj-hedgehog** [zeit/hyper#582]
Currently the best way to look for relevant/popular themes or plugins is the npms.io search https://npms.io/search?term=hyperterm.

There is no separation between themes and plugins. While themes are ordinary plugins as well most only use the theming capabilities. 

If you're looking especially for plugins extending/altering the functionality of Hyperterm you've got to browse through all the 1xx available plugins.

~~There'll likely be some kind of plugin directory or plugin to browse plugins / themes efficiently soon.~~
There will be a plugin directory at https://plugins.hyperterm.org.

My proposal is that (similar to Atom) **plugins and themes** should add:

```
  "engines": {
    "hyperterm": ">=0.7.0 <0.7.1"
  }
```

and another key `type` with the value `theme` or `plugin` to their respective `package.json`
This way an index of plugins/themes can be built much easier.

**Let's discuss this here!**

**Comment by sindresorhus** [comment]
Could also use the `keyword` field: `hyperterm-plugin` and `hyperterm-theme`.

**Comment by dj-hedgehog** [comment]
Is it possible to search the NPM API by keywords? I can't find any documentation whatsoever.

**Comment by sindresorhus** [comment]
@dj-hedgehog The npm API is both undocumented and awful. I did at some point make a module for it: https://github.com/sindresorhus/npm-keyword

**Comment by iamstarkov** [comment]
* [keyword/hyperterm](https://www.npmjs.com/browse/keyword/hyperterm)
* [keyword/hyperterm-plugin](https://www.npmjs.com/browse/keyword/hyperterm-plugin)
* [keyword/hyperterm-theme](https://www.npmjs.com/browse/keyword/hyperterm-theme)

**Comment by iamstarkov** [comment]
i would like not to distinguish them in any specific way. right now hyper's api surface is so small clean, so separate apis for themes and plugins will hurt it

**Comment by iamstarkov** [comment]
pkg's keywords should be enough

**Comment by timothyis** [comment]
Closing this now that we have a Store for [plugins](https://hyper.is/plugins) and [themes](https://hyper.is/themes)!

Thanks for the issue (no matter how long ago)
