### ISSUE TITLE
String longer than terminal width: ZSH buggy behaviour

### ISSUE THREAD

**Issue by lordgiotto** [zeit/hyper#597]
Hi guys,
if i try to paste a string longer then the terminal width (or in general insert it in one step such dropping a file with a long path onto the terminal after #559), in ZSH produce a strange behaviour: 
**I can only see the last portion of the string and, if I backspace, i can go to the previous line with the cursor.** 

I attach some gif to explain it clearly: i used the following invented long path `/Users/lord/Users/a/very/very/very/long/PathTo/a/file/or/in/general/a/very/longString.png`.

Expected behaviour (with bash):
![bash](https://cloud.githubusercontent.com/assets/5115382/17518178/1bbfa7c2-5e47-11e6-8def-7858a3021e24.gif)

Buggy behaviour (with zsh):
![zsh](https://cloud.githubusercontent.com/assets/5115382/17518195/3037c04a-5e47-11e6-979a-19a592dfca32.gif)

**Comment by matheuss** [comment]
I used to have this bug all the time but now I can't reproduce it anymore 😰 
![long-string](https://cloud.githubusercontent.com/assets/4721750/17531224/5c015c4a-5e51-11e6-8c7a-2569a020f879.gif)

**Comment by aniket-deole** [comment]
I got this same behavior in Hyperterm and iTerm2 as well.
So, I think this may not be related to Hyperterm.

**Comment by lordgiotto** [comment]
Update zsh to version 5.2 changed slightly the issue, but still behaves in a strange way: if i try to deletebackspace all the text, two letters remains there.
![zsh-notstillperfect](https://cloud.githubusercontent.com/assets/5115382/17535081/c61a1d48-5e8c-11e6-86c8-06d1e70113ed.gif)

**Comment by lordgiotto** [comment]
it's a locale related probmel #441 and will be fixed by #605
