### ISSUE TITLE
Can Hyperterm support some of the ideas and innovations from Termkit?

### ISSUE THREAD

**Issue by booc0mtaco** [zeit/hyper#599]
For those who've never heard of [TermKit](https://github.com/unconed/TermKit), [here's an introduction](https://acko.net/blog/on-termkit/).

It would be interesting to see plugins for file type handling, and handling other media that can be previewed in a web context. Could Hyperterm's Plugin API handle some of this functionality? What changes would have to happen in the app to allow for this type of customization?

**Comment by kevinSuttle** [comment]
See also: http://xiki.org/

**Comment by Stanzilla** [comment]
Please file issues for individual feature requests.
