### ISSUE TITLE
Code signing/notarization issue on macOS Big Sur

### ISSUE THREAD

**Issue by plygrnd** [zeit/hyper#6003]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  macOS Big Sur 11.6
- **Hyper.app version**: 3.1.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: Vanilla/fresh install
- **Relevant information from devtools**: N/A
- **The issue is reproducible in vanilla Hyper.app**: N/A

## Issue

When I try open Hyper after freshly installing it from GitHub, I receive the following error:

```
“Hyper.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
```

Appears to be a code signing issue in 3.1.3; on Big Sur (11.6), the OS doesn't recognize the signing cert or developer profile used to sign Hyper, so the app won't open unless I work around Gatekeeper (right-click app, click "Open").

I verified that this isn't due to Hyper being 32-bit:

```
:: Hyper.app/Contents/MacOS » file Hyper
Hyper: Mach-O 64-bit executable x86_64
```

**Comment by LabhanshAgrawal** [comment]
Not yet, working on something, will release with that
