### ISSUE TITLE
New Version available pop-up -> No option to disable the notification

### ISSUE THREAD

**Issue by I2evard** [zeit/hyper#6023]
There is no option to remove the notification saying that there's a new version of Hyper. 

Quite often it is blocking some lines and feels really annoying. The fact that I can't disable it is also annoying... Could it be set has a pop-up only when the app starts? Still, with the option to ignore the new update? 

---

- **Hyper version**: undefined "3.1.3"
- **OS ARCH VERSION:** win32 x64 10.0.19043
- **Electron:** 13.2.3  **LANG:** undefined
- **SHELL:** undefined   **TERM:** undefined
<details><summary><strong>.hyper.js contents</strong></summary>
</details>

**Comment by LabhanshAgrawal** [comment]
I guess we do need to update the color, it's quite difficult to see
