### ISSUE TITLE
Scroll lag with multiple panes in neovim

### ISSUE THREAD

**Issue by koekeishiya** [zeit/hyper#603]
When having more than one pane (split) open in neovim, scrolling becomes extremely laggy. If I close one of the panes, everything returns back to normal.

~~Also, when just scrolling in general, the new line that would appear, is incorrectly placed at the top of the buffer for a very short amount of time before it seems to be moved back to the end of the buffer, where it should appear. (The reverse also happens when scrolling in the opposite direction.)~~ This part appears to be fixed in version 1.0.0

I am using the `hyperclean` plugin and padding `15px 15px`.

Edit: I'm running on OSX El Capitan 10.11.6

**Comment by CrashyBang** [comment]
Experiencing this also on Ubuntu 16.04.

However I receive scroll lag regardless of the number of panes 1, 2 or more.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
