### ISSUE TITLE
Renderer forgets how big the window is

### ISSUE THREAD

**Issue by heshamsalman** [zeit/hyper#606]
![screen shot 2016-08-10 at 5 55 17 pm](https://cloud.githubusercontent.com/assets/3388381/17572670/cc884c1c-5f23-11e6-9d10-1db7727863c6.png)

After using a window for a while, this starts happening. Closing the window and re-opening it fixes it.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
