### ISSUE TITLE
Adware OSX.Bundlore Bundled in Hyper?

### ISSUE THREAD

**Issue by vallieres** [zeit/hyper#6061]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **Big Sure 11.6.1**: 
- **Hyper 3.1.4 (stable)**: 
- **No config, just started the app**: 
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue
So I just installed Hyper :
- I got it from https://hyper.is/ (the M1 download button)
- moved the app to my Applications folder
- Launched it
- I clicked on the menu`Install Hyper CLI command in Path`
- And I get this popup from CleanMyMac X background agent:

![CleanMyMac X Popup](https://user-images.githubusercontent.com/182217/139435993-09fbe314-4742-44ea-b89a-74ea4e039a9e.png "CleanMyMac X Popup")

The adware OSX.Bundlore was detected.

When opening up CleanMyMac X, you see this:

![CleanMyMac X Details](https://user-images.githubusercontent.com/182217/139436047-e57fcc4b-bcdd-49af-9c1b-0188b533c0d5.png "CleanMyMac X Details")

Is that a false positive or a legitimate issue in the app bundle?

**Comment by LabhanshAgrawal** [comment]
Looks like a false positive
```"Bundlore" is an installer which bundles legitimate applications with offers for additional third party applications that may be unwanted by the user.```
From what I get, this is trying to indicate that one thing is installing other things too. Which in our case is the cli command.
