### ISSUE TITLE
LANG and LC_CTYPE env variables cause many issues with unicode chars

### ISSUE THREAD

**Issue by lordgiotto** [zeit/hyper#607]
Hyperterm sets LANG variable in [`app/session.js`](https://github.com/zeit/hyperterm/blob/master/app/session.js#L30), but the way we are doing it creates some problems. 

Since LC_CTYPE inherits from LANG variable, if the locale name returned by app.getLocale() is not an XPG syntax described by gnu.org [here](https://www.gnu.org/software/libc/manual/html_node/Locale-Names.html) (`LANGUAGE_TERRITORY.CHARSET`) and it's not found in locales list `locale -a`, shell will fail with some unicode special chars, causing issues like #183, #597, #441 and probably #589.

I also noticed that, if locale is not set correctly like described above, alt key is used as metakey, despite hterm 'alt-sends-what' is set to 'browser-key' [here](https://github.com/zeit/hyperterm/blob/master/lib/components/term.js#L40).

A temporary workaround is to manually set the right locale for you in your `.bashrc`/`.zshrc`: for me it's `export LANG=it_IT.UTF-8`.

Hope it helps 😄

**Comment by hoffi** [comment]
The workaround solves my issue #589. 
I have set the `LANG`-Variable to `de_DE.UTF-8` in my fish config (was `de.UTF-8`) and it helped.

**Comment by Arttse** [comment]
> A temporary workaround is to manually set the right locale for you in your .bashrc/.zshrc: for me it's export LANG=it_IT.UTF-8.

Not fully worked for me with locale `ru_RU`. 
Hyper version `0.8.3`.

I checked the locale:
```sh
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: ?????????? ?????????? LC_ALL ? ?????? ?? ?????????.: ??? ?????? ????? ??? ????????
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU
LC_CTYPE=ru.UTF-8
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

I saw that the variable `LC_CTYPE` is set incorrectly.

So for me, a working version was like this:
```sh
export LANG=ru_RU.UTF-8
export LC_CTYPE=ru_RU.UTF-8
```
Put this to your `.bashrc` or `.zshrc`

**Comment by dunst0** [comment]
Works for me as well had locale errors when using ssh client

**Comment by ZeFifi** [comment]
Hi guys, I had the same issue, here's what I did to fix it (no é, è, à, ù, etc characters were well displayed) : 

Made sure my library language is installed: `sudo install language-pack-fr-base` (for french)
Then, allowed Ubuntu to automatically configure it: `sudo dpkg-reconfigure locales`
Finally: `export LC_ALL="fr_FR.utf-8"`

Hope it helps!

**Comment by onip** [comment]
this also causes problems with ssh tab-completion.
