### ISSUE TITLE
Don't show "No changes!" notification when there are local plugins

### ISSUE THREAD

**Issue by ianwalter** [zeit/hyper#614]
I think that the "Plugins Update > No Changes!" notification shouldn't be shown when there are local plugins because it's not necessarily true and for me it actually blocks an error notification about the plugin I'm working on. May I submit a PR to change this conditional?
https://github.com/zeit/hyperterm/blob/f175268912d01ce13bf853fa5afe5dda2c3ae0aa/app/plugins.js#L101

**Comment by CodeTheory** [comment]
Probably best to submit a PR and then have it reviewed so ZEIT knows what your intentions are. This is the easiest way for the change to happen. 😄

**Comment by ianwalter** [comment]
Yea, I need to do some further investigation actually, because what I really want is for the notifications to stack, instead of overlapping.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
