### ISSUE TITLE
Keyboard shortcuts don't work when closing a tab with cmd+w

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#62]
The problem is that we can't give programmatic focus to hterm (it seems) when keyboard events are used. It seems to require a click event, probably due to the fact that there's an `<iframe>` in the way.

We might need to register all the `Mousetrap` shortcuts as accelerators in Electron _as well_.

**Comment by marcbachmann** [comment]
Is this still the case? I can't reproduce it.

**Comment by ppot** [comment]
@rauchg  It look like on the present build my cmd+w work.

**Comment by CodeTheory** [comment]
I don't think this is an issue anymore. I'll close it for now unless @rauchg can still reproduce or we get a duplicate issue.
