### ISSUE TITLE
cursorShape resets on tab completion

### ISSUE THREAD

**Issue by controversial** [zeit/hyper#620]
I'm in `zsh`. When I press tab and there are multiple matches for completion, the `cursorShape` goes back to `BLOCK` (it's `BEAM` in my `~/.hyperterm.js`).  The `BLOCK` shape stays until I focus another system text field and switch back, at which point it's reset.

**Comment by controversial** [comment]
Note that this happens in all cases when the terminal emits a "ping." (no idea how else to describe this set of scenarios). But the same bug occurs when pressing down in a new terminal line, or pressing up at the top of `vim`.

**Comment by maxdeviant** [comment]
I believe this bug is the same as #674.

**Comment by controversial** [comment]
You're right, it is.

**Comment by controversial** [comment]
Actually, re-opening because mine was first

**Comment by maxdeviant** [comment]
First, but I didn't see this one until after I started putting my debug notes in the other thread 😛 

We can keep both open, I was just trying to link to make sure that they both get closed when we fix the issue.

**Comment by controversial** [comment]
Ok, cool.

**Comment by ppot** [comment]
@rauchg @matheuss  I thin'k we can close this now?
