### ISSUE TITLE
Cursor renders in the wrong position after changing prompt

### ISSUE THREAD

**Issue by controversial** [zeit/hyper#621]
If I change the powerline settings in my config file and reload it, the terminal cursor forever appears one character behind. See this gif:
![wrongcursor](https://cloud.githubusercontent.com/assets/10377391/17654551/3c2b6f30-6272-11e6-82ae-04d79242bf9e.gif)

I suspect this is a bug rendering the status line as one character too large. When I make the same change and re-source the same way in macOS Terminal.app, the status line is the same length, but in HyperTerm it's one character larger than before.

I don't know if this is something that can be fixed at the  `hyperterm` level, but it'd certainly be nice (or at least a temporary hack; this is driving me crazy)

**Comment by BenoitAverty** [comment]
This is related to #535. The cursor shifts a little bit to the left for each character that's larger than a single monospaced char. That's why you notice it more with the awesome patched font: there are three such characters instead of one.

**Comment by BenoitAverty** [comment]
See also #577

**Comment by controversial** [comment]
Ok, thanks.

**Comment by denysdovhan** [comment]
the same issue: 

![image](https://cloud.githubusercontent.com/assets/3459374/19766208/4ed296dc-9c55-11e6-8ed8-4f2f6bc7b02b.png)

**Comment by BenoitAverty** [comment]
@denysdovhan See PR #740

**Comment by ppot** [comment]
@matheuss

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
