### ISSUE TITLE
Using 'back button' on mouse causes Hyperterm window to go black.

### ISSUE THREAD

**Issue by JackMordaunt** [zeit/hyper#626]
Makes the app unusable if I accidentally hit the back button just under my thumb.
Shouldn't Hyperterm have "back" command disabled?

Thoughts?

Excuse me if this is totally off base.

**Comment by booc0mtaco** [comment]
Do you have a "forward" button mapped? What happens if you were to press that?

Related: if you use the "view a website" feature, where you type in a URL, you can't get back to the terminal window, as far as I can tell. Wondering if your back button lets you get back to the shell...

**Comment by ppot** [comment]
What is the current state of this in the master? @JackMordaunt

**Comment by JackMordaunt** [comment]
With the latest version of hyper on OSX the issue appears to be resolved. Haven't tested on Windows. @ppot

**Comment by ppot** [comment]
Good. Il close it.
