### ISSUE TITLE
$SHELL environment variable not changing if different shell being used

### ISSUE THREAD

**Issue by BenDiuguid** [zeit/hyper#629]
First off, HyperTerm is AWESOME! 😄 

In my `.hyperterm.js` file I have the shell field set to zsh:

`shell: '/usr/local/bin/zsh'`

but when I run `echo $SHELL` the response is: `/usr/local/bin/bash`
and when I run `echo $0` the response is `/usr/local/bin/zsh`

This isn't currently causing any notable issues for me, but It may cause problems with other programs.

Any ideas? I'm open to submitting a PR, I just haven't figured out how to solve the problem yet.

Thanks!

**Comment by hpcodecraft** [comment]
I had a similar issue - are you on a Mac? Maybe try to change your default shell in the User settings of the system preferences. I had to change the shell there to make it work, and $SHELL now is /bin/zsh for me.

**Comment by knownasilya** [comment]
Issue for me as well, although I've set the shell in Hyper and used `chsh`. The shell is changed in Hyper and iTerm2 and `echo $SHELL` returns `/bin/zsh` in iTerm2 but in Hyper it returns `/bin/bash`.

**Comment by knownasilya** [comment]
Seems to be fixed with the latest release.

**Comment by BenDiuguid** [comment]
This is fixed for me as well!

**Comment by CodeTheory** [comment]
Thanks @BenDiuguid!

**Comment by midgethoen** [comment]
this is still happening to me on a clean Mac..

**Comment by jnardiello** [comment]
I'm experiencing this too, right now. Similar scenario as described above: clean macOS, installed hyper. `echo $SHELL` on hyper returns `/bin/bash`, while it should be `/usr/local/bin/fish`.

**Comment by amlcodes** [comment]
still happening, $0 returns correct zsh. $shell does not change

**Comment by Aningaaq** [comment]
still happening for me too.

**Comment by matthewcoxx** [comment]
Still have the same issue. Clean Mac. Regardless of what is set in hyper.js or using chsh, still receive 

> The default interactive shell is now zsh.
> To update your account to use zsh, please run `chsh -s /bin/zsh`.
> For more details, please visit https://support.apple.com/kb/HT208050.

On start. Terminal has no issues.

**Comment by YewTreeWeb** [comment]
This is still the same issue for me I'm running macOS 10.15.4 and if I run `echo $SHELL` or `echo $0` in Hyper I get **/bin/bash** but if I run the commands in iTerm2 I get **/usr/local/bin/zsh**
