### ISSUE TITLE
`export EDITOR=/usr/bin/vim` gets appended to .zshrc every time I open HyperTerm's Preferences

### ISSUE THREAD

**Issue by olivier-w** [zeit/hyper#630]
Might be related to #153? This is what my `.zshrc` becomes after a few days:

![screen shot 2016-08-17 at 1 57 47 pm](https://cloud.githubusercontent.com/assets/465250/17747408/b85049de-6482-11e6-868d-024d6c41c38b.png)

**Comment by escobara** [comment]
I worked around this by adding the export flag inside of my .profile. 
    
    echo "export EDITOR='vim'" >> ~/.profile

Then I restarted my terminal.

**Comment by olivier-w** [comment]
@escobara Unfortunately, that's not working for me 😞

**Comment by olivier-w** [comment]
Update: this was completely unrelated to hyper, my bad 😞  I was `echo`-ing it for every time `zsh` was sourced.
