### ISSUE TITLE
Non-hex formart colors do not work

### ISSUE THREAD

**Issue by jasonkuhrt** [zeit/hyper#650]
Hyperterm version `0.7.1 (0.7.1.36)`

Configuring terminal colours in `~/.hyperterm.js` with non-hex values does not currently work, but it should because CSS colour values are accepted (seemingly) everywhere else.

For example the following would not work:

``` js
colors: {
  black: "hsl(0, 0%, 10%)",
},
```

**Comment by jasonkuhrt** [comment]
I am going to look through the source code tomorrow morning. I will try to submit a PR to fix this issue.

**Comment by CodeTheory** [comment]
Might possibly be available via #524 or #197?
