### ISSUE TITLE
Background not transparent in apps

### ISSUE THREAD

**Issue by davegomez** [zeit/hyper#651]
I'm trying to set the terminal background transparent using `backgroundColor` and the `borderColor` properties like this:

    backgroundColor: '#ARGB',
    borderColor: '#ARGB'

It is working fine for the main terminal window but is not working if I get into applications like **Vim**, where the background color keeps being of a solid color.

I usually have this transparency in **iTerm2** and it also works on applications like **Vim**, so I would like to know if there is some way to fix this or if it's an **Hyperterm** limitation.

PD: how can I override `backgroundColor` and `borderColor` values from the custom `CSS || termCSS` properties o even when is being already set by a installed theme?

**Comment by albinekb** [comment]
Alpha is supplied in the format `#RRGGBBAA` if you want it in HEX, otherwise `rgba(R,G,B,A)`

[Source (https://googlechrome.github.io)](https://googlechrome.github.io/samples/css-alpha-channel/)

**Comment by davegomez** [comment]
The shortcut is supported but is not the problem at all because of course I tried both.

**Comment by ekmartin** [comment]
This has been fixed since, `rgba` should work in master.
