### ISSUE TITLE
Ctrl+Tab and Ctrl+Shift+Tab not working on macOS?

### ISSUE THREAD

**Issue by verekia** [zeit/hyper#658]
Pressing Ctrl+Tab on macOS causes the terminal to prompt autocomplete suggestions instead of switching tabs. Cmd+Option+Arrows correctly switch between tabs though.
## 

HyperTerm 0.7.1
Electron 1.2.8
darwin x64 15.0.0

OSX El Capitan 10.11.1

**Comment by verekia** [comment]
Thanks for tagging my request. However, isn't this supposed to be implemented already?

hyperterm.js seems to contain relevant lines:

https://github.com/zeit/hyperterm/blob/7fbd8ccaf17dd662903cea21cd97455c2807b265/lib/containers/hyperterm.js#L54

That would probably make it a Bug and not a Feature Request if that's the case.

**Comment by verekia** [comment]
@matheuss ^

**Comment by verekia** [comment]
Thanks!

**Comment by samhinshaw** [comment]
I am still running into this issue, even with all plugins disabled. 
I am also still able to use Cmd+Option+Arrows. 
Ctrl+Tab inserts a tab, Ctrl+Shift+Tab inserts the 'Z' character. 

Hyper 1.4.4
zsh shell
macOS 10.12.6

**Comment by ltblueberry0** [comment]
same problem on macOS. unable to use Ctrl+Tab. it just inserts the 'Z' character.
