### ISSUE TITLE
can't write accented characters on a portuguese keyboard

### ISSUE THREAD

**Issue by nfcampos** [zeit/hyper#66]
This sentence here

> Note that composed characters (those that require multiple keystrokes) are not currently supported by this mode.

https://chromium.googlesource.com/apps/libapps/+/HEAD/nassh/doc/FAQ.md#How-do-I-enter-accented-characters

suggests this is not possible using `hterm`

any has any idea how to solve this?

**Comment by rauchg** [comment]
![image](https://cloud.githubusercontent.com/assets/13041/16639147/a0b1561c-43a1-11e6-9771-2e04c1a2e6e7.png)

We might need to revisit how input is being captured right now by hterm. It relies on key events, which are not capable of themselves triggering composition modals (like the emoji window).

Instead, I think it'd be interesting to explore inserting a tiny contenteditable `<div>` inside the caret div, and capture events inside it. That way, when composition happens, the modal will be displayed where the user expects.

**Comment by xaviervia** [comment]
👍  to this one. I can't type `@` in the swedish keyboard =) (also can't put emojis)

**Comment by nfcampos** [comment]
@rauchg I played around with capturing user input through an always focused hidden `input` but got stuck on capturing backspace and enter keystrokes, but I didn't try too hard to be honest

**Comment by rauchg** [comment]
@nfcampos we might want to try `keypress` + composition events on that input (https://developer.mozilla.org/en-US/docs/Web/Events/compositionstart). The input has to be placed in the caret, not be altogether hidden, otherwise the emoji dialog will show out of place.

**Comment by nfcampos** [comment]
We might be able to do without adding any element. I've tried just making the current `x-row` element (current as in the one the cursor is in) contenteditable and it appears to work (sort of)
```js
// this could maybe be ran every time something is written to the terminal
this.term.screen_.rowsArray.map((row, i) => {
  if (i === this.term.getCursorRow())
    currentRow.contentEditable = true;
  else
    currentRow.contentEditable = false;
})
```
- this makes the emoji dialog appear in the right place (as long as that x-row has focus, we can probably give it focus when you click anywhere in the terminal, it already gains focus as soon as you type anything)

<img width="539" alt="screenshot 2016-07-07 23 45 03" src="https://cloud.githubusercontent.com/assets/56902/16672259/d9135c48-449c-11e6-9cad-37a60155cfd0.png">
- clicking an emoji inserts a bunch of gibberish, but there's probably something we can do to fix that
- accents do appear but when I type a letter after hitting the accent key (which would normally insert the accented letter, eg. á) gibberish appears (the same gibberish that appears if I paste the same accented character to the terminal

<img width="185" alt="screenshot 2016-07-07 23 49 05" src="https://cloud.githubusercontent.com/assets/56902/16672375/ae860740-449d-11e6-8f4f-6646698ca9b8.png">
<img width="190" alt="screenshot 2016-07-07 23 51 01" src="https://cloud.githubusercontent.com/assets/56902/16672376/b03c7b00-449d-11e6-91e9-74b10bc1228b.png">
- and obviously we'd have to remove that hideous blue outline

@rauchg do you know what to do about getting rid of the gibberish and writing the actual characters/emojis to the terminal?

**Comment by Adejair** [comment]
Also its not possible write characters `~` and `'` in hyperterm on keyboard `EUA - INTERNATIONAL - PC` (Macbook)

**Comment by ghostbar** [comment]
Nor ", \`, ', ˜ or accentuated characters with US International. That means, no: áéíóúäëïöüàèìòùñÑäë'"~`. It won't show gibberish, just won't write the special-chars and for vocals will just write them plain.

**Comment by rainerborene** [comment]
Same here.
