### ISSUE TITLE
Developer tools not functional on Linux Ubuntu 14.04

### ISSUE THREAD

**Issue by flybayer** [zeit/hyper#664]
Running the latest code on master at a23022d5e0a7b9d04552337f057a4ac9489b033b.

**Toggle Developer Tools** results in a solid, white pane appearing. It appears the tools are actually running, but they are not displaying at all. Hovering the mouse at the top of the white pane turns the cursor into a hand. I'm able to click things and sometimes make something happen, but I can't see what I'm doing! :laughing: 

No errors are are shown anywhere, including the dev logs.

This same behavior existed back in v0.7.1

**Comment by matheuss** [comment]
Is that an Electron bug? 🤔

**Comment by capaj** [comment]
@matheuss This happens for me too- I am on Ubuntu 16.04. All other electron apps(Atom for example) I have tried have this working, so I think this might be problem only in hypertherm. 
Although Atom uses much older electron version https://github.com/atom/atom/blob/2ef61af84e4ee7ae838b903aab7a8b8554fc9b5c/package.json#L15

**Comment by matheuss** [comment]
OK, so it is a bug! 😛

**Comment by flybayer** [comment]
I tracked this regression down to commit d8e841a3d8f60309ab9262453a97401caf616b21 from #28 where hterm was first implemented.

I'll try to investigate more tomorrow.

/cc @rauchg

**Comment by flybayer** [comment]
@rauchg do you have any ideas on this? I'm not sure what further debugging to do or where to look for solutions. Commit fe69d519a2b7f04a98fe7aeec2d3309934a9b52a from the pull request is the commit that seems to break it because of hterm.

If I comment out the `new hterm.Terminal()` line as below, the dev tools appear again.
```js
export default class Term extends Component {

  componentDidMount () {
    //this.term = new hterm.Terminal();
    this.term.prefs_.set('font-family', 'Menlo');
    this.term.prefs_.set('font-size', 11);
```

**Comment by flybayer** [comment]
In fact, just calling `new hterm.Terminal()` breaks the tools!

```js
export default class Term extends Component {

  componentDidMount () {
    new hterm.Terminal();
    //this.term = new hterm.Terminal();
    this.term.prefs_.set('font-family', 'Menlo');
    this.term.prefs_.set('font-size', 11);
```

**Comment by flybayer** [comment]
So dev tools are actually working for @fearphage on Ubuntu 16.04... 🤔

**Comment by flybayer** [comment]
YAY! :clap: Somehow this got fixed. Devtools are now working properly for me on Ubuntu 14.04
