### ISSUE TITLE
GOOGLE_API_KEY is set as an environment variable by default

### ISSUE THREAD

**Issue by migueloller** [zeit/hyper#696]
It took my a while to figure out what was wrong, but recently downloaded HyperTerm and every session exports `GOOGLE_API_KEY`. Haven't found a way to remove this on startup and need to manually `unset GOOGLE_API_KEY` every time.

**Comment by ekmartin** [comment]
This seems to be coming from Electron, [here](https://github.com/electron/electron/blob/master/atom/common/google_api_key.h#L9) - not sure why yet. As a workaround in the meantime I guess you could add the unset command to your `.bashrc`/`.zshrc` file?

**Comment by matheuss** [comment]
Closing since it is an upstream issue 😊

**Comment by migueloller** [comment]
Is there a reason why Hyper can't simply `unset GOOGLE_API_KEY`? Does it need this to be defined in the environment to work?

**Comment by albinekb** [comment]
Looks like it's only set by electron IF it's not already set to something, then it will be overridden:
https://github.com/electron/electron/blob/637bdc239b8f613fec7295e119aa86a753c51d0d/atom/browser/atom_access_token_store.cc#L68

**Comment by migueloller** [comment]
The issue is that when using a tool like [`dotenv`](https://github.com/motdotla/dotenv) that inserts environment variables at build or run time it will already be set. And because these tools don't override already set environment variables as a best practice then the `GOOGLE_API_KEY` environment variable ends up leaking from Electron into Hyper into the application causing esoteric errors that are very hard to debug until you realize where the problem is coming from.

**Comment by albinekb** [comment]
We can get the bundled API key via:
```
const electronPath = require('electron').app.getPath('exe')
const { execFileSync } = require('child_process')
const key = execFileSync(electronPath, ['--interactive'], { input: 'console.log(process.env.GOOGLE_API_KEY)' })
  .toString()
  .match(/^> (.+)/)[1]
```

and then use that when we spawn the child process:
https://github.com/zeit/hyper/blob/master/app/session.js#L26
```
if (key === process.env.GOOGLE_API_KEY) delete baseEnv.GOOGLE_API_KEY
```

🎉 
Don't know if we really want this though 😄

**Comment by migueloller** [comment]
Hahaha. Maybe that could work. 😄 

I guess I still don't fully understand how Hyper uses the api key (perhaps location services?), especially since it's an expired one. And even if it uses it, if it could still prevent exposure of it to Hyper users.

**Comment by albinekb** [comment]
Actually, it's even easier than that: 

```
if (baseEnv.GOOGLE_API_KEY && process.env.GOOGLE_API_KEY === baseEnv.GOOGLE_API_KEY) delete baseEnv.GOOGLE_API_KEY
```
