### ISSUE TITLE
Ability to hide title bar from config

### ISSUE THREAD

**Issue by hhsnopek** [zeit/hyper#697]

**Comment by leo** [comment]
Already possible! Just do it [like this](https://github.com/leo/hyperterm-native/blob/b1e717e51abf888368f12a1ebf9d880def3bbd50/index.js#L27) and set "titleBarStyle" to "hidden".

**Comment by hhsnopek** [comment]
Hmm, I can't quite add this to my `.hyperterm.js` looks like it's only accessible from the extensions api?

**Comment by leo** [comment]
@hhsnopek Correct!

**Comment by hhsnopek** [comment]
Any reason it cannot be inside my config? Seems a little silly to have an extension just so I can hide the title bar

**Comment by leo** [comment]
@hhsnopek Oh. Just noticed that you actually want to hide the title bar (what electron does is simply remove the title bar but the traffic lights stay in place). What's your intention behind that?

**Comment by hhsnopek** [comment]
Minimalism and I don't use tabs in Hyperterm, I use vim-tabs. Thus the title bar doesn't actually reflect the directory I'm in, and rather than creating an extension to get my real directory in vim, I'd rather just hide it as my vim-tabs give me the correct title bar. Just unnecessary redundancy for me

**Comment by hhsnopek** [comment]
This could be done by adding a check when exporting the object if I'm not mistaken
```javascript
exports.decorateConfig = config => Object.assign({}, config, {
  padding: '7px 7px',
  backgroundColor: '#fff',
  foregroundColor: '#000',
  cursorColor: '#000',
  cursorShape: 'BEAM',
  css: (config.css || '') + styles,
  browserOptions: {
    titleBarStyle: config.browserOptions.titleBarStyle || 'default',
    transparent: config.browserOptions.transparent || false
  },
  colors
})

exports.decorateBrowserOptions = defaults => Object.assign({}, (config.browserOptions || defaults), {
  titleBarStyle: 'default',
  transparent: false
})
```

**Comment by fmartingr** [comment]
I'm also interested in this behaviour.

**Comment by hhsnopek** [comment]
If no one is able to get around to this during the week, I can take a whack at it this weekend

**Comment by Jarvvski** [comment]
Any update @hhsnopek ?

**Comment by hhsnopek** [comment]
I decided implementing this and went with iTerm2 as it had everything I was looking for out of the box, sorry @Jarvvski

**Comment by henrikdahl** [comment]
Closing since there's plugins that does this such as https://github.com/jancborchardt/hyperminimal ✌️

**Comment by etos** [comment]
would be nice to include this as default

**Comment by joaogabrielfjob** [comment]
i created this simple [plugin](https://www.npmjs.com/package/@joaogabrielfjob/hyper-hide-title) to solve this issue :)
