### ISSUE TITLE
Option to disable tab close button

### ISSUE THREAD

**Issue by karlhorky** [zeit/hyper#720]
Let me start by thanking everyone involved for this project. Great to have hackable web tech drive our terminal!

The tab close button introduced in #58 (original issue #40) is a nice feature, thanks for that. However, sometimes on a small terminal window with many tabs, this can result in mis-clicks, closing important tabs unintentionally.

What do you think about introducing a configuration option to disable the close button if a user wants to?

cc @johanbrook

**Comment by bildepunkt** [comment]
Hey all. I'd love to tackle this one if that's alright.

**Comment by matheuss** [comment]
Is more than alright @bildepunkt 😄 Go ahead 🙌

**Comment by johanbrook** [comment]
We could hide the buttons on the tabs if they're small enough too :) One part of me thinks a configuration option is overkill, but I guess some users want hardcore configurability.

**Comment by karlhorky** [comment]
> I guess some users want hardcore configurability

Yeah I don't want to click on a tab in the wrong place and lose some important process. Since this can potentially be quite damaging, I would suggest that a configuration option is a quite small price to pay.

**Comment by bildepunkt** [comment]
> We could hide the buttons on the tabs if they're small enough

@johanbrook I was thinking the same thing. The user can still close it with the keyboard once it's in focus. Maybe that can be a separate feature request.

**Comment by knownasilya** [comment]
Why not have a confirmation dialog ask if you're sure you want to close? I do this all the time... even with large tabs. The icon should always be visible so you know you're clicking it.

**Comment by Tallestthomas** [comment]
I think @knownasilya has the right idea.  Maybe make it possible for someone to disable the prompt if they want?

**Comment by karlhorky** [comment]
> Why not have a confirmation dialog ask if you're sure you want to close?

This would be annoying to me to have to close a dialog every time I make a mistake. It would still be penalizing the user for making the mistake of clicking in the wrong place.

**Comment by johanbrook** [comment]
> It would still be penalizing the user for making the mistake of clicking in the wrong place.

Agree.

On tors 29 sep. 2016 at 09:10 Karl Horky

<
mailto:Karl Horky <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Why not have a confirmation dialog ask if you're sure you want to close?

This would be annoying to me to have to close a dialog every time I make a mistake. It would still be penalizing the user for making the mistake of clicking in the wrong place.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/zeit/hyperterm/issues/720#issuecomment-250388271
, or

**Comment by bildepunkt** [comment]
should I (rebase and) commit this then, or are we scrapping this feature request? It seems to me we could keep it as a config option and add the confirmation as another config seeing as the votes are split.

**Comment by knownasilya** [comment]
> This would be annoying to me to have to close a dialog every time I make a mistake. It would still be punishing the user for making the mistake of clicking in the wrong place. Albeit not as great a punishment, but a punishment nonetheless.

@karlhorky If the close button is always visible you'd be less likely to get the confirmation dialog.

>should I (rebase and) commit this then, or are we scrapping this feature request? It seems to me we could keep it as a config option and add the confirmation as another config seeing as the votes are split.

@bildepunkt probably worth asking someone who'd be merging it, but yes they could live together.

**Comment by karlhorky** [comment]
> are we scrapping this feature request?

In my perspective, the other recommendations on this thread don't address the use case, so the original feature request still stands.

For the other alternatives, I would suggest opening new feature requests.

**Comment by knownasilya** [comment]
> In my perspective, the other recommendations on this thread don't address the use case,

Sounds like it handles the use case exactly. 👇 

> However, sometimes on a small terminal window with many tabs, this can result in mis-clicks, closing important tabs unintentionally.

**Comment by karlhorky** [comment]
> If the close button is always visible you'd be less likely to get the confirmation dialog.

I don't believe this to be the case. Regardless, we are splitting hairs now, trying to measure the hypothetical possibility that someone misclicks. I opened this issue because misclicks happen on small targets like this (example: clicking on a tab quickly to switch to it). In the case of a misclick I would argue that a confirmation dialog is not an improvement. A configuration option to disable the close button is a low cost, effective solution.

A confirmation dialog is a different feature request (and not necessarily a bad one). It does not solve the use case.

**Comment by karlhorky** [comment]
@bildepunkt did you open a pull request for this?

**Comment by knownasilya** [comment]
It was rejected here: #737

**Comment by karlhorky** [comment]
Created a plugin for this: https://github.com/karlhorky/hyper-no-close
