### ISSUE TITLE
Hyperterm doesn't recognize F19 key

### ISSUE THREAD

**Issue by leira** [zeit/hyper#721]
I mapped Caps Lock as F19, and use it as a dedicated tmux prefix key. It worked well in iTerm2, but not working in hyperterm, seems like hyperterm doesn't recognize F19 key. The $TERM values in both iTerm2 and Hyperterm are both xterm-256color.

Here are the results from 'sed -n l', I pressed key F19, then F7, then Shift-F7, all followed by Enter. 

In iTerm2, F19 was recognized, and has the same value as Shift-F7, as expected:

```
> sed -n l
^[[18;2~
\033[18;2~$
^[[18~
\033[18~$
^[[18;2~
\033[18;2~$
^C⏎
```

In Hyperterm, F19 doesn't output any thing:

```
> sed -n l

$
^[[18~
\033[18~$
^[[18;2~
\033[18;2~$
^C⏎ 
```

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
