### ISSUE TITLE
brew cask install error

### ISSUE THREAD

**Issue by fanyer** [zeit/hyper#738]
iterms info as below:
```
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'hyperterm' with message: Download failed: https://github.com/zeit/hyperterm/releases/download/v0.7.1/hyperterm-0.7.1-mac.zip
The incomplete download is cached at /Users/fanyeer/Library/Caches/Homebrew/Cask/hyperterm--0.7.1.zip.incomplete
```

seems the url wrong,   Should be `***/0.7.1/***` , your resource on brew cask seems a `v` character more

**Comment by CodeTheory** [comment]
I think this might be an issue for `homebrew-cask` themselves. https://github.com/caskroom/homebrew-cask/blob/master/Casks/hyperterm.rb#L6 

Am I wrong?

**Comment by fanyer** [comment]
I've considered that you register hyperTerm in brew cask before that. Anyhow, I've got it installed.👍

**Comment by ekmartin** [comment]
Hm, this is weird - seems to work now: 
![image](https://cloud.githubusercontent.com/assets/3536982/18894530/6e847d32-84e1-11e6-823b-ffe37522d89a.png)

Maybe try `brew cask update` before installing?

**Comment by xn4v8h** [comment]
getting this now:

```==> Downloading https://github.com/zeit/hyper/releases/download/0.8.1/hyper-0.8.1-mac.zip

curl: (22) The requested URL returned error: 404 Not Found```
