### ISSUE TITLE
Please add cross-env for building on different plattforms

### ISSUE THREAD

**Issue by con-ssc** [zeit/hyper#755]
It would be nice if you'd add cross-env to the project and add it before setting env variables like NODE_ENV so this would make it usable on other platforms as well.

https://www.npmjs.com/package/cross-env

**Comment by fearphage** [comment]
This is just a Windows fix, right?

**Comment by con-ssc** [comment]
Well, since linux and macos share a similar bash, yes you could say this is a windows fix, but it would still work with macos or linux

**Comment by matheuss** [comment]
This is an upstream issue: we have several dependencies that are built when `npm install` is run 😕
