### ISSUE TITLE
nerd fonts

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [zeit/hyper#7686]
Using `0xProto` nerd fonts  (https://www.nerdfonts.com/font-downloads) in hyper on mac os 

```json
...
      fontFamily: '0xProto Nerd Font',
```

results in

<img width="1212" alt="Screenshot 2023-12-24 at 15 24 34" src="https://github.com/vercel/hyper/assets/15908060/bfa060ed-a0f9-4465-921a-4dd45f6e274b">

what is going on?

Thanks a lot

happy holidays, Fra :)

**Comment by vipinnation** [comment]
I want to work on this issue.

**Comment by FrancescoSaverioZuppichini** [comment]
Fixed, I had to do `'"<FONT_NAME"'`
