### ISSUE TITLE
Cursor respawns above previous lines after scrolling to the bottom in nano and exiting

### ISSUE THREAD

**Issue by timothyis** [zeit/hyper#772]
See image below.

When I enter nano, scroll to the bottom (or sometimes mid-way through when making various changes), the cursor of hyperterm appears higher up than it should be, forcing me to overwrite previous lines in the term window.

![image](https://cloud.githubusercontent.com/assets/1695613/19092682/0d882ec8-8a88-11e6-9b09-8c779c21d5a2.png)

**Comment by timneutkens** [comment]
Note: experiencing the same behaviour inconsistently when using vim.

**Comment by timothyis** [comment]
Haven't had this since switching to xterm 👍
