### ISSUE TITLE
hpm install: HTTPError: Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by Harryandrew** [zeit/hyper#775]
As per the title, `hpm i xxx` returns the following error: `HTTPError: Response code 401 (Unauthorized)`

Will research and post any findings here if I find the issue.

**Comment by iamstarkov** [comment]
@Harryandrew its an issue with hpm, not with hyper.app, pls move this issue into relevant repo

**Comment by matheuss** [comment]
@Harryandrew please open an issue on [zeit/hpm](https://github.com/zeit/hpm) 😅 – Thanks @iamstarkov

**Comment by Harryandrew** [comment]
ok thanks
