### ISSUE TITLE
HyperTerm automatic fullscreen

### ISSUE THREAD

**Issue by inventionlabsSydney** [zeit/hyper#776]
Hello!
Just wondering if it's possible to configure automatic fullscreen window mode on HyperTerm yet.

Also how far away multiple window panes vertical+horizontal?

Thanks,
## Karl.

HyperTerm 0.7.1
Electron 1.2.8
darwin x64 16.0.0

**Comment by jacksonSingleton** [comment]
I've been looking into auto fullscreen myself. However, to address the multiple window panes, I would stick to tmux. If you don't want to use tmux there is always [hyperterm split](https://www.npmjs.com/package/hyperterm-split).

**Comment by jacksonSingleton** [comment]
Also, this is a partial copy of Issue #56
