### ISSUE TITLE
Linux download link broken in the website.

### ISSUE THREAD

**Issue by vpakg** [zeit/hyper#780]
Linux version not downloadable from the website.

When clicking the link, I'm redirected to a blank page saying `Version not found: latest`

**Comment by c0b41** [comment]
Because [0.7.1](https://github.com/zeit/hyperterm/tree/0.7.1) not Deb or  AppImage build. @rauchg

**Comment by probonopd** [comment]
I can see an AppImage on the Releases page...

**Comment by vpakg** [comment]
Anywhere else I can find the download links?

**Comment by vpakg** [comment]
Anywhere else I can find the linux version to download?

**Comment by probonopd** [comment]
https://github.com/zeit/hyper/releases

**Comment by vpakg** [comment]
@probonopd thank you.

**Comment by ppot** [comment]
#799
