### ISSUE TITLE
Rich Support for Tweaking Modifier Keys

### ISSUE THREAD

**Issue by rye** [zeit/hyper#783]
#330 references remapping the Option key and using that as Meta on OS X.
#686, which introduced support for this, resolved #330, but I think that it wasn't enough to satisfy most users, especially those like myself who use Emacs in terminal and require having full access to all the modifiers.

I'd prefer to see something more like:

``` js
"modifierKeys": {
  "cmd": "super",
  "option": "meta"
}
```

In my configuration, personally.

[`lib/hterm.js`](https://github.com/zeit/hyperterm/blob/master/lib/hterm.js) will almost certainly need to be modified, specifically the `Keyboard.onKeyDown` callback.

Some questions to raise would be:
- What style would users like to see for a `"modifierKeys"` configuration?
- Is there even anything we can do to prevent operating systems like macOS from stealing these keybindings and entering 'special' characters?

I can and would love to work on this, but I'm not very familiar with the inner workings of things and I'd need to educate myself on VT.

**Comment by ferakpeter** [comment]
I've played around with the configurations for the meta keys, I would prefer your config style. However, the way cmdAsMeta is working right now, it's not usable, it overrides the hotkeys for new tab and new windows, and so forth. So Hyper loses core features in that case. And on windows and mac platforms there is no cmd button, so the setting with cmdIsMeta would be misleading. You configuration style can solve this.

So from my perspective there's only one question that should be answered in the config: do you want use ALT as meta, or do you want to not have a meta key.

**Comment by curioussavage** [comment]
I like the config too, and once https://github.com/zeit/hyper/pull/925 is resolved the cmd key issue will be resolved too.

**Comment by ppot** [comment]
close in #1876
