### ISSUE TITLE
Vim registers not working inside tmux

### ISSUE THREAD

**Issue by Roshanjossey** [zeit/hyper#786]
**Steps to reproduce**
- Open hyperterm
- Open tmux `tmux`
- Open vim `vim somefile`
- Copy something. say <kbd>y</kbd><kbd>y</kbd>
- Paste <kbd>p</kbd>

It gives an error

> E353: Nothing in register *

**Comment by bramkok** [comment]
If you're running macOS 10.12 Sierra you might have run into this problem:

https://github.com/tmux/tmux/issues/543

**Comment by Roshanjossey** [comment]
@bramkok: Yes, I'm using macOS Sierra. This problem was not there for iterm.
Thank you for guiding me to the right path.
I'd prefer to close this issue as its causing because of tmux.
Please share your thoughts on the same.

**Comment by jwhitley** [comment]
Frustratingly, the tmux issue also means that {vim clipboard registers, pbpaste} aren't viable workarounds for #484. 😓

**Comment by jhqian** [comment]
Add the following into your .vimrc
`if $TMUX == ''
    set clipboard+=unnamed
endif`

Reference:
https://stackoverflow.com/questions/11404800/fix-vim-tmux-yank-paste-on-unnamed-register
