### ISSUE TITLE
Upgrade to 0.8.0 or 0.8.1 broke pasting while in vim

### ISSUE THREAD

**Issue by criswell** [zeit/hyper#789]
Platform OSX.

*Not* running in tmux.

Happens whether vim is running locally, or remote.

Basically, prior to Hyperterm 0.8.0, it worked as expected. Working in vim, in insert mode, CMD-V would happily paste whatever was in the system clipboard. Now, after the 0.8.0 upgrade, it no longer works in vim. I can CMD-V to paste otherwise, it just is no longer working in vim.

I should note that the *only* change was the Hyperterm upgrade. My vim configs and vim versions haven't changed. I have tried it in both vim and neovim and get the same results. Further, firing up iterm or iterm2 and trying to paste into vim/neovim works as expected.

Pasting from Edit->Paste doesn't work either (in fact, when I CMD-V I see the "Edit" drop-down flicker, so it's obviously being registered).

I tried 0.8.1 (Hyper.app... blegh... WTF, guys...) and have the same result.

**Comment by jacksonSingleton** [comment]
Works perfectly fine for me in both the standard OSX Terminal and in Hyperterm. How are you pasting from clipboard?

**Comment by jona** [comment]
I am having the same issue

**Comment by criswell** [comment]
>  Works perfectly fine for me in both the standard OSX Terminal and in Hyperterm. How are you pasting from clipboard?

* Select text, somewhere (webpage, terminal, doesn't matter)
* Hit CMD-C to copy
* Go to Hyperterm with vim in it.
* Go into insert mode
* Hit CMD-V to paste

Like I said, works everywhere else, except the combination of post 0.8.0 Hyperterm plus vim. Worked fine with Hyperterm plus vim up until 0.8.0 came out.

**Comment by westlywright** [comment]
I am having the same issue. Except I can copy text from else where and use vim's paste command and the copied text is pasted. It only seems to be pasting text while in insert mode. @criswell do you experience the same thing?

**Comment by flybayer** [comment]
This is the same bug as #773.

**Comment by criswell** [comment]
This isn't the same bug as #773.  Pasting works fine if I'm in tmux and *not* Vim.

Only my vim is affected.

The stanza from the other user's hyper.js is not present in mine (my hyper.js is stock with the exception of a few plugins). My hyper.js can be found online here https://gist.github.com/criswell/1f9e05fdc670174f417425f707d1e91f

**Comment by ekmartin** [comment]
This has been fixed in 0.8.2.
