### ISSUE TITLE
Unable to dismiss "HyperTerm is now Hyper.app :O" notification

### ISSUE THREAD

**Issue by ctso** [zeit/hyper#790]
While I applaud all of the work done on HyperTerm (or I guess now, Hyper.app) - this is quite annoying.  Please give us a way to dismiss this alert:

![image](https://cloud.githubusercontent.com/assets/160060/19161441/a482daaa-8ba8-11e6-8182-ad07bfec2408.png)

**Comment by porkloin** [comment]
Seconded, this is incredibly annoying.

**Comment by karelwgonzalez** [comment]
Third. It's little, but it's super in the way of my workflow.

**Comment by jacksonSingleton** [comment]
Simple, but not a permanent fix, just go into the inspector(Ctrl+Alt+I/Cmd+Alt+I), and then delete the div, it shouldn't reappear.

**Comment by karelwgonzalez** [comment]
@jacksonSingleton Brilliant. Still doesn't solve the problem of the notification not being dismissible in the first place, but +1 for the easy fix so I can get on with my day.

**Comment by matheuss** [comment]
It's on purpose 😄 https://hyper-news.now.sh Please re-download as soon as possible! 😄

**Comment by ctso** [comment]
@matheuss then make that clear - it isn't clear, at all.

**Comment by hhsnopek** [comment]
maybe you could make this dismissible as some people might not want to update in the middle of their day?

**Comment by yarray** [comment]
As a newcomer I'm quite confused... I clicked the download link at hyper.is and the downloaded app told me to re-download from hyper.is. Also the release page of this GitHub repo contains no package named hyper but only hyperterm. So where can I download the hyper.app?

**Comment by sifex** [comment]
Same here @yarray.

**Comment by matheuss** [comment]
Fixed, thanks for reporting @yarray @sifex 😄

**Comment by sifex** [comment]
@matheuss Thanks for fixing so quickly! :)

**Comment by yarray** [comment]
@matheuss Wow that's amazing! Many thanks! Best response speed ever 😆

**Comment by steven-haddix** [comment]
Just downloaded this app from https://hyper.is/ (hyper-1.2.1.dmg) and I'm getting this message. Not sure what I'm supposed to be downloading...
