### ISSUE TITLE
0.8 Seems to Break Hyperborder

### ISSUE THREAD

**Issue by jacksonSingleton** [zeit/hyper#791]
<img width="565" alt="screen shot 2016-10-06 at 10 36 45 am" src="https://cloud.githubusercontent.com/assets/17009633/19161545/d6e97ef2-8bb9-11e6-9b9c-1a2268adaa74.png">
The gradient is supposed to be a border, not a fill for the terminal.
Not sure what's up with this, I plan on looking into this a little more after posting. This worked perfectly fine this morning.

**Comment by sebinsua** [comment]
[This is fixed.](https://github.com/webmatze/hyperborder/issues/9#issuecomment-252015762)

**Comment by ppot** [comment]
@matheuss  Close this 🎉

**Comment by matheuss** [comment]
Thanks @ppot <3
