### ISSUE TITLE
Make Linux UI frameless (use custom title bar)

### ISSUE THREAD

**Issue by flybayer** [zeit/hyper#795]
## Current

![image](https://cloud.githubusercontent.com/assets/8813276/19169871/c4b65b3e-8bdb-11e6-9be1-19b7fa2208e4.png)
## Desired

![image](https://cloud.githubusercontent.com/assets/8813276/19169815/95fc6518-8bdb-11e6-932e-6fe54018696d.png)

This is accomplished by adding `frame: true` to [browserDefaults](https://github.com/zeit/hyper/blob/master/app/index.js#L106-L121) if on Linux.

Custom elements for closing, minimizing, and maximizing will need to be added.

_[Electron Frameless-window docs](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md)_

**Comment by arikfr** [comment]
It's even worse on my setup (Ubuntu Gnome 16.04):

![screenshot from 2016-10-10 09-59-13](https://cloud.githubusercontent.com/assets/71468/19228705/60b7a730-8ed0-11e6-9c6e-9398f12d2b84.png)

**Comment by karlbateman** [comment]
Where to put the `frame: true`?

**Comment by flybayer** [comment]
@karlbateman click the [browserDefaults](https://github.com/zeit/hyper/blob/master/app/index.js#L106-L121) link and it'll show you the object to on which to add `frame`.

**Comment by karlbateman** [comment]
@flybayer Thank you, although I have it running on Debian Jessie amd64, so where would I edit that?

**Comment by flybayer** [comment]
@karlbateman did you install using the `.deb` package or did you clone this git repo and build it from scratch? If you did the first, you'll need to do the second following the instructions in the README. 

After cloning, edit the `app/index.js` file and then run `npm start`.

**Comment by karlbateman** [comment]
@flybayer I did the `.deb` install, so will follow your suggestion. Thanks for the help :wink:

**Comment by matheuss** [comment]
Yo y'all please check #946 😄

**Comment by karlbateman** [comment]
Is this included in the Linux binaries now?

**Comment by matheuss** [comment]
Not right now @karlbateman, but will be in the next release – which will be shipped very soon 😄

**Comment by karlbateman** [comment]
@matheuss Thank you, great job btw such an awesome app :+1:
