### ISSUE TITLE
Simple install for Linux? (Download link for Linux not working)

### ISSUE THREAD

**Issue by runvnc** [zeit/hyper#799]
Hello, I clicked on the Linux download and it says 'version not found 'latest'.

Why isn't there something like `brew install` to install this on linux?  Would be some nice if there was an `apt-get install hyper` for Ubuntu or an `npm i -g hyper.app` or maybe this appimage thing could be useful (I could not find an appimage).

I mean I don't really mind cloning the repo and installing everything manually but it should be easy to install.  Unless you don't like people who use Linux in which case you should continue making it hard :P Just kidding.

BTW this such a cool project.

**Comment by pveyes** [comment]
You can always use this -> https://github.com/zeit/hyper/releases, but I agree, `apt-get` would be awesome

**Comment by saule1508** [comment]
The doc is not clear, it took me a while to realize it is possible to install it on Fedora. There are some other - closed - issues that mention that but it should really be on the main download page.

On Fedora there was a missing depencency, 

/tmp/.mount_aytrIO/usr/bin/hyper: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

which got resolved by installing libXScrnSaver.

so 
- download the AppImage file from the link above
- dnf install libXscrnSaver
- chmod +x the AppImage file and run it

I am glad I can run it on my Fedora, it is really great

**Comment by probonopd** [comment]
In this case it looks like the AppImage is missing libraries that should be bundled inside @saule1508. That is a bug of the Hyper AppImage.

An AppImage should contain all libraries except the [blacklisted ones](https://github.com/probonopd/AppImages/blob/master/excludelist) which are expected to be part of every target system.

**Comment by programmador** [comment]
I've installed 0.8.0 deb package from releases page and found some packaging issues:
1. It writes "HyperTerm is now Hyper.app. Please re-download" though it's the latest deb package.
2. It's being installed to /opt and does not include any symlinks in /usr/bin or similar dir, so it needs to add a new PATH to .bashrc.
3. It does not include system menu icon, so it's able to run only either from other terminal or from custom launch icon.

**Comment by doug-wade** [comment]
I found a reasonable looking [askubuntu](http://askubuntu.com/questions/71510/how-do-i-create-a-ppa) on how to create a ppa -- would it be okay if I took a crack at setting one up?

**Comment by fearphage** [comment]
FYI, I've seen people host PPA's using github pages. 

http://www.dropboxwiki.com/tips-and-tricks/host-a-repository-of-deb-packages-with-dropbox

**Comment by flybayer** [comment]
We could also set this up like Yarn is doing:
https://yarnpkg.com/en/docs/install#linux

**Comment by pluma** [comment]
Mind changing the installation instructions if this can't be resolved on short notice? The Linux download link seems to have been broken for days and expecting Linux users to search the issues to figure out they have to use the GitHub releases isn't exactly great.

**Comment by hharnisc** [comment]
In the process of getting the latest version out for NixOS https://github.com/NixOS/nixpkgs/pull/19782

After that get's accepted, this can be installed as a package.

**Comment by fearphage** [comment]
> The Linux download link seems to have been broken for days

FYI it's been broken for weeks. The earliest report is now 16 days old.

**Comment by matheuss** [comment]
We can't fix it for past releases 😕 It'll be fixed on the next one – which will be shipped very soon 😄
