### ISSUE TITLE
Prompt before overwriting `.hyper.js`

### ISSUE THREAD

**Issue by maxdeviant** [zeit/hyper#802]
Currently, if there is an error in `~/.hyper.js` when Hyper is loading up, it will overwrite the file with the default configuration with no prompt.

Going along with #796, I think we should provide better errors for what's wrong with the file, or at the very least make the user confirm whether or not the config should be overwritten.

Otherwise someone else may find themselves with a not-so-pleasant surprise when their settings are gone 😨

**Comment by flybayer** [comment]
Did you mean to refer to #796 ? :thinking:

**Comment by maxdeviant** [comment]
@flybayer Ah yes, I did :sweat_smile: 

Thanks for catching that!

**Comment by BLamy** [comment]
Pretty frustrating lost my entire config because of a trailing comma.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
