### ISSUE TITLE
Provide newest builds 0.8.0 and 0.8.1 in brew cask

### ISSUE THREAD

**Issue by dotlouis** [zeit/hyper#807]
The latest version available in brew cask is 0.7.1 at the time this issue was created.

**Comment by nmontesdeoca** [comment]
Maybe doing brew cask update ?
After doing "brew cask info hyper" I get version 0.8.1

**Comment by nwinkler** [comment]
I can confirm that this is working now.

**Comment by albinekb** [comment]
Closing,  seems like 0.8.1 is available from cask now 👍  Please reopen if you still experience issues @dotlouis
