### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by boopathi** [zeit/hyper#808]
Updated to Hyper from Hyperterm, and this happens when I scroll up and then down. 

<img width="754" alt="screenshot 2016-10-07 12 03 27" src="https://cloud.githubusercontent.com/assets/294474/19186428/8251c4bc-8c86-11e6-941a-9eca848fc9cd.png">

**Comment by trueter** [comment]
Started appearing for me too once I tried the new split screen feature. Could be unrelated, though.

**Comment by dcalhoun** [comment]
I have experienced this as well. A few things I've noticed:

- There appears to be multiple, stacked scrollbars on the right side, as if there are multiple scroll containers.
- The issue temporarily resolved itself when I opened the dev tools inside of Hyper.
- I've primarily experienced this when a tool like [Jest](http://facebook.github.io/jest/) is writing to the window multiple times (i.e. – tests run, Jest clears the old output and writes new results).

### Environment
- Hyper 0.8.3 (0.8.3.873)
- macOS 10.12.1 (16B2555)
- Jest 17.0.3

### Screenshot
<img width="1440" alt="hyper-multiple-screens" src="https://cloud.githubusercontent.com/assets/438664/20626416/2dc5f0d8-b2df-11e6-82c7-b973c075a56e.png">

**Comment by dcalhoun** [comment]
I've noticed that screens that experience this issue will also [multiply values pasted into Hyper](http://quick.as/L6ZlI6Jq1). You can paste a simple string like `onefoo` and you'll end up with 12 copies of it with a single <kbd>CMD</kbd>+<kbd>v</kbd>.

I've primarily seen this bug when running Jest. I've noticed additional oddities every time Jest "clears" the window for each run (e.g. – previous runs are only partially cleared/cut off). I'm wondering if Hyper struggles with Jest's [approach](https://github.com/facebook/jest/blob/v17.0.3/packages/jest-util/src/clearLine.js#L15) to [clearing output](https://github.com/facebook/jest/pull/1596).

**Comment by jbaxleyiii** [comment]
@dcalhoun did you ever find a resolution? Jest watch mode is unusable with hyper currently 👎

**Comment by moskyb** [comment]
This issue presents to me any time I try to scroll further than the bottom of the screen - I love Hyper, but it's a massive drag dealing with this.

**Comment by dcalhoun** [comment]
@jbaxleyiii no, this is still very much an issue, even within 1.0.0.

**Comment by jbaxleyiii** [comment]
@dcalhoun dangit. @rauchg any pointers on where to look for a fix to this?

**Comment by bsmith-cycorp** [comment]
Is this the same issue as #1008?

**Comment by trueter** [comment]
I can confirm I have seen both issues. 808 I'm experiencing very regularly, 1008 more infrequently.

**Comment by chibicode** [comment]
This happens to me when I set [vibrancy](https://github.com/electron/electron/pull/7898) - specifically, use [hyper-one-light](https://github.com/andrepolischuk/hyper-one-light) theme with `enableVibrancy: true`, and scroll to the bottom of the window.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
