### ISSUE TITLE
Allow update notification to be dismissed

### ISSUE THREAD

**Issue by hhsnopek** [zeit/hyper#810]
After upgrading to to "Hyper" my workflow is borked and there are numerous bugs already ticketed here that are limiting me from working. I'm not sure what happened in all the "bug" fixes, between releases, but I can't use Hyper in my day to day workflow yet. Would you be able to allow the update notification, from #790, to be dismissible. I don't think forcing a non-dismissible notification upon users was a great idea in the first place, but if we could now that'd be awesome

**Comment by henrikdahl** [comment]
Since it's now dismissible I'm closing this ✌️
