### ISSUE TITLE
Alt + click in nano not working

### ISSUE THREAD

**Issue by robindboer** [zeit/hyper#811]
When you alt + click in nano you go to the desired line would be nice to have this feature in Hyperterm aswel since it is working in standart terminal on OSX

**Comment by flybayer** [comment]
Can you elaborate on how this works? Maybe create a gif showing what it is?

This is probably something that could be added with a plugin.

**Comment by yaycmyk** [comment]
Duplicate of https://github.com/zeit/hyper/issues/316

**Comment by matheuss** [comment]
Thank you @yaycmyk!
