### ISSUE TITLE
Need way to exit a webpage

### ISSUE THREAD

**Issue by dmfenton** [zeit/hyper#813]
After visiting a webpage in a terminal window I'd like to be able to exit that window with `cntrl c` but that does not seem to work. Apologies if this is a duplicate issue.

**Comment by CodeTheory** [comment]
Looks like this feature is even more broken in 0.8.1. cc @rauchg

**Comment by PandawanFr** [comment]
Ctrl + C works for me... 
I'm on mac tho, don't know about other platforms.

**Comment by hsyed** [comment]
An overlay mechanism that mentions ctrl c would help. Eventually the overlay could advertise some more useful shortcuts.

**Comment by ppot** [comment]
Fixed in #1287
