### ISSUE TITLE
Splitting more than once doesn't work on Linux

### ISSUE THREAD

**Issue by cjb** [zeit/hyper#816]
Well, this is odd -- I can split vertically, and I can split horizontally, but I can't (e.g.) split horizontally and then vertically.  Happening for anyone else?

**Comment by cjb** [comment]
Ah, it looks like this is caused by the `hypertile` plugin somehow.  If I don't load that, it works.

**Comment by flybayer** [comment]
Yeah, it's working fine for me :)

**Comment by cjb** [comment]
I tried watching in devtools while doing splits, but there's no output there at all.  If I do:

* split horizontally
* close the split
* try to split horizontally again (same thing that just worked..)

then that doesn't happen either.  So it looks like the bug is "I can do one split, and then no more for the rest of the lifetime of Hyper".

**Comment by flybayer** [comment]
Odd! Since this is a plugin-specific issue, it's probably better to close this and create one here:
https://github.com/danprince/hypertile/issues/new
