### ISSUE TITLE
Brew Cask formula broken after name change 

### ISSUE THREAD

**Issue by nhejazi** [zeit/hyper#824]
It seems like the name change from HyperTerm to Hyper has broken the [Brew Cask](http://caskroom.io) formula -- specifically, it looks like `brew cask install hyperterm` points to v0.7.1, while `brew cask install hyper` doesn't seem to install the correct package (i.e., I'm now unable to use HyperTerm). Any other cases of this happening and/or possible fixes? Should note that I am unsure of whether this is a side-effect of a recent upgrade to macOS Sierra. Apologies if this is a duplicate issue.

**Comment by matheuss** [comment]
@nhejazi thanks for the report! But I'm afraid that this is an upstream issue. Cask is out of our control – you should open an issue on their issue tracker 😄

**Comment by ekmartin** [comment]
@nhejazi `brew cask install hyper` works for me, did you run `brew cask update` first?

**Comment by nhejazi** [comment]
@ekmartin Thanks for verifying. I've run `brew cask update` and of course `brew cask install hyper`, but accessing the (newly) installed Hyper app doesn't seem to work. Not sure what else might be causing a weird issue like this on my machine.

**Comment by ekmartin** [comment]
What happens if you do `open /usr/local/Caskroom/hyper/0.8.1/Hyper.app`?

**Comment by nhejazi** [comment]
__Tried again with:__
`brew cask uninstall hyper`
`brew cask update`
`brew cask install --force hyper`
`open /usr/local/Caskroom/hyper/0.8.1/Hyper.app`

__Result:__
`The file /usr/local/Caskroom/hyper/0.8.1/Hyper.app does not exist.`

**Comment by ekmartin** [comment]
Weird. What kind of output does the installation command produce? Also, what does `brew cask info hyper` produce?

**Comment by nhejazi** [comment]
_Output from `brew cask install --force hyper`:_
==> Downloading https://hyper-install.s3.amazonaws.com/hyper-mac.pkg
==> No checksum defined for Cask hyper, skipping verification
==> Running installer for hyper; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
🍺  hyper was successfully installed!

_Output from `brew cask info hyper`:_
hyper: latest
Hyper
https://hyper.sh/
/usr/local/Caskroom/hyper/latest (12M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/hyper.rb
==> Contents
  hyper-mac.pkg (pkg)

**Comment by matheuss** [comment]
That's not the correct Hyper 😅

**Comment by nhejazi** [comment]
Right -- so then, there is an error in the Brew Cask formula?

**Comment by matheuss** [comment]
Nope, the `hyper` Brew Cask Formula is already in use 😕

**Comment by nhejazi** [comment]
@matheuss  Although I rely on brew / brew cask, I'm rather unsure of how best to fix this such that Hyper can be available.

@ekmartin I assume this output of `brew cask info hyper` does not match yours? It seemed like the procedure was working for you, right?

**Comment by ekmartin** [comment]
Yes @nhejazi, here's my output from `brew cask info`:
![image](https://cloud.githubusercontent.com/assets/3536982/19216393/af3333f6-8d87-11e6-9b48-220c69fd0b57.png)

The Hyper cask you linked is also the correct one. It seems like your `brew cask update` might have failed, since hyper.sh was moved from cask to homebrew/core here: https://github.com/caskroom/homebrew-cask/commit/e61202dacce55518cddf0c44b4ad284ee983db8f#diff-42c65679cd3130ec2f4798fc94916f13

Maybe try reinstalling Homebrew?

**Comment by nhejazi** [comment]
Confirmed -- reinstalling Homebrew fixes the problem. @ekmartin, thanks for the help.
