### ISSUE TITLE
Most common readline keybinding don't work (ctrl-a, ctrl-e, ctrl-w etc.)

### ISSUE THREAD

**Issue by qazwsxpawel** [zeit/hyper#833]
Some of those shortcuts are just muscle memory now, so it's hard to work without them e.g. ctrl-a, -e , -w. Also ctrl-d, ctrl-u e.g. in vim for scrolling as mentioned in https://github.com/zeit/hyper/issues/187. 

Is there a way to get those passed to the terminal etc. it seems that some of them are intercepted by hyper (ctrl-u for tab switching)? Is there a way to change that behaviour? Thanks!

**Comment by ekmartin** [comment]
Are you on Linux? If so I think this might be related to our general issues with Linux hotkeys (it works as expected on macOS).

**Comment by qazwsxpawel** [comment]
@ekmartin sorry, I am on OS X El Capitan (10.11.5 (15F34)). It doesn't seem to work. Hyper Version 0.8.1 (0.8.1.737). Thanks for replying. 

So if you say it's supposed to work I will investigate further, cheers!

**Comment by qazwsxpawel** [comment]
It looks like it Karabiner (https://pqrs.org/osx/karabiner/) messing up this functionality somehow (I've got "Ubiquitous Vim Bindings" turned on). Never seen this happen before. Will have a look if I can find a workaround and post it here in case anyone is using this combo (hyper & karabiner) as well. 
Thanks for help.

**Comment by matheuss** [comment]
Closing as this works flawlessly on macOS – feel free to reopen! 😄

**Comment by jritsema** [comment]
@qazwsxpawel did you end up resolving your hyper + karabiner issue?

I have Karabiner's "Use PC Style Copy/Paste" enabled which maps ctrl+c to cmd+c and it has recently stopped working.  Wondering if hyper or electron is somehow intercepting it before karabiner can see it?

**Comment by jritsema** [comment]
I actually just resolved this by adding some additional bindings to private.xml.  Looks like hyper somehow got added to the exception list (under terminal?).

```xml
  <item>
    <name>Hyperterm: Change Ctrl+C to Cmd+C</name>
    <identifier>private.hyper_copy</identifier>
    <only>hyperterm</only>
    <autogen>__KeyToKey__ KeyCode::C, VK_CONTROL, KeyCode::C, ModifierFlag::COMMAND_L</autogen>
  </item>  

  <item>
    <name>Hyperterm: Change Ctrl+V to Cmd+V</name>
    <identifier>private.hyper_paste</identifier>
    <only>hyperterm</only>
    <autogen>__KeyToKey__ KeyCode::V, VK_CONTROL, KeyCode::V, ModifierFlag::COMMAND_L</autogen>
  </item>
```

**Comment by sato-s** [comment]
This happens to me. (Fedora 24)
Please, reopen this. I cannot live without ctrl+A

**Comment by fhdhsni** [comment]
Same here (Linux Manjaro)

**Comment by ppot** [comment]
close in #1876

**Comment by qorrect** [comment]
@jritsema Im having the same issue with the latest builds, Karabiner seems to not be remapping keys in the Hyper app - did you ever get a fix for it ?

Where is private.xml and which apps config file is that ?
