### ISSUE TITLE
nano config editor: white on white

### ISSUE THREAD

**Issue by muescha** [zeit/hyper#838]
after installation and startup i try to edit preferences, but the footer of the editor where should be the commands are white on white:

![bildschirmfoto 2016-10-10 um 18 45 49](https://cloud.githubusercontent.com/assets/184316/19243973/686aa8c0-8f1a-11e6-8885-9b57d5355daf.png)

-

Hyper 0.8.1
Electron 1.4.0
darwin x64 15.6.0

**Comment by matheuss** [comment]
#819 😅
