### ISSUE TITLE
How to modify output?

### ISSUE THREAD

**Issue by rahatarmanahmed** [zeit/hyper#84]
This project is cool, and i'm really interested in how you implemented the plugin system (I'm working on my own extensible Electron IRC client). I'm still a bit new to React/Redux so I'm sure I can learn a lot from HyperTerm.

How would you go about writing an extension that would modify the output, instead of just decorating it? I'm imagining an extension like automatically making URLs clickable. I can't imagine how to do this in a way that wouldn't conflict with other extensions.

![rahat macbook-pro-4 2016-07-15 12-04-01](https://cloud.githubusercontent.com/assets/3174006/16882368/4137abc0-4a84-11e6-9e2f-9551c3d2f891.png)

**Comment by rahatarmanahmed** [comment]
So I found out about [hyperlinks](https://github.com/zeit/hyperlinks), but the source for it involves some hella monkeypatching that I don't really understand?

**Comment by ppot** [comment]
@rahatarmanahmed Yes since it involve playing with the hterm rendering.

**Comment by rahatarmanahmed** [comment]
Was hoping there was a better solution for solution, but I am no longer interested so I'll go ahead and close this issue.
