### ISSUE TITLE
Transparency not working?

### ISSUE THREAD

**Issue by simonmeusel** [zeit/hyper#841]
I've tried to get Hyper transparent (As the release notes pointed to transparency https://github.com/zeit/hyper/releases/tag/0.8.1 ) by using the bachgroundcolor config setting, thats what i tried:
```
backgroundColor:  '#22000000' // #AARRGGBB
```
```
backgroundColor:  'rgba(0, 0, 0, 0.3)'
```
but i can't figure out how to do it.

I could't find any documentation. Nothing on https://hyper.is/#cfg about transparency.

**So is transparency currently possible, if yes, how? Or do I need a plugin?**

Version: 0.8.1 (latest release, installed via brew)

**Comment by jamox** [comment]
I've been using it successfully w/o any plugins. Have you tried restarting hyperterm after editing the opaquity. Also, do you have any plugins/themes that modify css?

**Comment by c0b41** [comment]
@simonmeusel  linux or mac?

**Comment by simonmeusel** [comment]
My plugins:
plugins: ['hyperboring'/*Modification of wow mode*/, 'hyperterm-atom-dark'/*Atom theme*/, 'hyperfull'/*Full screen start*/]
So I remove hyperterm-atom-dark and it worked, thx for the fast support 😄 

@c0b41 Mac
