### ISSUE TITLE
Plugin error: [...] Error occurred in `getTabProps`

### ISSUE THREAD

**Issue by muescha** [zeit/hyper#844]
i have found 2 plugins with this error. 

[hyperterm-alternatescroll issue #5](https://github.com/lkzhao/hyperterm-alternatescroll/issues/5)

[hyperterm-tab-cwd issues #1](https://github.com/sdomino/hyperterm-tab-cwd/issues/1)

**Comment by ekmartin** [comment]
The relation between components got changed slightly in the 0.8.0 release, which means some plugins needs updates. Please track the issues you linked instead though, as this isn't a problem with Hyper's core.

**Comment by muescha** [comment]
is there an release info what changed exactly or how to fix this?

i dont see how its changed here https://github.com/zeit/hyper/compare/0.7.1...0.8.0
