### ISSUE TITLE
Split does not work

### ISSUE THREAD

**Issue by tonysickpony** [zeit/hyper#852]
Split does not work on my set up
When I hit ctrl + shift + O it creates a new line
When I hit ctrl + shift + E  it does nothing

I am running  hyper 0.8.1 with no plugins configured
```
$ uname -a
Linux  3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ekmartin** [comment]
There's a bug with Linux hotkeys at the moment, where you have to add super into any combination (i.e. the windows key). Let me know if it still doesn't work.

**Comment by fearphage** [comment]
@ekmartin Is that bug filed? Can you reference it here?

**Comment by ekmartin** [comment]
#274
