### ISSUE TITLE
Hangs when running `yarn`

### ISSUE THREAD

**Issue by bevacqua** [zeit/hyper#858]
Just so this is in `hyper`'s radar. See https://github.com/yarnpkg/yarn/issues/611.

**Comment by ekmartin** [comment]
This happened to me as well during my first yarn install, but I can't seem to reproduce it afterwards (even with a fresh yarn installation and `.yarn` and `.yarn_cache` deleted). Strange!

**Comment by rauchg** [comment]
Could be emojis?

**Comment by rauchg** [comment]
Or maybe the refresh rate on the progress bar?

**Comment by bevacqua** [comment]
Probably has to do with unicode

**Comment by iam4x** [comment]
Fresh install of yarn, ran into the same issue don't really know how to debug since JS process just freeze :(

Will try with https://github.com/zeit/hyper/pull/740 since it might be unicode related.

**Comment by iam4x** [comment]
How did you installed `yarn` ? Re-installing with `$ npm i -g yarn` fixed the issue for me!

**Comment by matheuss** [comment]
Happened to me as well when I first installed it 😩 Reinstalled it with `npm -i -g yarn` and now it works – thanks @iam4x 😄

**Comment by ynnoj** [comment]
Strangely, installing Yarn via `npm i -g yarnpkg` rather than the `curl` script recommended [here](https://yarnpkg.com/en/docs/install) fixed this for me too.

**Comment by CodeTheory** [comment]
@bevacqua @ynnoj does this still happen?

**Comment by ynnoj** [comment]
@CodeTheory I'm using `yarn` daily with Hyper now with zero issues.

**Comment by CodeTheory** [comment]
Thanks @ynnoj!
