### ISSUE TITLE
Selecting pane on blurred window requires two clicks

### ISSUE THREAD

**Issue by jacob-israel-turner** [zeit/hyper#861]
I use three screens, and constantly jump between them.  When going back to Hyper, I often want to use a different pane than I last had selected.  On first click, the last active pane is selected.  Only on the second click is the new pane (on which I clicked) active.

If this seems like an easy-ish fix, I'd love to submit a PR.

**Comment by kevinSuttle** [comment]
I wonder if this is related #897
