### ISSUE TITLE
possible memory leak in 0.8.1

### ISSUE THREAD

**Issue by curioussavage** [zeit/hyper#863]
My machine was running hot and I noticed monitor showed hyper using 20gb of memory. Not sure how to repro right now. I can remove this issue if this is unhelpful. Using up arrow to look at my history it doesn't look like i was running anything. I had just tried out the yarn JS package manager but it wasn't running. Is there somewhere I can find logs?
## 

Hyper 0.8.1
Electron 1.4.0
darwin x64 14.5.0

**Comment by black-snow** [comment]
Atom eats up all my RAM as well - guess it's a general issue w/ electron atm.

**Comment by Cl1608Ho** [comment]
can this be closed?

we are on 1.3.3 now, and i believe there ain't a such major leak
