### ISSUE TITLE
How to start a new tab or hyper.app with a certain number of panes

### ISSUE THREAD

**Issue by koresar** [zeit/hyper#865]
It would be great to open Hyper.app (or just a tab) with panes predefined (in a config/JSON file?).

Is there any (hacky?) way to do it?

UPD:
I'm thinking of something like `showPreferences()`
https://github.com/zeit/hyper/blob/7e71bf356b3df717316427fb3744320afdd6aba2/lib/actions/ui.js#L203
but customizable.

**Comment by OJFord** [comment]
Have you seen [the extensions API](https://hyper.is/#extensions-api)? I think that would be the way to go - hook onto `onApp` (or `onWindow`) and load new ones.

**Comment by ppot** [comment]
The onApp and onWindow don't provide such functionality. I'm currently working on this. As of the same time session memorization.

**Comment by ppot** [comment]
@koresar  You can still check [#617] for window creation.
```
'use strict';
const { globalShortcut } = require('electron');
exports.onApp = (app) => {
      app.createWindow(undefined,{
            position: [50,50], 
            size: [540,200]
      });
      app.createWindow(undefined, {
          position: [600,50], 
          size: [540,200]
      });
      app.createWindow(undefined, {
          position: [50,260], 
          size: [540,200]
      });
      app.createWindow(undefined, {
          position: [600,260], 
          size: [540,500]
      });
    });
};
```
