### ISSUE TITLE
Lower Window Opacity? 

### ISSUE THREAD

**Issue by khayyamsaleem** [zeit/hyper#87]
I usually use a transparent terminal. Is something like that possible for hyperterm? I know that CSS allows for lowering opacity, but I'm not sure where I would put that property.

**Comment by michaelmior** [comment]
This discussion might be helpful [electron/electron#381](https://github.com/electron/electron/issues/381).

**Comment by marcbachmann** [comment]
Looks like transparency is working on mac using hex colors with alpha transparency:
`#[alpha transparency code][hex color code]`
https://gist.github.com/marcbachmann/18df2187b3d1693a43ee60ccbfeab096#file-hyperterm-js-L16

<img width="578" alt="screen shot 2016-07-16 at 9 13 50 pm" src="https://cloud.githubusercontent.com/assets/431376/16896676/45837d5a-4b9a-11e6-9b4a-d57926cf33ee.png">

**Comment by hhsnopek** [comment]
@marcbachmann your config doesn't produce the same results locally on my machine

**Comment by bjankord** [comment]
I've set `backgroundColor: '#DD0a1a1f',` in my config. When I launch hyperterm on a fresh start, the transparency doesn't work, but if I do a full refresh after opening it, the transparency works.

**Comment by jaydson** [comment]
Anyone manage to get transparent background on Linux?

**Comment by leo** [comment]
Works with latest release!

**Comment by c0b41** [comment]
@leo Linux not working   `--enable-transparent-visuals --disable-gpu`   Ref: [Electron Docs](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#limitations)

**Comment by jacksonSingleton** [comment]
M
Few faffvV x c

fJackson Singleton
D.C. Did

**Comment by alexmarmon** [comment]
rgba colors are working with 0.8.1 on MacOS Sierra:

<img width="884" alt="screen shot 2016-10-10 at 3 17 15 pm" src="https://cloud.githubusercontent.com/assets/17775646/19252961/b844c20e-8efc-11e6-877d-5829b0669fb5.png">

**Comment by khayyamsaleem** [comment]
The transparency works, but there's occasionally ghosting from the last text that was in the terminal. Resizing the window fixes the problem, but I don't know what kind of bug this is.

**Comment by NekR** [comment]
`rgba` works fine on El Capitan too for me, but only when I don't use any themes. When I use themes they override the background.

**Comment by LeoAJ** [comment]
Is there any way to make background transparent along with the theme ? Thanks.

**Comment by pertrai1** [comment]
yes unfortunately I am only able to get the transparency to work when not using a theme. I look forward to finding out how this can be done when using a theme.

**Comment by LeoAJ** [comment]
I was able to hack into my theme's config in `.hyper_plugins/node_modules/` to make the background transparent by using `rgba`.

**Comment by pertrai1** [comment]
I was able to get it to work as I stated above but the only thing that sucks is that I lose the transparency when I am using vim

**Comment by alexandernst** [comment]
Is there a way to force transparent background no matter what the theme (or vim/nano/whatever) dictates? Something like `background-color: #282828; background-transparency: 70% !important;`

**Comment by pertrai1** [comment]
@alexandernst Yeah I tried that and did not have success when I changed `.hyper.js` config. I hope someone does come up with a solution for transparency when it comes to using vim in Hyper

**Comment by alexmarmon** [comment]
Hey guys,

It looks like V1.0.0 has a new vibrancy feature. I actually wasn't able to get it working but I think it's what most of us are looking for. 

https://github.com/zeit/hyper/releases

**Comment by pertrai1** [comment]
@alexmarmon yeah I was not able to get it working either. I added it and used rgba for opacity on background and no luck.

**Comment by tairabiteru** [comment]
Sorry, I'm a bit confused, is transparency working on Linux now or not? I'm running Ubuntu 16.04 and it seems to not be working...

**Comment by JarnoNijboer** [comment]
@tairabiteru Nope, it's only working on macOS. Electron and transparency isn't working great on either Linux and Windows, and there are several [limitations](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#limitations).

**Comment by adrianoresende** [comment]
@JarnoNijboer but I use macOS Sierra and not work for me 
![image](https://cloud.githubusercontent.com/assets/798755/23089327/3981018e-f56e-11e6-82fb-19339da897e2.png)

**Comment by dbarrett24** [comment]
I know you're using zsh as a terminal, but Has anyone made a hyper plugin that shows the side arrow in the screen shot above?

**Comment by mtslzr** [comment]
Also experiencing this issue. Latest version (1.3.1.1628) on macOS Sierra (10.12.4). Transparency only works with backgroundColor without a theme. As soon as I install a theme, it's gone. :(

**Comment by martmists** [comment]
Same issue on Antergos (4.11.3-1-ARCH), MATE DE. Transparency does not seem to work on latest version, tried both rgba as well as hex for backgroundColor, as well as hyper-transparency. Result: background is still black, no transparency at all.

**Comment by aequasi** [comment]
Same issue on macOS (10.12.5 (16F73))

**Comment by wuno** [comment]
Using High Sierra I cannot get transparency to work with or without a theme.

**Comment by FaheemAlam** [comment]
I am using High Sierra and its works fine for me. `backgroundColor: 'rgba(0,0,0, 0.8)'`

**Comment by apollomusa** [comment]
macOS High Sierra (10.13.4 (17E199)) and I tried `backgroundColor: 'rgba(0,0,0, 0.8)'` and it did not work.

**Comment by martmists** [comment]
KDE, Arch Linux (all latest stable)
Cannot get transparency with `backgroundColor: 'rgba(0,0,0,0.8)'`

**Comment by albinekb** [comment]
@martmists I believe electron has dropped support for transparency on Linux & windows due to chromium issues..

**Comment by martmists** [comment]
You can force it to allow transparency by setting WindowSettings.transparent to true.

**Comment by lucleray** [comment]
I don't know about Linux, but on Windows and MacOS, `browserWindow.setOpacity` is supported.

I made a plugin using it : [hyper-opacity](https://github.com/lucleray/hyper-opacity)

**Comment by thegriffindude** [comment]
@martmists where is this WindowSettings.transparent option??

**Comment by YoungElPaso** [comment]
This is a hack for Linux, but on Ubuntu 18.04 at least you can use hyper-init to set a transset value (0-1) at launch.  So, my Hyper config includes something like 'transset -a -t 0.85' which just means toggle the opacity of the active window to 85% at start up.  

This is the only workable solution for me since Electron does indeed no longer support transparency on Linux.

**Comment by sharmashubham850** [comment]
Windows users, follow these steps -:
1.) Add "hyper-opacity" to plugins array. (hyper-opacity plugin will be installed)
2.) Add property - "opacity: 0.8" (Editable)

**Comment by angelhdz** [comment]
> Windows users, follow these steps -:
> 1.) Add "hyper-opacity" to plugins array. (hyper-opacity plugin will be installed)
> 2.) Add property - "opacity: 0.8" (Editable)

Where? In the env: {} ? Or in the module exports {} as a javascript object property? Or in the css: ''  as a CSS string?

**Comment by Lateralus138** [comment]
Sorry, for the necro, but this is, of course, still an issue and there is an external solution for those who use *Gnome* desktop . You can use the *Gnome* extension '**transparent-window**'. I'm successfully using it on: `Ubuntu 20.04.1 LTS`

![ScreenShot](https://imgur.com/t5CsOq9.png)

Extension:
[https://extensions.gnome.org/extension/1454/transparent-window/](https://extensions.gnome.org/extension/1454/transparent-window/)
