### ISSUE TITLE
how to enable ligatures

### ISSUE THREAD

**Issue by tkisme** [zeit/hyper#874]
any instructions?

**Comment by dak0rn** [comment]
On 0.7.1 ligatures worked for the with [Hasklig](https://github.com/i-tu/Hasklig). After upgrading to 0.8.1, they are not shown anymore.

**Comment by iamstarkov** [comment]
there is `font-variant-ligatures: none;` defined on `<x-row />`

**Comment by iamstarkov** [comment]
to fix add this to your config

```js
    // custom css to embed in the terminal window
    termCSS: `
      x-screen x-row {
        font-variant-ligatures: initial;
        // background-color: black;
      }
    `,
```

**Comment by dak0rn** [comment]
That works, thanks for the advice!

Why has it been disabled in the first place, though?
Any disadvantages?

**Comment by iamstarkov** [comment]
> Why has it been disabled in the first place, though?

dunno, found about it from this issue also

**Comment by tkisme** [comment]
ok, now it works

**Comment by jhnsntmthy** [comment]
This seems to have broken again recently. The above fix does not work anymore. Any ideas why?

**Comment by albinekb** [comment]
See https://github.com/zeit/hyper/issues/2864#issuecomment-382430626 @jhnsntmthy
