### ISSUE TITLE
Neovim cursor support inhibited

### ISSUE THREAD

**Issue by nhejazi** [zeit/hyper#875]
The [Neovim](https://github.com/neovim/neovim) editor provides support for moving the cursor around via clicking on a region. After a recent update (at some point following Hyperterm --> Hyper), using Neovim in Hyper does not allow for the cursor to be moved around via clicking on a region -- is there some particular change in Hyper that could be contributing to this change in behavior?

Note that the (sometimes desirable) behavior of Neovim described above works fine in iTerm currently. My apologies in advance if this is a duplicate issue.

**Comment by rumpelsepp** [comment]
Maybe related #846

**Comment by ekmartin** [comment]
This should be fixed in the latest release (0.8.2).
