### ISSUE TITLE
Download link for linux says "Version not found: latest"

### ISSUE THREAD

**Issue by aniyanm** [zeit/hyper#877]
While trying to download the linux version it says "Version not found: latest"
Download url : https://hyper-updates.now.sh/download/linux

**Comment by jamox** [comment]
It can be downloaded from: https://github.com/zeit/hyper/releases
The download link should be fixed shortly

**Comment by c0b41** [comment]
dups #799

**Comment by matheuss** [comment]
Thanks @c0b41 😅
