### ISSUE TITLE
copyOnSelect and clearSelection are not working on macOS Sierra 

### ISSUE THREAD

**Issue by engsan710** [zeit/hyper#878]
I have recently been experiencing a problem in which, when my mouse highlights something on the terminal, it does not copy it to the clipboard. I have uninstall and re-installed, updated the ~/.hyper.js file with:
    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: true,
    clearSelection: true
And I still see the problem. Any suggestions will be greatly appreciated.

**Comment by engsan710** [comment]
It looks like it has been fixed on Version 0.8.2 (0.8.2.850)

**Comment by jgillman** [comment]
For what it's worth, it's not working for me on 0.8.3

![image](https://cloud.githubusercontent.com/assets/172217/19535937/a766ffac-95fe-11e6-89a1-a45d3e9e429b.png)

I couldn't find `copyOnSelect: true` in any of the documentation though, only `clearSelection`.
