### ISSUE TITLE
Beachballs and stops responding

### ISSUE THREAD

**Issue by dpo** [zeit/hyper#881]
So in one tab, I'm running an intense compilation job, and all Hyper tabs and windows stop responding:

![screen shot 2016-10-14 at 18 30 57](https://cloud.githubusercontent.com/assets/38760/19404550/b8367918-923c-11e6-88c8-4f3b3899995d.png)

Other apps are ok and usable. This is OSX 10.9.

**Comment by dkast** [comment]
Same here, running [yarn](https://yarnpkg.com) installing a project trough a package.json file on macOS 10.12. Hyper become unresponsive. Same operation on Terminal, everything works fine.

**Comment by parro-it** [comment]
Could be related to #858?

**Comment by MatthiasWinkelmann** [comment]
This is probably #687 – See the stats in https://github.com/zeit/hyper/issues/687#issuecomment-268141860: Hyper Helper can grow to 15GB of RAM usage.

**Comment by timothyis** [comment]
I feel like this could be due to performance issues that were resolved with the Xterm.js switch, and since this issue hasn't had activity in well over a year, I'm going to close it. Thanks for the submission though!
