### ISSUE TITLE
Configure fonts with attribute tuples

### ISSUE THREAD

**Issue by jwhitley** [zeit/hyper#885]
I agree with #175 (add font weight to config), but I'll add to this rather more radical thought: font weight doesn't sensibly apply across a variety of fonts, especially when we're talking fallbacks.  What's really needed are per-face attribute tuples:

``` javascript
{
  fontSize: 12,  // default size
  fonts: [
      { name: 'Source Code Pro', weight: 200, size: 14 }, // ExtraLight weight for this font @ 14pt
      { name: 'Menlo', weight: 400 },  // 400 weight for Menlo, default size
      { name: 'monospace' } // all defaults for monospace fallback.  Who knows what we've got?
    ],
}
```

This also makes a sort of sense in that often these kinds of fallbacks can be used to implicitly specify cross-platform defaults.  E.g. so Hyper behaves well on a stock [Linux, macOS, Windows] system, without any specialized fonts (Source Code Pro, etc.) installed.

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
