### ISSUE TITLE
Command preceded by a space

### ISSUE THREAD

**Issue by dpo** [zeit/hyper#887]
This is a small thing and technically, you could say it's an input error but both Terminal and iTerm accept it:
```bash
$  ls  # there's an accidental space prefixing the command
bash:  ls: command not found
```

**Comment by jamox** [comment]
I can't reproduce it; it seems to be working just fine and properly passing the command with prepended spaces. 
Tried it on osx 10.12, hyper: 0.8.2

it's not an input error either, since sometimes prepending command with scapes can be intentional, like with: `HISTCONTROL=ignorespace`

**Comment by dpo** [comment]
Thank you. Now I can't reproduce it either. Something else must have happened. Sorry for the noise.
