### ISSUE TITLE
Switch split pane with shortcut

### ISSUE THREAD

**Issue by Jonas-Drotleff** [zeit/hyper#890]
When terminal windows is divided, you should be able to switch the prompts with a key combination.

**Comment by jamox** [comment]
![like these:](https://cloud.githubusercontent.com/assets/1354151/19419382/fc15445e-93de-11e6-8b8b-8bb40ecf95e3.jpg)

**Comment by Jonas-Drotleff** [comment]
Oups, thanks anyways

**Comment by jrmlstfMt** [comment]
The two shortcuts to switch between previous/next panes doesn't work on Windows 10 and Hyper 1.0.1.

It triggers the switch between open programs https://support.microsoft.com/en-us/help/126449/keyboard-shortcuts-for-windows (ALT+TAB).

**Comment by Fastidious** [comment]
Forgive me for commenting on something as old as this, but my question relates. It is great to have the keyboard shortcuts, but is there a way to make panes on focus via mouse hover (like iTerm2 does)?

**Comment by ppot** [comment]
@albinekb Here your plugin request!

**Comment by chabou** [comment]
I begun to find a way to add this feature to huper-pane.

**Comment by chabou** [comment]
Done
https://github.com/chabou/hyper-pane/releases/tag/v1.1.0

**Comment by abigger87** [comment]
For anyone still wondering, the commands were updated:
<img width="322" alt="selectpane" src="https://user-images.githubusercontent.com/21288394/43083330-3dc0fe58-8e64-11e8-90d2-e0bd374fec15.png">
<img width="324" alt="selecttab" src="https://user-images.githubusercontent.com/21288394/43083331-3dd22fd4-8e64-11e8-8f4c-f8d757c2fc95.png">
