### ISSUE TITLE
Cannot insert ~

### ISSUE THREAD

**Issue by pedrorijo91** [zeit/hyper#891]
Mac OS Yosemite
version 10.10.5 (14F1909)

keyboard input source: Portuguese
system language: EN (UK)

When I type `~` I get a `'` and `shift + ~` makes a `"`

All the other special char keys work as expected on a portuguese keyboard

Portuguese layout: https://cdn.shopify.com/s/files/1/0810/3669/files/mac-portuguese-keyboard_1024x1024.png?9241482625966586546

UK layout: http://kb.parallels.com/Attachments/19485/Images/wireless-british.jpg

**Comment by pcalves** [comment]
You should subscribe to #29. 🙌 Also #214 (WIP right now) is supposed to fix this issue. It's [one of the goals](https://zeit.co/blog/the-hyper-plan) for v0.9.0 so for now we just have to hang tight.

**Comment by pedrorijo91** [comment]
thanks! feel free to close this issue since it is already reported on #29
