### ISSUE TITLE
Restart on update popup closes app but not restarting with new version

### ISSUE THREAD

**Issue by straku** [zeit/hyper#899]
Hi, thanks for hyper, it's awesome!

Unfortunately I've stumbled upon an issue during update. When there is update available I'm seeing update popup with possibility to click restart to launch hyper updated to new version. When I click on restart hyper closes and nothing else is happening. I have to launch it manually and version is unchanged.

I am working on macOS Sierra 10.12, hyper version is 0.8.2 and tries to update to version 0.8.3.

Did anyone else have any issues resembling this one? Do you know what can be causing it?

**Comment by brandonweiss** [comment]
Happened to me too.

**Comment by arielschiavoni** [comment]
I have the exact same problem while trying to update from v1.0.0 to v1.0.1.

**Comment by timothyis** [comment]
Since it's been over a year since we've had activity on this issue, I'm going to close it 🙏

Please let us know if the problem still exists, although we might not be able to help much due to the functionality belonging to upstream modules.
