### ISSUE TITLE
linux download link seems to be broken

### ISSUE THREAD

**Issue by Thebigbignooby** [zeit/hyper#900]
https://hyper-updates.now.sh/download/linux

results in 

404
This page could not be found.

**Comment by jamo** [comment]
While that url is being fixed you may download it from here: https://github.com/zeit/hyper/releases/latest

**Comment by Thebigbignooby** [comment]
any idea when the windows version will be out ?

**Comment by c0b41** [comment]
dups #799

**Comment by matheuss** [comment]
#799
