### ISSUE TITLE
Plugins not updating OSX

### ISSUE THREAD

**Issue by Fenwick17** [zeit/hyper#902]
Used homebrew to install hyperterm on my mac, when searching for hyperterm two apps are listed.
Hyper.app and HyperTerm.app.
When I go to add a plugin, for example a theme I get 'Update error check failed'.

**Comment by jamo** [comment]
You should be using the Hyper.app and remove Hyperterm - the project got renamed a while back: https://zeit.co/blog/the-hyper-plan

**Comment by Fenwick17** [comment]
Ah that explains it, HyperTerm remained from a previous install. Issue fixed
Thanks.
