### ISSUE TITLE
Use a local .hyper.js config file and and .hyper_plugins directory in DEV

### ISSUE THREAD

**Issue by chabou** [zeit/hyper#903]
It would be great to optionally have a config file and a plugin directory in root project directory.
It will offer the possibility to develop features or plugins, and continue to use a Hyper.app stable version for daily tasks.

**Comment by ppot** [comment]
Should totally do a differentiation between hyper.app and DEV. It's one reason why I don't use hyper and use ITerm2 for DEV.
