### ISSUE TITLE
Linux Copy/Paste. Blank preferences

### ISSUE THREAD

**Issue by Fenwick17** [zeit/hyper#909]
On Ubuntu 16.04 I am unable to copy via selection, and the command ctrl + c as listed does not copy, only terminates the current running task in the terminal. 
Any way to implement copy on selection? 
Edit preferences shows blank, and the text at the bottom is also not visible. And the only way to exit is closing the tab. ![Preferences](https://s11.postimg.org/95lv8g6mr/afenwick_afenwick_001.png)
Currently not using any theme.

**Comment by ekmartin** [comment]
You can enable copy on selection by putting `copyOnSelect` in your config.

**Comment by Fenwick17** [comment]
Thank you, was getting jumbled up by hyper.js and preferences.
