### ISSUE TITLE
Can't use r.js (RequireJS)

### ISSUE THREAD

**Issue by markzrt** [zeit/hyper#910]
when I write r.js or like the prompt disappears, and then displays an error
## 

HyperTerm 0.7.1
Electron 1.2.8
darwin x64 16.0.0

**Comment by ekmartin** [comment]
This is because it's recognized as a website URL. We should probably have some kind of check to make sure that the URL isn't a valid command before opening it in a webview.

**Comment by markzrt** [comment]
Exactly, you're absolutely right...

**Comment by rauchg** [comment]
URL handling has been vastly [improved on `1.0.1`](https://twitter.com/rauchg/status/815010770618437632)! Thanks for the reports 🙏
