### ISSUE TITLE
Window Title Flickers Between 'bash' and 'sh'

### ISSUE THREAD

**Issue by Miserlou** [zeit/hyper#912]
Weird one. Every second, the title bar flashes between 'sh' and 'bash'. Super annoying. 

Related to #699 likely. 

I launched Zeit, I assume it chose `sh` as the default shell because of #699, then called `bash`, now the window flickers.

**Comment by parro-it** [comment]
Should be solved by #892

**Comment by ppot** [comment]
@matheuss Can be closed since #892

**Comment by matheuss** [comment]
Thank you @ppot 🙇
