### ISSUE TITLE
Fira Code ligatures not showing

### ISSUE THREAD

**Issue by ericmarkmartin** [zeit/hyper#914]
After updating Hyperterm to 0.8.3 through homebrew cask, the Fira Code font's ligatures don't work, even though the font itself is being used
![screen shot 2016-10-20 at 11 49 09 pm](https://cloud.githubusercontent.com/assets/5509414/19586077/e192ce32-971f-11e6-9bc4-3a554968fa9c.png)

In the above screenshot, the 0 especially gives away that FiraCode is being used and not Menlo.

![screen shot 2016-10-20 at 11 51 50 pm](https://cloud.githubusercontent.com/assets/5509414/19586105/36c0dc3c-9720-11e6-9f81-79a47a095c0a.png)

Yet as you can see from the arrow function above, the ligatures are not being used.

**Comment by 0x6c7862** [comment]
This CSS will re-enable ligatures:

```css
x-screen x-row { font-variant-ligatures: contextual; }
```

**Comment by wolverian** [comment]
FWIW, even if I add the CSS to Hyper's config (the `css` key), the `x-row` elements don't get that style. 🤔

**Comment by dak0rn** [comment]
As suggested in another issue, I added the following to the configuration to make ligatures work. I am using Hasklig instead of Fira Code, though, but I expect the font not to be the issue.

![screen shot 2016-10-21 at 12 31 23](https://cloud.githubusercontent.com/assets/3854533/19595490/6ba3d3e0-978a-11e6-9aad-53a44ccb21ca.png)

**Comment by iamstarkov** [comment]
definitely a bug, but also a dup #874

**Comment by ericmarkmartin** [comment]
Thanks for the replies. Unfortunately I didn't see that issue since because it was marked closed, not a bug, and didn't contain the word Fira.

**Comment by mjswensen** [comment]
Thanks for the workaround, @0x6c7862 and @dak0rn ! Works great for now.

I didn't see any code in this repo explicitly turning them off so my guess is that a dependency upstream somewhere changed and broke this behavior.

I'd vote for ligatures being enabled by default unless there's a good reason not to. People coming to a terminal based on JS, HTML, and CSS will [expect ligatures to work out of the box](https://twitter.com/jordwalke/status/769424509501792257).

**Comment by ccorcos** [comment]
Hmm. I wasn't able to get it to work:

![image](https://cloud.githubusercontent.com/assets/1794527/20814717/b2b2f49a-b7cf-11e6-90d6-ee80956fa70c.png)

![image](https://cloud.githubusercontent.com/assets/1794527/20814724/be6fc6e6-b7cf-11e6-8b94-cbd06fa6e4ec.png)

**Comment by fczuardi** [comment]
@ccorcos the relevant lines:

```javascript
    // font family with optional fallbacks
    fontFamily: '"Fira Code", "Apple Chancery", Helvetica, Menlo, "DejaVu Sans Mono", "Lucida Console", monospace',

    // custom css to embed in the terminal window
    termCSS: `
        x-screen x-row {
            font-variant-ligatures: initial;
        }
    `,

```

**Comment by ccorcos** [comment]
wait, now its working! :)

**Comment by gluons** [comment]
Is it posible to add **a simple `boolean` option** to trigger this feature?

**Comment by thasmo** [comment]
`enableLigatures` pls :D

**Comment by matheuss** [comment]
It is @gluons

**Comment by Qix-** [comment]
Just curious; why are ligatures disabled by default? Is there an inherent overhead?

**Comment by timneutkens** [comment]
Just published https://github.com/timneutkens/hyper-ligatures. Guess we can close the issue 👍

**Comment by fleischie** [comment]
@timneutkens Just fyi (you probably already saw, but for completeness sake). As Hyper v2 uses a different terminal emulation, that is using different tags/classNames as rows, there should be a change to your plugin to accommodate for this. (I created a PR on your repo with the changes I think are necessary to support the new implementation as well).

:smile:

**Comment by albinekb** [comment]
@timneutkens this will break in future updates of hyper. (More exactly, when we change to xterm 3, based on canvas) you should state that in your readme 👍

**Comment by timneutkens** [comment]
@albinekb by then lets add ligatures built in ;p

**Comment by SanketDG** [comment]
Does the above solution work with the very latest pre release version?

**Comment by albinekb** [comment]
Nope @SanketDG hyper won't have support for ligatures until xterm3+ does 👍

**Comment by iamstarkov** [comment]
=( i will miss ligatures
<img width="445" alt="screen shot 2018-01-18 at 9 49 59 pm" src="https://user-images.githubusercontent.com/559321/35120815-a22e1e6e-fc99-11e7-8555-707ef42237e2.png">

**Comment by caiocutrim** [comment]
no working for me in Ubuntu and hyper 1.4.8

**Comment by Xunnamius** [comment]
This is incredibly sad, but at least they show up in Sublime so I'm not too disappointed 😄 (confirmed not working as of 2.0.0-11)

**Comment by Qix-** [comment]
Ref xtermjs/xterm.js#958

**Comment by JCMais** [comment]
addon for xterm with ligatures here https://github.com/xtermjs/xterm-addon-ligatures (from above issue)

**Comment by pokatomnik** [comment]
Win 10, the latest hyper.app build (I have just updated It from the stable channel), ligatures does not appear (i.e. `=>` does not show as an arrow)

**Comment by williamleiby** [comment]
latest hyper update on macOS Mojave, font ligatures don't work. Would like a useful way of implementing them.

**Comment by Neo42** [comment]
https://github.com/zeit/hyper/issues/2793

Try the method for this issue. Worked perfectly for me.

**Comment by aadibajpai** [comment]
> Win 10, the latest hyper.app build (I have just updated It from the stable channel), ligatures does not appear (i.e. `=>` does not show as an arrow)

did you find a fix?

**Comment by dankolesnikov** [comment]
Any updates on this? Just discovered Fira Code and really want to get it working on Hyper.

**Comment by bet4it** [comment]
@dankolesnikov #3607
