### ISSUE TITLE
Prevent CMD+R from refreshing and losing progress (or remove refresh)

### ISSUE THREAD

**Issue by bevacqua** [zeit/hyper#921]
I sometimes alt+tab into Hyper and accidentally refresh, which kills all my tabs, running process, and is generally super painful. Could we have an option that asks whether you're sure you want to reload?

**Comment by ppot** [comment]
@matheuss This should be included as part as the warn upon quit.

**Comment by jbergstroem** [comment]
I think the "hold to quit" is a nice pattern. I've seen websites have a small progressbar at the bottom of the notification to show "how long". Neat and informative.

**Comment by tblaisot** [comment]
Same thing for me. Since 1.0.0 I can't use reverse-i-search because Ctrl+R reload plugins
It is very painfull

**Comment by eryshev** [comment]
@tblaisot Me too, is it by design or should we create an issue?

**Comment by tblaisot** [comment]
@eryshev I think it is by design from commit #1058

**Comment by tyrsius** [comment]
This problem wouldnt be nearly as bad if reloading re-opened the same tabs

**Comment by rbudiharso** [comment]
+1 on missing reverse-i-search

**Comment by brunoqueiros** [comment]
https://github.com/zeit/hyper/issues/1178

**Comment by smpetrey** [comment]
Reverse-i-search would be 💯

**Comment by Ademord** [comment]
+1, still waiting for this

**Comment by sreetamdas** [comment]
+1, make this happen already.

**Comment by vmariano** [comment]
+1

**Comment by smpetrey** [comment]
Still holding out for a “hold to quit” pattern.

**Comment by thisisalessandro** [comment]
+1

**Comment by themaxsandelin** [comment]
Please god someone fix this.

**Comment by juliaovod** [comment]
+ 1

**Comment by CodeSyl** [comment]
+1

**Comment by timothyis** [comment]
We're planning to remove refresh from the app. It currently even breaks the app. 😓

**Comment by nathancocp** [comment]
I hope this is still going to happen. 

This just bit me. OSX has a nice feature where I can scroll my browser without it being the active window, but after a minute I forget this and when I go to reload the page I reload my terminal instead and lose my panes and that's no good. 

Is there a good way to recover from this quickly or do I just continue reopening everything manually? I'd be happy if my CMD+R inputs were sent to a blackhole rather than Hyper.

**Comment by jonathanandrewsuk** [comment]
I just changed my configuration to this and it disables all keymaps (including reload).

`  keymaps: {
    '': 'cmd+shift+r',
  },`

I'm assuming it's not valid format and stops the object from being mapped. The trade off is worth it for me as I didn't use any keymaps anyway.

### Before:
<img width="457" alt="screen shot 2018-10-25 at 9 40 31 am" src="https://user-images.githubusercontent.com/19194646/47504351-1366b100-d83a-11e8-8451-0ef5f53ed81a.png">

### After:
<img width="458" alt="screen shot 2018-10-25 at 9 41 22 am" src="https://user-images.githubusercontent.com/19194646/47504389-2bd6cb80-d83a-11e8-9271-0d0c0c26fae9.png">

**Comment by olsgreen** [comment]
This has hurt me so many times that I've:

1) Submitted a [PR to change the bindings](#3277), even if the reloads are going to be removed 'soon'.
2) Created a plugin that blocks `Cmd+R` while any windows are active... (add [hyper-kill-cmd-r](https://github.com/olsgreen/hyper-kill-cmd-r) to your plugin stack)

**Comment by jonathanandrewsuk** [comment]
For now, I've changed my reload keymaps in the preferences file to something I'm not going to press by accident, e.g:

`  keymaps: {
    'window:reload': 'cmd+9',
    'window:reloadFull': 'cmd+shift+9',
  },`

<img width="451" alt="screen shot 2018-11-01 at 9 25 49 am" src="https://user-images.githubusercontent.com/19194646/47854458-25a39a80-ddb8-11e8-9a3a-2a856ba8affa.png">

Anytime I do press `cmd+r` or `cmd+shift+r`when active on hyper it just goes into a black hole.

**Comment by olsgreen** [comment]
@jonathanandrewsuk For some strange reason, I couldn't get that to work last night. In the light of this morning, it does and is the best stop-gap until the default bindings are changed.

**Comment by emiljohansson** [comment]
@jonathanandrewsuk thanks for the tip! leaving them blank also worked for me

`keymaps: { 'window:reload': '', 'window:reloadFull': '', },`

**Comment by juliaovod** [comment]
@jonathanandrewsuk Thanks!
