### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by kartsims** [zeit/hyper#922]
I would like to contribute but when I clone the repo I see things that just slow me down in my development process and to get a good understanding of the project 😢

First thing first, **I believe the code should be linted**. Don't you ? I mean such a big project in an inconsistent code style (it is not really *that* inconsistent but I am just making a point : ) who codes JS without a linter nowadays ? There are some eslint-related comments here and there so I think it has been in the past and is not anymore.

My proposal :

- re-install ESLint by dropping the `.eslintrc` file
- add a linting NPM script : `npm run lint`
- fix existing lint errors

What do you guys think ?

The point is to make it easier for a new contributor to write some code.

**Comment by matheuss** [comment]
@kartsims we already have a linter 😄 We're using [XO](https://github.com/sindresorhus/xo).

For now we don't have a `lint` script, but I think we could accept one 😄 Feel free to send a PR – it'd be `"lint": "xo"` 💯

**Comment by kartsims** [comment]
Lol okayyy! :)
