### ISSUE TITLE
Can't download Hyper for Linux, link broken

### ISSUE THREAD

**Issue by Coolnesss** [zeit/hyper#926]
- [ ] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Hyper.app version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

The page linked on https://hyper.is that is supposed to be the download link for Linux seems broken: https://hyper-updates.now.sh/download/linux says

```Version not found: latest```

**Comment by matheuss** [comment]
#799 😄
