### ISSUE TITLE
Entering tilde (~) doesn't work on scandinavian (Finnish/Swedish) keyboard layout

### ISSUE THREAD

**Issue by pakastin** [zeit/hyper#930]
When I press alt + ^ on my Finnish keyboard (tilde), nothing happens. Finnish and Swedish Mac keyboards are the same. I'm using the latest MacOS with latest Hyper.app. It returned the following error to the console (cloned the master branch and ran `npm install && npm start`:

![nayttokuva 2016-10-24 kello 19 53 33](https://cloud.githubusercontent.com/assets/1475902/19655158/b2284986-9a23-11e6-87ab-63b6cdb54e5f.png)

Here's the FIN/SWE -layout:

![](https://glyptodon.org/jira/secure/attachment/12558/KB_0027_Swedish.png)

**Comment by CodeTheory** [comment]
#29.

**Comment by lachi001** [comment]
Thank you
