### ISSUE TITLE
Pin hyper to screen

### ISSUE THREAD

**Issue by janstieler** [zeit/hyper#934]
Hi,

is there a possibility to pinn hyper on the screen like TotalTerminal?
So that I can bring it to front with an shortcut.

Cheers

**Comment by CodeTheory** [comment]
It can be with a plugin. https://www.npmjs.com/package/hyperterm-overlay
Is that what you're looking for?

**Comment by janstieler** [comment]
Hi,
thats exactly what I'm searching for. Thanks!
Maybe you can help me to install the plugin.
If I add the npm to the hyper config and also the overlay configs I can't see any changes.
If I restart hyper the config will be set back to standard and all my personal settings are gone. What I'm doing wrong?

**Comment by CodeTheory** [comment]
Sorry for the delay @janstieler, I'm quite ill at the moment. I assume you've figured the installation query yourself?

**Comment by janstieler** [comment]
Hey,
no problem @CodeTheory, a delay of two hours are not a real delay :).
I don't know whats doing on. After it kills self the config I added the NPM and config for hyperterm-overlay again and hyper.js shows that it installed the npm. I reloaded it and it worked.
But hyperterm-overlay have a small bug if you use it with [menubar or hotkey](https://github.com/rickgbw/hyperterm-overlay/issues/17).
