### ISSUE TITLE
hyper brand

### ISSUE THREAD

**Issue by carlosvigil** [zeit/hyper#936]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

<img width="590" alt="screen shot 2016-10-25 at 8 52 02 pm" src="https://cloud.githubusercontent.com/assets/18217279/19709522/25bfd392-9af5-11e6-9d5c-55ec9319f149.png">

found on [this site]
(https://mic.com/articles/157365/pokemon-go-nest-location-updates-and-changes-players-tip-off-new-migration#.aJr8PFHCa)

it's an app for video things

**Comment by matheuss** [comment]
⁉️⁉️⁉️
