### ISSUE TITLE
"path_helper" is shown in place of shell name

### ISSUE THREAD

**Issue by fvgs** [zeit/hyper#937]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: 0.8.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: The default, vanilla config, no modifications
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is vanilla
## Issue

I just installed Hyper.app and everything is as vanilla as it gets. I've observed that sometimes, when I launch the app, instead of displaying the name of my shell (i.e. zsh) at the top of the window, it displays **path_helper**. This doesn't always happen. But it seems to occur occasionally when the app is first launched. Unfortunately, I'm not aware of a more deterministic way to reproduce the issue other than restarting the app multiple times.

**Comment by BenMagyar** [comment]
This issue no longer seems to exist in master (I had the same issue!). #892 and a bunch of other commits reworked the tab titles so this no longer entirely applies/is resolved.

**Comment by fvgs** [comment]
I'm on the latest release, not master, so I'll take your word for it. Thanks @BenMagyar!
