### ISSUE TITLE
[macos] Quit when last window is closed

### ISSUE THREAD

**Issue by ravinggenius** [zeit/hyper#939]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- **OS version and name**: macOS Sierra 10.12.1
- **Hyper.app version**: Version 0.7.1 (0.7.1.36)
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: https://gist.github.com/ravinggenius/332fa83fb8d3cff394c12f4c1547d6c7
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: N/A
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

Hyperterm doesn't quit when last tab/window is closed. Other terminals (Terminal, iTerm2) have an option in the Preferences to quit when closing the final window. As I am used to this behavior, I would like it it Hyperterm as well, optionally if need be.

---

Edit: Just verified this still applies to latest version (0.8.3 (0.8.3.873)).

**Comment by CodeTheory** [comment]
I'd agree with optionally! @rauchg @leo @matheuss Thoughts?

**Comment by ppot** [comment]
It can be done if it's an option. But only an option. Or as a plugin. Like hyper-quit

**Comment by matheuss** [comment]
I also agree that it should be **opt-in** since it's the opposite of the standard on macOS 😄

**Comment by OJFord** [comment]
It's non-standard, but is it actually harmful to make it opt-*out*, or even just 'the way it is, deal'?

I can't imagine anyone actually _liking_ the standard behaviour on macOS - indifferent, sure, but is there any benefit at all?

**Comment by trahma** [comment]
I'm a fan of it if it's opt-in.  I'm one of those that actually will close my windows and re-open a new one fresh at times.

**Comment by rauchg** [comment]
+1 for `hyper-quit` :)

**Comment by Skilgarriff** [comment]
Is there actually a hyper-quit at the moment? If not any pointers towards how I could work on this? Would really love this feature

**Comment by OJFord** [comment]
@trahma Personally any time I do that I cmd+Q (properly quit) and reopen to be sure it's completely fresh, what's the advantage of the default behaviour where it's still sort of 'there' even when 'closed'? I've genuinely never understood it in the slightest.

**Comment by matheuss** [comment]
@OJFord it's supposed to be closed since it's not something we'd like to include on Hyper itself. We're trying to triage features requests like this: it's doable as a plugin? If yes, then it's probably doesn't have a place on Hyper as a core.

+1 for `hyper-quit`, I'd use it 😄 

@Skilgarriff you probably would need to override the effect of the Redux action that's fired to remove a session 🤔

**Comment by OJFord** [comment]
> We're trying to triage features requests like this: it's doable as a plugin? If yes, then it's probably doesn't have a place on Hyper as a core.

@matheuss And yet there's a browser built-in? 😆 

Makes sense though - but maybe it would be useful to have a "potential-plugin" label, so it's clear there's nothing wrong with the idea, but it wants doing as a plugin? Then perhaps if someone fancies delving into it a bit, but isn't sure what features are being sought, they can just search `label:potential-plugin`.

**Comment by cblecker** [comment]
For anyone following this:
I prefer a terminal workflow to quit when I type "exit" on the last window as well. So I went ahead and created a plugin to do it. Issues/PRs are welcome.
https://github.com/cblecker/hyper-quit
