### ISSUE TITLE
3-finger tap to "look up" popup window appears in the wrong place

### ISSUE THREAD

**Issue by controversial** [zeit/hyper#942]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate
- **OS version and name**: macOS 10.12 Sierra
- **Hyper.app version**: 0.8.3
## Issue

I frequently touch the trackpad with three fingers while hovering over a word to bring up the "look up" menu which provides information about a word. In Hyper, this works, but the popup appears several inches below the word in question. This behavior also prevents the use of this feature on words near the bottom of the terminal.

**Comment by albinekb** [comment]
It works for me
![image](https://cloud.githubusercontent.com/assets/5027156/19850873/2d5c0714-9f5b-11e6-84e0-afd31108f2a4.png)

(Using force-touch)

**Comment by matheuss** [comment]
Works for me to 🤔

**Comment by controversial** [comment]
Hmm. I can't make it work in Hyper, Atom, or the Slack for macOS beta (my
three most commonly-used Electron apps)

**Comment by controversial** [comment]
It looks like I can perform the action for anything near the top half of the screen, but it appears several inches down on the screen. Trying for a word near the bottom fails.
![screenshot 2016-10-31 at 7 34 22 am](https://cloud.githubusercontent.com/assets/10377391/19852940/a387a476-9f3c-11e6-8403-1d0c6f7bbb6e.png)
![screenshot 2016-10-31 at 7 35 09 am](https://cloud.githubusercontent.com/assets/10377391/19852947/a5206458-9f3c-11e6-88ef-fbcfb4e73cea.png)

In each of these screenshots, the highlighted word actually appears several lines above where the popup spawns. This means I can't tap anything in or near the bottom line of the terminal window.

**Comment by matheuss** [comment]
@controversial I can reproduce 😩

**Comment by matheuss** [comment]
BTW: it's very easy to implement – https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsshowdefinitionforselection-macos

**Comment by controversial** [comment]
Ok. I'll edit the issue to match the actual issue (I only tested on the bottom half before)

**Comment by Stanzilla** [comment]
Hey there, please try again with the new Hyper v2 release and open a new issue if the problem stills exists. Thank you!
