### ISSUE TITLE
Wrong Hangul(Korean) typing and displaying problem

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [zeit/hyper#944]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS X 10.11.6**: 
- **Hyper.app 0.8.3**: 
- **The issue is reproducible in vanilla Hyper.app**

## Issue

1. Hangul characters are displayed as only initial consonant.
2. When I type in Hangul, I can't combine consonant and vowel.

Please refer follow screenshots.

![hyper](https://cloud.githubusercontent.com/assets/15520015/19834952/09b9e058-9eb9-11e6-9236-6531099e6c73.png)

<img width="834" alt="iterm" src="https://cloud.githubusercontent.com/assets/15520015/19834951/09b7ed66-9eb9-11e6-8e48-fdd5728d5537.png">

**Comment by CodeTheory** [comment]
#410.
