### ISSUE TITLE
Tab title switching between two different titles

### ISSUE THREAD

**Issue by tjgillies** [zeit/hyper#948]
When I run emacs [spacemacs]  in the terminal, the tab title switches between bash and emacs, back and forth. It's kind of annoying/distracting

-

Hyper 0.8.3
Electron 1.4.0
darwin x64 15.4.0

**Comment by OJFord** [comment]
Duplicate of #912; solved by #892.

**Comment by ppot** [comment]
@matheuss Can be closed since #892

**Comment by matheuss** [comment]
Thank you @ppot 😄
