### ISSUE TITLE
Paste from other apps does not work

### ISSUE THREAD

**Issue by kevinSuttle** [zeit/hyper#957]
1. Copy something on this page. 
2. Open Hyper
3. <kbd>⌘</kbd> + <kbd>v</kbd>

Nothing happens. 

Hyper 0.8.3
Electron 1.4.0
darwin x64 16.1.0

**Comment by kevinSuttle** [comment]
Hm. Seems intermittent. Will close until I have reproducible steps.

**Comment by ekmartin** [comment]
You might have stumbled onto this issue @kevinSuttle: https://github.com/zeit/hyper/issues/897
