### ISSUE TITLE
Use Closure instead of WebPack for better performance

### ISSUE THREAD

**Issue by somebody1234** [zeit/hyper#961]

**Comment by matheuss** [comment]
Please elaborate 🤔

**Comment by somebody1234** [comment]
@matheuss https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/

**Comment by somebody1234** [comment]
Not entirely sure it will affect performance at all, haven't checked the number of dependencies this has - feel free to close

**Comment by matheuss** [comment]
I think we had some discussion about this on [zeit.chat] the other day – might be worth to give it a shot 😄 

[zeit.chat]: https://zeit.chat

**Comment by yaycmyk** [comment]
Rollup would be better than both.
