### ISSUE TITLE
enable opacity of terminal window

### ISSUE THREAD

**Issue by nimo23** [zeit/hyper#964]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [ ] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **Hyper.app version 0.8.3 **: 

## Issue
Please add a option to set the opacity-level (transparency, for example: opacity: .8) of the terminal.

**Comment by matheuss** [comment]
You can use `rgba` on the `backgroundColor` field of `~/.hyper.js` 🙂
