### ISSUE TITLE
restore windows/tabs/state from last session after opening hyper

### ISSUE THREAD

**Issue by nimo23** [zeit/hyper#965]
## Issue
The Mac Terminal App restores the last sessions/tabs/windows when opening the app again. Please add a option (e.g., "restore_sessions") so Hyper.app will restore all the opened sessions/tabs/windows from the last session when user opens the app again.

**Comment by matheuss** [comment]
#567 
Please use the issue template – and the search box 😄

**Comment by nimo23** [comment]
Okay, will do it in future. Thanks!

**Comment by ppot** [comment]
This will be landed in #945
