### ISSUE TITLE
Website linux download link not working

### ISSUE THREAD

**Issue by PabloDinella** [zeit/hyper#971]
Hello, sorry if it's not the right location to report this, but the linux download file is missing on the website:

![image](https://cloud.githubusercontent.com/assets/2482730/20081292/cf0bb8a4-a535-11e6-8443-db6f70a1d239.png)

![image](https://cloud.githubusercontent.com/assets/2482730/20081284/b9b7da46-a535-11e6-8579-c69e18f72a96.png)

**Comment by matheuss** [comment]
#799 😅
