### ISSUE TITLE
Support multitouch Back/Forward swiping for webviews

### ISSUE THREAD

**Issue by BLamy** [zeit/hyper#972]
When opening a website in a web view I occasionally run into wanting to navigate back. I kind of like the UI as is and wouldn't necessarily like to see buttons or a URL bar added. However, Gestures for swiping back/forward would be really nice. 

Possibly a good use case for a plugin but I figured I'd share before looking into developing it myself.

**Comment by AlJohri** [comment]
@BLamy is there a way to go back right now that I'm not aware of?

**Comment by ppot** [comment]
@AlJohri  Nop ⏳
