### ISSUE TITLE
Don't show bold text as bright

### ISSUE THREAD

**Issue by kballard** [zeit/hyper#973]
- [X] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [X] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.12.1
- **Hyper.app version**: 0.8.3
- **The issue is reproducible in vanilla Hyper.app**: Is Vanilla

## Issue

It appears that HyperTerm renders bold text using the bright colors. I don't want that. There should be an option to turn this off, so bold text still uses normal colors, and you have to explicitly request bright text to get the bright colors. Terminal.app has this setting as "Use bright colors for bold text", which I have disabled.

**Comment by MarkBorcherding** [comment]
Additionally, Terminal.app has the setting for "Use bold fonts".  I have the opposite problem of wanting the bright color, but not the bold font. Whatever gets added to fix the above mentioned problem could also hit this issue as well.

**Comment by swaj** [comment]
@MarkBorcherding I've created a small plugin to remove the bold.  Check it out and let me know if it works for you:  https://github.com/swaj/hyper-nobold

**Comment by chabou** [comment]
duplicate #475

**Comment by joecridge** [comment]
Can this issue be reopened? @swaj’s plugin addresses #475 (which is still open), but it does not do anything to resolve this issue.

**Comment by kballard** [comment]
@joecridge is correct, @swaj's plugin does nothing to address this ticket and it should be reopened. #475 is basically the exact opposite of this ticket.

**Comment by johnslemmer** [comment]
This is more of an issue with the underlying xterm.js.  Here is a potential issue this could be linked with:

https://github.com/xtermjs/xterm.js/issues/1117

I'm hoping this can make some progress as other terminal emulators have these options.

**Comment by chabou** [comment]
@johnslemmer xtermjs/xterm.js#1117 has been merged in xterm v3.1 (and in hyper canary https://github.com/zeit/hyper/pull/2667)
Here a PR to use these new settings: https://github.com/zeit/hyper/pull/2669

But this is not exactly this issue subject.

**Comment by chabou** [comment]
I think that this issue is fixed in v2.0.0 canary (backed by `xtermjs`).

Feel free to comment if not.
