### ISSUE TITLE
Allow for CSS overrides (get rid of !important)

### ISSUE THREAD

**Issue by rauchg** [zeit/hyper#99]
We'll have to see if the Aphrodite team is open to an option to avoid `!important`: https://github.com/Khan/aphrodite/issues/25

If they do, we can get rid of an ugly hack we have for style overrides:
https://github.com/zeit/hyperterm/blob/master/app/lib/utils/override-style.js

**Comment by albinekb** [comment]
I think this is fixed? Can't see any `!important` being set, but i can't find the PR that changed this either..

**Comment by chabou** [comment]
Fixed by 470b747
