### ISSUE TITLE
Copying a high-lighted selection in the terminal removes the high-lighted selection

### ISSUE THREAD

**Issue by BChip** [zeit/hyper#990]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS Loki and Elementary**: 
- **Hyper.app latest**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: 
- **Relevent information from devtools** _(CMD+SHIFT+I on Mac OS, CTRL+SHIFT+I elsewhere)_: 
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Copying a high-lighted selection in the terminal removes the high-lighted selection.

Ex: Highlight something in the terminal, copy it, and the selection is gone. 

Most modern user interfaces face this problem

**Comment by ppot** [comment]
@BChip I can't reproduce this error on the laster hyper.app

**Comment by BChip** [comment]
@ppot Are you on Elementary OS (Ubuntu based)? It could just be my OS.

**Comment by ppot** [comment]
@BChip I'm on macOS

**Comment by ppot** [comment]
@BChip Are you copying with `ctrl+c`

**Comment by BChip** [comment]
Yes @ppot and I will create a GIF later tonight to show

**Comment by ppot** [comment]
@BChip Friendly ping 🎉

**Comment by askl56** [comment]
Having this same issue on Ubuntu 16.10

**Comment by ppot** [comment]
closed in PR #1218 :)

**Comment by askl56** [comment]
@ppot i only installed Hyper yesterday so that seems unlikely

**Comment by ppot** [comment]
@askl56 #1218 is in the next release! so 1.0.1 ;) comping soon this week or next!

**Comment by askl56** [comment]
Ah cool thanks @ppot
